### ISSUE TITLE
Janus 1.x compatibility problem

### ISSUE THREAD

**Issue by muchachagrande** [nextcloud/spreed#10003]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
There is an incompatibility issue using HPB with Janus 1.x (multichannel version).
The signaling server negotiates a Janus data channel, but this channel is not named as expected by Talk.
With Janus 0.x (non-multichannel version) the only possible data channel is named "JanusDataChannel" but with the new 1.x (multichannel version) the channels have not a fixed label anymore.
Talk will keep using only one data channel between any two peers, but these channel is labeled "1" on Janus 1.x.
Because there can be more than one channel between peers, Janus use the channel number as label and these channel will always be labeled "1" on Talk app.

**Describe the solution you'd like**
As far as I could find out on the Talk code, there seems to be only two places where the data channel label is checked.
On line 232 of CallParticipantModel.js and on line 1591 of webrtc.js:

https://github.com/nextcloud/spreed/blob/6714e9b73d888c16a23049703ca812918825da6b/src/utils/webrtc/models/CallParticipantModel.js#L232C3-L232C3

https://github.com/nextcloud/spreed/blob/6714e9b73d888c16a23049703ca812918825da6b/src/utils/webrtc/webrtc.js#L1591C3-L1591C3

If you add "1" as a possible label of the data channel Talk will recognize the channel as valid and will understand the messages coming from it.

**Describe alternatives you've considered**
As Meetecho considers Janus 0.x as "legacy", sooner o later they will stop maintaining that branch so I think that this fix will be needed then.

**Additional context**
https://github.com/meetecho/janus-gateway/issues/2566

**Comment by nickvergessen** [comment]
I'm pretty sure we had a ticket already, but doesn't seem like it.

**Comment by muchachagrande** [comment]
You may be referring to this ticket https://github.com/nextcloud/spreed/issues/9257
I opened it but after finding out it was an incompatibility with new Janus 1.x versions I closed it because it was not a Talk problem.
Also there is a ticket on the Signaling project https://github.com/nextcloud/spreed/issues/9257
It was opened to discuss Janus 1.x compatibility and I reported this findings there too.

**Comment by ksainc** [comment]
Good Morning,

There is also this issue ticket https://github.com/nextcloud/talk-android/issues/2704

Sebstian

**Comment by mircokam** [comment]
Hello,
we testet the Android App Talk Version 18.0.1 on Pixel 7 with Janus 1.x Multistream  an it works now with video. 

https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/109
