### ISSUE TITLE
Remember sidebar state per conversation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1002]
## Steps to reproduce
1. Have some conversations, maybe some 1on1, some group ones
2. In one of them, like a 1on1 where you only chat and never need to manage participants, close the right sidebar
3. Go to another group, and then later switch back to the 1on1 conversation from before

### Expected behaviour
The sidebar of that 1on1 conversation should still be closed, as you closed it before and never need it.

### Actual behaviour
The sidebar gets opened again every time, leaving you with the annoyance of having to close it again.

@nextcloud/talk

**Comment by nickvergessen** [comment]
Just for the record, I think it's unnecessary to mention the talk group on this repo. People are subscribed or don't need to be mentioned.
