### ISSUE TITLE
Feature Request: Webinar support

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/spreed#1003]
**Feature Request**

Next to the "standard" calling functionality there should be a "webinar" support, meaning, you can create a private/public conversation with an option to block video/microphone/screensharing for all (guest) users, so they can only follow the owners/moderators video feed and can communicate via chat.

Blocking other peoples video/microphone is necessary so no one can "steal" your show by talking and putting themselves infront of every participant.

Maybe some extra buttons to disable the different sharing options for not-moderators would be a good idea.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/931 and https://github.com/nextcloud/spreed/issues/282
