### ISSUE TITLE
Push notification (iOS/Android) not happening

### ISSUE THREAD

**Issue by eszeus** [nextcloud/spreed#1005]
## Steps to reproduce
1. Write a message
2. wait at the other end
3. no push notification

### Expected behaviour
Each message should be a notification

### Actual behaviour
Only the "Wants to talk with you" is appearing, but no other push notifications after

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** ubuntu 16 server

**Browser name:** Firefox/Chrome/safari

**Browser version:** newest
```


## Spreed app

**Spreed app version:** snap version of nextcloud, talk app via app store

**Custom TURN server configured:** no 

**Custom STUN server configured:** no 





**Operating system**: ubuntu 16 server

**Web server:** snap

**Database:** snap

**PHP version:** snap

**Nextcloud Version:** snap, stable

**List of activated apps:** 



**Nextcloud configuration:**

<details>
```
could not open input file: occ

```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>



To be honest, I dont have a clue right now why it isnt working :D Or is it even implemented yet?^^
And I cant find any other topic about it or a guide how to config the notificiation :D

So, thank you for every help beforehand.

**Comment by Ivansss** [comment]
Duplicate #875
