### ISSUE TITLE
formatation of email addresses are broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1007]
This is the result if I copy a email address to a chat:

![talk - email](https://user-images.githubusercontent.com/1589737/41961279-53c55414-79f2-11e8-8bed-57792afa14e0.png)

**Comment by mario** [comment]
Is this with master 14 or 13?

**Comment by schiessle** [comment]
testes on cloud.nextcloud.com, so 13

**Comment by nickvergessen** [comment]
Also happens with comments, fix is in the server repo:
https://github.com/nextcloud/server/pull/10020
