### ISSUE TITLE
current browser support for Talk

### ISSUE THREAD

**Issue by schleyk** [nextcloud/spreed#1008]
Hi Nextclouders

Is there a current list of what browsers are supported?
We test it successful with "Chrome / Chromium /Firefox / Talk-App Android & iOS" but it faild with Opera, Safari on Mac, IE and Edge :(

Thanks

**Comment by nickvergessen** [comment]
That's exactly the list.
Edge and Safari support are planned for the next steps:
https://github.com/nextcloud/spreed/issues/687
