### ISSUE TITLE
Silent call setting could be remembered per-room

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10085]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
We have both our team calls and design review calls in the "Design team public" channel. For neither we really want to ring all of the 90+ participants in the channel. We like the silent call feature a lot for that but sometimes we forget to use it.

**Describe the solution you'd like**
Since we always use the silent call feature for every call in that room (except if we forget), it seems it would be apt to remember this setting per-room, much like the video and audio settings are as well.

**Describe alternatives you've considered**
Alternative would be to globally remember, but this does not make a lot of sense as different rooms have different contexts.

**Comment by Antreesy** [comment]
We may reuse a current logic for showing MediaSettings via Pinia store (as well as for some other 'per-conversation' params kept in BrowserStorage):

https://github.com/nextcloud/spreed/blob/02e8329f10f8850a4ae8df87627f7fb66d208cb2/src/stores/settings.js#L57

**Comment by Antreesy** [comment]
related TODO: 

virtualBackground should be updated on room switch => model might remember `Blur`, although current setting is `None`
