### ISSUE TITLE
Can't enable notifications for guests.

### ISSUE THREAD

**Issue by dvastag** [nextcloud/spreed#10083]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a conversation that allows guests to join to via link.
2. Copy the link, open it in a private browsing session. Now you should be in the conversation as a guest.
3. As a guest open the conversation settings then go to 'Personal' -> 'Notifications' and select 'All messages'

### Expected behaviour
Either:
Setting is applied. Notifications are received for incoming messages.
Or:
'Personal' -> 'Notifications' is not available at all for guests and is hidden on the 'Conversation settings' interface.

### Actual behaviour
- After a few seconds the notifications setting switches back to 'Off' state. No notification uppon message receive.
- In the browser's debugger you can see that the response for switching to 'All messages' returns HTTP error code 401 with the following JSON response:
```
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 997,
      "message": "Current user is not logged in"
    },
    "data": []
  }
}
```

## Talk app

**Talk app version:** 16.0.5

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 22.04

**Browser name:** Firefox

**Browser version:** 115

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:** 8.1

**Nextcloud Version:** 26.0.4

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Definitely a bug. The notification settings should not be shown.
