### ISSUE TITLE
Confusing UI for mobile users accessing call by url

### ISSUE THREAD

**Issue by nu111** [nextcloud/spreed#10091]
On **Talk 15.0.7** when a mobile external user receives a link to join a call, this is the page shown in the browser:

![Screenshot_20230802_151133](https://github.com/nextcloud/spreed/assets/1246989/5327184d-0611-4304-a137-6df6ca1e9da5)

Users must tap on the X in upper right corner to be able to proceed and join the call.
Many users are confused by this, and I think that for everyone tapping X means _"leave, exit, close"_ rather than _"join the call"_.

I think that a redesign is needed, a big green call-to-action button **"Join the call"** is needed IMHO.

Talk `17.0.3` has the same behaviour:
![image](https://github.com/nextcloud/spreed/assets/1246989/6beb1d45-7129-4891-a076-5098a155f055)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
Doesn't look like that anymore in Talk 18

**Comment by nu111** [comment]
Great news! 🎉
Is it possible to share a couple of screenshots about it?

**Comment by nickvergessen** [comment]
Step 1 | Step 2
---|---
you have to enter a guest name: https://github.com/nextcloud/spreed/issues/855 | you see the chat
![Screenshot_2023-11-21-09-35-48-702_org mozilla firefox](https://github.com/nextcloud/spreed/assets/213943/1e298a4c-6a37-4a28-9b5f-f8ffa8266602) | ![Screenshot_2023-11-21-09-33-19-725_org mozilla firefox](https://github.com/nextcloud/spreed/assets/213943/98afd467-0d63-4caf-afe8-0655b37ced1a)
