### ISSUE TITLE
Improved design of avatars in calls

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1011]
A mockup without the controls, because we can use this in lots of cases – be it for voice calls on desktop or mobile, and also for incoming calls. cc @nextcloud/talk @mario @Ivansss 

- Left: current – the view is quite dark and bland
- Middle: Possible enhancement, larger picture, and picture in blurry in the background
- Right: Maybe even like that, full size picture, with some dark fade on the top so the white text can be read

![call](https://user-images.githubusercontent.com/925062/41923083-db5290e0-7966-11e8-810a-f3cb187f3e23.jpg)

**Comment by nickvergessen** [comment]
Don't forget that people might also upload small icon like images as avatars, so we need a strategy for when the image is only 100/200 pixels wide

**Comment by MorrisJobke** [comment]
I would prefer the one in the middle, because of the same reasons as @nickvergessen said - avatars could be too small.

**Comment by jancborchardt** [comment]
Good point, yes. Then let's go with the middle one.

What do you think regarding mobile @mario @ivansss?

**Comment by mario** [comment]
I'm not sure this will work.

The first screen you posted is not from Android since it also has the buttons (like you mentioned) + "Incoming call from".

Given that, I'm not sure buttons + text would be visible enough on the second mockup.

Introducing @AndyScherzinger to the mix.

**Comment by jancborchardt** [comment]
As said above:

> A mockup without the controls

And 

> with some dark fade on the top so the white text can be read

(Just like in video apps like Netflix, Twitch, Newpipe etc)

**Comment by jancborchardt** [comment]
As said above:

> A mockup without the controls

And 

> with some dark fade on the top so the white text can be read

(Just like in video apps like Netflix, Twitch, Newpipe etc)

I can do a specific mockup again, but will only be back on Monday.

**Comment by nickvergessen** [comment]
btw is this something you want to change on the desktop as well? or only in the mobile apps? @jancborchardt

**Comment by jancborchardt** [comment]
Yes, as said above:

> because we can use this in lots of cases – be it for voice calls on desktop or mobile, and also for incoming calls 

:) So what we need is to have another element for the current speaker avatar which repeats that avatar, so that we can resize and blur it via CSS. (Or do we do it via ::before @nextcloud/designers?)

**Comment by nickvergessen** [comment]
Superseded by #1056 

Or is this only for mobile @jancborchardt

**Comment by jancborchardt** [comment]
This is specific for 1-on-1 calls, and it’s for both mobile and server. As in a 1-on-1 voice call on the server there’s a lot of black space around the other person’s avatar which we can improve the looks of through the design above. :)

And regarding mobile:
- Is this done on iOS at all @Ivansss?
- On Android, the avatar duplicate shown in the background is stretched. Should always keep the aspect ration and just fill the background. @mario as discussed. :)

**Comment by Ivansss** [comment]
Not implemented on iOS yet. But it's in the todo list :)

**Comment by Ivansss** [comment]
@jancborchardt I think for default avatars it looks a bit weird.
@mario How do you handle this on Android?

![default](https://user-images.githubusercontent.com/4638605/49875076-657e8880-fe20-11e8-88f4-eaee2470f089.png)

**Comment by mario** [comment]
So if it's the default avatar (I check if the value returned is 201), I generate the background color using the following code:

                                        int color = palette.getDominantColor(getResources().getColor(R.color.grey950));

                                        if (color != getResources().getColor(R.color.grey950)) {
                                            float[] hsv = new float[3];
                                            Color.colorToHSV(color, hsv);
                                            hsv[2] *= 0.75f;
                                            color = Color.HSVToColor(hsv);
                                        }

**Comment by mario** [comment]
Basically, I get the dominant color off of the avatar (basically, the circle colour, and then adjust intensity)

**Comment by mario** [comment]
Here you go @Ivansss.
![screenshot 2018-12-12 at 16 53 06](https://user-images.githubusercontent.com/5810/49881365-77ffbe80-fe2e-11e8-8684-3b387d4d7cff.png)

**Comment by mario** [comment]
Btw. keep in mind I check if we have no-ping since 201 was introduced at the same time. Before that, the avatar endpoint would always return 200.

**Comment by nickvergessen** [comment]
Closing as the mobile apps are fixed or should deal with it in their repo, and server UI is going to be adjusted with #1056
