### ISSUE TITLE
Inline avatar and message input

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#1014]
I guess a user already knows who he is (or do we? :thinking: :laughing: )
So we should probably just keep the avatar? @nextcloud/designers 

![kazam_screenshot_00003](https://user-images.githubusercontent.com/14975046/42173306-e3f62344-7e1e-11e8-8193-ae04c406d3d9.png)
![kazam_screenshot_00004](https://user-images.githubusercontent.com/14975046/42173307-e410bfd8-7e1e-11e8-8456-541202016a88.png)

**Comment by nickvergessen** [comment]
Guests change their names in this place. having two different layouts for guests and logged in users sounds like pain

**Comment by jancborchardt** [comment]
It’s a good point, and I would say that it’s not so bad to have a slightly different layout for guests. After all it would just be one element difference, and the layout of the avatar (like it is currently for guests, but like @skjnldsv mocked up for users, vertically aligned with the input).

Sure it’s work to have both views, but those are two cases we should optimize.

**Comment by nickvergessen** [comment]
@skjnldsv want to make a PR?

**Comment by jancborchardt** [comment]
Just to add a detail: On hover/tap of the avatar we should show your own name, so you see how you appear to others.

**Comment by ma12-co** [comment]
Rough draft from @jenniferpiperek 

![Screenshot_20190916_115346](https://user-images.githubusercontent.com/26852655/64949085-b5d7ba80-d878-11e9-9d33-2fef701f2a8e.png)

**Comment by ma12-co** [comment]
..and messages
![Screenshot_20190916_115610](https://user-images.githubusercontent.com/26852655/64949232-051deb00-d879-11e9-85a5-103e5adbc959.png)

**Comment by nickvergessen** [comment]
Closing this as per above
