### ISSUE TITLE
Typo in the date separator of a text chat

### ISSUE THREAD

**Issue by GLLM** [nextcloud/spreed#1016]
Hi,

I'm running NC 13.0.4 with the last stable version of Talk / Spreed.
My system is in french, as well as NC language.

I can see a typo on text discussions when the date is today, spelled **_Aujourd'hui_** in french :

![image](https://user-images.githubusercontent.com/3989573/42229911-e80300a0-7ee7-11e8-8ca7-2a1f2b620263.png)

I guess this should be corrected :)

**Comment by nickvergessen** [comment]
Hmm, we don't allow HTML in there, but seems like the French translation is using an ordinary `'` instead of a UTF8 version of it.
