### ISSUE TITLE
follow-up(Message) - appearance of `Quote` component / Markdown `<blockquote>`

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10179]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Current appearance for Quote components / Markdown quotes:
![Screenshot from 2023-08-11 11-03-49](https://github.com/nextcloud/spreed/assets/93392545/8a057203-024a-4e59-9352-2bf8f5140c3f)

**Comment by Antreesy** [comment]
Tracker for competitor's screenshots:

_put some screenshots here_

**Comment by Antreesy** [comment]
Proposal: align styles with `<Quote>` component, but leave a grey background:

![image](https://github.com/nextcloud/spreed/assets/93392545/8b719e5d-8054-43fb-8385-2975e557d82b)

**Comment by marcoambrosini** [comment]
Hi, I think it's important for users to clearly discern between **Talk replies** and **rendered markdown quotes**. In differentiating the two, I think we should keep the simple vertical line style for **rendered markdown quotes** and "upgrade" the design of **Talk replies**. This is so we're consistent with other markdown solutions, including our own.

I have experimented with backgrounds a little bit but I think I found a better solution that would allow us to maintain high text contrast: using a shadow effect for **Talk replies**. To further differentiate them, we could also add a 16px avatar of the user that sent the original message (this is the same size as mention chips).

So in the mockup below I'm Bob and I see:
* My reply to Alice (Container shadow + gray bar)
* Alice's reply quoting **my message** (Container shadow + primary bar)
* Rendered markdown quote in Alice's message (simple gray bar with no shadow)

This should be very easy to implement, looks reasonably good and minimises chances of confusion between **Talk replies** and **rendered markdown quotes**

feedback welcome @nextcloud/designers @Antreesy @nickvergessen @AndyScherzinger as you were involved in the chat conversation 
<img width="1577" alt="Section 4" src="https://github.com/nextcloud/spreed/assets/26852655/3bd98b72-69ef-4fff-b14e-63f6d416a0be">

<img width="947" alt="Screenshot 2023-08-14 at 16 39 54" src="https://github.com/nextcloud/spreed/assets/26852655/5ca8892b-9ddc-4415-b6aa-96ac7da402ba">

**Comment by Antreesy** [comment]
Low-impact changes draft:

![image](https://github.com/nextcloud/spreed/assets/93392545/36957f0c-fa36-401b-ae74-0b70d07943f1)

**Comment by AndyScherzinger** [comment]
I like the draft @marcoambrosini 👍
