### ISSUE TITLE
Escaping: e.g. newline and apostrophes preceded by backslash

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1017]
In a conversation I wrote `"Something"` and it is now displayed as `\"Something\"`, with the apostrophe being preceded by backslash.

Similarly, something the other person sent through their mobile app and pressed enter in the message is shown with a `\n` instead of an actual new line.

Happening on current cloud.nc @nextcloud/talk

**Comment by nickvergessen** [comment]
If the messages have been sent from mobile, please open an issue in the respective app
