### ISSUE TITLE
[Bug] 'Scroll to bottom' doesn't dissapear when chat is scrolled

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10187]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a chat
2. Scroll up
3. Scroll down

### Expected behaviour
Button should dissapear

### Actual behaviour

https://github.com/nextcloud/spreed/assets/93392545/8953788f-0cc8-47af-91aa-784402fc9188

**Comment by nickvergessen** [comment]
Not happening anymore
