### ISSUE TITLE
Tooltips of conversation list not necessary anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1019]
We added the tooltips to the conversation list on the left before we had the participant list and proper sidebar. Now that we have it it’s not necessary anymore.

Also, it’s just really annoying and feels unpolished that when you hover over the list, these partly huge tooltips pop up.

I’d say we remove the tooltips. What do you think @nextcloud/talk?

**Comment by nickvergessen** [comment]
@jancborchardt please stop mentioning the group all the time. People necessary to do this will already look into this repository.
