### ISSUE TITLE
talk time does not show when joining and talking via android mobile

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#10209]
Not sure if this should rather be reported to the talk-android repo.

When joining a conversation via android-mobile on c.nc.c, it does not show the overall time of the account that is talking as we just experienced during our design call. I have Talk v17.10.0 Alpha 14 installed if it matters and joined via the phone and not video call button to only enable the microphone but not the camera.

cc @nextcloud/designers

**Comment by nickvergessen** [comment]
No need for design input.

It's a known bug in the Android app: It does not use data channels (correctly)
- https://github.com/nextcloud/talk-android/issues/88

**Comment by szaimen** [comment]
All right, thanks!
