### ISSUE TITLE
"unread messages filter" does not apply to "call started"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#10207]
- have "unread message filter" enabled
- receive an incoming call 
- do not see it in filter

**Comment by nickvergessen** [comment]
Those are not chat messages and therefore don't (and never did so) update the unread counter.

We can of course also add active calls to the filter (like in the dashboard) or we add a specific filter for calls.

cc @DorraJaouad @jancborchardt

**Comment by DorraJaouad** [comment]
This can be done by adding to the unread filter the `hasCall` flag. 
@jancborchardt would it be okay for the UX to also add the active calls to the unread conversations list?

**Comment by jancborchardt** [comment]
Yep @DorraJaouad, agree with @tobiasKaminsky that active calls are important enough that they should show even in the filtered lists.

**Comment by tobiasKaminsky** [comment]
![image](https://github.com/nextcloud/spreed/assets/5836855/d2a55bc3-abba-4198-a5b8-aa3350373232)


Not sure if this is related to your PR @DorraJaouad, or if this is already deployed on our instance.
It seems that "call ended" stat was not properly taken into account.

**Comment by nickvergessen** [comment]
yeah sounds like that would be the issue

**Comment by tobiasKaminsky** [comment]
Status was not correct, as there was at this time no call.
But it may come from notifications? As I had an unread notification about that call.

**Comment by ShGKme** [comment]
> Status was not correct, as there was at this time no call. But it may come from notifications? As I had an unread notification about that call.

Yes, I think that was from the notification. It updates the status of the call according to the notification.
