### ISSUE TITLE
Open conversations: Text not vertically aligned

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10210]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to Talk
2. Open the 3-dot action menu
3. Pick "Join open conversations"

### Expected behaviour
The list looks nice and consistent with the rest.

### Actual behaviour
- The text is not vertically aligned with the avatar / image
- The images are not shown, but instead a "?" in place of all of them
![image](https://github.com/nextcloud/spreed/assets/925062/05d049ea-bbe4-4617-b2af-1168cbe94726)

## Talk app

**Talk app version:** Current on cloud.nc and tech-preview as well.

**Comment by nickvergessen** [comment]
- Avatar thing is known: https://github.com/nextcloud/spreed/issues/9600 but hard to fix without reducing security quite a bit.

**Comment by Antreesy** [comment]
> * The text is not vertically aligned with the avatar / image

It should be aligned geometrically, but due to upstream component issue (see PR above), it has 0-height invisible element, which forces text to be slightly higher and jump on toggle

**Comment by jancborchardt** [comment]
> If we can't securely fix this (now), we could at least prevent the requests to the server and show a placeholder?!

Yes definitely. We can use this "groups" icon: https://fonts.google.com/icons?selected=Material%20Icons%3Agroups%3A

> It should be aligned geometrically, but due to upstream component issue (see PR above), it has 0-height invisible element, which forces text to be slightly higher and jump on toggle

@Antreesy is this being worked on?

**Comment by jancborchardt** [comment]
Ah the avatar was already fixed as per https://github.com/nextcloud/spreed/pull/10222, great stuff! :)

**Comment by Antreesy** [comment]
> is this being worked on?

Please check tommorow at company instance, or locally. Should be aligned with vue-library bump

**Comment by nickvergessen** [comment]
![grafik](https://github.com/nextcloud/spreed/assets/213943/b77b1bc2-3d21-4046-9c77-46dca416e1ec)

This is from the package I just build, so I guess the alignment is not fully working (chrome)

**Comment by Antreesy** [comment]
> I guess the alignment is not fully working (chrome)

Oh wow, I have thought about LeftSidebar, not the OpenConversations Modal :see_no_evil: 

cc @DorraJaouad please check, if you have time
