### ISSUE TITLE
call summary - allow to document the call time stats

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#10211]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Now that the call summary and call time stats are available it would be amazing if the stats could be put into the summary.
This could possibly be done by sending the stats at the end of the call from the client to the server and then processed.

**Comment by szaimen** [comment]
Sorry, I don't get the idea here? I mean I would have expected at least an answer? :)

**Comment by nickvergessen** [comment]
Not planned for now because it's technically not possible.

They would need to be a chat message (this is how the bot is receiving it's input).

**Comment by szaimen** [comment]
All right, thanks!
