### ISSUE TITLE
Pasted URL in Talk gets changed once posted

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/spreed#10227]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a Talk room
2. Paste the following link:
  ```
  https://instance.com/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=Invitation
  ```
4. Hit enter

### Expected behaviour
The exact same link should be displayed and a preview generated

### Actual behaviour
https://.com/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin§ion=Invitation

The "&sec" is replaced by a weird "§" character

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) c.nc.c

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

Firefox Windows latest stable

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
the HTTP request already contains that, so something wrong on the inserting part.

Doesn't even need to be a URL, `n&secti` is enough.

**Comment by Antreesy** [comment]
https://toolstud.io/web/charmap.php?encoded=sect&sort=name

`§` is also a special character :eyes: 

We already escaping`<` `>` and `&`, so should add it as well, but upstream to the NcRichContentEitable

**Comment by SystemKeeper** [comment]
`&sect` is enough, since this is the html entity for `§`: http://unicode.e-workers.de/entities.php
Also happens on 17.

**Comment by SystemKeeper** [comment]
Test (from https://stackoverflow.com/a/34064434)

```
function htmlDecode(input) {
  var doc = new DOMParser().parseFromString(input, "text/html");
  return doc.documentElement.textContent;
}

htmlDecode("&sect")
```

**Comment by lhsazevedo** [comment]
Just experienced that with an Penpot URL:
```
https://design.penpot.app/#/view/dea2d881-2623-80e5-8003-0ba727cf7be4?page-id=dea2d881-2623-80e5-8003-0ba727cf7be5&section=interactions&index=0&share-id=dea2d881-2623-80e5-8003-0bf7644526f5
                                                                                                                  ^^^^^
```

![image](https://github.com/nextcloud/spreed/assets/7695608/29525f0b-1a5a-41aa-a9b8-972edae54473)

Also happens with `&gt`, `&lt`, `&acute` etc.

**Comment by nickvergessen** [comment]
I guess https://github.com/nextcloud/spreed/issues/10412 is also related.

@DorraJaouad @Antreesy this is quite a problematic thing. Can you have a look if it's easily resolvable before the final?

I assume it's a bug in the vue library, so fixing it there (with unit tests) would be the best.

**Comment by nickvergessen** [comment]
yeah it's not NcRichText, that we ruled already out. The question is whether it's NcContentEditable or the wrapping bit/processing of Talk

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/4ea474d7e7f4914b6c3e092d35cfd0edea880701/src/components/NewMessage/NewMessage.vue#L477-L480

**Comment by Antreesy** [comment]
> Since the above mentioned issue is solved, maybe removign those lines fixes it?

It does, but there is still an open case for multiline + markdown: https://github.com/nextcloud-libraries/nextcloud-vue/issues/3908

**Comment by nickvergessen** [comment]
Well one thing after another then.
So lets have a PR which strips out those lines (best would be with tests) and makes sure posting works.

Afterwards we can have a second PR/test/fix for still open things.
