### ISSUE TITLE
Moderator login without being nextcloud user

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1022]
When joining a room there should be a way for a user to get moderator status without being a nextcloud user.  If I invite someone to a public meeting who is not a nextcloud user they should be able to join with a password that signals them as a moderator.  
In a separate app I am adding them to the participants table with moderator status and their email address as the user id, when they join the room they get added as a guest because there is no identifying information passed to allow looking up their email in the participants table.  When joining a room would it be possible to have a prompt if the user is a guest asking them for a user id before joining the meeting and this user id would be the email address?  In RoomController.php function joinRoom could accept an extra parameter userId which would be used if $this->userId is null.

**Comment by nickvergessen** [comment]
Definetly something we also want to have in the future. I'm not sure yet how we best do this.

Maybe with a second password and participant type and if the password is the second one, we change from GUEST to GUEST_MODERATOR or something like that?

Btw interesting stuff you are working on, feel free to join us on [IRC #nextcloud-talk](https://webchat.freenode.net/?channels=nextcloud-talk) to discuss things quicker :)

**Comment by Peterede** [comment]
Thanks, I will try IRC.
From my investigation so far I think using the sessionId would be a good way to identify the user once they have been validated using email address or any other validation.  Using the sessionId the rooms list and other information can be retrieved from the server instead of using the nextcloud user id.  So there would be no need to have GUEST_MODERATOR they would just be MODERATOR.

**Comment by nickvergessen** [comment]
> From my investigation so far I think using the sessionId would be a good way to identify the user once they have been validated using email address or any other validation.

The problem is, the sessionId changes everytime you reload the page, (so all participants correctly reconnect to you via webrtc). Also you don't have a sessionId before joining.

That's why I suggested a second password for moderators.
But I will think a bit more about it.

**Comment by Peterede** [comment]
I have implemented an idea of how this would work on my branch [https://github.com/Peterede/spreed/tree/guest-moderators](https://github.com/Peterede/spreed/tree/guest-moderators).  There are not too many changes, the preJoinRoomGuest hook returns the Participant type using the password for validation.  Then when removing a user from the room the sessionId is used to lookup the participant invoking the moderator command.
