### ISSUE TITLE
Nextcloud hangs when switching many times / fast from room to room - Too many SQL connections

### ISSUE THREAD

**Issue by FGIKCM** [nextcloud/spreed#1023]
## Steps to reproduce
1. Go to the rooms page
2. be sure to have at least 2 or 3 rooms available on the left side
3. click on one room, then on another, and again and again 

### Expected behaviour
We should see the last room we clicked^^

### Actual behaviour
 - After some clicks (10 ou 15 on my config), Nextclouds hangs for at least 15/20 seconds before responding again
 - We see a "too many SQL connections" on the log.

More info:
 - I'm the only user connected to the server,
 - there is only Nextcloud on it,
 - My MariaDB server accepts 8 connections at the same time.

As my fingers are slowers than 8 clicks/seconds, I suspect there is some part of the script that does not close the SQL connection as fast as it should...

## Browser
Tested on latest versions FF, Chrome, IE11 (Windows)

### Browser log
No error log on console, when hanging there is no event on the 'network' part. The lines appears *after* the hang finished

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
3.2.2
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian 9.4
**Web server:** Apache/Nginx
Apache 2.4.25
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB 10.1.26
**PHP version:**
PHP 7.2.27
**Nextcloud Version:** (see admin page)
13.0.4.0
**List of activated apps:**

<details>
```
Enabled:
  - activity: 2.6.1
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_antivirus: 1.2.0
  - files_markdown: 2.0.4
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - lookup_server_connector: 1.1.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - spreed: 3.2.2
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_saml: 1.5.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_versions
  - firstrunwizard
  - logreader
  - nextcloud_announcements
  - serverinfo
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
sorry, no (I can give parts if really needed)

### Server log (data/nextcloud.log)
```
Jul  6 11:08:46 drive Nextcloud[13989]: {PHP} Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1040] Too many connections at /xxxxxxxx/lib/private/DB/Connection.php#64
```

**Comment by nickvergessen** [comment]
I don't think there is a lot we can do, or do you have any suggestion?

**Comment by FGIKCM** [comment]
With this plugin, I had to double the RAM of my server (from 2GB to 4GB), and double the SQL accepted simultaneous connections. For the others parts of Nextcloud, I didn't see theses hangs.

So I just wanted to alert you that perhaps:
 - you open multiple SQL connections for a single process, instead of using a single connection,
 - you don't close it as fast as it could be?
 - Or are there persistent connections, staying opened after the end of the PHP scripts??

I don't know for the real reason, but 8 SQL connections should be sufficient for a single user on the web interface :-/
