### ISSUE TITLE
After group call ended number of unread messages don't disappear

### ISSUE THREAD

**Issue by binford6000** [nextcloud/spreed#10266]
## Steps to reproduce
1. Group call is ending an NO MESSAGE was written afterwards
2. Number of unread messages appaer under the chat name and won't be marked as read
3. With the next chat message written in the chat the unread messages disappear.

### Expected behaviour
After the call ended and all messages are read the number of unread messages disappears.

### Actual behaviour
Number of unread messages is shown:
<img width="288" alt="image" src="https://github.com/nextcloud/spreed/assets/29679540/8e5026dc-1141-4f3d-b558-487bb662172d">

After writing something into the chat the unread messages count disappears:
<img width="807" alt="image" src="https://github.com/nextcloud/spreed/assets/29679540/937c0ca9-0679-4631-86eb-7870a739f4b8">

**Comment by DorraJaouad** [comment]
As the unread marker is part of a message, it was collapsed in the system messages group and thus not visible.
The unread counter won't be cleared unless the marker becomes visible ( or post a message) 
![image](https://github.com/nextcloud/spreed/assets/84044328/b4e75d1b-4fba-4466-aff6-e5c9c6ad2b97)
