### ISSUE TITLE
Ability to copy message text (raw) to Clipboard

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10288]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
With added Markdown support, it's not possible now to copy a raw text of a message (e.g. if i need to copy-paste markdown somewhere)

**Describe the solution you'd like**
Specific NcActionButton in MessageButtonsBar
![image](https://github.com/nextcloud/spreed/assets/93392545/a13c3658-a789-4bb1-885d-3e4b8a547970)

**Describe alternatives you've considered**
Icon and wording is up to discussion

**Additional context**
-

**Comment by nickvergessen** [comment]
Yeah, especially when trying to debug messages it will be very helpful, but also when trying to "export" into a document or other data source it will be helpful.
