### ISSUE TITLE
follow-up: Reduce amount of component to wrap avatars

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10282]
We have several options to wrap user's/conversation's/other avatars:
  - ConversationIcon
  - AuthorAvatar
  - AvatarWrapper
  - NcAvatar itself

We need to review first three of the list thoroughly, to check which ones could be replaced or simplified, and wrap the rest of NcAvatar as well, if needed

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/pull/10262#discussion_r1299367439_

**Comment by nickvergessen** [comment]
Assigning to backlog as this is nothing we will backport

**Comment by nickvergessen** [comment]
Also note that they all serve different porpouses and have different special cases added. Happy to explain them in a call if you ever look into this.

**Comment by Antreesy** [comment]
Quick observations:

Component* / Wrapper | NcAvatar* | ConversationIcon | AuthorAvatar | AvatarWrapper
--|--|--|--|--
Used in | LocalVideo, VideoVue, MediaSettings | Dashboard, ConversationAvatarEditor, GuestWelcomeWindow, Conversation, LeftSidebar, RoomSelector, TopBar | MessageGroup | Participant, SelectableParticipant, ContactSelectionBubble, PollVotersDetails, NewMessageTypingIndicator, Quote
Size | 64 / 128 | 44 / fit to parent (only 180 now) | 32 | 22 / 44
Menu enabled? | No | No (except TopBar) | Yes (except Desktop and guest view) | No (except Participant) 
Status enabled? | No | Yes (except editor and guest welcome) | No | No (except Participant and SelectableParticipant for users)
