### ISSUE TITLE
delete chat messages - still visible to 3rd party despite `cleared the history..` indicator

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10298]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a rich, 2+ sided text conversation w many messages.
2. User1 (w privileges) chooses to **Delete chat messages - Permanently Delete all messages in this conversation!"
![image](https://github.com/nextcloud/spreed/assets/7018928/2626dbee-2e64-469d-835a-6bbc585568dd)

3. User2 sees "User1 cleared the history of the conversation", yet no messages are cleared or deleted - all messages remain visible.

### Expected behaviour
Expect all messages for User2 to vanish immediately following User1 choosing to delete all chat messages.

### Actual behaviour
User2 sees "User1 cleared the history of the conversation", yet no messages are cleared or deleted - all messages remain visible.
**EVEN IF** the conversation is reloaded (i.e. within Talk, move to a different conversation, then return). 
Only once User2 moves away from Talk (either selecting a different Nextcloud app, or reloads the page) do the messages vanish.

![image](https://github.com/nextcloud/spreed/assets/7018928/18c09cfe-7f0f-497e-a9ea-b9735942289e)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.0-rc.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
Linux openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
116.0.2

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

Nextcloud's internal tech preview instance 😎 
Nextcloud Hub 6 (27.1.0 beta 2)

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by gerbrent** [comment]
![talk - clear messages, they remain](https://github.com/nextcloud/spreed/assets/7018928/304d58d6-6eeb-45a9-aecf-dcfd1b31fd52)

**Comment by nickvergessen** [comment]
@Antreesy I guess some event handling was removed by accident?

**Comment by Antreesy** [comment]
> @Antreesy I guess some event handling was removed by accident?

Nope, we never handle it :eyes: But should be around three lines of code
