### ISSUE TITLE
Settings in local storage overwrite media settings when starting a call

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10324]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have the following in your local storage
  
![Bildschirmfoto 2023-08-23 um 19 42 00](https://github.com/nextcloud/spreed/assets/1580193/42e21e6c-10e6-4f11-a42b-51b39e84ff89)

2. Start a call and see
  
![Bildschirmfoto 2023-08-23 um 19 42 06](https://github.com/nextcloud/spreed/assets/1580193/391ec80b-d5e5-4987-bc3a-7cfd0a3083ee)

3. When entering the call you now have virtual backgrounds enabled and theater is set.

### Expected behaviour
The settings I select when starting a call should be reflected inside the call

### Actual behaviour
The settings for virtual backgrounds are irrelevant if something is stored in local storage.

Also after entering a call I noticed that keys without a token appeared:
![Bildschirmfoto 2023-08-23 um 19 42 47](https://github.com/nextcloud/spreed/assets/1580193/f8714d56-3e30-43b3-8294-bbc44bca7c4a)

## Talk app

**Talk app version:** c.nc.c

## Browser
**Operating system:** MacOS

**Browser name:** Chrome

**Browser version:** 116

**Comment by nickvergessen** [comment]
Having the same issue but most of the time the other way around. The preview shows my background blurred, but when I enter the call it's not blurred anymore.

cc @DorraJaouad you worked on the media settings recently. Did you fix something related?

**Comment by DorraJaouad** [comment]
Yes, the media settings changes are added to the local storage only after joining the call ( the commit https://github.com/nextcloud/spreed/pull/10188/commits/febde91632be4ff0a0309e73eb018a57bac9b0d9). the local storage should be overwritten after listening to `talk:media-settings:hide` from `CallButton` .

I tried to reproduce the issue:  the changes were applied and the BG becomes blurry as expected. I also tried Joas's scenario and it works as expected as well. Perhaps I am missing other settings enabled or changed?

**Comment by SystemKeeper** [comment]
Did you try to add the settings to local storage and then try it? (With the correct token of course)
Also could the mentioned commit change the behaviour ? Because we are testing on c.nc.c, so 17.1 rc1 which does not include your commit?

**Comment by DorraJaouad** [comment]
No, it is not on c.nc.c yet. I was testing on master.

And for c.nc.c, yes, I see the same issue of having the media settings overwritten by the local storage. It happens only when I try to disable blur BG or virtual BG.  I noticed that `_virtualBackgroundEnabled_` is set to false when clicking on None but when joining the call, it gets back to true.

**Comment by Antreesy** [comment]
Let's keep it open until tested on c.nc.c, and until someone takes care of cleanup with all these media keys. We could treat them all together , and store under single key `call_preferences_<TOKEN>`:
* virtual background
* grid view / speaker view
* silent / normal call
* audio / video disabled

**Comment by SystemKeeper** [comment]
Also, any idea where the settings without a key came from?

**Comment by SystemKeeper** [comment]
> device checker from the settings bottom left?

Did not use it, it appeared after „normally“ starting a call

**Comment by nickvergessen** [comment]
if not, feel free to reopen
