### ISSUE TITLE
Change the group talk icon In Group messages

### ISSUE THREAD

**Issue by christiansass** [nextcloud/spreed#10327]
Add the ability to change the group talk icon In Group messages. would allow for easier visual identification of groups

From:
![2023-08-23 15_04_59-RH Team - Talk - Revolution Harbor - Brave](https://github.com/nextcloud/spreed/assets/35471675/a4300fff-bbed-4d83-bc55-494be86ae459)

To:
![Talk-Revolution HarborGroup](https://github.com/nextcloud/spreed/assets/35471675/5d7e5464-30bb-451e-9e2c-86c50e6918c0)

**Comment by SystemKeeper** [comment]
Hey @christiansass, this already implemented in the latest version of Talk. Which version are you using?

**Comment by christiansass** [comment]
Talk Version 16.0.5 on NextCloud  26.0.4

**Comment by SystemKeeper** [comment]
Then all you need is update to 17 / 27.
