### ISSUE TITLE
Deck card sharing - success message - include more obvious link, conversation name

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10331]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Summary
Context: When sharing a card within Deck to a Talk conversation via the "Post to a conversation" feature

Upon sharing a Deck card to a Talk conversation via ^, the success message contains a link to the conversation it was posted to. However, the link is rather hidden, i.e. the word `conversation` is the link, but with no text colour change, underline, etc to display to the user it's clickable. 

The only way I discovered it was a link was through looking at the [code](https://github.com/nextcloud/spreed/blob/251587f5261f7ed277c68fdb0735969b5bfbc4bc/src/deck.js#L48) for a [related issue](#10330).

**Describe the solution you'd like**
Would be lovely to make the link more visible/discoverable, and stretch goal to make the conversation room name appear in the success message, instead of the generic "conversation":

current: "Deck card has been posted to the selected `[conversation](link)`"
could be "Deck card has been posted to `[name-of-conversation](link)`

![image](https://github.com/nextcloud/spreed/assets/7018928/e62a6c0b-8a2c-40df-86e6-9a4498ed78a8)
(ignore typo `selectedconversation` as described in #10330 )

**Comment by nickvergessen** [comment]
I guess we should underline like in talk chats?

cc @Antreesy not sure whether this should be fixed in talk or in https://github.com/nextcloud-libraries/nextcloud-dialogs/

**Comment by gerbrent** [comment]
> I guess we should underline like in talk chats?

at the very least yes, that would be a very helpful minimum viable solution indeed 👍🏻
