### ISSUE TITLE
Deck card sharing - success message typo

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10330]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
## Summary
When sharing a Deck card from Deck to a Talk conversation via the "Post to a conversation" feature, the success message contains a typo `Deck card has been posted to the selectedconversation`

![image](https://github.com/nextcloud/spreed/assets/7018928/5c3b4675-603e-458b-851f-835e4df22732)

The offending line appears to be [here](https://github.com/nextcloud/spreed/blob/251587f5261f7ed277c68fdb0735969b5bfbc4bc/src/deck.js#L48) - though... no obvious culprit here (at least to a lamens like me)

## Steps to reproduce
1. From within Deck, share a card using "Post to a conversation" feature
2. Success message appears, but with typo

### Expected behaviour
Tell us what should happen

Should read "...selected conversation"

### Actual behaviour
success message contains a typo `Deck card has been posted to the selectedconversation`

## Talk app

no access to admin

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
116.0.2

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

cloud.nextcloud.com

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Space is there:
https://github.com/nextcloud/spreed/blob/6bd07bec3a728c64a856e21072f4bd5c04fc1505/src/deck.js#L48
I fear it's a problem of the HTML option in the `showSuccess` function of the `@nextcloud/dialogs` library then?

**Comment by nickvergessen** [comment]
In the meantime this seems to have broken completely:
![grafik](https://github.com/nextcloud/spreed/assets/213943/0dcf9f6a-2c36-48c7-9c73-77b429e9770a)

![grafik](https://github.com/nextcloud/spreed/assets/213943/a0036727-f31b-4cbf-81ba-c0f1a31de0a8)

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/deck/pull/5351

**Comment by juliushaertl** [comment]
Regarding the initial report, the toast works fine here with the deck fix and latest talk main branch:
<img width="388" alt="Screenshot 2023-12-05 at 23 18 13" src="https://github.com/nextcloud/spreed/assets/3404133/514d2ca2-7fec-4183-8029-6cfe75d82df0">
