### ISSUE TITLE
Capability for markdown

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10355]
Currently we don’t have a capability for markdown and just added a markdown property to the message to determine if markdown should be rendered or not. After implementing the use of the markdown property I see a problem: When we write and send a message talk-ios it’s added to the chat as a temporary message. After we receive the „real“ message from the server, the temporary message is replaced. When creating a temporary message, we don’t know if we support markdown or not. So the temporary message is created without markdown rendering and then gets replaced by the real message, with markdown rendering.

I think that’s not a good experience. Should we add a capability as well to prevent these cases?

@Ivansss @nickvergessen

**Comment by Ivansss** [comment]
> I think that’s not a good experience. Should we add a capability as well to prevent these cases?

I agree, not rendering markdown in temporary messages doesn't look good in terms of UX.
I would be up for adding a capability so we can render markdown directly in the temporary message if the server supports markdown.

**Comment by nickvergessen** [comment]
Could also be helpful to GFM later I guess.

Do we go with `markdown-v*` or with  `markdown` and  `markdown-gfm`?

More things coming to mind?

**Comment by SystemKeeper** [comment]
> `markdown` and `markdown-gfm`?

Sounds good to me!
