### ISSUE TITLE
🚀 Integration tests performance followups

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10377]
* Follow up to #10374 

---

- [ ] APCu currently fails some tests sounds like bugs in server, talk or testing logic, the target is to revert https://github.com/nextcloud/spreed/pull/10374/commits/15df283dc2a154f75fefe6badcdc7c1f84305428
https://github.com/nextcloud/spreed/pull/10396
- [ ] Check other apps integration tests for more performance gain, e.g. https://github.com/nextcloud/deck/blob/a44612d970dfedc9185a096791e06762bf723e78/.github/workflows/integration.yml#L95-L97
https://github.com/nextcloud/spreed/pull/10396
- [ ] Currently every `occ` call seems to reset opcache: https://github.com/nextcloud/spreed/blob/dd2b3ac4c09d314f66072cae2753a7ea9819d829/tests/integration/features/bootstrap/CommandLineTrait.php#L70-L71 But I guess it could be limited to only do it in certain cases (app got enabled/disabled?)
https://github.com/nextcloud/spreed/pull/10396
- [ ] Improve the spliting of testsuits. The overhead if ~45 seconds, but we have some testsuits that run 30-40 minutes, so distributing them into more chunks (like done already) would improve the response time of tests

**Comment by SystemKeeper** [comment]
Some tests with `feature/command`

#### Baseline:
```
29 scenarios (29 passed)
325 steps (325 passed)
3m15.94s (12.78Mb)
```

#### Removing calls to `clean_opcode_cache`:
```
29 scenarios (29 passed)
325 steps (325 passed)
2m42.48s (12.73Mb)
```

#### Removing user deletion in tearDown:

https://github.com/nextcloud/spreed/blob/2dc321081b4025a5fd65ea82dc8d519a58f0ab4c/tests/integration/features/bootstrap/FeatureContext.php#L183-L191

```
29 scenarios (29 passed)
325 steps (325 passed)
1m33.98s (12.75Mb)
```

#### Don't disable BFP on each scenario (also this is done before and after scenario?):

https://github.com/nextcloud/spreed/blob/2dc321081b4025a5fd65ea82dc8d519a58f0ab4c/tests/integration/features/bootstrap/FeatureContext.php#L2975

```
29 scenarios (29 passed)
325 steps (325 passed)
0m48.99s (12.77Mb)
```

* APCu / Redis only had a small impact on this test (but we already saw an impact on other tests)
* Using nginx / php-fpm only had a small impact on this test (tried it for fun)
* Had some fun with moving everything to `ramfs`, but no real impact here

**Comment by nickvergessen** [comment]
Removing user deletion will make files test fail either in sequence or when executed individually.

Also removing the resets of BFP, users, etc. Will cause failing chains. A failed single test will make random things fail afterwards. We've been there before and it gets even more annoying to debug.

**Comment by nickvergessen** [comment]
Maybe it's possible to check the file name and only reset BFP on the bruteforce file and things alike

**Comment by SystemKeeper** [comment]
> Removing user deletion will make files test fail either in sequence or when executed individually.

The main question is, can we limit user deletion to only the needed tests? Or can we improve delete performance?


> Maybe it's possible to check the file name and only reset BFP on the bruteforce file and things alike

Yep, I think the usage of occ in general (how it is invoked) should be checked. Each occ execution spawns a new php process to execute the command. Maybe we can check the DB for attempts before trying to reset them?
Also could we invoke occ without using proc_open?

**Comment by nickvergessen** [comment]
> Maybe we can check the DB for attempts before trying to reset them?

No, because BFP now works without DB
