### ISSUE TITLE
🤖 Bot - Currency converter

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/spreed#10400]
### Bot name

Currency convertor

### Description

Example of how easily bot can be implemented in Python.

### Screenshot URL

https://raw.githubusercontent.com/cloud-py-api/nc_py_api/main/examples/as_app/talk_bot/screenshots/talk_bot.png

### License

MIT

### Source code URL

https://github.com/cloud-py-api/nc_py_api/tree/main/examples/as_app/talk_bot

### Installation steps

https://github.com/cloud-py-api/nc_py_api/blob/main/examples/as_app/talk_bot/HOW_TO_INSTALL.md

**Comment by nickvergessen** [comment]
The screenshot seems weirdly stretched. Can you redo it (and also use bright mode for consistency)

**Comment by bigcat88** [comment]
> The screenshot seems weirdly stretched. Can you redo it (and also use bright mode for consistency)

done
