### ISSUE TITLE
Markdown rendering "eats" html tags

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/spreed#10412]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Use talk rc that has markdown support
2. send "\<test\>" as a message

### Expected behaviour
The "\<test\>" text is visible

### Actual behaviour
An empty message shows up

Some properly formatted html messages ("\<b\>test\</b\>") only have the tags stripped, while others  ("\<h1\>test\</h1\>") have both the tag and the content removed during rendering.

Instead of completely removing unsupported tags, it should instead render the html "source" as plain text

**Comment by nickvergessen** [comment]
```
    ```
    <b>test</b>
    ```
```

Should work at the moment. But yeah I agree that showing it "plain" would be better, but that needs fixing in https://github.com/nextcloud-libraries/nextcloud-vue
