### ISSUE TITLE
API "SIP dial-out"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10410]
* Overview at https://github.com/nextcloud/spreed/issues/10346

---

- [x] https://github.com/nextcloud/server/pull/40620

**Comment by fancycode** [comment]
## 1. Request to send from Talk to backend endpoint of Signaling Server:

```json
{
  "type": "dialout",
  "dialout": {
    "number": "the-e164-number",
    "options": {
      "actorId": "the-actor-id",
      "actorType": "the-actor-type",
      ...optional additional properties...
    }
  }
}
```

Answer will either be success:
```json
{
  "type": "dialout",
  "dialout": {
    "callid": "the-call-id"
  }
}
```

Or an error:
```json
{
  "type": "dialout",
  "dialout": {
    "error": {
      "code": "error-code",
      "message": "Human readable error.",
      "details": {
        ...optional-details-object...
      }
    }
  }
}
```

**Comment by fancycode** [comment]
## 2. API required in Talk to be called by SIP bridge workflow

- Receives the room token, `number` and `options` from dialout request from above.
- Verifies that the dial-out is actually allowed (a safe-guard as the dial-out is triggered by a different service than what receives the dial-out request initially).
- Should return the same structure as the existing API to check participant PINs from the SIP bridge. https://github.com/nextcloud/spreed/blob/c67c782a910aa9c77611d43dad598bacadc1f781/docs/participant.md?plain=1#L254

**Comment by fancycode** [comment]
## 3. Events sent to all sessions in a room for outgoing call status changes

Dial-out request was accepted for processing:
```json
{"type":"dialout","dialout":{"type":"status","status":{"callid":"the-call-id","status":"accepted"}}}
```

Outgoing call is rejected by the SIP provider:
```json
{"type":"dialout","dialout":{"type":"status","status":{"callid":"the-call-id","status":"rejected","cause":"EndedByTemporarilyUnavailable","code":480,"message":"Temporarily Unavailable (Call limit) "}}}
```

Outgoing call is ringing:
```json
{"type":"dialout","dialout":{"type":"status","status":{"callid":"the-call-id","status":"ringing"}}}
```

Outgoing call is connected:
```json
{"type":"dialout","dialout":{"type":"status","status":{"callid":"the-call-id","status":"connected"}}}
```

Outgoing call is cleared:
```json
{"type":"dialout","dialout":{"type":"status","status":{"callid":"the-call-id","status":"cleared","cause":"EndedByRemote"}}}
```

**Comment by fancycode** [comment]
## 4. Existing API to notify joining / leaving

The calls will use the existing API to `join` / `leave` the room:
https://github.com/nextcloud/spreed/blob/c67c782a910aa9c77611d43dad598bacadc1f781/lib/Controller/SignalingController.php#L584

**Comment by fancycode** [comment]
Draft PR for signaling server available at https://github.com/strukturag/nextcloud-spreed-signaling/pull/563

**Comment by nickvergessen** [comment]
- The same number might have to be called multiple times (call centers, etc) so might not be able to use that as actor-id

**Comment by nickvergessen** [comment]
@fancycode for the database structure:

1. callId is a string as I read in the Golang code, any max length known? 64? 255?

    > Events sent to all sessions in a room for outgoing call status changes
2. the above is not sent to the server, so a potential later joining user would not know the state of the SIP contact? Doesn't look like it would change frequently, so we could store it in the nextcloud server?

3. When a user types more numbers on a callId (to proceed in a call center), does the users frontend send this info directly to SIP/HPB or to the nextcloud server and the server then tells the HPB/SIP to type number X on callId Y?

**Comment by nickvergessen** [comment]
### Tech details

- [ ] Callid 255 chars can be wiped after call
- [ ] callid status will be saved as transient data and so be available for people that join later, storing on the server is not necessary at the moment
- [ ] SIP bridge will send a DELETE when the call was denied by the SIP gateway or hangup
- [ ] DTMF (numbers dialed later) are sent directly to the HPB (+ callId)

**Comment by fancycode** [comment]
See https://github.com/nextcloud/spreed/issues/10410#issuecomment-1726196063 for details on the call status with transient data.

**Comment by fancycode** [comment]
Possible SIP status codes are available e.g. from here:
https://en.wikipedia.org/wiki/List_of_SIP_response_codes

**Comment by fancycode** [comment]
## 5. Send events to established calls (both incoming and outgoing)

As DTMF and hangup also apply to incoming phone calls, I defined a generic way to send these:
https://github.com/strukturag/nextcloud-spreed-signaling/pull/563/commits/d4763f807a0afa4a0e0aee812b5e1292e0a78d25

Basically you have to get the session id of phone calls from the `joined` event (you can match this through the call id) and then send a `control`  message to these sessions to hangup or send DTMF (or to mute them).
