### ISSUE TITLE
Can not leave conversation when the lobby is enabled and you are not a moderator

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10420]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Get invited to a conversation as normal user
2. You are blocked by the lobby

### Expected behaviour
You can leave the conversation

### Actual behaviour
No leave option displayed
![Bildschirmfoto vom 2023-08-30 13-52-54](https://github.com/nextcloud/spreed/assets/213943/d349d766-d0b5-42b6-8a0f-514c9e880984)

## Talk app

**Talk app version:** 17.1

**Comment by Antreesy** [comment]
Conversation 'capabilities' for a user comes from server like this:

![image](https://github.com/nextcloud/spreed/assets/93392545/74c8606c-77a1-4375-8840-d22679999d80)
