### ISSUE TITLE
Bots are guests. That is kind of odd. Can't we make them 'bots'?

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#10466]
See screenshot. The meeting summary bot is noted as guest in notifications and such. That's a bit strange, esp in a 1:1 where you can't even have guests 🙄 

![2023-09-04 17-45-13-0](https://github.com/nextcloud/spreed/assets/551757/8bfa08c7-427e-4cda-9aef-a387c5f7012e)

**Comment by nickvergessen** [comment]
Definitely not intended
