### ISSUE TITLE
Removing participant info from rooms api

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1046]
Because we removed the usage of it from the web UI with https://github.com/nextcloud/spreed/pull/1045
We could remove the participant list from the rooms api (it should also not belong there in first place).

Relevant values are:
* numGuests
* guestList
* participants

But we need to be sure the mobile clients don't use them, please confirm:
- [ ] Android @mario 
- [ ] iOS @Ivansss

**Comment by mario** [comment]
So we can't do this, as discussed :)
