### ISSUE TITLE
Show error if recording server is configured, but no signaling server

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10486]
https://github.com/nextcloud/spreed/blob/14f77fcb51485025250aa094ebccba9e8c456496/src/components/AdminSettings/RecordingServers.vue#L30-L32

Like the upload warning, we should show a warning in case a recording server is configured, but no signaling server.

**Comment by nickvergessen** [comment]
Should be an error, because it actually doesn't even work?
