### ISSUE TITLE
[Bug] Participants list is fetched twice from server

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10497]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
## Overview
Mixin `getParticipants.js` doesn't share data between components (`TopBar` and `ParticipantsTab`), so they are not aware of CancelableRequest processing already => create a new one, resulting in second server request

Possible steps to solve:
- [ ] implement logic from messageStore - it keeps cancelable requests in store, making them available for all instance
- [ ] move logic from mixin to the participantsStore
- [ ] Replace mixin with composable

## Steps to reproduce
1. Open DevTools - Network
2. Join group conversation
3. See result

### Expected behaviour
![image](https://github.com/nextcloud/spreed/assets/93392545/c03f39f7-2806-4fb9-8de7-57f70add76d6)

### Actual behaviour
![image](https://github.com/nextcloud/spreed/assets/93392545/587ccae1-f094-4149-8ddd-771beaf754e0)

## Talk app

**Talk app version:** master and below (code is there since 2021: 449260f9435bece772b0c4d025152157db7c3e93)

**Comment by nickvergessen** [comment]
But only for 1-1 conversations, right?
