### ISSUE TITLE
The problem of displaying text in two languages

### ISSUE THREAD

**Issue by parsmmm** [nextcloud/spreed#10522]
I have a basic problem, when I write and send a message which has a combination of English and Arabic letters, the sent message is displayed completely messed up. Please solve this problem... I think it is the same for other perso-arabic languages.

**Comment by Antreesy** [comment]
> I think it is the same for other perso-arabic languages.

Hi! Could you provide us with more explanations?
- Screenshots
- Examples of sentences, with different word combination, and different leading words
- Are other messengers behaving normally for your examples?

We're suspecting, that it could be Right-To-Left issue for the input component, and test in in Meta Messenger - it behaves the same for our examples

**Comment by parsmmm** [comment]
the problem occurs when the sentence starts with arabic language it doesnt happen in other messengers like meta messenger because they become rtl instantly when you type arabic words but in nextcloud it doesnt 
for example the sentence 
السلام علیکم my friend
In meta messenger:
![image](https://github.com/nextcloud/spreed/assets/136156164/6190dc8a-8bb5-48dc-9248-311763e5d0c1)
In Nextcloud Talk:
![image](https://github.com/nextcloud/spreed/assets/136156164/70e8117f-6e7a-4531-98a3-1eb988f0a5dd)

(Note that the original sentence is that in way the arabic words come first)

**Comment by Antreesy** [comment]
Attribute `dir` is missing for parsed markdown in that case, so putting `dir="auto"` on the root element of NcRichText. But it should it be upstreamed and discussed on a library level for all components with possible user inputs

**Comment by parsmmm** [comment]
So if I understand it correctly, there is no fix for talk at the moment and it need to be fix globally
Its almost everywhere for example in about section in profile pages or in search area

**Comment by Antreesy** [comment]
You are right, it's not set up globally, and should be solved mostly on the libraries level, but also, as I understand, interface of each application should be mirrored from left to right, which is a big effort.

Least we can do, is to apply that only for messages text for now, but should be aligned with @nextcloud/designers if it is okay to do that or not, and also loopthrough all markdown styles applied, as they should also be fixed according to text direction:

![image](https://github.com/nextcloud/spreed/assets/93392545/5c9d4ab0-ab7f-4b07-b0b1-da8910957818)

**Comment by parsmmm** [comment]
Sorry to bring this up again, 
Is there any temporarily fix to this problem ? 
Im kinda stuck in a situation that need this to be fixed.
What did you mean by putting dir="auto" on the root element of NcRichText ? Does it mean that I should change the code and recompile the whole nextcloud ? 
Regards

**Comment by Antreesy** [comment]
Hi,
Looking by design team reaction, I think, I can make a pull request for this, and provide a patch, so you can test it on your instance. Give me some time, please =)

**Comment by parsmmm** [comment]
@Antreesy I have a question you...
Is this problem fixed in version 17.1.3 ?

**Comment by Antreesy** [comment]
> Is this problem fixed in version 17.1.3 ?

Hi! We are currently testing it in production with version 18 beta. If it goes smoothly, we may consider to backport it for 17.1.4
