### ISSUE TITLE
UI Issue with additional actions menu

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/spreed#10520]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to talk web app and to a chat room with some messages from you.
2. Make sure, there is a message from you (that you can delete)
3. Open the additional options (3 dot menu)
4. Make sure, that the additional menu needs scrolling (change window size, resolution, or zoom factor)
5. Try to access the menu entry to delete the chat message

### Expected behaviour
Smooth scrolling and no UX issues

### Actual behaviour
If you scroll down using the mouse wheel and move the mouse after that, the scroll jumps back to the top. I think this happens once the mouse touches one of the horizontal lines in the menu.

## Talk app

I have no access, this was tested on the server of the Nextcloud conference 2023 running right now.

## Browser

**Microphone available:** irrelevant

**Camera available:** irrelevant

**Operating system:** Archlinux

**Browser name:** Firefox

**Browser version:** 110.0

### Browser log

_Nothing was logged_

## Server configuration
_Mostly irrelevant as UX. Also unknown as foreign server._

**Nextcloud configuration:**
_Unknwon as foreign server_

### Server log (data/nextcloud.log)

_Irrelevant here as pure UX_

**Comment by christianlupus** [comment]
I am unsure if this issue is in the Vue components used of in the usage of them. You might need to investigate.

For Clearness, I added a screencast here:

https://github.com/nextcloud/spreed/assets/8202922/09702084-3a48-46b3-b376-78c8499595dc

**Comment by Antreesy** [comment]
Hi, Christian! This definitely looks like an issue with vue-library, as we don't have any scrolling changes in the Talk for this menu. Should come from this code part:

https://github.com/nextcloud-libraries/nextcloud-vue/blob/57557706ea8141dfafee62d211d7b2810a0d19e7/src/components/NcActions/NcActions.vue#L843-L860

**Comment by christianlupus** [comment]
I will report at the Vue library. Thanks for looking into it.

**Comment by nickvergessen** [comment]
Fixed upstream and the library was updated, so assuming this is fixed.
