### ISSUE TITLE
Weird response/log coming in from API calls

### ISSUE THREAD

**Issue by bugbountyguy** [nextcloud/spreed#10526]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Make a valid POST request to /ocs/v2.php/apps/spreed/api/v1/chat/{id}

### Expected behaviour
I should be able to make POST requests like I used to without an error showing up

### Actual behaviour
Errors in logs, but works fine - noisy logs?

## Talk app

**Talk app version:** 17.1.0
**Custom Signaling server configured:** no
**Custom TURN server configured:** no
**Custom STUN server configured:** no

### Server log (data/nextcloud.log)
<details>

```
127.0.0.1 nextcloud: {"reqId":"[filtered]","level":3,"time":"2023-09-18T00:49:24+00:00","remoteAddr":"172.20.0.1","user":"[filtered]","app":"spreed","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/[filtered]","message":"You need Nextcloud Server version 27.1 or higher for Bot support (detected: 27.0.2.1)","userAgent":"python-requests/2.31.0","version":"27.0.2.1","data":{"app":"spreed"}} 
```
</details>

### Info/Questions

Considering the overall system works fine, this error doesn't appear to be breaking my scripts, but I'd like to confirm that my current scripts are not going to break once Nextcloud goes up to the next version, and if they are, what I need to do to avoid that from happening. I have LOTS of automation that takes advantage of the Nextcloud Talk API in order to notify me of things immediately on my mobile phone (basically it's a "free sms" in a way for me and stays internal and secure)... If there's going to be a breaking change in v27.1+, I'd like to prepare some time to get a list of all my scripts and what fixes I need to implement to make this as least impactful and stressful as possible. If there's nothing that should break and the regular POST request will continue to work, then awesome.

Thanks

**Comment by nickvergessen** [comment]
You can easily fix that by updating Nextcloud Server to the latest (supported) version: 27.1.0
