### ISSUE TITLE
Icon has wrong aspect ratio after reload from being logged out

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#10534]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Be in a room with a user account and close your laptop over night.
2. Have your session expire while laptop is closed.
3. Open your laptop, notice your signaling connection is not reconnected automatically and reload the page (now as anonymous guest user).

### Expected behaviour
The UI should look consistent.

### Actual behaviour
![icon-aspect-ratio](https://github.com/nextcloud/spreed/assets/247730/34fb71ae-36e3-4329-b8a5-86653fc53761)

Experienced on c.n.c in the Talk development room.

**Comment by Antreesy** [comment]
Caused by added image description `alt` here: https://github.com/nextcloud/spreed/commit/d098455b5c1b94782408ea7261ff89b7555d33a0
