### ISSUE TITLE
In fullscreen, sidebar should shrink video view instead of overlap

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1054]
Currently the sidebar overlaps the video feed when in fullscreen. This is not so nice when you want to chat next to the video call, because it overlaps the main video and yourself too.

Instead, it should do it like in non-fullscreen and "push" the video.

**Comment by nickvergessen** [comment]
I think this was not possible because Mozilla prevents width/margin controll on fullscreen elements

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/749

**Comment by jancborchardt** [comment]
Hmm, bummer. But let’s keep the issue open, because margin is not the only way to solve this. :)

**Comment by nickvergessen** [comment]
This is already the case in Talk 13
