### ISSUE TITLE
Link to message of same conversation could directly scroll to it, currently it opens new tab

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10565]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently when clicking the link to a message in the same conversation, it opens in a new tab.

**Describe the solution you'd like**
It could be checked first if it’s the same conversation (e.g. by comparing the URL), and then only navigating via the anchor.

**Comment by Antreesy** [comment]
Duplicate of #8855?
