### ISSUE TITLE
Animated reaction emojis

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10561]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
The current reaction emojis could be a bit more celebratory. :D 

**Describe the solution you'd like**
Animated emojis! This library could help: https://googlefonts.github.io/noto-emoji-animation/

**Comment by DorraJaouad** [comment]
I think it's better to add the library in upstream.
Should call reactions be also updated ?

**Comment by nickvergessen** [comment]
This ia only about call reactions and only about the displaying in the CallView I think

**Comment by Antreesy** [comment]
Could be designed that way, so it may be reused for Message component => Single Emoji message
![image](https://github.com/nextcloud/spreed/assets/93392545/04ba0239-374c-4da1-8d91-24f376aab134)

**Comment by jancborchardt** [comment]
Yep, as @nickvergessen said for now this is only about call reactions. :) For in the chat something like stickers would be more fitting but that’s a different topic. :)
