### ISSUE TITLE
Emojis autocomplete in talk

### ISSUE THREAD

**Issue by lukyrys** [nextcloud/spreed#10569]
Is there any way to disable autocomplete? or eg. autoclose on basic smiles.. when i type ":D" on end of message i will need to double enter for send message.. this is annoying

probably after this merge #8870

**Comment by nickvergessen** [comment]
No such option available. We added the plain text emojis as a first option in the emoji picker to avoid people posting 🫥 instead of :D and 🇨🇨 instead of :)

But I don't think we can do more at the moment
