### ISSUE TITLE
Video/people layout of group calls or conversations shared by link looks off initially

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10567]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When starting a call in a group room, the starting layout is grid view which leads to this strange layout in the beginning:
![image](https://github.com/nextcloud/spreed/assets/925062/e8b4209b-364b-47e2-974b-1bdcba4ae489)

And even when the first person joins it’s side by side which is an unusual view – but most importantly it jumps around immediately:
![image](https://github.com/nextcloud/spreed/assets/925062/1c59fee3-f23e-4b66-8aee-9630e521c7b2)

**Describe the solution you'd like**
It would be nicer to use the speaker view at least for the first 3 participants. (Note that of course the emptycontent message or the own video has to be adjusted a bit so it all fits also on smaller screens):
![image](https://github.com/nextcloud/spreed/assets/925062/f792812d-32ac-4655-8cfa-7225e214db77)

**Comment by Antreesy** [comment]
Might be solved together with #10496?
