### ISSUE TITLE
"Disable video" icon should be half-opacity, and only show on hover/focus

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1057]
Currently the "Disable video" icon on people’s video feeds is shown very present and overlapping. Instead it should show at opacity: .5; and only show on hover/focusing.

**Comment by nickvergessen** [comment]
mind to show with a screenshot what you mean exactly?

**Comment by jancborchardt** [comment]
Yes, sorry – here is an example from a call with 5 people. The "Disable video" icon (the camera) is almost in the middle of the video, and especially when the person is muted too almost nothing of their video is visible because it’s obstructed by 2 icons and name text:
![screenshot from 2018-07-04 16-08-28-cropped](https://user-images.githubusercontent.com/925062/42954259-8fc44650-8b7c-11e8-983d-67f3ab5fcc1f.png)
