### ISSUE TITLE
Notification count bubble should only be blue for direct mentions/messages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1058]
Currently the notification count bubble is always blue, regardless if the message is to the whole room or directly to you.

What we should do is to only add the blue bubble around it when there’s direct @mentions to you or when they are in a 1on1 convo. Otherwise the number should not be in a bubble (or the bubble should be grey, like when there’s an @-mention to another person.)

@danxuliu

**Comment by nickvergessen** [comment]
Moving from frontend to api, because the problem is we don't know if a user was mentioned after the readmarker.
