### ISSUE TITLE
Show out-of-office message in 1:1 conversations

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#10599]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

As a Nextcloud user I want to be warned when another users is currently out-of-office.

**Describe the solution you'd like**

Integrate with https://github.com/nextcloud/server/issues/40397 and show the long out-of-office message in 1:1 chats. The short message will already be in the status.

**Describe alternatives you've considered**

N/a

**Additional context**

I'm working on https://github.com/nextcloud/server/issues/40650 and appreciate input on the data and APIs needed for this integration.

**Comment by ChristophWurst** [comment]
Example:

![](https://techcommunity.microsoft.com/t5/image/serverpage/image-id/31624iC5B4E6A45AF9467B/image-size/large?v=v2&px=999)

https://techcommunity.microsoft.com/t5/microsoft-teams-blog/what-s-new-in-microsoft-teams-april-update/ba-p/179801

**Comment by nickvergessen** [comment]
* To enable the settings UI currently an appconfig needs to be set:
```
occ config:app:set dav hide_absence_settings --value no
```

* Afterwards `/index.php/settings/user/availability` shows the setting:
![grafik](https://github.com/nextcloud/spreed/assets/213943/f9c029c5-250d-4df9-bdf9-64f9e955767f)


* https://github.com/nextcloud/server/issues/41378 will bring an automated status
* When the status message id is the [magic string `availability`](https://github.com/nextcloud/server/blob/f14a4f8fd73c71e76a9747ac51e657030f5bb835/lib/public/UserStatus/IUserStatus.php#L78-L82) the UI should then show the status message better visible (as per above) in a way that makes clear that no reply can be expected at this point.

**Comment by nickvergessen** [comment]
cc @Antreesy this was forgotten to add to the list/board.

Can you check it?
