### ISSUE TITLE
System Notifications

### ISSUE THREAD

**Issue by Smith-fms** [nextcloud/spreed#10596]
Hello!

We have the issue that we've set up various info channels in our association where all members are integrated. When we remove or add members, the system sends corresponding notifications in these channels. Can these be turned off? Or can they only be made visible to moderators?

Best regards,
Smith

**Comment by nickvergessen** [comment]
No, the system messages are like chat messages and their visible can not be restricted at the moment.

**Comment by Smith-fms** [comment]
You closed this, but this is also a Feature request.
