### ISSUE TITLE
Feature Request : add calls (video/audio) actions into the text chats

### ISSUE THREAD

**Issue by GLLM** [nextcloud/spreed#1060]
**Use case :** 
I have a chat session with someone.

1. This person calls me, but I could not take the call, or even missed it.
It would be great to see, in the Chat texts,
_Missed call from contact_name at hh:mm on dd/mm/yyy_

2. I call this person, we talk and hang.
I would be great to see, in the Chat texts,
_You called contact_name for duration, at hh:mm on dd/mm/yyy_

3. This person calls me, we talk and hang.
I would be great to see, in the Chat texts,
_Contact-name called you for duration, at hh:mm on dd/mm/yyy_

These lines could appear in a different bubble color than the standard blue chat bubbles.

Is this something feasible ? interesting to anyone ?

Ideally, this works with whatever device is used

Thanks
GLLM

**Comment by nickvergessen** [comment]
This is pretty much what #614 is about.
Feel free to add your comment there too

**Comment by GLLM** [comment]
@nickvergessen : Oh, yo are right ... I didnt find this one when looking for this F.R. Sorry about this. I'll close this issue and commetn in the other one.
