### ISSUE TITLE
RFC: Mentions in forwarded messages

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#10631]
ATM we handle mentions by names here: https://github.com/nextcloud/spreed/blob/77a4405ae0f0e315fa4e412bf04bb8c987fdde5b/src/store/messagesStore.js#L1266

Depending on correlation id/name it will be rendered in different conversation if:
- `name === id`
- `name.split(' ').includes(id)`.

Notification won't be triggered for this person though (or something prevents reproducing it)
When developing, all mention options should be considered:
```
@all
@user1
@"user@2"
@"user 3"
```

See screenshot attached
![image](https://github.com/nextcloud/spreed/assets/93392545/bc260931-6759-4297-890c-9382bb920f97)

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/pull/10603#discussion_r1345572096_

**Comment by DorraJaouad** [comment]
```javascript
				if (key.includes('mention-call')) {
					message.message = message.message.replace(`{${key}}`, `@${mention.name}`)
				} else {
					message.message = message.message.replace(`{${key}}`, `@"${mention.id}"`)

				}
```
The double quotes " could solve mentions with `id` containing space and the other types remain rendered correctly.
For the at-all mention, we can just identify it by 'mention-call' and use `name` instead of rendering its token but it won't remain as a mention object in forward. 

![image](https://github.com/nextcloud/spreed/assets/84044328/16d140fc-958c-44c0-9588-f7d323a4dc36)

**Comment by nickvergessen** [comment]
> For the at-all mention, we can just identify it by 'mention-call' and use name instead of rendering its token but it won't remain as a mention object in forward.

yes, that is actually the plan and okay.

Can be an issue thou if e.g. the room name starts with a user ID or the word "All", because then `@Old room display name` will actually create a mention with `@old` if the user exists.

**Comment by Antreesy** [comment]
Or we can avoid using @, just posting the Conversation name, maybe with **bold markdown** wrapping?

**Comment by DorraJaouad** [comment]
> with bold markdown wrapping?

That might not be read as a mention though. maybe also wrap it with double quotes ? 
e.g : @"conversation name"

**Comment by nickvergessen** [comment]
> That might not be read as a mention though.

Well the `@all` from the other room must not be a mention in the new room, so it would exactly match the desired behaviour.

> maybe also wrap it with double quotes ?

That still renders mentions. We need to use it when the mention id conttains a space or slash. but for `@all` marking it bold sounds like a reasonable replacement.

**Comment by Antreesy** [comment]
Note: as it's a bug in 27 and below, do we consider backporting it? Requires manual backport, as logic was moved to store with feature PR

**Comment by nickvergessen** [comment]
It was a bug since such a long time and no one cared, so no backporting :)
