### ISSUE TITLE
New WebRTC library

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1063]
SimpleWebRTC was officially deprecated and is now replaced with a business:
https://github.com/andyet/SimpleWebRTC
> The open-source version of SimpleWebRTC has been deprecated. This repository will remain as-is but is no longer actively maintained. Read more about the "new" SimpleWebRTC (which is an entirely different thing) on https://simplewebrtc.com

**Comment by nickvergessen** [comment]
We should go for the "official" webrtc adapter lib directly and manage the rest ourselves.
https://github.com/webrtc/adapter

**Comment by nickvergessen** [comment]
Prerequirement for #1076

**Comment by Vaibhav1587** [comment]
Is it done ? are we already transferred to the new webRTC  ?  
Checking on 30th Oct 2018 commit 

> 5b36480d052a2e69fd051038bb0f0312b289e46a

**Comment by nickvergessen** [comment]
No :crying_cat_face:
