### ISSUE TITLE
Notifications should consider message read status

### ISSUE THREAD

**Issue by poiNt3D** [nextcloud/spreed#10641]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

The problem is, when a conversation is open, but the window is not in focus, minimized, or another tab is opened,
no notifications are received about new messages.

**Describe the solution you'd like**

Notification should be sent if a user has not read a message for an X amount of time, even if the chat is open.

**Describe alternatives you've considered**
Use some another way to notify users about new messages

**Comment by nickvergessen** [comment]
> The problem is, when a conversation is open, but the window is not in focus, minimized, or another tab is opened,
no notifications are received about new messages.

Fixed with #1575 for the upcoming major version
