### ISSUE TITLE
Readme screenshot: one name is missing

### ISSUE THREAD

**Issue by moritz-t-w** [nextcloud/spreed#10644]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
 guy in the bottom right doesn't have a name and icons
![image](https://raw.githubusercontent.com/nextcloud/spreed/master/docs/call-in-action.jpg)

**Comment by nickvergessen** [comment]
That's "your own" video, your own icons are in the top bar and we don't show your own name

**Comment by moritz-t-w** [comment]
wow lmao
