### ISSUE TITLE
Seeking Community Assistance for Integrating Nextcloud spreed signaling with OpenLiteSpeed

### ISSUE THREAD

**Issue by aaglctest** [nextcloud/spreed#10665]
Hello everyone,

I hope you are all doing well. I'm reaching out to the Nextcloud community for some guidance and assistance with a specific integration task.

Integration Task:

I am currently working on integrating Nextcloud-spreed-signaling with OpenLiteSpeed as my web server. While I have followed the recommended configuration steps, I have encountered some unexpected issues and challenges.

Seeking Community Expertise:

I believe there are many experienced members in the Nextcloud community who may have valuable insights and expertise in this area. Therefore, I would like to request your assistance, suggestions, and guidance to help me successfully complete this integration.

Specific Issues Encountered:

I have encountered [describe the specific issues or errors you've faced briefly]. Here are the details of my setup:

Operating System: Ubuntu LTS 20.04 (with Cyberpanel 2.3)
OpenLiteSpeed Version: 1.7.18
Steps Taken:

I have followed the following steps as recommended in this documentation:

https://markus-blog.de/index.php/2020/07/30/how-to-install-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu/

I am open to any suggestions, tips, or solutions that you may have. If anyone has successfully integrated Nextcloud-spreed-signaling with OpenLiteSpeed or has experience with similar setups, I would greatly appreciate your input.

Thank you for being part of this fantastic community!

Best regards,

**Comment by nickvergessen** [comment]
Since this is not a bug or feature request for talk, I think you are better off posting in https://help.nextcloud.com/
