### ISSUE TITLE
Unability to write message in a Talk chat if several colleagues are editing the document

### ISSUE THREAD

**Issue by GreenWebspace** [nextcloud/spreed#10670]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start editing any shared document with several colleagues.
2. Click on icon "Share" nearby "Close document" in a right upper corner.
3. Choose "Chat" tab and click on the "Join conversation" button/hyperlink.
4. Try to put any text to the document, then click on the Talk chat.
5. Ask your colleagues to edit the document simultaneously with you.
6. Try to write anything in the chat.

### Expected behaviour
You are writing in the chat something to your colleagues.

### Actual behaviour
While your colleagues are typing, your cursor is constantly returning back to a place in the document where you have edited text last time. You can click to the chat, but there is no way to text anything there :-)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
yes
d22b4ef2ad7f52fd5a91d2dce6bf89f7d6c49295

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
yes

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Windows, but reproduces on Linux too.
**Browser name:** Firefox/Chrome/...
Chrome, but reproduces on other different browsers
**Browser version:** 85/96/...
(117.0.5938.149)
### Browser log
Sorry, haven't caught log during the issue.
<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian
**Web server:** Apache/Nginx
Apache
**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria
**PHP version:** 8.0/8.1/8.2
8.2
**Nextcloud Version:** (see admin page)
27.0.2

**List of activated apps:**

<details>
Enabled:
  - activity: 2.19.0
  - bbb: 2.5.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.1
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_fulltextsearch: 27.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - fulltextsearch: 27.0.2
  - fulltextsearch_elasticsearch: 27.0.3
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.3.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.1
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nc1-co.greenwebspace.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "overwrite.cli.url": "https:\/\/nc1-co.greenwebspace.at",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "0.0"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "enable_previews": "true",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "auth.bruteforce.protection.enabled": "true",
        "trashbin_retention_obligation": "auto,7",
        "defaultapp": "file",
        "updater.release.channel": "stable",
        "default_phone_region": "AT",
        "maintenance": false,
        "serverinfo": {
            "token": "9aac417748816e3b2e430d86c499358ce87732b388e818775df68565c00259bb"
        }
    }
}
</details>

### Server log (data/nextcloud.log)
<details>
[nextcloud.log](https://github.com/nextcloud/spreed/files/12850772/nextcloud.log)

https://github.com/nextcloud/spreed/assets/142007937/421ef3ac-de76-41cf-b0c7-a870777622ce

</details>

**Comment by nickvergessen** [comment]
Sounds like a bug in Text, if that is always stealing back the focus?

**Comment by GreenWebspace** [comment]
> Sounds like a bug in Text, if that is always stealing back the focus?

yes
