### ISSUE TITLE
Participants count in call inaccurate

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10677]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. be in a call with many participants
2. note the total participants number active in the call is incorrect
3.

### Expected behaviour
Call participant count should reflect actual participant count

### Actual behaviour
Here, the participant count (top bar, beside call duration counter) is 3, but clearly there are more participants

![273933036-014a6141-267a-4a0e-8367-eb29750e4542](https://github.com/nextcloud/spreed/assets/213943/38c9d30c-3738-4890-8cdb-8504f6de3e4d)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no
no

**Camera available:** yes/no
no

**Operating system:** Windows/Ubuntu/...
Linux/openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
118.01

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

cloud.nextcloud.com

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Antreesy** [comment]
`getParticipants()` mixin depends on `isActive` prop, and will update participants list only when true.
Should be the reason why it's not happening for TopBar and open RightSidebar with ParticipantsTab as inactive tab
