### ISSUE TITLE
Add preview options for the sharing dialogue in Talk

### ISSUE THREAD

**Issue by geonom** [nextcloud/spreed#10689]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

When I want to share a file from Nextcloud in Talk, there are no previews, making sharing images very, very tedious, especially when they do not have unique helpful names (see screenshot)

**Describe the solution you'd like**
I would like to have either the option to show preview images or showing preview images always in the sharing dialogue.

**Describe alternatives you've considered**
You could make it optional. But apart from that it is difficult to enforce a clear naming convention for hundreds of users in our case.

**Additional context**
![grafik](https://github.com/nextcloud/spreed/assets/1165081/849f79a4-ffea-47ef-a363-52217b23d422)

**Comment by nickvergessen** [comment]
> When I want to share a file from Nextcloud in Talk, there are no previews, making sharing images very, very tedious, especially when they do not have unique helpful names (see screenshot)

If previews are supported by the server they should show up there. Maybe the right size was not generated yet and just needs more time to be created and then delivered to your browser.

If also after a longer waiting time they do not appear, this is a bug in the upstream library. Can you report it in …


---

Actually it's already reported as a regression:
https://github.com/nextcloud-libraries/nextcloud-dialogs/issues/1010

So we will have to wait for upstream and will then just bump the library version once it was released

**Comment by nickvergessen** [comment]
In the meantime we upgraded to version 5 but now the previews are gone completely:
![grafik](https://github.com/nextcloud/spreed/assets/213943/dcd55b1a-4d55-4ee8-a4f4-df8780355bc5)

Also the padding seems to be missing on the left side. Is this all intended @susnux ?

**Comment by SystemKeeper** [comment]
Works for me with 18 rc3, can you confirm @geonom ?

**Comment by Antreesy** [comment]
Works for Talk at stable28, older versions might require to bump `nextcloud/dialogs` library up to 4.2.2
So considering as closed with https://github.com/nextcloud/spreed/pull/10821
