### ISSUE TITLE
🌏 Testing federation while there is no frontend yet

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10686]
Couple of manual steps are needed at the moment before being able to execute federation things locally.

1. Enable federation on your instance
```
occ config:app:set spreed federation_enabled --value yes
```
2. Allow federation with self-signed certificates and local remote servers
```
occ config:system:set sharing.federation.allowSelfSignedCertificates --value true --type bool
occ config:system:set allow_local_remote_servers --value true --type bool
```
3. In case you do have a SSL cert set up on the instance you want to sent the federation invite to, make sure it's imported into your nextcloud and check it really worked (second command)
```
occ security:certificates:import /path/to/the/nextcloud.crt
occ security:certificates 
```
Lists something like the following for me:
```
+-----------------+-------------+--------------+--------------+-------------------------------------+
| File Name       | Common Name | Organization | Valid Until  | Issued By                           |
+-----------------+-------------+--------------+--------------+-------------------------------------+
| nextcloud28.crt | nextcloud28 | Nickv        | May 20, 2028 | Nickvergessen Certificate Authority |
+-----------------+-------------+--------------+--------------+-------------------------------------+
```
4. Install the OCS viewer app https://github.com/nextcloud/ocs_api_viewer
5. Navigate to the OCS > spreed > room > "Add a participant to a room"
6. Fill in the auth (your current user name + password)
7. Fill in the parameters: (see big screenshot below)
    - apiVersion: `v4`
    - token: _token of the conversation you want to invite to_
    - newParticipant: `USERID@SERVERIP` or when you use a domain to access nextcloud use that, e.g. `admin@nextcloud.local`
    - sources: `remotes`
    - Confirm with `Send API Request`
8. 🎉  The invited user should now have a notification informing them about the invite
![grafik](https://github.com/nextcloud/spreed/assets/213943/71410a48-8673-4c1d-8522-dfdce5e72644)

![grafik](https://github.com/nextcloud/spreed/assets/213943/fea281db-8f75-4638-ba3d-175920194472)

**Comment by Antreesy** [comment]
Frontend shortcut: modify method
https://github.com/nextcloud/spreed/blob/8f989237c6e98e6aafec71d05303d6d0b2136796/src/components/RightSidebar/Participants/ParticipantsSearchResults/ParticipantsSearchResults.vue#L246-L249
with following code:
```js
addableRemotes() {
	if (this.searchResults !== []) {
		return this.searchResults.filter((item) => item.source === 'remotes')
			.concat(this.addableUsers.map(user => ({
				...user,
				id: user.id + '@' + window.location.host,
				label: user.label + '@' + window.location.host,
				source: 'remotes',
			})))
	}
```

That should allow to list local users as remote users:
![image](https://github.com/nextcloud/spreed/assets/93392545/2b65d403-a414-460f-a7e5-260b494fc738)

**Comment by SystemKeeper** [comment]
When using julius docker container (when using the `nextcloud` container, otherwise adjust the name):

```
./scripts/occ.sh nextcloud config:app:set spreed federation_enabled --value yes
./scripts/occ.sh nextcloud config:system:set sharing.federation.allowSelfSignedCertificates --value true --type bool
./scripts/occ.sh nextcloud config:system:set allow_local_remote_servers --value true --type bool

For SSL (adjust the filename):
docker compose cp data/ssl/nextcloud-mm.local.crt nextcloud:/tmp
./scripts/occ.sh nextcloud security:certificates:import /tmp/nextcloud-mm.local.crt
./scripts/occ.sh nextcloud security:certificates
```

**Comment by nickvergessen** [comment]
Moving 2+3 into the readme, the rest is not needed anymore
