### ISSUE TITLE
Left sidebar - conversation alt text incorrect

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10698]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
## Summary
In Talk, hovering the mouse cursor over a conversation in the leftbar conversation list produces alt-text, however that text is incorrect. The text that's actually presented is the name for a different conversation.

## Steps to reproduce
1. hover mouse over conversation name in left side bar
2. alt-text appears, but is incorrect
3.

### Expected behaviour
should show alt-text for entire conversation name of currently mouse-over conversation

### Actual behaviour
... shows instead the name for a different conversation, i.e. not the conversation currently with mouse-over

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
Linux openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox 

**Browser version:** 85/96/...
118.01

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

cloud.nextcloud.com 2023.10.13

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by gerbrent** [comment]
It has also been observed that two conversations (A, B) present alt text for conversation C.

As in:
Conversation A alt text = name of conversation C
Conversation B alt text = name of conversation C
Conversation C alt text = name of conversation C

Note:  these conversations ABCDE are NOT neighbors in the listing.. showing here how occasionally there are duplicates, seemingly random.

**Comment by Antreesy** [comment]
Hello!
Is it possible for you to provide a screenshot? I can't understand from the description, whether it is `title` browser tooltip or image `alt` attribute for you

**Comment by nickvergessen** [comment]
Shared it with you

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/spreed/pull/10589
