### ISSUE TITLE
Chinese zhuyin fuhao input is not available

### ISSUE THREAD

**Issue by ktshen** [nextcloud/spreed#1071]
## Behaviour
A chinese word can be represented by one to four symbols in Zhuyin.
For example：ㄋㄧˇ  =>  你
But when I try to type in , the first symbol (ㄋ) will disappear after I key in the second and the third symbol(ㄧˇ) and I will get another word like 以 (ㄧˇ).

**Operating system:  Windows and MacOS

**Browser name:**  Firefox Chrome

**Browser version:**  Chrome 67,  Firefox 61

**Comment by nickvergessen** [comment]
I can only copy paste the character and that works pretty well.
Do you have any hint how to cause the problem on ubuntu with a european keyboard, e.g. with a input helper or something?

**Comment by ktshen** [comment]
Typing English character is fine. The problem happens when zhuyin characters are trying to form a Chinese word. Below is an example to illustrate this. The girl tries to type 你(ㄋㄧˇ）好(ㄏㄠˇ
）.  I've copied the link of the youtube video at specific time.
[Example](https://youtu.be/9Uqx4DaD_2c?t=112)

I'm using Mac, so if you have a mac at hand, you can find the Zhuyin Keyboard at
"Open Keyboard Preference" > "Input Sources" > "Chinese, Traditional" > "Zhuyin"

If you are using Ubuntu, I've found a website teaching how to install it with clear pictures (Chinese words won't influence your comprehension)
[Website](https://goo.gl/c2pjeX)

Hope these pieces of information are useful for you.

**Comment by jimmy5670** [comment]
when try input start at zhuyin, doesn't work, but start from English or symbol, then I can type zhuyin normaly,
so I type every chinese message start from use ［.］ ,then type my chinese message.

win10 chrome and firefox

**Comment by stephanosio** [comment]
> when try input start at zhuyin, doesn't work, but start from English or symbol, then I can type zhuyin normaly,
> so I type every chinese message start from use ［.］ ,then type my chinese message.
> 
> win10 chrome and firefox

The exact same behaviour is observed when attempting to type Korean.

**Comment by medivh-jay** [comment]
hello, I have the same problem

**Comment by nickvergessen** [comment]
We are now (in Talk for Nextcloud 18) a different At lib.
This is developed with Chinese comments in the source code and it seems to work atm. So hopes are high it stays working.
