### ISSUE TITLE
Add acoustic feedback for a call actions

### ISSUE THREAD

**Issue by alexara** [nextcloud/spreed#1072]
As @mario stated, that's a task for you: https://github.com/nextcloud/talk-android/issues/254

It would be great to have the following acoustic feedback as a normal phone or Skype does :)    

- Play a ringing sound when a call is initiated until the call receiver picks ups or joins the call
- When a user hangs up or a call ends, play an appropriate sound

### Actual behaviour
Currently when Alice calls Bob with NextCloud Talk, the screen simply stays black until Bob joins; or when Bob leaves, Alice won't be notified about it. That's a pretty bad UX as I figured out with friends.

### Naive suggestion

Could it not be solved by a simple status message system?

When Alice calls Bob and Bob's phone rings, Bob's phone could send periodically status messages to Alice, telling her that his phone rings.

If no status message is received by Alice, which indicate that the phone rang, the status is however unclear, but it could be assumed that Bob is offline.

During a call both could send keep alive messages to make clear that no one has gone offline (due to a bad mobil connection eg).

Those status messages could also be applied to the "hung up" action.

Or let's assume Alice and Bob are in a call and Charlie calls one of them. Then Charlie could be notified that Alice and Bob are currently not available, while Alice or Bob hears the knock sound that someone else is calling.

That's of course a very simple and naive idea; if you can think of an better solution I would very much welcome that of course :-)

**Comment by mario** [comment]
We already know when someone goes offline - e.g. if the caller goes offline, your phone will stop ringing.

But we dn't really know when to start an "acoustic feedback" cause we don't really know if the other side is ringing OR if the other side hang up. So the issue really is the API.

**Comment by cottoa00** [comment]
Sorry if this is a bit off topic but trying to determine what is supposed to happen when I call a Talk user on an iPhone... is the "notification" audible (an iPhone ring), or just a screen display... a message that can float to the lock screen or just a "notification" only visible within the Talk app itself?
I have NC 14.0.7, Talk 4.0.3, and Notifications 2.2.1 and only seem to get the notification icon with the app on the iPhone... I guess I just need to know what is supposed to happen before I go chasing down some phantom functionality ;-)

**Comment by Ivansss** [comment]
Hi @cottoa00,
A new version (3.3.0) of Nextcloud Talk iOS app was just released yesterday.
This version includes CallKit support. So from now on, you will see an incoming call view (like a normal phone call) when someone calls you. For group calls, we still show just a notification.

**Comment by cottoa00** [comment]
Thanks.. will give it a whirl. I'm in Costa Rica taling with my brother in the US trying to get off of WhatsApp... but the interface is so good from a "ring" standpoint. Fingers crossed.. Thank you for all the great work you guys are doing!

**Comment by cottoa00** [comment]
The new Talk 3.3.0 works!... Calls come thru very simila to WhatsApp... Thank you so much. Now at least I can lean on my family and friends to use Talk... will have to work on the Ticos ;-)

**Comment by ostasevych** [comment]
Do you foresee adding sound for inbound calls in the web version?

**Comment by nickvergessen** [comment]
Once browsers allow automatic playing of audio in the background without user interaction sure

**Comment by ostasevych** [comment]
> automatic playing of audio in the background

Well, movim.eu may do that: a special window pops-up with the melody.

![image](https://user-images.githubusercontent.com/5199030/83975633-6735e900-a8fd-11ea-8265-0115c3ff4272.png)
