### ISSUE TITLE
Case clash in sync client when uploading same image to different chat conversations 

### ISSUE THREAD

**Issue by ChildLearningClub** [nextcloud/spreed#10721]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Share photo from device to a chat conversation with someone in talk.
2. Open a separate chat conversation with someone else and share the same photo from device.

### Expected behaviour
A quick file name check could be run to find that the file or photo has already been shared within the talk folder, and then a pop-up could give the option to share that same file with two or more people or to create a separate share with different permissions.

### Actual behaviour
In my particular case with images, the first image shared had "original_filename.JPG" and the second, "original_filename.jpg". The name conflict was recognized by the server and automatically changed from .JPG to .jpg. This only really becomes an issue when using the Sync Client in Windows when a case clash is generated.

**Comment by nickvergessen** [comment]
Duplication resolution is nothing Talk can do or handles here. The files are uploaded to the normal WebDAV API and not sharing the same files but a copy can even be intended, so it's not easily possible to automate this.

Regarding the `.jpg` vs `.JPG` issue, that is also unrelated to Talk and needs either fixing in the server's WebDAV API or the Desktop client.
Feel free to report it at https://github.com/nextcloud/server

**Comment by ChildLearningClub** [comment]
Okay thank you @nickvergessen, I thought that might be the case, thank you for clarifying.
