### ISSUE TITLE
Message reactions: all emoji elements blank

### ISSUE THREAD

**Issue by pedropintosilva** [nextcloud/spreed#10722]
### How to use GitHub

![image](https://github.com/nextcloud/spreed/assets/65948705/0da21f38-29b3-44b2-812b-c1d20b5284f3)

---

## Steps to reproduce
1. log on 
2. Click in the add reaction button
3. See a empty white pill

Tried to refresh and refresh with shift + ctrl + R but got the same result 

## Versions

* Web browser : FF 115.3.1esr
* Talk version: 
* Operating System: openSUSE Leap 15.5

**Comment by pedropintosilva** [comment]
Tried also in a private window without login , same result

**Comment by pedropintosilva** [comment]
on Chrome/mium it works but not on Firefox

**Comment by nickvergessen** [comment]
Is this still happening?
I would assume it's a bug in your local setup. I use emojis on Firefox on a daily basis and it works totally find and I'm pretty sure that we would have many more reports if this was a general issue with Firefox and Talk
