### ISSUE TITLE
Improvements to screensharing presenter overlay

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#10732]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
We now have the nice presenter overlay when screensharing: https://github.com/nextcloud/spreed/pull/10669 based on the discussion at https://github.com/nextcloud/spreed/issues/4478
Possibly there is some more visually amazing stuff doable.

**Describe the solution you'd like**
Apple recently announced this as "presenter overlay". It is either available as a little circle of your video over the presentation, or as your full video view with the presentation inside it and behind you:

https://www.apple.com/jo/newsroom/2023/06/macos-sonoma-brings-new-capabilities-for-elevating-productivity-and-creativity/

https://github.com/nextcloud/spreed/assets/925062/f899e911-ad67-4bdd-81f9-5d12faefa0c4

**Small circle**
![image](https://github.com/nextcloud/spreed/assets/925062/27b8b559-041a-44d4-9a61-c2f77370dd24)
**Full video composite**
![](https://www.apple.com/v/macos/sonoma-preview/a/images/overview/video-conference/share_preview_startframe__fz9vau8gox26_large.jpg)

cc @karlitschek @AndyScherzinger @nickvergessen

**Comment by DorraJaouad** [comment]
The small circle can be placed only at the inner edge frame ( e.g, bottom and upper width is 1/4 of full width ), right ? If the user drags it and tries to put it in the middle, it will bounce to the closest point of that frame.

For development, we can use this package https://www.npmjs.com/package/vue3-draggable-resizable with disabling the resizable option ofc and we can also add some moving effect. Basic demo : https://draggable-resizable-vue3.netlify.app/docs/examples/no-props.html cc @Antreesy
