### ISSUE TITLE
Safari and Edge support 

### ISSUE THREAD

**Issue by schleyk** [nextcloud/spreed#1076]
Hi Nextclouders,

I’ve talked to my boss about the Nextcloud Talk solutions. We already use it for our internal purpose and we love it! 

We are looking forward to offer Nextcloud Talk to our customers as a secure video call solution. 
The only problem we have right now is that not every browser is supported. 
Our Costumers usually use the preinstalled Microsoft Edge Browser.

The customers are not satisfied with the alternative of using another Browser like Firefox or Chrome.
Is there an approximate time when further browsers are supported?

We are looking forward to enrol Nextcloud with talk for a bunch of costumers because we like the software very much. 

It thinks it would be a great idea to develop a Windows app like the „Skype for business web app “so the users aren’t limited on the browser they have got installed on their device.

**Comment by nickvergessen** [comment]
Safari and Edge support are on the todo: https://github.com/nextcloud/spreed/issues/687

But unluckily the Webrtc lib we were using is modfied too much already and was discontinued #1063 

So we will have to switch to something else which will cause quite a huge amount of work, but we are work towards/on it.
