### ISSUE TITLE
Mention chips in markdown headlines are cut off

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10765]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Post `# PSA @all` in a chat room (emojis in the room name help to show the problem)

![grafik](https://github.com/nextcloud/spreed/assets/213943/6a8bf991-fd0a-45c7-849c-d9802024cbba)

**Comment by DorraJaouad** [comment]
The size of `NcUserBubble` is set to default 20 for all tags . Should it be changed based on tag when processing the markdown in [`NcRichText`](https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcRichText/NcRichText.vue) ? ( cc @Antreesy )
![image](https://github.com/nextcloud/spreed/assets/84044328/53c57a24-a0a3-47cf-9d2e-dad622533892)

**Comment by Antreesy** [comment]
I got a little carried away
