### ISSUE TITLE
Incorrect character encoding in link header when inserting link into chat room

### ISSUE THREAD

**Issue by caww** [nextcloud/spreed#10798]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to spreed and add this link in the chat https://www.nalog.gov.ru/rn77/related_activities/ucfns/el_sign_getting/
here is example 
https://disk.yandex.ru/i/lXurL5sqAEf2hg

### Expected behaviour
Tell us what should happen
title of the link must recognized with right encoding like this:
<title>Порядок получения электронной подписи |  ФНС России  | 77 город Москва</title>

### Actual behaviour
Tell us what happens instead
but ATM its recognized like this
ÐÐ¾ÑÑÐ´Ð¾Ðº Ð¿Ð¾Ð»ÑÑÐµÐ½Ð¸Ñ ÑÐ»ÐµÐºÑÑÐ¾Ð½Ð½Ð¾Ð¹ Ð¿Ð¾Ð´Ð¿Ð¸ÑÐ¸ |  Ð¤ÐÐ¡ Ð Ð¾ÑÑÐ¸Ð¸  | 77 Ð³Ð¾ÑÐ¾Ð´ ÐÐ¾ÑÐºÐ²Ð°

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.2
**Operating system:** Windows/Ubuntu/...
Windows 10
**Browser name:** Firefox/Chrome/...
google chrome
**Browser version:** 85/96/...
117.0.5938.152
**Nextcloud version
27.1.3

**Comment by nickvergessen** [comment]
Works fine here on my test system:
![grafik](https://github.com/nextcloud/spreed/assets/213943/c9bc1651-9985-4ac5-8c2b-156b2ac47fdb)

So make sure to check your server that it has all the correct dependencies installed:
https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html#php-modules
