### ISSUE TITLE
Footer background color not look good

### ISSUE THREAD

**Issue by Honeshwar** [nextcloud/spreed#10795]
Assign me this task with hacktoberfest label

What i will do:
**Before edit**

![Calls, chat and video conferencing with Nextcloud Talk - Google Chrome 27-10-2023 12_39_45](https://github.com/nextcloud/spreed/assets/73346917/bf4fb7f5-46d3-475c-b492-aa2b7b4e5afb)

**After edit**

![Security in Nextcloud - Google Chrome 27-10-2023 12_37_07](https://github.com/nextcloud/spreed/assets/73346917/32905f76-8640-458b-96b6-d252428f2fd5)

Thank you ‎😃

**Comment by nickvergessen** [comment]
I'm not aware the website is available on github anymore.
