### ISSUE TITLE
Icon for promoting/demoting a moderator

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1080]
@nextcloud/designers 

Currently we use the edit-pencil for promotion.
I would prefer something like contact-icon with + and - or so.
Any suggestions/ideas, someone volunteering to make one?

**Comment by jancborchardt** [comment]
The pencil is an ok icon in this case because it gives _edit_ rights to the person. :)

**Comment by Ivansss** [comment]
@jancborchardt What about the icon for demotion?

**Comment by jancborchardt** [comment]
@Ivansss @nickvergessen to keep stuff simple and not have people need to learn a lot of separate icons, we should simply keep using the "edit" / pencil icon because you edit the state. Also, it will always have the text next to it, right?

**Comment by skjnldsv** [comment]
Though I guess we can also have a popovermenu with promote and demote in the menu, right @jancborchardt ?

**Comment by nickvergessen** [comment]
There is already a popover menu. It just misses an icon that describes what the actuon is doing.
But well seems to be not intended

**Comment by jancborchardt** [comment]
@nickvergessen as said, the edit icon is proper here.

If we have 2-3 places where we would use this same icon also for promote/demote or something, then it's something we can create. But having a specific icon for this generic action is more likely to result in confusion.
