### ISSUE TITLE
Still sending room id instead of room token

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#1083]
Tested for at least calls. Nextcloud 14 beta1 + git checkout of spreed app.

**Comment by nickvergessen** [comment]
Where?

**Comment by mario** [comment]
Push notifications of course.

**Comment by nickvergessen** [comment]
In which notification exactly?

Can you please make full bug reports?

**Comment by mario** [comment]
@nickvergessen I wanted to update the issue in full tomorrow when it's a working day and I had the time to do a complete test.

But just to answer you: one on one calls.

**Comment by mario** [comment]
I will of course, just for you, check this further later tonight.

**Comment by mario** [comment]
Mentions send a token while calls still send room id.

**Comment by mario** [comment]
(I don't show the invitations at all, so I didn't test this)
