### ISSUE TITLE
Youtube preview text decoding is wrong (at least for french)

### ISSUE THREAD

**Issue by guerby** [nextcloud/spreed#10842]
Hi,

Using nextcloud 27.1.2 (storage share from hetzner.de) nextcloud talk 17.1.2 PHP Version : 8.2, language french, when posting the following youtube URL in a call (safe to see, about using wood to provide heat, public servants) : 

https://www.youtube.com/watch?v=MnVpPAt53l0

We get garbled characters in the preview:

![Screenshot from 2023-11-06 21-09-07](https://github.com/nextcloud/spreed/assets/6659329/5bd9d747-57c9-4f4c-bf18-39d7e512a72e)

This happens with both firefox 119.0 and chrome  119.0.6045.105, french language too.

**Comment by nickvergessen** [comment]
Works fine here:
![grafik](https://github.com/nextcloud/spreed/assets/213943/8687426f-62ec-4024-8278-046d3e41ac86)

Sounds a bit like the `intl` php extension is missing from your server?

It's only in the recommended section of:
https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html

After installing it, the wrong strings might still be shown for some time as the info is cached (I think 1 hour)
