### ISSUE TITLE
Cannot upload image/file while still being able to chat

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#10851]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. go into a room
2. chat
3. try to upload an image

### Expected behaviour
Upload of image should work.

### Actual behaviour
Nothing. In console I see 401: 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>CSRF check not passed.</s:message>
</d:error>

- Happens on our c.nc.c 
- Already chatted with nickvergessen about it, no meaningful logs on server.
- session cookie looks 1:1 between heartbeat and 401/propfind

**Comment by SystemKeeper** [comment]
Had the same happen to me a few seconds ago. Every image I tried to upload failed with 401, while everything else worked fine. The cookie was also the same for me. Only thing I noticed is that the RequestToken was different between working (sending a message) and non-working (uploading a file) requests.

After reloading the site everything worked fine again (and the request tokens were the same!)

**Comment by SystemKeeper** [comment]
Wondering if it's because of this commit: https://github.com/nextcloud/spreed/commit/86c83bfb88c8f6350375e2abe5b793c540ac9568 Because now the `requestToken` will be added to the client only once when the page loads.

So while I see at the console that the requestToken changed:
```
OC.requestToken changed PAsy5....
```

And is used by every request I am doing (e.g. sending a message, heartbeat, etc), for file upload it's still the old one:

```
Requesttoken: 9mFpHT0tQz ...
```
