### ISSUE TITLE
Error: Duplicate section id found: basic-info. Settings navigation sections must have unique section ids.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10858]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the conversation settings
2. Open the browser console
3. Close the conversation settings

### Expected behaviour
🏜️ 

### Actual behaviour
🔴 
![grafik](https://github.com/nextcloud/spreed/assets/213943/3dfdf24c-f8a8-40ac-bc2d-a7306379c707)

## Talk app

**Talk app version:** main

**Comment by ShGKme** [comment]
This is `@nextcloud/vue` issue

**Comment by nickvergessen** [comment]
Resolved by latest vue lib update
