### ISSUE TITLE
Feature request: Allow disabling "Talk updates ✅" default conversation

### ISSUE THREAD

**Issue by tristan-cottam** [nextcloud/spreed#10868]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Nextcloud Talk automatically adds the "Talk updates ✅" conversation for all new users. However, beyond possibly being considered irrelevant, it also means people who choose another language than English will see a conversation in a language they might not understand. 

**Describe the solution you'd like**
An option to disable the default "Talk updates ✅" conversation.

**Comment by SystemKeeper** [comment]
See the changelog parameter at https://nextcloud-talk.readthedocs.io/en/latest/settings/#app-configuration

**Comment by nickvergessen** [comment]
>However, beyond possibly being considered irrelevant

...

> it also means people who choose another language than English will see a conversation in a language they might not understand.

The changelog is translated and will be posted in the language of the user (each user has their own chat with these lines)


---

But as per above link there is an appconfig available if you still think it's important to not let people know in a short format what they can now do with the software.
