### ISSUE TITLE
Link to directly join to Call

### ISSUE THREAD

**Issue by g-nardiello** [nextcloud/spreed#10867]
I need to send invitations to meeting to external user, including invitations to talk videocall.

Problem: if I send the generated link to new guests, who didn't used nextcloud before, they see the chat but not opens the video call, as they not recognize button.

Solution: generate a link that automatically opens the video call, allowing users to join and ignore the chat. This link could be symply enriched by a query parameter. A settings could be included into talk settings to allow generate standard or new link type by default.

Alternative: Create a different type of group chat, prioritize the call instead of chat. Allow to select which type of group to create by settings (e.g. depending on where it is created) or into group creation form. Defaults to call group into calendar and appointments.

I don't know if there are other alternatives or existing solution. Thank you

I searched about a different solution before write the Issue, but have found nothing. I'm new to this community, hope I does the request correctly.

**Comment by SystemKeeper** [comment]
I think this should be possible with https://github.com/nextcloud/spreed/pull/10724 in talk 18

**Comment by g-nardiello** [comment]
Thank you, it seems what I need. As mentioned I think it will be allowed and could be forced with links as `call/{token}#direct-call`! It is already in [v18.0.0-beta.1](https://github.com/nextcloud/spreed/milestone/189).

Will be available on Talk 18 and Nextcloud 28.
