### ISSUE TITLE
File caption is lost if files are removed

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10872]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Drag a file into the chat
2. Write a caption
3. Remove that file from the preview
4. Send

### Expected behaviour
Either a normal message should be send (without a file), sending should be forbidden, or the caption should be preserved.

### Actual behaviour

https://github.com/nextcloud/spreed/assets/1580193/aad62b65-f906-41c7-9720-fdca73b3f3fb

## Talk app

**Talk app version:** 18 Beta 2 on c.nc.c

**Comment by DorraJaouad** [comment]
Do we proceed with disabling the button until a file is added or we can use the dialog to also send simple text messages ? 
cc @Antreesy

**Comment by nickvergessen** [comment]
> or we can use the dialog to also send simple text messages

This, because if you first type text and then drop/add a file the normal input text is moved into the modal, so you should still be able to send what you typed.
