### ISSUE TITLE
"+" button for creating rooms instead of three-dot menu

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/spreed#10878]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Since Talk 17 or so, if I want to create a new room, I have to click the three-dot button, which is not where I would look for such an important action:
![Bildschirmfoto vom 2023-11-13 15-56-23](https://github.com/nextcloud/spreed/assets/28591861/dcdfd1a1-56fb-4be4-9d5e-a8f502ea7861)
In other places, we have a big "New message" or "New event" buttons, and here it is hidden behind an icon that is normally used to hide options which are not needed most of the time. Bad UX in my opinion.

**Describe the solution you'd like**
Bring back the "+" button as it was used until Talk 16. When you click it, you get the two options "create new room" and "join exisiting rooms", just as it is now.
![call-in-action](https://github.com/nextcloud/spreed/assets/28591861/d1129aa9-3447-4e35-bb04-d5e3dcbdbe0e)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by SystemKeeper** [comment]
You can also just enter the name of the conversation you want to create and then you see a "Create conversation" option:

<img width="297" alt="image" src="https://github.com/nextcloud/spreed/assets/1580193/97eb8d9c-daf0-48f3-ac9a-b948d36fd77e">

**Comment by nickvergessen** [comment]
SHould we also use the speechbubble+plus there? cc @Antreesy

**Comment by Antreesy** [comment]
![image](https://github.com/nextcloud/spreed/assets/93392545/a9636e72-f598-41d8-9d69-67ed2d6e2b23)

It kind of aligned with all included actions, so I have nothing against this change.
cc @nextcloud/designers for the opinion

**Comment by szaimen** [comment]
> ![image](https://user-images.githubusercontent.com/93392545/282761879-a9636e72-f598-41d8-9d69-67ed2d6e2b23.png)
> 
> It kind of aligned with all included actions, so I have nothing against this change. cc @nextcloud/designers for the opinion

looks good 👍
