### ISSUE TITLE
File drop is not possible when file modal is open

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10883]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Add a file to share -> Dialog opens
2. Try to add a second file by drag'n'drop

### Expected behaviour
Should work

### Actual behaviour

https://github.com/nextcloud/spreed/assets/1580193/cd4731c0-5282-495e-bcb2-a4c8340786cd

**Comment by nickvergessen** [comment]
Aparently this never worked, so moving to enhancement
