### ISSUE TITLE
Changelog bot icon is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10885]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Expected behaviour (stable27)
![grafik](https://github.com/nextcloud/spreed/assets/213943/cca16238-cc95-444a-9bc9-da638b1308d2)

### Actual behaviour (main)
![grafik](https://github.com/nextcloud/spreed/assets/213943/61781129-6377-4a66-8d45-6e1d51983132)

Regression from https://github.com/nextcloud/spreed/pull/10602 mostlikely?
cc @Antreesy

**Comment by Antreesy** [comment]
Styles for changelog icon are adjusted in ConversationIcon component, should do the trick here as well:

https://github.com/nextcloud/spreed/blob/2111c38ef12c7ebf9bc792c9a787d55aeeb3ef10/src/components/ConversationIcon.vue#L248-L250
