### ISSUE TITLE
"Unread mentions" differ between filter and unread button

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#10882]
Unread mention button is shown when we have a room with "unreadMention" set
https://github.com/nextcloud/spreed/blob/737456361b3461299f7828f7aa01ef2263b72c97/src/components/LeftSidebar/LeftSidebar.vue#L161-L166

https://github.com/nextcloud/spreed/blob/737456361b3461299f7828f7aa01ef2263b72c97/src/components/LeftSidebar/LeftSidebar.vue#L871

When we filter for "Unread mentions" in contrast we also take into account unread messages from 1:1 rooms:
https://github.com/nextcloud/spreed/blob/737456361b3461299f7828f7aa01ef2263b72c97/src/utils/conversation.js#L40-L45

Question is, should we align the handling of both?

**Comment by nickvergessen** [comment]
I think both should include unread 1-1s
