### ISSUE TITLE
Before final: Remove toast about session inactivity

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10886]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

It's confusing for endusers:
![grafik](https://github.com/nextcloud/spreed/assets/213943/be4b1bdd-e3e6-43b5-8d6a-0ba4cb1daefc)

**Comment by Antreesy** [comment]
Re-open until backport is merged to stable28
