### ISSUE TITLE
Confusing prominent buttons on poll dialogue

### ISSUE THREAD

**Issue by blizzz** [nextcloud/spreed#10893]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
0. Have a theme with warm colors
0. Have a poll
1. Vote on that poll
3. Close the dialog by visual style, not reading

### Expected behaviour

I shall not be confused with an destructive action i cannot undo.

### Actual behaviour

![vote actions buttons](https://github.com/nextcloud/spreed/assets/2184312/12dbb41d-79f0-4d00-9eac-b5afa33e432e)

When I am about to sumbit my poll the primary color and the big red end button are very similar.  But because the submit button is disabled before I select the option, I see the change and survive this step.

![not close poll](https://github.com/nextcloud/spreed/assets/2184312/c43c88d7-6bb7-460c-ab70-ef2b940aafd6)

Then, I read the results and want to close the dialogue, so i click on the lower right button, expecting close. While I do not expect to be able to close the poll (I did not start, but am moderator), I also would expect a close button there, rather an end one.

Eventually, I cannot undo ending the poll.

While you can argue it is my fault to have an orange primary color, the styling, positioning and incorrectability of my action may be considered nevertheless.

## Talk app

**Talk app version:** 18.0.0-beta2

## Browser

**Browser name:** Firefox

**Browser version:** 119.0.1

</details>

## Server configuration

**Nextcloud Version:** 28.0.0 beta 2

**Comment by nickvergessen** [comment]
I guess that is a general problem with theming atm.

But yeah gets more complicated when the buttons are next too each other.

**Comment by DorraJaouad** [comment]
cc @nextcloud/designers 
Option1: Move "End Poll" to a 3-dot menu like it is done in Media Settings
![image](https://github.com/nextcloud/spreed/assets/84044328/41ef951b-601e-48b9-8bfb-518fd8b83a69)

Option2 : Change the button type to tertiary with no background 

Option3: Move both buttons in a menu-button like this (bottom right)
![image](https://github.com/nextcloud/spreed/assets/84044328/4cb0c300-c741-4db3-ac95-6eedd3119e51)

IMO, I prefer the 3rd option as it leaves a room for scalability and also doesn't emphasize any action that causes confusion in some way. Beyond this issue, I would like to bring these points 
* Share results automatically after closing the poll should be an option 
* "Private Poll" means "keep responses anonymous" (rewording) 
* At least Moderator/Poll creator should see who voted when the poll is open (when it is not anonymous ofc) 
* Option to export results after Poll is closed ( already mentioned in a discussion)

If they are valid, I will create a new issue.

**Comment by nickvergessen** [comment]
> Option1: Move "End Poll" to a 3-dot menu like it is done in Media Settings

This sounds like the best option from the things still doable atm

**Comment by DorraJaouad** [comment]
> This sounds like the best option from the things still doable atm

The menu button is also doable ( NcActions )

**Comment by nickvergessen** [comment]
yeah but I don't want the button to submit the poll to be that hidden.

**Comment by marcoambrosini** [comment]
I think that this is us being too permissive with themes. All "error" buttons are going to look like primary with such theming colors. I don't think that hiding all of them is a workable solution. 

cc @nextcloud/designers

**Comment by DorraJaouad** [comment]
> I think that this is us being too permissive with themes. All "error" buttons are going to look like primary with such theming colors. I don't think that hiding all of them is a workable solution.
> 
> cc @nextcloud/designers

We can also use the same technique as in Call button ( showing a default button text and clicking brings the menu) 
![image](https://github.com/nextcloud/spreed/assets/84044328/fdc76933-bef7-431f-b337-42a164464fff)

**Comment by szaimen** [comment]
I think the `Change your vote` and the `Submit Vote` should be clearly visible. However I would indeed hide the `End Poll` button in a 3-dot menu...
