### ISSUE TITLE
Can't Share Screen on LibreWolf MacOS Sonoma 14.1.1

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/spreed#10892]
## Steps to reproduce
1. Install [LibreWolf](https://librewolf.net/) browser
2. Start meeting
3. Share Screen

### Expected behaviour
When user wants to share screen native MacOS permission popup appears everytime even user already gave permission. Ignoring popup or giving permission again not solving problem to share screen.

### Actual behaviour
User should able share screen

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS Sonoma 14.1.1

**Browser name:** LibreWolf

**Browser version:** 119.0.1-1

**Comment by SystemKeeper** [comment]
> When user wants to share screen native MacOS permission popup appears everytime even user already gave permission.

Not reproducible for me on Sonoma with LIbreWolf. Granted MacOS permission on the first screenshare and was not asked again by the OS (Make sure LibreWolf was restarted).
Even if it would be the case, I don't think we can do anything against it, that's between browser and OS.

**Comment by SystemKeeper** [comment]
After talking to @alperozturk96 we realized that we used different installation methods, if you use the provided .dmg file to install it, screensharing works fine as expected. If you use homebrew it has the problem mentioned above. 
So I don't see a way for us to work around that tbh.
