### ISSUE TITLE
Autocompletion shows internal user id instead of avatar + display name 

### ISSUE THREAD

**Issue by blizzz** [nextcloud/spreed#10895]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Use autocompletion to mention a user
2. hit enter

### Expected behaviour

I see a highlighted span containing the avatar and the display name of the mentioned user.

### Actual behaviour

I see `@userid` instead.

No errors in the browser console.

## Talk app

**Talk app version:** 18.0.0-beta2

## Browser

**Browser name:** Firefox

**Browser version:** 119.0.1

</details>

## Server configuration

**Nextcloud Version:** 28.0.0 beta 2

**Comment by nickvergessen** [comment]
Also happens for comments:
![grafik](https://github.com/nextcloud/spreed/assets/213943/5cc49922-3a86-4856-82d0-d7b0f2c22aed)

But works on the docs:
https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable

So not sure where this goes wrong, but should be in the lib I guess?

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/spreed/assets/1580193/a58b46f8-4718-477f-9081-70297e0d593f

What am I missing? 🤔

**Comment by blizzz** [comment]
@SystemKeeper you should not see `@joas` but **👤 Joas Lastname** in the text input box after confirming him.

**Comment by SystemKeeper** [comment]
> @SystemKeeper you should not see `@joas` but **👤 Joas Lastname** in the text input box after confirming him.

🤦  That makes sense, thank you!

**Comment by blizzz** [comment]
For the record how it worked in 27:

[Screencast_20231114_134030.webm](https://github.com/nextcloud/spreed/assets/2184312/e5a532d3-5e39-4118-9df4-f68305ce24b1)

**Comment by Antreesy** [comment]
Found it, comes with vue-lib version bump: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4386#issuecomment-1759250020

cc @susnux

**Comment by blizzz** [comment]
Still an issue on RC2

**Comment by nickvergessen** [comment]
> Still an issue on RC2

Yeah, vue library 8.3 was only released after yesterdays Talk release

**Comment by nickvergessen** [comment]
Ah, nevermind the linked vue PR is the breaking one, not the fixing one.

Was it actually reported upstream @Antreesy ?

**Comment by Antreesy** [comment]
Link usptream issue: https://github.com/nextcloud-libraries/nextcloud-vue/issues/4901
