### ISSUE TITLE
Create meeting inside a group chat

### ISSUE THREAD

**Issue by mecpcanada** [nextcloud/spreed#10901]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
creating a meeting for a group chat or its team is more complicated than it should be, it's either creating one in the calendar and then inviting all members one by one, 

**Describe the solution you'd like**
we should be able to schedule meetings for a team if there is a group chat or conversation with them that uses the same chat for the call rather than creating new rooms for it each time it also speeds it up 

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/spreed/issues/6292
