### ISSUE TITLE
Does anyone know how to establish a connection using HTTP instead of HTTPS?

### ISSUE THREAD

**Issue by theBig-brother** [nextcloud/spreed#10906]
Here, only HTTPS can be used to establish communication. I want to use HTTP instead; how can I do that?

![screenshot20231115 (1)](https://github.com/nextcloud/spreed/assets/111228176/f4c29214-8abb-435c-98bc-447cc886de94)

**Comment by nickvergessen** [comment]
Browsers only allow to access the camera and microphone using HTTPS or localhost.
So Talk does not work without HTTPS

**Comment by theBig-brother** [comment]
I know,so how to change PHP code
