### ISSUE TITLE
Does anyone know how to change PHP code to establish a connection using HTTP instead of HTTPS? 

### ISSUE THREAD

**Issue by theBig-brother** [nextcloud/spreed#10911]
I wonder if i can change the code to get it.
![283005118-f4c29214-8abb-435c-98bc-447cc886de94](https://github.com/nextcloud/spreed/assets/111228176/e67a624f-d4ad-48f8-af01-3fe1b0bc06e3)

**Comment by nickvergessen** [comment]
It's not possible, the browsers do not allow it.
It's not about PHP, it's not about the code from this app. You would need to modify Firefox, Safari, Chrome or whatever you use
