### ISSUE TITLE
fullscreen + `esc` = unable to access chat list / left sidebar

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#10928]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Summary
When in fullscreen mode, if the user hits `esc`, then the browser window retracts to it's windowed state from fullscreen, however the chat list (left sidebar) remains hidden.

The sidebar can be re-enabled with `f` however this is not user-friendly or discoverable.

![Peek 2023-11-17 11-06](https://github.com/nextcloud/spreed/assets/7018928/ca9f9e23-4a04-44c1-9ba0-40ffa70b5fce)

Also, note the lack of button to enable/disable the left sidebar/navigation pane:
![Peek 2023-11-17 11-19](https://github.com/nextcloud/spreed/assets/7018928/da04da4e-59e5-4fff-91c0-f46df1e00df9)

## Steps to reproduce
1. in a Talk chat room, go to full screen mode (hit `f` or user interface button)
2. in fullscreen mode now, hit `esc` on the keyboard

### Expected behaviour
once `esc` is pressed, the browser window becomes windowed again, i.e. not full screen, AND the Talk interface reverts to showing the left sidebar

### Actual behaviour
once `esc` is pressed, the browser window becomes windowed again, i.e. not full screen, the Talk interface reverts but does not show the left sidebar

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
18.0.0-beta.3

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
Linux / openSUSE Tumbleweed

**Browser name:** Firefox/Chrome/...
Firefox 119.0.1
Chromium 119.0.6045.123

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

tech-preview on 23-11-17
- Nextcloud Server version 28.0.0 beta 4
- Nextcloud Talk version 18.0.0-beta.3

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
cc @Antreesy
