### ISSUE TITLE
"Create new conversation" only shows up if there is no match for existing rooms

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#10926]
Not sure if it is a bug or a feature request. 

The "Create new conversation" option only shows up if there are no results in the conversations search:

![image](https://github.com/nextcloud/spreed/assets/1589737/62a5a30c-67f8-4b67-a784-a6533f215cc1)

But after the room "foo bar" from the example above was created there are legitimate reasons that the user want to create a room "foo" later. But now the "create new conversation" option is not shown:

![image](https://github.com/nextcloud/spreed/assets/1589737/2c18340c-977f-414b-8449-8de0088f1ad2)

I think the option to create a new room should always be present. The assumption that you only want to create a new room if there is no match is to strong in my opinion and doesn't match real use cases.

**Comment by nickvergessen** [comment]
you can still create a room with the speechbubble+plus icon when there is no search. But yeah whne you search already it's much easier.
I think this short cut way was added and removed already X times....
