### ISSUE TITLE
Users disconnect from calls every ~25 minutes

### ISSUE THREAD

**Issue by h0lley** [nextcloud/spreed#10930]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call and have at least two participants join
2. Wait 25 minutes
3. Notice that you disconnect. This message appears:
```
The conversation does not exist
Join a conversation or start a new one!
```
4. However, the conversation does in fact still exist and can be re-joined.

### Expected behaviour
Being able to have a conversation for 25+ minutes without disconnecting.

### Actual behaviour
Every 25 minutes, users disconnect from the call. It appears to be individual for each user; when one user joined the call one minute later than another, then they will also disconnect one minute later.

## Talk app

**Talk app version:** 17.1.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no (stun.nextcloud.com:443)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu, Windows

**Browser name:** Vivaldi, Chrome

**Browser version:** Vivaldi 6.4.3160.42 (Stable channel) stable (64-bit) 

### Browser log
Embedding didn't work properly for some reason, so here's a file.
[browser.log](https://github.com/nextcloud/spreed/files/13398707/browser.log)

## Server configuration

**Operating system**: Debian

**Web server:** nginx

**Database:** MariaDB
```
Type: mysql
Version: 11.1.2
Size: 39,9 MB
```

**PHP version:**
```
Version: 8.2.12
Memory limit: 512 MB
Max execution time: 3600
Upload max size: 512 MB
Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, sysvsem, zip, Zend OPcache
```

**Nextcloud Version:** 27.1.3

**List of activated apps:**

<details>

```
  - activity: 2.19.0
  - calendar: 4.5.3
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.1
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - forms: 3.3.1
  - groupfolders: 15.3.1
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - polls: 5.4.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - side_menu: 3.11.2
  - spreed: 17.1.2
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.crater.company",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "custom",
        "enforce_theme": "dark",
        "skeletondirectory": ".\/new-user-default-files",
        "knowledgebaseenabled": false,
        "session_relaxed_expiry": true,
        "simpleSignUpLink.shown": false,
        "default_phone_region": "DE",
        "default_locale": "de_DE",
        "debug": false,
        "maintenance": false,
        "app_install_overwrite": [
            "talk_matterbridge"
        ],
        "loglevel": 0
    }
}

```
</details>

### Server log (data/nextcloud.log)
It's 64 MB, so this is only the tail. But this log has been taken relatively shortly after a conversation in Talk disconnected.

[nextcloud.log](https://github.com/nextcloud/spreed/files/13398700/nextcloud.log)

**Comment by nickvergessen** [comment]
This is very unlikely caused by the software as we regularly have calls taking much longer.
So I guess it's better to go to the forum and get help with your setup:  https://help.nextcloud.com/c/support/talk/52

**Comment by h0lley** [comment]
yeah, of course not every issue can be reconstructed on every system - doesn't necessarily mean it's not related to the source.

also before posting this issue, I've spent like 15 minutes looking for something like a support board without success. should probably be linked in this repo's readme.md and/or contributing.md.

thanks for the pointer.
