### ISSUE TITLE
Can no longer click "outside" to close modals

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10958]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Happens for

1. Talk settings
2. Conversation settings
3. Selecting a file from Nextcloud (so the file picker)
4. Selecting  conversation avatar from Nextcloud

Still works for

1. Participants permissions editor
2. Conversation creation
3. Open conversation list
4. Forwarding a message
5. Creating a poll

**Comment by Antreesy** [comment]
Upstreamed for component in general and NcAppSettingsDialog: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5062
