### ISSUE TITLE
Option for notification levels

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1099]
The levels should be:
* Always (default for one2one rooms)
* On mention (default for other rooms?)
* Never

Maybe even "Temporary mute" (1h, 8h, 24h, 1 week seem to be most common)

Basically a follow up to #875

**Comment by doc-jay** [comment]
would this enhancement allow users to be alerted to when there is a new chat from someone that hasn't been read yet?  Such as to just draw their attention to the chat window per say?

**Comment by nickvergessen** [comment]
Yes, the HTML notifications of the browser will also be triggered by this.

**Comment by barthel-eu** [comment]
I don't understand and read through a lot of messages on this, thought from the content it to be solved. But for me it is not. If I message someone directly inside Nextcloud Talk app on IOS, the recipient on an IOS iPhone does **_not_** see that a message was sent. So if not opening the app by chance, the message will not be read. All notification in settings are ON.
It is known, that adding the username with "at", like @username - the message reception **_does_** show. It should have the same behavior if a message is sent to that user without addressing it "additionally"?
Until that is, I won't use Talk, as this is a very basic necessity for the user to see incoming message without manual monitoring. Works with iMessage, WhatsApp, Skype, Threema, you name it. Just not in Talk :-(
It seems @nickvergessen has the understanding of the topic, help finding if this is still an open issue and where would be **_very much_** appreciated.
