### ISSUE TITLE
Standalone desktop app

### ISSUE THREAD

**Issue by ronnicek** [nextcloud/spreed#1100]
Hi,

just want to say, that I like where Nextcloud Talk is going! Lot of new functionalities and great features!

I wanna ask, if there is some plan to have a standalone desktop application for Talk? Because for parents etc. its quite hard to use web browser.. I know everybody is going to hate me because I say this, but I think even Electron app could do the job :). Of course native is native, but as "workaround" it should do the job and hopefully not eat whole computer memory :-D.

I found issue #597 about that, but no info / reply about desktop client.

**Comment by ERnsTL** [comment]
I have also previously requested this feature and want to re-affirm that this would be great to have.

**Comment by john-2000** [comment]
I have raised a bounty for this topic on Bountysource:

[https://www.bountysource.com/issues/61616435-standalone-desktop-app](https://www.bountysource.com/issues/61616435-standalone-desktop-app)

to allow most users to use this it would be good if the client is cross platform desktop

the alternative would be for a dev to build the ability to link up to a cross platform and cross messaging client (such as Franz or similar) - I would prefer the Nextcloud talk desktop client though

I would prefer the former but would be more than happy with a fully working latter...!

**Comment by wouterVE** [comment]
I also want to affirm that this would be a greate feature! Be it a standalone Nextcloud talk programm or an api so that other IM programs  (eg pidgin through plugins) are able to connect to your cloud instance. 
kr 
wouter

**Comment by MacLemon** [comment]
A native Chat application for macOS would be a very welcome addition to the Nextcloud ecosphere. Having a browser open for chat is a terrible user experience and it mixes 100s of tabs for everything else with communication.
My users certainly insist on native applications and refuse to use web stuff because web stuff is very inefficient to use.

Alternatively one could maybe integrate Nextcloud Talk with Matrix and use a native Matrix client instead. (Like Riot or Seaglass, etc.)

**Comment by c0urier** [comment]
You could try to use: https://rambox.pro/#ce

And add a custom service, seem to work fine - Set the custom url to https://your.cloud/apps/spreed/.

I'm not affiliated with rambox, I was just looking for a client too, and found it to be rather useful.

**Comment by john-2000** [comment]
@c0urier can you confirm that you had all the functions in question? 

I still think a stand alone client or api would be very helpful in getting higher user adoption, I have only a few users but there remains reluctance to use it even in a "stripped down webbrowser window"

**Comment by nickvergessen** [comment]
We might be looking into an Electron based App. That should do as a first version.

**Comment by lachmanfrantisek** [comment]
Since [Purism partners with Nextcloud](https://nextcloud.com/blog/nextcloud-partners-with-purism-to-provide-a-secure-open-source-and-privacy-focused-mobile-device/), is there some plan to support also this platform? I am just thinking about that phone and want to be sure this will work.

thanks

(I hope flatpak version will "just work" on it.)

**Comment by c0urier** [comment]
@john-2000 You are correct, but still easier to administer imo. Personally I'd prefer a standalone app anyday, but I also understand the time the devs have to put into it. I'll chip in on the bounty shortly, and recommend others to do the same.

**Comment by thigg** [comment]
I'd be happy if there would be an interface which messengers like pidgin could use, so I am not bound to use yet another client...

**Comment by ostasevych** [comment]
Another alternative might be addon or extension to Mozilla Thunderbird, as it has already the chat functionality inside of it.

**Comment by stratoss** [comment]
> You could try to use: https://rambox.pro/#ce
> 
> And add a custom service, seem to work fine - Set the custom url to https://your.cloud/apps/spreed/.
> 
> I'm not affiliated with rambox, I was just looking for a client too, and found it to be rather useful.

That just emulates a browser, didn't implement any of the functionalities in question.

**Comment by gerroon** [comment]
> You could try to use: https://rambox.pro/#ce
> 
> And add a custom service, seem to work fine - Set the custom url to https://your.cloud/apps/spreed/.
> 
> I'm not affiliated with rambox, I was just looking for a client too, and found it to be rather useful.

Interesting idea however, I see no notifications, also it does not remember the last open room. :( Better than a browser I guess

**Comment by ronnicek** [comment]
Not a best, but look on https://github.com/jiahaog/nativefier/blob/master/README.md

**Comment by szaimen** [comment]
Sry for interrupting but wouldn't be a progressive web app much more convenient, then an additional desktop app?

Btw: I think the same also applies to mobile view.

**Comment by thigg** [comment]
Whats meant by desktop app is only good system integration.
Mainly working notifications therefore.

Let me know, if notifications work on any of them reliably.

**Comment by stratoss** [comment]
> Mainly working notifications therefore.

Can't agree more! It is a basic functionality for any communications platform.

**Comment by szaimen** [comment]
PWA-Notifications will be able to work very reliably in the future with service workers: https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
Also these apps (and service workers) can be executed if the browser is closed. So that should not be the problem.

**Comment by cbacit** [comment]
This would be great if we had a windows / mac / linux app.

**Comment by thigg** [comment]
@szaimen you cannot integrate with other chat applications like pidgin however. It would be good, if any standard chat-protocol would be supported

**Comment by lachmanfrantisek** [comment]
What about implementing a [libpurple](https://developer.pidgin.im/wiki/WhatIsLibpurple) plugin?

It would bring support in apps like [pidgin](https://pidgin.im/) or [chatty](https://source.puri.sm/Librem5/chatty/).

**Comment by thigg** [comment]
Also there is #1838

**Comment by tiiiecherle** [comment]
Are there any news or developments on this? We would really like to use spreed/talk in production but the desktop app for mac is an essential requirement.

Has anyone managed to build natively, with catalyst or nativefier? Or any other way or integration for a mac desktop app.

Thanks to the nextcloud and spreed/talk team, amazing work ;)

I'll be thankful for any help.

**Comment by nickvergessen** [comment]
> Are there any news or developments on this? 

Not really.

**Comment by tiiiecherle** [comment]
Too bad. I think a lot of users would like a desktop client with all features and notifications.

Would be very nice to see that in the near future. Thanks a lot in advance.

**Comment by MacLemon** [comment]
A customer recently explicitly refused to replace their aging XMPP setup with Nextcloud Talk *because there was no native client* for macOS.

**Comment by jospoortvliet** [comment]
Hi all,

Can we please not have discussions about who wants what? This is a technical issue tracker. If you're a home user or contributor and want to help build an app, get involved. Otherwise, we have this on our todo and more requests of people that they want it or questions about when it is done are just distracting engineers from their work and making it take longer.

Unless there is interest from customers in such a desktop app, it will be developed when we've gone through our current (rather large) priority list.

> A customer recently explicitly refused to replace their aging XMPP setup with Nextcloud Talk because there was no native client for macOS.

That would be great - you can get started developing this app for your customer on https://nextcloud.com/developer - we're happy to open a sub repo for it in the Nextcloud repo.

**Comment by jospoortvliet** [comment]
Hey all!

So FDS has started to develop a desktop app! Some 👏 please.

You can see the work in progress here:
https://github.com/fds2610/NCT-Desktop

Please, offer help and support!

**Comment by jancborchardt** [comment]
> You could try to use: https://rambox.pro/#ce
> And add a custom service, seem to work fine - Set the custom url to https://your.cloud/apps/spreed/.

Something more well-integrated in a similar vein seems to be https://www.beeper.com/

They say:
> We built Beeper on [Matrix](https://matrix.org/), the open source federated messaging protocol. All of our 'bridges' which connect Beeper to other chat networks are open source, available on our [Gitlab](https://gitlab.com/beeper?sort=latest_activity_desc). You can run our backend stack on your own server or pay for our hosted option.  [Read more](https://medium.com/@ericmigi/the-universal-communication-bus-42dfb9a141ad)

**Comment by nickvergessen** [comment]
There is now a preview of the upcoming Talk Desktop client available:
https://github.com/nextcloud/talk-desktop
