### ISSUE TITLE
Taskbar/Dock Badge Application Notification / Counter

### ISSUE THREAD

**Issue by git529** [nextcloud/spreed#11022]
It would be great to have a notification counter or message indicator on the application counter of the web browser on the dock/taskbar similar to what other messaging apps have, like web.whatsapp.com for instance.

With chrome, one could "install" the web version of nextcloud talk as it were an actual app which one can pin to the taskbar/dock. Unfortunately if a message is received there is no indication on the app icon on the taskbar/dock, making it difficult for users to know if they have unread messages.

Here's a screenshot of what I am referring to. The WhatsApp icon with white background, is actually a web app installed on Chrome.

<img width="280" alt="image" src="https://github.com/nextcloud/spreed/assets/85685642/f6cbb528-02f7-443a-b142-f1c113e573b7">

**Comment by nickvergessen** [comment]
> With chrome, one could "install" the web version of nextcloud talk …

Or you install the official desktop client we develop:
https://github.com/nextcloud/talk-desktop

There the feature is tracked at https://github.com/nextcloud/talk-desktop/issues/391

**Comment by git529** [comment]
> Or you install the official desktop client we develop:
> https://github.com/nextcloud/talk-desktop

The desktop client does not support this type of badge app icon notifications either.
