### ISSUE TITLE
follow-up: slow and fast debounced methods are independent in getParticipants

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#11048]
`this.debounceSlowUpdateParticipants` and `this.debounceFastUpdateParticipants` seem to have a different context, so if both are requested, both will be executed

https://www.npmjs.com/package/debounce library has `clear()` and `flush()` methods, although it either cancel both requests or none of them, depending on usage.

This potentially could save 1+ request to server, depending on conditions

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/issues/11038#issuecomment-1833406298_

**Comment by DorraJaouad** [comment]
Or use flags ( e.g: isFetchedAlready). As fast comes after slow ( at least at the start of the call) :
When fast debounce starts excecuting, it puts isFetchedAlready = true. Then , the previously last scheduled slow debounce has to check the flag. If it is true, then skip.

**Comment by nickvergessen** [comment]
But we need to fetch in the future again. When would it be reset?
