### ISSUE TITLE
Only show out of office message when applicable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11059]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up OOO for upcoming (not current!) vacation 24th Dec to 8th Jan
2. Have DND user status (availability or manual)

### Expected behaviour
Nothing happens

### Actual behaviour
![Bildschirmfoto vom 2023-11-30 22-34-39](https://github.com/nextcloud/spreed/assets/213943/65373ce8-25fe-405f-933e-790d28fd66cb)

THe OOO api endpoint returns start and end time. We should check it before displaying.

## Talk app

**Talk app version:** main

**Comment by Antreesy** [comment]
Isn't it possible to expose status message id on that stage? Acting on 'dnd' here is firing cannons at sparrows

**Comment by nickvergessen** [comment]
> Isn't it possible to expose status message id on that stage?

Not really, due to bad architectural decisions back then the user status is one of the worst code/API we have atm with way too many layers and abstractions in-between (2 different models pass the data through 3 services and managers...).

It's not worth breaking at this stage of the server release (11 days left). So let's just add a check for the time before displaying the message from OOO
