### ISSUE TITLE
Restrict access to Talk app by Group

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#1105]
## Steps to reproduce
1. Install App
2.  Attempt to restrict access by Group

### Expected behaviour
No admin option to restrict access by Group

### Actual behaviour
All users of a Nextcloud 13.0.5 instance have access to the Talk app.

**Comment by nickvergessen** [comment]
Well the problem is it breaks public calls and makes the user experience bad.
See https://github.com/nextcloud/spreed/issues/201 for more details

I'm open to reopen the issue once the basic problem has been solved in the server repository. (group limited apps need to be loaded for other users too)

**Comment by pagaille** [comment]
I find this misleading too, especially for the Talk app which is widely used. My system hosts multiple groups that has nothing to do with each other and I don't want them to see each other inside the Talk app. Please consider reopening this issue.
