### ISSUE TITLE
Nextcloud Talk displays all contacts to all users and groups

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#1106]
## Steps to reproduce
1. Restrict access to Nextcloud Contacts by Group on 13.0.5
2. Login as a user with no group access to Contacts app.
3. Open Talk app.

### Expected behaviour
Access to contacts can be restricted for Talk app

### Actual behaviour
All Contacts on a system are directly accessible through Nextcloud Talk by all users and groups.

**Comment by nickvergessen** [comment]
The user list is not pulled from the contacts app, but from the sharing app.
You can use the feature to limit sharing to users in the same groups,
this setting is respected by the app. You can find it in:
Settings > Admin > Sharing >Restrict users to only share with users in their groups
