### ISSUE TITLE
Discussion: ActivityPub Integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#1107]
It would be very useful to integrate Nextcloud Talk with [ActivityPub](https://activitypub.rocks/).  From issue #965 

![activitypub-tutorial-image](https://user-images.githubusercontent.com/1787238/43660763-cbe07002-9714-11e8-83c5-1efabc43f8c0.png)

> Enter ActivityPub! ActivityPub is a decentralized social networking protocol based on the ActivityStreams 2.0 data format. ActivityPub is an official W3C recommended standard published by the W3C Social Web Working Group. It provides a client to server API for creating, updating and deleting content, as well as a federated server to server API for delivering notifications and subscribing to content.

ActivityPub integration would allow Nextcloud Talk to communicate with other federated chat / notification services, including:

    Mastodon & GNU Social
    Hubzilla
    Friendica
    Pleroma
    Socialhome

**Comment by nickvergessen** [comment]
I'm still not sure ActivityPub is the right thing for Talk. Talk is a real life chat which works while having a video call.

**Comment by sunjam** [comment]
Here is an example:

User invites others to chat on Talk app via federated ActivityPub notification that can reach Nextcloud users + notify them across Mastodon, Friendica, Hubzilla, etc.
Whether some users can or cannot join the call, ActivityPub federated comments on the notification can still show up within Nextcloud Talk chat.

**Comment by sunjam** [comment]
Thanks to the new [Nextcloud Social app](https://github.com/nextcloud/social/) there is progress towards supporting ActivityPub and Diaspora* protocols!

**Comment by nickvergessen** [comment]
> User invites others to chat on Talk app via federated ActivityPub notification that can reach Nextcloud users + notify them across Mastodon, Friendica, Hubzilla, etc.

That sounds okay but that is then job of activity/notifications, so closing it here

**Comment by Mannshoch** [comment]
I was searching for the same idea.
I'm searching for a solution to subscribe Mastodon and may also comment on Mastoton blogs. My idea was to use talk for this. 

So I would like to subscribe to Mastodon, have them apearing news in a chat group If I ge answers to my reaction they appear in talk.
Thinking it further, may I need a "Mastodon" group in talk and in there a sub-group per commented article.
