### ISSUE TITLE
Empty sidebar when you are not in any call

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#111]
When you are not in any call the sidebar is fully white.
Should display a message like "Start a call by searching for a user" or something like that.

**Comment by jancborchardt** [comment]
Good call. Maybe we should even open the select2 by default?

@nextcloud/designers @LukasReschke @rullzer @Ivansss @MorrisJobke what do you think?

**Comment by Ivansss** [comment]
I would go for showing a message.

**Comment by skjnldsv** [comment]
Same! I like the idea of focusing the select but we also need to think at mobile viewers :)

**Comment by jancborchardt** [comment]
On mobile, you want to tap even less. ;)

Basically opening the dropdown by default is like prefilling the left list with suggestions on who to call. It directly shows faces / avatars to prompt you to call instead of an empty white pane with instructions. It’s more engaging.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/187 for some more input
