### ISSUE TITLE
Quirks joining an open conversation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#11101]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Search for an open group conversation
2. Join it

### Expected behaviour

See participants

### Actual behaviour

See myself twice (once as guest) and nobody else. The list never finishes loading:

![Bildschirmfoto vom 2023-12-04 09-25-18](https://github.com/nextcloud/spreed/assets/1374172/8a59c90c-3a05-49db-bee1-a34e7213afff)
![Bildschirmfoto vom 2023-12-04 09-24-57](https://github.com/nextcloud/spreed/assets/1374172/3396b0b9-33e1-488c-b420-3f7a9980cecc)
![image](https://github.com/nextcloud/spreed/assets/1374172/ba7581ac-f5d6-48dd-b4f9-18b08997449b)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** 28.0.0 RC2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
The 2 logs in the console are from the vue library `¯\_(ツ)_/¯`

But should look into the double participants yeah
