### ISSUE TITLE
Sharing & unsharing doesn't turn conversation back into one-to-one/group call

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#1110]
Latest spreed, for sure this time :)

**Comment by nickvergessen** [comment]
One2one yes. It always goes back to a group room, by current design

**Comment by mario** [comment]
So unexpected. So not a bug?

**Comment by nickvergessen** [comment]
The thing is, if you created a new one2one room in the meantime we would need to merge them.

I guess in the end it was not a good decision to put the guest feature into the room type.
