### ISSUE TITLE
Does Nextcloud Talk (spreed) version 3.99.8 work on NC 13 ?

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/spreed#1111]
Does Nextcloud Talk (spreed) version 3.99.8 work on NC 13 or it requires NC 14 ?

**Comment by mr-bolle** [comment]
This version is only for NC 14 available https://apps.nextcloud.com/apps/spreed

**Comment by nickvergessen** [comment]
Yes its a prerelease for 14, because there are some incompatible changes required for nextcloud 14
