### ISSUE TITLE
webdav doesn't support upload progress since v5

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#11153]
Reference: https://github.com/perry-mitchell/webdav-client/blob/master/CHANGELOG.md#v500

**Comment by Antreesy** [comment]
cc @marcoambrosini @szaimen since we can't get the data to fill a progress bar, maybe replace it with a spinner on top of file preview?

**Comment by nickvergessen** [comment]
Or keep it with a wrong state until the lib fixed it. It's planned to fix it, right?

**Comment by nickvergessen** [comment]
> We can fake a progress bar filling up, until library will be ready for it, though

Okay, reading the linked tickets it seems it's not planned to fix this ever.
Then I guess a loading spinner or something else might be better

**Comment by Antreesy** [comment]
> It looks like it is possible to measure this

Library accepts and returns Stream.Readable / Stream.Writable, which are part of Node.js API, there is nothing we can use in browser. A note from Readme:

> NB: Streams are not available within the browser, so createReadStream and createWriteStream are just stubbed. Calling them will throw an exception.

**Comment by Antreesy** [comment]
Differences coming with a new lib `@nextcloud/upload` (https://github.com/nextcloud-libraries/nextcloud-upload):

Tool | 3RD webdav | NC upload
-- | -- | --
Requests | Fetch | Axios / XHR
Concurrent upload | Yes | Yes
Total upload time | Same | Same
Parallel upload | Yes (amount depends on fetch) | No (Yes, but max 3 small files without chunk)
Total upload time | Faster | Slower
Chunk upload | No | Yes (max 3 by lib atm)
Effect | File should be bufferized - high impact on browser for big files | File is read chunk by chunk
Upload progress | No | Yes (Only if loaded by chunks, shows total for queue)

So, it works fine in general, but:
- we have to sacrifice upload speed from parallel upload for small files
- we can't track upload progress for a single file, when loading several at once
- we may benefit in big files upload (RAM usage)
