### ISSUE TITLE
Message expiration, I just cant figure how to use/change it

### ISSUE THREAD

**Issue by JackDinn** [nextcloud/spreed#11154]
Sorry i must be going straight mad, but I just can not find how to change or switch on/off the Message expiration. **There is no dropdown option or anything like that that i can edit?**

I have attached a shot of one my test conversations, it says
Current message expiration 4 weeks

But i can’t change it and its driving me nuts that it should be so straight forward, why can’t I just see the answer?
Where do i set the Message expiration of a conversation?

![Screenshot_20231205_132456](https://github.com/nextcloud/spreed/assets/5557560/ed229208-dd3a-4ec0-a07e-9253096c88ae)

I have asked on the nextcloud forum but no response at all

I have tried using firefox & brave on my Linux client, Nextcloud is running on my truenas server. Everything is up to date.

**Comment by nickvergessen** [comment]
Maybe we can improve the wording a bit

**Comment by JackDinn** [comment]
Hmm, v odd. Iv just checked on my android phone app of "talk" and all my accounts are already marked as "moderator" and i also have the drop down box available.... so?
![Screenshot_20231207_175905_Talk](https://github.com/nextcloud/spreed/assets/5557560/c7c2975e-9398-4f47-8066-9c2067edca8b)

**Comment by nickvergessen** [comment]
Maybe the setting is broken in your version,
But you didn't fill out the form, so we can't see which version you are using, etc.

**Comment by JackDinn** [comment]
Version: TrueNAS-13.0-U6
Version [Nextcloud Hub 6] (27.1.4)
Talk 17.1.3

Host: greg-optiplex7050 Kernel: 6.6.3-1-MANJARO arch: x86_64 bits: 64
Desktop: KDE Plasma v: 5.27.9 Distro: Manjaro Linux

Hope these are correct and cover the info you are looking for.

**Comment by Antreesy** [comment]
Regression from https://github.com/nextcloud/spreed/pull/10491

**Comment by meonkeys** [comment]
I found no moderators listed for a couple old(?) 1:1 chats in the web UI. I was able to change the message expiration setting for those chats via the Android app.
