### ISSUE TITLE
TURN STUN Server with same port as nextcloud

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/spreed#1117]
Hi,

I am linking this problem to hope somebody can see this and it also has to to with nextcloud talk.

Is there in the future any chance that there is a ready to install TURN and STUN server included in the nextcloud talk app so that we can use them both on the same server?

I am trying to run nextcloud and other webpages and COTURN on the same port (443 tcp).

Coturn should run on port 443 both tcp and udp.

Is there any other way to accomplish this?

https://github.com/coturn/coturn/issues/259

**Comment by nickvergessen** [comment]
I think at the moment we don't have Turn TLS support, see #257 for more details.
