### ISSUE TITLE
Psalm Error: lib/Share/Helper/FilesMetadataCache.php:61:19: InvalidNullableReturnType

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11182]
See CI run https://github.com/nextcloud/spreed/actions/runs/7159931810/job/19493731802?pr=11181

> Error: lib/Share/Helper/FilesMetadataCache.php:61:19: InvalidNullableReturnType: The declared return type 'array{height: int, width: int}' for OCA\Talk\Share\Helper\FilesMetadataCache::getMetadataPhotosSizeForFileId is not nullable, but 'array{height: int, width: int}|null' contains null (see https://psalm.dev/144)

> Error: lib/Share/Helper/FilesMetadataCache.php:77:10: NullableReturnStatement: The declared return type 'array{height: int, width: int}' for OCA\Talk\Share\Helper\FilesMetadataCache::getMetadataPhotosSizeForFileId is not nullable, but the function returns 'array{height: int, width: int}|null' (see https://psalm.dev/139)

**Comment by nickvergessen** [comment]
Weird, at least programmatically it's not possible and I had fixed that in the PR.

**Comment by nickvergessen** [comment]
Psalm update from saturday makes the difference: https://github.com/nextcloud/spreed/pull/11169
CS Fixer was still green: https://github.com/nextcloud/spreed/pull/11168

Problem is psalm was not marked required. Fixed that now
