### ISSUE TITLE
Event listeners changed from 27 to 28

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11223]
27: https://github.com/nextcloud/spreed/blob/stable27/lib/Activity/Listener.php#L82-L107
vs.
28: https://github.com/nextcloud/spreed/blob/main/lib/AppInfo/Application.php#L184-L188

Notes from the chat:
- `stable27` has a join call listener with prio 0 and leave call with -100
- Starting from `stable28` its the same event and the listener is registered with prio -100
- Notifications go out with prio 0, before we the `in_call` property is set with prio -100

Idea: either
- Move setting the `in_call` property before the notifications
- Move the notifications behind it
- Split to two separate events

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/commit/cf0a10aad53df4af33860cb8c2f05df1a3bef116

So have to check if we can move notifications to the later block
