### ISSUE TITLE
🌐 Federated invitation handling 💌 - Overview

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11229]
- https://github.com/nextcloud/spreed/issues/11278
- https://github.com/nextcloud/spreed/issues/11279
- https://github.com/nextcloud/talk-ios/issues/1465
- https://github.com/nextcloud/talk-android/issues/3532

**Comment by mahibi** [comment]
would it make sense to change the subject and text of an invite, so it would fit better for limited space on mobiles?

Currently it looks like:
![Bildschirmfoto vom 2024-02-09 15-53-17 geaendert](https://github.com/nextcloud/spreed/assets/2932790/d4db1101-8fa4-41bf-a61b-3d39c6528222)

What about something like:
![Bildschirmfoto vom 2024-02-09 15-53-08 geaendert](https://github.com/nextcloud/spreed/assets/2932790/47105f3b-dead-44a2-8637-33212409136c)

**Comment by nickvergessen** [comment]
That was done in https://github.com/nextcloud/spreed/issues/11278#issuecomment-1923344622 already

**Comment by nickvergessen** [comment]
All marked closed, closing overview
