### ISSUE TITLE
🌐 Federated invitation handling 💌 - Frontend

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11279]
- Overview at https://github.com/nextcloud/spreed/issues/11229

---

- [x] Administration settings / Talk / Federations:
  - [x] Enable federations in Talk for this instance
  - [x] Allow users on this server to invite users to Talk conversations from all other servers / only trusted servers / only specific groups
- [x] Participants Tab:
  - [x] List remote users provided by `'core/autocomplete/get'` endpoint (should be there, if `settings/admin/sharing` is [configured](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/federated_cloud_sharing_configuration.html) and other servers provide their users
   - [x] Allow users on this server to invite users to Talk conversations from other servers (works if regex is matching `userid@domain`)
- [x] App level:
  - [x] invite - join conversation when invitation is accepted
    - [x] update participants list on moderator side from system message
  - [x] dismiss -verify that works as expected
  - [x] disinvite - verify that conversation is removed, participant is left and store is purged as for normal disinvite
  - [x] list - get all pending invitations from remore servers, and list them

**Comment by Antreesy** [comment]
Visual changes follow-ups (V2) moved to #11722
