### ISSUE TITLE
Search (filter) chat messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1127]
While a search is nice, filtering (jumping to the message) in the loaded history is a okay first version of this feature.

**Comment by jakobroehrl** [comment]
Hi, is there already a possibility to search in chats? 
If yes, I can't find it, thanks.

**Comment by nickvergessen** [comment]
No, it's not there yet

**Comment by bitdivine** [comment]
What is needed to make this happen?  Funding, developer time, design decisions?

**Comment by jakobroehrl** [comment]
This could be closed since search is solved by the united search feature?

**Comment by nickvergessen** [comment]
Right.

Ref #3493 and #4017
