### ISSUE TITLE
Notify about DND status when trying to resend call notification

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11282]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a user that is on DND
2. Send them the call notification again

### Expected behaviour
Either it works or I know it didn't

### Actual behaviour
Moderator is not notified that no push notification was send.

**Comment by nickvergessen** [comment]
Basically
https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Service/ParticipantService.php#L1174-L1194
should get the user status via
https://github.com/nextcloud/server/blob/f19645adab404a9c2642b42ec335bf2830dd8aa7/lib/public/UserStatus/IManager.php#L45
check if it's DND. If it is, throw an exception (InvalidArgumentException with code/message is good enough atm) and the controller should return an `return new DataResponse(['error' => 'status'], Http::STATUS_BAD_REQUEST);`

Afterwards clients/frontend should handle this error message with a dedicated user shown message

**Comment by skalidindi53** [comment]
This issue looks interesting, I will start working now! :)
