### ISSUE TITLE
Padding on confirmation when deleting all chat messages is missing

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11285]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

<img width="435" alt="image" src="https://github.com/nextcloud/spreed/assets/1580193/51b09675-384b-463a-b0c0-3ce953bedc09">

Looks a bit weird, I guess there should be a padding around the message at least?

Talk 18.0.1
Browser Chrome 120

Might be fixed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/4897 ?

**Comment by Antreesy** [comment]
Should be fixed
![image](https://github.com/nextcloud/spreed/assets/93392545/9e3166f6-b917-4851-9649-de1134e01c8b)
