### ISSUE TITLE
File upload from within a chat

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1129]
Subtasks:
* File picker
* Upload
* Displaying images inline

**Comment by daita** [comment]
Not sure what is your ideas, but could be nice to be able to upload within the file picker and also directly in the chat; and the file is stored in a folder specific to the app

**Comment by Ivansss** [comment]
That's the idea we have @daita :)
There will be 2 options when you press the '+' button.
- Share a file (that you already have in your NC)
- Upload a file (that will be stored in a specific folder and shared directly in the chat)

**Comment by Ozzie76** [comment]
Just did a pilot and this came up as one of the 2 missing features.

**Comment by jancborchardt** [comment]
Here’s wording suggestions for the + menu:

- :cloud: Add from Nextcloud
- :arrow_up: Upload from device

**Comment by jancborchardt** [comment]
Discussed about wording and storing files with @nickvergessen @Ivansss:

- Updated our wording decision in the comment at https://github.com/nextcloud/spreed/issues/1129#issuecomment-431566823
- Files are stored in a folder in the Files app root (of the person who uploaded the file) called "Talk files". (Compare to "WhatsApp images" on mobile.)
- When I upload a file in Talk and it gets added to my "Talk files" folder, the file will also get shared in the background with the other participants of the call read-only. Same for files from others, they get shared with me into the "Talk files" folder.

**Comment by JLueke** [comment]
I think storing all the files of all the chats in one folder gets messy really quick. Sure there is the extra option to share an existing file somewhere in you're structure, but why not combine it for "Upload from device".

1. Specify the destination where the file should be uploaded to
2. Upload file
3. Share file automatically with the chat

I think that otherwise it's just a user unfriendly detour to first upload a file in the files app and then return to the chat to share it.

**Comment by jancborchardt** [comment]
> Specify the destination where the file should be uploaded to

This step already makes it more complicated than "it just works". ;)

To be specific: The whole "saving it in a root folder" is just an addition we do because we happen to have Files. The important thing is that you can simply send a file in the conversation, either from your Nextcloud or your device. Where they are specifically stored is imolementation detail (they could also just be somewhere in a non-visible location – but different topic).

**Comment by manswiss** [comment]
And please add the avaibility of add file with drag&drop. I would use nextcloud&talk in our company, but without the feauture to add an local file with drag&drop to a group chat, i will have no chance. This is a basic requirement in our company.

**Comment by ldesgrange** [comment]
Hi, that would be a nice feature, looking at how my colleagues work, being able to copy/paste into the chat would be nice too (they tend to some content generated on the fly (like screenshots) and paste them directly without saving the file somewhere first).

**Comment by makayabou** [comment]
> I think storing all the files of all the chats in one folder gets messy really quick

is True . Then
>  Specify the destination where the file should be uploaded to

is good. But
> This step already makes it more complicated than "it just works". ;)

is True also!
In my opinion, what would be great is a folder Talk-files with a subfolder for each conversation.
And in it, we have files that have been uploaded from local storage, and also links to files stored in Nextcloud Files and shared in the conversation.
It's kind of linked to another issue I submitted : https://github.com/nextcloud/spreed/issues/1577 
What is common here is the need to centralize files linked to a room. In a working group, each conversation could be a project.

**Comment by Pedulla** [comment]
With the iminent demise of HangOut, this is a must have!

**Comment by DeeeeLAN** [comment]
> In my opinion, what would be great is a folder Talk-files with a subfolder for each conversation.
> And in it, we have files that have been uploaded from local storage, and also links to files stored in Nextcloud Files and shared in the conversation.

This is the obvious solution to me. It "just works", but also keeps the file upload system organized and easy to clean up.

**Comment by nickvergessen** [comment]
How to avoid conflicts with conversations with the same name? Renaming a conversation also renames the folder on the filesystem and therefor takes a lot of time all of a sudden?

**Comment by DeeeeLAN** [comment]
Why not just prevent conversations from having duplicate names in the first place? Allowing duplicate conversation names seems complicated for a user to deal with.

For renaming a conversation, renaming a folder shouldn’t take that long. I don’t know of any instance where it takes any observable time at all. Do you?

You could also kick it off as a background job on the server. By the time a user renamed it then goes back to the file view, it should be updated.

**Comment by nickvergessen** [comment]
> Why not just prevent conversations from having duplicate names in the first place? Allowing duplicate conversation names seems complicated for a user to deal with.

Well because of privacy reasons, I can create a conversation which is called `Fire DeeeeLAN` and you should not be able to check if it exists  by trying to create it. But in the end I could add you to the conversation, so if you created the conversation in the meantime you have it twice.

> For renaming a conversation, renaming a folder shouldn’t take that long. I don’t know of any instance where it takes any observable time at all. Do you?

Well in home-instances this might work. But not in conversations with hundreds of participants...

> You could also kick it off as a background job on the server. By the time a user renamed it then goes back to the file view, it should be updated.

Background jobs are ran every 5 minutes, not sure this matches the expectation.

**Comment by DeeeeLAN** [comment]
That makes sense. It sounds like each conversation needs a unique key attached to it that is not the name. Database management practices would definitely discourage using a non unique name as the key. The folder names would be harder to interpret, but the interface could hyperlink to it for easy locating.

**Comment by Bellusterra** [comment]
Would adding a date & time stamp onto the back of the conversation name work in this situation? That should at least allow for the same conversation being created twice. As @DeeeeLan mentioned having a link to just the conversation name. 
  Also like the idea of the having the folder hidden. With the photos and attachments still available in the Talk app. Under a tab like it’s done on things like rocket.chat. The uploads could also have a time stamp, if that would help with organizing them?

**Comment by nickvergessen** [comment]
Upload is explained in https://github.com/nextcloud/spreed/issues/1811#issuecomment-505096933

**Comment by fsxadmin** [comment]
we added this feature, and it goes into your home folder. im look for a dev to port it to the latest nextcloud!
https://github.com/fsxadmin/spreed

**Comment by nickvergessen** [comment]
Hi @fsxadmin any bigger reason why you forked it and added the feature there, instead of putting it in our code base?
I will invite you to our org and add you to the talk team, then you can send future features directly as a pull request. Also feel free to jump into our public conversation if you need help with anything: https://cloud.nextcloud.com/call/c7fz9qpr

**Comment by nickvergessen** [comment]
I tried to find the change in your repo, but I couldn't find anything. All your branches seem to have no additional commits. Do you mind to point out where the changes are? Otherwise it's hard for us to help porting it to the newest version

**Comment by fsxadmin** [comment]
@nickvergessen i will speak with my devs and see where the code is. We have had it working on 16 and 6 versions respectively and are still using it. It would be great to add to the main code base! More info soon.

**Comment by fsxadmin** [comment]
@nickvergessen 
https://github.com/omarusman/talk

**Comment by fsxadmin** [comment]
Let me know if the code is good enough; we can get Omar working on this project again if you find the code to be good. We also modified alerts for calls, created “temp “ messages that go away after a minute for privacy, and other features.

**Comment by nickvergessen** [comment]
I created a draft PR to just copy everything over:
https://github.com/nextcloud/spreed/pull/2852 

From there we can see more easily what is there and what we should pick to the newest version

**Comment by nickvergessen** [comment]
@fsxadmin I failed to be able to get that stuff extracted. It seems Omar added the code in a "initial" commit together with the Talk 5.0.2 code
If he is willing to work on it again and send a proper patch on the new Vue frontend, that would be highly appriciated.

**Comment by pc-robelbois** [comment]
We are not using Talk but another open source team chat solution. Mostly because this feature is missing. Being able to drag drop files to chat is a minimum. The next step is so allow smarter external content display (links with thumbnail + desc, maps) and allow (bidirectional) web hooks.

**Comment by ma12-co** [comment]
Done in #2891
