### ISSUE TITLE
[Bug]: Contact person cannot be found in talk

### ISSUE THREAD

**Issue by wangxiuguo** [nextcloud/spreed#11307]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Contact person cannot be found in talk

### Steps to reproduce

It's just normal decompression and installation

### Expected behavior

It's just normal decompression and installation

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
It's just normal decompression and installation
```

### List of activated Apps

```shell
It's just normal decompression and installation
```

### Nextcloud Signing status

```shell
It's just normal decompression and installation
```

### Nextcloud Logs

```shell
It's just normal decompression and installation
```

### Additional info

It's just normal decompression and installation

**Comment by joshtrichards** [comment]
What do you mean, precisely, by "a contact person"? Is this a user with a Nextcloud account or someone without an account?

**Comment by nickvergessen** [comment]
Closing as

> It's just normal decompression and installation

**Comment by wangxiuguo** [comment]
Hello, I'm very sorry. I was hospitalized a while ago and the issue I want to solve is that my NEXTCloud cannot see my contacts，Here are some screenshots and error logs
[nextcloud.log](https://github.com/nextcloud/spreed/files/13858114/nextcloud.log)
![2](https://github.com/nextcloud/spreed/assets/53425510/2bc7da2f-35d3-455c-8ed1-c2ad6bb93e7e)
![1](https://github.com/nextcloud/spreed/assets/53425510/1c2e1a68-93fd-4264-bb88-d47a3e7ae098)
