### ISSUE TITLE
Notifications doesn't work

### ISSUE THREAD

**Issue by ibahnasy** [nextcloud/spreed#11310]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the Talk app and enable browser notifications.
2. Let other users send messages.
3. Switch to another tab or application to lose focus.

### Expected behaviour
I should receive notifications about new messages.

### Actual behaviour
Notifications doesn't show up at all.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
17.1.4

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No.

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes.

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes.

## Browser

**Microphone available:** yes/no
Yes.

**Camera available:** yes/no
Yes.

**Operating system:** Windows/Ubuntu/...
Ubuntu 23.10

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
120

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu 22.04

**Web server:** Apache/Nginx
Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria.

**PHP version:** 8.0/8.1/8.2
8.1

**Nextcloud Version:** (see admin page)
27.1.5

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
We fixed this for Talk 18.
You have to update to Nextcloud 28 and Talk 18

**Comment by RTechSn** [comment]
I'm not sure it's working always. 
There are cases when you just don't receive a notification, i haven't figured out the circumstances yet.
