### ISSUE TITLE
Secure TURN Protocol Not Working With Nextcloud 28 and Spreed 18

### ISSUE THREAD

**Issue by smolinde** [nextcloud/spreed#11327]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install latest release of Talk (Spreed)
2. Configure coturn server
3. Fill out TURN fields in Talk admin settings
4. Set turns: only protocol and run health check

### Expected behaviour
A green checkmark appears.

### Actual behaviour
A red circle with an exclamation mark appears.
Identical configuration of coturn works with Nextcloud 27.1.5, Talk 17.1.4, and turns: only setting.

## Talk app

**Talk app version:** 18.0.1

**Custom Signaling server configured:** no
**Custom TURN server configured:** yes (coturn 4.6.1)
**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 11 Pro (23H2) (build 22631.2861)

**Browser name:** Chrome

**Browser version:** 120.0.6099.130 (Official Build) (64-bit)

### Browser log

<i>No errors</i>  

## Server configuration

**Operating system**: Ubuntu 23.10 (mantic) Server (x64)

**Web server:** Apache 2.4.57

**Database:** MariaDB 10.11.4

**PHP version:** 8.2

**Nextcloud Version:** 28.0.1

**List of activated apps:**

<details>

```
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.7.0
  - backup: 1.2.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.1
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - cms_pico: 1.0.21
  - comments: 1.18.0
  - contacts: 5.5.0
  - contactsinteraction: 1.9.0
  - cookbook: 0.11.0
  - cospend: 1.5.14
  - dashboard: 7.8.0
  - dav: 1.29.1
  - dicomviewer: 1.2.5
  - drawio: 3.0.1
  - drop_account: 2.4.0
  - eidlogin: 1.0.15
  - encryption: 2.16.0
  - extract: 1.3.6
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.0
  - files_external: 1.20.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - files_zip: 1.5.0
  - firstrunwizard: 2.17.0
  - forms: 4.0.0
  - group_default_quota: 0.1.8
  - groupquota: 0.1.12
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.0
  - music: 1.9.1
  - news: 24.0.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - passwords: 2023.12.32
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - ransomware_protection: 1.14.0
  - recommendations: 2.0.0
  - registration: 2.3.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_retention: 1.11.0
  - user_status: 1.8.1
  - user_usage_report: 1.12.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - user_ldap: 1.19.0
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "duscloud-beta.local",
            "www.duscloud.eu",
            "192.168.0.85",
            "duscloud.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/www.duscloud.eu",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "maintenance": false,
        "trashbin_retention_obligation": "30, auto",
        "default_phone_region": "DE",
        "default_language": "en_US",
        "default_locale": "de",
        "allow_local_remote_servers": true,
        "app_install_overwrite": [
            "backup",
            "breezedark",
            "cms_pico",
            "extract",
            "holiday_calendars",
            "files_markdown",
            "metadata",
            "music",
            "news",
            "files_texteditor",
            "quicknotes",
            "ransomware_protection",
            "files_retention",
            "files_rightclick",
            "video_converter",
            "dicomviewer"
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "jwt_header": "AuthorizationJwt"
        },
        "encryption_skip_signature_check": true
    }
}
```
</details>

### Server log (data/nextcloud.log)

<i>No logs regarding this issue</i>

**Comment by SystemKeeper** [comment]
Does it work when you skip verification ?

**Comment by smolinde** [comment]
How do I skip verification? Where to set this?

**Comment by SystemKeeper** [comment]
Ah sorry, I mixed it with the HPB.
What you can do, set your loglevel to debug, re-run the TURN test and check the logs. There should be some information about the certificate check.

**Comment by smolinde** [comment]
After executing the steps you mentioned I received the following log error:
```
{
    "reqId":"kP0t0SrKMDTFXJ8JlPb7",
    "level":3,
    "time":"2024-01-01T12:48:41+00:00",
    "remoteAddr":"XXX.XXX.XXX.XXX",
    "user":"XXXXX",
    "app":"PHP",
    "method":"GET",
    "url":"/ocs/v2.php/apps/spreed/api/v1/certificate/expiration?host=www.duscloud.eu:3478",
    "message":"stream_socket_client(): Unable to connect to ssl://www.duscloud.eu:3478 (Connection timed out) at 
    /var/www/nextcloud/apps/spreed/lib/Service/CertificateService.php#107",
    "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 
    Safari/537.36",
    "version":"28.0.1.1",
    "data":{"app":"PHP"},
    "id":"6592b4b56cd90"
}
```

**Comment by SystemKeeper** [comment]
> stream_socket_client(): Unable to connect to ssl://www.duscloud.eu:3478 (Connection timed out)

Looks like your server is unable to connect to TURN on that port. Previous versions of Talk only checked from the client side, starting with 28 we also check the certificate of TURN (in case `turns:` is used), this fails here. Generally the check is working fine with that URL:

<img width="678" alt="image" src="https://github.com/nextcloud/spreed/assets/1580193/6d8519d4-3d62-46a5-9289-d82b88415b42">

**Comment by smolinde** [comment]
The problem in my case is that my home network does not support loopbacks. This means if I run the ```turnutils_uclient``` command I don't get any response on www.duscloud.eu. What should I do?

**Comment by SystemKeeper** [comment]
> What should I do?

Guess fix your network setup 😅
On a more serious note, what you’re experiencing is not a bug in Talk, so nothing we can do here. So either connection should be made possible or you need to live with the error. Since only your instance can’t connect, clients should still be able to connect.
If you need any help, feel free to reach out to help.nextcloud.com.

**Comment by tigermick** [comment]
Hi,
I just upgrade to nextcloud 28 and I have the same problem ...
no problem with nextcloud 27.1.6
Are you sure it's a network setting problem ?

**Comment by SystemKeeper** [comment]
> Are you sure it's a network setting problem ?

Feel free to execute the steps mentioned above. But as said, if the instance can't connect to check the SSL certificate, there's nothing we can do.

**Comment by tigermick** [comment]
If I don't use tls, I just select "turn only" in talk setting in nextcloud administration setting ?

**Comment by SystemKeeper** [comment]
> If I don't use tls, I just select "TURN only" in talk setting in nextcloud administration setting ?

Yes. As soon as you select an option with `TURNS` TLS is expected and will be checked.

**Comment by tigermick** [comment]
Ok, sorry for answering late ....
Thank you for information and sorry to disturb you with a fake problem ....
