### ISSUE TITLE
Talking time is hidden when another participant joins/leaves

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11336]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call with User1 and start talking, notice that your speaking time is visible in the side bar
2. Now join the room with User2 (only the room so the session gets active)

### Expected behaviour
You should still see the speaking time

### Actual behaviour
The speaking time is not visible anymore, it will only be shown again, once you start to speak again

https://github.com/nextcloud/spreed/assets/1580193/c6d59fb0-9ab3-4fc7-8118-22a82361a422

## Talk app

**Talk app version:** main, also on c.nc.c

**Custom Signaling server configured:** yes

## Browser

**Operating system:** MacOS

**Browser name:** Chrome

**Browser version:** 120

**Comment by Antreesy** [comment]
Could reproduce it only after reverting commits from https://github.com/nextcloud/spreed/pull/11254
So hopefully, was fixed by it, @SystemKeeper, please, give it a try again on updated main branch

**Comment by SystemKeeper** [comment]
> give it a try again on updated main branch

Looks like I did not build the frontend code when pulling latest master changes 😵‍💫 Sorry about that. It's fixed indeed.
