### ISSUE TITLE
Capabilities check for talk-desktop / minimum supported version

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11342]
> Also an issue for the desktop client when talking to an old server

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/11335#issuecomment-1877782749_

Creating a new issue to have it listed, as I couldn’t find a ticket about this. I think a lot of features on web miss capability checks, which are needed for talk-desktop.

E.g. creating polls only checks for chat permissions and 1-1 conversations:

https://github.com/nextcloud/spreed/blob/5ea09ae4dccd803021046dfef4cc244ac8d8a2d8/src/components/NewMessage/NewMessage.vue#L355-L357

Either we need to add checks for the features or need to enforce a minimum server version that can be used with talk-desktop.

**Comment by nickvergessen** [comment]
Nvm, I think it requires 17 iirc, at least per repo readme

**Comment by SystemKeeper** [comment]
Right, see

https://github.com/nextcloud/talk-desktop/blob/da52f757634aae78f709c82b133ab7c255cf9352/src/constants.js#L35

Checked at 

https://github.com/nextcloud/talk-desktop/blob/da52f757634aae78f709c82b133ab7c255cf9352/src/authentication/renderer/AuthenticationApp.vue#L170-L177
