### ISSUE TITLE
Bots settings rendered even if no bots are configured

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/spreed#11356]
Consider not rendering [Bots settings](https://github.com/nextcloud/spreed/blob/d790a147c794c3e83c0337fc7f94d5b0af5e5a70/src/components/ConversationSettings/ConversationSettingsDialog.vue#L91) if no bots are configured to keep UI clean.

**Comment by nickvergessen** [comment]
![grafik](https://github.com/nextcloud/spreed/assets/213943/a43a626f-31e7-497d-8f62-922122b2d0ba)

This is currently shown intentional to promote the functionality a bit.
