### ISSUE TITLE
Unread count includes system messages

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1135]
At the moment the unread count in the sidebar also counts system messages. I wonder if this is really useful? When I noticed it the first time it was quite confusing to me and my initial gut feeling was that it should only show real messages but maybe there are also rare use cases where a system message is interesting enough to indicate it with a increased unread count... Opinions?

**Comment by Ivansss** [comment]
Hi @schiessle :)
That shouldn't be the case using latest master or beta release.
https://github.com/nextcloud/spreed/pull/1087
You could try it in our instance 😉
