### ISSUE TITLE
Replying to other chat messages

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1136]
A few day ago a new version of riot.im was released, I really like the way they allow you to add a reply to a existing message and create some kind of a thread while discussing something, see here for a more detailed explanation including some screenshots and videos: https://medium.com/@RiotChat/look-out-its-riot-im-0-16-composer-jitsi-replies-8b29f89271a1 

I think it is worth to consider something similar for Talk.

**Comment by nickvergessen** [comment]
As far as I know the comment system has the option of a parent item,
but not sure if it allows for infinite nesting. If it does and still allows us to get the items easily we can use that.
