### ISSUE TITLE
password field should be empty if no password is set

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1137]
Tested with version 3.99.10:

- create an new public room
- click on the "set password icon"

Result:

![image](https://user-images.githubusercontent.com/1589737/43949556-258c9008-9c8e-11e8-9762-2070b8053b66.png)

For a moment I was really confused and wondered if there is already a password set.

Expected: An empty input field to indicate that no password is set.

**Comment by nickvergessen** [comment]
Use a browser which respects:
* autocomplete: off
* autocomplete: new password

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Long story short, there is nothing we can do. Browsers ignore all the things that were invented to help with such cases 🤷
