### ISSUE TITLE
Make polls more visible when "live"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11372]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
During a webinar polls are a useful option to steer the conversation going forward, but only if people vote.

**Describe the solution you'd like**
Popup the poll when they happen "live" directly so more people vote.

**Describe alternatives you've considered**
Mark the poll message visually so they are less likely to be missed

**Comment by nickvergessen** [comment]
Other idea, show a "sticky button" similar to "unread mentions" that scrolls to the message when the poll is still open.

**Comment by Antreesy** [comment]
As i see it, both options should be applied above the call view, not only in the chat:

| Forced poll to vote directly | Popup with suggestion |
| -- | -- |
![image](https://github.com/nextcloud/spreed/assets/93392545/84ee8054-019b-4ab2-a35a-7d96ba6acd48) | ![image](https://github.com/nextcloud/spreed/assets/93392545/1e982a68-05bc-4034-907f-a0e968a28644)
