### ISSUE TITLE
Installing offline "Could not download app spreed" on the GUI

### ISSUE THREAD

**Issue by alejandro59** [nextcloud/spreed#11387]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install nextcloud 28.0.1 offline
2.Download the tar.gz file spreed-18.0.1.tar.gz and untar it in /var/www/nextcloudfolder/app
3.In the GUI, go to "+APP > Disabled apps > Talk > and click in Enable"

Taking some captures, I can see that the system wants resolve, using DNS, apps.nextcloud.com

Is there a way to be able to install completly spreed (Talk) offline?

Thank you.

If you need more information, do not hesitate to ask for it.

Alejandro

### Expected behaviour
Having Talk running

### Actual behaviour
"Could not download app spreed" on the GUI, and the app is not installed

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
18.0.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No.

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Not yet.

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
No

## Browser

**Microphone available:** yes/no
N/A

**Camera available:** yes/no
N/A
**Operating system:** Windows/Ubuntu/...
N/A
**Browser name:** Firefox/Chrome/...
N/A
**Browser version:** 85/96/...
N/A
### Browser log
N/A
<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian GNU/Linux 12
**Web server:** Apache/Nginx
Apache2
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB
**PHP version:** 8.0/8.1/8.2
8.2.7
**Nextcloud Version:** (see admin page)
28.0.1
**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - spreed-18.0.1: 18.0.1
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0

</details>

**Nextcloud configuration:**
Basic one?
<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
root@Nextcloud2:/var/www/nextcloud/apps# sudo -u www-data php ../occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.22.86.10"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/1.1.1.1",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}
</details>

### Server log (data/nextcloud.log)
<details>

```
x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"internet_connection_check","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Cannot connect to: www.startpage.com","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"No DNS record found for www.startpage.com","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":85,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":68,"function":"isSiteReachable","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":643,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","Line":139,"message":"Cannot connect to: www.startpage.com","exception":{},"CustomMessage":"Cannot connect to: www.startpage.com"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"internet_connection_check","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Cannot connect to: www.eff.org","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"No DNS record found for www.eff.org","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":85,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":68,"function":"isSiteReachable","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":643,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","Line":139,"message":"Cannot connect to: www.eff.org","exception":{},"CustomMessage":"Cannot connect to: www.eff.org"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"PHP","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#111","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"lQFQDsxLJmq423Bxgyp3","level":3,"time":"2024-01-15T14:28:06+00:00","remoteAddr":"1.1.1.1","user":"adminnextcloud","app":"internet_connection_check","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Cannot connect to: www.edri.org","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"28.0.1.1","exception":{"Exception":"OCP\\Http\\Client\\LocalServerException","Message":"No DNS record found for www.edri.org","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":85,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/SetupChecks/InternetConnectivity.php","line":68,"function":"isSiteReachable","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":49,"function":"run","class":"OCA\\Settings\\SetupChecks\\InternetConnectivity","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":643,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","Line":139,"message":"Cannot connect to: www.edri.org","exception":{},"CustomMessage":"Cannot connect to: www.edri.org"}}
```

</details>

**Comment by nickvergessen** [comment]
Did you put the files correctly into your file structure?
Does `apps/spreed/appinfo/info.xml` exist?

When your installation has no internet access try adding the following configuration to your `config/config.php`:
```php
'has_internet_connection' => false,
```

That avoids doing some unnecessary requests.

> Taking some captures, I can see that the system wants resolve, using DNS, apps.nextcloud.com

That could be the frontend loading app categories, bundles or screenshots of apps or something a like. Spreed/Talk itself is not installing anything manually from apps.nextcloud.com

> Is there a way to be able to install completly spreed (Talk) offline?

yes, exactly like you tried at least when the path you extracted to is correct.

**Comment by alejandro59** [comment]
Hello,

thank you very much for your answer, but I get stucked anywhere else. My 
folder name in app was not good, my bad.

But now, I have this:
{"reqId":"dVLrn2i36MHFk6Li5yhZ","level":3,"time":"2024-01-15T16:03:28+00:00","remoteAddr":"1.1.1.1.30","user":"adminnextcloud","app":"PHP","method":"POST","url":"/index.php/settings/apps/enable","message":"require_once(/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php): 
Failed to open stream: No such file or directory at 
/var/www/nextcloud/apps/spreed/composer/autoload.php#5","userAgent":"Mozilla/5.0 
(Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 
Firefox/102.0","version":"28.0.1.1","data":{"app":"PHP"}}
{"reqId":"dVLrn2i36MHFk6Li5yhZ","level":3,"time":"2024-01-15T16:03:28+00:00","remoteAddr":"1.1.1.1.30","user":"adminnextcloud","app":"index","method":"POST","url":"/index.php/settings/apps/enable","message":"Failed 
opening required 
'/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php' 
(include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') 
in file '/var/www/nextcloud/apps/spreed/composer/autoload.php' line 
5","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) 
Gecko/20100101 
Firefox/102.0","version":"28.0.1.1","exception":{"Exception":"Exception","Message":"Failed 
opening required 
'/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php' 
(include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') 
in file '/var/www/nextcloud/apps/spreed/composer/autoload.php' line 
5","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Failed 
opening required 
'/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php' 
(include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps')","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":158,"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":119,"function":"registerAutoloading","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":94,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Installer.php","line":145,"function":"runLazyRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":454,"function":"installApp","class":"OC\\Installer","type
":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/spreed/composer/autoload.php","Line":5},"message":"Failed 
opening required 
'/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php' 
(include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') 
in file '/var/www/nextcloud/apps/spreed/composer/autoload.php' line 
5","exception":{},"CustomMessage":"Failed opening required 
'/var/www/nextcloud/apps/spreed/composer/../vendor/autoload.php' 
(include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') 
in file '/var/www/nextcloud/apps/spreed/composer/autoload.php' line 5"}}


It seems that nextcloud doesnt find the file 
/var/www/nextcloud/apps/spreed/composer/autoload.php, but it is there 
and with the right permissions and ownership.

**Comment by nickvergessen** [comment]
Ah, you downloaded the 18.0.1.tar.gz from https://github.com/nextcloud/spreed/releases/tag/v18.0.1 right?

You need to download `spreed-v18.0.1.tar.gz` either from the appstore https://apps.nextcloud.com/apps/spreed or from the our release organisation directly: https://github.com/nextcloud-releases/spreed/releases/tag/v18.0.1

**Comment by alejandro59** [comment]
Hello,

Thank you very much for your help and time, I really appreciate it.

I downloaded 
https://github.com/nextcloud/spreed/archive/refs/tags/v18.0.1.tar.gz and 
tried to install it. but now I am going to download 
https://github.com/nextcloud-releases/spreed/releases/download/v18.0.1/spreed-v18.0.1.tar.gz 
and try to install it.

Have a nice day!
