### ISSUE TITLE
Allow user to change font size easily  

### ISSUE THREAD

**Issue by john-2000** [nextcloud/spreed#1138]
Changing default font size of the chat is not straight forward (espeically for non technical users), giving the user simple font size and perhaps font selector would improve readabilty

### Expected behaviour
"cog" or button to allow to choose font size

### Actual behaviour
currently not a feature

**Comment by nickvergessen** [comment]
The font size is now a bit bigger. That should be sufficient for now.
The rest should be fixed globally in Nextcloud
