### ISSUE TITLE
Camera & Microphone Access not Working for Raspbian Clients

### ISSUE THREAD

**Issue by MichaelNiemetz** [nextcloud/spreed#1139]
## Steps to reproduce
1. Install current Raspbian run upgrades
1a. Ensure camera and webrtc is working by using cheese and navigating to https://opentokrtc.com/
using Firefox. Note that things work fine with opentokrtc.
2. Connect to a working nextcloud 13.0.5

### Expected behaviour
Browser should ask for permission and access to microphone and camera should be possible.

### Actual behaviour
An error on camera and microphone access is reported. The error will show up before Firefox/Chrome is asking for permission to access them. Chrome behaves similarly and also fails.

Usage of camera and microphone is blocked in the app.

## Browser
Firefox and Chrome

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Raspbian

**Browser name:** Firefox and Chrome

**Browser version:** recent

### Browser log

<details>

```

Joined Object { ocs: Object }  signaling.js:183:5
addRoomMessage  roomlistview.js:226:4
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
Joined Object { ocs: Object }  signaling.js:183:5
addRoomMessage  roomlistview.js:226:4
startLocalVideo  simplewebrtc.js:18261:3
CONNECTED  simplewebrtc.js:18020:4
Access to microphone & camera failed MediaStreamError { name: "NotFoundError", message: "The object can not be found here.", constraint: "", stack: "" }  webrtc.js:991:4
Error while accessing microphone & camera:  The object can not be found here.  webrtc.js:1008:5

```

</details>

## Spreed app

**Spreed app version:** 3.2.5

**Custom TURN server configured:** no 

**Custom STUN server configured:** no 

## Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.0 

**Nextcloud Version:** 13.0.5

**List of activated apps:**

<details>

```

  - bookmarks: 0.11.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - circles: 0.14.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.1
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mindmaps: 0.1.0
  - news: 12.0.4
  - notes: 2.4.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - spreed: 3.2.5
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

```

</details>

**Nextcloud configuration:**

<details>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "htaccess.RewriteBase": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "upgrade.disable-web": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN"
    }
}

```
</details>

**Comment by Ivansss** [comment]
> Connect to a working nextcloud 13.0.5

Is this Nextcloud server SSL enabled?

**Comment by Ivansss** [comment]
Could you share the error log shown in the browser's js console?

**Comment by MichaelNiemetz** [comment]
I have already added what was avalable in the js console under details in the _Browser log_ section. How can I get more output?

**Comment by Ivansss** [comment]
Sorry @MichaelNiemetz, I totally missed "Details" 😅 
You already wrote the important info there:
`MediaStreamError { name: "NotFoundError", message: "The object can not be found here."`

If you have a cam and a mic and you can use them with other webrtc sites, this is strange.
But let's try to debug this a bit more.
Are you trying to make a call with Talk while the camera&mic is being used by another browser/app?
You already said that your server works with ssl, but just to be sure, you are connected through https while using Talk, right?

**Comment by MichaelNiemetz** [comment]
Hi Ivansss,

I redid the tests and can confirm that the problem occurs without an other application or tab using the device.the collections is established via https.

**Comment by Ivansss** [comment]
Let's try another thing. Could you tell us at which video resolution can record your webcam?

**Comment by MichaelNiemetz** [comment]
Sorry for the delay, I was off site for some days. The camera can do 2048x1536, 1920x1080,1280x720, 640x480, 640x360, 352x288, 320x240.

**Comment by nickvergessen** [comment]
Well free to report again with the new details if this is still an issue.
