### ISSUE TITLE
Strike text is not working on web ui `~~striked text~~`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#11405]
When striking text on the WEB ui, it doesn't work.
Android works well though

| Web | Android |
|:---------:|:------:|
|![image](https://github.com/nextcloud/spreed/assets/14975046/f88cfa3c-389b-4dae-9cce-1cd9556d7a1c)|![image](https://github.com/nextcloud/spreed/assets/14975046/5db300b5-d0a8-4f1c-b04f-2f42cb58f561)|

**Comment by Antreesy** [comment]
- Technically a duplicate of https://github.com/nextcloud/spreed/issues/10066
- Upstream PR: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4365
