### ISSUE TITLE
Follow-up(Edit message) 

### ISSUE THREAD

**Issue by DorraJaouad** [nextcloud/spreed#11403]
Follow-up to #11374

## **To do 🚧** 
- [x] Mention parsing for the input
- [x] Add hint 
![image](https://github.com/nextcloud/spreed/assets/84044328/e1ad32aa-b46c-4fc7-be8e-be602dfe5ec6)
- [x] Improve edit history design in MessageButtonsBar
![image](https://github.com/nextcloud/spreed/assets/84044328/854a8852-a7a0-4593-bfc3-f6421b739926)
- [x] Error handling (showError + keep the edit on)
- [x] Handle capabilities (for Talk Desktop) https://github.com/nextcloud/spreed/pull/11408
  - [x] `delete-messages-unlimited`
  - [x] `edit-messages`
- [ ] Move edit option above "Delete message"
- [ ] https://github.com/nextcloud/spreed/issues/11402

**Comment by DorraJaouad** [comment]
@nextcloud/designers, could you please share some feedback on these points:
* The hint "Adding a mention ..."  will be a NcNoteCard. Is it okay in terms of the spacing ? It is not shown only if a user edits a message and add a mention.
* Edit history design in MessageButtonsBar
* Should the edit message button be moved above delete button ? 
![image](https://github.com/nextcloud/spreed/assets/84044328/e26891d1-d748-4c93-ada2-a372e634fc81)


You can refer to https://github.com/nextcloud/spreed/pull/11374 for the basic edit feature screenshots

**Comment by szaimen** [comment]
> * The hint "Adding a mention ..."  will be a NcNoteCard. Is it okay in terms of the spacing ? It is not shown only if a user edits a message and add a mention.

I don't see this on the screenshot, do I see it somewhere?

> * "Last edit info" design in MessageButtonsBar

Looks good but I would show the time before the date...

> * Should the edit message button be moved above delete button ?

It is alreaddy above it in the screenshot?

**Comment by DorraJaouad** [comment]
> I don't see this on the screenshot, do I see it somewhere?

It's the yellow line 
![image](https://github.com/nextcloud/spreed/assets/84044328/85468283-cd52-4742-9679-2f79251d4e7e)


> It is alreaddy above it in the screenshot?

Currently, it is here 
![image](https://github.com/nextcloud/spreed/assets/84044328/46b48395-cce7-467e-a9f2-a97b059305d7)

**Comment by jancborchardt** [comment]
> > I don't see this on the screenshot, do I see it somewhere?
> 
> It's the yellow line ![image](https://private-user-images.githubusercontent.com/84044328/299600608-85468283-cd52-4742-9679-2f79251d4e7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzM3MzQsIm5iZiI6MTcwNjE3MzQzNCwicGF0aCI6Ii84NDA0NDMyOC8yOTk2MDA2MDgtODU0NjgyODMtY2Q1Mi00NzQyLTk2NzktMmY3OTI1MWQ0ZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MThlZWQ4NGM0NzI4ZGIyMTA0YmQ3ZWNiZDNhZGVjODlhMWNhN2MxM2YxNmVmZDI5NzRjMjk1NDllZTk0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UssAf7mtLFe0TOu4H0X10zZVdElLEbWZMLiIiFcfHnw)

This doesn’t look like NcNoteCard though? If it would be NcNoteCard then it would be fine. :)

---

> > It is alreaddy above it in the screenshot?
> 
> Currently, it is here ![image](https://private-user-images.githubusercontent.com/84044328/299600133-46b48395-cce7-467e-a9f2-a97b059305d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzM3MzQsIm5iZiI6MTcwNjE3MzQzNCwicGF0aCI6Ii84NDA0NDMyOC8yOTk2MDAxMzMtNDZiNDgzOTUtY2NlNy00NjdlLWE5ZjItYTk3YjA1OTMwNWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA5MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1M2Y1MDZmYmU4ZGI3ZjU2OGI0YjM2MDEwMDU0NjgxMmM2NWNkZDBkMDkwYjg3MTIyNDU3OWU0YzdhYTA2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8jcuUSjb6d9C-wX3QfHmtUYWAvIg0VjDX1Uh55RWwLk)

This seems good to me, however the detail list as per this screenshot could be improved. There is strange spacing between the nickname and the time. We would probably have to make it 2-line, so that it’s "Edited by Simon Lindner" in the first line (as we shouldn’t just show account names there and they might be long) and the date in the subline
![image](https://github.com/nextcloud/spreed/assets/84044328/854a8852-a7a0-4593-bfc3-f6421b739926)

Similar to how it is on iOS as per the comment https://github.com/nextcloud/spreed/issues/11203#issuecomment-1880143767
![image](https://github.com/nextcloud/spreed/assets/925062/cff95fdf-4a5e-406c-a45d-04da19e37581)

**Comment by DorraJaouad** [comment]
Currently it is like this :
![image](https://github.com/nextcloud/spreed/assets/84044328/31451c4c-38f8-4617-9ab9-fda8a270da49)

The line will expand depending on the username length.

>  so that it’s "Edited by Simon Lindner" in the first line (as we shouldn’t just show account names there and they might be long) and the date in the subline

I am worried that it will be a bit confusing to see 2 dates and each is on a line ( sent timestamp and edited timestamp). There should be way to distinguish between them (like change the edited stamp text color to secondary ?) .

**Comment by nickvergessen** [comment]
> Currently, the author+timestamp line is like this :

Can you use a "real name" as sample in the screenshot so we see it wrap (rebasing on latest master should give you the display name)

**Comment by jancborchardt** [comment]
> I am worried that it will be a bit confusing to see 2 dates and each is on a line ( sent timestamp and edited timestamp). There should be way to distinguish between them (like change the edited stamp text color to secondary ?) .

Sure, sounds good! :) Then let's indeed use colore-text-maxcontrast for the timestamp of any edits (not for the main timestamp), and also separate the name and timestamp with a middle dot like so:

> Simon Lindner · Jan 17, 2024 3:42 PM

**Comment by DorraJaouad** [comment]
Option 1 (as iOS shows only time, and you can edit within 24 hours) 

|![image](https://github.com/nextcloud/spreed/assets/84044328/0e43bf0f-423e-42a8-aba0-74bdf413c35d) |![image](https://github.com/nextcloud/spreed/assets/84044328/bf1d9486-92e5-497a-ad38-e25ce788e8f4)|


Option 2 
![image](https://github.com/nextcloud/spreed/assets/84044328/9d8dcb2f-d7ac-4289-ba70-7dd1d5aa629b)|![image](https://github.com/nextcloud/spreed/assets/84044328/cbe72a4e-0b1c-447a-a9ae-ca9375f32805)

**Comment by SystemKeeper** [comment]
> Option 1 (as iOS shows only time, and you can edit within 24 hours)

Just for clarification, iOS shows the time only when it happened today, otherwise it shows date and time
