### ISSUE TITLE
User status in right sidebar no longer updates to "In a call"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11441]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Most likely a regression from https://github.com/nextcloud/spreed/pull/11394

## Steps to reproduce
1. Be online and set a status
2. Open Dev tools to check participants?includeStatus=true requests
3. Start a call
4. See that your status is correctly `Away - In a call`

### Expected behaviour
Shows in the UI

### Actual behaviour
Old status is shown in UI

**Comment by Antreesy** [comment]
There is Issue with a Vue reactivity of a prop. But yes, caused by participant patch (not this PR, the one before it with a soft update)
