### ISSUE TITLE
Redundant database indices

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#11442]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Install Nextcloud

### Expected behaviour

Efficient use of database indices

### Actual behaviour

```
MariaDB [(none)]> select * from sys.schema_redundant_indexes sri where table_schema = 'nextclouddev' and table_name like 'oc_talk_%';
+--------------+---------------------------+----------------------+-------------------------+----------------------------+----------------------+-----------------------------+---------------------------+----------------+----------------------------------------------------------------------------------------+
| table_schema | table_name                | redundant_index_name | redundant_index_columns | redundant_index_non_unique | dominant_index_name  | dominant_index_columns      | dominant_index_non_unique | subpart_exists | sql_drop_index                                                                         |
+--------------+---------------------------+----------------------+-------------------------+----------------------------+----------------------+-----------------------------+---------------------------+----------------+----------------------------------------------------------------------------------------+
| nextclouddev | oc_talk_attendees         | ta_room              | room_id                 |                          1 | ta_ident             | room_id,actor_type,actor_id |                         0 |              0 | ALTER TABLE `nextclouddev`.`oc_talk_attendees` DROP INDEX `ta_room`                    |
| nextclouddev | oc_talk_attendees         | ta_room              | room_id                 |                          1 | ta_roompin           | room_id,pin                 |                         1 |              0 | ALTER TABLE `nextclouddev`.`oc_talk_attendees` DROP INDEX `ta_room`                    |
| nextclouddev | oc_talk_bots_conversation | talk_bots_convo_id   | bot_id                  |                          1 | talk_bots_convo_uniq | bot_id,token                |                         0 |              0 | ALTER TABLE `nextclouddev`.`oc_talk_bots_conversation` DROP INDEX `talk_bots_convo_id` |
+--------------+---------------------------+----------------------+-------------------------+----------------------------+----------------------+-----------------------------+---------------------------+----------------+----------------------------------------------------------------------------------------+
3 rows in set (0,015 sec)
```

Suggestions:
* kill `talk_attendees.ta_room`
* kill `talk_bots_conversation.talk_bots_convo_id`

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Removed performance label as we never update that column, but should still clean it up
