### ISSUE TITLE
Can't select message text box

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/spreed#11454]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

When using FF Mobile 122.0 (Build #2015998391), I cannot select the textbox yo type a new message.

## Steps to reproduce
1. Open any chat 
2. Switch to another chat
3. Try selecting the message text box to type

### Expected behaviour
Tell us what should happen

The keyboard should open, the cursor should appear and I should be able to send a message

### Actual behaviour
Tell us what happens instead

No keyboard or cursor

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) c.nc

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`) c.nc

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`) c.nc

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`) c.nc

## Browser

**Microphone available:** yes

**Camera available:** yes/no

**Operating system:** Android

**Browser name:** Firefox Mobile 122.0 (Build #2015998391)

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Antreesy** [comment]
Is there a placeholder on the text field, with that text, by chance? It takes time even for web to join the conversation, until field is avilable:

![image](https://github.com/nextcloud/spreed/assets/93392545/f42b7ff0-f17d-414c-95c3-a2a33a8719f2)

Tested with Android Firefox 122, can't reproduce, joining (and typing afterwards) works fine

**Comment by Antreesy** [comment]
default placeholder means, that at least:
- conv is not read-only
- permissions to chat are granted
- conversation is joined

if input is still disable, then:
- ~~conv is read-only~~
- ~~no chat permissions~~
- ~~conversation is not joined~~
- isRecordingAudio is `true`

Is button with `microphone` icon presented / clickable?

**Comment by SystemKeeper** [comment]
The same is reproducible on mobile safari on iOS. We can take a look tomorrow if you like  @Antreesy

**Comment by Antreesy** [comment]
Coming from vue-lib focus-trap (because we always render RightSidebar even if it's not shown)
