### ISSUE TITLE
User is shown as Guest if switch from desktop to mobile app

### ISSUE THREAD

**Issue by solracsf** [nextcloud/spreed#11453]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Login on desktop, join a conversion, write something, username appears
2. Login on mobile app, join the same conversation, write something
3. Message appears as "Guest"

![image](https://github.com/nextcloud/spreed/assets/12234510/ca1b0215-3c8b-45a3-bf7c-8ad1f5bcc0bd)

No log errors.

## Talk app

**Nextcloud version:** 26.0.11

**Talk app version:** 16.0.10

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by nickvergessen** [comment]
This kind of makes no sense. Also there were no changes in 26 for a long time especially in that area.
I think this is more a problem of the mobile app you used that it somehow did not send the authentication data when writing the chat message.
