### ISSUE TITLE
FLOW troughs an error

### ISSUE THREAD

**Issue by pflegende** [nextcloud/spreed#11483]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce

1. 
---
Preface: 
using the nextcloud functionality [linked her in gh](https://github.com/nextcloud/spreed/tree/efbdcd8c04d359ff29e67d1411aba30466251f98/lib/Flow)

requirement that is now set:
- user is attached to one "Circle" (in german location: "Kreise")

We go to Section "Workflow" in "Prerequisits" (in german location: "Einstellungen")
https://wim.nl.tab.digital/settings/user/workflow

1st step is fine, we create a set with an in morning routine created file

![Opera Momentaufnahme_2024-01-28_230740_sync-thumbnails operacdn com](https://github.com/nextcloud/spreed/assets/52720420/41c763d3-8e8c-4097-836f-717cf64ba264)

2.
---
to see in the 2nd step, that this will never work because the following field "select option" is showing "List is empty"
and not surprised it throws an error:

![Err-Msg - Opera Momentaufnahme_2024-01-28_230841_wim nl tab digital](https://github.com/nextcloud/spreed/assets/52720420/5c66f133-6902-499f-bed8-febcc938aef4)

3.
---
so we show, that an "List item" aka Circle  is also available, (in german location: "Kreise" aka "Gruppe")

![Kreise Def Opera Momentaufnahme_2024-01-28_231037_wim nl tab digital](https://github.com/nextcloud/spreed/assets/52720420/eb5003e9-8863-4cff-a652-f80758aceac7)

### Expected behaviour
We expect in point "2." (above),
that the field "select option" contains the Circle "adminPflegecafe"

We expect regardless of whether we have admin access, that a Nextcloud core functionalty like "flow" could only be deployed with the simplest logical parameters like non free fields or at least with user communication that doesn't leave data (and the user and custumer too 😢 ) out in the cold.

😄 
... not at all, please.

### Actual behaviour
this is described above in point No "3."

## Talk app
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Custom Signaling server configured:** 
dont know what is is
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:**
dont know what is is
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

 yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** 
dont know what is is
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser
`Opera One(Version: 106.0.4998.52)`

**Microphone available:** no

**Camera available:** no

**Operating system:** Windows 10

**Browser name:** 
`Opera One(Version: 106.0.4998.52)`

**Browser version:** 
`Opera One(Version: 106.0.4998.52)`

### Browser log
not relevant
<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Operating system**: Ubuntu/RedHat/...
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Web server:** Apache/Nginx
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Database:** MySQL/Maria/SQLite/PostgreSQL
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**PHP version:** 8.0/8.1/8.2
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**Nextcloud Version:** (see admin page)
we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

**List of activated apps:**

![App List - Opera Momentaufnahme_2024-01-29_001303_wim nl tab digital](https://github.com/nextcloud/spreed/assets/52720420/fcba8fba-a543-4d1c-bcfb-fbaed5ce27da)

<details>

non cli access

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
non cli access

</details>

### Server log (data/nextcloud.log)

we have non Access to admin
we use an freehosted Nextcloud with no Admin access and also no admin communication channel

<details>

```
Insert your server log here
```
</details>

Thank you for your patience!
Allow me to say a final word.
You can also pass it on to Nextcloud management.
There are now so many free (and also paid) Nextcloud hosts that simply leave users out in the cold with problems that it is urgently necessary to improve the app-related contextual help by orders of magnitude. As a non-profit group, we particularly strive for the recognition of open source, especially among state governments and in the public sector. but it won't be anything like that!

The Maintainer is not the rhight adress, we know. May be you can communicate it forward.

**Comment by nickvergessen** [comment]
> We expect in point "2." (above),
that the field "select option" contains the Circle "adminPflegecafe"

This seems to be the confusion here.
You need a "Talk conversation" to select there. So navigate to "Talk" and type the name into the search:
![grafik](https://github.com/nextcloud/spreed/assets/213943/96171df1-2ff0-42bc-ac8a-17f234796ac7)

Afterwards you can select that on the Workflows:
![grafik](https://github.com/nextcloud/spreed/assets/213943/6125f14c-affd-4693-8f72-9d277eaff46f)

The circles are not actually linked to / needed for this. If you have a circle, you can invite that to the conversation, so each user of the circle is automatically added to the chat room, but that is totally unrelated:
![grafik](https://github.com/nextcloud/spreed/assets/213943/34ba0979-5b70-496a-9a6b-ab5ccc606e31)
