### ISSUE TITLE
Preload the list of users for the »Choose person« dialog

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#115]
Currently every time you want to add someone (via »Choose person« or »Add person«), you get greeted with the »Searching« message. This is annoying and we should simply preload the content.

**Comment by nickvergessen** [comment]
Any idea how to do that? I googled for all kinds of keywords in the last minute, but this seems to not exist, only when you have a fixed amount of data without live-searching later on.

**Comment by jancborchardt** [comment]
Maybe it’s a select2 function or so? cc @nextcloud/javascript on this one.

**Comment by nickvergessen** [comment]
Well I read all the select two docs...

**Comment by jancborchardt** [comment]
I removed the starter issue label since this is not a starter issue really. It really is an important issue though cause it impacts the initial user experience.

Calling @nextcloud/javascript again for ideas. @danxuliu? :)

**Comment by muppeth** [comment]
As I stated also on the linked issue. 
I would say talk should not perform any search if in case of LDAP autocompletion is disabled. In case of large database the search simply timesout and prevents people to for example start public call (as this option is unavailable until the search is complete). The only way around it is to type in a name of existing user. Only then you can select to start public call or a group.

**Comment by nickvergessen** [comment]
#1010 will obsolete this, because we will filter the room list on the first 2 chars and then search against the server in the background, so it's not empty and flickering anymore
