### ISSUE TITLE
Initial chat messages should be loaded most recent first

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1150]
Currently, chat messages are loaded from the beginning of time in the room, so the most recent messages are loaded last.

This should be reversed, so the most recent messages are loaded first and afterwards the batches of older messages. There should also be a limit to not load all messages by default and not load messages endlessly for very old rooms.

**Comment by nickvergessen** [comment]
The API already supports this, so this is just a matter of the JS UI

**Comment by nickvergessen** [comment]
Lets close this in favor of #1164
