### ISSUE TITLE
Markdown Images not displayed on Android

### ISSUE THREAD

**Issue by MartinAirN** [nextcloud/spreed#11511]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a talk conversation in a web browser.
2. Send a chat message containing a known available image. Example: `![Test Image](/apps/spreed/img/app.svg)`
3. View the image that was just sent (The Q)
4. Open the Android Talk Client, and open the same conversation
5. Notice the "Test Image" text is displayed on the Android App, not the image.

### Expected behaviour
Image should be displayed on the Android App similarly to the Desktop.

### Actual behaviour
Replacement text is displayed on the Android App.

## Talk app

**Talk app version:** 17.1.5

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 11 & Android 14

**Browser name:** Firefox

**Browser version:** 122.0

**App version:** 18.0.1

### Browser log

N.A.

## Server configuration

**Operating system**: Docker

**Web server:** Reverse Proxy: Nginx

**Database:** Maria

**PHP version:** N.A. (Docker)

**Nextcloud Version:** 27.1.5

**List of activated apps:**

<details>

```
  - activity: 2.19.0
  - bookmarks: 13.1.3
  - calendar: 4.6.4
  - camerarawpreviews: 0.8.4
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.3
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.3.4
  - integration_reddit: 2.0.2
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.2.0
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.2
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.2.4
  - password_policy: 1.17.0
  - passwords: 2023.12.32
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 5.0.3
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - snappymail: 2.32.0
  - spreed: 17.1.5
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - timemanager: 0.3.11
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
```
</details>

**Nextcloud configuration:**

N.A.

### Server log (data/nextcloud.log)

N.A.

**Comment by nickvergessen** [comment]
> Open the Android Talk Client, and open the same conversation

Relative links will never work in the mobile app.
They should also not render in the web, if they do, that is a bug.

**Comment by MartinAirN** [comment]
> > Open the Android Talk Client, and open the same conversation
> 
> Relative links will never work in the mobile app. They should also not render in the web, if they do, that is a bug.

The same behaviour happens with full links: `https://nextcloud.my.url/apps/speed/img/app.svg`

**Comment by nickvergessen** [comment]
Ah this works on stable28, but seems we fixed it on master already with the github-flavor 
cc @Antreesy
