### ISSUE TITLE
Support browser notifications

### ISSUE THREAD

**Issue by WilliamDEdwards** [nextcloud/spreed#11528]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

From what I understand, notifications work as follows:

- Depending on conversation settings, users receive notifications for all messages, messages in which they were mentioned, or no messages.
- For mobile users, a 'notification' means a push notification.
- For desktop users, a 'notification' means a sound being played.
- Regardless of notification settings, an asterisk is shown in the page title for any new message.

(Out of scope for this issue: when not mentioning a user, but responding to a message of theirs, that user does not seem to receive a notification.)

**Describe the solution you'd like**

For desktop users, browser notifications would be ideal. After all, desktop users have typically muted sounds, and are not monitoring browser tabs (to see the asterisk).

If my understanding of how notifications work is incorrect, there is at least a documentation issue.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nickvergessen** [comment]
> when not mentioning a user, but responding to a message of theirs, that user does not seem to receive a notification.

They do

> For desktop users, browser notifications would be ideal. After all, desktop users have typically muted sounds, and are not monitoring browser tabs (to see the asterisk).

Browser notifications are done by the notifications app. The only misunderstanding could be that we do not send notifications when you are active in the chat, to avoid your phone vibrating while actively chatting in the browser.


> If my understanding of how notifications work is incorrect, there is at least a documentation issue.

It's not correct, but also I'm not sure what we should document about it.

**Comment by WilliamDEdwards** [comment]
> > when not mentioning a user, but responding to a message of theirs, that user does not seem to receive a notification.
> 
> They do
> 

No, they don't. You may mean 'they should'.

> > For desktop users, browser notifications would be ideal. After all, desktop users have typically muted sounds, and are not monitoring browser tabs (to see the asterisk).
> 
> Browser notifications are done by the notifications app. The only misunderstanding could be that we do not send notifications when you are active in the chat, to avoid your phone vibrating while actively chatting in the browser.
>

Does 'the notifications app' mean the [Bell app](https://github.com/nextcloud/notifications)? If so, it is nowhere to be found that it would support browser notifications.
 
> > If my understanding of how notifications work is incorrect, there is at least a documentation issue.
> 
> It's not correct, but also I'm not sure what we should document about it.

If 'we' refers to the Spreed developers, sure. That doesn't change the fact that from a user perspective, how notifications are supposed to work is extremely confusing. This can also be judged by the many, many forum posts and issues created about the same subject. I doubt simply closing such issues helps NextCloud achieve its mission.

**Comment by nickvergessen** [comment]
Please make sure you run Nextcloud 28 and Talk 18. We improved the notification handling there quite a lot. It now is how it should be and how users expect it to be.
Before there were a couple of issues we were not able to solve due to technical limitations, but it's reworked and improved in Talk 18

**Comment by WilliamDEdwards** [comment]
> Please make sure you run Nextcloud 28 and Talk 18. We improved the notification handling there quite a lot. It now is how it should be and how users expect it to be. Before there were a couple of issues we were not able to solve due to technical limitations, but it's reworked and improved in Talk 18

Done three days ago.

Although users that have never received notifications before now do receive notifications - including browser notifications, which is not documented anywhere AFAICS - they now receive notifications on mobile devices while NextCloud Talk is open in their browsers. These notifications are also marked as unread.

I understand this may not be Spreed's 'department', but the fact that users receive notifications after updating while they did not before, attests to the fact that my notification settings are not funky.

P.S. Nice username :)

**Comment by alexpi4** [comment]
friend ! a chat program, which does not notify you that a conversation has arrived. It's a bad joke.

**Comment by nickvergessen** [comment]
It could be considered a joke, but it's not a nice way of communicating, if it would be true.
But we have browser notifications, as I myself implement them 8 years ago:
https://github.com/nextcloud/notifications/commit/15b0ce0795f119f204a5ee82149ee3f5508fb17e

This is how the look live when

### Being added to a conversation
![Bildschirmfoto vom 2024-02-09 00-07-58](https://github.com/nextcloud/spreed/assets/213943/cc6ab0fa-96e0-4ac7-a6e5-3d329c4cbeff)

### Being mentioned in a chat
![Bildschirmfoto vom 2024-02-09 00-08-27](https://github.com/nextcloud/spreed/assets/213943/518ef58e-6891-4e07-8d5e-03eb389d2516)

And this when 
### Checking the notification center of the operating system later
![Bildschirmfoto vom 2024-02-09 00-08-43](https://github.com/nextcloud/spreed/assets/213943/09c04a63-9bb5-4d16-a067-b694d87d791a)
