### ISSUE TITLE
User status indicator blank on safari

### ISSUE THREAD

**Issue by hamza221** [nextcloud/spreed#11557]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. open talk app using safari
2. check participants in a conversation
3.  blank status indicator 

### Expected behaviour
User status indicator blank 
<img width="330" alt="image" src="https://github.com/nextcloud/spreed/assets/40746210/5984196f-af07-4a95-8e41-e43504f79c64">
### Actual behaviour
User status indicator is not blank
<img width="330" alt="image" src="https://github.com/nextcloud/spreed/assets/40746210/651adf01-c0c2-40a6-90ad-f17bec635f97">

## Talk app

**Talk app version:** cloud.nc.com

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macos

**Browser name:** safari

**Browser version:** 17.0

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by hamza221** [comment]
Setting an explicit height on the svg seems to fix it 
https://stackoverflow.com/questions/27245673/svg-image-element-not-displaying-in-safari

**Comment by nickvergessen** [comment]
Requires a fix either in server or in the vue library.

@Antreesy should know where

**Comment by SystemKeeper** [comment]
Just saw this issue here, corresponding issue on the vue lib: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5386

**Comment by nickvergessen** [comment]
Yeah I expect it to be a vue library as well. So closing this here
