### ISSUE TITLE
Embed images and video

### ISSUE THREAD

**Issue by dataphreak1001** [nextcloud/spreed#1156]
I'd like to be able to send pictures of cats and videos from youtube of children after the dentist.

Links should have a preview mode as well.

It would also be nice to attach files directly from my cloud, whether they are public or not.

**Comment by iromeister** [comment]
Not sure if this is the right place to ask - am I missing something or is there no way yet to connect the main Nextcloud and the Nextcloud Talk app on smartphones? One way to do it would be from Nextcloud using the sharing function, but on my phone I can share files via WhatsApp but not via Nextcloud Talk. How come?

**Comment by nickvergessen** [comment]
Replaced by #2002
