### ISSUE TITLE
Delete option should always be available on messages in "Note to Self" chat channel

### ISSUE THREAD

**Issue by SteveDinn** [nextcloud/spreed#11593]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Since the "Note to Self" chat channel is purely for the one user who is posting in it, there should be no limitations on the time during which the "Delete" option is available for messages in this channel.

**Describe the solution you'd like**
The "Delete" options should *always* be available for messages in the "Note to Self" channel.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by nickvergessen** [comment]
This will come with Talk 19 for Nextcloud 29
