### ISSUE TITLE
can't choose colour for a conversation (edited simplified)

### ISSUE THREAD

**Issue by punkyard** [nextcloud/spreed#11602]
## Steps to reproduce
1. create a discussion (using browser brave and safari)
2. customize with emoji to access the colour button

<img width="497" alt="Capture d’écran 2024-02-23 à 09 41 42" src="https://github.com/nextcloud/spreed/assets/59349105/ade68642-22b5-43ff-bedd-90d9e353bdb2">

### Actual behaviour
- the colour box wouldn't open

## Talk app
17.1.5

**Custom TURN server configured:** yes
turn:only ip:3478
NC AiO 7.12.1

**Custom STUN server configured:** yes
ip:443
NC AiO

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macos ventura

**Browser name:** brave & safari 

**Browser version:** 85/96/..

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log oh yeah

<img width="671" alt="Capture d’écran 2024-02-18 à 16 33 10" src="https://github.com/nextcloud/spreed/assets/59349105/d664c6e5-aeaa-404c-9e76-4902684898c7">


b) The network log
c) ...
```

</details

## Server configuration (issuetemplate wouldn't work)
Server configuration detail

Operating system: Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-2 (2023-07-14) x86_64

Webserver: Apache/2.4.58 (Unix) (fpm-fcgi)

Database: pgsql PostgreSQL 15.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit

PHP version: 8.1.27

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, readline, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, Phar, exif, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_pgsql, pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

Nextcloud version: 27.1.5 - 27.1.5.1

Signing status

Integrity checker has been disabled. Integrity cannot be verified.

List of activated apps

Enabled:
 - activity: 2.19.0
 - admin_audit: 1.17.0
 - auto_groups: 1.5.2
 - bruteforcesettings: 2.7.0
 - calendar: 4.6.5
 - cfg_share_links: 4.2.0
 - circles: 27.0.1
 - cloud_federation_api: 1.10.0
 - collectives: 2.9.2
 - comments: 1.17.0
 - contacts: 5.5.2
 - cospend: 1.6.0
 - dashboard: 7.7.0
 - dav: 1.27.0
 - deck: 1.11.4
 - event_update_notification: 2.3.0
 - external: 5.2.1
 - federatedfilesharing: 1.17.0
 - files: 1.22.0
 - files_antivirus: 5.4.2
 - files_mindmap: 0.0.30
 - files_pdfviewer: 2.8.0
 - files_reminders: 1.0.0
 - files_sharing: 1.19.0
 - files_trashbin: 1.17.0
 - files_versions: 1.20.0
 - forms: 3.4.6
 - gestion: 2.4.3
 - group_default_quota: 0.1.7
 - groupfolders: 15.3.4
 - integration_youtube: 0.1.5
 - logreader: 2.12.0
 - lookup_server_connector: 1.15.0
 - mail: 3.5.6
 - money: 0.25.1
 - nextcloud-aio: 0.4.0
 - nextcloud_announcements: 1.16.0
 - notes: 4.9.2
 - notifications: 2.15.0
 - notify_push: 0.6.9
 - oauth2: 1.15.1
 - onlyoffice: 8.2.4
 - password_policy: 1.17.0
 - polls: 5.4.3
 - provisioning_api: 1.17.0
 - quota_warning: 1.18.0
 - registration: 2.2.0
 - settings: 1.9.0
 - sharebymail: 1.17.0
 - side_menu: 3.11.8
 - spreed: 17.1.5
 - support: 1.10.0
 - suspicious_login: 5.0.0
 - tasks: 0.15.0
 - terms_of_service: 2.3.1
 - text: 3.8.0
 - theming: 2.2.0
 - timemanager: 0.3.11
 - timetracker: 0.0.81
 - twofactor_backupcodes: 1.16.0
 - unroundedcorners: 1.1.2
 - user_status: 1.7.0
 - viewer: 2.1.0
 - welcome: 1.0.10
 - workflowengine: 2.9.0
Disabled:
 - contactsinteraction: 1.6.0
 - encryption
 - federation: 1.17.0
 - files_external
 - files_rightclick: 1.5.0
 - firstrunwizard: 2.14.0
 - photos: 2.3.0
 - privacy: 1.10.0
 - recommendations: 1.4.0
 - related_resources: 1.1.0-alpha1
 - serverinfo: 1.16.0
 - survey_client: 1.13.0
 - systemtags: 1.16.0
 - twofactor_totp: 7.0.0
 - user_ldap
 - weather_status: 1.5.0

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "overwriteprotocol": "https",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "domain.net",

    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/lib\/docker\/volumes\/nextcloud_aio_nextcloud\/_data\/skeleton",
    "dbtype": "pgsql",
    "version": "27.1.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "check_data_directory_permissions": true,
    "maintenance": false,
    "loglevel": "2",
    "log_type": "file",
    "logfile": "\/var\/www\/html\/data\/nextcloud.log",
    "log_rotate_size": "10485760",
    "log.condition": {
        "apps": [
            "admin_audit"
        ]
    },
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "enabledPreviewProviders": {
        "1": "OC\\Preview\\Image",
        "2": "OC\\Preview\\MarkDown",
        "3": "OC\\Preview\\MP3",
        "4": "OC\\Preview\\TXT",
        "5": "OC\\Preview\\OpenDocument",
        "6": "OC\\Preview\\Movie",
        "0": "OC\\Preview\\Imaginary"
    },
    "enable_previews": true,
    "upgrade.disable-web": true,
    "trashbin_retention_obligation": "auto, 30",
    "versions_retention_obligation": "auto, 30",
    "activity_expire_days": "30",
    "simpleSignUpLink.shown": false,
    "share_folder": "\/Shared",
    "one-click-instance": true,
    "one-click-instance.user-limit": 100,
    "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
    "htaccess.RewriteBase": "\/",
    "files_external_allow_create_new_local": true,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "preview_imaginary_url": "http:\/\/nextcloud-aio-imaginary:9000",
    "default_language": "fr",
    "default_locale": "fr_FR",
    "default_phone_region": "FR",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "allow_local_remote_servers": true,
    "updatedirectory": "\/nc-updater",
    "overwritehost": "domain.net",
    "overwrite.cli.url": "https:\/\/domain.net\/",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
    "davstorage.request_timeout": 3600,
    "dbpersistent": false,
    "appsallowlist": [],
    "integrity.check.disabled": true
}

</details>

Cron Configuration: Array
(
[backgroundjobs_mode] => cron
[lastcron] => 1708677965
)

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

Talk configuration:

STUN servers

ip:443

TURN servers

turn:1ip:3478 - udp,tcp

Signaling servers (mode: default):

SIP dialin is disabled

SIP dialout is disabled

https://domain.net/standalone-signaling/ - 1.2.3~docker

Recording servers:

Recording is enabled

Recording consent is set to "default"

no recording server configured

Browser: BRAVE
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by nickvergessen** [comment]
The 0 is invalid iirc. It does not validate as a dingle emoji for unknown reasons

**Comment by nickvergessen** [comment]
The color only works for the avatar so when the emoji could be picked.

**Comment by punkyard** [comment]
sorry I don't understand. Could you reformulate?

**Comment by punkyard** [comment]
ok, I think I get
sorry, my mistake, I probably put too much information at once
I will edit the initial content of the issue - to make it more accessible to understanding

**Comment by DorraJaouad** [comment]
The color picker popover was not rendered due to a missing container. This is only on Talk 17.

**Comment by nickvergessen** [comment]
Ah, fix in https://github.com/nextcloud/spreed/pull/11637

**Comment by punkyard** [comment]
yeah! I like the feeling I'm useful here! 🤣
do I get a pin, a star or som'thin?
