### ISSUE TITLE
Left sidebar padding issue on main

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11601]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

<img width="331" alt="image" src="https://github.com/nextcloud/spreed/assets/1580193/9ecf6fe9-a83f-4353-842b-a5cfff227a7e">

As seen on sermo, the right part of the selected conversation is cut off.

**Comment by SystemKeeper** [comment]
Related to https://github.com/nextcloud/spreed/issues/11494 ?

**Comment by DorraJaouad** [comment]
Regression from https://github.com/nextcloud-libraries/nextcloud-vue/pull/5198/files#r1487603056
