### ISSUE TITLE
Can't go to conversation when forwarding message. happens in the files feature, I use spreed v.12.2.3

### ISSUE THREAD

**Issue by Gibran2075** [nextcloud/spreed#11604]
Hii, I have a problem with forwarding messages, the problem is with the files feature, in the files sidebar I can chat but if I forward it I can't open go to conversation, how do I fix it? i am now using spreed 22.2.3, please help me
![Screenshot (452)](https://github.com/nextcloud/spreed/assets/107015940/510fd5b6-f8c1-4e5f-b716-1152d901669c)

**Comment by nickvergessen** [comment]
Main results in:

![grafik](https://github.com/nextcloud/spreed/assets/213943/eb4c1036-6d11-4fa6-bd78-3a879e7e9a50)

**Comment by Antreesy** [comment]
> is this due to recent changes
> i am now using spreed 22.2.3

Unlikely
