### ISSUE TITLE
hidden 'advanced permissions' window

### ISSUE THREAD

**Issue by punkyard** [nextcloud/spreed#11603]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. go to conversation settings
2. clic advanced permissions

<img width="802" alt="Capture d’écran 2024-02-18 à 15 05 02" src="https://github.com/nextcloud/spreed/assets/59349105/51a359bf-c774-42d2-b3f1-aece61b4cee8">

### Actual behaviour
impossible to access the permission window
which appears behind the setting window !

I had a chance to capture a view of the window
during that very short moment after I clicked the closing cross of the conversation SETTINGS
the advanced setting window can be seen for 1 second and closes too

<img width="447" alt="Capture d’écran 2024-02-18 à 15 05 07" src="https://github.com/nextcloud/spreed/assets/59349105/87127106-8b30-4113-89bd-17f477799c14">

## Talk app
17.1.5

**Custom TURN server configured:** yes
turn:only ip:3478
NC AiO 7.12.1

**Custom STUN server configured:** yes
ip:443
NC AiO

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macos ventura

**Browser name:** brave & safari 

**Browser version:** 85/96/..

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log oh yeah

<img width="671" alt="Capture d’écran 2024-02-18 à 16 33 10" src="https://github.com/nextcloud/spreed/assets/59349105/d664c6e5-aeaa-404c-9e76-4902684898c7">


b) The network log
c) ...
```

</details>

## Server configuration

AiO 7.12.1

**Nextcloud Version:** 27.1.5

**List of activated apps:**
Activity	2.19.0	Featured

Disable
Antivirus for files	5.4.2	

Disable
Auditing / Logging	1.17.0	Featured

Disable
Auto Groups	1.5.2	

Disable
Brute-force settings	2.7.0	Featured

Disable
Calendar	4.6.5	Featured

Disable
Circles	27.0.1	Featured

Disable
Client Push	0.6.9	

Disable
Collectives	2.9.2	

Disable
Comments	1.17.0	Featured

Disable
Configurable Share Links	4.2.0	

Disable
Contacts	5.5.1	Featured

Disable
Cospend	1.6.0	

Disable
Custom menu	3.11.7	

Disable
Dashboard	7.7.0	Featured

Disable
Deck	1.11.4	Featured

Disable
Default group quota	0.1.7	

Disable
Deleted files	1.17.0	Featured

Disable
External sites	5.2.1	Featured

Disable
File reminders	1.0.0	Featured

Disable
File sharing	1.19.0	Featured

Disable
Forms	3.4.5	Featured

Disable
Gestion	2.4.3	

Disable
Group folders	15.3.4	Featured

Disable
Impersonate	1.14.0	Featured

Disable
Log Reader	2.12.0	Featured

Disable
Login notes	1.3.1	

Disable
Mail	3.5.6	Featured

Disable
Mind Map	0.0.30	

Disable
Money	0.24.0	

Disable
Nextcloud All-in-One	0.4.0	

Disable
Nextcloud announcements	1.16.0	Featured

Disable
Notes	4.9.2	Featured

Disable
Notifications	2.15.0	Featured

Disable
Notifications for calendar event updates	2.3.0	

Disable
ONLYOFFICE	8.2.4	Featured

Disable
Password policy	1.17.0	Featured

Disable
PDF viewer	2.8.0	Featured

Disable
Polls	5.4.3	

Disable
Quota warning	1.18.0	

Disable
Registration	2.2.0	

Disable
Share by mail	1.17.0	Featured

Disable
Support	1.10.0	Featured

Disable
Suspicious Login	5.0.0	Featured

Disable
Talk	17.1.5	Featured

Disable
Tasks	0.15.0	Featured

Disable
Terms of service	2.3.1	

Disable
Text	3.8.0	Featured

Disable
Time Tracker	0.0.80	

Disable
TimeManager	0.3.11	

Disable
Unrounded Corners	1.1.2	

Disable
User status	1.7.0	Featured

Disable
Versions	1.20.0	Featured

Disable
Welcome	1.0.10	

Disable
YouTube integration	0.1.5	

Disable
Zipper	1.4.1	

Disable

</details>

**Comment by SystemKeeper** [comment]
Duplicate of https://github.com/nextcloud/spreed/issues/11543 ?

**Comment by punkyard** [comment]
yep, sorry, my mistake
Duplicate of https://github.com/nextcloud/spreed/issues/11543
