### ISSUE TITLE
"Create new conversation" shows above more useful conversation results in search

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#11632]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently when searching for a talk room, for example "design" or "design team", you can not press enter or click the first entry below the search (which is usually the best result) to enter the conversation. If you do press enter or pick the first result, a new empty conversation is created.

**Describe the solution you'd like**
The "Create new conversation" suggestion of course is nice so it should stay, but it should not take precedence over existing conversations. It would be nice to just be able to press enter or click the first result (usually the most fitting one) to go into the conversation.
**A sensible solution to take these requirements into account seems to be to simply move the "Create new conversation" suggestion to the end of the "Conversations" list in the results.**
(This incidentally also reduces the height and noise of sections – and it further seems that the whitespace between the section headings and the results can be reduced.)

Current | Proposal
-|-
![image](https://github.com/nextcloud/spreed/assets/925062/560d8274-9cb9-48ff-9e3b-95690967883a)|![image](https://github.com/nextcloud/spreed/assets/925062/8512a8be-f142-41b4-a4a2-9c1d16d0dac8)

**Comment by nickvergessen** [comment]
I would keep it distinct from the existing conversations to clearly indicate it creates a new one.

But yeah makes sense to move it below the existing conversations, so it's also closer to the user/group/team results which also create new conversations
