### ISSUE TITLE
Chat flow experience

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1164]
After a little discussion we decided to handle the chat like the following:

The conversation list contains the last read message id, from there on the flow should be the following:
* [x] A `-- 🆕 --` marker is shown at 1/3 of the screen
* [x] Below it a set of new messages is loaded (covering the bottom 2/3rds of the screen)
* [x] Above the marker old messages are being loaded, serving context for the new messages

More details:
* [x] When there are too few "new" messages available, of course the `-- 🆕 --` marker should be moved down (and hidden when there are none at all) and more old messages should be shown instead.
* [x] When you scroll up, the read marker is not changed.
* [x] When you scroll down, the read marker should be set to the last message id that was displayed on the screen.
* [ ] If you scroll up, after scrolling down, *ideally* the `-- 🆕 --` marker is moved after the message that is the last one that was on the screen.
* [ ] If you are far in the past or not "at the bottom" and there is a new chat message written just now, a "⏬" button should be displayed, which allows you to jump to the bottom of the conversation. (current implementations of iOS and Android are fine)
* [ ] If there are unread mentions between `-- 🆕 --` and the bottom of the conversation (room API `unreadMention`), a `@` button should be displayed, which allows you to jump to the next unread mention.

```
  old
  old
-- 🆕 --
  new
  new
  new     
  new     @  ⏬
```

### Sub issues

- [ ] #3825

**Comment by nickvergessen** [comment]
# Pre 17
Currently both mobile clients seem to do the following:
1. `lookIntoFuture=0&lastKnownMessageId=-1` or `lookINtoFuture=0&lastKnownMessageId=0`
2. From the response they take the newest message `<23>` (not the one from the header) to start waiting for new messages: `lookIntoFuture=1&lastKnownMessageId=<23>`

# 17
Instead the following should happen (after #2135  is in, so beta2, but you can assume it works like this in all 7, so when the `chat-read-marker` capability is there)
1. Get `lastReadMessage` `<42>` from the conversation list for this conversation
2. Load history: `lookIntoFuture=0&lastKnownMessageId=<42>&includeLastKnown=1`
3. Load future (can happen in parallel): `lookIntoFuture=1&lastKnownMessageId=<42>`

# 17 but nice :heart_eyes_cat: 
Depending on the amount of work load, the read flag should be set manually on scroll (see initial post). In those cases you would use `lookIntoFuture=1&lastKnownMessageId=<42>&setReadMarker=0` in the 3rd request.
Afterwards you always wait a reasonable amount of time and then [set the read-marker](https://nextcloud-talk.readthedocs.io/en/latest/chat/#mark-chat-as-read) to the last message that was actually shown in the UI, so when a user goes in, sees 2 more messages, you mark 44 as read, instead of 100 (assuming it was the last message you received).

**Comment by PVince81** [comment]
setting milestone to 22 since the PR also is

**Comment by PVince81** [comment]
how about reusing the "scroll to bottom" button with three possible states:

- if the read marker is below the current view, clicking the button scrolls to the first unread message
- if the read marker is more than half of the page at the top, and a "next unread mention" exists, the button becomes blue and clicking it scrolls to the next unread mention
- if neither read marker or next unread mention exist below, clicking the button scrolls to bottom

Otherwise we'd have a lot of buttons for all these functions.

@ma12-co @nickvergessen thoughts ?

Detecting these conditions might be a bit tricky.

Also unclear: do we iterate over all the unread mentions or just jump to the first one and mark it as read by clearing the DB field ?

**Comment by PVince81** [comment]
I've also updated the top checkboxes to reflect what is already working in https://github.com/nextcloud/spreed/pull/3825

Remaining is mostly the mention and jumping handling.

**Comment by nickvergessen** [comment]
the "scroll to bottom" didnt exist back then, so makes sense to rethink it with the current state. the discussion also took place 2.5y ago

**Comment by nickvergessen** [comment]
> if the read marker is more than half of the page at the top, and a "next unread mention" exists, the button becomes blue and clicking it scrolls to the next unread mention 

we dont have such an info available. you would need to parse it out of the message store

**Comment by PVince81** [comment]
@nickvergessen what about the field "last_mention_message" ?

**Comment by nickvergessen** [comment]
well its the last mention, so when you are mentioned twice the first one would be skipped. of course you could use it as an indicator if you need to check the messages store, but it wont help you to jump to the "next" mention, only the "last"

**Comment by PVince81** [comment]
Okay, so maybe for now we skip the mention part as it would likely need backend additions to keep track of the first unread mention. If we go with frontend route, we could add such button later that triggers the heavy logic that scans the store for mentions starting with the "lastReadMessage" entry.
