### ISSUE TITLE
Implementation of a whiteboard

### ISSUE THREAD

**Issue by 105Dezibel** [nextcloud/spreed#1167]
It would be great if there was also a whiteboard in a call-session avalable. by example the cracker0dks/whiteboard

Its great in any ways

**Comment by sunjam** [comment]
[Here is the link to the Github page for cracker0dks/whiteboard](https://github.com/cracker0dks/whiteboard).

[Would it be possible to use the existing draw.io app for this kind of realtime collaboration?](https://github.com/pawelrojek/nextcloud-drawio)

**Comment by 105Dezibel** [comment]
Yes, when it’s integrated into the Talk app would be great. So, it wold be accessible from all visitors in a call. I think it would give an outstanding advantage to nextcloude compared to Skype ore other solutions. I-am completely new to nextcloud. I’m still testing it out, but I’m already impressed.

Thank you for your reply
Leo

**Comment by helmut72** [comment]
> advantage to nextcloude compared to Skype

No advantage, because Whiteboard is integrated in Microsoft Teams, successor of Skype and Skype for Business. Sadly they are ahead for this topic and this is recognized by companies.

https://products.office.com/de-de/microsoft-whiteboard/digital-whiteboard-app

It's not just drawing some bad forms from the "artist"/user, it recreate and resize forms on the fly.

**Comment by yrammos** [comment]
Yes, but being part of the NextCloud ecosystem is in itself an advantage :) Just as it makes sense to have a word processor or spreadsheet on NextCloud, there are likewise countless cases for a collaborative whiteboard on NextCloud. The question is, who's going to put in the necessary resources (work-hours).

**Comment by ruedigerkupper** [comment]
Just for the record: Here's a Bavarian company combining Jitsi (which is WebRTC), Etherpad and whiteboard into one experience. (All of which is FOSS.) It's quite appealing, I think:
https://meetzi.de/
You can test it out anonymously right from this page.
Something like this would be really nice having in Talk.

**Comment by sunjam** [comment]
That whiteboard is called Etherpad-lite [1] and it is already available
within Nextcloud via the Ownpad app [2]
- https://etherpad.org/
- https://apps.nextcloud.com/apps/ownpad

**Comment by ruedigerkupper** [comment]
Nice! But as I read from he documentation, this app only manages links to files stored on an external etherpad instance. Would be really nice to have it running inside Nextcloud.
BTW the whiteboard is https://github.com/cracker0dks/whiteboard
It's obvious that these apps can be used together, but what makes https://meetzi.de/ so intriguing is that they combine all three into one application. You never have to leave the site or switch browser tabs to change between video chat, etherpad and whiteboard. It is all just one click away.

**Comment by nickvergessen** [comment]
When ownpad would implement the viewer API of Nextcloud, that would work too in the upcoming version.

**Comment by nickvergessen** [comment]
Done by @eneiluj  in https://github.com/nextcloud/integration_whiteboard/

**Comment by nickvergessen** [comment]
Closing as per above.
