### ISSUE TITLE
Unable to Manage Group Conversation as Moderator

### ISSUE THREAD

**Issue by parsman** [nextcloud/spreed#11717]
I am currently facing an issue where the creator of a group conversation in Talk Nextcloud is not available, and as a moderator, I am unable to add new members to the conversation. Since the creator is not accessible, I need assistance in adding a new admin to the group who can have full access to manage the conversation.

Could you please guide me on how to add a new admin or resolve this issue?

**Comment by SystemKeeper** [comment]
Hey, as a moderator you should be able to add new members to the conversation in general, this is independent of "the owner". If you need to change conversations where you're not a moderator, you need to use occ (see https://nextcloud-talk.readthedocs.io/en/latest/occ/).

If you have any questions, feel free to head over to https://help.nextcloud.com as this seems not to be a bug after all :)
