### ISSUE TITLE
Add indicator showing who is speaking right now during conversation

### ISSUE THREAD

**Issue by pktiuk** [nextcloud/spreed#11729]
**Is your feature request related to a problem? Please describe.**

When I talk with new people I don't know it is difficult to see who is currently talking. (Especially when there is no camera image)

**Describe the solution you'd like**

Some kind of indicator showing who talks.  
Either small icon on top of  the tile showing selected participant.  
![image](https://github.com/nextcloud/spreed/assets/45544416/ff282d0b-2cc8-4f9a-9bf4-69caaa4476be)  
Either some kind of thick border around the window of selected user.

**Describe alternatives you've considered**

Asking everyone to enable camera.

**Additional context**

**Comment by pktiuk** [comment]
I couldn't find any similar issue.    
I am a bit surprised that this is not implemented yet.

**Comment by nickvergessen** [comment]
There is a "3px white border" around the video/avatar placeholder of the person:
![grafik](https://github.com/nextcloud/spreed/assets/213943/a95a7d48-8f77-4355-91f6-3a1b91335af0)

**Comment by pktiuk** [comment]
Maybe I should report it as a bug, because I didn't have these borders.

**Comment by nickvergessen** [comment]
Maybe you jsut turn it into a bug report by providing the versions you are using, browser and OS information and maybe a quick screen recording additionally :)

**Comment by pktiuk** [comment]
Should I see this when I am alone in the conversation? (It would be easier to show it on video)

**Comment by SystemKeeper** [comment]
> There is a "3px white border" around the video/avatar placeholder of the person:

Also a blue border on the participant in the participant tab.

Please add the information about your system. Like nextcloud version, talk version, etc. Are you using only web or any mobile client as well?

**Comment by pktiuk** [comment]
This was Talk in version 17.1. Nextcloud version: 27.1.7

I used it with Firefox 123 on Ubuntu.   
My friend used Chrome on Ubuntu and also had this problem. He said, that he had also this problem. 

But after some time this issue disappeared and I am no longer able to reproduce this.
