### ISSUE TITLE
Evaluate "inCall" bit flags in UI

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1174]
Now that #914 has landed, the UI should be updated to handle the "inCall" flags. Most important the `FLAG_WITH_VIDEO` which will not be set if a participant doesn't send video:
https://github.com/nextcloud/spreed/blob/be28b56d0a7524f0ffe40b5b0a2e65c4d35c15b9/js/app.js#L41

Currently a black video panel is shown even though the participant will never send video.

**Comment by nickvergessen** [comment]
Not the case anymore in Talk 9 :)
