### ISSUE TITLE
Prevent accidentally leaving call

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1175]
## Steps to reproduce
1. Be in a call
2. Forget that clicking anywhere else (other conversation in the list, other app in header) will drop the call
3. Click on another conversation to read messages. ;)

### Expected behaviour
You should continue to be in the call.

### Actual behaviour
You are dropped from the call and need to rejoin.

## There are several ways we could mitigate this problem:

1. Automatic: As soon as you are in a call, clicking on anything which would drop the call or switch the view (which leads to dropping) could automatically open in a new tab. This is the most automatic way, but also unexpected.
2. Confirmation: As soon as you are in a call, clicking on anything which would drop the call or switch the view (which leads to dropping) could ask people if they want to leave the call. This is quite annoying as popups are rarely read. When you click "OK" out of habit and then the call drops it’s even more annoying.
3. Keeping call active in background: This would be possible somewhat when staying in the Talk app, but is definitely more difficult when you navigate in a way which forces a full refresh. Future stuff.

I’d say that measure 1 (opening these call-dropping navigation elements in a new tab during an active call) is the best short-term solution. Then in the future when at some point we have 3 implemented, we can drop that.

What do you think @nickvergessen @Ivansss?

**Comment by nickvergessen** [comment]
Duplicate #259

**Comment by jancborchardt** [comment]
Reopening cause this issue has a design discussion and more info on it.

**Comment by MorrisJobke** [comment]
> 3. Keeping call active in background: This would be possible somewhat when staying in the Talk app, but is definitely more difficult when you navigate in a way which forces a full refresh. Future stuff.

It seems that this option is what I requested in #1228.

I guess this is sooner or later on the roadmap once talk calls are being integrated into other apps, because then the call is just something ontop of other apps, which means that you can switch to other messages in talk without dropping the call.

**Comment by jancborchardt** [comment]
@evaryont not really. The only workaround is to do the call in a separate window or tab.
