### ISSUE TITLE
Disappearing screen share button

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#11751]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call
2. Start screen sharing
3. Stop screen sharing

Noticed on Firefox 123.0.1 (64-bit).

Please check screen recording:
[vokoscreenNG-2024-03-08_12-06-02.webm](https://github.com/nextcloud/spreed/assets/85954408/71b1bcd7-9584-4e83-b8ac-27f295b6a6fd)

### Expected behaviour
The screen sharing button shouldn't disappear.

### Actual behaviour
The screen sharing button disappears.

## Talk app

**Talk app version:** 18.0.3

**Custom Signaling server configured:** yes (v1.2.2)

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 22.04 LTS 

**Web server:** Apache

**PHP version:** 8.1

**Nextcloud Version:** 28.0.3

**Comment by nickvergessen** [comment]
Already fixed with https://github.com/nextcloud/spreed/pull/11721
