### ISSUE TITLE
Flow: two messages are created 

### ISSUE THREAD

**Issue by X3PPY** [nextcloud/spreed#11787]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Created a flow “Write to conversation”
When: File updated and file name is test.txt
2. Update file test.txt
3. Check Talk

### Expected behaviour
One message should come

### Actual behaviour
Two identical messages arrive

## Talk app

**Talk app version:** 18.0.5

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 22.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1

**Nextcloud Version:** 28.0.3

**Comment by nickvergessen** [comment]
I can not reproduce this, but at the same time if the workflow's are triggered twice there is nothing Talk can fix about it.
