### ISSUE TITLE
chat integration via slash command

### ISSUE THREAD

**Issue by mapson01** [nextcloud/spreed#1179]
The uses of tag for external apps permit integration and interaction helping to promote single workspace like SLACK a /command will help to this. From my point of view it not necessary to be fancy,  just a system() call and userid like variable and a text response will make integration apps easy for every one..... Just and idea.

cheers
a good guide https://api.slack.com/slash-commands

**Comment by nickvergessen** [comment]
We want apps to be able to "react to" and parse chat messages.
Base work is done with #1168 

Anyone could then work on an app that allows such commands in the chat.
