### ISSUE TITLE
Own video sizing glitch when third participant joins call

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#118]
1. Have a group call with 2 people in the room
2. Third person joins the room
3. See how your own video becomes real big for a second, then smaller

I think the issue here is that `participants-3` is set before the `.videoContainer` is added to the `#videos` element. This causes flexbox to think there’s only 2 elements and gives them both the available space.

Can we make sure that the .videoContainer is inserted before the participants counter is updated? cc @LukasReschke

**Comment by nickvergessen** [comment]
Will be dealt with in #1056
