### ISSUE TITLE
Mentioning is broken when whitespace is removed

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11813]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Mention Person A
2. Mention Person B
3. Make sure there's no space between the mention chips

### Expected behaviour
Mentioning should still work

### Actual behaviour

https://github.com/nextcloud/spreed/assets/1580193/2d0caee0-d1e6-4010-a8d5-15a6d9599fad

Could argue that it's expected to fail, but since the chip is still rendered, it gives the feeling of everything working fine.

## Talk app

**Talk app version:** main

**Comment by nickvergessen** [comment]
> Make sure there's no space between the mention chips

That's a human error and nothing we can fix :shrug: 

Last week Ivan and you complained about the double space, so we removed one, now you remove the other and complain again?

**Comment by SystemKeeper** [comment]
> That's a human error and nothing we can fix 🤷

Well, if the inputbar shows it correctly, but is not handled by the server, I don't think this is purely a human error. If this is not possible, why is the autocomplete opened for a "@" without a space in front?

> Last week Ivan and you complained about the double space, so we removed one, now you remove the other and complain again?

Not intentionally when it happened the first time, just here for reproduction. But still, this is something different, when you look at the issue (https://github.com/nextcloud-libraries/nextcloud-vue/issues/4127) this is about showing something different in the input, then what is send to the server.

**Comment by nickvergessen** [comment]
Sounds liek https://github.com/nextcloud-libraries/nextcloud-vue/issues/5351 then

**Comment by SystemKeeper** [comment]
Opened at https://github.com/nextcloud-libraries/nextcloud-vue/issues/5410
