### ISSUE TITLE
Member RTCIceServer.urls is required and must be an instance of (DOMString or sequence)

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#1182]
## Steps to reproduce
n/a, found on Sentry

### Expected behaviour
No error

### Actual behaviour (and stack trace)
https://sentry.rullzer.com/share/issue/8f251775d96049c7b8f96ffe9c2cad73/

## Browser

![bildschirmfoto von 2018-09-10 14-04-02](https://user-images.githubusercontent.com/1374172/45296471-6a226080-b502-11e8-8ca3-37cddffe2acc.png)

### Browser log

![bildschirmfoto von 2018-09-10 14-04-29](https://user-images.githubusercontent.com/1374172/45296484-78707c80-b502-11e8-856d-8bc200eb4c35.png)

**Comment by nickvergessen** [comment]
Safari can not be supported currently as per #1076

**Comment by ChristophWurst** [comment]
Alright, didn't know :+1:
