### ISSUE TITLE
Ability to add a title or topic for chat

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/spreed#1184]
### Expected behaviour
It would be nice to be able to add a title to chat rooms.  

Use case, discussing a feature for development.  The decision I then put into Deck or Tasks, but the thread regarding the decision may need to be referenced.

This would fit in with the request to archive chats as well.

**Comment by nickvergessen** [comment]
You can currently change the name of a conversation already.
Just hover the current name in the right sidebar at the top (will make a pencil appear) and then click it.

Or do you need a title in addition to the name?!

**Comment by ashgoodman** [comment]
@nickvergessen  If the conversation name could be changed that would be brillilant. I wouldn't need a title also.

But that feature isn't working for me. I tried on Firefox and Chrome on Ubuntu 18.04 Desktop. Hovering over conversation title in the right sidebar does not make a pencil icon appear for me.

Nextcloud is also running on an Ubuntu server (18.04.01 LTS) Nextcloud version 13.0.5 installed via snap
Talk App version 3.2.5

**Comment by nickvergessen** [comment]
Ah, yeah it doesn't work for one2one rooms. When you tick the share box it is transformed into a public room (which has editable names) and on untick it becomes a group room (also editable name).

You can also just type the room name into the dropdown next time and then create the conversation. Then it should have this name already ;)

**Comment by ashgoodman** [comment]
Typing the name and then creating doesn't work - the room doesn't have the name I typed. Instead, it has the name "New Conversation." But it does make it editable right away.

Group convos are still private - only those users invited can see it?

Public are visible to all users on the server?

**Comment by Ivansss** [comment]
> Typing the name and then creating doesn't work - the room doesn't have the name I typed. Instead, it has the name "New Conversation." But it does make it editable right away.

Typing the name and then create is only possible on Talk 4.0 for Nextcloud 14.

> Group convos are still private - only those users invited can see it?

That's right :)
> Public are visible to all users on the server?

Public rooms can be accessed by anyone who owns the link to it.
They don't need to be users of your server.
That's why you can also protect that rooms with a password.
If you add users from your server to that room, they will see that room in their room list.
And if a user from your server follow the public link, they will be automatically added to the room as participants.

**Comment by ashgoodman** [comment]
Great, thanks for the assist. Closing as editing convo names = titles for my use case
