### ISSUE TITLE
Configuration from config.php

### ISSUE THREAD

**Issue by pschichtel** [nextcloud/spreed#11851]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Describe the solution you'd like**

It would be great to be able to configure spreed from files. This would simplify infrastructure as code setups. I personally hate it when I have to remember (and/or document) all the little configuration changes I (have to) make in the UI in case I ever have to setup nextcloud from scratch. Especially with all the configuration needed for the various high performance backends (spreed, notify_push, ...) this quickly gets unmanagable.

I'm suggesting this as a configuration source additional to the appconfig values as to leave the current config process unchanged.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by SystemKeeper** [comment]
From what you listed, you should be able to achieve everything through occ, see https://nextcloud-talk.readthedocs.io/en/latest/occ/

**Comment by pschichtel** [comment]
@SystemKeeper true, but that makes the automation a lot more complicated:

* i have to check that nextcloud and its database are fully operational and relevant apps are installed+enabled (especially directly after setup, when this would come into play)
* with containerized deployments I have to inject commands into the container from the outside or run a another instance of the nextcloud container with (hopefully) the same configuration as the main application to run the occ commands
* the currently available talk:* commands don't seem to support a declarative way of configuring things like "this is the list of stun servers", so I have to first list, diff that with what I want and perform corrective commands

I would be perfectly fine with just being able to change the defaults. I think there is #9182 which tries to remove the STUN server for example. If the default is configurable in the config.php, then configuring an empty list could be a solution for that issue.

**Comment by nickvergessen** [comment]
Apps are not supposed to use config.php (Called system config), so that is not really an option.
In fact we try to move things out of it since a long time and make sure new configs are stored in the database instead.
But you can put all the `occ config:app:set` or `occ talk:...` calls into a bash file if that makes you feel better.

The commands to manage stun, turn and signaling servers haven't been touched in a long time, so if they could be improved for better management of the servers I'm happy to receive input on what things you try to do but are unable to do properly.

**Comment by pschichtel** [comment]
Unfortunate to see config files go away. What's the reasoning there? (if that has been asked before I link would be fine)

> I'm happy to receive input on what things you try to do but are unable to do properly.

As I said: A declarative way to configure the servers would be nice, but if I already have to write a script externally I might as well do the diffing myself.

**Comment by pschichtel** [comment]
@nickvergessen while scripting this stuff: The stun and turn commands allow adding the same server multiple times with the exact same config. It would be helpful if duplicates would be ignored

**Comment by nickvergessen** [comment]
> It would be helpful if duplicates would be ignored

That sounds like a bug indeed.

> Unfortunate to see config files go away. What's the reasoning there?

Clustered setups. If you maintain an instance that is distributed over multiple server / datacenters / etc. it's problematic if you have to redeploy changed files just to change an app option. Each individual node needs to be "off" to apply changes, etc.
The database is in mostcases set up as a master-slave setup and works better and quicker for changes in this case.

**Comment by nickvergessen** [comment]
If you have more things that could be improved, feel free to create individual issues.
