### ISSUE TITLE
Poll rounding error

### ISSUE THREAD

**Issue by moritztim** [nextcloud/spreed#11867]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a poll
2. Have a bunch of people vote
3. Watch the numbers

### Expected behaviour
Tell us what should happen

### Actual behaviour
![iOS](https://github.com/nextcloud/spreed/assets/90388353/373c8c09-a94d-428d-a6a5-ff68877e47e6)
![Android](https://github.com/nextcloud/spreed/assets/90388353/7ee8220f-432f-46ae-a1d9-5bb58fedd8ce)
![Linux](https://github.com/nextcloud/spreed/assets/90388353/6b8c8093-0bb5-40af-938e-5918cd08c174)
Desktop
The math is not mathing.
`69+30=99`

## Talk app
I don't currently have access to the server but I can get access if you need me to.

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** n/a

**Camera available:** n/a

**Operating system:** Arch Linux, iOS, Android

**Browser name:** Native App

**Browser version:** respectively latest versions

### Browser log

n/a

## Server configuration
I don't currently have access to the server but I can get access if you need me to.

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Can you tell us the real numbers of the options?

**Comment by fancycode** [comment]
You could round all but the last number and use `100 - SumOfOtherNumbers` for that.

**Comment by moritztim** [comment]
![13](https://github.com/user-attachments/assets/999bd2e9-f1a5-4785-b694-91cab4b44047)
It seems like it's not even being rounded, because `11/13 ≈ 0.8462`, which, when rounded to two digits would be `0.85`, not `0.84`

**Comment by ShGKme** [comment]
We don't round it but just show int number indeed 

https://github.com/nextcloud/spreed/blob/df923967fa31f9abe1c674f43b2ed88f3064415b/src/components/PollViewer/PollViewer.vue#L340

**Comment by ShGKme** [comment]
> You could round all but the last number and use `100 - SumOfOtherNumbers` for that.

This makes the result depend on the order of options and may increase an option that was far from new value when there are options with fewer remainders.

I'd say a proper method should result in:
- sum to be <= 100%
- sum to be >= 99%
- if options are equal, better to show sum 99. E.g. 1/3 should be `33% | 33% | 33%` rather than `33% | 33% | 34%`

I think the largest remainder methods may work here with a small adjustment to respect equal values.
