### ISSUE TITLE
Overwriting capability setting does not invalide proxy hash

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#11865]
In https://github.com/nextcloud/spreed/pull/11846 we started overwriting some of the remote capabilities. As this is done after setting the proxy-hash, it will not change the provided proxy-hash. That means for everything we introduce/change in later versions of Talk, clients will not refetch the room capabilities.

**Comment by nickvergessen** [comment]
> That means for everything we introduce/change in later versions of Talk, clients will not refetch the room capabilities.

Since the Talk version is part of the hash as well, I guess it would have worked already, but added it never the less
