### ISSUE TITLE
Web root error in server logs when opening talk app

### ISSUE THREAD

**Issue by leander091** [nextcloud/spreed#1186]
### Steps to reproduce

- A nextcloud 14 instance with minimal two app paths, one writable second not writable.
- Open the talk app.

### Expected behaviour
No errors in the logs regarding the setting of the web root

### Actual behaviour
Error meesage: ResourceLocator can not find a web root (root: /usr/share/webapps/nextcloud/apps/spreed, file: css/spreed/4950-4beb-autocomplete.css?v=7a173342cb0e112d3b11053e87e64a8e, webRoot: , throw: true)

But the css is loading fine.

## Server configuration detail

**Operating system:** Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64

**Webserver:** nginx/1.12.2 (fpm-fcgi)

**Database:** mysql 5.5.56

**PHP version:** 

7.1.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, redis, Zend OPcache

**Nextcloud version:** 14.0.0 - 14.0.0.19

**Updated from an older Nextcloud/ownCloud or fresh install:** 13 

**Where did you install Nextcloud from:** Manual install with zip file

<details><summary>Signing status</summary>

Array
(
    [news] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/ezyang/htmlpurifier/maintenance/.htaccess] => Array
                        (
                            [expected] => 4d51270ac56b1600199cd52c4f0fc34171bb306db59761863c87978049b771a053ebb80c8dda03b4d98bf5e43361ec0e1e1d2ad4b01fc315fb809b40acd23843
                            [current] => 
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.2
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.4.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - metadata: 0.7.0
 - mindmaps: 0.1.0
 - news: 13.0.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - qownnotesapi: 18.8.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 4.0.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_totp: 1.5.0
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - accessibility
 - checksum
 - circles
 - dashboard
 - encryption
 - files_external
 - ocdownloader
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/var\/www\/cloud.domain.com\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/usr\/share\/webapps\/nextcloud\/apps",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.domain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.domain.com",
    "dbtype": "mysql",
    "version": "14.0.0.19",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "tls",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local storage

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Operating system:** Windows 10 1803

## Logs

<details><summary>Browser log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
ResourceLocator can not find a web root (root: /usr/share/webapps/nextcloud/apps/spreed, file: css/spreed/4950-4beb-autocomplete.css?v=7a173342cb0e112d3b11053e87e64a8e, webRoot: , throw: true)
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by nickvergessen** [comment]
Can you please include your server config as requested by the issue template:

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

**Comment by leander091** [comment]
@nickvergessen I have already uploaded the server config, section "configuration"

**Comment by leander091** [comment]
All apps default installed by nextcloud are in the non writable folder. `/var/www/cloud.domain.com/apps `
The apps witch I have installed are located in the writable apps folder `/usr/share/webapps/nextcloud/apps`

**Comment by nickvergessen** [comment]
The problem is, that this dir is not accessible from the web, and the webroot you specified `/apps2` is also invalid, so the error is expected.

If you move the spreed app to the non writable dir it should work without the log message.

**Comment by leander091** [comment]
I'm using a nginx alias to make the secondary app folder accessible from the web. Like this:
`location ~ /apps2/(.*)$ {
    alias /usr/share/webapps/nextcloud/apps/$1;
}
`
The browser is loading the assets (css ,js etcetera) without issues except from the warning message in the logs of nextcloud.

**Comment by nickvergessen** [comment]
Well the php code which is trying to make the path does not go through nginx ;)
So it fails to generate a path with the input, and then just continues with best effort, which works for you
