### ISSUE TITLE
Feature request - add syntax highlighting for commands/code

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#1187]
Add syntax highlighting for commands/code.

Like the integrated editor:

![image](https://user-images.githubusercontent.com/16019165/45599866-838c4680-b9f3-11e8-9533-a6c2e76f96dd.png)

**Comment by nickvergessen** [comment]
Duplicate of #1027

**Comment by owzim** [comment]
@nickvergessen I don't see anything related to code highlighting in issue #1027
