### ISSUE TITLE
Allow to remove a note to myself

### ISSUE THREAD

**Issue by elephantastyczny** [nextcloud/spreed#11902]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Once the note to myself is no longer needed instead of having a possibility to delete it I have to delete a whole conversation as you can delete a note to yourself only within the same day.

<img width="416" alt="image" src="https://github.com/nextcloud/spreed/assets/120596179/1911d52c-066f-416f-b833-d71f6d806bae">

**Describe the solution you'd like**
Allow to delete older than 24 hours note to yourself the same way as it's available within 24 hours.

<img width="631" alt="image" src="https://github.com/nextcloud/spreed/assets/120596179/33fe4687-c80b-498b-bafd-861f848ef2d0">

**Additional context**

**Comment by SystemKeeper** [comment]
> Allow to delete older than 24 hours note to yourself

Not specific to note to self, but in the upcoming talk version 19 you can delete a message at any time.
