### ISSUE TITLE
No flow notifications

### ISSUE THREAD

**Issue by manu-torres** [nextcloud/spreed#11914]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up a flow to post messages on a talk conversation (for example when a file is uploaded with a pattern on the name)

### Expected behaviour
A single message should appear on the conversation with a link to the file and information. Users should get notifications on the mobile app and desktop client if they have them enabled.

### Actual behaviour
The message appears twice (only appeared once before), and no notifications are generated.

## Talk app

**Talk app version:** 18.0.5

**Nextcloud Version:** 28.0.3 installed with AIO. 

## More context

The server was recently updated to 28 from 27 automatically by Nextcloud AIO, the problem has been present since. Notifications for the conversation are working properly (when a user replies to a message). Bot messages appear (twice) and do not generate notifications.

**Comment by nickvergessen** [comment]
The missing notification is mostlikely because you have the chat open.

**Comment by manu-torres** [comment]
> The missing notification is mostlikely because you have the chat open.

Thanks for the reply, but I do not think that's the case. When a regular user posts a message everything works as expected, it's just the nextcloud flow bot messages that do not generate them. Also, for some reason the bot messages appear twice on the chat when they used to appear once every time the event is triggered.

**Comment by nickvergessen** [comment]
I found 2 additional issues:

- *pointed out already* You must not have an active session in the chat
- Before my patch notifications did not work in the "Note to self" conversation
- Before my patch notifications did not work when you yourself created the matching file

---

The duplicate thing I can not reproduce with default flow configuration, so a screenshot of your flow would be helpful

**Comment by nickvergessen** [comment]
Was able to reproduce the "duplicate". Reported it upstream: https://github.com/nextcloud/server/issues/44448
