### ISSUE TITLE
Images are attaching in reverse order

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/spreed#11948]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Paste some image in chat
2. Modal window with list of images will appear
3. Paste some more images. They will be added in chronological order.
4. Send. Attached images will appear in reverse order

### Expected behaviour
Images attaching in same order as you see in modal window.

### Actual behaviour
The order is reversed.
## Talk app

**Talk app version:** 18.0.3

**Comment by Antreesy** [comment]
Hi!

There was a decision made to speed up the file upload to the chat: share process is now processing in parallel, and as a drawback, whichever request reaches the server first, will be the first in the chat list. For now, we consider files that were shared together, as non-dependent on chronological order (unless there were a caption added)

It should be solved in future release with [multiple share support](https://github.com/nextcloud/spreed/issues/11411), but for the versions 18+19 we may reconsider it.
