### ISSUE TITLE
Manually enlarge videos

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1195]
It sometimes happens that in a three-party meeting, the automatic enlarging of the current speaker is not working (or only working for some of the participants). Unfortunately I haven't found a way to reproduce this reliably yet :-/

It would be great if there was a way to manually enlarge / promote a video, e.g. by double-clicking on it?

**Comment by PVince81** [comment]
not sure if it was possible back then but in Talk 10 you can already focus/follow on a video by clicking on it
