### ISSUE TITLE
Talk 18.0.5 not work after update Nextcloud to 28

### ISSUE THREAD

**Issue by pablopcarmona** [nextcloud/spreed#11979]
## Steps to reproduce
1. Update docker container from version 27 to 28
2. **Talk 18.0.5** not works
3. Try to reinstall Talk from Apps administration menu and I read "**Error: This app cannot be enabled because it makes the server unstable**"

When enable Talk app I get this error:
**Error: This app cannot be enabled because it makes the server unstable**

**Operating system**:
Dockerized Linux 5.10.0-28-amd64 x86_64

**Web server:**
Nginx

**Database:** 
MYSQL Version: 10.5.11

**PHP version:** 
8.3.4

**Nextcloud Version:**
28.0.4.1

**List of activated apps:**
<details>
Enabled:
  - activity: 2.20.0
  - calendar: 4.6.7
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - integration_collaboard: 1.0.6
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.7
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.4
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.1.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.1
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - deck: 1.12.2 (installed 1.12.2)
  - encryption: 2.16.0
  - facerecognition: 0.9.31 (installed 0.9.31)
  - files_rightclick: 1.6.0 (installed 1.6.0)
  - groupfolders: 16.0.5 (installed 16.0.5)
  - integration_google: 2.2.0 (installed 2.2.0)
  - onlyoffice: 9.0.0 (installed 9.0.0)
  - richdocuments: 8.3.3 (installed 8.3.3)
  - spreed: 18.0.5 (installed 18.0.5)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_ldap: 1.19.0
</details>

**Nextcloud configuration:**
<details>
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_domains": [
            "esminube.es",
            "nextcloud.esminube.es"
        ],
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "http:\/\/esminube.es",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "default_phone_region": "ES",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "upgrade.disable-web": true,
        "app_install_overwrite": [
            "spreed",
            "files_rightclick"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Comment by nickvergessen** [comment]
Please try to redownload the package and overwrite all files

**Comment by pablopcarmona** [comment]
@nickvergessen when I uninstall talk app, the spreed folder under nextcloud/apps/ path disappear.
I renamed speed folder under nextcloud/data/appdata_oceeb1zy5ril/ also.
I install the talk app again but I've getting the same error: "This app cannot be enabled..."

Can you be more explicit about procedure for reinstall and overwrite? Thanks

**Comment by nickvergessen** [comment]
Can you check your nextcloud.log file if it contains more information as to "why" it seemingly doesn't work

**Comment by pablopcarmona** [comment]
finally i upgraded to nextcloud 29 and installed talk 19 with occ app:install talk
With all this it worked
