### ISSUE TITLE
No mobile push notifications in Talk after server migration

### ISSUE THREAD

**Issue by MochaMoth** [nextcloud/spreed#11995]
### Steps to reproduce

1. Create NC Docker container w/ volumes for data and config
2. Create a MariaDB container and grant privileges to NC w/ volumes for data and config
3. Add the Talk app
4. Add 2 users and have both logged in on mobile (iOS or Android)
5. Send messages to each other - notifications work as expected
6. Shut down NC and MariaDB containers
7. Create a new NC Docker container w/ new volumes for data and config
8. Create a new MariaDB container w/ new volumes for data and config
9. Copy over all volumes 1:1 from first containers to new containers
10. Turn on containers and see that the users and talk chats are persisted properly
11. Send messages to each other - notifications no longer work

### Expected behaviour

Users should receive push notifications to their devices

### Actual behaviour

Users do not receive push notifications

### Device brand and model

Samsung Galaxy Note 20 Ultra

### Android version

13

### Nextcloud Talk app version

18.0.5

### Nextcloud server version

28.0.3

### Talk version

18.1.0

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Server log

```bash
Log file is much to large to provide
```

### Additional information

I have attempted to force reset the connection a few ways:

- Deleted `/data/appdata_xxxxxxx/identityproof/user/*`, then re-opened talk app
- Uninstalled and reinstalled talk app
- removed talk app from server and re-downloaded

I've tried testing notifications with `occ notification:test-push --talk User` and recieved:
```
Trying to push to 1 devices

Language is set to en
Private user key size: 1704
Public user key size: 451
Data to encrypt is: {"nid":3126,"app":"admin_notification_talk","subject":"Testing push notifications","type":"admin_notifications","id":"66052428"}
Signed encrypted push subject
Push notification sent, but 1 failed
```

I can see [here](https://github.com/nextcloud/notifications/blob/stable27/lib/Push.php#L540) that this message is based on the response to the notification server, however it does not offer much to debug with.

**Comment by mahibi** [comment]
looping in @nickvergessen to check if there is anything that can be improved/clarified
