### ISSUE TITLE
Mentions are broken in "todo lists" with github markdown patch

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12009]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Post a message:

```
- [ ] Hi @admin bye
```

### Expected behaviour
Check box shows with mention

### Actual behaviour
mention and everything afterwards is missing:
[Bildschirmaufzeichnung vom 2024-04-05 10-45-41.webm](https://github.com/nextcloud/spreed/assets/213943/dbb81225-531d-4748-a4d9-04ff81d040a0)

```
☐ Hi
```

## Talk app

**Talk app version:** 29+

**Comment by nickvergessen** [comment]
Most annoyingly this break the call-summary-bot or at least makes the assignments invisible :see_no_evil:

**Comment by DorraJaouad** [comment]
It's from upstream, when transforming it into a check box component, it was destructured to take the first label and the input node only.
