### ISSUE TITLE
send without notification is not obvious enough

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/spreed#12008]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Attempting to send messages via "Send without notification" no longer works.
ERR... wait, is this now a toggle?

## Steps to reproduce
1. type message
2. select "Send without notification"
3. message does not send (previously it would send when you selected "Send without notification"

### Expected behaviour
The message sends, silently for the recipient.

### Actual behaviour
Now the option toggles to "Send with notification" but the user only discovers the behaviour change if selecting the `...` menu again?

![image](https://github.com/nextcloud/spreed/assets/7018928/8bb832f2-58b5-400a-8eb4-d373043c8f54)

Suggest:
* either the behaviour return to previous behaviour
* or have an indicator appear that message notification silence is now enabled.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
- Nextcloud Server version 29.0.0 RC2
- Nextcloud Talk version 19.0.0-rc.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...
NixOS/Linux

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 85/96/...
124.0.1

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)
- Nextcloud Server version 29.0.0 RC2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
> either the behaviour return to previous behaviour

That's not an option, as we fixed 2 other complaints with the fix.

> or have an indicator appear that message notification silence is now enabled.

The send icon seems to change, but I agree it's quite subtle.
Could add a "Switch" icon to the popup

**Comment by gerbrent** [comment]
you're right, I never noticed the `Send` icon changed! That's a good solution, but agree w making it more obvious.

**Comment by SystemKeeper** [comment]
While this issue was improved in #12109, it’s still very hard to notice in day-to-day usage. Now the setting is locally saved, so you easily end up in a situation where you send multiple messages as silent, also not intended.

**Comment by DorraJaouad** [comment]
- [ ] Disable silent sent after switching a conversation  
(if there is no draft in the chat input)
- [ ] Make the button (to send as silent) more visible, e.g., with a different color, and also when chat input is empty (voice recording symbol shows)
- [ ] Always show the "silent sent" icon when enabled
- [ ] Change new message placeholder?
- [ ] Show indicator on the message when it was sent silently by others (in place of read-marker?) and for own messages show it in buttons menu of the message
