### ISSUE TITLE
Pressing arrow up on empty input should open last own message for editing

### ISSUE THREAD

**Issue by susnux** [nextcloud/spreed#12010]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Its common among other messenger services to use the arrow up key on the empty input field to open the last own message for editing.

**Describe the solution you'd like**
If the chat message input is empty and arrow-up is pressed, the last own message is opened for editing.

**Describe alternatives you've considered**
Every time clicking the actions menu -> then searching for editing (there are too many option) -> pressing editing manually

**Comment by DorraJaouad** [comment]
We have omitted using simple arrow up press for editing because it is used to navigate in open tribute too.
`Ctrl` + `↑` is the shortcut for editing your last message.

**Comment by nickvergessen** [comment]
TIL! :tada: 

Time to add it to:
![grafik](https://github.com/nextcloud/spreed/assets/213943/0631bdbe-df68-4f23-a332-040dd6ea54e4)

**Comment by susnux** [comment]
:see_no_evil: It is even in the keyboard shortcuts...

The reasoning makes sense for using ctrl + :arrow_up:
