### ISSUE TITLE
File caption is sometimes preserved in inputbar

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12061]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Drag and drop a image to the conversation 
2. Write a caption and send it

### Expected behaviour
The "normal" inputbar of the chat should be empty

### Actual behaviour
Sometimes the file caption is shown in the "normal" inputbar

https://github.com/nextcloud/spreed/assets/1580193/1e2297d8-8e97-4ab9-a9bb-1294698383cb

## Talk app

**Talk app version:** main @ 949d1cab1394d6d31d8891f8f93959bf06e87611 and 19 rc2

## Browser

**Operating system:** MacOS

**Browser name:** Chrome

**Browser version:** 121

**Comment by nickvergessen** [comment]
Been there, reported that
