### ISSUE TITLE
[NCDialog] onMounted is called when there is no active component instance to be associated with

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12102]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open conversation settings of a conversation (click on top bar)

### Actual behaviour

<img width="1090" alt="image" src="https://github.com/nextcloud/spreed/assets/1580193/cb57b4cd-feb8-46ba-8848-d3cdcf571456">

## Talk app

**Talk app version:** main @ 694bd354ea9a5e7baef3ce036a959a7281937e43

**Comment by nickvergessen** [comment]
Should be a vue lib issue

**Comment by Antreesy** [comment]
Tracked in vue-lib and by https://github.com/nextcloud/spreed/issues/11494 (see 8.9.1)
