### ISSUE TITLE
Loading feedback when opening conversation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1211]
Currently we show the emptycontent view "No messages yet" when you open a conversation. This is confusing and could lead you to believe messages where lost.

Only after a second or so the first (oldest) messages are actually shown. The emptycontent view should only be shown when there actually are _no_ messages. When it’s still loading, a loading spinner should be shown with "Loading messages …" below.

**Comment by nickvergessen** [comment]
Rel #1164

**Comment by jancborchardt** [comment]
This is an issue with the Vue.js rewrite as well – we don’t show any loading feedback here, so it looks like the messages are lost.

**Comment by nickvergessen** [comment]
It was not an issue until signaling was brought in. We need to do that correctly. Signaling is currently not happening async so it is blocking everything which is why you feel the lag.

**Comment by nickvergessen** [comment]
Fixed by #2766

**Comment by jancborchardt** [comment]
@nickvergessen :medal_sports:
