### ISSUE TITLE
"Apply settings" button of media settings is difficult to discover, especially on smaller resolutions

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#12120]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Initially when changing my settings, I totally missed that I have to apply them because it looks like this:
![image](https://github.com/nextcloud/spreed/assets/925062/44eff4ff-8c48-4703-b04f-5cf842de43c0)
Only when scrolling down I saw the "Apply settings" button:
![image](https://github.com/nextcloud/spreed/assets/925062/23fe0e0a-2f15-4c73-8245-71fd13a01bf1)

**Describe the solution you'd like**
If the button is necessary, then it would be better if it’s floating so it is visible if it appears. Maybe even rather that it is floating and disabled by default, and gets enabled if there are changes.

**Comment by nickvergessen** [comment]
Could also be above the checkbox and "unchangable" options.
