### ISSUE TITLE
Camera / Microphone is unavailable, if permission were not granted for this site

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#12122]
There seems to be an issue now with Chromium at least.

After resetting permissions and reloading the page:
![grafik](https://github.com/nextcloud/spreed/assets/213943/120c7fd2-ac84-4e90-9297-9e93f631b963)

It's only asking for my camera permission after several seconds and even after granting it does not allow to enable the camera.
Browser console is yelling: `Error getting video stream: OverconstrainedError:`

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/12108#issuecomment-2058751628_

**Comment by nickvergessen** [comment]
Seems to be a Chrome bug. The problem reproduces on 27-30 with `Chromium Version 123.0.6312.122 (Official Build) snap (64-Bit)`

**Comment by Antreesy** [comment]
- Delay between request for mic / request for camera permissions is a common issue for Chromium browsers (observed at Discord as well)
- Overconstrained error isn't reproducible since `Chromium Version 124+`

**Comment by sbe-arg** [comment]
This happens on 124 also
