### ISSUE TITLE
polishing of sidebar in public view

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#12132]
just tested on nc29.0.0b1
- [x] The icons in system dark mode in the header look broken:
  ![image](https://github.com/nextcloud/server/assets/42591237/e039afec-f3f6-4972-b84e-5187b7d5dfb0)
- [x] Also the sidebar toggle button does not seem to work... https://github.com/nextcloud/spreed/pull/12133

**Comment by Pytal** [comment]
Seems to be the Talk public share sidebar, cc @danxuliu

**Comment by nickvergessen** [comment]
Reopening as the icon color and file name color is still wrong if I see that correctly

**Comment by nickvergessen** [comment]
And just for the record, we need to adjust the used variable, not the content of the variable. it claims to be a button tertiary-on-primary, but it's not on primary, it's on the background.
Might be non trivial to solve. Best is to check the color/variable used by the app list when you are logged in

**Comment by Antreesy** [comment]
That's the result of applying `tertiary-no-background`. But I'm not sure it's consistent:
- either both NcButton and NcActions here should have dark color on a dark theme
- or file name and "Download" button should have white color
 
![image](https://github.com/nextcloud/spreed/assets/93392545/2c52fddd-f23c-4f11-813a-8b99d1d7711c)

**Comment by susnux** [comment]
should be fixed with:
https://github.com/nextcloud/server/pull/46785

**Comment by susnux** [comment]
correct color is btw: `--color-background-plain-text`

**Comment by Antreesy** [comment]
Nein, that indeed fixes the file name, but not the button =/

![image](https://github.com/user-attachments/assets/7a8191bf-7b28-4869-87e4-e013bb65e8b9)

It's Talk-only now, so I'll take over from here
