### ISSUE TITLE
Make notifications quicker

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/spreed#12188]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Right now notifications arrive with significant delay. 
In other apps i compared Talk to, notifications arrive almost instantly (Mattermost, Rocketchat, Skype).
Sometimes new messages don't appear, until you switch to the tab with Talk open.
In general it creates an impression of Talk as unreliable and buggy.
It causes a great frustration when using Talk for text messaging.

**Describe the solution you'd like**
Make notifications snappy and more reliable. Allow users to control if they want to receive notifications even when the chat window is open.

**Describe alternatives you've considered**
Use another mechanism for notifying the user about new messages, other than Nextcloud Notification system, maybe?

**Comment by nickvergessen** [comment]
Set up https://github.com/nextcloud/notify_push and they are instant.

**Comment by RTechSn** [comment]
![image](https://github.com/nextcloud/spreed/assets/119056784/969d794d-13ff-47f3-9e66-103960807296)
