### ISSUE TITLE
Add a sharing file system on talk

### ISSUE THREAD

**Issue by SnowFlorent** [nextcloud/spreed#1221]
Sorry for my poor school english.

### Expected behaviour
I think that's interesting to share files in talk module like slack. This functionality could pass some files directly in conversation and depose in some talk's folder in user space.

**Comment by nickvergessen** [comment]
You can already share files from your nextcloud with Talk4.
Just click on the :heavy_plus_sign: next to the chat input.

File upload is planned with #1129

**Comment by SnowFlorent** [comment]
Hi. 

I m in version 3.2.6 and i have + button.

**Comment by Ivansss** [comment]
> I m in version 3.2.6 and i have + button.

I guess you mean that you don't have the + button.
The file picker was introduced in Nextcloud Talk 4.0.
You should update to Nextcloud 14 in order to install Nextcloud Talk 4.0.
