### ISSUE TITLE
Prefer hardware based video encoding

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1223]
A first attempt was started in #1171 

This should be looked into again, after we moved away from SimpleWebRTC (see #1063 ).
Using the current hack from #1171 (which just does it in php instead of a proper js method) already cuts the cpu usage by 25-50%.

**Comment by mokkin** [comment]
Due to the actual corona crisis and the following increase of cloud and talk usage, this issue (and others inside talk) shoul be prioritized.
With a couple of windows opened cpu usage during a 1:1 video call gets really high and the fan blows louder than participants can talk ;)

**Comment by mokkin** [comment]
Today I had a 1:1 call with screen sharing and the cpu load still became very high:
![grafik](https://user-images.githubusercontent.com/2938748/79618932-b0db3200-810b-11ea-9d40-44be72f69def.png)

Browser: Firefox 75.0 on Ubuntu 18.04
actual NC + Talk
Intel® Core™ i5-5200U CPU @ 2.20GHz × 4

Yesterday we had a meeting with four people and the system became almost unusable.

Any idea what's the problem?

**Comment by nickvergessen** [comment]
Did you try to set the config as described in https://github.com/nextcloud/spreed/pull/3153
