### ISSUE TITLE
Mouse pointer is not in the correct location recorded

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/spreed#12245]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. You need two monitors to reproduce this attached to your machine, configured to be layed out side by side
2. Open Talk and start a call
3. Share the right monitor in the session
4. Move the mouse around

### Expected behaviour
The mouse in the screenshare should reflect the position on the monitor

### Actual behaviour
The pointer is not recorded on the right monitor. Instead if you move the pointer in the left monitor (outside the shared region!) it suddenly appears.

## Talk app

This was expected right now (2024-04-30 17:00 CEST) in the cloud.nextcloud.com instance. I have no admin rights to extract these information.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 115.10.0

### Browser log

Does not make sense as no direct error happened.

**Comment by nickvergessen** [comment]
Since we are not actually aware of mouse nor shown region, this should be an issue with your browser or OS

**Comment by nickvergessen** [comment]
Having said that, Firefox 115 is quite old, maybe updating fixes it
