### ISSUE TITLE
conversations I've been invited too via link can't be bookmarked in the www browser and vanish on tab close

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/spreed#12251]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Sign in to a Nextcloud server via www browser.
2. Open a conversation link by someone else for that Nextcloud server.
3. Open the context menu for the conversation and `Add to favorites` will be missing.
4. Close alls browser tab with the conversation opened.
5. Open `https://example.org/apps/spreed/` and the conversation won't be in the list anymore.

Same for removing a conversation from favorites.

### Expected behaviour
The `Add to favorites` menu entry should show up.  
See here for the menu entry that's missing for me: [gif](https://user-images.githubusercontent.com/102530814/166231604-294034e3-5510-4c52-99e4-2bb92837b0ca.gif)

Also the conversation should still be in the list after closing and reopening the browser tab with the Talk app.

### Actual behaviour
`Add to favorites` is missing from the menu.

Conversation is being forgotten when closing the browser tab.

## Talk app

Nextcloud: `27.1.9.1`  
_(don't know how to lookup the Talk app version, because I'm not the administrator of the server)_

## Browser

**Browser name:** Firefox

**Browser version:** 125.0.3

## Additional data
Keep the conversation open in a www browser window. Then open the Android Talk app. There you'll see the conversation while it's open in the browser. Long tap the conversation in the Android app and you can add it to favourites. Upon reloading the browser window you'll also see a star icon at the favorite conversations. Nevertheless the conversation will still vanish when closing the browser tab.

**Comment by nickvergessen** [comment]
The owner needs to make the conversation joinable, otherwise this is the expected behaviour, as users would survive a password adding/changing which is not okay in general.

Ref https://docs.nextcloud.com/server/latest/user_manual/en/talk/talk_basics.html#view-all-open-conversations
