### ISSUE TITLE
✨ Better visibility of smart picker

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12250]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

I noticed that there is no way to discover the smart picker without accidentally typing in a `/`.
We should add a (slash-forward-box) option into the attachment button, with a submenu to show them

**Comment by jancborchardt** [comment]
> We should add a (slash-forward-box) option into the attachment button, with a submenu to show them

Additionally to this, I would recommend to change the attachment "paperclip" icon to a simple "plus".

**Comment by DorraJaouad** [comment]
> with a submenu to show them

Or we can trigger the tribute programmatically

**Comment by DorraJaouad** [comment]
> rather than having 2 entirely different flows.

That's what I tried to avoid indeed.
