### ISSUE TITLE
selfhosted sip solution with asterisk on a hpb server

### ISSUE THREAD

**Issue by comsyspro** [nextcloud/spreed#12279]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)

**Is your feature request related to a problem? Please describe.**
i dpn't know how to integrate selfhosted sip solution with asterisk on a hpb server and there are no infos in the nextcloud documentation.

**Describe the solution you'd like**
i would like to have a selfhosted sip solution with asterisk on a hpb server. is there a tutorial how to set it up? how can you do it?

**Comment by Fuseteam** [comment]
this might help https://help.nextcloud.com/t/sip-gateway-setup/118109/5
But as far as i understand we need a "SIP Adapter" component which is currently offered as a paid product by Stuktur AG.......i haven't had luck finding information on the product however

**Comment by nickvergessen** [comment]
> i haven't had luck finding information on the product however

It's part of the Nextcloud Talk subscription. You can find more information at https://nextcloud.com/talk/

**Comment by Fuseteam** [comment]
> > i haven't had luck finding information on the product however
> 
> It's part of the Nextcloud Talk subscription. You can find more information at https://nextcloud.com/talk/

All that page tells is
> optionally enables connecting a SIP bridge so users can dial in by phone into calls.

It does not tell me much else, not even how it fits in when once has managed to bring up everything else including the PBX

**Comment by comsyspro** [comment]
i have more infos. first you need to have a nextcloud (not community). than you can get from struktur ag a software package with install instructions. as i do only have a demoserver with nextcloud community i couldn't install it. so if someone has a nextcloud userid you can install the sip bridge and then we could look how to install an own asterisk to get it running and to develop a step by step install guide or script. at the moment there is no easy install method for this.

this project uses another approach to make calls but it's not integrated in nextclod talk:
https://apps.nextcloud.com/apps/sip_trip_phone

**Comment by Fuseteam** [comment]
Ah so it comes with a nextcloud subscription itself? i don't know if something like nextcloud AIO would count as a "demo server" hmmm

but yeah sip trip phone, is just een webapp bolted onto nextcloud, that's not what we want xd
