### ISSUE TITLE
Chat in a different room when in a video call

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#1228]
Once you are in a video/audio call you are not able to chat in any other room without leaving the call. Would be nice to able to do that.

cc @nickvergessen

**Comment by nickvergessen** [comment]
You can use a second tab/window to do that.
I do not think we will be able to pull messages in multiple rooms without a major rework of all the JS

**Comment by MorrisJobke** [comment]
> You can use a second tab/window to do that.

🙈 




> I do not think we will be able to pull messages in multiple rooms without a major rework of all the JS

Sadly that means that functionality is sacrificed for technical limitations.

It seems that this one here is a duplicate of an older ticket by @jancborchardt - see #1175
