### ISSUE TITLE
Dashboard error: MessageParser::createMessage(): Argument #3 ($comment) must be of type IComment, null given

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/spreed#12282]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

The problem started after upgrading hub from 28 to 29

```
[no app in context] Error: OCA\Talk\Chat\MessageParser::createMessage(): Argument #3 ($comment) must be of type OCP\Comments\IComment, null given, called in /var/www/html/custom_apps/spreed/lib/Dashboard/TalkWidget.php on line 262 in file '/var/www/html/custom_apps/spreed/lib/Chat/MessageParser.php' line 62
	GET /ocs/v2.php/apps/dashboard/api/v2/widget-items?widgets%5B%5D=spreed
	from xx.xx.xx.xx by username at 6/05/2024, 10:16:54 am
```

deleting all conversations clears the error including self and release notification channel.

odd

![Screenshot from 2024-05-06 10-17-08](https://github.com/nextcloud/spreed/assets/23391642/0152193e-420f-4386-87a9-00726057b96e)

![Screenshot from 2024-05-06 10-28-00](https://github.com/nextcloud/spreed/assets/23391642/150a8e4f-ca0e-42ee-83a4-3afea1443c8e)

![Screenshot from 2024-05-06 10-27-46](https://github.com/nextcloud/spreed/assets/23391642/28008786-5209-4690-8006-c3cab515459e)

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

19.0.0

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

NO

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

YES

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

NO

## Server configuration

**Operating system**: TRUENAS APP

**Nextcloud Version:** 29

**Comment by Antreesy** [comment]
By the error looks like it originates from here: https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Dashboard/TalkWidget.php#L244

If i get it right, `$room->getLastMessage()` might return null for empty conversations (with expired/deleted messages)
