### ISSUE TITLE
⛔ Banning users and guests - API

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12292]
- Overview at https://github.com/nextcloud/spreed/issues/12291

---

- [x] Deliver contract up front https://github.com/nextcloud/spreed/pull/12259
- [x] Implement database model
- [x] Implement Blocking the join
- [x] Add integration tests
- [x] https://github.com/nextcloud/spreed/issues/12670

**Comment by SystemKeeper** [comment]
`RequireModeratorParticipant` is also true for 1:1 conversations. Do we allow blocking in 1:1 ?

**Comment by nickvergessen** [comment]
Answered in https://github.com/nextcloud/spreed/issues/12291

**Comment by nickvergessen** [comment]
- [ ] Banning an IP does not validate the actorId to be a valid IP
- [ ] Banned IP ranges are not checked against guest IPs
