### ISSUE TITLE
In a room show in the chat line if the message has been read for each participant.

### ISSUE THREAD

**Issue by AT-SGAI-CSIC** [nextcloud/spreed#12310]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 28.0.3

**Is your feature request related to a problem? Please describe.**
In chat room, normally dedicated to reporting incidents, we need a confirmation   that the recipients have read the message.
**Describe the solution you'd like**
In a chat group for each message see by the avatars what members has read the message.

**Describe alternatives you've considered**
In others chat systems like element/synapse (matrix) this feature it's very useful. 

**Additional context**
From element/matrix system:

![imagen](https://github.com/nextcloud/spreed/assets/139878963/c58e9b82-1c20-4750-9960-185d06059973)

**Comment by nickvergessen** [comment]
There is ![check](https://github.com/nextcloud/spreed/assets/213943/9f102230-f1f9-401f-ace7-590cb447e712) when the message was sent and ![check-all](https://github.com/nextcloud/spreed/assets/213943/9a80edfe-b0e4-448c-a836-ee029a11aada) when it was read by all users.

We don't have a "number" or "list of users" yet, but that is being covered by https://github.com/nextcloud/spreed/issues/8128

**Comment by Noctisik** [comment]
is

> There is ![check](https://github.com/nextcloud/spreed/assets/213943/9f102230-f1f9-401f-ace7-590cb447e712) when the message was sent and ![check-all](https://private-user-images.githubusercontent.com/213943/329551555-9a80edfe-b0e4-448c-a836-ee029a11aada.svg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1MTc0MjAsIm5iZiI6MTc3MTUxNzEyMCwicGF0aCI6Ii8yMTM5NDMvMzI5NTUxNTU1LTlhODBlZGZlLWIwZTQtNDQ4Yy1hODM2LWVlMDI5YTExYWFkYS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIxOVQxNjA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjYwZTYwNTVhNmI2MGQ5NGQzMDA2NmU3OTUyNTljOGY2MTcxMDc3YWU5ZWMzNjNmZjkyOWYwYjAzMmMyMzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-VD5UjF-YGbFOkOQwGs79wKczg8BdM490inY40oF7fc) when it was read by all users.
> 
> We don't have a "number" or "list of users" yet, but that is being covered by [#8128](https://github.com/nextcloud/spreed/issues/8128)

How is it working in NC Talk for ![check-all](https://private-user-images.githubusercontent.com/213943/329551555-9a80edfe-b0e4-448c-a836-ee029a11aada.svg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE1MTc0MjAsIm5iZiI6MTc3MTUxNzEyMCwicGF0aCI6Ii8yMTM5NDMvMzI5NTUxNTU1LTlhODBlZGZlLWIwZTQtNDQ4Yy1hODM2LWVlMDI5YTExYWFkYS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIxOVQxNjA1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjYwZTYwNTVhNmI2MGQ5NGQzMDA2NmU3OTUyNTljOGY2MTcxMDc3YWU5ZWMzNjNmZjkyOWYwYjAzMmMyMzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-VD5UjF-YGbFOkOQwGs79wKczg8BdM490inY40oF7fc)  to appear when message was read by everyone? I mean if it records a moment when every single user of chat reads a message, then it's possible to make such a list in css + js.

**Comment by Antreesy** [comment]
> How is it working in NC Talk for check-all

Id of last read message in the conversation is tracked per each participant. Then by querying conversations list a minimum value across all participants is defined, this should be a lightweight query.

> then it's possible to make such a list

Now you need to query all participants with value below or above per each message you want to check read receipts for. It's technically doable, but brings another level of server load. Therefore not taken into development phase yet. Please follow the discussion in #8128 if you have any relevant details to add

**Comment by Noctisik** [comment]
> > How is it working in NC Talk for check-all
> 
> Id of last read message in the conversation is tracked per each participant. Then by querying conversations list a minimum value across all participants is defined, this should be a lightweight query.
> 
> > then it's possible to make such a list
> 
> Now you need to query all participants with value below or above per each message you want to check read receipts for. It's technically doable, but brings another level of server load. Therefore not taken into development phase yet. Please follow the discussion in [#8128](https://github.com/nextcloud/spreed/issues/8128) if you have any relevant details to add

Thanks a lot! I see it now.

<img width="491" height="431" alt="Image" src="https://github.com/user-attachments/assets/3d528a1d-4d03-4b73-b891-b8a5e97142c9" />
