### ISSUE TITLE
Chrome and Chromium users don't have the camera and mic detected

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/spreed#12336]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

I can use devices (camera, mic etc) Firefox and forks, Safari but not on any Chromium based browser.
This problem happens for several users and any third party I invite to the organization.

Chrome engine `124`

![image](https://github.com/nextcloud/spreed/assets/23391642/b3949dea-8797-4cda-a4fd-9edf0954e201)
![image](https://github.com/nextcloud/spreed/assets/23391642/1e7a0a34-bd42-4b0e-8c3a-97e2a256b3b9)

**Comment by sbe-arg** [comment]
I noticed this issue https://github.com/nextcloud/spreed/issues/12122

But this is only happening in talk 19 and seems related to https://github.com/nextcloud/spreed/pull/12152

**Comment by sbe-arg** [comment]
@Antreesy ?

**Comment by nickvergessen** [comment]
Well the error in the console seems to indicate that something else is tampering with the security policy of the site.
If Chrome based browsers would not work in general there would be much more issues than 1 after 3 weeks 😅

Do you have a proxy in front of the Nextcloud or other nextdoor apps installed that change the site permissions or CSPs

**Comment by Antreesy** [comment]
To add a bit: found this question opened recently for Chrome support: https://support.google.com/chrome/thread/259019910/camera-access-permission-violation-issue-while-accessing-the-web-app?hl=en

Referencing MDN docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy

Where `Permissions-Policy` header has an alternate name: `Feature-Policy` for **Firefox** and **Safari**

**Comment by nickvergessen** [comment]
Do you mind sharing a public conversation link? Can also be via email `<my github handle>@nextcloud.com`

**Comment by sbe-arg** [comment]
Just sent you the details by mail
