### ISSUE TITLE
Add blurhash to image metadata

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/spreed#12351]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Is your feature request related to a problem? Please describe.**
For showing a preview of an image while it is still loading a blurhash can be used. It is not currently exposed in the metadata though. This was supposed to happen with https://github.com/nextcloud/spreed/issues/10844, but it wasn't added in https://github.com/nextcloud/spreed/pull/11093.

**Comment by SystemKeeper** [comment]
> but it wasn't added in #11093.

Indeed, blurhash was postponed to NC 29, that’s why it was missing from that PR.
