### ISSUE TITLE
Junk automated meta data posts never expires even when message expiration mode is enabled, and cannot be manually deleted

### ISSUE THREAD

**Issue by LMRW** [nextcloud/spreed#12355]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
Latest

**Is your feature request related to a problem? Please describe.**
Yes, the issue is as such.

1. Create a new Nextcloud talk toom
2. Set the messages to expire (example... after 24 hours)
3. Setup the group channel with an icon, name, description, add users
4. Messages expire but the metadata posts such as "You set the description", "You added X users" etc NEVER expire. So the top 2-3inches of an iPhone display when loading that chat room (as messages expire every 24 hours) is always ancient junk information about who named the group, what members were added etc. And this ancient junk info never expires, even though messages do.
5. It's impossible to manually delete them and impossible to make them expire over time so they build up and up to entire screens of junk information users have to scroll past to see real content

**Describe the solution you'd like**
The metadata info automated posts should expire with the same time expirations as messages do when the message expiration tool is enabled.

**Describe alternatives you've considered**
Ability to X off / delete these messages if you are the person who generated them

**Additional context**
Please remember in very old chats where users are added and removed over a year or more, this junk ancient meta information can span entire screens one needs to scroll through to get to real messages

**Screenshots**
Enable message expiration, and the meta information becomes un-deletable spam clogging up entire screens and inches of valuable screen real estate

<img width="781" alt="Screenshot 2024-05-14 at 18 18 10" src="https://github.com/nextcloud/spreed/assets/97672626/ba2fd9cb-b697-4742-9c27-e1c848bad67a">
<img width="655" alt="Screenshot 2024-05-14 at 18 18 26" src="https://github.com/nextcloud/spreed/assets/97672626/127c1523-e716-45b0-9a14-1715b2d828d0">

**Personal note**
Thank you everyone for the incredible Nextcloud & Nextcloud Talk platforms. They are fantastic.
I hope I can help with beta branches ets if needed.

**Comment by SystemKeeper** [comment]
Are you sure you enabled message expiration before doing all these actions? Message expiration only affects messages that are created after enabling the expiration. What you can try is to clear the chat (in conversation setting under danger zone), so these old messages should be removed

**Comment by LMRW** [comment]
The problem is, you cannot enable message expiration without at least a couple of junk messages appearing at top first - it is impossible due to the prescribed order of events we have to follow. There will always be some meta notifications right at the top before you get to the part where you can enable message expiration, meaning you always - no matter what you do - have these messages stuck there forever. And they can pile up taking over an entire phone size screen and cannot be deleted.

**Comment by LMRW** [comment]
Please consider to create a new group chat you have to choose a name at the very least... that name then junks the chat with a non-deletable message about how you set the name... only then can you set expiration after this and that meta message can never ever be deleted ever. If a couple more actions take place like adding users or descriptions or pictures the list gets very long and requires scrolling by the user. I think there either needs to be a way to clear these meta messages, they are not useful long term information.

**Comment by SystemKeeper** [comment]
But you can still clear the chat, which removes the system messages you’re talking about?! (See above)

**Comment by LMRW** [comment]
That's new information for me thank you. It resolved my problem but perhaps it's a little hard to find and others may have the same confusion. Regardless - thank you! For this advice; and your contributions to great software.
