### ISSUE TITLE
Add possibility to restrict app by group

### ISSUE THREAD

**Issue by ntrp** [nextcloud/spreed#1238]
A lot of applications have the possibility to restrict the usage by user group, how comes this one doesn't support that?

**Comment by nickvergessen** [comment]
See #1105

**Comment by ntrp** [comment]
oh ok sorry, I searched the issues but forgot to remove the is open filter.

**Comment by q3wr3** [comment]
I was hoping that you can limit the users to be able to contact only other users from the same group
Can this be achieved in any way?

**Comment by nickvergessen** [comment]
Just restrict the options in the Nextcloud admin sharing
