### ISSUE TITLE
Desktop browser notifications on call and messages 

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/spreed#1239]
## Steps to reproduce
1.Call someone on nextcloud 14
2.the called guy does know he was called because the nextcloud page was not the active one

### Expected behaviour
We should have a browser notifications like hangout or whatsapp , clicking on it would put the focus on the nc page 

### Actual behaviour
no notifications

## Browser : chromium 

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Ubuntu/...

**Browser name:** chromium
**Browser version:** 68 

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
This happens, when the notifications app (it's shipped in the default release package) is enabled.

**Comment by freechelmi** [comment]
Thanks but yes I have Notification 2.2.1 app enabled.

I still don't understand what happen

**Comment by k00ni** [comment]
I also have the notification app (2.7.0) activated on NC 19.0.2 but receive no push notification in the browser. I only got notifications in area behind the bell-icon.
