### ISSUE TITLE
Undo and Redo not working properly while adding new text/link on message text.

### ISSUE THREAD

**Issue by adityagi02** [nextcloud/spreed#12425]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Type something to send.
2. Now select some text and paste(CMD + V) some text(link in my case) in place of it.
3. Now undo(CMD + Z) what you have done, the newly added link remains, and text get undo or deleted accordingly.
4. Keep on doing undo or redo, behaviour persists.

### Expected behaviour
Newly pasted text should go away first, before the base text.

Here is the screen recording:

https://github.com/nextcloud/spreed/assets/77538183/fa8523d0-16d9-4306-895f-e44f51078f38

**Comment by SystemKeeper** [comment]
Sounds like https://github.com/nextcloud-libraries/nextcloud-vue/issues/4101 ?

**Comment by adityagi02** [comment]
> Sounds like https://github.com/nextcloud-libraries/nextcloud-vue/issues/4101 ?

yeah it looks same

**Comment by SystemKeeper** [comment]
Then I will close this here, thanks for the report
