### ISSUE TITLE
Nextcloud 14 compatibility

### ISSUE THREAD

**Issue by GreatEmerald** [nextcloud/spreed#1242]
Trying to install Talk 4.0.0 on Nextcloud 14 doesn't seem to work in my case. The disabled apps view states:

```
This app cannot be installed because the following dependencies are not fulfilled:

    Server version 13 or lower is required.
```

It's technically installed, just can't be enabled, as the button to do so is greyed out. Yet the website states that 4.0.0 should be compatible with Nextcloud 14?

**Comment by nickvergessen** [comment]
if 13 is required, you have 3.3 and not 4.0

Please check whether there is an update button next to it or a "update apps view"

**Comment by GreatEmerald** [comment]
Yes, there was an update button, which asked to confirm with my password. It got installed, but the "enable" button is still grey. Maybe I should remove it and add it again...

**Comment by GreatEmerald** [comment]
Hm, a relogin worked to make the "enable" button work.
So I guess it's a strange upgrade issue, then.
