### ISSUE TITLE
Frontend error: Uncaught SyntaxError: identifier starts immediately after numeric literal

### ISSUE THREAD

**Issue by thegabriele97** [nextcloud/spreed#12430]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

I am unable to open Talk (sometimes it works on new browser, then stops working). Tried different PCs, networks and browsers. Both when logged in and logged out (like inviting a user via public link). On mobile (firefox) it works without problems.

The related error seems to be: 

```
Uncaught SyntaxError: identifier starts immediately after numeric literal talk-main.js:899:2549
```

This is the Console log, look at the differences when it works and when it doesn't:

| *WORKING* | *NOT WORKING* |
|----------|----------|
| ![image](https://github.com/nextcloud/spreed/assets/35406071/903b524c-c4c4-48cc-be1c-4f44f902637d) | ![image](https://github.com/nextcloud/spreed/assets/35406071/b3cec2f2-4f6c-40f2-8ce0-928d057d44c8)| 

## Steps to reproduce
1. Go to https://yourinstance/apps/spreed/
2. See that nothing appears
3. Open the log console

## Talk app

**Talk app version:** 18.0.8

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Ubuntu 20

**Browser name:** Firefox

**Browser version:** 126

</details>

## Server configuration

**Operating system**: Debian 12

**Web server:** Nginx

**Database:** PSQL

**PHP version:** 8.0.1 fpm

**Nextcloud Version:** 28.0.5

**List of activated apps:**
<details>

```
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cfg_share_links: 5.1.0
  - cloud_federation_api: 1.11.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_archive: 1.2.3
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_scripts: 4.0.3
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - firstrunwizard: 2.17.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - memories: 7.3.1
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.2.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.5.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.8
  - support: 1.11.1
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflow_media_converter: 1.11.7
  - workflow_script: 1.13.1
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0 (installed 26.0.0)
  - comments: 1.18.0 (installed 1.16.0)
  - duplicatefinder: 1.1.10 (installed 1.1.10)
  - encryption: 2.16.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_versions: 1.21.0 (installed 1.19.1)
  - metadata: 0.20.0 (installed 0.20.0)
  - ncdownloader: 1.0.20 (installed 1.0.20)
  - suspicious_login: 6.0.0 (installed 5.0.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.6.0)

```
</details>

**Nextcloud configuration:**

<details>
```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "2": "nxc.g97.top",
            "3": "davnxc.g97.top"
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.5.1",
        "overwrite.cli.url": "https:\/\/nxc.g97.top",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filesystem_check_changes": 1,
        "trashbin_retention_obligation": "auto, 30",
        "overwritewebroot": "\/",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "ffmpeg": "\/usr\/local\/bin\/ffmpeg",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF"
        ],
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "cfg_share_links"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "2587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "onlyoffice": {
            "editors_check_interval": 0
        },
        "enforce_theme": "",
        "ncd_admin_settings": {
            "disallow_aria2_settings": "1"
        },
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.disable": false,
        "memories.vod.ffprobe": "\/usr\/local\/bin\/ffprobe",
        "memories.video_default_quality": "-2",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.vaapi": true
    }
}
```
</details>

### Server log (data/nextcloud.log)

No relevant log about the error.

**Comment by Antreesy** [comment]
> This is the Console log

Hi! Could you provide more information on this?
- Information from [Learn More]
- Screenshot from Sources panel (line talk-main.js:899:2549 and around)
- Did you experience it before update https://github.com/nextcloud/spreed/compare/v18.0.7...v18.0.8 ?

Otherwise I couldn't identify, from there it might come from. Unlikely from the src code, but could be any of the libraries we bumped in that release.

**Comment by thegabriele97** [comment]
I had to refresh with CTRL+R a few times before let the error appearing again.

- Larn more redirects to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
- It is strange but I don't have talk-main.js in apps/spreed/j:
![image](https://github.com/nextcloud/spreed/assets/35406071/7b5b5a51-ee51-42f9-9dd6-4ba36b526400)
If I click on talk-main.js:899:2549 in the log console, in redirects me to the url where the js should be but I am not expert but it seems wrong as js file. It has a "stack trace" at the beginning. Maybe this is why it gives me the error? because the js is created/loaded wrongly. 
![image](https://github.com/nextcloud/spreed/assets/35406071/a55cfc68-1378-4932-9d6b-d80b97764bb4)

You can find the file I get by selecting the text by hand: [selection.txt](https://github.com/user-attachments/files/15530410/selection.txt)

- I can't tell for sure if I experienced it before the update. I could say 75% no

**Comment by Antreesy** [comment]
This stack trace looks like a part of a library, but it's unrelated to the issue.
Problematic line 899 (951 in yours) contains `B.exports=o(1 .valueOf)` and is coming from `vue-multiselect` library, which doesn't receive updates anymore, and we are no longer using it since `@nextcloud.vue@8.0.0`

Solution would be to:
- bump `nextcloud-vue-collections` to ^0.12.0 (should be compatible with NC v28)
- bump `@nextcloud/dialogs` to ^5.0.0 (compatible with NC v28)

cc @nickvergessen

**Comment by nickvergessen** [comment]
Does https://github.com/nextcloud/spreed/blob/main/webpack.common.config.js#L43 need adjusting somehow?

**Comment by ShGKme** [comment]
Sorry, I've suddenly marked this notification as read.

Looking on the issue.

**Comment by ShGKme** [comment]
I tried to reproduce by steps:
1. Checkout `v18.0.8`
2. `npm ci && npm run build`
3. In server config: `'projects.enabled' => true,` (just in case as it happened in collections)
4. Load page in Firefox 126 (126.0.1)

No errors. Everything loads correctly.

Note: `1 .valueOf` is a valid JS while `1.valueOf` (without space) is not valid indeed.

In the local build I see no `1.valueOf`.
Then I checked the release: https://github.com/nextcloud-releases/spreed/releases/tag/v18.0.8
And the release also does not contain this invalid string.

Then I checked exactly the same file on the exact same place on the server of the issue with the same version hash. And it also has this line correct.

So, as I see, everything is correct.

@thegabriele97 Could you check that this issue is still actual for you and if it doesn't, that it crashes in different browsers. Ideally in a web-browser without any extensions installed.

**Comment by ShGKme** [comment]
> Problematic line 899 (951 in yours) contains `B.exports=o(1 .valueOf)`

This line, as it is, is not a problem, this is a valid and expected line.

There is no issues in `nextcloud-vue-collection` or `@nextcloud/dialogs`

> Does https://github.com/nextcloud/spreed/blob/main/webpack.common.config.js#L43 need adjusting somehow?

No, this line is fine, it tells to transpile a dependency which is totally fine

**Comment by thegabriele97** [comment]
> I tried to reproduce by steps:
> 
>     1. Checkout `v18.0.8`
> 
>     2. `npm ci && npm run build`
> 
>     3. In server config: `'projects.enabled' => true,` (just in case as it happened in collections)
> 
>     4. Load page in Firefox 126 (126.0.1)
> 
> 
> No errors. Everything loads correctly.
> 
> Note: `1 .valueOf` is a valid JS while `1.valueOf` (without space) is not valid indeed.
> 
> In the local build I see no `1.valueOf`. Then I checked the release: https://github.com/nextcloud-releases/spreed/releases/tag/v18.0.8 And the release also does not contain this invalid string.
> 
> Then I checked exactly the same file on the exact same place on the server of the issue with the same version hash. And it also has this line correct.
> 
> So, as I see, everything is correct.
> 
> @thegabriele97 Could you check that this issue is still actual for you and if it doesn't, that it crashes in different browsers. Ideally in a web-browser without any extensions installed.

I recorded a video to show you the steps. I refreshed the page with CTRL+R, the same should happen if you disable caches in the network tab. I tried different computers and browser and networks previously. It doesn't happen using firefox on android but I guess it is because I can't refresh without caches as I do on desktop.


https://github.com/nextcloud/spreed/assets/35406071/188ee293-b37e-425a-9b57-b7f677596b4b

**Comment by ShGKme** [comment]
@thegabriele97 Could you do the following:
1. Open devtools, network tab
2. Reload the page until there is an issue
3. In the network tab search for `talk-main.js`
4. Then the page is loaded, copy response
5. Save it to the file and send it to this issue

Then we can check the actual server response.

On my test, your server responds with the correct content.

![image](https://github.com/nextcloud/spreed/assets/25978914/4c2bc5ae-f6d3-419f-9f5e-a3467d9d3628)

**Comment by thegabriele97** [comment]
Here it is. 

[response.txt](https://github.com/user-attachments/files/15778222/response.txt)

It doesn't work on Firefox for Android too. Did you refreshed multiple times with CTRL+R?

**Comment by ShGKme** [comment]
@thegabriele97 I removed a comment with your credentials, this is not needed.

**Comment by ShGKme** [comment]
Indeed, your server responds with different content for `/apps/spreed/js/talk-main.js`...

Sometimes it is correct:
- Size 9527993 bytes

Sometimes it is not correct:
- Size: 9277119 bytes

I'm almost sure that if you check the file on the server, you find that it is `9527993` bytes.

I'm also pretty sure that this file was correct in previous versions as well, it is not an issue from previous releases.

**Comment by ShGKme** [comment]
I've just checked the headers.

Correct:
- **Cf-Cache-Status: MISS**

Invalid:
- **Cf-Bgj: minify**
- **Cf-Cache-Status: HIT**

According to headers, you are using Cloudflare proxy, and the wrong file is cached and processed by Cloudflare.

See this discussion: https://community.cloudflare.com/t/minification-produces-invalid-javascript/406236

The file is corrupted by Cloudflare 🥳

**Comment by ShGKme** [comment]
This is officially the bug of the month for me 😶

**Comment by thegabriele97** [comment]
> This is officially the bug of the month for me 😶

Yep. It should be get corrected  by cloudflare, it is a very subtle bug that may affect a lot of other services!

I added a cache rule on cloudflare meanwhile

![image](https://github.com/nextcloud/spreed/assets/35406071/437470b2-2350-44f6-85bc-d9b4d9ddf79f)
