### ISSUE TITLE
Allow to clear chat history

### ISSUE THREAD

**Issue by Ngri88** [nextcloud/spreed#1243]
> > ~I often used chat and there were a lot of messages. Now as soon as I open a chat, the application starts opening all messages from the very first. Opening this message history can take 20-30 seconds, during which I cannot write anything to the chat or even close the tab in the browser. Is it possible to hide the history of the chat as it is made in Facebook messenger?~
> 
> The chat is loaded newest to oldest as a temporary workaround in Talk 7.
The optimal solution is to start at the read marker as described in #1164 
Which will be covered by #1788

Since emptying all chat might still be a useful feature, eg in webinaries before opening the lobby, I will keep this issue open. - @nickvergessen

**Comment by nickvergessen** [comment]
We will change the loading order, whether or not a delete history is needed then, we can see later.

For more information see #1164 and #1214

**Comment by intrazik** [comment]
+1

**Comment by nickvergessen** [comment]
The loading speed is down to milliseconds again since we merged #1271 
We will change the loading order also before the next release, so it loads the newest messages first and loads older messages only when you scroll up.

**Comment by Ngri88** [comment]
> The loading speed is down to milliseconds again since we merged #1271
> We will change the loading order also before the next release, so it loads the newest messages first and loads older messages only when you scroll up.
> 
> I guess we don't need a workaround like an option to hide the history then?

Yes, changing the loading order is a good alternative to hiding chat history.

**Comment by nickvergessen** [comment]
The chat is now loaded newest to oldest as a temporary workaround.
The optimal solution is to start at the read marker as described in #1164 
Which will be covered by #1788

Since emptying all chat might still be a useful feature, eg in webinaries before opening the lobby, I will keep this issue open and update the first post with this information.

**Comment by nickvergessen** [comment]
Frontend todos after #5889 


- [ ] UI option in the "Danger zone"
- [ ] Reset(recover) read marker in the UI when being used as offset for a chat request

**Comment by nickvergessen** [comment]
Reopening for frontend

**Comment by PVince81** [comment]
@nickvergessen should we also add an occ command to make it possible to automate this ? might need to also provide a timestamp

**Comment by nickvergessen** [comment]
I'm not a too big fan of an occ command, as administrators with console access are mostly not the moderators. It's a difference between deploying and terminating a room and moderating it.

**Comment by mahibi** [comment]
i have a group with multiple users. i send the delete request as user2 but i receive as an answer that user1 cleared the chat:

```
<?xml version="1.0"?>
<ocs>
    <meta>
        <status>ok</status>
        <statuscode>200</statuscode>
        <message>OK</message>
    </meta>
    <data>
        <id>181</id>
        <token>q2fysw5t</token>
        <actorType>users</actorType>
        <actorId>user1</actorId>
        <actorDisplayName>user1</actorDisplayName>
        <timestamp>1626352322</timestamp>
        <message>You cleared the history of the conversation</message>
        <messageParameters>
            <actor>
                <type>user</type>
                <id>user1</id>
                <name>user1</name>
            </actor>
        </messageParameters>
        <systemMessage>history_cleared</systemMessage>
        <messageType>system</messageType>
        <isReplyable></isReplyable>
        <referenceId></referenceId>
    </data>
</ocs>
```

i would expect either user2 as the actor (or a 403 Forbidden if he is no moderator)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/b138414888dc8a558bacd9cfe3cf6735117f40b7/tests/integration/features/chat/delete.feature#L196-L209

We have an integration confirming exactly this. A non moderator gets a 403 and when a moderator does it both receive a message that says the moderator cleared it.

**Comment by mahibi** [comment]
ah it seems this is a bug in postman which i use to send requests. seems it doesn't update the auth field correctly after a change... after a restart everything works as expected..
