### ISSUE TITLE
Date separator invisible before reloading the page

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/spreed#12453]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Before reload
![336085283-a4fcc4dc-2d13-4b7b-bf0f-a03c30c512b0](https://github.com/nextcloud/spreed/assets/7427347/54324f23-18cf-4757-a11c-b6389b50ab54)

After reload
![image](https://github.com/nextcloud/spreed/assets/7427347/a9c8f751-2f46-4521-943f-fa0d1f1da4ae)

## Steps to reproduce
I had a conversation that I hadn't opened in a while. When I sent a new message, the Date separator was invisible.

### Expected behaviour
Date separator shows

### Actual behaviour
Conversation wasn't separated by todays date

## Talk app

**Talk app version:** c.nc
**Custom Signaling server configured:** c.nc
**Custom TURN server configured:** c.nc

**Custom STUN server configured:** c.nc

## Browser

**Microphone available:** yes
**Camera available:** yes
**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 125

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Antreesy** [comment]
Just observed it, date is there, but not visible for some reason:
![image](https://github.com/nextcloud/spreed/assets/93392545/fb6fa969-b6d4-4f2e-9364-57a595fd9c7e)

**Comment by DorraJaouad** [comment]
> Not visible, because has-sticky class is applied

If it is applied, it means `rect.top <= scrollerRect.top && rect.bottom >= scrollerRect.top` went truthy somehow. It is expected to be truthy only when the top edge of date ul element is at or above the top edge of the chat list.
https://github.com/nextcloud/spreed/blob/main/src/components/MessagesList/MessagesList.vue#L793-L806
