### ISSUE TITLE
@usr tag is broken when usr name contains blanks

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/spreed#1246]
## Steps to reproduce
1. text chat
2. try @tag with some user that actually contains a blank in his usr name
3.

### Expected behaviour

usr link in chat msg

### Actual behaviour

"@Unknown user" + part of the user name after the blank is inserted.

e. g. @ with usr "Erika Mustermann" (picked from usr list given) results in "@Unknown user" Mustermann when posted.

## Browser

Safari, Firefox, Chrome, iOS app - version and OS seems irrelavant. Tested several.

## Spreed app

**Spreed app version:**

3.2.6

**Comment by nickvergessen** [comment]
Yeah, this is sadly not possible at the moment:
https://github.com/nextcloud/server/issues/2443

**Comment by herrmannsdorfer** [comment]
Just checked with NC 14.0.3 and spreed app 4.0.0:

Instead of "@Unknown user" (the part before the blank/white space part of the user name) we now get "@Erika Mustermann" as an unlinked text string. There are no options for chat, mail and no avatar.

That is better than "@Unknown user" but we miss the functions expected with user mentioning - working user name provided.

Fun fact: When you create a conversation with some user who has white space in his user name the user mentioning in the activity log at the beginning works!
"You added 'Erika Mustermann'" with avatar, clickable user name to select options like chat, mail ...
-- 
Rolf
