### ISSUE TITLE
Black screen in Firefox using public link

### ISSUE THREAD

**Issue by gerazo** [nextcloud/spreed#1247]
## Steps to reproduce
1. With Firefox, open chat using a public link!
2. Start or Join video chat!

### Expected behaviour
Video and audio communication starts up like in Chrome, Chromium.

### Actual behaviour
Only black screen with idle indicator, video/audio communication never starts up.
See related bug: https://github.com/coturn/coturn/issues/261

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 18.04

**Browser name:** Firefox

**Browser version:** 62.0.3

### Browser log
Webrtc log shows a couple of these:
<details>
```
ICE(PC:1539109772175640 (id=83751862276 url=https://....../index.php/call/dzc7u8ek)): peer (PC:1539109772175640 (id=83751862276 url=https://...../index.php/call/dzc7u8ek):default) has no stream matching stream 0-1539109772175640 (id=83751862276 url=https://...../index.php/call/dzc7u8ek) aLevel=1
```
</details>

## Spreed app

**Spreed app version:** 4.0.0

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Maria

**PHP version:**

**Nextcloud Version:** 14.0.1

**Comment by gerazo** [comment]
In my case, the problem was originated from Firefox plugin uBlock Origin, see: https://github.com/gorhill/uBlock/issues/3009
However, it seems that the issue is partly because Nextcloud Talk is not using the latest webrtc standard. The browser console shows things like (even when working correctly):
```
RTCIceServer.url is deprecated! Use urls instead. simplewebrtc.js:14207
Using more than two STUN/TURN servers slows down discovery simplewebrtc.js:14207
onaddstream is deprecated! Use peerConnection.ontrack instead. simplewebrtc.js:14225 
```
See https://github.com/coturn/coturn/issues/261#issuecomment-429318654 for details!

**Comment by nickvergessen** [comment]
Updating WebRTC will be tracked in #1063
