### ISSUE TITLE
[Question] Why are all users of a Nextcloud instance visible in Talk App?

### ISSUE THREAD

**Issue by eggithub** [nextcloud/spreed#1248]
Hi

Whether this is a bug or a feature, I'm not sure. But, all users of a Nextcloud instance appear to be visible within the Talk App. They also turn up as Contacts within the Android Talk App. I would rather expect and on Opt-In for such a feature. This might also be privacy related, e.g. not every User might be in to participating or communicating via the Talk App. It might even be undesirable for a user to be exposed in a Nextcloud instance.

Your thoughts please.

**Comment by nickvergessen** [comment]
If you do not want this, simply disable the user enumeration in the sharing settings:
Settings > Sharing > `Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered.`

It is the same when you share a file btw.
