### ISSUE TITLE
Status bar notifications android

### ISSUE THREAD

**Issue by leihergo** [nextcloud/spreed#1249]
## Steps to reproduce
1. Receive a message in nextcloud talk
2. Go to the bar notifications
3. There is nothing there

### Expected behaviour
Get the notification, not just a vibration of the terminal

### Actual behaviour
The mobile just vibrates, if you don't feel it, you don't know you have messages

**Comment by nickvergessen** [comment]
Can you open your issue in the android repository?
https://github.com/nextcloud/talk-android/issues

Thanks :smile:
