### ISSUE TITLE
Remember guest usernames

### ISSUE THREAD

**Issue by poiNt3D** [nextcloud/spreed#12491]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:**  29.0.1

**Is your feature request related to a problem? Please describe.**
Currently, when a guest joins a chat shared by a link, he must enter their name each visit.

**Describe the solution you'd like**
Remember entered username by a cookie.

**Describe alternatives you've considered**
Alternatively, allow generation of invite URLs with pre-entered username.

**Comment by nickvergessen** [comment]
> Alternatively, allow generation of invite URLs with pre-entered username.

That's planned in the long run. Ref https://github.com/nextcloud/spreed/issues/6098

> Remember entered username by a cookie.

It's stored in the browser storage already. When it's not loaded also a cookie wouldn't work anymore.

**Comment by poiNt3D** [comment]
> It's stored in the browser storage already
Can't get it to work. Does it mean it's something wrong with my setup?

**Comment by nickvergessen** [comment]
What do you mean by "Can't get it to work"?
Are you testing in a private window?
