### ISSUE TITLE
Mailto in avatar overlay is wrong

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#12516]
- click on an avatar in a conversation
- see that mailto is: https://cloud.server.com/call/mailto:first.second@server.com
- in e.g. sharing menu of a file, it is "mailto:first.second@server.com"

**Comment by nickvergessen** [comment]
In Desktop client or browser?

**Comment by nickvergessen** [comment]
Bug from the vue library

**Comment by nickvergessen** [comment]
Fix in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5703
