### ISSUE TITLE
Talk app connected users show as offline participants

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/spreed#1251]
## Steps to reproduce
1. Connect to a chat room with Talk app (eg Android).

### Expected behaviour
Show participant as online in sidebar of browser.

### Actual behaviour
In participant sidebar these Talk app connected users will remain greyed out (offline).

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
4.0.0, Talk app 3.0.1

## Server configuration

**Nextcloud Version:** (see admin page)
14.0.2

**Comment by nickvergessen** [comment]
@mario do you have background to this? Is the android app not joining the room when you open it?

**Comment by herrmannsdorfer** [comment]
I just checked the issue with a friend:

NC 14.0.4, Spreed 4.0.1, Talk (Android) 3.1.1

Participant shows as online in 1:1 chat.
Switch to another room with group chat the same participant ist marked as offline/greyed out.
Switch back to 1:1 chat - participant is online again.

When I login with a browser I will be marked online in all chatrooms for the other participants.

**Comment by herrmannsdorfer** [comment]
Follow-up:

My fault. Participant is marked online only when actively joined specific room. In other rooms same participant is marked offline. Maybe I was puzzled by delay in signaling the status when switching rooms or browser caching in web GUI.

So we do not have an issue with signaling between spreed and talk apps. I will close the issue.

On the other hand: There had been already feature requests about some extended status info like: 

- logged out (and truly offline)
- logged in NC
- joined room
- busy in video chat in another room (and therefore not available in this room)
- ...

If this kind of status info is OK with privacy concerns of your NC (maybe as an option?) you would have to design some clear status icons to show other participants your availability - independent of the currently joined room.
Is it worth opening another issue for that? The others were all closed shortly. It seems the privacy topic dominates other use cases.

**Comment by mario** [comment]
@herrmannsdorfer overall presence support is a server request, but yea - we've had people request it. We will see what happens in this space in the future - please be sure to follow us and thank you for being awesome! :)
