### ISSUE TITLE
Conversation list not updated when not joined a room

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12548]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open `/apps/spreed/` in two pages
2. See the conversation list on the left sidebar (from the browser cache)
3. Wait

### Expected behaviour
You should see a request to `ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true` in the second page

### Actual behaviour
No request is ever done

## Talk app

**Talk app version:** 19.0.3 on c.nc.c

**Comment by Antreesy** [comment]
We don't do room requests for secondary tabs. But it's worth checking that we are passing enough data to update them (modified rooms, hash, fed invites)

**Comment by SystemKeeper** [comment]
But the requests start on a secondary tab, I I join a room. That’s still expected ?
