### ISSUE TITLE
Background image is mirror-inverted on own video stream

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/spreed#12545]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
**This only affects the own video stream. The other participants get the correct background.** 

1. Start a call and klick on backgrounds
2. Choose a custom video background wich has text (e.g. the company name) in it. 

### Expected behaviour
The preview of the own video stream (obove the background button) shouldn't show the background image mirror-inverted. 
Also when actually starting the call, the background image of the own video stream shouldn't be displayed mirror-inverted. 

### Actual behaviour
In both cases the background image is displayed mirror-inverted. 
This confuses people. They regularly assume, that the other participants get the same mirror-inverted video shown. 

![2024-06-19 11_55_03-Window](https://github.com/nextcloud/spreed/assets/60740965/8d0e3e87-c498-446b-9c08-b9bea1c2bd76)

## Talk app

**Talk app version:**  17.1.9

**Custom Signaling server configured:** yes 1.2.2-1~ubuntu20.04

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 115 esr

**Comment by nickvergessen** [comment]
Your own video is inverted for you all the time.
This is generally in most of the video call software, to give you a better perception of yourself (like when you look into a mirror).

I can see how that is confusing when setting up a background with text/logo, but I assume we will not change it.

cc @jancborchardt @marcoambrosini

**Comment by jancborchardt** [comment]
Since this issue is very specific to setting up a custom backgroud (with text), we could add a little sentence (in a notice box) saying:

> Your video is mirrored only for yourself. Others will see it normally, including text in custom backgrounds.

**Comment by hartsberger** [comment]
I know, that this is intended. Like using a selfie camera on the smartphone. 

I would have guessed that it is quite common to have a background image that is branded with the company name in it. 
We actually replace the default background images with our own ones on the server. 

But I would appreciate the notice you mentioned. Perhaps it makes sense to place it on top of the preview like this: 

![2024-06-19 16_25_35-Window](https://github.com/nextcloud/spreed/assets/60740965/1c4bef23-aa0f-4ed8-895a-e593d4e1c7dc)
