### ISSUE TITLE
Missing index for talk_invitations database lookup

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#12553]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. ???

### Expected behaviour

Efficient database operations

### Actual behaviour

```sql
SELECT
  COUNT (*)
FROM
  `oc_talk_invitations`
WHERE
  (`user_id` = ?)
  AND (`state` = ?)
```

not using an index.

Looking at https://github.com/nextcloud/spreed/blob/38bfcad79113a110084789db21e93cbaed668627/lib/Model/InvitationMapper.php#L71-L100 it seems like an index on (user_id, state) would be a good candidate.

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

Query ID 805953543f46cc758e6b0239a23b8bfd

**Comment by nickvergessen** [comment]
yeah it's more important now that we don't delete invites when they got accepted.
This was not the case in the beginning
