### ISSUE TITLE
TURN connectivity check fails in specific network conditions

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#12576]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Execute the TURN server connectivity test with:
    - option 1: `turns:only` and `UDP only`, or 
    - option 2: `turns:only` and `TCP only`

### Expected behaviour
The test succeeds.

### Actual behaviour
The test fails.

## Talk app
19.0.3 on Nextcloud Server 29.0.2

While the test fails, selecting one of the options, make it possible to do a call between two participants both relayed on this TURN server  (forced setting media.peerconnection.ice.relay_only=true in Firefox). Notice that the connectivity check is ok and the TURN server works as expected when selecting `turn:only`.

The issue happens only when the Nextcloud instance is on the same internal network as the TURN server.

My TURN server configuration file

```
listening-port=443
fingerprint
use-auth-secret
static-auth-secret=mysecret
realm=myrealm.com
total-quota=0
bps-capacity=0
stale-nonce
no-multicast-peers
## Allowed peers
# this system
allowed-peer-ip=10.0.0.10
# Talk HPB
allowed-peer-ip=10.0.0.20
# Nextcloud instance from which the test is done
allowed-peer-ip=10.0.0.30
## TLS Certificate and Key
cert=/path/to/cert.pem
pkey=/path/to/key.pem
```

**Comment by SystemKeeper** [comment]
> The issue happens only when the Nextcloud instance is on the same internal network as the TURN server.

The issue is probably that the Nextcloud instance is not able to connect to the TURN server. Please check the logs, there should be a more detailed explanation of what went wrong. Most likely it's the certificate check and either the certificate is not valid (but then connection might not work) or no connection to check the certificate. 
Otherwise having the instance on the same networks should not cause any issues.

**Comment by pmarini-nc** [comment]
Thanks @SystemKeeper .

Your analysis is correct:

```
{
  "reqId": "M6eaNeQQVRAM2OqLhV28",
  "level": 3,
  "time": "2024-06-25T11:30:12+02:00",
  "remoteAddr": "XXX.XXX.XXX.XXX",
  "user": "nc-admin",
  "app": "PHP",
  "method": "GET",
  "url": "/ocs/v2.php/apps/spreed/api/v1/certificate/expiration?host=turn.mydomain.com:443",
  "message": "stream_socket_client(): Unable to connect to ssl://turn.mydomain.com:443 (Connection timed out) at /var/www/nextcloud/apps/spreed/lib/Service/CertificateService.php#107",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0",
  "version": "29.0.2.2",
  "data": {
    "app": "PHP"
  }
}
```

If Nextcloud instance resolves the turn hostname to its internal IP, both connectivity check and calls work as expected.

**Comment by SystemKeeper** [comment]
Thanks for the info! So this seems to work as intended then.
