### ISSUE TITLE
Rendering bug when unread marker is removed on Safari

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12595]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation which has unread messages - see the conversation marker
2. Focus another window
3. Go back to the conversation

### Expected behaviour
Unread marker is removed and the message list is correctly rendered

### Actual behaviour
Unread marker is removed, but the message list "jumps" up. This seems to be a rendering issue, because at that point I am in a state where the rendered UI is not identical to the elements anymore.

https://github.com/nextcloud/spreed/assets/1580193/c283e0fb-326e-4136-8f5b-94dc38a906a0

## Talk app

**Talk app version:** main @ 61e2b6c3edfc7a52304324516652fee3fe0f857b but also seen on c.nc.c

## Browser

**Operating system:** MacOS 14.5

**Browser name:** Safari 17.5

**Comment by SystemKeeper** [comment]
Still happens :( Not totally sure yet if it's still related to the unread marker or not:

![Image](https://github.com/user-attachments/assets/7cb5bf0f-b1d1-4056-8fff-7448eccfeb65)

**Comment by nickvergessen** [comment]
- Moved to https://github.com/nextcloud/spreed/issues/13764
