### ISSUE TITLE
Sidebar trigger not shown on mobile devices

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1259]
I have just updated from v3.2.4 to v4.0.0 and on mobile devices the sidebar trigger is not shown so it is not possible to join calls.  The problem appears to be the negative left-margin in the commit https://github.com/nextcloud/spreed/commit/7b38bee77276ea48018a5b6826ec696ae133397a#diff-9c227ff7cd07ef67bd28fd246b54f5b7 which pushes it off the edge of the screen.  If I change the margin-left value to 0px then the trigger appears and I can join calls.

**Comment by nickvergessen** [comment]
@danxuliu can you haz a look?

**Comment by Peterede** [comment]
In the web browser on PC simulating mobile it appears but on an actual android phone it doesn't. I tried on a nexus 5 and opportunities r15

**Comment by Peterede** [comment]
I checked just now and found the menu icon in the top left is also missing.

**Comment by nickvergessen** [comment]
Can not reproduce.
