### ISSUE TITLE
Youtube video previews does not show up

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#12624]
On cloud.nextcloud it works:
![grafik](https://github.com/nextcloud/spreed/assets/24530680/65c9892b-4783-4731-97f7-af0732fff24f)

On my other servers not:
![grafik](https://github.com/nextcloud/spreed/assets/24530680/c64e2ea2-4def-4a9b-8757-2086a4806a01)

Is there a bug or is this a configure setting?
I run 29.0.3

**Comment by SystemKeeper** [comment]
I assume you miss https://github.com/nextcloud/integration_peertube

**Comment by jakobroehrl** [comment]
you mean youtube integration, right?
That works, but it looks not like not cloud.nextcloud.com:

![grafik](https://github.com/nextcloud/spreed/assets/24530680/8e3db7ca-02da-47a4-96cf-5d184bcfb430)

**Comment by SystemKeeper** [comment]
Right, sorry. The youtube/peertube integration directly renders a video. What you're seeing in your first screenshot is the data returned by opengraph, which is enabled by default, but can be disabled through config.php: https://github.com/nextcloud/server/blob/72b6db40435ce0407d0aafa626945d4f2380460f/config/config.sample.php#L2446

But in talk we only show what is delivered by the reference provider (that's handled UI wise in the vue lib and backend wise in server / the corresponding app providing the reference provider).

**Comment by jakobroehrl** [comment]
Thanks for clearification.
Do you have an idea, why the preview could be lost? See screenshot 1, pic2.
There is no entry in the config.php and true is the default.

**Comment by DorraJaouad** [comment]
Can you please check the request's payload of `resolve?reference=https...` ?

**Comment by SystemKeeper** [comment]
Besides the suggestion from Dorra, I'd suggest to set logging to debug and check the logs. There are some debug outputs from the reference provider is something goes wrong. Another thing to keep in mind, the server does the reference lookup, not the client. So if your server firewall is quite restricted and unable to do the requests, that's the result.

**Comment by jakobroehrl** [comment]
![grafik](https://github.com/nextcloud/spreed/assets/24530680/4e165fd5-d176-4ff1-9848-c0c83ead4357)
The server is "free", I disabled the ufw firewall for testing, no differences. 
Could I do a curl to trigger the opengraph API? Someting like this:
curl https://opengraph.io/api/1.1/site/https%3A%2F%                                                                                   2Fwww.youtube.com%2Fwatch%3Fv%3DrOQAK2p-i4Q
{"error":{"code":-9,"message":"API key required. Please refer to documentation.

**Comment by jakobroehrl** [comment]
Now the youtube thumbnails does not shop up on cloud.nextcloud.com, too.
Channel previews are working, video previews not, is this as expected?

![grafik](https://github.com/user-attachments/assets/6c6b83d6-b036-4429-afbc-51ed438f648e)

**Comment by nickvergessen** [comment]
There is nothing we can do in Talk.
If something could be done it'll be in server where the reference link provider is.
But I guess we are just throttled with our server on the API
