### ISSUE TITLE
Missing notification on public chat/call

### ISSUE THREAD

**Issue by hendrikreimers** [nextcloud/spreed#1263]
## Steps to reproduce
1. Login as user and go to "Talk"
2. Create a public shared conversation
3. Let a public user join
4. write a message
5. On your mobile lookup for notifications.

### Expected behaviour
Like on registered NC Users, on joining/creating a chat/talk/video/... the ios/android app is receiving an notification for each join or since NC 14 for new unseen messages (if Talk App isn't open) too. But on public conversations with unregistered (public) users, the notifications still missing.

### Actual behaviour
Missing notification on public users that joined and write messages, only on starting a video call notifications are coming. So no one will see if new users write something or joined.

## Browser
Firefox (62.0.3) or Chrome (70+) and iOS 12.0.1 (or earlier)

**Microphone available:** yes/no
yes

**Camera available:** yes/no
yes

**Operating system:** Windows/Ubuntu/...
Windows 10, MacOS or Ubuntu 18.04

## Spreed app

**Spreed app version:** 4.0.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
Apache 2.4+, PHP 7.2 FPM, no errors in NC except SQLIte hint ;-)

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** SQLite

**PHP version:** PHP 7.2 FPM

**Nextcloud Version:** latest stable 14.x

**List of activated apps:** Defaults, Collabora, Talk, Polls, Contacts, Cal, Tasks

**Comment by nickvergessen** [comment]
Someone joining a conversation for chat never triggered a notification.

Also note that notifications are not send when you have an active session in that conversation.
So when you still have the conversation open in your browser, your phone will not receive a notification.

**Comment by Ivansss** [comment]
Notifications on every message are sent just for one2one conversations at the moment.
For public and group conversations only if a user is mentioned in a message.
You will be able to modify this behaviour on the next Talk release https://github.com/nextcloud/spreed/pull/1230

**Comment by hendrikreimers** [comment]
This is what i'm looking for. I'll be wait for the next release.
