### ISSUE TITLE
Speaker view should not change when hovering icons

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12631]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
![grafik](https://github.com/nextcloud/spreed/assets/213943/c18ea8fd-e721-472b-a86c-4eb5f5e02d15)

**Comment by Antreesy** [comment]
Same for LeftSidebar and ParticipantList
