### ISSUE TITLE
Ability to attach local files to a conversation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1264]
Currently it’s only possible to add files which are already in Nextcloud. When I want to add screenshots I just took (for example) this is very cumbersome.

It should also be possible to add local files.

For that, the + icon should probably open a menu first which says

- :cloud: Add from Nextcloud
- :arrow_up: Upload from device

**Comment by nickvergessen** [comment]
Duplicate #1129

**Comment by jancborchardt** [comment]
Ah sorry, did search for "local file" or so but didn’t find it. Thanks!
