### ISSUE TITLE
How to avoid displaying all accounts in a multi-domain nextcloud installation?

### ISSUE THREAD

**Issue by joe-average-user** [nextcloud/spreed#1266]
## Steps to reproduce
1. Simply use Talk

### Expected behaviour
It would be a lot better to be able to filter the displayed accounts in some way. We use account names that include a domain (e.g. testuser@testdomain.com) and want to be able to display only accounts inside that single domain to a talk user. But not someone like anotheruser@anotherdomain.net.

### Actual behaviour
Actually talk shows all users of all domains.

## Browser
Does not depend on browser.

**Comment by jospoortvliet** [comment]
Hi average user,

The Nextcloud Talk app is designed for home users and very small installations - where I don't think this is a problem. For our enterprise version of Talk this might be a possibility, yes.

**Comment by joe-average-user** [comment]
I doubt that this is a small issue regarding EU General Data Protection Regulation. You give all available account names to every user logged in. So a user cannot request not being displayed in this list. He can only drop the nextcloud service alltogether. As an admin my only chance to avoid this problem is by dropping the talk service. It is not possible to fulfill the GDPR with an enabled Talk app.

**Comment by nickvergessen** [comment]
There are several other places in Nextcloud where users can find each other. This has also nothing todo with the GDPR unless you are a hosting provider and host multiple unrelated people on one instance.

Sharing files also reveals other users, same for the contacts menu in the upper-right corner.
There is a sharing setting which restricts sharing to people of the same user groups. This setting is also respected by the Talk app. If you need more, e.g. a special user handling based on their email-domain, feel free to sign a support contract and sponsor that specific feature.
