### ISSUE TITLE
GitHub references are not rendered anymore

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12683]
* Post a link to a GitHub Issue or Permalink
* Expected: See rendered widget
* Actual: Empty widget is rendered

<img width="859" alt="image" src="https://github.com/user-attachments/assets/9622683f-9a88-4e4d-8010-bcf792de877d">

Seems to still work fine for URLs. The GitHub integration is on the version that's 4 month old. So either we broke something, or the Vue-Lib I assume?

Seen after upgrade to Talk 19.0.5 and 29.0.4 RC1.

Also CC @julien-nc

**Comment by nickvergessen** [comment]
gitLAB integration for updated tonight, maybe that is related?

**Comment by nickvergessen** [comment]
- Fixed by #12610 
Was a bug in the vue version
