### ISSUE TITLE
After updating Nextcloud Talk - browser conversation stuck on "Joining Conversation"

### ISSUE THREAD

**Issue by CreativePR** [nextcloud/spreed#12711]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1.  Updated Nextcloud installation to 18.0.10
2. Login to Nextcloud account and go to talk on either Edge or Chrome - Windows 11 pro
3. When entering conversation, you cannot type - only see joining conversation.  Using Nextcloud Talk iPhone app, there are no issues

### Expected behaviour
You should be able to talk in a conversation using WIndows 11 Pro and either the Edge or Chrome Browswer

### Actual behaviour
Conversations all stuck at Joining Conversation...  Cannot type in either the Edge or Chrome Browser on Windows 11 Pro

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)
18.0.10

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)
Using Defaults on Docker Installation

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

Using Defaults on Docker Installation

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

Using Defaults on Docker Installation

## Browser

Chrome 126 or Edge 126

**Microphone available:** yes/no
Yes

**Camera available:** yes/no
Yes

**Operating system:** Windows/Ubuntu/Mac/...
Windows 11 Pro

**Browser name:** Firefox/Chrome/Safari/...
Chrome and Edge

**Browser version:** 124/125/...
126

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
> Using Defaults on Docker Installation

Which docker are you taking about? Please check the settings in Admin -> Talk and update your post. 

Please check your browsers console for errors and post these here.

**Comment by CreativePR** [comment]
Sorry -  mistated about docker.  This install was Nextcloud AIO.  After rebooting the server, the issue that we saw on Windows 11 with Chrome and Edge resolved itself.

**Comment by SystemKeeper** [comment]
Thanks for the feedback, I am closing the issue for now then.
