### ISSUE TITLE
Start/leave call needs some padding on the right

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#12720]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to a chat
2. Optional: start a call

### Expected behaviour

Good design

### Actual behaviour

No space at the right side of the button

![Bildschirmfoto vom 2024-07-15 13-26-56](https://github.com/user-attachments/assets/ac19d491-b926-4b01-a15e-9ca16fbeaad3)
![Bildschirmfoto vom 2024-07-15 13-05-40](https://github.com/user-attachments/assets/8f308305-4bf1-4591-9256-5090456fa61a)

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Is this on daily?

Can not see it on c.nc.c

**Comment by ChristophWurst** [comment]
I have the sidebar open

![image](https://github.com/user-attachments/assets/d9c94c93-6ad4-4a6c-b54d-4636bce2fa76)

**Comment by ChristophWurst** [comment]
yes, still happens. But only on FF. Chrome is fine.

**Comment by nickvergessen** [comment]
Not happening anymore
