### ISSUE TITLE
Ease participating as a internal user when joining public conversations

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/spreed#12772]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 29

**Is your feature request related to a problem? Please describe.**
As a user of talk I want to be able to join a conversation, with my internal user, even if I am not currently logged in, because there is just a manual way to achive this.

After opening to a conversatiin with a public link, I only have the option to enter a name for my current guest user. If I want to join with my internal identity, I have to enter the URL of the login page, enter my credentials. After that I have to change to the talk app and search the conversation I want to join. Or I have to reopen my mail program to fetch the link of the invitation. 

**Describe the solution you'd like**
Add an option to login to the welcome screen. Either by allowing to use the login there or route to the login page and rediret to the conversation.

**Comment by nickvergessen** [comment]
A login button there sounds quite useful.
On the other hand if you ever added a guest name I think the dialog is skipped? So another option to the login in the right sidebar would also be helpful?

**Comment by dartcafe** [comment]
Suggestion like in Polls: The login option is offered on the registration page

It then simply routes to https://foo.com/login?redirect_url=/apps/polls/s/{token}

![grafik](https://github.com/user-attachments/assets/5db3e812-885f-4739-8534-39e4af4fb575)

**Comment by dartcafe** [comment]
Regarding the login button after participating as a guest. In Polls the mechanism is quite different. 

When a user enters the poll as guest, the username is stored within a cookie, which name is the token string for 30 days. 
The user has the option to delete the cookie (aka log out of this poll). 
Then he has the possibility to register again via the dialog above.

Storing the cookie help to reenter the poll after registering as a user without the necessity to register again and with all options to change or comment as the same user.

**Comment by nickvergessen** [comment]
A simple login button that redirects to the login page with a redirect URL will have to be enough for Talk at the moment
