### ISSUE TITLE
Volume is too low

### ISSUE THREAD

**Issue by biva** [nextcloud/spreed#1278]
Quite often, the volume of my contact is too low: I can only hear them when they speak very close to the mic (while their sound is OK when using Skype). I don't know where to find the info to configure this. I'm willing to do a manual page on Nextcloud to explain that, but I don't know what should be set up to improve the sound quality. Any hint?

Configuration: usually Windows 10 or Mac OS, Firefox / Chrome / Safari

Thank you!

(Edit: related to https://github.com/nextcloud/spreed/issues/154)

**Comment by nickvergessen** [comment]
I'm not sure if we can influence the voice level at all. But can you check that you didn't reduce the sound level of your browser in your system?

**Comment by biva** [comment]
Thank you @nickvergessen . On my side no, the volume is standard in the Windows Sound Mixer for Firefox. Maybe my contact did reduce the mic sound.

I really think that the standard user will not be able to manage that. As discussed in #154, I think it's necessary to provide information and solutions to the standard user to manage the sound, depending on the browser and the platform. On Skype, it's often a problem to manage sound issue, while the interface is much easier and more advanced than the one of Nextcloud Talk.

About influencing the voice level, I'm not skilled enough. But Skype does it, so I think it's doable, even within a browser. Don't you think?

**Comment by biva** [comment]
Hi, does anybody else meets this issue as well? Since my first message, I noticed that the audio level of my correspondents is sometimes too low, sometimes OK: When they speak, it can happen that the level is very low, and suddenly it increases a lot and becomes high enough. And it's not because suddenly, they stick their mouth to the microphone ;)

**Comment by nickvergessen** [comment]
Some operating systems or audio drivers do that themselves to reduce background noise.

**Comment by biva** [comment]
Thanks @nickvergessen : maybe you're right, but I don't have the issue with Skype. With same configuration, same computer, same people.

Isn't there something possible to avoid this? Or tell to the OS to disable such feature within Talk?
