### ISSUE TITLE
Conversation list item pop-up menu icon design

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/spreed#12781]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

cc @jancborchardt since we discussed the outline style for the content copy icon and also generally using the filled style for icons.

## Steps to reproduce
1. Open menu of a conversation item

<img width="145" alt="2024-07-23 09_54_35-Talk" src="https://github.com/user-attachments/assets/2328a672-9530-4210-a4bd-84822fa731f1">

### Expected behaviour
* read/unread icon should be "filled" styled
* content-copy icon should be unfilled styled

### Actual behaviour

the opposite happens:
* read/unread icon is "unfilled" styled
* content-copy icon is "filled" styled

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`): current `master` / v20

**Comment by ShGKme** [comment]
@jancborchardt Do we keep Settings icon (cog) filled?
