### ISSUE TITLE
Remove moderator if removed from Team/Circle.

### ISSUE THREAD

**Issue by jvir** [nextcloud/spreed#12799]
## Feature request

**Which Nextcloud Version are you currently using: 29.0.3

**Is your feature request related to a problem? Please describe.**
When a user who belongs to a Room by belonging to a Team/Circle is promoted to moderator they are not removed from the Room when they are removed from the Team/Circle.

**Describe the solution you'd like**
Whenever a user belongs to a Room because of a Team/Circle they should be removed regardless of their permissions in the Room.

**Describe alternatives you've considered**
Another solution could be to indicate whether the user is a member due to a circle or directly in a visual way which would make him/her appear in the Room as a direct member when removed from the circle and other members could see it.

**Comment by nickvergessen** [comment]
Moderators are never removed from a conversation based on other membership as that could lead to conversations without any moderator left.
So to phrase it in your words, by promoting a user to moderator, they are always a direct member of the room.
