### ISSUE TITLE
Video stops after 30 seconds with Google Chrome

### ISSUE THREAD

**Issue by m0urs** [nextcloud/spreed#1279]
## Steps to reproduce

1. Open a Talk sessions with two users in Chrome
2. Video and Audio does work for about 30 seconds
3. After about 30 seconds the video is no longer working. Re-entering the call does enable video again for another 30 seconds

Both users are in the same local network and using the Nextcloud server in a remote data center.

### Expected behaviour
Video should not stop during the call

### Actual behaviour
Video stops after about 30 seconds

## Browser
Chrome 70.0.3538.77 / Firefox 63.0.1 does work

**Operating system:** Windows 7 and MacOS

## Spreed app

**Spreed app version:** 4.0.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Debian 8

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud Version:** 14.0.3

**Comment by nickvergessen** [comment]
Any output in your console in that regard? Press F12 in your browser and go to "Console"

**Comment by m0urs** [comment]
Yes, that is what I see on my browser if my video disconnects:

```
DevTools failed to parse SourceMap: https://owncloud.acme.com/apps/spreed/js/vendor/backbone.radio/build/backbone.radio.min.js.map
webrtc.js?v=4f1da582-11:612 trace {time: Tue Dec 04 2018 17:13:33 GMT+0100 (Mitteleuropäische Normalzeit), type: "oniceconnectionstatechange", value: "disconnected"}time: Tue Dec 04 2018 17:13:33 GMT+0100 (Mitteleuropäische Normalzeit) {}type: "oniceconnectionstatechange"value: "disconnected"__proto__: constructor: ƒ Object()arguments: (...)assign: ƒ assign()caller: (...)create: ƒ create()defineProperties: ƒ defineProperties()defineProperty: ƒ defineProperty()entries: ƒ entries()freeze: ƒ freeze()getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()getOwnPropertyNames: ƒ getOwnPropertyNames()getOwnPropertySymbols: ƒ getOwnPropertySymbols()getPrototypeOf: ƒ getPrototypeOf()is: ƒ is()isExtensible: ƒ isExtensible()isFrozen: ƒ isFrozen()isSealed: ƒ isSealed()keys: ƒ keys()length: 1name: "Object"preventExtensions: ƒ preventExtensions()prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}seal: ƒ seal()setPrototypeOf: ƒ setPrototypeOf()values: ƒ values()__proto__: ƒ ()[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
webrtc.js?v=4f1da582-11:561 Disconnected.
webrtc.js?v=4f1da582-11:612 trace {time: Tue Dec 04 2018 17:13:48 GMT+0100 (Mitteleuropäische Normalzeit), type: "oniceconnectionstatechange", value: "failed"}
webrtc.js?v=4f1da582-11:582 Connection failed.

```

**Comment by nickvergessen** [comment]
That should really not be related.
I use Chromium all the time for testing, 50% of the time without the console.

Is this still happening?

**Comment by m0urs** [comment]
Yes, I can still reproduce the issue. If the Chrome console is open, then the connection is stable. If the Chrome console is closed, then the connection ends after about 30 seconds.

**Comment by SaltyCybernaut** [comment]
I currently run Nextcloud 15.0.2 with Talk/Spreed 5.0.2. The problem still occurs on Ubuntu 18.04 running Chromium Version 71.0.3578.98, Google Chrome Version 72.0.3626.81, and Firefox 65.0. It will also occur when the two clients are Android phones using the Talk application. All of these test were run with the two clients and server all running over the same LAN. The connection will last for about 3-10 minutes before video and audio is lost.

**Comment by danxuliu** [comment]
@SaltyCybernaut Based on your description and the original description I think that your problem is a different one.

#1522 may fix this issue... although I think that this is a different one, as the problem fixed in that pull request happened "randomly" (both the request for signaling messages and the request for chat messages had to happen at the same second), while in this issue it seems pretty consistent.

**Comment by nickvergessen** [comment]
Closing as per above
