### ISSUE TITLE
Adjust UI according to the design review

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#12800]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Conversation and composing

* [x] Top bar title is cut off @Antreesy 
  https://github.com/nextcloud/spreed/pull/12851
  https://github.com/nextcloud/spreed/pull/12875
* [x] Date marker "Today, July 23, 2024" border radius should be reduced to make it similar to the button @Antreesy 
  - https://github.com/nextcloud/spreed/pull/12810/

## List view

* [ ] ~~#13923~~
* [x] Margin on the left of list item is too much and on the right is too little --> it should nicely aligned with the left of the search bar and right aligned with the new conversation button (upstream issue?) @Antreesy 
  - https://github.com/nextcloud/spreed/pull/12810/
* [ ] ~~Settings button should be left aligned and not bold like in Files (visually)~~
  - https://github.com/nextcloud-libraries/nextcloud-vue/pull/5866
* [x] Counter bubble should have min-width such that width is never lesser than height (even when counter bubble has "1" it should be a circle) @ShGKme 
  - https://github.com/nextcloud-libraries/nextcloud-vue/pull/5905

## Sidebar

* [x] Participant list: @Antreesy 
  - Issues:
    - [x] Too much padding on left and right of each participant is too much
    - [x] Vertical space can also be reduced
    - [x] border radius should be reduced
    - [x] avatar focus should be circle
  - Migrate to `NcListItem`? https://github.com/nextcloud-libraries/nextcloud-vue/pull/5870
* [x] Media tab: thumbnails are top left aligned their containers @Antreesy https://github.com/nextcloud/spreed/pull/12810/

## Calling

* [x] Media settings:
  - [x] border radius on bg should be consistent
    - @Antreesy https://github.com/nextcloud/spreed/pull/12810/
  - [x] "Test devices" button should be left aligned with select components
    - @Antreesy https://github.com/nextcloud/spreed/pull/12810/
  - [x] Height changes when you change between devices and background tabs --> render both tabs and make one not visible @ShGKme 
    - https://github.com/nextcloud/spreed/pull/12815
* [ ] Ongoing call:
  - [ ] Hide participants and timer in mobile? @ShGKme 
    - https://github.com/nextcloud/spreed/pull/12928
  - [x] Chat view read receipt: width can be reduced to 20px @Antreesy https://github.com/nextcloud/spreed/pull/12823
  - [x] Reduce gap between avatar and message @Antreesy https://github.com/nextcloud/spreed/pull/12823
  - [x] Is it possible to have an animation when "raise hand" button appears on the top? @ShGKme 
    https://github.com/nextcloud/spreed/pull/12926

## Admin settings

- [x] Use the password field for shared secrets @ShGKme 
  - https://github.com/nextcloud/spreed/pull/12812
- [x] Some icon-only buttons don't have hover feedback @shgkme
  - https://github.com/nextcloud/spreed/pull/12814

**Comment by nickvergessen** [comment]
@Antreesy please extract things that don't have a PR yet into a new issue and close this one.
