### ISSUE TITLE
Banning should remove the participant server-side

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12804]
Since banning is now a dedicated endpoint and not tied to removing the participant, we should automatically remove the participant from the conversation when the participant was banned. Currently these are separate 2 requests done by the clients.

**Comment by nickvergessen** [comment]
Initial idea (just to have it commented) was to have both, an option on removing a user and an API endpoint to block IPs and others that are currently not a participant.

Since we don't have UI for the 2nd anyway, we could also just continue with the first approach?
