### ISSUE TITLE
Implement recording consent with federated calls

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12813]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

`CallController::joinFederatedCall()` is not handling it atm

**Comment by danxuliu** [comment]
Recording consent for federated users should work already in [#12668](https://github.com/nextcloud/spreed/pull/12668/files#diff-e37e897d7dd8675069229cf0b50fa9bf92ddc114085094b5ecdbe73d50cf3f53R218). Is anything missing (besides integration tests for that)?

**Comment by nickvergessen** [comment]
I raised the ticket before the last commits of your PR. So might be fine, let's keep it fo rthe tests
