### ISSUE TITLE
Join of federated user is missing displayName

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12818]
Join of a federated user misses the displayname, that we usually have for local users.

This is a join from a federated user:
<img width="361" alt="Bildschirmfoto 2024-07-25 um 19 36 50" src="https://github.com/user-attachments/assets/7d7b281c-f39e-4eec-ad20-fec464356b02">

This from a user of the instance:
<img width="388" alt="Bildschirmfoto 2024-07-25 um 19 36 32" src="https://github.com/user-attachments/assets/aef93961-f087-47eb-a14f-34eb43988e63">

_Originally posted by @SystemKeeper in https://github.com/nextcloud/spreed/issues/12802#issuecomment-2251057160_

**Comment by fancycode** [comment]
The userdata is extracted from the auth token (`userdata` in claims), so it must be added there:
https://github.com/nextcloud/spreed/blob/e6f5bc7b3f93b933680feb800c76a2e0b1f4aeae/lib/Config.php#L589-L594

**Comment by nickvergessen** [comment]
I'll have a look, thanks for the pointer
