### ISSUE TITLE
Change logo so that it's not confused with the letter Q

### ISSUE THREAD

**Issue by oparoz** [nextcloud/spreed#1281]
Most people looking at the toolbar from within Nextcloud see the letter Q and don't understand what app it is, until they try it.

We should redesign the app's logo to avoid this.
Maybe as a first step, we could put the leg on the left?

cc @nextcloud/designers

**Comment by nickvergessen** [comment]
I just checked my messengers and indeed, all of them have the foot on the left side

**Comment by WNYmathGuy** [comment]
Wait, wut? It's not a big Q? I thought it would make sense if I spoke another language like Sweedish.

**Comment by jancborchardt** [comment]
> I just checked my messengers and indeed, all of them have the foot on the left side

So if we do the same there will be even more confusion. :wink:

Seriously, this is a hard issue to solve as simple icons for messengers will always conflict with something. Either a letter, or an existing messenger, or something else we didn’t think about.

I’m happy about other suggestions. Filling the circle is something we could also do, but that would make the "confusion with other messengers" even worse. And the circle is there to be a nod to the Nextcloud logo, to make the app related to Nextcloud for people who don’t know it yet.

> Most people looking at the toolbar from within Nextcloud see the letter Q and don't understand what app it is, until they try it.

@oparoz this is also alleviated with the new "show all app names when hovering the app list".

**Comment by mcnesium** [comment]
renaming the app to TAL**Q** could solve this issue

**Comment by DjSlash** [comment]
How much would the confusing concur if all other aspects of the icon breathes 'Nextcloud-app'? 

What if there are two Q's combined, somewhat like [this](https://cdn4.iconfinder.com/data/icons/apps-set-1/24/Comments-01-512.png) ?

**Comment by ruedigerkupper** [comment]
Sorry for me asking, but what does the icon in its current state really mean to depict? It's no Q, so what is it, really …? Sorry for my ignorance.

**Comment by raimund-schluessler** [comment]
> Sorry for me asking, but what does the icon in its current state really mean to depict? It's no Q, so what is it, really …? Sorry for my ignorance.

It is supposed to be a speech bubble.

**Comment by WNYmathGuy** [comment]
> Sorry for me asking, but what does the icon in its current state really mean to depict? It's no Q, so what is it, really …? Sorry for my ignorance.

I asked that too @ruedigerkupper :smiley: It's very abstract because so many other communication apps already trademarked their unique design, and it's really hard to be original.

**Comment by jancborchardt** [comment]
Yeah, it’s supposed to be a speech bubble and a combination with the circle design of the Nextcloud logo:
![Nextcloud Talk logo](https://raw.githubusercontent.com/nextcloud/spreed/master/img/favicon-touch.png)
![Nextcloud logo](https://raw.githubusercontent.com/nextcloud/server/master/core/img/favicon-touch.png)

We could fill it, and/or put the speech bubble triangle on the left, but then it would look rather similar to Signal’s logo, especially since their recent redesign:
![Signal logo](https://signal.org/assets/header/logo-f7ef605fe417d5520d38d546b3b774b4261c75220b9904da4d8b2ffc19a761ff.png)

**Comment by stefan-niedermann** [comment]
Have you ever thought about something like this (just quick mockups):

![grafik](https://user-images.githubusercontent.com/4741199/81416693-5cdfce00-914a-11ea-916d-8e619dbe0191.png)


or try to associate **T**alk with an **T**?

![grafik](https://user-images.githubusercontent.com/4741199/81416778-7da82380-914a-11ea-8969-94978031f9c4.png)

**Comment by stefan-niedermann** [comment]
To be honest: I always thought the focus of the talk app was Voice and Video communication rather than chatting - The current icon indicates associates Talk more with a pure chat focused client than a full communication suite. just my 2 cts :)

**Comment by WNYmathGuy** [comment]
This was what I tried to describe earlier in the thread.
![Mikes Talk Icon](https://user-images.githubusercontent.com/28640985/81430062-cd77f200-912c-11ea-8962-32bf9807a13d.png)

**Comment by stefan-niedermann** [comment]
@WNYmathGuy this won't work as favicon nor as monochrome icon :-/

**Comment by WNYmathGuy** [comment]
> @WNYmathGuy this won't work as favicon nor as monochrome icon :-/

I sadly know that @stefan-niedermann but I had fun making it.

**Comment by Bugsbane** [comment]
Honestly, while I can see that there is potential to be confused for the letter Q, I still feel that the current logo works very well. It does look like a speech bubble, which is appropriate iconography. It does reference the Nextcloud circles, suggesting talking in Nextcloud. It's clean and simple and as such comes across professional.

Yes, it would be great if it could communicate everything it does and look 100% unique and not like any other icon / letter on Earth, but I'd say it does a pretty great job already.

Let's by all means discuss how improvements could be made. I just hope that we can keep what's already great about it (as mentioned above)

**Comment by ruedigerkupper** [comment]
@Bugsbane: I completely agree that this is not the most important issue and that the talk app seems to work well. This is for sure.
However, I disagree that the logo works well: People seem to accept that "Q" stands for "talk", but that does not mean the logo conveys this message. Your say: "It does look like a speech bubble, which is appropriate iconography." I need to say: No, it dies not at all, at least not for me. I never understood the meaning of the logo unless I ask at this very place what it means. Honestly, it never looked anything else but "Q" tor me, and ever time I planned a meeting with friends, I told them: "You need to click the Q-Icon in the apps bar to join out meeting." Sorry if I disappoint the designers, but the logo is not working. At least not for me.

**Comment by ruedigerkupper** [comment]
Not meaning to upset anyone, to say again.

**Comment by Bugsbane** [comment]
Not upset in the slightest. To you it looks like a Q. To me it looks like a speech bubble. Usability testing with a large group size would be needed to know what most people see. Ideally, any test like that would also test against some alternative, which we can talk about here.

On a side note, what would be awesome, would be a "Usability survey" app in the Nextcloud store, that let people opt in to usability surveys which the dev / design teams could use to poll users. To be clear, I'm not talking about asking users what they think we should do, but doing traditional usability polls.

**Comment by nickvergessen** [comment]
Changing the logo is unlikely to happen at this point. We have a lot of "inexperienced" users which learned the icon now. If we change the Logo they will not find the app again easily or be confused, so currently only mirroring the icon would be an option and for that I think we dont really need a long discussion.

I agree the link between Q and Talk might be confusing, it was not intended, but breaking peoples estimate is worse then being able to guide people to a Q or live with the Q.

**Comment by jancborchardt** [comment]
![image](https://user-images.githubusercontent.com/925062/86803566-65835080-c076-11ea-8186-97b462e2d0d4.png)

The speech bubble also has the pointer in the bottom left in the logos of WhatsApp, Signal, Facebook Messenger, Viber, etc. So the conflict with Signal specifically is not really so bad, and rotating/mirroring it this way might be the easiest way to fix the "Q" issue. cc @karlitschek @jospoortvliet in case there’s anything I’m missing.

**Comment by ruedigerkupper** [comment]
Nice point.

**Comment by karlitschek** [comment]
Flipping the icon as suggested is possible. But I am not sure the ‘Q’ issue is really that serious. This is not a huge problem imho. While rebranding is some work and takes time and energy to change the icon in the minds of all users. Honestly I would keep it as is.

**Comment by ruedigerkupper** [comment]
Hi Frank, thanks for caring.
I certainly won't insist. For me, the icon was confusing and I could not perceive its meaning without an explaination. But that does not mean I'm a typical case.

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by Dubidubiduu** [comment]
> ![image](https://user-images.githubusercontent.com/925062/86803566-65835080-c076-11ea-8186-97b462e2d0d4.png)
> 
> The speech bubble also has the pointer in the bottom left in the logos of WhatsApp, Signal, Facebook Messenger, Viber, etc. So the conflict with Signal specifically is not really so bad, and rotating/mirroring it this way might be the easiest way to fix the "Q" issue. cc @karlitschek @jospoortvliet in case there’s anything I’m missing.

For me this looked really like the proper solution for the Q-Problem. Simple, elegant and without breakings for established users.

Must confess I understood the idea for that Logo only by reading this thread.
