### ISSUE TITLE
Disable Calling Functionality

### ISSUE THREAD

**Issue by DrEVILish** [nextcloud/spreed#1282]
Request for Feature

Disable Calling Functionality while leaving the group chat functionality enabled and working.

Ability to disable Video and Screen Sharing while leaving Audio Chat working.

Edit:

@danir-de found a work around:

> You can disable calling and videochatting as well as greying out the button but changing the following database entry:

> `appconfig > spreed > start_calls > 3`

> The buttons etc won't disappear, but all functionality will be disabled.

**Comment by WNYmathGuy** [comment]
I don't know if I'll sound ignorant here, but I tried a voice-only call from app to app and never got it to work right. The icon of the old wired phone handset would start a call but the other person's app had no way to answer it as a voice only call. 

Seems like on a big group video chat business meeting it may be handy to let people who might participate in a questions portion of a Q&A might find voice only useful.

**Comment by JimBTek** [comment]
I'd love to enable just group Chat, and not enable any of the calling, and then progressively add audio, screen and maybe even video.  

This is both for ease of rollout to 140 users and also because our bandwidth at our offices may not allow the others to work well.

**Comment by joe-speedboat** [comment]
@JimBTek 
I just was looking for same functionality. 
Talk is great for teamworking and discussing an issue but bandwith and connectivity needs are not really easy in the wild. 
Would love to see possibility, even if it is disabling audio/video for whole server.
cheers chris

**Comment by WNYmathGuy** [comment]
Tested the Talk app (_NextCloud server 16.0.1_) voice only call from two mobile devices, Google Fi to Verizon. Things went well.

**Comment by yodatak** [comment]
I'm just looking for the same functionality !

**Comment by bes1002t** [comment]
would be a nice feature to reduce the needed bandwith

**Comment by tilobes** [comment]
Hi,
can you explain, why this feature takes so long?
Isn't it that simple, that you just have to modify the function 
public function canStartCall(): bool  
at spreed/lib/Participant.php plus the surrundings like setting options at admin interface?

**Comment by nickvergessen** [comment]
Feel free to send a pull request:
https://github.com/nextcloud/spreed#development-setup

We didn't do it, because it's not on the top of the priority list

**Comment by tilobes** [comment]
Thx for the quick answer, didn't expected that ;)
I have never used github, so my overhead doing that is too large.
How to get this topic up at priority? Is there a voting available?

**Comment by nickvergessen** [comment]
you can leave a 👍🏼  on the first post. That will help sort them in:
https://github.com/nextcloud/spreed/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

But even then it needs to be picked up. The Nextcloud employees currently work on Call features and improvements, so we won't pick up removing this as first "fun" task 😉

**Comment by WNYmathGuy** [comment]
> you can leave a 👍🏼 on the first post. That will help sort them in:
> https://github.com/nextcloud/spreed/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
> 
> But even then it needs to be picked up. The Nextcloud employees currently work on Call features and improvements, so we won't pick up removing this as first "fun" task

@nickvergessen I'm ignorant of all the open-source legalities, but could @tilobes or a collection of Nextcloud Talk dependents pool resources and place a bounty on such a feature to put it on the priority list for some coder inside Nextcloud or even in the ecosystem of related coders doing work on apps related to Spreed or Nextcloud?

**Comment by danir-de** [comment]
You can disable calling and videochatting as well as greying out the button but changing the following database entry:

> appconfig > spreed > start_calls > 3

The buttons etc won't disappear, but all functionality will be disabled.

**Comment by andreas-lindgren** [comment]
Hi @danir-de 

Thank you for the info. This seems to be the best solution at the moment.

One question is if this entry will be changed after a Nextcloud or talk update?

**Comment by danir-de** [comment]
> Hi @danir-de
> 
> Thank you for the info. This seems to be the best solution at the moment.
> 
> One question is if this entry will be changed after a Nextcloud or talk update?

I'm not sure since we enforce it with puppet, but I'd guess that it remains the same when there aren't any related code/db changes to that specific setting.

**Comment by BlueRazer112** [comment]
> 

Hello all,
can someone copy these lines from the appconfig for me?
Unfortunately I can't get the command line to work.

**Comment by gonzalo** [comment]
As our orgnization already provides a videocall solutionm, having this feature having this option on admin gui interface would be really interesting, and seems not hard to implement (not a developer, maybe I'm wrong)

Meanwhile, the DB trick seems to work fine. Call buttons are not seen anywere

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/7043

When you use a supported Nextcloud and Talk version the admin option is there. (was added before the now oldest supported version)

**Comment by idominiki** [comment]
> hey, looking for this.
> 
> * Is this available in the un-supported version
> * where do I change database entries like these: `appconfig > spreed > start_calls > 3`

Login to nextcloud database (for me it's a postgres database) and run this command:

```
UPDATE oc_appconfig SET configvalue = '3' WHERE appid = 'spreed' AND configkey = 'start_calls';
```

**Comment by nickvergessen** [comment]
The UI option was added for Nextcloud 25 / Talk 15.
You should not run a version that is older than that. In fact Nextcloud 27 is even running out of support this month.

**Comment by nickvergessen** [comment]
![image](https://github.com/nextcloud/spreed/assets/213943/634c825e-6e63-4ddb-aae6-94c76dbfbe6b)
