### ISSUE TITLE
Change mention permissions does not create a system message

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12837]
* Related https://github.com/nextcloud/spreed/pull/12618

All other operations we do (Opening for guests, listable, expiration, etc.) do generate system message of that change. Changing the mention permissions does not. Is it intended or should it be added?

**Comment by nickvergessen** [comment]
Changing other permissions does also not post. I think it's fine?

**Comment by SystemKeeper** [comment]
You mean the default permissions of participants? Yea, I think that is a valid point. Then let's close this here?
