### ISSUE TITLE
participantInCall and participantFlags are turned upside down on latest 14 + latest stable spreed

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#1283]
To clarify, here's the output from the server:

"participantInCall":0,"participantFlags":false

Shouldn't it be the other way around?
participantFlags: 0
participantInCall: false

Please shed some light on this or tell me I'm wrong :)

**Comment by nickvergessen** [comment]
Reason is  #1233 is missing from stable14

**Comment by fancycode** [comment]
@mario is this still an issue now that #1291 has landed?

**Comment by fancycode** [comment]
Closing as per offline discussion with @mario
