### ISSUE TITLE
Constantly receiving messages when no cache is configured

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12868]
In a federated scenario, new messages are constantly requested:
![image](https://github.com/user-attachments/assets/e1f58507-5384-4652-939e-88920aa0843e)

It seems to happen when there's no cache configured, although that should already be accounted for in code.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/main/lib/Federation/Proxy/TalkV1/Controller/ChatController.php#L143-L147

Can you tell the headers of the requests, the offsets and the timeout?

**Comment by nickvergessen** [comment]
As per chat I assume that somehow the chat got corrupted by the old bug where we accidentally post a message in the federated copy room and that updates the last read message, etc. and then everything goes ham as we have a message ID and loop (empty) until we get it

**Comment by SystemKeeper** [comment]
![image](https://github.com/user-attachments/assets/5565aa86-dd1e-41ef-9263-d09b44365e61)

**Comment by SystemKeeper** [comment]
It's reproducible in this room, but yes, seems to be specific there, as the other federated room does not show this behavior.

**Comment by nickvergessen** [comment]
Is the offset ID "plausible" for the server?

**Comment by SystemKeeper** [comment]
Cool, does not seem to happen anymore after tonights update. No idea why. Closing for now.
