### ISSUE TITLE
End call button has the same icon as enable video on larger zoom levels

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#12862]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

<img width="692" alt="Screenshot 2024-07-31 at 14 10 44" src="https://github.com/user-attachments/assets/417b6352-a5f5-4c35-9b76-7ecd73ddbad7">

## Steps to reproduce
1. Zoom in your browser while being in a call and having webcam disabled

### Expected behaviour

The buttons should be different so that users know what the action will be

### Actual behaviour

Both the enable camera button and the end call button have the same icon (crossed camera)

### Additional context

**Talk app version:** Current 29 latest on our instance
**Browser:** Firefox on macOS

(sorry for shortening the issue template a bit, just wanted to file this quickly)

**Comment by nickvergessen** [comment]
let's remove the text they said... it will look better on mobile they said...
