### ISSUE TITLE
Confusion about the number of participants

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/spreed#12871]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

I'm highlighting a problem with the word “participant”, which is used in two places in the interface. There are potential participants in the room, whether they are absent, present in the chat, or in a call. They are listed in the participants tab on the right-hand side panel. We also mention participants in calls at the top, next to the button that lets you leave the call. At this point, the number of participants in the call is displayed, which is less than or equal to the number of participants in the right-hand side panel, which makes mathematical sense. Although we see a tooltip indicating “... participants in call” when we hover the cursor over the number of participants at the top of the interface (calls), it's not clear because, instinctively, we can't tell the difference between the two numbers of participants and we wonder if there isn't a bug somewhere (especially as we don't necessarily have the idea of hovering the cursor over the number of participants in call). Confusion is increased by using the same word and icon. In fact, the right-hand side panel lists all the people with access to the room (whether logged in or not) and uses the same word “participant” as for the value at the top (number of people on the call).

I think some thought needs to be given to clarifying all this, using different terms, or making some changes to the presentation, or adding visible information without having to move the cursor over a value.

![2024-08-01_09-10](https://github.com/user-attachments/assets/139fe758-0e5a-4c92-a372-002776ffcfda)

## Feature request

Nextcloud : 29.0.4

Nextcloud Talk app : 19.0.7

**Comment by Jerome-Herbinet** [comment]
@nextcloud/designers

**Comment by nickvergessen** [comment]
topbar should use `7 Participants in call` I guess

**Comment by marcoambrosini** [comment]
I think this needs a bigger solution for 31. I wouldn't add such a long label in the top-bar.

**Comment by nickvergessen** [comment]
It's only about the hover-title of the element, doesn't need a full refactoring spinning out of control.

**Comment by marcoambrosini** [comment]
Oh ok if it's just a tooltip that's ok with me! I thought you wanted that to be the text of the button

**Comment by jancborchardt** [comment]
Agree with @ShGKme’s comment that the current solution as per https://github.com/nextcloud/spreed/issues/12871#issuecomment-2263013417 seems fine. I wouldn’t use a different icon because the icon for "participants" should be the same, and it will be weird to differentiate between a "participants" icon and a "participants in call" icon.

So I would honestly close this. Other solution I see is remove the indicator in the heading and instead have 2 sections in the participants tab, "Participants in call (7)" and "Other participants (6)".
