### ISSUE TITLE
Bots can be activated in former one-to-one conversations

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12883]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Goto a former 1:1
2. Goto conversation settings, try to activate a bot

### Expected behaviour
Not working

### Actual behaviour
Works

## Talk app

**Talk app version:** 20 Beta 2

**Comment by nickvergessen** [comment]
As per https://github.com/nextcloud/spreed/issues/12884#issuecomment-2265303797 deactivating should be allowed

**Comment by nickvergessen** [comment]
Assigning @skalidindi53 for backend work
