### ISSUE TITLE
Avatars of former one-to-one conversations are broken

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12886]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

<img width="290" alt="image" src="https://github.com/user-attachments/assets/24d713cd-3d08-450d-89d0-db0357cc3cbd">

Server now returns a 404 for the avatars, this should be handled in talk.

## Talk app

**Talk app version:** 20 Beta 2

**Comment by Antreesy** [comment]
We need an error handling here, I assume?

https://github.com/nextcloud/spreed/blob/1ccbf67da231c37801c1406b10000144125aec35/lib/Controller/AvatarController.php#L146

**Comment by SystemKeeper** [comment]
Or maybe even in the avatar service ?

It is not a deleted user per se, is it? It’s a conversation of type former-one-to-one and that should always show the single person fallback avatar?

**Comment by SystemKeeper** [comment]
See: https://github.com/nextcloud/spreed/pull/8600
