### ISSUE TITLE
Conversation settings for former one-to-one conversations should be reduced

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#12884]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/eb0f3a69-0407-4b39-b90d-451c59904c6b">

In former 1:1 information like "Mention permissions", "Recording consent", "Bots" or "Message expiration" do not make sense and should not be visible.

Related API wise:
* https://github.com/nextcloud/spreed/issues/12883
* https://github.com/nextcloud/spreed/issues/12882

## Talk app

**Talk app version:** 20 Beta 2

**Comment by nickvergessen** [comment]
Bots might be useful, so you can "uninstall" them?

**Comment by SystemKeeper** [comment]
Indeed, that would be good. Alternatively I wonder if we should disable any bots when we set the room as former 1:1 ?

**Comment by nickvergessen** [comment]
Could also make sense
