### ISSUE TITLE
Make more obvious that you can add Federated Cloud ID accounts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#12912]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
Latest master of v30.

**Is your feature request related to a problem? Please describe.**
Currently it is not very clear that you can add people to conversations via Federated Cloud ID, as noted by @karlitschek 
![image](https://github.com/user-attachments/assets/4f7ffb7a-a11e-4dc5-83d1-66a469146985)

**Describe the solution you'd like**
In Files, the input at least says:
> Name, email or Federated Cloud ID …

The placeholder can be adjusted to be similar:
> Search or add participants via name or Federated Cloud ID …

Maybe even something shorter works.
![image](https://github.com/user-attachments/assets/bb5523e2-a19c-4a50-99aa-c5c0f7b2d449)

**Describe alternatives you've considered**
To make it even more visible, in addition to adjusting the placeholder, we could add a short info-paragraph below the search field saying something like:
> Participants can now also be added via Federated Cloud ID. Find yours in the sharing settings.

("sharing settings" is a link to: `settings/user/sharing`)

**Comment by ShGKme** [comment]
> To make it even more visible, in addition to adjusting the placeholder, we could add a short info-paragraph below the search field saying something like:

A permanent note between the search and the participants list? Won't it be too much?

**Comment by ShGKme** [comment]
> The placeholder can be adjusted to be similar:
> 
  > > Search or add participants via name or Federated Cloud ID …

This is quite a huge line even in English. And even bigger in other languages like German

Small | Large
---|---
![image](https://github.com/user-attachments/assets/a2a69d4b-7271-4728-bf8c-623071ae2169) | ![image](https://github.com/user-attachments/assets/2c258457-e6d4-4a2a-b58e-b795cb20265c)


> Name, email or Federated Cloud ID …

In this case, though, it's less obvious than you can use search for adding participants.

**Comment by karlitschek** [comment]
So this longer description text takes a lot of space and is too short to properly explain it to users at the same time. Can we do something with a mouseover. or make the input line bigger with more explanation on click?

**Comment by DorraJaouad** [comment]
![image](https://github.com/user-attachments/assets/2770f072-412b-4bd3-84b4-058e286b7a5e)

We can add a popover with "info" button next to the search box. When focusing on the search box, it can be expanded to cover the button so to be able to read the placeholder (like search box in left side bar).

**Comment by ShGKme** [comment]
Hiding the full placeholder under a button seems also complex and non-obvious for users.

I think, from the UX side, the problem is that this field is at the same time the "search" and the "add" field. And sometimes it's only a search. 

In this case a user even has no clue that it has no right to add participants and may think that the "add" feature is just somewhere else.

Maybe instead of an "info" button add an "Add participants" button that explicitly switches search to adding mode. It can also be disabled with a hint to explain, why it is disabled.

**Comment by DorraJaouad** [comment]
> Maybe instead of an "info" button add an "Add participants" button that explicitly switches search to adding mode. It can also be disabled with a hint to explain, why it is disabled.

Maybe to keep it separate, we can render "add participants" modal instead (from new conversation creation). User can see all users without typing a character and can do bulk addition.

**Comment by ShGKme** [comment]
> Maybe to keep it separate, we can render "add participants" modal instead (from new conversation creation). User can see all users without typing a character and can do bulk addition.

Sounds good actually

@jancborchardt What do you think?

**Comment by jancborchardt** [comment]
> ![image](https://github.com/user-attachments/assets/2770f072-412b-4bd3-84b4-058e286b7a5e)
> 
> We can add a popover with "info" button next to the search box. When focusing on the search box, it can be expanded to cover the button so to be able to read the placeholder (like search box in left side bar). 

I like @DorraJaouad's suggestion here, would also be in line with what Frank suggested with the tooltip.

I would not split search and add or render the dialog here, as it would hinder the flow which currently is super quick and seamless.
