### ISSUE TITLE
Windows compatibilty: upload does not show correct error

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#12914]
- enable windows compatible filenames (in admin -> settings)
- try to upload a forbidden file, e.g. CON
- see without any real error message, only "error while uploading file"
![image](https://github.com/user-attachments/assets/23a2ae75-b848-4c44-8b05-d39be79f9617)

**Comment by DorraJaouad** [comment]
We can parse error XML response to extract the message and show it in a toast.

**Comment by tobiasKaminsky** [comment]
But is also seems to have an endless "spinner"?
You can test on our daily LTD, if you like.

**Comment by DorraJaouad** [comment]
It's not a spinner, it's an empty uploading indicator meaning uploading wasn't progressing. We think that empty loading indicator with an exclamation mark on the right side is enough explain to user that upload has failed. Maybe it would be clearer if it turns to red circle ?

**Comment by ShGKme** [comment]
Maybe we should just rename the file? We do it anyway on name conflict.

**Comment by nickvergessen** [comment]
> Maybe we should just rename the file?

That's non-trivial in the future. We should error here.

**Comment by nickvergessen** [comment]
Same as when you upload a `.htaccess` file or something else that is blocked
