### ISSUE TITLE
Internal link sharing without integration in chats

### ISSUE THREAD

**Issue by jcharaoui** [nextcloud/spreed#12935]
While the internal link preview/integration in chats is a useful feature, it can get in the way of a conversation.

For example, when sharing a link to a Nextcloud document or Deck boards, the integration takes up a lot of screen space.

The interactivenes is also often a distraction: working on a document or a deck board from within a chat conversation doesn't really work well because the viewport is reduced compared to when they're opened in their own tab.

It should be possible to post a link to an internal document without integrating it directly into the conversation.

Furthermore, it would be very useful to be able to disable these previews/integrations per conversation.

**Comment by ShGKme** [comment]
- duplication of https://github.com/nextcloud/spreed/issues/8609
