### ISSUE TITLE
Be specific about signaling server version required

### ISSUE THREAD

**Issue by manumitted** [nextcloud/spreed#12946]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
NC Version 30 Beta 5

**Is your feature request related to a problem? Please describe.**

Error message "The configured signaling server needs to be updated to be compatible with this version of Talk. Please contact your administration." and/or " RuntimeException Signaling server needs to be updated to be compatible with this version of Talk
Failed to send message to signaling server " is not specific enough for me to know how to fix the problem.  

**Describe the solution you'd like**

It would be great if at least one of those messages would convey which server version would be required.

**Describe alternatives you've considered**

More information in the Admin panel.

**Additional context**

**Comment by fancycode** [comment]
Federation support is part of nextcloud-spreed-signaling 2.0.0 and was just released at https://github.com/strukturag/nextcloud-spreed-signaling/releases/tag/v2.0.0
