### ISSUE TITLE
UI elements gone (top left and top right)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/spreed#12948]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. unable to reproduce reliably, it just happened three times today, never happened before today. (To try to reproduce, click on different chats on cloud.nextcloud.com - after a while it happens):
2. UI elements at the top left (search) and top right (sidebar) are gone:
<img width="960" alt="357179328-fba47b40-4a90-401d-9442-af04a0c5ab37" src="https://github.com/user-attachments/assets/7e923bbc-597d-4778-848c-f55228fdd9db">

### Expected behaviour
UI elements at the top visible/usable 

### Actual behaviour
UI elements at the top not visible/usable 

## Details
this is on cloud.nextcloud.com
NC 30.0.0 beta 5
I can't see the app version

## Browser
Firefox 129.0
there is no error in the browser console when it happens...

**Comment by nickvergessen** [comment]
Did you try "Ctrl + F5" as per email?

**Comment by alexanderdd** [comment]
The problem was gone when I did a regular refresh.

Now I did a ctrl f5, maybe that will fix the problem, I will report here if it happens again.

**Comment by nickvergessen** [comment]
Closing for now
