### ISSUE TITLE
compose message field sometimes not showing

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/spreed#12949]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. not reliably but it happened a few times today, and never before:
2. open new chat with a person on cloud.nextcloud.com
3. compose message field not showing
4. reload - message field is back

### Expected behaviour
message field always there

### Actual behaviour
message field gone

## Details
this is on cloud.nextcloud.com
NC 30.0.0 beta 5
I can't see the app version

## Browser
Firefox 129.0
there is no error in the browser console when it happens.

**Comment by ShGKme** [comment]
Did you try force refresh with CTRL+F5?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/12948#issuecomment-2284966938

**Comment by alexanderdd** [comment]
The problem was already gone when I did a regular refresh.

Now I did a ctrl f5, maybe that will fix the problem, I will report here if it happens again.
