### ISSUE TITLE
Should be able to ban federated users?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12945]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Ban code should fully support federated users?
https://github.com/nextcloud/spreed/blob/c61cc1055147ff215cfd3b81dff6f8a919b06f56/lib/Service/BanService.php#L48
does not allow them, but 
https://github.com/nextcloud/spreed/blob/c61cc1055147ff215cfd3b81dff6f8a919b06f56/lib/Service/BanService.php#L80
checks for it? Or we remove it in the later line to avoid confusion?

Also the first line should use the Attendee constants when they exist (not the case for `'ip'`, but all others)

**Comment by SystemKeeper** [comment]
Does it make sense to ban a federated user, as a federated user can't join on its own, but needs to be explictly added?

**Comment by skalidindi53** [comment]
> Does it make sense to ban a federated user, as a federated user can't join on its own, but needs to be explictly added?

I think so, even as a safety measure, it's better to be able to ban federated users.
