### ISSUE TITLE
Deprecate "clustered HPB" mode

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13011]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Once @fancycode is back from vacation, we should align on the way to scale the HPB (is it multiple configured, or one configured and that might be a load balancer, or …) and then remove the "fake clustering" which assigns a single HPB to a conversation

**Comment by fancycode** [comment]
The recommended way is to have a cluster of signaling servers running behind a frontend server / load-balancer that distributes the requests between the avaliable servers and have that single frontend URL configured for Talk.

That way the load-balancer will do the failover in case one of the signaling servers goes down and you don't have to check from Talk if the assigned server is still available and select a different one if not.
