### ISSUE TITLE
"Next call" is showing thing from the past when it's "current"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13047]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Screenshot from 15:58 (2 minutes before the scheduled end)
![Bildschirmfoto vom 2024-08-20 15-58-12](https://github.com/user-attachments/assets/eabc1562-d831-4b6c-ab73-bdbc35871d40)

I think it should only show that before the meeting, maybe overlapping 5-10 minutes? 
cc @jancborchardt @st3iny

**Comment by jancborchardt** [comment]
> I think it should only show that before the meeting, maybe overlapping 5-10 minutes?

Yep, I would say it could still say:

> Next call
> Now

For the first 5 minutes, and after that people already see during the current call when the next call will be.

**Comment by nickvergessen** [comment]
@st3iny according to the API it seems to only want to get events for -1 minute:
https://github.com/nextcloud/server/blob/370a9d77ea0aadd736d42741623cf98729797d8b/apps/dav/lib/CalDAV/UpcomingEventsService.php#L39

Is the `lastoccurence` and `firstoccurence` check wrong in the backend?
https://github.com/nextcloud/server/blob/b8ec68d212cb7214c862ee817e2661e67c6a4582/apps/dav/lib/CalDAV/CalDavBackend.php#L1935-L1957

https://github.com/nextcloud/server/blob/b8ec68d212cb7214c862ee817e2661e67c6a4582/apps/dav/lib/CalDAV/CalDavBackend.php#L1935-L1957

**Comment by jancborchardt** [comment]
Also noticed that the "Next call" info is not showing while you are in the call, which is what I assumed when I left the above comment: https://github.com/nextcloud/spreed/issues/13047#issuecomment-2299769474

**Comment by nickvergessen** [comment]
> Also noticed that the "Next call" info is not showing while you are in the call,

I'm also not sure it should be. The top bar is quite heavy already when you are in a call:
![grafik](https://github.com/user-attachments/assets/2660bca4-dd18-477a-b105-17c745cb8e73)

**Comment by jancborchardt** [comment]
@nickvergessen yes good point, it’s a different topic also.

**Comment by DorraJaouad** [comment]
> For the first 5 minutes, and after that people already see during the current call when the next call will be.

So show "Now" for 5 minutes after the starting time and until the ending time of the event?
a) show nothing
b) show the next event

For now, it shows the current event until its end.

**Comment by jancborchardt** [comment]
@DorraJaouad I’d say b), show the next event. Because:
- Showing the current event is not needed as the call is live already anyway
- Showing nothing is not really useful
- Showing the next event has some value, to know when then next one is

**Comment by nickvergessen** [comment]
Since the API gives you an event, we should basically do:
- if time is in the past, show "Now"
- Otherwise if you get something show that
- if you get nothing, show nothing


That the 1h old event was returned is an API bug that should be solved there (from the code it looks like it would not want to return it)

**Comment by DorraJaouad** [comment]
Use "Now" or "Ongoing"? as we will keep until the end of the event :)

**Comment by nickvergessen** [comment]
Reopening for the backend issue mentioned in https://github.com/nextcloud/spreed/issues/13047#issuecomment-2301864538
