### ISSUE TITLE
Removing a federated participant has wrong message?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13048]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

What I see:
![Bildschirmfoto vom 2024-08-20 16-04-17](https://github.com/user-attachments/assets/02217f51-68cf-4346-b05e-d86a844f42c8)

What Andy sees:
![Nicht gespeichertes Bild 1](https://github.com/user-attachments/assets/5927cdc3-df34-4eed-95d4-939aa967d7a9)

**Comment by Antreesy** [comment]
I might have found another case that requires a fix:

Host: nextcloud.local
- as `admin@nextcloud.local` - send invitation
- as `admin@nextcloud2.local` - decline invitation
- see result:

as `admin@nextcloud.local` | as another user
-- | -- 
![image](https://github.com/user-attachments/assets/4307a64b-99b5-4ddb-8de9-b9ea197ffdd3) | ![image](https://github.com/user-attachments/assets/182c642d-b81c-4b6d-b0d7-183413b8cedb)
