### ISSUE TITLE
improve turn server test

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1305]
It is great that with the latest release we can test the turn server settings! But it took my quite some time to identify the button for it.

Therefore my suggestion. I think it would be an improvement if it would work similar to the external storage settings and have a colored sign which indicated if the turn server is configured correctly:

![image](https://user-images.githubusercontent.com/1589737/48784139-581f2400-ece2-11e8-9f8f-630009891007.png)

If the user enters the settings the test should be triggered and show a green or red sign. Same if the user change the settings, a test should be triggered automatically and the sign updated.

**Comment by nickvergessen** [comment]
Done with #1596
