### ISSUE TITLE
Error on "Join call" is not shown to user

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13077]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

- Extracting from https://github.com/nextcloud/spreed/issues/13045

## Steps to reproduce
1. As a user try to join a call
2. Receive a 400 response, see patch below for hardcoded 400

```diff
diff --git a/lib/Controller/CallController.php b/lib/Controller/CallController.php
index 373337913..c8a6fe00f 100644
--- a/lib/Controller/CallController.php
+++ b/lib/Controller/CallController.php
@@ -136,6 +136,7 @@ class CallController extends AEnvironmentAwareController {
        #[RequireParticipant]
        #[RequireReadWriteConversation]
        public function joinCall(?int $flags = null, ?int $forcePermissions = null, bool $silent = false, bool $recordingConsent = false): DataResponse {
+               return new DataResponse(['error' => 'consent'], Http::STATUS_BAD_REQUEST);
                try {
                        $this->validateRecordingConsent($recordingConsent);
                } catch (\InvalidArgumentException) {
```

### Expected behaviour
You see an/the error message

### Actual behaviour
Browser warning about leaving the page:
![grafik](https://github.com/user-attachments/assets/d49e06de-6ea5-4663-b973-d7c78c5947d9)

**Comment by Souptik2001** [comment]
Hey @nickvergessen I am not sure about the exact design that was required (like whether the error message should be just a toast using `showError()` or not), but does this look good? -


https://github.com/user-attachments/assets/38194ca9-1f06-4419-862d-914214f26f24


If yes then I have raised a PR for this above.
