### ISSUE TITLE
Recording consent property is inconsistent 

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#13085]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

API on room level should only return 0/1, but seems to be able to also return 2. 

## Talk app

**Talk app version:** 20 RC2

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/spreed/blob/7f414d3fd2b6fa6be2a1ee6fcf2417d87bcee2c0/docs/conversation.md?plain=1#L111 might need change then to not refer to the consent constants?

**Comment by nickvergessen** [comment]
It's properly documented in OpenAPI docs:
https://github.com/nextcloud/spreed/blob/956a1ab00ffb25d87c0f5192333c9b66e56a63fe/lib/Controller/RoomController.php#L2284-L2285

Will adjust the other docs too
