### ISSUE TITLE
Add previews for links on tiktok (not showing on web or android app)

### ISSUE THREAD

**Issue by kaincenteno** [nextcloud/spreed#13132]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 29.0.4

**Is your feature request related to a problem? Please describe.**
It's really difficult to get someone to click on a URL if there is no preview of it from tiktok. It works for other services like instagram but not tiktok.

**Describe the solution you'd like**
I'd like to see preview of tiktok videos like it works when sharing on other applications like messenger/whatsapp

**Describe alternatives you've considered**
Talking about the video when sending it so it doesnt feel like a random URL without context

**Additional context**

this is how it looks in talk

<img width="807" alt="Screenshot 2024-08-24 at 8 25 07 AM" src="https://github.com/user-attachments/assets/cb6dbd6c-746e-4ad0-ac27-4b73f0a5ac32">

this is how it looks in messenger (same link)

<img width="807" alt="Screenshot 2024-08-24 at 8 47 13 AM" src="https://github.com/user-attachments/assets/a03f3745-1257-4101-8256-bf21bbc13305">

**Comment by nickvergessen** [comment]
The link rendering is done by the server. We show the opengraph data which is a standard for this. If tiktok does not provide this there is nothing the server can do.
