### ISSUE TITLE
Cannot open a new talk conversation from mobile Firefox and Chrome

### ISSUE THREAD

**Issue by PeopleInside** [nextcloud/spreed#13134]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open nextcloud from a mobile device using the browser and navigate to talk application. I tried with the latest version of Chrome and Firefox on an Android 14 device
2. Try to create a new conversation, once the button to create is pressed you cannot type a name or a description so the conversation cannot be created

### Expected behaviour
When the name and description field, on the conversation creation screen is clicked in a touch android device from the mobile browser, the keyboard to type inside the field should be showed. Is not.

### Actual behaviour
When the name or the description field is pressed from a mobile touch device, the mobile keyboard should be showed. Is not happening, unable to type in the field also if I set the browser to show the page as desktop. I'm unable to type conversation name with a mobile touch device.

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)
19.08

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`) NO

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)
NO

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)
NO

## Browser
Firefox mobile developer and Chrome stable

**Operating system:** Windows/Ubuntu/Mac/...
Server is Ubuntu, the issue is from Android device when surfing the talk web interface to create a new conversation

**Browser name:** Firefox/Chrome/Safari/...

Firefox Nightly for Developers 

**Browser version:** 124/125/...
131.0a1

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```
No browser log on mobile
</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu

**Web server:** Apache/Nginx
Apache and Nginx as proxy

**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria

**PHP version:** 8.1/8.2/8.3
8.3
**Nextcloud Version:** (see administration page)
[Nextcloud Hub 8] (29.0.5)
**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>
https://help.nextcloud.com/t/cannot-open-a-new-talk-conversation-from-mobile-firefox-and-chrome/201704

**Comment by Antreesy** [comment]
Was fixed in nextcloud/vue 8.15.0, we just didn't bump the library for this Talk version

**Comment by PeopleInside** [comment]
When I will be able to test this fix?
On the next nextcloud update?
Thanks.

**Comment by Antreesy** [comment]
> On the next nextcloud update?

Hi! Yes, should be available with the next Talk release for version 29.
As I said before, in recent versions (30 at the moment) it's already fixed, tested with Android/Chrome
