### ISSUE TITLE
follow-up(CallView): connection state visual enhancements

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#13160]
Some follow-ups for the CallView:
- [x] replace `<div class="iconClass" />` with MDI icons used across the project: https://pictogrammers.com/library/mdi/icon/alert-octagon/
  - [x] Make sure color is consistent on light-dark theme
- [x] add statusCode from response to `connectionFailed` state (Dorra)
  - [x] apply translations from iOS repo
  - [ ] check qualityWarningTooltip for reuse at the same place https://github.com/nextcloud/spreed/blob/main/src/components/TopBar/TopBarMediaControls.vue#L323
- [x] Think about https://github.com/nextcloud/spreed/pull/13133#issuecomment-2315134339: intermediate state while connecting / do not switch to CallView at all

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/issues/13133#issuecomment-2315209527_

**Comment by DorraJaouad** [comment]
>  intermediate state while connecting / do not switch to CallView at all

We can put a modal showing loading status until we receive a response from join call request. If it's success, modal goes away as the call view appears and if it's an error, the modal stays there showing the error message. wdyt ?

**Comment by DorraJaouad** [comment]
@Antreesy do we close this?
