### ISSUE TITLE
Reintroduce notification radio in the conversation menu 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#13176]
now that we have space
<img width="263" alt="Screenshot 2024-08-29 at 12 02 22" src="https://github.com/user-attachments/assets/59964765-5b43-4cfe-9f1b-9431cd491fb6">

Possibly in a submenu

**Comment by nickvergessen** [comment]
Since we are going to add more notification options I'm not sure that is suitable

**Comment by ShGKme** [comment]
I did not understand the proposal. What is proposed to be in a sub menu?

**Comment by marcoambrosini** [comment]
The 4 notifications options we'll have:
- off 
- direct mention
- team mention
- all

**Comment by nickvergessen** [comment]
And call?

**Comment by marcoambrosini** [comment]
What's the plan with call notifications? So far call is always notified unless `off` no? Would we have 2 'sections' with call notification switch and message notification radio?

**Comment by ShGKme** [comment]
It's a separate setting:

![image](https://github.com/user-attachments/assets/e8a6260b-a257-4716-be0c-4f1256d710e1)

**Comment by marcoambrosini** [comment]
OK so would be fine by me if it was a submenu with: 

<- Back `NcActionButtton`
All messages `NcActionRadio`
All @-mentions `NcActionRadio`
Direct @-mentions only `NcActionRadio`
Off `NcActionRadio`
Call notifications `NcActionCheckbox`
