### ISSUE TITLE
Video is overlapped by chat on narrow windows

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1318]
Similar to #1054, the video is overlapped by the right panel if the browser window is too narrow. Instead, the video should be scaled down to be visible completely and to avoid clipping people that are on the left/right side of the video,

**Comment by nickvergessen** [comment]
Delayed until after Vue

**Comment by nickvergessen** [comment]
Ref #1056

**Comment by nickvergessen** [comment]
Closing as per above
