### ISSUE TITLE
Let audio recordings play after each other

### ISSUE THREAD

**Issue by devserge** [nextcloud/spreed#13199]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
29.0.6 (RC)

**Is your feature request related to a problem? Please describe.**
No,  there is no problem.

**Describe the solution you'd like**
On, for example Whatsapp, when you send multiple voice memo's they keep playing after each other so you don't need to press them all. In nextcloud, you have to keep clicking on play. Maybe it's a nice idea to make them just play after each other automatically.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Souptik2001** [comment]
@nickvergessen Raised a PR for this one! 👆
