### ISSUE TITLE
Reloading public room sometimes redirects to login page

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1319]
## Steps to reproduce
1.Create public room
2.Open public room as anonymous user
3.Reload the page a couple of times

### Expected behaviour
Shoud always load room.

### Actual behaviour
Sometimes the browser is loading the login page (as "https://server.tld/login?redirect_url=/apps/spreed/%3Ftoken%3D").

## Browser

**Operating system:**
Ubuntu 18.04

**Browser name:**
Firefox

**Browser version:**
63, 64-bit

## Spreed app
master 7168c684afd29d0c28b9ad4c148dc590e52fbb4d

No error in nextcloud.log

**Comment by nickvergessen** [comment]
I noticed this too, but I never managed to find out why

**Comment by nickvergessen** [comment]
Closing this in the hope that the rebuild frontend fixed this
