### ISSUE TITLE
Bot enable and disable routes have no "target" key

### ISSUE THREAD

**Issue by kyteinsky** [nextcloud/spreed#13204]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Enable/Disable a bot in a room

### Expected behaviour
The received params should contain the "target" key which should have a "type" key with value "Collection".

### Actual behaviour
The "object" key instead has the values of the collection. This only happens on the enable/disable routes that were introduced in #12551.
Lines of interest from my understanding: https://github.com/nextcloud/spreed/blob/main/lib/Service/BotService.php#L57-L87
The docs related to bots: https://nextcloud-talk.readthedocs.io/en/latest/bots/

cc @sanskar-soni-9 @Antreesy 

## Talk app

**Talk app version:** 21.0.0-dev.0

**Comment by sanskar-soni-9** [comment]
from [Activity Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-join)
> JOIN: Indicates that the `actor` has joined the `object`. The `target` and `origin` typically have no defined meaning.

But in our case [target](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-target) makes meaning from the context. so go with `object` or `target`?

**Comment by Antreesy** [comment]
cc @skalidindi53 for discussion

**Comment by sanskar-soni-9** [comment]
Maybe if we don't overthink it, we can go with `target` as the same is used while receiving message

**Comment by skalidindi53** [comment]
I think using `target` makes sense to me
