### ISSUE TITLE
Set conversation avatar updates account avatar instead

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#13208]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Quite an edge case, but still happens under conditions described below.

## Steps to reproduce
1. Upload square picture via Files app (width = height)
2. Try to set conversation avatar "from Nextcloud"
3. See result

### Expected behaviour
Cropper should open (to show how picture would look like, and maybe crop some more)

### Actual behaviour

Frontend logic copied from server settings / AvatarSection:
https://github.com/nextcloud/spreed/blob/bd84203ddd2672fc017fa9883a315a0da2e20445/src/components/ConversationSettings/ConversationAvatarEditor.vue#L278-L288

If image is square, cropping isn't requested, and image is set by default endpoint => as avatar image
https://github.com/nextcloud/server/blob/af6de04e9e141466dc229e444ff3f146f4a34765/core/Controller/AvatarController.php#L243-L254

## Talk app

**Talk app version:** (main, but given server/frontend code is unchanged, also valid for 17)

**Comment by Antreesy** [comment]
Looking at the upstream server code, it should be possible to add a flag (like `temp`) to skip dimensions check and cache a result to get it from `avatar/tmp`?

**Comment by nickvergessen** [comment]
Well the tmp thing would conflict between 2 moderators modifying the same conversation image at the same time. Not sure that's worth it for now. Maybe instead we just "error"?

**Comment by Antreesy** [comment]
> Maybe instead we just "error"?

Not sure if we can, as server will return 'success'. Will take a look if we can avoid using '/avatar' endpoint and prepare smth like Blob instead on a client
