### ISSUE TITLE
Nextcloud Talk should Work with Matrix

### ISSUE THREAD

**Issue by thoys1** [nextcloud/spreed#13212]
Hello everyone, 

My Festure Request is a suggestion to reduce the jungle of messengers a little. 

Is it possible to underpin Talk with a matrix structure? In other words, that Talk no longer has a self-built substructure, but uses the Matrix network. 

My idea would be that when I install Talk, a Matrix server is installed and Talk can communicate with everyone who uses Matrix. So Nextcloud doesn't isolate itself, but becomes part of a large messaging ecosystem. 

There is the possibility of a bridge, but that's not what I mean. 

That would be THE solution for many institutions and private individuals. I install or buy a Nextcloud and have a matrix server already included. Whether I use Element or Talk would then be irrelevant. 

Talk could then become a very well-functioning Matrix client alongside Element. 

The symbiosis of both would create new Nextcloud users and new Matrix users. 

Best regards

**Comment by Antreesy** [comment]
Hi! Is your suggestion similar to what is currenlty being discussed at https://github.com/nextcloud/spreed/issues/809 ?

**Comment by thoys1** [comment]
Thanks a lot. And sorry for my bad search scills. I searched, bevore i wrote my own comment, but not good enoug :-) 

Have a nice week!
