### ISSUE TITLE
"Scroll to bottom" does not scroll all the way

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#13237]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a conversation
2. Navigate somewhere else
3. Miss lots of messages
4. Open the conversation again
5. Click *Scroll to bottom*

### Expected behaviour

I'm scrolled to the very bottom

### Actual behaviour

I'm scroll a bit but there are still messages below. *Scroll to bottom* will still show. If I click it a couple of times I eventually reach the bottom.

## Talk app

**Talk app version:** the one for Hub 9

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by Antreesy** [comment]
> Miss lots of messages

How many messages are we talking about? Are all new of them uploaded? 
Are there any link previews in this list

My first assumption is that there's something in the list that will extend the list and we can't consider at the moment

**Comment by DorraJaouad** [comment]
If it's a long list, it can fetch progressively by scrolling down. So when you first press "scroll to bottom" , it reaches the end of fetched messages list and then fetch the next batch.

**Comment by Antreesy** [comment]
This might interrupt the scrolling (tried with file preview widgets): https://github.com/nextcloud/spreed/commit/4081fd58484083ddab831b82af20f1151553e4a0

**Comment by DorraJaouad** [comment]
Also tried to reproduce, it seems widget anti-jumping blocks scroll to bottom from being completed.
