### ISSUE TITLE
Unread mention notification does not go away if the message in question has been deleted

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/spreed#13286]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Login as one user, send a direct message to another user.
2. Delete the message.
3. Login as the other user, see the unread mention button
4. Click the button - conversation scrolls down but no unread messages visible.
5. Reload the page - unread mention button still there.

### Expected behaviour
Either the unread mention button should not show
or it should disappear after the scrolling and opening the conversation with the deleted message for the first time.

### Actual behaviour
The unread mention only went away after staying in the conversation in question for a prolonged time (to take a screenshot).

## Talk app

on cloud.nextcloud.com

**Talk app version:** 20.0.0-rc4

## Browser

Firefox

### Browser log
![grafik](https://github.com/user-attachments/assets/57df46eb-6acc-4397-9d1e-97dad323cea4)
![grafik](https://github.com/user-attachments/assets/3ea3a5ca-0dcd-46b1-bb9e-7d14d9d699ba)

## Server configuration

cloud.nextcloud.com

**Comment by Souptik2001** [comment]
@nickvergessen Seems like we just had to bust the unread cache on the delete message action. I checked to see if there will be any regression issues due to this seems like no.
