### ISSUE TITLE
Banning a user shows error and afterwards offer to remove yourself

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13334]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a group conversation
2. Remove and ban a user

### Expected behaviour
- User is removed and banned

### Actual behaviour
- You see a message that ban failed
- The user is banned
- The user is removed
- Afterwards the dialog offers to "ban yourself"

**Comment by ShGKme** [comment]
https://github.com/user-attachments/assets/3f57c406-f50c-4a48-a3f0-832295f039b0
