### ISSUE TITLE
Files inside a shared folder should provide a room accessible by the users that can access the folder

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1338]
Each file should have its own room; if the file is then reshared with other users those users should be able to access the room as well, but not the rooms of other files in the shared folder.

**Comment by nickvergessen** [comment]
isn't that the case already?

**Comment by danxuliu** [comment]
No, there are two issues here.

First, the server only creates a room for a file if the file itself is shared. This is trivial to fix, and it would require just checking the parents of the file until the root to see if any of them is shared.

The second problem is the client. The FileInfo object for files in a shared folder includes the `shareOwnerId` property when got as the sharee, but not when got as the sharer. So, for the receivers of a shared folder the _Chat_ tab is shown for the files in that shared folder (although the chat itself does not work due to the server issue above), but for the sharer it is not.

Even if the _Chat_ tab is going to be always shown for files the FileInfo properties will still be used to check whether to show the chat itself or the _Start a conversation_ message, so the problem persists.

I see two options to fix this; either by adding the needed information to the FileInfo properties to know that a file is in a folder shared by the user (maybe not having the `shareOwnerId` is even a bug of the server, I have not checked yet), or whenever the _Chat_ tab is opened a spinner or something like that is shown while sending a request to the server to know if a room can be created for that file (not a fan at all of this second option).
