### ISSUE TITLE
Participants of rooms for files should be made persistent when they join

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1339]
Currently the participants of rooms for files are removed from the room as soon as they leave it. Instead, they should be persistent, so once the user has joined a room through the Files app the room can be later accessed from the main Talk UI and the mobile apps even if the file is no longer open in the Files app.

Like in any other public room, once joined persistent participants will be able to remove themselves from the room by using the main Talk UI or the mobile apps.

The documentation should be updated in https://github.com/nextcloud/spreed/blob/19e166191ba58a6d0919f81ef491eecc867458f8/lib/Controller/FilesController.php#L78-L79 and https://github.com/nextcloud/spreed/blob/3b103512520b6fae1afa2dfad09cae85776fc37e/lib/Files/Listener.php#L38-L39

**Comment by nickvergessen** [comment]
Also "Messages for "User joined the conversation" is missing"
