### ISSUE TITLE
Absolute link breaks href in certain situations

### ISSUE THREAD

**Issue by MightyM17** [nextcloud/spreed#13405]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open Nextcloud dashboard
2. Check the app menu items links
3. Spreed will have a hardcoded link

### Expected behaviour
Ideally all links (href) are relative, so even if the base url is different, we can naviagte

### Actual behaviour
Spreed hardcodes the href which breaks the navigation

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 130.0.0.1

### Browser log

<details>

```
<li data-v-62f74e6b="" data-app-id="activity" class="app-menu-entry"><a data-v-62f74e6b="" href="/apps/activity/" aria-label="Activity" title="Activity" class=""><img data-v-62f74e6b="" src="/apps/activity/img/activity.svg" alt=""> <div data-v-62f74e6b="" class="app-menu-entry--label">
					Activity
                                       <!----></div></a></li>
<li data-v-62f74e6b="" data-app-id="spreed" class="app-menu-entry"><a data-v-62f74e6b="" href="http://SERVER_IP_ADDR:10081/apps/spreed/" aria-label="Talk" title="Talk" class=""><img data-v-62f74e6b="" src="/custom_apps/spreed/img/app.svg" alt=""> <div data-v-62f74e6b="" class="app-menu-entry--label">
					Talk
					<!----></div></a></li>
```

</details>

## Server configuration

**Operating system**: Ubuntu/CasaOS

**Web server:** Nginx

**Database:** Maria

**PHP version:** 8.1

I have used nginx to get HTTPS access in the server with the following config, nextcloud runs on 10081 originally with nginx proxy on 10082 to get HTTPS access
```
server {
  listen 10082 ssl;
  listen [::]:10082;
  server_name $NAME;
  ssl_certificate $CERT.crt;
  ssl_certificate_key $KEY.key;

  location / {
    proxy_pass http://SERVER_IP_ADDR:10081/;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Accept-Encoding gzip;
    }
}
```

**Comment by nickvergessen** [comment]
Absolute links have to be used in several places to not break clients.
The top bar app included, as those links are also shown by the desktop client.

Check https://docs.nextcloud.com/ or the forum for help on fixing your setup properly instead.
