### ISSUE TITLE
Talk sidebar not shown for public shares in Nextcloud 31

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#13402]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

In Nextcloud 31 the public share page for single files and for folders was unified [when it was migrated to Vue](https://github.com/nextcloud/server/pull/45652); now single file shares show a file list with a single file, but no Talk sidebar.

Note that in previous Nextcloud versions the Talk sidebar was shown for public shares of a single file, but not in folder shares.

Anyway, maybe there will be further changes to the public share pages (I think that @susnux mentioned something about that, like providing a file list sidebar, but I might be mixing things up, many chats during the conference :-) ), so it would be worth taking those possible changes into account when fixing this.

## Steps to reproduce
- In Talk administration settings, ensure that `Allow conversations on public shares for files` is enabled (it is by default, but just in case)
- Open the Files app
- Create a public share of a file
- Open the link

### Expected behaviour
There is a Talk sidebar

### Actual behaviour
There is no Talk sidebar, nor a way to show it

**Comment by Antreesy** [comment]
Should be some recent changes on nextcloud/server? I remember it working earlier this week

**Comment by Antreesy** [comment]
> the Talk sidebar was shown for public shares of a single file, but not in folder shares

Smoke tested, still the case. Although it's rendered as a file list, talk-sidebar source code is not fetched for directory shares, only for single files
