### ISSUE TITLE
Maximize Shared Screen

### ISSUE THREAD

**Issue by adarmalik** [nextcloud/spreed#1341]
When sharing a screen I would like to be able to maximize the shared screen. In this case I am usually not interested in the other video feeds.

It was already mentioned in #401.

**Comment by cornzy** [comment]
I think it would be even more flexible to have the ability to open the shared screen in an extra window. This way we could easily rearrange the shared screen or have the shared screen on one display while having the video on another one.

**Comment by baruch234** [comment]
The ability to maximize the shared screen to the full desktop on the side of the recipient is essential for private webcasts, webinars, presentations and so on. Unfortunately Talk/Spreed does not allow the recipient to use the whole desktop even if the "full screen" icon is clicked. Because of that lines, fonts and so on may appear crippled and difficult to read.

**Comment by madmath03** [comment]
I have some kind of trick to bypass this : when there is a screen share, I zoom out as much as possible.
This ends up reducing the size of the other participants profiles / video feed, and the screen shared takes more place.

Maybe we could a button to hide/display completely the other participants, this would automatically let the screen sharing take the whole screen.

**Comment by nickvergessen** [comment]
I guess this will be looked into again after #1056  was done

**Comment by ruedigerkupper** [comment]
A fix for this is highly appreciated. Shared screen should ultimately be shown in full screen.

**Comment by bes1002t** [comment]
Why are the participants shown in full screen? I think if you have the full screen enabled there is no need to show the participants at the bottom because you want the image as big as possible

**Comment by nickvergessen** [comment]
In Talk 11 the video stripe at the bottom can be folded away
