### ISSUE TITLE
AI generated call summaries

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#13429]
Add ability to generate call summaries

**Comment by marcoambrosini** [comment]
Kickoff meeting happening on Monday 7

**Comment by nickvergessen** [comment]
- Single line transcripts are okay for the summary AI
- After recording automatically trigger transcript
- After transcript automatically trigger summary
- After summary is available post to chat with "*Summary is AI generated and may contain mistakes*"

**Comment by Antreesy** [comment]
Frontend: toggle in admin settings

**Comment by nickvergessen** [comment]
Overall done
