### ISSUE TITLE
AI generated unread messages summaries

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#13430]
When we have a lot of unread messages in a conversation, it would be nice to have a short summary of them.

## Expectation

A button that allows to generate summaries would appear next to the unread messages divider. Clicking it would start the action

![Image](https://github.com/user-attachments/assets/07f0e862-c226-464a-bba3-1946a17867aa)

An "info" badge would appear in the new message form, indicating that the task has started

![Image](https://github.com/user-attachments/assets/544e4f8b-1bbc-447a-b1a0-b1d162c46a5a)

And finally, when the summary is generated, it could look like this.

![Image](https://github.com/user-attachments/assets/ad7c3def-2a80-4d27-9de7-7e4af95f63fb)
 
>[!WARNING]
> The summary box **MUST** contain a disclaimer that the summary is AI generated and can contain mistakes

**Comment by marcoambrosini** [comment]
Kickoff meeting happening on Monday 7/10

**Comment by nickvergessen** [comment]
- Takes in time range of 10+ seconds to multiple minutes
- Should be "prompted" but only done once the user requests it to save energy and time on AI
- Summary state should be shown near the chat (similar to OOO note?, or in topbar?)
- Once available the summary can be read in a popup and afterwards is deleted again

**Comment by marcoambrosini** [comment]
A few mockups based on our discussion:

A button that allows to generate summaries would appear next to the unread messages divider. Clicking it would start the action
![Image](https://github.com/user-attachments/assets/07f0e862-c226-464a-bba3-1946a17867aa)

An "info" badge would appear in the new message form, indicating that the task has started
![Image](https://github.com/user-attachments/assets/544e4f8b-1bbc-447a-b1a0-b1d162c46a5a)

**Comment by nickvergessen** [comment]
Looks like a good place for the button and the summary.
Just have to keep in mind that we should generate the summary from the "button point" because the readmarker might have been updated already (we have visual vs another readmarker), so the UI needs to send the "since message" part to the API.

**Comment by nickvergessen** [comment]
>[!WARNING]
> The summary box **MUST** contain a disclaimer that the summary is AI generated and can contain mistakes

**Comment by nickvergessen** [comment]
API ready in https://github.com/nextcloud/spreed/pull/13661

**Comment by SystemKeeper** [comment]
> When we have a lot of unread messages in a conversation, it would be nice to have a short summary of them.

Do we have a threshold or conditions for when to show the summary button or not?

It feels like a waste of resources having a summary for something like:

<img src=https://github.com/user-attachments/assets/055f0d14-035f-4af1-b06f-8e4834415b8c width=800 />

**Comment by nickvergessen** [comment]
> It feels like a waste of resources having a summary for something like:

Yeah, definitely a threshhold. Not sure what we had discussed. I think 100+ floats around in my head.

**Comment by SystemKeeper** [comment]
This reminds me of https://github.com/nextcloud/talk-ios/issues/1381, so might be more tricky than I thought ..

**Comment by marcoambrosini** [comment]
Could the threshold take into account the char count too? That way it would have a more accurate representation of the actual amount of text.

**Comment by nickvergessen** [comment]
If all messages have been loaded already, yes. If we want to avoid loading 2k or more messages in the future and show it on an "empty page" not anymore.

**Comment by SystemKeeper** [comment]
> If all messages have been loaded already, technically yes, but not sure what that does to client performance

Would need to try it, if we stored the messages locally already on ios, it might work, but if we need to load all those messages first... But the unread message count is already available through the API endpoint, so that would be way easier.

**Comment by nickvergessen** [comment]
We could of course also do something like:
- Show if > 100 messages or
- if > 20 messages with more than 5.000 characters

**Comment by SystemKeeper** [comment]
Would that be checked on backend and exposed as an attributed or should we do it in clients?

**Comment by nickvergessen** [comment]
>  `config => chat => summary-threshold` (local) - Number of unread messages that should exist to show a "Generate summary" option


Added to capabilities for now

**Comment by SystemKeeper** [comment]
Some notes:

* The "Get task by id" is a "GET" instead of a "POST" as documented: https://github.com/nextcloud/documentation/pull/12371
* Status seems to be a string instead of an int as documented: https://github.com/nextcloud/documentation/pull/12371#issuecomment-2480803484
* Changing the provider might be inaccurate: https://github.com/nextcloud/server/issues/49335
* Make sure that cron is run to retrieve the results

**Comment by Antreesy** [comment]
Follow-ups:
- [ ] partially failing tasks
- [ ] store task status
- [ ] add copy to clipboard (instead of note to self)

**Comment by nickvergessen** [comment]
Overall done
