### ISSUE TITLE
Automatic locking of rooms after a certain time of inactivity

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Optional duration in app config

**Comment by alexanderdd** [comment]
should the title be "after a certain time of inactivity" (instead of "are"?

**Comment by miaulalala** [comment]
I'm only implementing this for public and group rooms, I hope that's in the spirit of this ticket. Locking 1:1 conversations doesn't make a lot of sense IMHO since I won't always interact with people 1:1 at the same frequency.

**Comment by nickvergessen** [comment]
Apparently there is a second angle to the requirement, which is that the lobby should also be enabled.
