### ISSUE TITLE
Add option for camera and mic to be disabled by default

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13446]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

- [ ] API: https://github.com/nextcloud/spreed/pull/13488
- [ ] Frontend: https://github.com/nextcloud/spreed/pull/13484

**Comment by DorraJaouad** [comment]
Along with https://github.com/nextcloud/spreed/issues/11211
