### ISSUE TITLE
Allow to import list of participants

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13451]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

E.g. CSV list of `email,displayname` to add many (at another place exported) participants easily

**Comment by Antreesy** [comment]
1) We do not currently have an API option for bulk adding of participants to reuse here (and during conversation creation).
2) Javascript should be able to generate CSV file for import/export, but if it's preferred to done on backend, also fine by me

### Frontend:
#### Design note:

Participants setup dialog from conversation creation can be reused (to be called from Right Sidebar):

![Image](https://github.com/user-attachments/assets/6e7cc600-4a08-409f-ac86-289d087beaf1)

- Import option in three-dot-menu next to the searchbar (combined with dialpad button or separately?)
- Export option in the dialog footer (or also in three-dot menu?)

**Comment by nickvergessen** [comment]
The export is most likely from another product, not from another chat/conversation in first place.
So not sure this makes sense to combine UI wise. Export needs to happen during/after a call/meeting.

**Comment by nickvergessen** [comment]
Done for now
