### ISSUE TITLE
Add option to force passwords for public conversations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13450]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Since we return the room object we can do this already, but the moderator has no way to see the password atm

**Comment by miaulalala** [comment]
- [ ] Config option to determine if server only allows password protected talk conversations
- [ ] Change "create Room" endpoint (RoomController) to have a password option
- [ ] Password policy checking on password not empty or config option set

If config option is given
- [ ] Reject room creation if global password option is set an no password is given or it doesn't match password policy
- [ ] RoomService -> setPassword as inspiration for how to store and validate a password
