### ISSUE TITLE
Force call ends after X - Follow ups

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13463]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

- [ ] Setup check to check:
     - [ ] system cron is used
     - [ ] value is big enough to cover an "up to 5 min" delay due to background jobs
- [ ] Expose via capability
     - [ ] Raise issue for frontend and mobile apps
- [ ] Use a different system message

**Comment by Antreesy** [comment]
Shall we add a visual warning, that the time is almost over, and the call could be ended automatically?

**Comment by ShGKme** [comment]
> Shall we add a visual warning, that the time is almost over, and the call could be ended automatically?

Yes, that's why we need to have the capability
