### ISSUE TITLE
Chat messages not shown for some users

### ISSUE THREAD

**Issue by hno** [nextcloud/spreed#1349]
## Steps to reproduce
1. Not exactly sure. Works for some users but not me..
2.
3.

### Expected behaviour
Chat messages should be shown

### Actual behaviour
Screen says there is no chat messages.

Error log contains:

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Linux

**Browser name:** Firefox and Chromium

**Browser version:** 63.0.3

### Browser log

<details>
Firefox: Type Error: data.ocs is undefined

Chromium:  TypeError: Cannot read property 'data' of undefined     at Internal.<anonymous> (signaling.js?v=9a9cfb01-7:382)
</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
4.0.1
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Docker nextcloud/apache. Probably Debian based?

**Web server:** Apache/Nginx

Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL

MariaDB

**PHP version:**

Not sure. Whatever is in the nextcloud docker image.

**Nextcloud Version:** (see admin page)

14.0.3

**List of activated apps:**

<details>
Enabled:
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - calendar: 1.6.4
  - circles: 0.15.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - event_update_notification: 0.3.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - lookup_server_connector: 1.2.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.1
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - telephoneprovider: 1.0.2
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - accessibility
  - encryption
  - files_external
  - files_videoplayer
  - groupfolders
  - logreader
  - mail
  - nextcloud_announcements
  - support
  - theming
  - user_ldap

</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.borderlight.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{***REMOVED SENSITIVE VALUE***}"
                ]
            },
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "***REMOVED SENSITIVE VALUE***"
                ]
            }
        ],
        "maintenance": false,
        "skeletondirectory": "",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}

</details>

### Server log (data/nextcloud.log)
<details>
{"reqId":"oWwEPwQ270qR6GmZTHON","level":3,"time":"2018-12-07T10:15:43+00:00","remoteAddr":"**REMOVED***","user":"***REMOVED***","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/chat\/jq4eoikn?lastKnownMessageId=0&lookIntoFuture=1","message":"Error: Call to a member function getPath() on boolean at \/var\/www\/html\/custom_apps\/spreed\/lib\/Chat\/SystemMessage\/Parser.php#221","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
</details>

### My analysis

The failing line is
https://github.com/nextcloud/spreed/blob/stable14/lib/Chat/SystemMessage/Parser.php#L221

My guess is that the $userNodes array is empty and reset() returns FALSE.

I tried adding a debug exception just before the line, but it does not show up in the log for some reason. The problem however got masked by adding that debug exception and chat messages is shown.

**Comment by nickvergessen** [comment]
Add `if (!$userNode instanceof Node) throws new \Exception();` there as a workaround

**Comment by nickvergessen** [comment]
Full fix is at https://github.com/nextcloud/spreed/pull/1352/files if you want to try it.

**Comment by hno** [comment]
Thanks. Will test this tomorrow.

Den mån 10 dec. 2018 12:00 skrev Joas Schilling <notifications@github.com>:

**Comment by hno** [comment]
Tested and the chat now works.
