### ISSUE TITLE
Screen sharing not working in Chrome 71

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1350]
## Steps to reproduce
1. Connect a call using Chrome version 71
2. Click on Screen sharing with the screen sharing extension installed
3. Nothing happens

### Expected behaviour
A dialog should be shown allowing selection of the screen to be shared

### Actual behaviour
Nothing happens

## Browser
Chrome 71

**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
**Operating system:** Windows/Ubuntu/...
Windows/Ubuntu
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 50.1/55/...
71
### Browser log
Nothing is logged except a warning about googLeakyBucket which is irrelevant

## Spreed app
version 3.2.4

## Server configuration
Nextcloud 13

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7

**Nextcloud Version:**13

**Comment by lazyfrosch** [comment]
Can confirm this with 2 separate NC installations.

**Comment by afeefghannam89** [comment]
The same problem

**Comment by nickvergessen** [comment]
Works fine with `Chromium Version 70.0.3538.110 (Offizieller Build) Built on Ubuntu , running on Ubuntu 18.10 (64-Bit)` so yes, seems like something was broken by 71.

Could `Remove URL.createObjectURL from MediaStream` from https://developers.google.com/web/updates/2018/10/chrome-71-deps-rems be related?

@fancycode any idea? It was also reported in the extension repository (https://github.com/nextcloud/spreed-screensharing-chrome-extension/issues/5). But I'm not sure if that extension could be the problem?

**Comment by Peterede** [comment]
It works if I change the lines in simplewebrtc.js at 3889:
`			var chromematch = window.navigator.userAgent.match(/Chrome\/(.*)\b/);
			var chromever = chromematch !== null ? parseInt(chromematch[1], 10) : "";
			var maxver = 33;
			var isCef = !window.chrome;`

**Comment by Peterede** [comment]
Also needs app.js 264:
`if (!!window.chrome) {// Chrome`

**Comment by fancycode** [comment]
Chrome dropped support for `window.chrome.webstore` in 71, so the detection was no longer working correctly. #1360 fixes this.

**Comment by nickvergessen** [comment]
Fixed with #1360 

New version 4.0.2 was released for Nextcloud 14
New version 3.2.7 was released for Nextcloud 13

**Comment by nickvergessen** [comment]
Nextcloud 15 will receive the brand new 5.0.0 later this week.

**Comment by DylanAnlezark** [comment]
> Chrome dropped support for `window.chrome.webstore` in 71, so the detection was no longer working correctly.

How/Where did you find out support had been dropped

**Comment by nickvergessen** [comment]
https://developer.chrome.com/extensions/inline_faq
