### ISSUE TITLE
Edit Messages

### ISSUE THREAD

**Issue by axelrindle** [nextcloud/spreed#13535]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)

28.0.9

**Is your feature request related to a problem? Please describe.**

I'd like to edit messages. Most common problem is me misspelling something or accidentally sending a message unfinished.

This feature is now common in most communcation platforms like MS Teams, Telegram, etc. Nextcloud Talk should have it too.

**Describe the solution you'd like**

An additional edit button allows me to edit a message.

A user can edit his own messages only.

**Describe alternatives you've considered**

**Additional context**

**Comment by Antreesy** [comment]
Feature is implemented in Nextcloud 29 - Talk 19.
Update your instance to enjoy new functionality 😉
