### ISSUE TITLE
we have't shit reaction on daily meeting, please add it.

### ISSUE THREAD

**Issue by dyoma-bat** [nextcloud/spreed#13568]
add all reaction to calls please

**Comment by dyoma-bat** [comment]
![Image](https://github.com/user-attachments/assets/a23306fa-07ef-48f5-ac09-7abde2aa81f3)

**Comment by nickvergessen** [comment]
This is currently not planned. However, we added 🔥 and 👋  for the upcoming versions.

**Comment by dyoma-bat** [comment]
💩 (

**Comment by nickvergessen** [comment]
No garantees and it will break the integrity check, but if you are so dependent on it, feel free to change the source code in https://github.com/nextcloud/spreed/blob/main/lib/Capabilities.php#L196 on your instance
