### ISSUE TITLE
Iridium browser screen-sharing cannot be started

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1359]
## Steps to reproduce
1. Install and open Iridium browser
2. Start a call and click on the screen-sharing button
3. Console logs error and button is not responsive

### Expected behaviour
Screensharing should prompt to install extension or if extension is installed show a dialog for screen sharing

### Actual behaviour
Nothing happens

## Browser
Iridium
**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu

**Browser name:** Iridium

**Browser version:** Version 2018.11 (Developer Build) Built on Ubuntu 16.04, running on Ubuntu 18.04 (64-bit)

### Browser log

<details>
simplewebrtc.js:3889 Uncaught TypeError: Cannot read property '1' of null
    at module.exports (simplewebrtc.js:3889)
    at WebRTC.LocalMedia.startScreenShare (simplewebrtc.js:7612)
    at SimpleWebRTC.shareScreen (simplewebrtc.js:18299)
    at HTMLButtonElement.<anonymous> (app.js:242)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.r.handle (jquery.min.js:3)
</details>

## Spreed app

**Spreed app version:** 3.2.4

**Comment by nickvergessen** [comment]
Fixed with #1360 

New version 4.0.2 was released for Nextcloud 14
New version 3.2.7 was released for Nextcloud 13
