### ISSUE TITLE
Do not perform synchronous Ajax requests

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1363]
When [leaving a room](https://github.com/nextcloud/spreed/blob/3a9a407fc20ddde2c22ef2a690cb6e0ee25d773f/js/signaling.js#L282) or [leaving a call](https://github.com/nextcloud/spreed/blob/3a9a407fc20ddde2c22ef2a690cb6e0ee25d773f/js/signaling.js#L332) the Ajax request is synchronous, which causes the UI to freeze while waiting for the response; those calls should be made asynchronous (but, of course, the code should be analysed before doing that to _ensure_ that there will be no regressions ;-) ).

**Comment by nickvergessen** [comment]
We will solve this while doing #1347

**Comment by nickvergessen** [comment]
Done partly now, the rest is in #2591
