### ISSUE TITLE
The shortcuts use the control (^) button on macOS instead of the command (⌘) button

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed#13654]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Click on settings in the bottom left
2. Shortcuts show that the used modifier button is control
3. I tried it and it actually uses control instead of command

### Expected behaviour
Normally shortcuts on macOS should use command as the modifier button, while control is mostly used in the terminal or to trigger very specific shortcuts.

### Actual behaviour
Shortcuts use the control button as the modifier.

## Desktop client

**Talk Desktop client version:** v0.9.0

**Operating system:** macOS

**Operating system version:** Ventura 13.4.1 (c)

**Microphone available:** yes

**Camera available:** no

## Server

**Nextcloud version:** (see status page: `/status.php`) 27.0.1

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 17.0.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`) yes

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Client log

<details>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by ShGKme** [comment]
- Was fixed by https://github.com/nextcloud-libraries/nextcloud-vue/pull/6021
