### ISSUE TITLE
Users should not join the room for a file just by opening the Chat tab in the Files app

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1366]
In The Files app, when the user opens the _Chat_ tab for a shared file the user immediately joins the room for that file.

This can lead to users joining a room by accident, not only by explicitly clicking on the _Chat_ tab, but also by just changing to a different file, as the details view tries to open again the same tab that was open for the previous file (and I guarantee you that this can happen :-P ).

This is not only an annoyance for the user that entered the room by mistake (as she would need to explicitly leave the room from the Talk UI), but also for other users in the room, as the chat would be _polluted_ by system messages about users joining and leaving.

Due to this, a user should not join a room just by opening the _Chat_ tab for a shared file.

What should be done, then?:
- When the user opens the _Chat_ tab for a shared file the chat is loaded, but the user does not join the room until she explicitly writes something or joins a call.
- When the user opens the _Chat_ tab for a shared file if she has not joined the room yet a button to join will be shown (similar to the UI shown when the file is not shared: an icon, a message and a _Join_ button); if the user has already joined the room then the chat is loaded.
- Something else

The first approach may require quite some changes in both the frontend and the backend; the second one should be easy, and would prevent the chat in the room from being "stalked", but has the drawback of requiring an extra click in this age of streamlined UIs :-P Despite that, I would go for the second approach ;-) Opinions?

@nextcloud/designers

**Comment by nickvergessen** [comment]
I don't see this happening anymore with the new Talk
