### ISSUE TITLE
Syntax Highlighting for Code-Boxes

### ISSUE THREAD

**Issue by emendir** [nextcloud/spreed#13687]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
Nextcloud 29.0.8

**Is your feature request related to a problem? Please describe.**
Code-Boxes are rendered in a plain uncoloured monospace font:

![Image](https://github.com/user-attachments/assets/260a6256-9d51-45b0-8759-e72adb9b23cd)
 

**Describe the solution you'd like**
Render the code-boxes with syntax highlighting according the the language specified in the markdown code-fence header, for example:
![Image](https://github.com/user-attachments/assets/2b47d594-f2dd-4af5-8e04-8d2a2ad5c9b7)

**Describe alternatives you've considered**

**Additional context**
This feature request was made 6 years ago but ignored because it was misinterpreted as a duplicate of a different issue.
That old issue was closed: https://github.com/nextcloud/spreed/issues/1187

**Comment by Antreesy** [comment]
Hi, thanks for opening the issue!

> 6 years ago but ignored

Basic Markdown support was missing back then, so it should have been solved first

> Render the code-boxes with syntax highlighting

One of these libraries would work, need to upstream to `nextcloud-vue`:
https://github.com/rehypejs/rehype-highlight
https://github.com/rehypejs/rehype-starry-night
![Image](https://github.com/user-attachments/assets/6cb4c314-b8c1-4de0-b8f6-5e34faa81993)

Should be checked for MacOS, as there were some issues with losing the language identifier

**Comment by jclsn** [comment]
I just requested the same feature on the forum https://help.nextcloud.com/t/feature-request-syntax-highlighting-for-talk-code-snippets/209604
