### ISSUE TITLE
Calls created via »New shared call« can’t be unshared

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#137]
They still have the »Delete« icon there, but it does nothing. How should we fix this?

- Make it work. Maybe the simplest solution. Then of course people can’t follow the link anymore, but hey you deleted it.
- Remove the delete button because it doesn’t do anything. Might be confusing though.
- Anything else?

cc @nickvergessen @Ivansss @LukasReschke @MorrisJobke

**Comment by jancborchardt** [comment]
Actually, the delete button next to the »Share link« doesn’t work at all. :O cc @Ivansss 
(Firefox)

**Comment by nickvergessen** [comment]
I guess this only happens until the page is reloaded?

**Comment by nickvergessen** [comment]
Works here on Chrome, but not on FF
