### ISSUE TITLE
Automatically ended calls with no participants shows incorrect system message

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#13734]
To reproduce:
- Start a call
- Reload page to leave it quietly
- Server sees the number of participants as 0, ends call and posts a falsy message (call duration)
![image](https://github.com/user-attachments/assets/cee76ad0-3c83-4931-b227-84da098b0611)

_Originally posted by @Antreesy in https://github.com/nextcloud/spreed/issues/13491#issuecomment-2464230648_

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/14030
