### ISSUE TITLE
Custom profile picture is not loaded

### ISSUE THREAD

**Issue by valentinthedon** [nextcloud/spreed#13766]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go in Talk App
2. Go on a discussion (no profile picture)
3. Go on the profile via the profile picture circle
4. Go back to the Talk app
5. The custom profile picture is loaded
6. Go on another app 
7. Go back to app
8. The custom profile picture is unloaded

### Expected behaviour
The custom profile picture is loaded and display on the discussion al times

### Actual behaviour
The profil picture is loaded only when you go into the profile of the user

## Talk app

**Talk app version:** 20.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS Sonoma

**Browser name:** Arc (Chromium based)

**Browser version:** 1.67.2 (Chromium Version : 130.0.6723.117)

### Browser log

no log

## Server configuration

**Operating system**: Debian Bookworm

**Web server:** Nginx

**Database:**PostgreSQL

**PHP version:** 8.2

**Nextcloud Version:** 30.0.2

**List of activated apps:**

<details>

- activity: 3.0.0
- admin_audit: 1.20.0
- app_api: 4.0.0
- bruteforcesettings: 3.0.0
- calendar: 5.0.1
- circles: 30.0.0
- cloud_federation_api: 1.13.0
- comments: 1.20.1
- contacts: 6.1.1
- contactsinteraction: 1.11.0
- dashboard: 7.10.0
- dav: 1.31.1
- deck: 1.14.2
- drawio: 3.0.3
- external: 5.5.2
- federatedfilesharing: 1.20.0
- files: 2.2.0
- files_downloadlimit: 3.0.0
- files_pdfviewer: 3.0.0
- files_reminders: 1.3.0
- files_sharing: 1.22.0
- files_trashbin: 1.20.1
- files_versions: 1.23.0
- logreader: 3.0.0
- lookup_server_connector: 1.18.0
- mail: 4.0.2
- notifications: 3.0.0
- oauth2: 1.18.1
- password_policy: 2.0.0
- privacy: 2.0.0
- provisioning_api: 1.20.0
- recommendations: 3.0.0
- related_resources: 1.5.0
- serverinfo: 2.0.0
- settings: 1.13.0
- sharebymail: 1.20.0
- spreed: 20.0.2
- support: 2.0.0
- systemtags: 1.20.0
- theming: 2.5.0
- twofactor_backupcodes: 1.19.0
- updatenotification: 1.20.0
- user_status: 1.10.0
- viewer: 3.0.0
- weather_status: 1.10.0
- webhook_listeners: 1.1.0-dev
- workflowengine: 2.12.0
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.inspemon.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "templatedirectory": "",
        "version": "30.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.inspemon.com",
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 1,
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "default_timezone": "Europe\/Paris",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "user": "default",
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0,
            "timeout": 1.5,
            "read_timeout": 1.5
        },
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app.mail.attachment-size-limit": 10485760,
        "app.mail.background-sync-interval": 300,
        "forbidden_filename_characters": [
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            ".filepart",
            ".part"
        ],
        "defaultapp": ""
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
No log
</details>

**Comment by Antreesy** [comment]
Hi @valentinthedon !

Could you provide a screen recording with reproduction? I'm afraid I didn't understand some of your steps
