### ISSUE TITLE
Notification "*" is added even though nothing happened

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#13799]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
https://github.com/user-attachments/assets/e1451e25-ac5f-4704-9338-872dc37d52fd

### Actual behaviour
A star is added to the conversation title of an inactive tab, even though nothing happened. I checked the notify_push websocket as well, no message was received when it happens.

**Comment by SystemKeeper** [comment]
Hm, fixed by https://github.com/nextcloud/spreed/pull/13797 already ? 🧐

**Comment by Antreesy** [comment]
> Hm, fixed by https://github.com/nextcloud/spreed/pull/13797 already ? 🧐

Yup, sorry for missing that. Wasn't the case before the change, although compare code is the same
