### ISSUE TITLE
When creating a room via »New shared call«, directly copy the link to clipboard

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#138]
If the browser APIs are available, we should directly copy the link to the clipboard and provide feedback via tooltip on the entry. That will massively ease the flow.

**Comment by nickvergessen** [comment]
Not possible because of browser security:
https://stackoverflow.com/questions/43235239/copy-text-to-clipboard-using-clipboard-js-without-button

I think we could add a system message to the chat instead which has a button.

**Comment by nickvergessen** [comment]
Closing as per above
