### ISSUE TITLE
Multiple mentions in a single message broken

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#1380]
Trying to mention multiple users in a single message is currently broken.
Only the first user gets mentioned.

Typing the message:

![screen shot 2018-12-12 at 17 17 36](https://user-images.githubusercontent.com/4638605/49882924-e6924b80-fe31-11e8-8d00-9460533fafb1.png)

Sent message:

![screen shot 2018-12-12 at 17 17 48](https://user-images.githubusercontent.com/4638605/49882950-f1e57700-fe31-11e8-9417-e4c34b9c9104.png)

**Comment by nickvergessen** [comment]
Sometimes it works, sometimes not. If you type it manually it works all the time. Some weird magic is going on

**Comment by nickvergessen** [comment]
@jancborchardt you reported this too somewhere but I dont find it anymore.
Anyway it's fixed now.
