### ISSUE TITLE
User Frequently Removed and Automatically Re-added to Group Chat

### ISSUE THREAD

**Issue by fajarbs08** [nextcloud/spreed#13816]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
![Image](https://github.com/user-attachments/assets/fcd70d46-5939-44cf-a64d-43eb7a24f5ff)

## Steps to reproduce
1.Add a user to a group conversation.
2.Observe the user being removed and re-added repeatedly without manual intervention.
3.Check the user management settings, especially LDAP integration with Zimbra mail server.
4.Review the activity logs for automated re-addition and removal.

### Expected behaviour
The user should remain in the group conversation without being removed or re-added automatically.

### Actual behaviour
The user is automatically removed from the group and re-added multiple times within a short timeframe. This disrupts the conversation flow and creates unnecessary log entries.

### Additional Context
1. User Synchronization: All Nextcloud users are synchronized using LDAP integration with a Zimbra mail server.
2. Potential Issue: LDAP syncing might be causing user status instability, leading to automatic removal and re-addition.

## Talk app

**Talk app version:** 20.0.1 (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** no  and version (see  Talk administration settings: `/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Chrome/Firefox//Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Web server:** 
Server version: Apache/2.4.52 (Ubuntu)
Server built:   2024-07-17T18:57:26

**Database:** MySQL 8.0.40-0ubuntu0.22.04.1

**PHP version:** PHP 8.3.11 (cli) (built: Aug 30 2024 09:27:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.11, Copyright (c), by Zend Technologies

**Nextcloud Version:** (see administration page)
Nextcloud Hub 9 (30.0.0)

**List of activated apps:**
<details>

Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - call_summary_bot: 2.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - drawio: 3.0.3
  - external: 5.5.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - forms: 4.3.1
  - google_synchronization: 3.0.0
  - impersonate: 1.17.0
  - integration_google: 3.1.0
  - integration_zimbra: 1.0.10
  - integration_zulip: 1.0.4
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - ocs_api_viewer: 1.0.7
  - ownershiptransfer: 1.0.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - socialsharing_email: 3.2.0
  - socialsharing_facebook: 3.2.0
  - spreed: 20.0.1
  - support: 2.0.0
  - systemtags: 1.20.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - whiteboard: 1.0.4
  - workflow_script: 1.15.0
  - workflowengine: 2.12.0
Disabled:
  - audioplayer: 3.4.1 (installed 3.4.1)
  - encryption: 2.18.0
  - extract: 1.3.6 (installed 1.3.6)
  - files_external: 1.22.0 (installed 1.22.0)
  - integration_openstreetmap: 2.0.1 (installed 2.0.1)
  - survey_client: 2.0.0 (installed 2.0.0)
  - suspicious_login: 8.0.0
  - text: 4.1.0 (installed 3.10.1)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - webhook_listeners: 1.1.0-dev (installed 1.1.0-dev)

</details>

**Nextcloud configuration:**
<details>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.cde-coal.com",
            "localhost",
            "chat.cde-coal.com",
            "103.196.146.210"
        ],
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "hnrdata01",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "nos.wjv-1.neo.id",
                "port": 443,
                "use_ssl": true,
                "region": "optional",
                "use_path_style": true
            }
        },
        "bulkupload.enabled": false,
        "tempdirectory": "\/tmp",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "https:\/\/nextcloud.cde-coal.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": "01:00",
        "default_phone_region": "ID",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "defaultapp": "",
        "maintenance": false,
        "app_install_overwrite": [
            "extract",
            "zimbradrive"
        ],
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "jpeg_quality": 60
    }
}

</details>

### Server log (data/nextcloud.log)
[nextcloud_latest.log](https://github.com/user-attachments/files/17826316/nextcloud_latest.log)

**Comment by ekozer03** [comment]
How to solution?

**Comment by miaulalala** [comment]
Are you able to run occ commands? Can you please run `occ ldap:show-remnants`?

**Comment by fajarbs08** [comment]
> Are you able to run occ commands? Can you please run `occ ldap:show-remnants`?

yes
![Image](https://github.com/user-attachments/assets/7ee0e579-7bb1-48eb-97a0-011a97d376cb)

**Comment by nickvergessen** [comment]
This is definitely not an issue in Talk.
Most likely the user is being added and removed again from a Nextcloud user group that has been added to the conversation.

**Comment by fajarbs08** [comment]
> Ini jelas bukan masalah di Talk. Kemungkinan besar pengguna tersebut ditambahkan dan dihapus lagi dari grup pengguna Nextcloud yang telah ditambahkan ke percakapan.



> This is definitely not an issue in Talk. Most likely the user is being added and removed again from a Nextcloud user group that has been added to the conversation.

Ah, of course. Because everyone surely has plenty of free time to manually add and remove users repeatedly, just to make things more interesting. Unfortunately, I’m not one of those people. However, if you have another more reasonable theory instead of blaming user behavior, I’d be happy to hear it.

**Comment by Antreesy** [comment]
Since you have mentioned LDAP integration, that might be the case, that user's group assignments are frequently updated with LDAP sync - user is added/removed from group automatically. Again, not on the Talk side, app is just reflecting what server does

**Comment by fajarbs08** [comment]
> Karena Anda telah menyebutkan integrasi LDAP, mungkin itu masalahnya, penugasan grup pengguna sering diperbarui dengan sinkronisasi LDAP - pengguna ditambahkan/dihapus dari grup secara otomatis. Sekali lagi, tidak di sisi Talk, aplikasi hanya mencerminkan apa yang dilakukan server

Yes, I also suspect LDAP, but I haven't been able to pinpoint the issue since it only affects a small number of users. I was hoping to find a solution here because I'm currently stuck.
