### ISSUE TITLE
Discord Matterbridge Use Channel ID Instead of Channel Name

### ISSUE THREAD

**Issue by Fibbicles** [nextcloud/spreed#13877]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** Hub 9 (30.0.2)

**Is your feature request related to a problem? Please describe.**
Essentially we can only identify Discord channels by name, this leads to many problems for users of most Discord servers where unicode symbols and emojis are used within the text names. Also mentioned here: https://github.com/nextcloud/talk_matterbridge/issues/71

**Describe the solution you'd like**
We can specify the Server ID as an integer like `1187942610669686868` and should be able to do the same with channel ids rather than specifying the name.

**Describe alternatives you've considered**
None because there's no alternatives.

**Additional context**
This has been a problem for almost 2-3 years now since it was reported and seems like a very quick and simple fix.

**Comment by nickvergessen** [comment]
Specifying `ID:1234567890` should work
https://github.com/42wim/matterbridge/wiki/How-to-create-your-config#step-5

**Comment by Antreesy** [comment]
Tested and onfirmed with using `general` or `ID:12345`
