### ISSUE TITLE
Add admin setting for AI generated call recording summary

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13906]
> Frontend: toggle in admin settings 

 _Originally posted by @Antreesy in [#13429](https://github.com/nextcloud/spreed/issues/13429#issuecomment-2488438112)_

**Comment by SystemKeeper** [comment]
When we add a switch for that, we should also add the transcription switch, as summary depend on transcription ?

**Comment by nickvergessen** [comment]
When transcription is off and summary on, the transcription is still created, just never saved into the users files. But yeah we could still add it.
