### ISSUE TITLE
Differences in the style of tab headers between Talk and server

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1390]
@nextcloud/designers and, specially, @jancborchardt , as you made the style of tab headers [in Talk](https://github.com/nextcloud/spreed/pull/568) and [in the server](https://github.com/nextcloud/server/pull/12180).

There are some differences (besides [the position of the icon](https://github.com/nextcloud/spreed/pull/1389)) in those styles:
- Padding (larger in Talk, [12px](https://github.com/nextcloud/spreed/blob/020202c8c57a8ffe2f9fb9f66bb64e54e4a65dec/css/style.scss#L547) instead of [5px](https://github.com/nextcloud/server/blob/ac7c7782ff0681e6f192e4f0b9858af753cb7234/core/css/apps.scss#L792))
- Underline of inactive tab (shown in Talk, and explicitly mentioned as a fix [in the pull request for Talk](https://github.com/nextcloud/spreed/pull/568), while not shown in server)
- Opacity of inactive tab (in Talk is lower than the active tab, in server is the same)
- Highlight of hovered tab (in Talk the whole tab header is highlighted, in the server only the underline is highlighted)

I think that [all this should be unified](https://github.com/nextcloud/spreed/blob/020202c8c57a8ffe2f9fb9f66bb64e54e4a65dec/css/style.scss#L536) but, how? Personally I prefer the style of Talk regarding inactive and hovered tabs, and I have no preference regarding the padding.

**Comment by nickvergessen** [comment]
We are using the sidebar component now, so closing
