### ISSUE TITLE
Separate file-related chats from the rest, in the chats list

### ISSUE THREAD

**Issue by eldelacajita** [nextcloud/spreed#13947]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 
Nextcloud Hub 9 (30.0.1)

**Is your feature request related to a problem? Please describe.**
Once you start creating chats related to files/documents/folders, the chat list in the Talk app becomes very crowded and it's hard to find the topic-related chats or channels I have set up with other people. I would like to be able to "weed out" those file-related chats.

**Describe the solution you'd like**
The sidebar could have two sections, one for "regular" chats and another one for "file-related" ones. Those sections could be collapsible.

**Describe alternatives you've considered**
A possible (maybe better?) alternative would be to use filters. In the same way we have filters for only showing unread chats and @ mentions, a new filter could be used to filter out document-related chats.

![Image](https://github.com/user-attachments/assets/839c771c-4736-460d-a07a-e8c033ec00a6)

**Comment by nickvergessen** [comment]
- I think this can go with https://github.com/nextcloud/spreed/issues/2448 It's one of the things that has to be grouped in some way. Same with calendar/event conversations
