### ISSUE TITLE
Allow Users to authenticate if room has guests allowed/enabled

### ISSUE THREAD

**Issue by LexioJ** [nextcloud/spreed#13968]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 29.0.8

**Is your feature request related to a problem? Please describe.**
When joining a meeting where guests are allowed but without establishing a session in the browser beforehand, users with accounts are joined as guests.

**Describe the solution you'd like**
Add an option to logon and join instead of using a guest account for "full-access"-users
![Image](https://github.com/user-attachments/assets/cbd3eafe-fa93-4bf5-80d5-596ef22ee14d)

**Describe alternatives you've considered**
none

**Additional context**

**Comment by Antreesy** [comment]
Added in Nextcloud 30.0.0 / Talk 20.0.0

![Image](https://github.com/user-attachments/assets/dff36daa-00db-460a-80c6-d5a0f9ca0338)
