### ISSUE TITLE
Can’t change conversation image since version 20.1.0

### ISSUE THREAD

**Issue by Framasoft-org** [nextcloud/spreed#13986]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a conversation
2. In conversation creation modale, there is no way to change the image
3. Once conversation created, there is no way to change the image (no pencil, nothing indicating that you can edit the image) 

### Expected behaviour
I should be able to choose and change the conversation image.

### Actual behaviour
I’m not able to choose and change the conversation image.

## Talk app

**Talk app version:** 20.1.0

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Browser name:** Firefox, also tested with Chromium

**Browser version:** FF 135, Chromium 131

**Comment by SystemKeeper** [comment]
Thanks for your report, I just tested it and can’t confirm your observation, below the image are buttons to change to an emoji, upload a picture or select a picture. Same for a new conversation dialog. Can you please post a screenshot?

**Comment by Antreesy** [comment]
From frontend side, controls should be in place:
- when creating a new conversation: all the time;
- when configuring existing conversation: when you're owner or moderator;
<img width="271" alt="Image" src="https://github.com/user-attachments/assets/2e60c0c2-c977-43ff-8015-21cb66a74975" />

**Comment by SergioArbarviro** [comment]
Hello to all,

I confirm that when I open the "Settings" of a conversation I am the owner of, I can change everything, except the image. See attached screenshot.
![Image](https://github.com/user-attachments/assets/af06763e-06f6-4df7-a9b7-29e9157bcc41)

**Comment by ldidry** [comment]
NB : account mixup has been made when I opened the issue with the @Framasoft-org account.

I wanted to open the issue with the present account @ldidry (for @SergioArbarviro, who noticed the problem).

**Comment by Antreesy** [comment]
Buttons have the same conditions to be shown as 'The file must be a PNG or JPG' hint. Could you check browser console for any errors logged? I assume somehow the render of components failed in this place

**Comment by ldidry** [comment]
Find the culprit: a custom CSS rule added with theming app 😓 

Sorry for the noise 🙇
