### ISSUE TITLE
Filter for unread messages doesn't show rooms with a ongoing call

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#13995]
Actually I'm not sure if this is a bug or a desired behavior, that's why I want to put it up for discussion.

Most of the time I have set the filter on the left sidebar to only show rooms with unread messages. This helps me to stay focused on the important parts.

If someone calls me I get a call notification but the room doesn't show up on the left sidebar. You could argue that this is the expected behavior because a call is not a unread message. On the other hand is a call similar important as a new chat message and technically speaking there is a new message: "a call was started".

From my personal use case and how I use the filter I would say that rooms in which a call was started should be threaten the same as rooms with unread messages. But I could also understand the other way around... What do you think?

**Comment by Antreesy** [comment]
It's actually an exception for conservations with ongoing call. It might have been changed recently with archiving feature, but in general should work:

https://github.com/nextcloud/spreed/blob/main/src%2Fcomponents%2FLeftSidebar%2FLeftSidebar.vue#L554-L562

https://github.com/nextcloud/spreed/blob/main/src%2Futils%2Fconversation.js#L39-L41

**Comment by nickvergessen** [comment]
The second link could explain the issue. Conversations are not listed if you disabled the call notification for them.

**Comment by Antreesy** [comment]
> Conversations are not listed if you disabled the call notification for them.

Yes, that was changed with 20.1.0. But wouldn't it be the expected result?

`IF` I don't want to receive notifications about calls in this conversation
`THEN` I'm likely not interested in participating in these calls
`AND THEN` I also don't want to see it popping out in filtered list

**Comment by nickvergessen** [comment]
While I mostly agree, I can see how e.g. a "Coffee call" could be the counter proposal.
When you got the time and see the call, you might join, but you don't want all the clients and mobile apps to scream at you each week.

**Comment by schiessle** [comment]
> While I mostly agree, I can see how e.g. a "Coffee call" could be the counter proposal.
> When you got the time and see the call, you might join, but you don't want all the clients and mobile apps to scream at you each week.

I don't think it is a real counter argument. The "Coffee call" screams on me already all the time with any chat message by showing up in the filtered list "unread messages", counting the started call additionally as a unread message can be ignored in this regard because it happens way more seldom than random chat messages.

Actually this is another mostly unrelated problem that actually a lot of rooms which I have set to "no notifications" or "only notify on mention" scream on me all the time with the "unread message" filter. 

Maybe we should combine it with the notification settings of each room:

- notification setting "no notification at all": no pop up in the "unread message"-filter at any time
- notification setting "notify on all messages": pop up in the "unread messages" filter whenever a new message was posted, including a call was started
- notification setting "notify only on mention": pop in the "unread message"-filter only when I was mentioned, the room was mentioned or a non-silent call was started (which I would count as a room mention)


Would this make sense?

**Comment by nickvergessen** [comment]
> Actually this is another mostly unrelated problem that actually a lot of rooms which I have set to "no notifications" or "only notify on mention" scream on me all the time with the "unread message" filter.

Talk 20.1 has you covered:
![Image](https://github.com/user-attachments/assets/84fadb53-3b46-4b8a-b896-d03cf41840fd)

When mentioned | With > 1k unread messages in more than 20 chats
---|---
![Image](https://github.com/user-attachments/assets/e7e07c6a-1d55-4365-9cee-df39363b5b45) | ![Image](https://github.com/user-attachments/assets/c1306ce3-0b14-4b3b-b6a9-a955eb30eeb9)
