### ISSUE TITLE
Compatibility with Nextcloud 10

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#140]
We talked about it in Stuttgart – would be cool to have compatibility with Nextcloud 10, so more people can try it out and don’t need to upgrade.

@nickvergessen did you say the only problem is something with the notifications? Or is this more complex? cc @LukasReschke @Ivansss @MorrisJobke

**Comment by LukasReschke** [comment]
Let's not waste time on such stuff while we have way bigger work to do. Either upgrade or well, don'4 have the feature. Also we will not put that in the oC appstore for sure... (new one is 11 only)

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/129

**Comment by jancborchardt** [comment]
Ok, makes sense.
