### ISSUE TITLE
Login always needed when you enter a room via bookmark

### ISSUE THREAD

**Issue by Speed7811** [nextcloud/spreed#14045]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Login via URL on your nextcloud instance e.g. https://cloud.mycompany.com
2. Save a URL as a bookmark of a room/call e.g. https://cloud.mycompany.com/index.php/call/znq3okmr 
3. Close the browser completely (all tabs etc.)
4. Open the browser and the the url of your login instance e.g. https://cloud.mycompany.com => Now your are logged in => That's ok!
5. Close the browser completely (all tabs etc.)
6. Open the browser  and click on the bookmark (yes it sounds crazy but it must be a bookmark - paste the URl will work) - repeat this speed 3 or 4 times if necessary

### Expected behaviour
The room/call should be opened and the user is still logged in without any dialog

### Actual behaviour
- A dialog occurs: Please enter your name (in NC 29 and NC 30).

### Additional info
- Info 1: If you now close the browser after the login dialog occurs and open it again and enter your url https://cloud.mycompany.com you always need to login
- Info 2: We just updated last week from 28 one instance to 29 and another instance to 30 (Latest patch level). In 28 and before it works many years without any problem.
- Info 3: This doesn't happens if you first login, let the browser open and then click on the bookmark

- Info 4: I can share a video if necessary.

## Talk app

**Talk app version:** 20.1.1 (in NC 30)

**Custom Signaling server configured:** yes => 0a04ea290969cfe1ebc3ef3aaeeae1bdc49ea552

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Opera

**Browser version:** Opera: 115.0.5322.119 / Chrome: 131.0.6778.205

### Browser log

<details>
```
I will post it if this is really necessary. Please give me an info if you need it
```

</details>

## Server configuration

**Operating system**: Ubuntu 24.04.1 

**Web server:** Apache 2.4.58

**Database:** Maria 10.11.8

**PHP version:** 8.3.6

**Nextcloud Version:** 30.0.4

**List of activated apps:**

<details>

```
Enabled:
  - activity: 3.0.0
  - app_api: 4.0.3
  - bruteforcesettings: 3.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - firstrunwizard: 3.0.0
  - keeweb: 0.6.20
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.1.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.7.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.1.1
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - unsplash: 3.0.3
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - dashboard: 7.10.0 (installed 7.0.0)
  - encryption: 2.18.0
  - files_versions: 1.23.0 (installed 1.20.0)
  - recommendations: 3.0.0 (installed 1.2.0)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0 (installed 1.8.1)
  - weather_status: 1.10.0 (installed 1.0.0)
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mycompany.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.mycompany.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "default_language": "de",
        "default_phone_region": "DE",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "preview_max_x": "1024",
        "preview_max_y": "1024",
        "preview_max_scale_factor": "1",
        "jpeg_quality": "60",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "maintenance": false,
        "theme": "",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "app_install_overwrite": [
            "previewgenerator",
            "files_rightclick",
            "unsplash"
        ],
        "updater.release.channel": "stable",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "maintenance_window_start": 1
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>

```
I will post it if this is really necessary. Please give me an info if you need it.
```
</details>

**Comment by Antreesy** [comment]
Hi, thanks for the report!
Could you clarify if:
- that happens on another pages (not only Talk, but Files or another app)? 
- which browser are you using?
- just to be sure, it's not incognito mode?

I'm asking because it sounds like a server-side issue with browser sessions, which are mostly reproducible on Chrome

**Comment by Speed7811** [comment]
Hey @Antreesy,

I just changed the description - please see again: It must be a bookmark (wired). 

1. I will test it with other pages within the next hours
2. Browser is Chrome and Opera (latest version).
3. Yes, I'm sure it's not incognito mode

**Comment by Speed7811** [comment]
Hey,

i just tested it e.g. with files and it is the same behavior to. Whenever I open a NC url via Bookmark I need to login. Therefore it looks like it is not a spreed thing. Where is the best location to report it? https://github.com/nextcloud/server?

**Comment by Speed7811** [comment]
I created a new issue on the server side (See here: https://github.com/nextcloud/server/issues/49968). I think with issue can be closed because it is not Spreed related.

**Comment by Antreesy** [comment]
We could have just transfer it to the server repository, but that way is also fine. Thanks for double checking!
