### ISSUE TITLE
Doesn’t work in certain scenarios without TURN server

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#141]
Just tried it out on my simple PHP+MySQL server, a 1on1 shared call. Each one of us only saw a black rectangle of the other person instead of video, and no audio.

@LukasReschke said this is most likely because of a missing TURN server (correct, as I don’t have that) and maybe cable internet (also correct, as I have that here – my call partner has normal Telefondosen-Internet).
We should make that really clear inside of the app (as an emptycontent message if it’s possible to detect cc @Ivansss @fancycode) as well as in the readme, and in any release notes, not that people think this just works.

cc @jospoortvliet @karlitschek

**Comment by fancycode** [comment]
There will always be scenarios that require a TURN server. You should probably add some more error handling / timeout detection in the `iceConnectionStateChange` handler in https://github.com/nextcloud/spreed/blob/a2e2db0af7ee034f5f37ee38f26dafa2bcaafb1d/js/webrtc.js#L351

In your case, you should have seen the `checking` and then after some time the `failed` (or `closed`) event, without any `connected`/`completed` in between. If no TURN server is configured, you can then show the user that a TURN server might help. If TURN is configured and it didn't work, you can show a generic error message that the connection could not be established.

**Comment by LukasReschke** [comment]
Agreed with @fancycode.

**Comment by jancborchardt** [comment]
Ok, that sounds like a good improvement. We should have that in the release to give proper feedback to users.

**Comment by nickvergessen** [comment]
We have a TURN by default now, anything to do here? Or can we close this?

**Comment by jancborchardt** [comment]
@nickvergessen we have STUN by default, not TURN. We still need to give feedback and a proper error emptycontent.

**Comment by wscheicher** [comment]
Well, if a TURN server is required in some situations, it is kinda is necessary to install one.
I for myself have no experience when it comes to TURN servers and am quite clueless what to do now.
And i bet i'm not the only one.
So i think it would be a good idea to have some install hints for Admins enabling this app about how to install a TURN server, which different choices there are, which TURN server fits the situation best, etc ...

**Comment by jancborchardt** [comment]
@fancycode @nickvergessen @LukasReschke please advise. Can we have some help in the Admin settings?

**Comment by nickvergessen** [comment]
I have no idea about turn either

**Comment by jancborchardt** [comment]
@fancycode @Ivansss who has the clue here? :)

**Comment by nickvergessen** [comment]
@Ivansss something to add on the reconnection stuff?

**Comment by Pazu** [comment]
Would TURN-TLS help ( #257)?

**Comment by nickvergessen** [comment]
We will deal with this in #655
