### ISSUE TITLE
Empty space on the left of the content

### ISSUE THREAD

**Issue by lachmanfrantisek** [nextcloud/spreed#1411]
### Steps to reproduce
Open the talk app in some browser (firefox/chromium/epiphany).

### Expected behaviour
Show the content in the full width.

### Actual behaviour
There is a space between the left border (or menu) and the content.

![snimek z 2018-12-14 22-33-38](https://user-images.githubusercontent.com/20214043/50029557-5ef43a80-fff3-11e8-9648-794bfcc416d2.png)
![snimek z 2018-12-14 22-33-08](https://user-images.githubusercontent.com/20214043/50029556-5ef43a80-fff3-11e8-9a4e-a541a5b0ff9c.png)
![snimek z 2018-12-14 22-32-24](https://user-images.githubusercontent.com/20214043/50029559-5f8cd100-fff3-11e8-96d6-6d50b399dec5.png)

- What I have tried:
    - different browsers - firefox (desktop + android), chromium, epiphany
    - reinstalling app
    - restarting the nextcloud
    - turn off the dark mode
    - different user
- I am running same containerized setup in other two instances without problems. (This is the main one, with higher usage.)
- The problem is older than the major release.

## Server configuration detail

**Operating system:** Linux 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64

**Webserver:** nginx/1.15.6 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit

**PHP version:** 

7.2.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, gd, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, Phar, exif, ftp, gmp, imap, intl, ldap, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, zip, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** [wonderfall/nextcloud](https://hub.docker.com/r/wonderfall/nextcloud/) -> [hoellen/nextcloud](https://hub.docker.com/r/hoellen/nextcloud/) docker images from version 10

**Where did you install Nextcloud from:** [hoellen/nextcloud](https://hub.docker.com/r/hoellen/nextcloud/) docker image

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.3.1
 - apporder: 0.6.0
 - audioplayer: 2.4.1
 - bookmarks: 0.14.3
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.4
 - camerarawpreviews: 0.6.3
 - checksum: 0.4.1
 - circles: 0.15.2
 - cloud_federation_api: 0.0.1
 - cms_pico: 0.9.7
 - comments: 1.4.0
 - contacts: 2.1.8
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.5.1
 - drawio: 0.9.1
 - dropit: 0.1.3
 - end_to_end_encryption: 1.0.5
 - event_update_notification: 0.3.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_downloadactivity: 1.3.0
 - files_external: 1.5.0
 - files_linkeditor: 1.0.8
 - files_markdown: 2.0.5
 - files_mindmap: 0.0.11
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - gpxedit: 0.0.10
 - gpxmotion: 0.0.8
 - gpxpod: 3.0.0
 - groupfolders: 2.0.1
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - keeporsweep: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - metadata: 0.8.0
 - mindmaps: 0.1.0
 - mood: 0.4.0
 - music: 0.9.3
 - news: 13.0.3
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ocsms: 2.0.2
 - ownbackup: 18.11.0
 - password_policy: 1.4.0
 - passwords: 2018.12.0
 - polls: 0.8.3
 - provisioning_api: 1.4.0
 - qownnotesapi: 18.11.0
 - quicknotes: 0.1.5
 - quota_warning: 1.3.0
 - radio: 0.6.4
 - ransomware_detection: 0.4.2
 - ransomware_protection: 1.2.0
 - registration: 0.4.5
 - richdocuments: 3.0.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.3.0
 - sociallogin: 1.11.2
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 4.0.2
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - telephoneprovider: 1.0.2
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_nextcloud_notification: 0.2.4
 - twofactor_totp: 1.5.0
 - twofactor_u2f: 1.6.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - encryption
 - mail
 - ocdownloader
 - support
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "apps_paths": [
        {
            "path": "\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/apps2",
            "url": "\/apps2",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Prague",
    "logdateformat": "Y-m-d H:i:s",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "appstore.experimental.enabled": true,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0

**Operating system:** Fedora Workstation 29 + GNOME 3.30.2

## Logs

<details><summary>Browser log</summary>

```
[Violation] Forced reflow while executing JavaScript took <N>ms
core.js?v=dba47f93-1:7 JQMIGRATE: Migrate is installed, version 1.4.0
VM431:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=dba47f93-1:3877)
    at Object.register (merged-template-prepend.js?v=dba47f93-1:3829)
    at en.js?v=dba47f93-1:1
_generatePluralFunction @ merged-template-prepend.js?v=dba47f93-1:3877
register @ merged-template-prepend.js?v=dba47f93-1:3829
(anonymous) @ en.js?v=dba47f93-1:1
VM434:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=dba47f93-1:3877)
    at Object.register (merged-template-prepend.js?v=dba47f93-1:3829)
    at en.js?v=dba47f93-1:1
_generatePluralFunction @ merged-template-prepend.js?v=dba47f93-1:3877
register @ merged-template-prepend.js?v=dba47f93-1:3829
(anonymous) @ en.js?v=dba47f93-1:1
VM437:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=dba47f93-1:3877)
    at Object.register (merged-template-prepend.js?v=dba47f93-1:3829)
    at en.js?v=dba47f93-1:1
_generatePluralFunction @ merged-template-prepend.js?v=dba47f93-1:3877
register @ merged-template-prepend.js?v=dba47f93-1:3829
(anonymous) @ en.js?v=dba47f93-1:1
6[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
q843mh2t:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden">​…​</form>​
signaling.js?v=dba47f93-1:224 Joined {ocs: {…}}
5[Violation] 'load' handler took <N>ms
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps/notifications/js/notifications.js.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps2/spreed/js/vendor/backbone.radio/build/backbone.radio.min.js.map
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps2/spreed/js/vendor/backbone.marionette/lib/backbone.marionette.min.js.map
core.js?v=dba47f93-1:3 GET https://***REMOVED SENSITIVE VALUE***/svg/spreed/menu-people/fff?v=1 404
xa @ core.js?v=dba47f93-1:3
css @ core.js?v=dba47f93-1:3
sa @ core.js?v=dba47f93-1:3
ta @ core.js?v=dba47f93-1:3
Ja @ core.js?v=dba47f93-1:3
show @ core.js?v=dba47f93-1:3
n.fn.(anonymous function) @ core.js?v=dba47f93-1:3
show @ core.js?v=dba47f93-1:13
updateContentsLayout @ app.js?v=dba47f93-1:493
(anonymous) @ app.js?v=dba47f93-1:452
(anonymous) @ core.js?v=dba47f93-1:2
j @ core.js?v=dba47f93-1:2
fireWith @ core.js?v=dba47f93-1:2
e.(anonymous function) @ core.js?v=dba47f93-1:2
success @ signaling.js?v=dba47f93-1:198
t.success @ backbone-min.js?v=dba47f93-1:1
j @ core.js?v=dba47f93-1:2
fireWith @ core.js?v=dba47f93-1:2
x @ core.js?v=dba47f93-1:4
(anonymous) @ core.js?v=dba47f93-1:4
load (async)
send @ core.js?v=dba47f93-1:4
ajax @ core.js?v=dba47f93-1:4
e.ajax @ backbone-min.js?v=dba47f93-1:1
e.sync @ backbone-min.js?v=dba47f93-1:1
sync @ backbone-min.js?v=dba47f93-1:1
fetch @ backbone-min.js?v=dba47f93-1:1
OCA.Talk.Signaling.Base.syncRooms @ signaling.js?v=dba47f93-1:196
syncAndSetActiveRoom @ app.js?v=dba47f93-1:425
joinRoom @ connection.js?v=dba47f93-1:93
onStart @ app.js?v=dba47f93-1:725
r @ backbone.marionette.min.js?v=dba47f93-1:9
start @ backbone.marionette.min.js?v=dba47f93-1:10
(anonymous) @ init.js?v=dba47f93-1:23
(anonymous) @ init.js?v=dba47f93-1:24
DevTools failed to parse SourceMap: https://***REMOVED SENSITIVE VALUE***/apps2/spreed/js/vendor/backbone/backbone-min.map
roomlistview.js?v=dba47f93-1:287 addRoomMessage
```
</details>

Thanks!

**Comment by nickvergessen** [comment]
This does not happen for me.
I guess another app is interfering?

**Comment by lachmanfrantisek** [comment]
@nickvergessen thanks for the tip. I'll try to find that app. Any advices which can cause these problems? Or which I do not need to test? (I have quite a lot of apps installed (viz server config), so it can save me some time...) 

Just an alternative idea. Some time ago I have problems with having `apps` folder out of the root. (But I think it was already fix and working well for some time.)

Thanks!

**Comment by blitzdesigner** [comment]
I second that phenomenon. Just upgraded from NC13 (where everything was fine) to NC14.02 and whoops, big empty space left of chat/video-area and right of conversations-pane like in the screens of @lachmanfrantisek .

all the content is squeezed in the small space, video is actually not cut but scaled.

**Comment by fti7** [comment]
Same here.
In an anonym Public Channel (Not logged in), the empty block is an <div id="app" class="nc-enable-screensharing-extension"...
Happens in Chrome and Firefox

**Comment by scurrvy2020** [comment]
Same issue.  Nextcloud 15, nginx, and postgresql.

**Comment by blitzdesigner** [comment]
I tested it also in Firefox, Opera and Vivaldi on different computers, no luck.
This is actually quite annoying, because you can not really use the app like this.

Would be great if a dev could take this up the priority list :-)

**Comment by jdloft** [comment]
Seems to be a problem related with the [GpxPod](https://apps.nextcloud.com/apps/gpxpod) extension. Disabling it resolves the problem.

**Comment by nickvergessen** [comment]
Replace line 17+18 https://gitlab.com/eneiluj/gpxpod-oc/blob/master/appinfo/app.php#L17-18 of apps/gpxpod/appinfo/app.php

With
```php
$eventDispatcher->addListener('OCA\Files::loadAdditionalScripts', function() {
		Util::addScript('gpxpod', 'filetypes');
		Util::addStyle('gpxpod', 'style');
	});
```

And report the problem to the author of the other app: https://gitlab.com/eneiluj/gpxpod-oc/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=

**Comment by blitzdesigner** [comment]
Disabling the PgxPod extension sovled it also on my site. 
Thumps up for figuring this out... 
For my side, this issue is solved :-)

**Comment by lachmanfrantisek** [comment]
@blitzdesigner @nickvergessen @jdloft Thanks for finding it out!

I've submitted [a new issue](https://gitlab.com/eneiluj/gpxpod-oc/issues/139) in the gpxpod repo.

**Comment by eneiluj** [comment]
Thanks for the bug report. Sorry about that. It's fixed and will be included soon in next GpxPod release.
