### ISSUE TITLE
Moderator menu cut off when opened

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1416]
## Steps to reproduce
1. Join a room as an owner with one guest
2. Use the moderator control menu on the guest to remove them
3. The popup menu is cut off and hidden 
![screenshot from 2018-12-18 15-44-01](https://user-images.githubusercontent.com/11549367/50132685-6f9afe00-02dc-11e9-9a79-68288b2604cf.png)

### Expected behaviour
The menu should be visible

### Actual behaviour
The menu is not visible

## Browser
Firefox

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 64.0

## Spreed app

**Spreed app version:3.2.7

Adding height: 100% in style.scss for:

#app-sidebar #participantsTabView .participantWithList {

and

#app-sidebar #participantsTabView {

Fixes this.

**Comment by nickvergessen** [comment]
@ma12-co you fixed this, right?

**Comment by ma12-co** [comment]
@nickvergessen   Yes, but I just hard-coded more padding, It wont work if that menu will have more items in the future.

https://github.com/nextcloud/spreed/pull/1822/commits/d5695d3f92054e25ec681e87298126d07441dbee
