### ISSUE TITLE
huge favorite icons after the update to Talk 5.0

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1417]
Favorite Icons are huge since the update to Talk 5.0:

![image](https://user-images.githubusercontent.com/1589737/50149590-ea075600-02bb-11e9-8ef7-6efc82872e45.png)

**Comment by jancborchardt** [comment]
Also just saw this. Guess that’s because favorites in the `#app-navigation` are not standardized yet? https://docs.nextcloud.com/server/15/developer_manual/design/navigation.html#app-navigation-menu

cc @nextcloud/designers

**Comment by nickvergessen** [comment]
Na, its a regression from https://github.com/nextcloud/spreed/pull/1346
