### ISSUE TITLE
Guests can immediately re-join a public meeting after being removed by the moderator

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1423]
## Steps to reproduce
1. Join a public room as owner
2. In another browser join the room as a guest
3. Remove the guest using the owner

### Expected behaviour
The guest should be removed and not be able to rejoin

### Actual behaviour
The guest is removed and rejoins almost immediately when the polling for participants is performed

## Spreed app

**Spreed app version: 3.2.7
To prevent guests from rejoining a blacklist should be maintained for the nextcloud session cookie and if the guest is in the blacklist they should be redirected to another page instead of joining the call.  A configurable timeout could be implemented for the blacklist so that a guest can rejoin after the timeout, default perhaps an hour.  This can be bypassed by clearing the cookies but it at least provides some control in a webinar environment.

**Comment by GoetheG** [comment]
It would be nice if there were interaction between Nextcloud Talk and Rocket.Chat. This could solve some problems in the future.

**Comment by nickvergessen** [comment]
Just for the record, such problems are unluckily to get fixed in 3.2 and 4.0
Since this involves bigger and behaviour changes, we only ever fix such things in the upcoming feature release

**Comment by PVince81** [comment]
the moderator should also have the option to add back that guest, in case the guest was banned by mistake (or got forgiven somehow)

**Comment by nickvergessen** [comment]
Well the idea is to not allow guests anymore and instead invite people via their email address giving them custom login pins.
This way you can remove them in the future (invalidating the pin) and invite them again (creating a new pin for the email again)

**Comment by socialize-IT** [comment]
As a workaround you can change the password after kicking the guest, so he can't enter again. AFAIK nobody is kicked out because of the password change. Doesn't work if you are waiting for more new guests to join..

**Comment by nickvergessen** [comment]
Solved by https://github.com/nextcloud/spreed/issues/12291
