### ISSUE TITLE
Limit group call size for instances without signaling server

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#1425]
When there is no signaling server configured, the practical technical limit to group calls is at about 4 participants, since the data stream has to be handled peer-to-peer on each client.

However, nothing is preventing users to setup larger group calls anyway - which may result in a bad user experience without having been warned.

Some server-side prevention of too large p2p group calls would make sense to me.

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/spreed/issues/337
