### ISSUE TITLE
Does the Talk server enable PFS (Perfect Forward Secrecy) cipher suites by default it the browser supports them?

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/spreed#1428]
Check /  enhancement feature:

If we use Talk with browser(s) which is(are configured to use PFS (Perfect Forward Secrecy) cipher suites as default, does the Talk server enable/use them also?

Thanks!

**Comment by mario** [comment]
Yes it should, considering that both Firefox and Chrome support this.

**Comment by nickvergessen** [comment]
@fancycode do you know what this is about and something we can/should do?

**Comment by fancycode** [comment]
Talk is using WebRTC with peer-to-peer connections, so if the browsers support PFS, it will be used.
