### ISSUE TITLE
Remove dependency on external TURN service

### ISSUE THREAD

**Issue by 9662** [nextcloud/spreed#1429]
## Steps to reproduce
1. Install Talk
2. Attempt call between two endpoints, at least one of which is behind NAT, or any other situation requiring TURN.

### Expected behaviour
Call should succeed. It should be possible to have two-way voice and/or video comms.

### Actual behaviour
Call fails.

## Description

The requirement for TURN is an extremely frequent scenario for internet (i.e., non-LAN) calls (cf. #141). Requiring that the user install and configure an external service such as `coturn` raises the entry barrier quite unnecessarily.

In my view, for Talk to be useful as a first-class Nextcloud component, its installation and configuration need to be as frictionless as possible. This implies removing the requirement for installing / configuring an external TURN server with shared password support (that is an *very* specific requirement, e.g., my `ejabberd` server with STUN/TURN support is not enough).

One possible solution is to ship with a built-in TURN implementation. There may be other options too.

**Comment by nickvergessen** [comment]
Php can not handle the functionality of a turn server.
Also providing a host service for turn servers is neither our business nor our goal, as we prefer people to host stuff themselves to have the control on their size
