### ISSUE TITLE
Orphan conversations after the last moderator/owner leaves

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1435]
## Steps to reproduce
1. Create a group conversation
2. Leave the conversation
3. Remaining members of the group are left in a room where no one is owner/moderator

### Possible solutions
1. When the last owner/moderator leaves, the room is deleted
2. When the last owner/moderator leaves, everyone is promoted to a moderator
3. When the last owner/moderator leaves, the last active user is promoted to a moderator
4. When the last owner/moderator leaves, the first alphabetic user is promoted to a moderator
5. When the last owner/moderator leaves, it's okay to have this "dead" chat
6. The last owner/moderator can not leave the conversation, they have to either promote someone first, or delete the conversation instead.

Currently 5 is what is happening. The biggest problem is, no one can tell people to leave the conversation and continue in the "correct new" conversation. Also no one can add new people, e.g. the creator of the room.

This happened on our instance, @mario created the "Engineering" call for testing ( https://cloud.nextcloud.com/call/eoz9oqvw ) and left it directly afterwards. Now the group is used sometimes (e.g. by @jancborchardt ) instead of the correct internal conversation, but there is no way for us to recover.

Whatsapp also has this problem, Threema e.g. blocks leaving for the admin.

I would prefer 1 (with a notice) or 6.

Opinions @jancborchardt @Ivansss @mario

**Comment by mario** [comment]
Option 1 is very dangerous - I am against deleting conversations for the other involved sides when a person leaves by default.

If I have to pick between the suggested options, 6 is fine.

What about an option:

7) Archive the conversation - (this would obviously need the Archiving concept) allowing people to read, but not write in the conversation or start/join calls in it), along with the reason why this conversation was archived:
"This conversation was archived because the last active moderator/owner left"

**Comment by jancborchardt** [comment]
The options which seem to be most expected are:

> 2. When the last owner/moderator leaves, everyone is promoted to a moderator

and

> 6. The last owner/moderator can not leave the conversation, they have to either promote someone first, or delete the conversation instead.

Probably it’s easiest to first implement 2? It’s most simple and just works. Then in another step we could think if we need 6.


-------------

> This happened on our instance, @mario created the "Engineering" call for testing ( https://cloud.nextcloud.com/call/eoz9oqvw ) and left it directly afterwards. Now the group is used sometimes (e.g. by @jancborchardt ) instead of the correct internal conversation, but there is no way for us to recover.

Hah, I didn’t know! :D Thanks for the explanation, then let’s abandon it! :)
