### ISSUE TITLE
no video when using mobile internet connection

### ISSUE THREAD

**Issue by nofear87** [nextcloud/spreed#1441]
When using a mobile internet connection (f.e. lte) no video is send, audio works as expected. Video is not send in both directions.

Mobile connection bandwidth is good enough!

As soon as we switch to cable internet video is transmitted without any problems.

Log is quietly :-(

Browsers: Firefox/Chrome
Talk: 3.2.7
NextCloud: 13.0.1

**Comment by nickvergessen** [comment]
The Talk and Nextcloud version you are using is very old. Please update to Nextcloud 15 and Talk 5 and retest.
