### ISSUE TITLE
Own video is too big, should be smaller

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1442]
https://github.com/nextcloud/spreed/blob/9c56e0d3ae20f2a6c40c3312695977d74aafee88/css/video.scss#L172
A better size is 22%

**Comment by nickvergessen** [comment]
I guess we'll address this in #1056

**Comment by jancborchardt** [comment]
@nickvergessen I’d treat this separately, since #1056 is specifically for the UI when there’s _many_ participants.

@Peterede do you want to suggest a pull request changing the value from 33% to 22%? :slightly_smiling_face:

**Comment by jancborchardt** [comment]
Fixed by @anstue in https://github.com/nextcloud/spreed/pull/1508 :tada:
