### ISSUE TITLE
More visible in-browser notifications

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/spreed#1443]
The in browser notifications should be more visible. 
1. Currently if you miss the system notification popup and you are not on the NC tab you will have no idea something is up. Ideally the tab should have some indicator on it - number of notifications or at least some colored dot or something similar.
2. Calls by definitions require urgent attention and should have a persistent system notification popup along with call sounds.

**Comment by nickvergessen** [comment]
1. I would say it refers to #798 

2. will be dealt with in #1444 and just for the record sound is not possible, because firefox and chrome prevent automatic audio playing without user interaction.

**Comment by gradinaruvasile** [comment]
Yes, it is pretty much what #798 wants to accomplish. I was thinking about something like this:

![riot](https://user-images.githubusercontent.com/16729939/51444769-b1b4c680-1d04-11e9-9ce8-7448a6a038f6.png)

The idea is to have a notification count visible even if the user is on another tab.

**Comment by nickvergessen** [comment]
Closing as duplicate
