### ISSUE TITLE
sidebar overlaps the video window

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1446]
When resizing the window the sidebar overlaps the video window clipping the content, this comes from the server.css rules for sizing the app-content at window sizes 768 and also the percentage margin which need to be overridden:

#app-content { 
    width: auto !important; 
}
	
#app-content.with-app-sidebar { 
    margin-right: 300px !important; 
}

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/issues/1056

**Comment by nickvergessen** [comment]
There were a lot of changes in that area and also #1056 is still there, so I will close this
