### ISSUE TITLE
streaming to twitch, youtube and other similar services

### ISSUE THREAD

**Issue by tansaku** [nextcloud/spreed#1455]
I'd love to be able to stream meetings to youtube, twitch and similar so make the meeting available to those who just want to watch, and also to make a recording of the meeting possible

Is that something that's currently supported?

**Comment by nickvergessen** [comment]
That's not planned and not supported atm.

For recordings, the external MCU unit can assist you: https://nextcloud.com/talk/

Otherwise you can use any known tool to stream your screen+audio to whatever side, but nothing we will implement.
