### ISSUE TITLE
Possibility to order chats in groups (public, private, group)

### ISSUE THREAD

**Issue by theDyingMountain** [nextcloud/spreed#1470]
**Is your feature request related to a problem? Please describe.**
If many conversations are open in the left sidebar, it would be useful to be able to arrange them. At the moment every new conversation is placed on top.

**Describe the solution you'd like**
An icon button to move and order the conversations.

**Describe alternatives you've considered**
"Group by type" button to automatically organize the conversations into the 3 groups public, groups and private.

**Comment by nickvergessen** [comment]
Conversations are currently sorted by last-activity similar to all other chat platforms (apart from slack). So not sure if adding an option for that is high on the list.

**Comment by Nyco** [comment]
> Conversations are currently sorted by last-activity similar to all other chat platforms (apart from slack).

Only personal instant messengers sort by last activity: WhatsApp, Facebook Messenger, Telegram.

Enterprise/team chats have a fixed, non-dynamic ordering: Slack, Discord, MS Teams, Rocket.Chat, Mattermost.

Some, like the now-defunct HipChat allowed the user to re-order chats by drag and drop, which was quite a useful feature, that's lacking in other such software.

> So not sure if adding an option for that is high on the list.

That non-predictive ordering makes it diffcult to find your conversations.

**Comment by nickvergessen** [comment]
Closing this for now as this is nothing we plan to implement
