### ISSUE TITLE
Spreed not usable with more than four persons

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/spreed#1475]
Turnserver is created and server has no load, network load or memory load. 

Any hints to configuration? 

Thanks in advance, Details are listed below. 

## Steps to reproduce
1. Login with a few particupants 
2. The first four persons don't have any issue
3. The fifth Person does not get connected or can only hear half of the group

### Expected behaviour
IT should work correctly 

### Actual behaviour
The fifth or later Person cannot attend correctly

## Browser
Different Browser tried. 
**Microphone available:** yes

**Camera available:** yes and no

**Operating system:** windows 10

## Spreed app

**Spreed app version:** 5.0 1

**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0 32

**Nextcloud Version:** 15.02

**Comment by nickvergessen** [comment]
There have been several tries to fix this. One is #1284 but it is currently blocked by #1063 and will be looked at after that again.

The other solution is to acquire a Nextcloud talk subscription and use the MCU which makes your client only render one video everytime: https://nextcloud.com/talk/
