### ISSUE TITLE
Make local video mirroring configurable via the UI

### ISSUE THREAD

**Issue by frzb** [nextcloud/spreed#1476]
**Is your feature request related to a problem? Please describe.**

The video of myself is mirrored - it just feels odd.

<video id="localVideo" autoplay="" style="transform: scaleX(-1);"></video>

**Describe the solution you'd like**

The mirroring of the local video is switchable via `style="transform: scaleX()`.
This should be made **configurable in the UI** - to give the user a choice according his preference.

### Mirrored (current default)
```
<video id="localVideo" autoplay="" style="transform: scaleX(-1);"></video>
```

### Not Mirrored 

```
<video id="localVideo" autoplay="" style="transform: scaleX(1);"></video>
```

**Describe alternatives you've considered**

I could mirror the video stream from the camera on the system level - but this would require further software and configuration.

**Comment by nickvergessen** [comment]
I'm also not a huge fan of mirroring.

@jancborchardt do you happen to know why this was added?

**Comment by jancborchardt** [comment]
> The video of myself is mirrored - it just feels odd.

What about it feels "odd"?

Mirroring the selfie-video is standard in video chat apps and I couldn’t find any single app which does not do this. Tested with: Signal, WhatsApp, Skype, Hangouts, Facebook Messenger, Instagram and camera apps on iOS and Android. (Not tested: Snapchat.)

Yes this is odd when you hold some text into the camera and it appears as mirrored. But others will see it correctly. And also, it’s much weirder when it’s _not_ mirrored and when you want to adjust what to film and you move one way but it moves the other way and you need to adjust in your head.

Feel free to try it out with this fix, using the [Custom CSS app](https://apps.nextcloud.com/apps/theming_customcss):
```
#localVideo {
    transform: none !important;
}
```

**Comment by jancborchardt** [comment]
> But it is also not uncommon to provide the user an option to swap the local preview to be not mirrored.
It all depends on the context the user is coming from.

I understand you would like a setting for this, and the Custom CSS app solves it for you. But putting it in the core software is a different thing.

The reality is that as described, the default for all of the platforms is mirrored. And that regular users rarely change any settings.


> Which is possible without adding much clutter to the UI.

We heard that many times through the years, for things big and small. :) A lot of small "not much clutter" makes for a messy product over time that is not nicely usable for anything.

For further reading on why Nextcloud has a minimum of settings, I recommend »[Choosing our Preferences](https://ometer.com/preferences.html)«.
