### ISSUE TITLE
Talk - in browser

### ISSUE THREAD

**Issue by dhenry123** [nextcloud/spreed#1477]
## Steps to reproduce
1. Open discuss and add file from nextcloud (button +) 
![screen shot 01-27-19 at 11 40 am 001](https://user-images.githubusercontent.com/27366357/51797375-75172c80-2228-11e9-8732-d08636a83a19.PNG)

2. Div is opened now, and show nextcloud storage ressources, but each line is masked because of css styles missing

### Expected behaviour
![screen shot 01-27-19 at 11 48 am](https://user-images.githubusercontent.com/27366357/51797430-79901500-2229-11e9-8897-007f75dff1ad.PNG)

### Actual behaviour
![screen shot 01-27-19 at 11 40 am](https://user-images.githubusercontent.com/27366357/51797384-c45d5d00-2228-11e9-8a0f-12373b120320.PNG)

**### Solution which is working inline is : "add css style" : 
background-repeat: no-repeat;
padding-left: 20px;**

## Browser
**Microphone available:**  no
**Camera available:** no
**Operating system:** Windows
**Browser name:** Firefox
**Browser version:** 64.0.2
### Browser log
a) The javascript console log : 
it's displayed when i click on (+) button
![screen shot 01-27-19 at 11 51 am](https://user-images.githubusercontent.com/27366357/51797460-2d91a000-222a-11e9-836d-52e2cc1d02d6.PNG)
 **not reproductible with Chrome Version 71.0.3578.98**

## Server configuration
**Operating system**: ???
**Web server:** ???
**Database:** ???
*PHP version:** ???
**Nextcloud Version:**  **15.xxxx**
**List of activated apps:** ???

**Comment by nickvergessen** [comment]
This works perfectly fine here.
I guess the JS console error you are seeing is the point where you should start looking at.

**Comment by dhenry123** [comment]
thank you for your reply, i tried with a fresh install (15) and no problems... This given config is hosted and i have no ways to debug on server. The test with a fresh install was made on my home rock64-4GB server (arm64 debian distrib) and it's just...amazing.
Thank you, we keep in touch if i ve more informations
