### ISSUE TITLE
Share a location

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#1478]
**Is your feature request related to a problem? Please describe.**
Sometimes, I would like to let my family know my current whereabouts without typing it as I might not even know the correct address.

**Describe the solution you'd like**
Give me the ability to send a message with messageParameter of type "location" with lat and lng parameters.

**Comment by DeeeeLAN** [comment]
Maybe an integration with phonetrack would make this possible

**Comment by PVince81** [comment]
this lib could do for rendering a live map: https://github.com/vue-leaflet/Vue2Leaflet

**Comment by PVince81** [comment]
Some example here: https://vue2-leaflet.netlify.app/examples/simple.html

One thing that comes to mind for such complex objects is that we better not render them until the user scroll to them using the "v-observe-visibility" directive that is already available

We also need to think about how to render it when it's quoted, which is usually a smaller version of it, maybe in this case a static image would do.

**Comment by nickvergessen** [comment]
Okay so in a call we decided to store and share the location data via ROS similar like we do it with the deck cards.

This allows us to have the coordinates separately available already and on rendering it can then be turned into a OSM or google link or handed over to an installed mobile Map app.

**Comment by nickvergessen** [comment]
Server base to allow geo-location as rich object: https://github.com/nextcloud/server/pull/26764

**Comment by nickvergessen** [comment]
Also pinged @tacruc and @eneiluj  in the Maps channel if they want to add an API like https://github.com/nextcloud/deck/pull/2772 so Talk could add a Right-click action menu item

**Comment by nickvergessen** [comment]
API in server is updated, so you can now share to Talk with:
```
curl -k -u admin:admin \
    -H "OCS-APIRequest: true" \
    https://localhost/ocs/v2.php/apps/spreed/api/v1/chat/3cyxfvxm/share  -X POST \
    -d 'objectType=geo-location' \
    -d 'objectId=geo:52.5450511,13.3741463' \
    -d 'metaData={"type":"geo-location","id":"geo:52.5450511,13.3741463","latitude":"52.5450511","longitude":"13.3741463","name":"Nextcloud Berlin Office"}'
```

**Comment by nickvergessen** [comment]
capability added in https://github.com/nextcloud/spreed/pull/5592
