### ISSUE TITLE
PHP Fatal error:  Cannot use OCP\Util as Util because the name is already in use in /var/www/nextcloud/apps/spreed/lib/Files/TemplateLoader.php

### ISSUE THREAD

**Issue by Emi94** [nextcloud/spreed#1489]
## Steps to reproduce
1. Set crontab to run /var/www/nextcloud/cron.php every 15 minutes

### Expected behaviour
The crontab should run without errors

### Actual behaviour
`PHP Fatal error:  Cannot use OCP\Util as Util because the name is already in use in /var/www/nextcloud/apps/spreed/lib/Files/TemplateLoader.php on line 27` is thrown everytime the cron is running and Nextcloud is reporting that the cron did not run in days. This started after I upgraded to Nextcloud 15.0.2 from 14.0.4

</details>

## Spreed app

**Spreed app version:** 5.0.1 (error present in 5.0.0 as well)

## Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.5

**PHP version:** 7.0

**Nextcloud Version:** 15.0.2

### Server log (data/nextcloud.log)

> {"reqId":"sMkhvIgBrGddmImiDFm4","level":3,"time":"2019-01-29T11:45:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Cannot use OCP\\Util as Util because the name is already in use at \/var\/www\/nextcloud\/apps\/spreed\/lib\/Files\/TemplateLoader.php#27","userAgent":"--","version":"15.0.2.0"}

**Comment by nickvergessen** [comment]
The patch we are going to make does not apply cleanly on your current version.

In order to fix it yourself, edit `apps/spreed/lib/Files/TemplateLoader.php`:
find and delete:
```php
use OCP\Util;
```

And then replace all occurrences of `Util::addStyle(` with `\OCP\Util::addStyle(` and all occurrences of `Util::addScript(` with `\OCP\Util::addScript(`

**Comment by Emi94** [comment]
The new app version fixed the issue. Thanks for the fast fix.
