### ISSUE TITLE
talk 5.0.2 bug (server error)

### ISSUE THREAD

**Issue by jookk** [nextcloud/spreed#1499]
![img_20190130_225349-picsay](https://user-images.githubusercontent.com/11217085/52015671-c4888180-24e2-11e9-9313-b6ac454836d1.jpg)
## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
In `apps/spreed/lib/Config.php`
find:
```php
if (is_array($servers)) {
```
replace with:
```php
if (is_array($servers) && !empty($servers)) {
```

**Comment by jookk** [comment]
After that fix I can not use Talk (android nc talk only loading without call and freezes. 
https://github.com/nextcloud/notifications/issues/202#issuecomment-459689384
