### ISSUE TITLE
Named user appearing as Guest when sharing their screen

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#1509]
## Steps to reproduce
1. User A initiates group conversation
2. User A adds User B to group conversation
3. User A starts Call
4. User B joins call
5. User B shares their screen

### Expected behaviour
User A sees User B's screen, below it says "User B's screen"

### Actual behaviour
User A sees User B's screen, below it says "Guest's screen"

## Spreed app

**Spreed app version:** 

5.0.2

**Comment by nickvergessen** [comment]
I can not reproduce this, neither on master, nor on stable15 nor on our company instance
