### ISSUE TITLE
Spinner flickers ontop of avatar during call

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#1511]
## Steps to reproduce
1. having a call with at least 3 people

### Expected behaviour
no flickering spinner/loading icon on avatars

### Actual behaviour
flickering spinner on avatars

Talk 5.0.2 on Nextcloud 15.0.2 with Chrome.

This was recorded during a call: https://cloud.morrisjobke.de/s/Gj2nN5KBfXRp8KJ

cc @nickvergessen @danxuliu

**Comment by nickvergessen** [comment]
@fancycode any idea what could be wrong?

**Comment by fancycode** [comment]
One difference that comes to my mind is that with the MCU we regularly send the nickname to the peers instead of just once when publishing starts:
https://github.com/nextcloud/spreed/blob/f18ae3391627743422fb1f866819479dc9e654d2/js/webrtc.js#L608

Could receiving the name multiple times cause the flickering?

**Comment by nickvergessen** [comment]
@Ivansss any idea?

**Comment by Ivansss** [comment]
> Could receiving the name multiple times cause the flickering?

That's exactly the reason
https://github.com/nextcloud/spreed/blob/master/js/webrtc.js#L1300

**Comment by nickvergessen** [comment]
Ah oh, I guess we should just ignore that for login users? doesn't matter if your avatar doesn't live update in calls?

**Comment by fancycode** [comment]
> That's exactly the reason

Hmm, this was not the case in earlier versions, has something changed when setting an avatar name?

Anyway, there are two possible solutions:
- Fix #991 :smiley: 
- Only set the avatar name if it really has changed since the last `nick`  event.

**Comment by Ivansss** [comment]
> Hmm, this was not the case in earlier versions, has something changed when setting an avatar name?

I think that's because avatars now show this spinner while loading the image. Didn't happen in earlier NC versions.

**Comment by nickvergessen** [comment]
I will make a patch

**Comment by danxuliu** [comment]
@nickvergessen 
>  I will make a patch

I will do it once I have finished with #1513.
