### ISSUE TITLE
Nextcloud/Talk not working after upgrade from 15.0.2 to 15.0.4

### ISSUE THREAD

**Issue by Thomas301263** [nextcloud/spreed#1526]
## Steps to reproduce
1.Upgrade from 15.0.2 to 15.0.4
2.Open up Nextcloud/Talk
3.

### Expected behaviour
Tell us what should happen
Normally Nextcloud Talk should work like before the upgrade but I am getting error message instead.
### Actual behaviour
Tell us what happens instead
Nextcloud/talk will not start and error message is shown on screen
## Browser
Firefox
**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Ubuntu 18.04
**Browser name:** Firefox/Chrome/...
Firefox
**Browser version:** 50.1/55/...
65.0
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
5.0.2
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
yes  Ubuntu / Coturn
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu
**Web server:** Apache/Nginx
Nginx
**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria
**PHP version:**
7.2.10
**Nextcloud Version:** (see admin page)
15.0.4
**List of activated apps:**
<details>
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - audioplayer: 2.6.0
  - bookmarks: 0.16.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - gpxedit: 0.0.10
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ojsxc: 3.4.3
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - weather: 1.5.5
  - workflowengine: 1.5.0

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx",
            "xxxxx",
            "xxxxx"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "integrity.check.disabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 2,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxxxx\/nextcloud",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "forcessl": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "has_internet_connection": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "apps_paths": [
            {
                "path": "\/var\/www\/xxxxx\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appcodechecker": true,
        "appstore.experimental.enabled": true,
        "updatechecker": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "theme": "",
        "maintenance": false,
        "overwritewebroot": "\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "debug": false,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "updater.release.channel": "stable",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "auth.bruteforce.protection.enabled": false,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
{"reqId":"z6aqo2SZ6EYTAPeKn4sE","level":3,"time":"2019-02-09T11:09:26+01:00","remoteAddr":"192.168.178.100","user":"thomas","app":"PHP","method":"GET","url":"\/nextcloud\/index.phpeader\/poll?lastReqId=njKJZJ1u5v6iVuN0fYSX","message":"fopen(\/media\/cloud\/nextcloud\/data\/nextcloud.log): failed to open stream: No such file or directory at \/var\/www\/xxxxx\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php#71","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"z6aqo2SZ6EYTAPeKn4sE","level":3,"time":"2019-02-09T11:09:26+01:00","remoteAddr":"192.168.178.100","user":"thomas","app":"index","method":"GET","url":"\/nextcloud\/index.phpeader\/poll?lastReqId=njKJZJ1u5v6iVuN0fYSX","message":{"Exception":"Exception","Message":"Error while opening \/media\/cloud\/nextcloud\/data\/nextcloud.log","Code":0,"Trace":[{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php","line":101,"function":"getLogIterator","class":"OCA\\LogReader\\Controller\\LogController","type":"->","args":["11111"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php","line":130,"function":"getLastItem","class":"OCA\\LogReader\\Controller\\LogController","type":"->","args":["11111"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"poll","class":"OCA\\LogReader\\Controller\\LogController","type":"->","args":["njKJZJ1u5v6iVuN0fYSX","11111"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\LogReader\\Controller\\LogController"},"poll"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\LogReader\\Controller\\LogController"},"poll"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\LogReader\\Controller\\LogController","poll",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"logreader.log.poll"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"logreader.log.poll"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"logreader.log.poll"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/logreader\/poll"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/xxxxx\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php","Line":78,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"3vK3Gtebvoub3j8ZirKy","level":3,"time":"2019-02-09T11:09:33+01:00","remoteAddr":"192.168.178.100","user":"thomas","app":"index","method":"GET","url":"\/nextcloud\/index.phped\/","message":{"Exception":"Error","Message":"Minimum value must be less than or equal to the maximum value","Code":0,"Trace":[{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","line":157,"function":"random_int","args":[0,-1]},{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","line":57,"function":"getStunServer","class":"OCA\\Spreed\\Config","type":"->","args":[]},{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Controller\/PageController.php","line":176,"function":"getSettings","class":"OCA\\Spreed\\Config","type":"->","args":["thomas"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Spreed\\Controller\\PageController","type":"->","args":["","",""]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"spreed.Page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/spreed\/"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","Line":157,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"dFQ4uTiG2F5jLhDFthnB","level":3,"time":"2019-02-09T11:15:56+01:00","remoteAddr":"192.168.178.100","user":"thomas","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v2.php\/apps\/spreed\/api\/v1\/signaling\/settings","message":"Error: Minimum value must be less than or equal to the maximum value at \/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php#157","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}
{"reqId":"vNY7BzTBCuiGNHNGgRsF","level":3,"time":"2019-02-09T11:25:22+01:00","remoteAddr":"192.168.178.100","user":"thomas","app":"index","method":"GET","url":"\/nextcloud\/index.phped\/","message":{"Exception":"Error","Message":"Minimum value must be less than or equal to the maximum value","Code":0,"Trace":[{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","line":157,"function":"random_int","args":[0,-1]},{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","line":57,"function":"getStunServer","class":"OCA\\Spreed\\Config","type":"->","args":[]},{"file":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Controller\/PageController.php","line":176,"function":"getSettings","class":"OCA\\Spreed\\Config","type":"->","args":["thomas"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Spreed\\Controller\\PageController","type":"->","args":["","",""]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"spreed.Page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/xxxxx\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/spreed\/"]},{"file":"\/var\/www\/xxxxx\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/xxxxx\/nextcloud\/apps\/spreed\/lib\/Config.php","Line":157,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.4.0"}


```
</details>

**Comment by nickvergessen** [comment]
What error message are you seeing?

**Comment by Aejoh** [comment]
I think i have the same error.

## Browser

```
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
```

## nextcloud.log

`"Error","Message":"Minimum value must be less than or equal to the maximum value"`

`{"reqId":"PCHHnR8KwQAEmdFy3fdh","level":3,"time":"2019-02-10T09:52:13+01:00","remoteAddr":"x.x.x.x","user":"xxxxxn@xxxxx.xxx","app":"index","method":"GET","url":"\/index.php\/apps\/spreed\/","message":{"Exception":"Error","Message":"Minimum value must be less than or equal to the maximum value","Code":0,"Trace":[{"file":"\/var\/www\/apps\/spreed\/lib\/Config.php","line":157,"function":"random_int","args":[0,-1]},{"file":"\/var\/www\/apps\/spreed\/lib\/Config.php","line":57,"function":"getStunServer","class":"OCA\\Spreed\\Config","type":"->","args":[]},{"file":"\/var\/www\/apps\/spreed\/lib\/Controller\/PageController.php","line":176,"function":"getSettings","class":"OCA\\Spreed\\Config","type":"->","args":["admin@sn3t.com"]},{"file":"\/var\/www\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":"OCA\\Spreed\\Controller\\PageController","type":"->","args":["","",""]},{"file":"\/var\/www\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\PageController"},"index"]},{"file":"\/var\/www\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"spreed.Page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"spreed.Page.index"}]},{"file":"\/var\/www\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/spreed\/"]},{"file":"\/var\/www\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/apps\/spreed\/lib\/Config.php","Line":157,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.96 Safari\/537.36","version":"15.0.4.0"}
`

**Comment by Aejoh** [comment]
my problem was solved that i entered my own stun instead of the default stun.nextcloud.com:443

**Comment by nickvergessen** [comment]
Ah, your issue should be fixed with https://github.com/nextcloud/spreed/pull/1500/files
