### ISSUE TITLE
Call signal when ringing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#1527]
I suggest adding a call signal when connecting to another user. Similar to a telephone connection.

This is missing. During the call, it is not known whether you are connecting to another user and when you have answered or disconnected.

**Comment by nickvergessen** [comment]
This should be handled in #1444

**Comment by Valdnet** [comment]
@nickvergessen My request for a function is different.
I am asking for a function so that the person calling the user will hear the call signal as in the telephone earpiece (tiiiiiiit, tiiiiiiit, tiiiiiiit ...) :grin:  Something similar to Skype.

:telephone:
Currently, when calling from the Nextcloud Talk application for Android from the phone placed to your ear, you can not see if a call is being made.

**Comment by nickvergessen** [comment]
If you are talking about the android app, you should report it at https://github.com/nextcloud/talk-android/issues

**Comment by Valdnet** [comment]
OK. I thought that the ringing must be added in Spreed 😉 
When connecting from a computer, laptop (of course, not holding it to your ear) :smile:, this option would also be needed. It would always reflect the authenticity of ringing. There is such a feature in Skype.
