### ISSUE TITLE
Duplicate call termination message

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#1530]
## Steps to reproduce
1. Create a conversation with a registered user.
2. The added user is to make a call.
3. The user leaves the call.
4. You start a call.
5. The user join the call.
6. The user ends the call,
7. You end the call.

![obraz](https://user-images.githubusercontent.com/47037905/52579818-4e134a00-2e27-11e9-9fba-967949fb347e.png)

### Expected behaviour
Valid connection information.

### Actual behaviour
Duplicated information:  `left the call` and `You left the call` (marked in red squares).

## Browser
**Microphone available:** yes

**Camera available:**  no

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 65.0

## app
NextCloud v15.0.4
Spreed  v5.0.2

**Comment by Valdnet** [comment]
The duplicate call termination still occurs in Talk 6.0.1.

**Comment by Valdnet** [comment]
The duplicate call termination still occurs in Talk 6.0.1.

**Comment by nickvergessen** [comment]
Does it only happen with the android app?
Can you reproduce it with another user?

**Comment by nickvergessen** [comment]
Can I ask you to still reopen a new issue, because this one is already part of a release.
