### ISSUE TITLE
Wrong signaling ticket on video verification for logged in users

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1537]
## Steps to reproduce
1. Setup standalone signaling, share document through video verification.
2. As logged in user, click on link to access share.

### Expected behaviour
Connection to standalone signaling server should get established.

### Actual behaviour
Standalone signaling server rejects authentication data.

This happens because the signaling settings (i.e. the ticket) are fetched as the authenticated user (from `https://domain.tld/ocs/v2.php/apps/spreed/api/v1/signaling/settings`), but the authentication data for the signaling server uses the anonymous credentials:
```json
{
  "type": "hello",
  "hello": {
    "version": "1.0",
    "auth": {
      "url": "https://domain.tld/ocs/v2.php/apps/spreed/api/v1/signaling/backend",
      "params": {
        "userid": null,
        "ticket": "random-data:123456789:userid:even-more-random-data"
      }
    }
  },
  "id": "1"
}
```

Either the userid of the authenticated user should be sent to the standalone signaling server, or the ticket should not contain a userid.

**Comment by nickvergessen** [comment]
Since on `ocs/v2.php/apps/spreed/api/v1/signaling/settings` we don't know whether it is called from a share auth or not, I would say the share auth should use the user?

**Comment by fancycode** [comment]
That would probably be the best, however there is currently no user authenticated in the context of the share.

The signaling code is using `OC.getCurrentUser()` which is `{uid: null, displayName: null}`:
https://github.com/nextcloud/spreed/blob/master/js/signaling.js#L899
