### ISSUE TITLE
Offer help for not working mic/video

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#154]
On my laptop mic/video does not work: "Error while accessing microphone & camera The object can not be found here."

And I (as a slightly experienced user ;) ) have no idea what to do.
So it would really be helpful to provide some help.
(on my mobile phone it is working with firefox, so it should not be a server problem).

**Comment by jancborchardt** [comment]
Can we output a more helpful error here? cc @fancycode @LukasReschke 

@tobiasKaminsky any other logs in the JS browser console? Does it work on https://talky.io?

**Comment by tobiasKaminsky** [comment]
No, talky.io is also not working. 
They also do not give me a hint what to do ;)

**Comment by tobiasKaminsky** [comment]
I made a really dump mistake: my webcam did not work at all.
But now it is working with a local program.
But neither talky.io not nextcloud11 are working (tested with firefox and chromium)

**Comment by sushidave** [comment]
Tested on Nextcloud 11 with these scenarios:


1) Firefox on a MacBook:
=> working fine


2) Firefox on a Windows 7 PC with a microphone but no camera:
=> error: "Error while accessing microphone and camera. The object cannot be found here."

Would it be useful to provide some instructions for troubleshooting, for example in the help section/manual?


3) Firefox on iOS (iPhone):
=> error: "WebRTC is not supported in your browser. Please use a different browser like Firefox or Chrome."

The error message is confusing here because in this scenario a Firefox browser is being used. WebRTC seems to work with Firefox on @tobiasKaminsky's mobile device, but obviously it does not work with Firefox on iOS. Is there any overview of browser <-> OS combinations that are WebRTC-capable and if so, could it be added to the app's page (https://apps.nextcloud.com/apps/spreed)?

**Comment by jancborchardt** [comment]
@sushidave thank you for the thorough testing! :) Does it work with Chrome on iOS or Safari on iOS? Like, any iOS browser at all? Because they basically all use the Safari/Webkit engine, don’t they?

On the systems with microphone but no camera it should also work. @nickvergessen @fancycode @Ivansss didn’t we have checks for that in place? If not can that be improved?

**Comment by nickvergessen** [comment]
Mic and no video works for robin IIRC. I can't test that....

**Comment by sushidave** [comment]
@jancborchardt You're welcome.

Tested with Safari on iOS (iPhone):
=> error: "WebRTC is not supported in your browser. Please use a different browser like Firefox or Chrome."

It looks as if WebRTC for Webkit still is in development:
https://webkit.org/status/#specification-webrtc

What's your view on these two short term solutions:
1. Add a list of supported browsers/OS in the README file and manual.
2. Review the browser checks and adapt the error message accordingly.

**Comment by jancborchardt** [comment]
@sushidave I would say for iOS we should ideally have a dedicated message. Like

> **This app does not work on iOS yet**
> WebRTC support is in development by the vendor

Because people tend to not read the README or manual. :) We should have everything like that directly in the software.

@sushidave would you like to contribute that as a pull request?

**Comment by sushidave** [comment]
@jancborchardt Excellent idea to show a message inside the app! I'd like to contribute a pull request but I'd need more programming skills... Is there someone who can do it?

What if the README/manual/app summary we mention at least that the app works with selected browsers and platforms only? This would manage users' expectations, it's for the sake of better transparency and we would also cover those who read the app's summary before activating the app.

**Comment by sushidave** [comment]
#209

**Comment by nickvergessen** [comment]
@tobiasKaminsky are you using Firefox?
If so #221 should fix it. Would be nice if you can test that.

**Comment by tobiasKaminsky** [comment]
@nickvergessen yes Firefox.
Do I have to build the app somehow? Or can I just copy it to my app directory? (sorry...I am just a simple android dev :smile:  )

**Comment by nickvergessen** [comment]
Use the nextcloud appstore or download the tar.gz from the releases page

**Comment by tobiasKaminsky** [comment]
So I now have spreed video chat app 1.2.0 installed, but it the same.
"Fehler beim Zugriff auf Mikrofon & Kamera
The object can not be found here."
But I have enabled both in site settings (and it is working with local "cheese" webcam app.

**Comment by nickvergessen** [comment]
You have no audio card? 😱

**Comment by tobiasKaminsky** [comment]
Of course I have ;-)
Gentoo Linux, pulseaudio as sound server
But I was playing a stream with VLC while testing with chromium.

**Comment by Schroeffu** [comment]
I have the same problem with Linux Mint Firefox+Chromium.
- Firefox is not asking for access and says: "The object can not be found here."
- Chromium is asking for access for the webcam, there i can say yes, the light goes on, but the error message appears and light goes off: "Failed to execute 'createMediaStreamSource' on 'BaseAudioContext': MediaStream has no audio track".

**Comment by blizzz** [comment]
I experience the same problem, since yesterday. Also on Firefox, Camera works on other applications. On Antergos (Arch based).

**Comment by blizzz** [comment]
From the browser log:

```
11:25:00.365 Access to microphone & camera failed MediaStreamError { 
    name: "NotFoundError",
    message: "The object can not be found here.", 
    constraint: "", 
    stack: "" 
} 1 webrtc.js:276:4
```

**Comment by nickvergessen** [comment]
Which FF version?

**Comment by blizzz** [comment]
52.0.1

**Comment by blizzz** [comment]
[This demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/) works here  however

**Comment by blizzz** [comment]
Bollocks. Somehow my sound card profile was switched to _Analog Stereo Output_. Setting it to  _Analog Stereo Duplex_  makes it work. Perhaps there is a way to catch it more nicely, e.g. by trying to identify what the issue is? → "Yo, Bro, your cam is here, but do something about your Mic."

**Comment by kas70** [comment]
I can confirm this problem on Firefox 53.0 (Linux) and Video Calls version 1.2.0. Everything works fine with chromium.

**Comment by funkytraffic** [comment]
"Error while accessing microphone & camera" can be caused if another app locks them by using them. 

E.g. you cannot call from one to another on the same OS.

**Comment by atkulp** [comment]
Since mic/camera access is only supported on secure connections, you should also check the current scheme to give an error for that if appropriate.  I'm running a test instance over HTTP at the moment and couldn't figure out why mic didn't work until I checked the console.  Easy thing to check!

**Comment by nickvergessen** [comment]
So connecting without camera and/or mic will be handled in #512

So this here boils down to ask the user to check if another program/tab/window is using the camera already.
