### ISSUE TITLE
Add "copy link" to the '...' menu on the room list

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1558]
It happens to me now already multiple time:

1. I created a room for a group chat/call. I need to send the link to an additional attendee. I always go to talk click the '...' menu and look for the link before realizing that I have to join the room to copy the link from the right hand sidebar.

2. Be in a ongoing call and someone asks where the meeting later today takes place. Now I have to join the other room in a separate window/tab just to copy the link from the right hand sidebar. Being able to get it directly from the '...' menu of the room list without moving to a different window/tab would be so much easier and more intuitive.

**Comment by nickvergessen** [comment]
You can right click on a room in the sidebar and "Adresse des Links kopieren" just fine in Chrome and same for Firefox. Sure we could readd the clipboard thing to that, but I'm not really convinced it's needed?

**Comment by nickvergessen** [comment]
cc @jancborchardt

**Comment by schiessle** [comment]
indeed, this would work. Never thought of it. But I think that's to "technical" you can not expect that normal people come up with it, if not even I considered it.... let's see what Jan says

**Comment by jancborchardt** [comment]
Good point. I mean, initially we did have the whole sharing flow in the menu (before we had the sidebar).

It definitely makes sense to have a quick way to copy the link without needing to go all the way inside the conversation. An entry "Copy link" below "Add to favorites" in the menu would be good.

If possible: If the conversation is not shared yet, clicking "Copy link" could share it with default settings (no password protection) and copy it.

**Comment by nickvergessen** [comment]
> If possible: If the conversation is not shared yet, clicking "Copy link" could share it with default settings (no password protection) and copy it.

Expect the unexpected, hu? So if someone copies the link to an internal conversation it automatically gets public and all the confidential chat is leaked.

**Comment by jancborchardt** [comment]
Right, might be a bit aggressive there (although hash-link does not equal "public" ;).

Then let’s just go with displaying a "Copy link" entry below "Add to favorite" if a conversation has a shared link.
