### ISSUE TITLE
Feature Request: Inline Photos

### ISSUE THREAD

**Issue by tablador** [nextcloud/spreed#1560]
It would be nice, when on a phone for example, to be able to take a picture/video or select one from one's library, and send it to the chat window so that it is part of the conversation.

**Comment by nickvergessen** [comment]
File upload into the chat is handled in #1129

**Comment by tablador** [comment]
Not sure if this is still monitored, but is this the wrong place to file requests for the Nextcloud Talk app, which appears to be separate from Chat? I use talk because there is a nice app for it that works well as a messaging app on my phone.
