### ISSUE TITLE
/commands are not discoverable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1563]
* The empty chat input should state something about it
* We should have some thing like an intro to commands

This should of course only happen if there have commands been set up, or we add some default commands for Talk

**Comment by nickvergessen** [comment]
Commands are deprecated in favor of webhook bots:

---

Webhook based bots are available in the upcoming Nextcloud 27.1 with Talk 17.1
Preview versions of both are already available, detailed documentation can be found at https://nextcloud-talk.readthedocs.io/en/latest/bots/

Please let us know if you need any help with the API or have any questions on the usage

**Comment by ShapeShifter499** [comment]
@nickvergessen do I understand this will not change?   I am looking to replicate the feature in Telegram where a bot can display all of it's commands inside of the context menu, a popup menu next to chat inputs. See screenshot.

<img width="678" height="227" alt="Image" src="https://github.com/user-attachments/assets/e15c8a98-ed68-4782-a60b-99a53e0df1c1" />

**Comment by ShapeShifter499** [comment]
Maybe it could be implicated as a feature when registering a bot, allow bots to send a list of command they'd accept.

php occ talk:bot:install --feature webhook --feature response --feature reaction --feature commands

Then a bot account can push the list of commands to nextcloud, which gets stored with the bot account. Just as an idea.
