### ISSUE TITLE
UX when other person leaves

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#157]
Currently we have a 30 second (?) timeout until the app actually realizes the other person left the room. Until then there’s a black screen without feedback.

How can we improve this? Send an explicit message that the other person left when they closed the tab for example? Or instead of black screen show the avatar and name below, maybe with explanatory message that there are connection problems (whcih could be the case too, right?)

cc @Ivansss @nickvergessen @LukasReschke

**Comment by nickvergessen** [comment]
Maybe the loading spinner together with "Connection problem"?

**Comment by jancborchardt** [comment]
The thing is that when the person actually left, it’s not a connection problem. If the other person closes the tab, the app could send a specific signal, no?
