### ISSUE TITLE
Add voice messages

### ISSUE THREAD

**Issue by makayabou** [nextcloud/spreed#1576]
I would like to send voice messages over Nextcloud Talk
By the way, thanks a lot for Nextcloud and Nextcloud Talk, it's amazing.

**Comment by Dubidubiduu** [comment]
This would also make nextcloud/talk much more interesting for everyone collaborating without an root-server/the possibility to install a turn-server.

**Comment by l4b4r4b4b4** [comment]
Although having set and operating a hi-end signaling server for the nextcloud talk app, we would still highly appreciate this feature, since its the most time efficient way to drop a quick message :)

**Comment by cgman7** [comment]
when this feature will be added?!!
we will love it!!

**Comment by SmartLiving-Rocks** [comment]
Yes! That would be a huge improvement! It is a more natural way to communicate! But anyways - you have done a great job already! Thanks for your work! Thank you

**Comment by nickvergessen** [comment]
Fixed via nextcloud/spreed#5616 + nextcloud/spreed#5742 + nextcloud/spreed#5741 + nextcloud/spreed#5669 + nextcloud/spreed#5610
