### ISSUE TITLE
Shared file not immediately visible to remote user

### ISSUE THREAD

**Issue by ccandreva** [nextcloud/spreed#1589]
## Steps to reproduce
1.Use the '+' button to share a file to a chat.
2.
3.

### Expected behaviour
Tell us what should happen
The other user should see the file that was shared.

### Actual behaviour
Tell us what happens instead
The other users sees "<user>  shared a file which is no longer available"
Reloading the page, or clicking to another Nextcloud page and back, shows the file.

## Browser
Linux Firefox 65.0.1 , 
Windows Chrome 72

**Microphone available:** no

**Camera available:** no

**Operating system:** Windows/Fedora...

**Browser name:** Firefox/Chrome/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: RedHat 7

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.27

**Nextcloud Version:** (see admin page) 15.0.4

**List of activated apps:**

<details>
```Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - audioplayer: 2.6.0
  - bookmarks: 0.16.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.5
  - files_fulltextsearch_tesseract: 1.2.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.4
  - fulltextsearch_elasticsearch: 1.2.3
  - gallery: 18.2.0
  - groupfolders: 2.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: true
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
[config-list.txt](https://github.com/nextcloud/spreed/files/2911445/config-list.txt)
[config-list.txt](https://github.com/nextcloud/spreed/files/2911446/config-list.txt)
[nextcloud.log.gz](https://github.com/nextcloud/spreed/files/2911450/nextcloud.log.gz)

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Works fine here, and I can also not reproduce this technically, as the message is only sent after the share was created :thinking:

**Comment by Slug-V** [comment]
I saw this behavior just now in my server.
This server is using mirrored WD Red 2.5Inch 1TB, so I think this is caused by poor write performance.

## Spreed app

**Spreed app version:** 5.0.3

**Custom TURN server configured:** no

**Custom STUN server configured:** no, default with `stun.nextcloud.com:443`

## Server configuration

**Operating system:** Gentoo(`=sys-kernel/gentoo-sources-4.19.27-r1`) with ZoL(`=sys-fs/zfs-0.7.12`) on all filesystem includes rootfs

**Web server:** H2O(`=www-servers/h2o-2.2.5`)

**Database:** MariaDB(`=dev-db/mariadb-10.2.22-r1`)

**PHP version:** 7.2.16(`=dev-lang/php-7.2.16`)

**Nextcloud Version:** 15.0.7(`=www-apps/nextcloud-15.0.7`)

**List of activated apps:**

<details>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - announcementcenter: 3.4.1
  - calendar: 1.6.5
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.1
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - keeweb: 0.5.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.6.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.3
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.1.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

Disabled:
  - admin_audit
  - files_external
  - user_ldap
```
</details>
