### ISSUE TITLE
Voice/Camera access denied on Firefox

### ISSUE THREAD

**Issue by ThePfaffanater** [nextcloud/spreed#1595]
## Steps to reproduce
1. Create a call
2. Give site permission to use camera and microphone
3. Join that said call

(I have to manually give it the permission in the "show more" window since it doesn't not trigger the prompt. Discord works as well. Other people are able to use their microphones on this server) 

![freenas-talk](https://user-images.githubusercontent.com/16065962/53697262-b1a9eb00-3dc7-11e9-8391-92a37a2795b7.png)

### Expected behavior
Voice and Camera are allowed and you can talk with others hearing you

### Actual behavior
It provides the message that voice and camera access were denied. 

## Browser
**Microphone available:** Yes
**Camera available:** Yes
**Operating system:** Windows
**Browser name:** Firefox
**Browser version:** 65.0.2 
### Browser log
<details>
```
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More] jfo6y4xk
CONNECTED merged.js:23454:4
Access to microphone & camera failed 
MediaStreamError
​
constraint: ""
​
message: "The request is not allowed by the user agent or the platform in the current context."
​
name: "NotAllowedError"
​
stack: ""
​
<prototype>: MediaStreamErrorPrototype
​​
constraint: 
​​
message: 
​​
name: 
​​
stack: ""
​​
<get constraint()>: function constraint()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<prototype>: Object { … }

</details>

## Spreed app
**Spreed app version:** 5.0.2
**Custom TURN server configured:** no 
**Custom STUN server configured:** no 


## Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->


**Operating system**: FreeBSD

**Web server:** Nginx

**Database:** MySQL

**PHP version:**

**Nextcloud Version:** 15.0.5

**List of activated apps:**
<details>
```Accessibility 
Activities for shared file downloads, visible to all admins 
Activity
Antivirus for files 
AppOrder 
Audio Player 
Auditing / Logging
Auto Mail Accounts
 Automated PDF conversion 
Calendar 
Checksum
Circles
Collaborative tags 
Comments
Contacts
Dashboard
Data Request 
Deck
Deleted files 
Draw.io 
DropIt
End-to-End Encryption
Everyone Group
External sites
External storage support
Federation
File sharing
Files Right Click
First run wizard
Gallery
Mail
Metadata
Monitoring
Notes
Notifications
Password policy
PDF viewer
Quota warning
Ransomware protection
Registration
Share by mail
Social sharing via email
Support
Talk
Text editor
Theming
Two Factor TOTP Provider
Two Factor U2F
Two-Factor Authentication via Nextcloud notification
Two-Factor Gateway
Unsplash
Update notification
Usage survey
Video player 
```
</details>

<details>
```

```
</details>

### Server log (data/nextcloud.log)
<details>

```
</details>

**Comment by nickvergessen** [comment]
The Problem is, that your server does not use a secure connection.
If you move it to https, the permission prompt will show up similar to the other sites you mentioned.

**Comment by ThePfaffanater** [comment]
I do use https but it is self signed atm so I have to add a manual exception. Will the same thing occur? Also my friend on a different browser did not have this problem. I believe that browser was chromium based.

**Comment by Fuseteam** [comment]
i believe i have the same issue
