### ISSUE TITLE
Should also work when person only has microphone and no cam

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#160]
In many cases people don’t have a webcam but only microphone (or headset), especially on desktop computers. Instead of not working at all, we should handle this gracefully:

- Still ask for permission to use the microphone
- Show the avatar placeholder for yourself and for the others (currently a black video view is shown)
- Maybe give some feedback about the missing webcam in case it’s not working or you forgot you have one

cc @fancycode @Ivansss @LukasReschke can we make that work?

**Comment by fancycode** [comment]
See here for an example on how we handle something similar with spreed-webrtc (we do a transparent graceful fallback to the avaliable device):
https://github.com/strukturag/spreed-webrtc/pull/395

**Comment by jancborchardt** [comment]
Killer work here @Ivansss :tada: :)
