### ISSUE TITLE
Config settings for dial-in numbers

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#1605]
Dial-in numbers for the SIP bridge mode need to be configurable in the Nextcloud's Talk admin section.
Ideally multiple numbers can be configured to have different numbers for different souce countries. 

The countries shall be selectable from a pre-defined list.

**Comment by nickvergessen** [comment]
I would (for now) go for a free text input field where you can enter whatever you want. Because I think it's unnecessary to implement phone number validation and providing a country list which is unnecessary as the admin knows the few countries they have a phone number in.
