### ISSUE TITLE
Experience when testing »Share link«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#161]
1. Choose a person from the dropdown
2. Their face & name is displayed in the sidebar entry and the emptycontent view
3. Find »Share link« in the menu and click it.
4. Decide you don’t want it anymore and delete the link again

Now you would expect it to go back to step 2, seeing their face & name in the sidebar entry in the emptycontent view. Instead you see the the »Contacts« icon and »Waiting for others to join the room«. This gives the impression that others except the person you chose can join the room still, which is wrong.

I know this is because we promote the room to a group room at the point of sharing a link. But if the link is removed from that 1on1 room, it should be demoted to a 1on1 call again, right? cc @Ivansss @nickvergessen

**Comment by nickvergessen** [comment]
Downgrading to a one2one room is currently not possible. Same issue when you add a person to a one2one call and one of them leaves again. The problem is you could have 2 one2one rooms now, which causes troubles. Therefor we don't do this.

**Comment by jancborchardt** [comment]
Yeah, true …
