### ISSUE TITLE
Proxy miss-configuration causes talk to fail

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/spreed#1610]
If talk users are behind a proxy, and the socks host is configured in the browser when no socks proxy is installed, the talk client fails to connect.

This happens "accidentally" when someone sets the option "Use this proxy server for all protocols"

This can be seen as a user mistake, but it is hard to enforce for all users. Therefore it would be great if talk could somehow identify and then override this miss-configuration.
![2019-03-13_19-57](https://user-images.githubusercontent.com/8102905/54307918-2ac9ef00-45cd-11e9-8056-3241bca8fb92.png)
![2019-03-13_19-58](https://user-images.githubusercontent.com/8102905/54307936-31586680-45cd-11e9-8655-3642bb200cde.png)

**Comment by nickvergessen** [comment]
after some thinking and checking I don't think there is anything we can do here. We in talk can not even access proxy information configured in the browser. Of course it would also be bad, if a website could even overwrite your proxy configuration, as this would basically make all "anonymousing proxies" useless. So the only thing we could do is in case a conneciton completly fails tell the user to check if they have an internet connection, can ping the turn/stun server, etc. But at that point there are sooo many things that could go wrong, I'm not sure listing them all is useful in any case.

But we can leave this issue open for now, maybe someone has more ideas how we could help the user in this case.

**Comment by nickvergessen** [comment]
Closing as per above
