### ISSUE TITLE
ResourceLocator can not find a web root on several extensions

### ISSUE THREAD

**Issue by Famku** [nextcloud/spreed#1615]
newest nextcloud snap install have issues with spreed

can you please take a look on your site regarding this issue:

https://github.com/nextcloud/nextcloud-snap/issues/902

**Comment by nickvergessen** [comment]
This is a bug within the snap and needs to be solved there.

**Comment by sireebob** [comment]
@nickvergessen after reading the recent comments in the issue referenced by the OP, do you still believe this is a snap bug?

**Comment by nickvergessen** [comment]
It is at least not a bug in talk, because we do everything like it should be. So either its a bug in snap, or in the server repo how it loads apps

**Comment by the-sane** [comment]
FYI:  It has been determined that these errors are the result of a problem in the server: https://github.com/nextcloud/server/issues/13556
