### ISSUE TITLE
Remove call notification again if the person who initiated the call left the room

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#162]
I just logged in to my Nextcloud and saw several notifications like "User A invited you to a call", "User B invited you to a call",... But it is not possible to say if this is still a up-to-date invitation or if it is already a few days old and no longer relevant.

@nickvergessen mentioned at some point that we could remove the notification again if the person who initiated the call left the room. Is this still a option? Additionally it could make sense to show a date (or like the desktop client something like "X hours ago"), so that you get a feeling if this is still a valid notification or not.

**Comment by jancborchardt** [comment]
> we could remove the notification again if the person who initiated the call left the room.

This seems like a good mechanic, yep!

Showing the date for notifications would be relevant for any notification soon, right? Like mentioning, receiving shares etc. We need to have that in the Notifications app proper.

**Comment by nickvergessen** [comment]
Yeah, please reopen in the notifications app

**Comment by jancborchardt** [comment]
> we could remove the notification again if the person who initiated the call left the room.

@nickvergessen however that part we should fix here. :)

**Comment by nickvergessen** [comment]
Leaving a room deletes it when it was a one2one room and then notifications are not displayed anymore either.

**Comment by jancborchardt** [comment]
@nickvergessen I guess with »leaving the room« we meant that the person is not in the room anymore, like switched to another one or another app or closed the tab. Not that they clicked »Leave room«.

**Comment by nickvergessen** [comment]
Well this totally defeats the purpose of the notifications at all.
This was discussed differently in the office and is what it is now.

**Comment by jancborchardt** [comment]
@nickvergessen huh ok, I thought that’s what @schiessle meant.

(Please never ever lock an issue without a really good reason. Not sure what it achieves in this case. ;)
