### ISSUE TITLE
Sometimes issues with shared rooms not working

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#164]
Check this out:
![sharedcall](https://cloud.githubusercontent.com/assets/925062/20835278/f999bb94-b899-11e6-8503-e47412377aa6.png)

No idea where the issue is, as it’s all localhost. Should it not simply work? (And _if_ there’s really an issue, we should give better feedback.)

**Comment by Ivansss** [comment]
@jancborchardt Could you give some more info about this issue? Is still reproducible for you?
