### ISSUE TITLE
Add an UI option for "read-only" conversations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1647]
With #1640 conversations can be marked read-only.
This is currently only available via the APIs, since it was needed as a base for #1616 

We should add an option for moderators to allow toggling the state in the callinfoview?
Maybe a (un)lock-icon next  to the conversation name or the copy-link/make public/private checkbox?

Also the change event somehow does not toggle the editable-state of the chat-input.

@nextcloud/designers opinions?

**Comment by skjnldsv** [comment]
We should be careful not to make the user confused about the password protection and the locking state of the conversation. For read-only I'm not sure I would put an icon. Putting everything without any interaction is pretty self-explanatory :thinking: 
Though the title of the conversation could have `(read-only)` in it ?

**Comment by nickvergessen** [comment]
No, we may use another icon maybe, and its pretty obvious when its locked, as chat input and call button are disabled. Also a system message is disabled and you can revert it easily.

**Comment by jancborchardt** [comment]
Yep – I also think an icon is not needed here and would possibly be confusing. Appending (read-only) to the title is also a possibility, not sure if needed though.

> and its pretty obvious when its locked, as chat input and call button are disabled.

@nickvergessen exactly. :+1:  In addition I’d say the chat input placeholder should say "Conversation is read-only for you" so it’s 100% obvious (or something similar if you find something shorter so it also works better on mobile).

**Comment by Supergamerx3000** [comment]
how can i use this function now?
can I make channels read-only via a command?

**Comment by nickvergessen** [comment]
No, via the API or directly in the database

**Comment by PVince81** [comment]
seems this discussion is old and might refer to an older version of the UI as I didn't find any "callinfoview".

I agree that it doesn't need to be a clickable icon as this kind of action is not that frequent.

Here's a proposal based on the master version of Talk:

1) for moderators only, add lock/unlock action in the three dots menu behind the conversation name on the left sidebar
![image](https://user-images.githubusercontent.com/277525/94912026-53fbea00-04a7-11eb-8d5c-fe011c804b26.png)

2) when locked, the action says "Unlock conversation" (also moderators only)

3) when locked, the conversation title has "(read-only)" appended in a faded color:
   - in the left conversation list
   - in the top of the sidebar panel on the right

4) New message form appears but is disabled with placeholder "Conversation is read-only"


As I understand the conversation is locked for everyone ? Or can moderators still post messages ?

**Comment by nickvergessen** [comment]
It should go to the top right menu which is the moderation menu.

![Bildschirmfoto von 2020-10-06 15-54-03](https://user-images.githubusercontent.com/213943/95210882-3a7ed900-07ec-11eb-8715-14adb965a210.png)

> As I understand the conversation is locked for everyone ? Or can moderators still post messages ?

No one can.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4331

I noticed that the backend still allows the following:
- adding participants
- promote participants
- rename conversation
- lobby operations

I guess it's ok to leave this visible then. Makes it possible for someone to prepare a room before letting people rush in it and start chatting.

**Comment by nickvergessen** [comment]
Yeah, also renaming to "... (Archive)" should be possible when locked, so that's okay

**Comment by PVince81** [comment]
I have implemented the feature in https://github.com/nextcloud/spreed/pull/4331.

The only missing bit is the "read-only" indicator.
I gave this a thought and considering that one can still rename conversations, as an admin I'd want to be able to write whatever I want there: "(read-only)" or "(archived)" or "(locked)". So if we force a suffix then the room name will become "Past thing (archived) (read-only)" which is a bit redundant.
In that regard I'd prefer not adding the text "read-only" in the conversation name.

We can still explore the idea of adding a non-clickable lock icon:
1. in the left sidebar
<img width="289" alt="image" src="https://user-images.githubusercontent.com/277525/95506740-9a25e180-09b0-11eb-803b-8800c9b82e85.png">

2. behind or after the room name in the right sidebar:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/277525/95507075-29cb9000-09b1-11eb-98b4-38ea3a668a9a.png">

@jancborchardt @skjnldsv

**Comment by nickvergessen** [comment]
> In that regard I'd prefer not adding the text "read-only" in the conversation name.

yeah, that's what I ment. Should be done manually, and that's why being able to rename manually afterwards is okay (and even needed)

**Comment by nickvergessen** [comment]
Don't really like the "lock" on the conversation icon, as that takes away the info if the conversation is still publicly shared, but we need a new solution for that anyway when conversation-images arrive (or we just don't care in that case)

**Comment by PVince81** [comment]
okay then, I've set the PR https://github.com/nextcloud/spreed/pull/4331 to "To review" without indicators.
these could still be added later if needed

**Comment by DineshRefex** [comment]
Hi, if i lock the conversation, even the modulator can't able to send message for me. but i want to make modulator to send message like broadcast some buddy help me please. how will i met this.

**Comment by nickvergessen** [comment]
You can do that in 25+ by using the chat permission instead

**Comment by DineshRefex** [comment]
> You can do that in 25+ by using the chat permission instead

even if we lock the conversation. will modulator able to send message.

**Comment by nickvergessen** [comment]
You just modify the permissions without locking and then mods can still post
