### ISSUE TITLE
Menu list link behind proxy

### ISSUE THREAD

**Issue by ralfi** [nextcloud/spreed#1671]
Hello nextcloud-talkies,

I am using nc talk behind a reverse proxy (apche 2.4, nc 16 beta-1, nc talk 5.99.10). 

With nc talk app on android evreything works fine but if i try to use nc talk with my browser the link in the menu list - where all other apps appears - fails. The link shows to the reverse proxy address instead to the https address like all other apps.

"Mouse over" shows me for example https://<fqdn>/apps/files or https://<fqdn>/apps/notes and only nc talk shows me https://<fqdn>:<reverse-port>/apps/spreed. This can not work because the reverse-proxy port should not be appears. If i remove this port in another browser window everything is fine and works.

Oh, i forgot - THANKS for this beautiful work...

**Comment by ralfi** [comment]
Could be closed: Setting the correct values for overeriteprotocol and overwritehost in confip.php is the solution. IMHO is this behavior caused by proxy config (see documentation)

**Comment by nickvergessen** [comment]
Glad you found the issue :)
