### ISSUE TITLE
Online status  web and mobil app

### ISSUE THREAD

**Issue by Scofield81** [nextcloud/spreed#1683]
Hello. It would be good if you could see who I would like to talk to online or offline.
And that sent the message, sent it, received it, read 
for example: messenger or whatsapp chat

Online
[Online](https://www.wikihow.com/images/thumb/9/9d/Tell-if-Someone-Is-Online-on-WhatsApp-Step-4.jpg/aid8190983-v4-728px-Tell-if-Someone-Is-Online-on-WhatsApp-Step-4.jpg)

Sent ✔  Received ✔✔  Readed✔✔(two blue colored mark)
[Státus](https://www.hijosdigitales.es/wp-content/uploads/2017/01/enlinea_wasap1.jpg)

**Comment by nickvergessen** [comment]
Online status: #832 
Read indicator: #1012
