### ISSUE TITLE
[notifications] Fatal: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/spreed#1684]
[notifications] Fatal: error:0906D06C:PEM routines:PEM_read_bio:no start line
POST /ocs/v2.php/apps/spreed/api/v1/chat/ii32kaau

Nextcloud 14.0.8.2
ubuntu 18.04.1
postgresql 10.6
apache 2.4.29
php 7.2.15
Talk 5.0.2
Nextcloud Talk (android 9) 3.2.7
notifications 2.2.1
openssl 1.1.0g-2ubuntu4.3
letsencrypt 0.31.0-1+ubuntu18.04.1+certbot+1

I get an error in the logs when I add an account in the nextcloud-talk 3.2.7 (android 9) or send a message to chat or call.

nextcloud.log:
"Error	notifications	error:0906D06C:PEM routines:PEM_read_bio:no start line"
or
"error:0E06D06C:configuration file routines:NCONF_get_string:no value"
or
"error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size"

**Comment by nickvergessen** [comment]
Please post the full lines from the log.

**Comment by lvarnava** [comment]
{"reqId":"xJwyreNcO92VmWWyynQ6","level":4,"time":"2019-04-07T16:54:16+03:00","remoteAddr":"xx.xxx.xxx.xx","user":"username","app":"notifications","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/chat\/ii32kaau","message":"error:0906D06C:PEM routines:PEM_read_bio:no start line","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.6.1"}

**Comment by nickvergessen** [comment]
Ah, actually https://github.com/nextcloud/notifications/issues/298 is the right place.
