### ISSUE TITLE
Adhere to semver

### ISSUE THREAD

**Issue by dvzrv** [nextcloud/spreed#1685]
Please adhere to semver, also for prereleases!
I'm packaging spreed for Arch Linux and just ran into the issue, that this app falsely promotes a fully qualified version, in accordance with semver, but is actually a beta (that only works with nextcloud >= 16.0). For me this now means introducing an epoch to downgrade the package again (which is ugly).

The correct way to tag a beta (or any prerelease version for that matter) would be of the form `<major>.<minor>.<patch>-<prerelease>` ([according to the defined standard](https://semver.org/#spec-item-9)), as this is always < `<major>.<minor>.<patch>`. It would be very awesome, if you could integrate this in your workflow!

For package maintainers it is vital to not be forced to go to all of their upstream websites constantly to check what is actually hidden behind a (seemingly well-defined) semver based git tag, but be able to rely on what semver represents.

**Comment by nickvergessen** [comment]
The last time I tried this, the appstore had a problem with it. It flags them and does not provide them as updates to Nextclouds, which would mean that no one would test the version, if they don't go to the appstore and manually download it, which would at the same time mean no one tests the beta which is somewhat useless too.

I will try it again...

But well I'm not a too big fan of packages for web apps, so I will not put too much effort into it.

**Comment by MorrisJobke** [comment]
Also keep in mind that semver was meant for libraries and not for applications, because in Nextcloud we typically try to keep backwards compatibility where it's possible to guarantee it (our public APIs for example).

**Comment by dvzrv** [comment]
> The last time I tried this, the appstore had a problem with it.

If the appstore can't distinguish versions according to semver/calver, then I would consider it a bug of the appstore.
Is there a common interface on how to distinguish between pre-releases and releases in the appstore?

> I will try it again...

Thanks!

> But well I'm not a too big fan of packages for web apps, so I will not put too much effort into it.

I'm also not a too big fan of a multitude of web applications on a single host, that all run as the same user, have no proper privilege separation and can install whatever they want. However, I try to integrate these applications securely (e.g. sandbox them, root-only file permissions for all non-transient files) and separate them from one another (e.g. separate users) on a (Linux) host.
Question of perspective I guess :-)

> Also keep in mind that semver was meant for libraries and not for applications, because in Nextcloud we typically try to keep backwards compatibility where it's possible to guarantee it (our public APIs for example).

This is somewhat of a moot point, as my issue is about applying semver correctly, not whether it should be used or not.
By introducing a major change (e.g. compatibility only with the next major version of nextcloud), without incrementing the major version of the app, it makes the versioning very confusing to follow and not coherent (at least from an outsider's perspective).
In general I would assume, that if semver is used, it's best to stick to the best practice of using the definition of how semver is applied, instead of building a unicorn system that is "kind of semver" (in regards to the aforementioned problems with the appstore). Otherwise there needs to be a clearly specified best practice on how (prerelease) versioning is done within the nextcloud app ecosystem.

Last, but not least: Please don't take my request as offense. I greatly appreciate, what you are doing here and have been a happy nextcloud user from the start (but of a packaged version ;-) )!

**Comment by nickvergessen** [comment]
> Is there a common interface on how to distinguish between pre-releases and releases in the appstore?

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml
> must be a semantic version without build metadata, e.g. 9.0.1 or 9.1.0-alpha.1

That is exactly the problem. So if it is a pre-release it is detected as such and seen as an "unstable" version. Unstable versions are not delivered to nextclouds when they ask for an update.

**Comment by nickvergessen** [comment]
Just tested again and it's still the same issue.

My proposal is at https://github.com/nextcloud/server/pull/14994

**Comment by nickvergessen** [comment]
So we will use full semver in the future, for now I would recommend you ignore 5.99 versions.

Sorry for your inconvenience

**Comment by dvzrv** [comment]
@nickvergessen thanks so much! That's great news! :)

**Comment by dvzrv** [comment]
@nickvergessen sorry to bug you again in this rather undead ticket, but 8.0.0 just got released and it's only compatible with nextcloud server 18 and up (but currently the latest version of the server is 18.0.0RC2).
Maybe you have inside information about an immanent release of nextcloud server 18?

**Comment by nickvergessen** [comment]
RC means it's close to🍿 time mostly.

**Comment by dvzrv** [comment]
> RC means it's close topopcorn time mostly.

However, "close to" is not "after".
I was kind of lucky, that I did a lot of bug reporting on github yesterday in regards to other package additions, otherwise I would have not noticed, that nextcloud-spreed is not compatible with the current stable version of nextcloud-server (and when doing a package release would have broken everyone's setup).
Therefore I don't quite understand, why you released a stable version of nextcloud-spreed, incompatible with the current stable release of nextcloud-server. I thought this exact ticket was created and the communication therein done to prevent exactly that scenario.

**Comment by nickvergessen** [comment]
> Therefore I don't quite understand, why you released a stable version of nextcloud-spreed, incompatible with the current stable release of nextcloud-server.

Because Nextcloud 18 (Nextcloud Hub) was released 2 hours ago and we wanted people to be able to update as soon as it is out. As said before, on our side increasing the major version is a semversion change, it means it has incompatibility with something that worked before, in our case it's the Nextcloud version.
