### ISSUE TITLE
Some participants may not be shown in the participants autocompletion dropdown

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1686]
In the _Participants_ tab the dropdown used by moderators to add new participants to a conversation may not show some of the possible participants to add.

The candidates are got using the [`core/autocomplete/get` endpoint, which by default limits the results to 10](https://github.com/nextcloud/server/blob/55f627d20b6eacb1773381ea4325d2159f9c3103/core/Controller/AutoCompleteController.php#L69). However, this does not take into account which participants are already in the conversation; [the participants already in the conversation are filtered in JavaScript](https://github.com/nextcloud/spreed/blob/b84e4737ad7ea78b6a6b97631ab1d4e6470da63f/js/views/participantview.js#L127) from the 10 received results (because [no explicit limit is given when the endpoint is called](https://github.com/nextcloud/spreed/blob/b84e4737ad7ea78b6a6b97631ab1d4e6470da63f/js/views/participantview.js#L104), so the default limit is used).

Due to this, once a participant is added to a conversation it is no longer shown in the _Add participant_ dropdown, but a different participant not added yet is not shown in its place; depending on the number and user names of the participants in the conversation the dropdown could even be empty.

## Steps to reproduce ##

- Create users _user01_, _user02_, _user03_... to _user12_
- Create a group or public conversation in Talk
- Add _user01_, _user02_... to _user06_ to the conversation
- Show the _Add participant_ dropdown in the _Participants_ tab

### Expected result: ###

_user07_, _user08_... to _user12_ are shown in the dropdown.

### Actual result: ###

_user10_, _user11_ and _user12_ are not shown in the dropdown (_user09_ may not be shown either if you have a _user0_ in your test system); note that _user10_... can still be added by typing their full name in the filter.

**Comment by nickvergessen** [comment]
yeah, maybe we need to switch to a talk specific endpoint instead. But then we duplicate half the work again. Maybe instead we should add context to the autocomplete endpoint. Let me check if this would somehow be possible.

**Comment by nickvergessen** [comment]
> However, this does not take into account which participants are already in the conversation; the participants already in the conversation are filtered in JavaScript from the 10 received results 

The results are filtered out now with #3002 
But the problem remains the same, because the search plugins only register "10" results which are then later on filtered out.

**Comment by mario** [comment]
Can't we just up the limit to 50 or 100 in the web client therefore solving this issue for the 99% of users?

**Comment by nickvergessen** [comment]
Fixed by #3002
