### ISSUE TITLE
Not able to use Talk (Spreed) with nextcloud 16 (even RC1)

### ISSUE THREAD

**Issue by ynjo** [nextcloud/spreed#1713]
### Steps to reproduce
Enable the Talk app (even the last 6.0.0-rc.2)

### Expected behaviour
Server and apps normally working

### Actual behaviour
The server doesn't work at all I got the blue rectangle box with an error message and the request to ask the administrator.
In the NC logs I get this one:
[index] Error: TypeError: Argument 10 passed to OCA\Spreed\Room::__construct() must be of the type string, null given, called in /var/www/nextcloud/apps/spreed/lib/Manager.php on line 124 at <<closure>>

 0. /var/www/nextcloud/apps/spreed/lib/Manager.php line 124
    OCA\Spreed\Room->__construct(OCA\Spreed\Manager {}, OC\DB\Connection {}, OC\Security\SecureRandom {}, Symfony\Componen ... {}, OC\AppFramework\Utility\TimeFactory {}, OC\Security\Hasher {}, 5, 3, 0, null, "", "", 0, null, null, null, "", "")
 1. /var/www/nextcloud/apps/spreed/lib/Manager.php line 163
    OCA\Spreed\Manager->createRoomObject({id: "5",name: " ... "})
 2. /var/www/nextcloud/apps/spreed/lib/Share/RoomShareProvider.php line 757
    OCA\Spreed\Manager->getRoomsForParticipant("marco")
 3. /var/www/nextcloud/lib/private/Share20/Manager.php line 1144
    OCA\Spreed\Share\RoomShareProvider->getSharedWith("marco", 10, null, -1, 0)
 4. /var/www/nextcloud/apps/files_sharing/lib/MountProvider.php line 79
    OC\Share20\Manager->getSharedWith("marco", 10, null, -1)
 5. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php line 113
    OCA\Files_Sharing\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
 6. /var/www/nextcloud/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
 7. /var/www/nextcloud/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("marco")
 8. /var/www/nextcloud/lib/private/legacy/util.php line 308
    OC\Files\Filesystem::init("marco", "/marco/files")
 9. /var/www/nextcloud/lib/base.php line 974
    OC_Util::setupFS()
10. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/theming/js/theming?v=70
from 127.0.0.1 by marco at 2019-04-11T20:18:42+00:00

## Server configuration detail

**Operating system:** Linux 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64

**Webserver:** Apache/2.4.34 (Ubuntu) (fpm-fcgi)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.15-0ubuntu0.18.10.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.0 RC 1 - 16.0.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.0
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.0
 - apporder: 0.6.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - checksum: 0.4.2
 - circles: 0.17.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.0
 - dav: 1.9.2
 - drop_account: 0.1.0
 - extract: 1.0.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 2.0.4
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.9.4
 - nextcloud_announcements: 1.5.0
 - notes: 2.5.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.4.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - radio: 0.6.4
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - richdocuments: 3.2.4
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - social: 0.1.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - terms_of_service: 1.2.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - user_usage_report: 1.1.1
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - audioplayer
 - dashboard
 - data_request
 - deck
 - drawio
 - encryption
 - files_accesscontrol
 - files_automatedtagging
 - files_markdown
 - flowupload
 - gpxpod
 - impersonate
 - mail
 - mindmaps
 - occweb
 - onlyoffice
 - quicknotes
 - ransomware_detection
 - socialsharing_email
 - socialsharing_facebook
 - socialsharing_twitter
 - spreed
 - tasks
 - theming_customcss
 - user_external
 - user_ldap
 - w2g2

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "1": "192.168.0.15",
        "3": "nubotec.sytes.net"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nubotec.sytes.net",
    "dbtype": "mysql",
    "version": "16.0.0.6",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "beta",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "radio",
        "apporder"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** a local owncloud and a remote nextcloud, both via WebDAV

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** Kubutntu 18.10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
Can you try applying the change from https://github.com/nextcloud/spreed/pull/1716/files
Thanks

**Comment by ynjo** [comment]
Nope, same behavior and same error in NC log.
Ty!

**Comment by nickvergessen** [comment]
Can you share the database entry of oc_talk_rooms with the id 5? 🤔

**Comment by ynjo** [comment]
mysql> select * from oc_talk_rooms where id=5;
+----+------+-------+------+----------+--------------+---------------+---------------+--------------+-------------+-----------+-----------+
| id | name | token | type | password | active_since | active_guests | last_activity | last_message | object_type | object_id | read_only |
+----+------+-------+------+----------+--------------+---------------+---------------+--------------+-------------+-----------+-----------+
|  5 |      | NULL  |    3 |          | NULL         |             0 | NULL          |            0 |             |           |         0 |
+----+------+-------+------+----------+--------------+---------------+---------------+--------------+-------------+-----------+-----------+
1 row in set (0.00 sec)

**Comment by nickvergessen** [comment]
Not sure where this entry comes from, but I think its save to delete.

**Comment by ynjo** [comment]
> Not sure where this entry comes from,
Imagine if I could know :-D

> but I think its save to delete.
yeah, and the row with id=4 was the same.
Deleted both, the problem looks solved.

Thank you very much!
