### ISSUE TITLE
Connect all files shared in a chat to the project(s) associated to the chat

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#1725]
Sharing files in chat is great, but sometimes you want to see all of them. Perhaps this is where projects can come in - create a project and connect them all.

If you start with a chat and share a file in it, and there is no project associated to the chat, a new project could be created and the file and chat added to it.

This is a simple way to create and handle projects - have a chat central to it, share files to the chat and they're added to the project.

The nice thing is that, just like the file is shared with participants of the chat, so is the Project itself.

Question: should every file associated with a project be shared in the chat? I say not, people can associate files to a project which aren't shared with other members. So I would NOT go that far. So the Project view is different for all members, but AT LEAST includes all files shared in the chat, PLUS all files they shared with each other.

Related to https://github.com/nextcloud/spreed/issues/1577 - and a possible solution to it :smile:

**Comment by nickvergessen** [comment]
Lets keep the discussion in one place for now: #1577
