### ISSUE TITLE
Mobil native keyboard opens when opening chat

### ISSUE THREAD

**Issue by JLueke** [nextcloud/spreed#1726]
## Steps to reproduce
1. Open the chat on a mobile phone
2. Open a chat room

### Expected behaviour
I can see the last few messages of the chat room.

### Actual behaviour
The native keyboard opens.
I can only the a portion of the messages so I first need to close the keyboard.
And if you open another room after closing the keyboard, the keyboard will be opened again.

## Browser
**Operating system:** Android 8

**Browser name:** Chrome

**Browser version:** 73

**Comment by nickvergessen** [comment]
Yeah we are focusing the input.
Maybe we shouldn't do this on mobile?

**Comment by JLueke** [comment]
Would be great because currently the native keyboard takes up almost half of the screens height (at least on my mobile phone). Thus leaving a chat history window with a height where only 5 lines of the message can be displayed.

**Comment by nickvergessen** [comment]
@nextcloud/javascript whats the best way to detect a mobile browser in our JS and not run the following line:
https://github.com/nextcloud/spreed/blob/3e3926bebdabf64709d957527ea010f57530df55/js/views/chatview.js#L252

**Comment by skjnldsv** [comment]
What is the issue about opening the keyboard?
The missing space?
If so detecting the height size and having a threshold might be relevant :)

**Comment by nickvergessen** [comment]
Yes, it covers 50% of the screen and you can only read few chat messages instead of reading more log before

**Comment by skjnldsv** [comment]
Let's only focus if height is over 768?

**Comment by nickvergessen** [comment]
"Wizards… do your magic" 🧙‍♂️

**Comment by skjnldsv** [comment]
```js
if (window.outerHeight > 768) {
    $message.blur().focus(); 
}
```
