### ISSUE TITLE
Prettify appstore entry

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#173]
1. Screenshot
2. More description – ask @jospoortvliet if you need some boilerplate text :)

Ref https://apps.nextcloud.com/apps/spreed

**Comment by jancborchardt** [comment]
@jospoortvliet seems to have the best screenshot, which is published with the Nextcloud 11 release too. ;) Jos, I can’t find it in the screenshots repo.

**Comment by jancborchardt** [comment]
Aaah right in the docs folder :) We should rename that to screenshots probably. That’s what it’s called in Mail.

**Comment by Ivansss** [comment]
Screenshots were already added and proper description was added in #189

**Comment by jancborchardt** [comment]
@Ivansss I actually added that to the readme yesterday directly to master so I could send a proper tweet ;)

**Comment by Ivansss** [comment]
The description won't be changed in the App Store until the next release though

**Comment by jancborchardt** [comment]
I know, but I tweeted the repo link to the readme because I want people to get involved. ;)

Retweet this by the way: https://twitter.com/jancborchardt/status/809098505105080320
