### ISSUE TITLE
Chat background turns black on screenshare

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1736]
## Steps to reproduce
1. As user1 start a call
2. As user2 join the call and leave it, but stay in the chat
3. As user1 share your screen

### Expected behaviour
user2 should just be left in it's state

### Actual behaviour
chat background goes black :eyes:

**Comment by LeoSum8** [comment]
I see the same behavior on two different nextcloud instances. Both are running Nextcloud 15.0.7 and Talk 5.03 with additional TURN Server set up.

Additionally to the background going black, the video and audio transmission stop. Once screensharing is canceled, audio/video goes back to normal.

The error started occurring after the latest updates (either Nextcloud to 15.0.7 or Talk to 5.03) which unfortunately happened at the same time, so I cannot pinpoint which one is the bad guy.

**Comment by danxuliu** [comment]
@LeoSum8 
> The error started occurring after the latest updates (either Nextcloud to 15.0.7 or Talk to 5.03) which unfortunately happened at the same time, so I cannot pinpoint which one is the bad guy.

Probably Talk 5.0.3 ;-) The interrupted audio and video when the screen is shared should be fixed by #1746 and, thus, in Talk 5.0.4.

Thanks for the information :-)

**Comment by LeoSum8** [comment]
This is nice to hear, thank you! I was already afraid of having to wait until the next major release due to the assigned milestone.
