### ISSUE TITLE
Improvement: make single emojis bigger

### ISSUE THREAD

**Issue by FramboisePi** [nextcloud/spreed#1744]
Hello,

When we send a message with only one emoji, it is really small. In my opinion it would be better if it was bigger. 
Sending emojis is indeed a way to express sentiments, they can be used instead of sentences and can be important.

**Describe the solution you'd like**
I would suggest to make bigger messages with a small number of emojis and no text.

On macOS or iOS Messages, if there is one, two or three emojis in a message there are bigger and not on a blue background.
On the contrary, if the message contains text or more than 3 emojis, it looks like a classic message.
<img width="165" alt="Capture d’écran 2019-04-21 à 11 42 52" src="https://user-images.githubusercontent.com/25133304/56470004-42ed2380-6441-11e9-9952-8e3afe646f35.png">

Currently it looks like this on Talk:
<img width="89" alt="Capture d’écran 2019-04-21 à 11 43 56" src="https://user-images.githubusercontent.com/25133304/56470006-4aacc800-6441-11e9-9441-b4a27165e1a6.png">

**Comment by nickvergessen** [comment]
In the android app this is at least already the case, but yeah its missing on web atleast

**Comment by FramboisePi** [comment]
I am really happy to heard it will be improved. 

This issue may not be the best place for that, but I want to thank you for all the work on Nextcloud. It is a really great tool.

**Comment by jospoortvliet** [comment]
> I am really happy to heard it will be improved.
> 
> This issue may not be the best place for that, but I want to thank you for all the work on Nextcloud. It is a really great tool.

ANY place is a great place to thank us! We appreciate the kind words, really.
