### ISSUE TITLE
Could not find resource vendor

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/spreed#1758]
## Steps to reproduce
1.Update Nextcloud version 16.0.0
2.Update Talk application version 0.10.0-alpha3
3.Start a call

### Expected behaviour
To call an user

### Actual behaviour
No possibility to call an user

## Browser
Firefox 66.03 64Bits
Chrome Version 73.0.3683.103 (Build officiel) (64 bits)
**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) The firefox console log
Source map error: TypeError: NetworkError when attempting to fetch resource. Resource URL: https://my.domain/core/js/dist/main.js?v=d6679cb7-5 Source Map URL: main.js.map[Learn More]

Source map error: TypeError: NetworkError when attempting to fetch resource. Resource URL: https://my.domain/core/js/dist/main.js?v=d6679cb7-5 Source Map URL: main.js.map[Learn More]

XXX Remove peer - Connection closed.

Deprecated call $.tooltip('destroy') has been deprecated and should be removed
tooltip https://my.domain/core/js/dist/main.js?v=d6679cb7-5:504
    setTooltipContainer https://my.domain/js/spreed/merged.js?v=d6679cb7-5:9995
    updateContentsLayout https://my.domain/js/spreed/merged.js?v=d6679cb7-5:18182
    _ https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    m https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    f https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    trigger https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    set https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    set https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    success https://my.domain/js/spreed/merged.js?v=d6679cb7-5:1
    u https://my.domain/core/js/dist/main.js?v=d6679cb7-5:39
    fireWith https://my.domain/core/js/dist/main.js?v=d6679cb7-5:39
    k https://my.domain/core/js/dist/main.js?v=d6679cb7-5:39
    t https://my.domain/core/js/dist/main.js?v=d6679cb7-5:39
</details>

## Spreed app

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes


## Server configuration

**Operating system**: Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64

**Web server:** Apache

**Database:** MariaDb

**PHP version:**7.2.13-1+0~20181207100540.13+stretch~1.gbpf57305

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - announcementcenter: 3.5.0
  - apporder: 0.6.0
  - bookmarks: 0.17.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - circles: 0.17.2
  - cloud_federation_api: 0.2.0
  - cms_pico: 0.9.8
  - comments: 1.6.0
  - contacts: 3.1.1
  - cospend: 0.0.10
  - dav: 1.9.2
  - deck: 0.6.0
  - dropit: 0.2.1
  - event_update_notification: 0.3.4
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_antivirus: 2.0.1
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_fulltextsearch: 1.3.0
  - files_fulltextsearch_tesseract: 1.2.2
  - files_linkeditor: 1.0.10
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.5.0
  - files_readmemd: 1.0.2
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - fulltextsearch: 1.3.1
  - fulltextsearch_elasticsearch: 1.3.0
  - gallery: 18.3.0
  - groupfolders: 3.0.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - photosphereviewer: 0.0.3
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quicknotes: 0.1.7
  - quota_warning: 1.5.0
  - recommendations: 0.4.0
  - registration: 0.4.6
  - richdocuments: 3.2.4
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - sharerenamer: 2.6.0
  - socialsharing_email: 1.0.5
  - socialsharing_facebook: 1.0.4
  - socialsharing_twitter: 1.0.4
  - spreed: 6.0.0-rc.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.10.0-alpha3
  - telephoneprovider: 1.0.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - w2g2: 2.2.4
  - workflow_pdf_converter: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - bookmarks_fulltextsearch
  - checksum
  - encryption
  - onlyoffice
  - passman
  - socialsharing_googleplus

```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "my.domain",
            "1": "2domain"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.0.9",
        "overwrite.cli.url": "https:\/\/my.domain",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "default_language": "fr",
        "force_language": "fr",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "beta",
        "session_lifetime": 86400,
        "session_keepalive": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie"
        ],
        "activity_expire_days": 14,
        "enable_movie_transcode": true,
        "auth.bruteforce.protection.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "forcessl": true,
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "w2g2",
            "apporder",
            "passman",
            "photosphereviewer",
            "bookmarks_fulltextsearch"
        ]
    }
}

</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
"user":"toto","app":"cssresourceloader","method":"GET","url":"\/apps\/spreed\/","message":"Could not find resource vendor\/select2\/select2.css to load","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}
"user":"toto","app":"jsresourceloader","method":"GET","url":"\/apps\/spreed\/","message":"Could not find resource vendor\/select2\/select2.js to load","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}

```
</details>

**Comment by nickvergessen** [comment]
There is no Talk 0.10.0-alpha3
The current versuon is 6.0.0, the version for Nextcloud 15 was 5.0.4

So I guess you talk about some packages. In that case please contact the maintainer of the package

**Comment by Ludovicis** [comment]
Thanks nickvergessen , it was the spreed/talk version 6.0.0 rc2... Sorry
My problem is still relevant with version 6.0.0, same problem withs vendor select2.css and select2.js
How i find the maintenaer of the package and how i find it, please ?

**Comment by Ludovicis** [comment]
OK I've turned off the bookmarks app and it's ok now i can call an user
