### ISSUE TITLE
Public vs private rooms - Allow users to freely join a room

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1763]
I had this idea while using Talk. With "public rooms" I don't mean rooms I share by a public link. I want to make a different distinction here.

We have two types of rooms at the moment:

1. 1-1 chat rooms
2. group chat rooms

Both have one in common, you have to invite your chat partner(s). Think about a larger setup of an organization, your sports club, etc. Every time someone new joins your organization you have to add them to the relevant rooms manually. If someone leaves you have to remove them again. A lot of manual work with a high risk to make mistakes.

That's where my idea of "private vs public" rooms starts.

I would define private rooms as rooms where the users in the room decide who can join and who not, by inviting users, sending links around, etc. Basically what we have now.

Public rooms would be rooms someone creates and which are then open to join for everyone. Users could search for public rooms on the left hand sidebar like they search for users and groups today. They can join any of this rooms and participate in the discussion. A bit like I can join a IRC server, look around which channels exists and join the one I'm interested in.

Opinions?

**Comment by sunjam** [comment]
[Circles integration](https://github.com/nextcloud/spreed/issues/860) is a possibility for helping add this functionality since you can create your own "groups" of users as public, private, closed, or secret circles.  Once conversations can be started with a circle, it will be possible to start group discussions.

**Comment by jancborchardt** [comment]
Totally agree! This could also be useful for guests, where you then have the AppNavigation shown with all the conversations specifically set to "Public". In our case all the public team channels.

**Comment by robertfromont** [comment]
I'm looking to replace Slack with NextCloud Talk, and this is the main thing I would need to achieve that; for already-registered users, a set of Conversations they can join without needing a specific invitation.
So that's a :+1: from me!

**Comment by jcastang** [comment]
Same thing for me ! 
Being able to join a room without invitation is a must-have.

**Comment by PVince81** [comment]
reuse the existing public rooms, but make them listable with an extra checkbox in the room settings:
- any guest (public link access) can find it (for public rooms)
- any logged in user can find it (for private rooms)

- make it possible to set/unset the listable property after creation?
- where do guests see that list?

**Comment by PVince81** [comment]
- use the opportunity to move most of the actions menu into the settings tab ? (except full screen)

**Comment by PVince81** [comment]
- only display listed rooms in the left panel:    
    - when searched in top left room search
    - click plus button, ability to join a room instead of creating
    - because otherwise: too crowded and performance impact

**Comment by PVince81** [comment]
- do we want a system message to be posted "actor_x made this room listable for Y" ? (like for when locking/unlocking)

**Comment by nickvergessen** [comment]
a system message yeah, but what is `for Y`?

**Comment by PVince81** [comment]
- "actor_x made this room listable for all"
- "actor_x made this room listable for guest users"

since we planned for both options ^

**Comment by nickvergessen** [comment]
The room type GROUP vs. PUBLIC room type controls that part? Not sure we need to repeat this. We don't mention it on any other message (lobby, read-only, ...) either.

**Comment by PVince81** [comment]
hmmm, from my understanding from last time I think we said almost all room types except 1-1 and files, which would give 4 cases:
- group room (non-public):
   - listable for regular users
   - listable for guest users (from guest app)
- public room:
   - listable for regular users
   - listable for guest users (from guest app)

so if as an admin+moderator in a group room I click "listable for regular users", the message "You made the room listable for regular users", then I click "listable for guest users", another message "You made the room listable for guests". So now everyone can see it.

or were the listable modes intended to be exclusive (radio buttons, not checkboxes) ?

**Comment by PVince81** [comment]
draft PR here: https://github.com/nextcloud/spreed/pull/4706

**Comment by PVince81** [comment]
I'm having doubts about the "separate flags" approach. Maybe it doesn't make sense to allow guests to list rooms without also allowing regular users ?

**Comment by nickvergessen** [comment]
yeah, should work like the "start call" option:
* regular users
* logged in users
* everyone
