### ISSUE TITLE
UI: Sidebar icons are over the scrollbar

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/spreed#1765]
## Steps to reproduce
![image](https://user-images.githubusercontent.com/12234510/57012071-f229b780-6c04-11e9-9c1a-a9bcdb243356.png)

## Browser

**Operating system:** Windows 10

**Browser name:** Firefox

**Browser version:** 66.0.4 (64-bits

**Nextcloud Version:** 16.0.0.9

**Comment by ma12-co** [comment]
I see that those two icons are located in the right sidebar wrapper, which overlaps with the chat divs and ul. A quick fix for now could be adding some padding-left to the sidebar div to push the icons away of maybe 10px. Then we could think of something better (I.e. using the css grid) for the future vue components.

**Comment by ma12-co** [comment]
Fixed here, turned out to be a bit more complicated than what I thought:
https://github.com/nextcloud/spreed/pull/1941
