### ISSUE TITLE
Avatar does not show if you disable your camera before joining a room

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/spreed#178]
When you disable your camera before joining a room it doesn't show avatar for other people (you still see your own)

enabling an re-disabling the camera fixes it

**Comment by Ivansss** [comment]
I can't reproduce this issue. The only time I don't see any avatar is when a guest hides its camera.

**Comment by jancborchardt** [comment]
@icewind1991 this occured because your webcam is broken or you don’t have one, right? We should catch that case too and then directly show the avatar in either case.

**Comment by nickvergessen** [comment]
@Ivansss this is fixed now for firefox, but not for chrome, right?

**Comment by Ivansss** [comment]
@nickvergessen not really 😬 , this is a different issue.
