### ISSUE TITLE
Allow pasting image to chat from clipboard

### ISSUE THREAD

**Issue by jirislav** [nextcloud/spreed#1789]
It's useful when I take a screenshot, it's in clipboard - most chatting clients allow to paste the image to the chat, which will create some kind of persistent file somewhere.

Spreed could potentially create the image in user's Images folder such as `Images/Spreed`

**Comment by fsxadmin** [comment]
we added this feature, and it goes into your home folder. im look for a dev to port it to the latest nextcloud! https://github.com/fsxadmin/spreed

**Comment by nickvergessen** [comment]
Closing this one in favour of https://github.com/nextcloud/spreed/issues/2172
