### ISSUE TITLE
Input cursor in Safari oversized

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#1792]
Open a chat in Talk in Safari:

 
![Bildschirmfoto 2019-05-09 um 00 04 14](https://user-images.githubusercontent.com/245432/57411611-5d1f5380-71ee-11e9-89c9-060617d8455a.png)

@skjnldsv Any idea?

**Comment by skjnldsv** [comment]
This is because safari is a terrible browser :grin: 
@nextcloud/talk the `display: inline-block;` on the contenteditable is what break the cursor. Block is working fine.

Though the cursor is big when you click, it go back to proper size when you start typing :wink:

**Comment by nickvergessen** [comment]
Resolved by Vue
