### ISSUE TITLE
Reuse session id for guests to prevent multiple guests appearing on page refresh

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1793]
A Guest gets a new session every time they join the room.  If they refresh the page then they will appear as a new Guest in the room with a new session id.  To improve this the existing session id could be used in RoomController.php joinRoom():

		$sessionId = $this->session->getSessionForRoom($token);
		if ($sessionId) {
			try {
				$participant = $room->getParticipantBySession($sessionId);
				return new DataResponse([
					'sessionId' => $sessionId,
				]);
			} catch (ParticipantNotFoundException $e) {
				// nothing to be done
			}
		}

Is there a reason why Guests should have a new session id every time?

**Comment by nickvergessen** [comment]
I dont think its a good idea, at least at the moment.
Most of the times guests/people reload atm is because they have issues with their connection. So reusing the samne session will make mobile clients and other webrtc peers to NOT reconnection, but keep the old connection. THis would create even more issues.

Also mind to explain what the advantage would be?

**Comment by Peterede** [comment]
The advantage is that the number of Guests does not grow if the page is reloaded.  It also allows consistent naming of anonymous Guests, we are adding a number to the Guest name so that each Guest is uniquely identifiable.  So if a page is reloaded Guest-11 does not become Guest-12.

**Comment by nickvergessen** [comment]
Let's fix it properly instead and:
1. Remove the old session from the call
2. Copy the name from the old session to the new one (maybe also the type in case they where promoted)

> Also there is a performance issue if the number of Guests is too large, 100 Guests and the participant list slows the browser to a crawl.

So we should switch to infinite scrolling there too (cc @danxuliu for the vue.js list)
