### ISSUE TITLE
Better description of notification options

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#1794]
![Capture d’écran_2019-05-09_08-53-15](https://user-images.githubusercontent.com/14975046/57433113-e7d87080-7237-11e9-8b91-fe6dcc0335b0.png)

**Comment by nickvergessen** [comment]
Calls always notify. So the last option is what you are looking for. Maybe we should make it more clear that this is about chat messages only.

**Comment by ma12-co** [comment]
We could add a section title like 'Chat notifications', which would allow us to remove the 'notify' word from the three options below and would make it clear that it'd be only for the chat.
![Screenshot from 2019-07-01 09-22-37](https://user-images.githubusercontent.com/26852655/60418131-73400380-9be2-11e9-8827-e6ff5bfdc1c7.png)

**Comment by nickvergessen** [comment]
Template:
https://github.com/nextcloud/spreed/blob/c2334265152980954f6b397c1e91166f92195d09/js/views/templates/roomlistview.handlebars#L46-L64

Label strings:
https://github.com/nextcloud/spreed/blob/c2334265152980954f6b397c1e91166f92195d09/js/views/roomlistview.js#L114-L116

Not sure if a caption is already implemented, but try it.

**Comment by nickvergessen** [comment]
Hint, when modifying the handlebar templates, you need to run `make compile-handlebars-templates`

**Comment by ma12-co** [comment]
Ok, I'm on it!

**Comment by nickvergessen** [comment]
If you can't find samples anywhere, use the left sidebar in the settings section as template, since that has headers.

**Comment by ma12-co** [comment]
Here's how it looks:
![Screenshot from 2019-07-01 16-12-52](https://user-images.githubusercontent.com/26852655/60443270-27f61700-9c1b-11e9-811b-5bab8d883e03.png)
