### ISSUE TITLE
Allow to create private 1-1 conversation from participant list

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#1795]
In the participant option menu, an entry to create or go to the existing chat room would be a nice feature :)

![Capture d’écran_2019-05-09_08-55-52](https://user-images.githubusercontent.com/14975046/57433240-43a2f980-7238-11e9-8fe5-a551a95d7084.png)

**Comment by juliushaertl** [comment]
It already works in the chat list when clicking the user avatars with the contacts menu, but yes this should be across all avatar occurances.

**Comment by skjnldsv** [comment]
@juliushaertl Oh yes, I forgot about the avatar menu.
Maybe we should add a three-dot icon when hovering a div that contains an avatar?

**Comment by nickvergessen** [comment]
> Maybe we should add a three-dot icon when hovering a div that contains an avatar?

That sounds like an interesting idea, or even turn the avatar into 50% opacity and show the dotdotdot on top of it?

**Comment by skjnldsv** [comment]
@nickvergessen Created on components: https://github.com/nextcloud/nextcloud-vue/issues/383

**Comment by georgehrke** [comment]
> In the participant option menu, an entry to create or go to the existing chat room would be a nice feature :)
> ![Capture d’écran_2019-05-09_08-55-52](https://user-images.githubusercontent.com/14975046/57433240-43a2f980-7238-11e9-8fe5-a551a95d7084.png)

Maybe we can call it `Message` or `Talk privately`. `Go to existing chat room` sounds a bit verbose. And after all, if i want to talk to that person, i don't care whether there is an existing chat room or not. If there is, it should open that one, if there isn't, it should just create a new one.

**Comment by nickvergessen** [comment]
Other messangers use `Message {name}`
