### ISSUE TITLE
Don't disable the input while the previous message is being sent

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#1796]
## Steps to reproduce
1. Start a conversation
2. Enter your message
3. Hit enter
4. Very quickly start with the next message/line

### Expected behaviour
The next message should be captured.

### Actual behaviour
At least the first few characters of my message are missing as the input gets disabled for a short period of time.

## Spreed app

**Spreed app version:** company one (latest?)

## Server configuration
n/a

**Comment by nickvergessen** [comment]
Fixed with temporary messages which we have now.
See #2454  for further tasks
