### ISSUE TITLE
Better message density & grouping

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#1799]
The density of the chat is too high I think.
It could benefit from shrinking a bit and having messages more close together.
As a comparison (some might argue this is not really readable), My irc screen have around 50 messages. Current talk is 9-10. Whatsapp is around 10 as well. Signal is ~12...

I would say merging a bit could be nice.

___ 

Default clickable area is 44px.
If we have the timestamp inline with the message and the avatar, it's one message = 44px.
My window is around 900px height, so it should be able to contain 20 messages.

Rough example: 
![Capture d’écran_2019-05-09_11-36-25](https://user-images.githubusercontent.com/14975046/57443599-b7e89780-724e-11e9-9db4-e47963a191e0.png)

@nextcloud/designers @jancborchardt any ideas to improve my bad mockup?

**Comment by nickvergessen** [comment]
I also thought about dropping the name from default, but it's pretty bad when people dont have an avatar set and you only see placeholders.

But maybe @jenniferpiperek has more ideas?

**Comment by jancborchardt** [comment]
Looking at the screenshot, it misses spacing. ;)

It looks a bit like Jos is named "exactly". I wouldn’t cut names even for the simple fact that people forget what everyone’s name is. Also, then you directly know how to @-mention them.

And in Jos’s middle message, the last block actually looks like it belongs more to Tobias.


Here’s a different before and after proposal, with reduced whitespace between user name and first message, as well as between grouped messages of the same person:

![talk screenshot](https://user-images.githubusercontent.com/925062/57513942-aca97080-730f-11e9-9b26-8202c600010c.png)
![talk app screen](https://user-images.githubusercontent.com/925062/57514004-ccd92f80-730f-11e9-858c-d76419d4f438.png)


```
#chatView .comment {
    margin-bottom: 20px; // from 30px – quick tryout, needs to be adjusted to font-size + line height
}

#chatView .comments li .message {
    padding-left: 42px; // Upped from 40px so messages are flush with username
    margin-top: -12px; // Added to reduce distance of username to first message
}
```

We could additionally think about vertically aligning the avatar not only with the username row, but with the username row + first line of text. Then we _could_ reduce the whitespace between user messages, if needed.


Also, @jenniferpiperek and I will have a call about including exactly the whitespace question today. :)

**Comment by biva** [comment]
+1 :)
I would also suggest ([Slack](https://a.slack-edge.com/73267c/marketing/img/downloads/screenshots/win10_screenshot.png), [Mattermost](https://raw.githubusercontent.com/tengu-team/layer-mattermost/master/files/mattermost-screenshot.png) and Skype do that and I like it :) ):
- aligning the top of the avatar with the top of the username (I think it's centred now).
- sticking the timestamp to the name (it's currently not easy to read the timestamp on wide screens)

What I'm not sure of, is this other suggestion: align my messages on the right, while others' messages are on the left (like on WhatsApp and Skype, but unlike Slack and Mattermost)

**Comment by nickvergessen** [comment]
Easy quick proposal for the time-being
https://github.com/nextcloud/spreed/pull/1807

We can still look into more improvements for the vue.js rewrite

**Comment by skjnldsv** [comment]
@nickvergessen we should keep track of those issues for the next version then :)

**Comment by biva** [comment]
> 
> 
> @nickvergessen we should keep track of those issues for the next version then :)

Should we open a new issue then?

**Comment by skjnldsv** [comment]
> Should we open a new issue then?

Or just re-open this one :p

**Comment by nickvergessen** [comment]
Well, I dont think we need an issue for it. With the Vue rewrite we start from scratch anyway.

**Comment by skjnldsv** [comment]
@nickvergessen okay, i'll guess this will come again if there is a need for some design adjustements on the rewrite anyway ;)

**Comment by jancborchardt** [comment]
> Well, I dont think we need an issue for it. With the Vue rewrite we start from scratch anyway.

Or rather, we start from components. ;) And where there are no components yet, we start from the current design.
