### ISSUE TITLE
Talk updates conversation is locked, not possible to try out stuff

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#1816]
The "Talk updates" default conversation is pretty cool as it shows updates etc. What would be nice is if you can directly try out stuff there, like the `/help` command, or the other console commands for example.

This is not possible though as it is locked:
![cant test help cause conversation is locked](https://user-images.githubusercontent.com/925062/57646789-afcb8780-75c1-11e9-8bcf-15eeda21fe75.png)

**Comment by nickvergessen** [comment]
Basically the following line needs to be removed:
https://github.com/nextcloud/spreed/blob/186c755403b6cf8b37e502872ad446e21d2fb046/lib/Manager.php#L519

And then for existing rooms the getReadOnly value should be checked and set to READ_WRITE in case it's needed

**Comment by nickvergessen** [comment]
We also need to check so this does not throw of the hacks we have in place for this.

**Comment by PVince81** [comment]
but then if you try out stuff, that room is getting messy ?

or will the bot re-post the full changelog at the next update ?
better make a new room for experimenting ? unless it's not possible to have lonely rooms

**Comment by nickvergessen** [comment]
No, it needs to be read only for now due to magic 🙈

**Comment by nickvergessen** [comment]
Closing as per above
