### ISSUE TITLE
bower.json vs package.json

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1834]
bower.json seems to be used to manage our JS libs?
https://github.com/nextcloud/spreed/blob/master/bower.json#L19-L25

Maybe this can be moved/combined into package.json, or we ignore it until vue replaces all JS?

**Comment by nickvergessen** [comment]
cc @danxuliu @skjnldsv

**Comment by skjnldsv** [comment]
@ChristophWurst :)

**Comment by ChristophWurst** [comment]
Bower has been deprecated for a while. You should try migrating over to npm indeed. You can do that with Vue. I don't think you need to rush now.

**Comment by nickvergessen** [comment]
Was killed on the reset of the JS code
