### ISSUE TITLE
[Discussion] Matterbridge support via Rest API

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#1838]
[Matterbridge](https://github.com/42wim/matterbridge) is a simple bridge coded in Python, which uses a Rest API to allow bridging between many chat systems.  _Does not require [mattermost](https://github.com/nextcloud/server/issues/3202)_.

"Bridge between mattermost, IRC, gitter, [xmpp](https://github.com/nextcloud/spreed/issues/826), slack, discord, telegram, [rocket.chat](https://github.com/nextcloud/spreed/issues/753), hipchat (via xmpp), steam, twitch, ssh-chat, zulip, whatsapp, minecraft, reddit, facebook messenger, discourse and [matrix](https://github.com/nextcloud/spreed/issues/809) with REST API"

**Comment by thigg** [comment]
Would solve #1100 
A bridge to other chat protocols would be amazing

**Comment by alex9434** [comment]
+1 integration with Matterbridge would be amazing

**Comment by alex9434** [comment]
An additional argument: Rest API could also be used to address:
https://github.com/nextcloud/spreed/issues/1936
(API integration for bots)

**Comment by thigg** [comment]
Has anyone already a plan on what would have to be done?
If someone shows a direction, I'd be happy to help.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/talk_matterbridge

**Comment by sunjam** [comment]
That definitely resolves this request.  Very cool and exciting.

[Started a forum discussion here](https://help.nextcloud.com/t/help-test-matterbridge-app-for-nextcloud-talk/90445)
