### ISSUE TITLE
Conversation started about a project, but Project is not listed within the conversation

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#1845]
Nextcloud 16.0.1 with Talk app

Here is conversation with project icon displayed.
![1558456157](https://user-images.githubusercontent.com/1787238/58113681-f107fc80-7baa-11e9-9e87-fa7a68c11d73.png)

No project listed under conversation details...
![1558456093](https://user-images.githubusercontent.com/1787238/58113652-dfbef000-7baa-11e9-9dab-8f0eab894374.png)

**Comment by nickvergessen** [comment]
That is not a project icon, but the `public share` icon, which means the room is accessable by guests. Uncheck the `Share link` checkbox next to the big `Start call` button and it should change to 👥
