### ISSUE TITLE
Content Security Policy error in files view

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#1846]
Tested with Nextcloud 16.0.1 and Talk 6.0.1

If the Signalling server URL is entered as `wss://...` I get this error message in the files view:

````
Content Security Policy: The page’s settings blocked the loading of a resource at wss://... (“connect-src”).
````

Changing the protocol to `https://` solves the issue.

I discussed this already quickly with @rullzer and @danxuliu in the chat

**Comment by rullzer** [comment]
Basically it is https://github.com/nextcloud/spreed/blob/master/lib/Config.php#L134 not handling wss properly.
