### ISSUE TITLE
TURN settings should not show up for normal users

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#185]
I see there's still a TURN setting for normal users... I guess that counts as a bug, right? No normal user would set up a TURN server, that's an admin's job and it does show up in the admin settings correctly.

**Comment by jancborchardt** [comment]
Yup, it should be an admin setting primarily. Part of the setting should probably be to »Allow users to change TURN settings«. Off by default of course.

cc @LukasReschke @MorrisJobke @fancycode @Ivansss

**Comment by jospoortvliet** [comment]
just for my curiosity, what is the use case for a user setting this? Under what circumstances would that be needed? Because if that is a super rare corner case I wouldn't put it in the admin settings, only in the config file... Or not at all, to keep the code from rotting away and causing issues ;-)

**Comment by MorrisJobke** [comment]
> just for my curiosity, what is the use case for a user setting this? Under what circumstances would that be needed, when would an admin not do it but the user would?

You can rent a TURN server by yourself and put it in there, but for convenience the admin should maybe provide one TURN server for all users.

**Comment by muppeth** [comment]
As I understand it right. Currently each user needs to provide TURN Server user and password?

**Comment by nickvergessen** [comment]
@muppeth no currently there are 3 steps IIRC:
1. User setting
2. Admin setting
3. Default fallback turn-server

**Comment by muppeth** [comment]
@nickvergessen Do they all have to be filled in? For example if I setup TURN Servers address in Admin > Additional Settings > Spreed video calls (by providing Address and shared secret) shouldn't that be enough. It works well like this with Spreed.me and other webrtc based services I'm hosting.

Does Admin in his Personal settings have to provide username for Turn Server? Or is it only optional?

**Comment by jancborchardt** [comment]
@nickvergessen can we have the user settings be prefilled with what the admin settings are? Just as the STUN defaults prefill with our server.

**Comment by MorrisJobke** [comment]
@jancborchardt we can't prefill because they are regenerated continuously from the secret for every user - we only could add an indicator that the admin already provided this

**Comment by jancborchardt** [comment]
> we only could add an indicator that the admin already provided this

Sounds good. Because there seems to be a major confusion about these settings being there. If the admin provided them, the whole section should maybe even be collapsed saying »Settings already provided by admin« and then a button to »Change« or so.

**Comment by LukasReschke** [comment]
I do again want to mention that I consider a by-user setting rather confusing and useless. I'd be totally fine with an instance-wide setting.

**Comment by nickvergessen** [comment]
I will then do that in january

**Comment by muppeth** [comment]
I also noticed once you put the turn settings in your personal settings section, you can't remove them as the fields cannot be blank. I had to remove them directly from the database.

**Comment by nickvergessen** [comment]
Now part of https://github.com/nextcloud/spreed/pull/198
