### ISSUE TITLE
text box doesn't accept Double-byte character

### ISSUE THREAD

**Issue by yokoyamy** [nextcloud/spreed#1864]
## Steps to reproduce
1.Start Talk in nextcloud
2.Create New conversation
3.Type into New message

### Expected behaviour
Text box accepts any character input from keybored

### Actual behaviour
Text box only accept single-byte character.
Never accept Double-byte character from keybored.

## Browser

**Microphone available:** yes/no
yes

**Camera available:** yes/no
yes

**Operating system:** Windows/Ubuntu/...
Windows

**Browser name:** Firefox/Chrome/...
FireFox
Chrome

**Browser version:** 50.1/55/...
Chrome 74.*
FireFox 66.*

### Browser log
<details>

Uncaught TypeError: Cannot read property 'which' of undefined
    at n.catchQuery (jquery.atwho.min.js?v=826243a8-10:1)
    at n.i.lookUp (jquery.atwho.min.js?v=826243a8-10:1)
    at e.dispatch (jquery.atwho.min.js?v=826243a8-10:1)
    at jquery.atwho.min.js?v=826243a8-10:1

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
Talk 3.2.8

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
yes

## Server configuration

**Operating system**: Ubuntu/RedHat/...
CentOS7

**Web server:** Apache/Nginx
Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL
MySQL

**PHP version:**
php7.2

**Nextcloud Version:** (see admin page)
13.0.11

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by GammaPi** [comment]
I can confirm this on nextcloud 16.0.1 Talk 6.0.1.
Plus, this issue only occurs on PC. Phone browser works fine.
It makes talk completely unusable for chinese users.

**Comment by GammaPi** [comment]
Edge browser works. This bug occurs on windows/linux Firefox and chrome.

**Comment by GammaPi** [comment]
#1071 maybe related?

**Comment by nickvergessen** [comment]
yes, it's #1071 in action.
