### ISSUE TITLE
Give feedback if there are no contacts

### ISSUE THREAD

**Issue by Henni** [nextcloud/spreed#187]
I haven't installed the contacts app. Because of this, the first time I open the app it looks like this:
![image](https://cloud.githubusercontent.com/assets/1267827/21195599/bbeceb28-c234-11e6-946a-2ae04fcafd14.png)

It would be great to get some feedback in the sidebar on what to do to make it work.

**Comment by jancborchardt** [comment]
For that, ideally the »Choose person« dropdown should be opened as long as there are no existing calls, as described inhttps://github.com/nextcloud/spreed/issues/111 cc @Ivansss 

Second thing is that when you have no contacts, there is no feedback in the dropdown. It’s just stuck at »Searching …«. It should say »No contacts found« and also have the »New public room« entry below. cc @Ivansss @nickvergessen

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/111

**Comment by jancborchardt** [comment]
@nickvergessen this is about there being no contacts in the contacts app or user management. Test that and click the »Choose person …« dropdown and then read my remark:

> when you have no contacts, there is no feedback in the dropdown. It’s just stuck at »Searching …«. It should say »No contacts found« and also have the »New public room« entry below.

**Comment by Ivansss** [comment]
> when you have no contacts, there is no feedback in the dropdown. It’s just stuck at »Searching …«. It should say »No contacts found« and also have the »New public room« entry below.
I tried this and "admin (group)" should be visible even when you have only the minimum admin user. Also "New public room" option will be visible.
![screen shot 2016-12-15 at 16 08 18](https://cloud.githubusercontent.com/assets/4638605/21229143/da19006c-c2e0-11e6-900a-9a19868e4d44.png)

**Comment by jancborchardt** [comment]
@Henni can you recheck if this is a different error?

**Comment by Henni** [comment]
In hindsight I think this happened because I ran my development instance with `php -S ...`. So the request for contacts probably didn't go through and also didn't show the 'public room' option because all sockets where blocked.

This won't happen on a productive system. So I'm happy with closing this.
