### ISSUE TITLE
"Call with XXX" messages shown before last "XXX left the call" message

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1870]
## Steps to reproduce
- Start a call with user A
- Join the call with user B
- Leave the call with user B
- Leave the call with user A

### Expected behaviour
"Call with user A and user B (Duration XXX)" message appears after "user A left the call" message.

### Actual behaviour

"Call with user A and user B (Duration XXX)" message appears before "user A left the call" message.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/2175
