### ISSUE TITLE
"Call with XXX" messages register users in the room instead of in the call

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1871]
"Call with XXX" messages register users that were at some point in the room when a call was ongoing, even if the user was not actually in the call.

This happens only with registered users; guests are only registered if they were actually in the call.

## Steps to reproduce (scenario 1)
- Start a call with user A
- Join the room, but not the call, with user B
- Leave the room with user B
- Leave the call with user A

### Expected behaviour

No "Call with XXX" message is shown (as it is only shown when there was more than one participant in the call).

### Actual behaviour

"Call with user A and user B (Duration XXX)" message is shown.

## Steps to reproduce (scenario 2)
- Start a call with user A
- Join the room, but not the call, with a guest
- Leave the room with the guest
- Leave the call with user A

### Expected and actual behaviour

No "Call with XXX" message is shown (as it is only shown when there was more than one participant in the call).

## Steps to reproduce (scenario 3)
- Start a call with user A
- Join the room and the call with a guest
- Leave the call and the room with the guest
- Leave the call with user A

### Expected and actual behaviour

"Call with user A and 1 guest (Duration XXX)" message is shown.

**Comment by nickvergessen** [comment]
> This happens only with registered users; guests are only registered if they were actually in the call.

Yeah for users we check their last ping timestamp. For guests we simply count up once they join, as they get totally deleted when they leave.

**Comment by nickvergessen** [comment]
Btw this basically means that self-joined users should miss from the call messages too :thinking:

**Comment by nickvergessen** [comment]
Duplicate #1735
