### ISSUE TITLE
"XXX left the call" message is not shown if the user log outs while in the call

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1872]
## Steps to reproduce
- Start a call with user A
- Log out with user A while in the call
- Join the room with user B*

*It does not matter if you join immediately or wait several minutes to ensure that user A was cleaned from the room due to inactivity.

### Expected behaviour
"user A left the call" message is shown (note that no "Call with XXX" message is shown when there was just one participant in the call).

### Actual behaviour

No "user A left the call" message is shown; note that the call button is "Join call" instead of "Start call", which means that based on the data returned by the server the call is still ongoing.

If user B "joins" the call and then leaves the "Call with user A and user B (Duration XXX)" message would also appear, with XXX being the duration since user A started the call to user B ending it.

**Comment by nickvergessen** [comment]
We could listen to the logout hook `\OC_Hook::emit('OC_User', 'logout', array());` and leave all rooms before.
