### ISSUE TITLE
Ability to admins control which type of group of users talk application can use on rooms.

### ISSUE THREAD

**Issue by emersonkfuri** [nextcloud/spreed#1882]
I have several LDAP security groups with a huge number of users which I use to control access to external storages in my NC instance.

I had to disable autocomplete to prevent users from clicking in those groups on mobile and open huge rooms causing spam into NC. With this last update on Android talk (don't know about IOS), users can now search for users and group. This feature is great but in my case, it opened the same problem as before.

It would be really great if administrators could filter which type of group of users talk application can address, like LDAP groups, personal groups, circles or else.

Thank you,

EHKP

**Comment by moarf56** [comment]
I have a litle instance of NC with groups, and I search the same thing ! 
The ability to choose who can speak with someone.

If someone want help for testing, I'm here ! 

ThX

**Comment by nickvergessen** [comment]
@emersonkfuri I guess best would be to not deploy the groups with the LDAP backend.
The thing is, we use the same endpoint as the file sharing dialog. So you can only fix it for both in one go, or not at all.

But also when I turn off autocomplete, people have to search the full group name `Nextclou` as search term will not bring up the `Nextcloud` group.
If your group name is too easily guessable that is a different issue of course. You could add an emoji or something :see_no_evil:

**Comment by emersonkfuri** [comment]
Hello @nickvergessen! It would be too much complex to do it at this endpoint? Besides to "fix" it on one go, other apps in the future may benefit from it.

Regard the group's names, they are pretty intuitive because they're created and used by an AD Domain.

**Comment by moarf56** [comment]
> 
> 
> @emersonkfuri I guess best would be to not deploy the groups with the LDAP backend.
> The thing is, we use the same endpoint as the file sharing dialog. So you can only fix it for both in one go, or not at all.
> 
> But also when I turn off autocomplete, people have to search the full group name `Nextclou` as search term will not bring up the `Nextcloud` group.
> If your group name is too easily guessable that is a different issue of course. You could add an emoji or something 🙈

But for an user like me ? I use nextcloud with local NC user. I can turn off autocomplete only for the talk app ?

Thx

**Comment by nickvergessen** [comment]
This is just too specific, so it is unlikely to get implemented at the moment, because there are other things way higher on the priority list.

**Comment by nickvergessen** [comment]
As per https://github.com/nextcloud/spreed/issues/1464 and https://github.com/nextcloud/server/pull/25658 apps are supposed to respect the share settings, so if something like a group filter is wished, it needs to be implemented on the server and then applies to all apps at the same time.
