### ISSUE TITLE
Notify users If the don't use the frontend

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#1886]
Most of my users don't work with the frontend all the time. 
So the possibility is high, they miss the information from the (group)chats.
Is there a way to inform/notify them?

Maybe sending the chat messages with mail?
This could solve the problem partwise too, I think: https://github.com/nextcloud/notifications/issues/314

**Comment by nickvergessen** [comment]
We are not going to turn our chat into an Email spam tool.

You can install the desktop sync client for files or the android mobile apps and will receive notifications.
