### ISSUE TITLE
No video and audio with Edge in Talk App

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/spreed#1888]
Hello,

i see no video and audio in talk app with the Edge browser. The connection is etablished and i see a black window in the chat frame and when i disconected the Chat fram come back. In Firefox or Chrome i have no problems.

Ubuntu 18.04
Maria DB 10.1.38
Windows 10 1809
php 7.2
Apache and Nginx (i have many server)

There are two tests in this log.
Here is the log from Edge browser:

HTML1300: Navigation wurde ausgeführt.
spreed (1,1)

2CSP14309: Unbekannte Direktive manifest-src in Content-Security-Policy. Die Direktive wird ignoriert.

SCRIPT7016: SCRIPT7016: XMLHttpRequest wird nicht mehr verwendet, während das synchronous-Kennzeichen auf TRUE festgelegt ist, weil die Websiteleistung für den Benutzer beeinträchtigt wird.

CSS3121: Die Medienabfrage -ms-viewport ist veraltet.

JQMIGRATE: Migrate is installed, version 1.4.1
main.js (278,474)

2The select2 library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

Legacy browser detected, applying css vars polyfill
merged-template-prepend.js (2121,3)

Joined [object Object]

83The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

localMediaStarted
merged.js (16186,4)

The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

Deprecated call $.tooltip('destroy') has been deprecated and should be removed
tooltip.js (29,5)

2The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

RTCIceServer.url is deprecated, please use RTCIceServer.urls instead.
merged.js (8077,3)

PEER CREATED [object Object]

ANSWER [object Object]

VIDEO ADDED [object Object]

Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification
merged.js (3919,11)

Connecting to peer...
merged.js (15680,8)

2Connection established.
merged.js (15686,8)

XXX Remove peer TEuqa6sG2phtzcpitVm6wV3oH+Xqs7mh4jlFHFapXgp4lzP7NOPcFKarJq8ulwvzqCTLrpzB5HN9B9Iq1s0nFcfTedlyHIldhtTDnjSYSVyLPMxZa8daj/PS41N3qSliUL1vatZUnpmaJ3bTqu5ZU9/k356XHUH6nBG7UfekMTD5/LLRC1XPRycq2ZcMlu6WKUCPcTWRfl+PkVBcQ22TqieYAM+467crTlqIWEs77+161jMjwEKNmnsmTfRi2nq
merged.js (15421,4)

4The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

PEER CREATED [object Object]

ANSWER [object Object]

VIDEO ADDED [object Object]

The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

Timeout for addRemoteCandidate. Consider sending an end-of-candidates notification
merged.js (3919,11)

Connecting to peer...
merged.js (15680,8)

2Connection established.
merged.js (15686,8)

2The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

XXX Remove peer nxFvec/naXN3kuWGW9TrLzu6Wf1qAc6Bq0RL4cjKK0tSF+6Wzf/d+kj8AVXkYcWZKMV/s3VVdVJ4+ax2WGidzGz4nbOZ9x6KhscgDRJjkYHnrjsr8vnxJAguzjBDuwBoLo6LIHgzoOZtsKdZaeLamriR/GujWPFEL1eqE5Hw0TJLfdjNM6K6vXNr0ra+aiEeytbmpTGwe0YLFlXQAEaiSJMiJB4Kg76JwJB802BPZZW35wQy4HWkc2PdZjpz7XM
merged.js (15421,4)

2The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js (31,3)

**Comment by nickvergessen** [comment]
`Timeout for addRemoteCandidate` seems like your Edge is having issues.

**Comment by nickvergessen** [comment]
@danxuliu any further ideas?

**Comment by nickvergessen** [comment]
@danxuliu any further ideas?

**Comment by nickvergessen** [comment]
Closing for now
