### ISSUE TITLE
Version 5.04 is not offered for update within 15.0.8

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/spreed#1893]
## Steps to reproduce
1. Goto to App menu within Nextcloud

### Expected behaviour
Offering update from 5.0.3 to 5.0.4

### Actual behaviour
No update offer

## Browser
FF 

**Operating system Server:**
Debian 9 Stretch (stable)

Note:
In the store i can see the 5.0.4 Version. Until now the automatic update within nextcloud was never a problem.

**Comment by jookk** [comment]
I have this too on nc 16. 
No update offer to new version.

**Comment by pm-pm** [comment]
Version 5.0.4 was offered today to me (10.6.2019).
From my side the issue can be closed.
Thanks.

**Comment by jookk** [comment]
To me not, till now

Dňa 10. júna 2019 13:09:07 používateľ pm-pm <notifications@github.com> napísal:

**Comment by Ivansss** [comment]
@pm-pm Could you please check if the update is being offered for you now?
There were some issues in apps.nextcloud.com that seem to be fixed now.

**Comment by jookk** [comment]
Yes, update offered, updated without problems. Thanks 👍😀
