### ISSUE TITLE
Error 404 when initially fetching the chat messages as a guest with the MCU

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#1896]
This is a regression introduced in https://github.com/nextcloud/spreed/commit/0321133f11581942d6c4188479ff6e2d1c52b606

[The endpoint to get the chat messages of a room requires a participant](https://github.com/nextcloud/spreed/blob/2825271bccfee46323a1465267f17d14ef43ab1c/lib/Controller/ChatController.php#L182), so guests need to join the room before being able to get its chat messages. This is done in the WebUI by [waiting until `currentRoomToken` is set before getting the messages](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L377-L381), but since 0321133f11581942d6c4188479ff6e2d1c52b606 `currentRoomToken` is set not only [when the participant has joined the room](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L238), but also [when trying to join the room without being connected yet to the external signaling server](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L1028-L1035).

## How to reproduce

- Setup the MCU
- Defer sending the "Hello" message by replacing [`this.doSend(msg, this.helloResponseReceived.bind(this));`](https://github.com/nextcloud/spreed/blob/71f66fe9b1e86fb244f9c7809bdf27c4c68e3d17/js/signaling.js#L964) with `setTimeout(function() { this.doSend(msg, this.helloResponseReceived.bind(this)); }.bind(this), 5000);` *
- Create a public room and copy its link
- Logout (or open a private window; in that case all the steps below should be done in that private window)
- Open the network tab in the development console of the browser
- Go to the copied link to open the public room as a guest

*Usually it fails without this change, but this "ensures" the failure

### Expected results

No errors in the network tab when fetching the chat messages.

### Actual results

Error 404 in the network tab when fetching the chat messages; once the guest has finally joined the room the chat messages can be successfully fetched.

**Comment by nickvergessen** [comment]
Not happening anymore
