### ISSUE TITLE
Calls do not work in the mobile application

### ISSUE THREAD

**Issue by albertooka** [nextcloud/spreed#1897]
## Steps to reproduce
Fix the problem of calls / video calls in the Android application.

### Expected behaviour
Calls / video calls should work correctly in the Android application.

### Actual behaviour
When you call someone through the Android application of Nextcloud Talk:
1. You do not listen to the speaker.
2. The person you are talking to does not listen to you.
3. In case of a video call, the screen is always black, so you can not see the speaker.

## Spreed app

**Spreed app version:** 6.0.2

**Custom TURN server configured:** no

**Custom STUN server configured:** no (I use the one that comes by default)

## Server configuration

**Operating system**: Linux 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64

**Web server:** Apache/2.4.34

**Database:** mysql 5.7.25

**PHP version:** 7.2.19-0ubuntu0.18.10.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, remctl, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud Version:** 16.0.1.1

**List of activated apps:** Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.0
 - camerarawpreviews: 0.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_antivirus: 2.1.1
 - files_linkeditor: 1.0.10
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.0.2
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quicknotes: 0.1.7
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - sharerenamer: 2.6.0
 - sociallogin: 1.14.5
 - spreed: 6.0.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - onlyoffice
 - user_ldap

<details>
</details>

**Nextcloud configuration:** {
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nubertini.tk"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "overwrite.cli.url": "https:\/\/nubertini.tk\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "beta",
    "mail_smtpmode": "smtp",
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "impersonate",
        "quicknotes",
        "secsignid",
        "onlyoffice",
        "occweb"
    ],
    "has_rebuilt_cache": true,
    "social_login_auto_redirect": true,
    "overwriteprotocol": "https"
}

<details>
</details>

**Comment by ezaquarii** [comment]
I can confirm this problem both on web-android and also on web-web.

Sometimes I manage to get 1 party visible. After multiple reconnections I managed to have video for both parties.

Unfortunately I do not see any logs so I don't know how to investigate this problem. I'm using a beefy VPS so there should be plenty of bandwidth available.

**Comment by nickvergessen** [comment]
Since 6.0.2 the situation should have been improved quite a lot.
If you never can get a connection, it is mostlikely that one of your devices is behind a restrictive firewall and you need a TURN server installed.
