### ISSUE TITLE
None to translated in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#1898]
**There are no descriptions to translate in Transifex:**
- Failed to add the item to the project
- Hide details
- Show details
- Rename project
- Failed to rename the project
- Connect items to a project to make them easier to find
- Add to a project
- Type to search for existing projects
- Failed to create a project
- Failed to add the item to the project

In `js/collectionsintegration.js` and `js/collections.js.map` files, the text refers to the `Core` directory.

## Spreed app
6.0.2

**Comment by nickvergessen** [comment]
@juliushaertl what do we need to do?

**Comment by nickvergessen** [comment]
@juliushaertl what do we need to do?

**Comment by juliushaertl** [comment]
We merged https://github.com/nextcloud/server/pull/15893 as a workaround for the next server release until we have found a proper way to add translations to the vue components.
