### ISSUE TITLE
show email invitees

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#1902]
**Is your feature request related to a problem? Please describe.**
When I invite somebody to a conversation via email, neither do I get a confirmation that the invitation has been sent, nor do I have an overview who I've already invited.

**Describe the solution you'd like**
- Invitees' email addresses are listed in the participants list.
- Moderators have a ...-menu, allowing to delete them - just as it is with named users
- Promoting guests to moderators should be out of scope.

**Additional context**
This has already been mentioned as todo by @nickvergessen in https://github.com/nextcloud/spreed/pull/1090#issue-205072459
> Currently we don't hold any record about these invites. A next step could be to add them as participants already, which would allow to make them moderators etc already before they join.

**Comment by brrrrrrrt** [comment]
that would be great, as currently there it is impossible to see "which guests are already invited?"

when inviting guests, there is no feedback at all, users are sending out invites again and again, because they think something went wrong.

**Comment by mokkin** [comment]
Maybe after joining the call they can be shown with their name from the contacts app or at least with their mail address. Both is better than having three "guests".

**Comment by nickvergessen** [comment]
This is the case in current 11 alpha

**Comment by sudwhiwdh** [comment]
@nickvergessen You mean for Talk 11 this is already implemented as suggested above by @wiswedel?

**Comment by nickvergessen** [comment]
mostly yes. Removing an email has however no effect when the conversation remains public, also they are not identified by the email link, so they will be normal guests, but that's part of another ticket (cant find it atm).

**Comment by wiswedel** [comment]
> they are not identified by the email link, so they will be normal guests, but that's part of another ticket (cant find it atm).

https://github.com/nextcloud/spreed/issues/1423#issuecomment-717173255
https://github.com/nextcloud/spreed/issues/4403#issuecomment-712930671
https://github.com/nextcloud/spreed/issues/2845#issuecomment-748155385
