### ISSUE TITLE
Help command is broken once commands are added.

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#1904]
## Steps to reproduce
1.add new command
2.use /help
3.observe

### Expected behaviour
Tell us what should happen
Help should list available commands and descriptions

### Actual behaviour
Tell us what happens instead
Help lists output from all commands in an odd way:

example output:
test
--help : Sven

**Operating system:** Windows/Ubuntu/...
Debian 

**Browser name:** Firefox/Chrome/...
Firefox 
**Browser version:** 50.1/55/...
67.0.2

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
6.0.2

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian 9

**Web server:** Apache/Nginx
Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria

**PHP version:**
7.1

**Nextcloud Version:** (see admin page)
16.0.2

**Comment by nickvergessen** [comment]
Well, if you `/help` it will show the short description of all commands (first line only):
> ```
> /wiki - A simple command to find wikipedia articles for a term
> /hackernews - A simple command to list the Top 5 top, new or best stories
> ```

If you do `/help wiki` it will show the full description of the wiki command:
> ```
>  /wiki - A simple command to find wikipedia articles for a term
>  
>  Example: /wiki Nextcloud
>  Wikipedia search results for "Nextcloud":
>  * Nextcloud - Nextcloud is a suite of client-server software for creating and using file hosting services. Nextcloud application functionally is similar to Dropbox. - en.wikipedia.org/wiki/Nextcloud
> ```

I'm not sure, what is odd about it.

**Comment by Luticus** [comment]
So for instance, I have a command "dotagen" and that command takes a list of arguments (user names) and suggests a dota character for them to play.  So when I run "/dotagen bob" the output ill be "bob:  sven" for instance (this part works).  Now when I run /help I would expect the output to be "dotagen: a dota character generator" or something like that.  Instead it is something like:

--help : Sven

Which is only possible if it is somehow executing the command, which is not desirable.

**Comment by nickvergessen** [comment]
Mind to share your scripts?

**Comment by Luticus** [comment]
Uh, sure I can probably do that.  Though the lyric one uses a web scraper for lyrics so we might want to modify it so the source points to something cool with a lot of people using a scraper against it like that.  Also the script is modified from a script I found online once upon a time, I want to rewrite the whole thing in python but haven't gotten around to it yet.  It currently has a ruby and bash component.  There is also a python component for fetching the playing song from a users spotify, but the version that's integrated into talk doesn't have that component because, well, spotify isn't ever going to be installed on my server  :).  Originally the script was designed so that I could type Lyrics in bash and it would grab the playing song from xmms2 and return the lyrics, I have modified it so it works with spotify and also so it takes an artist and song as arguments (you can quote them if there are spaces) and will return lyrics from a website it searches.

Python file to retrieve spotify's playing song (not used in talk version but here in case anyone is interested):
`
#!/usr/bin/env python

import dbus

try:
  session_bus = dbus.SessionBus()
  spotify_bus = session_bus.get_object("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2")
  spotify_properties = dbus.Interface(spotify_bus, "org.freedesktop.DBus.Properties")
  metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")
  artist = metadata['xesam:artist'][0]
  title = metadata['xesam:title']
  print artist + " - " + title
except:
  # no song returned.  spotify off? 
  print "null - null"
`


- There are some hard coded paths in the bash script, If you place this in another directory than /opt/Lyrics, change these paths accordingly.
Bash script to tie everything together  (spotify stuff is commented out):
`
#!/bin/bash

# Spotify stuff removed:
#if [ $# -eq 0 ]; then
#  input=$(/opt/Lyrics/getsong_spotify.py)
#  echo $input
#  artist=$(awk -F' - ' '{print $1}' <<< "$input")
#  song=$(awk -F' - ' '{print $2}' <<< "$input")
#else

artist=$1
song=$2
#fi
echo "$song by $artist:"
echo "Fetching Lyrics...  "

echo
/opt/Lyrics/spotifygetlyrics.rb `echo ""$artist"" | sed 's/ /_/g'` `echo ""$song"" | sed -e 's/ /_/g'`| sed -r 's/^.*[;]$//' | tr ";" "\n"
`

Ruby stuff to do web scrape and lyrics fetch:
`
#!/usr/bin/env ruby
#Requires packages:  ruby-hpricot

%w(rubygems open-uri hpricot).each { |dep| require dep }
BASE_URL = ""  #You'll need to add a source here for lyrics fetch.
# The code below may need to be updated for your particular source.  

artist, song = ARGV[0], ARGV[1]

page = Hpricot(open("#{BASE_URL}/#{artist}:#{song}")) rescue false
if page
 lyrics_search = (page/"div.lyricbox")
 if lyrics_search.size == 1
  lyrics_box = lyrics_search.first
  lyrics_box.inner_html = lyrics_box.inner_html.gsub("<br />", "\n")
  lyrics = lyrics_box.inner_text.strip
  #puts "#{artist}:#{song}\n\n#{lyrics}\n\n" + ('-' * 10)
  puts lyrics
  end
end
`

Eventually I'm going to get not lazy enough to rewrite this whole thing in python.  Until then, this is what I have so far.

**Comment by Luticus** [comment]
Here's the one that generates a random dota hero suggestion.  It takes players names as arguments and returns a hero name:  https://pastebin.com/g0QfH9rP

it has a wrapper because it's written in python.  Here's the wrapper:
`#!/bin/bash
python3 /usr/local/bin/gethero.py $@
`

**Comment by nickvergessen** [comment]
after:
```py
    if names.__len__() < 1:
        print("Please supply player names")
```
Just add:
```py
        return
    if names.__len__() == 1 and names[0] == "--help":
        print("/dota - Give a list of players to receive a random hero for everyone to pick")
	return
```

**Comment by Luticus** [comment]
Oh, so the help function just runs the script with a --help?  I will update the code then, thanks!

**Comment by Luticus** [comment]
Are you sure you didn't make any other changes to that script?  The return statements break execution because they are outside of a function which is a syntax error.  Once I fix that I get:

NameError: name 'names' is not defined

If all I need to do is watch for --help and respond, I can make that happen.

**Comment by Luticus** [comment]
I fixed it by making my shell script wrapper look like this:

#!/bin/bash
if [[ $@ == *"--help"* ]]
then
  echo "/dota - Give a list of players to receive a random hero for everyone to pick"
else
  python3 /usr/local/bin/gethero.py $@
fi

**Comment by Luticus** [comment]
Yep, it works now.  Thanks!
