### ISSUE TITLE
Provide a way to pass all participants in room to a command as arguments.

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#1905]
**Is your feature request related to a problem? Please describe.**
This is not really a frustration thing but more of a convenience thing.  It would just make things better.

**Describe the solution you'd like**
We need a way to list all of the participants in a conversation and feed that to a command as arguments.  I built a dota random character generator that basically tells you what character to pick, and currently you have to give it a list of names.  so like /dotagen Jeff Steve Frank.  It would be way neater if you could just run /dotagen and it would generate  a character for everyone in the room.  That would probably be very cool for other scripts as well.

**Comment by nickvergessen** [comment]
Well, you can simply get the list of participants from the API:
https://github.com/nextcloud/spreed/blob/master/docs/api-v1.md#get-list-of-participants-in-a-conversation

Just create an APP token for your user, and use that as Auth in a curl request inside your script.

**Comment by Luticus** [comment]
So if I create an app token for my user and use /room/{token}/participants as a url in curl to return the list of participants is that going to work when other users try to use the script?  What if I'm not part of the conversation?  Or can I create an app token for a different service account type user and let that user fetch the participants?  I've never really used this api before so I'm not 100% sure what I'm doing with it.  Any help you could give would be awesome, thanks!

**Comment by Luticus** [comment]
@nickvergessen can you maybe provide an example of how this might be done?  

I see the endpoint which is obviously appended to the url of the webserver with the app token:  /room/{token}/participants

I don't see a way to specify the user for the token, nor do I understand the difference between various commands with the same endpoint.  I don't understand how it differentiates between the endpoint that returns the participants and the one that adds a participant.  I wish that api guide has a few examples so I could get a better idea of how this might be used.

**Comment by nickvergessen** [comment]
Assumptions:
* You created the room where you want to use the bot, we will use `https://localhost/index.php/call/u5gqo3co` as example, so the token is `u5gqo3co`
* You created a fake user and invited it to the room, let's call the user `fakebot` with password `123456`

Now you can make a request to:
`curl -k https://fakebot:123456@localhost/ocs/v2.php/apps/spreed/api/v1/room/u5gqo3co/participants -H "OCS-APIRequest: true" -H "Accept: application/json"`
Which will give you a JSON reply with all the participants:
```json
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": [
      {
        "inCall": 0,
        "lastPing": 1561727472,
        "sessionId": "AUEbwxyqBa7WP49lhr\/HwVstcqrbuJrVvGXbpieS315HDzjz++1rwyBxbcnY+EKqoUsold0ZTqmn0skMS+oUTIYn3szqs2eGShDtrcAUULG8vH19szBJyVR75ROHwIl5anAVLzHYCPro01I1ji7g0pEqvfCvS9+052gHSSIetJLDm2yt1CwE3bgu+Gb0p\/UOqDVGZoAonOUY5m6erKAEuNhAtfKiyR2n5b\/hpm86tZJVH42At+dlr1ZQlCHKJWy",
        "participantType": 1,
        "userId": "admin",
        "displayName": "Heilbronner Falken"
      },
      {
        "inCall": 0,
        "lastPing": 0,
        "sessionId": "0",
        "participantType": 3,
        "userId": "test1",
        "displayName": "Bad Nauheim #1"
      },
      {
        "inCall": 0,
        "lastPing": 0,
        "sessionId": "0",
        "participantType": 3,
        "userId": "test2",
        "displayName": "Bad T\u00f6lz #2"
      },
      {
        "inCall": 0,
        "lastPing": 0,
        "sessionId": "0",
        "participantType": 3,
        "userId": "test3",
        "displayName": "Bietigheim #3"
      },
      {
        "inCall": 0,
        "lastPing": 0,
        "sessionId": "0",
        "participantType": 3,
        "userId": "test4",
        "displayName": "Crimmitschau #4"
      },
      {
        "inCall": 0,
        "lastPing": 0,
        "sessionId": "0",
        "participantType": 3,
        "userId": "test5",
        "displayName": "Kassel #5"
      }
    ]
  }
}
```

The data is per user and as described in the docs:
```
{
        "inCall": 0,
        "lastPing": 1561727472,
        "sessionId": "AUEbwxyqBa7WP49lhr\/HwVstcqrbuJrVvGXbpieS315HDzjz++1rwyBxbcnY+EKqoUsold0ZTqmn0skMS+oUTIYn3szqs2eGShDtrcAUULG8vH19szBJyVR75ROHwIl5anAVLzHYCPro01I1ji7g0pEqvfCvS9+052gHSSIetJLDm2yt1CwE3bgu+Gb0p\/UOqDVGZoAonOUY5m6erKAEuNhAtfKiyR2n5b\/hpm86tZJVH42At+dlr1ZQlCHKJWy",
        "participantType": 1,
        "userId": "admin",
        "displayName": "Heilbronner Falken"
      }
```
if `sessionId` is empty, the user is not in the chat.
if `userId` is empty, the user is a guest and does not have a nextcloud account.

You should be able to parse this information with any language you use for your command.

**Comment by Luticus** [comment]
So I finally got around to messing with this again and it's kinda bonkers.  Here's what I'm doing:

participants=$(curl -s -k  https://user:token@www.example.com/ocs/v2.php/apps/spreed/api/v1/room/roomtoken/participants -H "OCS-APIRequest: true" -H "Accept: application/json" |
  sed -e 's/[{}]/''/g' |
  awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' |
  grep -i displayname |
  awk -F"":"" '{print $2}' |
  sed "s/ /_/g" |
  sed "s/\"//g" |
  sed "s/\]//g" |
  sed "s/\n/ /g")

This gives me just the displaynames of the users, converts spaces to _ to ease expansion before handing off to python.  The thing is, I have a test user that I joined to the room and no matter what he doesn't appear when I query the participants of the room.  It doesn't make sense.  He can join a call, type and receive text, but when I query the room it shows the same users.  Bonkers.  Also this will only work if you bot is dedicated to a room.  If I add the command /dota to show random dota character suggestions for everyone in the room it'll work when they are in the dota room, but if someone does it while chatting one on one with another person or from a room other than dota it'll show... the participants of the dota room, not the room they are in... again, bonkers.  Not reliable either.  Would be nice if the command just supported a {participants} variable that could be used as an argument to the script that outputs the list of participants in the particular room.  Would also be nice if it could address.

So yea, hoping there is or could be a better solution out there.

**Comment by Luticus** [comment]
Would also be nice if it could just get the list of active participants rather than everyone who is a part of the room too.  It's kind of weird that the bot addresses people who aren't even actively using the room.
