### ISSUE TITLE
Message length exception for commands

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#1906]
**Is your feature request related to a problem? Please describe.**
This blocks a command script from working properly

**Describe the solution you'd like**
I wrote a script that would retrieve lyrics and post them to chat but the message length constraint is preventing some of the results from returning.

**Comment by nickvergessen** [comment]
Well, I wouldn't restrict the length at all. The problem is, that the comments api which we use in the background has this limitation.

**Comment by Luticus** [comment]
Ok, I thought it was just restricted for spam limitations or something.  I had a feeling this might be the case when I was looking through the code and saw where the warning was thrown but couldn't trace down or adjust where the limit was actually set.  Hopefully something can be done.  Would be nice to be able to run commands that return all kinds of neat stuff like that.

**Comment by Luticus** [comment]
One suggestion may be message splitting/paging.  So when you bust the limit you'd split the message into two messages and send them in succession.  Not sure if that's possible right now or how difficult that may be to implement in the current code, but it might be a work around if the api cannot be easily adjusted.

**Comment by nickvergessen** [comment]
We are currently thinking whether it's better to remove the restriction from the API and move it into the comments endpoint, or whether we clone the comments api and modify it for the chat messages.
