### ISSUE TITLE
Reactions to chat messages

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/spreed#1920]
Something similar to Slack:
![](https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2015/07/reaction-examples.png)

[Source](https://thenextweb.com/apps/2015/07/09/how-did-we-ever-live-without-this/)

**Comment by fsteinbauer** [comment]
This and threads are the crucial features we are missing to finally ditch Slack.

**Comment by nickvergessen** [comment]
API in progress: https://github.com/nextcloud/spreed/pull/6730

**Comment by nickvergessen** [comment]
Just for the record, there is a technical part to it. The summary of the emoji list is limited to 4k chars.

In telegram the list is also limited to 10 emojis:
👍👎❤️🔥🎉🤩😱😄😢💩🤢

**Comment by juliushaertl** [comment]
Just for completeness, slack also allows any emoji (even custom ones):
![image](https://user-images.githubusercontent.com/3404133/149380898-0e62b7cf-dad7-4c65-ac83-5ac3c417105c.png)

**Comment by vitormattos** [comment]
Complementing, follow reactions on rocket.chat, is very similar to Slack.

![Screenshot_20220113_161014](https://user-images.githubusercontent.com/1079143/149394005-4b8768b0-c7db-46af-a031-310ac8177f85.png)

![Screenshot_20220113_161101](https://user-images.githubusercontent.com/1079143/149394089-a38c1181-edc5-4d61-bb47-6d6caa7581e2.png)

![Screenshot_20220113_161256](https://user-images.githubusercontent.com/1079143/149394331-eb7dc11b-05d0-44ef-aeed-621c231044a0.png)

**Comment by nickvergessen** [comment]
Seeing this, maybe on the summary of the reactions we sort by count and only summary the first X entries, to make sure the summary is less than 4k chars @vitormattos

**Comment by vitormattos** [comment]
For now, the API don't restrict the emojis list to use, this rule is client side.

To display the reaction summary also is a client side implementation. Exists an endpoint to return a data dictionary with reactions emojis by type and the total of reactions using the emoji. I will change the return of API to return ordered by quantity to make more easy to display on client.

**Comment by marcoambrosini** [comment]
It would be nice to have both approaches: the ability to quickly select one emoji in a small set and also the possibility to expand it to the full emoji picker

**Comment by jancborchardt** [comment]
> It would be nice to have both approaches: the ability to quickly select one emoji in a small set and also the possibility to expand it to the full emoji picker

@marcoambrosini yep, this is pretty much the approach Signal uses and it’s pretty nice: https://support.signal.org/hc/en-us/articles/360039929972-Message-Reactions
