### ISSUE TITLE
Duplicate call termination message  with Talk Android

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#1924]
The duplicate call termination still occurs in Talk v6.0.2.

![obraz](https://user-images.githubusercontent.com/47037905/59187514-ec18e600-8b75-11e9-9b47-57b5d1859459.png)

The connection was it has been done with the Nextcloud Talk v6.0.7 application.
It happens **only** when the connection is through the Android Talk app.

**Comment by nickvergessen** [comment]
That's a but from the android app and should be fixed in one of the next versions

**Comment by Valdnet** [comment]
OK. I suspected so.
Does @mario know about this error? Should I report it to him?

**Comment by Ivansss** [comment]
@Valdnet He knows about it.
But feel free to open an issue in the [Talk android](https://github.com/nextcloud/talk-android/issues) repository, so you know when he fixes it.
