### ISSUE TITLE
auto scroll current open room into visible area when opening over search

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/spreed#1925]
**Is your feature request related to a problem? Please describe.**
when opening a room over the search you can't be sure if you really are in the correct room because you don't have a visual feedback

**Describe the solution you'd like**
the room list in the sidebar should auto scroll so the opened room comes in to the visible range

cc @jancborchardt @danxuliu

**Comment by nickvergessen** [comment]
Fixed by Vue
