### ISSUE TITLE
Public room feature too hidden?

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/spreed#1927]
Hello,

I just discover that I can't create public room in Nextcloud Talk since i updated to version 16..
It's weird because former public room still works but I can't make a room public for the new one

I'm in Firefox but i check in Chromium also.
When i create a new room, there is no more the "Create a public room"
![image](https://user-images.githubusercontent.com/9005817/60336484-c0cd2e00-99a0-11e9-88ac-5c41b9fc9e99.png)

And in a room, there is share button anymore..
Did I miss something ??
![image](https://user-images.githubusercontent.com/9005817/60336487-c3c81e80-99a0-11e9-8cf2-76efe413493e.png)

## Browser

**Operating system:** Ubuntu 18.04

**Browser name:** Firefox & Chromium last update

## Spreed app

**Spreed app version:**  6.0.2

## Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** Maria

**PHP version:** 7.2.15

**Nextcloud Version:** 16

**Comment by nickvergessen** [comment]
You need to start typing a name for the room.
We changed to with Nextcloud 16, that rooms always need to have a name set.

**Comment by quentinDupont** [comment]
Thanks for your quick answer !
I don't find this very intuitive.

Other thing not intuitive for my collegues was the button "Share the link" (in french anyway) in conversation group.
I think it will be more clear with the name "Make the conversation public" or something like that.

What do you think ? Maybe open a other issue.

**Comment by nickvergessen** [comment]
Let's reopen it for now and think a bit about it.

**Comment by nickvergessen** [comment]
cc @jancborchardt @jenniferpiperek

**Comment by easyfic** [comment]
hi @nickvergessen I'm also confused. And sorry for my silly answer but I don't get how to set now the conversation name. Any help?

**Comment by easyfic** [comment]
ok forget it i found this. that's not intuitive and clear at all. and we can't protect with password anymore? It was so much better before. I totally agree with @quentinDupont

**Comment by jancborchardt** [comment]
Hm, I don’t remember the discussion where we decided to change this, was it in an issue?

So it seems we should have a "New public conversation" entry as the first thing in the list, right?

And the issue in the second screenshot is another one? Being that the share controls are not shown?

**Comment by nickvergessen** [comment]
Which then turns into a "input box asking for the conversation name"?
cc @jenniferpiperek

**Comment by easyfic** [comment]
Maybe you should ask "profane" users about their understanding and ergonomics thoughts before releasing updates. Like your grandmother or daily users.
Sincerely the previous release was so much simple to handle for new users. Now that's not simple at all

**Comment by jancborchardt** [comment]
This is fixed with the upcoming version, where the dialog to create a conversation looks like this :)
![creating conversation](https://user-images.githubusercontent.com/925062/71612120-bcdccb80-2bd0-11ea-92b2-1d712d9fe82c.png)

Was fixed by https://github.com/nextcloud/spreed/pull/2499
