### ISSUE TITLE
Put release info in repo, deactivate wiki

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#193]
We don’t use wikis for apps since then we have info in too many locations. All info should be in the repo, like in a Releasing.md file or so.

@nickvergessen can you transfer the page https://github.com/nextcloud/spreed/wiki/Releasing-an-new-version to that so we can deactivate the wiki?

**Comment by nickvergessen** [comment]
Just to hide it and make it less obvious and clutter the repo with useless stuff that is only for two people? Fine by me, do it.

**Comment by jancborchardt** [comment]
Right, nevermind, we also use it for Calendar and other apps.
