### ISSUE TITLE
Error 404 when clicking on the contributing guidelines

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#1934]
## Steps to reproduce
Open the readme.md and click on the 'guidelines for contributing link at the end of the page

### Expected behaviour
Link brings you to the guidelines for contributing

### Actual behaviour
404 page not found

**Comment by nickvergessen** [comment]
Works fine for me, it links to https://github.com/nextcloud/spreed/blob/master/.github/contributing.md which exists :thinking:

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/commit/0e7ab5471d808bac95312223f645dcbb33fe19b7
