### ISSUE TITLE
API for Bots

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/spreed#1936]
**Desired Feature**
So far I do not see the possibility to have bots/apps that can write messages to conversations (e.g. a gitlab bot which writes messages when a push to a group on pushes to certain projects like in Slack).
Is there already an API? And if not, would it be possible to implement one? I think this would also be useful for others.

**Describe the solution you'd like**
An API for bots/messaging apps, that can then be activated (for example as implemented in Slack)

**Comment by BRadHoc** [comment]
After installing NextCloud and Talk this is the first use-case that I saw as "missing". Had a quick look at the code and thought it might be possible to duplicate some of the room creation for the changelog and change it for bot support.

**Comment by fti7** [comment]
Check my Issue regarding Webhook Support:
https://github.com/nextcloud/spreed/issues/1879

**Comment by boppy** [comment]
Since this is Backlog'ed, I've created a (minimalistic) Node.js Module to provide bot functions to Nextcloud Talk: [github repo](https://github.com/boppy/nextcloud-talk-bot), [npm repo](https://www.npmjs.com/package/nextcloud-talk-bot).

**Comment by nickvergessen** [comment]
Webhook based bots are available in the upcoming Nextcloud 27.1 with Talk 17.1
Preview versions of both are already available, detailed documentation can be found at https://nextcloud-talk.readthedocs.io/en/latest/bots/

Please let us know if you need any help with the API or have any questions on the usage
