### ISSUE TITLE
Multi-line input overlaps latest messages

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#1938]
## Steps to reproduce
1. Open a chat with a long history
2. Type a new message
3. Press Shift+Enter
4. Type more text
5. See the input expand

### Expected behaviour
The message history shrinks and I can still see the latest messages at the bottom

### Actual behaviour
The growing input overlaps the latest messages and I have to manually scroll down to see them

## Browser

**Microphone available:** n/a

**Camera available:** n/a

**Operating system:** I use Arch btw

**Browser name:** FF

**Browser version:** 67.0.4

### Browser log

n/a

## Spreed app

Company cloud

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2019-07-02 08-46-55](https://user-images.githubusercontent.com/1374172/60490027-03934c80-9ca6-11e9-897d-dc9ad15af2f7.png)

---

![Bildschirmfoto von 2019-07-02 08-47-14](https://user-images.githubusercontent.com/1374172/60490026-03934c80-9ca6-11e9-9728-4d1233569d6b.png)

**Comment by nickvergessen** [comment]
@ma12-co maybe you want to look into this?

**Comment by ma12-co** [comment]
Sure @nickvergessen!
