### ISSUE TITLE
Closing another conversation while in a call break everything

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#1943]
## Steps to reproduce
1. Create a chat room from a file sidebar
2. open talk app
2. Start a call, and while you're in the call, try deleting another conversation from the navigation left section 

### Expected behaviour
Tell us what should happen

### Actual behaviour
See the chat take full content width
Call button still says you're in a call (leave call)
Deleted conversation disappear, then after a few sec appear again

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** I use Arch btw

**Browser name:** Chromium 

**Browser version:** 75.0.3770.100

**Comment by nickvergessen** [comment]
did you perform 2. in a different tab, or how did you manage to be able to try to delete a conversation from the file sidebar?

**Comment by skjnldsv** [comment]
Same tab while in the call

**Comment by skjnldsv** [comment]
> how did you manage to be able to try to delete a conversation from the file sidebar?

Sorry, navigation, not sidebar!

**Comment by nickvergessen** [comment]
So:
1. Create a sidebar call on file.txt
2. Move to talk app
3. Join call on file.txt
4. Delete group conversation "holiday"
?

**Comment by skjnldsv** [comment]
Damn, i'm terrible at this, sorry. :see_no_evil: 
3. Join holiday call
4. delete file.txt conversation

**Comment by fancycode** [comment]
This is a bug in the external signaling server which will disconnect all sessions of a user if he is disinvited from any room. Will be fixed in the next release.

**Comment by fancycode** [comment]
@Ivansss could you please verify the change in the signaling server?

**Comment by danxuliu** [comment]
I can reproduce it with the 0.0.9 version of the signaling server but not with the 0.0.10 version, so... fixed :-) Thanks @fancycode!

**Comment by fancycode** [comment]
Great, thanks for confirming.
