### ISSUE TITLE
Video not connecting

### ISSUE THREAD

**Issue by influenist** [nextcloud/spreed#1966]
## Steps to reproduce
1. Setup Talk on both Android devices
2. Start video call from either client
3. Video call initiated correctly, yet no video connection is made. After hang up from initiator side, call shows "duration". Yet no video connection has been made.

### Expected behaviour
Video call with sound

### Actual behaviour
Black screen, no connection

## Browser
NC official Android app 

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Xiaomi / Android

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
Latest

**Custom TURN server configured:**no
**Custom STUN server configured:**no

## Server configuration

**Operating system**: Centos

**Web server:**Nginx

**Database:**Maria

**PHP version:**

**Nextcloud Version:** latest

**List of activated apps:**

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_antivirus: 2.1.1
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - keeporsweep: 0.2.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - phonetrack: 0.5.2
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - ransomware_protection: 1.4.0
  - recommendations: 0.4.0
  - scanner: 0.1.4
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - weather: 1.6.1
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/xxxx\/nextcloud",
        "dbtype": "mysql",
        "version": "16.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "log_type": "nextcloud",
        "logfile": "[datadirectory]\/nextcloud.log",
        "loglevel": "2",
        "logdateformat": "M d H:i:s",
        "maintenance": false,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie"
        ],
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_scale_factor": 2,
        "filesystem_check_changes": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "tempdirectory": "\/tmp\/nextcloudtemp",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "spreed"
        ]
    }
}

**Comment by nickvergessen** [comment]
I guess you need a turn server when using it with the mobile apps.

**Comment by influenist** [comment]
The readme is very limited ... Let's quote:

> Nextcloud Talk is really easy to install. You just need to enable the app from the Nextcloud App Store and **everything** will work **out of the box**.

Yet then you mention a TURN server, with a script which is only tested with Ubuntu. CentOS clearly not supported nor does the settings menu from Nextcloud settings page give any info on this matter (it shows a pre-filled in TURN server which doesn't work). Also the script has no readme what so ever.
