### ISSUE TITLE
Talk Signal server doc ? 

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/spreed#1967]
Hi everyone i know there is a turn/stun doc but i did not found the signal server doc. 
![Screenshot_20190709_121224](https://user-images.githubusercontent.com/38983960/60879912-e977e200-a242-11e9-95ae-ff14e9beab49.png)
 
Best regards

**Comment by nickvergessen** [comment]
The signaling server comes with the Nextcloud Talk subscription.
Small setups work fine without it, if you need to have a call with a lot of people at the same time, please see the following website for more information:
https://nextcloud.com/talk/
