### ISSUE TITLE
Multiple Duplicate Indistinguishable "Initiate Call" Buttons in Sidebar

### ISSUE THREAD

**Issue by gohrner** [nextcloud/spreed#1990]
(It googled this issue and searched here in the issue tracker, but could not find any reference to it so far.)

## Steps to reproduce
1. Open the Favorites in Nextcloud Files
2. Click a Favorite's icon to show the sidebar
3. Click "Chat" in the side bar
4. Repeatedly click the icons of different Favorites to toggle the sidebar between them

### Expected behaviour
Not sure what the "Chat" tab in the sidebar is supposed to show, but surely not several identically named buttons which cannot be distinguished from one another.

### Actual behaviour
At step 3:

For basically every file, there will be three or four "Initiate call" buttons at first. Huh?

After step 4:

Every time you switch to another Favorite, the number of buttons increases. See screenshot...

![image](https://user-images.githubusercontent.com/26199042/61170830-12fc7a80-a56f-11e9-8726-a1094ad305d2.png)

## Spreed app

**Spreed app version:** 5.0.4

**Operating system**: Debian 9 Stretch

**Nextcloud Version:** 15.0.10

**List of activated apps:** 

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - dav: 1.8.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.1.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - nextcloud_announcements: 1.4.0
  - notes: 3.0.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - richdocuments: 3.3.13
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - spreed: 5.0.4
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
</details>

### Server log (data/nextcloud.log)
Nothing related, just the omni-present avatar-image related errors: (Possibly Issue #8635)
<details>
{"reqId":"rr4kisoNw7BP4fqiQCZ7","level":3,"time":"2019-07-13T08:18:39+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.png): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_6\/5.11.2 Safari\/534.34","version":"15.0.10.0"}
{"reqId":"mbvF8m7rlFgbPqs6lpZd","level":3,"time":"2019-07-13T08:18:58+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"OPTIONS","url":"\/remote.php\/dav\/calendars\/MY-USER\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.jpg): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Thunderbird\/60.7.1 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"XP1avoNK5oKGBMldaEKG","level":3,"time":"2019-07-13T08:18:59+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"OPTIONS","url":"\/remote.php\/dav\/calendars\/MY-USER\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.png): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Thunderbird\/60.7.1 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"Ctoxkrv71V3IJwP5EnBm","level":3,"time":"2019-07-13T08:18:59+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/calendars\/MY-USER\/xdis-termine\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.png): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Thunderbird\/60.7.1 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"kRdYjSdssfNduKQyztlO","level":3,"time":"2019-07-13T08:19:34+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/MY-USER\/OIT%20Verwaltung\/","message":"file_get_contents(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.jpg): failed to open stream: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#217","userAgent":"Thunderbird CardBook\/36.5 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"kRdYjSdssfNduKQyztlO","level":3,"time":"2019-07-13T08:19:34+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/MY-USER\/OIT%20Verwaltung\/","message":"stat(): stat failed for \/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.jpg at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#143","userAgent":"Thunderbird CardBook\/36.5 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"DTs0vNBOD9agE0cepThx","level":3,"time":"2019-07-13T08:19:38+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/MY-USER\/xdis-termine\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/generated): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Thunderbird\/60.7.1 Lightning\/6.2.7.1","version":"15.0.10.0"}
{"reqId":"GaTbSs73gPEMsGo4wbaG","level":3,"time":"2019-07-13T09:48:26+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.jpg): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_6\/5.11.2 Safari\/534.34","version":"15.0.10.0"}
{"reqId":"XhBx0LQNDg3bGDpLnFmk","level":3,"time":"2019-07-13T09:48:30+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/principals\/users\/MY-USER\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.jpg): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_6\/5.11.2 Safari\/534.34","version":"15.0.10.0"}
{"reqId":"t6XDTlDvjrH94QTyj7ab","level":3,"time":"2019-07-13T09:48:30+00:00","remoteAddr":"XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX","user":"MY-USER","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/principals\/users\/MY-USER\/","message":"unlink(\/mnt\/cstore\/nextcloud_data\/appdata_XXXXXXXXX\/avatar\/MY-USER\/avatar.png): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_6\/5.11.2 Safari\/534.34","version":"15.0.10.0"}
</details>

**Comment by nickvergessen** [comment]
Should be solved with the new Vue frontend
