### ISSUE TITLE
Add input fields for configuration page

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#2]
- [x] STUN
- [x] TURN

**Comment by jancborchardt** [comment]
@fancycode do you also want to do the TURN part of this issue? :)

**Comment by jancborchardt** [comment]
(Let me know if you need HTML/CSS help.)

**Comment by fancycode** [comment]
@jancborchardt that was the plan :) For TURN we should have a per-app configuration and also a per-user configuration.

**Comment by jancborchardt** [comment]
Ah cool. By the way, it would be nice to have a »Reset to default« icon-button as we have in theming to reset to that Google STUN server. :)

**Comment by jancborchardt** [comment]
TURN fixed by #84
