### ISSUE TITLE
Improve the way of opening attached pictures (and videos)

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/spreed#2002]
**Is your feature request related to a problem? Please describe.**
If someone sends you a picture in the chat and you click it, you are redirected to the "files" from where you view the picture. Same for video files. You get a small thumbnail showing you what the picture is but to view it in full, you have to go through files.

**Describe the solution you'd like**
The workflow would be much faster if the user was able to view pictures from within the chat, that is - click the picture and it appears on the screen (hovering above the chat). Close it and continue chatting. For videos, render a thumbnail in the chat area (currently no thumbnail is visible) and when clicked, play the video as an overlay the same way.

Some quick designs of what I mean:

![Web 1920 – 1](https://user-images.githubusercontent.com/36133540/61282384-8692c780-a7bb-11e9-8c0f-f9f8a8201aa8.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/36133540/61282383-8692c780-a7bb-11e9-9eac-4b0af2a92315.png)

**Comment by nickvergessen** [comment]
We plan to use the viewer app from the files list after #1811  and #1347

**Comment by szaimen** [comment]
https://github.com/nextcloud/viewer/pull/271 is merged so the viewer app is ready now. :)

**Comment by nickvergessen** [comment]
#1811  is in, and #2778 is on the way
