### ISSUE TITLE
Access denied to public room links, when app is limited to a group

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/spreed#201]
I have most of my apps set to only show to the admin group, so my family isn't confused by seeing various random apps I'm tinkering with on my server. This includes the Spreed app which is set to be visible just to the admin group.

When I, as an admin, log in though and create a public room link, anyone clicking on that link gets shown a Nextcloud error page saying that they don't have permission to access this page.

On the one hand I understand, I mean I *did* say t limit Spreed to the admin group. On the other hand I, as an admin user with full access rights, chose to make a room available to the world and Spreed doesn't let me.

Is there any way we can make an exception, so public rooms can be made available by authorized group members?

**Comment by nickvergessen** [comment]
No, because when the app is only available to some users, it is not even loaded for others.
That is nothing in control of the spreed app.

Fix is to remove the restriction.

I guess we should make use of [`prevent_group_restriction`](https://docs.nextcloud.com/server/11/developer_manual/app/info.html#types) Otherwise you can call people and neither you nor them ever notice it.

**Comment by Bugsbane** [comment]
Rather than completely removing people's ability to make Spreed available to specific groups, I suggest we only remove the ability to create "public" (*cough*) links when the app is group limited.

That way, we remove the confusion and links going to error pages, but retain people's ability to keep the app available to specific groups.

**Comment by nickvergessen** [comment]
Well but you can still try to call people, which don't have access to the app. And you have no way of knowing this.
That's why I think it's okay to remove the restriction.
