### ISSUE TITLE
Not all links are recognized properly

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/spreed#2022]
## Steps to reproduce
1. Post multiple links in one message

### Expected behaviour
All links are recognised correctly

### Actual behaviour
Not all links are recognised correctly
![7F6A4CB2-0E6D-4FD5-9463-AD8F090C9380](https://user-images.githubusercontent.com/1250540/61578822-d09de500-aafc-11e9-9fed-58b489b3ba4a.png)

## Browser

Reproducible in Safari, Firefox, ...

### Browser log

No error messages

Nextcloud 16.0.3, latest Spreed (c.nc.com)

**Comment by nickvergessen** [comment]
Can you check master? The regex was replaced there

**Comment by georgehrke** [comment]
![8791B186-215D-4F75-88DF-85C4BAFB0767](https://user-images.githubusercontent.com/1250540/61579622-f977a780-ab07-11e9-94b8-f95a7beece66.png)

Same behaviour
