### ISSUE TITLE
Archive chat histories in Nextcloud files

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2036]
I just saw this at one of the well known video conferencing tools.

After a meeting was finished the chat history was saved as a text file to a folder on my desktop.

Maybe a similar feature would be nice for Nextcloud talk? Saving the chat history in a folder like `Talk Archive/<date>-<room-name>.txt` if the user leaves a room. This way they can later always look up the history.

**Comment by nickvergessen** [comment]
This is a duplicate

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/232
