### ISSUE TITLE
Unify wording

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#204]
Only use one of:
* **call(s)**
* room(s)

And:
* **participant** ("Waiting for others" in empty room etc.)
* person ("Add person" in call menu)

"Unprofessional" strings for business context:
* "Time to call your friends"

@jancborchardt do you agree with the highlighted ones being the "goto" strings

**Comment by jancborchardt** [comment]
I’d say to use the more human »person« and simply »Waiting for others« as well as »Time to call someone«. And »Call« is good, yes.
