### ISSUE TITLE
Talk in Firefox browser Switches to 'waiting for others to join' in less than 10 seconds while typing

### ISSUE THREAD

**Issue by andrewbauman** [nextcloud/spreed#2049]
## Steps to reproduce
1. open talk on browser
2. start typing and pause for 3 seconds to reflect
3. waiting for others message destroys the half composed message.

### Expected behaviour
while typing a message we do not overwrite the text.

### Actual behaviour
we type messages multiple times before we manage to do it fast enough not to get swiped.

## Browser

**Microphone available:**no

**Camera available:** /no

**Operating system:** Windows/Ubuntu/ both

**Browser name:** Firefox old and current versions

**Browser version:** 60.01

**Comment by nickvergessen** [comment]
The sounds like a general problem with your server. If you still face this issue, reopen it with the logs that are requested when you try to report a bug. With the given information we can not do anything here.
