### ISSUE TITLE
Focus input field when selecting a conversation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2062]
## Steps to reproduce
1. Click on a conversation
2. Want to type a message
3. Have to click the input field on the bottom too

### Expected behaviour
The input field could be focused automatically.

What do you think @nextcloud/designers? I’m thinking if it makes sense to check if you’re on mobile and prevent it there, but is that worth it?

@nickvergessen @Ivansss if you state where this has to be changed, then I’d say this is a perfect good first issue. :)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blame/master/js/views/chatview.js#L253

This should already be the case, but I guess the size check broke at some point?

**Comment by danxuliu** [comment]
> This should already be the case, but I guess the size check broke at some point?

I have tested in _master_ and _stable16_ and it works as expected.

@jancborchardt For further information about why the input is not focused when the window height is < 768 please see #1726 and #1737.

**Comment by jancborchardt** [comment]
Instead of checking via screen size, is there a capability to check if a hardware keyboard exists? Or what’s the best practice here? (Seems odd to use screen size as it’s prone to errors?)

**Comment by nickvergessen** [comment]
Done in VueJS now.
