### ISSUE TITLE
Default setting for notifications

### ISSUE THREAD

**Issue by OliverNel** [nextcloud/spreed#2069]
**Default setting for notifications**
includes a place where you can set the default notification settings form groups and chats

**Comment by jakobroehrl** [comment]
Is this already possible in config file or so?

**Comment by Dubidubiduu** [comment]
Need default e-mail notification on daily basis for messages. Otherwise I send users messages and they don't know about cuz they haven't installed the smartphone app yet.

**Comment by jakobroehrl** [comment]
@nickvergessen 
How hard is this to do? Could you help a little bit?
I think I could implement the admin setting. 
Where do I have to set the notification for the user when it is assigning to a new group?
Room.php oder RoomController? Thanks

**Comment by nickvergessen** [comment]
Shouldn't be too hard. I can post some steps tomorrow

**Comment by nickvergessen** [comment]
Let's start of with an admin setting:

## Admin setting
Check the following files:
*  "copy" the code from `start_call` in `lib/Settings/Admin/GeneralSettings.php`
https://github.com/nextcloud/spreed/blob/5ab5ff47b8ec489739de70357a865462a4d6fd4c/lib/Settings/Admin/GeneralSettings.php#L49
* in `src/views/AdminSettings/GeneralSettings.vue` add a UI with the options Never/On mention/Always
https://github.com/nextcloud/spreed/blob/58e9e69a07c0d3524da1d8c10d88f241ab90ccc1/src/views/AdminSettings/GeneralSettings.vue#L27-L40

## Using the setting
* In the RoomController.php we need to check for the default value (like we do now) and show the picked admin setting instead, so read the config there with default falling back to the current value: https://github.com/nextcloud/spreed/blob/76709508b8c98d58d92885a99a93423059752d4e/lib/Controller/RoomController.php#L247
* More difficult is the notification handling: https://github.com/nextcloud/spreed/blob/d4fc586f1a796b8cb19cff543b668470556e44b2/lib/Chat/Notifier.php#L181-L182 
You need to modify this to read all users based on the admin setting in case it is always.
* In case the default is set to not notify on mention, https://github.com/nextcloud/spreed/blob/d4fc586f1a796b8cb19cff543b668470556e44b2/lib/Chat/Notifier.php#L330 also needs adjusting
