### ISSUE TITLE
Open Talk in a new tab

### ISSUE THREAD

**Issue by Almiraat** [nextcloud/spreed#2071]
**Is your feature request related to a problem? Please describe.**
Talk opens in the same tab as Files which is not convenient if you need to check back and forth.

**Describe the solution you'd like**
Make Talk open in a new tab.

**Comment by nickvergessen** [comment]
Same applies for Mail, Calendar and everything else.
It heavily depends on your way of working, so browser developers allowed you to choose with 2 options:
* Use right-click > "Open in new tab"
* Press `CTRL` while clicking on the Talk icon.
