### ISSUE TITLE
Show name of guest in notification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2074]
## Steps to reproduce
1. Have a chat which includes a guest who set a name for themselves
2. Get mentioned by that guest
3. Check the notification

### Expected behaviour
The notification says something like

> Marco mentioned you in **💬 Talk team public**

### Actual behaviour
It says

> A guest mentioned you in **💬 Talk team public**

![Ability to click links in notifications](https://user-images.githubusercontent.com/925062/62782220-11649a80-baba-11e9-8343-dfb532ab3858.png)

@nickvergessen I guess with pointers to where in the code it needs to be adjusted, this might also be a good first issue? :)

**Comment by nickvergessen** [comment]
I tried, but the unit tests are too messy so I just did it completly, see #2104
