### ISSUE TITLE
Add the possibility to like single messages

### ISSUE THREAD

**Issue by errotu** [nextcloud/spreed#2083]
**Is your feature request related to a problem? Please describe.**
In our organization it has come up that a solution for showing approval to a particular suggestion would be appreciated. In particular in bigger groups it might make sense not to urge everyone to write a message with regard to a proposition.

**Describe the solution you'd like**
A possibility to "like" a particular message in a (group) chat.

**Describe alternatives you've considered**
Text messages by every member of the group approving a suggestion. But this could lead quickly to spamming in a group chat.

**Comment by nickvergessen** [comment]
Duplicate of #1920
