### ISSUE TITLE
Change the default behaviour of notifications in group messages

### ISSUE THREAD

**Issue by errotu** [nextcloud/spreed#2085]
**Is your feature request related to a problem? Please describe.**
In most messengers (e.g. Telegram, Whatsapp etc.) the default-option for notifications is to be notified whenever a new message is sent to a group chat. Being notified in Nextcloud Talk (by default) only when you are mentioned is therefore counter-intuitive and can lead to the non-reading of messages.

**Describe the solution you'd like**
Either (1) change the default notification behaviour to "Always notify" and/or (2) give the user the possibility to set the default notification level in its own settings and/or (3) give the admin an option to set the default notification level in group messages system-wide.

**Describe alternatives you've considered**
The alternative is the current situation in which the notification level needs to be changed repeatedly in every single group message.

**Comment by nickvergessen** [comment]
I think the best way for now would be an admin wide setting. It heavily depends on whther you have Slack or Whatsapp in mind while looking at Talk, and that would basically allow setting the usecase for your instance.

**Comment by jancborchardt** [comment]
If we do it, it should absolutely be a user-specific setting (introducing a bottom left settings area). The admin should not decide a default for something as personal as notifications, no?

**Comment by manu-p** [comment]
Hi all, whether it's a global or user decision any idea of an implementation date?
Meanwhile, is there something that can be done at the database or code level to "patch" this behaviour, knowing this would need to be patched again after each upgrade?
Thanks

**Comment by nickvergessen** [comment]
What would you like to have as a default level?

**Comment by manu-p** [comment]
Hi @nickvergessen thanks for your interest. 

Always notify would be our default choice.

Thanks!

**Comment by manu-p** [comment]
Hi, has it to do with the **notification_level** column in the **oc_talk_participants** table?

And so, which value is for "notify on @-mention" that could then be SQL updated to the value for "always notify"?

**Comment by nickvergessen** [comment]
`1`

**Comment by manu-p** [comment]
Sorry @nickvergessen, I don't clearly understand what is this 1 for. 
Is it the notification_level value for @-mention?
If so, what's the value for always notify?
Thanks.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/master/lib/Participant.php#L44-L47

**Comment by manu-p** [comment]
Cool @nickvergessen thanks!

**Comment by manu-p** [comment]
Next step is to be able to select/set default notification in code or admin interface.

**Comment by tigermick** [comment]
@manu-p 
I'm looking for the same problem.
your solution is a SQL command to modify notification_level value ?
If yes, can you give me your SQL command please ?

**Comment by manu-p** [comment]
@tigermick 
Here it is: `UPDATE oc_talk_participants SET notification_level = 1 WHERE notification_level IN (0,2)`
You can try to put it en 'event' or 'trigger' depending on your MySQL possibilities, or in a cron job.

**Comment by tigermick** [comment]
@manu-p thanks
I have try and it doesn't work ... when i begin a new conversation, all people have "notification when you are mentionned" in "conversation info."

**Comment by manu-p** [comment]
@tigermick I guess you don't know much about SQL and IT prod, don't you? 

The UPDATE statement I put before is not a solution, a workaround would sound better. It changes (UPDATE) all notification levels as of 0 (default) and 2 (mention) to 1 (always) for all on existing conversations.

So, it needs to be run quite often, and that's the meaning of the 'event' and 'trigger' things I mentioned, which are MySQL/MariaDB features (depending on MySQL implementations), or a cron job on Linux systems.

**Comment by tigermick** [comment]
@manu-p you are right. I am not used to work with SQL.
My English isn't so good too ... I thought your UPDATE SQL command allowed to start new conversation with "notification for all message" automatically.
Thank you about that clarification.

**Comment by tigermick** [comment]
@manu-p I just tested now and that works fine ;) I 'm going to see to add this SQL command in a script.
