### ISSUE TITLE
Talk doesn't detect group folders

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2088]
## Steps to reproduce
1. Create a group folder
1. navigate to the group folder
2. Open the right sidebar and go to the chat tab
3. see screenshot

![image](https://user-images.githubusercontent.com/1589737/63222715-8cf5d400-c1ab-11e9-8526-48bd1ba0a7f4.png)

### Expected behavior
I'm able to start chatting with the other people who have access to the group folder. 

### Actual behavior
Talk ask me to share the folder with another user before I can start chatting

**Comment by nickvergessen** [comment]
Yeah, atm we only check if the item is shared...
