### ISSUE TITLE
Enhance the app's summary

### ISSUE THREAD

**Issue by sushidave** [nextcloud/spreed#209]
Current app summary:

"Voice over IP conferencing using WebRTC"

Proposal:

"
Experimental video conferencing app for Nextcloud, using Voice over IP and WebRTC (supported by selected browsers and platforms only). For one-to-one and group calls with up to about 6 participants. Public calls with participants who don't have a Nextcloud account.
- [Documentation for users](https://github.com/nextcloud/spreed/wiki/)
- [Visit website](https://github.com/nextcloud/spreed/)
- [Report a bug](https://github.com/nextcloud/spreed/issues/)
"

**Comment by jancborchardt** [comment]
Awesome @sushidave! :) Which version are you referring to though? The summary was improved in a recent version to what is now at https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml :)

**Comment by nickvergessen** [comment]
Closing as per above.

We just need to publish a new version to the app store so this gets live.

**Comment by sushidave** [comment]
@jancborchardt I was referring to version 1.1.2 and it seems as if I was too quick and too late at the same time :o) PS: Thank you for the invitation!
