### ISSUE TITLE
Show that a user is typing

### ISSUE THREAD

**Issue by cbacit** [nextcloud/spreed#2094]
**Is your feature request related to a problem? Please describe.**

When users are typing it would be great to see when they are typing.  Or even show when a users reads the message.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
I think typing is not really feasable performancewise.

Read status is dealt with in https://github.com/nextcloud/spreed/issues/1012

**Comment by medworthy** [comment]
Currently I am using Riot.im to host meetings. Within Riot there is an indicator (within the input field) that will display when an user is typing. Due having fairly free form meetings, this indicator helps percipients to uphold a form of etiquette (ie. allows percipients to wait until the current typist finishes typing before those percipients provide further replies).

I am also using a XMPP framework for personal purposes and various XMPP / Jabber clients also provide a similar typing indicator.

One of the features that would encourage me to move from Riot and start using Nextcloud Talk within a production scenario would be the inclusion of a typing indicator.

**Comment by nickvergessen** [comment]
A simple 👍  on the original report is enough 😎

**Comment by ladrua** [comment]
I guess it would require the use of websocet?

**Comment by nickvergessen** [comment]
Yeah, which we have with the external signaling backend.
Then again, the question is when to do this, only in 1-1 chats? Also in group chats? What should happen if multiple people type, ...

**Comment by nickvergessen** [comment]
Implemented with #9248
