### ISSUE TITLE
Allow video to be fullscreen in video call or screenshare

### ISSUE THREAD

**Issue by adam-tibbetts** [nextcloud/spreed#2112]
I'd like to be able to use the Screensharing functionality to show clients my design work, and it's really not ideal that they can't watch the screenshare in full screen.

Ideally, there'd be some way to collapse the list of call participants along the bottom of the screen, allowing the video to expand to fit the entire screen.

![Screen Shot 2019-08-25 at 6 58 58 PM](https://user-images.githubusercontent.com/5972063/63659066-3117e600-c77d-11e9-8970-c22f595cf717.png)
You can see in the screenshot how much screen is wasted in this screenshot, and it's also not too pretty.

**Comment by nickvergessen** [comment]
Will be part of #1056
