### ISSUE TITLE
Offer an chrome app 

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#2113]
So Chrome has a new, cool chrome apps concept. Some screenshots for how it is implemented for Discourse (help.nextcloud.com):

![Screenshot_20190826_095511](https://user-images.githubusercontent.com/551757/63674843-bd5ef300-c7e7-11e9-8346-4930f1585dcd.png)
![Screenshot_20190826_095105](https://user-images.githubusercontent.com/551757/63674844-bd5ef300-c7e7-11e9-963f-de48a8b9eafe.png)

Developer documentation:

https://developer.chrome.com/apps/about_apps

**Comment by nickvergessen** [comment]
> Important: Chrome will be removing support for Chrome Apps on Windows, Mac, and Linux. Chrome OS will continue to support Chrome Apps. Additionally, Chrome and the Web Store will continue to support extensions on all platforms. Read the announcement and learn more about migrating your app. 

From your link. Also it's the same as with an electron client. It basically means we have to maintain an even bigger range of features and test 2 ways of the same thing. So I will close this for now.
