### ISSUE TITLE
Voice Message

### ISSUE THREAD

**Issue by facb69** [nextcloud/spreed#2120]
I'm just trying to replace whatsapp with Talk. 
Two problems so far:
1) The lack of voice message;
2) The impossibility to send file outside Nextcloud.
The rest is very nice and I use it in regular basis.
Don't know if this is the right place to ask this. If it's not, sorry in advance.

**Comment by nickvergessen** [comment]
Issues for both already exist

**Comment by nickvergessen** [comment]
Searching for "voice message" brings up 4 issues:
https://github.com/nextcloud/spreed/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+voice+message

the first one is exactly what you want: #1576 

Searching for "send file" brings up 7 issues
https://github.com/nextcloud/spreed/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+send+file

the second oldest one is what you want: #1129

Maybe you searched with different strings then you used in your report?
