### ISSUE TITLE
Possible to make work over Tor?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#213]
It doesn’t seem to work when using the Tor browser bundle. Is it somehow possible to make that happen or just not feasible?

cc @nextcloud/spreed

**Comment by leonklingele** [comment]
If you enable WebRTC in Tor, then yes, it should work. But please be aware that enabling WebRTC will cause your browser to leak various details about your network (e.g. its internal IP). Generally speaking you should never do this (or only whitelist a specific domain)

**Comment by nickvergessen** [comment]
So nothing we can do
