### ISSUE TITLE
Show volume indicator in other colours when speaking while muted

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#2138]
[The volume indicator for the local audio added in Talk 7](https://github.com/nextcloud/spreed/pull/2021) is [now](https://github.com/nextcloud/spreed/pull/2016) shown too when the audio is disabled. This is useful to let the user check that the microphone is working, as well as to give immediate feedback about been talking while muted even before the warning is shown.

However, currently the same colours are used when the audio is enabled and when the audio is disabled.
![Volume-Bar-Muted-Current](https://user-images.githubusercontent.com/26858233/64005786-5015cf80-cb11-11e9-995a-fb1d2e7d7fdf.png)

I have been testing with different colour combinations and I think that monochrome or grey scale bar look the best (and clearly convey the "disabled" state):
White:
![Volume-Bar-Muted-White](https://user-images.githubusercontent.com/26858233/64006274-4771c900-cb12-11e9-87ee-dbcf0d8da088.png)

Grey:
![Volume-Bar-Muted-Grey](https://user-images.githubusercontent.com/26858233/64006178-12fe0d00-cb12-11e9-9b9e-0d9f6abd7332.png)

(Almost) Black to white:
![Volume-Bar-Muted-Almost-Black-To-White](https://user-images.githubusercontent.com/26858233/64006016-c6b2cd00-cb11-11e9-8293-617728d5bfd4.png)

Grey to white:
![Volume-Bar-Muted-Grey-To-White](https://user-images.githubusercontent.com/26858233/64006233-31640880-cb12-11e9-8e79-d70bb906a761.png)

In a static image I think that almost black to white looks the best, but in practice I think that an all white is the best (or grey to white, but the gradient is negligible), because low volumes are still clearly shown (with the almost black to white it is difficult to see them due to the background).

If it had to have a colour I would use blue to cyan:
![Volume-Bar-Muted-Blue-To-Cyan](https://user-images.githubusercontent.com/26858233/64006031-d16d6200-cb11-11e9-9ad9-5593c933ab0f.png)

Other colours, or mixing white/grey with a colour do not look good in my opinion:
Blue to white:
![Volume-Bar-Muted-Blue-To-White](https://user-images.githubusercontent.com/26858233/64006069-e5b15f00-cb11-11e9-9aa0-a4bd814b950b.png)

Blue to grey:
![Volume-Bar-Muted-Blue-To-Grey](https://user-images.githubusercontent.com/26858233/64006048-dcc08d80-cb11-11e9-94fc-4cb46f9bf00c.png)

Cyan to white:
![Volume-Bar-Muted-Cyan-To-White](https://user-images.githubusercontent.com/26858233/64006158-0bd6ff00-cb12-11e9-84e5-e9a825ef4b60.png)

Cyan to grey:
![Volume-Bar-Muted-Cyan-To-Grey](https://user-images.githubusercontent.com/26858233/64006078-ec3fd680-cb11-11e9-8732-51d36d894a23.png)

Grey to blue:
![Volume-Bar-Muted-Grey-To-Blue](https://user-images.githubusercontent.com/26858233/64006209-25784680-cb12-11e9-8049-a10f18e21cbc.png)

Grey to cyan:
![Volume-Bar-Muted-Grey-To-Cyan](https://user-images.githubusercontent.com/26858233/64006217-2b6e2780-cb12-11e9-90b3-3dabcf94235b.png)

Inverted:
![Volume-Bar-Muted-Inverted](https://user-images.githubusercontent.com/26858233/64006256-39bc4380-cb12-11e9-885f-eb9f63ee6c77.png)

Cyan to magenta:
![Volume-Bar-Muted-Cyan-To-Magenta](https://user-images.githubusercontent.com/26858233/64006103-f530a800-cb11-11e9-9d2c-539c3116e9a9.png)

Magenta to cyan:
![Volume-Bar-Muted-Magenta-To-Cyan](https://user-images.githubusercontent.com/26858233/64006261-3e80f780-cb12-11e9-87ec-ce99194a1c6e.png)

You can test all this yourself by adding this to the end of [_css/video.css_](https://github.com/nextcloud/spreed/blob/0e9dc43640719df7d45e4556ada9d20ae0bead94/css/video.scss#L475):
```
#muteWrapper .icon-audio-off + .volume-indicator {
	background: linear-gradient(0deg, #222, white 36px);
}
```

@nextcloud/designers Opinions?

**Comment by Ivansss** [comment]
I would go with "gray to white" when muted.

**Comment by skjnldsv** [comment]
Can't we fill the muted icon directly?
Not sure a gradient is needed to be honest.
I'd go with an opacity filler from bottom to top.

![vcfdsfd](https://user-images.githubusercontent.com/14975046/64008271-12677580-cb16-11e9-9af4-ef319c8dd06e.png)

**Comment by nickvergessen** [comment]
> Can't we fill the muted icon directly?

Different story I'd say.

Personally I would prefer blue-to-cyan
Second favorite is gray-to-white

**Comment by jancborchardt** [comment]
I would also fill the icon directly as @skjnldsv says, as the bar looks a bit out of place and you don’t immediately know what it’s for either.

But since @nickvergessen said it’s a different story:
- Agree grey to white is good
- If we put it _below_ the icon and make it left to right instead of bottom to top then it’s more clear it belongs to the audio icon.
