### ISSUE TITLE
Black video feed when joining public call with Safari on macOS, no feedback

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#214]
Joining a call shared via link with Safari on macOS shows this:
![sharedcall](https://cloud.githubusercontent.com/assets/925062/21997962/715e3194-dc32-11e6-8613-fd94b6372403.jpeg)

No feedback, just black screen. No notice of it not working. Any idea @nextcloud/spreed @nextcloud/mac?

**Comment by sushidave** [comment]
@jancborchardt I see two issues here:
1) Safari does not support WebRTC yet, see #154 
2) No error message displayed

**Comment by jancborchardt** [comment]
@sushidave aah, I thought it was only iOS! So on Safari desktop, the message »WebRTC doesn’t work in your browser yet« should be displayed too for sure. cc @LukasReschke

**Comment by nickvergessen** [comment]
@Ivansss you know whether there is a check so we can display "sorry your browser is not supported"?

**Comment by nickvergessen** [comment]
@jancborchardt same issue like with firefox maybe,
what does `navigator.userAgent` return?
