### ISSUE TITLE
Missing notification for other users when mentioning a guest

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#2141]
When sending a chat message with multiple mentions in it and one of them is a guest mention, other participants won't get any mention notification.

<img width="218" alt="Screenshot 2019-08-30 at 17 06 34" src="https://user-images.githubusercontent.com/4638605/64031752-5a53c000-cb49-11e9-879e-c5d6e9b97f7c.png">

In this case, user "Ivan" won't be notified.
Related: https://github.com/nextcloud/spreed/pull/1974

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/16968

But since then guest is a valid/known type, we can use this more
