### ISSUE TITLE
Some errors on Firefox

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#215]
Seems it was broken on Firefox recently? cc @nextcloud/spreed any idea?
![spreedissue](https://cloud.githubusercontent.com/assets/925062/21998198/ac262a74-dc33-11e6-86b9-acd699336d27.png)
![spreed error](https://cloud.githubusercontent.com/assets/925062/21998200/ac612174-dc33-11e6-97cd-cb7762d8a7c7.png)
That was on our cloud.nc instance just now.

**Comment by nickvergessen** [comment]
Is it really necessary to ping 10 people by mentioning a group?

It worked fine in FF when we tried it with 4 people this afternoon. So please provide the information of the issue template:
* Browser (including version)
* Copy+paste the log so we can actually use it
* Steps that have been made to "break" it

**Comment by jancborchardt** [comment]
> Is it really necessary to ping 10 people by mentioning a group?

That’s what the groups are for.


Browser FF 50.1.0

This is the log exactly as it appears in the screenshots
```
TypeError: navigator.userAgent.match(...) is null simplewebrtc.js:13336:22
ReferenceError: SimpleWebRTC is not defined webrtc.js:107:3
```

Steps to reproduce: As said above, use our cloud.nc instance and open the Spreed app.

**Comment by nickvergessen** [comment]
This works pretty fine for me with Firefox 50.1.0 on Linux Mint (Ubuntu 16.04 based).
But reading the log messages, are you using a custom user agent? And what is your user agent (you can use services like http://www.whoishostingthis.com/tools/user-agent/ )?

**Comment by nickvergessen** [comment]
Please also open your JS console and run the following two commands:
```
navigator.userAgent
window.navigator.userAgent
```

**Comment by jancborchardt** [comment]
Aaah, thanks a lot! I was actually using an extension »User Agent Overrider« which I totally forgot about! It overrode the user agent with:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
```
(It’s a commonly used hack needed to make Netflix work with Firefox.) Any way to have the app not stumble over it? Talky.io for example had no issues with it, that’s why I thought it to be an issue on our end.

**Comment by nickvergessen** [comment]
Okay I get the same error with that user agent. Will try to find the issue.

**Comment by nickvergessen** [comment]
Well that's obvious now, the webrtc lib detect Firefox by checking whether `window.mozRTCPeerConnection` exists and then tries to get the Firefox version, which fails, because `Firefox\/([0-9]+)\./` is not part of the user agent anymore.

Easy fix, add the actual Firefox version back into the user agent.
The only thing we can do is show a warning before breaking....
