### ISSUE TITLE
No space character for notifications

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2152]
There is no space between the username and the text when the conversation is notified.

![obraz](https://user-images.githubusercontent.com/47037905/64256877-965d9b00-cf24-11e9-9ed9-760e672816bd.png)

I reviewed this code in Notifier.php:

_(Line 379)_ `str_replace('{user}', $user->getDisplayName(), $l->t('{user} wants to talk with you'))`
_(Line 382)_ `$l->t('{user} wants to talk with you'), [`

The space character is in the code that is not displayed in the notifications.

## Browser
Firefox 69.0

**Operating system:** Windows/Ubuntu/...
Win10

## Nextcloud
16.0.4
## Spreed app
6.0.4

**Comment by nickvergessen** [comment]
Works fine here :thinking: 
Which notification app version are you running?

**Comment by Valdnet** [comment]
@nickvergessen I'm using the version 2.4.1.

**Comment by nickvergessen** [comment]
Hmm, thats all the same I used in my test. Can you check the response of the notification request, if the message contains the space there too?

**Comment by Valdnet** [comment]
I can not. How can this be done?

**Comment by Valdnet** [comment]
OK. I close the Issue. The problem is on the notification side.
