### ISSUE TITLE
Screensharing does not work with PowerPoint presentation mode

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/spreed#2158]
## Steps to reproduce
1. Start a video conference with another user
2. Open a PowerPoint-Document and start presentation mode
3. Start screensharing and choose presentation window

### Expected behaviour
Presentation window should be shared with the other user

### Actual behaviour
A frozen window of the browser is shared.

Similar tests with Libreoffice Impress presentation mode or full screen sharing does work as expected.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10 / Ubuntu 18.04

**Browser name:** Firefox

**Browser version:** 69.0

## Spreed app

**Spreed app version:** 6.0.4

**Custom TURN server configured:** no

**Custom STUN server configured:** no (stun.nextcloud.com:443)

## Server configuration

**Operating system**: Ubuntu 18.04.3

**Web server:** Apache 2.4.29

**Database:** mariadb 10.1.41

**PHP version:** 7.2.19

**Nextcloud Version:** 16.0.4

**List of activated apps:**

<details>
  - accessibility: 1.2.0
  - activity: 2.9.1
  - announcementcenter: 3.5.1
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.6
  - drawio: 0.9.3
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.1.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.4
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.1
  - text: 1.0.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.xx.xx.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "https:\/\/xx.xx.xx.de\/nextcloud",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "force_language": "de",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2
    }
}
</details>

### Server log (data/nextcloud.log)
<details>
No log entries
</details>

**Comment by nickvergessen** [comment]
I dont have a Office license. Maybe I can try it on someone elses laptop at the conf.
But I guess if this is really a problem it needs to be fixed in the browers.

**Comment by Nils160988** [comment]
It would be great if you could test it, please let me know if I can help.

**Comment by Nils160988** [comment]
Re-Test with NC 17 does not show this behavior anymore, seems to be fixed now.
