### ISSUE TITLE
Guests which change their name still show up as »1 guest« in sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#216]
Instead, of course the name they put in should show up. :) @nextcloud/spreed

**Comment by nickvergessen** [comment]
The name is not stored in the database, but only in the users local-storage, so this is not possible.
And I think they should still be listed as guests, to be able to identify the number of actual users vs. guests.

**Comment by jancborchardt** [comment]
> And I think they should still be listed as guests, to be able to identify the number of actual users vs. guests.

Their names are shown in the video view though (as they should be), so it’s confusing and looks like a bug that it’s not the same in the sidebar.
Just like with sharing we want to make it a seamless experience, regardless of if people are »guests« or on the same Nextcloud.

> The name is not stored in the database, but only in the users local-storage, so this is not possible.

Ok, so that’s the current state. But that’s not a reason for it never being possible at all, right? :)
How can we make it happen that at least for the time that this guest with the custom name is in that room, the name in the sidebar also reflects that custom name?

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/spreed/issues/551 which has more current info on it.
