### ISSUE TITLE
Information about the time of call connection when there is no call

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2163]
## Steps to reproduce
1. Call user X on Talk Android.
2. User X does not answer the call.
3. End connection.
**Information about the duration of the call appears:**
![obraz](https://user-images.githubusercontent.com/47037905/64476457-1dae4700-d18f-11e9-8267-cd19cbb2d6cc.png)

**Nextcloud Version:**
16.0.4
**Talk Version:**
6.0.4
**Talk Android Version:**
7.0.0b4

**Comment by nickvergessen** [comment]
Yeah, that is a mistake, becuase people reading the chat are also taken into account for the call summary. This was fixed for Nextcloud 17 with the Talk 7 release

https://github.com/nextcloud/spreed/pull/2012
