### ISSUE TITLE
Copy paste image into the chat

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2172]
We are using Riot for our teams and often we take screenshots, copy and paste them in the Riot chat directly. Such a useful little thing. Helps to report bugs and such. Would be fantastic to see it implemented.

**Comment by nickvergessen** [comment]
This could be looked at after #1129

**Comment by vix95** [comment]
Hi, I'll be grateful if this option will be implemented. As above, feature is really helpful and must have to be implemented. 💃

**Comment by Valdnet** [comment]
This feature should be added as soon as possible. This facilitates picture communication :sunglasses:.

**Comment by Flingafu** [comment]
Pictures in chat is an absolutely vital service to provide and one of the things lacking, making switching from discord and riot difficult!

**Comment by Mercurial** [comment]
we really need this in our little team

**Comment by ma12-co** [comment]
@tiotrom do you mean drag and drop file upload? I tested copy-pasting with riot and I'm unable to do it.

**Comment by szaimen** [comment]
@ma12-co I know that e.g. [telegram web](https://github.com/zhukov/webogram) is allowing copy and paste images into chats

**Comment by tiotrom** [comment]
> @tiotrom do you mean drag and drop file upload? I tested copy-pasting with riot and I'm unable to do it.

Did you try with copy image? Or copy file? Like if you have an image in your browser, right click it and "copy image" then paste in Riot, it should work. A great use was when I screenshot my desktop (add whatever annotations to it) and simply copy that and paste it into Riot. Signal Desktop also allows for that. Make sit super fast to share bugs and such in chats.

**Comment by grand-lotus-iroh** [comment]
How do I press CTRL + V inside the chat browser tab and share my file with the group?

I also tried drag and drop from Windows Explorer... that too did not work.

**Comment by nickvergessen** [comment]
> I also tried drag and drop from Windows Explorer... that too did not work.

It will come with teh next major version in time for Nextcloud 19

**Comment by vix95** [comment]
> > I also tried drag and drop from Windows Explorer... that too did not work.
> 
> It will come with teh next major version in time for Nextcloud 19

Yes! I'm waiting for that! ❤️

**Comment by ediazcomellas** [comment]
> > I also tried drag and drop from Windows Explorer... that too did not work.
> 
> It will come with teh next major version in time for Nextcloud 19

That will be great. A very useful feature.

**Comment by guryanovev** [comment]
@ma12-co Is pasting screenshots from the clipboard still missing? If yes, we would like to implement it and submit a PR or is there some work-in-progress already? Thank you.

**Comment by ma12-co** [comment]
Hi @guryanovev!
yep, the feature is still missing and it would be awesome if you'd implement it :)

**Comment by guryanovev** [comment]
Done in https://github.com/nextcloud/spreed/pull/3399

**Comment by guryanovev** [comment]
One thing I noticed -- when you paste a screenshot or drag a file there is a delay about 0.5-1 second without any indication, it is probably the moment when actual uploading is in progress. Maybe it would be helpful to have some kind of busy-indication on top of chat control, something like this;

![image](https://user-images.githubusercontent.com/2764795/80461034-59279c80-893d-11ea-9435-1220dc78a5f7.png)

**Comment by nickvergessen** [comment]
Yeah, there is also another idea to have something like a "Confirm" window which allows you to check previews etc first, in case you drop the wrong file into the wrong conversation or something.

Can't find an issue at the moment. Where did we discuss this @ma12-co

**Comment by ma12-co** [comment]
I don't think we discussed this in an issue @nickvergessen 
@guryanovev Ideally for this we'd need something similar to the temporary message that is appended to the message list and gets deleted when the real message is received. 

Please join us in our talk development channel so we can coordinate this more easily :) 
https://cloud.nextcloud.com/call/c7fz9qpr
