### ISSUE TITLE
TypeError: navigator.userAgent.match(...) is null

### ISSUE THREAD

**Issue by jaakristioja** [nextcloud/spreed#2176]
## Steps to reproduce
1. Set navigator.userAgent to "Mozilla/5.0"
2. Go to Talk app

### Expected behaviour
Talk finishes loading and I can have conversations.

### Actual behaviour
Left-hand sidebar (conversations list) never finishes to load (shows spinner).

## Browser

**Browser name:** Firefox

**Browser version:** 68.1.0

### Browser log

```
00:07:13.242 TypeError: navigator.userAgent.match(...) is null merged.js:8196:42
```

## Spreed app

**Spreed app version:** 6.0.4

## Server configuration

**Nextcloud Version:** 16.0.4

## More information

The offending code seems to be located at js/simplewebrtc/bundled.js:8737: https://github.com/nextcloud/spreed/blob/822384b24bb8600956cc23f57543f5a9b9f92ec4/js/simplewebrtc/bundled.js#L8731-L8741

I suppose that any non-Firefox browsers based on the Mozilla codebase will also fail with this. Setting the `navigator.userAgent` value to something like "Firefox/9999.999 Mozilla/5.0" seems to be one workaround.

**Comment by nickvergessen** [comment]
Sorry to hear, but yeah with webrtc invalid custom user agents can not be supported. There is no other way for all the webrtc libraries to know which tools to use, when you change the user agent.

**Comment by jaakristioja** [comment]
@nickvergessen I'm sorry I don't fully understand. Although not all browsers can be supported, I suggest that `if (window.mozRTCPeerConnection || navigator.mozGetUserMedia)` but `navigator.userAgent` doesn't match `Firefox`, it would be sane to fall back to a reasonable default, e.g. to expect that a reasonably modern version of the Mozilla codebase is installed instead of simply failing.

**Comment by nickvergessen** [comment]
This is a library we use and I would like to keep the changes as small as possible in this foreign library.

The problem is not the null, yes we could fix that, but then what? Which Scim should be loaded later on, the old Firefox one, or the new one, .... and the trail continues.

If yourun a firefox based browser, make your user agent give us the version of firefox that it is based on.
