### ISSUE TITLE
App name: Spreed (video calls)

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/spreed#218]
I think we should call the app simply **Spreed** instead of **Spreed video calls** because:

* everybody is calling it spreed #simplicity 😅 
* appid/repo name is already spreed
* distinction between Spreed.ME and Spreed is enough by the missing **.ME**
* video calls makes the app name unnecessary long

And the most important thing: The app is (and will be) doing more than video calls ;) Screen sharing for example 😜 ...and also video calls are optional as you can also use it for audio calls only.

What do you think? @Ivansss @nickvergessen

**Comment by nickvergessen** [comment]
Well Spreed does not tell anyone what it is. The app name was also changed to "Video calls" for now. So it's not that long anymore.

**Comment by MariusBluem** [comment]
> The app name was also changed to "Video calls" for now. So it's not that long anymore.

It was not? 🤔 https://github.com/nextcloud/spreed/blob/master/appinfo/info.xml#L4 @nickvergessen

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/master/appinfo/app.php#L31

Okay will adjust info.xml

**Comment by MariusBluem** [comment]
And what about **Calls** or **Spreed Calls** ... to get rid of the **Video** 😅 @nickvergessen

**Comment by MariusBluem** [comment]
Removing the Spreed Trademark may also has downsides, as some guys already know it now 🤔

**Comment by jancborchardt** [comment]
As @nickvergessen already said, the app is called »Video calls«. We used »Calls« before but it was not descriptive enough.

But we always use descriptive & simple names (like Files, Mail, Contacts, Calendar, Notes, Tasks etc.), and »Spreed« is really not descriptive at all. :)

> everybody is calling it spreed

This is only true for us few developers. The majority of people have no idea what Spreed is, but most people know what a video call is. ;)

**Comment by rugk** [comment]
> distinction between Spreed.ME and Spreed is enough by the missing .ME

Actually from a user perspective I can say, I still don't get the difference between these two. It is very confusing too have two apps with this name, so "video calls" (as it stands) is a good name for one of them at least…

**Comment by jancborchardt** [comment]
Yes, the only thing where it says »spreed« now is in the URL and the app folder and repository name. ;)

We always give apps descriptive names, like Files, Calendar, Contacts, Mail … and Video calls. ;)
