### ISSUE TITLE
Calls rarely work

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2182]
### Steps to reproduce
1. Use nextcloud talk hosted (say cloud.tromsite.com) or the nextcloud talk app
2. Just call any contact in the list
3. The contact either does not receive a notification of the call, or does but answering does nothing. It keeps on calling...

### Expected behaviour
Call. Answer. Talk. :)

### Actual behaviour
The call doesn't go through. You cannot answer most of teh times, and when you do it appears as if you didn't.

## Server configuration detail

**Operating system:** Linux 4.9.159-vs2.3.9.8-vs+ #4 SMP Wed Aug 28 15:05:40 PDT 2019 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.11
Modules loaded: Core, date, libxml, pcre, sqlite3, filter, hash, mbstring, SPL, PDO, Reflection, sodium, pdo_sqlite, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, exif, fileinfo, ftp, gd, gettext, iconv, imap, json, mysqlnd, openssl, pcntl, pdo_mysql, zlib, posix, pspell, mysqli, SimpleXML, soap, sockets, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, imagick, memcached, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** webinstaller from nextcloud

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - apporder: 0.7.1
 - bruteforcesettings: 1.4.0
 - checksum: 0.4.3
 - cloud_federation_api: 0.2.0
 - dav: 1.9.2
 - deck: 0.6.6
 - drawio: 0.9.3
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_antivirus: 2.1.1
 - files_markdown: 2.0.6
 - files_mindmap: 0.0.15
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - systemtags: 1.6.0
 - tasks: 0.11.2
 - text: 1.0.2
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - announcementcenter
 - audioplayer
 - bookmarks
 - comments
 - dropit
 - encryption
 - files_external
 - gallery
 - keeporsweep
 - mail
 - ojsxc
 - onlyoffice
 - polls
 - richdocuments
 - sharebymail
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.cloud.tromsite.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "http:\/\/www.cloud.tromsite.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** mo
## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by fancycode** [comment]
@TheDarkula With WebRTC you are having peer-to-peer connections, so if your participants are behind a firewall, you still might need a TURN server - even if your Nextcloud server is directly connected to the internet. Nextcloud is only handling the signaling part, the actual audio/video is directly sent between the participants.

The order of which participant initiates the peer connection is pseudo-random, so depending on which of your participants starts it (and how their firewall/NAT looks like), it might work for one order but not the other way around. This could explain the "sometimes restarting a device" fix: the order of the call establishment changes and the call works.

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by tiotrom** [comment]
I have to update on this. We created a TURN server but it is still nowt working. What are we doing wrong? What could we test more?

**Comment by nickvergessen** [comment]
Check the console log of your browser if it shows an error

**Comment by tiotrom** [comment]
I see this:
`Deprecated call $.tooltip('destroy') has been deprecated and should be removed`
and
`The escapeHTML library is deprecated! It will be removed in nextcloud 19`

Thats when 2 devices are on the same network. Other networks there is no call going through and I see the same errors in the console. We tried with the latest Firefox and Android. Between each other (ff to android, ff to ff, android to android).

**Comment by nickvergessen** [comment]
Well as per above, if you are in different networks you need a TURN server. If that is properly configured it should work just fine.

The console lines you posted above are just debug information and are irrelevant for now.
