### ISSUE TITLE
Messages scrolling down every time you re-open a chat

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2191]
**Is your feature request related to a problem? Please describe.**
Whenever I go on a chat that has multiple messages the messages take a few good seconds to scroll down. It is almost unusable. Can't it load just the last 10 or so and the rest to load if people scroll up?

**Describe the solution you'd like**
Not scrolling through all of the messages when a chat is re-opened.

Cheers!

**Comment by nickvergessen** [comment]
This is in the making already:
https://github.com/nextcloud/spreed/issues/1164
