### ISSUE TITLE
Allow to ignore a chat so it does not display unread messages count

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2195]
**Is your feature request related to a problem? Please describe.**
When I want a chat to "never notify", I want less distractions, so seeing messages count makes it distracting. Why not simply disable all notifications? Like also the number of messages (the count) in the Talk window...

**Describe the solution you'd like**
Complete distraction-free mode. No notifications what-so-ever. Not even the messages count in the chat window.

Cheers!

**Comment by nickvergessen** [comment]
Well, all messengers show the count when a chat is muted and I think that also makes sense 🤔

**Comment by tiotrom** [comment]
Riot doesn't for example. If it is on "mute" then it should not bother you, right? If you talk to someone else but see this other "muted" chat constantly adding new numbers to its tab, then it gets very distracting. We manage teams and I find this very distracting to be honest. :D

**Comment by nickvergessen** [comment]
Well like I personally have almost all chats on mute, doesnt matter if Talk, Whatsapp, Signal, Threema or Telegram.
But without the unread count that would be pretty useless, I just don't want my phone ne to ring 🤷‍♂️

Cc @jenniferpiperek

**Comment by tiotrom** [comment]
I understand. But a distraction free option would be appreciated. Imagine your desk is inside a glass room. You mute the sound from the outside world. But you can still see people, cars, etc. You then put blurry window glass all around. Now you can't distinguish who's outside, but you can still see shapes moving, all the time. That's how I feel with seeing the messages count :D - I prefer proper not-see-through walls sometimes so I can focus on the chats I want, and if I want to see what's outside, I'll open the door and have a look whenever I want ;).

**Comment by nickvergessen** [comment]
After a quick chat with Jennifer about this, we think a designated "distraction free mode" is more what you are looking for. That should in this case affect the full instance (all conversations, notifications, other "popups" (we dont have any, but just in case))

**Comment by tiotrom** [comment]
I am not saying all conversations, only the one you want to mute. Like Riot does it. It simply stops all notifications for that chat room, and only that. No message counts, sounds, popups, nothing. That's what I would call "mute". Because if I keep on seeing the message count updating while I am talking to other people from other chats, then that is indeed distracting. Imagine you have an email app and want to turn off the notifications, but you still get notifications about the number of emails you are receiving - something displayed besides the mail app icon in your taskbar. It's like you don't get a pupup saying "you got mail", but you get those email counts updating all the time telling you !you got mail". I hope you understand what I am trying to explain :)

**Comment by nickvergessen** [comment]
As we are stumbling over this every now and then and it results in people leaving and later again joining a conversation, adding up to the marking as unread even more with e.g. our sysadmin room, I think what we actually need is another notification setting which is basically "Ignore unless mentioned" which would move the room to the end of the conversation list and not show the "unread counter" unless you were pinged.

**Comment by nickvergessen** [comment]
You can now archive such a conversation so it is no longer visible in your conversation list.
