### ISSUE TITLE
📝 Note to self - Overview

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2196]
For quickly sharing links or notes between your devices, a "Note to self" entry in the conversations is cool.

Signal for example has this. Technically it used to be the case when you sent a message to your own number, and now it's directly called "Note to self".

For us it could be a default conversation called "Note to self ✅", and as picture it could use the ["pencil" icon](https://pictogrammers.com/library/mdi/icon/pencil/) in white on the blue gradient background, similar like we have it for the "Talk updates ✅" conversation.

The issue of quickly exchanging text content between devices or desktop and mobile was also brought up by @tobiasKaminsky @jakobsack and this is a cool solution for that. :)

- [x] API https://github.com/nextcloud/spreed/issues/10404
- [x] Frontend https://github.com/nextcloud/spreed/issues/10405
- [x] Android https://github.com/nextcloud/talk-android/issues/786
- [x] iOS https://github.com/nextcloud/talk-ios/issues/300

**Comment by nickvergessen** [comment]
Yeah basically a designated group conversation with just you.

**Comment by marcusquinn** [comment]
Rocket Chat also does this. It's both useful and nice to be able to *Talk* to oneself and get a sensible answer 😁

**Comment by marcusquinn** [comment]
Just realised, you can only do this with the `+` sign for a new conversation, and only adding yourself.

However, you can't search your own name in the "Search conversations or users" input, which is what most users have assumed should be the way to do this.

@mario Chance we can make your own name return in the search results and initiate this 1-2-1 conversation with oneself that way too?

**Comment by nickvergessen** [comment]
Mario is not with the project anymore.
The thing is we would like to have more than a normal conversation with ourselves.

**Comment by Yiannis128** [comment]
This would be a nice quality of life feature.

**Comment by jancborchardt** [comment]
Added specification details on the top:

> For us it could be a default conversation called "Note to self ✅", and as picture it could use the ["pencil" icon](https://pictogrammers.com/library/mdi/icon/pencil/) in white on the blue gradient background, similar like we have it for the "Talk updates ✅" conversation.

**Comment by jancborchardt** [comment]
@nickvergessen yes on the first 3 sounds good, yep.

And for the last one the special handling as with Talk updates sounds good. Manual restore is a good question, I think it's probably fine to not have that first, otherwise we are going into overengineering territory.

**Comment by nickvergessen** [comment]
@jancborchardt should there be a predefined chat messages be posted in the room with some kind of explanation text?
If so can you come up with one?

**Comment by jancborchardt** [comment]
I don't think there should be a default message as all messages will be coming from yourself.

We could set a short description like:
> A place to post messages or use bots which stay private to just yourself.

**Comment by SystemKeeper** [comment]
> * Should we add a "Note to self" on the message … Menu, which is a "Forward to your own 'Note to self'" shortcut? Assuming: Yes

The action will always be called „Note to self“, even if the conversation was renamed by the user, correct ?

**Comment by nickvergessen** [comment]
I would say so, yes

**Comment by nickvergessen** [comment]
All done 🎉

**Comment by krelltunez** [comment]
Hi, just an average user here.  My "Note to self" disappeared for no reason.  How do I get it back?

**Comment by tobiasKaminsky** [comment]
Maybe you have deleted it?
Can you see it on "add new conversation"?

![image](https://github.com/nextcloud/spreed/assets/5836855/a0e4513f-af3c-40bf-99a8-37d73dec17f5)

**Comment by krelltunez** [comment]
That's my point.  When I click that icon, I only see "Create a new conversation" and "Join open conversations."  I do not have a "New personal note" option (nor, incidentally, do I see a "Call a phone number" option).

One minute, Talk had been updated and I saw the personal note thing, the next minute it was gone (without me doing anything).

**Comment by krelltunez** [comment]
Actually, I see the issue now.  Per the "Apps" section, I'm still running 17.1.3.  Yet I know it updated to 18x at one point.  How do I force an update?

**Comment by nickvergessen** [comment]
I guess you use docker or something and have 17.1.3 in a read-only files directory.
Since quite some time there is a bug that Nextcloud Server does no longer load the newest version but any version of the JS files and then that causes issues.

Then again, this is full offtopic on the feature overview. I would recommend you open an issue in https://help.nextcloud.com/ or at the package/docker/VM or whatever you installed.
