### ISSUE TITLE
Latest version is broken in Safari

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/spreed#2212]
## Steps to reproduce
1. Open talk
2. Conversation list is visible

### Expected behaviour
- expect chat to be visible as well.

### Actual behaviour
- no matter what conversation i click, i do not see any conversation 

When opening a chat, you see a mispositioned "No messages" screen for a tenth of a second. Afterwards the entire list is black. Also see that the participants list changes and contains people that are not participants.

![opening](https://user-images.githubusercontent.com/1250540/65410475-c04f0280-ddea-11e9-935d-ebd37a3d4aa9.jpg)
![opened](https://user-images.githubusercontent.com/1250540/65410478-c218c600-ddea-11e9-824c-7aa466f90c57.jpg)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macOS

**Browser name:** Safari

**Browser version:** Version 13.0 (14608.1.49)

### Browser log

<details>
```
[Error] Unrecognized Content-Security-Policy directive 'worker-src'. (x2)

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (collectionsintegration.js.map, line 0)
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by Ivansss** [comment]
I just try to reproduce this issue, but working fine here using Safari 13.
Could you try to do a hard refresh @georgehrke ? Maybe something was cached after version update 😕
