### ISSUE TITLE
Have volume icon filled with current speaking level

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#2225]
From https://github.com/nextcloud/spreed/issues/2138#issuecomment-526524520

![vcfdsfd](https://user-images.githubusercontent.com/14975046/64008271-12677580-cb16-11e9-9af4-ef319c8dd06e.png)

**Comment by nickvergessen** [comment]
@nextcloud/designers-talk I leave this up to you. Do we want to move the colored speaking level indicator into this (if it is technically possible) or close for now?

**Comment by skjnldsv** [comment]
Still think it's a better enhancement that the bar next to it :)

**Comment by ma12-co** [comment]
Would this be compatible with material's iconfont @skjnldsv ??

**Comment by jancborchardt** [comment]
> Still think it's a better enhancement that the bar next to it :)

Agree, it’s nicer and cleaner.

@ma12-co we did this in the old version of Gallery with the pause icon which was duplicated and one changed height as the counter. What we could do here (cause we can not do it with height of the icon itself) is put one in a container, which changes height according to volume and is `overflow: hidden`, hiding the top part of the icon, and on 0 volume hiding all of it cause it has 0 height.

**Comment by skjnldsv** [comment]
One day we'll be able to use background clip to gradient the text directly, but it's not production ready yet ;)
https://cssgradient.io/blog/css-gradient-text/
