### ISSUE TITLE
Create new deck-card of a chat message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#2226]
Inspired from this video: https://slack.com/intl/de-de/
What do you think about this feature?

**Comment by nickvergessen** [comment]
I think the feature is nice.

The biggest problem is, the same should be possible with a card for the deck app, an event in the calendar, etc. and we just can't do this all in the base app. Maybe a plugin mechanism makes sense which allows those apps or connector apps to offer an option for our future `...` menu messages will have.

**Comment by jakobroehrl** [comment]
@nickvergessen Nice idea with a plugin mechanism. Who could help with that?

**Comment by jakobroehrl** [comment]
@nickvergessen 
Could this be accomplished with nextcloud flow?

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/deck/issues/2630

**Comment by nickvergessen** [comment]
Creating a deck card of a chat message will be possible via the reply-button which will become a ... menu.

* 🗨️ The talk app allows to register actions for messages and deck provides one.
* 🗨️ When clicked the chat message object including author information will be provided to the deck provider
* :card_index_dividers: The deck app will then (depending on the length) use the message as title (limited to 250?) or body of the card, together with an option to select the board + stack and is then posted towards the deck api.

**Comment by nickvergessen** [comment]
Implemented with #5202, #5203, #5204 and #5201
