### ISSUE TITLE
In 3 person call, sometimes middle picture overlays promoted speaker

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#223]
Check this out:
![bildschirmfoto 2017-01-18 um 19 45 53](https://cloud.githubusercontent.com/assets/925062/22090570/cd3e234a-ddf2-11e6-8cd1-fa9eb0deb61f.png)

In this case the middle person (Jan) overlays the promoted speaker Lukas. Especially when you are in the middle of the picture, this can overlay a large portion of your face or mouth and just looks a bit broken.

For 4 people and more this is not really a problem anymore because the other people’s videos are smaller.
But for 3 people it would be good if we would have a specific case. Which is to **always have the promoted speaker take the middle slot, and the other person gets the bottom left.**

(As talked about with @LukasReschke @MorrisJobke, cc @nickvergessen @Ivansss)

**Comment by nickvergessen** [comment]
Can you fix it?

**Comment by jancborchardt** [comment]
Not really, there's heavy JS involved switching the speaker container from the bottom row to the promoted big view already. Cc @Ivansss @MorrisJobke

**Comment by nickvergessen** [comment]
Well just move the non speaking people out of the video screen so they are below? We need that for screensharing as well i guess

**Comment by irmhild314** [comment]
Please have a look at my comment to #420

**Comment by nickvergessen** [comment]
Superseded by #1056
