### ISSUE TITLE
Missed call message

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#2232]
From here: https://github.com/nextcloud/talk-android/issues/248
May be add to chat "You have a missed call..."&Time or "You have a missed videocall"&Time, if they were?

**Comment by nickvergessen** [comment]
A notification for that is already in place, I guess we could also add a chat message, although I think that the joined/left messages should be information enough already

**Comment by jakobroehrl** [comment]
Hi @nickvergessen @mario 
I want to bring up this topic again. 

My use case is to substitute telephone mobile calls with talk mobile calls and it works great expect for the missed call message. 

I tested it. If John (mobile) calls user Jane (mobile) and Jane missed the call she gets an notification **but only** on the web interface. This notifications is not shown on mobile neither on the nextcloud app nor within the talk app. So If Jane is not working with the web interface she will never notified that she missed a call. 

Maybe the talk android app could pick up and show the notification as well as the "new chat message" notification is shown. 

Thanks for your effort! Talk is awesome!

**Comment by nickvergessen** [comment]
>  If John (mobile) calls user Jane (mobile) and Jane missed the call she gets an notification but only on the web interface. This notifications is not shown on mobile neither on the nextcloud app nor within the talk app.

That sounds wrong. There is no filtering happening. Maybe there was an issue registering yourself for push notifications, or the android app kills the call notification automatically after some time?

**Comment by jakobroehrl** [comment]
I don't think so. This is not working on Android.
It seams to me, Androd is not using this kind of notification. 
I'm aware of the battery setting, this is not the problem, I think. 
I can test again if that helps.

**Comment by nickvergessen** [comment]
While thinking about the "missed call" system message with @Ivansss we thought it might also make sense to spice up the call messages a bit.
We could:
* ↗️ have an arrow to top-right in green for "joined call"
* ↙️ have an arrow to bottom-left in red for "left call"
* 🔵 have the blue message background on the "missed call" message (like on the "X started a call" when you didn't join yet) so it's more noticable and you can follow up on the person.

**Comment by jakobroehrl** [comment]
That would be great!
Maybe we could solve the problem, that the missed call notifications are not shown on Android, too?
https://github.com/nextcloud/talk-android/issues/248

**Comment by nickvergessen** [comment]
> Maybe we could solve the problem, that the missed call notifications are not shown on Android, too?

For now we will start with a simple chat message
