### ISSUE TITLE
Improve the code quality of "Talk sidebar on public shares"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2237]
See open comments in https://github.com/nextcloud/spreed/pull/2107

**Comment by jospoortvliet** [comment]
Not sure if this is a Text, Viewer or Talk bug but the talk sidebar has an issue with the Call button being covered by a part of the Text viewer:
![Screenshot_20190928_182258](https://user-images.githubusercontent.com/551757/65819458-1e317f00-e21d-11e9-9e50-b0fe709a1427.png)

I guess it's a CSS fix... ;-)

**Comment by nickvergessen** [comment]
Reopening for the UI thing

**Comment by nickvergessen** [comment]
This is now done? @danxuliu

**Comment by danxuliu** [comment]
No, not yet.

**Comment by jospoortvliet** [comment]
It is fixed now, at least I don't see it anymore on cloud.nextcloud.com -> close.
