### ISSUE TITLE
Add a calendar for group conversation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2240]
I suggest adding the option to select the start time (day and time) by selecting the day and time from the system calendar.

![obraz](https://user-images.githubusercontent.com/47037905/65758075-b265ee00-e118-11e9-8af2-35f20c81c9aa.png)

Entering a start time manually is burdensome for users. It is not known what format the date and time should be.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/2668
