### ISSUE TITLE
Make Lobby feature easier discoverable

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2244]
I just tried out the lobby feature of Nextcloud Talk 7.0 and it works really nice! :slightly_smiling_face: 

But the menu was quite confusing for me:

![image](https://user-images.githubusercontent.com/1589737/65767522-64f47b80-e12e-11e9-8f76-bcd3de22be6e.png)

"Enable for" but what? What is the affect for the user? Also if I click on "moderators only" the drop down closes immediately which means that almost noone will discover that they can add a start data.

What about having a check box instead:

````[ ] Lobby````

Maybe with a tooltip which describes it in a short sentences like "non-moderators have to wait in a Lobby until the call starts". If you check it the dialog should stay open and the input field for the start date should be shown so that the user actually sees that there are further config options for the meeting.

What do you think?

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Indeed, we should improve a bit. I too don't really get why you need "moderators only" for the lobby to be activated (thats how it behaved last time I check during the conf)

**Comment by nickvergessen** [comment]
Also something seems to be broken, the `|` above the divider was not there before.

**Comment by nickvergessen** [comment]
The wording and choose of radio button vs checkbox goes back to @jancborchardt :
https://github.com/nextcloud/spreed/pull/1926#issuecomment-506962798

I personally would also prefer a check box, just like we have it with the share link

**Comment by schiessle** [comment]
> Also something seems to be broken, the | above the divider was not there before.

it's on c.nc.com... in @Ivansss dev system it looks fine

**Comment by nickvergessen** [comment]
On my local dev it looks like that too. Maybe 2 apps interfer

**Comment by Ivansss** [comment]
> it's on c.nc.com... in @Ivansss dev system it looks fine

Should be something related with your browser.
I don't see that weird divider in c.nc.com either.

**Comment by nickvergessen** [comment]
Firefox it is

**Comment by Ivansss** [comment]
> Firefox it is

But not in Firefox on macOS 😕

**Comment by jospoortvliet** [comment]
A 'enable lobby' checkbox seems to make more sense to me, too, esp as there are two options anyway. If there were three options, a radio button selection might be the better solution...

**Comment by jancborchardt** [comment]
The mockup at https://github.com/nextcloud/spreed/pull/1926#issuecomment-506962798 looks a bit different than what came out (highlight, icons ;) but so be it.

Yes, a simple checkbox saying "Use lobby" which by default is unchecked would be good. Below it we can have an explanatory sentence like:

> **Use lobby**
> Only moderators can enter the room until the meeting is started for everyone.
