### ISSUE TITLE
Multi-platform for OwnCloud&NextCloud

### ISSUE THREAD

**Issue by flionet89** [nextcloud/spreed#2264]
Hi. Is it possible to make this application work not only in NextCloud but also in OwnCloud?

**Comment by nickvergessen** [comment]
Hi @flionet89 

Glad you like our Talk app :grin: While in theory we could look into this, it does not make too much sense anymore at this point. ownCloud decided to drop PHP and is currently rewriting their thing to GoLang. So with the next version this is all not even an option anymore.

Therefor I would instead recommend that you migrate to Nextcloud. You can then easily install the app from the appstore.

Hope that helps.
