### ISSUE TITLE
Is it possible to deactivate talk on file sharing web pages?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/spreed#2280]
Guys I noticed that when I generate a file sharing scream, whatever it is, opening the url in the page also gives me the possibility to call as an anonymous user. in practice it enables talks in the pages of the url that I generate for sharing.

How can I turn off talk in the browser that points to shared urls?

I attach photo

![Immagine](https://user-images.githubusercontent.com/35575744/66304642-fbc6f200-e8fd-11e9-9dcd-b4224dcabc85.png)

**Comment by nickvergessen** [comment]
Not yet, but I think we should at least add a global option for that.

**Comment by tigernero79** [comment]
in the talk setting there is the possibility to choose start call only for users and members, but even if I exclude this item it is not kept, always remaining on the "all" entry

![Immagine2](https://user-images.githubusercontent.com/35575744/66306161-3ed69480-e901-11e9-8332-455f54c4be41.png)

it is unnerving to always see the talk bar in the sharing url

**Comment by nickvergessen** [comment]
> but even if I exclude this item it is not kept, always remaining on the "all" entry

I fixed that with https://github.com/nextcloud/spreed/pull/2281 already.

**Comment by nickvergessen** [comment]
Note that this will not influence the sidebar on public shares, that is a different story.

If you still want to change the setting now already, you can just run the following database query:
```sql
INSERT INTO `oc_appconfig` (`appid`, `configkey`, `configvalue`) VALUES ('spreed', 'start_calls', '1');
```

**Comment by tigernero79** [comment]
so even by manually applying the fix in the database and then setting up call start only for users and moderators, won't the bar disappear in shared URLs?  ok i will wait for the possibility to disable it as soon as you can implement this.  thanks for everything

**Comment by tigernero79** [comment]
this "query" will set users and moderators, but it does not allow me to change them only by moderator or all, do I still have to wait for your correction right?
