### ISSUE TITLE
Add hint for mentions and commands

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#2287]
It would be nice to have some kind of hint for mentions and commands.

For example, we could add something in the text input placeholder:
<img width="446" alt="Screenshot 2019-10-09 at 08 44 09" src="https://user-images.githubusercontent.com/4638605/66457630-1c638900-ea71-11e9-9c30-8a187b67490f.png">

@nextcloud/designers any ideas?

**Comment by skjnldsv** [comment]
I think it's great for tech or semi-tech people, but not very straightforward for people that have no idea about it. Though it doesn't help as the current state is not discoverable for non tech anyway :thinking:

**Comment by nickvergessen** [comment]
Sounds good to me.

Telegram shows a `/` button when there are commands available. I could see that too, or we put it into the obscure `+` button or something?

**Comment by jancborchardt** [comment]
Putting it in the placeholder is a bit much. I think the point of @nickvergessen is better, where we have a button like a 3-dot menu which can show you more possibilities. (This we probably need anyway for other elements.)

**Comment by nickvergessen** [comment]
#2649
