### ISSUE TITLE
native app for mobiles

### ISSUE THREAD

**Issue by maprambo** [nextcloud/spreed#229]
The video call / spreed app is currently not usable with iOS devices due to the lack of webrtc. Further, using services as this one is generally better with a native App, both for iOS and android of course.
struktur AG is providing a spreed.me app but that doesn't work with nextcloud, however this would probably be the easiest way to make an app available.

**Comment by nickvergessen** [comment]
The plan is to make the Spreed.Me iOS app also work with Nextcloud spreed

**Comment by e-alfred** [comment]
@nickvergessen Is there also an Android app planned? It would make it easier to use with one too...

**Comment by nickvergessen** [comment]
On Android you can use Chrome, but yeah as far as I know it's also planned

**Comment by mase76** [comment]
Does it only work with Chrome / Chromium on Android?
In Firefox I only get a view of myself.

**Comment by nickvergessen** [comment]
Android app #338 https://github.com/nextcloud/talk-android
iOS app: https://github.com/nextcloud/spreed-ios
