### ISSUE TITLE
Video/voice chat overlay in other parts of Nextcloud

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#230]
We discussed in the past about a video overlay in the bottom right in other parts of Nextcloud.

The crucial part here is when switching an app or opening a document with Collabora the video & audio will cut out for a few seconds. This is especially strange for the recipient.

Basically, when a video call is in progress, we can not do a full page refresh. A potential solution would be a pseudo-single-page app which only changes the content of the #app-content area. Discussed this before with @xMartin and @LukasReschke, what do you think @Ivansss @nickvergessen?

This is also related to the upcoming Contacts menu https://github.com/nextcloud/server/issues/207 which will enable people to make calls from anywhere. cc @ChristophWurst

**Comment by nickvergessen** [comment]
Yeah sounds good, but that needs to be done in the server to begin with, not in this app.
Not sure if this is fastly doable thou, but 1. I'm no JS expoert and 2. long term goal for sure.

**Comment by jancborchardt** [comment]
Yup, just putting it here for reference. :) Will definitely need some modifications in the server.

**Comment by jancborchardt** [comment]
This might even be natively possible on macOS: https://www.howtogeek.com/275514/how-to-use-sierras-picture-in-picture-mode-with-netflix-youtube-and-other-unsupported-sites/

And on Linux and Windows we can simply use a popup, then you can use it on top of other apps too. In Gnome there’s even the right-click option »always on top« so it will float above all other windows. (Sure it’s a bit complicated, but we can point it out.)

cc @gsambrotta @Ivansss :) This would be something cool for Nextcloud 12 and the whole »Collaboration« narrative.

**Comment by nickvergessen** [comment]
https://testpilot.firefox.com/experiments/min-vid

**Comment by nickvergessen** [comment]
Done for the files app. Closing
