### ISSUE TITLE
Call menu input box positioning broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#231]
Check this out:
![capture du 2017-01-24 01-24-29](https://cloud.githubusercontent.com/assets/925062/22228872/34a92f5e-e1d4-11e6-8304-4747debf9251.png)
![capture du 2017-01-24 01-24-09](https://cloud.githubusercontent.com/assets/925062/22228873/355c794c-e1d4-11e6-8b60-059a5d0efb81.png)
Instead it should be like before:
- The share link input box below the »Share link« row, full width. Delete button on the same row as the »Share link« label, to the right. Copy button on the right in the input field.
- Rename input box should be full width too, with the confirm button on the right inside the input box
- Also the position is slightly off (too far left) and the top right border radius is missing

Also, the rename input box should have the current name prefilled and selected as a whole. cc @Ivansss

**Comment by nickvergessen** [comment]
Does not happen for 1to1 calls.
