### ISSUE TITLE
Error in Navigation Link with reverse proxy

### ISSUE THREAD

**Issue by PocketFR** [nextcloud/spreed#2312]
## Steps to reproduce
Use nginx as reverse proxy
Install the talk app

### Expected behaviour
The link to the app is relative and links to "/index.php/apps/spreed/" 

### Actual behaviour
The link to the app is absolute and links to "http://127.0.0.1:8080/index.php/apps/spreed/"

My fix : 
replace line 164 of /lib/AppInfo/Application.php:
from : 
'href' => $server->getURLGenerator()->linkToRouteAbsolute('spreed.Page.index'),
to : 
'href' => $server->getURLGenerator()->linkToRoute('spreed.Page.index'),

If this isn't a good fix, why this link needs to be absolute ?

**Comment by nickvergessen** [comment]
Well you should never the less fix the method, because otherwise links send via emails and more wont work as intended

**Comment by nickvergessen** [comment]
Please provide the data requested by the issue template for more assistance:
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

**Comment by PocketFR** [comment]
> Well you should never the less fix the setup, because otherwise links send via emails and more wont work as intended

Yeah i see that later... Now i will RTFM about how to configure reverse proxy on nextcloud, sorry for wasting your time :/
