### ISSUE TITLE
Can't hide the call panel when accessed by smartphone with a shared URL.

### ISSUE THREAD

**Issue by Bables55** [nextcloud/spreed#2313]
## Steps to reproduce
1. Activate Talk app
2. Create a shared URL
3. Access the shared URL on smartphone.

### Expected behaviour
The user can close/hide the details panel (call start panel).

### Actual behaviour
No user can close/hide the details(call start) panel.
There is no button to close the panel with the "Start Call" button.
The user does not hide the detail panel wherever the user touches the NC with the smartphone in landscape view.
In other words, if I have the Talk app enabled, I will be specialized in calling and messaging on my smartphone.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** iOS 13.1.2

**Browser name:** Safari, Chrome, iCab

**Browser version:** Latest

## Talk app

**Talk app version:** 7.0.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: CentOS 7.7

**Web server:** Nginx 1.14.2

**Database:** MariaDB

**PHP version:** 7.3.10

**Nextcloud Version:** 17.0.0

**Comment by danxuliu** [comment]
This was fixed in #2413, and therefore in the just released Talk 7.0.2 :-)
