### ISSUE TITLE
"Add to projects" dialog sorts Talk conversations unexpectedly

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2314]
When you add a Talk conversation to a folder, you see this dialog:
![Add to project conversation list sorting oldest first](https://user-images.githubusercontent.com/925062/66846374-07f02680-ef72-11e9-8c04-d7286002c8ac.png)

The converations are sorted by date of creation, oldest first. How we should do it instead:
- Sort by recently active first
- Favorited rooms even above that

cc @juliushaertl

**Comment by juliushaertl** [comment]
Actually this is done in talk itself cc @nickvergessen

**Comment by nickvergessen** [comment]
I will have a look, but I guess it's actually sorted by recent activity, just the wrong direction, because we actually only have one endpoint to return conversations.

**Comment by jancborchardt** [comment]
@nickvergessen I thought that too, but scrolled to the bottom and it was definitely not the most recently active. (E.g. in the screenshot you can see "Talk team private" which we use pretty actively.)

That’s why i was so confused too. :)

**Comment by nickvergessen** [comment]
okay, face palm there... currently conversations are sorted in the UI, not in the backend.

So the items should be sorted here:
https://github.com/nextcloud/spreed/blob/master/vue/src/views/RoomSelector.vue#L151
