### ISSUE TITLE
No ldap users visable in new conversation section.

### ISSUE THREAD

**Issue by dionsamsoe** [nextcloud/spreed#2324]
### Steps to reproduce
Open Nextcloud Talk and try to open a new conversation via webbrowser

### Expected behaviour
When opening Nextcloud Talk app it usually shows a list of users when u click on the New Conversation tab.

### Actual behaviour
When opening Nextcloud Talk app will keep informing that it is searching for users and no users are displayed.

## Server configuration detail

**Operating system:** Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.18

**PHP version:** 

7.3.10-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 15

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.zip

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - admin_audit: 1.6.0
 - apporder: 0.8.0
 - cloud_federation_api: 0.2.0
 - dav: 1.9.2
 - deck: 0.6.6
 - external: 3.3.1
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_rightclick: 0.15.1
 - files_texteditor: 2.8.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - serverinfo: 1.6.0
 - spreed: 6.0.4
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - uploaddetails: 0.1.2
 - user_ldap: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - activity
 - comments
 - encryption
 - federation
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_versions
 - files_videoplayer
 - firstrunwizard
 - gallery
 - nextcloud_announcements
 - password_policy
 - recommendations
 - sharebymail
 - support
 - survey_client
 - systemtags

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "drive.itwolk.nl"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "https:\/\/drive.itwolk.nl",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": false,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "loglevel": 0,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 5368709120,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "overwriteprotocol": "https",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "theme": "",
    "trashbin_retention_obligation": "auto, 7",
    "updater.release.channel": "production",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "2525",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "app_install_overwrite": [
        "occweb",
        "ldaporg"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** SMB to Windows Server 2016

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: s01cleanUpJobOffset: 0enabled: yesinstalled_version: 1.6.0s01_lastChange: 1571253572s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: S0A5TEcqbSs9Rg==s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: dc02-2016.itwolk.nls01ldap_backup_port: 389s01ldap_base: DC=itwolk,DC=nls01ldap_base_groups: DC=itwolk,DC=nls01ldap_base_users: DC=itwolk,DC=nls01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: CN=SA_Nextcloud,OU=Service Accounts,OU=Nextcloud,DC=itwolk,DC=nls01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 0s01ldap_expert_username_attr: sAMAccountNames01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=group))(|(cn=NC_FR_CANTO)(cn=NC_FR_MIRAGE)(cn=NC_SHR_CANTO_DATA)(cn=NC_SHR_Sales)(cn=NC_SHR_Support)(cn=NC_SHR_Tijdelijke_Bestanden)(cn=NC_Users)(cn=NC_Admins)(cn=NC_SHR_BNSolutions)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: members01ldap_groupfilter_groups: NC_FR_CANTO
NC_FR_MIRAGE
NC_SHR_CANTO_DATA
NC_SHR_Sales
NC_SHR_Support
NC_SHR_Tijdelijke_Bestanden
NC_Users
NC_Admins
NC_SHR_BNSolutionss01ldap_groupfilter_objectclass: groups01ldap_host: dc01-2016.itwolk.nls01ldap_login_filter: (&(&(|(objectclass=user))(|(|(memberof=CN=NC_Users,OU=Security Groups,OU=Nextcloud,DC=itwolk,DC=nl)(primaryGroupID=3251))(|(memberof=CN=NC_Admins,OU=Security Groups,OU=Nextcloud,DC=itwolk,DC=nl)(primaryGroupID=3254))))(samaccountname=%uid))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: NC_Users
NC_Adminss01ldap_userfilter_objectclass: users01ldap_userlist_filter: (&(|(objectclass=user))(|(|(memberof=CN=NC_Users,OU=Security Groups,OU=Nextcloud,DC=itwolk,DC=nl)(primaryGroupID=3251))(|(memberof=CN=NC_Admins,OU=Security Groups,OU=Nextcloud,DC=itwolk,DC=nl)(primaryGroupID=3254))))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

**Operating system:** Windows Server 2016/Windows 10 1809

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
well there should be something in the browser log if an error happens there.

**Comment by dionsamsoe** [comment]
Excuse me, i forgot to add the logs.

This is what the Google chrome console gives when clicking on the "New Conversation" while changing the status to Searching.

Google Chrome:
JQMIGRATE: Migrate is installed, version 1.4.1
DevTools failed to parse SourceMap: https://drive.itwolk.nl/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://drive.itwolk.nl/apps/notifications/js/notifications.js.map
main.js?v=8526a869-14:750 The select2 library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=8526a869-14:750
initAddParticipantSelector @ merged.js?v=8526a869-14:12355
onRender @ merged.js?v=8526a869-14:12334
r @ merged.js?v=8526a869-14:17
triggerMethod @ merged.js?v=8526a869-14:17
render @ merged.js?v=8526a869-14:17
P @ main.js?v=8526a869-14:39
(anonymous) @ main.js?v=8526a869-14:39
(anonymous) @ main.js?v=8526a869-14:39
initialize @ merged.js?v=8526a869-14:12314
e.View @ merged.js?v=8526a869-14:1
constructor @ merged.js?v=8526a869-14:17
n @ merged.js?v=8526a869-14:1
_showParticipantList @ merged.js?v=8526a869-14:18628
onStart @ merged.js?v=8526a869-14:19039
r @ merged.js?v=8526a869-14:17
start @ merged.js?v=8526a869-14:18
(anonymous) @ merged.js?v=8526a869-14:19294
(anonymous) @ merged.js?v=8526a869-14:19295
main.js?v=8526a869-14:750 The select2 library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=8526a869-14:750
_registerPageEvents @ merged.js?v=8526a869-14:18443
onStart @ merged.js?v=8526a869-14:19060
r @ merged.js?v=8526a869-14:17
start @ merged.js?v=8526a869-14:18
(anonymous) @ merged.js?v=8526a869-14:19294
(anonymous) @ merged.js?v=8526a869-14:19295
DevTools failed to parse SourceMap: https://drive.itwolk.nl/apps/spreed/js/collections.js.map
merged.js?v=8526a869-14:18455 Uncaught TypeError: Cannot read property 'SHARE_TYPE_USER' of undefined
    at n.<anonymous> (merged.js?v=8526a869-14:18455)
    at main.js?v=8526a869-14:504
(anonymous) @ merged.js?v=8526a869-14:18455
(anonymous) @ main.js?v=8526a869-14:504
setTimeout (async)
(anonymous) @ main.js?v=8526a869-14:504
updateResults @ main.js?v=8526a869-14:504
opening @ main.js?v=8526a869-14:504
open @ main.js?v=8526a869-14:504
(anonymous) @ main.js?v=8526a869-14:504
(anonymous) @ main.js?v=8526a869-14:504
dispatch @ main.js?v=8526a869-14:39
_.handle @ main.js?v=8526a869-14:39

**Comment by nickvergessen** [comment]
> Uncaught TypeError: Cannot read property 'SHARE_TYPE_USER' of undefined

That's interesting. It works pretty fine here.

**Comment by dionsamsoe** [comment]
I also encounter the same problem when using the deck application. (Version 0.6.6)

If the users clicks on the contact icon at the top right of nextcloud they can see all the users that are in the same group.
Both the users and groups are integrated from the LDAP user and group backend.

This is the chrome console error in case it is a similar issue.

Google Chrome:
Possibly unhandled rejection: Error while searching for sharees
(anonymous) @ deck.js?v=8526a869-14:53474
(anonymous) @ deck.js?v=8526a869-14:49753
processChecks @ deck.js?v=8526a869-14:55884
$digest @ deck.js?v=8526a869-14:57019
$apply @ deck.js?v=8526a869-14:57407
done @ deck.js?v=8526a869-14:51250
completeRequest @ deck.js?v=8526a869-14:51507
requestLoaded @ deck.js?v=8526a869-14:51412
load (async)
(anonymous) @ deck.js?v=8526a869-14:51395
sendReq @ deck.js?v=8526a869-14:51195
serverRequest @ deck.js?v=8526a869-14:50936
processQueue @ deck.js?v=8526a869-14:55852
(anonymous) @ deck.js?v=8526a869-14:55900
$digest @ deck.js?v=8526a869-14:57019
$apply @ deck.js?v=8526a869-14:57407
(anonymous) @ deck.js?v=8526a869-14:59508
completeTask @ deck.js?v=8526a869-14:59138
(anonymous) @ deck.js?v=8526a869-14:44719
setTimeout (async)
Browser.self.defer @ deck.js?v=8526a869-14:44717
timeout @ deck.js?v=8526a869-14:59498
ctrl.refresh @ deck.js?v=8526a869-14:83313
(anonymous) @ deck.js?v=8526a869-14:82990
$digest @ deck.js?v=8526a869-14:57047
$apply @ deck.js?v=8526a869-14:57407
done @ deck.js?v=8526a869-14:51250
completeRequest @ deck.js?v=8526a869-14:51507
requestLoaded @ deck.js?v=8526a869-14:51412
load (async)
(anonymous) @ deck.js?v=8526a869-14:51395
sendReq @ deck.js?v=8526a869-14:51195
serverRequest @ deck.js?v=8526a869-14:50936
processQueue @ deck.js?v=8526a869-14:55852
(anonymous) @ deck.js?v=8526a869-14:55900
$digest @ deck.js?v=8526a869-14:57019
$apply @ deck.js?v=8526a869-14:57407
bootstrapApply @ deck.js?v=8526a869-14:39870
invoke @ deck.js?v=8526a869-14:43048
doBootstrap @ deck.js?v=8526a869-14:39868
bootstrap @ deck.js?v=8526a869-14:39888
angularInit @ deck.js?v=8526a869-14:39773
(anonymous) @ deck.js?v=8526a869-14:74337
u @ main.js?v=8526a869-14:39
fireWith @ main.js?v=8526a869-14:39
ready @ main.js?v=8526a869-14:39
O @ main.js?v=8526a869-14:39

**Comment by nickvergessen** [comment]
> Error while searching for sharees

Here you have the problem. You can either try to solve this yourself, or I would suggest to search for help in the forums: https://help.nextcloud.com/ . This seems to be an issue with your setup, not with Talk or Deck.

**Comment by dionsamsoe** [comment]
I resolved the issue by enabeling the following app:
File sharing 1.8.0

**Comment by intika** [comment]
Indeed if files haring is not enabled starting conversation does not work... the dependency should be indicated...
