### ISSUE TITLE
No new translations from Transifex - v7.0.1

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2325]
Version 7.0.1 is missing new translations from Transifex.

One example:

![obraz](https://user-images.githubusercontent.com/47037905/67034274-b1245180-f117-11e9-8f41-57e497c336a7.png)

The last download from Transifex was c28a91f59db69d40e3f123c3308757f1c49d0101.

I always ask developers to download new translations from Transifex before releasing the new version. This will help us translators further improve the translation of the app. Full translation will also allow users to use and fully understand the app options.

**Comment by nickvergessen** [comment]
(I originally posted it in the wrong issue (#2326 )

Sorry about that, in fact we have a cron job which takes care to download the translations on a daily basis. However it seems to be broken since 8 days.
I will look into this tomorrow.

**Comment by nickvergessen** [comment]
Should be fixed and I manually triggered it once now:
https://github.com/nextcloud/spreed/commit/1743f056f3e46cf1f4d20ade5345a1bfb07d52d1

**Comment by Valdnet** [comment]
@nickvergessen Thanks great 😉.
