### ISSUE TITLE
No translated: Select option

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2326]
## Steps to reproduce
1. Select Talk settings in the admin panel.
2. Click in the selection window: Start calls
3. No translated description: **Select option**.

![obraz](https://user-images.githubusercontent.com/47037905/67077297-3f87ea00-f18f-11e9-9844-24a9c559af53.png)

Description not available for translation in Transifex.

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
7.0.1

**Nextcloud Version:** (see admin page)
17.0.0

**Comment by nickvergessen** [comment]
Sorry about that, in fact we have a cron job which takes care to download the translations on a daily basis. However it seems to be broken since 8 days.
I will look into this tomorrow.
