### ISSUE TITLE
PeerConnection not established between Chrome and FF with only one camera/mic

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#234]
## Steps to reproduce
1. Run Chrome 49.0.2623.110 (yeah old, but latest version supported on my Ubuntu Precise) without a camera/mic (i.e. camera/mic access disabled). Logged in to NC and created public room.
2. Run Firefox 50.1.0 with camera/mic enabled. Join as guest to public room.

### Expected behaviour
Chrome should see the Firefox user.

### Actual behaviour
The PeerConnection is not being established. Firefox only shows the local SDP in `about:webrtc` but no remote SDP or candidates. Chrome shows a black area for the Firefox user, the Firefox user sees `Warte auf Teilnehmer <username> ...`.

I'm running 3740dc0b08bb97957a34f5f6e302e8d57684168c.

Please let me know if you need any additional information or where I should add some debugging code to track this down.

@Ivansss @nickvergessen

**Comment by JSoko** [comment]
Same here with chrome  55.0.2883.87 m under Windows without Mic and Video
On the other side Firefox or Chrome under Android with active Mic/Video

**Comment by fancycode** [comment]
Further information: Chrome sends an answer and candidates to the `signalling` endpoint, but they don't show up in the Firefox debugging console / networking tab.

**Comment by fancycode** [comment]
@LukasReschke any ideas? No error is logged in either of the browsers or in `nextcloud.log`.

**Comment by Ivansss** [comment]
@JSoko @fancycode are you still experimenting this issue?

**Comment by Ivansss** [comment]
@fancycode Could you take a look to this PR #255 and check if it solves the problem?
