### ISSUE TITLE
prevent people from navigating away from a call

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2344]
It happens regularly to me that I'm in a call, want to look something up in another chat, click on it in the sidebar and leave the ongoing call this way.

A warning like "do you really want to leave the call" would be nice in this case. Or, if we don't want to disturb the user with a dialog, automatically open the room in another tab/window in case of a ongoing call might be a nice solution as well.

**Comment by nickvergessen** [comment]
Duplicate of #1175
