### ISSUE TITLE
Add entries in the Activities app

### ISSUE THREAD

**Issue by oparoz** [nextcloud/spreed#236]
## Steps to reproduce
1. Create a group call
2. As a recipient, click on the notification to got to the call and close the notification

### Expected behaviour

I should be able to got to Activities and see that I got a call, who with and for how long

### Actual behaviour

I don't see anything in my activities stream

**Comment by jancborchardt** [comment]
Yup! cc @nickvergessen @Ivansss

**Comment by MariusBluem** [comment]
And with this new use-case of the notifications - we may overthink permanent showing the notification-icon next to the contacts-menu 🤔 @jancborchardt

**Comment by nickvergessen** [comment]
This is about activities not notificationd

**Comment by MariusBluem** [comment]
Forget what i've said 😏🙊

**Comment by jancborchardt** [comment]
It’s part of the same flow though:
1. You get a call, it shows up in Notifications
2. You take it, call with that person
3. Afterwards the activity app shows the details of the call as activity

**Comment by nickvergessen** [comment]
Jan can you please comment on the question in the PR?

**Comment by nickvergessen** [comment]
Call invitations are handled in #243 now.

Calls are a bit more tricky, because there is no request sent to the server for "now the call starts" and "now the call ended"
