### ISSUE TITLE
Remember "users" panel visibility

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2368]
Everytime I open a chat room the users panel opens as well. If I close it, and change the chat room, it is again opened. What if it remembers the latest state? Could be helpful and maybe it makes some chat-rooms load faster.

**Comment by nickvergessen** [comment]
> maybe it makes some chat-rooms load faster

I don't really think so, because the chat is much more compared to the few participant entries.

**Comment by nickvergessen** [comment]
Duplicate of #1002
