### ISSUE TITLE
Do not display 'file-conversations' in talk if nobody actually sent a message in the share. 

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2382]
I think that if users just joins conversations automatically by opening the shared file without actually sending a message, we shouldn't display that conversations in the talk app.

The conversations list can get very long if  you share files.

![Screenshot_20191031_141743](https://user-images.githubusercontent.com/26852655/67950188-87742b80-fbe9-11e9-9756-2f2d8e9990ea.png)

**Comment by ma12-co** [comment]
let's keep this in mind for the vue app!

**Comment by ma12-co** [comment]
@nickvergessen @jancborchardt??

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/spreed/pull/2347

**Comment by nickvergessen** [comment]
Closing as per above
