### ISSUE TITLE
Suggest sharing the link to enable others to join a call and collaborate

### ISSUE THREAD

**Issue by hugoroy** [nextcloud/spreed#2422]
**Is your feature request related to a problem? Please describe.**
When creating a call, it's not obvious how to invite people to join in the call and collaborate. Sharing the URL won't work in most cases.

**Describe the solution you'd like**
Maybe provide some pointer that to invite people on the call, you can use a sharing link (provide the URL and the clipboard icon just like in "Sharing")

**Describe alternatives you've considered**
An alternative could be a button "Invite others" to launch a modal dialog with some explanations - share by link, share by sending an email... etc.

**Additional context**
Seems self explanatory

**Comment by juliushaertl** [comment]
Moved to the talk repo. 

@danxuliu @jancborchardt I think this is a nice suggestion. I would be good to give a better indication on how you can add people to the call when a file is not yet shared with others.

**Comment by nickvergessen** [comment]
There is now a prominent option in the creation dialog
