### ISSUE TITLE
Direct talk to a LDAP User

### ISSUE THREAD

**Issue by squalo80** [nextcloud/spreed#2437]
## Steps to reproduce
1.MUST have ldap user in the server
2.Open task
3.you must insert the USERId to find it a particular Ldap User. No other option

### Expected behaviour
Use the Email or a part of Shown name.

### Actual behaviour
ONLY user id

## Browser
 Firefox 64bit 70.0.1

**Microphone available:** no

**Camera available:** no

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 64bit 70.0.1

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** 7.0.1

**Custom TURN server configured:**no
**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu
**Web server:** Apache

**Database:** SQLite

**PHP version:**

**Nextcloud Version:** 17.0.0

**List of activated apps:**Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.7.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_downloadactivity: 1.6.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.4
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.1
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - theming_customcss: 1.4.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - user_usage_report: 1.1.2
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_accesscontrol
  - files_external
  - maps
  - privacy
  - recommendations

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "fs.tecnowerk.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "17.0.0.9",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 1,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
The display name works quite fine. I guess if at all, it is a problem with the configuration of your LDAP.
It should also affect the sharing suggestions as it uses the same API, so I will close this issue.

Try to find help in the forums: https://help.nextcloud.com/
