### ISSUE TITLE
Error message when both video&audio don’t work (like Firefox non-HTTPS)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#244]
When neither your video&audio work, it’s really not necessary to show the placeholder and the icons in the bottom right. They only distract from the error message in the center.

Also then, there should be a more specific error message in the main view. Like when you use Firefox and your instance does not have HTTPS it currently says:
> Error while accessing microphone & camera
> Starting video failed

Better would be:

> Calling only works over a secure connection
> Ask your admin to enable https for your Nextcloud

cc @nextcloud/spreed

**Comment by MG2R** [comment]
Looking at [the code](https://github.com/nextcloud/spreed/blob/86dd06a331cde5bc5e13a73be64f507b5034f2eb/js/webrtc.js#L279-L281), it would seem this is already the case. Maybe your specific issue is caused by something else?

Then again, I'm just a noob so I might be looking at the wrong thing here.

**Comment by nickvergessen** [comment]
It's okay for now, joining without all the stuff will work in #512
