### ISSUE TITLE
Feature request: Delivery and Read Receipts

### ISSUE THREAD

**Issue by alex9434** [nextcloud/spreed#2441]
**Is your feature request related to a problem? Please describe.**
Currently I am not able to see whether the recipient has received the message and read the message

**Describe the solution you'd like**
It would be nice to have indications on each message of the status. I like the logic from other chat systems to mark on each message a) sent, b) delivered and c) read.

**Comment by nickvergessen** [comment]
Duplicate of #1012

**Comment by alex9434** [comment]
Sorry, did not see this. You are right it is a duplicate.
