### ISSUE TITLE
Please let us discuss Threads again

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#2450]
Please notice: Since https://github.com/nextcloud/spreed/issues/1469 is closed, I decided to bring this up again to get more opinions on that topic.

**Is your feature request related to a problem? Please describe.**
When using Nextcloud Talk, you will be able to respond to messages like in Whatsapp or Telegram or other Chat Programs. 

The thing with that is, that the whole chat system is linear. So if you quote a Message, and other topics appear in between, you will not be able to see all replys to a message in one place. 
Additionally this linear chat form often results in people forgetting to answer, because everything is listed in only one level and everyone has to read everything to not beeing endangered to miss something. 

Also to reply you have to select the message you are responding to each time again you want to answer to it if something is posted in between.

In conclusion it becomes really fast a mess and is not really improving productivity.

**Describe the solution you'd like**
I think threads are the solution to the last mentioned problems. 
Because you would be able to see all responses to a message in a fold out view 

So just the normal chat level with new messages representing a possible start for a thread. If answering to a message on the first level, you then would be able to answer directly below the message and not after the newest one of the first level.
All comments in this thread view are then ordered chronically again, so the newest on the buttom, etc. 

A new message on the first level would then be appear on the buttom of the chat. If somebody responds to the thread of a message above, the whole thread then would be listed on the buttom: so it should probably reorder the threads automatically based on the last message.

BTW: I think, that one thread level would be enough. More than one would be less productive imo.

If you haven't understand my proposal or wonder how this could work, please feel free to ask!

**Comment by nickvergessen** [comment]
Well we just can't implement all features, it will simply make Talk unusable all together.

Replies are not yet released, so I would propose to check it out and rediscuss it again after you tried to use it sometime, although I don't see much point in this.

Afterwards please continue the discussion in #1469 because having the discussion spread over multiple issues doesn't help really.
