### ISSUE TITLE
Error handling for temporary messages

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2454]
Temporary messages are local messages that show up in the chat view as soon as the user hits enter. For now, while waiting for the server response we display a little spinner instead of the message time. Once we get a confirmation from the server we display the timestamp. Atm we don't handle unsent messages.

![Screenshot_20191112_103056](https://user-images.githubusercontent.com/26852655/68659486-9f2ba800-0537-11ea-8553-ef4691aeecc7.png)

Things to do: 

- [x] Properly style a temporary message like regular messages (avatar / no avatar);
- [x] Display the temporary message in the conversations preview text. 
- [ ] Set a timeout and add a warning if no response from the server is received. 

^ for this last one I'm not sure how to display the warning.. Red text on top of the message? Red message? What do you think @nextcloud/designers-talk  @nextcloud/talk?  Also I was thinking to display the delete and retry actions explicitly (no 3 dot menu) on the right.

**Comment by ma12-co** [comment]
btw @nickvergessen check out the date :see_no_evil:

**Comment by skjnldsv** [comment]
What about a small airplane icon while sending turning into a small checkmark when sent?
I remember Jan suggesting for something similar  :thinking:

**Comment by jancborchardt** [comment]
Signal does it very well, with
- spinning circle while sending
- one circled checkmark when sent
- 2 circled checkmarks when received
- 2 circled and filled checkmarks when read (if enabled)

Regarding errors, we can show an error icon in place of the spinner. Tapping it can open a menu with a short error info, "Retry send" and "Delete".

**Comment by ma12-co** [comment]
> What about a small airplane icon while sending turning into a small checkmark when sent?

@skjnldsv  I think that the spinner conveys a sense of 'pending stuff to be done' much better than the airplane icon does

>2 circled and filled checkmarks when read (if enabled)

What do you mean with this @jancborchardt? I thought we weren't going to support read confirmation. 

>Regarding errors, we can show an error icon in place of the spinner. Tapping it can open a menu with a short error info, "Retry send" and "Delete".

I like this :-)
We don't have support for anything other than the 3 dot menu for grouped actions atm, right @skjnldsv ?

**Comment by jancborchardt** [comment]
@ma12-co I was simply describing what Signal does and including their design for indicating read state. :) Also, we never know if we will support it in the future.

**Comment by skjnldsv** [comment]
> We don't have support for anything other than the 3 dot icon for grouped actions atm, right @skjnldsv ?

You can use a custom icon now thanks to Georg :)
Though the icon-loading-small might require a tiny bit of css fixes, but give it a try!

**Comment by nickvergessen** [comment]
well read checkmarkers are handled in https://github.com/nextcloud/spreed/issues/1012

The point of this issue is how to deal with failed sendings, to bring in missing parsing of mentions, and make sure the poster information is handled already

**Comment by nickvergessen** [comment]
Just this one left:

> * Set a timeout and add a warning if no response from the server is received.
