### ISSUE TITLE
people only from group

### ISSUE THREAD

**Issue by happyreacer** [nextcloud/spreed#246]
It wuld be nice to see only peoples from the nextcloudgroup. Is it easy to introduce?

**Comment by nickvergessen** [comment]
You mean that the search results should only list users from your own groups?

**Comment by happyreacer** [comment]
@nickvergessen yes, exactly, perhaps with an option 
`all NC users <-> only group users`

**Comment by nickvergessen** [comment]
This uses the same control as sharing. It already has the option to limit sharing, so you can only see people in your groups.
