### ISSUE TITLE
 nextcloud. Applications talks. not loading

### ISSUE THREAD

**Issue by serjke46** [nextcloud/spreed#2463]
![Сохраненное изображение 2019-11-14_13-19-19 372](https://user-images.githubusercontent.com/57752172/68848604-7d155f80-06c8-11ea-9adf-11528ba4bd16.jpg)

loading spins endlessly. help me please

**Comment by serjke46** [comment]
I tried to reinstall the application, went through different browsers. Nothing helps

**Comment by nickvergessen** [comment]
Please press F12 and check if your console shows any useful error messages

**Comment by serjke46** [comment]
![image](https://user-images.githubusercontent.com/57752172/68921703-77c01f80-0771-11ea-9bf9-10f1895f83a5.png)

**Comment by nickvergessen** [comment]
Is there something in your nextcloud log file

**Comment by serjke46** [comment]
![image](https://user-images.githubusercontent.com/57752172/68935265-40ad3680-0790-11ea-9755-17a1ee91e20d.png)

**Comment by serjke46** [comment]
{"reqId":"oAh4IM4eSn3zqq33b7Uq","level":3,"time":"2019-11-15T09:54:21+00:00","remoteAddr":"192.168.1.15","user":"smotrov","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/spreed/api/v1/room","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?' with params [\"\\x83\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb2\\x20\\xd0\\x90\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9d\\xd0\\xb5\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd1\\x86\\xd0\\xb5\\xd0\\xb2\\x20\\xd0\\x92\\x2e\\xd0\\x9f\\x2e\\x2c\\x20\\xd0\\x91\\xd1\\x83\\xd1\\x80\\xd0\\xb4\\xd0\\xb0\\xd1\\x81\\xd1\\x82\\xd1\\x8b\\xd1\\x85\\x20\\xd0\\x9d\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x94\\xd0\\xb0\\xd0\\xb2\\xd1\\x8b\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xba\\xd0\\xbe\\x20\\xd0\\x98\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9a\\xd0\\xb0\\xd0\\xbb\\xd1\\x83\\xd0\\xb3\\xd0\\xb8\\xd0\\xbd\\x20\\xd0\\x92\\x2e\\xd0\\x9d\\x2e\\xe2\\x80\\xa6\", 8]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1","Code":0,"Trace":[{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?' with params [\"\\x83\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb2\\x20\\xd0\\x90\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9d\\xd0\\xb5\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd1\\x86\\xd0\\xb5\\xd0\\xb2\\x20\\xd0\\x92\\x2e\\xd0\\x9f\\x2e\\x2c\\x20\\xd0\\x91\\xd1\\x83\\xd1\\x80\\xd0\\xb4\\xd0\\xb0\\xd1\\x81\\xd1\\x82\\xd1\\x8b\\xd1\\x85\\x20\\xd0\\x9d\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x94\\xd0\\xb0\\xd0\\xb2\\xd1\\x8b\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xba\\xd0\\xbe\\x20\\xd0\\x98\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9a\\xd0\\xb0\\xd0\\xbb\\xd1\\x83\\xd0\\xb3\\xd0\\xb8\\xd0\\xbd\\x20\\xd0\\x92\\x2e\\xd0\\x9d\\x2e\\xe2\\x80\\xa6\", 8]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1",{"errorInfo":["HY000",1366,"Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":158,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY000",1366,"Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?' with params [\"\\x83\\xd1\\x88\\xd0\\xba\\xd0\\xbe\\xd0\\xb2\\x20\\xd0\\x90\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9d\\xd0\\xb5\\xd0\\xb6\\xd0\\xb5\\xd0\\xbd\\xd1\\x86\\xd0\\xb5\\xd0\\xb2\\x20\\xd0\\x92\\x2e\\xd0\\x9f\\x2e\\x2c\\x20\\xd0\\x91\\xd1\\x83\\xd1\\x80\\xd0\\xb4\\xd0\\xb0\\xd1\\x81\\xd1\\x82\\xd1\\x8b\\xd1\\x85\\x20\\xd0\\x9d\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x94\\xd0\\xb0\\xd0\\xb2\\xd1\\x8b\\xd0\\xb4\\xd0\\xb5\\xd0\\xbd\\xd0\\xba\\xd0\\xbe\\x20\\xd0\\x98\\x2e\\xd0\\x92\\x2e\\x2c\\x20\\xd0\\x9a\\xd0\\xb0\\xd0\\xbb\\xd1\\x83\\xd0\\xb3\\xd0\\xb8\\xd0\\xbd\\x20\\xd0\\x92\\x2e\\xd0\\x9d\\x2e\\xe2\\x80\\xa6\", 8]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1"]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1088,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY000",1366,"Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?",{"1":null,"2":8}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?",[null,8],[2,1]]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":222,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = :dcValue1 WHERE `id` = :dcValue2",{"dcValue1":null,"dcValue2":8},{"dcValue1":2,"dcValue2":1}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":299,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Manager.php","line":637,"function":"setName","class":"OCA\\Spreed\\Room","type":"->","args":[null]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":157,"function":"resolveRoomDisplayName","class":"OCA\\Spreed\\Manager","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},"smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":205,"function":"getDisplayName","class":"OCA\\Spreed\\Room","type":"->","args":["smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":121,"function":"formatRoom","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},{"__class__":"OCA\\Spreed\\Participant"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"getRooms","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v2.php","line":24,"args":["/snap/nextcloud/16739/htdocs/ocs/v1.php"],"function":"require_once"}],"File":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":125,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1","Code":"HY000","Trace":[{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1079,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?",[null,8],[2,1]]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":222,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = :dcValue1 WHERE `id` = :dcValue2",{"dcValue1":null,"dcValue2":8},{"dcValue1":2,"dcValue2":1}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":299,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Manager.php","line":637,"function":"setName","class":"OCA\\Spreed\\Room","type":"->","args":[null]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":157,"function":"resolveRoomDisplayName","class":"OCA\\Spreed\\Manager","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},"smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":205,"function":"getDisplayName","class":"OCA\\Spreed\\Room","type":"->","args":["smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":121,"function":"formatRoom","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},{"__class__":"OCA\\Spreed\\Participant"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"getRooms","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v2.php","line":24,"args":["/snap/nextcloud/16739/htdocs/ocs/v1.php"],"function":"require_once"}],"File":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":143,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x83\\xD1\\x88\\xD0\\xBA\\xD0...' for column 'name' at row 1","Code":"HY000","Trace":[{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":141,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1079,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/Connection.php","line":216,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = ? WHERE `id` = ?",[null,8],[2,1]]},{"file":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":222,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_talk_rooms` SET `name` = :dcValue1 WHERE `id` = :dcValue2",{"dcValue1":null,"dcValue2":8},{"dcValue1":2,"dcValue2":1}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":214,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":299,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Manager.php","line":637,"function":"setName","class":"OCA\\Spreed\\Room","type":"->","args":[null]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Room.php","line":157,"function":"resolveRoomDisplayName","class":"OCA\\Spreed\\Manager","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},"smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":205,"function":"getDisplayName","class":"OCA\\Spreed\\Room","type":"->","args":["smotrov"]},{"file":"/var/snap/nextcloud/16739/nextcloud/extra-apps/spreed/lib/Controller/RoomController.php","line":121,"function":"formatRoom","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[{"__class__":"OCA\\Spreed\\Room"},{"__class__":"OCA\\Spreed\\Participant"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"getRooms","class":"OCA\\Spreed\\Controller\\RoomController","type":"->","args":[]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Spreed\\Controller\\RoomController"},"getRooms"]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Spreed\\Controller\\RoomController","getRooms",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","_route":"ocs.spreed.Room.getRooms"}]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/room"]},{"file":"/snap/nextcloud/16739/htdocs/ocs/v2.php","line":24,"args":["/snap/nextcloud/16739/htdocs/ocs/v1.php"],"function":"require_once"}],"File":"/snap/nextcloud/16739/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":141}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","version":"16.0.5.1","id":"5dce75fed5f40"}

**Comment by nickvergessen** [comment]
Which language have you selected?

**Comment by serjke46** [comment]
Russia

**Comment by nickvergessen** [comment]
Hmm I think you need to use utf8mb4 for the russian language to work:
https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

It will also cause problems for emojis and other characters otherwise.
But of course we should try to not fail hard like this.

**Comment by nickvergessen** [comment]
Hmm actually it seems to be a problem with the userid. If you use utf8 characters in your user id, you need to use mysql 4byte support as per above. Otherwise also one-to-one conversations will not work
