### ISSUE TITLE
The column 'in_call' on table 'oc_talk_participants' already exists.

### ISSUE THREAD

**Issue by SirBirne** [nextcloud/spreed#2470]
## Steps to reproduce
1. Activate app in store (maybe it was already installed on previous version of nextcloud)

### Expected behaviour
Should activate the app.

### Actual behaviour
Doesn't activate the app. Throwing the following error: The column 'in_call' on table 'oc_talk_participants' already exists.

**Comment by izio38** [comment]
Can I know why you turn this issue down when the issue is still here ?

**Comment by nickvergessen** [comment]
Well I can not reproduce the issue and the given information is not enough to reproduce it, so the ticket was closed after ~6 months without a reply. Also no one else asked for it in the meantime, meaning it looks more like someone fiddled around in the database directly and broke things with that.

**Comment by izio38** [comment]
I can provide more informations if needed.

I created a Nextcloud stack 
![image](https://user-images.githubusercontent.com/9900846/91567162-fc68dc80-e944-11ea-9e5a-a9e9314a9966.png)

First in an older version (the rancher template is using an old version), then I updated to latest, which triggered the applications update. During the update my server crashed hence, stopping the nextcloud process.

I think it's like stopping the update (migrations ?)

I can resolve the issue by manipulating the database, but I just wanted to make sure you guys know something isn't smooth here.

**Comment by sundowndev** [comment]
I have the same issue with the last version of Nextcloud.

**Comment by SirBirne** [comment]
Nobody asked me for more information. I don't know what kind of information you need. I never touched the database. Can't think of any crashes. The error message itself is very self explanatory. There is a column on a table... How to fix? Drop and recreate, ignore, whatever. I don't know how it did get there but i guess it was created when i installed the plugin for the first time but it was not removed when i uninstalled it? If there is something like a "install history" on Nextcloud I would love to give it to you. It might be that there was just a bug in your uninstall logic in the version I installed first.

Just tell me how I can deliver meaningfull information to you guys. I still have the issue, and I don't want to fiddle around in the database. It seems to be a rare issue but as you see, there are still others with the same problem.

**Comment by celonix** [comment]
@SirBirne @nickvergessen @izio38 @sundowndev 

I ran into the same issue after the installation of Talk failed and I tried to reinstall it. After a few hours I found a very simple workaround which worked for me: 
Go into phppgadmin or whatever you use to manage your PostgreSQL Database and remove that column from the table... 
and then the reinstallation worked... :)

**Comment by celonix** [comment]
@nickvergessen 
I don't understand the problem behind this error yet, but I tried to removed the tables of Talk completly and ran into following error:
`There is no table with name 'oc_admin.oc_talk_participants' in the schema.`

Is there maybe somewhere an information stored that Talk was installed before? 
I have some logs for you, maybe they will help:

<details>
{
   "reqId":"d0OZjy5qieFCaeUbZeef",
   "level":3,
   "time":"2020-10-18T16:54:24+02:00",
   "remoteAddr":"XXXXXXXXXXXXXXXXXXXXXXXXXX",
   "user":"admin",
   "app":"settings",
   "method":"POST",
   "url":"/index.php/settings/apps/enable",
   "message":{
      "Exception":"Doctrine\\DBAL\\Schema\\SchemaException",
      "Message":"There is no table with name 'oc_admin.oc_talk_participants' in the schema.",
      "Code":10,
      "Trace":[
         {
            "file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php",
            "line":168,
            "function":"tableDoesNotExist",
            "class":"Doctrine\\DBAL\\Schema\\SchemaException",
            "type":"::",
            "args":[
               "oc_admin.oc_talk_participants"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/DB/SchemaWrapper.php",
            "line":93,
            "function":"getTable",
            "class":"Doctrine\\DBAL\\Schema\\Schema",
            "type":"->",
            "args":[
               "oc_admin.oc_talk_participants"
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/spreed/lib/Migration/Version3003Date20180722152849.php",
            "line":45,
            "function":"getTable",
            "class":"OC\\DB\\SchemaWrapper",
            "type":"->",
            "args":[
               "talk_participants"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/DB/MigrationService.php",
            "line":478,
            "function":"changeSchema",
            "class":"OCA\\Talk\\Migration\\Version3003Date20180722152849",
            "type":"->",
            "args":[
               {
                  "__class__":"OC\\Migration\\SimpleOutput"
               },
               {
                  "__class__":"Closure"
               },
               {
                  "tablePrefix":"oc_"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/DB/MigrationService.php",
            "line":414,
            "function":"executeStep",
            "class":"OC\\DB\\MigrationService",
            "type":"->",
            "args":[
               "3003Date20180722152849",
               false
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Installer.php",
            "line":157,
            "function":"migrate",
            "class":"OC\\DB\\MigrationService",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
            "line":447,
            "function":"installApp",
            "class":"OC\\Installer",
            "type":"->",
            "args":[
               "spreed"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":170,
            "function":"enableApps",
            "class":"OCA\\Settings\\Controller\\AppSettingsController",
            "type":"->",
            "args":[
               [
                  "spreed"
               ],
               [
                  
               ]
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":100,
            "function":"executeController",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\AppSettingsController"
               },
               "enableApps"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/App.php",
            "line":137,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\AppSettingsController"
               },
               "enableApps"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
            "line":47,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::",
            "args":[
               "OCA\\Settings\\Controller\\AppSettingsController",
               "enableApps",
               {
                  "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
               },
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "function":"__invoke",
            "class":"OC\\AppFramework\\Routing\\RouteActionHandler",
            "type":"->",
            "args":[
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Route/Router.php",
            "line":297,
            "function":"call_user_func",
            "args":[
               {
                  "__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"
               },
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/base.php",
            "line":1011,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->",
            "args":[
               "/settings/apps/enable"
            ]
         },
         {
            "file":"/var/www/nextcloud/index.php",
            "line":37,
            "function":"handleRequest",
            "class":"OC",
            "type":"::",
            "args":[
               
            ]
         }
      ],
      "File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php",
      "Line":30,
      "CustomMessage":"--"
   },
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
   "version":"19.0.4.2"
}
</details>
<details>
{
   "reqId":"59UhsWd5yimsAaeIcADc",
   "level":3,
   "time":"2020-10-18T15:22:26+02:00",
   "remoteAddr":"XXXXXXXXXXX",
   "user":"admin",
   "app":"settings",
   "method":"POST",
   "url":"/index.php/settings/apps/enable",
   "message":{
      "Exception":"Doctrine\\DBAL\\Schema\\SchemaException",
      "Message":"The column 'in_call' on table 'oc_talk_participants' already exists.",
      "Code":40,
      "Trace":[
         {
            "file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php",
            "line":450,
            "function":"columnAlreadyExists",
            "class":"Doctrine\\DBAL\\Schema\\SchemaException",
            "type":"::",
            "args":[
               "oc_talk_participants",
               "in_call"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php",
            "line":291,
            "function":"_addColumn",
            "class":"Doctrine\\DBAL\\Schema\\Table",
            "type":"->",
            "args":[
               {
                  "__class__":"Doctrine\\DBAL\\Schema\\Column"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/spreed/lib/Migration/Version3003Date20180722152849.php",
            "line":47,
            "function":"addColumn",
            "class":"Doctrine\\DBAL\\Schema\\Table",
            "type":"->",
            "args":[
               "in_call",
               "integer",
               {
                  "default":0
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/DB/MigrationService.php",
            "line":478,
            "function":"changeSchema",
            "class":"OCA\\Talk\\Migration\\Version3003Date20180722152849",
            "type":"->",
            "args":[
               {
                  "__class__":"OC\\Migration\\SimpleOutput"
               },
               {
                  "__class__":"Closure"
               },
               {
                  "tablePrefix":"oc_"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/DB/MigrationService.php",
            "line":414,
            "function":"executeStep",
            "class":"OC\\DB\\MigrationService",
            "type":"->",
            "args":[
               "3003Date20180722152849",
               false
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Installer.php",
            "line":157,
            "function":"migrate",
            "class":"OC\\DB\\MigrationService",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
            "line":447,
            "function":"installApp",
            "class":"OC\\Installer",
            "type":"->",
            "args":[
               "spreed"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":170,
            "function":"enableApps",
            "class":"OCA\\Settings\\Controller\\AppSettingsController",
            "type":"->",
            "args":[
               [
                  "spreed"
               ],
               [
                  
               ]
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":100,
            "function":"executeController",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\AppSettingsController"
               },
               "enableApps"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/App.php",
            "line":137,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\AppSettingsController"
               },
               "enableApps"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
            "line":47,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::",
            "args":[
               "OCA\\Settings\\Controller\\AppSettingsController",
               "enableApps",
               {
                  "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
               },
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "function":"__invoke",
            "class":"OC\\AppFramework\\Routing\\RouteActionHandler",
            "type":"->",
            "args":[
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Route/Router.php",
            "line":297,
            "function":"call_user_func",
            "args":[
               {
                  "__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"
               },
               {
                  "_route":"settings.AppSettings.enableApps"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/base.php",
            "line":1011,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->",
            "args":[
               "/settings/apps/enable"
            ]
         },
         {
            "file":"/var/www/nextcloud/index.php",
            "line":37,
            "function":"handleRequest",
            "class":"OC",
            "type":"::",
            "args":[
               
            ]
         }
      ],
      "File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php",
      "Line":119,
      "CustomMessage":"--"
   },
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
   "version":"19.0.4.2"
}
</details>

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/772#issuecomment-384211357

**Comment by celonix** [comment]
@nickvergessen Doesn't worked ;)

**Comment by nickvergessen** [comment]
Well this is where records are kept that talk was installed. 🤷‍♂️

Feel free to ask for further help in the forum.
