### ISSUE TITLE
Missing required prop: "icon" for ActionText

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2484]
## Steps to reproduce
1. Have a conversation in your list
2. Open the `…` menu on it in the navigation

### Expected behaviour
No error in console

### Actual behaviour
```
[Vue warn]: Missing required prop: "icon"

found in

---> <ActionText> at src/components/ActionText/ActionText.vue
       <Actions> at src/components/Actions/Actions.vue
         <RouterLink>
           <AppContentListItem> at src/components/Navigation/ConversationsList/AppContentListItem/AppContentListItem.vue
             <Conversation> at src/components/Navigation/ConversationsList/Conversation.vue
```

The problem is
https://github.com/nextcloud/spreed/blob/d40a337e8183ed11d41561b03232d01c322a4d6b/src/components/Navigation/ConversationsList/Conversation.vue#L54-L55

It does (and should) not have an icon, because it is the caption. I guess we should either add a ActionCaption, or we need to ask for the text component to be allowed without an icon.

cc @ma12-co @skjnldsv

**Comment by skjnldsv** [comment]
> we need to ask for the ActionText component to be allowed without an icon.
Agreed :)

**Comment by ma12-co** [comment]
Here : https://github.com/nextcloud/nextcloud-vue/pull/735

**Comment by nickvergessen** [comment]
Closing as per above
