### ISSUE TITLE
Dialog looks like a password was set

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2501]
## Steps to reproduce
1. create a new public room
2. go to the '...' menu on the right sidebar

![image](https://user-images.githubusercontent.com/1589737/69718403-924dad80-110e-11ea-9a04-911eb77fe9cd.png)

### Expected behaviour

A empty password field, maybe with a placeholder like "protect the room with a password"

### Actual behaviour
I see '*********' like in the screenshot above which looks like a password was already set

## Browser

**Browser name:** Firefox

**Browser version:** 70.0.1

## Server configuration

**Nextcloud Version:** 17.0.1 (c.nc.com)

**Comment by nickvergessen** [comment]
That's your browser doing nasty things.
I though we had a hack before.

**Comment by nickvergessen** [comment]
Any way, I will check this works in 18, we are not fixing this on 17

**Comment by nickvergessen** [comment]
Fixed in 18 as good as possible
