### ISSUE TITLE
cannot install talk

### ISSUE THREAD

**Issue by daniu-de** [nextcloud/spreed#2508]
## Steps to reproduce
1. trying to download talk in Nextcloud
2. get an error message "There is no table with name 'tableusername.oc_talk_participants' in the schema."

### Expected behaviour
install talk

### Actual behaviour

error message
## Browser
Firefox 68.2.0

**Microphone available:** yes/no
no

**Camera available:** yes/no
no

**Operating system:** Windows/Ubuntu/...
Win 10

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

```

</details>

## Talk app

**Talk app version: 7.0.2


## Server configuration
hosted server 


**Operating system**: no idea

**Web server:** Apache - I guess

**Database:** MySQL

**PHP version: 7.xx

**Nextcloud Version: 17.0.1

**List of activated apps:**

lots ...
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

sorry - don't have

**Comment by nickvergessen** [comment]
Please search for help in the forum: https://help.nextcloud.com/
