### ISSUE TITLE
Status API for SIP bridge

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2512]
SIP bridge needs to be able retrieve information on
- valid room IDs
- valid subscriber PINs per room ID
- activated lobby incl. meeting start time

**Comment by nickvergessen** [comment]
The External signaling server has all this information and needs to do this I think.

**Comment by wiswedel** [comment]
> The External signaling server has all this information and needs to do this I think.

@fancycode can you please provide some details for @nickvergessen on what you need?

**Comment by vroomr** [comment]
Is the External Signaling server only available in the paid version of Talk? I cannot find anything for the self hosted users.

**Comment by nickvergessen** [comment]
Yes, that IS the paid version.

**Comment by wiswedel** [comment]
Strictly, the SIP bridge is part of the Nextcloud Talk High Performance Back end, which is an extra external module to Nextcloud Talk, coming with costs - however that High Performance Back end is also self-hosted.
You can find out more about the capabilities at https://nextcloud.com/talk/.
