### ISSUE TITLE
After setting up a signaling server it's not possible to create a conversation anymore

### ISSUE THREAD

**Issue by himpierre** [nextcloud/spreed#2515]
## Steps to reproduce
1. Configure a signaling server (https://saltyrtc.org/pages/getting-started.html)
2. Try to create a new conversation
3. No conversation is created

### Expected behaviour
New conversation should be creqted.

### Actual behaviour
Nothing happens.

## Browser
Firefox 70

## Logs
`
{"reqId":"XeaMo6knC4qABm@IzkWYKgAAAAo","level":3,"time":"2019-12-03T16:26:11+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"user","app":"no app in context","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/room","message":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `POST https:\/\/signaling.domain.de:8765\/api\/v1\/room\/q74vfqi3` resulted in a `400 Bad Request` response:\nFailed to open a WebSocket connection: did not receive a valid HTTP request.\n\n","Code":400,"Trace":
`

Is there a list of supported signaling servers?

**Comment by nickvergessen** [comment]
> Is there a list of supported signaling servers?

Only the "High performance backend" from https://nextcloud.com/talk/ is currently supported.

**Comment by pierfu** [comment]
Hi,
do you plan to support other (free / opensource) external signaling server in near future, and if so when ?
Could you tell why this is restricted ?

**Comment by nickvergessen** [comment]
No plans. It mainly boils down to having the time to support them all and keep the code workign for all of them, so we decided to just allow/support that one for now.

**Comment by pierfu** [comment]
Tks, that's undserstandable.
However, i would recomend you explain that clearly on https://nextcloud.com/talk and mostly https://nextcloud-talk.readthedocs.io/en/latest/TURN/#what-else : i'm sure it would fill a missing answer to a frequent question for a lot of (enthousiastic) users. And explain too why the service is so expensive : most organizations cannot afford 40.000 €/year.

**Comment by Blackclaws** [comment]
Would work on this to support alternative signalling servers as a pull request be accepted or not?

**Comment by nickvergessen** [comment]
I don't think this is very suitable to answer in general. It would need constant maintenance, otherwise it is bound to break on every new feature we implement.
The question is also how tied the things would be coupled and therefor how much code would be needed to send as PRs. In theory this could all be done independently in another app i think. 🤔

**Comment by jospoortvliet** [comment]
> Would work on this to support alternative signalling servers as a pull request be accepted or not?

Are you aware of any open source signalling servers that could do what Talk does that we could support? A concrete feature request issue is welcome, as would be a pull request to add support - esp if that comes with a promise to help maintain it, of course.

**Comment by zundg** [comment]
https://github.com/nextcloud/spreed

> If you need to use Talk in a enterprise environment, including the ability to have calls with more than 5-6 users, you can contact our sales team for access to our high performance back-end. This is a set of components that replaces some of the PHP code with a more scalable and performant solution that decreases network traffic and allows dozens or hundreds of users in a call.

sounds like more than a few users is considered enterprise functionality and not intended for the community edition?

**Comment by jospoortvliet** [comment]
> sounds like more than a few users is considered enterprise functionality and not intended for the community edition?
Consider reading the issue and the comments before you add your own comments. let me do you the favor of giving you a summary: no, it is not our decision, it is a technical limitation of PHP and WebRTC. You can have a call with 100 people with Talk as it is, if you want - you just need a 32 core CPU with 10G ethernet on a local LAN **for each participant.** If you don't have that, you'll need a third party product. There is only one, at the moment, but anyone can write one if they want - just keep in mind it's a few years of work.

**Comment by acs-ferreira** [comment]
> 
> 
> > Is there a list of supported signaling servers?
> 
> Only the "High performance backend" from https://nextcloud.com/talk/ is currently supported.

Shouldn't this be added to the docs + the config page on Talk?
