### ISSUE TITLE
Avatars are displayed broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#252]
> ![video_calls_-_nextcloud_-_2017-03-07_12 48 43](https://cloud.githubusercontent.com/assets/213943/23655218/6e484836-0334-11e7-8708-93fe731da12f.png)

@Ivansss

**Comment by Ivansss** [comment]
@jancborchardt This commit https://github.com/nextcloud/server/commit/38f684aadfb10d491fabfeb0af9a22c109c9cfff makes avatars look broken.
Should we change something in core or fix it for this app only?

**Comment by nickvergessen** [comment]
It's basically because we abuse the navigation icons.
I'd overwrite the CSS rules in this app.
