### ISSUE TITLE
Not possible to copy share link for existing shared conversations

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2540]
Display copy link actionbutton under share link in the sidebar's actions

**Comment by nickvergessen** [comment]
This is about the menu in the right sidebar, or the creation dialog?

**Comment by ma12-co** [comment]
> This is about the menu in the right sidebar, or the creation dialog?

menu in the right sidebar!

**Comment by jancborchardt** [comment]
Yup, and this is quite important as it is currently impossible to copy the share link for existing shared conversations:
![copy link](https://user-images.githubusercontent.com/925062/71612152-02999400-2bd1-11ea-9fe2-28b69d18e97a.png)
