### ISSUE TITLE
Refine new_group_conversation feature

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2546]
Complete unchecked todos here #2499

---

- [x] Add docs :books:
- [x] Make it pretty :nail_care:
- [x] Selected Participant bg color: use the same as active appnavigationitem

Jan: 
- [x] Test with more people in the list – when there are more, it should cut off the last entry half, so people know there’s more. Also a fade from transparent to white behind the buttons, just like in the "Move or copy" dialog
- [x] search icon in searchbox;

The dialog should no only show an emptycontent view and force you to search, but:

- [x] Show the first ~50 contacts/groups/etc. in the list so people see immediate feedback that content exists and in the ideal case can directly choose the people to start a conversation with.
- [x] While it loads these initial contacts, show a loading spinner and text below saying "Loading contacts …" (compare to the Contacts menu in the top right)
- [x] On the bottom of this list of 50, show an emptycontent element saying "Search for more contacts" which on tap focuses the search field.

This should be the same cross-platform, on the web, Android and iOS.

**Comment by nickvergessen** [comment]
We need to show the "Type" of the search matches.
Especially with #2518  when you find circles, local groups and local users all matching, it's a mess as there is no indication of the source of each.

**Comment by jancborchardt** [comment]
Biggest confusion (as mentioned @ma12-co) but also needs some backend work from what I understand:

The "Add participants" step shows just an empty view and you need to know to search – it feels like a bug when you know there _are_ other users on your instance.

What I’d expect is being shown a list of users so I can already click and select people. Ideally this list would have some frequently contacted people listed first.

**Comment by ma12-co** [comment]
@jancborchardt  I spoke about this during the talk call and for now there's no way to display frequently contacted users.
What we can do now is submit a request with an empty string as search term, which would return 200 of your contacts in alphabetical order. This could mean all of your contacts if your instance is small or just the contacts starting with 'A' if your instance is very big. 
Also, when the user starts to search we wouldn't have a 'filtering' effect, instead, the list would disappear and a new list of matches for the current search term word would re-appear.

Taking all that into account, In my opinion, a good informative empty view here is the way to go for now as:
1) it doesn't slow the browser down with a request and hundreds of html elements that you probably don't need.
2) UX-wise it's more honest as it doesn't pretend to be a pre-loaded list with filtering (e.g. what's app / telegram)

**Comment by jancborchardt** [comment]
> What we can do now is submit a request with an empty string as search term, which would return 200 of your contacts in alphabetical order. This could mean all of your contacts if your instance is small or just the contacts starting with 'A' if your instance is very big.

This is by far the best solution.



> * it doesn't slow the browser down with a request and hundreds of html elements that you probably don't need.

This request can’t really be a problem, no? And if you have a small instance with friends, you actually don’t need anything else. Hell, even with our company it will be enough and you just need to scroll.


> * UX-wise it's more honest as it doesn't pretend to be a pre-loaded list with filtering (e.g. what's app / telegram)

The honesty doesn’t really have so much value here. It just looks like data is not there where people expect it to be. :\

**Comment by ma12-co** [comment]
I get your point, I'm mostly worried about very big instances. Anyway it's not a big deal. If you think it's necessary, let's go for it!

**Comment by jancborchardt** [comment]
Yes please. :) Also for very big instances it is good to get immediate feedback that there are actually other users on the instance.

**Comment by ma12-co** [comment]
Expected behaviour

The dialog should no only show an emptycontent view and force you to search, but:

    Show the first ~50 contacts/groups/etc. in the list so people see immediate feedback that content exists and in the ideal case can directly choose the people to start a conversation with.
    While it loads these initial contacts, show a loading spinner and text below saying "Loading contacts …" (compare to the Contacts menu in the top right)
    On the bottom of this list of 50, show an emptycontent element saying "Search for more contacts" which on tap focuses the search field.

This should be the same cross-platform, on the web, Android and iOS.

**Comment by mario** [comment]
Does it make more sense to have "Search for more participants" instead of "Search for more contacts"? Since contacts are only "people", while you can add groups, mails, etc as well.

**Comment by nickvergessen** [comment]
I don't think it matters too much, as also a group is a collection of "contacts"/"persons you know"

**Comment by nickvergessen** [comment]
But also see #2864 which might help with that
