### ISSUE TITLE
Guests should not see the favorite star in the sidebar

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2556]
Favoriting works only for logged in users

**Comment by nickvergessen** [comment]
Caused by:
https://github.com/nextcloud/spreed/blob/8fa88f2d91b2ddd6d97213653cbfb1b664099d67/src/components/RightSidebar/RightSidebar.vue#L27

It needs to be given null when it's not favorable. But I couldnt get this working with the used `.sync`.

Maybe @skjnldsv has an idea?

**Comment by skjnldsv** [comment]
you mean it still show if this is null?
Without the .sync it works?

**Comment by nickvergessen** [comment]
Well on our api the value is bool all the time, so for guests its false. And since we need the sync i can not create a wrapping fake computed?

**Comment by skjnldsv** [comment]
Yes, you can a simple :starred="xxxx"
and listen to the @update:starred event.
You can also use computed getter/setter
