### ISSUE TITLE
Hover creates a shadow/round circle that overlaps unread counter

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2564]
## Steps to reproduce
1. Install Spreed master
2. Take a look at the Changelog conversation and hover over the three dots
3. See that the hover effect overlaps the unread counter

### Expected behaviour
This should not happen.

**Comment by nickvergessen** [comment]
That is what the designers wanted.

Even if this is changed, it would need fixing in the nextcloud/nextcloud-vue repo

**Comment by mario** [comment]
Ok, this is not what the users want :-/
