### ISSUE TITLE
Title in sidebar is not properly aligned

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2565]
## Steps to reproduce
1. Install Spreed master
2. Click on "Talk updates room"
3. Notice that the title is not properly aligned in the sidebar

### Expected behaviour
It should be properly aligned.

<img width="488" alt="Screenshot 2019-12-14 at 09 54 42" src="https://user-images.githubusercontent.com/5810/70846255-dacbd180-1e57-11ea-9fb8-c0443e0b5720.png">

**Comment by nickvergessen** [comment]
Thats in the sidebar
