### ISSUE TITLE
Start call button overlaps the date "header"

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2566]
## Steps to reproduce
1. Install Spreed master
2. Create a conversation and write something
3. See that the "Start call" button overlaps the date header

### Expected behaviour
This should not happen.

<img width="642" alt="Screenshot 2019-12-14 at 09 56 38" src="https://user-images.githubusercontent.com/5810/70846283-0cdd3380-1e58-11ea-910c-d4eceeffd1a8.png">

**Comment by nickvergessen** [comment]
It was decided that the topbar is not a bar with background, so overlapping is okay

**Comment by mario** [comment]
Uh.
