### ISSUE TITLE
Three dots item in sidebar seems always selected

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2568]
## Steps to reproduce
1. Install Spreed master
2. Open a conversation
3. Take a look at the sidebar - three dots item seems to always be selected

### Expected behaviour
It shouldn't look selected if it's not!

**Comment by ma12-co** [comment]
This comes from the nextcloud-vue library. @skjnldsv is there a reason why that button looks always focused?

**Comment by skjnldsv** [comment]
Could you provide a screenshot @mario ? :)

**Comment by ma12-co** [comment]
![Peek 2019-12-19 11-04](https://user-images.githubusercontent.com/26852655/71164484-7772e280-224f-11ea-848f-ed357f0050a8.gif)

**Comment by skjnldsv** [comment]
Ah yes, this was on purpose, requested by Jan when creating the new sidebar :)

**Comment by ma12-co** [comment]
I agree with the need of having it highlighted, as it's a very important button, this should probably happen also for the new group conversation button as well

**Comment by skjnldsv** [comment]
Ask Jan ;)

**Comment by ma12-co** [comment]
@jancborchardt should we go for it? 

![Screenshot from 2019-12-19 11-08-39](https://user-images.githubusercontent.com/26852655/71164864-20b9d880-2250-11ea-8a22-0660735322de.png)

**Comment by jancborchardt** [comment]
@ma12-co sure, try with making the + button primary as per @jenniferpiperek’s mockup. :)
