### ISSUE TITLE
Favorite action hover is strange

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2569]
## Steps to reproduce
1. Install Spreed master
2. Select a conversation and open sidebar
3. See that the conversation is not favorited
4. Hover above the star - it gets colored
5. Click the star - it becomes grey!

### Expected behaviour
The star should be yellow since I've actually favorited the conversation, not grey.
Total confusion

**Comment by nickvergessen** [comment]
It is like that with every favorite icon.
So let's keep it for now.

cc @jancborchardt in case you want to change this globally

**Comment by jancborchardt** [comment]
I don’t fully understand the problem – the way it is on master seems fine, and is in line with how it is in Files and Mail for example?
