### ISSUE TITLE
One-to-one conversation shouldn't offer "Talk to XYZ" when clicking on the avatar

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2571]
## Steps to reproduce
1. Install Spreed master
2. Open a conversation with Mario
3. Click on "Mario" avatar and see that you're given an option to "Talk to Mario" which esentially opens the same conversation you're already in

### Expected behaviour
This option should not exist in one-to-one conversations. If anything, clicking on the avatar in one-to-one conversations should trigger adding "@mario " to the new message field, but even that's up to discussion.

**Comment by nickvergessen** [comment]
Its going to be tough, as the stuff is returned from server api

**Comment by jancborchardt** [comment]
> If anything, clicking on the avatar in one-to-one conversations should trigger adding "@mario " to the new message field, but even that's up to discussion.

That would indeed be pretty neat! Keeps the menu consistent and also shows people how to @-mention.

**Comment by nickvergessen** [comment]
Closing in favor of #1803
