### ISSUE TITLE
Talk icon is cut off in on-avatar-click three dots menu

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2572]
## Steps to reproduce
1. Install Spreed master
2. Open a conversation with "mario"
3. Click on the avatar and three dots menu
4. See that the logo is cut off.

### Expected behaviour
This could be a font alignment issue, logo size issue or something else - I don't know, didn't do the measurements. But the expected behaviour is simply - logo should not be cut off.

<img width="176" alt="Screenshot 2019-12-14 at 22 40 40" src="https://user-images.githubusercontent.com/5810/70854916-c83ab200-1ec2-11ea-9de9-06f68db47c65.png">

**Comment by nickvergessen** [comment]
That's weird, maybe it is making all icon round, instead of avatars only?

**Comment by nickvergessen** [comment]
Server CSS problem, fix is in https://github.com/nextcloud/server/pull/18504
