### ISSUE TITLE
Wrong icon for groups in the "Select participants" dialog

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2573]
## Steps to reproduce
1. Install spreed master
2. Try creating a conversation 
3. Look for "admin" and notice it has an "A" rather than a Group icon

### Expected behaviour
It should have a group icon.

<img width="300" alt="Screenshot 2019-12-14 at 22 42 40" src="https://user-images.githubusercontent.com/5810/70854942-29fb1c00-1ec3-11ea-82f8-eb0f96d47cc4.png">

**Comment by nickvergessen** [comment]
That was mentioned in #2546 already
