### ISSUE TITLE
"No search results" is missing padding

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2574]
## Steps to reproduce
1. Install Spreed master
2. Search for "admin"
3. See that "No search results" misses padding

### Expected behaviour
All entries, even "No search results" should have padding.

<img width="301" alt="Screenshot 2019-12-14 at 22 44 14" src="https://user-images.githubusercontent.com/5810/70854961-6c245d80-1ec3-11ea-86aa-e68b796cef46.png">

**Comment by wiswedel** [comment]
same goes for "loading"

![image](https://user-images.githubusercontent.com/1804221/71822921-666f0180-3096-11ea-8ceb-847e2433efac.png)
