### ISSUE TITLE
Avatar menu on a participant in sidebar menu is broken

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2575]
## Steps to reproduce 
1. Install Spreed master
2. Create a conversation
3. Open sidebar and click on a three dot menu of another participant
4. See that the menu is broken

### Expected behaviour
The menu should not be broken.

Browser: Latest Firefox on MacOS

<img width="487" alt="Screenshot 2019-12-14 at 22 48 15" src="https://user-images.githubusercontent.com/5810/70855008-f8368500-1ec3-11ea-9338-244734381b35.png">

**Comment by mario** [comment]
Better screenshot:

<img width="613" alt="Screenshot 2019-12-14 at 22 49 42" src="https://user-images.githubusercontent.com/5810/70855013-0b495500-1ec4-11ea-8c98-750cd7947261.png">

**Comment by nickvergessen** [comment]
You mean the avatar menu, I think that hints to nextcloud-vue.
Maybe we can fix the z-index with `v-deep` temporarily, until a lib update fixes it? @ma12-co

**Comment by ma12-co** [comment]
I disabled both menu and tooltip here. If we want the ability to open a new conversation from there, we should implement it from the actions

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2019-12-20 11-58-58](https://user-images.githubusercontent.com/213943/71250532-2ed72a00-2320-11ea-9b1f-3e789c510e5d.png)

Also in issue in the chat view + avatars of follow up chat messages or shown on top of the popover :-1:

**Comment by materthewelon** [comment]
Does anyone know when this issue will be fixed?

**Comment by jospoortvliet** [comment]
![Screenshot_20200327_133427](https://user-images.githubusercontent.com/551757/77756588-c5a63780-702f-11ea-959e-c502200661f7.png)
Another screenshot of this during a call we're just having on cloud.nc.c ;-)
