### ISSUE TITLE
Users are shown as guests in a call from the guest UI

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#2590]
## Steps to reproduce
1. Start a call with a user
2. Join the call with a user
3. Join the call with a guest

### Expected behaviour
The avatar shown for the user is the right avatar in all cases.

### Actual behaviour
In the guest browser, the avatar shown for the users is the avatar of a guest (white letter on a grey background). However, in the user browsers, the avatar shown for the other user is the right avatar.

**Comment by nickvergessen** [comment]
Arg...

This is done by:
https://github.com/nextcloud/spreed/blob/714ac2a1c6fdde036be4b6bf8d7d4c25ed2622ee/src/components/CallView/CallView.vue#L395-L398

Guest's shouldn't use an avatar with the avatar component but instead use custom div+css as in all other places: https://github.com/nextcloud/spreed/pull/2618/files
