### ISSUE TITLE
Switching to another conversation is sluggish

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2591]
## Steps to reproduce
1. Click on any conversation

### Expected behaviour
A UI and route change is triggered immediately, regardless of the requests that are being made under the hood.

### Actual behaviour
There's a pretty significant lag between the click and anything happening

**Comment by nickvergessen** [comment]
Regression due to the signaling code that had to be copied because we ran out of time, instead of refactoring it to allow async everywhere.
Actually signaling should only be done when you join a call.

**Comment by nickvergessen** [comment]
Should be better now. If you feel this is still an issue, please be more specific which part feels sluggish

**Comment by ma12-co** [comment]
I think it's still not ideal. When clicking on a different conversation, ideally the current conversation should immediately lose the active state, the clicked one should acquire it, and the loading empty view in the chatview should also be triggered immediately on click. 
We lost the "immediate reactivity" of the UI when we introduced signaling.
