### ISSUE TITLE
Continuous long text in chat messages widens the chat view

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#2594]
## Steps to reproduce
1. Open a conversation
2. Focus the chat input
3. Hold the _a_ key for a while so the message to be sent becomes _aaaaaaaaaaaaaaaaaaaaaaaaa..._ (keep going until it is longer than the input width)

### Expected behaviour
When the _aaaaa..._ reaches the right end of the input it is wrapped and continues in a new line. If the message is sent the message is wrapped too in the list of messages.

### Actual behaviour
When the _aaaaa..._ reaches the right end of the input the chat view is widened more and more. If the message is sent the message is not wrapped either in the list of messages and the chat view is widened too.

**Comment by nickvergessen** [comment]
Not happening anymore
