### ISSUE TITLE
Avatar sizes are off for groups and link shares

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2645]
Compare the sizes of the avatars for people vs groups/links/documents:
![avatar size](https://user-images.githubusercontent.com/925062/71559749-99ad0180-2a94-11ea-9e98-ea4f4102f9da.png)

The latter are bigger, leading to being to close to the text on the right. cc @ma12-co @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
PR in #2673

**Comment by jancborchardt** [comment]
Fixed via the pull request at https://github.com/nextcloud/spreed/pull/2673, thanks @skjnldsv!
