### ISSUE TITLE
Alignment of "Chat notifications" heading in actions menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2646]
Currently the "Chat notifications" heading in the actions menu of the navigation is not really aligned anywhere:
![chat notifications menu](https://user-images.githubusercontent.com/925062/71559803-0922f100-2a95-11ea-9119-6f4fe985c18a.png)

It should move slightly to the right to be aligned with the other text. :)

**Comment by nickvergessen** [comment]
I think it helps to note that this is something different, not just an option were the image is not loading

**Comment by nickvergessen** [comment]
This is using `ActionText` in the meantime, so if it is still an issue it needs fixing there
