### ISSUE TITLE
After creating a new group conversation, "New message …" field should focus

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2648]
If you create a new conversation, it seems the sidebar is focused. This leads to a weird glow effect like this:
![focus bydefault sidebar](https://user-images.githubusercontent.com/925062/71559952-771be800-2a96-11ea-9dae-9c7680a7818a.png)

Besides that being strange, focusing the "New message …" field just makes more sense as we also do when switching conversations.

**Comment by nickvergessen** [comment]
Already works here
