### ISSUE TITLE
Empty view after starting call, missing feedback

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2650]
When pressing the "Join call" button, you are faced with a black screen and don’t know what the current state is:
![missing emptycontent on started call](https://user-images.githubusercontent.com/925062/71569722-a9affa00-2b03-11ea-9cd3-7ea63b7433e9.png)

Instead there should be a proper empty content view like before which helps you with the next steps:
![emptycontent](https://user-images.githubusercontent.com/925062/71569783-14f9cc00-2b04-11ea-8377-f978f7c118d4.png)

@ma12-co @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
I would put the empty content message on the black screen.
I think it helps users to have only 2 screens instead of tons of different mixed levels, currently you have white screen when you are in a call. But when you start a screenshare while being alone it turns black, etc.

**Comment by jancborchardt** [comment]
Yes, absolutely, putting it on the black screen is good. :+1:  The color of the screen wasn’t the concern, but the missing info. :)

(And indeed it’s better to have the black background to communicate that the call is active – that way we have 2 distinct states.)
