### ISSUE TITLE
"New message" box alignment in sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2651]
Previously, the "New message" box in the sidebar was sticky to the bottom, now it’s floating in mid-air for a new call:
![sidebar long names and new message input position](https://user-images.githubusercontent.com/925062/71569849-6dc96480-2b04-11ea-8ffa-aa70f1d662bc.png)

It should be sticky to the bottom again like before. :)

@nextcloud/designers-talk

**Comment by nickvergessen** [comment]
There was a discussion if we need to replace the infinite scrolling lib again, so it was not a focus point

**Comment by jancborchardt** [comment]
Ah ok – seems separate from that input field though, as it could just be positioned on the bottom regardless of the content of the list? But I’ll let @ma12-co handle that. :)

**Comment by nickvergessen** [comment]
Fixed already
