### ISSUE TITLE
Loading feedback for conversation list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2655]
## Steps to reproduce
1. Open the Talk app
2. See that there’s no conversations in the navigation
3. Be shocked that your data seems lost, only to have it appear a second later

### Expected behaviour
Just a simple loading spinner in the navigation, no text needed. Just like we had in the previous version.

### Actual behaviour
Nothing

cc @nextcloud/designers-talk, very related to **Loading feedback when opening conversation #1211** – loading feedback is very important, as it otherwise makes the app seem unstable. It’s also a regression since we had that in the previous version.

**Comment by nickvergessen** [comment]
Fixed by #2761
