### ISSUE TITLE
Bolding for unread messages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2657]
Currently the only way to identify unread messages is the little counter in the list. That’s not very distinguished and can be overlooked.
![vertical issues](https://user-images.githubusercontent.com/925062/71612518-85bbe980-2bd3-11ea-9d9e-42a1a10bdcfa.png)

As other messengers are doing as well (and email apps too, including Nextcloud Mail), conversations with unread messages should be displayed with bold text in the navigation.

This is a regression in some ways because the previous counter was more obvious. cc @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
Also before the unread counter was in a grey circle

**Comment by tobiasKaminsky** [comment]
Sometimes I get a blue circle (or to be precise an ellipse), but not on every chat…

**Comment by nickvergessen** [comment]
blue is when you got mentioned

**Comment by jancborchardt** [comment]
I’d reopen it again since yes, we have a bubble, but it should still be bolded so you can very quickly see which entries have unread messages. No?

**Comment by nickvergessen** [comment]
So a bold conversation name? Or what is going to be bold?

**Comment by Ivansss** [comment]
> I’d reopen it again since yes, we have a bubble, but it should still be bolded so you can very quickly see which entries have unread messages. No?

Should both the title (name) of the conversation and the subtitle (last message) be bolded?
Or just the subtitle?

**Comment by jancborchardt** [comment]
> Should both the title (name) of the conversation and the subtitle (last message) be bolded?

Both title and subtitle, as well as the unread counter – essentially all text of the entry. :) (Same as in Nextcloud Mail.)
