### ISSUE TITLE
Conversations cannot be renamed anymore

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2670]
Since the Vue redo, conversations cannot be renamed anymore.
The rename pencil is missing in the right sidebar.

Here's a screenshot with the expected behavior from 7.0.2

![image](https://user-images.githubusercontent.com/1804221/71813578-47fb0d00-307a-11ea-9371-2edee394076a.png)

**Comment by nickvergessen** [comment]
Fixed in #2757
