### ISSUE TITLE
copy link button gone for public conversations

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2671]
Unless this was intended with the Vue redo (which I'd see as a UX regression), the copy link button for public conversations isn't appearing anymore.

Here's a screenshot from 7.0.2 where it's still there:

![image](https://user-images.githubusercontent.com/1804221/71813729-b770fc80-307a-11ea-92d2-d88b04f66892.png)

**Comment by nickvergessen** [comment]
Duplicate of #2540
