### ISSUE TITLE
Chat messages hand after sending one 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#2678]
## Steps to reproduce
1. have nc18 with latest Talk
2. write a text, press enter
3. no new chat messages appear, but you see them in side bar
4. This does not happen if you go into a chat and "watch" it without sending a message

### Expected behaviour
New chat messages should appear

### Actual behaviour
Nothing

**Comment by wiswedel** [comment]
> Chat messages hand

You mean _hang_, don't you?

By the way: scrolling up and down once loads them (workaround for the time being)

**Comment by nickvergessen** [comment]
#2636
