### ISSUE TITLE
Not possible to open other conversation in separate tab

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2687]
## Steps to reproduce
1. Be in a call
2. Want to catch up on another conversation
3. Try to find a way to open that other conversation without leaving the call

### Expected behaviour
Right-click → Open in new tab could work on the conversation list. Or Ctrl-Click as well.

### Actual behaviour
It’s not possible to open other conversations in separate tabs without manually opening a new tab with Nextcloud.

cc @nextcloud/vuejs as this might be a general issue with the AppNavigation component, as it should be possible in general to open things in a new tab. (It was possible in the old version of Talk and is also possible in other Nextcloud apps.)

**Comment by skjnldsv** [comment]
ah, duplicate of #2684

**Comment by ChristophWurst** [comment]
> cc @nextcloud/vuejs as this might be a general issue with the AppNavigation component

Nope, works fine in Mail :)

**Comment by skjnldsv** [comment]
Talk uses its own custom navigation item

**Comment by jancborchardt** [comment]
> ah, duplicate of #2684

Thanks! Sorry, I rely on the "related issues" feature of Github and that one wasn’t listed when opening this here. :) Closing this as duplicate then

**Comment by skjnldsv** [comment]
> Thanks! Sorry

No worries :)
It's hard to find duplicates in such specific use cases!
