### ISSUE TITLE
Reply action doesn’t focus the reply input field

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2697]
## Steps to reproduce
1. Click the reply button to reply to a message
2. Start typing
3. Notice nothing happens

### Expected behaviour
The message input field should be focused on clicking the reply button so you can directly start replying.

### Actual behaviour
Focus is lost and you need to manually click into the input field.

cc @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
Duplicate #2672
