### ISSUE TITLE
Show last message's actor

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#2700]
At the moment we don't see the last message's actor display name in the left side bar (Web UI).
In mobile clients we show it in different styles.
I think we should come up with a common style for all platforms.

**1-to-1 conversations:**

If the message is from the other participant, just show the message:
<img width="421" alt="Screenshot 2020-01-09 at 10 34 42" src="https://user-images.githubusercontent.com/4638605/72056047-25603280-32cc-11ea-99ec-2f9fff2cab48.png">

If the message is from you, show "You:" + last message:
<img width="421" alt="Screenshot 2020-01-09 at 10 40 02" src="https://user-images.githubusercontent.com/4638605/72056189-69ebce00-32cc-11ea-8146-e03368726f49.png">

**Group conversations:**

If the message is from other participant, show just the first name + last message: **[OPTION A]**
<img width="420" alt="Screenshot 2020-01-09 at 10 35 04" src="https://user-images.githubusercontent.com/4638605/72056303-a8818880-32cc-11ea-8ea6-8dd095bd3c22.png">

Or show the complete name and the message in different rows: **[OPTION B]**
<img width="420" alt="Screenshot 2020-01-09 at 10 45 45" src="https://user-images.githubusercontent.com/4638605/72056644-483f1680-32cd-11ea-8c51-59a49b353ee8.png">

If the message is from you, show "You:" + last message: **[OPTION A]**
<img width="418" alt="Screenshot 2020-01-09 at 10 54 52" src="https://user-images.githubusercontent.com/4638605/72057325-812bbb00-32ce-11ea-8151-0394dd3b226f.png">

Or show "You" and the message in different rows: **[OPTION B]**
<img width="423" alt="Screenshot 2020-01-09 at 10 50 02" src="https://user-images.githubusercontent.com/4638605/72056947-d9ae8880-32cd-11ea-849a-9c0dd7a17d42.png">

These are just some ideas we discussed yesterday. @nickvergessen 
Any other ideas @nextcloud/designers-talk?
@mario @ma12-co @danxuliu

**Comment by nickvergessen** [comment]
I think using the first name is quite some magic, might work for most languages thou.
But I'm strongly against the 3 lines layout....

**Comment by mario** [comment]
I'd opt against the first name as it indeed won't work everywhere. And apart from the three line layout, this is how the Android app works for one-to-one and group/public conversations pretty much (it uses full name though).

**Comment by nickvergessen** [comment]
The android app also shows the name of the other user for one-to-one conversations.
So currently it shows:
```
Ivan Sein
Ivan Sein: Hi there
```
Which is quite repetitive

**Comment by mario** [comment]
That's fixed in master.

**Comment by nickvergessen** [comment]
The problem with the full name is that "Daniel Calvino Sanchez" almost takes up all the space in the web already. We would only ever see 2-3 chars of the message

**Comment by mario** [comment]
Well, we could elippsize end after 10 chars or so?

**Comment by ma12-co** [comment]
I vote for full name, ellipsized name + ellipsized message would look quite weird
e.g.
nickvergessen: Schmet...
as opposed to  
nickverg...: Schmetterlin...


@nextcloud/designers-talk

**Comment by ma12-co** [comment]
BTW this might be a good opportunity to increase the left sidebar width by 50px and maybe take them back from the right sidebar which is huge for what we need in talk!
doing that would bring it to 350px, which still fits most small mobile screen widths.

**Comment by nickvergessen** [comment]
> maybe take them back from the right sidebar which is huge for what we need in talk!

Just remember that when you are in a call, the chat is in the right sidebar

**Comment by jancborchardt** [comment]
While I’d also prefer option A, maybe it’s best to start with option B (3 rows) because we can’t determine what the first name is.

---------

Now this here is a completely separate thing, but to move from option B to A what we could do is what we also consider for Contacts, that is moving from a combined "Name" field for the User management to a "First name" and "Last name" field, cc @skjnldsv. See Contacts issue: https://github.com/nextcloud/contacts/issues/1376#issuecomment-569604269

**Comment by nickvergessen** [comment]
Well user management != contacts

I really think the 3rd row is taking away way too much space

**Comment by ma12-co** [comment]
final decision after discussion: `Display name until first space`: `message`
