### ISSUE TITLE
Bubble for @-mentions is grey with white text

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2728]
## Steps to reproduce
1. Have some conversations with new messages
2. Try to look for the blue notification bubble to focus on the ones where you were mentioned

### Expected behaviour
The bubble for conversations where you are mentioned is blue with white text.

### Actual behaviour
The bubble for conversations where you are mentioned is the same grey, but with white text:
![at mention bubble is grey](https://user-images.githubusercontent.com/925062/72253793-ea942c80-3634-11ea-92af-09c15e538c4a.png)

Latest Talk on c.nc

cc @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
is grey your primary color?
And do you think a designer can fix this, or why you mentioned them?

**Comment by jancborchardt** [comment]
Sorry no this is Vue. :)  And no, I use the default primary color.
