### ISSUE TITLE
Firefox MediaStreamError/NotAllowedError accessing from same LAN behind reverse proxy

### ISSUE THREAD

**Issue by jdsmall25** [nextcloud/spreed#2735]
I have a Nextcloud instance running via docker on my NAS via port 80.  I have a nginx reverse proxy that is running via docker on a separate host.  The reverse proxy is handling https via let's encrypt and has a valid certificate.  I access the server via the domain name and have hairpin enabled on my router.  Everything works fine outside my network and everything works fine when I'm on my local LAN except for calls via spreed.  I know Firefox requires https for microphone/camera access however I am accessing it via https.  Other browsers work fine, chromium and brave both work.  I've manually enabled microphone and camera access via page properties and it still doesn't work.  My best guess is that Firefox still thinks its accessed via http and autoblocking media access even though I'm routed through the proxy.  This seems like a Firefox issue specifically but figured I'd open a bug just in case.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/59858074/72313318-eabb1900-3682-11ea-887b-7cc647705552.png">

## Steps to reproduce
1. Setup nextcloud via port 80
2. Setup nginx reverse proxy to rewrite to nextcloud on port 80.
3. Start a call in Talk

### Expected behaviour
I should be prompted to grant access to my microphone and camera

### Actual behaviour
Firefox immediately blocks access to microphone and camera without prompting

## Browser
Firefox 71.0 

**Microphone available:** yes

**Camera available:** yes

**Operating system:** KDE Neon 18.04

**Browser name:** Firefox

**Browser version:** 71.0

### Browser log

<details>
Access to microphone & camera failed 
MediaStreamError { name: "NotAllowedError", message: "The request is not allowed by the user agent or the platform in the current context.", constraint: "", stack: "" }

</details>

## Talk app

**Talk app version:** 7.0.2

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu Server 18.04

**Web server:** Nginx

**Database:** Maria

**PHP version:** 

**Nextcloud Version:** 17.0.2

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Since the error message is directly from the browser, there is nothing we can do about it. Can you make sure no other program or browser is using your media?

**Comment by jdsmall25** [comment]
I an confirm that nothing else is using my mic or camera.  Unsure if anyone else can cofirm the behavior. It's possible it has something to do with my Firefox configuration but unsure what.

**Comment by nickvergessen** [comment]
Try starting firefox in save mode so without all add-ons

**Comment by jdsmall25** [comment]
Thanks for the suggestion but sadly no joy.  Still immediately blocks access to mic and camera without prompting.  Even the manual overrides are not working.

**Comment by nickvergessen** [comment]
Well try checking your browsers console for any hints.

You can also try Firefox fake streams:
* Go to `about:config`
* Search for "fake"
* Enable `media.navigator.streams.fake`
* Make sure to revert after testing

If that works, something is using your camera/audio already.

**Comment by j-tai** [comment]
I'm having this issue as well. Joining a call works fine in Chromium, but I get the following error in Firefox:

> Access to microphone &amp;amp; camera is only possible with HTTPS: Please move your setup to HTTPS

I am using HTTPS with a valid Let's Encrypt certificate.

I doubt this is a bug with Firefox, as [this WebRTC demo](https://webrtc.github.io/samples/src/content/devices/input-output/) works fine.

I found the following browser logs which may be relevant:

```
talk.js:147:8501: Access to microphone & camera failed DOMException: "Operation is not supported"
talk.js:707:4408: The request has been canceled Object { message: undefined }
talk.js:993:32472: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
```

Nothing else in the browser is using my camera or microphone. Setting `media.navigator.streams.fake` to true does not make a difference; the same error occurs.
