### ISSUE TITLE
Calls are not left when clicking on a different conversation

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2741]
## Steps to reproduce
1. Start a call with someone
2. Click on another conversation
3. Click on the previous conversation

### Expected behaviour:
On 2. the user should leace the call and on 3. The chatview should loaded 

### Actual behaviour:
The user never leaves the call so on 3. the callview is still there

**Comment by nickvergessen** [comment]
It works fine here on latest master, did you have a waiting debugger maybe?
