### ISSUE TITLE
Html entities get double encoded in the message list/sidebar

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#2750]
## Steps to reproduce
1. Send the following message ">"

### Expected behaviour
The ">" symbol should show up properly

### Actual behaviour

![image](https://user-images.githubusercontent.com/3404133/72418676-93e53a80-377b-11ea-8708-d0301d85a798.png)

![image](https://user-images.githubusercontent.com/3404133/72418704-a3648380-377b-11ea-824f-fe90dd0eed2c.png)

**Comment by nickvergessen** [comment]
Regression from #2691

**Comment by GVodyanov** [comment]
![Screenshot from 2024-03-28 11-47-22](https://github.com/nextcloud/spreed/assets/76647797/145ac361-01f0-4e09-95f4-0d42f1f34dad)

Looks like this is happening again on c.nc

**Comment by nickvergessen** [comment]
Please don't reopen 3 year old tickets -.-
