### ISSUE TITLE
@-mention input cursor is misplaced

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2752]
## Steps to reproduce
1. Open the talk app;
2. Use the @ - mention feature and select somebody in the input field;

### Expected behaviour
The `userBubble` component appears and the blinking input cursor appears after it

### Actual behaviour
The `userBubble` component appears and the blinking input cursor appears before it

**Comment by ma12-co** [comment]
@danxuliu I've looked into this but I haven't been able to find out why this happens, do you have any suggestion?

**Comment by PVince81** [comment]
works for me in Chromium 85.0.4183.102 and Firefox 80.0, the cursor is always on the right:
![image](https://user-images.githubusercontent.com/277525/94932455-638c2a80-04c9-11eb-8a9a-40b3ceb863e5.png)

**however** it seems that backspacing or trying to move over the bubble in Firefox makes the cursor disappear. And it's not possible to delete the bubble. This is only happening in Firefox, Chromium is fine :-/

**Comment by nickvergessen** [comment]
Could also be that it as fixed as a side-effect at some point. Shall we close it?

**Comment by PVince81** [comment]
works for me on master / 11.0.0-alpha.3, both Firefox and Chromium

I also retested the backspacing and it also works in both browsers.

@ma12-co can you confirm so we can close ?

**Comment by nickvergessen** [comment]
I think this is fixed since we have the emoji picker
