### ISSUE TITLE
Open @-mention stays when navigating away

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2758]
## Steps to reproduce
1. Share a file to a group/user
2. Join conversation and start typing `@t`
3. Navigate to another file/item/sidebar tab

### Expected behaviour
Autocomplete should close

### Actual behaviour
Autocomplete is stuck on this position on your screen until a page reload happens

> ![Peek 2020-01-16 08-58](https://user-images.githubusercontent.com/213943/72504693-9a88b600-383e-11ea-955e-fa649c65b095.gif)

**Comment by nickvergessen** [comment]
cc @danxuliu if you can still have a look

**Comment by PVince81** [comment]
Still happening in 11.0.0-alpha.3

**Comment by PVince81** [comment]
seems the popover in that specific case is missing some handler to close when clicking outside.
doesn't matter where I click outside, it never closes.

seems to be a bug in the original library, see how in this demo it also doesn't close when clicking outside: https://fritx.github.io/vue-at/#/en/quickstart

so we'll likely need to write our own "click outside" handler in our "AdvancedInput" component for proper closing

**Comment by PVince81** [comment]
bug report still open: https://github.com/fritx/vue-at/issues/114
with a potential solution to implement on our side: https://github.com/fritx/vue-at/issues/114#issuecomment-565777450

**Comment by PVince81** [comment]
I had a quick local try with only the blur event and while closing works, now clicking on a mention in the dropdown closes it too early. I had to add a setTimeout() before closing of at least 500ms... That might explain why the proposed solution of the author also involves at timer :-/

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/4978 with a timeout handler
