### ISSUE TITLE
New group form: remove password checkmark

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2763]
And show directly the password input field whn the "public" check-mark is checked.

**Comment by ma12-co** [comment]
So I opened after talking about it with @mario, I was pretty convinced at the time but now looking at what we have I'm not sure we want this. The password checkmark de-clutters the UI from a second input field and also serves as a sort-of confirmation that you're setting the password. The input field only can feel a bit random, especially since we don't have any confirmation feedback at that stage. What do you think @nextcloud/designers-talk @nickvergessen ?

**Comment by nickvergessen** [comment]
Agreed, makes it much more clear
