### ISSUE TITLE
Show avatar placeholders for people who have no webcam, instead of showing videoContainer

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#277]
In the company call today you might also have seen the issue where the people who have no webcam on their device didn’t have an avatar (or placeholder) but instead a small black box on the bottom.
![many participants](https://cloud.githubusercontent.com/assets/925062/24658846/34c53a88-194b-11e7-848d-05d0303eca13.png)
See below the names of @nickvergessen @oparoz @icewind1991 @daita – can you also confirm that you not having a webcam is the issue, or was there anything else?

Inspecting this, it was the videoContainer. Maybe this resulted in reducing the call quality a bit and we should fix it anyway to show the avatars (or placeholders) for these people too.

**Comment by daita** [comment]
My webcam is not working on Linux, and I couldn't find a way to disable it under firefox without disabling the mic
