### ISSUE TITLE
Plugin does not work on fresh installation

### ISSUE THREAD

**Issue by physikerwelt** [nextcloud/spreed#2782]
## Steps to reproduce
1. Install a fresh nextcloud instanace via docker-compose
2. search for plugin spreed
3. Click download and enable

### Expected behaviour
Tell us what should happen
The plugin should appear

### Actual behaviour
Tell us what happens instead
The following error appears
```
Server error: `GET https://nextcloud.struktur.de/s/x81symJCy7MD6hh/download` resulted in a `503 Service Unavailable` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" > <head data-requesttoken=""> <meta cha (truncated...) 
```

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL

**PHP version:**

**Nextcloud Version:** Nextcloud 17.0.2

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by fancycode** [comment]
Please switch to the "Talk" app (which is this one).

**Comment by physikerwelt** [comment]
Thank you.
