### ISSUE TITLE
Android app Talk it does connect to the server, but after the user does not login

### ISSUE THREAD

**Issue by Klagio** [nextcloud/spreed#2787]
After I open my Android Talk app, after putting my nextcloud self hosted server name, click the arrow and does connect to it .
It asks user and password, I put it in but it does not login, the circle spins but nothing happens

Nextcloud works well

**Comment by nickvergessen** [comment]
Please create a new issue at https://github.com/nextcloud/talk-android/issues providing all the  necessary information
