### ISSUE TITLE
Prevent URL change mid-call for public rooms

### ISSUE THREAD

**Issue by oparoz** [nextcloud/spreed#279]
## Steps to reproduce

1. Join a public link
2. Wait until you get disconnected
3. Refresh

### Expected behaviour

The room should be reloaded

### Actual behaviour

There is an error message saying that the call doesn't exist.

After the organiser emailed me saying he couldn't see me anymore, I figure something was wrong and I noticed the address got reset to a URL which didn't contain the room ID anymore.

**Comment by nickvergessen** [comment]
I suspect this is the same issue as https://github.com/nextcloud/spreed/issues/283

Because other then that we only change URLs when you change your current room.

Can you confirm?

**Comment by oparoz** [comment]
I don't think it is, because there is not much which can be done from a public link, but maybe I did click on something or maybe the PC went into screensaver mode and that changed something?

**Comment by nickvergessen** [comment]
That all should not change the URL
