### ISSUE TITLE
remote controll screenshare

### ISSUE THREAD

**Issue by ruben-herold** [nextcloud/spreed#2795]
Hi,

it would be nice if you could hand over control to someone else in a screensharring session. 
So that you can use it like teamviewer and so on for support puprose.

**Comment by nickvergessen** [comment]
This sdoes not work technically because webrtc does not allow this.

**Comment by nickvergessen** [comment]
Well since it's electron app, it is not inside your browser so they can take over the mouse.

**Comment by schiessle** [comment]
Would be interesting to know if they use the webrtc protocol to take over the mouse or if they use another protocol for this in parallel.

**Comment by nickvergessen** [comment]
> Would be interesting to know if they use the webrtc protocol to take over the mouse or if they use another protocol for this in parallel. If we could do something similar, this would eliminate the last reason to use something else like Talk.

Your browser can not control your mouse (luckily).

Once we have a desktop client (see #1100 ) we can talk about this. Until then NO chance 🤷‍♀

**Comment by schiessle** [comment]
sure, a desktop client will be mandatory. But it is good to know that it will be possible with a desktop client. Until now my impression was that this feature was not only blocked by the browser but also by the webrtc protocol as such, which doesn't seems to be the case.

**Comment by Githopp192** [comment]
https://webrtc.ventures/2016/03/3-things-webrtc-cannot-do/

**Comment by neufeind** [comment]
This came up again in #14280. It requires a desktop-client. But since we have talk-desktop maybe that's realistic at some point in the future.

**Comment by fathix4** [comment]
i really hope we can have these features cuz we want to have our own real opensource collaboration that fills our needs also please make sure to make it work in all possible supported platforms
