### ISSUE TITLE
Add Ability to end a search-conversation operation

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2799]
## Steps to reproduce
1. Start searching a conversation in the left sidebar;
2. Decide that you don't need searching anymore;

### Expected behaviour
* You press `esc` and the search operation is aborted;
* There's a small x button in the search box that allows aborting the search operation;

### Actual behaviour
You have to manually clear the input field to revert the filtering of the conversations.

**Comment by nickvergessen** [comment]
Duplicate of #2551
