### ISSUE TITLE
Could not find resource file .../spreed/js/admin/sha1.js

### ISSUE THREAD

**Issue by j-ed** [nextcloud/spreed#2802]
## Expected behavior
An app package should contain all required files to prevent any problems or error messages.

## Current behavior
The following message is logged when using the talk app:
```
...,"app":"spreed","method":"GET","url":"\/index.phpadmin\/talk","message":"Could not find resource file \"\/apps2\/spreed\/js\/admin\/sha1.js\"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
```

I've checked the repository for the missing file but it seems not to exist or hasn't been created.

## Steps to reproduce
1. Open and use the talk app
2. Monitor the log file for any related messages.

#### Server Configuration
OS: Linux 4.9.207
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.0
**Talk app version: 8.0.0**

#### Client Configuration
Browser: Mozilla Firefox 72.0.1
Operating system: Windows 10

**Comment by nickvergessen** [comment]
The resource is neither shipped nor used anymore. But it seems like you are having talk in two directories: `apps/` and `apps2/`
Can you check that and make sure to delete the old one?

**Comment by j-ed** [comment]
I ran additional tests today and saw that all log message contained the "`version":"17.0.2.1"`" string, although I had already installed NC 18. With the latest app version I couldn't find the mentioned error message in the log anymore. (I also double-checked that only one copy of the app has been installed in the /apps2 directory.)
