### ISSUE TITLE
Selecting Circle on discussion creation does nothing on Talk8/NC18.

### ISSUE THREAD

**Issue by jcastang** [nextcloud/spreed#2807]
## Steps to reproduce
1. Create a circle (Private or public no matter)
2. Create a discussion and select circle 
3. Nothing happens (Users from circle are not in talk group, unable to talk to circle).

### Expected behaviour
Users from the circle should be added to discussion dynamically according to circle members.

### Actual behaviour
Nothing 
- circles is not in the discussion member list
- users are not added

## Browser

**Microphone available:** N/A

**Camera available:** N/A

**Operating system:** Ubuntu/Windows

**Browser name:** Firefox

**Browser version:** 72.0.1

## Talk app

**Talk app version:**  8.0.0

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

**Comment by nickvergessen** [comment]
Yeah, creating conversations with circles seems to not work yet.
But adding the circle afterwards should work fine.

**Comment by jcastang** [comment]
>  But adding the circle afterwards should work fine.

From my tests, adding circles afterwards do not work either.

**Comment by nickvergessen** [comment]
Note: it only works for local users in circles as there is no federation at the moment.
