### ISSUE TITLE
Spreed on Raspian?

### ISSUE THREAD

**Issue by AlexHowser** [nextcloud/spreed#281]
Is there any way to get it running on raspbian? I am running n11 on it, all I did so far was installing the plugin. HTTPS is set up. I tested the plugin on Chrome, I can set up rooms, but there is no camera throughput or audio throughput. Id be glad for any help availible here, since i was not able to find some sort of setup guide.
Alex

**Comment by nickvergessen** [comment]
Well the availability of mic/video is not depending on the server.
Also while calling the connection is between all the participants and not the pi, so should be fine.
