### ISSUE TITLE
Reply doesn't remove reply placeholder from input field

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#2810]
## Steps to reproduce
1. Click to reply on a message
2. Type a reply
3. Click enter
4. See message sent and in chat list, but also quoted message still left in the input field

### Expected behaviour
Quoted message should be cleared from the input field.

Firefox latest, stable 18, MacOS

**Comment by nickvergessen** [comment]
It does here, but I noticed yesterday that there seems to be a delay sometimes. Maybe it's just cleared once the message is received back, let me check that.
