### ISSUE TITLE
@mention + `tab` submit current message

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#2814]
## Steps to reproduce
1. Open chat
2. Type `@jan`
3. See Jan's handle pop up
4. Press <kbd>tab</kdb>

### Expected behaviour
My cursor continues after the inserted mention

### Actual behaviour
The current message is submitted.

## Browser

FF

**Comment by born2webdesign** [comment]
The behaviour is different for me: Hitting [space] with the handle pop-up visible simply aborts the substitution with the avatar and inserts the plaintext `@whoever` for me (as I would expect). (NC 17.0.2, Firefox 68)

**Comment by nickvergessen** [comment]
This is about Talk 8 were the UI was rebuild completely, so it should not apply on 17, yes.

**Comment by born2webdesign** [comment]
Thank you @nickvergessen , that clears that up.
I’m just wondering—is there a way I could have seen this from the bug report?

**Comment by ChristophWurst** [comment]
No. Sorry, I should have added that information.

**Comment by nickvergessen** [comment]
I can not reproduce this, neither locally nor on our instance. :thinking:

**Comment by nickvergessen** [comment]
So it's actually the tab key, not space.
There is currently no option to change that in vue-at documented.
But it's there, so PR incoming

**Comment by nickvergessen** [comment]
Couldn't find the docs location, so I created an issue for them: https://github.com/fritx/vue-at/issues/117
