### ISSUE TITLE
Hitting enter on a search should select the first entry

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2816]
Applicable to:
* Conversations filter/creating
* User list on conversation creation
* Participants filter/adding

Found myself trying that all the time when i populated my 19 dev environment today.

Cc @nextcloud/designers-talk 
Also works like that e.g. here on github.

**Comment by ma12-co** [comment]
Sounds good to me as long as we change the background of the first element to he same color as if it was hovered/focused :)

**Comment by nickvergessen** [comment]
Github does this on "Enter"

**Comment by ma12-co** [comment]
Yep, just saying that we should highlight the first entry, which is the one that would be "clicked/tapped" upon pressing enter. Did I get this right?
