### ISSUE TITLE
Ability to mute others

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#282]
Sometimes one of the ppl in the call is in a hugely noisy environment or has horrible echo and doesn't realize it or is super slow to respond to calls to turn it off. With more than 2 or 3 ppl in a call the ability to mute each other becomes quite important.

I suggest to just allow everyone to mute everyone else - the 1% of cases where this is unwanted seem rare enough to perhaps warrant an option somewhere but I'm not terribly worried about that.

**Comment by jospoortvliet** [comment]
Note, as per https://github.com/nextcloud/spreed/issues/285#issuecomment-296698587 - this mute is 'global', as in, it replaces a user muting him/herself.

If you would mute only for a single user, you don't really solve the problem of disruption (unless everybody mutes that person) and you introduce the problem that that user suddenly can't participate in the conversation anymore and has no way to solve that.

Of course, if you have one person being disruptive, you have an entirely different social problem but that should be fixed by a moderator mode with special rights. For a normal group of people, the ability for everyone to mute everyone works 99% of the time without issues.

**Comment by jospoortvliet** [comment]
Note that for a webinar, you'd want to have one or more moderators who have the ability to mute people. You could even simplify this: guests can be muted by anyone with an account, as usually those with an account aren't visitors but the presenter(s).

So if you we'd allow people with an account/logged in users to mute everyone and guests only themselves (like now), you cover 95% of the normal group call AND webinar use case. Right now logged in users can already kick out guests, right? Fits well, I think...

**Comment by nickvergessen** [comment]
We have moderators/owners, they can kick and they would also be able to mute then

**Comment by jospoortvliet** [comment]
@nickvergessen would do the trick, yes

**Comment by theDyingMountain** [comment]
@nickvergessen: is the kick and mute function for owners/moderators already imlemented? I found the following line in the [PR Announcement from January 2018](https://nextcloud.com/press/pr20180111/):
- Full control - the moderator can invite, mute and remove participants as needed.

**Comment by nickvergessen** [comment]
Kick is implemented, yes.
Mute is still unclear how it should happen on a technical level.
