### ISSUE TITLE
Support for Opera Browser (audio/video9

### ISSUE THREAD

**Issue by davidcheeeese** [nextcloud/spreed#2841]
Hello, 
Actually video and microphone not working on Opera browser (Version :66.0.3515.27) on a Linux system. There is a error message telling "Camera/Microphone" not accessible.

Will be great if we can use videoconference on this browser

Tested with a webcam test site succesfully, and Talk s working on Firefox

Many thanks for your work

**Comment by nickvergessen** [comment]
The thing is, the WebRTC library we use does not support Opera.
And given how complicated it is and seeing Opera having ~1% market share, I don't think this will change.
So I will close this and we can rediscuss once the lib has opera support (or well it will work out of the box on the next update then)
