### ISSUE TITLE
reconnects getting counted as participants

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2845]
Had a long call with 2 guests and several reconnects during that call.
After the call, the summary showed the follwing:

![image](https://user-images.githubusercontent.com/1804221/73071652-9f3f1100-3eb3-11ea-9cd5-af60543fde9c.png)

**Comment by nickvergessen** [comment]
Yeah we can't identify guests yet, so we don't know of that were individuals or the same all the time

**Comment by PVince81** [comment]
could try and reuse the PHP session to identify

**Comment by nickvergessen** [comment]
Yeah if guest attendees don't expire anymore that would be the way to go.

**Comment by nickvergessen** [comment]
Closed via #5137
