### ISSUE TITLE
Notify user when talking while being muted

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#285]
## Steps to reproduce
1. Manually disable your microphone
2. Speak while being in a call

### Expected behaviour
User should see a warning that they are muted

### Actual behaviour
People don't know that they are talking while being muted and no one can here them

**Comment by jospoortvliet** [comment]
Especially relevant if https://github.com/nextcloud/spreed/issues/282 is implemented - so you warn users that they got muted ;-)

**Comment by nickvergessen** [comment]
No, #282 should only mute the other person for yourself, until we have something like "moderators"

**Comment by jospoortvliet** [comment]
I think the problem we're trying to solve is:
* make sure a user who forgets to turn on mute isn't disrupting a call

We solve that with a global mute. A private mute might do the trick if many or most users mute that person, but then you introduce the problem that if that user talks, nobody else can hear him/her so you are creating a bigger problem than you are solving.

What is the downside of muting globally and warning users when they talk when muted that you solve by having a private mute function? I honestly see no benefit in a 'private mute' feature at all, pretty much ever... This isn't twitter.

**Comment by nickvergessen** [comment]
Well i dont say global mute is bad, but when I'm in a call and someone enters my office room I want to be able to mute my microphone...
Now when I start talking, I want some indication that I'm not heard...

**Comment by jospoortvliet** [comment]
I think we don't understand each other than, as OF COURSE users should be able to mute themselves. I just think everyone should also be able to mute others, that is all ;-)

**Comment by nickvergessen** [comment]
Yeah, i just don't unterstand way you comment here, yours is another open issue xP

**Comment by jospoortvliet** [comment]
True, I was commenting because the issue I linked would require this one to be implemented. A mute-somebody-else is a bad idea if the person who got muted won't be warned that he/she is muted next time they talk...

**Comment by jancborchardt** [comment]
(Just deleted some comments which were related to a different issue – #282 – and a bit confusing here. To make this starter issue clear to start with. :)

**Comment by jancborchardt** [comment]
Just for the record, this is how appear.in or Jitsi meet do it (don’t remember, took the screenshot some time ago). Just a simple tooltip on the speaker icon which is shown when there’s audio input when muted:
![screenshot from 2017-06-06 19-04-26](https://user-images.githubusercontent.com/925062/46365201-48874580-c678-11e8-8bcf-30a5b5d4f16e.png)
