### ISSUE TITLE
Talk flow is not sending notifications

### ISSUE THREAD

**Issue by Tealk** [nextcloud/spreed#2861]
Hello,

is it possible that Talk sends a notification as soon as a new message has arrived?

I have created a flow that writes a message to a specific chat on every new upload, now I want to see this without looking at the chat.
Notifications in the notification center are also displayed via the sync client, but unfortunately Talk does not send such a notification.

**Comment by nickvergessen** [comment]
Just go to the conversation where the messages are posted and change the notification level to "always notify"

**Comment by Tealk** [comment]
I did, but I'm still not getting any.

**Comment by Tealk** [comment]
@nickvergessen 
So here's what I set:
![image](https://user-images.githubusercontent.com/12276250/73336301-58fa0100-4269-11ea-84f1-2b2c2dec4293.png)
![image](https://user-images.githubusercontent.com/12276250/73336575-171d8a80-426a-11ea-8f06-ee58a844d83f.png)
![image](https://user-images.githubusercontent.com/12276250/73336478-d6257600-4269-11ea-9cf6-686d9f744af8.png)



If someone uploads something to a shared folder that is not an image, a chat message should appear and I should get a notification.
But this does not work.

- Is the flow only triggered if I upload something myself?
The notification that someone else has uploaded something came only when I uploaded something myself
- Why don't I get a notification even though I have set it up the way you have described it?

**Comment by nickvergessen** [comment]
So, there is a bug in the flow component which breaks the flow when the user is a guest:
https://github.com/nextcloud/server/pull/19186

But never the less notifications are not send, but at least a message is now posted into the chat.

**Comment by Tealk** [comment]
> So, there is a bug in the flow component which breaks the flow when the user is a guest:
> [nextcloud/server#19186](https://github.com/nextcloud/server/pull/19186)

But I do not work with guests or public releases. In my example only registered users use the system.

But even if a message is created in Talk, I do not get a notification? Is this on purpose or a bug after all?

**Comment by Tealk** [comment]
There is no possibility to assign uploads in certain folders to certain chats?

**Comment by nickvergessen** [comment]
Sure, apply a tag to the folder and add a check for that tag to the flow

**Comment by Tealk** [comment]
I thought for this query the file must have the tag?
Would you care to elaborate on that, please?

**Comment by Tealk** [comment]
Does the following problem belong to the above mentioned?
If I upload a file myself and receive a message, there is no notification.
![image](https://user-images.githubusercontent.com/12276250/73358135-e0f60000-4295-11ea-9822-e205316a502d.png)

**Comment by Tealk** [comment]
The folder works, but I don't understand why.
The selection means that the file must have the tag not the parent folder?
![image](https://user-images.githubusercontent.com/12276250/73358309-3cc08900-4296-11ea-88dd-b3a896310901.png)

**Comment by nickvergessen** [comment]
For tags it's the file or any parent, as otherwise tags would not work with shares

**Comment by Chartman123** [comment]
@nickvergessen Just a quick question: Does this work with groupfolders, too? In our case the Talk message is only generated when the file in a tagged folder is created by the user who created the flow action. We're using 19.0.2 with all apps up to the latest released version.

**Comment by nickvergessen** [comment]
cc @blizzz

**Comment by blizzz** [comment]
The File entity misses a check with group folders. Right now it validates whether the user is owner or has access to the file in question by share. The group folder case is missing there: https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/Entity/File.php#L136-L147

**Comment by Chartman123** [comment]
Thanks for making it clear. So we will have to wait for a fix as we're relying heavily on groupfolders. As a workaround, everyone who has access to that special folder could create his own flow action...
