### ISSUE TITLE
How to add custom js file in new 8 version?

### ISSUE THREAD

**Issue by AkashiHidaka** [nextcloud/spreed#2881]
**Is your feature request related to a problem? Please describe.**
I want to message the edit feature and print file copy/paste feature.

**Describe the solution you'd like**
When already sent message edit and other image file print and copy/paste/upload process to easy way.

**Describe alternatives you've considered**
Before 6 versions I made the features custom JS file type and it is worked. But the new 8 versions used VueJS way and I don't know where to insert the custom js files.

**Additional context**
![image](https://user-images.githubusercontent.com/44053447/73581455-429bb180-44c4-11ea-8d7f-9befe62d6273.png)
This is before old version worked.

**Comment by nickvergessen** [comment]
This is not supported at the moment. You can try to make an app for your modifications and just load your own js files with this app when the talk app is active.

But nevertheless all your features have been mentioned before and some are even being worked on for the next version.

**Comment by AkashiHidaka** [comment]
Hello
How to add the new js files in there?
In new 8 versions is very different than before 6 versions.
Before merged.json file added it, but now version all js file make to one talk.js file and it has complex architecture.
Can you teach it?
Thanks
