### ISSUE TITLE
Public Groupchannels, Guests should not see history.

### ISSUE THREAD

**Issue by schu-r** [nextcloud/spreed#2889]
When I make a Groupchannel and make an public URL, every guest can join the Channel. Thats a very handy function. I could use it on my Homepage to be contacted or similar things. 
But I dont want the Guest to see the whole History i discussed with others. 
I would like to have a Switch per Channel where you can set if the Guest sees the whole History or just the part, where he/she was Participating to the Channel. 
Similar to Whatsapp, so you dont get all the older News.

**Comment by nickvergessen** [comment]
Basically something like #1525 
So I'm closing as duplicate
