### ISSUE TITLE
Remove ability to attach file from "talk updates" conversation

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2890]
The paper-clip button should not be visible in the talk updates conversation

**Comment by ma12-co** [comment]
actually, the whole newmessageform should be hidden

**Comment by nickvergessen** [comment]
In 17 we showed the form but it was disabled. The flag to do this is the readOnly flag, not the room type thou

**Comment by AkashiHidaka** [comment]
Hello nickvergessen
What is the solution for this?
#2881
