### ISSUE TITLE
Autocomplete API issues/enhancements

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#2897]
`/core/autocomplete/get`

**Issues**:
- There are no real differences in the results when `itemId` is `'new'` or `{room-token}`
- When UserA (userId=userA) searches for its exact username `search=userA` the autocomplete API returns that user, but it doesn't return it when the name is not complete `search=user`

**Enhancements**:
- The API should be able to filter the participants that are already in one room when passing the room token as a parameter.
- Also there should be an option to filter yourself from the result.

**Comment by mario** [comment]
Isn't this a server issue rather than Spreed?

**Comment by nickvergessen** [comment]
No, we are interacting with an even there

**Comment by mario** [comment]
I have tried this once again and it seems to be working on 19?

**Comment by nickvergessen** [comment]
Yes
