### ISSUE TITLE
Spreed not init on development mode with php server

### ISSUE THREAD

**Issue by gsambrotta** [nextcloud/spreed#290]
## Steps to reproduce
1. run Nextcloud in development mode with php -S localhost:8080
2. go to video/chat app
3. app is stack on "allow your browser to use mic and cam"

### Expected behaviour
App should load properly and show rooms, show cam and let user interact with it.

### Actual behaviour
app crash and is not possible to use in any way.
Is still possible to use other nextcloud app, like file or calendar

## Browser
**Microphone available:** yes

**Camera available:** yes

**Operating system:** OS

**Browser name:** Firefox/Chrome

**Browser version:** 57.0/52.0.2

### Browser log

<details>
```
No error in javascript console
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Something in the log of your browser which helps knowning what the problem is?

**Comment by nickvergessen** [comment]
I think this was caused by the http2 problem.
If it is still happening after the release of Spreed 3.0/Nextcloud 13, please reopen
