### ISSUE TITLE
Don't fail silently when you're not allowed to re-share a file

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#2900]
## Steps to reproduce
1. User A creates a folder and shares it with B (re-sharing is disabled globally in the settings)
2. A and B talk together and B tries to add a file of the shared folder to the chat (with the Paperclip)

### Expected behaviour
Either the file should be added to the chat (but I see this may be problematic permission-wise), or it should at least result in an error-message and not failing silently.

### Actual behaviour
Nothing happens

## Browser
**Operating system:** Windows

**Browser name:** Chrome

**Browser version:** 79.0.3945.130 

### Browser log
![image](https://user-images.githubusercontent.com/1580193/74031441-c87e9780-49b1-11ea-95fe-c8c43d6c1a9a.png)

![image](https://user-images.githubusercontent.com/1580193/74031472-e3510c00-49b1-11ea-9535-8c0c352b1c74.png)

## Server configuration
Talk 8.0.1
NC 18.0.0

**Comment by nickvergessen** [comment]
Actually there should be a Toast:
https://github.com/nextcloud/spreed/blob/92aeb14f956ddc57ac45166165ce2f50632b3cf1/src/components/NewMessageForm/NewMessageForm.vue#L211

But seems that OCP.Toast is broken at the moment :thinking:
