### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/spreed#2919]
**Is your feature request related to a problem? Please describe.**
(New) users don't look often in cloud and haven't got the talk app installed. They don't get a notification of a conversation.

**Describe the solution you'd like**
Mail notification option (just, hourly, daily) for messages is needed.

**Describe alternatives you've considered**
Using mailinglists, but that doesn't suit our environment.

**Additional context**
We're a small ngo, just workin with volunteers. We connected CiviCrm with Nextcloud, so we can change group membership in civi and these are inherited in nextcloud. This works great*, but the (new) users don't have nextcloud/nextcloud talk installed on their smartphone, don't know how to do that, are not that technical people and don't look that often in the cloud via web. So they don't know if a conversation happened, which is critical. So it would be good to reveice mailing information about a new message, which can, of course, be disabled by the user.

* despite we don't have true group chats and have to readd the group of a chat over and over again to get the new groupmembers into it.

**Comment by nickvergessen** [comment]
> despite we don't have true group chats and have to readd the group of a chat over and over again to get the new groupmembers into it.

That will be fixed with #1329 

I'm not sure emails make a lot of sense for a chat app... None of the messengers out there has something like this.

**Comment by magreiner** [comment]
Mail notification would be also useful for us. There is already a feature to get a mail notification for "You were invited to a conversation or had a call" in the activity tab of the nextcloud settings (https://<nextcloud-instance>.com/settings/admin/activity).
Maybe it would be possible to add some more notification options here?

**Comment by lorddavidiii** [comment]
This would also be useful for us, as some of us have too old smartphones for the talk mobile apps
> I'm not sure emails make a lot of sense for a chat app... None of the messengers out there has something like this.

Team chat applications like slack or rocket chat, have also email notification at least for DM and mentions

**Comment by herrfinke** [comment]
I can confirm: email notifications would for mentions, direct messages would be very helpful for us as well.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/3076#issuecomment-597503721
