### ISSUE TITLE
Shortcuts still not working again completely

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2922]
https://github.com/nextcloud/spreed/pull/2779 claims to fix https://github.com/nextcloud/spreed/issues/2755, in fact it fixes only microphone and video.
The following are still missing:

f. Fullscreen (also ref https://github.com/nextcloud/spreed/issues/2921)
c. Chat
p. Participants list

**Comment by nickvergessen** [comment]
I'm not sure c and p are possible anymore unless it is implemented directly into the nextcloud-vue library.
Or is there a prgramatic way for an app to select the another tab @skjnldsv ?

**Comment by wiswedel** [comment]
Most important is fullscreen. Save your braincells if c and p are too tricky.

**Comment by nickvergessen** [comment]
So f is handled in #2921 and the rest we are ignoring for now and therefor closing

**Comment by wiswedel** [comment]
> So f is handled in #2921 and the rest we are ignoring for now and therefor closing

Great. Thanks
