### ISSUE TITLE
Chat in sidebar broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2933]
Tested with Talk 8.0.3 on Nextcloud 18.

Open the right sidebar ("Details" view) and go to the chat tab. 

Expected: see the chat for the file.

Result: The user only sees an empty tab.

![image](https://user-images.githubusercontent.com/1589737/74165132-f0c1fc80-4c24-11ea-9eba-7ec7ef77bbe7.png)

I couldn't test it until now because the whole chat in the sidebar is broken. But please also double check that the video calling functionality works in the sidebar when a document (office and/or markdown) is opened.

**Comment by nickvergessen** [comment]
It's a regression from the `@nextcloud/vue` upgrade to 1.3.x from #2886
