### ISSUE TITLE
Copied/Pasted multi-line message in chat insert <div> at end of each line 

### ISSUE THREAD

**Issue by jcastang** [nextcloud/spreed#2941]
## Steps to reproduce
1. Copy multiple line from Chat 
2. Paste them in conversation
3. End of line are replaced by `<div>` 

### Expected behaviour
Pasted text should reproduce end of line and do not insert `<div>` tag.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu

**Browser name:** Firefox/Chrome

**Browser version:** Latest

## Talk app

**Talk app version:** 8.0.0 -> 8.0.4

**Comment by nickvergessen** [comment]
So, I totally agree that it is annoying when posting text.
But stripping away all code is also bad, as it basically makes Talk useless for code related communication

**Comment by nickvergessen** [comment]
The problem is basically that Chrome (more than firefox) copies text strangely from websites and adds divs all around the place.
