### ISSUE TITLE
scrolling issue (participants list)

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2946]
Tested with Talk 8.0.3, in large rooms where you can scroll the participants list the user scroll through the "Add participants to the conversation" input field:

![image](https://user-images.githubusercontent.com/1589737/74441915-e136f380-4e70-11ea-87e3-d8249bd1ed74.png)

I would expect that the scroll are stops below the input field.

**Comment by PVince81** [comment]
another "position: sticky" nightmare...

it seems it's not possible to increase the padding as the element will move down and still have some space at the top

making it "position: absolute" doesn't make the scroll work correctly, unless we add some top margin to make up for it.

maybe need to switch to another way of doing scrolling there

**Comment by PVince81** [comment]
quickfix here: https://github.com/nextcloud/spreed/pull/4264

**Comment by PVince81** [comment]
PR was merged, closing
