### ISSUE TITLE
Persistent external text-chats

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/spreed#2958]
**Is your feature request related to a problem? Please describe.**
Our Nextcloud users need to Chat (Text not Video) with external participants on a regular basis. Setting up a public Talk room is great but some critical features are missing:
- Mobile Apps
- "Anonymously" Rejoining a conversation

**Describe the solution you'd like**
1) Provide a very simple mobile app that allows someone to join one or more discussions via an invitation token (qrcode?)
2) The app "remembers" the user until the room is deleted or a moderator removes a specific user from the conversation

**Describe alternatives you've considered**
- Integration with Whatsapp, RocketChat, Matrix, ....

**Comment by nickvergessen** [comment]
> Provide a very simple mobile app that allows someone to join one or more discussions via an invitation token

This is already possible with our android app.

**Comment by brtptrs** [comment]
Thanks for the quit reply. Maybe I'm missing something but the android app requires a login to a Server before I can select the option to join via a link.
That defeats the purpose, doesn't it?

**Comment by nickvergessen** [comment]
It should be handled with https://github.com/nextcloud/talk-android/issues/715

**Comment by brtptrs** [comment]
Great, I'll wait for  v9.1.0 then.
