### ISSUE TITLE
Add OpenPush support

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [nextcloud/spreed#2960]
Google's Firebase Cloud Messaging (FCM) should be removed in the same process.

**About OpenPush**

https://bubu1.eu/openpush/
https://fosdem.org/2020/schedule/event/dip_openpush/
https://f-droid.org/en/2020/02/03/openpush-talk.html

**Comment by nickvergessen** [comment]
This is dicsussed in https://github.com/nextcloud/talk-android/issues/257 already
