### ISSUE TITLE
Introduce types of participants

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#297]
In some environments, it would be nice to have different permission levels for participants:

1. Moderators (can change room type, invite people, set name, ...)
2. Invited members (can participate)
3. Guest user / members that followed a public link (should be dropped, if the type is switched back to group call)

@karlitschek @Ivansss makes sense?

**Comment by karlitschek** [comment]
Makes 100% sense

**Comment by jancborchardt** [comment]
Yup. Interface-wise, we can introduce an icon/control next to the username to promote people to Moderators.

**Comment by nickvergessen** [comment]
Reopening because promotion/demotion has no interface yet

**Comment by jancborchardt** [comment]
Regarding design, as mentioend in https://github.com/nextcloud/spreed/pull/353#issuecomment-313879177: 

> > When there is a call for participants I would suggest a dropdown on the name of the user, or a little triangle behind it.
>
> @nickvergessen Yup, exactly. :) Clicking on the username should open a popover menu. Just like we already do when screensharing to switch between screens, so we can extend that.
> Good question for how we do that before the call. Let's for now just have it in the call, and make sure to remember the roles of people even if they disconnect and reconnect later, or the call is days apart. Ok?

**Comment by nickvergessen** [comment]
Interface was merged with the sidebar from #28
