### ISSUE TITLE
8.0.4 breaks manual tagging support with 18.0.1

### ISSUE THREAD

**Issue by thomasgg23** [nextcloud/spreed#2989]
## Steps to reproduce
1. Install latest 8.0.4 talk app
2. Install latest Collaborative tags 1.0.8
3. Open details file/folder and click on the three dots for tags selection
4. When removing the talk app, tagging is working again.

### Expected behaviour
Tag selection window should open

### Actual behaviour
Window didn't open, there is noch debug/error message in the logs

## Browser
Chrome  80.0.3987.116 (64 bit)
Firefox 73.0.1 (64 bit)

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

### Browser log
No error in log.

## Talk app

**Talk app version:** 8.0.4

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.2.24

**Nextcloud Version:** 18.0.1

**List of activated apps:**
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.0
  - groupfolders: 6.0.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflow_script: 1.3.1
  - workflowengine: 2.0.0

**Nextcloud configuration:**

**Comment by nickvergessen** [comment]
Its fixed already with https://github.com/nextcloud/spreed/pull/2962 or https://github.com/nextcloud/server/pull/19511 so updating either 18.0.2 or 8.0.5 will fix it. But both are not yet released

**Comment by chrissi55** [comment]
There are changed 3 files!
Could it be that the path apps/systemtags/src/systemtagsinfoview.js is usually not available on 18.0.1 when installing from zip file downloaded from nextcloud.com??

I've patched the files in js folder ....

**Comment by nickvergessen** [comment]
Yeah, the src/ is compiled into the js/ so replacing that should be enough

**Comment by nickvergessen** [comment]
But i just noticed i pointed to the master branch, so in case it doesnt work try https://github.com/nextcloud/server/pull/19574

**Comment by chrissi55** [comment]
Thank you nickvergessen
I patched them as is behind your latest link. Hope the 18.0.2 will override all manual changes too, to have a clean js folder after that. Roadmap says March 2020 for the 18.0.2, right?

**Comment by thomasgg23** [comment]
Works for me with talk version 8.0.5 and nextcloud 18.0.3
