### ISSUE TITLE
Strange 3-point Menu in videochat

### ISSUE THREAD

**Issue by jgrete** [nextcloud/spreed#299]
### Steps to reproduce
1. Start videochat app
2. choose a chat partner
3. click the 3-point menu of your chat partner

### Expected behaviour
a well looking vertical menu should appear

### Actual behaviour
a not so good looking one liner menu appears. All entries are written on this one line making it nearly unreadable and unusable

### Server configuration
**Operating system**: Linux cloud 4.4.57-18.3-default #1 SMP Thu Mar 30 06:39:47 UTC 2017 (39c8557) x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, pcre, hash, SPL, Reflection, session, standard, SimpleXML, filter, xml, mysqlnd, apache2handler, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, gd, iconv, intl, json, exif, mcrypt, mysql, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, sqlite3, tokenizer, xmlreader, xmlwriter, zip, zlib, mhash

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - activitylog: 0.0.1
 - admin_audit: 1.1.0
 - apporder: 0.3.3
 - checksum: 0.3.4
 - comments: 1.1.0
 - dav: 1.1.1
 - external: 1.2
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_retention: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - ownbackup: 17.3.0
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - qownnotesapi: 17.3.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - spreedme: 0.3.8
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_external: 0.4
 - workflowengine: 1.1.1

Disabled:
 - delete_confirmation
 - encryption
 - imprint
 - notes
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocwkdzl05b94",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxx.xxxx.xxx",
        "1xx.xx.xx.xxx",
        "localhost",
        "127.0.0.1",
        "1xx.xxx.xxx.xxx"
    ],
    "datadirectory": "\/srv\/oc_data",
    "overwrite.cli.url": "https:\xxxxxxxxx/owncloud",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "gpcloud_db",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbdriveroptions": {
        "1002": "SET wait_timeout = 28800"
    },
    "log_type": "owncloud",
    "logfile": "\/srv\/oc_data\/owncloud.log",
    "loglevel": 5,
    "syslog_tag": "Owncloud",
    "logdateformat": "F d, Y H:i:s",
    "logtimezone": "Europe\/Berlin",
    "cron_log": true,
    "log_rotate_size": 10485760,
    "installed": true,
    "maintenance": false,
    "theme": "gp3",
    "mail_from_address": "oc.admin",
    "mail_smtpmode": "smtp",
    "mail_domain": "xxxxx.xx",
    "default_language": "de_DE",
    "trashbin_retention_obligation": "auto, 30",
    "trashbin_auto_expire": true,
    "updatechecker": false,
    "enable_certificate_management": true,
    "htaccess.RewriteBase": "\/owncloud",
    "filelocking.enabled": true,
    "mail_smtphost": "xxxx.xxxxxx.xx",
    "mail_smtpport": "25",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\SFTP
    [4] => \OCA\Files_External\Lib\Storage\AmazonS3
    [5] => \OCA\Files_External\Lib\Storage\Dropbox
    [6] => \OCA\Files_External\Lib\Storage\Google
    [7] => \OCA\Files_External\Lib\Storage\Swift
    [8] => \OCA\Files_External\Lib\Storage\SFTP
    [9] => \OCA\Files_External\Lib\Storage\SMB
    [10] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by jgrete** [comment]
![2017-04-27 12_16_46-issue-videochatnc](https://cloud.githubusercontent.com/assets/14105933/25478984/9803bac0-2b43-11e7-9865-38e0771ae2b1.png)

**Comment by nickvergessen** [comment]
We will release a fixed version on tuesday

**Comment by jgrete** [comment]
Thanks for quick response!
Juergen
