### ISSUE TITLE
treat replies like mentions if it comes to notifications

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2991]
Most of the time you expect a answer / response if you reply to someones message. Therefore I think it would make sense to treat replies like mentions when it comes to notifications. This means that if a user set "only notify me on @-mention", they should also get a notification for replies... What do you think?

**Comment by nickvergessen** [comment]
This should already be the case, I also talked to ivan about this last week. I think the only thing missing is the unread count does not turn blue
