### ISSUE TITLE
Drag and drop file upload

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2994]
Add ability to upload and share files to a chat by dragging them in the chat.

**Comment by nickvergessen** [comment]
Btw, I would make it similar to gihub and make the dropzone the new message part only.

**Comment by ma12-co** [comment]
> Btw, I would make it similar to gihub and make the dropzone the new message part only.

Why not the whole chatview? I think it's more user friendly

**Comment by nickvergessen** [comment]
Well as long as there is good enough hover feedback, that should be good enough.
Having the full chat view show a hover state when you drop a file looks kind of weird (check files app)

**Comment by szaimen** [comment]
> Why not the whole chatview? I think it's more user friendly

+1 for that. E.g. whatsapp web is also allowing that.
