### ISSUE TITLE
File upload: prevent files with the same name from getting overwritten.

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2995]
## Steps to reproduce
1. Upload a file;
2. Upload a file with the same name;

### Expected behaviour
The second file is renamed before the upload: a suffix is added e.g filename(1) so that the first uploaded file isn't overwritten.

### Actual behaviour
The first file gets overwritten by the second;

**Comment by nickvergessen** [comment]
Duplicate of #2987

**Comment by ma12-co** [comment]
lol
