### ISSUE TITLE
optional high scalability backend

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#30]
It should be possible in the future to switch to a high scalable signaling backend for very big installations. This is for version 2.0 and not needed today.
There is some technology evaluation needed. Possible is a new Go or Node.js daemon.

**Comment by fancycode** [comment]
See https://github.com/nextcloud/spreed/pull/366 for the PR adding support for a standalone signaling server and https://github.com/nextcloud/spreed/wiki/Spreed-Signaling-API for the documentation of the API.

**Comment by nickvergessen** [comment]
Closing as this is "done"
