### ISSUE TITLE
Unread counter position

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3004]
See this screenshot, the unread counter position is all over the place depending on the amount of unread messages, and seemingly also if the last message touches the unread counter.
![Talk unread counter position and count](https://user-images.githubusercontent.com/925062/75270231-ca0ee300-582c-11ea-8e47-7d830580b4a1.png)

Instead:
- The maximum unread count should be 99+. It doesn’t matter if there’s 1230 or 1748 unread messages – if it’s 100 then it’s a lot.
- The bubble should be aligned somewhere. Looking best is probably horizontally centered below the 3-dot icon.

cc @nextcloud/designers-talk if you point out where in the code this could be changed, this would be a good first issue. :)

**Comment by nickvergessen** [comment]
Im with you that it should be limited, but I think 99+ is too little :/
100 is not even half an average day in engineering. And you can skim quickly over 💯 messages to catch up at least with your mentions, for more you know you need some time if you care. So I would prefer 999+ 🤔

**Comment by nickvergessen** [comment]
Code location is https://github.com/nextcloud/spreed/blob/master/src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue#L217
And https://github.com/nextcloud/spreed/blob/master/src/components/LeftSidebar/ConversationsList/Conversation.vue#L351

**Comment by VincentWo** [comment]
This seems to be fixed in the newest version. Isn't it?

**Comment by nickvergessen** [comment]
Yeah I think so.
