### ISSUE TITLE
Show a proper warning when talk cannot connect to the HPB

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#3012]
## Steps to reproduce
1. Setup a HPB
2. The HPB is not rechable from a users machine due to some proxy/firewall settings

### Expected behaviour
A proper error message is showning

### Actual behaviour
The UI seems to load, but chats do not open, no error is shown.

https://github.com/nextcloud/spreed/blob/b9f99991b174d90a49aee6121ad5c463f9e1fb9f/src/utils/signaling.js#L587-L590 was not triggered so I assume that the connection attempt was still running but the server didn't respond and the connection did not timeout in a reasonable amount of time. It might be a good enhancement to add a manual timer for such cases.

**Comment by nickvergessen** [comment]
The thing is triggering a reconnect wouldn't help, if a connection is simply not possible. I guess it would mean we simply terminate for now and maybe you get another signaling server next time that works...

It will also change once #2560 is done

**Comment by nickvergessen** [comment]
This is happening now

**Comment by nickvergessen** [comment]
Done in https://github.com/nextcloud/spreed/pull/3282
