### ISSUE TITLE
Last room message should always show the last public message

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#3023]
Currently when a participant triggers a private command message the other participants will get an empty message in the last message of the conversation data.

## Steps to reproduce
- Create a conversation with user B
- Send _hello_
- Send _/help_
- Open Talk with user B

### Expected behaviour
The last message preview for the conversation in the list of conversations should be _hello_.

### Actual behaviour
The last message preview for the conversation in the list of conversations is empty.

**Comment by nickvergessen** [comment]
Well yes, but on the other side we don't know if the command is public or not.
Also it would be somewhat confusing for the actual author, if they execute a command but the last message is different.

So while not optimal, I think the current method is the better option, as the number of private commands is even less than the number of public commands.

**Comment by danxuliu** [comment]
> Also it would be somewhat confusing for the actual author, if they execute a command but the last message is different.

Sure, I did not express myself clearly. I meant that the last room message should always show the last public message... for the other participants. For the participant that triggered the command it should be the command output, of course.
