### ISSUE TITLE
Shared files are saved in the root folder for new users

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#3041]
## Steps to reproduce
1. Create a new user (don't login with this user);
2. Share files with this user in a talk conversation;

### Expected behavior
The shared files are saved in the /Talk folder

### Actual behavior
The shared files are saved in the new user's root folder. (The talk folder doesn't exist yet)

**Comment by nickvergessen** [comment]
Did you run newest master?

**Comment by ma12-co** [comment]
Yes, the talk folder isn't generated until the newly created user first opens the talk app. 
I think that the folder should be generated regardless of that if the talk app is enabled.

**Comment by szaimen** [comment]
What happens if the talk folder cannot get created? Does the app function nonetheless? (E.g. if the root folder isn't writeable or the /Talk folder isn't existant/cannot get created)

I hope this doesn't happen:
https://github.com/nextcloud/notes/issues/436

**Comment by szaimen** [comment]
As an admin, it would be really nice beeing able to define a default path for storing the attachments from the admin settings, which preferably also works with varibles like the userid. :)

**Comment by nickvergessen** [comment]
Since the code is executed while trying to setup the users home folder the logic is going to be kept as simple as possible. So an admin setting as well as palceholder variables are not on the list.

**Comment by szaimen** [comment]
Hm okay... But what happens if the /root folder isn't writeable and the /Talk folder not existant? 
Will the app bug out like it happened here? nextcloud/notes#436

**Comment by Dubidubiduu** [comment]
> 
> 
> Hm okay... But what happens if the root-path for a user isn't writeable and the Talk-folder not existant?
> Will the app bug out like it happened here? [nextcloud/notes#436](https://github.com/nextcloud/notes/issues/436)
> Or here: [nextcloud/notes#429 (comment)](https://github.com/nextcloud/notes/issues/429#issuecomment-579195034)

I have this setup. How do I get my attachments in a "Talk" Folder if my root path isn't writeable?

**Comment by nickvergessen** [comment]
Why should your root not be writeable?
For now Talk does not support such behaviour.

**Comment by PVince81** [comment]
some deployments use an external storage as primary storage, so they mount it for all their users and lock the root folder with zero quota or other.

or maybe they use a received share as common storage and don't allow private storage

in any case, the workaround is that when you provision users, you'll need to create the "Talk" folder for these users

Talk cannot bypass the storage permissions to automatically create that folder.

**Comment by Dubidubiduu** [comment]
I use group folders and and prevent writing at root.

However, no Talk functionality planned to fix this issue?

Also someone know how to do it via ./occ? Can't fix it for 60 users via impersonate or so

**Comment by szaimen** [comment]
You can set it via occ user:setting in a loop for each user

**Comment by nickvergessen** [comment]
> I use group folders and and prevent writing at root.

Workaround 1: allow writing to root

Workaround 2: allow writing to root, make everyone login and open Talk so it creates the folder, disallow writing to root again and prepare for follow up issues with other apps

Workaround 3: Create it manually as per Vincents comment
