### ISSUE TITLE
Weird behavior of NewMessageForm when switching conversations

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#3049]
## Steps to reproduce
1. Open a conversation;
2. Start writing a message;
3. Switch to a different conversation;

### Expected behavior
If you had been writing a message in the newly routed conversation before but you didn't send it, display that message in the new message form. Else the new message form should be empty.

### Actual behavior
The message that you were writing in the previous conversation is displayed in the newly selected conversation.

**Comment by nickvergessen** [comment]
> if any, display a the message that you were writing in the newly routed conversation.

sounds like the worst of both worlds

**Comment by ma12-co** [comment]
> sounds like the worst of both worlds

That's badly worded, let me try and rephrase

**Comment by PVince81** [comment]
how about remembering typed message per conversation ? (in session storage)

this has the advantage that if an error occurs that resets the page (like the "conversation not found" we had before in big channels), the message would not get lost and can be recovered after a page refresh

and it would solve this issue :smile:

**Comment by nickvergessen** [comment]
@PVince81 you implemented this now with https://github.com/nextcloud/spreed/pull/5379 right?

**Comment by PVince81** [comment]
yes, implemented and even approved by @ma12-co himself, closing
