### ISSUE TITLE
Unsent message gets lost when accidentally closing tab

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3055]
## Steps to reproduce
1. Write some well thought-out message, don’t send it yet cause it’s in progress
2. Accidentally close the browser tab or whole browser (alternatively have it crash)
3. Reopen it and see the message is gone

### Expected behaviour
Somehow there should be error-prevention here. Several options:
- Easy: If there’s anything typed in the message field and you try to close the window, show one of these browser alerts that you will lose your input.
- Medium: Save the message locally in the browser so it’s restored even on crashes.
- Hardcore (and proper): Have the possibility to have per-conversation drafts which are saved cross-platform so you can continue on your mobile.

**Comment by nickvergessen** [comment]
Easy: sure we can do for now

Medium: I guess #3049 together with https://github.com/nextcloud/nextcloud-browser-storage/issues/1 could solve this pretty good.

Hardcore: *closes issue*

**Comment by Shen** [comment]
Hardcore would be sooo great 😄
