### ISSUE TITLE
screensharing in Firefox 73.0.1 broken

### ISSUE THREAD

**Issue by foss-** [nextcloud/spreed#3070]
## Steps to reproduce
1. create call in talk
2. allow audio + video in firefox
3. click screensharing
4. Firefox offers selection of screens + windows, select one
5. error is shown

### Expected behaviour
Screensharing should be initiated.

### Actual behaviour
Error "An error occurred while starting screensharing.✖"

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macOS 10.15.3

**Browser name:** Firefox 73.0.1

**Nextcloud:** 18.0.1

This is likely a problem in Firefox itself as jitsi is having similar trouble: https://github.com/jitsi/jitsi-meet/issues/5119

**Comment by nickvergessen** [comment]
I just did one this morning using Firefox 73.0.1, so it seems to be an issue with your firefox. Try starting it either with an empty profile or without any extensions/addons.

**Comment by foss-** [comment]
@nickvergessen on macOS?

**Comment by nickvergessen** [comment]
No, but that seems to be exactly the point after checking further on the jitsi and other issues.
But we can't fix this :crying_cat_face: 

Anyway thanks for letting us know :sunglasses:

**Comment by Ivansss** [comment]
Hi @foss- 
I have tested it using macOS 10.15.3 and Firefox 73.0.1.
After giving the privacy permissions for Screen Recording to Firefox and restart Firefox, I was able to share my screen.

<img width="645" alt="Screenshot 2020-03-09 at 13 32 24" src="https://user-images.githubusercontent.com/4638605/76213426-f2beb180-620a-11ea-88f2-0436d6b61981.png">

**Comment by foss-** [comment]
@Ivansss thanks for verifying this is not a general issue.
Did add Firefox in the screen recordings privacy settings and restarted Firefox. But the issue persists. Maybe it's specific to the instance I am using. Will double check.

**Comment by nickvergessen** [comment]
You can try on our instance in the talk dev channel if you want:
https://cloud.nextcloud.com/call/c7fz9qpr

**Comment by foss-** [comment]
When I visit https://cloud.nextcloud.com/call/c7fz9qpr I am unable to initiate a call, as the button is greyed out. Probably behaving as intended, since maybe it's a sane policy to not allow guests to initiate a call.
<img width="551" alt="Start Call greyed out" src="https://user-images.githubusercontent.com/5708172/76324538-74cfd880-62e6-11ea-9979-37f469a50a8e.png">

**Comment by Ivansss** [comment]
Reproducible in our test call but only with @foss- machine (I was using the same macOS and Firefox versions :S)
Might be realted with some plugin/add-on? 

There was no error in the console but the following alert was visible:

![FF0sHPJ](https://user-images.githubusercontent.com/4638605/76326263-b19ccf00-62e8-11ea-980b-08bde53ebb3e.png)

Re-opening the issue for further investigation.
@danxuliu any idea?

**Comment by nickvergessen** [comment]
> Reproducible in our test call but only with @foss- machine (I was using the same macOS and Firefox versions :S)

Even more a reason why the fault is on his maschine. So the spirit is to:

https://github.com/nextcloud/spreed/issues/3070#issuecomment-596490152
> Try starting it either with an empty profile or without any extensions/addons.

**Comment by foss-** [comment]
I am really unsure what to make of this. I tested Firefox 74.0 and nightly build. Both worked and both gave the error. When it worked it did work with add-ons enabled. When it didn't work it continued to not work even with add-ons disabled.

Maybe something is indeed broken in the Firefox profile. After everything is pointing to a local issue, let's close this and sorry for the noise. Currently it works. Sadly I am unable to understand the pattern why it does not work when it does not work.
