### ISSUE TITLE
Conversation is ended on click on a Project shared item

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/spreed#3074]
## Steps to reproduce
1. Start a conversation (video)
2. Click on a folder (or other item) shared on a project
3. Conversation is ended because that click reloads the page and goes to the page of the folder

### Expected behaviour
New tab is opened

### Actual behaviour
Conversation is ended because that click reloads the page and goes to the page of the folder

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Firefox/Chrome

**Browser version:** 73/80

## Talk app

**Talk app version:** 7.3.0

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3.15

**Nextcloud Version:** 17.0.3

**Comment by nickvergessen** [comment]
This is fixed in Talk 8, so if you update to Nextcloud 18 and Talk 8.0.5, it will work
