### ISSUE TITLE
Keyboard shortcuts for mute/unmute and video enable/disable

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#308]
Currently it’s a bit annoying to need to click on the mute/unmute button manually each time. Ideally that would work via a keyboard shortcut.

- `m` for mute/unmute toggle
- `v` for video enable/disable toggle
- we don’t need a shortcut for screensharing

Is it also possible to catch shortcuts globally? Then we could use Ctrl-M for mute/unmute toggle even if the tab or browser is not focused – only if possible and if that’s not considered privacy invasion for an extension.

@Ivansss @nickvergessen @gsambrotta what do you think?

(cc @jospoortvliet cause we talked about this.)

**Comment by nickvergessen** [comment]
I hate global catching of keys and hope it's not possible.
But when the window is focused, I'm okay with m+v

**Comment by jancborchardt** [comment]
Yeah, was just thinking about the global catching cause it’s pretty handy if you don’t need to switch to the window / tab first. Now you still need to be in the window/tab, but at least it would be an improvement. :)

So let’s go with `m` and `v` since it will already improve a lot. :)

**Comment by nickvergessen** [comment]
>ChristophWurst: nickvergessen: sorry for the delay, was afk. We register the global event handler here: https://github.com/nextcloud/mail/blob/7c3db4dd4067d8a14c5adf3e80739d1ddfc572d0/js/views/appview.js#L75-L77 and then dispatched via the backbone radio here https://github.com/nextcloud/mail/blob/7c3db4dd4067d8a14c5adf3e80739d1ddfc572d0/js/views/appview.js#L126-L137


>ChristophWurst: the actual handling of different keys happens here https://github.com/nextcloud/mail/blob/ba221fb53baa64bb362ae03d186b46105a261a48/js/views/foldercontent.js#L151-L199

**Comment by nickvergessen** [comment]
We  now went with:
* a - toggle audio on/off
* v - toggle video on/off
* p - switch to participants tab
* c - switch to chat tab

**Comment by Luticus** [comment]
This is breaking talk for gaming completely. For some reason now it mutes and un-mutes constantly during game play. Please make these keys customizable and/or able to be disabled entirely. This created an awful situation where no one understood why they were being muted and un-muted.
