### ISSUE TITLE
Feature: Allow hiding conversation list / true full screen mode

### ISSUE THREAD

**Issue by clawoflight** [nextcloud/spreed#3082]
It is quite surprising that the details panel can be closed, but not the conversation list.

It would be very nice to get more screen real-estate for the actual video call when wanted.
There are 2 straightforward solutions to this:

1. allow collapsing the conversation list, like the details panel
2. do not show the conversation list in full screen mode

**Comment by nickvergessen** [comment]
Try pressing `F` while in a call or use the fullscreen button in the top right of the call view

**Comment by clawoflight** [comment]
@nickvergessen Should that hide the conversation list?
If so, this should be a bug instead of a feature request :)

OS: Arch Linux
Browser: FF 74
NC: 18.0.1
Talk: 8.0.5

**Comment by nickvergessen** [comment]
Hmm seems like app-navigation, app-content and app-sidebar are now 3 elements on the same level.But I guess we can change this manually with a vue `v-show=isFullscreen` in the right place.

**Comment by clawoflight** [comment]
Thank you!
I am familiar with React, but not Vue or this codebase - if you could give me a 2 sentence primer on the architecture of the project, and a 2 sentence primer on how to test it locally, I can give tackling this a go :)

**Comment by nickvergessen** [comment]
Sorry, I was about to explain it, but since it ment moving the information to a store I ended up doing it while trying to prepare an explanation :cat2: 


But you can still check it out:
https://github.com/nextcloud/spreed/pull/3101

So you either need git in your development enviroment with a Nextcloud server also installed from git.
Then you clone this repo checkout the branch in question and run `make dev-setup && make build-js`

**Comment by clawoflight** [comment]
Cool, thank you very much!
So I would have the Nextcloud server repo in a web server's root, and clone this repo in the apps directory?

**Comment by nickvergessen** [comment]
yes, but I would only do this in a local test enviroment.

**Comment by clawoflight** [comment]
Sure :)

**Comment by newhinton** [comment]
@nickvergessen would it be a bad idea to add a burger menu to the left menu? While it would be a deviation from the "normal" way nextcloud handles the menu (on desktop browsers at leats), it would not be unreasonable (and intuitive) to allow the user to collapse this while a call is ongoing

**Comment by nickvergessen** [comment]
Yeah, it seems to only appear when the window is narrow enough.
Maybe you can create a new issue for it, @newhinton ?
