### ISSUE TITLE
Nginx complains about (js).map files

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/spreed#3086]
- NC 18.0.2
- Spreed 8.0.5

```
open() "js/collections.js.map" failed (2: No such file or directory)
open() "js/talk.js.map" failed (2: No such file or directory)
open() "js/talk-files-sidebar-loader.js.map" failed (2: No such file or directory)
```

**Comment by nickvergessen** [comment]
Well check your nginx config? We don't deliver the map files at the moment, as the just increase the package size drastically without helping end-users

**Comment by acs-ferreira** [comment]
Hum, i'm surely wrong but how can nginx look for files to `open()` alone? Isn't this application stuff?

I've checked https://github.com/nextcloud/spreed/issues/2802 also as nginx also claims about 

`open() "/apps/spreed/js/admin/sha1.js failed (2: No such file or directory)`

you state there that user is having apps in two locations, here too we are using custom apps locations (`/apps` and `/shipped_apps`) but after check, spreed is present only on `/apps` (folder for apps not shipped with Nextcloud).

![image](https://user-images.githubusercontent.com/12234510/76707244-ca90f000-66ed-11ea-8de6-0a11b80f9810.png)

Those apps are installed, only Spreed is noisy on `error.log` 

The only non-standard nginx configuration (taken from doncs) is this block:

```
location ~ /apps/(.*)$ {
    alias /srv/nfs/shipped_apps/$1;
}

location ~ /custom_apps/(.*)$ {
    alias /srv/nfs/custom_apps/$1;
}
```

Nextcloud was upgraded from 17.0.4 to 18.0.2 (no warnings or errors before upgrade).

**Comment by acs-ferreira** [comment]
Regarding `sha1.js` file, it isn't shipped, but it is loaded here, no?
https://github.com/nextcloud/spreed/blob/016ee3fe9288d25492caac5ddefae8fbcd22644a/templates/settings/admin/turn-server.php#L4

**Comment by nickvergessen** [comment]
That's right, fix is in #3107

**Comment by acs-ferreira** [comment]
Thanks. Also, FYI:

```
# grep -rl "sourceMappingURL"

js/talk-files-sidebar-loader.js
js/collections.js
js/talk-public-share-auth-sidebar.js
js/admin/allowed-groups.js
js/admin/stun-server.js
js/admin/general-settings.js
js/admin/signaling-server.js
js/admin/commands.js
js/admin/turn-server.js
js/talk-files-sidebar.js
js/talk.js
js/flow.js
js/talk-public-share-sidebar.js
```

**Comment by nickvergessen** [comment]
yeah well we are intentionally removing map files to decrease the package size:
https://github.com/nextcloud/spreed/blob/master/Makefile#L71

But sure we can remove this and make everyone download more than 20MB instead of 2MB

**Comment by acs-ferreira** [comment]
Sure! And what about
https://github.com/nextcloud/spreed/blob/91cbdb612db83c677fddf3cd6389b71024cbb39c/webpack.prod.js#L6
and https://webpack.js.org/configuration/devtool/#production
or https://github.com/facebook/create-react-app/issues/2787#issuecomment-434943749

Can't these help?

**Comment by nickvergessen** [comment]
Reopening for https://github.com/nextcloud/spreed/issues/3086#issuecomment-602594138
