### ISSUE TITLE
Custom Ringtones per Conversation and/or per User ID

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/spreed#3087]
**Is your feature request related to a problem?**
At one place I worked, I got messages from the CEO but we were using the Google "G Suite" and his messages were filtered as advertisements. This caused me to not see important messages from him. Also, I would like to know if a conversation is of different importance is getting a new message before I want to distract myself from what I'm doing. 

**Describe the solution you'd like**
A place to store a custom ringtone of some sort to distinguish the urgency of a conversation or of a specific person. The person with a custom tone would take precedence over a conversation custom tone if there were a clash (I think that's best?).

**Comment by nickvergessen** [comment]
Almost no messenger app does this. So at least not a priority at the moment.

Also this should be posted in the mobile app repos instead. Do you want to create the issues there?
https://github.com/nextcloud/talk-android/issues
https://github.com/nextcloud/talk-ios/issues

**Comment by WNYmathGuy** [comment]
> Almost no messenger app does this. So at least not a priority at the moment.
> 

@nickvergessen I'm taking your point, but my Signal app for android does this. I have a reworked Borat clip that sounds when my wife texts me as well as others.
["My wife, my wife, my wife"](http://wnymathguy.com/RT/mywife.mp3)

> Also this should be posted in the mobile app repos instead. Do you want to create the issues there?
> https://github.com/nextcloud/talk-android/issues
> https://github.com/nextcloud/talk-ios/issues

I will post it there if you insist, but my intention was to have the central cloud system host the customization and from there the apps would pull the audio files into the cache for local playback. It seemed to me that having consistency across all devices was the advantage so a server-level solution was intentional.

**Comment by nickvergessen** [comment]
A server-level solution is not going to make it up on the priority list anytime soon

**Comment by mario** [comment]
Android already has an issue for this: https://github.com/nextcloud/talk-android/issues/401

**Comment by nickvergessen** [comment]
Created iOS here:
https://github.com/nextcloud/talk-ios/issues/291
