### ISSUE TITLE
Enforce password policy for shared links

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#3089]
The password policy under Administration/Security is not applied on shared links in talk.
![image](https://user-images.githubusercontent.com/16019165/76714656-a4d50c80-6728-11ea-8faf-d106b796c182.png)

Since it is a general security setting (and not only for sharing files), it should apply to every shared link including talk rooms. 

**Describe the solution you'd like**
1) The password field in talk should respect the settings in Administration/Security/Password policy
![image](https://user-images.githubusercontent.com/16019165/76714334-ba493700-6726-11ea-97e5-3654ead32762.png)

2) There should be an option (like in Administration/Sharing) to enforce password protection for talk conversations. This would prevent users from creating rooms without a password.
![image](https://user-images.githubusercontent.com/16019165/76714544-de594800-6727-11ea-9746-7173d74b27ce.png)

3)  People invited by mail should get a second e-mail with a custom password for this talk conversation (like sharing via mail). 
![image](https://user-images.githubusercontent.com/16019165/76714607-3ee88500-6728-11ea-9be6-3fba80b5d673.png)

**Comment by sudwhiwdh** [comment]
> Since it is a general security setting (and not only for sharing files), it should apply to every shared link including talk rooms.

Especially since Talk is also a default app, I would like to see this handled more consistently, yes!

**Comment by nickvergessen** [comment]
Event to trigger:
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Security/Events/ValidatePasswordPolicyEvent.php#L33

**Comment by michag86** [comment]
Has this really been fully implemented?

I cannot find an option to enforce all link shares to be password protected.
