### ISSUE TITLE
Enhance display of currently speaking participant

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#309]
When there is no video, the avatar of the promoted person looks a bit tiny floating in the middle. I would say we improve that view by:

- Doubling the size of the promoted avatar (only if there’s no video of course), twice the size seems good
- Bolding the username in the bottom bar
- Additionally it would be cool for the avatar be also used in a blurred version to cover the whole background. Kind of like it’s on video platforms for portrait videos which are shown in landscape. Can be done entirely in CSS, I just need to have a second avatar container to do that with. :)

What do you think @Ivansss @gsambrotta?

**Comment by nickvergessen** [comment]
Superseded by #1056
