### ISSUE TITLE
missing activity notification via email

### ISSUE THREAD

**Issue by brrrrrrrt** [nextcloud/spreed#3094]
## Steps to reproduce
1.check if all **_invited users_** have enabled the checkbox for `Mail` at `You were invited to a conversation or had a call` within `personal-settings->activity`: 
![Bildschirmfoto von 2020-03-17 13-07-45](https://user-images.githubusercontent.com/4489013/76855613-c41b8900-6851-11ea-9968-837de11c5dcd.png)

2.start a new conversation
3.add some local users as participants
4.create conversation
5.nobody ever gets the "promised" email

### Expected behaviour
all users who have activated mail notifications within their activity settings should get email notifications

### Actual behaviour
no emails are sent, notifications are only shown in the browser (stream, notification area), the checkbox for mail has no effect.

## Talk app

**Talk app version:** 8.0.5

## Server configuration
**Operating system:** Linux 4.19.0-6-amd64 #1 SMP Debian 4.19 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 7.3.15-4+0~20200224.55+debian10~1.gbpbea824

<details>

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, memcache, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

</details>

**Nextcloud version:** 18.0.2 - 18.0.2.2

**List of activated apps:**

<details>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - socialsharing_email: 2.0.0
 - socialsharing_facebook: 2.0.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - recommendations
 - user_ldap
```

</details>

**Nextcloud configuration:**

<details>

```
{
    "debug": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.funny-domain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "asset-pipeline.enabled": false,
    "enable_previews": true,
    "preview_max_x": 1000,
    "preview_max_y": 1000,
    "preview_max_scale_factor": 100,
    "htaccess.RewriteBase": "\/",
    "loglevel": 2,
    "theme": "",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\PDF",
        "OC\\Preview\\SVG"
    ],
    "trashbin_retention_obligation": "auto",
    "appstore.experimental.enabled": true,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "overwrite.cli.url": "https:\/\/my.funny-domain.com",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true
}

```
</details>

** **

email notification does work with other apps, e.g. if `Mail` is checked at `A calendar event was modified`. this is why i thought this might be the right place to report this issue, sorry if i am wrong...

**Comment by nickvergessen** [comment]
> email notification does work with other apps, e.g. if Mail is checked at A calendar event was modified. this is why i thought this might be the right place to report this issue, sorry if i am wrong...

This was still a bug in the activity app, but that was impossible to know up front.

I fixed it in https://github.com/nextcloud/activity/pull/437

**Comment by levigo-systems** [comment]
Is this just a bug in new conferences or in all activity notifications?

Currently we have the problem with Nextcloud 18 on all activity notifications. No emails are sent.

**Comment by brrrrrrrt** [comment]
i did not get notifications about calls and new conferences, but i did get emails on calendar changes.

after some hours without changing anything it seems i suddenly got emails about activity without any hint about what kind of activity, i think they were related to some calls i tried.

**Comment by nickvergessen** [comment]
> after some hours without changing anything it seems i suddenly got emails about activity without any hint about what kind of activity, i think they were related to some calls i tried.

exactly. But that is fixed with the activity PR.

**Comment by levigo-systems** [comment]
So there are no issues with the other activity notifications?
We tested on 2 NC 18, test mail works, activity notifications do not work

**Comment by nickvergessen** [comment]
Normal activities work. If they don't for you, ask for help in the forum instead of high-jacking a talk issue ;)
https://help.nextcloud.com/
