### ISSUE TITLE
polish new group conversation creation

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#3097]
Some remarks:

1. I think the `Search for more contacts` text + icon should only show up when the search term is empty. It looks very confusing at the bottom otherwise:

> ![Bildschirmfoto von 2020-03-12 16-14-42](https://user-images.githubusercontent.com/213943/76537034-75e73e00-647d-11ea-896c-d64a5fb9ddbb.png)

2. I think empty headers should not be displayed, or they should be grouped and show a "No search results" message like in the left sidebar

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/pull/3073#issuecomment-598247961_

- [ ] Bring back search icon

**Comment by nickvergessen** [comment]
Done
