### ISSUE TITLE
Think about way to display all participants of a call even if they are not connected

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#310]
We never see a list of all participants of a room, except when hovering the entry in the sidebar. We could think about showing half-transparent »ghost entries« in the bottom bar to be able to directly know who could potentially be in this call.

A 3-dot menu next to the name could then also be used to promote them to moderator, or remove them from the call. Ref https://github.com/nextcloud/spreed/issues/297

What do you think @nextcloud/spreed?

**Comment by nickvergessen** [comment]
Yeah sounds good

**Comment by Ivansss** [comment]
At this moment, we show the participants who are in the call or connecting to the call at the bottom bar.
I don't think is a good idea to also add there people who has been invited to that call but they are not even trying to connect to the call.
I would rather add an option in the call menu like 'Edit call' that will show a popup view where you can see a list of participants and there you can assign them as moderators, remove them from the call,...

**Comment by nickvergessen** [comment]
I missread, yeah I thought in the three dot menu of the call. Ghost users are bad, because just imagine our company room, 20 half overlaying user avatars, not really helpful to find the right user. Also later for hundreds of users with the webinary feature we need it different

**Comment by nickvergessen** [comment]
Quick thought after some local discussions.

How about using the sidebar?
We need space for the scheduling etc anyway in the future.
So we could also just have the side bar (not opened on default), where owners can:
* Remove participants
* Promote/demote moderators
* Schedule calls

So I could imagine to have in the top persistent:
* Link to pass on to other participants
* Make call private/public
  * Set password
* Start/end a call when in lobby mode

Below two sidebar tabs:
* Participants
  Full list of usernames + avatars and a `…`-menu hiding the options:
  * Remove participants
  * Promote/demote moderators
* Scheduling: content to be discussed and designed...

What do you think @jancborchardt @Ivansss

**Comment by jancborchardt** [comment]
Sounds good to use the sidebar, yes! :)

**Comment by nickvergessen** [comment]
Implemented already
