### ISSUE TITLE
Problem with docker installation + nginx map.js

### ISSUE THREAD

**Issue by frankBahlsen** [nextcloud/spreed#3103]
## Steps to reproduce
Nextcloud docker image 18.0.2 - fpm
Tried to call somebody, both saw the message, but connection could not be established.
Webconsol tells me:
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://our.nextcloud/custom_apps/spreed/js/talk.js?v=704c200c-11
Source-Map-Adresse: talk.js.map

## Browser
Tried with mobile app, Chromium, Firefox, Chrome on Linux and Win 10

## Talk app

**Talk app version:** 8.0.5

**Custom TURN server configured:** no

**Custom STUN server configured:** no 

## Server configuration

**Operating system**: Debian, Docker

**Web server:** Nginx

**Database:** Maria

**PHP version:**

**Nextcloud Version:** 18.0.2

**List of activated apps:** 
Accessibility	1.4.0	Featured	
Activities for shared file downloads	1.7.0		
Activities for shared file downloads, visible to all admins	1.7.0		
Activity	2.11.0	Featured	
Announcement center	3.7.0	Featured	
AppOrder	0.9.0		
Automated PDF conversion	1.3.1		
Calendar	2.0.2	Featured	
Checksum	0.4.4		
Collaborative tags	1.8.0	Featured	
Comments	1.8.0	Featured	
Contacts	3.2.0	Featured	
Custom CSS	1.5.0		
Deleted files	1.8.0	Featured	
Draw.io	0.9.5		
External sites	3.5.0	Featured	
Federation	1.8.0	Featured	
File access control	1.8.1	Featured	
File sharing	1.10.1	Featured	
Files automated tagging	1.8.2	Featured	
Files From Mail	0.4.0		
First run wizard	2.7.0	Featured	
Impersonate	1.5.0	Featured	
Log Reader	2.3.0	Featured	
Markdown Editor	2.2.0		
Metadata	0.11.1		
Monitoring	1.8.0	Featured	
Nextcloud announcements	1.7.0	Featured	
Notifications	2.6.0	Featured	
ONLYOFFICE	4.1.4	Featured	
Password policy	1.8.0	Featured	
PDF viewer	1.7.0	Featured	
Photos	1.0.0	Featured	
Privacy	1.2.0	Featured	
Quota warning	1.7.0		
Recommendations	0.6.0	Featured	
Right click	0.15.2	Featured	
Share by mail	1.8.0	Featured	
Social sharing via email	2.0.0	Featured	
Support	1.1.0	Featured	
Talk	8.0.5	Featured	
Tasks	0.12.1	Featured	
Text	2.0.0	Featured	
Theming	1.9.0	Featured	
Update notification	1.8.0	Featured	
Usage survey	1.6.0	Featured	
Versions	1.11.0	Featured	
Video player	1.7.0	Featured	
W2G2	3.0.1		
<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Comment by nickvergessen** [comment]
You mostlikely need to set up a turn server

Regarding the map files see #3086
