### ISSUE TITLE
Enable only for specific groups

### ISSUE THREAD

**Issue by kchan101** [nextcloud/spreed#311]
On initial install/enabling, the option appears available for the Video calls app.  However, after attempting to specify a group, the gui returns "spreed can't be enabled for groups".  Subsequently, the tick box disappears from the Enabled apps tab but is there in the Social & communication tab.

Running on NC 11.0.3 (stable)

**Comment by sggalan** [comment]
We have human users but project-name 'users' as well, and also some not-to-be-called users. So use of Video Calls limited to groups or individual users is a must for us.

**Comment by happyreacer** [comment]
looks ike the same as https://github.com/nextcloud/spreed/issues/246

**Comment by nickvergessen** [comment]
The "Enable only for specific groups" is not possible on 11 and 12 anymore.

Excluding groups from the "call this group" and a list of users from "call this user" is both not possible atm, but  I can see how it would be useful.

**Comment by nickvergessen** [comment]
Closing as per above
