### ISSUE TITLE
new message indicator when sidebar is collapsed 

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3110]
It would be nice if we would have a new message notification when the right sidebar is closed. Maybe the button to re-open the sidebar could have a unread message count? Maybe also change the color or blink twice if a new message comes in... just some ideas.

**Comment by nickvergessen** [comment]
You mean while being in a call?

**Comment by nickvergessen** [comment]
the main issue is, when the sidebar is closed, the message view is destroyed and we are actually not pulling for new messages anymore Oo

Otherwise the work is at https://github.com/nextcloud/spreed/pull/new/feature/3110/unread-indicator-on-folded-chat

**Comment by schiessle** [comment]
> You mean while being in a call?

yes, would be nice to get somehow notified about chat messages while in a call. While writing this I noticed that this would be not only useful when the sidebar is closed but also when the user is in a different tab, e.g. the participants list.

**Comment by PVince81** [comment]
also applies to when the participant list is open, for example when viewing who raised hands, if a message is posted in the chat tab, we should maybe post a number bubble there showing how many new messages are present there

**Comment by nickvergessen** [comment]
Same the otherway around, there should be a raised hand bubble when you have the chat open

**Comment by PVince81** [comment]
> the main issue is, when the sidebar is closed, the message view is destroyed and we are actually not pulling for new messages anymore 

as far as I could observe on master today, the message view is not destroyed while the sidebar is closed.
the calls to `getNewMessages()' are still pumping so we could then find out about unread messages once https://github.com/nextcloud/spreed/issues/1164 is done.

however I'm not sure if we should continue the above long pool as it might disturb call performance and use different techniques to find out about new messages, like through signaling: https://github.com/nextcloud/spreed/issues/3377

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5534
