### ISSUE TITLE
Function keep room alive with notification that is still alive

### ISSUE THREAD

**Issue by nocerainfo** [nextcloud/spreed#3111]
I would like to have talks available for a longer period of time if That would be possible at talk settings to be set.  Could Administrator set the longest a talk could be available? or Could a link be available as long as it is there with noone deleting the link? 

Situation:

> User-master creates the talk on monday (set this talk to last x days)
> User01 - joins talklink-hey
> User02 - joins talklink-hey
> Everyone leaves talklink-hey on monday
> 
> Wednesday comes:
> User 01 - rejoins same link (talklink-hey)
> User 02 - rejoins same link (talklink-hey)
> 

Could a talk link be available for x days or until it is deleted?

**Comment by nickvergessen** [comment]
They are currently always available until they are deleted

**Comment by nocerainfo** [comment]
That is great, Shall I delete this treath?
