### ISSUE TITLE
Easy possibility to start group chats and calls from the app

### ISSUE THREAD

**Issue by scroom** [nextcloud/spreed#3122]
**Is your feature request related to a problem? Please describe.**
I tried the Nextcloud Talk app with a colleague for the first time yesterday. The problem quickly emerged that we could not invite another person from our 1: 1 chat. We also couldn't add more people to a chat from within the app, we could only use ready-made groups that are LDAP-based, or we had to choose a file, share it with multiple people and then open a chat with this file . This is not particularly intuitive.

**Describe the solution you'd like**
Would be great if it would be possible to start a group chat/call from within the app (button start new chat opens selection field where I can search for persons/groups and can add them to a list before I open the new chat.

**Comment by nickvergessen** [comment]
Which app is this about?

Because it should be possible to just create a conversation and then invite anyone you like.
Just not into one-to-one chats (like it is with any other messenger)

**Comment by scroom** [comment]
@nickvergessen About the Nextcloud Talk App (7.0.2) And how do I do so? We've both searched for a while and both did not find a possibility to invite another person to our talk. Under participants (Teilnehmer in german) our names are listed but there is no button ore textfield for adding more persons.

**Comment by scroom** [comment]
If it is already a group chat there is a textfield to add more people.

**Comment by nickvergessen** [comment]
Please try Talk 8.0.x

The UI was redone there and especially creating new conversations is a lot easier there.

**Comment by scroom** [comment]
@nickvergessen I have made an update in the meantime. But it is still not possible to start a group chat with individual users who are not yet in a group.

We use LDAP for user authentication and for groups. Users cannot create their own groups. Nevertheless it would make sense if they would consider using this feature when three of them want to speak together. Unfortunately, this is not possible from the Talk app so far, which I consider a big shortcoming. Or is it a bug that no search field or similar is displayed under participants?

**Comment by nickvergessen** [comment]
Can you add a screenshot to make sure we are taking about the same things?

**Comment by scroom** [comment]
@nickvergessen Here it comes:
![Bildschirmfoto vom 2020-03-24 00-44-03](https://user-images.githubusercontent.com/5347731/77373673-26501e80-6d69-11ea-99f7-de013629c31c.png)

I would like to add another person to this chat. But how could I?

**Comment by nickvergessen** [comment]
Yeah, well that is a one-to-one chat and they can never be extended (doesnt work in any other messenger app either?).

To fix your usecase:
1. Press the `+` in the top left:
![Bildschirmfoto von 2020-03-24 11-32-45](https://user-images.githubusercontent.com/213943/77415901-6ba13a00-6dc3-11ea-854c-833dfae0b64c.png)

2. Enter the group name and afterwards select the participants:
![Bildschirmfoto von 2020-03-24 11-33-01](https://user-images.githubusercontent.com/213943/77415940-807dcd80-6dc3-11ea-8f4c-4ee815f477d0.png)

**Comment by scroom** [comment]
@nickvergessen Shame on me!
