### ISSUE TITLE
Option to stop the automatic change of focus

### ISSUE THREAD

**Issue by scroom** [nextcloud/spreed#3123]
**Is your feature request related to a problem? Please describe.**
Yesterday I tested the Nextcloud Talk app with some colleagues for the first time. A colleague said that it would be extremely annoying that the focus would always be on the one who was speaking at the moment, as the noise would change perspective relatively quickly. This would make it difficult to follow the conversation.

**Describe the solution you'd like**
Insert an option to stop the automatic focus change

**Comment by genma** [comment]
If it's possible to define on which windows / person the focus is made and stay, it will be great. An option to set "this call in big size, other in small size".

**Comment by nickvergessen** [comment]
Well there is also the idea of #1056 

I guess there are just very different needs.
for a 4 person call I sometimes would prefer a layout like:
```
+----+----+
|    |    |
+----+----+
|    |    |
+----+----+
```

But for many (maybe 9+) a layout like that also makes no sense anymore.

cc @nextcloud/designers-talk

**Comment by jancborchardt** [comment]
It seems most platforms like Zoom and Jitsi have a setting for this. Our current layout is the default also usually for them, but the "grid" layout can be toggled.

See a blog post by Jitsi: https://jitsi.org/news/new-feature-brady-bunch-style-layout/

We could also have this, with the toggle "Grid view"/"Speaker view" being in the 3-dot action menu next to the call button when a call is active.

cc @ma12-co

**Comment by nickvergessen** [comment]
So let's close in favor of https://github.com/nextcloud/spreed/issues/1056
