### ISSUE TITLE
URL to Talk is wrong

### ISSUE THREAD

**Issue by jzilg** [nextcloud/spreed#3125]
## Steps to reproduce
1. Install Nextcloud with Docker
2. Use Ngnix as Reverse Proxy
3. Install Talk App via Appstore
4. Open App Talk via the Navigation Bar in Header

### Expected behaviour
The Url to Talk should be https://my.url.de/apps/spreed.
This is the Url I set in my nextcloud config.php as 'overwrite.cli.url'

### Actual behaviour
The Url to Talk is http://localhost:8080/apps/spreed/
It seems Talk does not use the above mentioned Url from config but the URL of the Apache inside the Docker container. 
It works with other Nextcloud Apps.

## Browser

**Microphone available:** yes/no
yes

**Camera available:** yes/no
yes

**Operating system:** Windows/Ubuntu/...
MacOS 10.15.3

**Browser name:** Firefox/Chrome/...
Firefox 

**Browser version:** 50.1/55/...
74.0.0

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
8.0.5

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Debian

**Web server:** Apache/Nginx
Apache with Ngnix Reverse Proxy

**Database:** MySQL/Maria/SQLite/PostgreSQL
Maria

**PHP version:**
7.3.15 (inside Docker Container)

**Nextcloud Version:** (see admin page)
18.0.2

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Should then also happen for all other apps in the top navigation?

**Comment by jzilg** [comment]
I've checked the DOM: All other Links use a relative Path, also "Decks", which is an additional App from the Appstore too. Sreed uses the absolute paht with the localhost as URL.

```
<ul id="appmenu">
    ...
    <li data-id="activity" class="" tabindex="-1">
        <a href="/apps/activity/" aria-label="Aktivität">
            <svg width="20" height="20" viewBox="0 0 20 20" alt="">
                <image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet"
                    xlink:href="/apps/activity/img/activity.svg?v=7fa407ba" class="app-icon"></image>
            </svg>
            <span>
                Aktivität </span>
        </a>
    </li>
    <li data-id="spreed" class="" tabindex="-1">
        <a href="http://localhost:8080/apps/spreed/" aria-label="Talk">
            <svg width="20" height="20" viewBox="0 0 20 20" alt="">
                <image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet"
                    xlink:href="/custom_apps/spreed/img/app.svg?v=7fa407ba" class="app-icon"></image>
            </svg>
            <span>
                Talk </span>
        </a>
    </li>
    <li data-id="mail" class="" tabindex="-1">
        <a href="/apps/mail/" aria-label="E-Mail">
            <svg width="20" height="20" viewBox="0 0 20 20" alt="">
                <image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet"
                    xlink:href="/custom_apps/mail/img/mail.svg?v=7fa407ba" class="app-icon"></image>
            </svg>
            <span>
                E-Mail </span>
        </a>
    </li>
    ...
    <li data-id="deck" class="" tabindex="-1">
        <a href="/apps/deck/" class="active" aria-label="Deck">
            <svg width="20" height="20" viewBox="0 0 20 20" alt="">
                <image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet"
                    xlink:href="/custom_apps/deck/img/deck.svg?v=7fa407ba" class="app-icon"></image>
            </svg>
            <span>
                Deck </span>
        </a>
    </li>
    ...
</ul>
```

**Comment by jzilg** [comment]
I have the solution. I need to to add other overwrites to the nextcloud config.php. Spreed uses this URLs and now i have the correct one in the navigation.

```
'overwritehost' => 'my.url.de',
'overwriteprotocol' => 'https',
```

**Comment by ultrasites** [comment]
> I have the solution. I need to to add other overwrites to the nextcloud config.php. Spreed uses this URLs and now i have the correct one in the navigation.
> 
> ```
> 'overwritehost' => 'my.url.de',
> 'overwriteprotocol' => 'https',
> ```

I had the same problem! Thank you for the solution!

**Comment by dhiachou** [comment]
I have the same problem

I agree that the config edit is a workaround but the URL should be relative like all the other apps. 

Can we reopen the issue ?

**Comment by nickvergessen** [comment]
Editing the configs is exactly what you need to do. Also changing the URL is not a think you would do often as it means you need to reconfigure all clients everytime.

**Comment by Thanson16** [comment]
Since this bug only affects the Talk app, I would also like to see this reopened.

If changing URLs to be relative would fix the issue, it would be useful to me: I currently make the same instance available on 3 different domains (using the trusted_domains configuration parameter), so I can't use overwritehost to fix the URL as it overwrites the URL for all domains. Getting this fixed in the Talk app is all I can see holding up this behavior from working from behind a reverse proxy.

Thank you all for the work that you do.

**Comment by Thanson16** [comment]
I patched my copy of stable19 by replacing the following line in `lib/AppInfo/Application.php`:

Changed line:
```
'href' => $server->getURLGenerator()->linkToRouteAbsolute('spreed.Page.index'),
```
to
```
'href' => $server->getURLGenerator()->linkToRoute('spreed.Page.index'),
```

This changes the nav bar to have the correct URL, which was the only issue I was seeing so far. I do not know if there are other places where the absolute->relative would need to be applied.

If this is a fix you guys want I can make a PR, or if it is easier for you guys to apply it yourselves that's fine too.
If this isn't something you guys want changed then I'll just build my version from source with this line swapped.

I've never contributed to Nextcloud or Talk so I'm not super familiar with your guys' process for this.

**Comment by nickvergessen** [comment]
This breaks the desktop client link?

**Comment by Thanson16** [comment]
> This breaks the desktop client link?

Not sure which link you mean. I don't use the desktop client, but I'm downloading it now to see if there are any issues with it re: this fix.

I quick checked out the mobile client (Android) and everything seemed fine.

**Comment by Thanson16** [comment]
Oh, I think I see what you mean - setting up the desktop client doesn't work with my current setup?

That would be a separate issue then. It definitely inhibits me from using the desktop client with this setup, but I don't see how it would be related to this fix. Let me know if I'm misunderstanding something.

Perhaps I will see if a similar issue has been raised on the client's page.

**Comment by Thanson16** [comment]
I see another issue over there that indicates the Talk button within the client may not work either, which is probably what you're talking about.

Sorry about how clueless I am - like I say I don't usually use the desktop client so I'm figuring this out as I go.

**Comment by Thanson16** [comment]
Looking at the Desktop issues, it seems that configuring it with a set domain is considered the only correct way to do it:

https://github.com/nextcloud/desktop/issues/1233

Which is unfortunate. I will have to just consolidate to using only one domain name then.
Thank you for your time.

**Comment by Thanson16** [comment]
I have good news for anyone struggling with this.

The real solution for me was to enable ProxyPreserveHost in my Apache reverse proxy configuration, as well as making sure to set overwriteprotocol to https in the config.php. This makes Nextcloud's automatic domain detection work as needed.

No need to use modified Talk client, nor set the overwritehost. Desktop client connects normally and all links work perfectly.

Sorry for all the comments on the issue, but I hope anyone else who has this problem might find this helpful.
