### ISSUE TITLE
Login from android-talk does not work

### ISSUE THREAD

**Issue by jmaister** [nextcloud/spreed#3126]
## Steps to reproduce
1. Open Talk on Android for the first time
2. Set my server URL, which works fine with the browser
3. Set username and password

### Expected behaviour
It should login in the the Talk application

### Actual behaviour
It does not login, the spinner keeps rotating indifenitely.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Firefox

**Browser version:** 74

### Browser log
N/A

## Talk app

**Talk app version:**  8.0.5

**Custom TURN server configured:** No

**Custom STUN server configured:** No

## Server configuration
Default, only the my domain to allowed domains added.

**Operating system**: Ubuntu

**Web server:** Apache (Docker)

**Database:** SQLite

**PHP version:**  PHP/7.3.16

**Nextcloud Version:** 18.0.2.2

**List of activated apps:**
Default. None installed

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.paellalabs.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.2.2",
        "overwrite.cli.url": "http:\/\/nextcloud.paellalabs.com",
        "installed": true
    }
}
</details>

### Server log (data/nextcloud.log)
<details>
```
app_1  | 192.168.64.1 - - [21/Mar/2020:15:45:30 +0000] "POST /login HTTP/1.1" 303 856 "-" "Xiaomi Mi 9T Pro (Nextcloud Talk)"
</details>

**Comment by nickvergessen** [comment]
Sorry SQLite is not too suitable to run Talk anyway.
I would suggest to migrate to mysql or postgresql and then retry.

**Comment by jmaister** [comment]
Thanks. I'll try setting up a mysql database.

I just installed a new version. I run Nextcloud+Talk (version 15) with sqlite before and it worked.

**Comment by nickvergessen** [comment]
Then your webserver config might be wrong. Mind to share a test account (send an email to `<my github username>@nextcloud.com`)

**Comment by jmaister** [comment]
I added these configuration parameters to config/config.php.
```
  'overwrite.cli.url' => 'https://nextcloud.paellalabs.com',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'nextcloud.paellalabs.com',
```


It works now.
