### ISSUE TITLE
Adding group to conversation adds individual users, including disabled

### ISSUE THREAD

**Issue by asadana** [nextcloud/spreed#3131]
## Steps to reproduce
1. Create a group with some users (disabled and not disabled)
2. Start a new conversation in Talk
3. Added group created in Step 1.

### Expected behaviour
The ideal behavior would be:

  1. "Group" is added and can be removed
  2. Only the enabled users are added to the conversation

### Actual behaviour
All users in the group, both enabled and disabled are added individually to the conversation.
To remove the users in the group, each user has to be removed individually.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 18.04.4

**Browser name:** Firefox

**Browser version:** 74.0

## Talk app

**Talk app version:** 7.0.2
**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 18.04.4

**Web server:** Apache

**Database:** MySQL 5.7.29

**PHP version:** 7.3.15

**Nextcloud Version:** 17.0.3

**List of activated apps:**

<details>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.1
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.2.0
  - dav: 1.13.0
  - deck: 0.8.0
  - external: 3.4.1
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.5
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.3
  - metadata: 0.11.1
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - richdocuments: 3.5.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.3
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - drawio
  - encryption
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - onlyoffice
  - polls
  - support
  - tasks
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "s3-us-X-X.amazonaws.com",
                "use_ssl": true,
                "region": "us-X-X"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logtimezone": "America\/Indianapolis",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "token_auth_enforced": true,
        "skeletondirectory": "",
        "maintenance": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "theme": ""
    }
}
```
</details>

**Comment by nickvergessen** [comment]
Yeah, so tracking group memberships is a topic in #1329 

And as for adding disabled users, it's the same with group file shares. the only difference is you don't see them there, so I would say it's the expected behaviour for now until the behaviour of #1329 will take care of it.

**Comment by asadana** [comment]
@nickvergessen Thanks for the quick reply and clarification, I'll track #1329.
