### ISSUE TITLE
Use Picture-in-Picture mode for video calls

### ISSUE THREAD

**Issue by David-Development** [nextcloud/spreed#3136]
**Is your feature request related to a problem? Please describe.**
When talking to someone using video chat while watching netflix together, there is currently no way of seeing the other person. For example the native Skype App is showing an overlay when the Skype Window is not focused. 

**Describe the solution you'd like**
Chrome introduced the Picture-in-Picture mode in Version 70. For now it is only supposed to be used for Videos. However I recently discovered, that it is possible to show for example your webcam feed in it as well. [Blog Entry](https://css-tricks.com/an-introduction-to-the-picture-in-picture-web-api/#article-header-id-5) / [Codepen Example](https://codepen.io/ayoisaiah/pen/MWWGOKq)

Therefore it would be great if showing the other person in the picture in picture mode would be possible. 

**Describe alternatives you've considered**
Resizing the browser window and placing it on top of other windows. However the disadvantage is, that you'll still see the navigation bar, address bar, etc.. And you can't make it smaller than ~400px.

**Comment by Tachi107** [comment]
Strange, I can use Chromium's picture-in-picture for my friend's video without issues.
This still is a limitation, as I can select only one video at the time, and I can't see all my friends at the same time when in PiP

**Comment by PVince81** [comment]
for own local video we should probably disable it as it doesn't make much sense to watch self: https://github.com/nextcloud/spreed/issues/4754

it does make sense for the presenter's video

**Comment by nickvergessen** [comment]
Closing as PiP now works. See the following issues for follow ups:
#4754 
#4674
