### ISSUE TITLE
Document system requirements

### ISSUE THREAD

**Issue by PhrozenByte** [nextcloud/spreed#3139]
Nextcloud Talk currently has various undocumented system requirements, prerequisites and limitations that should be documented.

For instance, you can't run Nextcloud Talk on a Apache webserver with both HTTP/2 and the Apache `mpm_prefork` module - it will slow down Nextcloud Talk beyond usability. See #602 and #2211. You must use Apache `mpm_event` instead.

Furthermore Nextcloud Talk has some significant system requirements for both the server and client. Servers will face additional load - users on a dedicated server should just be aware of this fact, but more importantly, users of shared webhosters might do something illegal by installing Nextcloud Talk.

Clients will experience a massive resource usage when connecting multiple users at a time - affecting both CPU and RAM usage, as well as bandwidth usage. This effectively limits the number of concurrent users to about 5 people, depending on the client's abilities. That's due to technical limitations of WebRTC, but Nextcloud Talk should document this nevertheless.

The fact that you might need a TURN server is at least mentioned in the app's `README.md`, but without explaining what the TURN server is actually for and under which circumstances one is required. Neither STUN nor signalling servers are even mentioned nor explained what they are for.

Nextcloud Talk kinda is on a "either it works on the first try or simply forget about it" state regarding its docs right now... Very frustrating if it doesn't work on the first try. :unamused:

**Comment by nickvergessen** [comment]
> For instance, you can't run Nextcloud Talk on a Apache webserver with both HTTP/2 and the Apache mpm_prefork module - it will slow down Nextcloud Talk beyond usability. See #602 and #2211. You must use Apache mpm_event instead.

Yeah sorry I'm not too good with system administration, but all documentations to enable HTTP2 I ever saw mentioned switching to mpm_event, so I thought that is "clear".

> Furthermore Nextcloud Talk has some significant system requirements for both the server and client. Servers will face additional load - users on a dedicated server should just be aware of this fact, but more importantly, users of shared webhosters might do something illegal by installing Nextcloud Talk.

Actually the load is not increasing on the server. you just have 2 open connections per user, but being in a call doesn't add a lot of load to the server itself additional, as audio and video are peer-to-peer between the participants and never reach the server in first place.

> Clients will experience a massive resource usage when connecting multiple users at a time - affecting both CPU and RAM usage, as well as bandwidth usage. This effectively limits the number of concurrent users to about 5 people, depending on the client's abilities. That's due to technical limitations of WebRTC, but Nextcloud Talk should document this nevertheless.

Just now a PR came in to add this to the readme:
https://github.com/nextcloud/spreed/pull/3142

> The fact that you might need a TURN server is at least mentioned in the app's README.md, but without explaining what the TURN server is actually for and under which circumstances one is required. Neither STUN nor signalling servers are even mentioned nor explained what they are for.

We can't put everything in the readme, and the documentation at https://nextcloud-talk.readthedocs.io/en/latest/TURN/ explains at least STUN and TURN, what they are for and why one has a default and how you can install the other one.
The bottom of the page also explains the signaling server a bit which is currently only available with a subscription.

**Comment by nickvergessen** [comment]
Also we are more than happy to accept additions to the documentation.

* Create a new Markdown file in https://github.com/nextcloud/spreed/tree/master/docs
* Add it to the navigation in https://github.com/nextcloud/spreed/blob/master/mkdocs.yml#L18

And then it will be build automatically when the PR is merged :sunglasses:

**Comment by nickvergessen** [comment]
Should also check if https://docs.nextcloud.com/server/18/admin_manual/installation/system_requirements.html#mobile-apps is still up to date

**Comment by mario** [comment]
Still Android 5.x+ for Talk.

**Comment by nickvergessen** [comment]
Yeah, the Browser list at least is outdated
