### ISSUE TITLE
Font size of user menu is too big

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3143]
The font size of the user menu is just slightly bigger than the normal size, which looks very strange. It should be the regular text size:
![Talk sidebar user menu font size](https://user-images.githubusercontent.com/925062/77432468-61d90000-6dde-11ea-8587-c5c1b7e17343.png)
![Talk nav user menu](https://user-images.githubusercontent.com/925062/77432469-62719680-6dde-11ea-9330-b504deb0fc82.png)

cc @ma12-co – not sure if it’s only in Talk. If it is a Vue component issue, feel free to move it to that repository.

**Comment by nickvergessen** [comment]
I guess its a result of the `13px` font size experiment in talk?

**Comment by PVince81** [comment]
I've also observed a mix of font sizes in the conversation menu:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/277525/95463924-a773a980-0979-11eb-8dc2-672bab62a6a6.png">

The action buttons with checkboxes have a font-size of 15px but the other action buttons only have font-size 13px.

**Comment by ma12-co** [comment]
@PVince81 I created a new issue about that. 
@jancborchardt on the latest master the  user menu font size looks ok

![Screenshot from 2020-10-08 15-38-39](https://user-images.githubusercontent.com/26852655/95466245-6cbf4080-097c-11eb-8440-0eb3973521a4.png)
