### ISSUE TITLE
Issues with Video calls app not spreed.me

### ISSUE THREAD

**Issue by hevisol** [nextcloud/spreed#315]
Hello,

I guess I was being confusing with my first entry and was giving log information which was related to the spreed.me app. That application is working, and that cool, but your guys' app looks much better and the issue that I am having probably more toward the config of the video call app settings i believe as both the spreed.me app and the video calls app are using the same spreedme server.

The issue is I can conduct a video conference no problem, however no matter what device and what browser I use that has the nextcloud screen sharing app made available to it ( so any linux, windows, mac device using either chrome or firefox) will not show me the conputer icon to which we can screen share applications or the screen. 

The server is freebsd 11 running nextcloud 11 and running the video calls 1.2.0. I do not get any error info from the spreed server logs or withing nginx or php so if further information is needed ( im sure that there will be) if you could give me some guidance on how to open up more verbose debugging in efforts to fix this issue.

**Comment by Ivansss** [comment]
Hi @hevisol ,

I see the problem now 😄 

This app does not need the spreed-webrtc server running on your instance.
You just need to install this app and everything will work out of the box.

Screensharing feature was introduced in version 2.0 of this app. 
This version only runs in Nextcloud 12.

You can update your Nextcloud instance to the Beta release of Nextcloud 12 or wait to the official release of Nextcloud 12.
