### ISSUE TITLE
Adding Groups with same user to Talk Room leads to heavy load

### ISSUE THREAD

**Issue by MiMoV119** [nextcloud/spreed#3152]
## Steps to reproduce
1. Have two groups from LDAP with at least one user being in both groups
2. Add both groups to a new room
3. open the room in webinterface as the user being in both groups

### Expected behaviour
everything should be fine

### Actual behaviour
The server gets into heavy load. Nextcloud slows down for everyone until unusable.
I saw that the user is added twice to the oc_tak_participants table with the same user_id and room_id. Deleting the entries and adding one entry solves the problem. 

I could see one php and one database (postgres) process with heavy load on the webserver.
I had to kill the php-process on the webserver too. The postgres process ended with the php process.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox/Chrome

**Browser version:**

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** PostgreSQL 10.12

**PHP version:** 7.2.24

**Nextcloud Version:** 18.03

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by MiMoV119** [comment]
As a workaround I added a UNIQUE constraint for room_id and user_id to oc_talk_participants table.
This seems to prevent adding a user twice.

```
ALTER TABLE public.oc_talk_participants
    ADD CONSTRAINT oc_talk_participants_user_id_room_id_key UNIQUE (user_id, room_id);
```

**Comment by nickvergessen** [comment]
you just blocked guests from joining.

Which version are you running? I remember we fixed something in regards to this recently, so maybe you can check again with the latest Talk 8.0.5?

**Comment by MiMoV119** [comment]
After adding the constraint I tried again. Created a new room with adding both groups. Now there was no user added twice to the oc_talk_participants table.

I am using Talk 8.0.5

**Comment by MiMoV119** [comment]
I removed the constraint and tried again.
Now everything worked nice too. No double entries.
I retried several times. Also removed some people of a group and added the Group again. Everything ok now.
I have no idea why. I only added and removed the unique constraint to/from the table.
