### ISSUE TITLE
External link preview

### ISSUE THREAD

**Issue by mtadeunet** [nextcloud/spreed#3156]
**Is your feature request related to a problem? Please describe.**
When fast talking, like in brainstorms, there is the need to just push images, videos and text docs into the conversation. Most of the time, without the need to open the link just to see the idea. Actually, opening the link is most of the times a waste of time since we're just passing an idea or a concept.

**Describe the solution you'd like**
It would be a great deal to have external link previews, like in other messengers, where they load a thumbnail of the page, image or video.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by nickvergessen** [comment]
This is not (only) about internal items. Any link should show the OpenGraph Information when available.

**Comment by jakobroehrl** [comment]
yes sure, but maybe it's an easy step to start with internal link because there we have previews already

**Comment by nickvergessen** [comment]
Just as a summary. We are currently facing the decision whether this should leak/violate the privacy of the server or the users.
Either the clients do the request then their IP+ is leaked to the server, or the Nextcloud server proxies it but then its IP+ is leaked.

So it might be necessary to allow admins to specify if the nextcloud server can be used as a proxy and at the same time a user option is needed as you can use this to track reading.

**Comment by CarlSchwan** [comment]
Ideally, this needs to be done on the server and as soon as the message is sent, to make sure this can't be used for read-tracking. But this is tricky to implement and there are many possible pitfalls.

One of them affected Mastodon, that had the problem that then a popular account was sending a link, the preview ddos-ed the URL since many Mastodon instances were suddenly doing a request for a preview. See https://github.com/mastodon/mastodon/issues/4486 for context

**Comment by come-nc** [comment]
> Just as a summary. We are currently facing the decision whether this should leak/violate the privacy of the server or the users. Either the clients do the request then their IP+ is leaked to the server, or the Nextcloud server proxies it but then its IP+ is leaked.
> 
> So it might be necessary to allow admins to specify if the nextcloud server can be used as a proxy and at the same time a user option is needed as you can use this to track reading.

I would say it makes the most sense to leak the server IP and cache it server side, as this leaks the least information (the number of readers and the time of reading is not leaked, only the time of posting).

**Comment by webagroprom** [comment]
What stage is the development of this feature at?
In what version will the preview of external links in the conference appear?

**Comment by webagroprom** [comment]
> This is not (only) about internal items. Any link should show the OpenGraph Information when available.



> Just as a summary. We are currently facing the decision whether this should leak/violate the privacy of the server or the users. Either the clients do the request then their IP+ is leaked to the server, or the Nextcloud server proxies it but then its IP+ is leaked.
> 
> So it might be necessary to allow admins to specify if the nextcloud server can be used as a proxy and at the same time a user option is needed as you can use this to track reading.

//

What stage is the development of this feature at?
In what version will the preview of external links in the conference appear?

Is it possible to independently implement this function without waiting for a full-fledged update of the platform?

**Comment by jancborchardt** [comment]
This was implemented by @juliushaertl https://github.com/nextcloud/spreed/pull/7822 :)

**Comment by jancborchardt** [comment]
Or should this be kept open for video previews? @nickvergessen your call, or if it should be a separate issue to focus on what’s left.

**Comment by nickvergessen** [comment]
No, all fixed. Anything new will come in with a lib update and should come without bigger todos on our side.
