### ISSUE TITLE
Can't leave the video calls app

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/spreed#316]
## Steps to reproduce
1. open nc and login
2. open the spreed-videocallapp
3. start a call
4. end it
5. klick to files or a other app in the menu
6. nothing happens

### Expected behaviour
you should get to the app you wanted to

### Actual behaviour
You stay in the videoapp and have to reload the page manually

## Browser
firefox 53, linux and windows
**Microphone available:** both, happened on different machines

**Camera available:** no

**Operating system:** Win 10, Ubuntu 16.04

**Browser name:** Firefox 

**Browser version:** 53

### Browser log
after I click to files that happens:
<details>

```
Die Verbindung zu https://<domain>/index.php/apps/spreed/messages?requesttoken=W9gjc2L26ImzHcTtQ9VwCxS7i43SuKRm6AjhtFLVeMw%3D%3AM7JOMgqxgszgKIaMdp0cYlX0yvXlyJcVklLK1mejKfo%3D wurde unterbrochen, während die Seite geladen wurde.  merged-template-prepend.js:3943:15
GET 
https://<domain>/index.php/apps/files/ [HTTP/1.1 200 OK 73ms]
Kopfzeilen
Antwort
Cookies
Cache-Controlno-cache, no-store, must-revalidateConnectionKeep-AliveContent-EncodinggzipContent-Length6980Content-Security-Policydefault-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-dE16OXFJS3UvNDdaMEg1czBNb0ZqNm9MbVlVUlJpN2NpU28zRzU5bnQyaz06M0thUTZlcnBsY3VLNVR3TjVZSnA1dXRFMlAwbU5oMnY4M0FjZWFvUjVsOD0=' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self';frame-src 'self';child-src 'self'Content-Typetext/html; charset=UTF-8DateWed, 10 May 2017 06:14:55 GMTExpiresThu, 19 Nov 1981 08:52:00 GMTKeep-Alivetimeout=5, max=97Pragmano-cacheServerApache/2.4.10 (Debian)VaryAccept-EncodingX-Content-Type-OptionsnosniffX-Download-OptionsnoopenX-Frame-OptionsSAMEORIGINX-Permitted-Cross-Domain-PoliciesnoneX-Robots-Tagnonex-xss-protection1; mode=block
Accepttext/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8Accept-Encodinggzip, deflate, brAccept-Languagede-AT,en;q=0.5Connectionkeep-aliveCookienc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; ocrr64durf5y=0gn57e7k6hnpsaunp1d2ck5oc6; oc_sessionPassphrase=jNkdTcr1bSRI6bTac9GUafqvFRNEp0H757Nh5E45aAi%2F%2FHuiWXNIKbOQlulelv%2F3fC8y0Gi58g%2FnPuLwcwq0FzeZSl2T6BHAdOuCXP0VwKV8q6Xh0YPV70nYiSbXSI7S; ocmpp85hae4h=2pvlfeh7q3pv8uohct1q3ud0a4DNT1Hostonlycloud.r-d-w.netUpgrade-Insecure-Requests1User-AgentMozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

DELETE 
XHR 
https://<domain>/index.php/apps/spreed/api/leave [HTTP/1.1 200 OK 57ms]
Kopfzeilen
Antwort
Cookies
Aufrufliste
Cache-Controlno-cache, no-store, must-revalidateConnectionKeep-AliveContent-Length2Content-Security-Policydefault-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-Y1RaLytGcDNYa0hrWjBYR2hRMUgvYmNldlpvS0dhVXdSUkt1UEJzVkY4Yz06R1Z3U3VUSXdOQVMzVWdlbnNFVXJsUFpSL09JOWFaWkRQMGlGWGk1alJ2RT0=' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'Content-Typeapplication/json; charset=utf-8DateWed, 10 May 2017 06:14:56 GMTExpiresThu, 19 Nov 1981 08:52:00 GMTKeep-Alivetimeout=5, max=96Pragmano-cacheServerApache/2.4.10 (Debian)X-Content-Type-OptionsnosniffX-Download-OptionsnoopenX-Frame-OptionsSAMEORIGINX-Permitted-Cross-Domain-PoliciesnoneX-Robots-Tagnonex-xss-protection1; mode=block
Accept*/*Accept-Encodinggzip, deflate, brAccept-Languagede-AT,en;q=0.5Connectionkeep-aliveCookienc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; ocrr64durf5y=0gn57e7k6hnpsaunp1d2ck5oc6; oc_sessionPassphrase=jNkdTcr1bSRI6bTac9GUafqvFRNEp0H757Nh5E45aAi%2F%2FHuiWXNIKbOQlulelv%2F3fC8y0Gi58g%2FnPuLwcwq0FzeZSl2T6BHAdOuCXP0VwKV8q6Xh0YPV70nYiSbXSI7S; ocmpp85hae4h=2pvlfeh7q3pv8uohct1q3ud0a4DNT1Hostonlycloud.r-d-w.netOCS-APIREQUESTtrueUser-AgentMozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0X-Requested-WithXMLHttpRequestrequesttokenW9gjc2L26ImzHcTtQ9VwCxS7i43SuKRm6AjhtFLVeMw=:M7JOMgqxgszgKIaMdp0cYlX0yvXlyJcVklLK1mejKfo=

Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.  (unbekannt)

        
```

</details>

**Comment by nickvergessen** [comment]
You are missing some important information in your report:
1. Which version of nextcloud are you using?
2. Which version of the app are you using?
3. Are you using apache or nginx?
4. Did you manually remove the URL from the browser logs, or are they really `https:///index.php/apps/spreed/`
5. Are you having a proxy in place?

**Comment by devz3r0** [comment]
Hi,

I am using Nextcloud 12 Beta 2 as set in the title, the issue was already in beta 1 too,
The App is the version, which got issued by nextcloud, using apache 
I replaced my domain whith "<domain>" it looks like git can't handle that correctly so it got removed or something.
No I have no proxy.

**Comment by nickvergessen** [comment]
can you test with the newest version? We changed some stuff in the meantime and it works perfectly fine for me.

**Comment by devz3r0** [comment]
I just retested it, it just stalls on the same place. 
I did a retest with onlyoffice, there i can switch to the files. 
Current Browser: 53.0.3 (64-Bit) (ubuntu)

It even doesn't switch back if I refuse the permission to use my audio/video devices.

BTW I have updated NC to the final version.

**Comment by DJCrashdummy** [comment]
i'm pretty sure i notice the same behavior for a while now! therefore my bug-report, hopefully it helps.

## Steps to reproduce
1. open the app in nextcloud 12 (or nextcloud 11; BOTH are affected!) and start a video call
2. now try to continue working with nexcloud, so click anything else, an other app or even the settings, help or logout...

### Expected behaviour
the GUI should continue working as known and expected

### Actual behaviour
the GUI gets a kind of stuck...
1. the mic & cam gets deactivated
2. the URL is changed correctly to the chosen app or menu
3. but than nothing happens: the browser-icon stays the camera, the window-/tab-name is still "Video Calls - Nextcloud" and the wheel instead of the chosen app-icon (or menu-icon) keeps spinning forever
4. when hovering over other items the GUI still "works" so far that the highlighting and (in NC12) the names of the apps are displayed
5. but clicking anywhere does not have any effect. (also the opened menu stays open)
6. the only way to continue is to reload the page manually

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Linux Mint 17 (based on Ubuntu 14.04)

**Browser name:** Firefox

**Browser version:** 54.0 (64-Bit)


## Spreed app

**Spreed app version:**
NC 11.0.4: 1.2.0
NC 12.0.1: 2.0.1
NC 12.0.2: 2.0.1

**Custom TURN server configured:** no

**Custom STUN server configured:** no


## Server configuration

**Operating system:** Linux 3.13.0-128-generic Ubuntu x86_64
(i think to remember my hoster told me it is Ubuntu 14.04)

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.6.33

**PHP version:** 7.0.20-nmm1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dom
 - hash
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - json
 - mbstring
 - posix
 - Reflection
 - session
 - standard
 - shmop
 - SimpleXML
 - soap
 - exif
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - propro
 - raphf
 - http
 - mysqlnd
 - PDO
 - curl
 - fileinfo
 - gd
 - gender
 - gmp
 - htscanner
 - imagick
 - imap
 - interbase
 - intl
 - ldap
 - mailparse
 - mcrypt
 - mongodb
 - mysqli
 - OAuth
 - odbc
 - pdo_dblib
 - pdo_mysql
 - PDO_ODBC
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - pspell
 - recode
 - SourceGuardian
 - sqlite3
 - tidy
 - xsl
 - ionCube Loader
```
</details>

**Nextcloud Version:** 11.0.4 (stable) - 11.0.4.1
**AND** 12.0.1 - 12.0.1.5
**AND** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0.4: updated from pervious 11.0.x versions
12.0.1: no, a plain installation
12.0.2: updated just from 12.0.1

**Where did you install Nextcloud from:** hoster-script

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**

<details>
        <summary>App-List</summary>

```
activity
bruteforcesettings
calendar
comments
contacts
dav
federatedfilesharing
federation
files
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
logreader
lookup_server_connector
nextcloud_announcements
notifications
oauth2
password_policy
provisioning_api
serverinfo
sharebymail
twofactor_backupcodes
updatenotification
user_external
workflowengine

apporder
checksum
files_downloadactivity
files_opds
files_reader
keeweb
metadata
notes
qownnotesapi
quota_warning
socialsharing_email
spreed
tasks
telephoneprovider

**Disabled:**
admin_audit
systemtags
encryption
files_external
user_ldap
theming
survey_client

ransomware_protection
```
</details>

**Nextcloud configuration:**

<details>
        <summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.mydomain.tld',
  ),
  'datadirectory' => '/www/htdocs/server/nextcloud/data',
  'overwrite.cli.url' => 'http://cloud.mydomain.tld',
  'dbtype' => 'mysql',
  'version' => '12.0.2.0',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'xxxxx_',
  'mysql.utf8mb4' => false,
  'dbuser' => 'dbuser',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'default_language' => 'de',
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.mydomain.tld:993/imap/ssl/novalidate-cert/readonly}INBOX',
        1 => 'mydomain.tld',
      ),
    ),
  ),
  'updater.release.channel' => 'production',
  'loglevel' => 2,
  'customclient_desktop' => 'https://nextcloud.com/install/#install-clients',
  'customclient_android' => 'https://f-droid.org/packages/com.nextcloud.client',
  'customclient_ios' => 'https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/www/htdocs/server/nextcloud/apps_neu',
      'url' => '/apps_neu',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/www/htdocs/server/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'theme' => '',
  'filesystem_check_changes' => 1,
  'tempdirectory' => '/www/htdocs/server/nextcloud/tmp/',
  'maintenance' => false,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\FB2',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\OpenDocument',
    8 => 'OC\\Preview\\StarOffice',
    9 => 'OC\\Preview\\MSOfficeDoc',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
  ),
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

**Comment by nickvergessen** [comment]
Seems to happen here as well now. My browser console says:
```
Die Verbindung zu https://cloud.nextcloud.com/apps/spreed/messages?requesttoken=... wurde unterbrochen, während die Seite geladen wurde.  merged-template-prepend.js:3956:15
Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.  (unbekannt)
```

**Comment by DJCrashdummy** [comment]
from my point of view the title is a little bit misleading, since NC12 (stable) and NC11 are effected.

**Comment by DJCrashdummy** [comment]
can #225 be somehow related?
it sounds partly similar, but according to my hoster my server is using http2 since i also ran into this http2-problem (https://help.nextcloud.com/t/calendar-sync-with-thunderbird-lightning-broken-due-to-apache-2-4-http2/1802) last year.

**Comment by nickvergessen** [comment]
Does not happen with current master anymore because of how we refactored the signaling
