### ISSUE TITLE
Discussion: Etherpad Integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#3174]
[Etherpad](https://etherpad.org/) can already be added to Nextcloud using the [Ownpad application](https://github.com/fuerst/embed-etherpad-lite) and would make an excellent integration for Talk!  It is similar to Text application, but includes a number of additional features by allowing you to collaborate on documents and spreadsheets requested in #1167.
* It also includes very basic and useful [chat functionality](https://www.npmjs.com/package/ep_real_time_chat)
* [WebRTC integration is already possible](https://github.com/ether/ep_webrtc)
* [Click here for the Document Example](https://pad.riseup.net/p/nextcloudtalk)
* [Click here for the Spreadsheet Example](https://ethercalc.org/7tq1siiupkes)

See #3173 and the [etherpad-lite Github](https://github.com/fuerst/embed-etherpad-lite)

**Comment by nickvergessen** [comment]
We are currently working on bringing the Nextcloud Viewers into Talk.
So when the Ownpad application implements itself as a viewer it will work automatically.

At this point it is very unlikely for us to invest more time into adding support for a third party editor, so I will close this, but as always if you get this working feel free to shot in a PR
