### ISSUE TITLE
User lost in conversation

### ISSUE THREAD

**Issue by jovab** [nextcloud/spreed#3175]
## Steps to reproduce
as a non-profit organization we want to use talk to keep in touch with our employees and clients. however, we notice that user connection is lost. 1 to 1 conversations are going well. From 3 users, the connection with 1 or more users is lost. It is therefore not always possible to get back into the conversation.
Is this a known problem? Any idea what causes this?
Testen in several browsers Ans systems
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Did you configure a TURN server? And also how is the network situation on your server and the clients?

**Comment by nickvergessen** [comment]
Closing as per above
