### ISSUE TITLE
Problems after Upgrade 16 to 18 Error: "Could not find initial state circles_enabled of talk"

### ISSUE THREAD

**Issue by theDyingMountain** [nextcloud/spreed#3176]
I get the following JS Errors after upgrading from Nextcloud 16 to 18:

- `Error: "Could not find initial state circles_enabled of talk"`
- `TypeError: "e.searchResultsUsers is undefined"`

Also I can't select contacts to start a call or chat.

**Comment by nickvergessen** [comment]
Sounds like your backend files where not updated correctly. Try to manually remove all files from apps/spreed/ and upload the files from the latest release by downloading it here https://apps.nextcloud.com/apps/spreed

**Comment by theDyingMountain** [comment]
Unfortunately, that didn't help... Can it be caused by some old appdata in the datadirectory?

**Comment by theDyingMountain** [comment]
The Problem occurs again on a fresh install of nextcloud 18.0.3 and the latest spreed app. Please reopen the ticket.
