### ISSUE TITLE
No Screensharing even though using Firefox 53.x

### ISSUE THREAD

**Issue by RiSK1979** [nextcloud/spreed#318]
## Steps to reproduce
1. USe Firefox to create a conference call in the spreed / video calls app
2. Invite someone into the conference
3. once he joined, try to click the share screen button

### Expected behaviour
Firefox should share your screen with all participants of the call

### Actual behaviour
Spreed insists, that my browser doesn't support sharing my screen.

## Browser
Tested with both up-to-date Firefox 53.0.2 stable and Firefox 54 alpha2 (both 32 bit)

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Firefox

**Browser version:** Tested with both up-to-date Firefox 53.0.2 stable and Firefox 54 alpha2 (both 32 bit)

### Browser log

<details>
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
2.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->


**Operating system**: Not sure, used on a shared hoster

**Web server:** Apache

**Database:** MySQL 5.x

**PHP version:**
7.1

**Nextcloud Version:** 
12 beta2

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
No entries for this event (actually, no events for the whole day).
</details>

**Comment by Ivansss** [comment]
Do you see any errors in your browser console?

> Spreed insists, that my browser doesn't support sharing my screen.

Could you please tell us what the notifications says?

**Comment by RiSK1979** [comment]
Screenshot of the message attached:
![screenshot](https://cloud.githubusercontent.com/assets/4215448/26096470/a17f0022-3a21-11e7-90a7-b0c2f62cced3.jpg)

Bowser console log:
[browser-console.txt](https://github.com/nextcloud/spreed/files/1003688/browser-console.txt)

**Comment by Ivansss** [comment]
`https` is required for screen-capturing in Firefox and Chrome.

**Comment by RiSK1979** [comment]
Ok, good to know, but wouldn't be a hint on this better, than a message that my browser won't support screensharing. Because 1.) it's not a browser issue 2.) this message doesn't give you any hint on what's actually causing the issue.

**Comment by Ivansss** [comment]
@RiSK1979 yes, you are right.
We should think about a better feedback for this case.
Right now, FF automatically detects this case and returns that screensharing is not supported. That's why we show that notification.
https://github.com/nextcloud/spreed/blob/master/js/app.js#L235
