### ISSUE TITLE
Open Broadcaster Software (OBS), RTMP, FTL, and SRT Support

### ISSUE THREAD

**Issue by EliterScripts** [nextcloud/spreed#3182]
I think this feature would dramatically increase the value of Nextcloud and Nextcloud Talk, as Nextcloud Talk would have professional features (when combined with OBS), that would allow people to host and organize professional events, with many scenes, transitions, and people involved.

Furthermore, I will refer to "streaming" as streaming using a streaming software, such as OBS.

**Is your feature request related to a problem? Please describe.**
**An introduction to OBS (for those who don't know):**
OBS, or Open Broadcaster Software, is software that allows you to stream and/or record video/audio, very flexibly. It has abilities to record your screen, have multiple video/audio inputs, and switch between scenes (for example, "waiting screen" with music, disable screensharing while talking, playing a game with music, any combination of scenes), have video inputs displayed on top of each other, adjust sizes, many things. The cool part: you can do it all mid-recording or mid-stream. Here is the website: https://obsproject.com/ and the github: https://github.com/obsproject/obs-studio

**Problem:**
I would like to stream directly from OBS, and use that as my meeting audio/video input. Of course, any other broadcasting software could work, because OBS doesn't make their own protocol. According to https://obsproject.com/wiki/Streaming-With-SRT-Protocol , OBS uses the SRT protocol, and after talking to people on their IRC channel, they also support RTMP, FTL, and SRT. So what I am really asking, is can we open RTMP/FTL/SRT as an alternative interface for audio/webcam for meeting attendees?

NOTICE: I am a Ubuntu, Linux user, and have not looked at any Windows options, or any other option outside of Ubuntu/Linux.

Current workarounds include outputting OBS video into a faked dummy video device, then using the dummy video device in the browser, to then use the camera option in Nextcloud. However, I have not found this to work at all.
**VirtualCam Current Workaround:**
I know OBS has a plugin called VirtualCam (https://obsproject.com/forum/resources/obs-virtualcam.539/ and https://github.com/CatxFish/obs-virtual-cam ) however, that is very hacky, not officially supported by OBS, and since it is a plugin, introduces a security risk. It is also ONLY supported on Windows.
**v4l2loopback Current Workaround:**
There is also another plugin called v4l2sink (https://github.com/CatxFish/obs-v4l2sink ), which "works" on Linux, and only has an easy-to-install option for Ubuntu/Debian (because the release only has a .deb). It is also very difficult to use, I have not been able to get the dummy video device to show up on Chromium, and when I use Firefox, it shows up with the words "dummy", but when I get into the Nextcloud call using that device, Nextcloud's interface doesn't even let me use the "camera". It also doesn't have an audio option for getting audio from OBS.

**Describe the solution you'd like**
Instead of screwing around, forcing a "square peg into a round hole", I would like native OBS streaming support, as an option, in place of traditional audio/video from a microphone/webcam.

**Getting This Done**
So I would like to look into researching this problem, to actually be a part of the solution, and not just the suggestion.

What would you guys suggest for hosting an SRT/RTMP/FTL server?

I imagine the steps for putting this together are (backend1):
1. Figure out how to create a streaming server (compatible with OBS)
2. Figure out how Nextcloud receives audio/video from users
3. Figure out how to intercept Nextcloud's reception of audio/video from users
4. Intercept audio/video from a user that is streaming, and replace it entirely

Then, or do this simultaneously (frontend1):
1. Create a "streaming" icon (could be OBS's logo--it's probably open sourced)
2. Place "streaming" icon next to user's microphone, screenshare, and video icons
3. Create panel that pops-up when "streaming" button is pressed
4. Put "Create Key" button on streaming pop-up panel
5. Show streaming key on streaming pop-up panel
6. Copy button for streaming key
7. Button for disabling streaming
8. Display status of streaming ("streaming right now via 3rd-party software", "not streaming via 3rd-party software" for example) in different colors for each case
9. Button for closing out of streaming pop-up panel
10. Show "streaming" icon lit a different way, when streaming/not streaming
11. Javascript - check if user CAN stream
12. Javascript - don't show streaming icon, if cannot stream; show user streaming icon if can stream
13. Javascript - repeated checks, or open websocket to see streaming capabilities and info
14. Javascript - send server enable/disable streaming
15. Javascript – if user is streaming, disable microphone/camera
16. Javascript - if can/cannot stream changes, visually reflect those changes, notifying the user
17. Javascript - request NEW streaming key
18. Javascript - request streaming CURRENT key
19. Javascript - if changes to stream key, visually reflect those changes, notifying the user
20. Javascript - display new streaming key, if changed by the server
21. Javascript - copy streaming key (if user clicked button)
22. Javascript - check server if streaming or not
23. Javascript – visually show if user is streaming
24. Javascript – close streaming pop-up panel when “close” button is pressed

Steps for backend2 (after backend1 and frontend1 are done):
1. Make server configuration for “can stream” or “cannot stream” (either one or the other)
2. Listen for Javascript requests (individually or through websocket)
3. Respond with “can stream” to client (correlates with frontend1 #11)
4. Create stream key database/table
5. Create function for creating stream key (using CSPRNG, then checking for key duplicates)
6. If “request NEW streaming key”, do #7
7. Associate chatroom ID and user ID with stream key
8. If stream software sends a stream using stream key within table from #4, intercept video/audio, using method from backend1 #4

Then, we go on to further locking it down, by having a front-end and back-end for the server/chat administrator, to control who can use streaming.

**Authentication**
As for authentication, I think we should generate a random key when the user wishes to stream (the key should be generated by a CSPRNG - Cryptographically Secure Pseudo Random Number Generator - such as OpenSSL), for each user, each meeting room, and the key should only be active for either 24 hours after the key was requested by the user (regardless if the user is still streaming), or 6 hours since a streaming client connected. There should be a warning when the key is generated about the key expiry. I think the key should be no less than 12 bytes long, probably longer. I'm not sure if we should present it to the user as hexadecimal (which is easy-to-read, easy-to-type, longer), or base64 (shorter). But, we're probably going to have them copy-and-paste.
This should be for security purposes, since I don't believe we should be entering passwords, to be stored in plaintext, outside of the Nextcloud interface. It increases attack surface.

**Chatroom Administration**
I'm not really sure how Nextcloud ranks people in the chatroom, but I think there should be a specific option in the chatroom, for whoever administrates it, "allow anyone to stream[info]", "allow moderators to stream[info]" "allow specific people to stream[info]", with the info talking about OBS, and the protocol behind it that Nextcloud Talk supports.

**Nextcloud Talk Server Adminstration**
On the Nextcloud server, I think the server administrator should have the option to turn off streaming entirely, enable streaming on specific chatrooms, enable streaming for specific users, enable streaming from specific IP addresses, not allow streaming from guests (i.e. people that joined without logging in, on a public chatroom), set streaming time limits for guests, set total server limit of amount of guests that can stream, set total amount of people (guests and users) that can stream at once, purge all current streaming keys, maybe more.

**Comment by EliterScripts** [comment]
Just a little info on SRT: https://www.youtube.com/watch?v=m1FABQtAjgU

**Comment by EliterScripts** [comment]
I sent an email to info@srtalliance.org , and got their PDF on SRT from https://www.srtalliance.org/srt-deployment-guide/ , but I want to see if this group would be willing to take a look into implementing SRT into Nextcloud Talk.

**Comment by KeithCu** [comment]
This is a great idea, I just wanted to add that in addition, in many cases, people want to have just one person's audio, and video and the rest just want to text chat, like in a teaching situation. In this case, things should scale much better since you are only sending one stream out. Maybe Talk does this today?

**Comment by nickvergessen** [comment]
Not today and it's unrelated to this issue, but we might have it in the future

**Comment by boombatower** [comment]
[Using OBS video as webcam input can be achieved more generally than just for nextcloud](https://blog.boombatower.com/2020/04/14/greenscreen-webcam-on-linux) via https://github.com/CatxFish/obs-v4l2sink and an audio loopback sync if you want to do things to your audio as well.

**Comment by brtptrs** [comment]
The Nextcloud high performance backend already includes janus. As far as I can tell Janus supports webrtc streaming. How difficult would it be to use the Talk front end to get OBS to connect to the janus server?

**Comment by finnschi** [comment]
I just want to voice my voice my support of this "ticket" - it would be amazing to bypass the browser when streaming as previsouly mentioned for things like teaching.

**Comment by boombatower** [comment]
As of [December of 2020](https://github.com/obsproject/obs-studio/releases/tag/26.1.0) the virtual camera output is now available from base OBS on Linux, Mac, and Windows. The loopback device (as noted above) worked great for 3+ years and the new built-in works as well. Unless there is some specific feature desired the "virtual camera" is the way to go. It is flexible and works with all conferencing software  since it requires no special support. This also works today.

I am curious as to the teaching use-case. If the teacher enables video (with or without the virtual camera) and everyone else disables theirs what exactly needs to be implemented? Any features like disabling all video expect one person seems rather unrelated to the feature request.

The issues about the virtual device showing up are resolved with the following two options to the loopback device (as noted in my post): `exclusive_caps=1 card_label="Green-screen Webcam"` (where the label can be anything).

**Comment by nickvergessen** [comment]
Thanks s lot!
So we can close this 👍
