### ISSUE TITLE
Notifications, notifications everywhere

### ISSUE THREAD

**Issue by pasouf** [nextcloud/spreed#3191]
**Is your feature request related to a problem? Please describe.**
Without a Talk software client for macOS/GNU-Linux/Windows, it's always frustrating to have to go in the talk "app" of nextcloud to see if your talk conversations has had updates.

**Describe the solution you'd like**
I'd expect the following notifications
- a notification on the "talk" icon of nextcloud (with a number of unread messages, or an "@" when your name was "quoted").
- a notification on the browser tab that runs Talk.
- a notification on the icon of your browser in the "taskbar" (don't know if it's even possible).

**Describe alternatives you've considered**
Regarding the notifications in the browser tab, maybe that should be a Nextcloud feature after all, and about the bell on the right it is really not helping on that very matter.

I wanted to try to develop a software client based on electron like Mattermost for example, but I'm really not that fluent in any of the technologies involved...

**Comment by nickvergessen** [comment]
That all will work soon. It worked before and was broken by changes in browser APIs.
Nextcloud 18.0.4 will fix it with https://github.com/nextcloud/notifications/pull/608

**Comment by nickvergessen** [comment]
Closing as per above
