### ISSUE TITLE
One to many video / audio streams

### ISSUE THREAD

**Issue by KeithCu** [nextcloud/spreed#3203]
NextCloud Talk has known scalability issues because in a conversation. it sends everyone's video / audio to everyone else. For group meetings, that is what people want.

However, there are scenarios of teaching, webinars, etc. where people would want just one audio / video stream that the rest receive, and everyone else is just typing text. When the student joins the call, it wouldn't send their audio/video anywhere, just start receiving the audio/video, from the teacher.

That should also allow one server to scale out to many more users.

I will investigate hacking NextCloud Talk to support this on my instance, but it would be great to have this as a feature. It should be pretty easy to do since it's mostly disabling code.

**Comment by brtptrs** [comment]
It would be great if this could be backported to NC18, we need this feature urgently.

**Comment by jospoortvliet** [comment]
> It would be great if this could be backported to NC18, we need this feature urgently.

Can you please not post such replies. The kind of me too things - you're entirely welcome to share those on twitter or on the forums, but here we don't need that. If you need this in your company, ask the support team. If you need it at home, note that in the forums.

**Comment by brtptrs** [comment]
Sorry, but I am one of your paying for Talk-Customers. And have been for many years.

**Comment by nickvergessen** [comment]
> Sorry for the noise, but we are one of your paying Talk-Customers. And have been for many years.

Woopsie @brtptrs then get in contact with your account manager to speed things up 😎

**Comment by jospoortvliet** [comment]
> > Sorry for the noise, but we are one of your paying Talk-Customers. And have been for many years.
> 
> Woopsie @brtptrs then get in contact with your account manager to speed things up

yes, please use the support channel or your account manager for this, then we know! Sorry, it is hard to keep track of who's a customer on github ;-)
