### ISSUE TITLE
Support for Kurento or OpenVidu as a backend for signalling?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/spreed#3209]
**Is your feature request related to a problem? Please describe.**
Currently Nextcloud Talk as an Open Source project only supports a handful of participants at best which puts it at a huge disadvantage over Bigbluebutton and Jitsi Meet. There is only a proprietary HPB available starting at 5000€ and upwards.

**Describe the solution you'd like**
To make Nextcloud more useful and in line with the Open Source approach it would be good to have an alternative to the proprietary and expensive HPB. OpenVidu and Kurento (both Open Source) would be interesting alternatives for this purpose:

https://openvidu.io/docs
https://doc-kurento.readthedocs.io

**Comment by nickvergessen** [comment]
I think there is a misunderstanding. Our "Signaling server" is basically a SFU with some shortcuts to send signaling messages. the signaling party is not too difficult (details can be reverse engineered from the clients and https://nextcloud-talk.readthedocs.io/en/latest/standalone-signaling-api-v1/ should help a lot as well).

But the SFU part is actually the more important part helping to make it work for more people in one call.
If you find a freely available SFU or even MCU to plugin in, sure I will accept a pull request for that as it would benefit a lot of people. But a sole signaling server will not help as much.

**Comment by e-alfred** [comment]
Sorry, I might indeed miss a few things surely. Kurento Media Server is Open Source and has an integrated SFU and MCU so it seems like a good fit:

https://doc-kurento.readthedocs.io/en/6.13.0/user/about.html#kurento-media-server

OpenVidu is an SFU built on to of Kurento which should make it easier to integrate.

**Comment by danielegobbetti** [comment]
There is also a plugin by mozilla that turns Janus into an SFU https://github.com/mozilla/janus-plugin-sfu 

Could this be of any help?

**Comment by jospoortvliet** [comment]
Yeah, those could perhaps work and we'd accept a pull request of course.

**Comment by e-alfred** [comment]
So @ramezrafla made a fork of Talk that includes Bigbluebutton which is basically using Kurento as a base. Do you think this could be merged into the official Talk client as an alternative to the proprietary HPB?

Here is the repository:

https://github.com/ramezrafla/spreed-bigbluebutton

**Comment by gary-kim** [comment]
> So @ramezrafla made a fork of Talk that includes Bigbluebutton which is basically using Kurento as a base. Do you think this could be merged into the official Talk client as an alternative to the proprietary HPB?
> 
> Here is the repository:
> 
> https://github.com/ramezrafla/spreed-bigbluebutton

I just took a quick cursory look through the code and I would say no. It's not well integrated into Talk. As far as I can tell, it basically loads up an iframe of the BBB.

I'd prefer a solution that functions as signaling and an SFU/MCU and is well integrated.

To be clear, I am unaffiliated with Nextcloud GmbH. I also want a alternative to the HPB.

**Comment by ramezrafla** [comment]
@gary-kim 
Thanks for your comment.
I believe you are mistaken. Just like onlyoffice loads an Iframe and uses its client we do the same.

The BBB client is light years ahead of Talk. There is no reason to stick to Spreed’s API when one of the best (or even the best) open source solution exists. The only reason they are there is because of their relationship with NC. Otherwise another solution would have been picked. 

Try the BBB online demo and you’ll see. The Talk client is fundamentally weak.

Of course, we each have our applications. Our clients are picky and I can’t compete with Zoom with Talk, your mileage may vary.

**Comment by e-alfred** [comment]
> You have all the avatars at the bottom overlapping.

This will be hopefully fixed in the next major release https://github.com/nextcloud/spreed/issues/1056

Otherwise it is true that Talk needs a better footing if it wants to stand against Jitsi and BBB. A FLOSS MCU/SFU would be a major step in the right direction. That is why I created this issue in the first place.

> My expectation is that the low-cost of maintaining own servers or using BBB providers will eventually doom NC's own servers

I do not understand, Nextcloud is a selfhosted solution, what kind of "own servers" are you talking about? The vile move by Onlyoffice with their Open Source version was indeed a huge setback.

**Comment by e-alfred** [comment]
Somebody did it:

https://gitlab.com/powerpaul17/nc_talk_backend

**Comment by ramezrafla** [comment]
> My expectation is that the low-cost of maintaining own servers or using BBB providers will eventually doom NC's own servers

I meant that hosting your own BBB or paying a third-part would be cheaper than paying NC for their server

**Comment by ramezrafla** [comment]
> Somebody did it:
> 
> https://gitlab.com/powerpaul17/nc_talk_backend

Honestly, I wouldn't use a system like that for production. Maybe for private. But not with clients or enterprise.

**Comment by jospoortvliet** [comment]
Many scaling problems should be solved by 8.0.9, released last week - it adjusts quality based on the nr of participants, among other things. A typical network and hardware setup should handle 5-10 people.

The signalling back-end is now also open source, so you can give that a try.
https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/1

**Comment by e-alfred** [comment]
> The signalling back-end is now also open source, so you can give that a try.

Awesome move, this probably concludes this issue finally. Thanks for your help!
