### ISSUE TITLE
Improvement for the lobby screen

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#3210]
![Talk lobby](https://user-images.githubusercontent.com/925062/60385844-58f51100-9a8e-11e9-9ff3-9034e544c47f.png)

@ma12-co the idea was that _if_ the name is the default "Guest", you probably want to change it and we can directly show the input field. It wouldn’t need to show as input field if you already set a name. My only suggestions for that:
- We should call it "Your name" instead of "Display name" as that’s quite technical
- The input field could replace the current name and the edit button in place, especially

> Wow, that looks so different from what we have now...

Yeah – it’s rather bland at the moment. I’d still love for the mockup and spec to be followed a bit more:
- It looks much much better. We don’t necessarily need to have the dark background, but this standard blue header and the white content just looks so basic.
- Gives you feedback as to who you will be talking to – just like e.g. Hangouts does before joining
- Shows your own camera in case it’s a video call – also just like Hangouts
- Unclear what "waiting in the lobby" means. "Waiting for moderators to start the call" is clear and you know who to talk to if it does not start.
- Some other points in the spec as well – give it a read at https://github.com/nextcloud/spreed/pull/1926#issuecomment-506962798

_Originally posted by @jancborchardt in https://github.com/nextcloud/spreed/pull/3133#issuecomment-606502335_

**Comment by nickvergessen** [comment]
Closing this for now. We shouldn't show the video as the call is not starting immediately but you first enter the chat.
Asking the guest for a name already has a dedicated issue
And most of the other things are implemented by now.
