### ISSUE TITLE
High network latence prevents audio and video

### ISSUE THREAD

**Issue by timo12357** [nextcloud/spreed#3213]
### Steps to reproduce
1. Confirm that the B-subscriber is on a high latency, > 50 ms, connection
2. Invite B-subscriber to a Nextcloud Talk call
3. Watch the rolling icon until end of time

### Expected behaviour
The call should be connected and video and audio should be working despite the network latency, Everybody are now on webcalls due to Covid 19 and that increases network Latency. Talk should work also in a high latency environment.

### Actual behaviour
The video call fails, and a rolling icon is shown. Audio fails. Chat messages work.

## Server configuration detail

**Operating system:** Linux 2.6.32-042stab141.3 #1 SMP Fri Nov 15 22:45:34 MSK 2019 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.38

**PHP version:** 

7.2.29-1+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, libsmbclient, Zend OPcache, xdebug

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from old

**Where did you install Nextcloud from:** Automatic update

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.4
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - passman: 2.3.5
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - onlyoffice
 - richdocuments

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "38116.s.time4vps.cloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** true

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Server: Ubuntu 16.04, Clients Ubuntu 19.04

## Logs

<details><summary>Web server error log</summary>

```
Nothing related found
```
</details>

<details><summary>Nextcloud log</summary>

```
Nothing related found
{"reqId":"Kp2Xj7PGVAwSXtufmzvQ","level":2,"time":"2020-03-31T11:45:14+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"normalizing failed for \"xxxsenstivexxxremovedxxx.pdf\"","userAgent":"--","version":"18.0.3.0"}

```
</details>

<details><summary>Browser log</summary>

Nothing related found
</details>

Edit: Removed the copied text from the actual behavior.

**Comment by nickvergessen** [comment]
This sounds more like a missing TURN server.
Did you set one up?

**Comment by timo12357** [comment]
@nickvergessen Yes, we are using coturn. Video and audio work in 90% of the cases, but in 10% not at all. 
We tested this yesterday and found a clear correlation between high latency and failure to connect. Our engineer is working from home and sharing internet from his phone. From one side of the house he has low latency and the other high latency. The high latency connection fails. Text comes through, but video or audio not.

**Comment by nickvergessen** [comment]
Sorry to say, but "75ms" is not high latency. In germany you have to be  lucky to have that at all.

Mind to share a public conversation here, or send it to me via email (`<my github name>@nextcloud.com`)

**Comment by nickvergessen** [comment]
Turns out the TURN server is not completly configured.
