### ISSUE TITLE
Messages in the conversations list is updated but main messages list is not

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3216]
## Steps to reproduce
1. Open a conversation
2. Receive messages

### Expected behaviour
- Messages received should appear in the right sidebar or the main messages list (depending if you're on a call or not)

### Actual behaviour
- Last messages in the conversation list gets updated but the main content is not
- Reproducible on latest cloud.nc.com
- CLosing the sidebar and opening it again works. :thinking: 

### Details

- So I see you're using two different way of reaching the messages store.
https://github.com/nextcloud/spreed/blob/ed8a1c53c7ffb35d4518364dc9637591d52efd07/src/components/MessagesList/MessagesList.vue#L128-L130
https://github.com/nextcloud/spreed/blob/ed8a1c53c7ffb35d4518364dc9637591d52efd07/src/components/LeftSidebar/ConversationsList/Conversation.vue#L213-L215

https://github.com/nextcloud/spreed/blob/ed8a1c53c7ffb35d4518364dc9637591d52efd07/src/components/LeftSidebar/ConversationsList/Conversation.vue#L222-L234

So I guess either one is not properly detecting the change, but Vue's reativity should be active here. No idea why it is not updated. We could use some Vue debug tools so we can investigate and see why the data is not propagated properly.

@ma12-co

**Comment by nickvergessen** [comment]
the difference in the left sidebar is just to make sure when you write a message it immediately replaces the last message in the left sidebar.

the two getters access the same data:
https://github.com/nextcloud/spreed/blob/master/src/store/messagesStore.js#L34-L56

**Comment by skjnldsv** [comment]
> the two getters access the same data:
> [/src/store/messagesStore.js@`master`#L34-L56](https://github.com/nextcloud/spreed/blob/master/src/store/messagesStore.js#L34-L56)

Though the data is not updated simultaneously, meaning there is a reactivity lost somewhere :)

> the difference in the left sidebar is just to make sure when you write a message it immediately replaces the last message in the left sidebar.

I'm not only talking about messages that I write, I'm talking about received messages.

**Comment by nickvergessen** [comment]
I think the actual problem is that the message pulling was killed by the high load on our server, while the periodical 30sec room update brought the new last message in the sidebar.

Because `this.messages[lastMessageId].timestamp > lastMessageTimestamp` was not true, the `lastChatMessage()` from Conversation.vue was not using the store of messages anymore.

So we should check why pulling for messages could be canceled and not be repeating itself.

**Comment by skjnldsv** [comment]
> I think the actual problem is that the message pulling was killed by the high load on our server, while the periodical 30sec room update brought the new last message in the sidebar.

It doesn't matter. If the data is displayed in the right sidebar it means it's in the store. If it's in the store, the message should be visible in all places :)

**Comment by skjnldsv** [comment]
> Because `this.messages[lastMessageId].timestamp > lastMessageTimestamp` was not true, the `lastChatMessage()` from Conversation.vue was not using the store of messages anymore.

That would be the explanation then :)
There should not be two different data source I think, update the store and let vue do its magic ;)

**Comment by nickvergessen** [comment]
I think the issue was actually https://github.com/nextcloud/spreed/pull/3457

So closing for now.
