### ISSUE TITLE
Highlight color .forced-active should not eq --color-primary

### ISSUE THREAD

**Issue by jeichhor** [nextcloud/spreed#3227]
## Steps to reproduce
1. in Design change color to white #fff
2. open talk 
3. open a conversations context menu

### Expected behaviour
the selected notification setting should be highlighted in a contrast color - per default this seems #0082c9

### Actual behaviour
the selected notification setting can not be seen.
the highligt color "box-shadow" is inherited from css value --color-primary, which is customized to white and equals background color

## Browser
indep.

## Talk app

**Talk app version:** 8.0.5

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** 18.0.3

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>
![image](https://user-images.githubusercontent.com/5843366/78130048-ddf3c900-7418-11ea-8f3a-37525f1c4dba.png)

**Comment by nickvergessen** [comment]
Same issue on the app navigation.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
SHould be `--color-primary-element` iirc
