### ISSUE TITLE
Talk update fails

### ISSUE THREAD

**Issue by Mardiie** [nextcloud/spreed#3232]
## Steps to reproduce
1. Have nextcloud version 18.0.3
2. Update or install the newest version of Talk (spreed)

### Expected behaviour
I assume the upgrade window that appears should not give an error but just install the update.

### Actual behaviour

The upgrade page:
----
```
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)':


SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7-dump-0' for key 'tp_ident'

Update failed

```
Then if going to OCC:
----
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available

You may use your browser or the occ upgrade command to do the upgrade
```

A manual remove of spreed and trying to reinstall, even after removing the spreed directory from my nextcloud directory, after removing through OCC gives:

`PHP Fatal error: Cannot declare class OCA\Talk\Migration\Version8000Date20200331144101, because the name is already in use in /var/www/nextcloud/apps/spreed/lib/Migration/Version8000Date20200331144101.php on line 54`

## Talk app

**Talk app version:** 
8.0.6

## Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud Version:** 18.0.3

**List of activated apps:**
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_downloadactivity: 1.7.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.3
  - keeweb: 0.6.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.1.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

### Server log (data/nextcloud.log)

[log.txt](https://github.com/nextcloud/spreed/files/4417892/log.txt)

**Comment by octavsly** [comment]
Deleting duplicate entry from the table solved the issue for me.

**Comment by nickvergessen** [comment]
This works on MySQL, execute at your own risk:
```sql
CREATE TABLE `oc_talk_participants_temp` LIKE `oc_talk_participants`;
CREATE UNIQUE INDEX `tp_ident` ON `oc_talk_participants_temp` (`room_id`, `user_id`, `session_id`);
INSERT IGNORE INTO `oc_talk_participants_temp` SELECT * FROM `oc_talk_participants`;
DROP TABLE `oc_talk_participants`;
ALTER TABLE `oc_talk_participants_temp` RENAME TO `oc_talk_participants`;
```

If you have to do this, it means a user was twice in the same room, which also made the room unaccessible for that user, so it is "save" to clear the duplicate.

**Comment by Mardiie** [comment]
Thanks for the help!

**Comment by praptoumache** [comment]
worked for me
had to change the tablenames
```
CREATE TABLE `talk_participants_temp` LIKE `talk_participants`;
CREATE UNIQUE INDEX `tp_ident` ON `talk_participants_temp` (`room_id`, `user_id`, `session_id`);
INSERT IGNORE INTO `talk_participants_temp` SELECT * FROM `talk_participants`;
DROP TABLE `talk_participants`;
ALTER TABLE `talk_participants_temp` RENAME TO `talk_participants`;
```

**Comment by Xavier-github** [comment]
That does not work for me... Does anyone find something wrong?
I don't really have a doubt, but is there any way to check that nextcloud_db is my correct database?

```
MariaDB [(none)]> USE nextcloud_db
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [nextcloud_db]> CREATE TABLE `oc_talk_participants_temp` LIKE `oc_talk_participants`;
Query OK, 0 rows affected (0.33 sec)

MariaDB [nextcloud_db]> CREATE UNIQUE INDEX `tp_ident` ON `oc_talk_participants_temp` (`room_id`, `user_id`, `session_id`);
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
MariaDB [nextcloud_db]> show variables like 'innodb_file_format';
+--------------------+-----------+
| Variable_name      | Value     |
+--------------------+-----------+
| innodb_file_format | Barracuda |
+--------------------+-----------+
1 row in set (0.00 sec)

MariaDB [nextcloud_db]> show variables like 'innodb_file_per_table';
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_file_per_table | ON    |
+-----------------------+-------+
1 row in set (0.00 sec)

MariaDB [nextcloud_db]> 
```

**Comment by JB1985** [comment]
I wanted to update to version 8.0.7. Receive the error message:

An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '16-mschemmerling-2xTirzMoSBbeJXPBHwkWkaWxumQk2CTqxoUVqF/bcDr0ug6' for key 'tp_ident'

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/3232#issuecomment-607696462

**Comment by JB1985** [comment]
Sorry! I thought that was already fixed with 8.0.7.

**Comment by nickvergessen** [comment]
We can't fix this in a generic way because it only works on MySQL.

**Comment by octavsly** [comment]
> We can't fix this in a generic way because it only works on MySQL.

Agree but this error was for me a "kind of a disaster" since I was upgrading the nextcloud. Due to this error the whole nextcloud was not accessible as a result of a failed migration. 

So on nextcloud I **had** my files, contacts, emails, etc....

**Comment by Mardiie** [comment]
@octavsly use sql in bash, browse to the table, and delete duplicate entries. This solves it and your NC will function again.

**Comment by octavsly** [comment]
Thank you. I have solved using phpmyadmin.
