### ISSUE TITLE
Failed upgrade to v8.0.6

### ISSUE THREAD

**Issue by jgonyea** [nextcloud/spreed#3246]
## Steps to reproduce
1. Attempted upgrade to v8.0.6 from Nextcloud gui

### Expected behaviour
Upgrade to complete successfully.

### Actual behaviour
Receive the following error message:

Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Fix the namespace in database tables

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-USERNAME-0' for key 'tp_ident'

where USERNAME is a username from my NC instance.

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:**
Ubuntu Mate 18.04

**Browser name:** 
Firefox

**Browser version:**
74.0 (64-bit)

</details>

## Talk app

**Talk app version:**
8.0.6

## Server configuration

**Operating system**: 
Ubuntu Server 18.04

**Web server:** 
Apache

**Database:** 
Maria

**PHP version:**
7.2.24-0ubuntu0.18.04.3

**Nextcloud Version:** (see admin page)

**List of activated apps:**
<details>
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - breezedark: 18.0.10
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - drawio: 0.9.5
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.20
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - radio: 0.6.6
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.247",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 3
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "spreed",
            "radio",
            "ownpad"
        ]
    }
}

```

**Comment by jgonyea** [comment]
If it's helpful, it seems there is a duplicate entry here:
![image](https://user-images.githubusercontent.com/1057441/78261306-13f28500-74cd-11ea-84d2-0ce018ffb7e0.png)

**Comment by jgonyea** [comment]
Ran the following SQL command:
`ALTER IGNORE TABLE `oc_talk_participants` ADD UNIQUE (user_id, room_id);`

I then proceeded with another upgrade attempt from the CLI, which completed successfully.

**Comment by nickvergessen** [comment]
Don't do this. Instead see https://github.com/nextcloud/spreed/issues/3232
