### ISSUE TITLE
sidebar icon not visible in dark mode

### ISSUE THREAD

**Issue by reinhar2** [nextcloud/spreed#3248]
## Steps to reproduce
1. use dark theme
2. stark a new talk
3. look for the icon

### Expected behaviour
I expect to see the same icon like in the normal mode or high contrast mode.

### Actual behaviour
no sidebar icon is shown/seeable. It's still working though with clicks.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Mac Catalina 10.15.4 (19E266)

**Browser name:** Chrome

**Browser version:** Version 80.0.3987.149 (stable build)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Operating system**: Ubuntu 18.04, Nextcloud in Snap package

**Nextcloud Version:** 17.0.5

**List of activated apps:** Talk

<img width="247" alt="Screenshot 2020-04-02 21 30 49" src="https://user-images.githubusercontent.com/16307399/78294425-a83f0500-752a-11ea-9225-c8e9f65f2fb5.png">

**Comment by nickvergessen** [comment]
Please update to Nextcloud 18 and Talk 8
It will be much better there in dark mode
