### ISSUE TITLE
links with ports don't render

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#3250]
## Steps to reproduce
1. share a link with a port in a chat, for example https://cloud.josandcamila.com:444/call/.....
2. See that it remains plain text
3. 😭

### Expected behaviour
Should render as a link

### Actual behaviour
😭

**Comment by jospoortvliet** [comment]
hehe
label fight

**Comment by nickvergessen** [comment]
Actually it needs fixing in https://github.com/juliushaertl/vue-richtext/blob/master/src/RichText.vue#L26
But still a good starter issue :sunglasses:

**Comment by SystemKeeper** [comment]
First try, hope this is right...

**Comment by nickvergessen** [comment]
Thanks a lot @SystemKeeper

**Comment by nickvergessen** [comment]
@SystemKeeper want to make another PR here to update the lib to 0.3.1?
https://github.com/nextcloud/spreed/blob/master/package.json#L19

**Comment by SystemKeeper** [comment]
@nickvergessen I'll try, still new to this... 
Just to be sure: After changing the package.json I run "npm install" and commit both package.json and package-lock.json? Or is changing package.json enough here?

**Comment by nickvergessen** [comment]
Run npm install and commit both, yeah 😎

**Comment by SystemKeeper** [comment]
@nickvergessen Thanks for confirming :) Done and pushed - hope this works now.

**Comment by nickvergessen** [comment]
Thanks a lot, feel free to pick another issue from https://github.com/nextcloud/spreed/labels/good%20first%20issue and continue :)
