### ISSUE TITLE
Participant list shows the loading placeholder after closing and opening the right sidebar again

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#3254]
## Steps to reproduce
- Create a new group conversation (or open one that has less than 6 participants, as with more participants no placeholder is shown) 
- Close the right sidebar
- Open the right sidebar

### Expected behaviour
The list of participants shows only the participants in the conversation.

### Actual behaviour
The list of participants shows the participants in the conversation, but also the placeholder shown when loading the list of participants. The placeholder will not go away until the participants are fetched again, which can take up to 30 seconds without HPB and until a participant joins or leaves with the HPB.

**Comment by nickvergessen** [comment]
Yeah it seems the loading state is not set correctly when reopening the sidebar:
https://github.com/nextcloud/spreed/blob/0fe4e38a34043434618bfc59da482faae4fa028a/src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue#L25

**Comment by nickvergessen** [comment]
Seems to be fixed already
