### ISSUE TITLE
no email notifi

### ISSUE THREAD

**Issue by drlight17** [nextcloud/spreed#3255]
## Steps to reproduce
1. Create coversation
2. Add internal Nextcloud users as participants

### Expected behaviour
There must be an email invite letter for every participant, but there is only notification in NC GUI

### Actual behaviour
No email invite letter sent to participant user's emails

Is it by design or I missed some configuration? If you add non-nextcloud user's emails as guests they will receive invite letter without any troubles.

**Comment by nickvergessen** [comment]
Set https://github.com/nextcloud/activity/pull/437/files manually or wait until 18.0.4 is out.
