### ISSUE TITLE
Guest Accounts Being Provided With Read Only Access

### ISSUE THREAD

**Issue by medworthy** [nextcloud/spreed#3261]
I would like to have an option within Nextcloud Talk conversations / rooms which allows read only access for guest accounts, as well as having the ability to be able to disable video communication for guest accounts (or otherwise having an option that disallows guest accounts from being able to communicate within video based meetings).

**Comment by nickvergessen** [comment]
There is a setting to prevent guests from starting a audio/video call in the admin settings

**Comment by nickvergessen** [comment]
This is now implemented with several different permissions we introduced the chat permission from #7235  being the last one
