### ISSUE TITLE
Turn "test server" functionality

### ISSUE THREAD

**Issue by mthld** [nextcloud/spreed#3262]
hi,

actually there is a tool bundled in the app that aim to test if a turn server is properly configured and so on, accessible

sadly this tool hasn't a proper UI yet, actually there is 3 different states:
1. the test hasn't been run during this session
2. the test is running
3. the test is successful or not

#### this one is the first state described earlier
<img width="277" alt="Screenshot 2020-04-04 at 18 54 08" src="https://user-images.githubusercontent.com/41020854/78456793-0e03cc00-76a6-11ea-8be2-ef7e4eb839ce.png">

#### this one is the second
<img width="277" alt="Screenshot 2020-04-04 at 18 54 21" src="https://user-images.githubusercontent.com/41020854/78456796-11975300-76a6-11ea-87b5-6e11421fd55b.png">

#### and that's the third
<img width="277" alt="Screenshot 2020-04-04 at 18 54 30" src="https://user-images.githubusercontent.com/41020854/78456795-10662600-76a6-11ea-9756-7bca72dcb1d8.png">

### Expected behaviour
the result of the test should be clear (the UI should be intuitive) and understandable to everyone (the process should be documented)

### Actual behaviour
i'm not sure what means the result of the test, i'm confused: can my Nextcloud instance connect to my turn server?

## Talk app

**Talk app version:** 8.0.7

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration
**Operating system**: Debian 10 Buster

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.3

**Nextcloud Version:** 18.0.2

thanks in advance for your help

**Comment by nickvergessen** [comment]
Your Nextcloud does jot need to connect to the TURN server but your users. And the error icon means this did not work as expected

**Comment by mthld** [comment]
hi Nick,

thanks for answering, do you know if i can get some useful logs about what’s going on?

i carefully followed the last up-to-date procedure documented for the app, configuring coturn

i also setup a more verbose log output (level 0) to Nextcloud but i can’t find anything related to this in the logs

**Comment by nickvergessen** [comment]
So the error icon you are seeing means the turn server did not return any candidates for you.
The other state is a :ballot_box_with_check: check mark which means it returned candidates.

I'm not sure which further info we should display?!

**Comment by mthld** [comment]
hi nick,

an icon alone can't be read by a screen reader, a title or description must be added

**Comment by nickvergessen** [comment]
Is the `Test this server` accessible? Then I can change the text of that.

**Comment by mthld** [comment]
yes, i believe so, thanks for the proposed changes, it’s a good improvement!
