### ISSUE TITLE
Limit out of the box Talk calls to ~4 participants

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/spreed#3269]
**Is your feature request related to a problem? Please describe.**

The default installation of Talk does not work with more than ~4 participants.

References:
- https://help.nextcloud.com/t/videoconference-performance/74137
- https://github.com/nextcloud/spreed/issues/3163
- https://github.com/nextcloud/spreed/issues/3106
- https://github.com/nextcloud/spreed/issues/778

But people are (especially in Coronavirus days) trying out video conference solutions. If they install Talk and it doesn't work they are frustrated and just move on to the next service. That could damage the opinion about Nextcloud in general. Moreover if they find out somewhere hidden about the "high performance backend" they feel cheated about the open source model.

I know that isn't the case - but in my opinion it is not communicated clear enough.

**Describe the solution you'd like**

Clearly communicate or even better limit Talk video conference sessions to a small number of participants. Add a note why that is so. Also add notices that the high performance backend exists, what that does mean.

**Describe alternatives you've considered**

Keep it like it is. People install Nextcloud with Talk - try it - doesn't work → think it is crap

**Comment by gary-kim** [comment]
There's already a warning about connectivity issues that pops up if you are in a call with more than 4 participants. IMO, that seems sufficient and the README also includes this info.

**Comment by nickvergessen** [comment]
I think the biggest issue is that it only shows if you join and there are already 4 participants in the call or when there are more than 4 logged in users participants in the conversation when you start a call.
But maybe we should change that to always show (unless the admin disables the warning)

**Comment by weeman1337** [comment]
> There's already a warning about connectivity issues that pops up if you are in a call with more than 4 participants.

Three calls with two participants each do not work. Has that been considered as well?

> and the README also includes this info.

As we all know everyone reads READMEs ;)

> unless the admin disables the warning

For example. It could also go away if the magic high performance backend option has been set.

**Comment by gitte20** [comment]
The warning should show - before - people run into problems, not - while/after -they run into problems. It's a much more frustrating user experience if something happens unexpectedly than knowing there is a limit to what you can expect. So a clear statement what you can expect when you install the software and at the start of a call (for people who are just using an existing installation) is needed to restore confidence. In corona days much more (inexperienced) people will search for a video-call solution and you can choose whether the spread the word about nextcloud talk in a favourite or non-favourite way.

**Comment by nickvergessen** [comment]
> Three calls with two participants each do not work. Has that been considered as well?

That should work just fine. Note that the call participants maschines/connections are the bottleneck, not your Nextcloud server.

My server withholds easily 10 concurrent participants in calls. It's the same load as 20 people chatting.

> It could also go away if the magic high performance backend option has been set.

That already happens

**Comment by weeman1337** [comment]
> That should work just fine. Note that the call participants maschines/connections are the bottleneck, not your Nextcloud server.

As far as I understand Talk uses long polling. That means you may run out of PHP processes quickly depending on the config.

**Comment by jospoortvliet** [comment]
> > 
> 
> As far as I understand Talk uses long polling. That means you may run out of PHP processes quickly depending on the config.

A pull request to the documentation is welcome, but blocking any calls with >4 users seems way over the top as it can do that just fine... Sure, a bad setup might not be able to handle things - again, please, just get involved, help fix the documentation so people can more easily set up a Talk setup for more users. I've spend the last week countless hours updating our docs and website (see https://nextcloud.com/talk/#scalability and the readme and the docs) - perhaps you can add how to do this as I'm clueless about what long polling is or how to change PHP processes...

I hope you're OK closing this as it is no solution to the problem. Improved documentation would be.

WRT the whole 'Talk doesn't scale well' - you can either have:
1. easy to install
2. scaling real well

We rewrote Spreed.me which was in Go and very much "2" to PHP so it was "1". If you want "2" then you have options, our partners' HPB for one, or install Jitsi - there's nothing wrong with it and it is open source.

**Comment by jospoortvliet** [comment]
So the latest versions of Talk include a LOT of performance improvements. Without a back-end, conversations with 5-10 participants should generally* be possible. When it is not sufficient, we also are happy to announce that our partner Struktur has agreed to open source the back-end.

See more in our blog:
https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/


* with decent bandwidth and computing resources on the clients, yes

**Comment by weeman1337** [comment]
Hi @jospoortvliet thanks for all the effort. In my opinion that brings Nextcloud (Talk) some steps forward. It is a hard market out there. While I observe people are in general open to test alternatives they also switch to (maybe) insecure and proprietary solution when facing the smallest issue.

Good work!
