### ISSUE TITLE
Apache proxy_wstunnel

### ISSUE THREAD

**Issue by inpos** [nextcloud/spreed#327]
Is there any manual to configure apache proxy_wstunnel ?

**Comment by nickvergessen** [comment]
Tried google?

**Comment by inpos** [comment]
OK. Let's try second way )))
What subfolder or suburl (/some/magic/subfolder) I must specify in 
```
<Location /some/magic/subfolder>
		ProxyPass ws://192.168.0.111/some/magic/subfolder
</Location>
```
?

**Comment by nickvergessen** [comment]
I'm closing this, since it seems unrelated to the Spreed app
