### ISSUE TITLE
Do not show user email adress

### ISSUE THREAD

**Issue by fetfets** [nextcloud/spreed#3272]
When clicking on the name of a user in the left tab, there is an option to send a mail, and the user email adress is shown.

For privacy reason, I think this behaviour should be on opt-in option in Talk Application, and nothing to be show by default.

**Comment by nickvergessen** [comment]
This is the same menu in all places of Nextcloud.
You can change the privacy in `index.php/settings/user`

**Comment by fetfets** [comment]
> 
> 
> This is the same menu in all places of Nextcloud.
> You can change the privacy in `index.php/settings/user`

Thanks a lot. I'd rather have posted in a NC forum section.

**Comment by Dubidubiduu** [comment]
@nickvergessen please reopen. It's not just about my own settings, it's about all of my users and there should be a system-wide setting. I don't want my users to reveal their email by accident.

Maybe it's also solved when https://github.com/nextcloud/server/pull/20667 is. Propably the same discussion as in https://github.com/nextcloud/server/issues/14959#issuecomment-488608652.

**Comment by nickvergessen** [comment]
Yeah this is not in control of the Talk app. So it has to be fixed in the server anyway. Although server is changing the description of the scopes for Nextcloud 20 anyway to make sure that there is no misunderstanding what they mean (because currently there is).
