### ISSUE TITLE
Bug while upgrading Netcloud Talk

### ISSUE THREAD

**Issue by Xavier-github** [nextcloud/spreed#3273]
Hi,

I was asked to report following error. I open another subject in a forum to get some help...

Hope this helps,
Xavier

Mise à jour vers 18.0.3

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Journaux détaillés

Préparation de la mise à jour

Réglage du niveau de journalisation à "déboguage"

Mode de maintenance activé

Étape de réparation : Repair MySQL collation

Informations de réparation : All tables already have the correct collation -> nothing to do

Étape de réparation : Repair SQLite autoincrement

Étape de réparation : Copy data from accounts table when migrating from ownCloud

Étape de réparation : Drop account terms table when migrating from ownCloud

Mise à jour du schéma de la base de données

Base de données mise à jour

Étape de réparation : Fix the namespace in database tables

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

La mise à jour a échoué. Veuillez reporter le problème à la communauté Nextcloud.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/3246

**Comment by nickvergessen** [comment]
On a related note, you should check to enable 4byte support before:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by Xavier-github** [comment]
Hi,

Thanks for your answer, and sorry for the duplicated item.

 * I had already done the conversion to utf8mb4. But when I reload MariaDB (sudo /etc/init.d/mysql restart), it goes back to Antelope.
 * I followed the instructions given by nickvergessen at https://github.com/nextcloud/spreed/issues/3232 but that does not work either. Did I miss a step (I do not know how to select my database "nextcloud_db", neither if I should do that)?
MariaDB [(none)]> CREATE TABLE `oc_talk_participants_temp` LIKE `oc_talk_participants`;
ERROR 1046 (3D000): No database selected
MariaDB [(none)]> CREATE TABLE `talk_participants_temp` LIKE `talk_participants`;
ERROR 1046 (3D000): No database selected

Have a good afternoon!
Xavier

________________________________
De : Joas Schilling <notifications@github.com>
Envoyé : lundi 6 avril 2020 16:32
À : nextcloud/spreed <spreed@noreply.github.com>
Cc : Xavier-github <xaxou@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [nextcloud/spreed] Bug while upgrading Netcloud Talk (#3273)


On a related note, you should check to enable 4byte support before:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by nickvergessen** [comment]
> I had already done the conversion to utf8mb4. But when I reload MariaDB (sudo /etc/init.d/mysql restart), it goes back to Antelope.

Can you try to get that figured out in the forum first? (sorry for the back and forth)

> No database selected

You have to select your database first via `use THE_NAME_OF_YOUR_DATABASE;`
But this only works after the UTF8mb4 change was done

**Comment by Xavier-github** [comment]
(Addendum)
I ran following command:
`MariaDB [nextcloud_db]> select session_id from oc_talk_participants;`
All the results are "0" but one, namely "6z2luFRCc84GzxH2PaRqPYl+sqPQ/17RWO6vMiqjPDdjZ5z3ffsRwslPMU87QwJ910t7gOhdLr1Pb6W+Pw6TRgEZ36VX1GD+G0mBpnY+DmYpT/bjaANBMw5BK1xp9ZdmhlZH1QHjg9eKQyYfZ5VhSpWqSg8G1YSQk0DlzkUHUSMZ5e9IG0udpp5oeyI6mQd/m2F1NJFQkfBsRSVfpjhPMXap6i4aCxb7wOo4YqMBxW2OjirYEQ6/Km0XN3vHF6b".

I guess it should be a possibility to delete this entry to make all work again, but:
 * I do not know how to do that with MariaDB.
 * I do not know which problem I encounter afterwards. For me, there is no problem if I delete Talk and install it again, if Nextcloud work.

My assumption is to be bound with the error:

> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, **session_id**)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
