### ISSUE TITLE
Missing preview in quoted messages

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#3283]
1) User "A" sends a funny image
2) User "B" quotes the message and writes a reply after a while
3) User "A" is confused because he got a reply along with a cryptic file name
4) ???

Expected result: User A should see the preview of an image (original message) to understand the context of the message.

**Comment by nickvergessen** [comment]
Well yes, but the problem is we don't do any RichObjects in the quotes, just simple text replacements. :/
But maybe we need to do it differently for the uploads.
