### ISSUE TITLE
single user dismissals

### ISSUE THREAD

**Issue by RoundAboutWEB** [nextcloud/spreed#3284]
The new "Lobby" function is good for webinars, but in practice a "waiting room" where individual visitors can be admitted would also be very helpful.

For example, for onlinetalk at the doctor's office. A link is published on the website that takes you to the waiting room and the doctor can then call individual patients. The same function would also have great advantages in other places (service conversations, authorities, ...).

**Comment by nickvergessen** [comment]
Basically like https://github.com/nextcloud/spreed/issues/674 but with the lobby added?

**Comment by RoundAboutWEB** [comment]
Kind of like #674, but not exactly. The participants should wait in a lobby without chat (like now), but the monderator should have the possibility to allow single participants and the rest stays in the lobby.

**Comment by nickvergessen** [comment]
Yeah, let's add that to #674
