### ISSUE TITLE
Access from groups only

### ISSUE THREAD

**Issue by vasyakrg** [nextcloud/spreed#329]
If there are groups on the server that are not connected to each other.
You need to add the ability to limit the visibility of users between groups.
Now the list shows all users from the server

**Comment by nickvergessen** [comment]
Well it's the same with sharing.

But in Settings > Admin > Sharing there are two configs which might help you:
1. Restrict users to only share with users in their groups
2. Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.

**Comment by nickvergessen** [comment]
Closing as per above
