### ISSUE TITLE
Turnserver compatibility user/password instead static-auth 

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/spreed#3301]
With the current implementation, I did not find any ability to use the login procedure with the turnserver (coTurn, ...) In Talk config mask, only the static-auth is possible, which is actually not a good procedure. 

Request: User/pass for the talk setup should be allowed.

**Describe alternatives you've considered**
N/A

**Comment by nickvergessen** [comment]
User/Pass is used in the end. The Talk app creates the username and password.

**Comment by Bolli84** [comment]
When you look into the Settings for Talk, you van enter the turnserver URL and the shared-secret. 
With better setup configurations in the turnserver, you need to enter user/pass instead of the simple shared-secret = static-auth. 
If you use greatest setups, you cannot use the same turnserver, as most other setup require user/Password.
That should also be possible with talk.

**Comment by nickvergessen** [comment]
@fancycode maybe you can help to clarify this?

**Comment by fancycode** [comment]
Username/password for the TURN configuration are valid indefinitely and should only be on a per-user base (see #84 on the initial implementation). As the global TURN credentials are sent to each participant in a call (registered and anonymous), everybody could (ab-)use the credentials to create other connections through the TURN server from other services.

That's why Talk switched to the shared secret TURN configuration and hands out short-lived credentials to users that can not be used indefinitely.

If we allow configuring TURN username/password in the admin settings, it should show a big warning that the credentials will be sent to all participants and therefore must be considered "public". Another option would be to add this to the personal settings similar to what was done in #84 but fallback to the global shared secret setting if a user doesn't configure his own credentials.

**Comment by nickvergessen** [comment]
Okay, sounds like it is not a good idea, but only to get other turns to work. So not a priority at the moment.

**Comment by Bolli84** [comment]
It is the same as with the shared secret.
E.g. if you are using a second Implementation on the same turnserver, it has more needs like that. E.g. kurento-media-server

Using username:password of a turnserver user is exactly valid as it is with the currently used static-auth.

**Comment by nickvergessen** [comment]
> Using username:password of a turnserver user is exactly valid as it is with the currently used static-auth.

No the current approach is that every users get's unique custom credentials which expire, while with the fixed static auth, I can copy your turn credentials and server url to my instance after I had a guest call on yours, and then abuse your turn server for my talk calls?

**Comment by Bolli84** [comment]
Topic can be closed as it is not relevant.

**Comment by derStephan** [comment]
Sorry for bringing that up again. But I don't understand what that means @fancycode 

Let's take cloudflare. They describe how to get short-lived username/password from an TURN Key: 
https://developers.cloudflare.com/realtime/turn/generate-credentials/

This sounds exactly like what you described here: 

>That's why Talk switched to the shared secret TURN configuration and hands out short-lived credentials to users that can not be used indefinitely.

So will it suffice to put the API URL together with the TURN key in the talk setting and it will create username/passwords for each client automatically?



Regards
Stephan

**Comment by fancycode** [comment]
> Sorry for bringing that up again. But I don't understand what that means [@fancycode](https://github.com/fancycode)
> 
> Let's take cloudflare. They describe how to get short-lived username/password from an TURN Key: https://developers.cloudflare.com/realtime/turn/generate-credentials/
> 
> This sounds exactly like what you described here:
> 
> > That's why Talk switched to the shared secret TURN configuration and hands out short-lived credentials to users that can not be used indefinitely.

Yes, that's the same principle: the servers (here: Talk and the TURN server) know the shared secret, so Talk can generate TURN usernames/passwords for the clients to use and the TURN server can check if they are valid.
Cloudflare does something similar through their API.

> So will it suffice to put the API URL together with the TURN key in the talk setting and it will create username/passwords for each client automatically?

It would be if Talk supported the Cloudflare API to fetch the TURN information and sends it to clients. However this is a separate feature request. Feel free to open a new issue for it.

**Comment by fancycode** [comment]
> It would be if Talk supported the Cloudflare API to fetch the TURN information and sends it to clients. However this is a separate feature request. Feel free to open a new issue for it.

Just noticed there already is #12394 which you just commented on.

**Comment by derStephan** [comment]
Wow, you are quick. 

>Just noticed there already is https://github.com/nextcloud/spreed/issues/12394 which you just commented on.

Yes, sorry for the duplicate. I did not know if the people subscribed here will see this question in the other ticket.
