### ISSUE TITLE
Reveals internal IPs

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#3303]
Not sure if this is a nextcloud bug or a talk bug.  It was reported to me by a user and kinda seemed like a potential security flaw so I'm reporting it here.

## Steps to reproduce
1. Log into talk.
2. Say there for a long time until your token expires.
3. click on other things and observe this message:

The server was unable to complete your request.  If this happens again, please send the technical details below to the server administrator.  More details can be found in the server log.   Technical details     Remote Address: 100.x.x.x   Request ID: xxxxxxxxxxxxxxx

Remote address is the internal ip of my nextcloud server.

**Comment by nickvergessen** [comment]
You are using a reverse proxy?

**Comment by Luticus** [comment]
For some stuff like collabora office, guacamole, and such, but not the general nextcloud.  Although I am using sslh now that I think about it though.  So port multiplexing is a thing but I don't know if that would have any effect on this issue.  I'm actually wondering if it was an apache error that was thrown.  If that's all it was then it can be mitigated via setting ErrorDocument in apache.  Though I'm not sure if you want it to behave that way when a token expires though.  Not sure if there's anything that can be done about what happens when the token expires.  I wish I had more information on the error but I didn't even witness it first hand so I'm unsure.  I did set all my error documents to simple strings for now to try and mitigate it though.

**Comment by nickvergessen** [comment]
1. The token should be refetched periodically and therefor not expire anymore (at least in Nextcloud 18)
2. The IP shown should be the IP of the user and is displayed so they can reach out to the admins with the request id and their IP in a way allowing the admin to find out what was going wrong. If that is your servers IP and you had another one, your nextcloud proxy settings are misconfigured, checkout https://docs.nextcloud.com/server/18/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by Luticus** [comment]
I'm definitely not using any reverse proxy stuff at all.  Not for nextcloud anyway.  So I'm not sure why it's revealing the internal IP like that.

**Comment by Luticus** [comment]
Honestly we should probably not print the remote address to the screen anyway, instead we should only print it in a log.  That would be a good bit more secure I think.
