### ISSUE TITLE
Missing Talk Updates  icon

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#3319]
<img width="60" alt="Screenshot 2020-04-13 at 21 00 07" src="https://user-images.githubusercontent.com/5810/79150936-e4dfeb80-7dc9-11ea-8258-2ec8ebff141d.png">

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/spreed/commit/72edd115cccf18494ce54d08cf3cc801141586d7

cc @ma12-co @skjnldsv 

Why this change to lowercase without hitting F5 in the frontend?
