### ISSUE TITLE
Screen sharing app can't be installed on Firefox 43+

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/spreed#332]
The Firefox app shows the following message when trying to install from addons.mozilla.org:

> Caution: This add-on has not been reviewed by Mozilla and can't be installed on release versions of Firefox 43 and above. Be careful when installing third-party software that might harm your computer.

This means the addon cannot be installed on Firefox 43+. This was tested with the latest Firefox (Version 53.0.3 at the moment). Please provide a new version that is reviewed by Mozilla to let users do screen sharing on newer Firefox releases too.

**Comment by Ivansss** [comment]
Screensharing extension is not required for Firefox anymore.
You just need Firefox version 52 or newer to use the screensharing feature.

**Comment by Ivansss** [comment]
Updated the README file #333 to make it clear 😄
