### ISSUE TITLE
Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.

### ISSUE THREAD

**Issue by chaptergy** [nextcloud/spreed#3323]
## Steps to reproduce
1. ???
2. Start a call
3. Allow Firefox to access the microphone and camera

### Expected behaviour
The call is started, and my mic and camera are working

### Actual behaviour
The following error message pops up 
```
Access to microphone &amp; camera is only possible with HTTPS: Please move your setup to HTTPS
```
When looking into the console, the real error seems to be 
```
Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
```
I have no idea what that means and I can't find anything about that error online.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Archlinux

**Browser name:** Firefox

**Browser version:** 75.0

### Browser log

<details>

```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Setting current user talk.js:1661:19914
Source map error: Error: request failed with status 404
Resource URL: https://mynextcloud.com/custom_apps/spreed/js/talk.js?v=0194969a-12
Source Map URL: talk.js.map 2
Current participant found 2 talk.js:993:122107
The request has been canceled 
Object { message: "canceled" }
talk.js:707:3891
Joined 
Object { data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, request: XMLHttpRequest }
talk.js:119:3213
Joined 
Object { data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, request: XMLHttpRequest }
talk.js:119:3213
The request has been canceled 
Object { message: "canceled" }
talk.js:707:4581
Current participant found 2 talk.js:993:122107
Current participant found talk.js:993:122107
Joining call talk.js:993:123347
Access to microphone & camera failed DOMException: "AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported." talk.js:147:8501
The request has been canceled 
Object { message: undefined }
talk.js:707:4581
Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported. talk.js:993:32472
Current participant found talk.js:993:122107
```
</details>

## Talk app

**Talk app version:** 8.0.7

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Don't know

**Web server:** Don't know

**Database:** MySQL

**PHP version:** 7.3.15

**Nextcloud Version:** 18.0.3

**Comment by nickvergessen** [comment]
Okay, so one thing is showing a wrong error message.

I guess we run into `error.name === 'NotSupportedError'` and then we fall back to the HTTPS message.

The other question is if you did something fancy with the selected audio input to make your browser trigger `Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported`. Any idea how we can create that behaviour, so we can see how to differenciate it from the HTTPS problem?

**Comment by chaptergy** [comment]
The problem seems to be Firefoxes `resistFingerprinting` flag. If you go to `about:config` in Firefox, and set the flag `privacy.resistFingerprinting` to true, the issue arises.

**Comment by nickvergessen** [comment]
Confirmed. Okay so we have a problem here. It is also not possible to detect this I guess?

**Comment by chaptergy** [comment]
Nope, at least it shouldn't be. It might be with disproportionate effort, but I don't see that as an option.

**Comment by jahrvos** [comment]
Is this dependent on the version of FireFox? And where exactly can we set resistFingerprinting to false?

**Comment by chaptergy** [comment]
It should not be dependent on the Firefox version. Resist fingerprinting can be enabled as explained in https://github.com/nextcloud/spreed/issues/3323#issuecomment-617181533, so by going to `about:config`

**Comment by jahrvos** [comment]
Maybe I understand things wrong. One of the users of my jitsi server got this error. I am trying to find out what causes this error. I don't know how to go to  about:config in FireFox. In the **about FireFox** window there is no option config

**Comment by chaptergy** [comment]
No, just type that into the address bar.

**Comment by jahrvos** [comment]
I see, thanks a lot!

**Comment by nickvergessen** [comment]
This has been fixed for Firefox 77 and you can then enable resistFingerprinting again.

**Comment by vincerubinetti** [comment]
> If you go to `about:config` in Firefox, and set the flag `privacy.resistFingerprinting` to true, the issue arises.

In present day, I'm actually finding the opposite.  If `resistFingerprinting` is set to false, I get the error. If it's set to true, it goes away. Very weird...

```
AudioContext.createMediaStreamSource: Connecting AudioNodes from AudioContexts with different sample-rate is currently not supported.
```

**Comment by naktinis** [comment]
Possibly related to this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1674892
