### ISSUE TITLE
Hovering over an image partially hides the sender's name

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#3327]
![Screenshot from 2020-04-14 14-54-44](https://user-images.githubusercontent.com/26852655/79227361-0e4b5680-7e60-11ea-95a0-9d088995d3d6.png)

## Steps to reproduce
1. Upload an image to a conversation 
2. Hover the image with the mouse

### Expected behavior
The hover background change feedback shouldn't partially hide the name

### Actual behavior
The hover background change feedback partially hides the name

**Comment by nickvergessen** [comment]
Not happening anymore
