### ISSUE TITLE
Talk sidebar not available in ONLYOFFCE for public links

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#3331]
## Steps to reproduce
1. Share office file with public link
2. see Talk in the sidebar on the link page
3. click on 'edit in onlyoffice' and see - no way to access the sidebar :(

### Expected behaviour
A sidebar allows a call with Talk, chat etc

### Actual behaviour
No sidebar

## Browser
Chromium

**Comment by nickvergessen** [comment]
I think this is an issue with the OO app, not the Talk app.
Can you confirm @danxuliu

**Comment by danxuliu** [comment]
I also think that this is an issue with the OO app. If you press _Edit in ONLYOFFICE_ you are no longer in the public share page; you get redirected to _apps/onlyoffice/s/shareToken_. The OO UI should be embedded in the public share page instead.

**Comment by nickvergessen** [comment]
@jospoortvliet can you open an issue in their repo instead?
Thanks
