### ISSUE TITLE
Semantic markup of reply feature

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3334]
At the moment it’s just divs and a paragraph element. For accessibility, the reply feature needs to be marked up as `blockquote`. It seems sufficient to simply move `quote__main__text` from being a `div` to a `blockquote`.

Ideally we also use the `cite` attribute to refer to the quoted message: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

**Comment by tacruc** [comment]
Would the cite attribute make it possible to open the original message onClick. Right now it is hard to get the context of a cited message.
Basically you need to search the original message.

**Comment by nickvergessen** [comment]
No, there is more missing for that than "markup".
But it's tracked in #2708
