### ISSUE TITLE
Determining the hardware requirements for a TURN server for Nextcloud Talk

### ISSUE THREAD

**Issue by pmarini** [nextcloud/spreed#3339]
I would like to know if there exists a rule of thumb to determine the hardware requirements of a TURN Server depending on a number of variables: 

- number of users, 
- maximum concurrent number of calls, 
- maximum number of participants in a call, 
- whether usage will be mainly for voice or video calls, 
- and any other parameter that I'm not thinking about right now. 

The assumption is that we are dedicating a machine for the TURN Server.

**Comment by pmarini** [comment]
Hi, any hint on this? Thanks!

**Comment by nickvergessen** [comment]
Check the docs of coturn?

**Comment by simonspa** [comment]
This indeed is more of a `coturn` question. They have a few numbers in a ticket, but the bottom line is: you have to measure...

See https://github.com/coturn/coturn/issues/328
