### ISSUE TITLE
Show complete date on hover

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3340]
Maybe it is just me, but for me it happens often that I scroll/search through the chat history, found the message I was looking for and would like to know from when it was. In crowded rooms I have now to scroll a lot to find the beginning of the day and then go back to find the message again.

I think it would be really useful if the timestamp on the left would show the complete date on hover.

**Comment by nickvergessen** [comment]
The timestamp on the right used to show the hover. Was this dropped by accident when the reply button fix came in? cc @ma12-co

**Comment by ma12-co** [comment]
I think it used to show a tooltip in the old talk app but not in the Talk > 8. We could bring it back of course!

**Comment by ma12-co** [comment]
This is where the time is displayed:
https://:github.com/nextcloud/spreed/blob/master/src/components/MessagesList/MessagesGroup/Message/Message.vue#L56
