### ISSUE TITLE
Restrict starting calls to groups

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#3342]
It is currently possible to configure if only moderators should be allowed starting calls.
However, since everyone can create new conversations and start calls there, it's hard to predict the back-end server's load/bandwidth for large installations.

Feature request: Allow to limit starting calls to certain user groups

**Comment by nickvergessen** [comment]
With 19 there is a setting to limit who can create conversations. Does that solve it already?

**Comment by wiswedel** [comment]
That solves half of the cases, yes. However, text-chatting is usually supposed to stay allowed among students (Edu customers are the most common ones asking for this)

**Comment by wiswedel** [comment]
resolved by https://github.com/nextcloud/spreed/pull/3095

**Comment by nickvergessen** [comment]
#3095 is about conversations, not calls. But fine for me to have this closed? 😕

**Comment by wiswedel** [comment]
> #3095 is about conversations, not calls. But fine for me to have this closed?

oh noo. that's two different things now? I was so excited 😢

**Comment by nickvergessen** [comment]
Starting a call is now a permission which can be granted per room.
