### ISSUE TITLE
Opening viewer cycle through all share talk medias

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3347]
cc @danxuliu 

https://github.com/nextcloud/spreed/blob/6ab75d7816a015a2d4d5fb001e45d914db522e2b/src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue#L143-L146

- [ ] Create a new endpoint to get a list of filesInfos for all share files in a room
- [ ] Use this list
- [ ] Bonus: use pagination to not load a list of 1k shared files

**Comment by skjnldsv** [comment]
Reference of similar endpoint:
https://github.com/nextcloud/photos/blob/3320ac4e929a60bf2902a4e6b1fc4b5666f7a4bb/lib/Controller/AlbumsController.php#L85-L107

https://github.com/nextcloud/photos/blob/7bd7bf28808fc73bd2bfb09a352e7dca1c4c7938/src/components/File.vue#L122

**Comment by nickvergessen** [comment]
We don't have such a list at the moment and I'm not sure how performant a "loop over all shares of a specific conversation" is. We could also have an endpoint which only returns the data of this one file for the time-being? Or is there any other way to stop the "loop"?
People are getting quite scared assuming all the files of the same folder they shared a file from are shared with all participants.

**Comment by skjnldsv** [comment]
> We could also have an endpoint which only returns the data of this one file for the time-being? Or is there any other way to stop the "loop"?

You can do single image view in the meantime yes :)
That should mitigate the issue in the meantime :wink: 
```js
OCA.Viewer.open({path: '/.talk/Peek 2020-04-19 18-43.gif', list: [{filename: '/.talk/Peek 2020-04-19 18-43.gif', basename: 'Peek 2020-04-19 18-43.gif'}]})
```
Seems to do the trick in the meantime

**Comment by skjnldsv** [comment]
> We don't have such a list at the moment and I'm not sure how performant a "loop over all shares of a specific conversation" is.

Should not be harder than filtering by Share type or Share owner like we do in other places.

**Comment by nickvergessen** [comment]
Temporary solution is in #3370 with a follow up in #3409

**Comment by PVince81** [comment]
If we [stored attachments with one subfolder per conversation](https://github.com/nextcloud/spreed/issues/4340), it could help the viewer cycle by just querying the attachments of that folder. Still, might need to rename the files or use the timestamp to have them in the same order they were posted.

Hmmm, and what when the same file got posted/shared multiple times ?
