### ISSUE TITLE
UI Bug: Date picker partly out of window (Firefox 75.0)

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#3356]
## Steps to reproduce
1. Standard NC 18.0.3 setup with talk 8.0.7.
2. Start talk and activate lobby.
3. Pick date & time to oben talk.

### Expected behaviour
Date picker inside visible window

### Actual behaviour
Date picker partly moving outside the visible area.
This is independent of the browser size (within usual limits for desktop computers).

Bug only exists on Firefox. With Chrome, everything is fine.

![talk-ui-bug](https://user-images.githubusercontent.com/42836313/79701081-7f44a100-829a-11ea-813f-26fd1efc90ba.png)

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows 10

**Browser name:** Firefox

**Browser version:** 75.0

### Browser log
not applicable

## Talk app

**Talk app version:** 8.0.7

**Comment by nickvergessen** [comment]
Is this a bug in Talk or the Vue components @danxuliu ?

**Comment by danxuliu** [comment]
I think that it is [the same issue mentioned in the pull request that added the lobby timer](https://github.com/nextcloud/spreed/pull/2668#issuecomment-572514162).

When the lobby is enabled the menu width increases, but the menu is not repositioned, so it is partially hidden. If the moderation menu is closed and then opened again then, when the date picker is shown again, it should be fully visible.

@johkoenig Can you confirm? Thanks for the information.

**Comment by johkoenig** [comment]
Sorry for the late reply. Yes, I can confirm that the behaviour is as described by @danxuliu.

**Comment by johkoenig** [comment]
Hello,
the problem is still present with talk 8.0.9, see screenshot. 
![talk-ui-bug](https://user-images.githubusercontent.com/42836313/82245102-a1d1e480-9942-11ea-891b-12f13afd1440.png)

**Comment by johkoenig** [comment]
Note: When I click "activate lobby", the dialogue resizes, however, it resizes to the left and to the right (the center position stays the same). It should resize to the left only. By resizing also to the right, parts are beyond the margin.

**Comment by nickvergessen** [comment]
Yeah, it's fixed in Talk 9 beta1 and aparently not easily fixable in Talk 8
