### ISSUE TITLE
Safari compability

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/spreed#336]
With Safari 11.0 Apple will introuduce WebRTC 🙌 

- [ ] Make Safari **11** compatible (do not block it as incompatible browser)
- [ ] Consider about required changes in WebRTC implementation of Video calls
- [ ] Check, whether Screen sharing needs a separate plugin 

https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html

**Comment by MorrisJobke** [comment]
If you need help testing this: I can jump in and give feedback.

**Comment by nickvergessen** [comment]
Closing in favor of https://github.com/nextcloud/spreed/issues/1076
