### ISSUE TITLE
People joining public circles are not added to conversation

### ISSUE THREAD

**Issue by jcastang** [nextcloud/spreed#3366]
## Steps to reproduce
1. Create a public circle
2. Open a new conversation and add the created circle as participant
3. People that are already in circle are added
4. People that join this circle later are not added to conversation

### Expected behaviour
People in conversation must be added dynamically on circle join / quit

### Actual behaviour
1/ If you join a circle after it has been added to a conversation, you are not added to conversation
2/ If you leave circle, you are still included in conversation

## Browser Firefox / Chrome (last on both)

**Microphone available:** No matter

**Camera available:** No matter

**Operating system:** Windows/Ubuntu/MacOS

**Browser name:** Firefox/Chrome

**Browser version:** 75.0

## Talk app

**Talk app version:** 8.0.7

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2.24

**Nextcloud Version:** 18.0.3

**List of activated apps:**

<details>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - cospend: 0.4.5
  - dav: 1.14.0
  - deck: 0.8.2
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.7
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

</details>

**Comment by nickvergessen** [comment]
This is currently the expected behaviour. Circles (same as groups) are not tracked yet.
See #1329
