### ISSUE TITLE
Add logged-in user as regular participant when they join over a public link

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3367]
When I join a Talk room over a public link it seems like I'm in a intermediate state. Talk re-uses my name and avatar but I can't mark the room as favorite for example and when I close the browser I leave the room completely.

I think it would be a nice improvement if I would be added as a regular and permanent participant to a room when I join the room over a public link as a logged-in user.

**Comment by nickvergessen** [comment]
I still don't think so and I guess that #1763 is the better solution to it.
It will be too complicated to keep track of the passwords etc otherwise.

**Comment by schiessle** [comment]
I think #1763 is something different and would like to have both. :grin: 

#1763 is about having dedicated public rooms everyone can discover and join/leave as they want.

Here it is about the following scenario I have multiple times a day:

1. A colleague schedules a meeting and attaches a room to the meeting. 
2. Now I get the invitation with the public link, like everyone else
3. When I click on the link I will join in some kind of intermediate state:
    * Talk recognize that I'm logged in and reuses my display name and avatar
    * Many other features don't work like adding the room to my favorites, e.g. because it is a weekly meeting, getting notification if someone writes something or starts a call... etc 

That's why I think it would be great if Talk could promote me to a regular participants when I join over a public link and have a account on the same server.

At the end it shouldn't matter how I got invited. Over the participants tab or because someone send me the direct link. If I'm logged-in I should be a regular participant at the end. I think the way it is at the moment is also highly confusing to the end-user because it looks like I'm in a regular room but some actions in the '...' menu are missing and I don't get the same notification I'm used to from any other room in my room list.

**Comment by schiessle** [comment]
@nickvergessen please reconsider it as a separate feature request... Thanks!
