### ISSUE TITLE
Browser warning in 8.0.8 appears on iOS over and over again

### ISSUE THREAD

**Issue by stephanhoennekes** [nextcloud/spreed#3369]
## Steps to reproduce
1. Open Talk or Files app.

### Expected behaviour
No browser warning in mobile browsers on current iOS.

### Actual behaviour
Whenever Talk is loaded or refreshed, the new warning for unsupported browsers appears (#3296) This is not only happening in Talk itself, but also whenever the Files app is loaded. I know this message can be quite useful on outdated browsers, but appearing all the time on a current iOS installation is slightly too much ;)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** iOS 13.4.1

**Browser name:** Safari/Firefox/Chrome/...

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.7

**Nextcloud Version:** 18.0.0

**Comment by nickvergessen** [comment]
Ah the sidebar of the files app makes it appear I guess. as you can have a call there.
Maybe we only show it when the sidebar was opened on the chat tab?

And we could store when the user manually removed the toast in the browser store and then not show the warning again?

**Comment by stephanhoennekes** [comment]
That would be great, @nickvergessen . But why does it need to appear on iOS at all? Beside the screensharing feature Talk works quite well on mobile Safari. And there wouldn’t be a better option to use, because iOS does not allow any other browser engine than webkit. So every other browser available is also just mobile Safari with another skin.

**Comment by nickvergessen** [comment]
Can you provide the useragent safari mobile is sending?

**Comment by stephanhoennekes** [comment]
Sure:

_Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1_

**Comment by nickvergessen** [comment]
@ma12-co I guess `isIOS` should then also be checked?
https://github.com/ICJIA/vue-browser-detect-plugin/blob/master/src/main.js#L26-L27

**Comment by nickvergessen** [comment]
This was fixed in 8.0.10
