### ISSUE TITLE
Nextcloud Talk turn server. Using the turn-server does not give a positive (any) result 

### ISSUE THREAD

**Issue by graceastrid** [nextcloud/spreed#3372]
Hello everybody! I installed Nextcloud Talk and when I try to talk via voice communication with more than two people (on different networks, not on the local network), problems arise: one of my friends can hear only one person, but he cannot hear the third one (the third one also does not hear him). Many different combinations of inoperability.
Problems and freezes when connecting new people to a voice call.

On the Internet, I found a solution to this problem - this is installing and configuring my own turn-server (coTurn v4.5.0.8).
According to HowTo instructions: Setup Nextcloud Talk with TURN server HowTo: Setup Nextcloud Talk with TURN server I am on my separate server from Nextcloud (it is accessible all over the Internet, static IP address) installed and configured the turn server. But this did not give a result: as before, it is impossible to communicate normally and stably if more than two people participate in the conference. Problem saved.

I ask you for help in solving my problem.

I tried many different configurations, but all failed. I have so far settled on the configuration from the post above.

here are the settings from my tuneserver.conf file:
```
listening-port = 3478
fingerprint
use-auth-secret
static-auth-secret = XXXXXXXXxxxXXXXXXXXXXXxXXXXXXXXXa99cdcec03XxXxXxxx
realm = talk.domain.ru
total-quota = 100
bps-capacity = 0
stale-nonce
no-loopback-peers
```

testing the turn-server through the NC admin panel is successful (a daw appears when testing the connection)

## Steps to reproduce

1. install Nextcloud Talk
2. try to talk via voice communication with more than two people (on different networks, not on the local network)

### Expected behaviour
stable connection and conversation with people not in local network (in other city)

### Actual behaviour
one of my friends hears only one person, but the third does not hear (the third does not hear too)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS 10.15

**Browser name:** Chrome

**Browser version:** 80.0

## Talk app

**Talk app version:** 7.0.2

**Custom TURN server configured:** yes, coTurn v4.5.0.8

**Custom STUN server configured:** yes, stun.l.google.com:19302

## Server configuration

**Operating system**: Centos 6.10

**Web server:** Apache, Nginx (reverse proxy)

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud Version:** 17.0.5

**List of activated apps:**
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.9.0
  - auto_mail_accounts: 0.1.4
  - calendar: 2.0.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.8.2
  - drawio: 0.9.5
  - emlviewer: 0.0.5
  - event_update_notification: 1.0.1
  - external: 3.4.1
  - extract: 1.2.4
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - ldapcontacts: 2.0.1
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.3.2
  - notes: 3.2.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - piwik: 0.5.4
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - socialsharing_email: 1.0.6
  - spreed: 7.0.2
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - uploaddetails: 0.1.3
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

**Nextcloud configuration:**

```
$CONFIG = array (
  'instanceid' => 'XXXXXXXX',
  'passwordsalt' => 'XXXXXXXX',
  'secret' => 'XXXXXXXX',
  'datadirectory' => '/var/www/html/owncloud-data',
  'skeletondirectory' => '/var/www/html/owncloud-data/files_new_user',
  'overwrite.cli.url' => 'https://domain.ru/',
  'dbtype' => 'pgsql',
  'version' => '17.0.5.0',
  'dbname' => 'domain.ru',
  'dbhost' => 'XXXXXX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXX',
  'dbpassword' => 'XXXXXX',
  'logtimezone' => 'Europe/Moscow',
  'installed' => true,
  'maintenance' => false,
  'appstore.experimental.enabled' => true,
  'updatechecker' => false,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 1000,
  ),
  'asset-pipeline.enabled' => true,
);

```

**Comment by nickvergessen** [comment]
I would recommend to not use google STUN server.

Did you follow https://nextcloud-talk.readthedocs.io/en/latest/TURN/ when setting up your turn?
And does https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ return correct candidates?

I'm closing this as it sounds more like a configuration issue then a software bug and therefor https://help.nextcloud.com/ or the coturn forum is the better place to look for help.

On the other hand an update to Nextcloud 18 and Talk 8 could also help.

**Comment by graceastrid** [comment]
> I would recommend to not use google STUN server.
> Did you follow https://nextcloud-talk.readthedocs.io/en/latest/TURN/ when setting up your turn?

Yes

> And does https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ return correct candidates?

when I try to check the link you provided, I click the Gather candidates button and it becomes inactive. nothing else happens.
> I'm closing this as it sounds more like a configuration issue then a software bug and therefor https://help.nextcloud.com/ or the coturn forum is the better place to look for help.
> 
> On the other hand an update to Nextcloud 18 and Talk 8 could also help.

I upgraded to version 18, the result was not much better (now 3 participants can speak normally)

**Comment by nickvergessen** [comment]
Is the load and bandwith on both, your Nextcloud server and your TURN server, okay?

**Comment by Happyfeet01** [comment]
Have the same Problem. Setup an own signaling Server but nothing works. 
It get this message when i check the Server. Whats wrong?
![grafik](https://user-images.githubusercontent.com/3295104/103519018-0c557780-4e75-11eb-8b6b-500751348d30.png)

**Comment by nickvergessen** [comment]
Well that is indepentend of Talk then. Check your turn servers configuration. Also see https://nextcloud-talk.readthedocs.io/en/latest/TURN/
