### ISSUE TITLE
Direct link for video conf

### ISSUE THREAD

**Issue by pvalsecc** [nextcloud/spreed#3376]
**Is your feature request related to a problem? Please describe.**
Some users are not computer literate. The path to get to a video conf should be shorter. The user needs to click the URL, find the button to start the call and then have the user accept access to the camera/mic (I know this step is unavoidable). This is one step too much for my mother in law.

**Describe the solution you'd like**
It would be cool to be able to get a "direct to video conf" URL. One that skips the chat history view.

**Describe alternatives you've considered**
Changing mother in law is not an option. I like my wife and her mother.

**Comment by nickvergessen** [comment]
Are you on Talk 8?
We lately added the Join button very prominent there

**Comment by pvalsecc** [comment]
I am on the latest version. But that is one useless step IMHO. Please try to put yourself in a 75 year old grand mother's prostetic shoes. It would easier if she could only click on a link on her desktop and get directly in the video conf with her grand child.

**Comment by nickvergessen** [comment]
Well there is no way around approving camera+microphone permissions, so not sure if this helps a lot to "skip the green button" #3398

**Comment by jancborchardt** [comment]
The new **Add join call button to chat view #2969** is also very helpful here. Does this help @pvalsecc?

**Comment by nickvergessen** [comment]
Closing as per above.
