### ISSUE TITLE
Smarter room querying

### ISSUE THREAD

**Issue by rullzer** [nextcloud/spreed#3377]
I noticed that a lot of room requests are submitted when in a big call multiple people join or leave.

* If we listen to the signalling server anyway there is no need for the 30 sec poll.
* We should probably debounce the refresh of the room so we don't fireoff X when X people join. But rather debounce it a bit so it is less hammering the server.

**Comment by nickvergessen** [comment]
Also related to #1810

**Comment by PVince81** [comment]
was this solved with https://github.com/nextcloud/spreed/pull/3512 ?

the part about "when using signaling" seems to be covered by https://github.com/nextcloud/spreed/pull/3512

**Comment by nickvergessen** [comment]
No that only debounces for some seconds, but still polls every 30 seconds

**Comment by nickvergessen** [comment]
Stopped with #5780

Also see #5781, #5782, #5783
