### ISSUE TITLE
Wrong string for rename conversation in de_DE

### ISSUE THREAD

**Issue by RogoTe** [nextcloud/spreed#3379]
## Steps to reproduce
1. set language to German
2. go to a conversation
3. click ... in right panel to edit conversation settings
4. see first menu item

### Expected behaviour
menu item is labeled "Unterhaltung umbenennen"

### Actual behaviour
![Screenshot 2020-04-21 at 18 14 59](https://user-images.githubusercontent.com/45861130/79901435-20089d00-8410-11ea-852f-ee1b620d3d25.png)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** MacOS 10.15.4

**Browser name:** Firefox 75.0

**Browser version:** 75.0

## Talk app

**Talk app version:** 8.0.7 and 8.0.8

**Comment by nickvergessen** [comment]
I saw it before in another screenshot, but it seems to be correct now:
https://github.com/nextcloud/spreed/blob/master/l10n/de_DE.js#L334

**Comment by RogoTe** [comment]
> I saw it before in another screenshot, but it seems to be correct now:
That is the strange thing: l10n file seems to be okay. It was changed last time in January.
Parallel to creating this issue I looked into the repository thinking "That's easy, let me create a quick pull request". But turned out I could not retrace where this is coming from...

**Comment by nickvergessen** [comment]
So this was the case in the past:
https://www.transifex.com/nextcloud/nextcloud/translate/#de/spreed/191675354

but it should still be fixed nowadays

**Comment by nickvergessen** [comment]
Aparently the backporting to stable18 is not executed anymore since mid January. It still works on master, 17, 16 and by accident 15:

https://github.com/nextcloud/spreed/blob/stable18/l10n/de.js#L260

will be fixed later today and new translations may appear in 8.0.9 then
