### ISSUE TITLE
Android, Kodi, etc. clients

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/spreed#338]
If Possible I wish I could use Nextcloud as server for an Android Client like [siacs/Conversations](https://github.com/siacs/Conversations) and a Kodi app (Connect Family from the Family nextcloud via raspberryPI over TV)

Maybe you could create the Federation tool #21 that way, that also Clients are able to connect and Use nextcloud and it connected Federation network.

**Comment by nickvergessen** [comment]
This will be covered with https://github.com/nextcloud/spreed/issues/347

**Comment by nickvergessen** [comment]
Closing as per https://github.com/nextcloud/talk-android
