### ISSUE TITLE
feature request: recording

### ISSUE THREAD

**Issue by edmundlaugasson** [nextcloud/spreed#3380]
**Is your feature request related to a problem? Please describe.**
We need recording of audio, audio+video. Text will be recorded in conversation feed already. Definitely we need pause/continue feature. Currently MS Teams has such recording feature but does not have pause/continue feature - Nextcloud can excel here. Whenever we have meetings, also lectures, practical work, etc - we need recording. Whenever recording will be possible, after that we can start talking of replacing MS Teams. But we need replace it, believe me.

**Describe the solution you'd like**
allow to record audio or audio-video session:
* to cloud (Nextcloud itself)
* remotely to somewhere another computer (via SSH, SFTP, WebDAV, NFS, Samba, etc)
* locally (into local computer)

Allow at least YouTube streaming because it allows also to save there automatically. Hopefully also other video portals that support own streaming, e.g. Vimeo, probably LBRY, and other alternatives - https://alternativeto.net/software/youtube/
Also allow pause/continue during recording.
Also ensure that all participants voices will be recorded.
Perhaps also allow audio -, video codec selection and quality settings.
Text will be saved anyway in group conversation but why not allow text also save separately as txt file like Zoom does.

**Describe alternatives you've considered**
Jitsi Meet and its recording features - currently into Dropbox and YouTube streaming

**Additional context**
[MKV format](https://en.wikipedia.org/wiki/Matroska) would be appreciated. Possibly also [MP4](https://en.wikipedia.org/wiki/MP4). If possible to offer choices then probably [WebM](https://en.wikipedia.org/wiki/WebM) and [Ogg Theora](https://en.wikipedia.org/wiki/Theora) also. When audio only then perhaps can you consider voice-oriented [Opus audio codec](https://en.wikipedia.org/wiki/Opus_(audio_format)), why not also [Ogg Vorbis](https://en.wikipedia.org/wiki/Vorbis).

**Comment by nickvergessen** [comment]
See #1232 and #2014

So long story short, without a desktop client or 3rdparty server being a fake participant in the call, this is unlikely to happen.
But feel free to add your thumbs up on #1232

**Comment by edmundlaugasson** [comment]
Well, Jitsi Meet (based on same WebRTC technology) allows to record:
* directly to Dropbox
* via YouTube stream
Facing "busy recorder device" in Jitsi, would suggest local save. Certainly it requires to allow access local file URLs like WebRTC apps require acces to microphone and webcam. As this all is acknowledged actions, I do not see any other obstacles here. No need for desktop app. No idea, why you spoke about 3rd party server but won't see its need either. Just local save of recorded audio, video at least, why not also text chat (like Zoom does).
