### ISSUE TITLE
archiving room conversation

### ISSUE THREAD

**Issue by ediazcomellas** [nextcloud/spreed#3384]
**Is your feature request related to a problem? Please describe.**
I would find it useful to be able to store talk group conversation contents as a note or document for later review. This helps to collect meeting minutes. Group conversations are a great tool to help collaboration.  

**Describe the solution you'd like**
I want to have a Group Conversation property checkbox called "save to log file". If that checkbox is enabled, a folder must be selected where the conversation will be stored. Conversations can have a normalized name (something like : groupname-talk-logfile-YYYYMMDDhhmm-YYYYMMDDhhmm.log) with the start and end dates for the logfile.  Of course, ending times would be updated every time a new bunch of lines are added to the file, which can happen asynchronously once every minute or every 5 minutes if there is something to store. 

**Describe alternatives you've considered**
Current alternative is to remember to cut&paste the group contents before deleting the conversation. 

**Additional context**
In case a project is used, there can be a standarized way to show this meetings linked to it.

**Comment by ediazcomellas** [comment]
I would want to post a bounty for this issue if it has any option to be developed.

**Comment by nickvergessen** [comment]
Let's reopen #383 instead as the ui is still missing to set this
