### ISSUE TITLE
Guests' names don't update under avatar/video (with ext. signaling only)

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#3387]
Note: This only happens with active external signaling server (not in P2P mode)

## Steps to reproduce
1. Have a video call with a bunch of guest users
2. Guest users change their names

### Expected behaviour
Changed names appear under their avatars/videos

### Actual behaviour
Guests only appear with changed names in the chat sidebar but remain "Guest" under their avatar/video

**Comment by johkoenig** [comment]
I can confirm that this happens with an out-of-the-box installation of nc18 / talk 8.0.7.
I had this issue recently on a call with 6 people. All of those were connecting from their home place, so their computer was probably behind a router with NAT.

**Comment by wiswedel** [comment]
@nickvergessen Any ideas?

**Comment by nickvergessen** [comment]
Yes, the problem is the peer id between HPB and you is not the same as the same as the session id of the guest in our database. Currently there also seems to be no way to get the original session id as recipient, so no way for us to match the guest name.

**Comment by wiswedel** [comment]
> Yes, the problem is the peer id between HPB and you is not the same as the same as the session id of the guest in our database. Currently there also seems to be no way to get the original session id as recipient, so no way for us to match the guest name.

What does this mean now? No way = no idea = no solution, or _actually getting fixed in the 💙 Next Minor (18) milestone_?

**Comment by nickvergessen** [comment]
A fix should target or be backported until 18, that is what the milestone says.

Currently I personally am out of ideas, but it's also not the top item atm.
