### ISSUE TITLE
Define and document signaling API

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#339]
cc @karlitschek @schiessle @nickvergessen @Ivansss

I started thinking about the API for the Spreed signaling server:
https://github.com/nextcloud/spreed/wiki/Spreed-Signaling-API

This is a first rough draft with still lots of undefined areas (some already marked as TODO), but it would be great to get some early feedback.

The idea (at least imho) is to implement the same API in the PHP backend and the standalone signaling server and let the frontend use either of the backends depending on the configuration in Nextcloud. That way default installations work out-of-the-box and larger installations can setup one or multiple signaling servers and configure their urls to be used.

**Comment by nickvergessen** [comment]
We also need to move it to ocs api, to allow clients to use the apis as well, so it all will be wrapped with `ocs => data => ...`

Yeah sounds good, also had this in mind to workaround the http2 issue

**Comment by fancycode** [comment]
This is only relevant for the PHP backend, right? I would like to keep the API independent of the backend that is actually used to avoid having too much backend-specific code in the clients.

Ideally only the URL should be different and the rest should be the same (though we need to use COMET for PHP without WebSockets).

**Comment by nickvergessen** [comment]
Well OCS is a standard, and the wrapping inside ocs => data => is already the only noticable difference for consumers.

And yes, the URL should be the only thing that is different, which is why I suggest to also do the OCS wrapping on your backend?

**Comment by nickvergessen** [comment]
I will move the API to OCS this week, so Ivan can continue with the iOS app after his vacation.

**Comment by nickvergessen** [comment]
Ah ignore me, that's not even possible on the signaling thing, because that only returns one response....

**Comment by fancycode** [comment]
FYI, I just updated the wiki page:
- websocket/comet
- auth backend
- resuming sessions

This should now contain everything required for a version 1 and support at least the features available right now. So if no-one objects, I will start with some implementation the next days.

**Comment by fancycode** [comment]
Now that the standalone signaling server is (again) about to support the same functionality as the web-ui (#492), we should think about streamlining APIs of the polling-based PHP backend and the standalone signaling backend.

My idea was that the messages should be the same for both backends, with the only difference being the transport which is GET/POST for the PHP backend and WebSockets for the standalone signaling server.

Obviously this affects the web-ui as well as the mobile apps, so I'm not sure how to best proceed to maintain compatibility what we already have.

cc @nickvergessen @Ivansss @mario

**Comment by nickvergessen** [comment]
Closing as per https://github.com/nextcloud/spreed/pull/6892
