### ISSUE TITLE
Translation de_DE incomplete

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#3397]
## Steps to reproduce
1. Delete conversation
![translation](https://user-images.githubusercontent.com/42836313/80315306-eb715880-87f6-11ea-935b-a6befb14aa2d.PNG)

Text is partly english on a de_DE nextcloud

## Talk app

**Talk app version:** 8.0.8

**Comment by nickvergessen** [comment]
Yeah stable18 translations were broken. They are fixed now and 8.0.9 will bring all the translations
