### ISSUE TITLE
Sharing Button/Menu

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#34]
Invite people and send sharing links

**Comment by jancborchardt** [comment]
Yep, this should be a 3-dot menu in the left navigation. In the row of the room (just like with the Calendar app). We can have entries for »Invite people«, »Rename«, »Leave«.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/spreed/issues/7?

**Comment by jancborchardt** [comment]
@ChristophWurst so @Ivansss is working on this in https://github.com/nextcloud/spreed/tree/more-options-button – @Ivansss can you push your latest changes and open a work-in-progress pull request? :)

**Comment by ChristophWurst** [comment]
Good to know :-)

**Comment by jancborchardt** [comment]
Fixed meanwhile, and all features implemented :)
