### ISSUE TITLE
[Question/Feature Request] Create a Named/permanent group

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/spreed#340]
Is it somehow Possible to create a permanent named Group?
I wish to create a Family Video Chat. Goal at the end is a RaspberryPI on the TV on which Grandmother could switch and could see all current available Family Member which had open the spreedme app in their Browser. For that I had to set a link in their Firefox Link list.

**Comment by nickvergessen** [comment]
You can rename groups since the last major version. So that should cover your issue?
