### ISSUE TITLE
Copy link available even when there is no link

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3400]
I just noticed on  9.0.0-dev.5 that the "Copy link" operation is always available even if "share link" is unchecked:

![image](https://user-images.githubusercontent.com/1589737/80374954-c4b72e80-8897-11ea-9c34-d208588e6aee.png)

I think it should be disabled or maybe even hidden completely to have a cleaner menu?

Same is true for the Webinar options, which only makes sense for public rooms, right?

**Comment by nickvergessen** [comment]
But maybe you want to copy the "internal"  link to share it with your colleges?
I still think we should rename the checkbox to "allow guests" or something. For people not inside the Nextcloud bubble that would be much easier to grasp

**Comment by schiessle** [comment]
> But maybe you want to copy the "internal" link to share it with your colleges?

Why should I share the link instead of inviting them as a regular participant?

> I still think we should rename the checkbox to "allow guests" or something. For people not inside the Nextcloud bubble that would be much easier to grasp

Absolutely! :+1:

**Comment by nickvergessen** [comment]
Share link in terms of send them the link, it's the same as the f/id link for files.

**Comment by nickvergessen** [comment]
So I'm closing this as the copy option is still valid as per above
