### ISSUE TITLE
Invisible "icon-menu-people" in conversation when said menu is closed

### ISSUE THREAD

**Issue by Refhi** [nextcloud/spreed#3404]
## Steps to reproduce
1. create new conversation
2. Join call
3. Close Menu-People side bar with the cross
4. The "3-lines + little people" menu button is invisible but still works

### Expected behaviour
The button should be visible

### Actual behaviour
The button is invisible

### Browser log

<details>
the problem seem to be around here (I'm not sure it's the correct data needed, though, sorry)
```
span data-v-42604de1="" class="action-button__icon forced-white icon-menu-people"
```

</details>

## Talk app

**Talk app version: 8.08 was like that in 7.* too I believe** 

## Server configuration

**Operating system**: Ubuntu LTS 18.04

**Nextcloud Version:** 18.0.4

**Comment by nickvergessen** [comment]
Can not reproduce it. can you check if the icon is accidentally blocked by your adblocker or something? Do you see a 404 request in the network tab in your browser?

**Comment by nickvergessen** [comment]
Closing as per above. Feel free to reopen with answers to the questions.

**Comment by Refhi** [comment]
Sorry for the delay

So I've cleaned install a 18 snap nextcloud and started a conversation, it did the exact same bug as with my current installation (also snap, haven't tested other kind of install yet)
I've taken the liberty of including screenshots to be more clear : 


![before clicking join call](https://user-images.githubusercontent.com/2778215/81471567-40976c00-91f2-11ea-8081-02d4543093a3.png)
![after clicking join call](https://user-images.githubusercontent.com/2778215/81471564-3ffed580-91f2-11ea-9e82-8698730c2a7d.png)
![after clicking join call with mouseover showing invisible icon location](https://user-images.githubusercontent.com/2778215/81471566-40976c00-91f2-11ea-80dc-a29521a58d8d.png)

**Comment by Refhi** [comment]
Ok so : on the same versions (nextcloud 18.04 and talk 8.08)
- snap install = the bug is here
- docker install = the bug is not here
On firefox console I notice a "TypeError: n is null | MessagesList.vue:481" line when on snap install when I clic on the invisible button. It does not happen in docker install.
