### ISSUE TITLE
No screensharing button

### ISSUE THREAD

**Issue by nutzmdm** [nextcloud/spreed#341]
Chrome extension is installed

No errors in apache error.log
No error in Nextcloud admin apnel logging section

In html code, button is present:

`<button id="screensharing-button" class="app-navigation-entry-utils-menu-button icon-screen-off-white screensharing-disabled" data-placement="top" data-toggle="tooltip" data-original-title="Partager l'écran"></button>`

## Steps to reproduce
1.Open spreed app
2.Create a new room
3.try to share screen

### Expected behaviour
Have screen sharing icon

### Actual behaviour
There isn't screensharing icon

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10 pro

**Browser name:** Firefox/Chrome/...
chrome
firefox

**Browser version:** 50.1/55/...
chrome 58
firefox 53

### Browser log

<details>
```
a)

JQMIGRATE: Migrate is installed, version 1.4.0
detector.js:44 Detected Nextcloud Spreed app.
detector.js:53 Initialized extension Object {id: "kepnpjhambipllfmgmbapncekcmabkol", version: "1.0.0", priority: 100}
app.js?v=20d1f94…-12:492 Starting spreed …
core.js?v=20d1f94…-12:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ core.js?v=20d1f94…-12:4
ajax @ core.js?v=20d1f94…-12:4
leaveAllRooms @ rooms.js?v=20d1f94…-12:110
startSpreed @ app.js?v=20d1f94…-12:503
(anonymous) @ webrtc.js?v=20d1f94…-12:588
prototype.emit @ simplewebrtc.js?v=20d1f94…-12:17524
(anonymous) @ simplewebrtc.js?v=20d1f94…-12:18286
(anonymous) @ simplewebrtc.js?v=20d1f94…-12:7563
(anonymous) @ simplewebrtc.js?v=20d1f94…-12:4167
simplewebrtc.js?v=20d1f94…-12:17991 CONNECTED
(anonymous) @ simplewebrtc.js?v=20d1f94…-12:17991
emit @ xhrconnection.js?v=20d1f94…-12:22
(anonymous) @ xhrconnection.js?v=20d1f94…-12:15
j @ core.js?v=20d1f94…-12:2
fireWith @ core.js?v=20d1f94…-12:2
x @ core.js?v=20d1f94…-12:4
(anonymous) @ core.js?v=20d1f94…-12:4
DevTools failed to parse SourceMap: https://XXXXX/core/vendor/dist/purify.min.js.map
DevTools failed to parse SourceMap: https://XXXXXX/apps/spreed/js/vendor/backbone/backbone-min.map
DevTools failed to parse SourceMap: https://XXXXXX/apps/spreed/js/vendor/backbone.marionette/lib/backbone.marionette.min.js.map
DevTools failed to parse SourceMap: https://XXXXXX/apps/spreed/js/vendor/backbone.radio/build/backbone.radio.min.js.map
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)
2.0.1

**Custom TURN server configured:** no
**Custom STUN server configured:** no

## Server configuration

**Operating system**: DEBIAN
**Web server:** Apache

**Database:** MySQL

**PHP version:**

**Nextcloud Version:** (see admin page)
12

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by rakinzon** [comment]
I have this issue also in Google Chrome in MacOS Sierra.

**Comment by truelai** [comment]
I have this issue with Iceweasel (Firefox) & Chromium on Ubuntu 16.04

There is no share screen icon.

**Comment by Ivansss** [comment]
Screensharing button is hidden until you are in a call with someone.

**Comment by truelai** [comment]
@Ivansss It's still hidden during the call for me.

**Comment by nutzmdm** [comment]
for me too

**Comment by nickvergessen** [comment]
Like ivan I can not reproduce. You have any closer steps, what you do?

Also please post the exact browser, spreed and nextcloud versions you are using.

**Comment by nutzmdm** [comment]
I do not understand. After a week of vacation it works again...

**Comment by nickvergessen** [comment]
Good so maybe some old files were cached
