### ISSUE TITLE
Inconsistent state when accidentally joining with 2 devices

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#3415]
## Steps to reproduce
1. somebody calls you, you join in the browser
2. instead of turning off your ringing tablet, you accidentaly slide-to-join, then cancel that again

### Expected behaviour
Nothing special, you just have your call

### Actual behaviour
1. a spinning second avatar of you joins the call
2. after a while you suddenly get dropped back in the normal chat view, out of the call, join call button is there - but you can still hear the other participants and they can hear you
3. click join call and you're back, with a warning about leaving the page (?) that you can dismiss.

## Browser
Chromium, latest - 81.0.4.something

### Browser log
Sorry, totally failed to capture that

## Talk app
cloud.nextcloud.com setup

**Comment by nickvergessen** [comment]
Already being dealt with in #3338

**Comment by nickvergessen** [comment]
This is solved.

The rest will be dealt in #1587
