### ISSUE TITLE
No browser notifications on 18.0.4

### ISSUE THREAD

**Issue by dahumph** [nextcloud/spreed#3417]
## Steps to reproduce
1. log in to your nextcloud 18.0.4
2. find somone to call you or mention you on talk
3. wait to see no browser notification

### Expected behaviour
the browser should somehow catch my attention and inform me of incoming call or message. 

### Actual behaviour
nothing. you'll just miss the call

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 18.04 and 16.04

**Browser name:** Firefox/Chrome/ both

**Browser version:** newest, firefox 75

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
8.0.8

**Custom TURN server configured:** yes, push notification works for ios and android

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 16.04
**Web server:** Apache

**Database:** Maria

**PHP version: PHP 7.4.4

**Nextcloud Version:** 18.0.4

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by 9at8** [comment]
hmm, can confirm ^

**Comment by nickvergessen** [comment]
Do you have the notifications app installe? And did you click on the bell with the red dot once so Nextcloud has your browsers permissions to send notifications?

**Comment by ArnY** [comment]
Hello,

I can confirm the problem with NC 18.0.4 and Talk 8.0.8.

I can also add that there are no NC notification either  but as soon as the user clicks on the Talk icon and the app loads, the notifications are sent and showing in the notification indicator. But since the user is already in the app, no browser notification ever.

**Comment by dahumph** [comment]
> Do you have the notifications app installe? And did you click on the bell with the red dot once so Nextcloud has your browsers permissions to send notifications?

Notification app is installed and browser permissions granted...

**Comment by nickvergessen** [comment]
Then the only last point would be that notifications are not sent when you have an active session (open browser tab or in the mobile app) in the same conversation. This is unluckily currently necessary to avoid problems with multi-device support (you wouldnt want your phone vibrating all the time, while you are actively chatting on the browser, etc.)

**Comment by ArnY** [comment]
On my side, it wasn't the case. No active session on talk neither on browser nor on mobile. On my browser i had a tab open on nextcloud, but on the file app, not talk. 

Plus, as soon as I switched to the talk app, the notification indicator showed that I had notifications (the talk notifications...) which was not the case when I was on the file app a second before.

**Comment by nickvergessen** [comment]
Do you have `session_keepalive` disabled then?

**Comment by ArnY** [comment]
session_keepalive is enabled.

**Comment by dahumph** [comment]
> Do you have `session_keepalive` disabled then?

changed to `session_keepalive` enabled

Now notifications are working!

Danke!

**Comment by nickvergessen** [comment]
Can you report an issue in the notifications app then?
https://github.com/nextcloud/notifications/blob/master/src/Components/Notification.vue#L248
I guess we should just drop this and use some default

**Comment by nickvergessen** [comment]
@ArnY if that is reproducable for you, please reproduce it and have your browser console (F12 and then switch to "Console") open to see if an error happens. Also check the Network tab on an other occasion to see if a request fails.

If you find out more, please create an issue in the notifications app about it: https://github.com/nextcloud/notifications

**Comment by ArnY** [comment]
> Do you have `session_keepalive` disabled then?

It was indeed disabled (I checked on the wrong instance the other day, sorry about this).
