### ISSUE TITLE
No start date shown for the webinar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3424]
## Steps to reproduce
1. create a public room
2. enable the lobby
3. set a start date

### Expected behaviour

See the start date in the drop down

### Actual behaviour

It looks like no start date was set:

![image](https://user-images.githubusercontent.com/1589737/80598204-4b4f4580-8a29-11ea-9de7-027fd1112d60.png)

## Talk app

**Talk app version:** 9.0-dev5

**Comment by wiswedel** [comment]
> It looks like no start date was set

However, it _is_ in fact set.

Looks like the same Vue issue like we had for the share expiration date: https://github.com/nextcloud/server/issues/20520

**Comment by osm-frasch** [comment]
Yes it is in fact set. 

The bug still exists. I am using Nextcloud 19.0.2 Talk Version: 9.0.3

**Comment by schiessle** [comment]
While setting up an appointment I just noticed that the problem still (again?) exists on c.nc.com.
