### ISSUE TITLE
I want to invite external users to a group chat through a circle in Talk

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/spreed#3425]
I want to invite **external users to a group chat through a circle** in Talk

I’m trying to group external users together in the CIRCLES App and later invite them to a group chat in TALK (A school class for example) using this circle. 

I can't select the Circle in Talk. Either this is a bug or this feature is not yet implemented. I assume the latter.

Please implement the Circle functionality in Talk completely. 
It will be easier to invite external users in group chats if it works with Circles.

If I group external users in a circle and share a file or folder with them, this works best. 
It should also work that way in Talk. Otherwise this confuses.

**Comment by nickvergessen** [comment]
This should work since Talk8

**Comment by osm-frasch** [comment]
Hmmm. 
I just tried it again.

1. create a circle with 3 external participants
2. created a group chat
3. enter the name of the circle in the input mask of the right column of the group chat
4. the circle is found
5. I click on the circle

Nothing else is happening. The circle is not permanently listed in the right column.
There are also no e-mails received by the participants

Nextcloud version 18.0.3
Circles app: 0.18.5
Talk app: 8.0.8
PHP Version: 7.3.16

**Comment by nickvergessen** [comment]
I missed the "external" part. That will only work when #21 is done.
