### ISSUE TITLE
Short Link Syntax

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/spreed#3427]
**Is your feature request related to a problem? Please describe.**
Posting Link-URLs in Talk can take a lot of Space, e.g. "Hi Guys, check out the following App-Entity: https://mynextcloud.com/index.php/app/MyApp/#myCustomParameter=123&abc=123"

**Describe the solution you'd like**
It would be so nice to be able to link URLs in Chat, like: 
"Hi Guys, check out the following App-Entity: **MyApp Link1**"
by using this Github-esque-Syntax: `[MyApp Link1](https://mynextcloud.com/index.php/app/MyApp/#myCustomParameter=123)` 

**Additional context**
Implementing this URL-Syntax in the first step could be easier, than the more broad request here: https://github.com/nextcloud/spreed/issues/1027

P.S.: With shorter Links i do not mean using an external Link-Shortener :-)

**Comment by nickvergessen** [comment]
Might be possible after https://github.com/nextcloud/spreed/issues/1027
But for now we don't have markdown or any other syntax in place.

**Comment by nickvergessen** [comment]
And since you commented it there too, let me close this.
