### ISSUE TITLE
Fix (or hide) upload new files for guest user

### ISSUE THREAD

**Issue by kesselb** [nextcloud/spreed#3430]
## Steps to reproduce
1. Be a guest user
2. Join a public talk room
3. Try to upload new files

### Expected behaviour

![image](https://user-images.githubusercontent.com/3902676/80709534-b95d4080-8aed-11ea-9582-9dd5012743c0.png)

I can use "upload new files" to upload a new file

### Actual behaviour

![image](https://user-images.githubusercontent.com/3902676/80709580-cb3ee380-8aed-11ea-9712-387e4aceeb3a.png)

`PROPFIND https://cloud.nextcloud.com/remote.php/dav/files/guest%40test.com/Talk/meme_to_share_with_you.gi`f

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //Talk could not be located</s:message>
</d:error>
```

## Browser

**Microphone available:** yes

**Camera available:** no

## Talk app & Server configuration

cloud.nextcloud.com

**Comment by nickvergessen** [comment]
This is about guests from the [guest app](https://github.com/nextcloud/guests) not "not-logged in users"

**Comment by nickvergessen** [comment]
Also happens for users without a quota I guess

**Comment by nickvergessen** [comment]
Fixed
