### ISSUE TITLE
Move a room to the conversation area shows upload overlay

### ISSUE THREAD

**Issue by kesselb** [nextcloud/spreed#3431]
## Steps to reproduce
1. Open Talk
2. Click and hold a room
3. Move the room to the conversation area

### Expected behaviour

Nothing ;)

### Actual behaviour

![Peek 2020-04-30 11-51](https://user-images.githubusercontent.com/3902676/80710044-98e1b600-8aee-11ea-9e58-2fad2af923e3.gif)

## Browser

Microphone available: yes

Camera available: no

</details>

## Talk app && Server configuration

cloud.nextcloud.com

**Comment by nickvergessen** [comment]
Can we do something about this? @ma12-co

**Comment by ma12-co** [comment]
Not sure... I will look into it
