### ISSUE TITLE
group-chat vanishes from conversations-list after joining via invitation-link

### ISSUE THREAD

**Issue by MoonyCarolin** [nextcloud/spreed#3434]
## Steps to reproduce
1. Open a *.docx-file, which is stored on the nextcloud instance.
2. Klick on the link to a groupe chat of talk, which is stored in the docx-file.
3. Observe that you join the groupe-chat.
4. Leave the groupe-chat.
5. See the groupe-chat in the list of your conversations on the left in the talk-app.
6. Observe that after a few minutes, the groupe-chat disappears from the list of your conversations.

### Expected behaviour
Expected was that the groupe-chat stays in the list of conversations.

### Actual behaviour
The groupe-chat disappears from the list of conversations so that it would be necessary to join the chat over and over again to see what people are writing.
Staying in the group-chat seams to be possible if an admin adds the member.
It seams not possible to join the goupe-chat by searching for it via the "search conversations or contacts"-field.

## Browser
Mozilla Firefox 75.0 (64-bit)
**Operating system:** Windows 10

## Talk app
**Talk app version:**  8.0.8

**Comment by nickvergessen** [comment]
That is a recently common misunderstanding of how we imagined public calls should work.
Ref https://github.com/nextcloud/spreed/issues/1763 and https://github.com/nextcloud/spreed/issues/2784

I will close this as a duplicate.
