### ISSUE TITLE
Grey out "Start call" button if user is not allowed to start a call (and provide explanatory tooltip)

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3436]
If a user is not allowed to start a call we should hide the "start call" button completely, not just disable it. I don't think it makes sense to show a disabled button for a action a user will never be able to perform.

cc @nextcloud/designers

**Comment by ma12-co** [comment]
Totally makes sense

**Comment by jancborchardt** [comment]
If we remove the button, people might never know it’s even possible to do calls with Nextcloud Talk. And then _if_ someone does start a call, they don’t know how to join it.

What we should do is not only disable the button, but also on click/hover/focus of it show a tooltip saying why:

> Guests can not start calls on their own, only join those started by other participants.

**Comment by nickvergessen** [comment]
I wondered if we should even change the text already to join for such users?

**Comment by jancborchardt** [comment]
> I wondered if we should even change the text already to join for such users?

In that case it seems then as if a call is already active (which you can’t join as it shows as disabled), which is more confusing.

**Comment by schiessle** [comment]
> If we remove the button, people might never know it’s even possible to do calls with Nextcloud Talk. 

They are typically guests. They don't have to know that someone else can start calls if they can't. It is enough if they know that they can join a call if there is a ongoing call. For example they also don't know that a moderator could enable a lobby and many other features. I think the user interface should be optimized based on usefulness, easy to use and as less clutter as possible. That's the wrong place to "advertise Talk features". We also don't show the sidebar tabs only available for logged in users or the admin/moderator settings grayed out to show the guest what Nextcloud Talk could do.

Also depending on the theme it is really hard to distinguish between a disabled and enabled button.

**Comment by nickvergessen** [comment]
There is a huge difference between the call button and other moderator/admin features.
We still get a lot of complains about people not being able to find the join button, so hiding the "Start call" button is very contradicting to that from my POV.

**Comment by bes1002t** [comment]
I strongly agree to @jancborchardt thoughts. It is confusing for users if they usually see a button (probably in another nextcloud installation) and in this case there is no button. It's not about whether the user is Guest on this installation nor whether it forgot to login. If someone knows about Nextcloud and is familiar with its UI, it would be more user friendly to disable the button and show a tooltip that the user does not have sufficient permissions.

**Comment by schiessle** [comment]
> There is a huge difference between the call button and other moderator/admin features.
We still get a lot of complains about people not being able to find the join button, so hiding the "Start call" button is very contradicting to that from my POV.

Even after the inline "join call" button within the chat view? For me this was a great improvement! I'm all for making it intuitive and easy discoverable. But if people don't see the "join call" button I wonder if a disabled "start call" button at the same place will help.

Quite the opposite. With the disabled "start call" button the user might be used to have a useless GUI element at the top right and might not notice that the button changed to "Join call" and got enabled. While on the other hand, when all of the sudden a button "join call" pops up on a otherwise white area it might draw way more attention to it.

**Comment by jancborchardt** [comment]
Folks, it’s useless to have an endless discussion on it. Hiding the call button in any way will make one of the core things of Talk way less discoverable, so we are not doing it.
