### ISSUE TITLE
Video calls work intermittently - Poor signalling

### ISSUE THREAD

**Issue by tdm4** [nextcloud/spreed#3439]
## Steps to reproduce
1. Go into a channel, start a call
2. Get another person to join the call

### Expected behaviour
The two parties should be able to see and hear each other

### Actual behaviour
1. 1st party initiates call.
2. 2nd party joins call.
3. 1st party only sees spinning circle.
4. Neither party has audio or visual.
5. Both parties disconnect call.

Repeat first scenario 2-3 times, with each party taking turns initiating calls.

1st party initiates call.
2nd party joins call.
1st party only sees spinning circle.
2nd party can see and hear 1st party, but cannot enable their own cam or mic.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Linux

**Browser name:** Firefox and Chromium (browsers only)

**Browser version:** 75 (Firefox) or 81 (Chromium)

### Browser log
<details>

```
web console log:

Setting current user App.vue:289
Current participant found CallButton.vue:92
Current participant found CallButton.vue:92
The request has been canceled 
{…}

message: undefined

<prototype>: Object { toString: toString(), __CANCEL__: true, … }
MessagesList.vue:459
Stop pulling messages after repeated failures signaling.js:495:13    _startPullingMessages signaling.js:495
```

</details>

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: OpenBSD 6.7 GENERIC.MP#159 amd64

**Web server:** OpenBSD httpd (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.2 on x86_64-unknown-openbsd6.6, compiled by OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1), 64-bit

**PHP version:** 7.3.17
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, calendar, ctype, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, json, mbstring, session, PDO, bz2, posix, readline, Reflection, standard, SimpleXML, sockets, sodium, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, gd, imagick, intl, pcntl, pdo_pgsql, pdo_sqlite, pgsql, redis, zip, Zend OPcache

**Nextcloud Version:** 18.0.3 - 18.0.3.0

**List of activated apps:** 

<details>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - gpxpod: 4.2.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - passwords: 2020.4.1
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - rainloop: 6.1.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.8
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.8.0
 - user_sql: 4.5.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.pertho.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/mynextcloud.example",
    "overwritehost": "mynextcloud.example",
    "overwriteprotocol": "https",
    "dbtype": "pgsql",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "version": "18.0.3.0",
    "logtimezone": "Europe\/London",
    "installed": true,
    "default_language": "en",
    "defaultapp": "files",
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": false,
    "token_auth_enforced": false,
    "auth.bruteforce.protection.enabled": true,
    "mail_smtpmode": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "has_internet_connection": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0
    },
    "loglevel": 2,
    "theme": "",
    "maintenance": false,
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "integrity.check.disabled": true,
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "calendar",
        "rainloop"
    ],
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***"
}
```

</details>

### Server log (data/nextcloud.log)

Nothing applicable in the server log

### Extra Notes and Questions

When these calls fail, often the conversation will say there is an active call going on when there isn't one.

I had to join the non-existent call and leave it a few times for Nextcloud Talk to "see" the call actually wasn't there.

How is this signalling handled? Is it based on sessions? I have sessions stored in redis, and the keys do have a TTL which I can watch as it decreases. 

Or is it based on the turnserver entries?

How does Talk know who to send peering messages for signalling?

**Comment by tdm4** [comment]
coturn config:

<details>

```
lt-cred-mech
fingerprint
use-auth-secret
static-auth-secret=<SOMEREALLYLONGHEXSTRING>
realm=<SAME DOMAIN AS MY NEXTCLOUD>
total-quota=100
bps-capacity=0
stale-nonce
no-multicast-peers
external-ip=<MY EXTERNAL IP>/<INTERNAL IP>
redis-userdb="ip=127.0.0.1 dbname=1 port=6379 connect_timeout=10"
redis-statsdb="ip=127.0.0.1 dbname=2 port=6379 connect_timeout=10"
syslog
no-tls
no-dtls
```

</detalis>

**Comment by tdm4** [comment]
Now when I start a call and the other person tries to join, Nextcloud Talk says they joined the call but I don't see them, I just see:

Waiting for others to join the call  (with the grey paperclip)

Other person gets the same screen. It's like the site doesn't know how to join the two callers together.

<details>

```
main.js:566 JQMIGRATE: Migrate is installed, version 1.4.1
notifications.js:21 Proxying an event bus of version 1.1.2 with 0.2.1
t @ notifications.js:21
main.js:1082 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ main.js:1082
talk.js:1585 Setting current user
3z3wpcqe:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden">​…​</form>​
talk.js:562 Current participant found
talk.js:116 Joined Object
talk.js:562 Current participant found
4/ocs/v2.php/apps/spreed/api/v1/signaling/3z3wpcqe:1 Failed to load resource: the server responded with a status of 404 (Not Found)
talk.js:116 Stop pulling messages after repeated failures
(anonymous) @ talk.js:116
talk.js:562 Joining call
talk.js:116 localMediaStarted
talk.js:590 The request has been canceled r
```

</details>

**Comment by tdm4** [comment]
I found if I clear out PHP sessions (I have them stored in redis), I could get the two callers to join the calls, but getting them properly connected with audio/video seems to not work.

**Comment by tdm4** [comment]
I'm seeing some stuck javascript happening, and even if someone has left the call and restarted their browser it says they're in a call. Something seriously messed up with the signalling or whatever tells Nextcloud Talk a call is in progress.

**Comment by nickvergessen** [comment]
The next version will be a lot more verbose in regards to feedback on errors with the signaling.
I hope that helps.

**Comment by tdm4** [comment]
Hmm I'm not sure if this is related by I've turned on php-fpm slow log (30 seconds) and been noticing:

```
[04-May-2020 14:37:01] WARNING: [pool www] child 88314, script '/nextcloud/ocs/v2.php' (request: "GET /ocs/v2.php") executing too slow (32.123573 sec), logging
[05-May-2020 11:00:00] WARNING: [pool www] child 88314, script '/nextcloud/ocs/v2.php' (request: "GET /ocs/v2.php?lookIntoFuture=1&lastKnownMessageId=2654&includeLastKnown=0") executing too slow (30.498457 sec), logging
```

Not sure what is making them execute so slowly. 30 seconds is a long time for a php script. I don't know if this is a red herring or an actual clue.

**Comment by tdm4** [comment]
Here's a slow log trace while someone is trying to join a call in progress:

<details>

```
[08-May-2020 10:07:03]  [pool www] pid 20527
script_filename = /nextcloud/ocs/v2.php
[0x000018bdc041d7f0] sleep() /nextcloud/apps/spreed/lib/Controller/SignalingController.php:197
[0x000018bdc041d6e0] pullMessages() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:170
[0x000018bdc041d5b0] executeController() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:99
[0x000018bdc041d4e0] dispatch() /nextcloud/lib/private/AppFramework/App.php:125
[0x000018bdc041d300] main() /nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php:47
[0x000018bdc041d290] __invoke() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d220] call_user_func() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d140] match() /nextcloud/ocs/v1.php:82
[0x000018bdc041d080] [INCLUDE_OR_EVAL]() /nextcloud/ocs/v2.php:24

[08-May-2020 10:09:53]  [pool www] pid 20527
script_filename = /nextcloud/ocs/v2.php
[0x000018bdc041da20] sleep() /nextcloud/apps/spreed/lib/Chat/ChatManager.php:266
[0x000018bdc041d930] waitForNewMessages() /nextcloud/apps/spreed/lib/Controller/ChatController.php:269
[0x000018bdc041d6e0] receiveMessages() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:170
[0x000018bdc041d5b0] executeController() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:99
[0x000018bdc041d4e0] dispatch() /nextcloud/lib/private/AppFramework/App.php:125
[0x000018bdc041d300] main() /nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php:47
[0x000018bdc041d290] __invoke() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d220] call_user_func() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d140] match() /nextcloud/ocs/v1.php:82
[0x000018bdc041d080] [INCLUDE_OR_EVAL]() /nextcloud/ocs/v2.php:24

[08-May-2020 10:09:53]  [pool www] pid 88878
script_filename = /nextcloud/ocs/v2.php
[0x000018bdc041d7f0] sleep() /nextcloud/apps/spreed/lib/Controller/SignalingController.php:197
[0x000018bdc041d6e0] pullMessages() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:170
[0x000018bdc041d5b0] executeController() /nextcloud/lib/private/AppFramework/Http/Dispatcher.php:99
[0x000018bdc041d4e0] dispatch() /nextcloud/lib/private/AppFramework/App.php:125
[0x000018bdc041d300] main() /nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php:47
[0x000018bdc041d290] __invoke() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d220] call_user_func() /nextcloud/lib/private/Route/Router.php:299
[0x000018bdc041d140] match() /nextcloud/ocs/v1.php:82
[0x000018bdc041d080] [INCLUDE_OR_EVAL]() /nextcloud/ocs/v2.php:24
```

</details>

**Comment by tdm4** [comment]
I did some more tests. I tried this:

1. Cleaned out redis PHP sessions
2. Restart php-fpm
3. Started a call and had 2nd party join it
4. Users could not see video at first. However, toggling video off then back on fixed that.

Could it have something to do with cleaning the php sessions to make it work?

**Comment by nickvergessen** [comment]
> I wonder if the signalling code is sending php into an endless loop?

Yes, or well not endless, but we do 30sec long polling.
See https://github.com/nextcloud/spreed/issues/3183#issuecomment-610332282 for further setup hints

**Comment by tdm4** [comment]
@nickvergessen I'm using OpenBSD's [httpd](https://man.openbsd.org/httpd) and php-fpm (v7.3.17).

php-fpm config:

<details>

```
[global]
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s
 
[www]
user = www
group = www
listen = /var/www/run/php-fpm.sock
listen.owner = www
listen.group = www
listen.mode = 0660
 
pm = ondemand
pm.max_children = 20
pm.process_idle_timeout = 10s
request_terminate_timeout = 120s
chroot = /var/www

;request_slowlog_timeout = 60s
;slowlog = /var/log/php-slow.log

env[PATH] = /bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

security.limit_extensions = 
```

</details>

Going to test with Nextcloud 18.0.4 and Talk 8.0.9 and see if anything has changed.

**Comment by tdm4** [comment]
I tested with guests (who don't have a Nextcloud account) and there were difficulties connecting. I'm going to have to shelve this for now.

**Comment by nickvergessen** [comment]
@tdm4  You can also try the external signaling backend which has been open sourced recently:
https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/
