### ISSUE TITLE
Shares should query parent and permissions

### ISSUE THREAD

**Issue by rullzer** [nextcloud/spreed#3440]
I see a lot of queries of the form:

```sql
SELECT `storage`
FROM `oc_filecache`
WHERE `fileid` = 'XYZ' 
```

As far as I can tell this is due to: https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/apps/files_sharing/lib/SharedMount.php#L249

Hence we should do something like https://github.com/nextcloud/server/blob/cde6d768de0c48d470e6585d9b688c241187e229/lib/private/Share20/DefaultShareProvider.php#L1053 as  well.

@icewind1991

**Comment by icewind1991** [comment]
Do you have a backtrace for the `getNumericStorageId` or do you know what request is triggering it?

**Comment by nickvergessen** [comment]
Should be all in https://github.com/nextcloud/spreed/blob/34a131da24eb315d3b5fd7f04f3f45bec5490904/lib/Share/RoomShareProvider.php I guess
