### ISSUE TITLE
small video stream on the bottom can overlap screensharing

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3448]
Tested with Talk 9.0-beta. When I share my screen, depending on the window size it can happen that the video streams at the bottom overlap the screensharing:

![image](https://user-images.githubusercontent.com/1589737/80964523-4f0c0f00-8e11-11ea-9731-c2eacc324543.png)

While for normal video calls it might be ok if the video of the other users overlap the speakers video, for screesharing I think that's highly disturbing. Depending on what you share the video could overlap important parts of the screenshare.

**Comment by nickvergessen** [comment]
It's not okay to overlap the video by 33% with tones of other avatars/videos and this was adjusted last week internally already and the fix will be pushed to stable18 soon.

For 19 we are still waiting for the Grid View to avoid further conflicts.
