### ISSUE TITLE
Annoying delay after starting a call

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/spreed#3454]
Hello
I try to set up a nextcloud talk environment with local turn-server. Until know it seems to work quite well, but I face the following problem:

Description:
When a user is starting a call, there is immediately a message in the talk-notification log that tells me "user YXZ started a call". But then only after some annoying delay of 10-20 seconds, the call gets available to participate by button "Join call".

Question:
Where could this delay come from? Is it maybe a general problem of nextcloud/talk, or is is maybe a network-configuration issue on my side. Sometimes it also happens that the delay is short like 2-3 secondes. But most of the time the delay is relay too long....

Thanks for your help
René

**Comment by nickvergessen** [comment]
its something between instant and 30 seconds. We update the conversation list every 30seconds and that info influences whether the button says "Join call" or "Start call". But pressing "Start call" will result in the same thing as pressing "Join call", so you can click it immediately.

We still have this on our todo in https://github.com/nextcloud/spreed/issues/1810 and https://github.com/nextcloud/spreed/issues/3377

**Comment by rgl1234** [comment]
Thanks for the prompt feedback and this information...
René

**Comment by nickvergessen** [comment]
Closing as per above
