### ISSUE TITLE
video area overlays the "Share from files" popup

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3455]
Tested with 19-beta. When I'm in a call and want to share a file to the chat on the sidebar the video area overlays the "Share from files" popup:

![image](https://user-images.githubusercontent.com/1589737/81067481-01f66e80-8edf-11ea-86d1-cdd0145a0c3a.png)

**Comment by ruedigerkupper** [comment]
I noticed that the "Share from files" pop up does not show at all when video is in full screen. Is this the same bug?

**Comment by nickvergessen** [comment]
Fixed with #4016
