### ISSUE TITLE
Messages Double Escaped for Most Recent Message in List

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/spreed#3459]
## Steps to reproduce
1. Send a message that has characters that must be escaped

### Expected behaviour
The message should be as sent.

### Actual behaviour
The message gets double escaped.

![image](https://user-images.githubusercontent.com/47195730/81085664-14e26080-8f2a-11ea-83e5-b1d8e4afe85b.png)
![image](https://user-images.githubusercontent.com/47195730/81085570-f41a0b00-8f29-11ea-875b-b94b69e771b0.png)

## Talk app

**Talk app version:** Version on `cloud.nextcloud.com`

**Comment by nickvergessen** [comment]
See #3451
