### ISSUE TITLE
Cannot add a participant to a room if the user joined the call via public link

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3462]
Veeeeeerry specific edge case :grin: 

## Steps to reproduce
1. Be user0 on a server
2. Create a room with share link enabled 
3. Login as user1
4. Open talk
5. See that the Room is NOT there
4. Access the call via share link while still being logged
5. As user0, try to add user1 to the room

### Expected behaviour
You can add it to the room

### Actual behaviour
You can't add it to the room as it appear in the participant list, while *technically* not being part of the room *official* user list.

**Comment by PVince81** [comment]
I assume that the wanted solution here is that if a moderator is adding a user while they are "USER_SELF_JOINED" we simply convert them to "USER" so they become a "true" participant.

**Comment by nickvergessen** [comment]
Yeah

**Comment by PVince81** [comment]
I just tried the steps and looking at the UI I don't know how as user0 I would come to the idea of trying to add user1 since I already see that user in the participant list.

And even if we allowed this, it means tweaking the UI to make it visually clear that this user1 is not "fully joined", so that user0 could decide to add the user permanently.

**Comment by nickvergessen** [comment]
This comes from our instance where people open public conversations and ask to be added, but you as a moderator have to kick them before you can search and add them.
I guess it would also be fine to allow searching them and clicking them would add them. so basically 
https://github.com/nextcloud/spreed/blob/459858a69527311bf60ffa553d45ba2a7eeec032/lib/Chat/AutoComplete/SearchPlugin.php#L103-L110
would need to ignore `USER_SELF_JOINED` so they are still returned as options

**Comment by PVince81** [comment]
Also an interesting effect in the current implementation is that if you add the group of the self-joined users, there is no error but they don't get permanently added either.

So this will need handling as well.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/6a019ed418f86185fb19ca520dc576f128758fcb/lib/Controller/RoomController.php#L1250-L1252

I guess `$this->participantService->getParticipantUserIds(` should be replaced with `getParticipantsForRoom` then so we can check the type and run an update.

**Comment by PVince81** [comment]
Draft PR here https://github.com/nextcloud/spreed/pull/5048
