### ISSUE TITLE
As guest or un-invited user, the room load all the messages

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3463]
## Steps to reproduce
1. Join a room as guest or as a logeed user not part of a public room
2. See 30s of loading of all messages
3. Log in as a user belonging to a room
4. See the last 10 messages being loaded ONLY

### Expected behaviour
Same as logged participants, should only load the last xx, not the full list

**Comment by nickvergessen** [comment]
Only happens with HPB

**Comment by nickvergessen** [comment]
Fixed by #3292 already, as it makes sure the room join response is used when the chat is grabbed
