### ISSUE TITLE
Idea: another performance improvements for large rooms

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3478]
We have many great performance improvements for Talk 9.... While thinking about them I had another idea. I don't know if it is technically possible, but if it is possible this could be another real boost.

With Talk 9 you will be able to scroll through the videos at the bottom. This reduces the CPU load at the clients a lot because they only have to render a fixed number of videos. But the user still receive all video stream which means that you can still reach client-side bandwidth limitations quite fast.

Now my idea: Would it be possible to tell the HPB my scroll position so that it only sends me the videos I have selected at the moment + the speaker and pause the other streams?

If this would be possible, the client would not only have to render a fixed number of streams but also only receive a fixed number of streams. Completely independent from the room size. This would enable people to really have rooms with a "infinite" number of participants. The CPU load and the needed bandwidth would be always the same.

Also the HPB would only send a fixed number of streams to all participants and could handle much larger and/or more rooms.

The main challenge (and maybe the reason why it doesn't work at the end) is to switch the speaker stream fast enough if someone starts speaking.

**Comment by nickvergessen** [comment]
No
