### ISSUE TITLE
Copy pasting screenshots only works when chat input is focused

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3482]
Follow up to #3399 

Should also work when the chat input is not focused.

**Comment by nickvergessen** [comment]
cc @fsxadmin in case you want to fix this.

**Comment by nickvergessen** [comment]
cc @guryanovev  in case you want to fix this.

**Comment by PVince81** [comment]
might need to clarify what else is allowed to be focussed.
if I'm in the search box on the top right or the search box for conversation, pasting an image should do nothing

maybe the browser focus is on an element that is not an input field (except the send message form), then trigger pasting

it seems it will require some hacks, as some browser don't trigger the paste event outside of input fields: https://stackoverflow.com/a/24705589

I personally think it's fine to need to be in the input field as I cognitively connect sending an image to sending a message (just like with emojis).

**Comment by nickvergessen** [comment]
Yeah i think the origin of this was that the input was unfocused after an upload, so you could systemkey+tab to another window copy another file and come back to repaste it.

**Comment by PVince81** [comment]
and we fixed that already with https://github.com/nextcloud/spreed/issues/4242
