### ISSUE TITLE
Call view in sidebars is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3483]
## Steps to reproduce
1. Go to a file
2. Share it
3. Go to the Talk tab and start the call on the file

### Expected behaviour
You have a call and see mostly the other user, or a grid, or ...

### Actual behaviour
You overlap almost everything.

**Comment by nickvergessen** [comment]
cc @jancborchardt what was the expected result again?

**Comment by jancborchardt** [comment]
- Only show the promoted speaker in large
- Your own video in quite small overlaid on the bottom right
- Only audio and video controls for you (fade out after some seconds of not moving mouse / interacting keyboard over it, just like in Talk)
- Names won’t fit so no need to display them.
- The screensharing button doesn’t need to be there either as no one will screenshare in there. ;)
