### ISSUE TITLE
When closing right side bar during call, the icon for getting it back is invisible

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/spreed#3486]
## Steps to reproduce
1. Start a call in Nextcloud Talk
2. When video is shown, close right side bar clicking the »X« icon.
3. Try to get the sidebar back.
4. Observe that the icon for doing so (normally shows three bars with two silhouettes) is invisible.
5. It still can be clicked and works as intended, it just isn't visible. 

### Expected behaviour
The "show sidebar" symbol is visible while video is displayed.

### Actual behaviour
It is invisible, but still there.

## Browser
Confirmed in Chromium 81.0.4044.138 (latest snap) and recent Firefox.

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu

**Browser name:** Firefox/Chromium

**Browser version:** Chromium 81.0.4044.138 (latest snap) and recent Firefox

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes (coturn)

**Custom STUN server configured:** yes (coturn)

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.17

**Nextcloud Version:** 18.0.4 (snap)

**List of activated apps:**

<details>
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - audioplayer: 2.10.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - cospend: 0.5.1
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_external_gdrive: 0.4.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - radio: 0.6.6
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - calendar
  - encryption
  - files_external_dropbox
  - theming
  - user_ldap
  - workflow_script

</details>

**Comment by nickvergessen** [comment]
Duplicate of #3404 ?

**Comment by ruedigerkupper** [comment]
Yes, it is! Thank you!
