### ISSUE TITLE
Add an option to activate notification on all devices

### ISSUE THREAD

**Issue by rebootit** [nextcloud/spreed#3499]
I have quit often my laptop muted or with the volume low and my phone have the app Talk installed, so I miss a lot of notifications if not all.

I understand that you made this choice to not have too much notifications but it doesn't work for me and for all the users / coworker that I know,  an option to activate all the notifications on all device seem a good compromise.

Thanks for your consideration and for all your work.

Mathieu R

**Comment by nickvergessen** [comment]
I'm not sure what you mean. We do send notifications, just not for the one conversation that is open.

**Comment by rebootit** [comment]
If have Nextcloud open on the browser I don't get the notification on smartphone. At fist I through it was a bug/misconfiguration but I read somewhere here on I closed issue that it was on purpose "to not have your phone vibrating on your pocket while chatting" or something like that (sorry not my language).

**Comment by nickvergessen** [comment]
Yeah but that is only for the very same conversation.

**Comment by rebootit** [comment]
An option to have notifications all the time for each reply would be nice, even in the same conversation (we went back to Signal at work because of the missed reply)
