### ISSUE TITLE
Chat integration

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#35]
Do research together with the chat app to see how this works seamless together.

**Comment by jancborchardt** [comment]
cc'ing @sualko and @LEDfan of the Chat app here. What do you think? How can we ideally integrate this?

We already discussed it with the »Contacts menu« https://github.com/nextcloud/server/issues/207 and we should have some nice integration with Chat for sure!

Also cc @Henni of the Contacts app and @schiessle for federation.

**Comment by LEDfan** [comment]
Hey. This repo is about porting spreed.me to PHP? Or is it an adapter to the real spreed.me?

My comments in https://github.com/nextcloud/server/issues/207#issuecomment-232711189 are still also valid for this.

The best option for me looks like splitting the Chat option and the conference part. (Note that JSXC also supports WebRTC, but I'm not sure if it can be used as a conference too? @sualko )
This way both apps can be installed separately and if wanted a more strong server (XMPP) can be installed.

BTW what (protocol, implementation) will be used for the signaling of WebRTC in this implementation?

**Comment by sualko** [comment]
I agree with @LEDfan.

>  I'm not sure if it can be used as a conference too?

Not now, put it is on the roadmap.

**Comment by Bugsbane** [comment]
I'm also curious to see how this ties in to integrating chat contacts with contacts from other apps (eg NC users, mail contacts etc). I'm really hoping we can take a similar approach to Android, where it keeps a central list of contacts with other apps adding in their own user lists.

For example in Android you have contacts, and if you install Skype, then your Skype contacts appear in your contacts as well. Similarly, NC could have it's own contacts and Mail / Chat / NC / Spreed can all hook their own contact lists into this (and of course unhook them if those apps are uninstalled).

I'm really hoping we can avoid growing an already confusing situation where there are different contacts available in different apps, and the user has to remember which users are available in which apps, often duplicating them to make them available cross-app. Of course this depends on having systems to figure out when two+ user accounts from different apps are really the same person (ie they have matching user info such as the same email address, phone number etc).

**Comment by jancborchardt** [comment]
@Bugsbane we already do this ;) Mail as well as Spreed simply source from the [Contacts app](https://github.com/nextcloud/contacts). Spreed and sharing in apps also source from the users on that Nextcloud, and some can handle federated sharing.

**Comment by Bugsbane** [comment]
I'm glad to hear that some of this already exists, however I wouldn't say we do it completely.

For example, on my install, I have most of my family members set up as users with their email and avatar pictures set. When I get an email from them though, Mail doesn't recognize that it's the same person, despite Nextcloud knowing that the email address is the same.

Consequently emails from my family are displayed with a generic single letter avatar, instead of their profile picture.

If we're being smart about contacts, then really, whether someone is created in the Nextcloud users section or the contacts section, then we should recognize from the matching entered into (such as email or federated ID) that they're the same person, instead of having to enter the same info (such as avatars) twice.

**Comment by jancborchardt** [comment]
@Bugsbane good point and I agree completely. However this is a separate issue then – can I ask you to please open it in https://github.com/nextcloud/server/issues as improvement for the users+contacts backends? :)

**Comment by Bugsbane** [comment]
Absolutely. Will do.

**Comment by putt1ck** [comment]
Ref chat: will it be possible (future feature!) to associate a chat session with a file or folder, with the chat(s) stored for reference, available to anyone with read or better permissions for the associated object? Thinking about collaboration on projects where the collaboration is distributed not only by geography but also over considerable lengths of time (years to decades); sometimes the best explanation for "why was this done" is the conversation between those who decided to do it - but may have moved to other projects a long time ago.

**Comment by jancborchardt** [comment]
@putt1ck this is already possible now with comments on files. :) Just open the details sidebar of a file, and in the comments tab you can collaborate with comments over considerable lengths of time, as you require. :)

**Comment by putt1ck** [comment]
@jancborchardt comments are very useful (and a good alternative for Kanban cards) - but are for existing docs/folders, rather than what initiated them. I guess what I'm asking for is a way to export/copy a chat session into comments on a new file/folder

**Comment by jancborchardt** [comment]
@putt1ck can I ask you to open a separate issue for this? :) Cause this issue is about basic chat integration first.

**Comment by nickvergessen** [comment]
Now handled in #294

**Comment by petrk94** [comment]
Hey is the feature already integrated?
Is still as feature open in [Coming Versions](https://github.com/nextcloud/spreed#why-is-this-so-awesome)

**Comment by jancborchardt** [comment]
@petrk94 as @nickvergessen said above:

> Now handled in #294

**Comment by rgarrigue** [comment]
The README.md includes a link to this issue that should be updated then

**Comment by nickvergessen** [comment]
Yes, we will, together with all the screenshots and stuff ;)
