### ISSUE TITLE
Some participants can't hear each other

### ISSUE THREAD

**Issue by Nyco** [nextcloud/spreed#3507]
## Steps to reproduce
1.Create a room with several participants (more that three-four) with HPB
2. Launch a call
3. Let everyone unmute and test/validate their sound setup with microphone + (speakers or head/earphones)
4. Each participant can hear each other, except a pair

### Expected behaviour
Each participant should be able to hear and speak to every one else without exceptions

### Actual behaviour
Alice, Bob, Carol, Dave, etc. join a call
* Alice can hear everyone else except Bob
* Bob can hear everyone else except Alice
* Carol can hear everyone else
* Dave can hear everyone else
Etc.

### Problem

This is very annoying, since you can't realise it immediately.

For example, for Alice to realise she can't hear Bob, it is necessary Bob clearly speaks alone for a long enough time (seconds to minutes, whether the cam is enabled or not). Then Alice tells everyone she can't hear anything from any one, or asks what happens since she believes no one speaks.

When it is clear to participants that Alice can't hear Bob and Bob can't hear Alice, then other participants have to repeat what they say.

## Browser

**Microphone available:** yes

**Camera available:** yes/no => does not apply

**Operating system:** Several

**Browser name:** Several

**Browser version:** Several

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**:

**Web server:**
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips (fpm-fcgi

**Database:**
mysql 5.5.56

**PHP version:**
7.2.17
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, gnupg, imagick, smbclient, zip, libsmbclient, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
18.0.3 - 18.0.3.0

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Then you are mostlikely missing a turn server.
See https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by Nyco** [comment]
We are not lacking a TURN server.

**Comment by nickvergessen** [comment]
The HPB does not replace a TURN server.

Anyway, if you have a subscription you should report your questions directly to the Nextcloud Portal.
Otherwise you need to search the forum for solutions https://help.nextcloud.com/

**Comment by Nyco** [comment]
We are reporting a bug.
