### ISSUE TITLE
All videos in line at bottom, yours is upper

### ISSUE THREAD

**Issue by Nyco** [nextcloud/spreed#3508]
## Steps to reproduce
1.Create a room with several participants (more that three-four)
2. Launch a call
3. All participants' videos are aligned at the bottom of the browser window, except yours which is upper than the others

### Expected behaviour
All participants' videos should be aligned at the bottom of the browser window without exception

### Actual behaviour
Your own video is slightly upper than the other's

I understand and I assume it is intended either to let some room to display the "Share screen" button, or to show a differentiated view of your own video feedback

### Suggestions
Display your own video feedback differently, for example a colored border, and/or colored controls (mic, cam, screen).

## Browser

**Microphone available:** yes/no does not apply

**Camera available:** yes/no does not apply

**Operating system:** Windows/Ubuntu/...  does not apply

**Browser name:** Firefox/Chrome/... does not apply

**Browser version:** 50.1/55/...  does not apply

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
This will change in the upcoming Talk 9 release as per #3330
