### ISSUE TITLE
Add an option to have a notification on each reply

### ISSUE THREAD

**Issue by rebootit** [nextcloud/spreed#3521]
I miss a lot of reply.

I think it is fine to have a notification only when a conversation is created but an option to have a notification on all reply would be nice.
Thank you for your consideration and all your work.

**Comment by nickvergessen** [comment]
Notifications are done for replies and mentions by default.

Are you confusing activities with notifications?

**Comment by rebootit** [comment]
You said on my previous message: 

> We do send notifications, just not for the one conversation that is open.

I just want to have a notifcation when someone reply. Now I have only one when a conversion is created and on on the firt reply, after I don't.

But I cannot be understand, I'll  ask someone with a better English to open a feature request

**Comment by nickvergessen** [comment]
Maybe you can post screenshots of what you mean?

**Comment by klada** [comment]
I am assuming this refers to the chat feature. I also do not get **reliable** notifications in chats, not even when I am being mentioned. Notification for the conversation is set to "All messages".

Maybe this is a duplicate of #1575

**Comment by Refhi** [comment]
Indeed there are times where having a notification for each reply, even if there's an opened client would be precious

**Comment by nickvergessen** [comment]
Duplicate of #1575  indeed
