### ISSUE TITLE
Missing invitation e-mail for registered users

### ISSUE THREAD

**Issue by MartinKoeditz** [nextcloud/spreed#3523]
## Steps to reproduce
1. Start a new Conversation
2. Add registered user
3. Add external user by email

### Expected behaviour
The registered user should receive e-mail.
The external user should receive e-mail.

### Actual behaviour
The invited user doesn't receive an invitation e-mail.
The external user receives an invitation e-mail.

## Browser

**Microphone available:** no

**Camera available:** no

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 76.01 x64

## Server configuration

**Operating system**: OpenSuse Leap 15.1

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.2.5

**Nextcloud Version:** 18.0.4.2

**List of activated apps:** OnlyOffice, Talk, Mail

**Nextcloud configuration:**

### Server log (data/nextcloud.log)
<details>
empty
</details>

**Comment by nickvergessen** [comment]
Registered users receive a notification instead and can be notified via emails on the activity

**Comment by MartinKoeditz** [comment]
Well, that's true. But the activity mail doesn't contain a link to the conversation. So the (usual) CEO doesn't know what to do next. The external user has a link to join the conversation. In that case it's easier for the external user to join the conference than for the internal user.

**Comment by nickvergessen** [comment]
Right, fix is in https://github.com/nextcloud/spreed/pull/3528

**Comment by MartinKoeditz** [comment]
Thank you.
