### ISSUE TITLE
Faces cut off in promoted view

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3524]
## Steps to reproduce
1. Start a promoted view call with 3 participans and videos
2. Check the non-promoted users

### Expected behaviour
Full face is visible

### Actual behaviour
Faces are cut off very oddly

![Bildschirmfoto von 2020-05-13 13-22-50](https://user-images.githubusercontent.com/213943/81810642-971ee600-9523-11ea-8f13-53af12c9b801.png)

**Comment by wiswedel** [comment]
also applies when someone shares their screen

**Comment by nickvergessen** [comment]
The following diff works pretty fine, but it should basically only be applied when in the "bottom strip of the promoted view". Is there another class I can use to check this, @ma12-co ?

```diff
diff --git a/src/components/CallView/shared/Video.vue b/src/components/CallView/shared/Video.vue
index 98f98df4..3a4cf0db 100644
--- a/src/components/CallView/shared/Video.vue
+++ b/src/components/CallView/shared/Video.vue
@@ -419,6 +419,10 @@ export default {
        overflow: hidden;
        display: flex;
        flex-direction: column;
+
+       &:not(.video-container-big) {
+               max-width: calc(250px * 16 / 9);
+       }
 }
 
 .video-container-big {
```

**Comment by ma12-co** [comment]
This has to be fixed in the `shrinkgrid` method @nickvergessen
