### ISSUE TITLE
Access to microphone & camera failed DOMException: Permission denied

### ISSUE THREAD

**Issue by Mic-Pod** [nextcloud/spreed#3530]
## Steps to reproduce
1. Chromium browser (Chrome, Edge v81)
2. Nextcloud 18.0.4 + Talk 8.0.8
3. Properly configured coturn server as described in various tutorials & docs
4. Start new conversation and start call

### Expected behaviour
User should be able to use microphone & camera on chromium-based browsers

### Actual behaviour
User can not use microphone & camera on chromium-based browsers (Error: Access to microphone & camera failed DOMException: Permission denied)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10 1909

**Browser name:** Chrome, Edge

**Browser version:** 81

### Browser log

<details>
Joined {data: {…}, status: 200, statusText: "", headers: {…}, config: {…}, …}
CallButton.vue:162 Joining call
webrtc.js:813 Access to microphone & camera failed DOMException: Permission denied
CallButton.vue:173 Leaving call
CallButton.vue:162 Joining call
webrtc.js:813 Access to microphone & camera failed DOMException: Permission denied
CallButton.vue:173 Leaving call
CallButton.vue:162 Joining call
webrtc.js:813 Access to microphone & camera failed DOMException: Permission denied
CallButton.vue:173 Leaving call
</details>

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.4

**Nextcloud Version:** 18.0.4

**List of activated apps:**

<details>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - breezedark: 18.0.15
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - federation
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - survey_client
  - systemtags
  - user_ldap
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by Mic-Pod** [comment]
Camera and microphone:

- works on Firefox

- are enabled in Windows Settings

- are working on other sites in Chrome (eg. Jitsi)

**Comment by nickvergessen** [comment]
Is your site using https?

**Comment by Mic-Pod** [comment]
Of course. HTTPS with valid SSL cert.

**Comment by nickvergessen** [comment]
Is your webcam used by another browser/program while trying? Because that will not work.

**Comment by Mic-Pod** [comment]
I know. Nothing is using the webcam during the testing.

**Comment by Mic-Pod** [comment]
Hmmm... I have deployed secondary Nextcloud instance on the same server and now everything works. Maybe something was messed up with the old one...

**Comment by Mic-Pod** [comment]
This is now even stranger... I have returned to the old instance without changing anything and now Talk works...
