### ISSUE TITLE
Can't reach Talk in a webbrowser after updating to 8.0.9

### ISSUE THREAD

**Issue by Byter3** [nextcloud/spreed#3533]
## Steps to reproduce
1. Updating Talk to 8.0.9
2. Navigate to Talk in webrwser
3.

### Expected behaviour
See Talk

### Actual behaviour
Blank page loads
Also Can't modify Talk's settings in the admin panel.

## Browser

Windows

Firefox/Chrome/Edge

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 	7.2.24

**Nextcloud Version:** 18.0.4

**List of activated apps:**

**Comment by nickvergessen** [comment]
Fixed already, I forgot one little command while building the archive, grab a new package from https://github.com/nextcloud/spreed/releases/tag/v8.0.9

Sorry for the inconvinience.

**Comment by Byter3** [comment]
There is no way that you could push it as an update? I'm running a univention image and really don't want to manually download it.
