### ISSUE TITLE
Fixing URLs of APIv1 before they are set in stone

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#354]
## Current Mapping

* `/api`
  * `/{apiVersion}`
    * `/ping` - `POST` your "I'm still here"
    * `/leave` - `DELETE` when you leave the app or close the browser
    * `/oneToOne` - `PUT` create a one2one call - **Suggested**: `/api/{apiVersion}/room/oneToOne` because you create items in the `/room` collection
    * `/group` - `PUT` create a group call - **Suggested**: `/api/{apiVersion}/room/group` because you create items in the `/room` collection
    * `/public` - `PUT` create a public call - **Suggested**: `/api/{apiVersion}/room/public` because you create items in the `/room` collection
    * `/room` - `GET` all rooms
      * `{token}` - `GET` room publicly
        * `/peers` - `GET` connected peers
        * `/join` - `POST` to a call that you are now there
      * `/{roomId}` - `PUT` rename a call
      * `/{roomId}` - `POST` add a participant - **Suggested**: `/api/{apiVersion}/room/{roomId}/participants`
      * `/{roomId}` - `DELETE` remove yourself from a room - **Suggested**: `/api/{apiVersion}/room/{roomId}/participants/self` - `/participants` required so we can delete a room by id as a owner/moderator; `/self` required because `DELETE` on `participants` will be used for the moderator action to delete a user
        * `/moderators` - `POST` promote a participant to be a moderator
        * `/moderators` - `DELETE` demote a moderator
      * `/public` - `POST` make a call public - **Suggested**: `/api/{apiVersion}/room/{roomId}/public` - instead of sending the id in the payload
      * `/public` - `DELETE` make a call private - **Suggested**: `/api/{apiVersion}/room/{roomId}/public` - instead of sending the id in the payload

## New mapping

`/api`

- `/{apiVersion}`
  - `/ping` - `POST` your "I'm still here"
  - `/leave` - `DELETE` when you leave the app or close the browser
  - `/room` - `GET` all rooms
    - `/{token}` - `GET` room publicly
      - `/peers` - `GET` connected peers
      - `/join` - `POST` to a call that you are now there
    - `/{roomId}` - `PUT` rename a call
    - `/{roomId}` - `DELETE` delete a room 🆕
      - `/moderators` - `POST` promote a participant to be a moderator
      - `/moderators` - `DELETE` demote a moderator
      - `/participants` - `POST` add a participant
      - `/participants` - `DELETE` remove a participant 🆕
        - `/self` - `DELETE` remove yourself from a room 🛠
      - `/public` - `POST` make a call public 🛠
      - `/public` - `DELETE` make a call private 🛠
    - `/oneToOne` - `PUT` create a one2one call 🛠
    - `/group` - `PUT` create a group call 🛠
    - `/public` - `PUT` create a public call 🛠

Makes sense @Ivansss @fancycode

**Comment by nickvergessen** [comment]
Or we move the "create a X call" methods even to `POST /api/{apiVersion}/room` and add the room type to the post data with the room name. Would also make sense.

**Comment by fancycode** [comment]
All methods above are for persistent room handling (i.e. not for calls), right? We should try to make everything that is non-persistent and realtime (i.e. for calls) similar to what is being worked on in #339 to avoid having different APIs for the PHP backend and the standalone signaling server.

**Comment by fancycode** [comment]
So imho the realtime signaling part should only have endpoints like

`/api`
- `/{apiversion}`
  - `/signaling` - `POST` send events
  - `/signaling` - `GET` (long) poll for events

The events then can be arbitrary JSON objects that are handled by the server. For the standalone signaling server, we can use a WebSocket connection and send/receive the same objects.

**Comment by nickvergessen** [comment]
Right, in that case the following two should be renamed to call
* `/api/{apiVersion}/room/{token}/peers` - `GET` connected peers
* `/api/{apiVersion}/room/{token}/join` - `POST` to a call that you are now there

Also `/ping` and `/leave` should be in `/api/{apiVersion}/call`

About signaling, it is currently on the index.php not the ocs/v2.php because the event source doesn't work well with ocs specs.

**Comment by nickvergessen** [comment]
Done in #349
