### ISSUE TITLE
"Add-user"-box glitches 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/spreed#355]
After starting the app for a second:

<img width="261" alt="bildschirmfoto 2017-07-11 um 12 25 45" src="https://user-images.githubusercontent.com/19711361/28064245-2bc52df4-6634-11e7-97ed-2e6a46350be1.png">

@Ivansss

**Comment by nickvergessen** [comment]
Happens for me all the time, until I gave media permissions. I think there are no js/css files loaded/executed by the browser until that is done?
