### ISSUE TITLE
9.0.0beta1: Incorrect display of conversation menu

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#3556]
## Steps to reproduce

1. Create only one conversation.
2. Click on the conversation menu.

### Expected behaviour
Correct display of the conversation menu.

### Actual behaviour
Incorrect display of the conversation menu.

![obraz](https://user-images.githubusercontent.com/47037905/81918365-a6ab3700-95d6-11ea-8d07-da7909574bf7.png)

## Browser

**Operating system:** Windows/Ubuntu/...
Win10

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 50.1/55/...
76.0.1

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
9.0.0-beta.1

## Server configuration

**Nextcloud Version:** (see admin page)
19.0.0 RC1

**Comment by Valdnet** [comment]
For Nextcloud 19.0.0 RC2 version is now working correctly.

**Comment by nickvergessen** [comment]
I guess it's the same issue as #3539

**Comment by Valdnet** [comment]
> I guess it's the same issue as #3539

I think so too.

The problem was solved by installing Nextcloud 19.0.0 RC2. I don't know if you want to correct it.

**Comment by Valdnet** [comment]
The problem reappeared in the version Talk 9.0.0 RC1.
