### ISSUE TITLE
Video Layout - superposed

### ISSUE THREAD

**Issue by Charli-T** [nextcloud/spreed#3572]
Hi I am trying this app and really like it but I noticed some strange behaviour during video calls, with three participants.

Here we go

## Steps to reproduce
1. Invite two participants to your video call, using a public link with password.
2. Try it with Safari Browser from Mac OS and tell them to use Chrome browser from Windows 10 OS.
3. Start talking as the host speaker to both of them and observe their videos layout.
4. During the conversation they will also experience how the active window (speaker) is hidden by one of the other listeners window.
5. Try the same thing sharing your screen with them and the main window will be. in a same way, eclipsed by the others instead of reorganizing in a proper way, "responsive", the three windows.
 
### Expected behaviour
Active participant must be in a main window surround by the other windows, but not superposed by one of the others causing a poor user experience during a conversation.

### Actual behaviour
When there are two guests in a three-side conference, one of the others window will appear superposed to the active (speaker) window.

Thank you,
Charli

**Comment by nickvergessen** [comment]
Can you add a screenshot and most important say which version you are refering to?

**Comment by Charli-T** [comment]
Sure.
It is Talk Version 8.0.8 
Screenshot:
![VideoLayoutView](https://user-images.githubusercontent.com/17940453/81987355-bc057d00-9639-11ea-8874-87defba5fb2f.jpg)

**Comment by nickvergessen** [comment]
This should be a lot better in the newest version 8.0.9 which was released yesterday.

**Comment by Charli-T** [comment]
Ok I'll try it and feedback
Thank you

**Comment by Charli-T** [comment]
Here is the feedback

Talk version updated to 8.0.9
Host/captures: Safari version 13.1
Guests: Mozilla Firefox

Image A.  When the three participants are connected the first time
![A  3ParticipantsNormalWindow-HiddenHost](https://user-images.githubusercontent.com/17940453/82087052-a81c5280-96ef-11ea-9001-5b88140ec1c1.jpg)

Image B. this happened after clicking on the white band, behind the main window
![B  3ParticipantsNormalWindow-ClickBand](https://user-images.githubusercontent.com/17940453/82087109-bff3d680-96ef-11ea-88d4-db683566182a.jpg)

Image C. Resizing browser window manually to some point
![C 3ParticipantsNormalWindow-RefreshingResizing](https://user-images.githubusercontent.com/17940453/82087129-c8e4a800-96ef-11ea-9cf3-3a1174be5d64.jpg)

Image D. After rebooting the browser and trying to go full screen
![D  3Participants-FullScreen](https://user-images.githubusercontent.com/17940453/82087152-d26e1000-96ef-11ea-8445-32ff07a320f1.jpg)

**Comment by nickvergessen** [comment]
This should be fixed in Talk 9 and Talk 8 and older are only in maintenance mode, so no such bigger changes there anymore
