### ISSUE TITLE
Install error if the database table prefix is longer than 38 characters

### ISSUE THREAD

**Issue by rubo77** [nextcloud/spreed#3593]
## Steps to reproduce
1. choose a database table prefix with more than 38 characters in your configuration
2. Try to install the Talk App

## ERROR
`An exception occurred while executing 'CREATE TABLE verylong123456789012345678901234567890_spreedme_room_participants (userId VARCHAR(255) DEFAULT NULL, roomId INT NOT NULL, lastPing INT NOT NULL, sessionId VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name 'verylong123456789012345678901234567890_spreedme_room_participants' 
`

## Talk app

**Talk app version:** 8.0.9

## Server configuration

**Operating system**: Debian (docker)

**Web server:** Apache

**Database:** Maria

**PHP version:**

**Nextcloud Version:** 18.0.4

**Nextcloud configuration:**
      'dbtableprefix' => 'verylong123456789012345678901234567890_',

**Comment by nickvergessen** [comment]
Yeah, well nothing we can/will fix. Let's continue it in your server PR
