### ISSUE TITLE
missing frontend after update to 8.0.9

### ISSUE THREAD

**Issue by uvaelazar** [nextcloud/spreed#3594]
## Steps to reproduce
After updating Talk (Spreed) to version 8.0.9 i'm missing the frontend to the Talk app on my Nextcloud 18.0.4 installation.

### Expected behaviour
After clicking on the Talk-Icon there should be the normal view with available chats, chat history and user list.

### Actual behaviour
Under the Icon-Bar: nothing / blanc screen
Not possible to edit the settings while not showing the options in the config-tab.

The connection via Nextcloud Talk-App (Android) is still working!

## Browser
Site-Sourcecode (part):

\<div id="content" class="app-spreed" role="main">
					\</div>

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10 1909 (Build 18363.836)

**Browser name:** Firefox / Edge

**Browser version:** Firefox: 76.0.1 / Edge 44.18362.449.0

## Talk app

**Talk app version:** 8.0.9

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 18.04.4 LTS 

**Web server:** nginx/1.14.0 (Ubuntu)

**Database:** Maria
10.1.44-MariaDB-0ubuntu0.18.04.1

**PHP version:** PHP 7.2.24-0ubuntu0.18.04.4
with Zend OPcache v7.2.24-0ubuntu0.18.04.4

**Nextcloud Version:** 18.0.4

**List of activated apps:**
<details>
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
</details>

**Nextcloud configuration:**

<details>
$CONFIG = array (
  'instanceid' => '*** removed ***',
  'passwordsalt' => '*** removed ***',
  'secret' => '*** removed ***',
  'trusted_domains' =>
  array (
    0 => '*** removed ***',
  ),
  'datadirectory' => '/var/nextcloud_data',
  'dbtype' => 'mysql',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'https://*** removed ***/nextcloud',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*** removed ***',
  'dbpassword' => '*** removed ***',
  'installed' => true,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => '*** removed ***',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '*** removed ***',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'nextcloud@*** removed ***',
  'mail_smtppassword' => '*** removed ***',
  'logtimezone' => 'Europe/Berlin',
  'theme' => '',
  'loglevel' => 2,
  'default_language' => 'de',
  'default_locale' => 'de_DE',
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 1.5,
  ),
  'updater.release.channel' => 'stable',
);
</details>

### Server log (data/nextcloud.log)
<details>
{"reqId":"IMkKjKZpzWdDGaHe5jEz","level":3,"time":"2020-05-13T18:38:02+02:00","remoteAddr":"*** removed ***","user":"*** removed ***","app":"spreed","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/*** removed ***","message":{"Exception":"InvalidArgumentException","Message":"Talk commands using the {ARGUMENTS_DOUBLEQUOTE_ESCAPED} are not supported anymore.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":191,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\ShellExecutor","type":"->","args":["php /var/www/nextcloud/apps/spreed/sample-commands/wikipedia.php \"{ARGUMENTS_DOUBLEQUOTE_ESCAPED}\"","--help","*** removed ***","*** removed ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":154,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},"--help"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":121,"function":"execHelpSingleCommand","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},"wiki"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":89,"function":"execHelp","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},""]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Listener.php","line":79,"function":"exec","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":1,"__class__":"OCA\\Talk\\Model\\Command"},""]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"OCA\\Talk\\Chat\\Command\\{closure}","class":"OCA\\Talk\\Chat\\Command\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/ChatManager.php","line":165,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/ChatController.php","line":173,"function":"sendMessage","class":"OCA\\Talk\\Chat\\ChatManager","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"},"users","*** removed ***","/help",{"date":"2020-05-13 16:38:02.502099","timezone_type":3,"timezone":"UTC","__class__":"DateTime"},null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sendMessage","class":"OCA\\Talk\\Controller\\ChatController","type":"->","args":["/help","*** removed ***",0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\ChatController","sendMessage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/chat/*** removed ***"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/ShellExecutor.php","Line":45,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v8.0.9","version":"18.0.4.2"}
{"reqId":"0VwKG37HFzhnv3JupQ1G","level":3,"time":"2020-05-13T18:38:17+02:00","remoteAddr":"*** removed ***","user":"*** removed ***","app":"spreed","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/*** removed ***","message":{"Exception":"InvalidArgumentException","Message":"Talk commands using the {ARGUMENTS_DOUBLEQUOTE_ESCAPED} are not supported anymore.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":191,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\ShellExecutor","type":"->","args":["php /var/www/nextcloud/apps/spreed/sample-commands/wikipedia.php \"{ARGUMENTS_DOUBLEQUOTE_ESCAPED}\"","","*** removed ***","*** removed ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":93,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},""]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Listener.php","line":79,"function":"exec","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},""]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"OCA\\Talk\\Chat\\Command\\{closure}","class":"OCA\\Talk\\Chat\\Command\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/ChatManager.php","line":165,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/ChatController.php","line":173,"function":"sendMessage","class":"OCA\\Talk\\Chat\\ChatManager","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"},"users","*** removed ***","/wiki",{"date":"2020-05-13 16:38:17.408289","timezone_type":3,"timezone":"UTC","__class__":"DateTime"},null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sendMessage","class":"OCA\\Talk\\Controller\\ChatController","type":"->","args":["/wiki","*** removed ***",0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\ChatController","sendMessage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/chat/*** removed ***"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/ShellExecutor.php","Line":45,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v8.0.9","version":"18.0.4.2"}
{"reqId":"XinngBp4OBORrKINJghK","level":3,"time":"2020-05-13T18:38:33+02:00","remoteAddr":"*** removed ***","user":"*** removed ***","app":"spreed","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/*** removed ***","message":{"Exception":"InvalidArgumentException","Message":"Talk commands using the {ARGUMENTS_DOUBLEQUOTE_ESCAPED} are not supported anymore.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":191,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\ShellExecutor","type":"->","args":["php /var/www/nextcloud/apps/spreed/sample-commands/wikipedia.php \"{ARGUMENTS_DOUBLEQUOTE_ESCAPED}\"","nextcloud","*** removed ***","*** removed ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":93,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},"nextcloud"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Listener.php","line":79,"function":"exec","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},"nextcloud"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":247,"function":"OCA\\Talk\\Chat\\Command\\{closure}","class":"OCA\\Talk\\Chat\\Command\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":80,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/ChatManager.php","line":165,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/ChatController.php","line":173,"function":"sendMessage","class":"OCA\\Talk\\Chat\\ChatManager","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"},"users","*** removed ***","/wiki nextcloud",{"date":"2020-05-13 16:38:33.375917","timezone_type":3,"timezone":"UTC","__class__":"DateTime"},null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"sendMessage","class":"OCA\\Talk\\Controller\\ChatController","type":"->","args":["/wiki ","*** removed ***",0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\ChatController","sendMessage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"apiVersion":"v1","token":"*** removed ***","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/chat/*** removed ***"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/ShellExecutor.php","Line":45,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v8.0.9","version":"18.0.4.2"}
{"reqId":"YjjPk3Tgwm0P5lR36Sun","level":2,"time":"2020-05-14T09:45:12+02:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 10000 milliseconds with 3850240 out of 4863410 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"18.0.4.2"}
</details>

**Comment by jospoortvliet** [comment]
Please update to 8.0.10, 8.0.9 was broken...

**Comment by scandinave** [comment]
And where is this 8.0.10? it does not exist.

**Comment by nickvergessen** [comment]
Try to redownload and manually replace the files again. There where 36 downloads of the first package which missed some important files. see #3548
