### ISSUE TITLE
Inconsistent handling of deleted users

### ISSUE THREAD

**Issue by simonspa** [nextcloud/spreed#3598]
## Steps to reproduce
1. Create user account
2. Create conversation, chat, call...
3. Delete user account

### Expected behaviour
The UI should consistently refer to the deleted user in one way (I don't mind which)

### Actual behaviour
Within the conversation and the sidebar, there are four different ways of mentioning the user:

* In the conversation list, it say "Deleted user (username)"
* Chat entries of the user are marked as "[Unknown user name]"
* Call starts/joins by the user are marked with "deleted_users" (plural)
* The call summary entry still features the username

Summary in one screenshot:

![image](https://user-images.githubusercontent.com/1677436/82157587-9e772400-9882-11ea-9197-17d9f4adbd23.png)

(This is Talk 8.0.9)

**Comment by nickvergessen** [comment]
Yeah, that looks aweful and it's due to the different components dealing with them in different ways all being combined by Talk.

**Comment by PVince81** [comment]
@nextcloud/designers probably something to unify on the whole platform ? Which one of the four ? :smile:

**Comment by jancborchardt** [comment]
Yep, should be unified, and that is into the form:
> Deleted user (`username`)

**Comment by nickvergessen** [comment]
You mean user id I hope/guess?

> Deleted user (user id)

Since we can't load any display names anymore as the information is gone. Also note that in theory this is not fully GDPR compliant in most cases (e.g. user id was your email or full name based)

**Comment by skjnldsv** [comment]
If we want, we can start using the Vue RichDocument rendering methods.
And define undefined mentions there.

> Also note that in theory this is not fully GDPR compliant in most cases (e.g. user id was your email or full name based)

Right, the data would still be in the message source doe, so not displaying it isn't being gdpr compliant :)

**Comment by nickvergessen** [comment]
Well mentions is one thing, left over one-to-one conversations is another, also author names and more.
