### ISSUE TITLE
Talk smlieys

### ISSUE THREAD

**Issue by zillo32** [nextcloud/spreed#3599]
Im Talk Desktop werde keine smileys und den Smileys button angezeigt könnt ihr da mal nachschauen?
________________________________________________________________________________________________________

No smileys will be shown in the Talk Desktop and the Smileys button can you look there?

**Comment by nickvergessen** [comment]
Do you mean the browser? Or are you using a talk desktop app I'm not aware of?

In the browser there is currently no such option. See #1130

**Comment by nickvergessen** [comment]
Closing as this can only be handled after #1130 and might be handled in the same step
