### ISSUE TITLE
Password protection rooms

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#36]
Sort out how public rooms and private rooms and password protected rooms and internal rooms fit together.

**Comment by Stibila** [comment]
Is there any ETA for this? Now it's easy to guess room ID (it is just incremental integer) so basically anyone can now join the call, even if he/she was not invited. Changing room ID from integer to random string UUID would be better, but password protected will do also.

**Comment by Ivansss** [comment]
Room IDs have been replaced with random Tokens #258 
This PR has been already merged to master and it will be included in the next app release.
Not-invited people can only join a public room if they know the URL but they can't never join a private one2one or group call.
Nevertheless, password protection for public rooms will be implemented.

**Comment by bbbjjj** [comment]
Does #258 also prevent guests from creating a room through a public url? Because at the moment everyone who knows a cloud can just create a room without login and share the link with others.

**Comment by Ivansss** [comment]
There is no way to create a new room when a guest joins into a public room (UI-wise). 
Only logged-in users have that option in the UI.
Also, even if you know a cloud url, that API for creating rooms is not exposed to the public.

**Comment by bbbjjj** [comment]
Yeah you are right, no way for creating a new one. But joining one which was created and empty is possible. But this will be solved with the new update and random room tokens. Thanks!

**Comment by leonklingele-work** [comment]
See this comment for more details on which different meeting types / authentication mechanisms should be supported: https://github.com/nextcloud/calendar/issues/563#issuecomment-323033951

**Comment by nickvergessen** [comment]
Just to get this strait, logged in users will not have to enter the password if they have been invited. If they follow the public link, they will have to enter the room password just like guests.

This said there will be a room password, not individual passwords per users.

**Comment by leonklingele-work** [comment]
Having no individual password/PIN for external users (i.e. users without a NC account) implies that all external users have the exact same status (_Guest_). You will not be able to invite an external user which should get _Moderator_ status. You'd need to create an unique account for every meeting moderator on your instance. Is this really what we want?

**Comment by nickvergessen** [comment]
For version 1 yes
