### ISSUE TITLE
Joining participants in grid view only shown after switch to promoted view

### ISSUE THREAD

**Issue by michag86** [nextcloud/spreed#3618]
I've tested the new grid view in Talk app 9.0.0-beta.1 in Nextcloud 19.0.0-RC2
Grid view looks nice. But if a participant joins the call, if grid view is enabled, the participant is not shown correctly.

## Steps to reproduce
1. Start a call as User A
2. Switch to grid view as User A 
3. Join the call as User B

### Expected behaviour
User A sees User B in grid view

### Actual behaviour
User A sees only him self.

If User B leaves and joins again, User A only sees the name of the user. After switch to promoted view and back to grid view, it is working.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 76.0.1

## Talk app

**Talk app version:** 9.0.0-beta.1

**Custom TURN server configured:** no

**Custom STUN server configured:** default

**Comment by nickvergessen** [comment]
The appstore is currently not allowing uploads, but you can find RC1 at https://github.com/nextcloud/spreed/releases/tag/v9.0.0-rc.1
Maybe you can retest with that?

**Comment by michag86** [comment]
Same problem with Talk App v9.0.0-rc.1
