### ISSUE TITLE
9.0.0RC1: No automatic refresh when deleting user

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#3621]
## Steps to reproduce

1. Create a conversation with the user.
2. Send a message.
3. Delete user from conversation list.

### Expected behaviour
Refresh (remove display of former conversation). Go to page with information: "The conversation does not exist".

### Actual behaviour
A conversation from the removed user from the list is displayed. The window is refreshed only after clicking on: "Search conversations or contacts".

![obraz](https://user-images.githubusercontent.com/47037905/82329393-89fd6d80-99e1-11ea-9beb-32e52639a41b.png)

## Browser

**Operating system:** Windows/Ubuntu/...
Win10

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 50.1/55/...
 76.0.1

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
9.0.0 RC1

**Nextcloud Version:** (see admin page)
19.0.0 RC2

**Comment by nickvergessen** [comment]
I'm not sure anymore what this is about. Can you explain a bit more where you think this is behaving wrongly?

**Comment by Valdnet** [comment]
It works fine in version 12.1.2. Thanks for your interest in the issue 😉. I close.
