### ISSUE TITLE
Extra scrollbar in search results when trying to open actions menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3632]
## Steps to reproduce
1. Use the search, have only 1 result
2. Try and copy the link of that conversation
3. See the scrolling issue:

![search result menu scroll](https://user-images.githubusercontent.com/925062/82581676-36318680-9b91-11ea-8490-fee233477419.png)

### Expected behaviour
There is no additional scrollbar and the menu opens properly.

**Comment by nickvergessen** [comment]
Seems to be fixed since #3625

**Comment by ma12-co** [comment]
Nope it's not, this is a separate issue :)

**Comment by nickvergessen** [comment]
But I tested it on master and it worked 😅

**Comment by jancborchardt** [comment]
Same, just tested on Sermo and there it worked too

**Comment by ma12-co** [comment]
Oh, I tested It when you opened it on my pr and it was still there... Well, nice :)
