### ISSUE TITLE
Design of following specific person

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3633]
To follow a specific person, you can click on their video to show in the promoted view.
- Following should have the same icon as the automatically promoted person, just the "person" icon (not a lock)
- The thick white frame of hover/focus stays to indicate the selected state
- If hovering/focusing the currently selected one, as feedback the white frame gets removed → inverted feedback to show what will happen if you click it

@ma12-co as discussed :)

**Comment by ma12-co** [comment]
Thought it would work but honestly it looks very weird.

**Comment by jancborchardt** [comment]
> I'm going to leave it for this release so we can discuss it a bit more

What does "leave it" mean? Do it, or not do it? I’d say let’s put that in as feedback, and then see how it fares. Better than the current state of no feedback for sure.

**Comment by ma12-co** [comment]
Meaning that it's out cause it's too late. In the current status the whole bkg changes as a feedback, it's good enough for now. Also, for now the only way to stop following is the button so no biggie.

**Comment by nickvergessen** [comment]
Seems to be all good atm
