### ISSUE TITLE
When in video call, fade out controls and mouse pointer also when mouse is over videos

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3635]
## Steps to reproduce
1. Be in a video call, grid view for example
2. Have your mouse over one video, but don’t move it
3. Mouse stays as well as the white frame video hover effect, so you need to manually move the mouse into the corner

### Expected behaviour
For Youtube and other video platforms, even if you have the mouse over the video, the mouse vanishes after some time, and so do the controls – until you move it again of course. It would be good if we could do the same, but not sure if that’s possible?

cc @ma12-co

**Comment by nickvergessen** [comment]
Already implemented
