### ISSUE TITLE
 9.0.0-rc.1 Creates Talk-folder in users files, breaks Desktop sync

### ISSUE THREAD

**Issue by RogoTe** [nextcloud/spreed#3653]
## Steps to reproduce
0. Check Desktop app is okay and sync works. Upgrade Talk to  9.0.0-rc.1
1. Just click Talk in the top bar
2. Goto Files
3. Find an empty folder called 'Talk'
4. Check Desktop app again: "server file discovery reply is missing data"

### Expected behaviour
None. Do not touch users files.

### Actual behaviour
It creates a new folder, that is automatically synced and fucks Desktop client

## Browser

**Operating system:** MacOS

**Browser name:** Firefox 76.0.1

**Browser version:** 76.0.1

## Talk app

**Talk app version:**  9.0.0-rc.1

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Debian 8 with Plesk

**Web server:** Apache+Nginx as Proxy

**Database:** MariaDB

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 6.0.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.0-rc.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - suspicious_login: 3.1.0
  - systemtags: 1.9.0
  - tasks: 0.13.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - apporder
  - breezedark
  - camerarawpreviews
  - checksum
  - files_automatedtagging
  - files_fulltextsearch
  - files_fulltextsearch_tesseract
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.example.de\/",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_language": "de",
        "default_locale": "de",
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "mysql.utf8mb4": true,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
> server file discovery reply is missing data

I'm not sure where to move this. It's either a bug in the server filesystem or in the desktop client.
cc @rullzer

**Comment by rullzer** [comment]
The folder is created normally right?

@er-vin @misch7 could you try to reproduce?

**Comment by er-vin** [comment]
I'll try to look into it today.

**Comment by er-vin** [comment]
So I've been trying to reproduce locally and didn't hit that issue. I'm not on MacOS though, even though I doubt it would be platform specific we should try to reproduce it there just in case. @misch7  could you please give it a try?

**Comment by nickvergessen** [comment]
Maybe you can check the source when you log/trigger "server file discovery reply is missing data", so we can see on the server why that could occure?

**Comment by RogoTe** [comment]
Hi guys,
I am kind of sorry to have opened this issue. Before I did I tested this twice to be sure.
Now after you could not reproduce I tried it again myself. Turned out sync error was there in 3 of 5 runs.
WTF?
Then the googling began... Turns out this error seems to be a typical zombie issue of Nextcloud. Looks like desktop client users see this whenever something is broken with sync in server or desktop.
Seems it is or was triggered by
- [external storage](https://github.com/nextcloud/desktop/issues/819)
- [user leaving team](https://github.com/nextcloud/server/issues/15634)
- [server behind a firewall](https://www.gitmemory.com/issue/nextcloud/desktop/819/489019219)
- [some versions of the desktop client](https://gitmemory.com/issue/nextcloud/desktop/908/506229513)
- shares created in previous versions of Nextcloud
- "bad characters" (like dots) in file or folder names
- some versions of the server package
- "bad characters" (like brackets) in file or folder names
- "bad characters" (like German Umlauts) in file or folder names
After first google page I stopped with links...

As I could not reproduce it for sure myself please CLOSE - but anyway stop to mess my with users folder structure please
