### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by machetto** [nextcloud/spreed#3659]
**Is your feature request related to a problem? Please describe.**
It would be awesome to be able to save video/audio stream(s) to a file.

**Describe the solution you'd like**
It could be a video file is available for download once the call is finished.
Or start saving video to a local disk at the beginning of a call.

**Describe alternatives you've considered**
Screeen recording apps do exist however the video will be re-encoded so of not good quality.

**Comment by nickvergessen** [comment]
See #1232 and #2014

So long story short, without a desktop client or 3rdparty server being a fake participant in the call, this is unlikely to happen.
But feel free to add your thumbs up on #1232
