### ISSUE TITLE
"invalid_backend", message: "The backend URL is not supported." 

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/spreed#3670]
Hi hi have nextcloud 18 with last talk and i'm using talk backends server : 
https://signaling.open-dsi.fr/standalone-signaling/api/v1/welcome

My browser can open websocket but i got error 
"invalid_backend", message: "The backend URL is not supported." 

best regards

**Comment by fancycode** [comment]
You need to whitelist the domain of your Nextcloud instance that is allowed to use the signaling server: https://github.com/strukturag/nextcloud-spreed-signaling/blob/563658bf59cfeae40cee75eb0a7b009feb9e79cd/server.conf.in#L50

**Comment by tanguy-opendsi** [comment]
@fancycode thx for reply wildcard is not working ? 
like *.MYDOMAIN.DOMAIN ?

**Comment by fancycode** [comment]
No, only whole domains are checked but you can add multiple entries (comma-separated).
