### ISSUE TITLE
Talk 9.0.0-rc.1 incompatible with Nextcloud 19.0.0

### ISSUE THREAD

**Issue by Sp1l** [nextcloud/spreed#3675]
## Steps to reproduce
1. Upgrade Nextcloud to 19.0.0
2. Update Talk to 9.0.0-rc.1
3. occ update

### Expected behaviour
Functional Talk app

### Actual behaviour
Message Talk disabled, not compatible

## Server configuration
**Operating system**: FreeBSD 12.1-p4

**Web server:** Apache 2.4.43

**Database:** MariaDB 10.4.13

**PHP version:** 7.4.6

**Nextcloud Version:** 19.0.0

**Comment by nickvergessen** [comment]
Well Talk 9 only supports Nextcloud 19 and it works pretty good.
I guess you are seeing this issue because neither Nextcloud 19 has been publicly announced yet, nor has Talk 9 been put into the appstore, so updating your Nextcloud can not get a matching stable release from the appstore.

**Comment by Sp1l** [comment]
A Nextcloud bot apparently published that 19 was released.
The tweet was later deleted. See Twitter conversation with Jos Poortvliet
https://twitter.com/Sp1l/status/1265243006426329090
