### ISSUE TITLE
Console Warnings (Firefox 76)

### ISSUE THREAD

**Issue by acsfer** [nextcloud/spreed#3676]
Using Signaling server:

- each time a call is started:

`RTCIceServer.url is deprecated! Use urls instead.`

- each time any participant leaves the call:

`An empty string was passed to "getElementById ()".`

https://github.com/nextcloud/spreed/blob/c58a9f2ff8ee2577de6cf78bef964d1e83238084/src/utils/webrtc/simplewebrtc/simplewebrtc.js#L354-L360

**Comment by nickvergessen** [comment]
> RTCIceServer.url is deprecated! Use urls instead.

It's from a 3rd party webrtc adapter library we use, they update very frequent so in case firefox ever removes it the next bump will bring it.
