### ISSUE TITLE
Someone leaving the conversation moves it to the top of the list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#3683]
## Steps to reproduce
1. Have a bunch of conversations
2. Someone leaves an old conversation to clean up their list
3. For everyone else in that conversation, the entry is moved to the top since a new event happened

### Expected behaviour
Someone leaving the conversation is the opposite of something current happening. If possible, that specific event should not necessarily make  a conversation move up top in the list.

cc @nickvergessen @ma12-co

**Comment by nickvergessen** [comment]
I think this is the same for all messenger apps I use :/
Also someone leaving a conversation could be a rather important/crucial thing which needs immediate action

**Comment by jancborchardt** [comment]
Yeah, I’m not very set on it, just is something that often trips me up. But can understand that it can also be an important thing, e.g. when someone accidentally leaves and doesn’t notice.

**Comment by nickvergessen** [comment]
So let's not do it for now.
