### ISSUE TITLE
Shared Desktop: Guests are not able to see shared desktop

### ISSUE THREAD

**Issue by g6094199** [nextcloud/spreed#3694]
i dont know if its no implemented yet or a bug.

### Expected behaviour
Guests should be able to see shared desktops

### Actual behaviour
we had a meeting with a guest (masos, safari) and when we tried to share a desktop (registered users) from Ubuntu or Windows (both FF 76) systems, the registered users could and the guest couldnt see the remote desktop.

## Browser

**Microphone available:** yes
**Camera available:** yes

**Operating system:** Windows/Ubuntu/...
MacOS
**Browser name:** Firefox/Chrome/...
Safari
**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
9.0 rc1
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)
no

## Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** /Nginx

**Database:** /Maria/

**PHP version:**
7.2

**Nextcloud Version:** (see admin page)
19.0

**Comment by nickvergessen** [comment]
That does work, but I'm not sure where you got the unreleased 19.0 from already. Anyway the upcoming Talk 9 final has some more fixes to screensharing, so should work in the final.
