### ISSUE TITLE
Project: adding/connecting folders/data to a running meeting doenst shows data immediately

### ISSUE THREAD

**Issue by g6094199** [nextcloud/spreed#3695]
### Actual behaviour
1. connect to a video meeting
2. you forgot to add data to the meeting project so open a 2nd tab an connect data to the running meeting
3. the data doesnt show under  projects. you will have to refresh the browser to see the data but you will be kicked out of the running video meeting

### Expected behaviour
when someone adds data to a project of a  already running meeting the data should immediately be shown

**Comment by nickvergessen** [comment]
Yeah the project features is not live updating at the moment, but only "on render".
But this is actually the case for all projects implementations, so I would like to ask you to report it in https://github.com/juliushaertl/nextcloud-vue-collections
