### ISSUE TITLE
Nextcloud Talk app installed via F-Droid does not raise notifications

### ISSUE THREAD

**Issue by dirdi** [nextcloud/spreed#3723]
## Steps to reproduce
1. Install the "Nextcloud Talk" app from the **F-Droid** store
2. Login to a Nextcloud instance with default Talk server settings:
![2020-05-31-201032_1518x514_scrot](https://user-images.githubusercontent.com/7914030/83359509-ed40b580-a37a-11ea-9985-6c283601fca6.png)
3. Start a conversation with another user or join a group chat
4. Make sure you have set the *...* > *Conversation info* > *Messages* option to *Always notify*
5. Switch to another app or completely close the Nextcloud Talk app
6. Wait for smb. to send a message

### Expected behaviour
The Nextcloud Talk app should raise a notification as soon as smb. else sends a message.

### Actual behaviour
Nothing happens: No sound. No vibration. No notification badge.

I stumbled upon a thread stating that the Nextcloud Talk app leverages some Google push services. In the past I already learned that apps installed from 3-rd party app stores do not play well together with Google services. Therefore, I removed the Nextcloud Talk app and re-installed it via the Google's Play store. Now everything works fine. So I suspect this is somehow related to the way how one installs the app.

## Talk app

**Talk app version:** 8.0.9

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Web server:** Apache

**Database:** MySQL/MariaDB

**PHP version:** 7.3.18

**Nextcloud Version:** 18.0.4

### Server log (data/nextcloud.log)
Does not contain anything related to this bug.

**Comment by nickvergessen** [comment]
Yes, the F-Droid version comes without G-Play and therefor can not have Push notifications at the moment.
