### ISSUE TITLE
Is Talk 9 / 8 really peer-to-peer? Makes it unusable

### ISSUE THREAD

**Issue by joe-average-user** [nextcloud/spreed#3724]
## Steps to reproduce
1. Use Talk 9 on nextcloud 19 beta with a variety of participants with different internet connection types (cable, wireless, dsl)
2.
3.

### Expected behaviour

In a setup with a central turn server I would expect to have every participant a single video stream, which does not overhaul his internet connection. How would you explain people that they can watch netflix, but cannot use talk on their boxes?

### Actual behaviour

If only one participant uses a slow tablet or a dsl connection of type ADSL2+ the whole chat is completely broken. Especially Audio goes crazy. We did not manage to use a setup with only 5 participants.

## Browser

All kinds: Firefox, Edge, Safari, Chrome intermixed
**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Linux/MacOS/Android

**Browser name:** Firefox/Chrome/...

**Browser version:** latest available on the corresponding box

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:**  9

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** 19 beta 3

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Yes it is peer to peer. A Turn Server only helps with public IP resolution and Firewall issues.

What you need is the High-Performance backend which takes care that everyone only uploads their video once instead of n-times.

See https://github.com/nextcloud/spreed/issues/3106#issuecomment-630714205 for more information
