### ISSUE TITLE
nextcloud talk ResourceLocator can not find a web root

### ISSUE THREAD

**Issue by merrpink** [nextcloud/spreed#3725]
Talk messaging works but actual calls do not. It shows that the other person has connected but the loading thing spins indefinitely in the middle of the window. Audio, video, screen sharing, etc do not work. When I check the logs, I find:

`nextcloud talk ResourceLocator can not find a web root (root: /var/snap/nextcloud/21232/nextcloud/extra-apps/spreed, file: index.php/css/spreed/6c9a-4e84-merged-files.css?v=b92d206521717ac032f8aa58d3c7ff2f, webRoot: , throw: true)`

I'm on Ubuntu 18.04 server running Nextcloud snap. 
Both sides using talk in chromium browser with Ubuntu OS.

**Comment by nickvergessen** [comment]
Please fill our the issue template.
It sounds like you are missing a TURN server. 

https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by nickvergessen** [comment]
The resourcelocator thing is a problem wirh snap and Nextcloud in general, nothing the talk app can solve.

See https://github.com/nextcloud/spreed/issues/1615

**Comment by merrpink** [comment]
@nickvergessen Thanks for your reply. The snap guys told me to speak with you. From looking at other posts, I see there is a bit of back and forth with who is to blame for this error. However, most of those issues did not pose any real problems outside of the cosmetic errors. However, in my case, the app doesn't work at all.

You suggested it was TURN issue, but I am testing on a LAN right now {sorry, should have mentioned that). However, on the page you linked to, it does say that talk requires webRTC. I have it disabled in my browser (for security reasons). Does that need to be on? Other VOIP chat programs work with my current browser config.

**Comment by nickvergessen** [comment]
Yes we use webrtc in our webrtc based video call software

**Comment by merrpink** [comment]
Ok, enabled webrtc in the browser and works perfectly now. In hindsight, I should have thought of that.
