### ISSUE TITLE
Glitch when past call had not fully connected participant in it

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#373]
## Steps to reproduce
1. Be in a call
2. Have one person in connecting state, or error state (due to double connection for example)
3. At the end of the call, start another one or switch to another call

### Expected behaviour
The new call should be normal, have no artifacts from the old one, have a white background etc.

### Actual behaviour
![screenshot from 2017-07-26 15-14-43](https://user-images.githubusercontent.com/925062/28671900-7ff117b0-72de-11e7-932a-00ad7e517853.png)
![screenshot from 2017-07-26 15-14-25](https://user-images.githubusercontent.com/925062/28671899-7feeca46-72de-11e7-927c-647211c9cdb7.png)
Happened with our cloud.nc instance.

**Comment by nickvergessen** [comment]
Not happening anymore since the empty content stuff was redone
