### ISSUE TITLE
Hidden selection bar in talk 9.0.0 (nextcloud 19)

### ISSUE THREAD

**Issue by BugProg** [nextcloud/spreed#3742]
Hello,
I have a little display bug.

And this is a screenshot.[
![Screenshot from 2020-06-04 14-28-31](https://user-images.githubusercontent.com/54059521/83756712-bbc43480-a66f-11ea-9a51-fae2f54847aa.png)
](url)

### Steps to reproduce
Select a conversation.
click on the "paper clip" to add an attachment

### Expected behaviour
See the both propositions

### Actual behaviour
I see half of it.

## Server configuration detail

**Operating system:** Raspbian (Buster 10)

**Webserver:** Apache/2.4.38 (Debian)

**Comment by nickvergessen** [comment]
Duplicate of #3455
