### ISSUE TITLE
Better preview of the shared files

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#3746]
I would suggest to make the preview of images and videos, and also text documents, a bit bigger. Perhaps make them as wide as the chat window itself or at least 50% wide. Just a suggestion. Thanks!

**Comment by jcastang** [comment]
Hello,

Tried a 50% live modification on browser. But it depends on the size of the image. 
After trying a couple of settings, 384px/384px seems a good value on most screen resolution. (1080p)

Maybe just a change in CSS ?

**Comment by tiotrom** [comment]
What would be the proper css code to change it for all files and not only images? Also, isn't it that the perview is just a very small thumbnail image and not a good quality one?

**Comment by jcastang** [comment]
> What would be the proper css code to change it for all files and not only images? Also, isn't it that the perview is just a very small thumbnail image and not a good quality one?

Do not really know. I just live-edited CSS using dev mode in FF. 
I found that 256x256 or 384x384 px are nicer than orignal 128x128px size.

As I am not involved in coding Talk, I donner know what IS the best way to mâle rhis change permanent.

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/4469 that makes the images wider
