### ISSUE TITLE
Prevent group of users from creating public conversations or calls

### ISSUE THREAD

**Issue by sirweazel** [nextcloud/spreed#3761]
**Describe the solution you'd like**
Prevent a subset of users from creating public conversations while still allowing others to create them.  In the enterprise settings, I would not want everyone in an organization to be able to create public links. I would only want this delegated to dept managers, admin, directors.    In personal setting, I would like the kids in the family to use talk to communicate with family members internally, but not use it to communicate with people outside via public links, and yet keep the functionality for everyone else on the server.  I'm talking about the "talk" chats and calls.  I'm not referencing public file sharing.

**Additional context**
Sorry if this is a duplicate of my other post.  I was't sure what to do as my previous ticket was closed stating this functionality was already available.  I'm either not describing accurately or being misinterpreted (quite possible).  I've also reached out on the community forum.  Maybe I've overlooked how to implement the configuration.  The functionality is probably there already, and i'm missing it?

[https://github.com/nextcloud/spreed/issues/3349](url)

[https://help.nextcloud.com/t/nextcloud-talk-disable-public-link-for-only-certain-users-and-groups/80559](url)

**Thank you**
Thank you for any help with this issue, and let me know what information you may need for me. If this is already available as a feature, can you please let me know how to configure or where in the documentation I need to look, and then i will try and confirm i can configure correctly and it is not related to my installation or configuration.

**Comment by sirweazel** [comment]
It looks like this feature may have been added in talk 9. I'll have to test out and verify.  I'll post my testing and close out this issue if it works correctly.  Give me a couple days to test and verify.

**Comment by nickvergessen** [comment]
Yeah should be it.
