### ISSUE TITLE
Talk is not working

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/spreed#3765]
## Steps to reproduce
1. Trying to make a call to some addressee either from web to android client or vice versa
2. The call is not establishing
3. Freezing app on android

### Expected behaviour
The call should be installed

### Actual behaviour
There's ongoing calling without any success.

## Browser
**Microphone available:** yes
**Camera available:** yes
**Operating system:** Windows 10
**Browser name:** Chrome
**Browser version:** 83

## Talk app
**Talk app version:** 9.0
**Custom TURN server configured:**  no
**Custom STUN server configured:**  no

## Server configuration

**Operating system**: Centos 6.10
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.3
**Nextcloud Version:** 19.0

### Server log (data/nextcloud.log)
<details>
```
{"reqId":"jsAahWljTBSDKxAMYVGt","level":3,"time":"06.06.2020 15:24:04","remoteAddr":"31.43.94.26","user":"username","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/spreed/api/v1/room/xnkb5n26","message":"Undefined index: notification_level at /var/www/html/nextcloud/apps/spreed/lib/Manager.php#194","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v8.0.9","version":"19.0.0.12"}
```
</details>

**Comment by nickvergessen** [comment]
You are missing a turn server.
See https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by ostasevych** [comment]
> You are missing a turn server.
> See https://nextcloud-talk.readthedocs.io/en/latest/TURN/

The thing, that I am testing in one LAN.  I also tried coturn server, which works well with xmpp, however NC says that it doesn't have ICE candidate and is not approving it.

**Comment by nickvergessen** [comment]
Which is exactly why calls are not working. So something is wrongly configured with your Turnserver

**Comment by ostasevych** [comment]
Moreover, I am constantly receiving in my log this rows related to Talk:

{"reqId":"eeN338GIFbRCEgURFrUc","level":3,"time":"07.06.2020 07:30:20","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: notification_level at /var/www/html/nextcloud/apps/spreed/lib/Manager.php#194","userAgent":"--","version":"19.0.0.12"}
{"reqId":"eeN338GIFbRCEgURFrUc","level":3,"time":"07.06.2020 07:30:20","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: notification_level at /var/www/html/nextcloud/apps/spreed/lib/Manager.php#194","userAgent":"--","version":"19.0.0.12"}
{"reqId":"eeN338GIFbRCEgURFrUc","level":3,"time":"07.06.2020 07:30:20","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: notification_level at /var/www/html/nextcloud/apps/spreed/lib/Manager.php#194","userAgent":"--","version":"19.0.0.12"}

**Comment by ostasevych** [comment]
Here wat I see in the NC settings:
![image](https://user-images.githubusercontent.com/5199030/83963074-b81cf180-a8ab-11ea-83f3-73f0a6a9c014.png)

**Comment by ostasevych** [comment]
It seems to me, it started work! Thank you, the matter was in listening-ip variable, which was commented in my configuration.

At the same time I see another issue: I cannot understand when there's incoming call in Nextcloud - there's no any audio signal about that.
