### ISSUE TITLE
 Invisible "icon-menu-people" in conversation when said menu is closed in Nextcloud snap

### ISSUE THREAD

**Issue by Refhi** [nextcloud/spreed#3766]
So about https://github.com/nextcloud/spreed/issues/3404

The only thing to add is that this bug only seems to appear when the Nextcloud server is in a snap.
Talked with https://github.com/kyrofa here https://github.com/nextcloud/nextcloud-snap/issues/1334 who suggest that it "Sounds like an issue with the app making some improper assumptions about where its assets are (e.g. assuming they're going to be in the nextcloud root when in fact they aren't)."

Could this be fixed ?

Thanks !

**Comment by nickvergessen** [comment]
Can you provide a test account?
Send an email to `<my github name>@nextcloud.com`

**Comment by Refhi** [comment]
Seems fixed with the last snap update
best regards
