### ISSUE TITLE
Feature Request - Edit Documents In Same Window As Group Video Call.

### ISSUE THREAD

**Issue by Bellusterra** [nextcloud/spreed#3773]
https://www.youtube.com/watch?v=Nr7cGN6ZJM0
Can this be done with Onlyoffice as well with the same layout and co-editing from within a group nextcloud talk conversation? NC 19 and Talk 9 Introduced the Drag and Drop Great work Everyone! Currently however adding a document opens it in a new window. When going from the file itself to the share tab and then "start conversation" it seems this is already maybe possible, but when going from a group call to drag and drop and then clicking on the document for editing it would be good to have the screen shift into what is in the above video link, and with the then limited video space maybe automatically go into follow mode where it would switch between who is talking. Anyway just a thought.

**Comment by nickvergessen** [comment]
It's automatically happening once onlyoffice is implementing the viewer api

**Comment by nickvergessen** [comment]
I'm closing this as this has to be fixed by oo and not by the Talk app
