### ISSUE TITLE
Screen sharing on linux with radeon/amdgpu driver unable to share windows

### ISSUE THREAD

**Issue by Tomasu** [nextcloud/spreed#378]
## Steps to reproduce
1. Use the radeon/amdgpu driver
2. try to share an individual window
3. see blackness

### Expected behaviour

Should show window.

### Actual behaviour

Nothing but black.

From what I remember, there is a weird issue with Mesa where a specific color depth or texture mode is required to be able to capture individual windows. I am not certain this app can do a ton about it, but I hope it's possible. I have three monitors and the display sharing shows all three desktops in one big strip which is unusable. That's a separate issue I suppose.

## Browser
Chrome 61

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Debian Sid

**Browser name:** Chrome

**Browser version:** 61 dev

### Browser log

Nothing applicable

## Spreed app

**Spreed app version:** 2.0.1

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration
N/A

### Server log (data/nextcloud.log)
N/A

**Comment by nickvergessen** [comment]
Is this still the case? Or did the recent Chrome updates help?

**Comment by nickvergessen** [comment]
Closing as per above, if you still experience this issue, feel free to reopen the issue
