### ISSUE TITLE
exception  while fetching participants since v9.0.1

### ISSUE THREAD

**Issue by atemp** [nextcloud/spreed#3787]
## Steps to reproduce
1. upgrade app from v9.0.0 to v9.0.1
2. visit existing conversation mit more than one participant, maybe a call had to ran before, but it happens even if no call is currently running
3. nextcloud will show a small popup saying: `An error occurred while fetching the participants` and the user list will show lots of grey circles and boxes instead of users

### Expected behaviour

showing users and no error

### Actual behaviour

the error descibed above will happen, i was able to cure it b starting a call and then stopping it. but in the case where an old call is still running but the user is or seems to be offline, joining and exiting the call does not help

## Browser

**Microphone available:** happens before call is started

**Camera available:** happens before call is started

**Operating system:** CentOS 7

**Browser name:** firefox

**Browser version:** firefox-68.9.0-1.el7.centos.x86_64

### Browser log

n/a

## Talk app

**Talk app version:** 9.0.1

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: CentOS 7

**Web server:** Nginx

**Database:** MariaDB (official docker image)

**PHP version:** official docker image from https://hub.docker.com/_/nextcloud/

**Nextcloud Version:** 19.0.0.12 (https://hub.docker.com/_/nextcloud/)

**List of activated apps:**

  - accessibility: 1.5.0
  - circles: 0.18.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_versions: 1.12.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - spreed: 9.0.1
  - systemtags: 1.9.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_saml: 3.0.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

<details>
<pre>
{
    "system": {
        "loglevel": "1",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "app_install_overwrite": [
            "circles"
        ]
    }
}
</pre>
</details>

### Server log (data/nextcloud.log)
<details>
<pre>
Error   no app in context   Exception: Argument 1 passed to OCA\Talk\Room::leaveRoom() must be of the type string, int given, called in                                     2020-06-09T09:11:13+00:00
                              /var/www/html/custom_apps/spreed/lib/Controller/RoomController.php on line 852 at lib/private/AppFramework/Http/Dispatcher.php line 110

                              0. lib/private/AppFramework/App.php line 137
                                 OC\AppFramework\Http\Dispatcher->dispatch(OCA\Talk\Controller\RoomController {}, "getParticipants")
                              1. lib/private/AppFramework/Routing/RouteActionHandler.php line 47
                                 OC\AppFramework\App::main(
                                   "OCA\\Talk\\Controller\\RoomController",
                                   "getParticipants",
                                   OC\AppFramework\DependencyInjection\DIContainer {},
                                   {apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"}
                                 )
                              2. <<closure>>
                                 OC\AppFramework\Routing\RouteActionHandler->__invoke({apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"})
                              3. lib/private/Route/Router.php line 297
                                 call_user_func(OC\AppFramework\Routing\RouteActionHandler {}, {apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"})
                              4. ocs/v1.php line 82
                                 OC\Route\Router->match("\/ocsapp\/apps\/spreed\/api\/v2\/room\/aisywkne\/participants")
                              5. ocs/v2.php line 24
                                 require_once("\/var\/www\/html\/ocs\/v1.php")

                              Caused by TypeError: Argument 1 passed to OCA\Talk\Room::leaveRoom() must be of the type string, int given, called in
                              /var/www/html/custom_apps/spreed/lib/Controller/RoomController.php on line 852 at custom_apps/spreed/lib/Room.php line 835

                              0. custom_apps/spreed/lib/Controller/RoomController.php line 852
                                 OCA\Talk\Room->leaveRoom(292604)
                              1. lib/private/AppFramework/Http/Dispatcher.php line 170
                                 OCA\Talk\Controller\RoomController->getParticipants(

                                 )
                              2. lib/private/AppFramework/Http/Dispatcher.php line 100
                                 OC\AppFramework\Http\Dispatcher->executeController(OCA\Talk\Controller\RoomController {}, "getParticipants")
                              3. lib/private/AppFramework/App.php line 137
                                 OC\AppFramework\Http\Dispatcher->dispatch(OCA\Talk\Controller\RoomController {}, "getParticipants")
                              4. lib/private/AppFramework/Routing/RouteActionHandler.php line 47
                                 OC\AppFramework\App::main(
                                   "OCA\\Talk\\Controller\\RoomController",
                                   "getParticipants",
                                   OC\AppFramework\DependencyInjection\DIContainer {},
                                   {apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"}
                                 )
                              5. <<closure>>
                                 OC\AppFramework\Routing\RouteActionHandler->__invoke({apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"})
                              6. lib/private/Route/Router.php line 297
                                 call_user_func(OC\AppFramework\Routing\RouteActionHandler {}, {apiVersion:"v2",token:"aisywkne",_route:"ocs.spreed.Room.getParticipants"})
                              7. ocs/v1.php line 82
                                 OC\Route\Router->match("\/ocsapp\/apps\/spreed\/api\/v2\/room\/aisywkne\/participants")
                              8. ocs/v2.php line 24
                                 require_once("\/var\/www\/html\/ocs\/v1.php")

</pre>
</details>

**Comment by nickvergessen** [comment]
Do you have users with only number ids?

**Comment by atemp** [comment]
yes, i have such users

**Comment by atemp** [comment]
thanks for the quick fix, applied it manually and it seems to help
