### ISSUE TITLE
Spreed doesn't take the ldap configuration in account (bug)

### ISSUE THREAD

**Issue by worldcitizen** [nextcloud/spreed#380]
I've configured Nextcloud to only show a limit amount of LDAP users. In the user list tis is shown correctly but when I want to add users to the conference,  users, from LDAP, are shown that don't meet the LDAP configuration.

## Steps to reproduce
1. Configure LDAP with the limited amount of people 
2. Check the user
3. Check user when adding them to the conference

### Expected behaviour
Tell us what should happen
Only show the users that are configured in ldap.

### Actual behaviour
Tell us what happens instead
All LDAP users are shown

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
This should also be an "issue" in the "Share with" field while sharing a file, right?

**Comment by nickvergessen** [comment]
Please report to the https://github.com/nextcloud/server repository
