### ISSUE TITLE
Scheduled calls / waiting lobby

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#382]
For a proper [calendar integration](https://github.com/nextcloud/calendar/issues/563), we need support to schedule meetings, i.e. start them at a specific date (show a "waiting lobby" for guests until this date was reached with information about the meeting) and optionally stop them at some point.

Support for recurring calls (e.g. meeting every Tuesday, 9AM – 11AM) is the next step.

**Comment by small1** [comment]
This is a feature that some customers of mine asked for this week. Just so it isn't forgotten :)
