### ISSUE TITLE
Web chat integration

### ISSUE THREAD

**Issue by HLFH** [nextcloud/spreed#3820]
Hi,

## Feature request

A Nextcloud Talk web chat you can integrate to your own website.

Similar to [Rochet.Chat Livechat](https://github.com/RocketChat/Rocket.Chat.Livechat).

Can be integrated with some simple JS code.

Thanks,
HLFH

**Comment by HLFH** [comment]
This is not a duplicate of https://github.com/nextcloud/spreed/issues/674 as the latter makes reference to a click-to-call integration in a website.

**Comment by nickvergessen** [comment]
To me it is exactly a duplicate to #674 as the call button is just the last step of it

**Comment by HLFH** [comment]
@nickvergessen OK.
