### ISSUE TITLE
Remember grid view state

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3824]
### Steps to reproduce
1. Join a call and select the grid view (should it be default?)
2. Share a screen
3. Unshare the screen

#### Expected behaviour
You are in the grid view

#### Actual behaviour
You are in promoted view

### Steps to reproduce
1. Join a call and select the grid view
2. Follow a video
3. Click "Unfollow"

#### Expected behaviour
You are in the grid view

#### Actual behaviour
You are in promoted view

### Steps to reproduce
1. Join a call and select the grid view
2. Quit the call
3. Reload
4. Join the call again

#### Expected behaviour
You are in the grid view

#### Actual behaviour
You are in promoted view

**Comment by PVince81** [comment]
could use "BrowserStorage"

also:
- [ ] remember collapsed state ? (once https://github.com/nextcloud/spreed/pull/4365 is merged)

**Comment by nickvergessen** [comment]
I think collapse should be done when a screenshare is coming  in, I would not remember this for now.

For grid, I think grid should be the default when in group calls.
I wouldn't really store it, or we need to store it on a per-conversation basis, because e.g. in one-to-one you mostlikely wouldn't want grid, but in group calls you would.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4451
