### ISSUE TITLE
full screen

### ISSUE THREAD

**Issue by Bellusterra** [nextcloud/spreed#3829]
**Is your feature request related to a problem? Please describe.**

Nextcloud talk does not go full screen on ios safari browser

**Describe the solution you'd like**

To go full screen, I used obs.ninja just now and I'm not completely sure of its implantation, but it does go full screen video in the ios safari browser. 

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
@Ivansss any idea what this is?
