### ISSUE TITLE
Support for room archival

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#383]
It would be nice to have an option to "archive" a room. In contrast to deletion, archiving a room does not remove the information associated with it. This is especially useful when we gain support for features like presentations.
An archived room should not be joinable. There must be a way to unarchive an already archived room.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/4331

**Comment by szaimen** [comment]
I thought #4487 was the PR for this?

**Comment by nickvergessen** [comment]
That PR handles the issue in #3886
the pr just has a "bad" title

**Comment by szaimen** [comment]
Now I am totally confused but it doesn't matter.
