### ISSUE TITLE
Conversation not possible - Network logs show a repetitive 504 error

### ISSUE THREAD

**Issue by zyonbv** [nextcloud/spreed#3867]
Hello Everyone

I am not able to fully use Talk in my environment. Chat Works fine, but it's a bit laggy. And video calls are not working. Please see details below.

## Steps to reproduce
1. Create conversation
2. Join call
3. Waiting for others to join call remains on the screen without something else happening.

### Expected behaviour
Others to join the call with video and audio.

### Actual behaviour
guests or other users join the call, but with a big lag. but the video and audio never connects. I am able to chat with them.

## Talk app

**Talk app version:** 8.0.9

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes 

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Firefox/Chrome/

**Browser version:** Latests

### Browser log

```
Insert your browser log here, this could for example include:
a) The javascript console log

b) Network log
```
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 5.03 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 9.62 s
t6pfsaa4 | 504 | xhr | xhr.js:178 | 214 B | 5.02 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 5.03 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 10.04 s
t6pfsaa4 | 504 | xhr | xhr.js:178 | 214 B | 5.01 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 5.02 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 10.00 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 5.02 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 10.02 s
t6pfsaa4?lookIntoFuture=1&lastKnownMessageId=182&includeLastKnown=0 | 504 | xhr | xhr.js:178 | 214 B | 5.03 s
```

c) ...
```

</details>

## Server configuration
Operating system: freenas 13.1

Webserver: nginx/1.18.0 (fpm-fcgi)

Database: mysql 5.7.30

PHP version:

7.4.5 Modules loaded: Core, date, libxml, pcre, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, apcu, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, iconv, imagick, intl, json, ldap, exif, openssl, PDO, posix, SimpleXML, xml, xmlreader, xmlwriter, zip, zlib, pdo_mysql, xsl, Zend OPcache

Nextcloud version: 18.0.6 - 18.0.6.0

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: freenas plugins

Signing status
Array ( )
List of activated apps
``` Enabled: - accessibility: 1.4.0 - activity: 2.11.0 - bbb: 0.5.1 - calendar: 2.0.3 - cloud_federation_api: 1.1.0 - comments: 1.8.0 - contacts: 3.3.0 - dav: 1.14.0 - federatedfilesharing: 1.8.0 - federation: 1.8.0 - files: 1.13.1 - files_pdfviewer: 1.7.0 - files_rightclick: 0.15.2 - files_sharing: 1.10.1 - files_trashbin: 1.8.0 - files_versions: 1.11.0 - files_videoplayer: 1.7.0 - firstrunwizard: 2.7.0 - issuetemplate: 0.6.0 - keeweb: 0.6.2 - logreader: 2.3.0 - lookup_server_connector: 1.6.0 - nextcloud_announcements: 1.7.0 - notes: 3.6.0 - notifications: 2.6.0 - oauth2: 1.6.0 - onlyoffice: 4.3.0 - password_policy: 1.8.0 - photos: 1.0.0 - printer: 0.0.3 - privacy: 1.2.0 - provisioning_api: 1.8.0 - recommendations: 0.6.0 - serverinfo: 1.8.0 - settings: 1.0.0 - sharebymail: 1.8.0 - spreed: 8.0.9 - support: 1.1.1 - survey_client: 1.6.0 - systemtags: 1.8.0 - text: 2.0.0 - theming: 1.9.0 - twofactor_backupcodes: 1.7.0 - updatenotification: 1.8.0 - viewer: 1.2.0 - workflowengine: 2.0.0 Disabled: - admin_audit - encryption - files_external - user_ldap ```
Configuration (config/config.php)
``` { "apps_paths": [ { "path": "\/usr\/local\/www\/nextcloud\/apps", "url": "\/apps", "writable": true }, { "path": "\/usr\/local\/www\/nextcloud\/apps-pkg", "url": "\/apps-pkg", "writable": true } ], "logfile": "\/var\/log\/nextcloud\/nextcloud.log", "memcache.local": "\\OC\\Memcache\\APCu", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "localhost", "192.168.100.6", "next.bcloud.ro", "oo.bcloud.ro" ], "trusted_proxies": "***REMOVED SENSITIVE VALUE***", "overwriteprotocol": "https", "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "mysql", "version": "18.0.6.0", "overwrite.cli.url": "http:\/\/localhost", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "mysql.utf8mb4": true, "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "instanceid": "***REMOVED SENSITIVE VALUE***", "maintenance": false, "theme": "", "loglevel": 2, "onlyoffice": { "verify_peer_off": true, "jwt_header": "Authorization" }, "mail_smtpmode": "smtp", "mail_smtpsecure": "tls", "mail_sendmailmode": "smtp", "mail_from_address": "***REMOVED SENSITIVE VALUE***", "mail_domain": "***REMOVED SENSITIVE VALUE***", "mail_smtphost": "***REMOVED SENSITIVE VALUE***", "mail_smtpport": "587", "mail_smtpauth": 1, "mail_smtpname": "***REMOVED SENSITIVE VALUE***", "mail_smtppassword": "***REMOVED SENSITIVE VALUE***" } ```

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
https://httpstatuses.com/504

Since you use nginx I would assume it's related to https://github.com/nextcloud/spreed/issues/2211, https://github.com/nextcloud/spreed/issues/2010 and https://github.com/nextcloud/spreed/issues/3183
