### ISSUE TITLE
How to setup default Talk-Folder-location globally for all users?

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/spreed#3868]
Hello
It is possible to change the Talk-Folder-Location individually per user in Talk-User-Settings. But how is it possible to set a Talk-Folder-Location globally for all users?
Maybe as configuration-value inside config.php? But how?
Thanks
René

**Comment by nickvergessen** [comment]
It's not possible right now without changing the sourcecode.
To change it there you would need to adjust:
https://github.com/nextcloud/spreed/blob/b42625f2c9997756c9200b40c13f6eb183bb67b2/lib/Config.php#L95

But to which value would you change it?

**Comment by rgl1234** [comment]
thanks for your prompt reply.
As I prefer to have all data on an external cifs-storage, every user has his personal folder in windows like "Z:" also mounted and available in nextcloud as "Z - my folder". So I think about setting this "global"-value to "Z - my folder/NextcloudTalk". So the users have all their data all together in one place where it should be....
do you understand?

**Comment by Kleisli** [comment]
> But to which value would you change it?
I would suggest the convention to have a hidden ".Apps" folder where apps can store their data for users that only need to be accessible from the app and not within the files.
but this should not be discussed in the Spreed/Talk repository.

for this app, the default path should definitely not be hardcoded, it should be possible to define it in the configuration

**Comment by nickvergessen** [comment]
In the meantime an appconfig `default_attachment_folder` was added which administrators can set:
https://nextcloud-talk.readthedocs.io/en/latest/settings/#app-configuration

**Comment by rglt** [comment]
> In the meantime an appconfig `default_attachment_folder` was added which administrators can set: https://nextcloud-talk.readthedocs.io/en/latest/settings/#app-configuration

How to use this? with occ command?

**Comment by manu-p** [comment]
@rglt there is a slider below the table of parameters shown in the [App Configuration section](https://nextcloud-talk.readthedocs.io/en/latest/settings/#app-configuration). The line corresponding to `default_attachment_folder` actually contains :

Key | Internal type | Default | Hash | Option | Valid values
-- | -- | -- | -- | -- | --
default_attachment_folder | string | /Talk | No |   | Specify default attachment folder location

There's no '_UI option in the admin settings available_' nor '_Dedicated OCC command available_'.

But according to what's written:
> **Note**: All app configs are stored as string in the oc_appconfig database table. Arrays and objects are therefor JSON encoded, integers are casted to string and booleans are replaced with 0/1 or no/yes strings.

Here's what I tried, and it works. 

1. Connect to your database, for instance `mysql -u yourDBuser -p yourDBname` where you replace `yourDBuser` and `yourDBname` with your own values and enter the correct password when prompted.
2. type `insert into oc_appconfig (appid,configkey,configvalue) values ('spreed','default_attachment_folder','/yourTalkDefaultFolderName');` where you replace `yourTalkDefaultFolderName` with the default name you want for the Talk folder.
3. quit mysql/MariaDB (e.g. Ctrl D)

Now, every **new** user should find a _yourTalkDefaultFolderName_ folder in his/her home directory.

You can even add it to a specific skeleton replacing the standard one as described [here](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/default_files_configuration.html). That's what I did, adding a Readme.md file in this folder to explain the user what this folder is here for.
