### ISSUE TITLE
Problems with webserver when video call with a group

### ISSUE THREAD

**Issue by HSoeren** [nextcloud/spreed#388]
## Steps to reproduce
1. Group call with video from each person
2. after 3-5 minutes the connection freezes and our nextcloud isn't avaible for some minutes

### Expected behaviour
The video call should run normally, i think

### Actual behaviour
The video stream of my chat partners freezes and if i click on the menu items in the nextcloud nothing happens. New connections/new tabs are loading "forever", after some minutes you can open the page again and everything runs normally. If we started a new call the problem started all over again after mostly 5-10 minutes after calling the others

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/MacBookAir/Android

**Browser name:** Chrome

**Browser version:** different.

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** 12.0.2

**Custom TURN server configured:** no

**Custom STUN server configured:** no

### General server configuration

**Operating system:** Linux zwarte-balk.nl 4.8.0-52-generic #55~16.04.1-Ubuntu SMP Fri Apr 28 14:36:29 UTC 2017 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - json
 - exif
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
{
    "core": {
        "FILE_MISSING": {
            ".htaccess": {
                "expected": "da8e0075f23227b107fc705aa1b20378107d3a1c195d96ed13e5f4f25c38d6c660aab75be183ae5799a4ff7eae0ea739a14c944430ee8bb9e9a824235aa136eb",
                "current": ""
            }
        }
    }
}
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - circles: 0.12.4
 - comments: 1.2.0
 - dav: 1.3.0
 - defaultgroup: 0.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - jsloader: 1.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - music: 0.4.4
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - registration: 0.3.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - audioplayer
 - encryption
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "occgnv07sgg8",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.the-pack.rocks"
    ],
    "datadirectory": "\/var\/www\/vhosts\/the-pack.rocks\/httpdocs\/cloud\/data",
    "overwrite.cli.url": "https:\/\/www.the-pack.rocks\/cloud",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "tpcloud",
    "dbhost": "localhost:3306",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true
}
```
</details>

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

I hope the attached information help you, if you need more information messega me please. I will try to film the problem. Thank you

**Comment by nickvergessen** [comment]
Navigating away is broken, as described in #316 
But freezing I never heard before.
Can you check on your machine whether there is a problem with RAM or your browser so it consumes too much resources?

**Comment by HSoeren** [comment]
We tried some minutes ago; we all stayed in the tab, while talking to the
others - maybe 2 or 3 minutes after starting the call the webserver was not
avaible anymore. I will answer you in some hours again, i try to find the
problems on our webserver (log i.e.)
Our browsers are fine, the highest ram consumption was a chrome browser on
windows 8 with around 400 mb in total (for the cloud tab and the video chat
tab. I asked him to send me the log, as i said I'll get back later with
more data :)
Thank you for helping

2017-09-28 10:29 GMT+02:00 Joas Schilling <notifications@github.com>:

**Comment by nickvergessen** [comment]
Should be fixed as well with the signaling refactoring that was done for NC 13
