### ISSUE TITLE
Excuse me, Why  can I add one person which isn't one of my group members?

### ISSUE THREAD

**Issue by cn-Meepo** [nextcloud/spreed#3880]
## Steps to reproduce
1.

### Expected behaviour
Tell us what should happen
 When I add one person which should be one of my group members, I should add my group mebers only.

### Actual behaviour
Tell us what happens instead
Why can I add one person which isn't one of my group members?

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.2/7.3/7.4

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by kinimodmeyer** [comment]
don´t know if i get it right but why should i not be able to communicate with other users in same instance?
i can also share my files with other groups/users which are not in my groups.

**Comment by cn-Meepo** [comment]
@kinimodmeyer Hi, I don't want to show the users which it isn't in one group of me,what should I do?

**Comment by nickvergessen** [comment]
There is a setting in the admin share settings which should affect this.

**Comment by cn-Meepo** [comment]
@nickvergessen Thanks, That's great
