### ISSUE TITLE
Add sound and pop-up noticiations about incoming events

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/spreed#3881]
**Is your feature request related to a problem? Please describe.**
Talk app is an instant chat application which should provide an easy and comfortable way of notifying interlocutors about new events: incoming chats and calls, invitation to join a group. 

Whilst they are present in mobile app, but web UI lacks of comfortable and intuitive way of notifying apart of small red dot close to the bell ring. Plus, these notifications are coming with a delay and are not comfortable to read.

![image](https://user-images.githubusercontent.com/5199030/86523527-87ae8000-be76-11ea-9587-6ec8a0168f9a.png)

**Describe the solution you'd like**
To add pop-up window informing about event independently of the app where a user is in Nextcloud, to add a ringtone informing about the event. This may be selected and switched on/off by a user in settings.

**Describe alternatives you've considered**
To add the integration to the operational system event (chrome/firefox based), which may allow the pop-up and audio events.
This may be implemented via Desktop app.

**Additional context**
See, how [jsxc](https://github.com/jsxc/jsxc) implemented this:

Incoming chat message  (with audio beep):
![image](https://user-images.githubusercontent.com/5199030/86523466-8f215980-be75-11ea-93a6-edb0415fcf35.png)

Incoming call (with audio ringtone):
![image](https://user-images.githubusercontent.com/5199030/86523448-3d78cf00-be75-11ea-8a73-7f10ca4f8820.png)

**Comment by nickvergessen** [comment]
We show browser notifications when you gave your nextcloud website the permissions (check the lock icon in the browsers addressbar, in case you denied it by accident).

As for calls, there is #1444

**Comment by nickvergessen** [comment]
For further chat notification improvements also see https://github.com/nextcloud/notifications/issues/637
