### ISSUE TITLE
Annoying continuous "unsupported Browser" message with Opera

### ISSUE THREAD

**Issue by DetlevCM** [nextcloud/spreed#3883]
## Steps to reproduce
1. Open Nextcloud with Talk in Opera Next - be greeted by the "unsupported browser" message EVERY TIME. (The last bit is my irritation/the bug. - It should remain hidden if I dismiss it once.)
2.
3.

### Expected behaviour
Tell us what should happen

Dimissing the message should dimiss it for good (or until cookies are cleared).
Incidentally, OperaNext is based on chromium - so there is no good reason why it shouldn't work and as far as I can tell it is a functional add-in... (Just a personal Nextcloud instance, so I can only test it with myself right now...)

### Actual behaviour
Tell us what happens instead

The message re-appears all the time, including on the files overview which makes me think I should maybe uninstall the add-on if it keeps annoying me...

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

9.0.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

no

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.2/7.3/7.4

**Nextcloud Version:** (see admin page) 19

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

19.0.0

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
See #3844
