### ISSUE TITLE
🛂 Chat permission

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#3886]
On a big talk group is often a lot of noise, so maybe it's helpful to restrict posting to moderators

**Comment by nickvergessen** [comment]
Closing this in favor of #383 or do we close #383 as "done" since #4331 is merged and your PR #4487 basically closes this here?

**Comment by jakobroehrl** [comment]
@nickvergessen 
This issue is about locking a conversation EXCEPT the moderators, so IMHO it should be open, maybe I can implement it for NC22?

But we can close https://github.com/nextcloud/spreed/issues/383 
I don't know if I want to continue with https://github.com/nextcloud/spreed/pull/4487

**Comment by xbluemonkx** [comment]
posting here to get updates on this ticket. we would like to have that feature too.

**Comment by marcoambrosini** [comment]
UI-wise:

- Input is grayed out with a "no permissions message"
- No reaction symbol to add new reactions (you can still see existing reactions from other ppl) 
- Attachment button disabled
- Forwarding messages to the conversation with no chat permissions should be blocked too

**Comment by nickvergessen** [comment]
Closing as it's implemented on all clients

**Comment by xbluemonkx** [comment]
is this already available in talk 14?
