### ISSUE TITLE
l10n (German): Replace "Webinar", because it's a registered trademark in Germany

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/spreed#3897]
It would be nice to replace "Webinar" with "Online-Seminar" or similar, because "Webinar" is a registered trademark in Germany: https://register.dpma.de/DPMAregister/marke/register/303160438/DE . 

Edit: I finally got it to save this as suggestion in transifex.

**Comment by nickvergessen** [comment]
Feel free to discuss this in https://help.nextcloud.com/c/translations/deutsch/139
Although is looks like this is being canceled or tried to be canceled by someone?
