### ISSUE TITLE
Odd-looking screensharing view

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#390]
## Steps to reproduce
1. Let someone join your meeting
2. Enable video camera (both participants)
3. Share your screen / a window

### Issues

1. The remote video element has a box shadow
2. The remote video is shown twice

See this screenshot:
![spreed_screensharing-issues](https://user-images.githubusercontent.com/31063993/29773938-f2c64514-8bff-11e7-9a5d-b031536360cd.png)

Reproduced with Spreed (8d8b8d943d829f2ff2c0122949854077a7fdc8d0), Nextcloud 13 beta (https://github.com/nextcloud/server/commit/8e4085526d071b8d6032277b02c700b7cac04cc9) and latest Chrome (60.0.3112.113) / Firefox (55.0.2).

**Comment by nickvergessen** [comment]
Cant reproduce anymore
