### ISSUE TITLE
Attachment gets re-uploaded if you close/open the talk tab

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3904]
## Steps to reproduce
1. Send a local `image.jpg` to a `room x`
2. Change to `room y`
3. Close tab
4. Re-open tab

### Expected behaviour
The `room y` loads

### Actual behaviour
The `room y` loads and upload the `image.jpg` again to `room y`
I guess this is because the `input[type=file]` doesn't get reset after upload, and it gets populated again when you reopen the page as it's considered as a form. cc @ma12-co 

## Talk app

**Talk app version:** 9.0.1
**Custom Signaling server configured:** no idea (company cloud)

**Custom TURN server configured:** no idea (company cloud)

**Custom STUN server configured:** no idea (company cloud)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/spreed/blob/99d8be74e0290bba6bbe91237d11126427b57da2/src/components/NewMessageForm/NewMessageForm.vue#L301
https://github.com/nextcloud/contacts/blob/b47082b0baf162be7647399276432054856b7716/src/components/ContactDetails/ContactDetailsAvatar.vue#L213-L217

**Comment by nickvergessen** [comment]
Seems fixed since #3988
