### ISSUE TITLE
Avatar gets transparent on bad connection

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3905]
## Steps to reproduce
1. Have a bad connection

### Expected behaviour
Your avatar is darken

### Actual behaviour
Your avatar is transparent
![429-253-max](https://user-images.githubusercontent.com/213943/87515897-d3360a80-c67c-11ea-8b52-b895b8a0ce66.png)

Transparent results in darken when there is more than 1 other participant because then your avatar/video is on black background, but in one-to-one:
https://github.com/nextcloud/spreed/blob/3b78a93386c20f5be2aace64ec08c53fc064591f/src/components/CallView/shared/LocalVideo.vue#L413-L418

Also My avatar ws put to transparent quite often without showing the tooltip. I had to hover the mic icon to notice that this is the problem to begin with.

**Comment by nickvergessen** [comment]
cc @danxuliu

**Comment by danxuliu** [comment]
Yes, the avatar (and video) should be darkened instead of being made transparent. But right now I do not know how to do that :shrug: Ideas are welcome :-)

Note that just adding a black background to the local container would not be a good option, because that could show black bars around the video.

> Also My avatar ws put to transparent quite often without showing the tooltip. I had to hover the mic icon to notice that this is the problem to begin with.

See https://github.com/nextcloud/spreed/pull/3839#issuecomment-656780792

**Comment by nickvergessen** [comment]
> Note that just adding a black background to the local container would not be a good option, because that could show black bars around the video.

Then we maybe only do it for avatar backgrounds. But okay will dive into it.

> > Also My avatar ws put to transparent quite often without showing the tooltip. I had to hover the mic icon to notice that this is the problem to begin with.
> 
> See #3839 (comment)

Well the first time the video is darken, the user needs to be shown the reason.

**Comment by danxuliu** [comment]
> Well the first time the video is darken, the user needs to be shown the reason.

Strange, it should be the case already :thinking:
