### ISSUE TITLE
Remove video filter for screensharing elements

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#392]
## Steps to reproduce
1. Share your screen in a meeting

### Expected behaviour
- Shared screen (video) should look similar to how the real screen looks

### Actual behaviour
- Shared screen looks funny, see the attached screenshots

List view (with filter):
![spreed_with-filter](https://user-images.githubusercontent.com/31063993/29777224-84ed4270-8c0b-11e7-8d37-79995ca7f126.png)

List view (without filter, notice the different row colors — this is how it should look like):
![spreed_without-filter](https://user-images.githubusercontent.com/31063993/29777236-8db3fc46-8c0b-11e7-8f7f-10e86d2fd8f1.png)

This took me quite a while to find out. I mean who would suspect CSS to be the villain?

Reproducible in Chrome.

**Comment by leonklingele-work** [comment]
In case you want to change this, a fix is in #393

**Comment by fancycode** [comment]
Interesting - I'm wondering why to apply a filter on videos at all? Depending on the video driver / hardware this could cause quite some CPU load if implemented in software...

**Comment by jancborchardt** [comment]
It’s just a CSS filter, so shouldn’t be a big performance hit. A bit more contrast & saturation, makes people look better, and people like when they look better. ;)
