### ISSUE TITLE
Trailing parenthesis gets incorrectly captured to be part of an URL

### ISSUE THREAD

**Issue by paulijar** [nextcloud/spreed#3922]
## Steps to reproduce
1. Start a chat in Nextcloud Talk
2. Write an URL enclosed in parentheses '(' and ')' to the message. The URL has to contain at least one slash '/' after the domain part, e.g. "(http://www.example.com/abc)".
3. Send the message.

### Expected behaviour
The URL should become a working link in the message history.

### Actual behaviour
When the application detects the URL in the message, it captures also the closing parenthesis to be part of the URL. Hence, the link will not work. With the example URL above, the link will become "http://www.example.com/abc)".

If the URL doesn't contain any '/' characters after the domain, then the closing parenthesis will not be captured as part of the link. This makes me believe that this is indeed a bug and not a new feature request.

Note that ')' is a legal character in an URL. Hence, it technically could belong to the URL. But if there is a '(' immediately preceding the URL and the last character of the URL seems to be ')', then the chances are pretty damn high that the user did not intend the parenthesis to be part of the URL.

![image](https://user-images.githubusercontent.com/8565946/87885087-bd796a00-ca1b-11ea-825c-9c86edaaae75.png)

## Talk app

Detected on https://cloud.nextcloud.com, I don't know about the versions or configuration of the app or the cloud.

## Browser

**Microphone available:** no

**Camera available:** no

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 78.0.2 (64-bit)

**Comment by nickvergessen** [comment]
Should be fixed with #3919

**Comment by call-me-matt** [comment]
Hello. It's fixed for links in parenthesis, but not if a question mark follows i. e.
Is the link in parenthesis really fixed (https://github.com/nextcloud/spreed/issues/3922)?
This still directs to https://github.com/nextcloud/spreed/issues/3922)? - including the closing bracket plus question mark.

**Comment by nickvergessen** [comment]
Cc @juliushaertl

**Comment by juliushaertl** [comment]
Yeah this is mainly because the regex considers `)` to be part of the url for wikipedia if the link is not wrapped into `()` without any spaces. @nickvergessen What's your oppinion about a "just wikipedia" exception there :see_no_evil: 

Or maybe we could assume that wikipedia always uses both opening and closing brackets in urls as in  https://de.wikipedia.org/wiki/Klammer_(Zeichen) so we only match the closing ones in the url if an opening is also part of it after the domain?

**Comment by nickvergessen** [comment]
Only accepting closing when there is an opening one sounds good, ignoring when there is only punctuation after the closing bracket also would be acceptable to me

**Comment by nickvergessen** [comment]
Fixed via https://github.com/juliushaertl/vue-richtext/pull/174 already I think.
