### ISSUE TITLE
internal link vs sharing to room

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#3932]
**Current handling**
A admin user shares a directory with user A and user B.
When user A shares a file form this directory to a chatroom with user B, the file will be copied in both users /Talk directories

Wouldn't it be nicer to not copy the file if user B has already access rather then creating a internal link?

And is it possible to create out of internal links automatically these nice file previews?
![grafik](https://user-images.githubusercontent.com/24530680/88141106-3c74cb00-cbf3-11ea-8789-0011df13c5fe.png)

**Comment by nickvergessen** [comment]
Previews of links are topic in #3156

**Comment by nickvergessen** [comment]
Magic detection if everyone in the conversation has already access to a file and then posting an internal link only is over the top from my pov. Especially this wouod mean that the context of a conversation can be removed by a third party.
So for now this is nothing we want to do.
