### ISSUE TITLE
Fix datachannel support with latest Janus

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#3937]
The latest version of Janus (actually since 0.7) sends all data channel messages on a channel named `JanusDataChannel`. In Talk partially support was added in https://github.com/nextcloud/spreed/commit/62f6205fafe88800a3338bb273d58599e75427dd but according to @danxuliu more changes are necessary in other places and the mobile apps.

A patch for Janus was suggested in https://github.com/meetecho/janus-gateway/pull/2285 but got rejected.

This issue to track the necessary changes in Talk to support the `JanusDataChannel`. Currently the speaker promotion doesn't work with newer versions of Janus.

**Comment by nickvergessen** [comment]
Further work done with #3940 

So now only the mobile clients are missing

**Comment by nickvergessen** [comment]
@Ivansss @tobiasKaminsky are the mobile apps sending datachannel messages? And if so on which channels?

**Comment by nickvergessen** [comment]
cc @danxuliu

**Comment by Ivansss** [comment]
As far as I know the sending was not a problem but the receiving.
The mobiles clients use the "status" datachannel to send the info.
And on iOS we also hear for @"JanusDataChannel" now.

**Comment by danxuliu** [comment]
Yes, as far as I can tell the Android app also sends messages using the "status" data channel.

If an official Janus >= 7.0.0 is used then, even if the message is sent in "status", it will be received in "JanusDataChannel". If Janus from the HPB repository is used it will be received in "status" (thanks @fancycode for the patched version :-) ).
