### ISSUE TITLE
Fix user bubble size in conversation creation dialog

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#3947]
#3901 introduced this bug

![Screenshot from 2020-07-24 14-01-06](https://user-images.githubusercontent.com/26852655/88389127-28c59200-cdb6-11ea-82b1-b9f8a7f75440.png)

Suggestion:
- Cut the first chars before the space;
- if length of the string < 3 add the second word to the selection;

_Originally posted by @ma12-co in https://github.com/nextcloud/spreed/pull/3901#issuecomment-663505063_

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/4256
