### ISSUE TITLE
📴 "Silent call" for group/public calls

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/spreed#3950]
When you are using group chats, and want to make a short call for a few persons, you need to set a new room for it.
It would be good to have the option to "JOIN" a call silently also, when yu are the first caller. The first one, sends a call message to every other registered person for the room. 

E.G You reuse an existing room for weekly meetings. the first one, wh enters the room sends call informations to all others. This is pretty inconvenient for group call or appointment calls.
For direct immediate one-on-X calls, this is pretty cool, but not for scheduled calls.

Feature-wish:
Add a checkbox: Call all participants now? with yes/no. with "no", the room shall behave as no other registered person is connected to the room.

- [x] API https://github.com/nextcloud/spreed/pull/7416
- [x] Web #7445
- [x] iOS https://github.com/nextcloud/talk-ios/issues/786
- [x] Android https://github.com/nextcloud/talk-android/issues/1991
   - [x] please ping @mahibi whenever API & Web is merged so the android implementation can be tested

**Comment by nickvergessen** [comment]
We are currently discussing an option to not be notified about calls in a conversation as addition to the chat notifications we have currently. I guess that would solve your issue too.

**Comment by Bolli84** [comment]
It is part of the solution.

Being not informed about a call needs the receipient to take the action.

It would be good if the caller would have the option during opening a group call

**Comment by jospoortvliet** [comment]
> It is part of the solution.
> 
> Being not informed about a call needs the receipient to take the action.
> 
> It would be good if the caller would have the option during opening a group call

I feel like recipients/participants should be able to decide what matters to them, not the sender.

Perhaps it makes sense to create an 'important'urgent' room where you start a call if you want everyone in, and let ppl disable this call notification on the other rooms.

**Comment by Bolli84** [comment]
If you look at Skype for business, Teams, Zoom, .... you enter a "GROUP"-room, without notifing all participants by ringing them. 

For group-rooms, talk should do that equally and the SENDER/INVITER can decide, ring all or not.
OR the ROOM-OWNER/opener/inviter should do that.

**Comment by nickvergessen** [comment]
Yeah and if you look at all mobile messengers which were our main comparisons before corona, they all do ring.

We will look into the issue, but we have many usecases to cover and we are yet unsure how to do it in a way that is not to troubleslme or disruptive

**Comment by Bolli84** [comment]
Cool.

A nice way would be a little Box for the First caller/opener in a group: "Do you want to call the participants or open the room?" 
1: Call them all
2: Open a room

1: Behavior as by now
2: Surpress the calls and just open the room.

Since we already have the Lobby/Webinar, we are already far ahead from Messengers.

**Comment by marcoambrosini** [comment]
`silent = true` when sending call request

**Comment by marcoambrosini** [comment]
Pass in `silent = true` in call request 

UI ideas
- option only available going through the device-checker?
- split button (web) / long press (mobile) approach?

**Comment by vitormattos** [comment]
@mahibi api ✅

**Comment by marcoambrosini** [comment]
Api tested [here](https://github.com/nextcloud/spreed/pull/7445) and works :)

**Comment by marcoambrosini** [comment]
@mahibi would it be possible to have some info text underneath the option like here

<img width="433" alt="Screenshot 2022-06-03 at 12 44 58" src="https://user-images.githubusercontent.com/26852655/171839554-66cbabe9-de26-4a71-8941-36d5e7cd8eec.png">

**Comment by nickvergessen** [comment]
All parts done
