### ISSUE TITLE
Generate automatic subtitles

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#3969]
### Summary
Sometimes, you're in a call with a bunch of Germans. Or French people. And you might not be German. Or French. At that point, while you could all speak Esperanto or English. But that isn't always possible! For such a situation, the automatic creation of subtitles would be immensely helpful.

This might not be super easy, on one's own server, but then again, who knows, it is 2020 already ;-)

### Solution
User can enable subtitles and select a language from a drop-down or such. Then, subtitles appear on the bottom of the video of the speaker.

### Alternative
Learn every language in the world

**Comment by nickvergessen** [comment]
Feel free to reopen when there is a JS based voice transcription lib available

**Comment by juliushaertl** [comment]
Not sure how feasible but whisper.cpp seems to be able to be compiled to WebAssembly: https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm

**Comment by sunjam** [comment]
> Feel free to reopen when there is a JS based voice transcription lib available

Would [Google Live Transcription](https://github.com/google/live-transcribe-speech-engine) be an option?  It is coded in Java and C and available under Apache 2.0 license.

**Comment by nickvergessen** [comment]
Well that basically means we would need yet another service that admins run.
The thing Julius found would run on the user's browser? Which would be much better

**Comment by simonspa** [comment]
> 



> Would [Google Live Transcription](https://github.com/google/live-transcribe-speech-engine) be an option? It is coded in Java and C and available under Apache 2.0 license.

The repository says

> This repository contains the Android client libraries for communicating with Google's Cloud Speech API that are used in Live Transcribe

so as far as I understand the actual transcription happens in a closed-source online service by Google and this is just the Android library to make use of their API.
