### ISSUE TITLE
Destroy room if empty

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#4]

**Comment by fancycode** [comment]
Empty rooms should only be removed if they have not been used for some time (configurable/fixed?), otherwise you can't reload your browser if you are the only participant in a room as the room could get deleted while reloading.

**Comment by jancborchardt** [comment]
We should delete it only after some time, but not configurable. Say when it’s not used for 12 hrs, delete it.

**Comment by ChristophWurst** [comment]
Hm, the public interface ``OCP\BackgroundJob\IJob``  is 💩  to implement and I cannot extend the convenient abstraction ``OC\BackgroundJob\Job`` because it's private API and we're using the app code checker.

@LukasReschke any idea how to solve this?

**Comment by nickvergessen** [comment]
Since leaving a room is a intentional action now, this is handled.
One2One rooms are also deleted as soon as one person intentionally leaves the room:
https://github.com/nextcloud/spreed/pull/81
