### ISSUE TITLE
External API to allow SIP bridging

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#40]
External APIs for SIP Bridge and other use-cases

**Comment by tedd77** [comment]
Hello ,
Could you please advise the status of SIP integration on spreed?
Can SIP Webrtc (ctxSip)  https://github.com/collecttix/ctxSip 
be integrated into spreed , could someone help ?
I am not a coder hence seeking some help please.

**Comment by LorbusChris** [comment]
NextCloud Talk now supposedly supports SIP gating, but I'm having a hard time finding info about the implementation.
Does the bridge functionality live here or in spreed-webrtc? Are there docs provided about the needed config?

Related: https://github.com/nextcloud/spreed/issues/575

**Comment by edidavide** [comment]
I too am very interested in the SIP Bridge feature, but could not find any info..

As far as i could see for now, it seems there will be a "SIP Gate" feature, as stated on https://nextcloud.com/talk/ , but it is not clear whether that's going to be an "hardcoded" integration with Struktur AG which will provide a callable number on their private platform and route it somehow to your nextcloud instance (which should mean SIP integration is handled by spreed?) or a generic way of registering with any SIP registrar and route calls to nextcloud users as if they were a PBX extension (which would be super cool)

Could anyone shed some light or provide some documentation about this?

Thanks !

**Comment by fancycode** [comment]
From a high-level perspective, the SIP bridge functionality is a separate service that connects one or multiple SIP endpoints (can be any SIP provider) to Nextcloud talk. Incoming calls are processed by a workflow that queries information on the room to join and connects web-participants with phone-participants that are in the same room.

**Comment by LorbusChris** [comment]
I think this topic merits further discussion, as there are various ways to implement this.

First I think it should be clarified what the goal is for this app.
Make Spreed a multi-protocol client, supporting sip, xmpp and the other ones mentioned #687?
Or leave Spreed as WebRTC-only client and rely on an MCU or a SFU for protocol translation (the aforementioned bridge)?

https://github.com/strukturag/spreed-webrtc as it is now is an an WebRTC-only MCU, is that right?
Using e.g. FreeSWITCH as MCU and WebRTC/SIP Bridge/Gateway and NC Spreed as a WebRTC softphone should be possible.
Using e.g. Jitsi as SFU and Jigasi as WebRTC/XMPP/SIP Bridge/Gateway should also be possible.

I think this is an important question, as it will also decide whether apps like the XMPP client can and will be integrated into this app or not.
Personally, I would favor working towards a plugin architecture that allows adding more transport protocols to this client, and not rely on conference servers to do all this.

**Comment by ndom91** [comment]
Any update on private SIP Gate usage? I see on the main page, you can buy the Spreed services for €5000/Year + 50€/User. This is way too much for my super small business.

**Comment by nickvergessen** [comment]
Closing this one, as SIP bridge is a feature for the MCU which is described in https://nextcloud.com/talk/

**Comment by helmut72** [comment]
This means:
- it's not self hosted
- it can't replace a PBX
- Spread doesn't allow provisioning for room systems

Using this chat/audio client for this, using that chat/audio client for that, using Lifesize/Bluejeans/Poly video conference client for another communication. This is really not what users wants. Non-IT users getting crazy with this situation.

Decision-makers take a one-client strategy. In this area, Microsoft is ahead with their Teams solution. Just for your information. I don't had any arguments lately in a discussion.

**Comment by nickvergessen** [comment]
Not sure what that has to do with provisioning rooms

And also just a correction. The high performance backend is self hosted. You get the software just like nextcloud and run it on your company's server
