### ISSUE TITLE
Conversation menu should not be in the main content

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#4007]
Currently the main menu for a conversation is on the main messages list.
When the sidebar is opened it is confusing as all the other apps on Nextcloud have the menu inside the sidebar (sharing, copy link, rename...)

TODO:
- [ ] Use the same sharing UI as server
  - [ ] Link share copy
  - [ ] Password protection
- [ ] Put the rename function in the Sidebar menu (when opened only?)

Already seen with @jancborchardt

![2020-08-12_11-03](https://user-images.githubusercontent.com/14975046/89997560-9285dd00-dc8c-11ea-9494-ce20be001ba5.png)

**Comment by nickvergessen** [comment]
Well, we've been there and had that.
I guess once we have the `Details` tab, we can move some things there. But then again adding all the "share related" settings in the participant list adds lot of bloat again that is almost never changed.

**Comment by skjnldsv** [comment]
> But then again adding all the "share related" settings in the participant list adds lot of bloat again that is almost never changed.

See with Jan, I think it should be the same across NC apps!

**Comment by PVince81** [comment]
From Talk 11.0 pre-alpha:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/277525/97972522-f0761c80-1dc4-11eb-9b93-ba23532de4e2.png">

As discussed, we can move most of the options to the "Settings" tag on the right sidebar:
- rename conversation: as pencil icon behind the name when moderator ?
- future section "visibility": see https://github.com/nextcloud/spreed/issues/1763#issuecomment-721008640
   - listable for regular users
   - listable for guest users (from guest app, when guest app is enabled)
- section "share":
   - share link
   - copy link
   - password protection
- section "Restrictions"
   - lock conversation
   - lobby mode + start time
- section SIP
   - enable SIP dial-in
   - ... potentially other new SIP options ...

**Comment by PVince81** [comment]
- if "full screen" stays the only ever option, we could replace the three dots directly with that icon

How to display "potentially dangerous flags" ? A simple auto-saving checkbox feels a bit risky for "lock room" or "visible for guests". Convert some to buttons ? 
Alternatively all this (or part of it) could be put into a modal that can be triggered from the menu or settings panel... the modal would then have a "Save" button.

Thoughts ? @nextcloud/designers-talk

**Comment by ma12-co** [comment]
We came to the conclusion that the 3 dot menu should stay there with at least the following:

- Fullscreen
- Rename
- Copy link if conv is public
- More settings (opens sidebar and conversations settings tab)

The 3 dot menu was moved out of the sidebar deliberately as a first move towards a more usable talk even with the sidebar always collapsed. Deck too has a 3 dot menu in that area just below the header.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4576

**Comment by schiessle** [comment]
Just as some quick feedback from a users perspective. I always get super confused that the rename operation is so detached from the actual name. Everytime I want to rename a room I hover over the name in the sidebar to see if I can click it in order to edit it or that a "rename icon" appears next to it on hover. It always feels strange that I have to go to the chat/video window to rename something which is displayed in the sidebar. Even that I use Talk every day and create/rename a room almost every day I can't get used to it, so I wonder how confusing it might be for people who use it only occasionally.

**Comment by PVince81** [comment]
@schiessle for now rename will stay in that menu. Moving it to a better place is a separate topic, and I agree that it's confusing currently. We did a user testing session this week and also observed that people tend to expect this elsewhere.

**Comment by PVince81** [comment]
as discussed with @ma12-co, more things to move:

- move to the conversation settings dialog:
   - [ ] mattermost settings
   - [ ] project link ?
   - [ ] from the left menu: notifications preferences

**Comment by ma12-co** [comment]
@PVince81 from the left menu I'd also bring leave/delete conversation.

To address the issue brought up by @schiessle I would go back to the regular `AppSidebar` renaming but also have a renaming capability in the conversation settigs.

Btw the discussion that we're having here is moving out from the original scope of the issue. Not sure if we should move it to anther one or rename this issue.

**Comment by PVince81** [comment]
assigning self since I'm working on https://github.com/nextcloud/spreed/pull/4576

however once this is merged we might defer the additional bits as they have less priority

**Comment by PVince81** [comment]
this https://github.com/nextcloud/spreed/issues/4007#issuecomment-721023598 is done now.

the "listable" section will be next as part of [publicly joinable rooms](https://github.com/nextcloud/spreed/issues/1763#issuecomment-721008640)

**Comment by PVince81** [comment]
the listable section was merged and appears in the dialog

**Comment by nickvergessen** [comment]
Closing as it is now a modal and things were moved from the sidebar to the modal, so I guess it is accepted by the design team (who did that)
