### ISSUE TITLE
Nextcloud disable ssl

### ISSUE THREAD

**Issue by serjke46** [nextcloud/spreed#4009]
Good day!
Installed nextcloud according to the instructions

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04

+ onlyoffoce

Can you tell me how to disable SSL for http access?

There is no domain to get a certificate. The "Unsafe connection" message in the browser is very disturbing for users.

thank

**Comment by nickvergessen** [comment]
Browsers do not allow getting microphone and/or camera permissions without https, so we can't change this 🤷‍♂️

**Comment by serjke46** [comment]
доступ к nextcloud по http?

**Comment by serjke46** [comment]
access to nextcloud over http?
