### ISSUE TITLE
Full screen application sharing

### ISSUE THREAD

**Issue by HAVP** [nextcloud/spreed#401]
Hi,

this is not a bug report, but a feature request.

It would be great if you coud specify the URL of a public room. The password protection is already requested and planed :-)

Also it would be helpfull if I could set the shared application to fullscreen without the webcam videos.

Would it be possible to join the room without a microphone and webcam and only use the screen sharing feature?

Thank you

**Comment by nickvergessen** [comment]
I dont think this is possible, you can't share your screen without being asked for audio/video by the browser before...

as for urls, I guess you want to use `/call/hello-friend` instead of `/call/abc123` ? That is and will not be possible from our side.

**Comment by florianwgnr** [comment]
@nickvergessen I think what he means is feature like "TeamViewer presentation mode", meaning guests with a link can see his applications (and hear him), but cant contribute their own video/audio feed when joining in the call.

That could be a nice feature for presentations to groups or webinars.

**Comment by nickvergessen** [comment]
> Would it be possible to join the room without a microphone and webcam and only use the screen sharing feature?

That is possible now, so I will close this issue
