### ISSUE TITLE
Artifact includes version number

### ISSUE THREAD

**Issue by stefannawrath** [nextcloud/spreed#4026]
## Steps to reproduce
I need to download several NextCloud Apps for manually installation. Therefore I will use the latest shortcut like:
https://github.com/nextcloud/calendar/releases/latest/download/calendar.tar.gz
https://github.com/nextcloud/contacts/releases/latest/download/contacts.tar.gz

This doesn't work for Spreed because the artifact name includes the version number!

### Expected behaviour
https://github.com/nextcloud/spreed/releases/latest/download/spreed.tar.gz

### Actual behaviour
https://github.com/nextcloud/spreed/releases/latest/download/spreed**-9.0.3**.tar.gz

**Comment by nickvergessen** [comment]
I prefer the version number as you know then which package you downloaded 🤷‍♂️

**Comment by stefannawrath** [comment]
It will be possible to refer a TAG like https://github.com/nextcloud/spreed/releases/download/v9.0.3/spreed.tar.gz to load a specific version

Please keep in mind, the version number beaks the latest functionality, you need to know a concrete version number to refer the latest.

I also found several other apps who includes the version number like "maps, bookmarks, social, ..." but other not "notes, calendar, contacts, tasks, mail, news, ..." Seems to be general issue/question

**Comment by nickvergessen** [comment]
Yeah well the thing is some apps are per Nextcloud version and others do not. so e.g. calendar has one upload in the appstore for 17, 18 and 19 https://apps.nextcloud.com/apps/calendar 2.0.3
But for Talk there is 7.0.4 for 17, 8.0.10 for 18 and 9.0.3 for 19. So when downloading calendar it doesnt matter as you get one file, but in talk every package is different.

If you want to update multiple instances on different versions, spreed.tar.gz and spreed (1).tar.gz are not really helpful

**Comment by stefannawrath** [comment]
Good point but in my use case I will install latest NextCloud with all latest apps.

**Comment by nickvergessen** [comment]
Closing for now
