### ISSUE TITLE
High load server for more than 4 participants

### ISSUE THREAD

**Issue by bjarkan** [nextcloud/spreed#4050]
The code is already free, but to build it and make it work is a complete nightmare.

Have you ever consider to package it in docker or inside the talk aplication itself???

**Comment by bjarkan** [comment]
Janus, nats, srtp and other libs, make it almost impossible to install... it's a nightmare...

**Comment by fancycode** [comment]
Assuming you are talking about the signaling server, docker is supported since https://github.com/strukturag/nextcloud-spreed-signaling/pull/7 was merged.

**Comment by bjarkan** [comment]
I'm not talking only about signaling server only... all the dependencies included, Nats, srtp, Janus, everything in a package included as an app for nextcloud

**Comment by nickvergessen** [comment]
That won't easily work, because the scope of PHP is too limited to run e.g. a janus server.
