### ISSUE TITLE
Own screen share is always presented even if others share their screen

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#4051]
## Steps to reproduce
1. Share your own screen
2. Let someone else also share their screen
3. Try to see the screen of the other person in promoted view

Also reproducible with two browsers on the same machine.

### Expected behaviour
You should see the others persons screen share

### Actual behaviour
You always see your own screen share

## Talk app

**Talk app version:** master

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Arch (btw)

**Browser name:** Firefox

**Browser version:** 79

**Comment by sokke90** [comment]
Hi, we also have this issue in forever, any updates? Can anyone narrow down a code location and we might take a look at it?
Thanks!

**Comment by sokke90** [comment]
https://github.com/nextcloud/spreed/blob/be0ed4a7f5f3b7eaa8acef96258862929dfd729f/src/components/CallView/CallView.vue#L93

Maybe this is the culprit, as it seems that my local screen share is shown in any case, no matter if there are any other screen shares or videos selected as priority.

**Comment by PVince81** [comment]
hmm, wondering if this is a regression from the recent changes or whether it was already happening in Talk 10.0.3

**Comment by PVince81** [comment]
right, the ticket was raised already a while ago before said changes, so not a regression but still an issue

**Comment by nickvergessen** [comment]
It used to be "sticky" either way. You always saw your own screen or the other screen. Don't remember what it used to be.
But definetly should fix.

**Comment by nickvergessen** [comment]
> or whether it was already happening in Talk 10.0.3

Report is from August btw. So that's Talk 9.0.x

**Comment by PVince81** [comment]
Still happening on master.

It is possible to see the other's screen in grid view but clicking on it doesn't enable following.

**Comment by PVince81** [comment]
I've tried with three participants to rule out https://github.com/nextcloud/spreed/issues/4817 and apparently you can see the participants' videos, but not their screen share. So something else is missing there.

In general I don't really understand why the own screen share is shown in big mode. Usually the presenter would not stay in the Talk window but be busy with the actual shared screen. In my opinion we should only show the own screen share at the bottom right in place of the own video.

But before we discuss change the design I'll see if I can fix the issue at hand first.

**Comment by PVince81** [comment]
As far as I can see in the code, the Grid view and Stripe view do not contain code to show screens, but only videos: https://github.com/nextcloud/spreed/blob/master/src/components/CallView/Grid/Grid.vue#L62

I do see use cases where people would want to show multiple screens like when doing pairing coding sessions.
This will require to extend the grid/stripe view code to detect screen shares and replace the videos with screen shares instead, when any.

**Comment by PVince81** [comment]
It also seems that it was a past design decision to always show the own screen with higher priority in the "big" part: https://github.com/nextcloud/spreed/blob/master/src/components/CallView/CallView.vue#L275

I guess this is ok, but then we need a way for the user to click to follow another user's screen share from the stripe view.

**Comment by nickvergessen** [comment]
So from my POV you should always see the "newest" screen

**Comment by PVince81** [comment]
> So from my POV you should always see the "newest" screen

Indeed.

It seems the current logic for screen share is separate from the promoted view / followed view thing. Maybe we should merge it with that somehow so we can automatically promote the "newest" screen but also allow to follow whatever screen works.

Somehow this starts to feel like a feature request "support for multiple screen shares" (with potential can of worms approaching) :-S

**Comment by PVince81** [comment]
One idea would be to get rid of Screen.vue and extend Video.vue to also support displaying a screen, if defined for the current call participant model. This way we don't need to distinguish between screen and video any more in grid view and promoted view.
The logic would be: if a screen is presented, show it, else fall back to the video, else avatar.

Then the only exception is when we want to see both the screen and the video of the presenter. This would be possible by having the presenter's Video element also present in the grid, but with a switch that tells it to not show the screen there.

@danxuliu do you see any possible issues with the merging of Screen.vue into Video.vue ?
I tried to diff both files and it seems Screen is just a stripped down version of Video.vue, with even some missing logic that we added to Video.vue later on related to display name.

And there's a myserious "remoteSessionHash" that is only used in Screen but not Video.

**Comment by PVince81** [comment]
Hmmmm... it seems the Video.vue already contains a Screen.vue, so maybe this used to work in the past: https://github.com/nextcloud/spreed/blob/master/src/components/CallView/shared/Video.vue#L39

**Comment by danxuliu** [comment]
> do you see any possible issues with the merging of Screen.vue into Video.vue ?

Screen.vue is probably there just for legacy reasons. When it was introduced the call view was a direct rewrite in Vue, so I kept the same structure that there was before. If you think that Screen.vue can be merged into Video.vue and that it simplifies the code and makes it cleaner fine by me (but please note that I have not touched that code in a while, maybe there is some reason to keep it separate too, I do not know).
