### ISSUE TITLE
rename document destroys the document

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/spreed#4065]
## Steps to reproduce
1. drag a file into the chat
2. access the file with CODE / have it accessed by two users
3. rename the file 

### Expected behaviour
file should be renamed (or: rename not possible -message)

### Actual behaviour
message appears: Das Dokument auf dem Speicher wurde geändert (...)
the original file in the Talk folder is NOT accessible any longer, op cit message appears instead

<img width="543" alt="grafik" src="https://user-images.githubusercontent.com/6523646/91426531-ee3f9100-e85c-11ea-9a98-d57b08cdc688.png">

## Talk app

**Talk app version: 9.0.3
**Custom TURN server configured:** yes/
**Custom STUN server configured:** yes

## Server configuration

**Nextcloud Version:** 19.0.2

</details>

**Comment by nickvergessen** [comment]
I guess the issue is that we loaded the path for the file in the chat already and that does not update when the file is renamed in the backend

**Comment by joergmschulz** [comment]
hopefully not related to https://github.com/nextcloud/richdocuments/issues/806

**Comment by nickvergessen** [comment]
It very likely is, as we in talk don't do anything with richdocuments itself. We just load the viewer and therefor open the file that existed.
