### ISSUE TITLE
Open shared photos directly within Nextcloud talk

### ISSUE THREAD

**Issue by Bellusterra** [nextcloud/spreed#4066]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

- Opening shared files in Nextcloud talk is not ideal, it opens Nextcloud then opens the folder then goes to where the file is and highlights it (which by the way is not visible in dark mode). Anyway it is pretty cool watching it do its thing, but not very good if you have several shared photos and when going back to Nextcloud talk it snaps back down to the bottom, which would usually be good but if you have a few photos in a row and some chat after its a real mess trying to view them all going back and forth between both apps and having to close Nextcloud each time for it to even work.

**Describe the solution you'd like**

- At least for photos i think a good solution might be automatically create the shared link as it does with the /preview extension. And have things open in a shadow box/iframe right within the talk app. That way it can all still be stored on the backend Nextcloud but feel like its in the talk app itself. 

**Describe alternatives you've considered**

- The ability to still view the file in the Nextcloud folder could also still be available through a button next to the thumbnail “View File in Nextcloud” or something like that.

**Additional context**

**Comment by nickvergessen** [comment]
Are you talking about the mobile clients or run an old version of Nextcloud (Talk)?

**Comment by nickvergessen** [comment]
Feel free to reopen with the answer.

In the web UI this improved heavily in the last two versions, so it's solved from my pov

**Comment by Bellusterra** [comment]
@nickvergessen, Sorry, missed your reply. Correct I was referring to the mobile clients, I have not tested with andriod, but on ios devices shared photos pop open the Nextcloud app and then search out the shared image and then highlight them. The way that is currently works is very handy for knowing where exactly the images are stored in Nextcloud, but most of the time I think people just want to view the photo and then get back to their conversation. It gets even more taxing when there are multiple images, going back and fourth between the Nextcloud Talk app and the Nextcloud app is not very smooth. A better option I would think would be to simply apply the /preview extension to the shared file and open it in their mobile browser or better yet a native Nextcloud Talk image view like a shadow box. I hope that this makes sense, please let me know if it isn’t and i will try and explain more.

**Comment by nickvergessen** [comment]
cc @Ivansss as we also discussed this yesterday in the office.

**Comment by PVince81** [comment]
also observed in the web UI: when clicking on a JPG image it opens a new tab (private link). Would be better if it could show the slideshow view like the photos app to view that picture full screen.

it might still be desirable to have a button to go to the actual file in NC files app

**Comment by nickvergessen** [comment]
Then you are just missing the viewer app on your dev Environment

**Comment by nickvergessen** [comment]
This is done nowadays
