### ISSUE TITLE
Default talk commands no longer work with NC 19

### ISSUE THREAD

**Issue by DrRSatzteil** [nextcloud/spreed#4077]
## Steps to reproduce
1. Use /help or /wiki in chat
2. See error message: Beim Ausführen des Befehls ist ein Fehler aufgetreten. Bitte einen Administrator, die Protokolle zu überprüfen.
3. Protocol says: Talk commands using the {ARGUMENTS_DOUBLEQUOTE_ESCAPED} are not supported anymore

### Expected behaviour
Command should be executed

### Actual behaviour
See step 2

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 9.0.3

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`) no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Android

**Browser name:** Chrome

**Browser version:** not relevant

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.2

**Nextcloud Version:** 19.0.2

**Comment by nickvergessen** [comment]
You need to remove them and then recreate them with the command. There was unluckily no way to automate this

**Comment by DrRSatzteil** [comment]
Thank you, that solved my problem
