### ISSUE TITLE
This is taking longer than expected. Are the media permissions already granted (or rejected)? If yes please restart your browser, as audio and video are failing

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#4080]
## Steps to reproduce
1. Start call
2. See appnavigation collapse
3. Wait for call to start

### Expected behaviour
Call screen is displayed

### Actual behaviour
Error notification appear, I need to close the browser and open it again to join a call

## Talk app

**Talk app version:** 9.0.3

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Arch

**Browser name:** Brave

**Browser version:** Version: 1.13.82 - Chromium: 85.0.4183.83

### Browser log

<details>
```js
Joining call
```

</details>

## Server configuration

**Nextcloud Version:** 19.0.2

**Comment by skjnldsv** [comment]
No idea how to debug further. It happens every time.
After a while or after joining a call, it fails. No logs, nothing is displayed :shrug:

**Comment by skjnldsv** [comment]
`needs info` what do you need @nickvergessen ?

**Comment by nickvergessen** [comment]
Reliable reproduction steps 🤷‍♂️😅

**Comment by skjnldsv** [comment]
> Reliable reproduction steps

Come at my office, it happens every time xD

**Comment by skjnldsv** [comment]
Please, this is just incredibly annoying, cc @danxuliu @PVince81 
It only happens with talk, it seems like it lock by webcam/microphone and only a browser close can fix it.
Any other website can still use the webcam !

**Comment by PVince81** [comment]
> Please, this is just incredibly annoying, cc @danxuliu @PVince81
> It only happens with talk, it seems like it lock by webcam/microphone and only a browser close can fix it.
> Any other website can still use the webcam !

see https://github.com/nextcloud/spreed/issues/4008 for the "camera still on during call"
