### ISSUE TITLE
Don't show join call message after starting a call 

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4085]
![Screenshot from 2020-09-02 09-18-14](https://user-images.githubusercontent.com/26852655/91954543-3ac61900-ed02-11ea-8877-c28b10ca74f6.png)

**Comment by nickvergessen** [comment]
It will update when your participant object is updated and tells that you have a session in the call `¯\_(ツ)_/¯`

**Comment by ma12-co** [comment]
We should open the callview (in a loading state) immediately upon clicking the start call button.

**Comment by nickvergessen** [comment]
See #4086

**Comment by danxuliu** [comment]
> We should open the callview (in a loading state) immediately upon clicking the start call button.

As explained in #3584 I do not think that we should do that. I think that the current behaviour, showing a loading spinner in the _Join call_ button that you have just clicked until the call can be really joined, is better than immediately showing an empty call view (even if in a loading state, as it could go away even before you had time to read what it says).

**Comment by nickvergessen** [comment]
![phonebook](https://user-images.githubusercontent.com/213943/92079308-f7ca7b00-edbf-11ea-9975-27dac2531797.jpg)

To me this looks just unresponsive and laggy. Android also doesn't put a spinner on the phone icon when you call a contact. Instead you get a black call like screen, hangup button and avatar of the other person are the only things visible. There doesn't need to be any text in this switching state, just clear indication that things are moving on and a loading icon on the call button is not good enough for 15 secs (which it takes in our company wide call with the hundreds notifications being sent).

**Comment by ma12-co** [comment]
> is better than immediately showing an empty call view (even if in a loading state, as it could go away even before you had time to read what it says).

@danxuliu we just need to implement proper feedback for all the possible states and tell the user about it. E.g. we could put up a message in the empty view that says something like "call failed" for a couple of seconds before going back to the chat 

So basically we'd be adding 2 states to the callview:

- Loading state;
- Connection failed state;

Is there anything else you think we need?

**Comment by danxuliu** [comment]
> we just need to implement proper feedback for all the possible states and tell the user about it.

No, I do not mean things like call failed. I mean that when you join a call if the call view is immediately shown until you start connecting to the other participants the call view will be empty. If in that state you show a message like "Connecting to the other participants" to give feedback to the user about why the call view is empty in some cases the user will be able to read that. But if connecting to the other participants is fast then you will just see a message that goes away before you were able to read what it said.

Anyway it seems that I am the only one concerned about that :-P so feel free to do the change.

**Comment by ma12-co** [comment]
> But if connecting to the other participants is fast then you will just see a message that goes away before you were able to read what it said.

But just like in any other app, even phone apps, the only ones that see the dialing/connecting messages are the ones that have the slow connection. If the connection is blazing fast you don't even notice it because it stays up for not much.

**Comment by nickvergessen** [comment]
This doesn't appear like that anymore atm, so I'm closing this
