### ISSUE TITLE
Shared folder to conversation isn't accessible through the conversation after leaving the share

### ISSUE THREAD

**Issue by quizilkend** [nextcloud/spreed#4087]
## Steps to reproduce
1. Someone shares a folder to a conversation I am part of.
2. I look at the folder (in the files app) and decide to leave the share.
3. Now the shared folder isn't available in the talk app anymore for me. For other participants the folder is still there.

### Expected behaviour
The folder should still be accessible in the talk app and the share should be reactivated if I click on it.
Right now the chat is inconsistent. Some users see the shared folders and others see the message 'xy shared a file which is not present anymore' (freely translated from 'xy hat eine Datei geteilt, die nicht mehr vorhanden ist'

### Actual behaviour
See steps to reproduce.

## Talk app

**Talk app version:** 9.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Debian buster

**Browser name:** Firefox

**Browser version:** 80

## Nextcloud:

**Nextcloud Version:** 19.0.2

**Comment by nickvergessen** [comment]
Well it's the same when you leave a normal group share. I don't really feel like working around this in the talk app, as we simply share files by saying to sharing `this is the file and this is the access list`. And when you leave the accesslist we can't render the item anymore as the file is not found for you anymore. Pumping that up to then get all shares and shares on parents for the owner and then reshares and see if there is somewhere a way for you to still access it is over the top for me.

**Comment by quizilkend** [comment]
Ok I get your point.
Just out of curiousity: would it be possible to handle the shares in a conversation like the shares via link. This way the share would be persistent I guess...

**Comment by quizilkend** [comment]
Hello,
I've been thinking about this issue and was wondering if it is possible to add the participants to the access list again, if they click on the shared link in the conversation.
