### ISSUE TITLE
add option to use system matterbridge binary

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4096]
In the config for matterbridge, it'd be good to have an option to use the matterbridge binary on the system. So a bit similar to how Collabora does it, but then only for a local binary in the $PATH, no need to complicate it more... A simple 2 option radio button - use built-in or use system matterbridge.

Current config:
![Screenshot_20200904_105231](https://user-images.githubusercontent.com/551757/92220958-02a70d80-ee9d-11ea-8079-18bce3d40c77.png)

How it is in Collabora Online:
![Screenshot_20200904_105251](https://user-images.githubusercontent.com/551757/92220948-fd49c300-ee9c-11ea-9d5e-adc5169252f1.png)

I can imagine it could look something like this (bit of gimping here):
![matterbridge mockup](https://user-images.githubusercontent.com/551757/92222664-a396c800-ee9f-11ea-8224-0d433768825f.png)

**Comment by nickvergessen** [comment]
We have an app config already where you can set the path. Since this is executed I don't feel like putting it in the UI. But maybe we need to extend the description to reflect this better

**Comment by eneiluj** [comment]
@nickvergessen But currently there is no way to change the config value except manually editing the DB, right?

What about an option to make the config value empty? It would lead to running `matterbridge` command and leave the server system admin the freedom to install/compile/whatever and place the binary somewhere in the PATH.

**Comment by nickvergessen** [comment]
> But currently there is no way to change the config value except manually editing the DB, right?

`occ config:app:set spreed matterbridge_binary --value="path to binary"`

**Comment by jospoortvliet** [comment]
yeah, if we document that a tiny bit and link to that doc, it is fine too... doesn't need to be a GUI, you need server CLI access for this anyway (to install the app manually).

**Comment by jospoortvliet** [comment]
so #4118 fixes this :+1:
