### ISSUE TITLE
matterbridge: restart bridges automatically

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4097]
Right now, if a matterbridge bridge process crashes or the server is rebooted, the bridge remains down. Would be good to have a cronjob that runs every now and then to check if all configured bridges are running and, when one is down, restart it.

**Comment by eneiluj** [comment]
@nickvergessen Would you be ok with an hourly cron job calling `checkAllBridges()`?

**Comment by nickvergessen** [comment]
Can also run every 5 minutes, don't care too much.

**Comment by jospoortvliet** [comment]
and #4119 fixes this!
