### ISSUE TITLE
installing matterbridge binary gives error

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4102]
Tried to install the matterbridge error on tech-preview (sysadmins can give access to logs).

Error I get:
![Screenshot_20200904_184324](https://user-images.githubusercontent.com/551757/92267188-b5e52600-eee0-11ea-8a7a-536bfb15ce58.png)

Logs: only have javascript log, as the Nc log stays empty. Both myself and another user tried, we both got the same error. Javascript console output:
```
call:
https://nextcloud.lucpasmans.nl/nextcloud/ocs/v2.php/apps/spreed/api/v1/bridge/version
{"ocs":{"meta":{"status":"failure","statuscode":400,"message":null},"data":{"error":"binary_permissions"}}}
(using javascript console)

MatterbridgeIntegration.vue:157 Error: Request failed with status code 400
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:61)
```
For me:
```
xhr.js:178 GET https://tech-preview.nextcloud.com/ocs/v2.php/apps/spreed/api/v1/bridge/version 400 (Bad request)
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
l.request @ Axios.js:61
r.forEach.l.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
(anonymous) @ matterbridgeService.js:76
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
i @ admin-settings.js?v=19c9f4e0-0:352
o @ admin-settings.js?v=19c9f4e0-0:352
(anonymous) @ admin-settings.js?v=19c9f4e0-0:352
(anonymous) @ admin-settings.js?v=19c9f4e0-0:352
(anonymous) @ matterbridgeService.js:75
(anonymous) @ MatterbridgeIntegration.vue:151
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ce @ admin-settings.js?v=19c9f4e0-0:373
i @ admin-settings.js?v=19c9f4e0-0:373
Promise.then (async)
ce @ admin-settings.js?v=19c9f4e0-0:373
i @ admin-settings.js?v=19c9f4e0-0:373
(anonymous) @ admin-settings.js?v=19c9f4e0-0:373
(anonymous) @ admin-settings.js?v=19c9f4e0-0:373
enableMatterbridgeAppCallback @ MatterbridgeIntegration.vue:137
(anonymous) @ MatterbridgeIntegration.vue:134
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
ce @ admin-settings.js?v=19c9f4e0-0:373
i @ admin-settings.js?v=19c9f4e0-0:373
(anonymous) @ admin-settings.js?v=19c9f4e0-0:373
(anonymous) @ admin-settings.js?v=19c9f4e0-0:373
enableMatterbridgeApp @ MatterbridgeIntegration.vue:127
ze @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
s._wrapper @ vue.runtime.esm.js:6917
MatterbridgeIntegration.vue:157 Error: Request failed with status code 400
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:61)
```

Hope it helps track down the problem and improve, if possible, error reporting ;-)

**Comment by sunjam** [comment]
@jospoortvliet [Appstore install doesn't seem to work](https://github.com/nextcloud/talk_matterbridge/issues/2), but [I was just able to install the app manually](https://github.com/nextcloud/nextcloudpi/issues/1177).

_copy-pasta of commands I used to install successfully, then restarted Nextcloud and clicked admin install button again.:_

`
cd /var/www/nextcloud/apps && wget https://github.com/nextcloud/talk_matterbridge/releases/download/v1.18.2/talk_matterbridge-1.18.2.tar.gz && tar -xf talk_matterbridge-1.18.2.tar.gz && rm -rf talk_matterbridge-1.18.2.tar.gz && chown www-data talk_matterbridge/ ./talk_matterbridge/bin/ ./talk_matterbridge/lib && chgrp www-data talk_matterbridge/ ./talk_matterbridge/bin/ ./talk_matterbridge/lib`

[Once installed you'll need to create a bot user](https://github.com/nextcloud/talk_matterbridge/issues/7).

**Comment by nickvergessen** [comment]
> Once installed you'll need to create a bot user. 

No, this is not needed as Talk does it automatically in 20

**Comment by nickvergessen** [comment]
Should be fixed in the next release of talk_matterbridge since https://github.com/nextcloud/talk_matterbridge/issues/2 is now closed.
