### ISSUE TITLE
Use /Attachments/Talk sub-directory by default

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#4114]
Bookmarks app now supports saving urls to the filesystem in latest beta under /Bookmarks.
Talk saves attachments to /Talk
Now doubt other apps will follow.

I gently recommend making the default directory structure:
`/Attachments/Talk`

**Comment by jospoortvliet** [comment]
would be good if outlook add-in would do that, too.

probably easy to do, a good first issue @nickvergessen ?

**Comment by nickvergessen** [comment]
Not really. The main issue is we can't change it really without breaking for people that got attachments already, but didn't configure the folder manually.

**Comment by garblixa** [comment]
Better provide a global configuration option to specify the talk attachments path.
Here the students have no local storage on the nextcloud server, everything is stored on the external storage. Therefore a configuration option would be good.

**Comment by sunjam** [comment]
> Better provide a global configuration option to specify the talk attachments path.

Yeah, this would be a solution.  I noticed in testing the v20 beta that if an app such as Talk must be re-enabled due to incompatibility it resets to default `/Talk` directory, which is then created on the filesystem.  So, that undermines my using `/Attachments/Talk` without some form of persistence.

**Comment by nickvergessen** [comment]
An admin option is issued here #3868

**Comment by sunjam** [comment]
Thanks!
