### ISSUE TITLE
Allow to immediately share a room via email

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/spreed#412]
the search for users to add to the video chat shows not only the name, but also the mail. A login can be "brute forced". This is very bad.

**Comment by lvarnava** [comment]
Nextcloud 12.0.2
Video calls 2.0.1

**Comment by lvarnava** [comment]
![_2017-09-20_00-32-18](https://user-images.githubusercontent.com/32108411/30616553-4605d832-9d9b-11e7-9071-de7c566db9b4.png)
![_2017-09-20_00-29-18](https://user-images.githubusercontent.com/32108411/30616562-4bc2f7b4-9d9b-11e7-8321-da3fda20e5af.png)

**Comment by nickvergessen** [comment]
Well there is no "bruteforce" vector here, because that also works via the share field ;)

But yeah, we should only show users and groups in the dropdown

**Comment by lvarnava** [comment]
![_2017-09-20_22-03-16-](https://user-images.githubusercontent.com/32108411/30662442-c88be814-9e4f-11e7-905c-469aa7012c99.png)

**Comment by nickvergessen** [comment]
Actually when you type an email we should create a public room and send an email to the recipient
