### ISSUE TITLE
menu hidden under video view

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4131]
## Steps to reproduce
1. start a video call
2. use the avatar menu (say you want to send an email to somebody...)
3. see how half the menu is hidden under the video view

### Expected behaviour
the menu should be above the video view - z-index issue?!?!

### Actual behaviour
it's not...

## Talk app

**Talk app version:**
Version and configuration of cloud.nextcloud.com
same on sermo - screenshot is from Sermo:
![Screenshot_20200909_180150](https://user-images.githubusercontent.com/551757/92623516-9b3af480-f2c6-11ea-8cbb-339b8e92fac4.png)

Lightly related to https://github.com/nextcloud/spreed/issues/2575 but that only solved the shining through of the avatar.

**Comment by nickvergessen** [comment]
Looks like a wrong boundaries-element for avatars in the chat
