### ISSUE TITLE
Own status indicator only updates after reload

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4132]
I just tested the new online status feature on c.nc.com... really nice!

I noticed that when I change my own status I need to reload the page to update the indicator for myself in the participant list. Even changing rooms doesn't update it. That's quite irritation because as a user you get confused about whether your status change was successful or not.

**Comment by nickvergessen** [comment]
That's a problem with all statuses and it's caused by the vue library.
Reference is https://github.com/nextcloud/server/pull/22801 and then the vue library needs to listen to that and update the status on avatars
