### ISSUE TITLE
Avatars and images are above avatar menu

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4147]
![Screenshot_20200914_100740](https://user-images.githubusercontent.com/551757/93060309-3854af00-f672-11ea-9533-4fb12894b576.png)

I guess the screenshot says it all.

This is on cloud.nextcloud.com with latest beta and all that 😭

**Comment by jospoortvliet** [comment]
related to https://github.com/nextcloud/spreed/issues/4131 and https://github.com/nextcloud/spreed/issues/2575

**Comment by nickvergessen** [comment]
Arg, what a painful back and forth...

**Comment by PVince81** [comment]
Just noticed that too

It seems the avatar element has `position: sticky` and removing it solves the issue.

Apparently the sticky is there to make sure the avatar stays visible when scrolling down.

It appears that increasing the z-index for the popover menu doesn't make it appear higher.
And making the menu "sticky" as well breaks its layout.

**Comment by PVince81** [comment]
Hmmm, tricky: I see that the popovermenu itself is also a child of the avatar, so it's inside a sticky element too...

One interesting thing to see is that when scrolling down, the "sticky" avatar element does get covered by the hamburger menu on top. So there is definitely a way to have another element overlap it.

I found a solution for z-index that requires to set position:relative + z-index: 1 on the currently highlighted element. I'll see if we can trigger this through code...

**Comment by PVince81** [comment]
Not a simple fix: it seems the Avatar element is from the library or server. We could extend it to emit an event whenever the popup opens or not.

I tried another thing with z-index, but it requires setting it on every row in descending order, based on the id... and cannot be negative... feels like a big hack. `<div class="message-group" :style="{'z-index': 100000-id, 'position', 'relative'}">` ...

**Comment by PVince81** [comment]
Would it be bad to not have the avatars be sticky any more ? It only means that when scrolling down one might not see the avatar for grouped messages.

Removing the sticky attribute would solve the overlap problem.

**Comment by nickvergessen** [comment]
cc @jancborchardt can you check the last comment

**Comment by PVince81** [comment]
some hope for a fix here https://github.com/nextcloud/nextcloud-vue/pull/831 as it changes the DOM structure, or at least more possibilities to explore for a fix

**Comment by jancborchardt** [comment]
> Would it be bad to not have the avatars be sticky any more ? It only means that when scrolling down one might not see the avatar for grouped messages.

Yeah I’d say that’s not desirable. Having them sticky is quite nice and gives you context, we did add it for that exact reason. :) 

> the "sticky" avatar element does get covered by the hamburger menu on top. So there is definitely a way to have another element overlap it.

This is unrelated but also something to fix – on narrow screens, the avatar should be sticky below the hamburger menu, not overlapped by it.

**Comment by jospoortvliet** [comment]
not sure if related:
![Screenshot_20201123_093706](https://user-images.githubusercontent.com/551757/99944593-6ee62e80-2d73-11eb-8847-a27106c656ac.png)
that is in the participant list.

**Comment by nickvergessen** [comment]
That's a but from the user status feature in server.
Please report there

**Comment by PVince81** [comment]
the new Avatar component PR would solve this issue, see: https://github.com/nextcloud/nextcloud-vue/pull/831#issuecomment-762186783

**Comment by PVince81** [comment]
PR here for library upgrade that will fix the issue: https://github.com/nextcloud/spreed/pull/4976

<img width="274" alt="image" src="https://user-images.githubusercontent.com/277525/105153759-14feac80-5b09-11eb-8553-66b8fad77d42.png">
