### ISSUE TITLE
Groupchat: Improvement suggestion: external participants disappear after invitation

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/spreed#4151]
Proposal for group chat with external participants

After clicking on external participants the mail address disappears. The participant is only visible when entering the conference room. There is no feedback to the moderator whether the invitation to the external participants was successful. The participant may already be listed here in grey. Laymen often have problems at this point. **Some kind of feedback for the moderator would be useful here to avoid uncertainty**

![test_Talk_ZBB_HUB](https://user-images.githubusercontent.com/63851138/93212860-6fef5400-f763-11ea-9a8a-65dfb4a6b2bd.png)

**Comment by nickvergessen** [comment]
Ser #1902
