### ISSUE TITLE
feature request: hyperlinks

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/spreed#4157]
feature request: being able to use in the chat, perhaps with a button, but also with CTRL-K
seems to me this would already be a request, but i searched for it and could not find it. apologies if i missed it. 

thanks for the amazing work on this app, we have just moved all our office admin over to NC because there is Talk!

**Comment by nickvergessen** [comment]
I don't quite get what you want. Mind to explain it?

**Comment by Rik44444** [comment]
to be able to add hyperlinks, like here in Github, when you select a bit of text and press "Ctrl-K", the hyperlink function is triggered and you can enter a URL to be the hyperlink for that bit of text

**Comment by nickvergessen** [comment]
Ah, yeah that's a duplicate of #1027
