### ISSUE TITLE
feature request: being able to export and import

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/spreed#4159]
feature request: being able to export and import Talk conversations, preferably to easily readible files that can be opened with basic programmes on a PC. 2 use cases:
1. being able to move NC Talk to a new instance 
2. backing up conversations for admin purposes in Files and being able to read those later with a standard text editor

**Comment by nickvergessen** [comment]
Well the thing is you will loose a lot of context on the way, as attachments user names and so on might not be available of have different ids, etc.
You can do this currently by just exporting the `oc_comments` database table. It holds all the message.

Also note that this is contraditing with our long term goal "end to end encryption", which would then not work anymore #1437

**Comment by Rik44444** [comment]
thanks for the reply, I appreciate it. Can the oc_comments table also be imported into a new instance?

**Comment by nickvergessen** [comment]
Not really, as the tokens and ids are generated randomly. you would need to manually fix them everywhere.

**Comment by Rik44444** [comment]
OK, well, but tbh this is something that really needs to be changed. On any Todo-list app, import/export functionality is super-important, especially because hosting providers stop operations all the time. I'm not sure why this request has been closed, but I would like to ask for it to be re-opened, so people can vote for it.

**Comment by nickvergessen** [comment]
well in that case you would export everything and import everything and it would work. just not copying something to an existing nextcloud works.

**Comment by Rik44444** [comment]
sure, that sounds logical
