### ISSUE TITLE
How can I add a button myself in the video calling UI to perform certain operations?

### ISSUE THREAD

**Issue by rohnitVizexperts** [nextcloud/spreed#4171]
Hi,
I wanted to add a button in the chat window and by the click of the button perform certain operations, it's too little of a thing to add it in your feature list. So, I thought I will do it myself, by a little guidance of anyone concerned with the app!

Can you please help me and guide me how it can be done?

Thanks in advance!

**Comment by nickvergessen** [comment]
Since our frontend is compiled JS that is not easily possible. The only way to do it otherwise is to wait until the UI loaded and then adding your button via your own app on our UI

**Comment by rohnitVizexperts** [comment]
@nickvergessen Thanks for the help!
