### ISSUE TITLE
Unclear which replies are to you or to others

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4174]
## Steps to reproduce
1. Go to a conversation which has messages with replies
2. Scroll through cause you were mentioned
3. Try and find the relevant replies for you

### Expected behaviour
It’s clear which replies are to messages from you, and which are to messages from others.

### Actual behaviour
All quotes look the same. It’s very difficult to see when a reply is to something you said or to someone else. You need to manually read the name.

One way would be e.g. to only make the left bar blue for the qoutes which are from you. The others could be grey like `var(--color-border-dark)`:

Before | After
-|-
![quotes before](https://user-images.githubusercontent.com/925062/93508750-12076b80-f91f-11ea-84bf-6d15330ca711.png) | ![quotes after](https://user-images.githubusercontent.com/925062/93508748-10d63e80-f91f-11ea-8ff8-1c2220f23693.png)

As discussed @ma12-co

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4940
