### ISSUE TITLE
Error log when User is part of a conversation that never logged in due to having no folders: [files_sharing] Error: OCP\Files\NotFoundException: / 

### ISSUE THREAD

**Issue by Debianer** [nextcloud/spreed#4183]
## Steps to reproduce
1. Create users (I used the API)
2. Create conversation in Nextcloud Talk containing said user
3. Get lots of errors in the log

Here is the log:

[files_sharing] Error: OCP\Files\NotFoundException: / not found while trying to get owner at <>

/var/www/html/custom_apps/spreed/lib/Share/Listener.php line 82
OC\Files\View->getOwner("/")
/var/www/html/custom_apps/spreed/lib/Share/Listener.php line 48
OCA\Talk\Share\Listener->overwriteMountPoint(OCP\Share\Events\VerifyMountPointEvent {})
/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
OCA\Talk\Share\Listener::listenVerifyMountPointEvent(OCP\Share\Events\VerifyMountPointEvent {}, "OCP\Share\Eve ... t", Symfony\Componen ... {})
/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
Symfony\Component\EventDispatcher\EventDispatcher->callListeners([Closure {}], "OCP\Share\Eve ... t", OCP\Share\Events\VerifyMountPointEvent {})
/var/www/html/lib/private/EventDispatcher/EventDispatcher.php line 86
Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCP\Share\Events\VerifyMountPointEvent {}, "OCP\Share\Eve ... t")
/var/www/html/lib/private/EventDispatcher/EventDispatcher.php line 98
OC\EventDispatcher\EventDispatcher->dispatch("OCP\Share\Eve ... t", OCP\Share\Events\VerifyMountPointEvent {})
/var/www/html/apps/files_sharing/lib/SharedMount.php line 98
OC\EventDispatcher\EventDispatcher->dispatchTyped(OCP\Share\Events\VerifyMountPointEvent {})
/var/www/html/apps/files_sharing/lib/SharedMount.php line 79
OCA\Files_Sharing\SharedMount->verifyMountPoint(OC\Share20\Share {}, [], OC\Cache\CappedMemoryCache {})
/var/www/html/apps/files_sharing/lib/MountProvider.php line 112
OCA\Files_Sharing\SharedMount->__construct("\OCA\Files_Sharing\SharedStorage", [], {user: "UserNameDebianer ... e}, OC\Files\Storage\StorageFactory {}, OC\Files\View {}, OC\Cache\CappedMemoryCache {})
/var/www/html/lib/private/Files/Config/MountProviderCollection.php line 115
OCA\Files_Sharing\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
/var/www/html/lib/private/Files/Filesystem.php line 451
OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
/var/www/html/lib/private/Files/Filesystem.php line 376
OC\Files\Filesystem::initMountPoints("UserNameDebianer")
/var/www/html/lib/private/legacy/OC_Util.php line 308
OC\Files\Filesystem::init("UserNameDebianer", "/UserNameDebianer/files")
/var/www/html/lib/private/Files/Utils/Scanner.php line 116
OC_Util::setupFS("UserNameDebianer")
/var/www/html/lib/private/Files/Utils/Scanner.php line 155
OC\Files\Utils\Scanner->getMounts("")
/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 83
OC\Files\Utils\Scanner->backgroundScan("")
/var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 111
OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
/var/www/html/lib/private/BackgroundJob/Job.php line 62
OCA\Files\BackgroundJob\ScanFiles->run(null)
/var/www/html/lib/private/BackgroundJob/TimedJob.php line 57
OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
/var/www/html/cron.php line 126
OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
at 2020-09-18T19:40:01+00:00

**Comment by Debianer** [comment]
I have only one user left that never logged in but is part of a conversation and I see the above error message almost exactly every 15 minutes, independent of activity.

**Comment by nickvergessen** [comment]
This was fixed with https://github.com/nextcloud/spreed/pull/4165/files already

**Comment by nickvergessen** [comment]
Feel free to apply the patch and report the results
