### ISSUE TITLE
Endpoint Hardware-Support

### ISSUE THREAD

**Issue by HansJochens** [nextcloud/spreed#4193]
In my company are 4 meeting rooms, which are equipped with lifesize-endpoints and an external pexip-server.
It would be nice, to use these endpoints for communication with nextcloud talk. 
Our board of directors wants endpoints instead of computers in the rooms. 
As long as endpoints are not supported, our IT cant deploy nextcloud talk as videoconference solution. 

Is there a solution how to use hardware-endpoints or are there plans to support them in the future?

**Comment by nickvergessen** [comment]
Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! 🙂

There are many way to get new features in Nextcloud:

1. The easiest and most straight forward way (especially here at Github): pull request.
    Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.

2. We have a [category for Freelancers in our forum](https://help.nextcloud.com/c/nextcloud-freelancing). Another option would be to post an offer there and try to find a freelancer who want to work on it.

3. The most direct way for a company or organization to get the issue addressed is to get a [Enterprise Subscription](https://nextcloud.com/pricing/). This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. Feel free to [reach out to us](https://nextcloud.com/contact/). We are happy to explore the possibilities how to make Nextcloud fit your needs.
