### ISSUE TITLE
Check JavaScript / CSS files for errors/style

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#42]
There should be a CI job checking the JavaScript / CSS files for errors/style on commit / PR.

If somebody could provide me some details how you handle this with your CI setup, I could take a look at creating a PR.

**Comment by jancborchardt** [comment]
cc @MorrisJobke for CI, can you help here?

**Comment by MorrisJobke** [comment]
We use drone: http://readme.drone.io/0.5/usage/overview/

Just create a PR with a `.drone.yml` and it should run. I enabled it for pull requests. If you need to place a special docker container we have our repo here: https://github.com/nextcloud/docker-ci <- for every special container we create a subdirectory and then I will setup a tag based automatic build on docker hub.

**Comment by fancycode** [comment]
I have a branch ready that implements this, but will wait for the Docker images to become available before pushing.

**Comment by MorrisJobke** [comment]
https://hub.docker.com/r/nextcloudci/stylelint/builds/ and https://hub.docker.com/r/nextcloudci/eslint/builds/  are now ready :) 

Feel free to add something similar to the server too 😉

**Comment by jancborchardt** [comment]
@fancycode so is this fixed via #42 and can it be closed? :)

**Comment by MorrisJobke** [comment]
It's fixed via #48 ;)

**Comment by fancycode** [comment]
Yeah, sorry for not closing earlier ;-)
