### ISSUE TITLE
Videocall tokens can be easily bruteforced

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/spreed#421]
Using NC 12.0.2.

nextcloud.example.com/call/**u8fw**

Currently the token is a 4 characters, which should in theory be easily bruteforceable. I suggest using a way longer token.

**Comment by nickvergessen** [comment]
It was already updated to 8 chars in the next release.
However we wanted the tokens to be easily transferable (e.g. via phone, or when you have to type it from a screen to your mobile etc)

**Comment by nickvergessen** [comment]
#381
