### ISSUE TITLE
Installation error: "oc_talk_participants"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#4230]
When installing Talk v10.0.0-rc.2 and v9.0.4 versions in Nextcloud 20.0.0 beta4 there is an error:
`There is no table with name 'xxx.oc_talk_participants' in the schema.`

There are no tables for Talk in the phpMyAdmin database.

**Database:**
phpMyAdmin
libmysql - mysqlnd 5.0.12-dev - 20150407

**PHP version:**
7.3.16 

**Nextcloud Version:** (see admin page)
20.0.0 beta4

**Comment by nickvergessen** [comment]
Can you add:
```php
\OC::$server->getLogger()->error(json_encode($files));
```

before this line in your server code:
https://github.com/nextcloud/server/blob/50230847ce47133dd0be170457f24bf5e6ac4ab8/lib/private/DB/MigrationService.php#L240

**Comment by Valdnet** [comment]
@nickvergessen The problem is still the same after adding the `\OC::$server->getLogger()->error(json_encode($files));` line in the MigrationService.php file.

**Comment by nickvergessen** [comment]
Sorry forgot to say, this will put a line in the log, can you check your log file for the new line? Should contain a lot of `OCA\Talk\Migration` strings

**Comment by Valdnet** [comment]
@nickvergessen Here are the errors in the log:

```
Error	settings
Doctrine\DBAL\Schema\SchemaException: There is no table with name 'xxx_chmura.oc_talk_participants' in the schema.
    /home/xxx/public_html/chmura/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php - line 172:
    Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist("xxx_chmura. ... s")
    /home/xxx/public_html/chmura/lib/private/DB/SchemaWrapper.php - line 93:
    Doctrine\DBAL\Schema\Schema->getTable("xxx_chmura. ... s")
    /home/xxx/public_html/chmura/apps/spreed/lib/Migration/Version8000Date20200331144101.php - line 38:
    OC\DB\SchemaWrapper->getTable("talk_participants")
    /home/xxx/public_html/chmura/lib/private/DB/MigrationService.php - line 478:
    OCA\Talk\Migration\Version8000Date20200331144101->changeSchema(OC\Migration\SimpleOutput {}, Closure {}, { tablePrefix: "oc_"})
    /home/xxx/public_html/chmura/lib/private/DB/MigrationService.php - line 414:
    OC\DB\MigrationService->executeStep("8000Date20200331144101", false)
    /home/xxx/public_html/chmura/lib/private/Installer.php - line 157:
    OC\DB\MigrationService->migrate()
    /home/xxx/public_html/chmura/apps/settings/lib/Controller/AppSettingsController.php - line 448:
    OC\Installer->installApp("spreed")
    /home/xxx/public_html/chmura/lib/private/AppFramework/Http/Dispatcher.php - line 169:
    OCA\Settings\Controller\AppSettingsController->enableApps([ "spreed"], [])
    /home/xxx/public_html/chmura/lib/private/AppFramework/Http/Dispatcher.php - line 100:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")
    /home/xxx/public_html/chmura/lib/private/AppFramework/App.php - line 152:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")
    /home/xxx/public_html/chmura/lib/private/Route/Router.php - line 308:
    OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { action: nu ... "})
    /home/xxx/public_html/chmura/lib/base.php - line 1009:
    OC\Route\Router->match("/settings/apps/enable")
    /home/xxx/public_html/chmura/index.php - line 37:
    OC::handleRequest()
```

**Comment by nickvergessen** [comment]
There should be one looking like:
```json
{"7":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2000Date20170707093535.php","29":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2000Date20171026140256.php","18":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2000Date20171026140257.php","4":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20170707115443.php","10":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20170913104501.php","17":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20170921145301.php","28":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20170929092606.php","11":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20171009132424.php","3":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20171026134605.php","27":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20171026141336.php","14":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20171031102049.php","25":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20180103144447.php","22":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version2001Date20180103150836.php","12":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3002Date20180319104030.php","16":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180707222130.php","15":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180718112436.php","19":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180718133519.php","31":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180720162342.php","30":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180722152733.php","26":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180722152849.php","6":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version3003Date20180730080327.php","9":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version4099Date20181001123058.php","5":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version5099Date20190121102337.php","2":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version5099Date20190319134820.php","0":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version6099Date20190627172429.php","1":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version7000Date20190717141457.php","24":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version7000Date20190724121136.php","32":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version7000Date20190724121137.php","21":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version8000Date20200331144101.php","33":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version8000Date20200402124456.php","20":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version8000Date20200407073807.php","23":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version8000Date20200407115318.php","13":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version10000Date20200819121721.php","8":"\/home\/nickv\/Nextcloud\/21\/server\/appsbabies\/spreed\/lib\/Migration\/Version11000Date20200922161218.php"}
```

**Comment by Valdnet** [comment]
`{"12":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2000Date20170707093535.php","19":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2000Date20171026140256.php","13":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2000Date20171026140257.php","7":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20170707115443.php","23":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20170913104501.php","11":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20170921145301.php","6":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20170929092606.php","18":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20171009132424.php","0":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20171026134605.php","30":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20171026141336.php","17":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20171031102049.php","10":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20180103144447.php","31":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version2001Date20180103150836.php","26":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3002Date20180319104030.php","9":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180707222130.php","16":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180718112436.php","27":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180718133519.php","8":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180720162342.php","14":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180722152733.php","24":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180722152849.php","21":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version3003Date20180730080327.php","3":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version4099Date20181001123058.php","28":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version5099Date20190121102337.php","20":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version5099Date20190319134820.php","15":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version6099Date20190627172429.php","2":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version7000Date20190717141457.php","4":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version7000Date20190724121136.php","5":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version7000Date20190724121137.php","22":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version8000Date20200331144101.php","1":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version8000Date20200402124456.php","29":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version8000Date20200407073807.php","25":"\/home\/xxx\/public_html\/chmura\/apps\/spreed\/lib\/Migration\/Version8000Date20200407115318.php"}`

**Comment by nickvergessen** [comment]
Hmm the error make no sense with this result 🤔 

Also you should not be able to install 9.0.4 on 20beta at all. 9.0.4 is only compatible with Nextcloud 19.

Also can you retry with 20rc2? beta 4 is quite old

**Comment by Valdnet** [comment]
@nickvergessen On the installed NC 20 RC2 I still have the option to download Talk 9.0.4, which reports the same error when installing.
![obraz](https://user-images.githubusercontent.com/47037905/94302623-c8e19800-ff6c-11ea-958b-21195a84acff.png)

**Comment by nickvergessen** [comment]
Well find the 10 rc release here:
https://github.com/nextcloud/spreed/releases/tag/v10.0.0-rc.2

**Comment by Valdnet** [comment]
@nickvergessen Same thing with Talk 10 RC2:
![obraz](https://user-images.githubusercontent.com/47037905/94304310-a8ffa380-ff6f-11ea-806d-9d60ea9d1aa3.png)

**Comment by nickvergessen** [comment]
I still can not reproduce this neither does it make any sense to me.
Version7000Date20190724121136  also uses that table and adds two columns and as posted in https://github.com/nextcloud/spreed/issues/4230#issuecomment-698923579 that migration is done before Version8000Date20200331144101 in your stacktrace of https://github.com/nextcloud/spreed/issues/4230#issuecomment-698901042 🤷‍♂️

**Comment by Valdnet** [comment]
@nickvergessen Thanks for the help.
On a clean NC20 RC2 installed correctly. Apparently something is wrong with the old instance.
I think the Issue can be closed.
