### ISSUE TITLE
[10.0.0 RC2] Automatic refreshing of user status icon

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#4240]
## Steps to reproduce
1. Select a conversation with the user.
2. Change your status to a different one.
3. Change of status by another user.

### Expected behaviour
Automatic refreshing of the status icon of conversation users.

### Actual behaviour
User status icon not changing in conversation after user changed status.

![obraz](https://user-images.githubusercontent.com/47037905/94345317-541e6480-0025-11eb-987a-351611d881fe.png)

**Note:** The automatic refresh of the status icon does not work for all conversation users.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
10.0.0 RC2

**Comment by nickvergessen** [comment]
Yeah this was foxed in the nextcloud/vue library already, but it was not released yet, so nothing we can do about it at the moment 🤷‍♂️

**Comment by PVince81** [comment]
there was a release of nextcloud/vue recently, at least on master.
not sure if the bit in question will get backported ?

**Comment by nickvergessen** [comment]
That's not related. It's only an issue with the hpb when the participant list is not reloaded all 30sec but only on change (of participants currently and not user status)

**Comment by nickvergessen** [comment]
Works nowadays
