### ISSUE TITLE
Focus message input field again after uploading a file

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4242]
## Steps to reproduce
1. Write in a conversation
2. Upload a file
3. Try writing more

### Expected behaviour
You can just continue writing.

### Actual behaviour
You need to manually click into the message input field again because the upload flow took the focus from the input field.

**Comment by PVince81** [comment]
same problem also when selecting an emoji

**Comment by PVince81** [comment]
one does not simply call ".focus()" on a content editable :-S

**Comment by PVince81** [comment]
right, I can call `advancedInput.focus()` but the cursor always appears at the beginning.

might need some extra magic to move it to the end

**Comment by PVince81** [comment]
draft PR here: https://github.com/nextcloud/spreed/pull/4266

**Comment by PVince81** [comment]
fixed in https://github.com/nextcloud/spreed/pull/4266
