### ISSUE TITLE
Add option to hide video thumbnails of users while someone shares the screen

### ISSUE THREAD

**Issue by croessner** [nextcloud/spreed#4245]
**Is your feature request related to a problem? Please describe.**
If you have several people in a video call and one shares the screen, there is no option to only have showing the shared screen. So the shared screen is very small. It would be nice, if you could hide the videos from other users while watching the shared screen. Like a dock that can be hidden.

**Describe the solution you'd like**
It would be nice to have a toggle that allows having the shared screen in "real" full screen and hiding all other elements.

**Describe alternatives you've considered**
I searched if there exists some hidden occ command for that or options for config.php, but had no luck. Customizing the talk "view" would be really nice :-)

**Additional context**
none

**Comment by kingfisher77** [comment]
That would be perfect for us either!

**Comment by nickvergessen** [comment]
I thought an issue for this would exist already for a long time. It's definetly on our todo list at least.

**Comment by PVince81** [comment]
maybe could be an additional option between "grid view", "speaker view" and maybe add "full speaker view" there ?

since this would add a third mode it might be a good idea to make it a dropdown

**Comment by nickvergessen** [comment]
No, there should just be a small arrow on top/over the video strip to allow folding it away.

**Comment by nickvergessen** [comment]
No, there should just be a small arrow on top/over the video strip to allow folding it away.

**Comment by PVince81** [comment]
Hiding the bottom bar also means hiding one own's avatar/video, so the microphone, camera and other options would become invisible.

In that case we could move them at the bottom-center of the full view in that mode.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4363

**Comment by PVince81** [comment]
I've raised https://github.com/nextcloud/spreed/issues/4441 for the next step: automatic collapse whenever a screen share starts

**Comment by majkinetor** [comment]
I am still having this.

Interesting, you can zoom OUT the page in browser to make shared screen bigger and avatars very small.

I am currently blocking this via uBlock Origin and rule

```
! 2021-02-23 https://cloud.nil.rs
cloud.nil.rs##.avatar-container
```

Microfon and stuff can still be accessed via other menus.
