### ISSUE TITLE
Guests over public link not loading

### ISSUE THREAD

**Issue by freakms** [nextcloud/spreed#4249]
Create a new conversation
copy link
open link on any browser  not logged in (maybe private session)

### Expected behaviour
Loading all Cam and Voices, stays in meeting

### Actual behaviour
Just loading the opponent talkers, no video or Screen sharing ist working. 

## Talk app

**Talk app version:** 9.0.4

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/ 10

**Browser name:** Edge Chromium / Internet Explorer

**Browser version:** 85 / 11

## Server configuration

**Operating system**: Linux 4.15.0 #1 SMP Tue Jun 9 12:58:54 MSK 2020 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.1.44

**PHP version:**
7.3.22
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud Version:** 19.0.3 - 19.0.3.1
**List of activated apps:**

<details>
```
  - accessibility: 1.5.0  - activity: 2.12.0  - announcementcenter: 3.8.1  - bruteforcesettings: 2.0.1  - calendar: 2.0.4  - cloud_federation_api: 1.2.0  - comments: 1.9.0  - contacts: 3.3.0  - contactsinteraction: 1.0.0  - dav: 1.15.0  - deck: 1.0.5  - documentserver_community: 0.1.7  - event_update_notification: 1.0.2  - federatedfilesharing: 1.9.0  - federation: 1.9.0  - files: 1.14.0  - files_mindmap: 0.0.22  - files_pdfviewer: 1.8.0  - files_rightclick: 0.16.0  - files_sharing: 1.11.0  - files_trashbin: 1.9.0  - files_versions: 1.12.0  - files_videoplayer: 1.8.0  - firstrunwizard: 2.8.0  - forms: 2.0.4  - groupfolders: 7.0.0  - guests: 1.5.0  - issuetemplate: 0.7.0  - logreader: 2.4.0  - lookup_server_connector: 1.7.0  - mail: 1.4.1  - nextcloud_announcements: 1.8.0  - notes: 3.6.4  - notifications: 2.7.0  - oauth2: 1.7.0  - occweb: 0.0.7  - password_policy: 1.9.1  - photos: 1.1.0  - polls: 1.4.3  - privacy: 1.3.0  - provisioning_api: 1.9.0  - recommendations: 0.7.0  - registration: 0.5.0  - serverinfo: 1.9.0  - settings: 1.1.0  - sharebymail: 1.9.0  - spreed: 9.0.4  - support: 1.2.1  - survey_client: 1.7.0  - systemtags: 1.9.0  - tasks: 0.13.3  - text: 3.0.1  - theming: 1.10.0  - twofactor_backupcodes: 1.8.0  - updatenotification: 1.9.0  - viewer: 1.3.0  - workflowengine: 2.1.0
</details>

**Comment by nickvergessen** [comment]
You can not access the camera/microphone twice on the same device. That is a technical limitation for WebRTC usages depending on the browser and nothing we can change.

**Comment by freakms** [comment]
> You can not access the camera/microphone twice on the same device. That is a technical limitation for WebRTC usages depending on the browser and nothing we can change.

the error also appears, when using another device or another computer on another private lan. So it's not the case, that you can't use the camera or audio twice, it's just loading when public users connect. It doesn't matter from which device or browser.
