### ISSUE TITLE
Talk cannot open PDF documents from the chat

### ISSUE THREAD

**Issue by MaxGitHubAccount** [nextcloud/spreed#4255]
## Steps to reproduce
1. Go to Talk
2. Open a chat
3. click the brace
4. open a pdf document from files or from pc
5. try to open it from talk

### Expected behaviour
The pdf viewer opens with the pdf

### Actual behaviour
OnlyOffice opens and shows the error message
"Die Verbindung ist unterbrochen. Man kann das Dokument anschauen. Es ist aber momentan nicht möglich das Dokument herunterzuladen oder auszudrucken bis die Verbindung wiederhergestellt ist."

This only happens for pdf documents. Only Office is NOT the standard tool to open pdf in the nextcloud (actually it's turned off in the options). For office documents the only office opens the file without problem. I assume that Talk should not hand this over to the plugin.

When opening the pdf from the files however the pdf opens as it should with no error

## Talk app

**Talk app version:**
 9.0.4

**Custom Signaling server configured:**
no

**Custom TURN server configured:** 
no
**Custom STUN server configured:** 
no

## Browser

**Operating system:** 
Windows

**Browser name:**
Firefox

**Browser version:** 
81.0 64 bit

### Browser log

The request has been canceled 
Object { message: undefined }
MessagesList.vue:467
Current participant found CallButton.vue:101
Joined signaling.js:192:10
Current participant found CallButton.vue:101
Opening viewer for file  /Talk/***REMOVED SENSITIVE VALUE***.pdf Viewer.vue:223
Fetching additional files... Viewer.vue:250
A files list have been provided. No folder content will be fetched. Viewer.vue:346
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:61:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:61:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:61:15
Notifications permissions denied App.vue:296
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
Current participant found CallButton.vue:101
session heartbeat polling started session-heartbeat.js:97:9
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:61:15
oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20 globals.js:61:15
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified 4
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing index.html:273
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. index.html
GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 60ms]

GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 118ms]

GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 97ms]

GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 120ms]

GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 147ms]

The resource from “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
index.html
Loading failed for the <script> with source “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined”. index.html:1:1
GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 74ms]

The resource from “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
index.html
Loading failed for the <script> with source “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined”. index.html:1:1
The resource from “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
4 index.html
Loading failed for the <script> with source “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined”. 4 index.html:1:1
GEThttps://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined
[HTTP/1.1 404 Not Found 63ms]

The resource from “https://***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
index.html
Loading failed for the <script> with source “https://-***REMOVED SENSITIVE VALUE***/apps/documentserver_community/3rdparty/onlyoffice/documentserver/web-apps/apps/documenteditor/main/undefined”. index.html:1:1
oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20
``

## Server configuration

**Operating system**:  Debian Buster Linux 4.19.0-9-amd64 x86_64

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.19

**Nextcloud Version:** 19.0.3

**List of activated apps:**

t
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - documentserver_community: 0.1.7
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.0.0
  - password_policy: 1.9.1
  - passwords: 2020.9.0
  - photos: 1.1.0
  - polls: 1.4.3
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - riotchat: 0.6.11
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable"
    }
}

### Server log (data/nextcloud.log)

Error | documentserver_community | OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined rawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"                                                                                ^ namespace error : Namespace prefix wp14 on pctWidth is not defined ain"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="margin"><wp14:pctWidth                                                                                ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined 4:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"                                                                                ^ namespace error : Namespace prefix wp14 on pctHeight is not defined 14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="margin"><wp14:pctHeight                                                                                ^ |  
-- | -- | -- | --

Edit: Corrected the nextcloud server settings from the correct nextcloud.

**Comment by SystemKeeper** [comment]
Have a look at #3900. This can be solved by upgrading OnlyOffice (I'm using a OnlyOffice docker installation instead of the provided DocumentServer in the NC AppStore).

Guess there're two ways to fix this:
- Wait for an updated OnlyOffice packages (see https://github.com/nextcloud/documentserver_community) 
- Wait for NC 20 where files_pdfviewer (https://github.com/nextcloud/files_pdfviewer) is integrated into viewer, which _should_ solve this problem (not sure if OO or pdfviewer will take precedence in viewing pdf files).

Also related (at least for me) is the following: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/372

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by MaxGitHubAccount** [comment]
Thank you very much for the quick reply - sorry for not finding the related task before. Made the mistake only looking for **open** pdf issues.

**Comment by SystemKeeper** [comment]
@MaxGitHubAccount Works great here with NC20 and pdfviewer instead of OO.
