### ISSUE TITLE
Unmute doesn't work

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/spreed#4276]
## Steps to reproduce
1. Make video connection (Firefox -> Android app)
2. Mute microphone icon in main view (Firefox)
3. Try to unmute. Doesn't work -> BUG

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
9.0.4

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 81 (Ubuntu version)

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** SQLite

**PHP version:** 	7.4.3

**Nextcloud Version:** 19.0.3

**Comment by nickvergessen** [comment]
Most likely SQLite is the problem here. It's just not suitable for calls.

also please press F12 in your browser and check the console and the network tab for errors that are related.

**Comment by pawlosck** [comment]
Could you tell me, what I should search for? I can't see any errors or I don't know what message is error.

PS. The icon should be changed, because this icon is not used to mute microphone, only to mute speaker. Two the same icons (microphone icons) for two different actions is not normal.

**Comment by pawlosck** [comment]
Why issue was closed?

**Comment by nickvergessen** [comment]
Does it still happen for you in 9.0.6?

Also as said before you might just be out of luck with SQLite. It does not scale good enough for all the connections that are necessary to do a chat+video call.

**Comment by pawlosck** [comment]
Yes, problem still exists.
version 9.0.6? I am using 10.0.3. Problem is connected with web version of talk.
Why database can be responsible for this bug? Database is just storage, not part of code.
Problem is during one to one connection.

**Comment by nickvergessen** [comment]
It works quite fine here with Firefox 83 (current) and Nextcloud 20.0.2 and Talk 10.0.3
I do it on a daily basis. Did you have the chance to try it with another browser or something?
Maybe a browser addon is breaking something for you?

**Comment by pawlosck** [comment]
I tried to run Firefox (Ubuntu) in safe mode and Chromium (Ubuntu) and the same result.
I updated Nextcloud to 20.0.2.

Did you checked it under Windows or Linux?

**Comment by nickvergessen** [comment]
I'm using Ubuntu 20.10 and 20.04

Can you provide a link to a public conversation on your instance?

**Comment by pawlosck** [comment]
Yes, I can. Do you want to talk real time?

**Comment by nickvergessen** [comment]
not necessary, you can send a link to `<my github name>@nextcloud.com`

**Comment by pawlosck** [comment]
Did you see my e-mail? Any progress?

**Comment by nickvergessen** [comment]
Yeah, thanks. it works fine here: 
![Peek 2020-12-10 21-54](https://user-images.githubusercontent.com/213943/101828857-655e1400-3b32-11eb-827d-3f16512fb6d9.gif)

So I would assume it's one of your browser addons/plugins or something blocking it.

**Comment by pawlosck** [comment]
Wrong icon
![obraz](https://user-images.githubusercontent.com/3769853/101830820-5d53a380-3b35-11eb-8938-46526e87b634.png)

**Comment by nickvergessen** [comment]
Well you can not unmute other users microphone to sneak up on them.
If a user is muted only they can unmute themselves.

**Comment by pawlosck** [comment]
So why I can set this icon as muted?

**Comment by nickvergessen** [comment]
So you know that they are muted

**Comment by pawlosck** [comment]
I don't understand it. If this icon show state of microphone (read only for me) other user, so I should not have option to mute this user.

If this icon add option to mute users - I mean, there are a lot of users and author of chat can mute all users except specific users, then I should have option to unmute it (as author of chat).

Do you know what I mean? This icon is not changed by owner of microphone, only by me.

**Comment by nickvergessen** [comment]
I know what you mean but this is not what we think it should do.
We allow moderators to mute people in case they create unwanted noice, static noice or have a lot of background noice which they don't know/hear themselves.

But allowing a moderator to later on unmute your microphone without your consent is a huge threat to the privacy of people.
The best we might do at a future point is "ask to unmute": #4566

**Comment by pawlosck** [comment]
Ok. Now it make sense, but I suggest to add any message ("only user can unmute" or similar), why I can't unmute, because currently it looks like bug.
