### ISSUE TITLE
Process for update to latest version in my NC instance

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/spreed#428]
Can u tell me how can update with latest commit in `/var/www/nextcloud/apps/spreed`

Stay alert

**Comment by nickvergessen** [comment]
You have to wait until we shipped a new released to the app store

**Comment by johnfelipe** [comment]
Then is not possible test candidate release?

2017-09-29 10:33 GMT-05:00 Joas Schilling <notifications@github.com>:

**Comment by nickvergessen** [comment]
Once we are closer to a release we might do a pre-release

**Comment by johnfelipe** [comment]
But anytime is with appstore, right?

2017-09-29 10:36 GMT-05:00 Joas Schilling <notifications@github.com>:

**Comment by nickvergessen** [comment]
yes

**Comment by johnfelipe** [comment]
Can you help me with this
https://github.com/strukturag/nextcloud-spreedme/issues/99, may be show me
right direction?

2017-09-29 10:38 GMT-05:00 Joas Schilling <notifications@github.com>:
