### ISSUE TITLE
Add generic Chromium support

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/spreed#4281]
**Is your feature request related to a problem? Please describe.**
Nextcloud Talk tells me that my browser is not supported, even that it of course, as it's Opera, based on Chromium and works nicely with all aspects of the app. Worse, the banner makes the generally wrong information true by hiding parts of the apps UI, making them unusable:

I think the blue hidden button at the top right there was to toggle the participants list, but I am unable to toggle it now 😢.

![image](https://user-images.githubusercontent.com/28480705/95022905-359a1800-067a-11eb-9ac5-72533dbf7d29.png)

**Describe the solution you'd like**
- Support all Chromium-based browsers in a generic way, which, aside of Opera, would include Vivaldi, Brave, Iron and some others that deserve more attention instead of feel like being forced to use one of the big four...
- Add a little `[x]` hide button to hide the notification, probably even remember that to not bother users again with it.

**Describe alternatives you've considered**
- If it's insisted to only support original Chrome and Chromium Edge as Chromium-based browsers and wanted to keep showing this to users on every access, at least let's make it a notification behind the bell instead of a banner that blocks parts of the UI, the banner does not make it's own message become true.

**Additional context**
Many thanks for the great conference and value speeches and presentations btw! I hope it's okay that parts of the conversation is included in the screen above, right after Julius Härtl finished great demonstrations of Nextcloud Flow and Dashboard widget development 👏.

**Comment by nickvergessen** [comment]
Opera is not supported by the webrtc lib. The hidden button is the call button. But you should be able to close the error popover there should be an X in the right end. 🤔

**Comment by MichaIng** [comment]
> But you should be able to close the error popover there should be an X in the right end. 🤔

Interesting, the close button is there, but the icon is missing, it still works when I click on the empty area at the right side. Checked on my own server and see that it is looking at the wrong location:
```
GET https://my.domain.org/js/close.svg?ba1f38e8d96ebd8b9b9561c893e2c86a 404 (Not Found)
```
- Actually my Nextcloud is located in `nextcloud/` sub dir. I think I remember seeing this behaviour somewhere else already 🤔.

On NC conference Talk I cannot see that error but a bunch of others. I left the conversation to clean things up and here is what is left:
<details>
<summary>Browser console log</summary>

```
sentry.js?v=a05d0f88-1:16 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
(anonymous) @ sentry.js?v=a05d0f88-1:16
handlers @ Viewer.vue:214
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
r @ sentry.js?v=a05d0f88-1:16
sentry.js?v=a05d0f88-1:16 The following mime is already registered text/csv {__ob__: De}
(anonymous) @ sentry.js?v=a05d0f88-1:16
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
r @ sentry.js?v=a05d0f88-1:16
sentry.js?v=a05d0f88-1:16 The following mime is already registered image/svg+xml {__ob__: De}
(anonymous) @ sentry.js?v=a05d0f88-1:16
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
r @ sentry.js?v=a05d0f88-1:16
sentry.js?v=a05d0f88-1:16 The following mime is already registered text/plain {__ob__: De}component: (...)group: (...)id: (...)mimes: (...)__ob__: De {value: {…}, dep: le, vmCount: 0}get component: ƒ ()set component: ƒ (t)get group: ƒ ()set group: ƒ (t)get id: ƒ ()set id: ƒ (t)get mimes: ƒ ()set mimes: ƒ (t)__proto__: Object
(anonymous) @ sentry.js?v=a05d0f88-1:16
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
r @ sentry.js?v=a05d0f88-1:16
sentry.js?v=a05d0f88-1:16 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
(anonymous) @ sentry.js?v=a05d0f88-1:16
handlers @ Viewer.vue:214
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ main.js:26
r @ sentry.js?v=a05d0f88-1:16
sentry.js?v=a05d0f88-1:16 The following mime is already registered application/pdf {__ob__: De}component: (...)id: (...)mimes: (...)__ob__: De {value: {…}, dep: le, vmCount: 0}get component: ƒ ()set component: ƒ (t)get id: ƒ ()set id: ƒ (t)get mimes: ƒ ()set mimes: ƒ (t)__proto__: Object
(anonymous) @ sentry.js?v=a05d0f88-1:16
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ main.js:26
r @ sentry.js?v=a05d0f88-1:16
```
</details>

> Opera is not supported by the webrtc lib.

Hmm, then this should be reported to the WebRTC lib, since it fully supports WebRTC like any other Chromium-based browser I know. I use Nextcloud Talk, not often but regularly, now I wonder how I found the call button then 😄, maybe UI changed a bid with v10, and in my instance I still can click the button via small part showing above the banner.

**Comment by nickvergessen** [comment]
#4287 brings back the `X` to close the error.

Reopening for future "support more chrome based browsers"

**Comment by MichaIng** [comment]
Many thanks for the quick solution. If browser support is a matter of an external library, give me a hint/link and I can do a start and open an issue there.

Hmm:
- https://github.com/nextcloud/spreed/blob/master/package.json#L57
- https://github.com/HenrikJoreteg/webrtcsupport It is not this archived long time not updated project? I see a bunch of [forks](https://github.com/HenrikJoreteg/webrtcsupport/network) which in cases add additional browser support, like: https://github.com/skysbird/webrtcsupport/commit/120dbb1095c69a3ff2832024dc30a8ab3ac48dc4, but no idea how composer resolves that, respectively which repository it is using 😄.

**Comment by nickvergessen** [comment]
It's more about https://github.com/webrtcHacks/adapter

**Comment by MichaIng** [comment]
The browser detection of both modules looks quite similar: https://github.com/webrtcHacks/adapter/blob/master/src/js/utils.js#L163-L192

Opera is listed in the webkit prefix block, but Chromium is not based on webkit for a loong time. That issues is somehow related: https://github.com/webrtcHacks/adapter/issues/764

Looks like a generic Blink browser engine detection is missing and not all Chromium-based browsers still support those webkit prefixed variables (anymore).

**Comment by nickvergessen** [comment]
Opera is now supported as the lib mentions it explicitly

**Comment by MichaIng** [comment]
Just tested and verified with NC21 RC1 and related alpha Talk version, not showing the warning now 👍.

**Comment by fippo** [comment]
> The browser detection of both modules looks quite similar

That is not a coincidence ;-)
In general I would recommend getting rid of webrtcsupport, see https://github.com/simplewebrtc/SimpleWebRTC/pull/559/files for some of the mechanics.

> Opera is listed in the webkit prefix block, but Chromium is not based on webkit for a loong time

Opera still supports webkitGetUserMedia. Should you encounter a chromium-based browser that doesn't please add a note to the adapter issue.
