### ISSUE TITLE
Starting gateway failed: Bridge nctalk.1 failed to join channel

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/spreed#4282]
Hello,

I would test the new Talk App. Create an Telegram Bot and copied the ID to the Bridge. I got this error at Matterbridge. 

```time="2020-10-04T19:55:48+02:00" level=fatal msg="Starting gateway failed: Bridge nctalk.1 failed to join channel: json: cannot unmarshal array into Go struct field RoomInfo.ocs.data.lastMessage of type ocs.TalkRoomMessageData" prefix=main```

I added the Bot ID and the ID from the Chat. But would not connect.

Ubuntu 20.04.1 lts
Php 7.4.3
Nextcloud 20.0.0
Mysql

**Comment by nickvergessen** [comment]
Did you use the talk_matterbridge app or configure matterbridge yourself?

**Comment by Happyfeet01** [comment]
Talk_matterbridge

**Comment by nickvergessen** [comment]
cc @gary-kim @eneiluj

**Comment by Happyfeet01** [comment]
The same message when I try to add discord

**Comment by eneiluj** [comment]
Maybe RoomInfo.ocs.data.lastMessage contains something that NCTalk Matterbridge backend is not expecting. Any clue @gary-kim?

@Happyfeet01 is the Talk room empty (no messages) when you enable the bridge?

**Comment by Happyfeet01** [comment]
@eneiluj yes is empty

**Comment by eneiluj** [comment]
Could you post messages in it and try to enable the bridge again?

**Comment by Happyfeet01** [comment]
New created ![Screenshot_20201005_130749_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/3295104/95072655-cff66c00-070b-11eb-80f5-4d0dc5621dbe.jpg)

` time="2020-10-05T13:06:40+02:00" level=info msg="Running version 1.18.3 8b26e42a" prefix=main
time="2020-10-05T13:06:40+02:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2020-10-05T13:06:40+02:00" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2020-10-05T13:06:40+02:00" level=info msg=Connecting prefix=telegram
time="2020-10-05T13:06:40+02:00" level=info msg="Connection succeeded" prefix=telegram
time="2020-10-05T13:06:40+02:00" level=info msg="telegram.0: joining  (ID: telegram.0)" prefix=telegram
time="2020-10-05T13:06:40+02:00" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2020-10-05T13:06:40+02:00" level=info msg=Connecting prefix=nctalk
time="2020-10-05T13:06:40+02:00" level=info msg=Connected prefix=nctalk
time="2020-10-05T13:06:40+02:00" level=info msg="nctalk.1: joining jcojm63y (ID: jcojm63ynctalk.1)" prefix=nctalk
time="2020-10-05T13:06:41+02:00" level=fatal msg="Starting gateway failed: Bridge nctalk.1 failed to join channel: json: cannot unmarshal array into Go struct field RoomInfo.ocs.data.lastMessage of type ocs.TalkRoomMessageData" prefix=main`

**Comment by eneiluj** [comment]
According to your screenshot you enabled the bridge before posting a message inside. Could you disable the bridge and reenable it so that there is an existing message when it tries connecting to Talk?

**Comment by Happyfeet01** [comment]
I tried it, but no luck

**Comment by eneiluj** [comment]
Then let's wait for @gary-kim 's expertise :smile:.

**Comment by gary-kim** [comment]
From the error message, it seems like the issue is that the rooms endpoint is expected to return a `lastMessage` response but is not doing so. That will need a fix upstream. Otherwise, it should work when restarted with at least one message sent already so I'm not sure why that's not working.

https://github.com/gary-kim/go-nc-talk/blob/af034cd7167c9af90c52ad3ff7081bd7b1fe21ac/user/user.go#L114

**Comment by Happyfeet01** [comment]
Okay I will start the Bridge again and join the Bot to existing chat with messages. And post the log entry again.

**Comment by gary-kim** [comment]
I'm trying to recreate this but I don't seem to be able to find a situation in which lastMessage is not set. Just creating a conversation is a message in and of itself.

Will still fix it but it is a bit confusing.

**Comment by nickvergessen** [comment]
Create a conversation and execute a command that is not visible to everyone.

**Comment by Happyfeet01** [comment]
@gary-kim I test it again yesterday. Now it works fine with telegram and Talk.
WhatsApp would be nice:)
