### ISSUE TITLE
matterbridge irc password is treaded as a channel password.

### ISSUE THREAD

**Issue by markuman** [nextcloud/spreed#4283]
https://github.com/nextcloud/spreed/blob/master/lib/MatterbridgeManager.php#L487

The description of the field said "Connection password".  
But that's a key value in the irc section: https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L21

But MatterbridgeManager saves the value as an option to the channel. ...like the channel is locked.

1. the current password description must be renamed to "Channel Password".
2. an addition optional password field must be added, when a password for the irc server itself is necessary.

**Comment by eneiluj** [comment]
@markuman Thanks for the feedback! Fix is coming with the PR.
