### ISSUE TITLE
Different favicon when a call is in progress to find the call tab easily

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4298]
**Is your feature request related to a problem? Please describe.**

1. Start a call/meeting
1. Like a good multitasker, open other browser tabs with different NC apps and also other ones with the Talk app to be able to chat with other people in other conversations while slightly bored in the current meeting :wink: 
1. Work/talk in the other NC tabs
1. Someone calls your name in the meeting, **quick**, find back the tab in which the call was happening to answer!

**Describe the solution you'd like**
To be able to quickly find back the browser tab where the call is happening, let's add the red camera icon on top of the Talk icon

**Describe alternatives you've considered**
Maybe also add something in the window title.

cc @jancborchardt

**Comment by nickvergessen** [comment]
I'm not sure, I think favicons are cached quite heavily especially on pinned tabs?

**Comment by PVince81** [comment]
as far as I understand, the target of favicon URLs are cached, but if we change the URL it will load the new one.
so in the end both the "in call" and "not in call" favicons would be cached but we can still switch between both.

will need some experimentation to confirm

**Comment by PVince81** [comment]
never mind, I just saw it working today: 
<img width="132" alt="image" src="https://user-images.githubusercontent.com/277525/95202321-752f4400-07e1-11eb-9a82-b55ca2a8063a.png">

it fades between the Talk icon and a red camera...

I didn't notice it before on my test instance

**Comment by jancborchardt** [comment]
Yeah, luckily browsers do this natively. :)
