### ISSUE TITLE
Ability to search for participants in a conversation

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4299]
**Is your feature request related to a problem? Please describe.**
Whenever there are lots of participants in a conversation (like the virtual conference room), I'd like to see if some friends also joined, what their status is and maybe ping them or start a private conversation.

**Describe the solution you'd like**
Reuse the search box that moderators can see in the participants list, but only allow searching (not adding) for non-moderators.

**Describe alternatives you've considered**
In theory someone could also use the "+" button to start a new conversation and search for the person there, but it won't tell whether the person is present in the current room.

**Additional context**

cc @jancborchardt

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4598

**Comment by danxuliu** [comment]
I agree that being able to search for participants when there are a lot of participants in a conversation is a must. However, when there are just a few participants now having a search box feels strange. Unfortunately I have no suggestion on how to improve it :-(

**Comment by PVince81** [comment]
we could hide it when there are less than X participants.

an even more dynamic way would be to detect if there's a scrollbar and if yes, enable the field. but enabling the field would also induce a scrollbar... so maybe not :sweat_smile:

**Comment by danxuliu** [comment]
> we could hide it when there are less than X participants.

I thought about that, but the problem is of course where to put the threshold ;-) Also there could be some "jumpiness" on public conversations when guests enter and leave.

> an even more dynamic way would be to detect if there's a scrollbar and if yes, enable the field. but enabling the field would also induce a scrollbar... so maybe not :sweat_smile:

Maybe an option would be to check the height of the participant list element (without the search field) instead of checking the tab itself.
