### ISSUE TITLE
"Copy link" at middle of screen isn't clickable/doesn't work

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/spreed#4311]
This has spanned multiple major versions of nextCloud now, so this is a longer standing bug. When I start a call, there's a blue button "Copy link" in the middle of the window. Clicking on it never copies the link, it does nothing. I have to go to the 3-dot menu to get the link copied.

I'm on NC20, but this has happened in NC18 and earlier versions. Latest version of Talk and previous versions too.

**Comment by BloodyIron** [comment]
Oooo I like the development! :D

**Comment by Chartman123** [comment]
I think this button is behind some other element as there is no explicit z-index... I tried adding z-index: 1 to the empty-call-view button style in the browser dev tools and then the link was clickable:

I think it should be added here: https://github.com/nextcloud/spreed/blob/825ffb624cc39f300e8ddf8f38a79742be8fb55c/src/components/CallView/shared/EmptyCallView.vue#L169

**Comment by nickvergessen** [comment]
@Chartman123 you want to fix this and send in a PR?

**Comment by Chartman123** [comment]
Yes, of course. Is adding z-index: 1 the correct way to do it?

**Comment by nickvergessen** [comment]
or you try to find out what is overlaying it and if that could be removed, reduced, etc.
But for now it sounds good enough

**Comment by BloodyIron** [comment]
Yay!
