### ISSUE TITLE
School communication - confirm messages

### ISSUE THREAD

**Issue by DarkknightAK** [nextcloud/spreed#4312]
Hi,

in our school, we use [schoolfox](https://web.schoolfox.com/) for communication with the teachers. It's a primary school (6 - 10 year). Schoolfox is kind of an digital class-register.

The following features were needed/used:
- The teacher communicate with the class (kind of e-mail)
- The Parents communicate with the teacher(s) and give feedback when the kids can leave the school
- Each message has to be confirmed from the addressee

I'm fine with schoolfox, but I think you can have a digital class-register also with Nextcloud talk together with Nextcloud Circles.

However what would be nice is to have an option to submit messages where the user(s) have to confirm that they get/reed/understood it. This could be also usefull in other areas outside of schools. For e-mail you can also define to get an confirm message for example.

**Comment by nickvergessen** [comment]
I guess this could be achieved via #1920

**Comment by DarkknightAK** [comment]
Thanks, yes that could work, but confirm message should be an very strict and clear message so the moderator should see how has confirm the message and how not.
