### ISSUE TITLE
Create conversation flow confusion

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4318]
## Steps to reproduce
1. Click the plus icon to create a conversation
2. Start typing participant name
3. Be confused that there are no results shown
4. Remember that this is the conversation name
5. Type in conversation name
6. Click next
7. Type participant names and pick a few

### Expected behaviour
The two views look too similar.
In some use cases I don't care about a room name, I just want to talk with people, so a room name could be auto-generated (if renamable later).

One idea would be to at least consolidate both views into one: first row "conversation name" and second row "participants", this way it's a bit clearer that they are separate and also that I'll have the option to pick participants. Otherwise the latter is hidden behind the "next" button.

### Actual behaviour
Once you start typing a name, the placeholder disappears so you don't know that this was the "conversation name field".

## Talk app

**Talk app version:** 10.0.0

@jancborchardt

**Comment by nickvergessen** [comment]
Maybe we need a label on the input than.

With more upcoming settings I don't think merging both pages is the best idea. And as soon as we add the upload option for the group icon the confusion should be gone anyway.

**Comment by ma12-co** [comment]
I also agree on that we shouldn't merge the 2 pages. For the rest, let's identify and separate the issues:

* The placeholder disappears so you don't know that this was the "conversation name field"
For this we could a label on top of both input fields as @nickvergessen suggests, but I'm not completely sure it's needed. If we find this necessary here, IMO should bring this to many other instances of text input with placeholder across Nextcloud. Not against it but we have to make a strong case on why this is necessary.

* There is no way of skipping the participant selection step after checking the "allow guests to join via link" option, brought up by @simonspa in the talk channel
To solve this I propose that  we add a second button that becomes enabled when the checkbox is checked and reads something like "Create public conversation". On click this  button would directly show the  final page with the copy link button; 

* There is no jitsi-like, quick way to open a new group conversation with an automatically generated name
Do we want this? If so, we could make both the above mentioned button and the add participants button always enabled, and generate a  name when none is provided by the user.

**Comment by PVince81** [comment]
Additionally, I always find myself typing a new conversation name into the search field at the top, intuitively believing that the plus button will already create a conversation. Maybe we should copy whatever was input in that field into the "create conversation" dialog ?

**Comment by ma12-co** [comment]
> button will already create a conversation. Maybe we should copy whatever was input in that field into the "create conversation" dialog ?

Hmm I see the issue but I think that the solution is not explicit enough. Instead I would bring back the old way of quickly creating a group conversation by providing a navigation entry that literally says something like "Create new conversation named xyz". What do you think?

**Comment by nickvergessen** [comment]
I'm closing this now. From my POV the two screens are different enough nowadays and there is also more difference coming up with conversation icon/avatar/image thingy.

**Comment by jancborchardt** [comment]
Agree that the issue can be closed. However what @PVince81 brought up above is a nice helpful shortcut, a simple quality-of-life enhancement. :)

> Additionally, I always find myself typing a new conversation name into the search field at the top, intuitively believing that the plus button will already create a conversation. Maybe we should copy whatever was input in that field into the "create conversation" dialog ?

**Comment by nickvergessen** [comment]
Oh,  I thought I added this quite some time ago, but seems it only works for groups
