### ISSUE TITLE
Automatic reply/Out of office bot

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#4319]
Just something that crossed my mind ;-)

With Talk 10 the new user status is shown in the candidate mentions pop up, which should make people aware if someone is not available and thus prevent mentioning that person.

However, in some environments (honestly not something that I would use myself :-P ) it could be interesting to also have a bot that posts a message when someone is mentioned when not available, for example, when on vacation.

And maybe it could be possible to integrate it with the calendar so the bot can automatically say something like "I'll be back on DD/MM" (of course it would be easier if that is simply written by the user when she enables the bot, like `/outofoffice message I'll be back on DD/MM`, but if the bot can do it automatically is fancier :-P ).

There is still the annoyance of the bot posting even if someone is knowingly mentioned when not available so that person can read the mention when she is back :shrug: But is the same with automatic reply e-mails I guess.

**Comment by nickvergessen** [comment]
Hmm I think the userbubble should take care of that, not an extra message being posted.

I could see it being useful however in 1-to-1 chats.

**Comment by nickvergessen** [comment]
cc @nextcloud/designers 
Looking at https://github.com/nextcloud/spreed/issues/6293 should we show a hint about away/DND above the chat input when going to a one-to-one with a user?

**Comment by nickvergessen** [comment]
I consider this solved with https://github.com/nextcloud/spreed/issues/10599
