### ISSUE TITLE
Plus icon in 'new conversation' button not centered vertically

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#4320]
...
![Screenshot_20201007_144816](https://user-images.githubusercontent.com/551757/95333246-d07a3880-08ac-11eb-9fd2-468ce6ecfdde.png)

![Screenshot_20201007_145102](https://user-images.githubusercontent.com/551757/95333436-1505d400-08ad-11eb-8939-d8c470ffd03c.png)

On cloud.nextcloud.com - latest Nextcloud and all that. Firefox browser.

I blame Jan for helping make Nextcloud so well designed that even a total 🤖 like me occasionally notes and gets irked by something like this ;-)

**Comment by jancborchardt** [comment]
Love the giant ruler :D 

→ @ma12-co one for you

**Comment by ma12-co** [comment]
I'm almost certain this comes from server's css. Should we leave it as a good first issue for a while?

**Comment by nickvergessen** [comment]
Because of the font size ?

**Comment by nickvergessen** [comment]
Seems to be fixed, for me it's now 14px on top and bottom
