### ISSUE TITLE
[Edge] Emoiji button triggers settings panel / left panel issues

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4326]
## Steps to reproduce
1. Open MS Edge / Win 10 (from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
1. Open a conversation
2. Collapse the left panel
3. Click on the emoji icon
4. Try reopening the left panel

### Expected behaviour
Emoji panel appears.
Reopening left panel works.

### Actual behaviour
Settings page appears.
Trying to reopen the left side panel doesn't work with the hamburger icon. Instead, the hidden search field gets focussed as I can see the cursor blinking there.

It seems that something isn't right with visibility or the layers of the left side panel.

## Talk app

**Talk app version:** 11 (master a4e9ad4e5c9d76dbe9e757cd09fec51c5e03aeb8)

## Browser

MS Edge with Win 10 from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by PVince81** [comment]
I tested with the wrong Edge version backend then (non-chrome), closing

**Comment by maradiIremadze** [comment]
helov
