### ISSUE TITLE
Mixed font sizes in the conversation menu

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4330]
I've also observed a mix of font sizes in the conversation menu:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/277525/95463924-a773a980-0979-11eb-8dc2-672bab62a6a6.png">

The action buttons with checkboxes have a font-size of 15px but the other action buttons only have font-size 13px.

_Originally posted by @PVince81 in https://github.com/nextcloud/spreed/issue_comments/705563029_

**Comment by nickvergessen** [comment]
Should go into the vue lib?

**Comment by PVince81** [comment]
fixed through https://github.com/nextcloud/nextcloud-vue/pull/1543

needs update of nextcloud-vue lib now

**Comment by PVince81** [comment]
assigning self to release and update vue, but waiting for a few more PRs :-)

**Comment by PVince81** [comment]
PR for the vue bump https://github.com/nextcloud/spreed/pull/4567
