### ISSUE TITLE
Push to talk and push to mute user instruction

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4335]
> Please document? Keyboard shortcuts in settings and maybe even the tooltip of the audio button?

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/pull/4328#issuecomment-706027611_

**Comment by BloodyIron** [comment]
Yeah really need the ability to change the shortcut for this.

**Comment by ma12-co** [comment]
@BloodyIron why would you need to change the shortcut? @nickvergessen is referring to the fact that the shorctut needs to be added to the settings' shortcut usage documentation

**Comment by BloodyIron** [comment]
Change it so spacebar doesn't mute/unmute? Oh I dunno.. .maybe because a single shortcut that you can't change won't work for most people? Or perhaps you're misunderstanding what I'm getting at?

The button you press to mute/push to talk, should be changeable.

**Comment by nickvergessen** [comment]
We have single shortcuts for every other thing as well. Don't think we will add an option to change them

**Comment by BloodyIron** [comment]
What exactly is wrong with adding one of the most used settings for push to talk? Every single other application that has push to talk lets you change the shortcut, and I guarantee you that once you add it, the first thing people will talk about is how you can't change the shortcut. Don't try to force such an asinine decision on people, whether they want to use an obscure shortcut not of their choice for push to talk, or just not use it at all.

**Comment by nickvergessen** [comment]
Well if ee add a setting for every shortcut it just bloats the complexity.
No problem if people report the need for changing it, but since we have a shortcut for mute/unmute and the others we got no request in 2 years to change them.

**Comment by BloodyIron** [comment]
I never called you a name, nor did I insult you, I called the decision asinine. You're reading words that aren't there.

Don't say I didn't warn you. I appreciate push to talk being added, but I'm trying to help bring to attention that not adding the ability to change the shortcut will cut the adoption of the feature at the knees.

**Comment by ma12-co** [comment]
done here #4532

**Comment by ma12-co** [comment]
done here #4532
