### ISSUE TITLE
Main-speaker-window shows speaker and switches between different width sizes in firerfox

### ISSUE THREAD

**Issue by isas-institute** [nextcloud/spreed#4339]
## Steps to reproduce
1. Create a video-conference
2. Create a room with more than four participants
3. All participants use firefox 78.3.0 ESR or latest

### Expected behaviour
Main-Speaker-Window appears and has fixed size 

### Actual behaviour
Main speaker and other speaker are changing window size 

## Talk app
9.x and 10.0.0

**Custom Signaling server configured:
yes´and version v0.1.0

**Custom TURN server configured:** yes --> coturn

**Custom STUN server configured:** yes --> coturn

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** 4 x Windows 10 and 1x Debian 10

**Browser name:** Firefox

**Browser version:** all 78.3.0 ESR or latest

**Comment by nickvergessen** [comment]
Sorry I don't understand the issue really.
Can you add some screenshots to help us understand what this is about?
