### ISSUE TITLE
Howto set fixed video-width for main speaker window?

### ISSUE THREAD

**Issue by isas-institute** [nextcloud/spreed#4341]
Hi, we are testing nextcloud-talk in our institute. 

While testing our installation, we run with firefox into the problem, that at that point, when the video of the main participant was shown, it changed every time its size after a short time, which made people nervous because of the flickering. This behaviour doesn't appear on microsofts edge-browser but we are using firefox here and cant switch browsers. If we wont get it fixed, nextcloud talk is no option. 

We found out, that there are different resolutions and window-sizes depending on the amount of participants 💯 
https://nextcloud-talk.readthedocs.io/en/latest/call-experience/

So we would like to set fixed video quality as workaround. Is there a way to set it? The number of video streams will be around 40. 

We changed the firefox-version from 78.3.0  ESR to latest , disabled all plugins, enabled h.264 plugin for better webrtc-support, read firefox-logs, checked options in the nextcloud-admin-panel, compiled and tested spreed 10.0.0 and searched the web for a solution. 

Greetings

**Comment by nickvergessen** [comment]
Do you have a recording of the flickering? It works quite good here on Firefox.

**Comment by isas-institute** [comment]
Will try to send a recording, next week.

**Comment by isas-institute** [comment]
Hey nickvergessen, where can i send the video? It's 5 MB and shouldn't be on public space.

**Comment by nickvergessen** [comment]
Send an email to `<my github name>@nextcloud.com` with a share link
