### ISSUE TITLE
Can't set a starttime on a new group chat with lobby

### ISSUE THREAD

**Issue by leuedaniel** [nextcloud/spreed#4364]
## Steps to reproduce
1. Create new group chat
2. Invite some people
3. Activate the lobby feature
4. Set a starttime on another day

### Expected behaviour
I can set the starttime

### Actual behaviour
I can mark a day, an hour and the minute and can click on ok but notthing happens

## Talk app

**Talk app version:**
9.0.4

**Custom Signaling server configured:** 
no

**Custom TURN server configured:** 
yes

**Custom STUN server configured:**
yes

## Browser

**Operating system:** 
Win10
**Browser name:**
Chrome
**Browser version:** 50.1/55/...
Version 86.0.4240.75
### Browser log
They say nothing

## Server configuration

**Operating system**: 
Ubuntu 20.04
**Web server:** 
Nginx
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud Version:**
19.0.4
**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - announcementcenter: 3.8.1
  - cloud_federation_api: 1.2.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - groupfolders: 7.1.0
  - guests: 1.6.0
  - login_notes: 0.3.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - spreed: 9.0.4
  - suspicious_login: 3.2.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_sql: 4.5.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - calendar
  - comments
  - encryption
  - federation
  - files_pdfviewer
  - firstrunwizard
  - photos
  - recommendations
  - sharebymail
  - support
  - survey_client
  - systemtags
  - text
  - user_ldap
</details>
**Nextcloud configuration:**
<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ehv.ch",
            "cloud.ehv.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "https:\/\/cloud.ehv.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "force_language": "de",
        "default_locale": "de-ch",
        "force_locale": "de-ch",
        "knowledgebaseenabled": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "filesystem_check_changes": 1,
        "skeletondirectory": "",
        "ldapUserCleanupInterval": 51,
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

### Server log (data/nextcloud.log)
No entry in log at the time where it happens

![2020-10-14 09_28_07-Besprechung Prozesse Stammdaten - Talk - EHV Cloud](https://user-images.githubusercontent.com/44936305/95957180-a6ba9780-0dff-11eb-9cd4-9e5007b4e85b.png)

**Comment by nickvergessen** [comment]
Fixed already with #4321 

The value is set, just displaying it fails.
