### ISSUE TITLE
Dashboard: Show favourite rooms at the top

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#4376]
Sort it like in the talk room overview: first the favourites then the other rooms

**Comment by nickvergessen** [comment]
Should only happen on the "No mentions" half-empty content view I guess?

cc @nextcloud/designers-talk

**Comment by jakobroehrl** [comment]
> Should only happen on the "No mentions" half-empty content view I guess?

Exactly

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/557de2c1842262fc40c5698fdcbc5c40c9cf0e47/src/views/Dashboard.vue#L166 needs to be extended to also check for the favorite status.
