### ISSUE TITLE
Messagelist doesn't scroll properly

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4378]
## Steps to reproduce
1. Be in conversation 1
2. Hit refresh
3. Click on a conv with no new messages

### Expected behavior
The chat should scroll to the bottom 

### Actual behaviour
The scroller scrolls to 50% height

**Comment by nickvergessen** [comment]
> So, when the bug happens, I have 2 requests for the history taking place
> 
> got it locally now :)
>
> okay, so basically when you enter the conversation, the view is empty, and then when the items are added, you are for a quick moment at the top of the list, so another history grab is called
>
> so yeah, thats it
> 
> it then triggers https://github.com/nextcloud/spreed/blob/515cfe8c8fbb68e711f002cf487501861775b95a/src/components/MessagesList/MessagesList.vue#L544-L550
> 
> so basically it would be enough to hardcode https://github.com/nextcloud/spreed/blob/515cfe8c8fbb68e711f002cf487501861775b95a/src/components/MessagesList/MessagesList.vue#L378 to only scroll down, no matter what
