### ISSUE TITLE
Talk for Windows & MacOS Client

### ISSUE THREAD

**Issue by axheli** [nextcloud/spreed#4381]
Hi Everyone, I wanted to bring up a idea and see what everyone things. I think it would be an amazing if there was an windows and MacOS app for the talk just like we have for the sync client.  The web based is very nice but i has some users in my organization ask me why dont we have a client install on the computer it would be so much nicer and easier. So then i thought about Microsoft Teams and they have a web based version and a client install. Would this be possible i think we would have a lot of people that would use this.

**Comment by axheli** [comment]
@Ivansss what do you think about this?

**Comment by axheli** [comment]
@nickvergessen whys this closed ?

**Comment by nickvergessen** [comment]
Because it's a duplicate of #1100 ?
