### ISSUE TITLE
Add pre-configured bridge accounts

### ISSUE THREAD

**Issue by plinss** [nextcloud/spreed#4385]
**Is your feature request related to a problem? Please describe.**

Having to enter URL/username/password each time when bridging a conversation is painful, and requires distributing credentials for bot users to anyone allowed to create bridges.

An improvement would be to allow the administrator to configure a set of known bridge accounts. This would allow anyone creating a room to add a bridge without knowing (or even having access to) the account specifics.

**Describe the solution you'd like**
Admin settings to specify a set of bridge accounts. 

Chose a service, and specify the service URL, username, password and/or API key as needed. Setting a custom name for the bridge would also probably be useful.

In the Talk "Add a bridged chanel" UI, allow selecting a pre-defined bridge and then prompt only for the remaining information, e.g. remote channel or room.
Ideally the pre-configured bridges would be listed first, and possibly differentiated from bridges that need to be fully configured.

A bonus feature would be restricting the use of these bridge accounts to specific users or groups.
An additional useful feature may be restricting users/groups to only use pre-configured bridges accounts. For example, regular users may select a pre-configured Matrix bridge, but not create other bridges.

Furthermore, it would be nice to be able to set pre-defined bridges to auto-join new conversations. e.g. I create a conversation named "Meeting" and the Matrix bridge is automatically added bridging to a Matrix room with the same name.

**Comment by nickvergessen** [comment]
With Nextcloud Talk 10, this is done automatically when you configure the bridge via Nextcloud Talk.
That is the recommended and supported way to do this.

**Comment by plinss** [comment]
I'm using Talk 10, and unless I'm missing something, no, this is not done automatically. The only configuration option in the admin settings is to turn bridging on and off.

I think you may be missing the point of what I'm asking for.

As a user, every time I create a new conversation I have to enter the URL, username, and password (or api key) for the bridge user on each bridged service. I'm asking for the ability to create a set of pre-configured bridge users and simply select from them, entering only the name of the room on the bridged service where necessary.

Please re-open this.

**Comment by nickvergessen** [comment]
So here you would want to offer random users from your Nextcloud to be able to select your own account of a 3rd party service?
![2020-10-20 18_16_57-Matterbridge](https://user-images.githubusercontent.com/213943/96627780-a47d9f00-1311-11eb-9da3-4cbf8dd1ddcd.png)

Really not going to happen. Also I would really recommend to use a custom API key per bridge, in case details are leaked somehow that not all your communication is leaked at once, but only one.

**Comment by plinss** [comment]
No, I want to offer random users of my Nextcloud to be able to access *specific* bridge accounts to other servers that *I* control.

e.g. my organization has its own Matrix server. All of our users have accounts on it and that's where most conversations happen. When someone creates a new Talk conversation I want them to be able to bridge that conversation to the organization's Matrix server.

So I have a single 'bridge-bot' user that has access to the Matrix server, and I DO NOT want to have to give that user's account credentials to *every* user of my Nextcloud instance, but I want every Nextcloud user to be able to add that bridge 
to a Talk conversation.

(I really want that to happen automatically, see "it would be nice to be able to set pre-defined bridges to auto-join new conversations" above, but will be happy with this as a first step).

I want the Nextcloud admin to be able to specify the 'bridge-bot' user's account credentials *once*, and regular users to not have access to those, but still be able to use the bridge account with new conversations that they may create. The only thing a regular user would be able to specify would be the bridged room name.

I'd also like the admin to be able to restrict regular users from creating non-predefined bridges, so that internal conversations can't be leaked to random 3rd party services, but that's another issue.

**Comment by nickvergessen** [comment]
> So I have a single 'bridge-bot' user that has access to the Matrix server, and I DO NOT want to have to give that user's account credentials to every user of my Nextcloud instance, but I want every Nextcloud user to be able to add that bridge
to a Talk conversation.

Ah, well the problem with that is that it basically still means they could "birdge" any of the conversations from matterbridge to their talk conversations, even if they are not a member of that conversation on the matterbridge.
Since this can cause unintended leaking of information it's mostlikely not going to happen (at least for now).


> I'd also like the admin to be able to restrict regular users from creating non-predefined bridges, so that internal conversations can't be leaked to random 3rd party services, but that's another issue.

While I understand the idea, they can always do this anyway. They just set up the matterbridge somewhere else and specify their account with an app token from the personal settings on it. 🤷

**Comment by plinss** [comment]
> Ah, well the problem with that is that it basically still means they could "birdge" any of the conversations from matterbridge to their talk conversations, even if they are not a member of that conversation on the matterbridge.
Since this can cause unintended leaking of information it's mostlikely not going to happen (at least for now).

That's a legit concern, but the solution (given the current state of matterbridge) is adding multiple pre-defined bridge users and being able to restrict their usage to given users or groups on the Talk side. e.g. a 'general' user, a 'management' user, team-specific users, etc. The users on the other service will see the bridge users join the rooms and will be able to tell what class of users might be on the other end of that bridge and can restrict accordingly on that side.

Furthermore, anyone with access to a bridge user's credentials can still do this. The matterbridge recommendation is to NOT use actual user accounts to to bridging, so there's still a problem of distributing bridge user credentials.

Ideally, matterbridge adds support for double-puppeting (or Talk supports a better bridging solution that does) so the users on the other side of the bridge know exactly who is in the room, rather than only seeing a bot.

I accept this may not be something that going to happen "now", and may need additional features to be fully useful and secure, but this is important functionality to make bridging something that regular people can actually use on a daily basis and not just a "marketing bullet" feature (while what's there is a good start, it's not ready for prime-time). Please re-open this issue, or at least track the feature request and genuine user need somewhere and give me a link to that so I can track status.

> While I understand the idea, they can always do this anyway. They just set up the matterbridge somewhere else and specify their account with an app token from the personal settings on it. 🤷

Given that the current implementation simply runs a matterbridge binary on the Nextcloud server, I don't see how this helps. The only (documented) controls available today for an admin are 'on' and 'off' (and selecting which binary to use via the command line). But as I said this is a different issue.
