### ISSUE TITLE
Inviting bridge-bot to a conversation is confusing

### ISSUE THREAD

**Issue by plinss** [nextcloud/spreed#4386]
## Steps to reproduce
1. Create a conversation and add a bridge, which in turn creates the bridge-bot user
2. Create a new conversation
3. Note that bridge-bot is listed in the set of users available to add to the conversation

### Expected behaviour
bridge-bot should not be listed as a potential user.

### Actual behaviour
When adding bridge-bot, there is no actual bridging taking place. This is a source of user confusion. Users will expect inviting the bridge-bot user to activate a bridge.

The bridge-bot user should only be present when bridging is taking place.

## Talk app

**Talk app version:** 10.0.0

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macOS

**Browser name:** Firefox

**Browser version:** 81.0.1

## Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.34

**Nextcloud Version:** 20.0.0(see admin page)

**Comment by nickvergessen** [comment]
Yeah the account should not be listed
