### ISSUE TITLE
Status icon is non-transparent when hovering

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#4387]
See avatar in file list:
![image](https://user-images.githubusercontent.com/5836855/96228150-786ec080-0f95-11eb-898e-91388112d703.png)

Mouser hover:
![image](https://user-images.githubusercontent.com/5836855/96228209-8b819080-0f95-11eb-93dd-4d9bc8fc1627.png)

I think it should be both the same…
It happens only with custom icons.

(Morris, I hope it is ok to use your avatar as example)

**Comment by PVince81** [comment]
as far as I understand, that status icon is part of the Avatar component, so that would be https://github.com/nextcloud/nextcloud-vue (to be confirmed)

unless you are observing this only in the file list but not in other places ?

**Comment by PVince81** [comment]
yeah, it might be this bit: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Avatar/Avatar.vue#L616

**Comment by nickvergessen** [comment]
Could also be a side effect of https://github.com/nextcloud/spreed/blob/1b923600cd641514bdebd8dfce778a0e1361e4ed/src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue#L171-L179

**Comment by nickvergessen** [comment]
This is actually required so theming colors don't break the visibility of the icon too much on hover.
