### ISSUE TITLE
Black background for "waiting for others"

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4388]
## Steps to reproduce
1. Start a call and stay alone
2. Admire the message "waiting for others"

### Expected behaviour
Another less dark background, maybe grey like in the stripe ?

### Actual behaviour
Black background.
It's so black that it looks like a bug
<img width="472" alt="image" src="https://user-images.githubusercontent.com/277525/96263806-baaef680-0fc3-11eb-91ff-d9aa0406c320.png">
## Talk app

**Talk app version:** 10.0.0 (from git v10.0.0)

@ma12-co any ideas how to make it better ?

**Comment by ma12-co** [comment]
Makes sense! Sure we could match the stripe selected video background :)

**Comment by PVince81** [comment]
fix is here https://github.com/nextcloud/spreed/pull/4408
