### ISSUE TITLE
[NC 20] Guest can't enter conversation via Lobby

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/spreed#4390]
## Steps to reproduce
1. Create conversation and turn Lobby on (with date and time). Allow guests to join via link
2. Send Link to guest
3. Guest enters Lobby
4. Start Call

### Expected behaviour
Guest should enter conversation

### Actual behaviour
Guest is still in Lobby

## Talk app
10.0.0
**Custom Signaling server configured:** yes
**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

**Comment by nickvergessen** [comment]
You need to remove the lobby so guests can join. It's done this way so moderators can already prepare the call/screenshare and so on

**Comment by jpbraun** [comment]
Thank you for your response.
