### ISSUE TITLE
i miss the feature "write to conversion" in flow

### ISSUE THREAD

**Issue by derpieler** [nextcloud/spreed#4401]
## Steps to reproduce
1. go to flow.
2. no card "write to conversion" apears
3.

### Expected behaviour
have the possibility to select the flow

### Actual behaviour
there not such a card. is it actually deactivated?

## Talk app
Talk 9.0.4
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no

**Custom STUN server configured:** no 

## Browser
opera, chrome, firefox

**Comment by PVince81** [comment]
as far as I can see there is code for that already in Talk 9.0.4: https://github.com/nextcloud/spreed/blob/v9.0.4/src/views/FlowPostToConversation.vue

and I see this in Talk 10.0.0:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/277525/96409376-77cc6900-11e5-11eb-9bf4-44190de586ee.png">

so this is definitely implemented.

if you don't see it in your setup please check the logs (browser log, nextcloud.log, etc)
