### ISSUE TITLE
A way to block guests based on IPs

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#4403]
Would be great to have this control of blocking guests that may disrupt conversations, based on their IPs.

**Comment by nickvergessen** [comment]
If you want to block certain IPs I suggest to do that on another level. It should either be Nextcloud itself, or even deeper. On webserver level there are quite good tools to do things like this.

**Comment by tiotrom** [comment]
I understand, but it could be very handy to be able to block guests directly from the chat itself. Imagine if someone is spamming an open chat....you will have to investigate what IP the guest has and try to block it at the server level. Takes a lot of time and skills.

What if public chats generate a unique ID based on someone's email - like for them to add an email, choose a username, and join the chat after a unique chat url is sent to the email? A way to use their emails as unique identifiers in case you want more control over Guests. Like another layer of protection.

However, as far as I remember most IRC have this level of control where and admin can ban users based on their IPs. Would be great to have that on Nextcloud.

**Comment by nickvergessen** [comment]
we are not quite there yet, but once we have "user pins" to identify guests you can also revoke them and remove their access in abuse case like this?

**Comment by tiotrom** [comment]
Seems interesting. How are these working? What are you "banning"? Their IP? Their username?

**Comment by nickvergessen** [comment]
Well they will get a unique pin in their email invitation and that pin can then be invalidated

**Comment by tiotrom** [comment]
Ah yes exactly what I was thinking. So is this something you work on already or? :)

**Comment by nickvergessen** [comment]
- Bans have been implemented recently https://github.com/nextcloud/spreed/issues/12291
