### ISSUE TITLE
Psalm failures in CI

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4404]
## Steps to reproduce
1. Create a PR and change non-PHP files
2. Push and wait for CI

### Expected behaviour
CI passing, no unrelated fails.

### Actual behaviour
Static check fail related to psalm:
See https://github.com/nextcloud/spreed/pull/4363/checks?check_run_id=1274170734
<img width="896" alt="image" src="https://user-images.githubusercontent.com/277525/96426109-17492600-11fd-11eb-893f-6f0461f57da0.png">

## Talk app
git master 613d089c820b36b41ab2b314192f22f264fd8b30

Strange that all passed in https://github.com/nextcloud/spreed/pull/4336.
Maybe a cross-merge happened from another PR ?

@nickvergessen

**Comment by PVince81** [comment]
Naive fix attempt here: https://github.com/nextcloud/spreed/pull/4405

**Comment by PVince81** [comment]
fix attempt failed, now it says: ` ERROR: MissingDependency - lib/Chat/SystemMessage/Listener.php:249:28 - OCP\Share depends on class or interface oc\share\constants that does not exist (see https://psalm.dev/157)
		$dispatcher->addListener(\OCP\Share::class . '::' . 'postShare', $listener);`

I wonder if something changed in the server maybe

**Comment by PVince81** [comment]
I suspect it might be because christophwurst/nextcloud's OCP\Share extends the OC\Share\Constants class which is not bundled in that library

**Comment by PVince81** [comment]
So it works if I cheat:
1) Use https://github.com/nextcloud/spreed/pull/4405
2) Run `composer install`
3) Go to "vendor/christophwurst/nextcloud" and remove the "extends" bit:
```
diff --git a/OCP/Share.php b/OCP/Share.php
index 9ecfccf..8056a8f 100644
--- a/OCP/Share.php
+++ b/OCP/Share.php
@@ -48,7 +48,7 @@ namespace OCP;
  * @since 5.0.0
  * @deprecated 17.0.0
  */
-class Share extends \OC\Share\Constants {
+class Share {
 
        /**
         * Get the item of item type shared with a given user by source
```

4) Run psalm locally

=> errors gone

Not sure how that project is constructed, @ChristophWurst any idea ?

**Comment by ChristophWurst** [comment]
> Not sure how that project is constructed, @ChristophWurst any idea ?

It's built from git https://github.com/ChristophWurst/nextcloud_composer/blob/master/build.sh

**Comment by PVince81** [comment]
I find it strange that all still "works" somehow despite the many references to the `\OC` namespaces in some classes

**Comment by ChristophWurst** [comment]
But yeah, that is a problem. We leak an internal type with ``\OCP\Share``

**Comment by ChristophWurst** [comment]
> I find it strange that all still "works" somehow despite the many references to the `\OC` namespaces in some classes

https://github.com/nextcloud/spreed/blob/master/psalm.xml#L22-L24 :speak_no_evil:

**Comment by PVince81** [comment]
I tried to restart from scratch and now when I run psalm locally it doesn't output any of those errors.
I did have errors on my PR with modifications but without them there are no errors...

So perhaps a slight difference in environment

**Comment by ChristophWurst** [comment]
That, or it's because the Psalm baseline silences all known errors until you touch the code.

**Comment by PVince81** [comment]
I did clear the local cache and global cache. Strange...

Anyway, here's a PR to skip those hook issues https://github.com/nextcloud/spreed/pull/4410 as discussed with @nickvergessen in the former PR
