### ISSUE TITLE
One string appears twice at Transifex. Maybe related to quotation marks

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/spreed#4406]
At Transifex there **two** occurences:

![2020-10-19_12h29_04](https://user-images.githubusercontent.com/2069590/96438250-b888aa00-1206-11eb-8461-be561ec71a04.png)

Just found only **one** related source string

https://github.com/nextcloud/spreed/blob/998626b68b47e13d2c2b196ef2310b54d15c8534/src/components/TopBar/TopBar.vue#L263

@MorrisJobke Can this be caused by scripts you are running. Do we need to escape quotation marks?

**Comment by nickvergessen** [comment]
Fixed via #4413
