### ISSUE TITLE
Mic/cam error toast persists, even when problem is resolved

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#4407]
## Steps to reproduce
1. Select no mic nor cam
2. Join call
3. See "Error while accessing microphone & camera"
4. Pic the actual mic
5. Join call

### Expected behaviour
Toast disappears (after the call at the latest)

### Actual behaviour
Toast persists forever.

## Talk app

**Talk app version:** company instance

**Comment by PVince81** [comment]
Yep, noticed that as well as I'm usually testing with permissions denied.
A delay would be nice.

There are other variations of the error message IIRC

**Comment by PVince81** [comment]
second one is "Access to microphone & camera was denied"

**Comment by PVince81** [comment]
This has annoyed me long enough, here's the fix https://github.com/nextcloud/spreed/pull/4409
