### ISSUE TITLE
Disable 'Enable video' button if no camera is connected

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#441]
## Steps to reproduce
1. Disconnect your camera
2. Open a call
3. Click on the crossed out video icon

### Expected behaviour
- Button should not be clickable / shouldn't indicate any functionality (e.g. using this CSS `cursor: not-allowed;` / `pointer-events: none;`) 

### Actual behaviour
- Button indicates that video can be enabled, fails silently with a console message `video can not be enabled - there was no stream available before`

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/469
