### ISSUE TITLE
Nextcloud 20, Talk(Spreed) / Firefox > switching camera does not work

### ISSUE THREAD

**Issue by rochelmeyer** [nextcloud/spreed#4414]
## Steps to reproduce
1. have multiple cameras, start a talk
2. Firefox requests permission to access one camera, accept
3. try to switch to a different camera 

### Expected behaviour
should switch camera

### Actual behaviour
Jumps back to the device selected first

Seems to be a browser issue at first, but maybe there's a workaround. that could be implemented within nextcloud. 

## Talk app

**Talk app version:** 10.0.0

**Custom Signaling server configured:** yes/**no** and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/**no** (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/**no** (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes

**Camera available:** yes 

**Operating system:** Linux KDE neon (ubuntu).

**Browser name:** Firefox 81.0.2 (64-Bit)

**Browser version:**

**Comment by danxuliu** [comment]
Have you tried with Chromium too? Did it work?

Also please check the following in Firefox: after starting the call and granting the permissions, instead of switching to a different camera, first switch to no camera AND no audio, and only then try to set a different camera. Is the camera changed in that case?

Thanks for the information.

**Comment by rochelmeyer** [comment]
@danxuliu Thanks for investigating. 

Yes, disabling audio & video works, but that of course is not what you would do in a meeting. 
Another solution seems to be having the camera(s) already connected at startup (reboot). I need yet to see if restarting the browser alone would be sufficient. Not fun with lots of tabs open,  but can be done.
Can we get camera switching out of the settings and onto the main screen, e. g. as another symbol besides the audio and video buttons? That would make it a  bit easier to handle. Anyway, I can work around that by using OpenBroadcastStudio, so not top priority. 
Cheers

**Comment by danxuliu** [comment]
> Yes, disabling audio & video works, but that of course is not what you would do in a meeting.

Of course, I just wanted to know if it is the issue I suspected ;-) And it seems to be. If both audio and video are requested at the same time (which is done when starting a call) Firefox does not seem to allow to change to a different audio or video device until the previous devices are stopped. We should be able to work around this in Talk by first requesting audio and then video, in different steps, when starting a call.

> Can we get camera switching out of the settings and onto the main screen, e. g. as another symbol besides the audio and video buttons? That would make it a bit easier to handle.

On one hand I think that is a good idea, as besides being "spatially pertinent" (I do not know how to express that :-P ) and more convenient it will also make possible to select devices when Talk is embedded in a sidebar (as there is no settings button in that case). On the other hand I fear that it might clutter the controls too much, and also for something that might not be used often by most people. @ma12-co @jancborchardt What do you think?

**Comment by nickvergessen** [comment]
> R: J… can we talk about a joining screen in talk like in teams, webex etc. So I can chose before I join if I want to show my naked torso to the whole company?
> J: Oh I totally agree, no discussion needed. Very important for privacy and checking devices – cc  J2, M. Jitsi does it very nicely with just showing your camera full-screen so you can adjust your hair and check that hte background is good, and a short feedback text about "Your microphone seems to work".

**Comment by ma12-co** [comment]
We could have a single settings button in the local media controls that brings up the settings modal with the audio and video settings without having to open the sidebars.

**Comment by jancborchardt** [comment]
Yes, both a "joining screen" to check your devices, as well as the ability to quickly switch your camera would be great.

Jitsi does both, they have a join screen. And a quick switcher in the join screen as well as during the call so you can switch audio/video devices. Very nice how it is linked to the audio and video buttons respectively so it is directly clear what it will switch, and you don’t need to go through a dialog where you see technical device names, but directly previews of the camera.
![image](https://user-images.githubusercontent.com/925062/96888064-833dbf80-1485-11eb-9c17-aaf6ecb50e1e.png)

Check for yourself on https://meet.jit.si with any room.

**Comment by ma12-co** [comment]
> Very nice how it is linked to the audio and video buttons respectively so it is directly clear what it will switch

I think that that is very bad UX: a button overlapping another button. Also it doesn't meet our accessibility standards: at least 44x44px buttons.

**Comment by jancborchardt** [comment]
Well, it is very obvious, so that’s what I’d call good UX. The accessibility is indeed not great though, I merely showed it as an example.

Since our local controls are getting filled up, what we could simply do is have 3 controls:
- Microphone mute/unmute
- Video on/off
- More 3-dot-menu with
   - Screensharing
   - Change microphone
   - Change camera

Also is very related since for screensharing we have the "Change screen" as well, and that’s very similar to changing the camera.

**Comment by nickvergessen** [comment]
Skype has device selection on hover (for quick access) and a "…" menu in the right as a better accessible version:

### Hover 
Audio | Video
---|---
![2020-10-26 19_52_37-](https://user-images.githubusercontent.com/213943/97287644-1e97b180-1845-11eb-9910-50d16e95f89e.png) | ![2020-10-26 19_52_52-](https://user-images.githubusercontent.com/213943/97287679-29524680-1845-11eb-98b0-e3c71954e77a.png)

### Detail Option in the right
![2020-10-26 22_08_43-Window](https://user-images.githubusercontent.com/213943/97287704-2f482780-1845-11eb-8a8e-64955b43dc90.png)

**Comment by PVince81** [comment]
3-dot menu was added in v11.0.0-alpha.2, you can invoke the settings dialog there
