### ISSUE TITLE
participant-row have pointer cursor despite not doing anything on click

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#4423]
![Sans titre](https://user-images.githubusercontent.com/14975046/96684275-a2502a80-137b-11eb-83b1-65d022e11393.png)

1. Don't be in a search
2. Hover The participant list
3. See the cursor pointer flash some time to time
4. Click when the pointer cursor is shown
5. See that nothing happens
6. Get confused
   ![96684456-e2afa880-137b-11eb-982d-6b35473c5478](https://user-images.githubusercontent.com/14975046/96684596-1d194580-137c-11eb-8d66-1448f605e616.png)

cc @ma12-co

**Comment by nickvergessen** [comment]
Ref #1803

**Comment by PVince81** [comment]
Fixed in v11.0.0-alpha.2

The hand cursor now only appears when an action is possible, like adding a participant.
