### ISSUE TITLE
Regain access to a lost "chat"

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#4435]
Say I create a chat. I am an admin. The I leave the chat. Can I find that chat again and take control over it? Like I created a public chat to test this, but I do not know how to regain access to that chat and delete it...

**Comment by PVince81** [comment]
Interesting question.

I've tried the following steps:

1. Login as admin
1. Create a conversation "pub"
1. Copy conversation link to clipboard
1. Leave conversation
1. Open link: this brings you back to the conversation (but if you lose the link you can't go back)
1. Leave conversation again
1. Log out
1. Open the link

Here you arrive as guest into a conversation that has no moderators.
In general when more than one person exists in a conversation it is not possible for the last moderator to leave it without assigning a new one.

Maybe we should automatically delete / lock conversations with no moderators ?
Or when clicking "Leave conversation" and being the last person there, do the same as "Delete conversation" if there is later no one that can join ?

Not sure if we should allow conversations with zero moderators and only guests...

**Comment by PVince81** [comment]
@tiotrom in your specific case, if you have access to the DB it is possible to find back the room URL by running `select token  from oc_talk_rooms where name like '%pub%'` and appending the token behind the URL. So if the token is "mytoken" then the URL becomes "https://yourhost/index.php/call/mytoken" or "https://yourhost/call/mytoken" if you have a setup without index.php in URL.

Open the URL while logged in to re-join the room.

**Comment by nickvergessen** [comment]
There is a background job which removes rooms that have no logged in users as foxed members.
That should clear it up.
Also (at least form my memory) the last moderator/owner can not leave the conversation but has to delete it.

**Comment by tiotrom** [comment]
> There is a background job which removes rooms that have no logged in users as foxed members.

Ok. I didn't test that. But still, as an admin of the nextcloud instance, and of the group, shouldn't I be able to regain control of the group somehow? Or to re-join and become a moderator?

**Comment by nickvergessen** [comment]
No, because as said it should immediately delete anyway when the last moderator leaves it

**Comment by tiotrom** [comment]
A, ok I understand. Makes sense.
