### ISSUE TITLE
Add support to specify tab order in right sidebar

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/spreed#446]
New tabs added to the right sidebar (via [`addRegion`](https://github.com/nextcloud/spreed/pull/439/files#diff-ba7318b77dd06e9df0c287718a83edadR100)) currently are always _appended_.
There should be an option to influence the position for new tabs (e.g. by specifying a `priority`).

**Comment by nickvergessen** [comment]
@danxuliu is that possible somehow?

**Comment by danxuliu** [comment]
Here you have: #448
