### ISSUE TITLE
Click/focus on main view should close navigation bar

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4465]
## Steps to reproduce
1. Have a narrow screen so that the navigation bar (on the left) is closed
2. Open a conversation
3. Click the hamburger menu to open the navigation bar
4. Now click either inside the main chat window or on the input field at the bottom

### Expected behaviour
Navigation bar should automatically close

### Actual behaviour
Navigation bar stays in the way, I need to move the mouse to the hamburger menu to close it again.

## Talk app

**Talk app version:** 11.0.0-dev.2 git master 02fb50c233ebf365f2bdf65b680b6bd663cd1b2a

**Comment by PVince81** [comment]
I wonder if this should be a general behavior for all apps. Thoughts ? @nextcloud/designers ?

**Comment by raimund-schluessler** [comment]
> 
> 
> I wonder if this should be a general behavior for all apps. Thoughts ? @nextcloud/designers ?

It should, see https://github.com/nextcloud/nextcloud-vue/issues/1070.

**Comment by PVince81** [comment]
thanks! closing in favor of https://github.com/nextcloud/nextcloud-vue/issues/1070 then
