### ISSUE TITLE
Dashboard widget does not show messages in 1on1 conversations

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4466]
Currently the Dashboard only seems to handle mentions. This has the drawback that new messages in 1on1 conversations – which are displayed as "blue" in the conversation list – do not show up in the widget, as it would be expected.

The widget should also show when there was a message (not only @mention) in any 1on1 conversation, which is inherently a direct notification.

Conversation list | Widget
-|-
![talk notifications](https://user-images.githubusercontent.com/925062/97179864-9f00d880-1799-11eb-98e5-369b3b954440.png) |![Talk widget](https://user-images.githubusercontent.com/925062/97179862-9e684200-1799-11eb-98b9-762e44391f3b.png)

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4944
