### ISSUE TITLE
Screensharing view does not show speaker

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4478]
Currently, the person screensharing is not visible, especially when you collapse the bottom bar like is possible in master.

Ideally the speaker should also be visible still in small in some corner of the screenshare (probably bottom right) – this is what Jitsi for example does.

We could reduce the size of the video in that case to a small circle to not overlap too much of the screen – but showing the speaker will make it look much nicer and interactive.

**Comment by nickvergessen** [comment]
> probably bottom right

Will be weird, as we then need to move away your controls or they are on top of someone elses video?

**Comment by Moini** [comment]
I'd like this to be optional, and arrangeable by the user, so each user can show or hide the speaker and any other video shares. 

Somehow, I haven't understood the concept of the two different views in Nextcloud Talk yet (the tile view cuts the video image in strange places, and there seems to be no option to decide which picture I want to enlarge - maybe it's different when one isn't the host, but I found the current fixed layouts rather limiting. Probably that's beyond the scope of this issue, though.).

**Comment by jancborchardt** [comment]
Apple now announced this as "presenter overlay". It is either available as a little circle of your video over the presentation, or as your full video view with the presentation inside it and behind you:

https://www.apple.com/105/media/us/macos/sonoma-preview/2023/e6d837c5-8a7e-49d8-b0bd-137b21320db3/anim/presentation/large_2x.mp4

![](https://www.apple.com/v/macos/sonoma-preview/a/images/overview/video-conference/share_preview_startframe__fz9vau8gox26_large.jpg)

cc @karlitschek @AndyScherzinger @nickvergessen

**Comment by jancborchardt** [comment]
@nextcloud/designers this was also selected and would need a mockup! :)

While of course the Apple presenter overlay would be the ideal state, we need to take it in steps. The basic first iteration could be to just show the speaker in a circle on the bottom right, like it's in some screencasts people do on Youtube, or Twitch streams, or presentation recordings. The only control needed would be to show or not show that (e.g. via expand/collapse).
