### ISSUE TITLE
Enforce use of ICommentsManager in all objects

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4481]
See https://github.com/nextcloud/spreed/pull/4425#issuecomment-717816406 for some context.

~~Objects should never rely on ICommentsManager but receive the `OCA\Talk\Chat\CommentsManager` instead, as we rely on implementation details of that specific instance.
Accepting any other implementation (like core's comments app CommentsManager) could result in unwanted side-effects.~~

After research we noticed that it is possible to alias ICommentsManager to CommentsManager to make it safe to use within the app.

**Comment by nickvergessen** [comment]
ChatManager already get's the right class.

**Comment by PVince81** [comment]
I've updated the subject and top post to match the new approach we discussed with aliasing.

PR here: https://github.com/nextcloud/spreed/pull/4483
