### ISSUE TITLE
Display call view directly after starting/joining

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4486]
## Steps to reproduce
1. Start a call or join a call

### Expected behaviour
Call view appears directly with a message "Connecting"
If permissions are needed, the browser dialog appears on top.

### Actual behaviour
First some delay with a spinner on the button.
Then the browser dialog (if needed).
Some slight UI jumpiness.
Then the call view appears.

## Talk app

**Talk app version:** 11.0 pre-alpha (git master)

## Notes

If we can display the call view immediately after clicking the button, it would make the app feel more responsive, even if the delay for the connection still happens afterwards.
It would prevent having the UI change multiple times during call initiation which makes it feel a bit clumsy.

**Comment by PVince81** [comment]
Same thing for when leaving a call with the button.
We should show the conversations again.
We might keep the call button there with "Leaving call" and the spinner but already let the user interact with the UI (but not join another call yet)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/3584

**Comment by nickvergessen** [comment]
The permissions are not handled by the device checker nowadays, so the flow is already much better.
From my POV I would close the issue, fine by you @PVince81 ?
