### ISSUE TITLE
Close button on duplicated session screen shouldn't leave conversation

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#4488]
## Goal
Open chat on Talk Web while being on a call on Talk iOS

## Steps to reproduce
1. Start a call in Talk iOS
2. Select the conversation in Talk Web
3. "Duplicated Session" window appears
4. The button "Diese Seite verlassen" does the same thing as the "X" on the top right corner.

![image](https://user-images.githubusercontent.com/1580193/97596220-c90a0300-1a04-11eb-9ad7-fcbb9c349f94.png)

### Expected behaviour
The "X" on the top right corner closes the "Duplicated Session" window and allows me to scroll through chat (chat is loaded and displayed anyways in the background)

### Actual behaviour
Clicking the "X" on the top right corner leaves the conversation, no chance to look through the chat

## Talk app

**Talk app version:** 10.0.1

**Comment by nickvergessen** [comment]
This is the expected behaviour at the moment.
What you wish is #1587
