### ISSUE TITLE
Talk v 10.0.1:  Missing text chat in same windows as video chat.  - sound sources unstable and impossible to choose.

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/spreed#4491]
## Steps to reproduce
1.activate text chat see participants.
2.sound sources unstable and impossible to find option for microphone and sound out source 
3.

### Expected behaviour
Tell us what should happen
It should be possible to choose sources microphone and loudspeaker etc. from settings
### Actual behaviour
Tell us what happens instead
I cant find this option.
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
Yes
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

## Browser
chrome last v
**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...
chrome last version
**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```
NA
</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.2/7.3/7.4

**Nextcloud Version:** (see admin page)
20.0.0
**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
As logged in user there is a "Settings" button in the bottom left, for all users there is a settings tab with a settings button that brings you to a device selection.

Audio out however is currently not selectable explicitly, it will play on your OS device.

**Comment by digitalrevisor** [comment]
Thanks. I know.  But this feature to write somthing in the chat has disapeared while doing a video conversation at same time.  Where is that possible to enable maybe?

**Comment by nickvergessen** [comment]
can you post a screenshot? Because the chat is in the right sidebar and still accessible while in a call
