### ISSUE TITLE
Image label in chat view causing layout disturbances

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4494]
## Steps to reproduce
1. Post a picture in landscape mode
2. Start a call
3. Open the chat sidebar
4. Reply to the message in question

### Expected behaviour
Time of message properly aligned.
No extra spacing below the file name label.
In the reply box, also no extra spacing below the file name label.

### Actual behaviour
Time of message properly pushed to the right.
Extra spacing below the file name label.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/277525/97631625-8d396280-1a31-11eb-8b35-2323bc5a94a6.png">

In the reply box, also extra spacing below the file name label.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/277525/97631726-ae01b800-1a31-11eb-9cc7-107de735e3b4.png">

## Talk app

**Talk app version:** 11.0 pre-alpha git master (062916bc71966e99bbf7a50b1c193f9c88013575)

## Notes

Likely introduced or worsened through the changes that allow the image to expand horizontally in https://github.com/nextcloud/spreed/pull/4472

I didn't find where the extra spacing is coming from.
Seems we need to change it to another display mode, not block.

**Comment by jancborchardt** [comment]
As also mentioned elsewhere – other chat apps don’t show the image title as it’s rarely useful and looks rather technical. Let’s just cut it. :)

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/4534

**Comment by PVince81** [comment]
As discussed in https://github.com/nextcloud/spreed/pull/4534, the file name will still be preserved for non-image file types.

As for the layout, I found that the order of elements matter, more precisely the spaces that are introduced by HTML markup can have an influence...

This is the current state:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/277525/98384338-ee72be80-204d-11eb-9433-8a5baa342038.png">

And if we move the "strong" element to the end of the comment blocks the extra space vanishes:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/277525/98384382-fe8a9e00-204d-11eb-9725-56a1abe7062e.png">

But it also means moving the file name below the progress bar on upload. I think it's not that bad as it would make the progress bar closer to the preview, as they fit well together.
