### ISSUE TITLE
Screen share feature of video call app is not working properly with windows8

### ISSUE THREAD

**Issue by ac07633-sac** [nextcloud/spreed#450]
Screen share feature of video call app is not working properly with windows8, The shared screen is not changing unless the shared screen is resized. But it is working fine with windows7

## Steps to reproduce
1. screen share using video call app from windows 8 system
2. screen will be seen but there will not be any movement until there is change in the size of shared window.

### Expected behaviour
shared screen should be responsive and it should be visible to all the accounts it is shared with.

### Actual behaviour
Tell us what happens instead

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Screensharing only works with Firefox 52 or later as per https://github.com/nextcloud/spreed#why-is-this-so-awesome

If you are using that or a later Firefox version, please be more specific by posting better setup descriptions, logs and steps to reproduce

**Comment by nickvergessen** [comment]
Closing because of the lack of feedback
