### ISSUE TITLE
Ellipsis long user names on sidebar

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#4500]
![Capture d’écran_2020-10-29_08-49-43](https://user-images.githubusercontent.com/14975046/97713619-5e1e0200-1ac0-11eb-9276-91d28cec775b.png)

**Comment by nickvergessen** [comment]
It used to be ellipsed :thinking:

**Comment by PVince81** [comment]
I have a quick solution for ellipsis that works for the participant list.

Still, I'm not happy to not have a tooltip there, so looking into the latter, and making it conditional with [ellipsis detection](https://stackoverflow.com/questions/7738117/html-text-overflow-ellipsis-detection)

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4548

**Comment by PVince81** [comment]
also no ellipsis on stable20 and Talk 10.0.1, same behavior there.
let's backport
