### ISSUE TITLE
Talk update bot messages should indicate if a change refers to web/android/iOS

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/spreed#4502]
## Steps to reproduce
1. open the Talk update bot chat on Talk android app
2. read messages like "you can now send files in talk"
3. be confused/disappointed because sending files does not work in android

### Expected behaviour
Always have three sections: "Updates in Talk web version" and "Updates in Talk Android App" and "Updates in Talk iOS App".

### Actual behaviour
Updates are meant for web view only but sent to android and ios users also.

## Talk app

**Talk app version:** 9

**Comment by nickvergessen** [comment]
Well normally this is for all clients. The android app is just lacking behind at the moment.

**Comment by alexanderdd** [comment]
@nickvergessen but do you agree or disagree with my proposal?

**Comment by nickvergessen** [comment]
I disagree, as all messages should always apply to all clients (mobile and web). Our plan is to always bring features to all clients in the same verison. Android is behind at the moment and will hopefully catch up soon and this problem will be gone.

**Comment by nickvergessen** [comment]
Closing as per above
