### ISSUE TITLE
Psalm issues share listening

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4512]
See https://github.com/nextcloud/spreed/runs/1340889286?check_suite_focus=true

```
ERROR: InvalidArgument - lib/Chat/SystemMessage/Listener.php:266:52 - Argument 2 of OCP\EventDispatcher\IEventDispatcher::addListener expects callable(OCP\EventDispatcher\Event):void, impure-Closure(Symfony\Component\EventDispatcher\GenericEvent):void provided (see https://psalm.dev/004)
		$dispatcher->addListener('OCP\Share::postShare', $listener);


ERROR: InvalidArgument - lib/Chat/SystemMessage/Listener.php:267:82 - Argument 2 of OCP\EventDispatcher\IEventDispatcher::addListener expects callable(OCP\EventDispatcher\Event):void, impure-Closure(Symfony\Component\EventDispatcher\GenericEvent):void provided (see https://psalm.dev/004)
		$dispatcher->addListener(RoomShareProvider::class . '::' . 'share_file_again', $listener);


ERROR: InvalidArgument - lib/Flow/Operation.php:85:67 - Argument 2 of OCP\EventDispatcher\IEventDispatcher::addListener expects callable(OCP\EventDispatcher\Event):void, impure-Closure(Symfony\Component\EventDispatcher\GenericEvent):mixed provided (see https://psalm.dev/004)
		$dispatcher->addListener(FlowManager::EVENT_NAME_REG_OPERATION, function (GenericEvent $event) {
			$operation = \OC::$server->query(Operation::class);
			$event->getSubject()->registerOperation($operation);
			Util::addScript('spreed', 'flow');
		});


ERROR: InvalidArgument - lib/Share/Listener.php:38:51 - Argument 2 of OCP\EventDispatcher\IEventDispatcher::addListener expects callable(OCP\EventDispatcher\Event):void, array{OCA\Talk\Share\Listener::class, string(listenPreShare)} provided (see https://psalm.dev/004)
		$dispatcher->addListener('OCP\Share::preShare', [self::class, 'listenPreShare'], 1000);
```

not sure why they just started appearing now...

**Comment by MorrisJobke** [comment]
BTW this is the same as https://github.com/nextcloud/server/pull/23742#issuecomment-717765293

This works code wise, because our dispatcher just accepts them. But those are old events anyways and shouldn't be used anymore. (see https://github.com/nextcloud/server/pull/23742#discussion_r514516180)

So the solution here is to either:

a) use the old dispatcher (`OC\EventDispatcher\SymfonyAdapter`) with the current events (as it is right now)
b) use the new dispatcher (as it is right now) but change the events to `OCP\EventDispatcher\Event`

**Comment by nickvergessen** [comment]
Errm we just listen. So the events need to change in the server. From my pov nothing to do on our/Talk side

**Comment by PVince81** [comment]
I'll update the baseline to "accept" these errors for now

**Comment by PVince81** [comment]
Weird... I don't get these errors locally:

- server ff08b10a897f059adbd30b61e6f4ba1e9af7b719 freshly pulled
- spreed 49342868037dd89e793eb546c7ff24fc477ef527 the one from CI
- `christophwurst/nextcloud              dev-master b2289bc` also the one like in that test run
- `psalm --clear-cache`
- `psalm --clear-global-cache`

then running Psalm shows no errors:
```
------------------------------
No errors found!
------------------------------
624 other issues found.
You can display them with --show-info=true
------------------------------

Checks took 18.49 seconds and used 600.091MB of memory
Psalm was able to infer types for 94.9047% of the codebase
```

PHP 7.4.11 (cli)

Might need to look into more setup discrepancies

**Comment by PVince81** [comment]
ah wait, there's a second thing that upgrades it on CI: `Upgrading christophwurst/nextcloud (dev-master b2289bc => dev-master 70e3634): Checking out 70e36349cd from cache`

**Comment by PVince81** [comment]
Fix is here https://github.com/nextcloud/spreed/pull/4517 + extras
