### ISSUE TITLE
Highlight the original message when scrolling on a reply

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4516]
## Steps to reproduce
1. Click on the original message part of a reply
> ![Bildschirmfoto von 2020-11-02 13-05-13](https://user-images.githubusercontent.com/213943/97866552-6cf8f480-1d0c-11eb-8d0b-227aa4b935cf.png)
2. Chat scrolls up to original message, but (due to mouse position) a "random" message is highlighted instead of the message you clicked on.
> ![Bildschirmfoto von 2020-11-02 13-05-18](https://user-images.githubusercontent.com/213943/97866632-9023a400-1d0c-11eb-8230-c556ec1eeb5a.png)

### Expected behaviour
The message you clicked on should be highlighted (maybe even more than a mouse hover and "sticky" (so hovering a different message does not loose it)

I also currently find the "message is scrolled to the middle" part confusing, but the correct (forced) highlight will solve this.

### Actual behaviour
Message under the cursor is highlighted.

**Comment by PVince81** [comment]
Seems this would introduce the concept of message highlighting that sticks (unless this is a regression, but I haven't seen such highlight before except on hober)

how long to highlight it ?
should clicking elsewhere remove the highlight ?
should we also allow to highlight by simply clicking on a message ?

**Comment by nickvergessen** [comment]
No strong feelings, something like https://stackoverflow.com/a/64617156 would be good enough from my pov

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4585

I've used the same highlight style like when highlighting uploaded files in the files app.

**Comment by PVince81** [comment]
Would be great to have the same effect when coming from search.
So far I haven't found the code path that reads the URL param with the message id.

**Comment by PVince81** [comment]
> Would be great to have the same effect when coming from search.
> So far I haven't found the code path that reads the URL param with the message id.

added to my PR: https://github.com/nextcloud/spreed/pull/4585
