### ISSUE TITLE
Bells, ringing sound while alone in call

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/spreed#4520]
If you start a call and your counterpart does not pick up immediately, the complete time is silent. If you use it in an office and have a real-life-talk with another person in the meantime, you forget about the open call. 

A little sound , bells, ringing tone would be fine during the time another person joins the call

**Comment by nickvergessen** [comment]
Duplicate of #3388

**Comment by Bolli84** [comment]
@nickvergessen it is not a duplicate of #3388

I am in the call/tab instead of the above named and want to have the "waiting" tone until the other one responds. Currently, there is only silence. It should be on one-on-one conversations to have the same rining behaviour like whatsapp, or the simple old telefon sound until the other one picks up.

**Comment by nickvergessen** [comment]
Well we will fix it in the same go
