### ISSUE TITLE
Multiple Users on Android & IOS not able to see one another

### ISSUE THREAD

**Issue by axheli** [nextcloud/spreed#4524]
## Steps to reproduce
1. Create a Meeting
2. Add Participants
3. When Participants joing via the androis or ios app they cant see each other but via web you can see everyone and hear everyone. Only happans via ios and android talk app 

### Expected behaviour
All user should be able to see and hear each other. 

### Actual behaviour
When Participants joing via the androis or ios app they cant see each other but via web you can see everyone and hear everyone. Only happans via ios and android talk app 
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
10.0.1
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Turn Server is turn.axtsolutions.com:443
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Stun Server is: stun.nextcloud.com:443

## Browser
Chrome, Firefox
**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Widnows, IOS, Android
**Browser name:** Firefox/Chrome/...
Firefox, Chrome
**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu Server 20.0.4
**Web server:** Apache/Nginx
Apache2 
**Database:** MySQL/Maria/SQLite/PostgreSQL
MySQL 8
**PHP version:** 7.2/7.3/7.4
7.4
**Nextcloud Version:** (see admin page)
20.0.1

**Comment by nickvergessen** [comment]
Please provide the stun and turn info from the issue template

**Comment by axheli** [comment]
@nickvergessen  

Stun Server is: stun.nextcloud.com:443
Turn Server is turn.axtsolutions.com:3478

**Comment by axheli** [comment]
> Please provide the stun and turn info from the issue template

Template has been updated with the stun and turn server
