### ISSUE TITLE
Scroll to bottom button is missing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4527]
## Steps to reproduce
1. Scroll up in the chat view
2. Use the "Scroll to bottom" button to jump to the bottom again

### Expected behaviour
Button is there

### Actual behaviour
Button is not in vision, regression from the height-mess in the sidebar #4493

**Comment by PVince81** [comment]
Works for me in the main conversation view.

But it's indeed missing in the sidebar chat mode.

**Comment by PVince81** [comment]
also, the sidebar chat doesn't automatically scroll to bottom

I suspect that the wrong scroll container is used now by the code, considering that we changed where the overflow and scrollbars are happening.

**Comment by nickvergessen** [comment]
Another related error:
1. Create a new conversation
2. Start call
3. Expect the chat input to be at the bottom of the sidebar

![Bildschirmfoto von 2020-11-04 11-21-44](https://user-images.githubusercontent.com/213943/98099644-19171880-1e90-11eb-8cba-899b8a97b091.png)

**Comment by PVince81** [comment]
PR here for scrolling issues: https://github.com/nextcloud/spreed/pull/4529

**Comment by PVince81** [comment]
new one liner that fixes both: https://github.com/nextcloud/spreed/pull/4530
