### ISSUE TITLE
Video verification gives "Access forbidden  CSRF check failed"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4528]
## Steps to reproduce
1. Share a file by link
2. Set a password
3. Open the share link in a private tab
4. Start the call
5. click in the password field and type something
6. Click on submit error

### Expected behaviour
Works or "Wrong password"

### Actual behaviour
> Access forbidden 
> CSRF check failed

## Talk app

**Talk app version:** master

## Server configuration

**Nextcloud Version:** master

**Comment by nickvergessen** [comment]
cc @danxuliu if you have an idea

**Comment by PVince81** [comment]
works for me on talk master b7727afe2580a34efb56ee324c4ccb34792d0b82
