### ISSUE TITLE
Jump to file / get private link from chat attachment

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4533]
**Is your feature request related to a problem? Please describe.**
Currently the file name of an image is shown. One could remember that name and then look for that file in their attachment folders to get a more direct access, maybe share it further or copy it. Doing so mentally is cumbersome.
A more direct way would be nice.

**Describe the solution you'd like**
Add a three dots menu overlaid on top of the image, or on its side. In the menu offer options like "Show in files app" and "Copy private link".

**Comment by PVince81** [comment]
note: for supported file types, clicking on the image would open an editor. But the editor itself might not offer to "show it in the files tree".

**Comment by jakobroehrl** [comment]
It could be implemented like in the deck app:
![image](https://user-images.githubusercontent.com/24530680/110470290-f36a7c00-80da-11eb-990e-4782305fc105.png)

**Comment by nickvergessen** [comment]
Sure

**Comment by nickvergessen** [comment]
Done via #5746
