### ISSUE TITLE
Upload confirmation screen needs mouse click

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4536]
## Steps to reproduce
1. Paste image content into the chat with Strg+V 
2. Upload confirmation dialog pops up
![Bildschirmfoto von 2020-11-05 10-03-39](https://user-images.githubusercontent.com/213943/98220335-6d80cd80-1f4e-11eb-8541-421e63bca086.png)
3. Try to submit with Enter 

### Expected behaviour
Submits

### Actual behaviour
Doesn't submit

**Comment by PVince81** [comment]
thanks for raising, had it on my "list of to raise" :smile:

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/spreed/pull/4541

I was first wondering if we should skip the dialog altogether, but one might want to review whatever they pasted before submitting anyway.

**Comment by nickvergessen** [comment]
We just added the dialog in the last release because too many people pasted into the wrong chat by accident and its currently quite complex to remove the share again.
