### ISSUE TITLE
Return room token in occ talk:room:create

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4544]
**Is your feature request related to a problem? Please describe.**
Write a shell script that creates a room with occ then adds participants.
1. Create a room with occ: `occ talk:room:create --owner admin room1`
2. Now try to add participants with `occ talk:room:add` but you don't have the token.

**Describe the solution you'd like**
`occ talk:room:create` should output the resulting room token so that the script can grab it for further use.

**Comment by PVince81** [comment]
context: I've created a script to setup my dev env and creates a lot of rooms.

currently I was able to work this around by adding participents to a group and passing them to `occ talk:room:create ... --group groupname`

**Comment by nickvergessen** [comment]
Yeah I noticed this issue when trying to write unit tests

**Comment by nickvergessen** [comment]
@vitormattos maybe something you can look into?

**Comment by vitormattos** [comment]
Yes, I will look
