### ISSUE TITLE
occ room list

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4545]
**Is your feature request related to a problem? Please describe.**
Since occ talk:room:* provides way to manage rooms to some extent, it would make sense to also be able to list the current rooms and get more info.

**Describe the solution you'd like**
`occ talk:room:list [pattern]` to list the calls, output in table and/or json. Optionally with a search term for the name, maybe participants, etc.
`occ talk:room:get token` to display info about a room. Can be useful before attempting to adjust it with `occ talk:room:update`

**Comment by nickvergessen** [comment]
We decided to not do this intentionally, as it makes it too easy for system administrators to sneak on your conversations and find what you do.

**Comment by davehayes** [comment]
It's a simple pgsql query?
