### ISSUE TITLE
Error "Duplicate session" after deleting room when joined call

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#4552]
## Steps to reproduce
1. Create room and join it
2. Join call
3. Delete the room

### Expected behaviour
No error should be shown.

### Actual behaviour
An error about a duplicate session is shown. This doesn't happen if I don't join the call in step 2.

## Talk app

**Talk app version:** as installed on s.n.c

## Browser

**Browser name:** Chrome

@nickvergessen FYI

**Comment by PVince81** [comment]
need to verify if https://github.com/nextcloud/spreed/pull/4593 (which is merged now) fixes this issue

**Comment by PVince81** [comment]
still happening on master

to clarify: to delete the room I used a separate browser tab and did not join that second room while deleting.
then after a few seconds the room with the call would reload the page and say "duplicate session".

I wonder if maybe it's just a misinterpretation of the error code.

**Comment by PVince81** [comment]
![image](https://user-images.githubusercontent.com/277525/106884140-33f06780-66e1-11eb-9f2d-191a0079b399.png)

maybe the attempt to leave the conversation returned an error

I'll dig further

**Comment by PVince81** [comment]
Fix is here https://github.com/nextcloud/spreed/pull/5082
