### ISSUE TITLE
High CPU with LoadingPlaceholder animation

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4553]
## Steps to reproduce
1. Apply this patch to display the placeholder forever:
```
diff --git a/src/components/MessagesList/MessagesList.vue b/src/components/MessagesList/MessagesList.vue
index 340341d6d..6918d365d 100644
--- a/src/components/MessagesList/MessagesList.vue
+++ b/src/components/MessagesList/MessagesList.vue
@@ -46,7 +46,7 @@ get the messagesList array and loop through the list to generate the messages.
                        v-bind="item"
                        :messages="item"
                        @deleteMessage="handleDeleteMessage" />
-               <template v-if="!messagesGroupedByAuthor.length">
+               <template v-if="true || !messagesGroupedByAuthor.length">
                        <LoadingPlaceholder
                                type="messages"
                                :count="15" />
```
2. Open a conversation in the UI
3. Observe CPU usage

### Expected behaviour
Low CPU usage, but not zero.

### Actual behaviour
High CPU usage, see more info below.

I noticed this because somehow the http requests were stuck so that state stayed longer and my laptop fan kicked in very loudly!

## Talk app

**Talk app version:** 11.0 pre-alpha (git master 3af57c87b27ae4a9a22c58232e195277c1326f5e)

**Hardware:** Dell XPS 13 Laptop with Intel GPU

** Browser:** Chromium 86.0.4240.111 (openSUSE Build) (64-bit)

## More information

On my laptop with Intel GPU, the load is about 54% CPU for Chromium.

I tried replacing it with a simple pulse animation with opacity and the load reduced to ~22%.
Then I added a `translate: translateZ(0)` but it didn't improve much (https://stackoverflow.com/a/13293044)

Now the opacity animation doesn't look as cool, so I tried to reproduce it by having the list twice. One list with regular gradient and one with inverted one. Then use pulse animation to fade between both. The CPU load is still at 22%.

PR upcoming

**Comment by PVince81** [comment]
@skjnldsv I heard that a similar component exists in the unified search, so might need adjusting there as well.

**Comment by skjnldsv** [comment]
Hum, this is a simple svg animation iirc, shouldn't be that hard on the processor unless you show tons of them.
We should 3 on the unified search, I think it make sense to lower the number of entries show.

**Comment by PVince81** [comment]
it's not that simple: we are changing the stop values of a gradient, which means recomputing the whole gradient for every frame.
simple would be using opacity in SVG.
also here I'm not sure if SVG animations run on GPU.

I have an alternative solution with CSS which visually looks almost the same: https://github.com/nextcloud/spreed/pull/4554

**Comment by skjnldsv** [comment]
I can load the entire set of placeholders without my browser beating an eye https://skeletonreact.com/#gallery

So We can definitely keep the sliding animation (which is much fancier than opacity. And is basically what the standards are on placeholders/skeleton nowadays :)
Nonetheless keep in mind we're now using this in a few places and it needs to stay consistent between apps, so changing this here should be changed on photos and unified search too :wink:

**Comment by skjnldsv** [comment]
Yep, I get consistent 144fps while scrolling on the other page, we use the same animation.

For me this is not the issue, but just something related to talk in general :)

**Comment by PVince81** [comment]
wow, 135% CPU in Chromium for me on that page (and another chromium process that stays at 40 % CPU at the same time)

**Comment by skjnldsv** [comment]
That is, a lot!  :scream:

**Comment by PVince81** [comment]
@skjnldsv your laptop specs ?

I'm running on openSUSE on a Dell XPS 13 9333 from 2013, with Intel GPU, so not that good in terms of acceleration.

**Comment by skjnldsv** [comment]
Let's nuke it then, see with Jan though, this is quite a change :)

**Comment by PVince81** [comment]
Maybe we can gather numbers for other people as well first.

Ideally this page only shows for a short time. But if the server is slow you might see for longer times.

**Comment by skjnldsv** [comment]
> @skjnldsv your laptop specs ?

RAM: 32054 MB
Processor Type: Intel(R) Core(TM) i5-8600K CPU@3.60GHz
GPU: AMD Radeon RX 5700 XT

**Comment by skjnldsv** [comment]
> Ideally this page only shows for a short time. But if the server is slow you might see for longer times.

Well, to be honest they're supposed to show something is loading, we display like a full height of them on talk load, displaying like 3 is more than enough

**Comment by skjnldsv** [comment]
> Currently, Chrome never divides an SVG graphic into different GPU layers (although they do other optimizations).
> 
> To create a fully GPU-optimized animation in Chrome, you can sometimes position separate inline <svg> elements over top of each other, creating your own layers.

That would explain why it doesn't scale

**Comment by PVince81** [comment]
probably would be a bit faster if rendered with WebGL and a matching shader for the gradients :sweat_smile:
