### ISSUE TITLE
Raise hand button

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4562]
**Is your feature request related to a problem? Please describe.**
In a call with many participants, like in a remote school setting, it is better that people don't unmute themselves and just talk as it could cause a lot of talking into each other and can quickly become chaotic.

**Describe the solution you'd like**
A "raise hand" button that one can click before speaking.
The moderator can see who raised their hands and grant them "unmute" rights, maybe "ask to unmute" which the person can confirm.

Ideally I think we should show the raised hand state both in the people's video view and also in the call sidebar.
Then the moderator could click on that icon either in the video view or on the sidebar to grant them speaking rights.

## Initial limitations

- The first iteration will not include a "permanent mute" feature, so people would still be able to unmute instead of raising hands. Permanent mute has a separate ticket: https://github.com/nextcloud/spreed/issues/4565
- Sidebar icon not supported yet for guests as it needs some specific backend support for mapping guests there.

## Technical / design notes

- Add hand icon on the left side of the mute button for both own controls and other people's video views
- Add hand icon on the participant sidebar
- We can use the signaling channels (but not data channels) to send the necessary messages about who is raising hand and not (broadcast to moderators).
   - "ask to unmute" message => https://github.com/nextcloud/spreed/issues/4566
   - "person X raised hand" message
   - "person X lowered hand" message
   - can check how https://github.com/nextcloud/spreed/issues/3015 was done as it uses similar channels
- Whenever a moderator joins the room, we could optionally also query whoever raised their hands already.

## Questions

- should only moderators see raised hands ? I think in other solutions everyone sees that, and that way it also looks like a real classroom or meeting. Also: whenever someone is already speaking if they see raised hands they might finish their topic more quickly to let other people speak.

**Comment by PVince81** [comment]
@nextcloud/designers-talk in case you have input

**Comment by PVince81** [comment]
I've raised the following as separate tickets/features:
- ask to unmute: https://github.com/nextcloud/spreed/issues/4566
- permanent mute: https://github.com/nextcloud/spreed/issues/4565

they somehow go hand in hand for a complete experience.

we can keep the current ticket here only for the hand raising topic

**Comment by PVince81** [comment]
PR here for first prototype: https://github.com/nextcloud/spreed/pull/4569

**Comment by PVince81** [comment]
cc @tobiasKaminsky for clients awareness

so far the technical bits about how the info is sent is not set in stone yet (the prototype PR uses signaling)

**Comment by nickvergessen** [comment]
Well also @Ivansss in that case, but as this is not going to end up in the clients until 21 release we can discuss it later.

**Comment by tobiasKaminsky** [comment]
> cc @tobiasKaminsky for clients awareness

Thanks :-)
Mainly I do the coordination for Files clients.

For Talk I leave it up to Joas to coordinate it.
Hopefully our new dev can pick this then up.

**Comment by Pilzinsel64** [comment]
> should only moderators see raised hands ? I think in other solutions everyone sees that, and that way it also looks like a real classroom or meeting. Also: whenever someone is already speaking if they see raised hands they might finish their topic more quickly to let other people speak.

My opinion is that everyone should be able to see that. There are cases where not only the moderator is the speaker, but a full discussion between all participants.

**Comment by PVince81** [comment]
raised https://github.com/nextcloud/spreed/issues/4770 for sorting participant list by raised hand timestamp
