### ISSUE TITLE
Duplicate key name 'tp_room'

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/spreed#4583]
Hello,

When I try to install talk I get this error message.

`An exception occurred while executing 'CREATE INDEX tp_room ON oc_talk_participants (room_id)': SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'tp_room'`

My Nextcloud 

Link: https://cloud.dasnetzundich.de/s/NrgYr5sRWbDMdW2
Passwort: ZohQv9zUrDzmsIQqAoBV

**Comment by nickvergessen** [comment]
Table does not exist any more
