### ISSUE TITLE
Clicking search result from current chat triggers conversation not found error

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4592]
## Steps to reproduce
1. Create a conversation
2. Type some text with the word "example" in it
3. Open the search box on the top bar
4. Type "example"
5. Click the result from the conversation

### Expected behaviour
Page reload to the matching conversation. (ideally no page reload, but that's something for another time)

### Actual behaviour
Sometimes, it seems that leaving the conversation also triggers a 404. Maybe some code has already left the conversation but the code that polls is still running:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/277525/99067281-b964ef80-25aa-11eb-93e2-db91a6aab654.png">

~~This happens fairly often and is annoying.~~

It only happens whenever the clicked search result is targetted at the currently open conversation.
If it targets another conversation the switch happens without issue.

## Talk app

**Talk app version:** 11.0 git master fd02d1a41e89043582523d4945e68c9ab013bf46

**Signaling server:** None

Potential indirect fix: https://github.com/nextcloud/spreed/pull/4338

What I currently don't understand is why the 404 is happening in the first place.
Maybe it's just a result of cancelling the requests.
Furthermore, the "unload" handler is synchronous, so nothing else should be able to happen or fail.

Sometimes it also seems to happen when I click on other links, even other conversations in the left sidebar.

**Comment by PVince81** [comment]
The access log reflects what I see in the network console:
```
127.0.0.1 - - [13/Nov/2020:12:24:38 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/amgxdf2n/participants/active HTTP/1.1" 200 707
127.0.0.1 - - [13/Nov/2020:12:24:38 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/amgxdf2n/participants/active HTTP/1.1" 200 81
127.0.0.1 - - [13/Nov/2020:12:24:38 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/signaling/settings?token=amgxdf2n HTTP/1.1" 200 255
127.0.0.1 - - [13/Nov/2020:12:24:38 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/amgxdf2n/participants?includeStatus=true HTTP/1.1" 
200 354
127.0.0.1 - - [13/Nov/2020:12:24:38 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/signaling/amgxdf2n HTTP/1.1" 404 111
127.0.0.1 - - [13/Nov/2020:12:24:39 +0100] "GET /index.php/apps/spreed/not-found HTTP/1.1" 200 6735
127.0.0.1 - - [13/Nov/2020:12:24:39 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/amgxdf2n/participants/active HTTP/1.1" 200 81
```

so it seems the participant already gets deleted earlier

**Comment by PVince81** [comment]
it seems something is already triggering the leave of the conversation earlier:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/277525/99068492-e5817000-25ac-11eb-9697-c50225d839b1.png">

I suspect it might be the router detecting the URL change, which likely triggers an event before the page event reloads

**Comment by PVince81** [comment]
confirmed, it's triggered in "onRouteChange".
actually the only change in the URL is the addition of a hash.

the issue might be fixable by taking note what conversation was already left and not trying to leave again, I'd expect this to be somewhere in the store

**Comment by PVince81** [comment]
Edited top post: this problem only happens when the search result link is for the currently open conversation.

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/spreed/pull/4593

**Comment by PVince81** [comment]
Aha, here's another set of steps to reproduce the issue, it involves having a hash then removing the hash through click:

1. Create two conversations A and B
1. In conversation A, write a message "example"
1. Switch to conversation B (this will dodge the bug from the OP)
1. Open the search box and type "example"
1. Click the search result: the page will reload with conversation A, but the URL will have a hash part
1. Open the left sidebar and click again on conversation A

The last step will change the URL by removing the hash, which triggers the route change bug reported above.
The result is the same: you land on a "conversation not found" page.

The PR above also fixes that :-)

**Comment by nickvergessen** [comment]
Same problem as https://github.com/nextcloud/spreed/issues/4552 ?
