### ISSUE TITLE
Buttons gathering on the bottom right of chat view

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4597]
## Steps to reproduce
1. Create a conversation with many messages to cause a scrollbar to appear
2. Click "Reply" on any message to trigger the reply box
3. Scroll up to make the "scroll to bottom" button appear
4. Then play with the scrollbar and mouse over to make a reply button appear close to the "scroll to bottom" button

### Expected behaviour
More distance between the buttons

### Actual behaviour
Happy gathering of button friends
<img width="108" alt="image" src="https://user-images.githubusercontent.com/277525/99097723-4e321200-25d8-11eb-8f8f-8ff1b75d78f6.png">

## Talk app

**Talk app version:** 11.0 pre-alpha git master 5add4bbd077eaa334548ad665da9ae95345095cc

**Comment by nickvergessen** [comment]
Doesn't happen anymore so badly in recent talk, so closing
