### ISSUE TITLE
auto join

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#46]
the old spreed.me has normal room and conference rooms where people automatically join the call when in this room. we need a config option per room. 
or is it ok to always have auto join / conference mode?

**Comment by jancborchardt** [comment]
Yes, people should automatically join the call when entering a room. We could have something that when more than 3 (or whatever high number) people are already in the room, any new person joining is muted.

**Comment by jancborchardt** [comment]
We agreed to do autojoin by default for now.

In the future we can do something like showing the video & audio before entering to make sure it’s working, and then having a »Join call« button. But for now let’s keep it simple.

**Comment by jancborchardt** [comment]
Done
