### ISSUE TITLE
Notifications are not shown when All notifications are selected

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/spreed#4609]
## Steps to reproduce
1. In chat settings select All notifications
2. Type in chat something
3. Receive no any notification

### Expected behaviour
To have pop-up notification when something new appears

### Actual behaviour
Notifications appear only when the user is explicitly mentioned. Both related to web and mobile versions.

## Talk app

**Talk app version:** 9

**Comment by nickvergessen** [comment]
Do you still have the conversation open on a device?

**Comment by ostasevych** [comment]
> Do you still have the conversation open on a device?

No, I closed the tab in the Chrome, if you are about that... What I found later that it works with NC20, but not NC18...

**Comment by nickvergessen** [comment]
Okay then we can close this.
