### ISSUE TITLE
Make last date divider sticky

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#4610]
Similar to

![Screenshot from 2020-11-16 13-18-51](https://user-images.githubusercontent.com/26852655/99251907-67240880-280e-11eb-9ad3-1e6dc7dfdc90.png)

**Comment by danxuliu** [comment]
Should it be always sticky, or only if it is not the current day?

**Comment by ma12-co** [comment]
Telegram makes it always sticky, but visible only when **scrolling up**. After the scrolling is done, it persists for a few seconds and then fades away. I think it's an excellent solution.
