### ISSUE TITLE
Slow image upload

### ISSUE THREAD

**Issue by jcastang** [nextcloud/spreed#4613]
## Steps to reproduce
1. Open a chatroom
2. CopyPaste image 
3. Wait for upload complete

### Expected behaviour
Image should be posted as soon as it was uploaded.

### Actual behaviour
Image takes long time to be uploaded.
It seems that when you have "many" image already uploaded, they are all fetched/listed regardind requests sent from web-browser to server before image is really uploaded.
See attached screen.

The result is that image is waitng some times before beeing displayed in chat room/

![image](https://user-images.githubusercontent.com/3185544/99256280-75c1ee00-2815-11eb-9492-91d6ff28c67f.png)

## Talk app 

**Talk app version: 10.0.1

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Browser
.

**Browser name:** Firefox/Chrome last version for both (at that day)

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version: 20.0.1

**Comment by nickvergessen** [comment]
cc @Ivansss what was the server issue to address this?

**Comment by nickvergessen** [comment]
Anyway #4539 should help too

**Comment by PVince81** [comment]
similar to the idea of https://github.com/nextcloud/nextcloud-vue/issues/1618 we could try and limit the number of previews that are loaded at the same time to avoid blocking other browser requests like uploads or posting messages

**Comment by nickvergessen** [comment]
Im closing this as #4539 should remove the default use case of it. You know would need to again and again upload an item with the same name.
