### ISSUE TITLE
Settings tab missing in right sidebar when initially closed

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4618]
## Steps to reproduce
1. Create a new conversation
2. Close all sidebars
3. Refresh the page
4. Open the right sidebar

### Expected behaviour
Settings tab is present, along with Participants.

### Actual behaviour
Only the participants tab is present.
Settings is missing!

### Versions
Talk 11.0 pre-alpha git 7b9a9c8d6cded9317cba69c9be9dd248014aac6f
Browser: Chromium 86

@ma12-co remember, we saw this on a screen share a while ago. Seems I can reproduce this consistently here.

**Comment by ma12-co** [comment]
Does this matter given the fact that we're removing the settings tab?

**Comment by PVince81** [comment]
it's more of a timeline thing and how fast we manage to move everything, considering that some discussions are still in progress.

anyway, I think we can keep this ticket on hold until then

**Comment by PVince81** [comment]
it might matter for backports though if we want to fix this in Talk 10.x

**Comment by ma12-co** [comment]
I think that the new settings should be backported, the old ones are just too confusing

**Comment by nickvergessen** [comment]
Sounds like a good changelog entry for the Talk 11 update though and it worked in 10, so I'd say no backport.

**Comment by PVince81** [comment]
Okay, so the settings tab is completely gone now. Closing as obsolete.
