### ISSUE TITLE
Send chat message on enter

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#463]
Currently enter adds a line break. That’s quite annoying because usually messages are short, and most platforms submit on enter.

We could do Ctrl-Enter to insert line breaks if necessary.

cc @danxuliu

**Comment by danxuliu** [comment]
>  That’s quite annoying because usually messages are short, and most platforms submit on enter.

Agreed.

It is simply a matter of changing the condition in `_onTypeComment`. I could push a new commit to #462, but I would prefer to fix this in a different pull request once that one is merged to better keep track of the issue ().

**Comment by jancborchardt** [comment]
Right, ok. Ideally we should do the same for comments in the Files sidebar too so it's consistent.

**Comment by danxuliu** [comment]
@jancborchardt 
>  Ideally we should do the same for comments in the Files sidebar too so it's consistent.

I can import the change in the Comments app if you want (although comments may be more prone to longer, more elaborated texts than chat messages and thus the current approach of _new line on enter_ is better, I do not know).

**Comment by jancborchardt** [comment]
@danxuliu yes, porting it would be great! The issue atm is more that not really a lot of people know we have Comment functionality, so we need to make it as dead-simple to use as possible. :)

**Comment by danxuliu** [comment]
@jancborchardt 
>  porting it would be great!

Here you have: nextcloud/server#7252 ;-)
