### ISSUE TITLE
No Participant refresh after 10.0.2

### ISSUE THREAD

**Issue by apg1980** [nextcloud/spreed#4631]
## Steps to reproduce
1. Open a Conversation with more than 1 Participants

### Expected behaviour
List of all Partiticants with Status Indicator should displayed

### Actual behaviour
All Participants are not shown its greyed out.
![grafik](https://user-images.githubusercontent.com/9514965/99492851-95b8f500-296e-11eb-95b2-30e912630544.png)
Refresh Browser with F5 the Participants are there (this behaviour is in all Rooms):
![grafik](https://user-images.githubusercontent.com/9514965/99492985-bed98580-296e-11eb-95ac-5bf1de54e425.png)
Also the Status bouble is quite big.

## Browser
Latest Firefox, Edge

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Ubuntu 20.04
**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
`Current participant found 2 CallButton.vue:101
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:489
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:489

​`
## Talk app

**Talk app version:10.0.2 (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes


## Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->


**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version: 7.04

**Nextcloud Version:** 20.01


<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by PVince81** [comment]
does this happen consistently ? could be a timeout of some sorts while loading the participant list

**Comment by apg1980** [comment]
this happens all the time, with f5 the list appears.

**Comment by jcastang** [comment]
Hello,

+1 on this issue.
After 10.0.2 update, participant list is very slow to be updated (or not updated at all) and unread messages are slow to be updated in room list.

Thanks a lot

**Comment by PVince81** [comment]
did you both update from 10.0.0 or 10.0.1 ?

**Comment by jcastang** [comment]
From 10.0.1 for me.

**Comment by PVince81** [comment]
Did you try shift+F5 to clear the cache, in case there was some old code or styles still cached ?

Will try locally

**Comment by jcastang** [comment]
> Did you try shift+F5 to clear the cache, in case there was some old code or styles still cached ?
> 
> Will try locally

Yes.
I will try with private mode to start from clean browser.

**Comment by jcastang** [comment]
Is there a way to make a quick fix or shall we downgrade to 10.0.1 ?

**Comment by PVince81** [comment]
I'd suggest a downgrade if possible. Shouldn't be an issue as there was no DB changes as far as I can see.

**Comment by PVince81** [comment]
cause found: https://github.com/nextcloud/spreed/pull/4639

fix incoming...

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/spreed/pull/4640

**Comment by apg1980** [comment]
i am missing the src directory under my spreed folder.

**Comment by PVince81** [comment]
you are likely using the released version from the app store, which is compiled, so no way to apply patches there directly

**Comment by jcastang** [comment]
> you are likely using the released version from the app store, which is compiled, so no way to apply patches there directly

Hum... How canwe apply this on 10.0.2 ?
Because waiting for next minor just to have this change (one line) will make us downgrade (for one line).

**Comment by PVince81** [comment]
as soon as the fixes are merged (there's another one also), we'll build and release 10.0.3.

**Comment by jcastang** [comment]
Nice ! 👍

**Comment by PVince81** [comment]
10.0.3 has been released, you should be able to update now

**Comment by jcastang** [comment]
App is not available yet to update.
Maybe some cache there...

**Comment by nickvergessen** [comment]
Yeah, I think your nextcloud caches the appstore for up to 6 hours
