### ISSUE TITLE
Feature Request: able to share device ressource

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/spreed#4635]
It would be awesome if nextcloud talk allow the user to share different ressource of his device. I’m mainly thinking of sharing a sound card but it could be sharing a part of a screen,... like it is possible with zoom.

**Comment by nickvergessen** [comment]
You can do screenshares already (note you need this extension on chrom* https://chrome.google.com/webstore/detail/screensharing-for-nextclo/kepnpjhambipllfmgmbapncekcmabkol )
Sharing the sound card will not work until there is a desktop app ( #4381 ), because websites just can't do this.

**Comment by fancycode** [comment]
The Chrome `chooseDesktopMedia` API actually supports requesting audio:
https://developers.chrome.com/extensions/desktopCapture#method-chooseDesktopMedia

Haven't tested it yet, but it might be possible to share a window including sound.

**Comment by JOduMonT** [comment]
> desktop app ( #4381 ), because websites just can't do this

Thank for the explanation; that explain why Zoom install an apps on your desktop :)
