### ISSUE TITLE
Sound alarm on receiving new message - option: turn on/off etc.

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/spreed#4651]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...]  
I have an open talk/spreed window on my browser and I just miss new messages, because only a little visual indicator appears in case of new incoming message.  

**Describe the solution you'd like**
* Audio alarm: I would like to hear an audible alarm (chime or something) which could alarm me to check the new message.  
  * Options: 
    * replace the default alarm sound from file in nextcloud
    * different alarm sound for different chatrooms
    * mute/unmute alarm globally (permanently, 10mins, 1hour, 1day, 1week,  every day between 20:00-08:00 etc.)
    * mute/unmute alarm for each chatroom (permanently, 10mins, 1hour, 1day, 1week,  every day between 20:00-08:00 etc.)
* Visual popup notice if possible from the browser, similar to the notification of the nextcloud desktop client.
* Optionally the desktop client could show a notification when new message arrives into a chatroom the user subscribed.

**Additional context**
So, the point is to get immediately a strong notification to do not miss important messages from spreed.

* Please note: I do not speak about android clients, the desktop client is optional as not every user install desktop clients.

**Comment by nickvergessen** [comment]
> * Visual popup notice if possible from the browser, similar to the notification of the nextcloud desktop client.
> * Optionally the desktop client could show a notification when new message arrives into a chatroom the user subscribed.

You should already see popup notifications from the browser when you are mentioned in a non-active chat. For the currently active chat we are still unsure how to solve this in a good and still meaningful way: https://github.com/nextcloud/spreed/pull/1970
So what you are missing is to change the notification level to "All messages" in the left sidebar.
This would then also work for the desktop client.

As for audio alarm: it's on our todo to look into this once browsers are allowed to play sounds in background again without the need of user interaction. However I think we would start with sounds on calls then.

**Comment by pongraczi** [comment]
> You should already see popup notifications from the browser when you are mentioned in a non-active chat. For the currently active chat we are still unsure how to solve this in a good and still meaningful way: #1970
> So what you are missing is to change the notification level to "All messages" in the left sidebar.
> This would then also work for the desktop client.

Oh boy, I feel stupid, you are absolutely right, the popup notification is working well in case (notification set to **All messages** as you mentioned):
* the message received into an inactive chat and I have an other browser tab active (like I edit this message, while I got a new message to an inactive chat)
* the message received into an inactive chat and I have the nextcloud talk tab is active (like I just talking on an other chatroom)

Unfortunately I got no popup notification in the following case:
* the message received into an active chat and I have an other browser tab active (like I edit this message, while I got a new message to an opened chat)

So, the situation is much better than I thought but it would be nice to get a popup in case of the active-chat but other tab is active.  

> 
> As for audio alarm: it's on our todo to look into this once browsers are allowed to play sounds in background again without the need of user interaction. However I think we would start with sounds on calls then.

Ok, I don't know the limitations, I just compare the feature set to the browser based fb messenger client, which can ring a bell on incoming messages.  

I focus on that case, when users have no desktop clients installed, but try to use the nextcloud/talk instead of skype/messenger and get a notification like this.  
For example user put to "background" the browser based talk with an active chat room (let's call it helpdesk chatroom), even minimize that browser window with an open chat, but should get a strong visual/audio signal on incoming message. At this moment in this specific case it is easy to miss instant message.

**Comment by nickvergessen** [comment]
> For example user put to "background" the browser based talk with an active chat room (let's call it helpdesk chatroom), even minimize that browser window with an open chat, but should get a strong visual/audio signal on incoming message. At this moment in this specific case it is easy to miss instant message.

yeah that's a known limitation at the moment, see #1970 as a concept to improve it. we are still on it. Just didn't manage to make it useful at the moment.

**Comment by pongraczi** [comment]
Thanks, ok, waiting for the solution :)

**Comment by JMLatGitHub** [comment]
This kind of functionality is simply a must for a real-time communication application: There is nothing more annoying than to see that someone is actually available, but the communication attempt does not work because the other person does not even notice the attempt. For me, this lack of functionality is a KO criterion regarding the everyday usability of this application.

Now that Talk offers a lot of interesting features, implementing rock-solid, reliable notifications should be first priority IMHO.

**Comment by brendan-pike** [comment]
Related forum post of support and reasoning here https://help.nextcloud.com/t/desperate-need-for-improved-talk-notification/136028

**Comment by morgannunan** [comment]
@marcoambrosini this is not completed. [See my comment](https://github.com/nextcloud/notifications/pull/1169#issuecomment-1647110016).
