### ISSUE TITLE
Talk 10.0.3 Duplicate Participants

### ISSUE THREAD

**Issue by axheli** [nextcloud/spreed#4655]
## Steps to reproduce
1. Create Group Meeting
2. Have everyone join
3.

### Expected behaviour
Should not see duplicates Participants

### Actual behaviour
duplicates Participants showing 

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
10.0.3
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
NO
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
turn.axtsolutions.com:443
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
stun.nextcloud.com:443

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Windows 10
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 50.1/55/...
Version 86.0.4240.198 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/59488153/99708427-6d5ef280-2a63-11eb-855b-bc24786a90c1.png)

**Comment by axheli** [comment]
Here's another picture 
![image](https://user-images.githubusercontent.com/59488153/99724909-f4b76080-2a79-11eb-95ca-6c68bd8eade7.png)

**Comment by nickvergessen** [comment]
That is the promoted speaker, that is they it has this grey placeholder with the speaker icon on it.

**Comment by axheli** [comment]
> That is the promoted speaker, that is they it has this grey placeholder with the speaker icon on it.

Do you see that the user is on there 3 times?!

**Comment by nickvergessen** [comment]
Yeah, but with a loading spinner which makes me assume it's a session that is about to time out and then it will be gone.

**Comment by axheli** [comment]
> Yeah, but with a loading spinner which makes me assume it's a session that is about to time out and then it will be gone.

I agree with you very much on that but it dose not go away!

**Comment by Ivansss** [comment]
Might you be trying to connect to the call with another device? With a mobile app for example?
Because that could cause that issue.

**Comment by axheli** [comment]
> Might you be trying to connect to the call with another device? With a mobile app for example?
> Because that could cause that issue.

I looked at my turn server connections and i did not see duplicates. When i left the call and re joined it went away but it happens offten. Though id bring it up and maybe we can look into that.
