### ISSUE TITLE
Media controls are misplaced from the video in the sidebar

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#4668]
From https://github.com/nextcloud/spreed/pull/4363#issuecomment-713487495

Since #4363 when the call view is shown in the sidebar the media controls are a bit off from the video (tested with current master).

**Before:**
![Files-Sidebar-Controls-Before](https://user-images.githubusercontent.com/26858233/96711039-37175000-139d-11eb-80f4-ed2349953f8b.png)

**After:**
![Files-Sidebar-Controls-After](https://user-images.githubusercontent.com/26858233/96711044-38487d00-139d-11eb-9181-5d1b3d99be74.png)

## Steps to reproduce
- Open the Files app
- Share a file
- Reload (to workaround the bug of `FileInfo` not being updated when a file is shared)
- Open the sidebar for the shared file
- Open the Chat tab
- Join the conversation
- Start a call

**Comment by PVince81** [comment]
so the controls are off only because they were assuming a specific local video size.

it seems that in sidebar mode the local video is smaller, so need to adjust the width of the control container

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/spreed/pull/4696
