### ISSUE TITLE
Follow up for SIP changes

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4677]
## Remaining steps:
- [x] Add back indexes for the queries
- [x] Add capability when sip can be enabled by the participant for mobile clients
- [x] Add docs
- [ ] Add integration tests (if possible)

**Comment by PVince81** [comment]
- [ ] also generate PIN, etc when the attendee is already in the room

### Steps:
1. create a room as admin / modeator
2. enable SIP
3. check the settings tab and browser console

### Expected
No errors and attendee PIN visible

### Actual
<img width="534" alt="image" src="https://user-images.githubusercontent.com/277525/100460852-32466a00-30c8-11eb-85fb-03e6d4f74456.png">

**Comment by PVince81** [comment]
- [ ] guests should no see the dial-in info panel

**Comment by nickvergessen** [comment]
- [ ] Invite 2 emails:

```
 [Vue warn]: Duplicate keys detected: 's#0'. This may cause an update error.

found in

---> <ParticipantsList> at src/components/RightSidebar/Participants/ParticipantsList/ParticipantsList.vue
       <CurrentParticipants> at src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue
         <ParticipantsTab> at src/components/RightSidebar/Participants/ParticipantsTab.vue
           <AppSidebarTab>
             <AppSidebarTabs>
               <AppSidebar>
                 <RightSidebar> at src/components/RightSidebar/RightSidebar.vue
                   <Content>
                     <App> at src/App.vue
                       <Root> vue.runtime.esm.js:619

​
```

**Comment by nickvergessen** [comment]
- [ ] Creating a new conversation responds without the data (as the participant is not loaded correctly it seems)

**Comment by nickvergessen** [comment]
- [ ] Users that are already in the room need to rejoin as well to get a PIN
