### ISSUE TITLE
Add missing primary keys

### ISSUE THREAD

**Issue by acsfer** [nextcloud/spreed#4679]
As I'm running a MariaDB cluster, migrate to 20.0.2 was expected to fix some (Galera) clustering issues with primary keys on tables. Perhaps, some tables still missing primary keys.

## Steps to reproduce
1. Run `occ db:add-missing-primary-keys`

_(i don't know if it should fix all primary keys issues or only _server_ ones...)_

### Expected behaviour
All missing primary keys should be added

### Actual behaviour
Following tables don't have primary key:
```
oc_talk_participants
oc_talk_signaling
```
Upgrade from 19.0.5 to 20.0.2

**Comment by nickvergessen** [comment]
Yeah, the command was only added quite recently and we didn't have time to adjust yet.
Also the participants table is about to be replaced and in the new tables there is a PK already.

For the signaling table you can just add a autoincrement column yourself for now.

**Comment by PVince81** [comment]
@nickvergessen fixed by https://github.com/nextcloud/spreed/pull/4735 or is there more missing ?

**Comment by nickvergessen** [comment]
No, thats all I guess
