### ISSUE TITLE
Allow to resend email invitation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4681]
This could especially be useful when SIP is enabled and the users where added before so their invite did not contain the PIN and dial-in information yet.

**Comment by sudwhiwdh** [comment]
you mean possible for all invited participants, don't you? including users of the guest app or people who have been invited externally via email.

**Comment by nickvergessen** [comment]
I mostly ment email invited guests, as logged in users will not get emails anyway

**Comment by sudwhiwdh** [comment]
except if the registered users are not logged in and have set an email notification preference for Talk actions, right?

**Comment by nickvergessen** [comment]
Well that's handled in activity/notifications and not talk.

**Comment by PVince81** [comment]
Possible ideas for this implementation:

1. When SIP gets enabled, automatically resend all email invitations
or
2. Same as 1 but prompt before sending
or
3. Have a button below the SIP checkbox called "Resend email invitations" that can be clicked any time
or
4. Have the option to resend emails for each participant individually. This could be tedious. 

Probably 3 is best.

**Comment by nickvergessen** [comment]
mostlikely 3 as a one-time thing?
Also could see an action in the ... menu of the participant list to resend manually individual emails

**Comment by PVince81** [comment]
Draft PR here: https://github.com/nextcloud/spreed/pull/5052

**Comment by PVince81** [comment]
PR was merged, closing
