### ISSUE TITLE
stopFollowingLabel is not defined

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4688]
## Steps to reproduce
1. Start a call with 2 users
2. Click on a video to follow it
3. Back button is very small and hidden

### Expected behaviour
Button is visible and clickable

### Actual behaviour
Button is behind controls:

![Bildschirmfoto von 2020-11-27 16-33-17](https://user-images.githubusercontent.com/213943/100464671-5016cd80-30ce-11eb-920a-75cf512dff97.png)

Also there is a console error:
```
Property or method "stopFollowingLabel" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <LocalVideo> at src/components/CallView/shared/LocalVideo.vue
       <CallView> at src/components/CallView/CallView.vue
         <MainView> at src/views/MainView.vue
           <AppContent>
             <Content>
               <App> at src/App.vue
                 <Root>
```

**Comment by PVince81** [comment]
indeed... maybe it got eaten by some conflict resolution.

I'll look into it.

**Comment by PVince81** [comment]
This PR fixes it: https://github.com/nextcloud/spreed/pull/4700
