### ISSUE TITLE
No use of spreed if user has Video but no Audio(microphone)

### ISSUE THREAD

**Issue by bergart** [nextcloud/spreed#470]
## Steps to reproduce
Open spreed if you have both video and audio, just **block** the use of the microphone out of your browser.

![selection_036](https://user-images.githubusercontent.com/22152652/32619362-cc3d1ec2-c57a-11e7-84a4-b5eb11eedaa9.png)

### Expected behaviour
At least the video function should be visible

### Actual behaviour
 
![selection_035](https://user-images.githubusercontent.com/22152652/32619348-c3363f8e-c57a-11e7-921f-ae6ccd8dc10c.png)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Chromium

**Browser version:** 62.0.3202.62

### Browser log

```
Insert your browser log here, this could for example include:
Access to microphone & camera failed {name: "NotAllowedError", message: "", constraint: undefined, toString: ƒ}
```

</details>

## Spreed app

**Spreed app version:** 2.1.7

**Comment by nickvergessen** [comment]
Yeah, currently audio is required. Not sure if functionality can be done without microphone?
cc @Ivansss

**Comment by fancycode** [comment]
Joining a call should be possible with either audio and/or video, and ideally also without any device as listener only.

**Comment by nickvergessen** [comment]
We'll deal with it in #512
