### ISSUE TITLE
automatically unfurl / preview / inline media when chat message includes a link

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/spreed#4705]
When I post a link to media that can be previewed (either it is publicly accessible or chat participants have access to it), it would be great to be able to optionally unfurl / preview / inline the linked-to media.

For example, if I paste in a chat "test 123 http://example.com/test.jpg" and if test.jpg is a valid JPEG image, it could be automatically previewed right in the chat. Similarly for internal Nextcloud file links and other linked-to media.

**Comment by PVince81** [comment]
duplicate of https://github.com/nextcloud/spreed/issues/3156

**Comment by meonkeys** [comment]
Ah, thank you! I didn't find that dup when I searched earlier. I'll add my thumbs up there.
