### ISSUE TITLE
Avatar menu not appearing any more

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4718]
## Steps to reproduce
1. Have a conversation with two members
2. Let both post messages
3. Click on the three dots either on the avatar in the messages list or in the participant list

### Expected behaviour
Avatar menu appears

### Actual behaviour
No menu appears after clicking, nothing happens.

## Talk app

**Talk app version:** 11.0.x git master e1f553a6f78f6f5cac1bdd620aa1330782b0eb69

On 10.0.0 the menu works fine and shows "Talk to X" where X is the participant name.

Wondering if it is related to https://github.com/nextcloud/server/issues/23872 or similar changes in nextcloud-vue.

@ma12-co

**Comment by nickvergessen** [comment]
Seems to be broken everywhere.
All hail to the vue-lib update?

**Comment by PVince81** [comment]
Caused by the accessibility change to make the event handler conditional. Apparently I didn't test properly :facepalm: 

Fix is here: https://github.com/nextcloud/nextcloud-vue/pull/1639

**Comment by PVince81** [comment]
- [ ] release the fix
- [ ] update nextcloud-vue after the fix is released

**Comment by PVince81** [comment]
update PR for nextcloud-vue is here: https://github.com/nextcloud/spreed/pull/4767
