### ISSUE TITLE
XHR errors in Talk app on Firefox 83

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/spreed#4724]
## Steps to reproduce
1. Call https://my.nextcloud/apps/spreed/

### Expected behaviour
No errors

### Actual behaviour
Firefox shows the error (Access forbidden CSRF check failed) on urls in this format:
https://my.domain/ocs/v2.php/apps/user_status/api/v1/statuses/my.user

These are  shown as XHR errors (404) in the Firefox console when visiting the talk app.

Firefox Version 83
NC 20.0.2
Talk: 10.0.3

![2020-12-08_21-44-nc-xhr](https://user-images.githubusercontent.com/8102905/101540455-547d9900-39a0-11eb-82f6-e0c737822c75.png)

**Comment by nickvergessen** [comment]
This is not an error.
We have to make the request in order to know if the user has a status at all.

**Comment by PVince81** [comment]
> This is not an error.
> We have to make the request in order to know if the user has a status at all.

Good to know, I was always wondering about this.

It seemed to happen for users who had not logged in at all.
Does it also happen for user who cleared their status ? If yes, I wonder why then it's not simply returning an empty string instead of 404.

**Comment by nickvergessen** [comment]
Yes happens too. 404 means not found. they dont have a status if it was removed or was cleared in the background job, so that's a 404. sounds pretty okay APIwise.
It's just wrong from firefox to highlight the 404 that much `¯\_(ツ)_/¯`
