### ISSUE TITLE
3-dot-menu of conversation list hovers centered -> out of visible range

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#4725]
## Steps to reproduce
1. Open NC talk 
2. In menu on the left, where all ongoing talks are shown, click on the 3-dot-menu 
3. See only half of the list. Other half is hidden behind edge of browser window

### Expected behaviour
The position of the list should be adjusted dynamically to the browser window.

### Actual behaviour
The list shows up centered. It is not visible completely as it reaches out of visible range to the left.
![3dot-menu](https://user-images.githubusercontent.com/42836313/101551262-10df5b00-39b1-11eb-8db3-5c21e79f5abc.png)

## Talk app

**Talk app version:** 9.0.6

## Browser

**Operating system:** Windows 10 x64

**Browser name:** Firefox 83.0

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**PHP version:** 7.4

**Nextcloud Version:** 19.0.5

**Comment by nickvergessen** [comment]
Fixed in Nextcloud 20 or 21, don't remember exactly
