### ISSUE TITLE
Join/Leave button updates too slowly

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#473]
In the CallInfoView there is the `Join call` aka. `Leave call` button.
Currently this view is based on the room model. So either we have to refresh the whole room list or allow to change the state from outside, so the update can update immediately and doesn't display a wrong state until the 10s interval for the room refresh is over again...

@danxuliu any clever idea how we could do this model-wise?

**Comment by danxuliu** [comment]
>  any clever idea how we could do this model-wise?

See #478 (not very clever, though, but it works :-P ).
