### ISSUE TITLE
Test failures on master related to attachment folder

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4736]
## Steps to reproduce
1. Checkout NC 21 master
2. Checkout spreed master
3. `cd tests/integration`
4. `./run.sh features/sharing/create.feature:8`

### Expected behaviour
No errors

### Actual behaviour
```
[Wed Dec  9 17:48:12 2020] 127.0.0.1:45004 [200]: GET /ocs/v1.php/apps/files_sharing/api/v1/shares/1
    And user "participant2" gets last share                                       # SharingContext::userGetsLastShare()
[Wed Dec  9 17:48:12 2020] 127.0.0.1:45004 Closing
    And share is returned with                                                    # SharingContext::shareIsReturnedWith()
      | uid_owner              | participant1              |
      | displayname_owner      | participant1-displayname  |                                                                           
      | path                   | /Talk/welcome.txt         |                                                                           
      | item_type              | file                      |                                                                           
      | mimetype               | text/plain                |                                                                           
      | storage_id             | shared::/Talk/welcome.txt |                                                                           
      | file_target            | /Talk/welcome.txt         |                                                                           
      | share_with             | own one-to-one room       |                                                                           
      | share_with_displayname | participant1-displayname  |                                                                           
      Field 'path' does not match
      Failed asserting that two strings are equal.                                                                                     
      --- Expected                                                                                                                     
      +++ Actual                                                                                                                       
      @@ @@                                                                                                                            
      -'/Talk/welcome.txt'                                                                                                             
      +'/welcome (2).txt'
```

### Versions
NC 21 git master c8e0f3015f9c9d2f5c0b10ab7c13dd8e89cc87ff
Talk app git master b9b76ff9a7fdf880477d06bf85a5d8d102fef11f

**Comment by PVince81** [comment]
I tried going back in time to a moment where CI was green, like the commit from https://github.com/nextcloud/spreed/pull/4712 which is ec8f3cf8d4c85b074c1110f8c31765e0aa79e7a1

It still fails, so it's probably a server side change.

**Comment by PVince81** [comment]
seems it was already failing on https://drone.nextcloud.com/nextcloud/spreed/1 and I can't go back further in Drone history

**Comment by PVince81** [comment]
I went as far back as the time we built 10.0.3 which is last month with 3f0f8efaaee6e84d6b8fd04bc97c21a6f7a60ec1, and here the tests also fail.

Now trying to go back in time on the server...

**Comment by PVince81** [comment]
I went as far back as beginning of November on the server side: 2b2af705f7ea79b491d26068d9e96198656486aa

The same error happens on my local environment, and I did reset everything before testing.

The error itself looks like the attachment folder is either not configured or not defaulting to "/Talk".

**Comment by PVince81** [comment]
Okay, I found a working combination in the past:
- server f7e17060226570c875ab039784a55b4178748313
- talk ceef9fce1118d4f1b3388520a1426dc1dd08df13

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/23820#issuecomment-733140929

**Comment by PVince81** [comment]
Ok, thanks. Bisecting two repos at the same time is not fun :-S

Seems our SharingContext is using v1.php, should be an easy fix... on it

**Comment by PVince81** [comment]
However it means that if other apps or code is using v1.php to create shares, the behavior will not be correct, so might still need a server side fix... or kill v1.php altogether :see_no_evil:

**Comment by PVince81** [comment]
hmm, damn, v2.php is simply requiring v1.php... so it won't work without a server fix

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/server/pull/24606

**Comment by nickvergessen** [comment]
No, it's there https://github.com/nextcloud/server/pull/24628

🤣
