### ISSUE TITLE
Emojis not working; Seemingly not related to MySQL or PHP!

### ISSUE THREAD

**Issue by simpledissection** [nextcloud/spreed#4744]
Hello,

## Steps to reproduce

1)  Follow the Nextcloud docs guide to enable emoji's with Nextcloud for use with Talk, etc.

      https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

2)  Confirm all steps have been completed successfully.

3)  Investigate to confirm if PHP or MySQL are functioning properly:
**It seems there is not a problem with the MySQL database and there is not a problem with PHP.**  Why do I assume this?  If I insert an emoji directly into the database, it works perfectly fine; phpMyAdmin, which is written in PHP, has no trouble resolving the data to display it in the browser, and MySQL has no problem storing it.  However, sending the emoji to the database by sending a message through the Talk interface causes "????" to be inserted into the database; retrieving the emoji I directly inserted from the database causes "?" to be displayed.  (See image linked below)

![image](https://user-images.githubusercontent.com/8690712/101850803-7f92f480-3b28-11eb-8c9d-4325e9bf9447.png)

It seems there may be something going on in the NextCloud or Talk code that is causing this.  If it somehow is still an issue with PHP or MySQL, why do emoji's work when used independently from NexCloud? 

### Expected behaviour
The Talk app for Android as well as the web app should display emoji's correctly and also insert them into the database correctly.

### Actual behaviour
Both the Talk Android app and the web interface submit emojis into and retrieve them from the MySQL database such that they are stored in the database as "????" and/or retrieved as "?"

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu

**Browser name:** Firefox

**Browser version:** `83`

## Talk app

**Talk app version:** 10.0.3

**Custom TURN server configured:** no

**Custom STUN server configured:** no (stun.nextcloud.com:443)

## Server configuration

**Operating system**:  Cloudlinux 7.9

**Web server:** Litespeed 5.4.11

**Database:** MySQL 5.7.32-cll-lve

**PHP version:** 7.3.23 (Have also tested with 7.4)

**Nextcloud Version:** 20.02

**List of activated apps:**
<details>

  - accessibility: 1.6.0
  - activity: 2.13.3
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - registration: 0.5.2
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0

</details>

**Nextcloud configuration:**

<details>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.ezbx.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "http:\/\/cloud.ezbx.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mysql.utf8mb4": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.13.3",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "304"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1606721886.1373",
            "lastcron": "1607650022",
            "lastupdateResult": "[]",
            "lastupdatedat": "1607584984",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_default_expire_date": "no",
            "shareapi_enforce_expire_date": "yes",
            "theming.variables": "f4d4cc181488479382aebbabd3e743b1",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "no",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.16.1",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "lookupServerEnabled": "no",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "8.2.0",
            "types": "filesystem,dav"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "news": {
            "autoPurgeCount": "200",
            "autoPurgeMinimumInterval": "60",
            "enabled": "no",
            "exploreUrl": "",
            "feedFetcherTimeout": "60",
            "installed_version": "15.1.0",
            "maxRedirects": "10",
            "types": "",
            "updateInterval": "3600",
            "useCronUpdates": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "no",
            "installed_version": "6.1.0",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.10.1",
            "minLength": "12",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "readableLocation": "us",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": ""
        },
        "registration": {
            "admin_approval_required": "no",
            "allowed_domains": "ezbx.net",
            "disable_email_verification": "no",
            "domains_is_blocklist": "no",
            "email_is_login": "yes",
            "enabled": "yes",
            "installed_version": "0.5.2",
            "show_domains": "no",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "10.0.3",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "25",
            "color": "#21A3C4",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.11.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "EZBX",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": "filesystem"
        }
    }
}

</details>

**Comment by PVince81** [comment]
this was also reported here https://github.com/nextcloud/spreed/issues/4463 with a potential issue found: https://github.com/nextcloud/spreed/issues/4463#issuecomment-739431146

**Comment by nickvergessen** [comment]
Can you post a picture of your table structure, just to be sure

**Comment by simpledissection** [comment]
> 
> 
> Can you post a picture of your table structure, just to be sure

Here you go!

![image](https://user-images.githubusercontent.com/8690712/101920837-48f5c200-3b9a-11eb-8b09-2cd7437772ff.png)

**Comment by nickvergessen** [comment]
Please update to the latest version

**Comment by simpledissection** [comment]
> 
> 
> Please update to the latest version

Somehow, just clicking the update button seems to have jacked up my entire NextCloud instance.  Now what?
![image](https://user-images.githubusercontent.com/8690712/102674218-43cce000-4163-11eb-8a09-8e1c0e37cf1c.png)

**Comment by simpledissection** [comment]
> 
> 
> Please update to the latest version

Okay, I have successfully updated to the latest version but the issue is not resolved.  I still am not seeing emojis showing correctly in my instance.

**Comment by hardwareadictos** [comment]
> > Please update to the latest version
> 
> Okay, I have successfully updated to the latest version but the issue is not resolved. I still am not seeing emojis showing correctly in my instance.

Me also..... I'm on latest version and my emojis aren't working on Nextcloud app and Android app, Nextcloud 20.0.3, emojis showing up as "????".

**Comment by simpledissection** [comment]
Why was this closed?  It is still not working.

**Comment by osm-frasch** [comment]
Same issue here.
Nextcloud: 20.0.6
Talk 10.0.5
mysql Version: 10.4.12 
PHP Version: 7.3.16

I also can't understand why you can't just turn off the emoji feature. It's embarrassing to carry around a bug for so long. Sure, it's nothing important and there are definitely more important things!!!. But everyone wants to use emojis.  I have 200 users in our education center and they are constantly asking why it doesn't work. The best thing to do is to deactivate the "feature" and add it back in the next version NC21 or 22. Please excuse me that I let off steam here

**Comment by nickvergessen** [comment]
@osm-frasch so the thing is emojis work for like 99.99% of servers. Not sure what's different wrong on your instance.
Can you post the `php-intl` version you have installed?

**Comment by osm-frasch** [comment]
Hello nickvergessen, thanks you for your reply. The PhP Version isnsalled on our  instance is: Version: 7.3.16

**Comment by nickvergessen** [comment]
```
$ LANG=C apt list | grep install | grep intl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

intltool-debian/focal,focal,now 0.35.0+20060710.5 all [installed,automatic]
php7.2-intl/focal,now 7.2.34-10+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
php7.3-intl/focal,now 7.3.27-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
php7.4-intl/focal,now 7.4.15-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
php8.0-intl/focal,now 8.0.2-1+ubuntu20.04.1+deb.sury.org+1 amd64 [installed]
```

**Comment by osm-frasch** [comment]
Sorry, I just noticed that the emojis are displayed in Chrome (last version). My hoster has configured everything correctly. 

It is due to my own Firefox (Vers. 85, Linux Opensuse) setting. 

I can select emojis, click on them, but in the input mask in the chat I don't see any emoji, only a blank space, and when I press send I don't see any emoji in the chat history. But all the other chat participants see the emoji I sent. Also participants with Firefox, but on Windows machines. 

So it's definitely not a bug, but a result of my settings or a bug in the Firefox Linux version.

**Comment by nickvergessen** [comment]
I use Firefox on Ubuntu and it works fine since the beginning. Maybe your Emoji font is broken or not loaded correctly.

**Comment by osm-frasch** [comment]
Problem solved. I had probably installed additional "noto-coloremoji-fonts" on my system some time ago. 
Something must have got tangled up here. 
I had also found the note on Opensuse "...to install multiple emoji fonts and it may cause problems. "

So very clearly not a bug! ;-)

Thank you for your answer.
