### ISSUE TITLE
Nextcloud talk opens instead of showing two factor page

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/spreed#4751]
## Steps to reproduce
0. Use a nextcloud instance with 2FA enabled
1. Open the link for nextcloud talk by navigating to "yourcloud.de/apps/spreed/"
2. you should see a login window
3. Enter the correct username and password, click login so that nextcloud asks for the second factor
4. Now open a new tab and navigate to the link "yourcloud.de/apps/spreed/" again. 

### Expected behaviour
Navigating to every other app opens the page where nextcloud asks for the second factor. 

![Clipboarder 2020 12 12-003](https://user-images.githubusercontent.com/39341393/101981897-74e37700-3c70-11eb-8a9e-cbc457110f3f.png)

### Actual behaviour
Nextcloud talk opens but is empty.

![Clipboarder 2020 12 12-002](https://user-images.githubusercontent.com/39341393/101981900-7876fe00-3c70-11eb-997c-4bbe68764bda.png)

If the login in the first tab is cancelled, nextcloud talk in the second tab redirects to the login page again.

## Browser

**Browser name:** Firefox

**Browser version:** 83

## Talk app

**Talk app version:** 10.0.3

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Nextcloud Version:** 20.0.3

**List of relevant apps:** 

Talk
Two Factor e-mail provider 
Two-Factor Authentication via Nextcloud notification 
Two-Factor TOTP Provider

**Comment by nickvergessen** [comment]
Well the talk page does not require authentication as you can also be part of a call as a non-logged-in guest, which is why it loads.
But the APIs don't return any authenticated data when the loggin is not finished, so all fine.
