### ISSUE TITLE
Disable picture in picture for own local video

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4754]
## Steps to reproduce
1. On Talk master
2. Start a call with another participant
3. Hover on own local video

### Expected behaviour
No picture in picture offer as it doesn't make much sense to watch self. (makes more sense for the presenter video)

### Actual behaviour
Mirrored picture in picture button
<img width="265" alt="image" src="https://user-images.githubusercontent.com/277525/102074465-21eef880-3e05-11eb-90d0-a20665085045.png">

## Versions

**Talk app version:** git master

**Browser:** Firefox 83.0

I heard discussions somewhere about the mirroring. Until this is resolved I suggest to try disabling this completly, if possible.

**Comment by nickvergessen** [comment]
Well from my pov we should disable all PiP apart from the the promoted windows, see #4674

**Comment by PVince81** [comment]
let me try this... the mirror thing looks too ugly

**Comment by PVince81** [comment]
https://www.w3.org/TR/picture-in-picture/#disable-pip

**Comment by PVince81** [comment]
doesn't seem to work, maybe Firefox (tested with 83.0) is not up to date yet with that spec:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/277525/102339728-e20b4b00-3f95-11eb-97fd-1c35b601246b.png">

and a closed ticket from Mozilla as won't fix https://bugzilla.mozilla.org/show_bug.cgi?id=1611831 :open_mouth: 

let me check chromium...

**Comment by PVince81** [comment]
in Chromium 87.0.4280.88 the picture in picture option is more hidden, need to right click on the video

when setting the attribute above the menu entry appears grayed out

so might still be worth adding and hope Firefox will reconsider adding it later...

but: this would not fix the flipped overlay issue which is the most annoying thing

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4772
