### ISSUE TITLE
Keeping user action menu open can cause accidental removal of participant

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4758]
## Steps to reproduce
1. Open the right sidebar of any conversation
2. You want to promote all of the people to moderator
3. When you promote the first and then quickly want to promote the second one, it results in removal of the first cause that participant’s menu is still open

### Expected behaviour
The menu should close when you pick one of the actions of promote/demote in the actions menu.

### Actual behaviour
The menu does not close and the participant moves up on promotion to moderation, leading to the menu entry "Remove participant" now being where you would click to open the menu of the next participant. See:
![Accidental removal of participant](https://user-images.githubusercontent.com/925062/102097973-e1a07200-3e26-11eb-8689-b2a42d3005d4.gif)

-----

Happens with latest master, regardless of browser.

**Comment by PVince81** [comment]
likely missing the option "close on click" or something

**Comment by nickvergessen** [comment]
`:close-after-click="true"` in src/components/RightSidebar/Participants/ParticipantsList/Participant/Participant.vue inside the `<Actions` component.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4765
