### ISSUE TITLE
Conversation list should not be collapsed when no conversation is selected

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#4766]
**Is your feature request related to a problem? Please describe.**
The conversation list is collapsed when the windows width is below 1024px. This makes sense when you're actually in a conversation, but not, when you need to select or start a new conversation.

**Describe the solution you'd like**
Only collapse the conversation menu when actually in a conversation.

**Additional context**
![image](https://user-images.githubusercontent.com/1580193/102273431-99ff1080-3f22-11eb-94a2-05616ed79ce5.png)

**Comment by nickvergessen** [comment]
The sidebar is so difficult in it's handling. But yeah totally makes sense

**Comment by nickvergessen** [comment]
Actually a duplicate of #1937
