### ISSUE TITLE
Listable rooms UX improvements

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4773]
Result of design call with @jancborchardt, @juliushaertl, @Clementine46 and @nickvergessen 
What do you think @PVince81? did we miss anything?

![Screenshot from 2020-12-16 12-31-56](https://user-images.githubusercontent.com/26852655/102343342-b5a5fd80-3f9a-11eb-95fa-65513b756438.png)

**Comment by PVince81** [comment]
yeah, looks fine to me

what about the status messages ? whenever you change an option there's a notification that confirms the change and also a system message in the chat for everyone to see the change.

should it stay the same ?

**Comment by nickvergessen** [comment]
System message should say accessible aswell
The toast notification is not needed from my pov as the chat shows the system message immediately

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4771
