### ISSUE TITLE
After a guest "Leave call"s out of a call the screen stays on call mode

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#479]
## Steps to reproduce
0. As logged in user create a public room and join the call
1. As a guest join a call
2. As guest click "Leave call"

### Expected behaviour
Should go back to some okay-ish screen

### Actual behaviour
Call screen stays

---

👷  ~~Also this reminds me, that we should fix the messages on that screen, because you might not be waiting for the other person, because that one actually is already in the call, just you are missing.~~ => #502

**Comment by Ivansss** [comment]
I think this happens with every user, not only guests.
We should fix leaveCall() function.
Maybe we should leave & join the room when leaving the call, then participants will get a new sessionId.

**Comment by nickvergessen** [comment]
It works fine here for logged in users.
But I will have a look once im done with teh notifications.

**Comment by nickvergessen** [comment]
> Maybe we should leave & join the room when leaving the call, then participants will get a new sessionId.

That would kill commenting for guests a bit, since they are not linked to their comments anymore. Also joining a room requires the password to be put in.

**Comment by nickvergessen** [comment]
This seems to work now. it correctly goes back to "Waiting for others to join the call …"
