### ISSUE TITLE
Add groupname and description to the chat view

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#4816]
Add it in the yellow area:
![grafik](https://user-images.githubusercontent.com/24530680/102722888-782bd200-4304-11eb-832b-d9f8d8d9b051.png)

see: https://github.com/nextcloud/spreed/pull/4546#issuecomment-748612056

**Comment by nickvergessen** [comment]
Hmm I think it would be okay, but when there is a call or the mobile view it should be hidden.

Cc @jancborchardt

**Comment by nickvergessen** [comment]
Done since #5596
