### ISSUE TITLE
Talk 11 alpha 2: See other participants when I share my screen

### ISSUE THREAD

**Issue by framarini02** [nextcloud/spreed#4817]
when I share the screen, it is not possible to see the screen also other participants as in Talk 10.

**Comment by PVince81** [comment]
@framarini02 you should be able to: see on the bottom right there's an icon to uncollapse the stripe

**Comment by framarini02** [comment]
2if I press that button I can only see me. Instead I would like to have the possibility to see other people in that black bar that is created.

**Comment by PVince81** [comment]
makes me think: maybe the first time the stripe automatically collapses we should show a tooltip there to inform users that they can bring it back

thoughts @ma12-co ?

**Comment by PVince81** [comment]
> 2if I press that button I can only see me. Instead I would like to have the possibility to see other people in that black bar that is created.

hmmm then it's a bug, you should be able to see everyone as you do when not sharing

**Comment by PVince81** [comment]
I've just tested and it works for me:
<img width="960" alt="Screenshot_20201221_110102" src="https://user-images.githubusercontent.com/277525/102764716-e2cc2480-437b-11eb-81e5-2d4b1c2f83d6.png">

(the colors are the videos from the test peers using Firefox fake streams)

I'm also able to switch to grid view to see other participants.

if you don't see anyone in the bottom bar, please fill the issue template and report logs, etc: https://raw.githubusercontent.com/nextcloud/spreed/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by framarini02** [comment]
Checking the problem I notice that if we are only two participants I can see only myself in the bar below the sharing. On the other hand, if we are three or more participants, I can see the others under the screen sharing.

**Comment by PVince81** [comment]
might be similar to https://github.com/nextcloud/spreed/issues/4051

**Comment by PVince81** [comment]
okay, I just compared these but they are not the same.

so here the bug is that the bottom stripe is not showing any participants if there would be only a single one there. it only starts showing starting with 2...

**Comment by PVince81** [comment]
From what I see the logic is fine when no screen shares are involved, the stripe is hidden when less than two participants are present: https://github.com/nextcloud/spreed/blob/master/src/components/CallView/Grid/Grid.vue#L59

I tried changing it to "less than one" but then the user whose video is visible in the big screen is also visible in the stripe.

So one idea would be to keep the "less than two" logic but extend it with "unless there is a screen share in the top".

**Comment by PVince81** [comment]
PR here that fixes it: https://github.com/nextcloud/spreed/pull/4941

but comes with some ugly layout issues
