### ISSUE TITLE
Room settings: hide unnecessary options

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4824]
Tested with Talk  11.0.0-alpha.2

The room settings look like this:

![image](https://user-images.githubusercontent.com/1589737/102785104-b6290480-439d-11eb-85e2-3f5e96aabd24.png)

If no Guests are allowed the "set password..." label should be hidden 

The "copy public link" button should be hidden as well or renamed to "copy internal link" (or something similar) if we think it is still useful to copy the link for internal use.

**Comment by PVince81** [comment]
indeed, I thought that message was hidden already

For the button: good point. Now that we have listable/visible rooms, the link wouldn't be only for guests

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4840.
