### ISSUE TITLE
Talk not working when accessed from iOS/iPhone browser

### ISSUE THREAD

**Issue by virre131** [nextcloud/spreed#4826]
## Steps to reproduce
1. Create room
2. Allow guests
3. Go to share/room-link on ios/iphone device

### Expected behaviour
Should render the Talk interface just like other devices. 
Guest users on ios devices can't use the ios app.

### Actual behaviour
Nothing happens, just white un rendered page with Nextcloud header. 
No error message just plane white, no buttons or text.

https://imgur.com/a/gypGgtJ

## Talk app

**Talk app version:**  10.0.4

**Custom Signaling server configured:** n/a

**Custom TURN server configured:** No, NC-server and mobile device are on same LAN-network

**Custom STUN server configured:** No, NC-server and mobile device are on same LAN-network

## Browser

**Operating system:** iOS/iPhone

**Browser name:** Safari

**Browser version:** 14.0

### Browser log
n/a

## Server configuration

**Operating system**: Linux/qnap

**Web server:** Apache & Nginx

**Database:** Maria

**PHP version:** 7.3

**Nextcloud Version:** 20.0.3

**Nextcloud configuration:**

### Server log (data/nextcloud.log)
Issue generates no logs.

**Comment by socialize-IT** [comment]
maybe related #4813 ?

**Comment by nickvergessen** [comment]
Yes same issue
