### ISSUE TITLE
After Update to nc20 - Volume of 2 microphones too low to use Talk 

### ISSUE THREAD

**Issue by florom** [nextcloud/spreed#4828]
Hi Devs,
 
nextcloud 20.0.4
php 7.3
maria db
talk 10.0.4

We had conference with 4 participants without HPB.

I noticed that cause I used it in 19.0.latest and there was everything ok
for many sessions.

That's really a pity.

Sorry for not many infos I just wanted you to know.

Thanks

**Comment by glOOmyART** [comment]
you managed to get it activated in nc20?

after my update to nc20 the app ist deactivated with a warning that it's not compatible with nc20

**Comment by nickvergessen** [comment]
@glOOmyART you seem to have disabked the app store on your instance (judging from all your reports), otherwise the uodate to Nextcloud 20 would update all apps too.

**Comment by glOOmyART** [comment]
@nickvergessen don't know what happend, but i got logged out of my instance, logged back in and now all apps seem compatible...
gonna close all the other issues now

**Comment by nickvergessen** [comment]
So there is https://github.com/nextcloud/spreed/issues/3155 for individual volume control.
But currently the "sender" can change the mic volume in their operating system
