### ISSUE TITLE
Conversation description expand shadow looking bad in dark mode

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4830]
## Steps to reproduce
1. Go to accessibility settings and switch to dark mode
2. Have a channel with a longer description
3. See description in sidebar

### Expected behaviour
The shadow effect has correct transparency.

### Actual behaviour
The transparency doesn't seem compatible with dark mode, or is missing some opacity values.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/277525/102869783-6ea58580-443c-11eb-9dff-4081bbace786.png">

## Talk app

**Talk app version:** v11.0.0-alpha.2

Observed on the company instance.

@ma12-co FYI

**Comment by juliushaertl** [comment]
Might need some extra hack for Safari to get the gradient properly working with the main background color

https://github.com/nextcloud/deck/pull/2622/files#diff-69eda78a5bddd7bf9ecb685d4b869b26a5a181d9b32e6321adf168532d64711bR296-R299

**Comment by nickvergessen** [comment]
Fixed with #4880
