### ISSUE TITLE
Accept Chromium Based Browsers (Opera, Vivaldi, Iron, etc.) 

### ISSUE THREAD

**Issue by Galileon-venta** [nextcloud/spreed#4831]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Nextcloud Talk shows me this message:
![image](https://user-images.githubusercontent.com/48894231/102876035-f1324300-4444-11eb-9abb-412846347f47.png)

**Describe the solution you'd like**
Opera, etc. should be 100% compatible to all features which Chrome accept.

**Describe alternatives you've considered**
Using Chrome is not an alternative :D

**Comment by nickvergessen** [comment]
> Opera, etc. should be 100% compatible to all features which Chrome accept.

That's why you would assume, but seems to not be the case. Chromium works, but for all others the WebRTC adapters don't fully work, so we prefer the "better save than sorry" and warn people that their browser is causing issues.

**Comment by nickvergessen** [comment]
But we could add something like a "never show me this again" thing.

**Comment by nickvergessen** [comment]
Opera was added to the supported list with #4974
