### ISSUE TITLE
Bridging with MS Teams fails with improperly formatted message

### ISSUE THREAD

**Issue by bugzy** [nextcloud/spreed#4832]
## Steps to reproduce
1. Go to existing NCTalk conversation and select Settings
2. Configure MS Teams bridge under "Bridge with other services"
3. Select "Show matterbridge log" and follow instructions to login to MSTeams in separtate window

### Expected behaviour
Messages sent in NCTalk conversation are bridged over to MSTeams Channel

### Actual behaviour
Matterbridge crashes and goes into state "Enabled (not running)." Relevant log details are as follows:
`
time="2020-12-22T06:39:48-08:00" level=info msg="Running version 1.20.0 1a5353d7" prefix=main
time="2020-12-22T06:39:48-08:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2020-12-22T06:39:48-08:00" level=info msg="Starting bridge: msteams.0 " prefix=router
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ************ to authenticate.
time="2020-12-22T06:40:29-08:00" level=fatal msg="Starting gateway failed: Bridge msteams.0 failed to start: invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: e20dc17c-c612-4e20-9452-45824a7e3e00
Correlation ID: df72443c-6b97-483e-8a66-4db94ae34505
Timestamp: 2020-12-22 14:40:29Z" prefix=main`

Filed [here](https://github.com/nextcloud/talk_matterbridge/issues/24) also since I am not sure where it should go: 

## Talk app

**Talk app version:** 10.0.4

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Fedora 32

**Browser name:** Firefox

**Browser version:** 84.0

**Comment by bugzy** [comment]
Looks like this may be fixed in
https://github.com/nextcloud/spreed/pull/4745

**Comment by bugzy** [comment]
The situation is still the same on upgrade to talk_matterbridge 1.21.0
`time="2021-01-04T06:43:39-08:00" level=fatal msg="Starting gateway failed: Bridge msteams.0 failed to start: invalid_client: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 8fa3be5e-a5ee-42ed-9a9d-a0f215952400
Correlation ID: f8fbd0c2-d8c7-4b9c-a693-fde318d962f2
Timestamp: 2021-01-04 14:43:39Z" prefix=main`

**Comment by eneiluj** [comment]
I tried with Matterbridge v1.20.0 and v1.21.0 and it works fine on my side. According to the log you mention, there might be something wrong with the OAuth app you created on microsoft side or with the values you give.

Anyway, I don't think the problem comes from Matterbridge integration in Talk. It just generates a config file and launches the Matterbridge binary.

Did you try to run Matterbridge manually outside NC Talk? I'm pretty sure you won't be able to bridge something with MSTeams with the same credentials/OAuth app.

**Comment by bugzy** [comment]
@eneiluj Thanks so much for the response. I will look into the OAuth app created on the Microsoft side first and report back. If I am still running into issues, I will try manually running Matterbridge outside of NC Talk.

**Comment by bugzy** [comment]
@eneiluj Thanks for pointing me in the right direction. It looks like the issue was that I did not set the OAuth app on the Microsoft side to work as a public client. https://github.com/42wim/matterbridge/wiki/MS-Teams-setup#set-application-as-public-client

Once that got fixed. bridging worked as expected.
