### ISSUE TITLE
Add Conversation API version 3 in capabilities when available

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#4834]
The last one added to capabilities was conversation-v2 but conversation-v3 was never added.

**Comment by PVince81** [comment]
Seems this was added as description for the "sip-support" capability. It was probably from the time where v3 was assumed to be only for SIP support.

Meanwhile we also added more stuff in v3 like listable rooms.

So to me it makes sense to add another one. I'll send a PR.

**Comment by PVince81** [comment]
I've raised https://github.com/nextcloud/spreed/pull/4839 to add the "conversations-v3" capability.

However, I think clients should anyway rely on the specific feature capability.
Probing for "conversations-v3" doesn't guarantee that features like "listable-rooms" and "chat-read-status" exist.
