### ISSUE TITLE
Default guest name "null"

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4837]
I just noted that in Talk 11.0.0-alpha.2 a guest who joins a room has by default the display name "null"

![image](https://user-images.githubusercontent.com/1589737/102924857-a17a6880-4492-11eb-9722-3f5729f713c9.png)

Looks like a bug.

**Comment by PVince81** [comment]
Weird. I didn't observe this in a local test where it appeared as "Guest".

**Comment by schiessle** [comment]
Maybe it happens only in combination with the HPB?

**Comment by nickvergessen** [comment]
@rullzer did you update our HPB to the latest version?

**Comment by nickvergessen** [comment]
Fixed by #5109
