### ISSUE TITLE
Mute other participant, cannot unmute them.

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/spreed#4849]
## Steps to reproduce
1. Click microphone of other person, they get muted, can't click on it again to unmute

### Expected behaviour
For me to be able to unmute them without them having to rejoin the call

This is the web version of Talk btw with NC20

**Comment by socialize-IT** [comment]
Because of privacy reasons this is the desired behaviour. The other people should be able to unmute themselves. You can't unmute others so there is no chance to leak voices without the people knowing.

**Comment by nickvergessen** [comment]
Yeah see #4276
