### ISSUE TITLE
Should avatar be centered between author name and first message?

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#485]
Currently the avatar is centered on the author name, but I have noticed that other chat platforms (for example, [Rocket.Chat](https://rocket.chat/images/index/screenshot.png) or Slack) center the avatar between the author name and the first message. @jancborchardt Should we use that style too?

Obviously I have a branch ready to be pushed if this change is desired; do not worry implementing this, it is already done ;-)

**Current**:
![chat-avatar-current](https://user-images.githubusercontent.com/26858233/32893709-cc1b4e2c-cada-11e7-99f5-9906a05d70b7.png)

**Centered only in message list** (I would go with this one):
![chat-avatar-centered-list](https://user-images.githubusercontent.com/26858233/32893715-d4863a9a-cada-11e7-8434-91bf5b3c51f3.png)

**Centered in both message list and new message form** (personally I do not like this one):
![chat-avatar-centered-all](https://user-images.githubusercontent.com/26858233/32893727-de2d9dfe-cada-11e7-9f84-a27319154bae.png)

**Comment by nickvergessen** [comment]
It basically removes a bit of padding, right?

Fine by me

**Comment by jancborchardt** [comment]
Both Slack and Rocket.Chat use square avatars though, which make the centering between name & first message look significantly better. I have to say visually the current implementation still looks best.

What do you think @nextcloud/designers?

**Comment by danxuliu** [comment]
>  Both Slack and Rocket.Chat use square avatars though, which make the centering between name & first message look significantly better

That is exactly why I opened this as a question instead of directly as a pull request ;-)

Let's see what others have to say :-)

**Comment by MorrisJobke** [comment]
I like it how it is now.

**Comment by pixelipo** [comment]
No strong opinion about this, but to add my 2 cents, I would align top of the icon with the top of the name.

By the way, I think this is related to https://github.com/nextcloud/server/pull/7195 - both should follow same design, I guess

**Comment by jancborchardt** [comment]
@pixelipo the app content list already follows the same design when there is one row. However it's not really comparable as it's a list with specific height and line dividers, where visually the image of course should always be vertically centered.

**Comment by nickvergessen** [comment]
Closing since it seems to be the most chosen option
