### ISSUE TITLE
Personal muting of others

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/spreed#4850]
I would like to see the ability where I can mute/unmute other people, except only for myself, not for the whole room.

There are times where I am in a meeting with someone right beside me, as well as online, and I want to mute the person beside me so there's no echo, but not mute them for everyone else.

Can we please get this? :)

**Comment by socialize-IT** [comment]
Would be nice to set the volume for every participant on the client side. Volume put to zero would achieve what BloodyIron wants, while I would be able to balance different volumes of others.

**Comment by BloodyIron** [comment]
I'd totally love volume per-participant! And it be my side only (so I'm not adjusting it for others). And that would totally do the mute stuff too! Yay! \o/

**Comment by socialize-IT** [comment]
So this is a duplicate of #3155 i guess..

**Comment by BloodyIron** [comment]
Ooops, closing in favour of #3155
