### ISSUE TITLE
"Raise hand" layout improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4865]
Currently, for participants which raise their hand, their name gets centered. The name should still be left-aligned though and only move by the space the icon needs.
![image](https://user-images.githubusercontent.com/925062/103289940-b2722f00-49e8-11eb-833f-10e05166237c.png)

Similarly, on your own side, the icon just appears inbetween the icon row. This makes the icons jump and as a result the interface appears not solid. Instead, the "Raise hand" icon should show on the bottom left of your video, just like it does for others.
![image](https://user-images.githubusercontent.com/925062/103289981-c453d200-49e8-11eb-8eb4-bb20b4e018ab.png)

**Comment by nickvergessen** [comment]
Since the "muted" icon pops up at the right, maybe the raised hand could too? makes much more sense if all "info" icons are in the same position?

**Comment by brtptrs** [comment]
It would be great if the hand icon (bottom left) could be more prominent. Especially for participants with light backgrounds/clothing the icon is often overlooked.

**Comment by nickvergessen** [comment]
That's a generic issue with all the icons and the name, we are looking into a generic solution that would work for all the things.

**Comment by marcoambrosini** [comment]
Still relevant?

**Comment by nickvergessen** [comment]
I don't think so
