### ISSUE TITLE
Establish audio/video connection takes up to 10 secons

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#4871]
Tested with Browser <> Android and Android <> Android
It takes 2-4 secons to ring/show the new call
It takes 7-10 secons for estabishing the connection

Could the Establishment be accelerated?
Tested within the same enviroment with Whatsapp, Signal and Telegram:
2-3 to ring
**0-1 sec for estabishing**

**Comment by Happyfeet01** [comment]
How can i get it work with telegram or whatsapp?

**Comment by jakobroehrl** [comment]
It was a comparison not a work together

**Comment by nickvergessen** [comment]
It works quite fine here, it's just short of a second with video on after pressing the button.
