### ISSUE TITLE
Mail notification for new messeages

### ISSUE THREAD

**Issue by josaur** [nextcloud/spreed#4878]
**Is your feature request related to a problem? Please describe.**
Right now I'm using Nextcloud Talk for contributing in a Team. An problem right now that not all of them are looking for new messages that often. New messages will not be read by everyone.  

**Describe the solution you'd like**
My solution would be to add an option that new messages will  be forwarded per E-Mail. One option would be to aggregate all messages in a given interval to one mail or to send out a mail for every single message. 

**Describe alternatives you've considered**
An other option would be to realize this using a workaround with the talk->matrix bridge an an  an matrix->Mail bridge. But in absence of an own matrix-server I don't prefer this way.

**Comment by nickvergessen** [comment]
See #3076
