### ISSUE TITLE
Talk does not display attached PDFs (neither the link nor the icon)

### ISSUE THREAD

**Issue by user67x** [nextcloud/spreed#4879]
Hi!

In Nextcloud 20.0.4 it is impossible to view a PDF that has been uploaded or linked as a file for users that are identificated (no problem for anonymous visitor).

To reproduce the bug:

- create a conversation,
- upload a PDF,
- and there you can see that the PDF is not listed.

So you can't click on it to view it.

PDF viewer is activated. No problem with Talk for Android, the bug appear only on desktop.

**Comment by user67x** [comment]
Yes, the bug I'm talking about for the GUI web.

**Comment by Happyfeet01** [comment]
i have the same issue with pdf files, or other documents.
The Browserdebugger show this

![grafik](https://user-images.githubusercontent.com/3295104/103649782-5c106d80-4f5f-11eb-9f2f-392bcb3365ee.png)

**Comment by Happyfeet01** [comment]
The fix for me: disabling raw preview.

**Comment by user67x** [comment]
Indeed. A work around until a patch is released?

**Comment by nickvergessen** [comment]
What "Disabling raw preview" is this from collabora online?
It works fine here with files_pdfviewer and the viewer app enabled.
