### ISSUE TITLE
Avatar right in the face of the far side partner

### ISSUE THREAD

**Issue by beccon4** [nextcloud/spreed#488]
## Steps to reproduce
1. establish a call with a smaller screen (1280x800) with only two participants
2. see the avatar (or just the caller's name) right in the middle of the image
3. use a smaller screen (Lenovo 7" Tablet) and the problem is even worse

### Expected behaviour
The avatar should never cover the image. 

### Actual behaviour
The avatar or just the first letter of the caller's name appears in a rather large size right in the face of the person. It doesn't happen all the time - sometimes the avatar goes to the base line of the screen or disappears alltogether. If it appears there is no way to get rid of it.

## Browser
- Firefox 56
- Chromium

**Microphone available:** yes

**Camera available:** yes/

**Operating system:** /Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/56/...

**Comment by nickvergessen** [comment]
Can you post some screenshots? and also specify which version of the App and Nextcloud you are running?

**Comment by beccon4** [comment]
Yes of course  (although I'm having a bad hair day and for the lack of time to install a decent screenshot program i took a photo with the phone not so nice but it shows what happens)
![img_20171123_221110_dro](https://user-images.githubusercontent.com/12436716/33188758-98536f58-d09c-11e7-97c8-62919d8e3f4c.jpg)

My Spreed App Version is 
## 2.0.1 – 2017-05-22
Nextcloud is 
Nextcloud 12.0.3

The screen the photo is taken from has 1920x1080 resolution, running Chromium Browser Version 60.0.3112.89 (Entwickler-Build) Built on Ubuntu 14.04, full screen

On the other end I had both Firefox 56 and Chromium - resolution (1280x800) with no problem at all. I managed to reproduce the problem on the big screen a couple of times. It doesn's seem to occur when i share a link to include more participants.

**Comment by nickvergessen** [comment]
I think this should be solved with 13 already

**Comment by evilphish** [comment]
Since 13 is still in beta and not fit for deployment in production environments I think a fix for 12 would be more than welcome. Even if it is as simple as just disabling the offending div in the HTML template as losing the avatar is a small price to pay for actually being able to use the video conference feature.

**Comment by nickvergessen** [comment]
Of course but the issue I have is that it works for me.
I tested Nextcloud 12.0.4-RC2 and Spreed 2.0.1 and it worked quite fine for me:
> ![bildschirmfoto von 2017-11-27 16-28-47](https://user-images.githubusercontent.com/213943/33274389-3a8af48a-d390-11e7-9b5e-44202923f34b.png)

I inspected the HTML and the avatar placeholder is correctly hidden with `display: none;`

Maybe @Ivansss knows where the code which does this is located?
I couldn't find it.

**Comment by fancycode** [comment]
The publisher triggers the event in https://github.com/nextcloud/spreed/blob/04b9761fb9645f6e5d5475545b75dc553a85adf3/js/webrtc.js#L307

If for some reason the datachannel is not ready yet (either on publisher or receiver side), the event will be lost and the avatar will not be hidden.

As a workaround you can disable and re-enable your video when everything is connected to trigger showing and hiding the avatar again.

**Comment by evilphish** [comment]
@fancycode Curiously enough, disabling and re-enabling the video does not change anything over here. The avatar just reappears in the center of the video feed. 

@nickvergessen what browser and version are you using? I can reliably reproduce this with Firefox 57 on Linux and Windows OS. Will check with chrome later today.

**Comment by Ivansss** [comment]
As @fancycode said, this issue is related with datachannels.
This issue was fixed https://github.com/nextcloud/spreed/pull/335, but I just noticed that it was closed after the release of version 2.0.1.
We are going to release a new version 2.0.2 containing this fix soon.

**Comment by Ivansss** [comment]
We just released version 2.0.2.
Update should be available from the App Store in a few minutes.
