### ISSUE TITLE
New lines displayed as <div>line</div> when entered in Safari (iPadOS)

### ISSUE THREAD

**Issue by sebidotorg** [nextcloud/spreed#4891]
### Steps to reproduce
1. Open the Talk page in Safari (on iPadOS/iOS).
2. Open a chat with another user.
3. Enter a line of text (e.g. “First line.”), press ```<Shift>```+```<Return>```, enter a second line (e.g. “Second line.”), click ```send```.

### Expected behaviour
Message should be:
``` 
First line.
Second line.
```

### Actual behaviour
Message is:
```
First line.<div>Second line.</div>
```

## Server configuration detail

**Operating system:** Linux 5.10.4 #1 SMP Fri Jan 1 00:05:37 CET 2021 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.27

**PHP version:** 

7.4.11
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.4 - 20.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud stable branch since February 2018

**Where did you install Nextcloud from:** Tarball from official download page

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - audioplayer: 3.0.0
 - audioplayer_editor: 0.3.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - camerarawpreviews: 0.7.10
 - checksum: 1.0.1
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - documentserver_community: 0.1.8
 - emlviewer: 0.0.21
 - encryption: 2.8.1
 - epubreader: 1.4.5
 - extract: 1.3.0
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_antivirus: 3.1.1
 - files_external: 1.11.1
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.1
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.1.0
 - imageconverter: 1.3.1
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - metadata: 0.12.0
 - nextbackup: 20.9.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.2.0
 - password_policy: 1.10.1
 - photos: 1.2.1
 - polls: 1.6.2
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - rainloop: 7.0.3
 - ransomware_protection: 1.8.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 10.0.4
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.1.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - user_usage_report: 1.4.2
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.sebi.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "https:\/\/cloud.sebi.org\/",
    "version": "20.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "maintenance": false,
    "loglevel": 1,
    "updater.release.channel": "stable",
    "theme": "",
    "data-fingerprint": "8cadcd3acd11b446973847d9e426736b",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mysql.utf8mb4": true,
    "logtimezone": "Europe\/Berlin",
    "app_install_overwrite": [
        "files_ebookreader",
        "files_reader",
        "ransomware_detection",
        "ocr",
        "emlviewer"
    ],
    "mail_sendmailmode": "smtp",
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false
}
```
</details>

**Are you using external storage, if yes which one:** sftp (only for one directory)

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

**Operating system:** iPadOS 14.3

## Logs

<details><summary>Web server error log</summary>

```
n/a
```
</details>

<details><summary>Nextcloud log</summary>

```
n/a
```
</details>

<details><summary>Browser log</summary>

``` 
n/a
```
</details>

**Comment by favincen** [comment]
Same issue from Safari 14.0.3 on MacOS Catalina 10.15.7.

Serveur OS: Linux 5.4.78-2-pve x86_64
PHP 7.3.20
Nextcloud 20.0.4
Talk 10.0.6

**Comment by AxelRothe** [comment]
I also experience this when we try using Safari with Nextcloud Talk.
Same goes for copying and pasting other chat messages. All new lines will be wrapped in divs.

This is an unusual behaviour for copy and pasting. Usually Safari won't copy html tags, is there something activated that forces Safari to copy HTML?

Everything is updated to the newest version, as of today.

**Comment by nickvergessen** [comment]
Well it's not a textarea but a "div contenteditable"

**Comment by jmhammond** [comment]
Happens also with Safari 14.0.3 on MacOS Big Sur 11.2.3.

**Comment by p-jo** [comment]
Here is a discussion about it https://stackoverflow.com/questions/18552336/prevent-contenteditable-adding-div-on-enter-chrome#20398548

**Comment by marcoambrosini** [comment]
I can confirm that this is happening on MacOS too
