### ISSUE TITLE
Do not show system message when self joined user leaves the conversation

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#4897]
Found while testing #4892 

A self joined user can leave a conversation by changing to a different conversation or by explicitly leaving it. In the second case a system message is shown (like when a normal participant leaves the conversation), but as the self joined user is not actually a normal participant it should behave just as changing to a different conversation and no message should be shown.

## Steps to reproduce
- Create a public conversation
- Copy the link
- In a private window, log in as another user
- Open the link
- Leave the conversation from the menu in the conversation list

### Expected behaviour

No system message is shown.

### Actual behaviour

`XXX left the conversation` appears in the chat.

**Comment by PVince81** [comment]
I wonder if it's a regression / side effects from the new listable conversations or whether it was here before

**Comment by nickvergessen** [comment]
Patch in https://github.com/nextcloud/spreed/pull/4933
