### ISSUE TITLE
Screensharing layout enhancements

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4920]
Depending on the size of your screen and browser window the screen share is align differently. Sometimes there is a black border at the top and at the bottom where the controls are located, but sometimes it looks like this:

![image](https://user-images.githubusercontent.com/1589737/104020777-04237200-51be-11eb-90ca-3a4c7444a0c4.png)

As you can see, the controls at the top and at the bottom hide some parts of the shared screen. Depending on what you share this can be really irritating and cover important parts of the screen. Regarding the transparent controls at the bottom it can also confuse people because it might not be obvious if they are part of the shared screen or if they are the users controls.

Not sure what's the best solution here but I think it would be good if we could find a solution where people can always see the whole shared screen without any overlays.

Maybe @nextcloud/designers might have some good ideas. :slightly_smiling_face:

**Comment by nickvergessen** [comment]
> Another thing mentioned by a user I talked to recently. Collapsing the videos on the bottom for screensharing is a great enhancement. But there is one big drawback, you no longer see who is speaking at the moment. Not the video, that's hidden by intention but the name. In large groups you still want to know who is speaking at the moment. Maybe we can come up with a nice idea to show the speakers name permanently or as some kind of "popup" bubble when someone starts speaking?

Mind moving that to another issue, as it needs a different fix.

**Comment by nickvergessen** [comment]
At least the bottom controlls should fade out if you don't hover with the mouse. Maybe we also do that in the top?
Could also add some 0.75 opacity background on the controls to make sure they are clearly visible

**Comment by nickvergessen** [comment]
![screensharing](https://user-images.githubusercontent.com/213943/142015520-6338bf5b-9e79-4ff1-b861-d9b697de930f.png)

This is solved with the controls in the topbar and the new call layout (screenshot for reference)
