### ISSUE TITLE
Show room description on the lobby view

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4921]
The recently added room description is a nice place to add some information about the planed meeting. The topic, maybe a short agenda, etc. Therefore it would be nice when the description would be also visible in the lobby view before a meeting starts.

**Comment by PVince81** [comment]
also nice would be to display the remaining time in a format like:
- 2 days left
- 4 hours left
- 32 minutes left
- 1 minute left

Basically only a single unit.
Could also be replaced with "In {value} {unit}" instead.

**Comment by nickvergessen** [comment]
and the exact time, because 6 days doesn't tell you when it is next thursday

**Comment by PVince81** [comment]
the exact time is already visible in the current implementation
