### ISSUE TITLE
error with installation 

### ISSUE THREAD

**Issue by framarini02** [nextcloud/spreed#4923]
## Steps to reproduce
1. download talk 11.0.0 alpha 3

### Expected behaviour
talk should work
### Actual behaviour
error with installation (this is teh error: App with id spreed has invalid signature)
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.0.0 alpha 3
**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 

*Browser name:** Chrome

[nextcloud.log](https://github.com/nextcloud/spreed/files/5789036/nextcloud.log)

**Comment by nickvergessen** [comment]
Are you using Nextcloud 21 beta5?
That's a hard dependency

**Comment by kibuuka** [comment]
Confirming reported behaviour on Nextcloud 21.0.0 beta5 for talk 11.0.0 alpha 3
Manual installation went quite well.

**Comment by nickvergessen** [comment]
Server issue https://github.com/nextcloud/server/pull/24727

**Comment by framarini02** [comment]
I can't use talk after manual installation. I brought the spreed folder into the app folder and if I open talk I see a white screen
