### ISSUE TITLE
Problem with manual installation 

### ISSUE THREAD

**Issue by framarini02** [nextcloud/spreed#4924]
I can't use talk after manual installation. I brought the spreed folder into the app folder and if I open talk I see a white screen. Do I have to do something else to make it work?

**Comment by framarini02** [comment]
i use nextcloud 21.0.0 beta 5

**Comment by nickvergessen** [comment]
what is manual installation? you should just install it from the appstore. Otherwise get it from https://github.com/nextcloud/spreed/releases/download/v11.0.0-alpha.3/spreed-11.0.0-alpha.3.tar.gz
If you just put the git repo on your server it will not work.

**Comment by kibuuka** [comment]
Ehm. By manual installation I've meant installing it by extracting contents of abovementioned tarball and putting them to apps subfolder of existing 21.0.0 beta5 installation, having it installed, activate and working as a result.

Installation from appstore fails, just like @framarini02 mentioned.

**Comment by framarini02** [comment]
if I install it from the app store it doesn't work so I tried manual installation but after bringing the spreed folder to the apps folder, do I have to do anything else?  because otherwise it doesn't work for me

**Comment by nickvergessen** [comment]
No, simply putting it there and then enabling it in the app management is enough.

**Comment by framarini02** [comment]
Doing this then when I go open talk I see a white screen

**Comment by nickvergessen** [comment]
Hmm which browser are you using? It works fine here (at least when the owner is set correctly to `www-data:www-data` after moving it to the apps directory)

**Comment by nickvergessen** [comment]
Actual issue is at https://github.com/nextcloud/server/pull/25088

**Comment by framarini02** [comment]
I have tried with many browsers but they all show nothing.  I tried chrome, safari and edge. What can I do to fix?

**Comment by nickvergessen** [comment]
With that patch you should be able to download it properly from the appstore again

**Comment by framarini02** [comment]
but when should the new patch come out?

**Comment by nickvergessen** [comment]
In the next Server beta, or you apply it manually.

**Comment by framarini02** [comment]
ok thanks

**Comment by nickvergessen** [comment]
Closing this. Feel free to reopen when it's still broken on Nextcloud 21 beta6
