### ISSUE TITLE
Invite emails directly when creating a conversation

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/spreed#4937]
### Expected behaviour
It's all in the title.
We have a lot of 1:1 conversations with external participants. For this purpose, the conversations are mostly created exclusively. It would be noticeable improvement if the creation dialog allows this form of usage.

### Actual behaviour
Currently, I have to go to the sidebar specifically to email invite a participant after the conversation has already been created.

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
v10.0.5

**Comment by nickvergessen** [comment]
Yeah, also mentioned in https://github.com/nextcloud/spreed/issues/2874#issuecomment-580479301

**Comment by sudwhiwdh** [comment]
Thanks for the link!
Do you have an idea how this improvement can be realized code-wise?

**Comment by nickvergessen** [comment]
Well someone needs to extend the API to accept a list of invitees, and change the frontend to also find emails and then either do an individual request per email or send them on the new creation api with the invitee list
