### ISSUE TITLE
Participants who have been invited to password-protected conversations by mail should be able to get the access password in a simple way if there are no other more secure ways of transmission

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/spreed#4938]
### Expected behaviour
I was wondering whether it would make sense to make it an option when creating the conversation that the password can be sent to the participant automatically in a separate email. Which then comes in a time-defined interval after the invitation email.
Or that the invitation email contains a standard note that the password must be requested from the person who sent the invitation email - and via a secure communication channel.

In addition, as the creator of the conversation, I have no way of accessing the password after I have logged it in.
And therefore I can't send it again to the invited participant. That's why it would be important that the password reaches the other participant in the creation flow before an exchange about it is no longer possible.

### Actual behaviour
Right now it is so that I the recipients of the automated invitation email possibly already click on the link, see that they should enter a password and of course then have no information about what the password can be, because also the email contains no such information. For example a hint that the password has to be exchanged in a separate way. Then they remain irritated for a while and the flow comes to a standstill.

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
v10.0.5

**Comment by PVince81** [comment]
Idea: provide a way to use video verification also for talk links ?
This option is available currently for folder/file shares only.

Otherwise you might be able to edit the email template in a theme and remove the password from it and add a note there.

**Comment by sudwhiwdh** [comment]
> Idea: provide a way to use video verification also for talk links ?

How would this look if I have a scheduled call with the lobby turned on?
The password would then be exchanged directly before the call? Or would I then have to make a second appointment with the person, where I can then tell them the password?

For me the question is also, is it only a call or should chatting also it also be possible in advance.

By the way, it gets more complicated with the oral transmission when people assign more complex password managers passwords.

> This option is available currently for folder/file shares only.

What do you think about this solution from your perspective?
Would it be easy to implement?

> Otherwise you might be able to edit the email template in a theme and remove the password from it and add a note there.

How do you mean remove the password from it? A standard invitation email currently contains the link to the conversation, not the password.

**Comment by nickvergessen** [comment]
We don't actually store the password, just a hash. We have no way to recover the password from this hash so we can also not send it anymore. With upcoming Talk 11 we can store data for email guests, so we might also be able to create them a unique password/pin which allows them to access the conversation without the conversation being public at all or replacing their password. But for now there is nothing we can do to improve this situation.

**Comment by sudwhiwdh** [comment]
Would it be conceivable to have a final screen during conversation creation that allows users to copy the password or send it as an automated email notification/note to the external user before the password is written to the database and thus hashed?
