### ISSUE TITLE
Screen sharing: from desktop sharing to screen sharing

### ISSUE THREAD

**Issue by rloutrel** [nextcloud/spreed#4945]
The screen sharing functionality as implemented today is more a desktop sharing functionality.
I am using using a multi-display configuration and I can only share per application or the entire desktop (2 screens).
I wish I could select one of the screen (a static area of the screen defined when starting the sharing would be even wonderful)

**Additional context**
Ubuntu 18.04 ; Gnome 3.28.2 ; Firefox 84.0.2

**Please:**
Before closing the ticket, please orientate me to the correct project, if this is not into your hands (I suppose that the RPC technology is strongly dependent on the OS or Browser API implementation)

**Comment by PVince81** [comment]
If not Firefox, then I believe I've seen Chromium allows to select a single display.

This if unfortunately specific to browser implementation and OS.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1412333 for the feature request for Firefox to support single selection.
