### ISSUE TITLE
Allow some space within long Meeting IDs and PINs

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#4947]
In email invitations, as well as in the Talk UI sidebar, the 10-digit room IDs and the 7-digit PINs would be easier readable if they had some spaces or dashes in between.

#### Current state:
![image](https://user-images.githubusercontent.com/1804221/104516058-0178b080-55f4-11eb-8a35-f0fa484cc8cc.png)

#### Suggestion

Meeting ID: 290 481 3567 or 290-481-3567
PIN: 409 5398 or 409-5398

**Comment by nickvergessen** [comment]
I would already see people searching for a `-` char to add on their phone pad, so let's try spaces

**Comment by wiswedel** [comment]
> I would already see people searching for a `-` char to add on their phone pad

I was afraid you'd share that initial fear about humankind of mine 😆

> so let's try spaces 

💯
