### ISSUE TITLE
grid view disapeard

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4953]
I had a strange experience a few minutes ago and Fabian told me that he had the same situation in the past.

We where in a call with 5 people, beside Fabian and me everyone joined over a public link. One of them switched to another device. I don't know if and when he closed the old browser window but at the moment he switched for both Fabian and me the grid view disappeared. Just a black screen. But we could still  hear all participants. In the speaker promotion view we just saw the person who switched the device, nobody else.

Video where off for all participants we just shared the screen from time to time.

This happened on Nextcloud 21.0.0 beta5 with Talk 11.0.0-alpha.3

**Comment by PVince81** [comment]
If he switched device quickly then maybe some session duplication happened somehow during the call and confused the UI

**Comment by nickvergessen** [comment]
> This happened on Nextcloud 21.0.0 beta5 with Talk 11.0.0-alpha.3

or c.nc.c?

**Comment by schiessle** [comment]
yes, on c.nc.c

**Comment by nickvergessen** [comment]
Feel free to open a new report (best with browser console and screenshot) when it happens again.
