### ISSUE TITLE
Dial-in without PIN

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#4957]
As a moderator, I would like to allow SIP dial-in without PIN, so I can invite an unspecified group of users to a public meeting and allow them to dial-in.

Non-PIN dial-in participants would appear as unnamed "Guest" in the participants list.

All registered invited users and email invitees shall remain receiving PINs.

Currently, only registered invited users and email invitees receive a PIN to dial-in. Guest participants with only the link to the conversation cannot dial-in.

Affected situations:
- Large meetings that are invited to via a mailing list
- forwarded invitations
- delegated participations

**Comment by nickvergessen** [comment]
Just for my record, there is still work to be done in the sipbridge, right  @fancycode ?

**Comment by fancycode** [comment]
Afaik the only thing remaining was to integrate the to-be-defined APIs of Talk to know which room allows guest phone users. So mostly small API / workflow changes.

**Comment by nickvergessen** [comment]
API in https://github.com/nextcloud/spreed/pull/6563

Going to add the moderator option in the same PR, but now you can have a look already.
It's actually so little I'm not sure why we missed to do it all the time
