### ISSUE TITLE
Make lobby disabling more accessible

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#4981]
**Is your feature request related to a problem? Please describe.**
When a moderator has activated the lobby with a meeting start date, the joining limitation for guests automatically drops once the start time is reached.
However, it is appropriate to start the meeting a few minutes early because for example the guests are already assembled in the lobby.

In order to disable that lobby manually, the moderator currently has to go to the ... menu, then to the conversation settings, scroll down and uncheck the lobby setting.

**Describe the solution you'd like**
A prominent button in the sidebar to disable the lobby with one click and open the doors for the guests waiting outside

**Comment by wiswedel** [comment]
see also https://github.com/nextcloud/spreed/issues/4982

**Comment by PVince81** [comment]
Are we ok to implement the proposal or do we want to explore other design alternatives ?

Possible alternative: have a "disable lobby" button in the three dots menu, only present if lobby as enabled.

Possible use case: the moderators already started a call in which they discuss preparations and they might want to disable the lobby without stopping the call. Having the button either in the right sidebar or top bar menu would work.

Thoughts ? @nextcloud/designers-talk

**Comment by nickvergessen** [comment]
There should be a direct "Disable lobby" button in the sidebar under the title/description if lobby is enabled.

**Comment by wiswedel** [comment]
> There should be a direct "Disable lobby" button in the sidebar under the title/description if lobby is enabled.

👍 that'll also close https://github.com/nextcloud/spreed/issues/4982

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/4997
