### ISSUE TITLE
[11.x] Lobby start time cannot be removed

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#4983]
Until Talk 10.x, the start time for calls with lobby was optional. A once set start time could be removed from the input field and what remained was the help text that the start time is optional:

![image](https://user-images.githubusercontent.com/1804221/105214685-9d547000-5b50-11eb-8d8f-67873e38dc10.png)

That is no longer possible with 11.x: Once the checkbox "enable lobby" is checked, the start time is pre-filled with "now".
You neither see the hint that the start time is optional after all, nor can you remove the pre-filled time. The UI simply immediately puts it back into the input field if you try deleting it from there.

**Comment by nickvergessen** [comment]
On 20 the displaying always failed

**Comment by wiswedel** [comment]
> On 20 the displaying always failed

not on my test system on 20.0.4 with Talk 10.0.5 🤔

**Comment by PVince81** [comment]
I went back in time to the moment where this feature was merged and at that time it was possible to clear the lobby field value. I did remember that it worked back then.

So maybe there were recent changes to the date picker field that disallowed empty values.

**Comment by PVince81** [comment]
Fix is here https://github.com/nextcloud/spreed/pull/4990 with some bonus UX adjustments.
