### ISSUE TITLE
Talking SIP participant triggers raise hand

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#4984]
## Steps to reproduce
1. User A joins a call via web
2. User B joins call via phone (SIP)
3. User B talks

### Expected behaviour
nothing special

### Actual behaviour
With every word user B says, the raise hand feature gets triggered. The user constantly (re-)raises their hand:

![image](https://user-images.githubusercontent.com/1804221/105215562-b3aefb80-5b51-11eb-98e7-3c01a18c8bf8.png)

**Comment by nickvergessen** [comment]
That's already fixed on master

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/commit/a542d701637578296a85f40f2a8edc89c6d2b1e2
