### ISSUE TITLE
Right side bar interaction / frontend improvements

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#499]
We had added bunch of actions to the right side bar.
But they have been added one under the other.
Some design love is needed 😄
@jancborchardt any suggestions? 

------
EDIT @jancborchardt: copied my suggestions up here for easier tracking. :)

- [x] »Room information« should be called »Room name«. Otherwise it’s strange that you can rename it.
- [x] When it’s just a 1-on-1 call, in place of »Room name« it currently only shows the other person’s name and it’s not renameable. So instead of just saying »Frank« it should say »Conversation with Frank« (only there, not in the left navigation – it’s merely additional text) https://github.com/nextcloud/spreed/pull/549
- [ ] »Join call« should be »Start call« when no call is in progress yet.
- [ ] When you check »Share link« the link should be automatically copied to the clipboard, and a tooltip should give feedback saying »Link copied to clipboard«
- [ ] »Set password« should be a button and not directly an input field. Also, it seems to be autofilled?
- [ ] For the guest view, the »Your name« input should be right next to the avatar in the chat, where there’s space. While no name is set, it should have the appearance of an input field (border)

---------------

Normal user:
![screen shot 2017-11-22 at 12 21 28](https://user-images.githubusercontent.com/4638605/33125631-93f477f2-cf81-11e7-84f8-433d218ab9a7.png)

Guest:
![screen shot 2017-11-22 at 12 22 05](https://user-images.githubusercontent.com/4638605/33125644-9ee33f36-cf81-11e7-885c-ca33c5d65bb7.png)

**Comment by jancborchardt** [comment]
Will look into it now that the run for feature freeze is over. ;)

**Comment by nickvergessen** [comment]
Also the handle is very hard to discover to open the sidebar.

But I think for that #461 is the best solution.

**Comment by Ivansss** [comment]
@jancborchardt any ideas for this?

**Comment by jancborchardt** [comment]
Some quick fixes:

- [ ] »Room information« should be called »Room name«. Otherwise it’s strange that you can rename it.
- [ ] When it’s just a 1-on-1 call, in place of »Room name« it currently only shows the other person’s name and it’s not renameable. So instead of just saying »Frank« it should say »Conversation with Frank« (only there, not in the left navigation – it’s merely additional text)
- [ ] »Join call« should be »Start call« when no call is in progress yet.
- [ ] »Set password« should be a button and not directly an input field. Also, it seems to be autofilled?
- [ ] For the guest view, the »Your name« input should be right next to the avatar in the chat, where there’s space


@nickvergessen @Ivansss @danxuliu what do you think? I will also work on the design details, but those changes mentioned above seem to require some code changes too.

**Comment by nickvergessen** [comment]
Okay, so nothing for 3.0

**Comment by jancborchardt** [comment]
@nickvergessen ah ok, I assumed things like that were what you are looking for, or I would have thought at least some of those things would be smth for 3.0? (And I also suggested one of the things at https://github.com/nextcloud/spreed/issues/493#issuecomment-346341174, to no feedback)

Thing is most of the design issues are of an interactive nature, or code-related. I don’t see a lot which could be improved with _only_ CSS. :\ Do you have something in mind?

**Comment by danxuliu** [comment]
@jancborchardt 
>  Some quick fixes:
>  ...
>  what do you think?

I agree with all of them, and they are needed fixes. However...

>  I don’t see a lot which could be improved with only CSS.

I think that the CSS has a lot of room for improvement in this case :-) I mean, looking to the room info what I see is just a bunch of fields thrown together. It lacks structure, style, _rythm_. But I have no idea about how to improve it; I was hoping that you could apply some of your visual design magic :-)

**Comment by nickvergessen** [comment]
> ah ok, I assumed things like that were what you are looking for

Yes, they are

> or I would have thought at least some of those things would be smth for 3.0

They all are, but without someone coding it in the next 6hours, they won't make it. Daniel is still busy with the chat stuff and Ivan and me have too little magic knowledge (CSS + JS)

**Comment by jancborchardt** [comment]
@nickvergessen yeah, makes sense.

> I mean, looking to the room info what I see is just a bunch of fields thrown together. It lacks structure, style, rhythm.

@danxuliu yes, I will try to modify some things. :) However many seem to require a bunch of code changes, but I'll see.

**Comment by jancborchardt** [comment]
First bunch of improvements at https://github.com/nextcloud/spreed/pull/547

**Comment by jancborchardt** [comment]
See https://github.com/nextcloud/spreed/pull/548 for more fixes. :)

**Comment by nickvergessen** [comment]
Most of the stuff has been addressed, if there is something left, please open a new issue
