### ISSUE TITLE
Translations overflow the menu

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4993]
## Steps to reproduce
1. Select german language
2. Try to access conversation settings

### Expected behaviour
✨ 

### Actual behaviour
![Bildschirmfoto von 2021-01-21 15-51-16](https://user-images.githubusercontent.com/213943/105367489-c92f2e80-5c00-11eb-816b-6d975850b84f.png)

**Comment by PVince81** [comment]
Need to use longtext instead of text to wrapping. But in this one case which is not wrappable, might need to adjust the longtext handling of the action menu items to allso ellipsize...
Or change the translation to at least contain some spaces. (too bad that there is no tech standard for wrapping German words at the correct position)

**Comment by nickvergessen** [comment]
Or we bump the default width by ... 25-50%?

**Comment by PVince81** [comment]
default with is 185px in hard-coded in nextcloud-vue.
we could either increase it there or add an override in Talk specifically for this one menu

**Comment by PVince81** [comment]
hah... the french translation is longer but thanks to the spaces it wraps:
<img width="187" alt="image" src="https://user-images.githubusercontent.com/277525/105480343-e8cc6280-5ca5-11eb-8136-bff3ff9c4b29.png">

I've checked all translations and there's only German and another one `Konversationsinställningar` which are without spaces.

So let's increase it to 220px.

**Comment by PVince81** [comment]
- [ ] PR to nextcloud-vue: https://github.com/nextcloud/nextcloud-vue/pull/1677
- [ ] nextcloud-vue patch release
- [ ] bump version

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5000

**Comment by PVince81** [comment]
Fixed by dep update: https://github.com/nextcloud/spreed/pull/5001
