### ISSUE TITLE
Safari not loading

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4995]
## Steps to reproduce
1. Open Talk with Safari

### Expected behaviour
✨ 

### Actual behaviour
```
SyntaxError: Invalid regular expression: invalid group specifier name
```

Ref https://github.com/sindresorhus/linkify-urls/issues/24

**Comment by nickvergessen** [comment]
Replacing line 5 in node_modules/linkify-urls/index.js with:
```js
const urlRegex = () => (/abcdef/g);
```

Fixes it (although then links in the description are not clickable)

**Comment by PVince81** [comment]
looking at the minified code by default, it seems the code is untouched:
`admin-settings.js:const urlRegex = () => (/((?<!\+)(?:https?(?::\/\/))(?:www\.)?(?:[a-zA-Z\d-_.]+(?:(?:\.|@)[a-zA-Z\d]{2,})|localhost)(
?:(?:[-a-zA-Z\d:%_+.~#*$!?&//=@]*)(?:[,](?![\s]))*)*)/g);`

so now to find a babel config that would detect and convert this...

**Comment by PVince81** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/277525/105510523-082bb580-5ccf-11eb-9a66-ea1db2d5dbfa.png">

and I found this https://github.com/babel/babel/issues/10699#issuecomment-553411564 that says that babel can't fix it because it's an engine feature that cannot be polyfilled.

so maybe best luck is find another library

**Comment by PVince81** [comment]
this one says it supports browserification: https://github.com/markdown-it/linkify-it#install (last commits 8 months ago)

**Comment by PVince81** [comment]
weird, seems we have two libraries for linkifying in nextcloud-vue: https://github.com/nextcloud/nextcloud-vue/blob/master/package.json#L53

and one was merged a while ago and Safari was reported working then: https://github.com/nextcloud/nextcloud-vue/pull/1289

need to check to track down why a new lib has been introduced

**Comment by PVince81** [comment]
I don't have Safari available for testing. @nickvergessen can you confirm that the problem also happens with the style guide ? https://nextcloud-vue-components.netlify.app/
If it loads, try also the rich content editor there.

**Comment by PVince81** [comment]
Assigning self to attempt to replace linkifyUrl with linkifyJs which is already available in nextcloud-vue

**Comment by nickvergessen** [comment]
> can you confirm that the problem also happens with the style guide ? https://nextcloud-vue-components.netlify.app/

That page is blank on safari

**Comment by PVince81** [comment]
Here we go, using linkifyJS and removing redundant libs: https://github.com/nextcloud/nextcloud-vue/pull/1678

@nickvergessen please test

**Comment by nickvergessen** [comment]
So with https://github.com/nextcloud/nextcloud-vue/pull/1678 it works again

**Comment by nickvergessen** [comment]
But there is some weird scrolling going on, see first the top on the left.
Then scrolling down:
* settings appear ✅ 
* create button+search field disappear 💥 
* space below the input 💥 

Top | Bottom
---|---
![21-01-23 00-06-39 0014](https://user-images.githubusercontent.com/213943/105559300-0f73b300-5d11-11eb-8eb5-d3d7080d9377.png) | ![21-01-23 00-07-12 0015](https://user-images.githubusercontent.com/213943/105559298-0edb1c80-5d11-11eb-813c-5ee46547303b.png)

**Comment by PVince81** [comment]
Here's the PR for the nextcloud-vue to fix the loading issue: https://github.com/nextcloud/spreed/pull/5008

I don't have any device with Safari here so can't debug the extra issues. @ma12-co any idea ?

**Comment by nickvergessen** [comment]
Layout issue moved to https://github.com/nextcloud/spreed/issues/5010

I guess it's a vue lib issue anyway

**Comment by nickvergessen** [comment]
Moved to https://github.com/nextcloud/nextcloud-vue/issues/1680 after confirming it in the deck app
