### ISSUE TITLE
[Feature request] Too small representation of the split screen

### ISSUE THREAD

**Issue by kleener** [nextcloud/spreed#5009]
Hi,

Last week we tested Talk for the first time with 12 people. 
Several people said that they didn't like the ratio of the split screen to their screen size.
The other participants and the layout took up too much space and the split screen was hardly visible. On smartphones they said that you see yourself more than the presentation.

Result, they don't want to use it for training.

Could one possibly create a view in which the other participants are hidden? Theoretically, the pictures of the participants would then no longer have to be displayed, which would reduce the load on the participants.

At the moment we have not found anything like that, if it is already possible.

Translated with www.DeepL.com/Translator (free version)

**Comment by nickvergessen** [comment]
This was done for Nextcloud 21 I think via #4700 
At least they fold away by default now when a screen is shared and there is a small arrow button to bring them back and hide them again manually
