### ISSUE TITLE
Talk freezes with pink screens every time using Chromium

### ISSUE THREAD

**Issue by ElkbA** [nextcloud/spreed#5013]
## Steps to reproduce
1. Start Chromium Browser in Ubuntu 18.04 LTS
2. Start or join Nextcloud-Talk with e.g. 5 participants

### Expected behaviour
Flawless and smooth videocall for the total duration of the cann.

### Actual behaviour
After some time (e.g. 10 minutes) the talk freezes - I can still hear other participants, but cannot see them anymore. Instead I see 5 pink squares on the screen. The other participants can still hear me, but only see my frozen picture.

## Talk app

**Talk app version:** 10.0.5

**Custom Signaling server configured:** yes 0.2.0-1~ubuntu18.04

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 18.04.

**Browser name:**Chromium

**Browser version:** 87.0.4280.66

## Server configuration

**Operating system**: CentOS

**Nextcloud Version:** 20.0.5

**Comment by nickvergessen** [comment]
We need the Browsers console log (as per issue template) to be able to see if there is an error.

**Comment by wiswedel** [comment]
I always get this after 38 minutes (then restart the browser), another pink-freeze after another 20 minutes and another one after another 15. The intervals are always the same.
Will try getting browser logs on next occasion.

Chrome 89.0.4389.114 64Bit Linux
