### ISSUE TITLE
Arrow to hide the video stream on the button not visible on white background

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5016]
The arrow to hide the video streams on the button:

![image](https://user-images.githubusercontent.com/1589737/105821085-ba5aca00-5fba-11eb-9fb9-a3d1ab721e56.png)

Is not visible on white background. Which happens quite often when people share slides:

![image](https://user-images.githubusercontent.com/1589737/105821282-f5f59400-5fba-11eb-8cdf-468218008cd9.png)

Maybe put a shadow around it? Or turn it to black on bright backgrounds (if this is possible)?

**Comment by nickvergessen** [comment]
> Or turn it to black on bright backgrounds (if this is possible)?

We can't detect the color of that corner in the video... Chrome can't even blur a static image without performance dying.

But yeah there should be a shadow just like on all other buttons
