### ISSUE TITLE
Align mentions with text 

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#5020]
Mention bubbles are not aligned with the rest of the message text.

![89-39-max](https://user-images.githubusercontent.com/26852655/105844639-7626f400-5fd1-11eb-9807-a43891512c43.png)

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2021-01-26 14-51-49](https://user-images.githubusercontent.com/213943/105853543-1dae2180-5fe6-11eb-8bbb-01f6f72a4dbb.png)


works fine here
