### ISSUE TITLE
Mute/unmute icon changes position on click

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#5021]
![Peek 2021-01-26 12-26](https://user-images.githubusercontent.com/26852655/105844825-bedead00-5fd1-11eb-8166-86517d0a998d.gif)

**Comment by Ivansss** [comment]
@ma12-co That's an issue in the SVG. I had the same issue in the iOS app.

**Comment by nickvergessen** [comment]
Should just switch to the Material Icon after 21 is split of

**Comment by PVince81** [comment]
draft PR https://github.com/nextcloud/spreed/pull/5058

**Comment by PVince81** [comment]
I went further and replaced most of the icons from the call view with material design icons here: https://github.com/nextcloud/spreed/pull/5058

This was useful to prevent alignment/offset differences.
