### ISSUE TITLE
Relay deletion via matterbridge

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5029]
Correctly forward "deletions" on matterbridge.
Checking the docs it seems to be not popssible for telegram. So maybe it is possible for talk?
https://github.com/42wim/matterbridge/wiki/FAQ#matterbridge-is-not-deleting-messages-from-telegram-to-other-bridges

Also the otherway around?

**Comment by eneiluj** [comment]
@nickvergessen This is something related to Matterbridge Talk backend. Cc @gary-kim

**Comment by gary-kim** [comment]
Yes, this needs to be implemented in the [go-nc-talk](https://github.com/gary-kim/go-nc-talk) library and then into [Matterbridge](https://github.com/42wim/matterbridge). I'll begin on that. I'm assuming deleting messages is also in the API documentation?

**Comment by nickvergessen** [comment]
Docs Are in https://github.com/nextcloud/spreed/pull/4861

**Comment by gary-kim** [comment]
Should be done by: https://github.com/42wim/matterbridge/pull/1492

**Comment by gary-kim** [comment]
This is completed and available in [Matterbridge 1.22.2](https://github.com/42wim/matterbridge/releases/tag/v1.22.2)
