### ISSUE TITLE
Option to restrict users to talk with other users of other groups

### ISSUE THREAD

**Issue by tigermick** [nextcloud/spreed#5039]
**Is your feature request related to a problem? Please describe.**
It's not a problem but It will be cool to have an option which allow me to restrict users to talk with other users if they are not part of the same group.

**Describe the solution you'd like**
Talk could propose an option in talk settings to block users in terms of their group.
for exemple, I have 4 users : user1, user2, user3 and user4.
I have 3 groups : talk, family1 and family2.
talk to allow all users of this group to use talk.
family1 and family2 to distinguish 2 groups of users ; user1 and user2 in family1 and user3 and user4 in family2.
With this option, admin can prevent user1 and user2 to start a chat with user3 or user4 and conversely
user1 can just talk with user2 and conversely and user3 can just talk with user4 and conversely

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/5442
