### ISSUE TITLE
Can't follow someone from grid view when someone else is screensharing

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#5069]
## Steps to reproduce
Scenario: call with 3 participants, user A, B, C. A is screensharing.
1. You are user B
2. Go to grid view
3. Click on user C

### Expected behaviour
The view should change to speaker view and be locked on (following) user C

### Actual behaviour
Nothing

**Comment by PVince81** [comment]
like with https://github.com/nextcloud/spreed/issues/4051 I think we should refactor the Video.vue vs LocalVideo.vue vs Screen.vue and make it possible to have them all within a single list with common behavior. This way it would be possible to follow any of those without having to write extra code for those.

**Comment by nickvergessen** [comment]
yeah this is all way to mislayouted. Should maybe just collect all the issues and remarks in a single ticket and then discuss in a dedicated call
