### ISSUE TITLE
Matterbride and Telegram Supergroups

### ISSUE THREAD

**Issue by poltrian** [nextcloud/spreed#5095]
## Steps to reproduce
1.create an api key and a chat id 
2.Mark'Matterbride as running
3.Save

### Expected behaviour
Log:

time="2021-02-06T11:26:15+01:00" level=info msg="Running version 1.22.0 afcd362c" prefix=main
time="2021-02-06T11:26:15+01:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg=Connecting prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="Connection succeeded" prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="telegram.0: joining s1xxxxxxxxx_xxxxxxxxx (ID: s1213433379_2380593036716017962telegram.0)" prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg=Connecting prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg=Connected prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg="nctalk.1: joining qbfinsqq (ID: qbfinsqqnctalk.1)" prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main

after Sending as Massage from talk to Telegram:
time="2021-02-06T11:26:15+01:00" level=info msg="Running version 1.22.0 afcd362c" prefix=main
time="2021-02-06T11:26:15+01:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg=Connecting prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="Connection succeeded" prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="telegram.0: joining s1xxxxxxxxx_xxxxxxxxx (ID: s1213433379_2380593036716017962telegram.0)" prefix=telegram
time="2021-02-06T11:26:15+01:00" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2021-02-06T11:26:15+01:00" level=info msg=Connecting prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg=Connected prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg="nctalk.1: joining qbfinsqq (ID: qbfinsqqnctalk.1)" prefix=nctalk
time="2021-02-06T11:26:16+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2021-02-06T11:27:03+01:00" level=error msg="SendMessage failed: strconv.ParseInt: parsing "s1xxxxxxxxx_xxxxxxxxx": invalid syntax" prefix=gateway

The Tegram bot is admin in the Supergroup. If try to connect to the bot, that wroks

### Actual behaviour
Tell us what happens instead

## Talk app

Lastes

Matterbride lastes from Yesterday

**Comment by poltrian** [comment]
If i try a channel its the same:
time="2021-02-06T13:47:35+01:00" level=info msg="Running version 1.22.0 afcd362c" prefix=main
time="2021-02-06T13:47:35+01:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2021-02-06T13:47:35+01:00" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2021-02-06T13:47:35+01:00" level=info msg=Connecting prefix=telegram
time="2021-02-06T13:47:35+01:00" level=info msg="Connection succeeded" prefix=telegram
time="2021-02-06T13:47:35+01:00" level=info msg="telegram.0: joining cxxxxxxxxxx_xxxxxxxxxx (ID: c1144873416_4125721201614441614telegram.0)" prefix=telegram
time="2021-02-06T13:47:35+01:00" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2021-02-06T13:47:35+01:00" level=info msg=Connecting prefix=nctalk
time="2021-02-06T13:47:35+01:00" level=info msg=Connected prefix=nctalk
time="2021-02-06T13:47:35+01:00" level=info msg="nctalk.1: joining majue9qs (ID: majue9qsnctalk.1)" prefix=nctalk
time="2021-02-06T13:47:35+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2021-02-06T13:49:14+01:00" level=error msg="SendMessage failed: strconv.ParseInt: parsing "c1144873416_4125721201614441614": invalid syntax" prefix=gateway

 I created a channel, created a bot and added the channel to it. Then enter the bot ID and the channel ID in Talk. Unfortunately, it only works when I write to the bot itself. But the bot should be a member of the group or the channel to then form the bridge. Or have I misunderstood something?

**Comment by nickvergessen** [comment]
Well, please check https://github.com/42wim/matterbridge/wiki/Section-Telegram-%28basic%29 and otherwise look for more docs in their repository. Since the configuration mostly works I expect this to be a problem with matterbridge-telegram part, so I will close this here.
