### ISSUE TITLE
Copy direct link to message

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5097]
**Is your feature request related to a problem? Please describe.**
Ability to copy a link to message to either:
- send it through other channels to mention it to someone
- link to it as a reference to a statement in some documents
- mention in another Talk channel

**Describe the solution you'd like**
For now, add a button or a link in the message row that allows to copy the already existing message link, the one with the hash that can be seen when using the unified search.

**Comment by PVince81** [comment]
There could be technical limitations to the current link format: since it uses a URL hash, the latter might get lost during a redirection for example when logging in

**Comment by nickvergessen** [comment]
Also currently it's not scrolling up and loading older chunks of messages.

**Comment by PVince81** [comment]
solved in https://github.com/nextcloud/spreed/pull/5285
