### ISSUE TITLE
Sidebar toggle is overlaid by profile picture

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#5099]
## Steps to reproduce
1. Scroll up with a device with a smaller screen width.
2. Sidebar toggle is overlaid by profile pictures.

### Expected behaviour
Sidebar toggle should not be overlaid.

### Actual behaviour
Toggle is overlaid over profile pictures:
![Screenshot 2021-02-08 at 11 40 03](https://user-images.githubusercontent.com/878997/107208909-7cba6000-6a02-11eb-8de4-7898c5f4b136.png)

## Talk app

Company instance.

## Browser

**Microphone available:** Yes

**Camera available:** Yes

**Operating system:** ChromeOS

**Browser name:** Chrome

**Browser version:** 88.0.4324.109

**Comment by nickvergessen** [comment]
So for me the sidebar icon is actually on top of the avatar:
![Bildschirmfoto von 2021-02-09 16-02-03](https://user-images.githubusercontent.com/213943/107382506-3cd1a680-6af0-11eb-86eb-459d23ed0def.png)

Also on our current c.nc.c version, tested with FF 85 and Chromium 88.

**Comment by PVince81** [comment]
From https://github.com/nextcloud/spreed/issues/4147#issuecomment-714576799:

"(...) on narrow screens, the avatar should be sticky below the hamburger menu, not overlapped by it."

I tried to set the hamburger menu to "position: sticky" but it doesn't seem that easy.
Needs further research

**Comment by nickvergessen** [comment]
Not happening anymore with the topbar being there all the time in 13+
