### ISSUE TITLE
Left sidebar "jumps" when selecting the "..." menu

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5100]
Assume you have a large list of rooms and want to delete one, mark it as favorite, change the notification settings,... Basically anything you can do in the "..." menu on the left sidebar.

## Steps to reproduce
1. Search for the room
2. Once the room shows up click the "..." button

### Expected behaviour

Room listing stays the same (with the search result) and the "..." menu opens at the right place

### Actual behaviour

Room listing gets reset, you no longer see the search result but the full room listing starting with the first room and the "..." menu opens completely out of place.

## Talk app

**Talk app version:** 11.0.0-alpha.3 (on c.nc.com 21.0.0 RC1)

**Browser:** Firefox

**Comment by nickvergessen** [comment]
yeah seems the search filter is cleared on click, instead of only when opening a conversation

**Comment by PVince81** [comment]
this is because the three dots menu is part of the anchor element, so the click bubbles up and it behaves as if you clicked the row instead of the menu.

we need to stop the click event from the actions menu

**Comment by PVince81** [comment]
ohhhh no... it's again dependent on v-tooltip's click handler, like in https://github.com/nextcloud/spreed/issues/5790#issuecomment-865297427

**Comment by PVince81** [comment]
I found another easier way: https://github.com/nextcloud/spreed/pull/5840
