### ISSUE TITLE
Allow to join without audio/video as "listener" or "screensharer"

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/spreed#512]
## Steps to reproduce
1. Create a new Call
2. activate Screensharing
3. Guest try to connect on Public link but has no Headset and Webcam
4. Guest could not connect

### Expected behaviour
After Creating a Call I'm able to select which allowed access are needed to connect sucesfully.
 - [ ] Microphone
 - [ ] Webcam
 - [x] Screensharing
 - [ ] Nothing, (only view and listen)

-> Guest could connect and see my screen. and is able to share his screen.

### Actual behaviour
Guest is not allowed to connect

## Browser
Firefox 57

**Microphone available:** yes/no

**Camera available:** no

**Operating system:** Windows and/or Ubuntu/

**Browser name:** Firefox
**Browser version:** 57

</details>

## Spreed app

**Spreed app version:** 2.0.2

**Comment by zyro23** [comment]
also just hit this trying out 13.0.0. would be great if hosting/joining a call and screen sharing would work without (or with denied) mic/cam as well.

**Comment by nickvergessen** [comment]
https://simplewebrtc.com/notsosimple.html
too bad that "Join without a camera or microphone" is empty

**Comment by nickvergessen** [comment]
But nevertheless ivan wants to look into it.

**Comment by Mannshoch** [comment]
Did you have added a settings menu as described?

**Comment by nickvergessen** [comment]
No, there are no settings needed

**Comment by Mannshoch** [comment]
Hmm... than please do not close this issue. The Requirement settings I think are Important. As default settings and if you do create a Public/Group-call to change from default.

**Comment by nickvergessen** [comment]
What settings are you talking about, there is nothing written in the PR description?

**Comment by Mannshoch** [comment]
See the "Expected behaviour" section.
### Expected behaviour
After Creating a Call I'm able to select which allowed access are needed to connect sucesfully.
 - [ ] Microphone
 - [ ] Webcam
 - [x] Screensharing
 - [ ] Nothing, (only view and listen)

**Comment by nickvergessen** [comment]
That's handled by the browser automatically.
You can just deny all permissions are use it without anything.

**Comment by Mannshoch** [comment]
You misunderstand me. It was intended to create a room with mandatory requirements. Only guests who met these requirements were able to join.

**Comment by nickvergessen** [comment]
Ah, now I understand what you are aiming for, however we are not going to do that, sorry.
