### ISSUE TITLE
Feature request: Prevent Call-Loops

### ISSUE THREAD

**Issue by Shen** [nextcloud/spreed#5127]
**Is your feature request related to a problem? Please describe.**
We have a few groups with a lot of members. If one person accidentally starts a call, all members are called. If the calling person hangs up quickly (because it was an accident) and one of the called persons accepts the call, the call is initiated again. This regularly leads to an endless loop that drives all members crazy. Of course, it's the users' own fault for accepting the call, but the basic problem is that a call is started immediately without asking.

**Describe the solution you'd like**
There are several ways to prevent this from happening.
a) There is a demand: "Do you really want to start a call?"
b) There is a possibility to disable the call function for individual groups.
c) There is an option to mute the call function for individual groups.

**Comment by nickvergessen** [comment]
Seeing that also from time to time on our instance. Maybe we shouldn't resend the call notification when it is restarted within X second or something. But I'm quite unsure about it.

**Comment by nickvergessen** [comment]
- In the meantime follow up calls are prevented by the frontend by disabling the join button for some seconds: https://github.com/nextcloud/spreed/pull/13243
