### ISSUE TITLE
Error in files with Polish translation.

### ISSUE THREAD

**Issue by jwolanski** [nextcloud/spreed#5128]
The conversation history is not loaded for conversations with more than one guest.
In the translation files there is:
`"_%n guest_::_%n guests_" : ["%n gość","%gości","%n gości","%n gości"],`
I think it should be:
`"_%n guest_::_%n guests_" : ["%n gość","%n gości"],`

**Comment by nickvergessen** [comment]
Please fix this on transifex directly

**Comment by nickvergessen** [comment]
This was fixed and translations synced. We will make a new release next week
