### ISSUE TITLE
l18n: Strings not translatable without context

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/spreed#5134]
There are some strings which are not translatable without context.

Example:
https://github.com/nextcloud/spreed/blob/066087bd7648d384ae1d0b6d44dda88545acdada/src/components/AdminSettings/TurnServer.vue#L37

Do you developers think the user will understand them?

Is there a need to translate such strings?

**Comment by nickvergessen** [comment]
I was thinking about taking out the `turns:` part. But then the translator needs to translate:
```
'{protocol} only'
```

I guess it's better?

**Comment by rakekniven** [comment]
Hmmh, the issue is that many translators are not so technical to know about the "turn" thing.

We need comments at vue files. See https://github.com/nextcloud/documentation/issues/5422

But for sure, your suggestion is an improvement 👍
