### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5152]
Several things changed and therefor the screenshots need to be updated:
* [x] call-in-action.png
  * Icons in call view
  * read-marker in the chat
  * No description
  * "Projects" tab is wrong name
* [ ] chat.png
  * Should show reply
  * Should show delete
  * Should show a shared deck card
  * Left sidebar could have an open conversation
  * Right sidebar should contain user status
  * "Projects" tab is wrong name
* [ ] file-darg-and-drop.png
  * should also have part2 with the modal to add more?
  * "Projects" tab is wrong name
* [ ] screensharing.png
  * Call view is missing the background colors of the avatars
  * Option to fold the bottom row
  * Conversation menu button is in old place
  * "Projects" tab is wrong name
* [ ] video-verfication.png
  * Call view is old scaling and buttons
  * Chat input is very old

**Comment by nickvergessen** [comment]
`call-in-action.png ` fixed in #5239

**Comment by PVince81** [comment]
Hmmm, the hidden overengineer in me is saying "how about automating screenshots with Cypress so they stay up to date".

The biggest challenge I see in replicating those screenshots is finding those user avatars again every time. Or finding new ones.
Unless you have a good source ?

**Comment by PVince81** [comment]
Extra advantage for Cypress screenshots: it could help keep some design consistency like in nextcloud-vue. Could be overkill though.
