### ISSUE TITLE
UI Bug: Context menu misplaced

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#5169]
## Steps to reproduce
1. Start a talk
2. Click screen sharing button

### Expected behaviour
context menu readable and correctly positioned

### Actual behaviour
context menu badly positioned, hidden by chat window
![misplaced-menu](https://user-images.githubusercontent.com/42836313/107864287-0df26200-6e5b-11eb-85f5-d41041136953.png)

## Talk app

**Talk app version:** 10.0.5

## Browser

**Operating system:** Windows 10 x64

**Browser name:** Firefox 85.0.2 (64-Bit)

## Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version:** 20.0.7

**Comment by nickvergessen** [comment]
Also happens on master and stable21

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/f2fc86de4078d497bf69e56564a119c08d365d8c/src/components/CallView/shared/LocalMediaControls.vue#L92-L119 should be an Actions component? @ma12-co

**Comment by nickvergessen** [comment]
Doesn't seem to happen anymore since we switched to the Actions component
