### ISSUE TITLE
Disable automatic logout after X minutes when screen sharing is active

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#5170]
## Steps to reproduce
1. Start a talk
2. Start screen sharing
3. Open another software and talk for about 30 minutes without touching the browser window

### Expected behaviour
Session keeps going and going

### Actual behaviour
User gets kicked out of the talk session because he gets logged out from nextcloud after certain time without any interaction

## Talk app

**Talk app version:** 10.0.5

## Browser

**Operating system:** Windows 10 x64

**Browser name:** Firefox 85.0.2 (64-Bit)

## Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version:** 20.0.7

**Comment by nickvergessen** [comment]
Check the session lifetime  and keepalive in you config.php
 https://docs.nextcloud.com/server/21/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=session#user-experience

**Comment by johkoenig** [comment]
Hey @nickvergessen 
I've actually checked my settings and I didn't change set any settings concerning session lifetime or token lifetime in my config. So, I wonder why I get logged out automatically after 30 minutes, since I don't find any settings where 30 minutes is a default value.

However, this was not the issue. The issue is that I want to keep auto-logout activated in general. However, when doing talk sessions, especially with screen sharing activated, the auto-logout shall be deactivated. Use case is for example giving a lecture for 90 minutes. Everybody joins the talk, I enable screen sharing, then my firefox gets minimized and I show a presentation for 90 minutes. Currently, I will get logged off after 30 minutes and I do not even notice (my listeners tell me they dont see my screen anymore).

**Comment by nickvergessen** [comment]
Well even when you are in a Screenshare we do requests every 30 seconds. So from talk point of view there is nothing we can do.
But then again there is no auto logout or something by default, so I would recommend that you search for help in the forums.
