### ISSUE TITLE
Changing devices microphone/cameras 

### ISSUE THREAD

**Issue by adosix** [nextcloud/spreed#5183]
**Describe the solution you'd like**

I had issue when I have connected several microphones on my mobile phone. That I can't select which device will be used. Discord has really nice solution to that and also many other applications so it would be very appreciated to see something similar implemented in nextcloud talk. 

But also I would like to thank all contributors of nextcloud talk. Great job.

**Comment by nickvergessen** [comment]
Are you speaking about the mobile apps (android or iOS?) or the web view?

**Comment by adosix** [comment]
in mobile apps ( android and IOS )

**Comment by nickvergessen** [comment]
Can you then create a dedicated issue in https://github.com/nextcloud/talk-ios or https://github.com/nextcloud/talk-android
Thanks!
