### ISSUE TITLE
Force Guests to Input a Name

### ISSUE THREAD

**Issue by luminous706** [nextcloud/spreed#5184]
**Is your feature request related to a problem? Please describe.**
When a Guest joins a channel, force them to put a name, because most of them just don't bother.

**Describe the solution you'd like**
An option to force Guests to put a name when they join.

**Describe alternatives you've considered**
Telling people to put a name when they join a channel.

**Comment by nickvergessen** [comment]
cc @jancborchardt

**Comment by nickvergessen** [comment]
Duplicate of #855
