### ISSUE TITLE
"Leave call" button disappears when the conversation is locked during the call

### ISSUE THREAD

**Issue by vaneslie** [nextcloud/spreed#5192]
## Steps to reproduce
1. Start a call.
2. Lock the conversation.
3. "Leave call" button disappears and you can't leave the call except by closing the browser window.

### Expected behaviour
"Leave call" button should be visible in any case (or is this a feature to stop people from leaving? 😁)

### Actual behaviour
"Leave call" button disappears

## Talk app

Latest Talk version we're currently using on the company instance.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Mac

**Browser name:** Chrome, Safari

**Browser version:** Chrome 88.0, Safari 14.0.3

**Comment by nickvergessen** [comment]
> Latest Talk version we're currently using on the company instance.

11.0.0-rc1 that is

**Comment by nickvergessen** [comment]
So either everyone should be removed from the call (then we also need a warning on the setting), or leaving should of course be possible.

**Comment by PVince81** [comment]
as discussed: when the flag is set to locked, we automatically remove everyone from the call.
similar like when switching on lobby mode.

**Comment by PVince81** [comment]
PR here for kicking everyone out: https://github.com/nextcloud/spreed/pull/5215
