### ISSUE TITLE
Tooltip in unified search doesn't show mentions correctly

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5199]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/277525/108479519-210b9480-7296-11eb-99ee-919614dba153.png">

We should probably switch to "v-tooltip" there anyway so we can display richer tooltips with the mention bubbles.

**Comment by nickvergessen** [comment]
Is thrummed search we don't manage the UI for that...

**Comment by PVince81** [comment]
Maybe we can tweak the response from our search plugin to pre-render names for the mentions. They won't appear as bubbles then but also not as placeholders.

But anyway, feels like low priority.
