### ISSUE TITLE
Message when group/room empty

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#52]
The default message that appears when no group/room is joined is fine: 'Time to do your hair! :) Then join a room or create a new one'

But a different message should appear when be alone in a group. Something like: 'You are alone in this group. Join a different one or invite someone'

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
Yep, the message should be contextual. Also for 1on1 chats we are going to show the avatar of the other person instead of the video icon. And as text something like »Waiting for Lukas to join the call …«

**Comment by jancborchardt** [comment]
- Avatar of other person as image (group icon when group)
- Waiting for Lukas to join the room …
- Waiting for others to join the room …
