### ISSUE TITLE
Audio lags for person hosting video call

### ISSUE THREAD

**Issue by tltucker** [nextcloud/spreed#520]
## Steps to reproduce
1. setup video call with public link and have them connect
2. 
3.

### Expected behaviour
While talking,  my voice and video, and their audio and video should be synced

### Actual behaviour
I am hosting the call, their audio and video are synced, but my audio lags by several second from my video. I don't know if distance makes a difference, but I am in the US, and they were in Great Britain. 

## Browser
Tried with Firefox, Chrome and Chromium, same results

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Linux Mint 18.2 and Ubuntu

**Browser name:** Tried with Firefox 57.01, Firefox ESR 52.5, Chromium 62.0.3202.94, and Chrome 53.02785.89

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** 2.0.2
**Custom TURN server configured:** No

**Custom STUN server configured:** No

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud Version:** 12.0.4

**List of activated apps:**

<details>
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.5.4
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - richdocuments: 1.12.39
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - user_usage_report: 1.0.1
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "d1bc93a643767cb4d547ef03c7086c17",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.riverfield.org"
        ],
        "datadirectory": "\/home\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.riverfield.org\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "riverfield.org",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Log file is empty
```
</details>

**Comment by Ivansss** [comment]
Hi @tltucker 

This app is based on WebRTC and communication between participants in a call is P2P.
So calls are not really hosted by anyone. Everyone is connected to everyone with a P2P connection.
This lag you are experimenting could be related to different reasons, your internet connection, the device (hardware) you are using,...

How many people are in that calls you are experimenting lag?

**Comment by nickvergessen** [comment]
Closing due to the lag of feedback
