### ISSUE TITLE
Browser warning with Opera GX

### ISSUE THREAD

**Issue by nils-kt** [nextcloud/spreed#5207]
## Steps to reproduce
1. Open Talk (Spreed) with Opera GX

### Expected behaviour
No warning, because its the same like Opera.

### Actual behaviour
Warning "Der von Dir verwendete Browser wird von Nextcloud Talk nicht vollständig unterstützt. Bitte verwende die neueste Version von Mozilla Firefox, Microsoft Edge, Google Chrome oder Apple Safari.".

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Opera GX

**Browser version:** 73.0.3856.400

**Nextcloud Version:** 20.0.7

**Comment by nickvergessen** [comment]
Opera warning should be gone in Talk 11+

**Comment by nickvergessen** [comment]
As per #4974 it's 11+ (should come next week)
