### ISSUE TITLE
{{ statusMessage }} in sidebar instead of actual message?

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/spreed#5211]
![grafik](https://user-images.githubusercontent.com/4741199/108501877-35f62100-72b2-11eb-9b6c-e0a5d0b4f5dd.png)

@ChristophWurst i just wanted to make sure that this is some kind of joke and not a bug :laughing: could you please confirm?

**Comment by ChristophWurst** [comment]
joke? me? never! :wink:

**Comment by nickvergessen** [comment]
The user seems to be broken, yesterday the status also showed `[object Object]`
