### ISSUE TITLE
LDAP full name user search not available

### ISSUE THREAD

**Issue by azuledu** [nextcloud/spreed#522]
Searching for a LDAP user to call, it is not possible to find it using the full user name (cn), only the username (uid).

In my LDAP I am using cn as dn.
In Nextcloud I am using cn as "full user name".

Tested in the last virtual machine version for Nextcloud (12.0.4)

Thanks.

**Comment by azuledu** [comment]
Ok, I found the "problem". 

For the search box functioning in a normal way it is necessary to activate the option "Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered" in /settings/admin/sharing

 If this is the expected behaviour this issue can be closed.

Thanks.

**Comment by danxuliu** [comment]
>  If this is the expected behaviour this issue can be closed.

It is the expected behaviour, although admittedly not a clear one; I have raised an issue in the server to improve the wording of the settings.

Thanks for letting us know! :-)
