### ISSUE TITLE
i cant call with NC and COTURN latest version

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/spreed#523]
Hi bro, i update to 12.0.4 and turnserver to 4.5.0.7, before that all is working, but now audio and video is stoped, pls tell me what i need to do
Stay alert

**Comment by nickvergessen** [comment]
Did you also update the spreed app?
If not I guess the problem is with the (co)turn server.

Also check your admin settings whether the server is still configured correctly.

**Comment by johnfelipe** [comment]
My problem is with a section of my office network, 3g, 4g, other networks is good, but ip static with noip static in my office network is not working, all perms is open, can u give me options?

**Comment by nickvergessen** [comment]
Feel free to create a new issue with the requested details, if that is still an issue for you.
