### ISSUE TITLE
Upstream all modifications and components

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5240]
- [ ] Left sidebar
  - [x] Rounded corners on app navigation item: #4934
  - [x] AppContentListItem https://github.com/nextcloud/spreed/tree/master/src/components/LeftSidebar/ConversationsList/AppContentListItem
     => https://github.com/nextcloud/nextcloud-vue/pull/616
  - [x] ActionCaption https://github.com/nextcloud/spreed/tree/master/src/components/LeftSidebar/ActionCaption
  - [x] App navigation caption https://github.com/nextcloud/spreed/blob/master/src/components/Caption.vue
  - [ ] App navigation hint https://github.com/nextcloud/spreed/blob/master/src/components/Hint.vue
  - [ ] App navigation search box https://github.com/nextcloud/spreed/tree/master/src/components/LeftSidebar/SearchBox
- [x] ~~Settings dialog (?) https://github.com/nextcloud/spreed/tree/master/src/components/SettingsDialog~~
- [x]  ~~Right sidebar https://github.com/nextcloud/spreed/tree/master/src/components/RightSidebar/Description~~
  - [x]  ~~Description overflow shadow/fade~~
  - [x]  ~~Countdown warning for max length of description~~

Please add things you know/notice that are "overwritten" in Talk and send PRs upstream to close the list, so we maybe have a clean -vue component for 22

**Comment by ma12-co** [comment]
ActionCaption: https://github.com/nextcloud/nextcloud-vue/pull/1739

**Comment by ma12-co** [comment]
cc @skjnldsv @juliushaertl @jancborchardt @ChristophWurst  is there anything in that list that you won't upstream to the vue lib?

**Comment by nickvergessen** [comment]
State updated

**Comment by nickvergessen** [comment]
Moving yet another time.

**Comment by marcoambrosini** [comment]
Can we consider this done @nickvergessen ?
