### ISSUE TITLE
[Talk 11] "Conversation Settings" string displaced

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#5249]
The string "Conversation Settings" in the group conversation context menu for admins is sitting 3px too high:

![image](https://user-images.githubusercontent.com/1804221/108893477-6a027680-7611-11eb-95ea-789c00ee97a0.png)

**Comment by PVince81** [comment]
let's switch those to material design, hopefully they might align better ? @ma12-co

**Comment by PVince81** [comment]
requires https://github.com/nextcloud/spreed/issues/5292 to be merged first

then we can try to switch all cog icons to material design everywhere, not only in that menu

**Comment by PVince81** [comment]
already fixed as seen on master:
<img width="182" alt="image" src="https://user-images.githubusercontent.com/277525/122906280-48f92a80-d352-11eb-996b-889c4faca653.png">
