### ISSUE TITLE
Conversation 3-dot-menu not responding in fullscreen mode

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#5250]
## Steps to reproduce
1. Create a group conversation
2. Enter fullscreen mode
3. click on the ... menu beside the "start call" button

### Expected behaviour
Conversation context menu opens

### Actual behaviour
Nothing happens

## Talk app

**Talk app version:** 10+11

**Comment by nickvergessen** [comment]
Duplicate of #5027

**Comment by wiswedel** [comment]
> Duplicate of #5027

Ah, missed that, sorry. Where's that handy duplicate suggestion dropdown gone anyway? 🤷‍♂️
