### ISSUE TITLE
Nextcloud Talk - TURN-TLS isn’t working

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/spreed#5251]
Nextcloud Talk - TURN + TLS connection not working

Hi,

I have troubles to configure successful nextcloud talk + tls connection.

Here is my configuration:
```
    tls-listening-port=5349 
    fingerprint 
    use-auth-secret 
    static-auth-secret=<secret> //openssl rand -hex 32 
    realm=mydomain.com 
    total-quota=100 
    bps-capacity=0 
    stale-nonce=600 
    cert=/etc/letsencrypt/live/mydomain.com/cert.pem pkey=/etc/letsencrypt/live/mydomain.com/privkey.pem 
    cipher-list=“ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES1>″ 
    no-multicast-peers 
    no-tlsv1 
    no-tlsv1_1 
    no-stdout-log 
```

ufw status:
```
    5349/tcp                   ALLOW       Anywhere 
    5349/udp                   ALLOW       Anywhere 
```

port forwarded (gateway):
```
    IP = Nextcloud host (where TURN-server is installed) 
    Port = 5349 (TCP + UDP) 
    Anywhere (Internet) 
```

curl -v https://mydomain:5349

\* Trying PUBLIC-IP.....

\* TCP\_NODELAY set

\* connect to PUBLIC-IP port 5349 failed: Connection timed out

\* Failed to connect to mydomain.com port 5349: Connection timed out

\* Closing connection 0

curl: (28) Failed to connect to mydomain.com port 5349: Connection timed out

&#x200B;

I found in the NC guide the following information:

Source: [https://nextcloud-talk.readthedocs.io/en/latest/TURN/](https://nextcloud-talk.readthedocs.io/en/latest/TURN/)

&#x200B;

https://preview.redd.it/c32pev5lz9j61.png?width=730&format=png&auto=webp&s=1b6f73e8a71845a58b4abbe4edfdf92c5705bf17

Is thats the reason why it is not working?

Has anyone successful configured TLS + NC Talk?

Without TLS it is working fine.

**Comment by Tachi107** [comment]
What's the need for TURN-TLS? Traffic between peers is already encrypted. 

TLS with coTURN is not supported anyway, as [described in the docs](https://nextcloud-talk.readthedocs.io/en/latest/TURN/). 

I think you can close the issue :)

**Comment by nickvergessen** [comment]
Just update to Nextcloud 21 and Talk 11
