### ISSUE TITLE
Register multiple possible actions in contacts menu

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/spreed#526]
Instead of the „Talk“ Button next to a contact in the contacts menu there should be mutliple buttons:

- Chat
- Audio call
- Video call

**Comment by nickvergessen** [comment]
There is no such thing as "Audio call" and "Video call".
There is only call.

But yeah, maybe we can add a parameter to the URL which makes the user automatically joining the call, not only the room.

**Comment by jancborchardt** [comment]
This would introduce a lot of complexity in the Contacts menu. Simply going to »Talk« and defaulting to the Chat, where you can then start the call from is best.
