### ISSUE TITLE
Padding menu

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#5260]
No padding at `Chat notifications` on the menu for conversation:

![obraz](https://user-images.githubusercontent.com/47037905/109019119-fd42b700-76b8-11eb-9f30-df23d6ca81c4.png)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.0.0

## Browser

**Browser name:** Firefox/Chrome/...
Firefox
**Browser version:** 50.1/55/...
85.0.2

**Nextcloud Version:** (see admin page)
21.0.0 RC2

**Comment by nickvergessen** [comment]
#5248
