### ISSUE TITLE
Error loading dashboard: Access denied to /admin/files/Talk after upgrading to 10.0.6 w/ Nextcloud 20

### ISSUE THREAD

**Issue by kienanstewart** [nextcloud/spreed#5271]
### Expected behaviour

The dashboard should load normally after logging in

### Actual behaviour

After logging in, an message indicating that an internal error ocurred is shown.

Disabling the spreed app allows the dashboard to load properly.

## Talk app

**Talk app version:** 10.0.6

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud Version:** 20.0.8

**List of activated apps:**

<details>
`
If you have access to your command line run e.g.:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.15
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - unsplash: 1.2.1
  - updatenotification: 1.10.0
  - user_external: 1.0.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
from within your server installation folder
`
</details>

### Server log (data/nextcloud.log)
<details>
`
{"reqId":"BwUCTFtktGtTxjOwpH3R","level":3,"time":"2021-02-26T19:54:56+00:00","remoteAddr":"184.160.35.43","user":"admin","app":"index","method":"GET","url":"/apps/dashboard/","message":{"Exception":"OCP\\Files\\
ForbiddenException","Message":"Access denied","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php","line":59,"function":"checkFileAccess","class":"OCA\\FilesAccessContro
l\\Operation","type":"->","args":[{"mountPoint":"/admin/","cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\FilesAccessControl\\St
orageWrapper"},"files/Talk",true]},{"file":"/var/www/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php","line":73,"function":"checkFileAccess","class":"OCA\\FilesAccessControl\\StorageWrapper","type":"->
","args":["files/Talk",true]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1167,"function":"mkdir","class":"OCA\\FilesAccessControl\\StorageWrapper","type":"->","args":["files/Talk"]},{"file":"
/var/www/nextcloud/lib/private/Files/View.php","line":271,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["mkdir","/admin/files/Talk",["create","write"]]},{"file":"/var/www/nextcloud/li
b/private/Files/Node/Folder.php","line":166,"function":"mkdir","class":"OC\\Files\\View","type":"->","args":["/admin/files/Talk"]},{"file":"/var/www/nextcloud/apps/spreed/lib/TInitialState.php","line":92,"functi
on":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["/Talk"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Files/TemplateLoader.php","line":99,"function":"publishInitialStateForUser","class":"OC
A\\Talk\\Files\\TemplateLoader","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Node\\LazyRoot"},{"__class__":"OC\\App\\AppManager"}]},{"file":"/var/www/nextcloud/lib/private/EventDis
patcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Talk\\Files\\TemplateLoader","type":"->","args":[{"__class__":"OCA\\Files\\Event\\LoadSidebar"}]},{"file":"/var/www/nextcloud/3rdpart
y/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Files\\Event\\LoadSidebar"},"OCA\\Files
\\Event\\LoadSidebar",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners
","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"}],"OCA
\\Files\\Event\\LoadSidebar",{"__class__":"OCA\\Files\\Event\\LoadSidebar"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Compon
ent\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Event\\LoadSidebar"},"OCA\\Files\\Event\\LoadSidebar"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatche
r.php","line":98,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Files\\Event\\LoadSidebar",{"__class__":"OCA\\Files\\Event\\LoadSidebar"}]},{"file":"/var/www/nextc
loud/apps/dashboard/lib/Controller/DashboardController.php","line":95,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Event\\LoadSidebar"}]
},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Dashboard\\Controller\\DashboardController","type":"->","args":[]},{"file":"/var/www/nextcl
oud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Dashboard\\Controller\\DashboardCon
troller"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Dashboard\\C
ontroller\\DashboardController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Dashboard\\Controller\\
DashboardController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"dashboard.dashboard.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","
class":"OC\\Route\\Router","type":"->","args":["/apps/dashboard/"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/app
s/files_accesscontrol/lib/Operation.php","Line":85,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0","version":"20.0.8.1"}
`
</details>

**Comment by nickvergessen** [comment]
The problem is your files accesscontrol rules. Can you share them?
