### ISSUE TITLE
Chromecast with TV

### ISSUE THREAD

**Issue by stevesss** [nextcloud/spreed#5279]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stevesss** [comment]
I'd like to see the android app work with the chromecast for TV. I can use Google Duo on the device. There is no installer for nextcloud talk. It is a lot more sociable video conferencing from the couch instead right front front of a computer screen.

**Comment by nickvergessen** [comment]
Please create a new frature request in the android repository

**Comment by stevesss** [comment]
I don't understand what you mean?  

  

  

  

  
  
  
  
  
>

**Comment by nickvergessen** [comment]
Report here https://github.com/nextcloud/talk-android/issues/new

**Comment by stevesss** [comment]
Tak!
