### ISSUE TITLE
Waterfox support? Thanks

### ISSUE THREAD

**Issue by indexr** [nextcloud/spreed#528]
## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Waterfox

**Browser version:** 55.2.2 (64-bit)

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: MacOSX/Linux Mint

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Do you have any idea what is different from firefox?

From reading the websire I guess it's just about changing the user-agent regexes everywhere.
Can you try it with setting a custom user agent which uses Firefox instead of Waterfox?

**Comment by indexr** [comment]
I believe it is a stripped down version of FF, as allegedly FF was bought out by a group of people and no longer considered private, kind of defeating the whole private calls thing.

Can a web browser compromise the privacy of a call?

I’ll try your suggestion and thanks for your hard work!

**Comment by nickvergessen** [comment]
Tested it, installing https://mybrowseraddon.com/useragent-switcher.html and selecting Firefox makes it work.

**Comment by indexr** [comment]
I’ll do it, thanks bro.
