### ISSUE TITLE
Forward a chat message to another chat

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#5287]
It would be nice if the user could select a message and forward it to another chat

**Comment by nickvergessen** [comment]
Yeah we can use the talk message actions option and the conversation picking on the deck card action that was introduced for 11.1 and just copy the text and send it as a message to the new conversation.

**Comment by jakobroehrl** [comment]
@nickvergessen 
Could you sketch out a litte bit how to solve this?

**Comment by nickvergessen** [comment]
When clicking on the action in the actions menu, copy the text and sent it as a message to the other chat.
