### ISSUE TITLE
Actions icons wrong size for material design icons

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5292]
## Steps to reproduce
1. Open the conversation settings menu on the top right

### Expected behaviour
Consistent sizes.

### Actual behaviour
The material design icon now appears smaller:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/277525/109640165-652d4d80-7b50-11eb-9362-aa8861181851.png">

## Talk app

**Talk app version:** master c48008efdc9a5fe74935a2aa05e275799aeda396

This is very likely related to recent changes to the Actions menu in the nextcloud-vue library.

@ma12-co can you have a look ?

**Comment by ma12-co** [comment]
pr here https://github.com/nextcloud/nextcloud-vue/pull/1741

**Comment by PVince81** [comment]
PR to update the lib here https://github.com/nextcloud/spreed/pull/5356 which also fixes the issue
