### ISSUE TITLE
How can I use my SIP account with Nextcloud Talk?

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/spreed#5294]
I read quite a lot about SIP dial-in in Nextcloud Talk. But this is not what I am looking for. I want to be able to use Android/iOS or the web version as a normal SIP client. Is this possible? And if so, how? Thanks and have a nice day!

**Comment by nickvergessen** [comment]
You need the SIP bridge component from our partner Struktur AG, as that talks directly with the High performance backend and provides the SIP participants as a normal stream to all existing users. You will the be able to normally dial in with any phone or sip app on the provided phone numbers

**Comment by sudwhiwdh** [comment]
Good day, thank you for your answer!
My question is not about dialing into an existing conversation using SIP or phone. My question is whether Talk can be used as SIP Cient software. For example in one to one phone calls. Like I imagine that works for Matrix via Matterbridge already. Just using the SIP standard and not WebRTC.

**Comment by eglipeter** [comment]
That would be really great if one could use Nextcloud as a SIP client!

**Comment by Fuseteam** [comment]
Yeah same here; we have an existing PBX server, i would love to sign into my sip account with talk to receive calls with it

**Comment by Fuseteam** [comment]
ah found this: https://help.nextcloud.com/t/sip-gateway-setup/118109/5
