### ISSUE TITLE
Edge: weird system messages centering

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5296]
![image](https://user-images.githubusercontent.com/277525/109704244-aba59b00-7b96-11eb-84a7-edec6b4137ea.png)

On master 4b78e91927293d3d9f7a9e46196a4313f39ac6dc
with Microsoft Edge 41.16299.15.0 using the modern.ie Win10 VM

**Comment by SystemKeeper** [comment]
Is the old non-chromium version of Edge still supported by Talk? I thought only the chromium-based was.

**Comment by nickvergessen** [comment]
Yeah, only chrome based Edge is supported

**Comment by SystemKeeper** [comment]
Okay, but the screenshot looks like "old" edge

**Comment by PVince81** [comment]
okay, so that might explain why that VM's Edge was trying to ask me to download Edge... felt non-sensical.

I guess we can assume that the Chrome-based Edge behaves the same as Chrome then.

**Comment by SystemKeeper** [comment]
Yes, I agree that this is weird... You can destinguish non-chromium and chromium-edge with the logo. The old with is the traditional "e" as seen in internet explorer. The chromium based one are waves (see https://de.wikipedia.org/wiki/Microsoft_Edge)
