### ISSUE TITLE
After NC Upgrade from 20.0.7 to 20.0.8 "Internal Server Error" and SQL Error "'oc_talk_participants' doesn't exist"

### ISSUE THREAD

**Issue by benks-io** [nextcloud/spreed#5324]
After upgrading from 20.0.7 to 20.0.8 Nextcloud throws

`Internal Server Error - The server was unable to complete your request.`

After disabling Spreed App with

`php occ app:disable spreed`

NC works normal. Both "reactivating" and "deinstalling=>installing" Spreed via Webinterface produces the Error above.

the following is noticeable in the log files:

`Base table or view not found: 1146 Table 'nextcloud_production.oc_talk_participants' doesn't exist"`
(more see below)

Compared to another working Instance the Table names ("attendees" vs "participiuants") and structure differs:

Working NC Instance oc_talk_* Tables:
```
| oc_talk_bridges             |
| oc_talk_commands            |
| oc_talk_guests              |
| oc_talk_participants        |
| oc_talk_rooms               |
| oc_talk_signaling           |
```

Not working NC instance oc_talk_* Tables:
```
| oc_talk_attendees              |
| oc_talk_bridges                |
| oc_talk_commands               |
| oc_talk_guests                 |
| oc_talk_rooms                  |
| oc_talk_sessions               |
| oc_talk_signaling              |

```

The Upgrade procedure was more or less as suggested in nc documentation:

```
wget https://download.nextcloud.com/server/releases/nextcloud-$version.tar.bz2
mv nextcloud nextcloud-old
tar xjf nextcloud-$version.tar.bz2 -v
cp nextcloud-old/config/config.php nextcloud/config/
cd nextcloud
php occ upgrade
```

The upgrade process didn't show any warnings.

I found some outdated advice about manually purging spreed from @nickvergessen in #772
https://github.com/nextcloud/spreed/issues/772#issuecomment-384211357

Would be great to get advice how to fix this! Not necessarily with preservation of the Data.
If necessary I am happy to paste more Log information to help.

## Talk app

**Talk app version:** 10.0.6

**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MySQL

**PHP version:**  Version: 7.4.16 

**Nextcloud Version:** 20.0.7 => 20.0.8

### Server log (data/nextcloud.log).
<details>
```
{"reqId":"OfyyC1WXQsllzOvhoBFY","level":3,"time":"2021-03-05T11:05:37+00:00","remoteAddr":"10.0.2.4","user":"XXXXXXXX_admin","app":"index","method":"GET","url":"/apps/files","message":{"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT `r`.*, `p`.* FROM `oc_talk_rooms` `r` LEFT JOIN `oc_talk_participants` `p` ON (`p`.`user_id` = ?) AND (`p`.`room_id` = `r`.`id`) WHERE `p`.`user_id` IS NOT NULL' with params [\"dotplex_admin\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud_production.oc_talk_participants' doesn't exist","Code":0,"Trace":[{"file":"/var/www/nextcloud/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->"}
```
</details>

**Comment by d0niek** [comment]
Upgrade Talk to version **10.1.3**

**Comment by benks-io** [comment]
@d0niek true - only 10.0.6 is available in the /setting/apps

**Comment by nickvergessen** [comment]
> Probably you won't be able to upgrade Talk from /settings/apps (I don't know why :-/)

See https://github.com/nextcloud/spreed/issues/5295

**Comment by nickvergessen** [comment]
Regarding the issue when the participants table is dropped, you updated to 10.1 or 11 already and then redeployed the PHP code of 10.0
That will not work.

**Comment by d0niek** [comment]
Some time ago I got upgrade Talk from **10.0.\*** to **10.1.\*** in `/settings/apps` and everything was good.

Yesterday I removed Talk app just to try fix this [issue](https://github.com/nextcloud/spreed/issues/5148#issuecomment-791388640), install again from `/settings/apps` and it gave me ver. **10.0.6** and I got the same error like here so I had to make upgrade Talk to **10.1.3** manually.

**Comment by benks-io** [comment]
@nickvergessen Okay that explains why on other 20.0.8 instances the 10.0.6 Talk works fine. Talk wasn't updates.
So, a newer Version X of Talk should not be availably in an older version of NC, if X is not available in a newer Version of NC!
I guess this is an issue for the server repo. Without command line access NC Gui Admins are pretty lost here.

**Comment by nickvergessen** [comment]
Well Talk 10 is for Nextcloud 20 and Talk 11 is for Nextcloud 21.
The appstore will make sure you only get the correct version. But downgrading just doesn't work.

**Comment by benks-io** [comment]
@nickvergessen
Is it possible, that there was a new Version (>10.0.6) Available in 20.0.7 that was not (yet) available in the default NC 20.0.8 Instance?

**Comment by nickvergessen** [comment]
By mistake 10.1 was in the appstore for some hours. Downloads were below 50 by the time i removed it again. So, sorry if you are one of those.

**Comment by d0niek** [comment]
> By mistake 10.1 was in the appstore for some hours. Downloads were below 50 by the time i removed it again. So, sorry if you are one of those.

It's Ok. But now if I'm using ver. **10.1.3** it's Ok or some how I should return to **10.0.6**?

**Comment by benks-io** [comment]
No worries! ;) Good to know. What a coincidence!

**Comment by nickvergessen** [comment]
You can't return. Update to 10.1.3
