### ISSUE TITLE
Make links in chat clickable

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#533]
Currently when you paste a URL in the chat, it’s just text. Instead it should become a clickable link, and for better readability have the protocol stripped.

Same as https://github.com/nextcloud/server/issues/7609

**Comment by blizzz** [comment]
Corresponding  JS methods within OCP.Comments from https://github.com/nextcloud/server/pull/7680 should come in handy

**Comment by jancborchardt** [comment]
@blizzz mind helping out here so it could be in for Nextcloud 13? :)

**Comment by blizzz** [comment]
added to my list… if someone is faster to get 'round to it, don't hesitate…

**Comment by blizzz** [comment]
added in #579
