### ISSUE TITLE
🗒️ Create empty text document within conversation

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#5330]
Use case
- have a call with a group / colleague
- want to e.g. notes, brainstorm via whiteboard, etc.

Right now: or those one have to open files app, create desired file, share to conversation)

Better to have this direct in conversation, within this dialog probably? 
![image](https://user-images.githubusercontent.com/5836855/110133910-222bde00-7dcd-11eb-9566-d7e959dd371f.png)

- [x] API: Normal WebDAV + sharing
- [x] Web
- [x] ~~iOS~~
- [x] ~~Android~~

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/nextcloud-dialogs/issues/264

**Comment by nickvergessen** [comment]
But that might actually be a level further away, but not sure how scalable it is to put it directly into the menu. I think it needs at least one parent menu when I see all the things the file app allows to create

**Comment by Spartachetto** [comment]
No idea if it is too far fetched, but maybe it could be interesting to offer the possibility to create a project from the conversation and then to associate to the project all the available Nextcloud functionalities (creating files, calendar appointments, etc. ....)

**Comment by nickvergessen** [comment]
The projects feature is already there

**Comment by tobiasKaminsky** [comment]
> But that might actually be a level further away, but not sure how scalable it is to put it directly into the menu. I think it needs at least one parent menu when I see all the things the file app allows to create

- upload new files
- share from files
- create new

would be totally ok, in my opinion 👍

**Comment by nickvergessen** [comment]
### Priority

- [ ] Create new text document

### Minor

- [ ] ➕ menu like in files + Template picker support

**Comment by nickvergessen** [comment]
- [ ] Effort estimation to bring all the different types into the dropdown, instead of only text?

**Comment by tobiasKaminsky** [comment]
In this issue I would focus on text.
Text can give you a list of templates, with a preview.

You can get infos about it in: 
/ocs/v2.php/apps/files/api/v1/directEditing

I cannot find a real documentation, only the PR: https://github.com/nextcloud/server/pull/17625

If you need any further help/input, just ask.
