### ISSUE TITLE
video verification behavior

### ISSUE THREAD

**Issue by mapson01** [nextcloud/spreed#5346]
HI there 

video verification it is powerfull tool when you manipulate sesitive information but,.... some times the other person no turn on their camera because he fourd not necesary because the password can be shared via the chat window. of course it is not the idea!!. so you have to expend few minutes explaining and force to drop the call and try again.

the best solution  for me is to disable the char window when you get into a video verification forcing the other people to turn on the camera and audio and also to force to give the  password via audio channel.

in the same way you have to copy and paste the password when you generate de link and store somewhere waiting the other person call. For one or two requests there is no problem,  but when you have 10 file to deliver using video verification is very complicated to keep a manual list of paswords

the solution for this is the posibility of the  automatic password generation when video call is stablished and show in the screen

cheers
mapson

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
Seems to be covered by #2730
