### ISSUE TITLE
"Raised hand" state not working properly in the sidebar with multiple sessions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5349]
## Steps to reproduce
1. Join a conversation with 2 sessions
2. In the session with the lower id raise hand
3. 

### Expected behaviour
Sidebar shows you raise your hand

### Actual behaviour
Sidebar doesn't show you raise your hand

**Comment by PVince81** [comment]
When I tested it worked fine with internal signaling, but not with the HPB.
It was likely related to the way session ids are mapped.

**Comment by PVince81** [comment]
I did some quick debugging and it looks like it's going to be tricky.
The results of the participant list only contain one session id (likely the one from the aggregated "max" participant result).

Maybe we should adjust the participant API and make 'sessionId` an array ? Or for compatibility, add a new separate array that contains a list of known session ids for that participant.

**Comment by nickvergessen** [comment]
there is no compatibility needed atm as v4 is brand new

**Comment by PVince81** [comment]
for now I'll go with an extra property as I'm a bit afraid of all the code paths to touch that could potentially break in our frontend.
most code paths only need to know if the session is "0" or not

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5482

I was able to remove the "sessionId" attribute still as the affected frontend code was minimal.
