### ISSUE TITLE
Screenshare freezes on slow internet connection

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/spreed#5353]
## Steps to reproduce
1. Have a slow internet connection (officially 16mbps, real speed 8mbps)
2. Share screen

### Expected behaviour
Screensharing works. If connection is slow, the resolution should scale down, and go up again when connection is better. 

### Actual behaviour
After ~2-10mins, screensharing freezes for all other participants and does not return to normal

### Details
High performance backend enabled via struktur.de
Talk: 10.0.6
Nextcloud 20.0.4
Browser: Firefox 86.0
Tell me if you need more info.

### Related?
Found this https://github.com/nextcloud/spreed/issues/4994 and tried to switch to grid view but it did not bring back screen sharing.

**Comment by nickvergessen** [comment]
Anything in your browsers console (press F12)?
