### ISSUE TITLE
Emoji wont send; Could not post message: Request failed with status code 400

### ISSUE THREAD

**Issue by kasperireland** [nextcloud/spreed#5358]
## Steps to reproduce
1. log into nextcloud
2. go to talk app, open a conversation
3. send an emoji

### Expected behavior
The emoji should send normally without any issues.

### Actual behavior
Shows this error: Could not post message: Request failed with status code 400

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.1.1

## Browser

**Microphone available:** yes/no
yes

**Camera available:** yes/no
yes

**Operating system:** Windows/Ubuntu/...
windows

**Browser name:** Firefox/Chrome/...
chrome, and firefox

**Browser version:** 50.1/55/...
88.0.4324.190

**Comment by zonque** [comment]
This is still reproducible on Talk 11.1.2 and Nextcloud 21.0.1, both in the web frontend and the native Android app.

**Comment by zonque** [comment]
Okay, this was resolved by fixing the MySQL config:
https://docs.nextcloud.com/server/21/admin_manual/configuration_database/mysql_4byte_support.html
