### ISSUE TITLE
Spreed not working on Blackberry Q10 browser (WebKit)

### ISSUE THREAD

**Issue by yoyoyoyoyoy** [nextcloud/spreed#536]
## Steps to reproduce
1. When trying to get access with Blackberry Q10 (WebKit browser) to a call, Spreed asks to select camera, but then it fails to open call:

![img_20171227_131134](https://user-images.githubusercontent.com/34887001/34381307-0be2f814-eb08-11e7-8d8f-9783b1a89f45.jpg)
![img_20171227_131140](https://user-images.githubusercontent.com/34887001/34381308-0c042dcc-eb08-11e7-9a6c-a9dbcbf28504.jpg)

### Expected behaviour

Call should open.

### Actual behaviour

Call fails to open.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Blackberry OS 10

**Browser name:** Blackberry Browser (WebKit)

### Browser log

Web Inspector Console:

Access to microphone & camera failed 
Error {line: 7545, sourceURL: "https://www.example.com/nextcloud/apps/spreed/js/…plewebrtc.js?v=2cabe3e70c2908225b95c5a8bac949d4-4", stack: "https://www.example.com/nextcloud/apps/spreed/js/…e.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4633:16"}
line: 7545
message: "undefined is not a function (evaluating 'stream.getTracks()')"
sourceURL: "https://www.example.com/nextcloud/apps/spreed/js/simplewebrtc.js?v=2cabe3e70c2908225b95c5a8bac949d4-4"
stack: "https://www.example.com/nextcloud/apps/spreed/js/simplewebrtc.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:7545:20↵https://www.example.com/nextcloud/apps/spreed/js/simplewebrtc.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4167:6↵lib$es6$promise$$internal$$tryCatch@https://www.example.com/nextcloud/core/vendor/core.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4839:23↵lib$es6$promise$$internal$$invokeCallback@https://www.example.com/nextcloud/core/vendor/core.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4851:51↵lib$es6$promise$$internal$$publish@https://www.example.com/nextcloud/core/vendor/core.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4822:51↵lib$es6$promise$asap$$flush@https://www.example.com/nextcloud/core/vendor/core.js?v=2cabe3e70c2908225b95c5a8bac949d4-4:4633:16"
__proto__: Error
 webrtc.js:592
Error while accessing microphone & camera:  undefined is not a function (evaluating 'stream.getTracks()') 

</details>

## Spreed app

**Spreed app version:**
2.0.2

**Custom TURN server configured:** 
no (stun.nextcloud.com:443)

**Custom STUN server configured:** 
no (empty)

**Operating system**: 
Blackberry OS 10
**Web server:** 
Apache
**Database:** 
MySQL 
**PHP version:** 
5.6.32
**Nextcloud Version:** 
12.0.4

**Comment by nickvergessen** [comment]
In the version for 12 and 13 currently only Firefox and Chrome are supported.

**Comment by yoyoyoyoyoy** [comment]
Hi,

thanks...hm, any plans to intergrate WebKit in the near future? This 
would not only apply to iOS then, but also several other browsers I 
suppose...it seems WebRTC is supported since June 2017:

https://webkit.org/blog/7726/announcing-webrtc-and-media-capture/

Am 08.01.2018 um 11:43 schrieb Joas Schilling:
> In the version for 12 and 13 currently only Firefox and Chrome are supported.
>

**Comment by nickvergessen** [comment]
For iOS we also built a native app which is going to be released soon.

As for general webkit support, we have to check whether the library we use for webrtc handling supports it. Then we can do it.

**Comment by yoyoyoyoyoy** [comment]
Sure...thank you for the great work otherwise!

Am 08.01.2018 um 11:56 schrieb Joas Schilling:
> For iOS we also built a native app which is going to be released soon.
> 
> As for general webkit support, we have to check whether the library we use for webrtc handling supports it. Then we can do it.
>

**Comment by mario** [comment]
Hm, can't you run Android apps on BB?

**Comment by yoyoyoyoyoy** [comment]
You mean running another browser? Yes, I was just about to test this 
over the weekend...but the sandbox is consuming a lot of battery power, 
which is why I would rather prefer the native way...

Am 26.01.2018 um 12:32 schrieb Mario Đanić:
> Hm, can't you run Android apps on BB?
>

**Comment by mario** [comment]
@yoyoyoyoyoy no, I mean - BB should be able to run an Android app, and there is an Android app for Talk. https://play.google.com/store/apps/details?id=com.nextcloud.talk2

**Comment by yoyoyoyoyoy** [comment]
Ah, ok, thank you for the link, highly appreciated! Will test it...only, 
the real beauty would be to be able to use just WebRTC capable browsers 
across systems and devices...but we are not there yet, I know...

Btw, connection between Win 7 64 FF 57 and latest Chrome on Mac (don't 
know the specs) didn't work recentely...we could see ourselves, but the 
other didn't connect properly...

Am 26.01.2018 um 13:44 schrieb Mario Đanić:
> @yoyoyoyoyoy no, I mean - BB should be able to run an Android app, and there is an Android app for Talk. https://play.google.com/store/apps/details?id=com.nextcloud.talk2
>

**Comment by nickvergessen** [comment]
Closing in favor of the app and #1076
