### ISSUE TITLE
Log debugging information in case of call quality degradation

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5362]
**Is your feature request related to a problem? Please describe.**
Some times the call quality warning pop up appears but it isn't clear what is causing it.
An admin might want to debug their infrastructure or check the caller's computer for issuers.

**Describe the solution you'd like**
To find out where to start, it would be useful to display more technical information about what triggered the dialog.
Since we don't want to confuse regular users, I suggest logging this extra information into the browser console with console.warning(), so the admin can ask their users to copy that information for them.

**Describe alternatives you've considered**
Something dialog like Youtube's "stats for nerds"

**Comment by PVince81** [comment]
@danxuliu I had a quick check in the code but I'm not sure how much we can log.

There are some change handlers for the connection quality so we could at least log which one has triggered.
Not sure if we can log more, like number of lost packets, etc.

It's more about finding which one of the conditions documented in https://nextcloud-talk.readthedocs.io/en/latest/call-experience/#judging-the-connection-quality have triggered:

- Lost packages: 30% in the last 5 seconds
- Too few packages: Less than 10 packages per second
- Round trip time: above 1.5 seconds

**Comment by PVince81** [comment]
possible hack:
```
OCA.Talk.SimpleWebRTC.webrtc.peers.forEach(peer => {
	peer.pc.getStats().then(stats => {
		for (stat of stats.values()) {
			if (typeof stat.totalRoundTripTime === 'number') {
            			console.log('RTT:' + ((stat.totalRoundTripTime / stat.responsesReceived) * 1000))
			}
			if (typeof stat.packetsLost === 'number') {
            			console.log('Packets lost:' + stat.packetsLost)
			}
		}
	})
})
```

**Comment by nickvergessen** [comment]
I think it's mostly
> Too few packages: Less than 10 packages per second

As a temporary hickup

**Comment by wiswedel** [comment]
I get those warnings all the time when I'm in group calls of 4+ people, even though connection and CPU aren't under any pressure 🤷‍♂️

**Comment by PVince81** [comment]
I noticed that `nick` is always undefined when connecting as guest even though it's displayed in the video view.
Not sure how to work it around in the snippet above.

In any case, it seems it will be good to have a cleaner output.
One idea would be to have a simple command like `OCA.Talk.debug(true)` that enables additional views, like adding stats for each peer directly inside their panels. Or if too complicate or visually obtrustive, log something to the console periodically in a copy-friendly format.

**Comment by PVince81** [comment]
hmm, tried it on c.nc.com during company call but the nick attribute is also undefined (Firefox) even though I can see the display name of everyone in the grid

in my tests previously it was with Chromium

**Comment by PVince81** [comment]
I suppose that now that we have the distinction between session id and nextcloudSessionId it might be possible to just pick the user id and display name from the call participant model or from the participant store.

**Comment by PVince81** [comment]
I've done a more accurate test and it appears that `peer.nick` is always undefined when using HPB, but it's populated when not using HPB. From my understanding in recent code, we should already be sending the nick through data channels, at least initially, but it doesn't seem to happen. So not sure if it's a bug or intended.

In any case, it seems that whatever approach we use to attach those stats to a nick, it will require bigger code changes and won't be possible with just a simple console.log snippet.

**Comment by PVince81** [comment]
@danxuliu ^

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/4182 🤷‍♂️😅

**Comment by PVince81** [comment]
> #4182 man_shruggingsweat_smile

yes, but it should send it initially and stop after a while... maybe it did not send them at all...
might be possible to debug this by looking at the code from the PR... definitely looks like a bug

on the other hand, despite "peer.nick" not being defined, the UI seems to work fine.
so maybe we never use that value anywhere...

**Comment by danxuliu** [comment]
> so might need to investigate why we did not add it for everyone

The RTP stats when the HPB is not used or for the receivers when the HPB is used are generated by the browser in bursts (it may not report any lost packet in 5 seconds and then all of a sudden report all the previous lost packets) so even if the stats are smoothed the analysis is not reliable. This is why it is only enabled for now for the sender (which, on the other hand, is the most relevant, because you can tell if you are not hearing or seeing others, but without the warning you can not know if others are not hearing or seeing you).

Regarding the false positives in the connection quality warnings it seems to be related to the stats suddenly and briefly stalling. For example, the browser can be reporting something like 50, 50, 50, 50 packets, then all of a sudden 0, and then 100 (what should have been instead of 0 plus the value of the new report). I am on it.
