### ISSUE TITLE
mark as unread: conversation list update

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#5375]
## Steps to reproduce
1. set a message to unread (possible on the latest master)
2. Wait 24 sec (on my system) until the conversation is getting bold and shows the unread counter

### Expected behaviour
It should be bold within 1-2 secs
The conversation should go to the top of the list

**Comment by PVince81** [comment]
Even though we update the conversations store, the left sidebar doesn't seem to react

I even tried to switch from `Vue.set()` with a full fledge `commit('addConversation', conversation)` like we do for other code paths, it still doesn't refresh the left sidebar.

Something seems broken with the reactivity on this side.

**Comment by PVince81** [comment]
Aha! got it... we'd also need to update the value of `unreadMessages` and potentially also `unreadMention'.
For the former it means we need to count how many messages are present in the array starting from the current position.
Not sure if worth the effort, maybe we could just trigger `fetchConversation` again earlier for that entry so the server can compute more accurate values.

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/5378
