### ISSUE TITLE
Menu activity

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#5377]
## Steps to reproduce
1. Select the menu for the conversation user.
![obraz](https://user-images.githubusercontent.com/47037905/111598780-da935200-87cf-11eb-9867-439c064eede9.png)

Dark theme:

![obraz](https://user-images.githubusercontent.com/47037905/111601160-63ab8880-87d2-11eb-8871-541494d9d64d.png)

It is **active** at the very beginning of the "Add to favorites" menu.
_In my opinion there should be no active menu._

2. Hover the mouse cursor over another menu item, eg.: "Copy link".

3. Move the mouse cursor out of the menu.

![obraz](https://user-images.githubusercontent.com/47037905/111599718-e03d6780-87d0-11eb-810d-0584eeb1e0fd.png)

Dark theme:

![obraz](https://user-images.githubusercontent.com/47037905/111601491-b38a4f80-87d2-11eb-80b6-58306b3474f0.png)

The menu remains **active even** though you move the mouse cursor out of the menu.
_In my opinion there should be no active menu._

### Expected behaviour
Correct operation of the menu:
1. Inactive menu for "Add to favorites" when opening menu.
2. Do not leave the menu active when the mouse cursor is out of the menu.

### Actual behaviour
1. "Add to favorites" menu active when opening the menu.
2. Active menu when the mouse cursor is out of the menu.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
10.1.3

## Browser

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 50.1/55/...
86.0.1

**Nextcloud Version:** (see admin page)
20.0.8

**Comment by PVince81** [comment]
Not happening on master, I believe @ma12-co has fixed this recently.

**Comment by PVince81** [comment]
Happening on stable21, not sure if the styling changes are expensive to backport ? @ma12-co 

The active state was there by design I believe, it's mostly the position of the mouse or a cursor when using keyboard navigation.

**Comment by nickvergessen** [comment]
I think it's from a vue lib update, so no backport
