### ISSUE TITLE
messages by email

### ISSUE THREAD

**Issue by Slender1808** [nextcloud/spreed#5382]
I wish I could send a message to someone outside the platform.
A solution could be via email to contacts who are not on the platform.
An alternative that I found was a project called Delta chat that sends messages by email.

![desktop-screenshot](https://user-images.githubusercontent.com/50336793/111713173-d007a580-882d-11eb-90e0-8581db70d19c.png)

**Comment by nickvergessen** [comment]
Duplicate #5116

**Comment by Slender1808** [comment]
> Duplicado [# 5116](https://github.com/nextcloud/spreed/issues/5116)

I believe it is a different suggestion, my suggestion is to send the message itself

**Comment by nickvergessen** [comment]
Yeah, but there is a Mail app and combining or duplicating them is currently out of scope
