### ISSUE TITLE
Ability to modify / delete messages 

### ISSUE THREAD

**Issue by dtcg** [nextcloud/spreed#5383]
Users should be able to edit and delete their own messages.
(It would be a plus if Admins could also do that to anyone, for moderation sake.)

**Comment by easaw** [comment]
@dtcg that is already possible?

**Comment by kinimodmeyer** [comment]
deletion is possible since nextcloud version  21 / talk 11.
edit is not possible yet but there is already a issue: https://github.com/nextcloud/spreed/issues/1836

this can be closes as duplicate.
