### ISSUE TITLE
personally block the video of others to reduce internet use

### ISSUE THREAD

**Issue by framarini02** [nextcloud/spreed#5388]
When we go to disable other people's cameras for ourselves it would be useful not to receive the video stream of other people to reduce the use of internet bandwidth. Instead, now if you turn off other people's videos, we don't see their video streaming but it continues to get there.

**Comment by djtilo-ol** [comment]
Hi,
this feature of blanking out cams, but still streaming them is killing any motivation with colleagues as many clients have difficulties decoding so many streams with WebRTC.
In BBB they resolved the issue by limiting to 5 simultaneous videostrems on desktops and two on mobile devices, but with an option to cycle through the videos.
In addition they have added two buttons: disable webcams for me & disable screenshare for me - this reduces the load tremendously.
I'm refering to NC 20 with HPB on single server as provided by StrukturAG
Apart from this, video is activated by default without asking the user - this is problematic in schools when interacting with students.
By simply adding asking for access/permission would resolve the issue in my opinion.
Any added option would increase the acceptance.
Cheers, John Alistair
