### ISSUE TITLE
Set username BEFORE join a call in talk as guest

### ISSUE THREAD

**Issue by TheRaven500** [nextcloud/spreed#5389]
**Is your feature request related to a problem? Please describe.**
When a Guest is joining a meeting/chat, his username is "Guest" and he has to change it after joining.

**Describe the solution you'd like**
Guests should be asked for username BEFORE joining the meeting/chat.

**Describe alternatives you've considered**
Of course, you can easily change username after joining, but it would be better to ask this before. Not? :-)

**Comment by nickvergessen** [comment]
Duplicate of #855
