### ISSUE TITLE
Avatars not aligned

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#539]
I just noticed that avatars are not aligned after this commit on server https://github.com/nextcloud/server/commit/d497f79625a35330f8a07d9d6913281fa2d0deac#diff-db7674460739f8466f1f0e1de98bbf01

`display:block` is added to the `.avatar` element.
might be because of the jQuery `show()` function?

@nextcloud/designers any ideas?

![screen shot 2018-01-04 at 19 22 51](https://user-images.githubusercontent.com/4638605/34578733-5bc4da6c-f186-11e7-99c6-acbf8c28c7a6.png)

**Comment by jancborchardt** [comment]
@juliushaertl since the referenced server commit is from you, do you have an idea? :)

**Comment by juliushaertl** [comment]
Yes, this was actually a server issue that came from removing an old code path in the avatar plugin. Fix is in #7711

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/nextcloud/server/pull/7711
