### ISSUE TITLE
End meeting for all

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#5395]
**Is your feature request related to a problem? Please describe.**
As a moderator, I want to be able to end a meeting once and for all, so participants cannot misuse ongoing meeting rooms after the official meeting time is over.

**Describe alternatives you've considered**

- Remove every remaining participant one by one and then lock the room
- Remove every remaining participant one by one and then delete the room (both hard when there's a whole lecture hall full of uncontrollable users remaining in the room)
- Leave the call and delete the conversation while others are still in it --> not effective. call session remains open even after room is deleted

**Additional context**
Here's how it looks in Zoom:
![end meeting](https://user-images.githubusercontent.com/1804221/111981983-b35abe80-8b08-11eb-830c-ce15e4c46586.gif)

**Comment by PVince81** [comment]
@wiswedel for the workaround, in an upcoming 11.1.x you don't need to remove participants from the room. Just lock the room or enable lobby and it will kill the call. (ref https://github.com/nextcloud/spreed/pull/5215)

**Comment by nickvergessen** [comment]
> call session remains open even after room is deleted

That should not be the case.

**Comment by PVince81** [comment]
@ma12-co where to put such button ? should the "leave call" button be made into a dropdown of some sorts ?

**Comment by nickvergessen** [comment]
I think that is too trouble some.

Just for the record this is only for moderators.


cc @jancborchardt

**Comment by PVince81** [comment]
On the API side:

The leave call is a `DELETE on /call/{token}`.
I suggest we either add an argument `?all=true` or make it `/call/{token}/all` to end the call for all.

**Comment by PVince81** [comment]
@nextcloud/designers-talk for a design concept for where to put the button, as this is not trivial

**Comment by nickvergessen** [comment]
From my perspective this is something for a managed call view which should be at the tip section of the sidebar.
There is currently a button to end the lobby and I think this is were the call moderation should be completely.

**Comment by marcoambrosini** [comment]
I think this should go in the topbar. A split button seems to me like the most appropriate solution. Teams does exactly that.

![split teams](https://user-images.githubusercontent.com/26852655/124246547-5025f280-db21-11eb-8ae3-65d05dbf99e3.PNG)

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5981
