### ISSUE TITLE
No Push notifications in Samsumg S9+

### ISSUE THREAD

**Issue by kamalaesh-uk** [nextcloud/spreed#5398]
## Steps to reproduce
1. There are no optimizing apps used for ex: battery saver, backgroung apps killer etc.
2. All settings required to receive push notifications is already on in phone and app settings 
3. Push notifications works with other users for example in Caterpillar S61 phone with Android 9 

### Expected behaviour
Receive push notifications when somebody calls or writes me

### Actual behaviour
No notification received

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Android Version 9

## Talk app

**Talk app version:** v11.0.0

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system** Linux 5.4.0-65-genericx86_64

**Database:** pgsql

**PHP version:**7.4.3

**Nextcloud Version:** 20.0.8

accessibility: 1.6.0
  - activity: 2.13.4
  - apporder: 0.12.0
  - bookmarks: 4.1.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.4
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - encryption: 2.8.1
  - epubreader: 1.4.5
  - external: 3.7.2
  - extract: 1.3.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_3d: 0.3.3
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.2
  - impersonate: 1.7.0
  - keeweb: 0.6.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.3
  - maps: 0.1.8
  - metadata: 0.13.0
  - nextbackup: 21.1.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - occweb: 0.0.7
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.7.5
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - registration: 0.7.0
  - richdocuments: 3.7.17
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.6
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - talk_simple_poll: 1.3.0
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_email: 2.0.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - files_external
  - twofactor_gateway

**Nextcloud configuration:**

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "healthcloud.3d-medico.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/healthcloud.3d-medico.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forcessl": "1",
        "overwritehost": "healthcloud.3d-medico.com",
        "overwriteprotocol": "https",
        "updatechecker": false,
        "updater.release.channel": "cloudron",
        "logfile": "\/dev\/stderr",
        "loglevel": "3",
        "debug": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "integrity.check.disabled": true,
        "htaccess.RewriteBase": "\/",
        "simpleSignUpLink.shown": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "app_install_overwrite": [
            "occweb"
        ],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "2525",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by nickvergessen** [comment]
Anything in your servers nextcloud.log file?

**Comment by nickvergessen** [comment]
Does `sudo -u www-data php occ notification:test-push --talk YOURUSER` work?

**Comment by kamalaesh-uk** [comment]
Answer for the above comment was: 'No devices found for user'. Do you already know how to fix it?
PS: Log files does not work at the moment. I could only see a Loading symbol there.

**Comment by nickvergessen** [comment]
Then you need to reauthenticate with the phone

**Comment by kamalaesh-uk** [comment]
Thank you for the info. We tried that with our complete team. Three people had the same issue. Out of three, for one device (Samsung S9+) it still did not work out.

In the Log files there were no errors shown.
The message looks like as follows:
notification:test-push --talk ........:
Trying to push to 1 devicesLanguage is set to de_DEPrivate user key size: 1704Public user key size: 451Identified 1 Talk devices and 0 others.Device token:583Device public key size: 451Data to encrypt is: {"nid":752,"app":"........._notification_talk","subject":"Testing push notifications","type":"........._notifications","id":"6061c8ae"}Signed encrypted push subjectPush notification sent successfully
