### ISSUE TITLE
Disable avatar menu for guests

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5399]
## Steps to reproduce
1. Create a public conversation
2. Post a message as any logged in user
3. Copy link conversation
4. Log out
5. Open conversation link
6. Click on the three dots on previous the message's avatar

### Expected behaviour
No three dots to click, no avatar menu.

### Actual behaviour
Three dots visible and clickable. After clicking, an animation glitch quickly appears and disappears, then the menu is gone.
And the three dots are too.

## Talk app

**Talk app version:** Observed on stable21 640939a84fe271a91d3b4f5fdb2a27c216858d7d

**Comment by nickvergessen** [comment]
Vue lib issue I guess

**Comment by PVince81** [comment]
Yes and no, the vue lib will query the server and the server will return nothing and cause the glitch.

In our case we know we don't want the menu so we should set the property to disable the menu.
Unless there are use cases where we want (future) user actions for guests also ?

**Comment by nickvergessen** [comment]
Ah, might then be from the switch of participants to actor type

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5485
