### ISSUE TITLE
Flickering hover state of reply button

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5408]
## Steps to reproduce
1. Hover the reply button
2. ???
3. Disco 🕺🏼 

### Expected behaviour
Hover feedback

### Actual behaviour
Party:
![Peek 2021-03-24 13-44](https://user-images.githubusercontent.com/213943/112312548-331e8f80-8ca7-11eb-80d2-b610bee2cff0.gif)

**Comment by PVince81** [comment]
I think I've seen this happen to other action buttons as well, the hover has always been a bit off

**Comment by nickvergessen** [comment]
the problem is the date-tooltip appearing on first entry

**Comment by nickvergessen** [comment]
nop
