### ISSUE TITLE
Cant enable Talk on NC13 (beta 3/4): Unknown column 'token' in 'where clause'

### ISSUE THREAD

**Issue by moretocome** [nextcloud/spreed#543]
## Steps to reproduce
1. Try to enable "Talk" app
2. Get error message:
```
An exception occurred while executing 'SELECT * FROM `oc_spreedme_rooms` WHERE `token` = ''': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'token' in 'where clause'
```
3. Cry, cry, cry :)

### Expected behaviour
App should activate

### Actual behaviour
Does not :(

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Linux Mint

**Browser name:** Firefox

**Browser version:** 57

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration detail

**Operating system:** Linux 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

**Webserver:** nginx/1.13.8 (fpm-fcgi)

**Database:** mysql 10.1.23

**PHP version:** 7.1.12-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 Beta 4 - 13.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - audioplayer: 2.2.2
 - bookmarks: 0.10.1
 - calendar: 1.5.7
 - contacts: 2.0.1
 - dav: 1.4.6
 - deck: 0.3.0-beta1
 - dropit: 0.1.0
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - passman: 2.1.4
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - qownnotesapi: 17.5.0
 - rainloop: 5.0.6
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - caniupdate
 - comments
 - documents
 - drawio
 - encryption
 - external
 - federation
 - files_reader
 - firstrunwizard
 - flowupload
 - mail
 - music
 - nextcloud_announcements
 - password_policy
 - spreed
 - survey_client
 - systemtags
 - tasks
 - user_external
 - user_ldap
 - workin2gether

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "13.0.0.9",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "updatechecker": true,
    "updater.release.channel": "beta",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "cron_log": false,
    "logtimezone": "Europe\/Copenhagen",
    "maintenance": false,
    "theme": "",
    "filesystem_check_changes": 1,
    "quota_include_external_storage": false,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\Epub"
    ],
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "mysql.utf8mb4": true,
    "activity_expire_days": 90,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
Did you have an earlier version of the talk/spreed app installed before?

**Comment by moretocome** [comment]
Yes I did have an earlier version of the spreed app installed. I tried 
deleting the oc_spreed* tables, but then the talk-app complained that 
the tables where missing, so I restored them.

**Comment by mase76** [comment]
I have exactly the same issues.

**Comment by moretocome** [comment]
I just tried with the new 3.0 version of the app, but the issue persists.

**Comment by nickvergessen** [comment]
Hmm, did you run the latest 2.0.1 on Nextcloud 12, or was it some earlier version?

**Comment by mase76** [comment]
I came from an earlier version in nc12. I updated to nc13. Spreed failed with the db migration. So I deleted the old tables. But then I got errors, because spreed still tried to migrate from non-existant tables. I created empty tables with the old names, then I could enable spreed. Now it works. Spreed should not try a migration when no old tables exist.

**Comment by nickvergessen** [comment]
> Spreed should not try a migration when no old tables exist.

Admins should not delete database tables 🙊 Sorry, but you can not delete stuff and assume it magically works.

If you run postgres, the issue should be fixed with #584

For mysql I'm still unable to understand what is happening.

**Comment by nickvergessen** [comment]
@moretocome can you run the following query:
```sql
SELECT `configvalue`
FROM `oc_appconfig`
WHERE `appid` = 'spreed'
    AND `configkey` = 'installed_version';
```

And can you recall, did you ever install Spreed before?

**Comment by mase76** [comment]
Yes, I had installed spreed in nc12 before. After upgrading failed, I removed the app completely, not the tables.  Reinstalling brought SQL (Postgres) errors. So I removed the app again, and its tables. Reinstalling brought again SQL errors, the app looked for the old tables, which did not exist any more. In the end I got it to work. I don't know, why the app tried to migrate after a fresh installation.

**Comment by nickvergessen** [comment]
> I removed the app completely, not the tables.

> I don't know, why the app tried to migrate after a fresh installation.

Because that is not a "fresh installation". Anyway install errors with postgres have been fixed with #584

**Comment by nickvergessen** [comment]
3.0.1 has been pushed to the app store which should work better when updating an old version

**Comment by moretocome** [comment]
@nickvergessen I can confirm that 3.0.1 fixes the problem with mysql. Thank you! :)
