### ISSUE TITLE
@mention + line break + 2x backspace deletes all of my input

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5440]
## Steps to reproduce
1. Open a chat in Talk
2. Mention a person
3. Put some more text after the mention
4. Break the line with ctrl+enter
5. Press backspace to delete the line break
6. Press backspace again

### Expected behaviour
Last character of the *text* is deleted

### Actual behaviour
The whole line vanishes

## Talk app

**Talk app version:** c.nc.com

**Comment by nickvergessen** [comment]
Which browser?

**Comment by ChristophWurst** [comment]
FF

**Comment by PVince81** [comment]
does it happen in the new https://github.com/nextcloud/nextcloud-vue/tree/master/src/components/RichContenteditable ?

eventually this old editor in Talk will get replaced by that one in https://github.com/nextcloud/spreed/pull/4333 so we might not want to invest more time trying to hack around on the old one

**Comment by ChristophWurst** [comment]
This bug only happened to me very rarely. We can ignore this for a while until the new component is shipped and then I can retry :)

**Comment by PVince81** [comment]
closing then
