### ISSUE TITLE
Leave call button never becomes active

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5441]
I just joined a call on c.nc.com (Talk 11.0.0-alpha.3, Nc 21.0.0.18). The call worked fine, but the "leave call" button showed a spinner and never become active which meant that I had to close the window/tab in order to leave the call:

![image](https://user-images.githubusercontent.com/1589737/112946128-752b5380-9135-11eb-8cdb-7acb9c455b12.png)

**Comment by nickvergessen** [comment]
C.nc.com ia not running 11.0.0-alpha 3

**Comment by nickvergessen** [comment]
Was there something in the browser console? I already used the leave button multiple times today (on c.nc.c and local master) but it always worked.
