### ISSUE TITLE
Delete chat messages allows up to 6 hours only

### ISSUE THREAD

**Issue by variantolog** [nextcloud/spreed#5457]
Quote from Nextcloud Talk API documentation: 
> delete-messages  -  Allows to delete chat messages up to 6 hours for your own messages or when being a moderator.

I would like to be able to delete any messages, not just messages from the last 6 hours.

**Question:** Is it possible to change the number of hours in the _config.php_?
If not, I suggest adding this feature. 

P.S. I am a newbie member of the community - I apologize if I asked a question in the wrong direction :)

**Comment by nickvergessen** [comment]
It's not possible to configure this and currently a design decision to limit it to 6h. We will keep it like that for some time and reevalutate feedback we get.

**Comment by variantolog** [comment]
Please, tell me where I can put my feedback

**Comment by nickvergessen** [comment]
its here already :)

**Comment by variantolog** [comment]
For chat one-to-one (with two participants only), in my opinion, function of delete messages need for any timestamp.
For other conversations - let allows up to 6 hours only.
