### ISSUE TITLE
Spreed v10.1.2 is missing from the app store

### ISSUE THREAD

**Issue by axheli** [nextcloud/spreed#5466]
Hello my server is on version 10.1.2.but when you open up the App Store that version is not there my question is i removed it from my server and now i can't install the same version  back on i tried installing the 10.0.6 but didnt work can someone update the app package  please
<img width="1539" alt="Screen Shot 2021-04-10 at 2 19 00 PM" src="https://user-images.githubusercontent.com/59488153/114282150-dc83b600-9a07-11eb-8014-fc6c25b762a7.png">

https://github.com/nextcloud/spreed/releases/tag/v10.1.2

**Comment by nickvergessen** [comment]
10.1 is a preview line and not going to the app store, as the appstore will always give 10.1 with some experiments instead of 10.0.6/7

With 11 forward this is being "fixed" https://github.com/nextcloud/spreed/issues/5295

**Comment by axheli** [comment]
Since my server was on 10.1 and if i install 10.0 i get error what should i do ?
