### ISSUE TITLE
Can not enable Talk 11.1.1 on NC 21

### ISSUE THREAD

**Issue by blacknred0** [nextcloud/spreed#5477]
## Steps to reproduce
1. Go to apps
2. Enable Talk in NC 21

### Expected behaviour
Install Talk version `11.1.1`

### Actual behaviour
I get this error

```
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

## Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud Version:** 21.0.1

**Comment by blacknred0** [comment]
Just notice an update on spreed for `11.1.2` and still experiencing same behavior.

**Comment by nickvergessen** [comment]
See https://docs.nextcloud.com/server/21/admin_manual/configuration_database/mysql_4byte_support.html
