### ISSUE TITLE
Description field changes getting lost on clicking outside of field is unexpected

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#5479]
## Steps to reproduce
1. Edit the description field
2. While doing so, look something up elsewhere (like in the Calendar)
3. Accidentally click outside of the field, e.g. to focus the page again.

### Expected behaviour
Nothing of note happens, I can continue to edit the description.

### Actual behaviour
The changes so far are lost due to the "discard on clicking outside of the field"-logic. However since we have both buttons for Cancel and Confirm, we should only do something when either of those buttons are clicked.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5668
