### ISSUE TITLE
Video doesn't work anymore with firefox

### ISSUE THREAD

**Issue by tigermick** [nextcloud/spreed#5481]
## Steps to reproduce
1.Start a call with another user of a nextcloud server with web version in firefox
2.You can see your contact join you but impossible to start call (circle spin endless)

### Expected behaviour
Normaly, you start a call with another user and call start and you can see and hear him.
Sooner, all worked fine with firefox and turn server test in setting had success.
Today, all works fine again with chromium but not with firefox (turn server test and call)

### Actual behaviour
impossible for your contact to join you

## Talk app

**Talk app version:** 10.0.7

**Custom Signaling server configured:** yes/**no** and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** **yes**/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
my coturn server in the same machine

**Custom STUN server configured:** **yes**/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
my coturn server in the same machine

## Browser

**Microphone available:** **yes**/no

**Camera available:** **yes**/no

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 87.0

### Browser log
In firefox dev console :
NS_ERROR_FAILURE: PeerConnection.jsm:510
    __init resource://gre/modules/media/PeerConnection.jsm:510
    testServer https://domainname/owncloud/apps/spreed/js/admin-settings.js?v=ad3d1b55-0:380
    testServer self-hosted:1173
    ze https://domainname/owncloud/apps/spreed/js/admin-settings.js?v=ad3d1b55-0:27
    n https://domainname/owncloud/apps/spreed/js/admin-settings.js?v=ad3d1b55-0:27
    _wrapper https://domainname/owncloud/apps/spreed/js/admin-settings.js?v=ad3d1b55-0:27

## Server configuration

**Operating system**: Debian

**Web server:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.27

**PHP version:** 7.4.16

**Nextcloud Version:** 20.0.9 - 20.0.9.1

**List of activated apps:**
Enabled:
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - bruteforcesettings: 2.1.0
 - calendar: 2.2.0
 - cloud_federation_api: 1.3.0
 - contacts: 3.5.1
 - contactsinteraction: 1.1.0
 - cookbook: 0.8.4
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - files: 1.15.0
 - files_external: 1.11.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_videoplayer: 1.9.0
 - groupfolders: 8.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.4
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - passwords: 2021.4.0
 - photos: 1.2.3
 - previewgenerator: 3.1.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.7
 - support: 1.3.0
 - survey_client: 1.8.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - accessibility
 - comments
 - encryption
 - end_to_end_encryption
 - federation
 - files_accesscontrol
 - files_pdfviewer
 - files_versions
 - firstrunwizard
 - keeweb
 - social
 - systemtags
 - user_ldap

**Nextcloud configuration:**

### Server log (data/nextcloud.log)
no log about this

**Comment by PVince81** [comment]
What happened before it stopped working:
- Was there an update of NC or the Talk app ?
- Was there an update of browsers or the TURN servers ?
- Are the certificates still up to date or did some expire maybe ?

I have Firefox 87.0 here and been doing calls these days which worked fine in our setup.

**Comment by tigermick** [comment]
I don't know because i don't use firefox frequently. I use talk android app.
The last time where all worked fine was several weeks sooner (maybe months).
I think talk and firefox have be updated  ... I don't remember if i had NC 20 or NC 21 ...
But if all work fine on chromium (video and turn/stun test), the problem is in firefox ... no ?

**Comment by tigermick** [comment]
I continue to search a solution and when I try to test turn serveur from firefox, i have no coturn log like if nothing was sent by firefox whereas with chromium, I receive the request (I can see it in coturn log) and my coturn server  success to answer ...

In firefox, i have found this log in console : 
`Uncaught 
Exception
columnNumber: 0
data: null
filename: "https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0"
lineNumber: 380
message: ""
name: "NS_ERROR_UNEXPECTED"
result: 2147549183
"testServer@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:380:77409\nz.methods.debounceTestServer<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:380:76923\nl@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:65:3015\nsetTimeout handler*l@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:65:2981\nsetTimeout handler*u@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:65:3128\nupdateServer@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:380:78755\nze@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:11252\nn@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:12996\nyr/s._wrapper@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:44399\nEventListener.handleEvent*yr@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:44425\nit@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:13275\nAr@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:44799\nv@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:53621\nd@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52915\nm@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:53378\nd@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52900\nla</<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:56922\ne.prototype._update@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:34351\nr@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64431\nfn.prototype.get@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:26610\nfn@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:26528\nwn.prototype.$mount/<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64455\nwn.prototype.$mount@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64602\ninit@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:19337\nd/<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52509\nd@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52786\nm@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:53378\nd@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52900\nla</<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:56922\ne.prototype._update@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:34351\nbeforeMount/this._update@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:62230\nr@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64431\nfn.prototype.get@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:26610\nfn@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:26528\nwn.prototype.$mount/<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64455\nwn.prototype.$mount@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:64602\ninit@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:19337\nd/<@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52509\nd@https://myDomain/nextcloud/apps/spreed/js/admin-settings.js?v=b47e2f67-0:27:52786\n"`

Can it help you to find where is the problem ?

**Comment by nickvergessen** [comment]
NS_ERROR_FAILURE is nothing we can help you with. It sounds like there is an issue with your server, the domain or the certificate of that server. So unless you can provide us with a link + call of your server we can't help you really.

**Comment by tigermick** [comment]
Hi,
I partially found the problem ..
it looks like i was using a blocked port for coturn service ... this port worked fine earlier but I don't know why or when, This port is now blocked (i can't find any blocking rules in iptables or in my router ...).
i am using another port and the test in nextcloud is working fine in firefox now (not sure why, chromium worked fine with this blocked port ; in all cases, nextcloud turn test was OK)
thanks for trying to help me and sorry for disturbbing for nothing
