### ISSUE TITLE
Reply button overlap on two row messages

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5486]
## Steps to reproduce
1. Type a message like in the screenshot and send it
2. Open the participants panel and conversations panel
3. Hover the reply button

### Expected behaviour
Buttons appear below the date

### Actual behaviour
Reply button overlaps the text

<img width="449" alt="image" src="https://user-images.githubusercontent.com/277525/114885520-04f42180-9e07-11eb-8e5e-faa8c9315c62.png">

## Talk app

**Talk app version:** Observed on c.nc.com and locally on master (c5015f53d1faeb097ed9b251037954ab850779f0)

Screen size is 1920x1080 with "Force font DPI" set to 144 on my Plasma workspace.

@ma12-co I guess the button should move to another row ?

**Comment by PVince81** [comment]
when zooming the browser to 110% it becomes 4 rows but still the logic decides that it's not tall enough:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/277525/114886287-b5622580-9e07-11eb-9162-52701f05783a.png">

probably using a pixel value of 56px is not accurate enough for all scenarios, especially considering bigger/smaller font sizes when zooming: https://github.com/nextcloud/spreed/blob/master/src/components/MessagesList/MessagesGroup/Message/Message.vue#L602

**Comment by PVince81** [comment]
ah! after refreshing the page the zoomed page has fixed itself.

so there are two bugs here:

- [ ] fix "is tall enough" calculation to be more accurate
- [ ] recalculate "is tall enough" in case of window resize (debounced)

**Comment by nickvergessen** [comment]
We should also fix the position. The jumping left and right from multi line vs. single line messages is way to annoying when you want to reply quickly.
![2021-04-15 18_57_34](https://user-images.githubusercontent.com/213943/114908800-bcdff980-9e1c-11eb-9042-a0e67e87169d.png)

**Comment by ma12-co** [comment]
A solution to this could be hiding the read status when hovering/focusing and shifting both reply and actions button to the right

**Comment by nickvergessen** [comment]
Makes the tooltip not-discoverable anymore, but I think it's fine. Should mostly be known what it means.
