### ISSUE TITLE
Make sharing vcard files display better

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5498]
## Steps to reproduce
1. Create a contact in the contacts app or somewhere else and download it
2. Share the vcard (.vcf) to a talk conversation

### Expected behaviour
It looks appealing and clear that it is a contact, maybe some meta data is displayed (FN, photo?)

### Actual behaviour
![Bildschirmfoto von 2021-04-19 10-54-28](https://user-images.githubusercontent.com/213943/115209193-aaf0a600-a0fd-11eb-8255-6e857e8a5964.png)

**Comment by PVince81** [comment]
at first I thought of [OpenGraph](https://ogp.me/) but it seems it's too specific for web pages

**Comment by nickvergessen** [comment]
> at first I thought of OpenGraph but it seems it's too specific for web pages

Could still work: title is FN, image is an avatar when one is given or a placeholder image, link leads to the contact file?
