### ISSUE TITLE
New function: Possibility to create anonymized rooms ?

### ISSUE THREAD

**Issue by migulen** [nextcloud/spreed#5502]
It would be a function for the moderator/creator of the room.

In this "blind chat" the participants can not be identified with their username (or full name) between them. They must be "renamed/called" like "anon1,anon2,anon3", or something like that.

**Comment by nickvergessen** [comment]
This will not work without major changes across all parts of the platform and therefor unlikely to happen any time in the future.
So I'm closing this.

**Comment by migulen** [comment]
Thanks for your attention and answers. It wasn't a bogus or tendentious question.

It was related to some scenarios like this:

https://www.researchgate.net/publication/323255771_Effects_of_Anonymity_Discourse_Analysis_of_Conversation_in_Electronic_Brainstorming/download

But understand the technological difficulties to achieve this goal are not on route.

You are doing GREAT. Keep going on.

Thanks.

**Comment by migulen** [comment]
> If you really have the need for this maybe guest accounts would fit your need

Guest accounts ?  Hummm, i'll try this (that):

https://apps.nextcloud.com/apps/guests

But it's for different approach.  This issue... I think has some similarities:

https://github.com/nextcloud/talk-android/issues/261
