### ISSUE TITLE
Guest usernames and avatar placeholders are not updated in sidebar (Chat, Participants)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#551]
It looks nice in the main view with colored placeholders and names below, but in the sidebar it’s just grey placeholders and »Guest«. That makes it very confusing who wrote what, and also impossible to kick or promote a specific person. ;)

Chat:
![screenshot from 2018-01-09 19-07-22](https://user-images.githubusercontent.com/925062/34737845-a23eb932-f577-11e7-8746-11195783bf77.png)
And Participants:
![screenshot from 2018-01-09 19-07-04](https://user-images.githubusercontent.com/925062/34737862-ac1796cc-f577-11e7-8006-240fc3de26bd.png)

@Ivansss @danxuliu @nickvergessen

**Comment by nickvergessen** [comment]
Yeah that's to be expected at the moment, because they are not stored in the database

**Comment by jancborchardt** [comment]
@nickvergessen @Ivansss just came up in the company call with everyone being guests. ;)
