### ISSUE TITLE
Screenshare icon not rendered

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5510]
## Steps to reproduce
1. Start a call on master
2. Try to share your screen

### Expected behaviour
You see Monitor vue material design icon

### Actual behaviour
The icon slot is not rendered

There was a lot activity recently:
https://github.com/nextcloud/nextcloud-vue/commits/master/src/components/Actions/Actions.vue

Also the icon appears when you delete all actions but one:
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L99-L123

So the talk code seems correct and something is broken in the hasMultipleActions part of the Actions component

cc @PVince81 @ma12-co @skjnldsv

**Comment by skjnldsv** [comment]
` <ActionButton v-if="!screenSharingMenuOpen" @click.stop="toggleScreenSharingMenu" /> ` What is this? No text? No icon?

Regarding the icons, none of the Actions you listed actually uses a slot, they use icon classes.
So my guess is that there is a caching issue on the iconsvg  api endpoint of server?

**Comment by nickvergessen** [comment]
The Actions component uses the icon-slot 
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L83-L97

**Comment by skjnldsv** [comment]
Try using vshow insteadof vif?

**Comment by ma12-co** [comment]
I investigated a bit and, rolling the actions back to before this solves the issue. I can't find what exactly broke it but it maybe rings a bell @skjnldsv 
https://github.com/nextcloud/nextcloud-vue/commit/1dcc668942d9394a0a31dc0451c85f267e4dad37#diff-bf9598f4696de7ddaf60040e215cc409afeaa80b7b515dbe450a2734dfab1678

**Comment by skjnldsv** [comment]
Well, how many actions are there simultaneously in the Actions?
If there is only one, then it will always use the icon from the action within.

So if you're using the icon-slot for the default MENU icon, it will not be displayed.

This will show the `icon-add` icon
```
<Actions default-icon="icon-add">
	<ActionButton icon="icon-user">....</ActionButton>
	<ActionButton icon="icon-group">....</ActionButton>
</Actions>
```

This will show the `icon-user` icon because we render the UNIQUE action within
```
<Actions default-icon="icon-add">
	<ActionButton icon="icon-user">....</ActionButton>
</Actions>
```

**Comment by skjnldsv** [comment]
Monitor and MonitorOff are here being used as the Actions MENU ICON, not a single Action icon.

**Comment by skjnldsv** [comment]
Wow, this template is weird. Why are the first 2 ActionButton using the same v-if and same question for the last 2 ActionButton?
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L101
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L107

https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L113
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L119

**Comment by nickvergessen** [comment]
https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actions-1
But action has a slot `icon` ? Can't we use it when there are multiple actions?

Oh wait, now I get it:
All conditions are false in Firefox (as we can't pick between single screen or window, so it only has this action and therefor ignores the slot icon and uses the icon of this action but it has none:
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L99

Let me try that.

**Comment by skjnldsv** [comment]
Actions's icon slot is for the menu. It supersede the `defaultIcon` prop.
The default behaviour still stands, when only one action is shown within an`Actions` component, it is not displayed within the dropdown, but straight away. So the displayed icon will be the one of the rendered `ActionXxxxx`, not the one of the `defaultIcon` prop

**Comment by skjnldsv** [comment]
If you play with the `forceMenu` prop, you will see the differences I'm talking about, even with a single `ActionXxxx` inside the `Actions` component

**Comment by nickvergessen** [comment]
Okay, so when you specify a slot-icon:Ö
https://github.com/nextcloud/spreed/blob/514405d556785ad9cf0d3ef925962b61e52a57d9/src/components/CallView/shared/LocalMediaControls.vue#L82-L97

and only have a single action with an icon:
```vue
				<ActionButton
					v-if="!screenSharingMenuOpen"
					icon="icon-share-window"
					@click.stop="toggleScreenSharingMenu" >
					Share a single window
				</ActionButton>
```

Nothing is displayed.

Deleting the slot-icon will make the icon of the action appear

**Comment by skjnldsv** [comment]
![Peek 24-04-2021 13-46](https://user-images.githubusercontent.com/14975046/115957565-86cd0480-a503-11eb-90bf-9adfb64f40bc.gif)

**Comment by nickvergessen** [comment]
We don't use the prop default-icon but the slot so we can use a material design icon, and that is what breaks it.

but it's fine, now that I know we can wrap the slot icon with a `v-if="has multiple actions"` a like construct until the component is fixed

**Comment by skjnldsv** [comment]
> prop default-icon but the slot so we can use a material design icon

It's the same. Wether you provide a component or a default-icon, they will  be used for the same usage. Replacing the default Actions-menu icon

**Comment by nickvergessen** [comment]
No, the fallback to an prop-icon action doesnt work when the actions component is in slot-icon mode ;)
