### ISSUE TITLE
1:1 chat room empty

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5511]
I just wanted to chat with Roeland on our instance but if I go into the room it looks like this (he seems to be no longer in the room):

![image](https://user-images.githubusercontent.com/1589737/115871236-933c5900-a440-11eb-8895-653192dc5034.png)

Probably he cleaned up his room list on the left but how can I now get back chatting with him. Do I have to leave the room as welll and start from scratch?

It is a bit confusing.

**Comment by schiessle** [comment]
now he is back in the participant list... Just a hiccup of the server. Or did he got a notification about my message and could re-join the room?

**Comment by nickvergessen** [comment]
He is readed when you write something, mention them or start a call, but I agree its confusing to participate like that.
I guess we need to "hack" the participant list in this case and add the second person no matter if they are still in the conversation or not.
