### ISSUE TITLE
All conversations gone after manual upgrade from Nextcloud 20.0.9 to 21

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/spreed#5518]
### Steps to reproduce
Upgrade from NC 20.0.9 to 21 manually via cli

### Expected behaviour
Talk conversations persist across upgrades

### Actual behaviour
Talk conversations purged. I think they are still in the database but not sure (OC_TALK_* still has a lot of entries but I dont know what i'm looking at)

## Server configuration detail

**Operating system:** Linux 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 21.0.1 - 21.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** NC 20.0.9 

**Where did you install Nextcloud from:** Manually 

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - analytics: 3.4.1
 - announcementcenter: 5.0.0
 - appointments: 1.9.1
 - apporder: 0.12.0
 - auto_groups: 1.3.1
 - bruteforcesettings: 2.1.0
 - calendar: 2.2.0
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - data_request: 1.8.0
 - dav: 1.17.1
 - deck: 1.4.1
 - documentserver_community: 0.1.9
 - event_update_notification: 1.2.0
 - external: 3.8.1
 - extract: 1.3.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_antivirus: 3.2.0
 - files_automatedtagging: 1.11.0
 - files_downloadactivity: 1.10.0
 - files_fulltextsearch: 21.0.1
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - flow_notifications: 1.1.0
 - fulltextsearch: 21.0.0
 - groupfolders: 9.0.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.9.5
 - metadata: 0.13.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 6.3.0
 - password_policy: 1.11.0
 - passwords: 2021.4.0
 - photos: 1.3.0
 - previewgenerator: 3.1.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.10.0
 - ransomware_protection: 1.10.0
 - registration: 1.2.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.1.2
 - support: 1.4.0
 - survey_client: 1.9.0
 - suspicious_login: 4.0.0
 - systemtags: 1.11.0
 - talk_simple_poll: 1.3.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.8.0
 - timemanager: 0.1.8
 - twofactor_backupcodes: 1.10.0
 - twofactor_email: 2.0.0
 - twofactor_nextcloud_notification: 3.1.2
 - twofactor_totp: 6.0.0
 - twofactor_u2f: 6.1.0
 - twofactor_webauthn: 0.2.9
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_saml: 4.1.0
 - user_status: 1.1.1
 - video_converter: 1.0.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflow_pdf_converter: 1.6.0
 - workflow_script: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - circles
 - cospend
 - duplicatefinder
 - encryption
 - files_clipboard
 - files_external
 - files_frommail
 - forms
 - printer
 - recommendations
 - twofactor_gateway

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "defaultapp": "files",
    "versions_retention_obligation": "auto, 365",
    "knowledgebaseenabled": true,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "cloud.domain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "21.0.1.1",
    "overwrite.cli.url": "https:\/\/cloud.domain.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": "true",
    "skeletondirectory": "",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "log.condition": {
        "apps": [
            "admin_audit"
        ]
    },
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "7200",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "simpleSignUpLink.shown": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Etc\/UTC",
    "htaccess.RewriteBase": "\/",
    "share_folder": "\/Shared",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF"
    ],
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "default_phone_region": "us",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 1800enabled: yesinstalled_version: 1.11.0s01_lastChange: 1602105310s01has_memberof_filter_support: 0s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: s01ldap_base_groups: s01ldap_base_users: s01ldap_cache_ttl: 600s01ldap_configuration_active: 0s01ldap_default_ppolicy_dn: s01ldap_display_name: displayNames01ldap_dn: s01ldap_dynamic_group_member_url: s01ldap_email_attr: s01ldap_experienced_admin: 0s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: s01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: s01ldap_host: s01ldap_login_filter: s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_matching_rule_in_chain_state: unknowns01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: s01ldap_userlist_filter: s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0

**Operating system:** Ubuntu

## Logs

<details><summary>Web server error log</summary>

```
https://hastebin.waaromzomoeilijk.nl/idebuloxob.sql
```
</details>

<details><summary>Nextcloud log</summary>

```
https://hastebin.waaromzomoeilijk.nl/uwiluyohec.json
https://hastebin.waaromzomoeilijk.nl/etiwarusin.json
```
</details>

<details><summary>Browser log</summary>

Navigating away, leaving conversation App.vue:217
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Comments.View initialized comments-app.js:31:21
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Notifications permissions granted App.vue:306
OCA.Viewer initialized Viewer.js:49:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:316
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
Setting current user App.vue:316
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
Detected browser Firefox 87 (87.0) browserCheck.js:29:11
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
session heartbeat polling started session-heartbeat.js:97:9
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
OCA.Sharing.ShareSearch not ready init-collections.js:44:10
OCA.Sharing.ShareSearch not ready init-collections.js:44:10
X-Nextcloud-Talk-Hash initialised:  7b0c54aed4fd34113fbc9f5b83fd7368a0f40109 talkHashStore.js:64:11
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 7 globals.js:60:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }

</details>

**Comment by nickvergessen** [comment]
The actual issue seems to be that your high-performance backend seems to throw a 403 error.
Check the credentials and settings of that one.

**Comment by nickvergessen** [comment]
Another error in your server error log:
PHP message: PHP Warning:  require_once(/var/www/nextcloud/lib/versioncheck.php): failed to open stream: Permission denied in /var/www/nextcloud/remote.php on line 35

make sure all files are owned by the correct user+group and have the correct file permissions set.

**Comment by ezraholm50** [comment]
Good call, secret was off. Fixed now, thanks. 
Also applied permissions as per documentation just now. 

Apache log (first entry of about 2.5 hours ago)
```
ud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\\DBAL\\Connection->getWrappedConnection()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(226): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\\DB\\Connection->executeQuery()\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/AppConfig.php(345): OC\\DB\\QueryBuilder\\QueryBuilder->exe...'
[Sun Apr 25 09:43:09.909619 2021] [proxy_fcgi:error] [pid 83116:tid 140593137186560] [client 54.226.205.62:18081] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Doctrine\\DBAL\\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432? in /var/www/nextcloud/lib/private/DB/Connection.php:85\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\\DBAL\\Connection->getWrappedConnection()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(226): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\\DB\\Connection->executeQuery()\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/AppConfig.php(345): OC\\DB\\QueryBuilder\\QueryBuilder->exe...'
[Sun Apr 25 10:00:03.801569 2021] [mpm_event:notice] [pid 83113:tid 140593577724992] AH00493: SIGUSR1 received.  Doing graceful restart
[Sun Apr 25 10:00:03.816600 2021] [mpm_event:notice] [pid 83113:tid 140593577724992] AH00489: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Sun Apr 25 10:00:03.816615 2021] [core:notice] [pid 83113:tid 140593577724992] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 25 10:55:45.639107 2021] [core:warn] [pid 83113:tid 140593577724992] AH00045: child process 91209 still did not exit, sending a SIGTERM
[Sun Apr 25 10:55:47.643953 2021] [core:warn] [pid 83113:tid 140593577724992] AH00045: child process 91209 still did not exit, sending a SIGTERM
[Sun Apr 25 10:55:49.646233 2021] [core:warn] [pid 83113:tid 140593577724992] AH00045: child process 91209 still did not exit, sending a SIGTERM
[Sun Apr 25 10:55:51.648525 2021] [core:error] [pid 83113:tid 140593577724992] AH00046: child process 91209 still did not exit, sending a SIGKILL
[Sun Apr 25 10:55:52.649263 2021] [mpm_event:notice] [pid 83113:tid 140593577724992] AH00491: caught SIGTERM, shutting down
[Sun Apr 25 10:55:56.173386 2021] [mpm_event:notice] [pid 105867:tid 140649888087104] AH00489: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Sun Apr 25 10:55:56.173503 2021] [core:notice] [pid 105867:tid 140649888087104] AH00094: Command line: '/usr/sbin/apache2'
[Sun Apr 25 11:23:01.865469 2021] [proxy_fcgi:error] [pid 105869:tid 140649535870720] (-102)Unknown error -102: [client 138.68.249.116:40536] AH01075: Error dispatching request to : (reading input brigade)
```

**Comment by ezraholm50** [comment]
Btw the timestaps on the `PHP Warning: require_once(/var/www/nextcloud/lib/versioncheck.php): failed to open stream: Permission denied in /var/www/nextcloud/remote.php on line 35` are from this morning, those where before the upgrade. I've updated about 5/6 hours after the first entry of those errors.

**Comment by nickvergessen** [comment]
But I can't see any logs from the update.
Can you check the updater folder log files?

**Comment by ezraholm50** [comment]
I've looked for update entries but i can't find it anywhere unfortunately.
I've noticed the nextcloud log also has a blank section from around the update time of a few hours.

Any advice? For for I'm going through the rotated logs. 
```
root@cloud:/var/log/nextcloud# ls /var/www/nextcloud/updater/
index.php  updater.phar
```

**Comment by ezraholm50** [comment]
https://hastebin.waaromzomoeilijk.nl/uwiluyohec.json
https://hastebin.waaromzomoeilijk.nl/etiwarusin.json

Thanks for the effort Joas!

**Comment by nickvergessen** [comment]
So that indicates to be the same issue again with a class being loaded/cached already with old content but the code was replaced on the update. This is not fixable for us in the app.

**Comment by ezraholm50** [comment]
Alright, and what now? Any pointers on where to look or what to do?

**Comment by nickvergessen** [comment]
If you have a backup you can restore it from there and do the update manually by downloading the zip and pjt it in place and then opening Nextcloud

**Comment by ezraholm50** [comment]
We have 50+ users that have been using the system for 2 or 3 days already, restoring the backup will overwrite files/calendars/contacts that they added since. Isn't there a way to go via the DB/migrate commands manually?

**Comment by skynick11** [comment]
The similar problem - migration from 20.0.9 to 20.0.1/Talk 11.2.1 and there are no old conversations... 

Tables oc_talk_guestnames and oc_talk_attendees are empty, but  oc_talk_guests and oc_talk_participants are deleted.

At this moment in the test environment I found a strange way to migrate:
- pg_dump dbname > dbname.sql
- make an upgrade of the nextcloud and all occ upgrade
- manually revert Talk to 11.1.2 (not disable it)
- psql < dbname.sql (ignoring warnings and errors... - it restores oc_talk_guestnames and oc_talk_attendees, but i don't know what else - in another clone from the same source, but with an attempt to restore only oc_talk_guestnames and oc_talk_attendees and run "occ migrations:migrate spreed", I see migrated oc_talk_guestnames and oc_talk_attendees but no conversations in the Talk app)
- remove the Version10000Date20201012144235.php file and delete all Version10000* and Version 11000* records from oc_migrations for app spreed (make a dump of this table before)
- run occ migrations:migrate spreed
- restore 10000Date20201012144235 record in oc_migrations

The Talk app shows old conversations, are oc_talk_guests and oc_talk_participants migrated to oc_talk_guestnames and oc_talk_attendees...

- upgrade Talk to current version, the conversations are survived.

**Comment by szaimen** [comment]
I've unfortunately got the same issue after updating to NC21.0.2. Fortunately there is currently no important chat in there and just a few so I don't need the chat history and can just recreate the chats manually.

**Comment by szaimen** [comment]
cc @enoch85 this might be something that needs to be changed in the update script of the VM. If I am correct does a configured HPB need to be accessible during spreed app updates. Otherwise all chats might vanish.

**Comment by skynick11** [comment]
updating from NC20 to NC21.0.2, isn't it?

if yes - it's possible to restore dropped chats (but if there is the backup of the database) without restoration of the whole database:
- Needed tables are: oc_talk_participants (will be migrated to oc_talk_attendees, which is empty), oc_talk_guests (will be migrated to oc_talk_guestnames, which is also empty), oc_talk_rooms (some records could be removed after migration) and oc_comments (also some records could be removed)... It's also possible manually merge current and backup data for those tables, if needed.
- In case of postgresql it's also needed to apply "SELECT pg_catalog.setval('public.<tablename>_id_seq', XXX, true" commands (from the backup or with recalculated values XXX), otherwise it's possible to obtain "can not create the conversation" and other errors with "Unique violation... duplicate key value violates unique constraint" in log(s).
- edit apps/spreed/lib/Migration/Version10000Date20201012144235.php:

```
--- Version10000Date20201012144235.php.ori      2021-05-21 00:50:55.451743461 +0300
+++ Version10000Date20201012144235.php  2021-05-21 01:38:44.568883954 +0300
@@ -43,11 +43,13 @@
                $schema = $schemaClosure();

                $table = $schema->getTable('talk_rooms');
-               $table->addColumn('sip_enabled', Types::SMALLINT, [
-                       'notnull' => true,
-                       'default' => 0,
-                       'unsigned' => true,
-               ]);
+               if (!$table->hasColumn('sip_enabled')) {
+                       $table->addColumn('sip_enabled', Types::SMALLINT, [
+                               'notnull' => true,
+                               'default' => 0,
+                               'unsigned' => true,
+                       ]);
+               }

                return $schema;
        }
```
or comment out this addColumn() at all

- re-run migrations from 10000Date20200819121721 up to the end (11001Date20210211111527 in case of Talk 11.2.1), for example, run "delete from oc_migrations WHERE app='spreed' and version like '1%Date20%';" (make sure that you have a backup of the database in the "after migration" state) in SQL and "occ migrations:migrate spreed" in command line.

But I don't know why chats are vanished after the upgrade.

And I don't sure - is it better to ask somebody to reopen this issue or just to create a new one?..

**Comment by nickvergessen** [comment]
Chats and messages are removed because there is a background task removing empty/stray data. The main problem is that the users are not copied over and there main problem for that is https://github.com/nextcloud/spreed/issues/5518#issuecomment-827542491

**Comment by Janl1** [comment]
I sadly have to report that the backported merge does not change anything and the issue still exists.
At the moment I surely cannot upgrade my larger instances as they rely on Talk and the past conversations.

**Comment by PVince81** [comment]
idea to prevent such issue to happen due to cron: making sure that cron finished during the upgrade https://github.com/nextcloud/server/issues/28508

**Comment by th-dorsch** [comment]
The upgrade in my test installation ist only a matter of a few (<10) minutes. I once again made sure that no cron jobs were active during the upgrade. The symptoms of losing previous chats after migration are still 100% reproducible.
