### ISSUE TITLE
Guest username is not remembered to host after guest refreshes

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#552]
## Steps to reproduce
1. Host a call
2. Have some guests, with names put in
3. One of them refreshes

### Expected behaviour
Comes back and is shown with name and colored placeholder avatar as before.

### Actual behaviour
Is shown as Guest with grey placeholder avatar.

See screenshot (the same person had a name set shortly before as you can see in https://github.com/nextcloud/spreed/issues/551#issue-287195223)
![screenshot from 2018-01-09 19-21-04](https://user-images.githubusercontent.com/925062/34738094-433393c6-f578-11e7-802b-08b83c2daecb.png)

Happened on our cloud.nc

@nickvergessen @Ivansss @danxuliu

**Comment by nickvergessen** [comment]
After reconnecting the user should have their name still set. It's saved in the browsers local data. Maybe it's just not sent via the channels to the other users anymore.

**Comment by jancborchardt** [comment]
Yep, exactly. The person mentioned they still see their own name, it was just not broadcasted again.

**Comment by oparoz** [comment]
I saw a javascript error when setting the name as a guest, this could be it. I didn't save it at the time. It said it couldn't read "success" of "undefined"

**Comment by oparoz** [comment]
```
Uncaught TypeError: Cannot read property 'success' of undefined
    at n.<anonymous> (editabletextlabel.js?v=627b207e-68:218)
    at n.r.success (backbone-min.js?v=627b207e-68:1)
    at n.sync (localstoragemodel.js?v=627b207e-68:62)
    at n.save (backbone-min.js?v=627b207e-68:1)
    at n.confirmEdit (editabletextlabel.js?v=627b207e-68:223)
    at n.handleInputKeyUp (editabletextlabel.js?v=627b207e-68:198)
    at HTMLDivElement.dispatch (core.js?v=627b207e-68:3)
    at HTMLDivElement.r.handle (core.js?v=627b207e-68:3)
```

**Comment by nickvergessen** [comment]
Autoclose still broken
