### ISSUE TITLE
Clear Chat Button

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/spreed#5536]
For a nicer experience with guest users, we had ideas for some handy features:
- the Moderation should be able to clear the chat.
- custom links to the room would be nice, like: server.com/call/meeting
- toggle option to switch on/off weather joining Members / Guests see previous messages

**Comment by nickvergessen** [comment]
Duplicate of #1243

Limiting the "history" will not happen in a nearer future, so I'm closing this.
