### ISSUE TITLE
Certificate is Invalid - Can't add SkipTLSVerify=true without .toml file being overwritten

### ISSUE THREAD

**Issue by greavette** [nextcloud/spreed#5568]
Matterbridge version : 1.22.1

Hello,

I'm attempting to connect my Matterbridge to my ejabberd.  My ejabberd does not have a valid certificate and I would like to exclude or ignore the cert check from matterbridge.  

https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample

I can see in the matterbridge.toml.example file how to disable or skip this check:

#Enable to not verify the certificate on your xmpp server.
#e.g. when using selfsigned certificates
#OPTIONAL (default false)
SkipTLSVerify=true

I've found my .toml file in my /tmp folder.  But when I try and update that file with this SkipTLSVerify=True...as soon as I start the matterbridge service or save the config on the matterbridge GUI in Nextcloud my .toml file is overwritten and the cert check is removed from my .toml file.

Please assist with how I can skip the check for TLS cert for matterbridge to connect to XMPP?  Could a checkbox be added to the matterbridge config to not check for TLS?

Thank you.

**Comment by gary-kim** [comment]
To be clear, there is no way to stop the config file from being overwritten. This would need to be added as a feature in Nextcloud Talk.

If you absolutely need it now, you will have to use Matterbridge on it's own.

Or you could help out by implementing it and sending a PR.
