### ISSUE TITLE
Favicon looks like very low quality

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#5591]
## Steps to reproduce
1. use c.nc.c (after an update since Friday)
2. see ![image](https://user-images.githubusercontent.com/5836855/117610282-c2053f80-b161-11eb-9028-7fdbd775619d.png)

### Expected behaviour
High-resolution image

### Actual behaviour
See above

## Talk app
latest c.nc.c

**Comment by fbartels** [comment]
I have to ask, if this has nothing to do with talk, why is it the worst icon out of all the Nextcloud apps?

![example of low res icon compared to other Nextcloud apps](https://user-images.githubusercontent.com/1257835/209078024-be867920-93b6-4512-b7ca-743f5ef4f2c1.png)

**Comment by nickvergessen** [comment]
Maybe because of the SVG content that defines it and the algorithm turning it into a favicon 🤷‍♂️
On our server we updated to Ubuntu 22.04 LTS and then it was fixed

**Comment by oktayacikalin** [comment]
Hmm.. my instance is on a pikapod and my dashboard and talk icons are of low quality - the rest looks fine.

**Comment by szaimen** [comment]
Looks like this might be a cause? https://github.com/nextcloud/server/issues/27502
