### ISSUE TITLE
No History for Guests

### ISSUE THREAD

**Issue by it-open** [nextcloud/spreed#5594]
I would like a Talk Channel for a Chat and direct communication on the Website.
The Gust should just click on the Chat Icon and enter the Chatroom. But he/she should not see the whole conversion we hat with previous guests.

Or you have a better Idea to implement this. (Automatic Room Creation)

**Comment by PVince81** [comment]
This could also apply to regular users being accepted after lobby mode or from a [waiting room](https://github.com/nextcloud/spreed/issues/5394). This could be a new setting for conversation "don't show history for newly joined participants".

### Draft concept

- new option in conversation settings "don't show history for newly joined participants".
   - this will likely require a new flag in the "talk_rooms" table as the existing flags/modes don't seem suitable to extend
- maybe the same option specifically for guests, in case we want to restrict this only for them
- add a column "joined_time" in the "talk_attendees" table and populate it whenever a user or guest has joined a conversation
- in lobby mode, that column should only get populated once the user is actually allowed into the room, not before. Technically, we could update that column's value when switching off lobby mode (or as in [the waiting room concept](https://github.com/nextcloud/spreed/issues/5394 when accepting the participant into the conversation)
- the messages endpoints must only return messages that are more recent than the "joined_time"
- all endpoints must not allow any operations (ex: mark as read, delete) on message ids for messages older than "joined_time" and return a 404 as if they did not exist
- when a user leaves a room and rejoins, the "joined_time" is reset/updated, so they don't see past messages, even their own. This makes it possible that when kicking out a user they don't see what happened between the time they were kicked out and accepted again.
- should moderators always have access to the full history ? if yes:
   - being promoted to moderator instantly gives access to past history
   - being demoted from moderator removes access to history

### Further ideas for later

If there are good reasons like good user stories to do these:

- could allow to specify a number of minutes/hours/days of backlog that is accessible
- manually allowing a user to see past history, exempting them from the rule ? (this has technical implications on the flag implementation)
- is there a situation where no one has access to past history and we could even delete it ? I think the conversation owner always has access to the whole history

**Comment by nickvergessen** [comment]
This gives somewhat false sense of security and breaks with matterbridge and mobile clients that store the history. So retroactively updating the value and hiding the history will be pain. I would therefore close this issue for now and instead go with #1243 instead.
Might not be as convenient, but solves most user stories and is much easier to implement.

**Comment by PVince81** [comment]
Indeed, mobile pagination might be messy to make compatible with this.

Regarding the false sense of security, this makes me think that moderators can't actually track or see who is seeing what, which could lead to even more confusion.

Clearing for everyone is simpler so everyone is on the same page. Let's go with that approach then.
