### ISSUE TITLE
Chat messages are often not send

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5603]
I have it almost all the time that chat messages are not send to the recipient. Today I even had the situation that first everything looked good and after coming back to the browser tab I saw this:

![image](https://user-images.githubusercontent.com/1589737/117818225-b18bbc80-b268-11eb-811c-a42b5c9b4e5d.png)

The last five messages all not send. Also the "retry" button never works for me in such a situation. I always have to first  copy the messages out of the chat view, reload the whole browser window and than past the chat message back again.

Maybe this happens because I have multiple different chats open in different tabs and switch between them? But this was never an issue with Nextcloud < 21. All of it happens on c.nc.com.

**Comment by nickvergessen** [comment]
I think it's more related to the general server issues we keep seeing on c.nc.c

I use 2 browsers and a mobile device all the time in mixed states and never see this unless tuesday afternoons where a lot of big calls are happening.

**Comment by PVince81** [comment]
I remember seeing in RocketChat that it has an auto-retry feature.
It would show a banner at the top "connection lost, retrying in X seconds" and then it would attempt resending the messages.
If it fails, it would show the same message again, where X increases exponentially (aka exponential back-off)
