### ISSUE TITLE
Link back to document

### ISSUE THREAD

**Issue by livier** [nextcloud/spreed#5607]
I go to the talk UI, see on left the list of topics, 
and some are associated, created, in the document UI
nice, I would like a link back to the document ...

**Comment by nickvergessen** [comment]
Can you maybe at a screenshot to clarify what you mean?

**Comment by livier** [comment]
Excuses, I should blur a large part of the screenshot for privacy reasons an I don't have habit to handle pictures... and I forgot it a moment
What I mean is, 
- when I open a "Tchat" in the riht panel off a document, and then go to the Tchat app, I can see the topic off the previous document, and that's nice ;-)
- Later, In the Tchat app, when I see topics related to documents, I would appreciate a link to go back directly to the document. 
- It could be on the left panel, associated with the topic name ; or on the right panel, associated with the title, or the "detail" sub-panel. 

Is my english understandable and is it more clear now ?

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2021-06-08 10-23-43](https://user-images.githubusercontent.com/213943/121150325-b6319980-c843-11eb-9570-6268d61ddb96.png)

You mean this?

**Comment by livier** [comment]
Yes, I did not saw it when I wanted to, since it was there. 
I hoped to find it in the right "details"(in french) panel... and did look around enough
Thanks and excuses for the noise
