### ISSUE TITLE
Hide call log

### ISSUE THREAD

**Issue by RandomBloke85** [nextcloud/spreed#5609]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

In the message area it would be nice to be able to hide the call log in favor to gain some clarity on the actual messages. Maybe a toggle on/off?

**Describe alternatives you've considered**

**Additional context**

Thank you and kind regards
P.S.: Thank you for developping this fantastic app!

**Comment by nickvergessen** [comment]
Duplicate of #1148
