### ISSUE TITLE
TURN.md - TRUN test procedure results in "deprecated in NC21" warning

### ISSUE THREAD

**Issue by isdnfan** [nextcloud/spreed#5611]
follow the procedure described in [6-testing-the-turn-server](https://github.com/nextcloud/spreed/blob/master/docs/TURN.md#6-testing-the-turn-server)

### Expected behaviour
test should work without warnings/errors

### Actual behaviour
entering `OCA.Talk.SimpleWebRTC.webrtc.config.peerConnectionConfig.iceTransportPolicy = 'relay' `
in the browser console results in the warning
`OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment`

## Talk app
NC21 + latest Tlak
**Custom TURN server configured:** yes
**Custom STUN server configured:** no

## Browser
Firefox 88.0
**Microphone available:** yes
**Camera available:** yes
**Operating system:** Windows 10
**Browser name:** Firefox
**Browser version:** 88.0

## Server configuration

**Nextcloud Version:** 21.0.0

**Comment by nickvergessen** [comment]
That's not an issue at the moment.
