### ISSUE TITLE
Guest name input field jumps on hover

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#563]
It shows the edit icon and "Your name..." label moves down.

![screen shot 2018-01-10 at 10 33 30](https://user-images.githubusercontent.com/4638605/34765514-ff9be5f8-f5f1-11e7-92b7-a370996652dd.png)

**Comment by jancborchardt** [comment]
Fixed in https://github.com/nextcloud/spreed/pull/562 :)

**Comment by Ivansss** [comment]
The edit icon is aligned now but the "Join call" button is still pushed down on hover.

**Comment by nickvergessen** [comment]
@skjnldsv also happens on master and stable13

Additionally on master the confirm arrow is "broken":
> ![bildschirmfoto von 2018-03-23 10-13-53](https://user-images.githubusercontent.com/213943/37821469-f5a17386-2e83-11e8-80b4-282cc09bdd7f.png)
