### ISSUE TITLE
Nextcloud Talk desktop application

### ISSUE THREAD

**Issue by kz6fittycent** [nextcloud/spreed#5635]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature request.

**Describe the solution you'd like**
It would be really awesome/handy if there was a "Talk" desktop application, even if it was Node based. This would allow users to open the app instead of the browser and hold conversations and video chat. This would be a feature that could go miles in terms of widespread adoption. The mobile Talk apps are great, it's the desktop that's missing out. 

**Describe alternatives you've considered**
Typically, I open the browser, sign into my server, and start the chat - a little cumbersome. 

**THANKS**
You guys are awesome, and I appreciate all the hard work you do in creating an amazing product.

**Comment by nickvergessen** [comment]
See all the duplicated issues
