### ISSUE TITLE
Guest name position

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#565]
Currently we show a notification »You can set your name in the right sidebar so that others can identify you better«. This vanishes quite quickly and is not really visible.

Instead, we should put the name input directly next to the avatar both in the big chat view and in the sidebar tab when we are in a call. Same where the name of a logged-in user is.

That will also take care of the stray username element we have in the sidebar.

@danxuliu if you give me the element, I can style it. :)

**Comment by nickvergessen** [comment]
Guest name input is now available above the chat box:
https://github.com/nextcloud/spreed/pull/710
