### ISSUE TITLE
No audio and video if not on the same network

### ISSUE THREAD

**Issue by RandomBloke85** [nextcloud/spreed#5654]
We're on a small Nextcloud with only 4 users spread over 3 households with PC's, Android and iOS phones. Everything worked flawlessly until a couple of days ago, when Nextcloud Talk suddenly decided to stay dark and silent, when picking up the phone.

*****************************
Edit: Same network obviously means "if not on WiFi". I just made a video call with a person outside my house, but both on WiFi - that worked. If one phone (or both of course) goes over 4G instead over WiFi, than it behaves like described above. Messaging works in any case.
*****************************

We have no turn or stun server installed.
All on Android 11 or latest iOs versions.
Samsung S10 and iphones 6, 10 and 11.

Truenas 12.2, Nextcloud 21 latest update installed, latest Talk version
Apache2.4, php 7.4, MySQL

Within the same network, everything works great as usual, except if on different networks, then it does not. It rings but when you pick up, there is no audio and video.

Maybe this problem is known already, then I appologize for posting it again. But I couldn't find anything in here.

**Comment by nickvergessen** [comment]
You need a TURN server:
https://nextcloud-talk.readthedocs.io/en/latest/TURN/
