### ISSUE TITLE
Option to turn off audio processing / echo cancellation

### ISSUE THREAD

**Issue by wiwikuan** [nextcloud/spreed#5657]
Hi, I’m a piano teacher, and I want to use NextCloud Talk to give remote piano lessons. But every video conferencing software I tried (except Zoom) doesn’t have an option to turn off “noise/echo cancellation”, without the option to turn off echo cancellation, the communication software will ruin all the music, resulting it being almost unusable for music teaching and professional audio work.

Can we get an option to turn off noise/echo cancellation in NextCloud Talk in the future? Or are there any hacks that I can do to adjust audio codec, stereo audio and other advanced audio settings?

I really want to use NextCloud (instead of Zoom) to do this, any help is appreciated, Thanks!

**Comment by nickvergessen** [comment]
Duplocate of #3252
