### ISSUE TITLE
[Matterbridge] cannot unmarshal array into Go struct field RoomInfo.ocs.data.lastMessage of type ocs.TalkRoomMessageData

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/spreed#5701]
## Steps to reproduce
1. Create some chat with more than 1 participants 
2. Enable matterbridge
3. Post 1-5 messages
4. Disable relaying
5. Truncate table oc_comments
6. Post same count of messages again
7. Try to enable relaying again
8. Check oc_talk_rooms to ensure last messge is set and exists

### Expected behaviour
Bridging successful

### Actual behaviour
Error: 
    cannot unmarshal array into Go struct field RoomInfo.ocs.data.lastMessage of type ocs.TalkRoomMessageData

## Talk app

**Talk app version:** last release

**Comment by nickvergessen** [comment]
Truncating a table is not supported. 🤷‍♂️
Apart from that it seems to be an issue with matterbridge and not Talk.

**Comment by nickvergessen** [comment]
> Well no button "Clear history" is in the Talk.

Just because there is a missing feature doesn't mean you can mess up the database and expect things to work 👯‍♂️ 
Anyway see #1243 it will come at some point.
