### ISSUE TITLE
Participant drop down is hidden in overflow

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#571]
not sure which of the recent PRs did that:
> ![bildschirmfoto von 2018-01-10 12-13-45](https://user-images.githubusercontent.com/213943/34770002-e03bef2e-f5ff-11e7-8709-706082617602.png)

@jancborchardt or @danxuliu who of you?

**Comment by danxuliu** [comment]
I think that it was like that before the PR frenzy.

But I thought that I had changed the participant list to fill all the available space. Strange...

**Comment by jancborchardt** [comment]
Didn’t check yet, but might be related to: Limit scroll bar in sidebar to chat view #550?

**Comment by danxuliu** [comment]
The participant list can (and should) be stretched to fill all the available space using `flex-grow`, which would fix this issue when there is empty space below the last participant.

However, when the list of participants is larger than the available space showing the menu below the three-dots will still cause the list of participants to grow; in that case the list would need to be further scrolled to be able to remove the participant (just like now, although now the menu is cropped even if there is enough room). Thus, the menu should be shown above the three-dots menu when there is not enough room.
