### ISSUE TITLE
🌏 Federated Conversations Overview

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/spreed#5723]
# See [🌏 Testing federation while there is no frontend yet](https://github.com/nextcloud/spreed/issues/10686) for testing steps

Progress on implementing federated Nextcloud Talk rooms.

This implementation will have each room on a single server so each participating server will only communicate with the server hosting the room (This does mean that the room will be inaccessible regardless of the server the user is on if the server hosting the room is not available).

### Required

* [x] API compatibility checker
  * [x] Capability handling https://github.com/nextcloud/spreed/issues/10680
  * [ ] Publish OCM resource https://github.com/nextcloud/spreed/pull/10692
* [x] Remote message access API
* [x] Remote message send API
* [x] Remote user list + presence API
* [x] Remote API authentication
* [x] Add messages from other instances in the client receive messages API
* [x] Send messages to instance hosting the room
* [ ] Remote call attendance
  * [ ] Remote signaling
  * [ ] Remote Talk configuration info
  * [ ] Handling CSP issues
* [x] Keeping track of remote servers (current through is to use server_url but how to handle if that changes?) #5775 
* [ ] Request join system?
* [ ] Remote moderators?
* [ ] Token shares (for various ROS shares)
	* Probably public link shares at first. Can add proxying through remote server later.
* [x] Sending Shares #5775
* [x] Receiving Shares #6105 
* [x] Validation by remoteAttendeeId + accessToken might be ambiguous, maybe we should keep the invites in the DB with an accepted flag and add the remoteServer there? https://github.com/nextcloud/spreed/pull/10766
* [x] Send `sendRemoteUnShare` when removing participant https://github.com/nextcloud/spreed/pull/11464
* [x] Federation is not checking if the target user is allowed to use talk

### Integration tests

- [x] Test that it doesn't work when federation is not enabled
- [x] Test remote participant is added to participant list
- [x] Test invite is sent
- [x] Test accepting an invite (any change for the inviter?)
- [x] Test declining an invite (is the remote participant removed?)
- [x] Test requesting the room as a remote participant
- [x] Test if remote participants can see the participant list

### Bugs

- [x] Database has unique index on token which needs to be extended to token+server_url

@nickvergessen

**Comment by nickvergessen** [comment]
> Remote message send API

I guess we use this for it:
https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/apps/cloud_federation_api/appinfo/routes.php#L35-L40

> Remote API authentication

We introduced "pins" for users recently for SIP calling. It's a string field 32 chars long. Maybe we can use that? Ah would prevent them from having a phone pin later on. So I guess we need a new field.

> Add messages from other instances in the client receive messages API

Since messages are pulled on a per room basis this should also be done on the source instance

> Handling CSP issues

We could just reload the page when opening such a conversation as an easy workaround. The big issue is not the remote server, we could loop over the conversations of the user. But the STUN/TURN/HPB as well which are needed for remote calls.

> Federated Room ID. Probably (@token@cloud.example.com)

That would conflict with the federated cloud ids of users. But do we need it for now?

**Comment by nickvergessen** [comment]
> Request join system?

I guess we just use OCM for that too. The big question is if we want to have to accept users. Could also say room is either public or not. If it is people can add themselves, if not they can't.
"Open conversations" are not supported for now I guess 👯

**Comment by gary-kim** [comment]
> That would conflict with the federated cloud ids of users. But do we need it for now?

Trying to figure out how to identify remote rooms in the database (the federated cloud IDs for users would also be useful for identifying each user in the room). Maybe we could use `#token@cloud.example.com` to avoid the conflict?

**Comment by nickvergessen** [comment]
Well so the only place where the remote info would be needed is the rooms table and there we could just add a column `server_url` or something. everything else works based on the integer room id from that table 🤔

**Comment by gary-kim** [comment]
Sounds fine. There's other places like how to make the room URL for remote rooms but that does not have to be easily readable so.

**Comment by nickvergessen** [comment]
- [ ] Database has unique index on token which needs to be extended to token+server_url

**Comment by nickvergessen** [comment]
> Database has unique index on token which needs to be extended to token+server_url

Actually that might not even work, as the token also needs to be in the URL and be unique there.
So maybe we have to store the room with a different local token which then is still unique and basically you get the remote_url and remote_token from the API and if that is there (or the type reflects it) you use that to communicate with the remote server, but locally you always interact with the local token.

**Comment by gary-kim** [comment]
Does modifying the `receiveMessages` endpoint for allowing remote servers to receive messages sound okay? I think it will be better than creating a separate API since most of the code/functionality is shared anyways.

**Comment by nickvergessen** [comment]
What do you mean?

**Comment by gary-kim** [comment]
So when someone on a remote server tries to read their messages, the user's server will send a request to the server hosting the chat to the same API as used by clients normally but with the shared secret. Then the server hosting the chat can use that to authenticate and send back messages in the same format it sends it to clients.

https://github.com/nextcloud/spreed/blob/b5fa5cf8dd313056dd6f1c0ffb6ca9d6e8925d3a/lib/Controller/ChatController.php#L383

I will go ahead and implement it. Can also discuss further in the PR.

**Comment by nickvergessen** [comment]
No we are not proxing the messages. The clients will directly contact the remote server and ask for the messages.

Also there is currently an open PR about federation which should be the next bit we work on.

**Comment by nickvergessen** [comment]
More steps in #7464

**Comment by nickvergessen** [comment]
### Common flow

User/Server | Action | PR
---|---|---
UserA | Creates ConversationA | ☑️
UserA | Invites remote user UserB@ServerB | ☑️
ServerA | Sends OCM share to ServerB | ☑️
ServerA | Shows invitation as system message | ☑️
ServerB | Shows notification to UserB | #7464
UserB | Sees invitation | #7464

### Accept

User/Server | Action | PR
---|---|---
UserB | Accepts invitation | #7464
ServerB | Sends OCM response to ServerA | ☑️
UserA | Sees in the ChatA that UserB@ServerB accepted | #7464


### Decline

User/Server | Action | PR
---|---|---
UserB | Declines invitation | #7464
ServerB | Sends OCM response to ServerA | ☑️
UserA | Sees in the ChatA that UserB@ServerB declined | #7464
UserA | UserB@ServerB is removed from the participant list | ☑️

**Comment by nickvergessen** [comment]
- [ ] Remote rooms with pending invites are deleted as there is no attendee in the database table when background jobs run

**Comment by Thatoo** [comment]
I'm a bit surprised not reading anything about using matrix protocol for federation purposes.
 It could allow Talk server-to-server federation, but also to Matrix / Teamspeak / Gitter, etc.

**Comment by nickvergessen** [comment]
Mostly done, so closing this overview

**Comment by Thatoo** [comment]
Does that mean this issue could be closed https://github.com/nextcloud/spreed/issues/21 or it's a different issue?
