### ISSUE TITLE
Timezone problem. Talk message cannot be received without reload, but video call can receive

### ISSUE THREAD

**Issue by yangboyd** [nextcloud/spreed#5729]
## Steps to reproduce
1. Install Nextcloud 21.0.2
2. Enable Talk App
3. Two users begin talk, send message to each other

### Expected behaviour
Message  arrive before page reload

### Actual behaviour
Message does not arrive without page reload

But video call is immediate and works.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.2.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
ubuntu
**Browser name:** Firefox/Chrome/...
chrome
**Browser version:** 50.1/55/...
91.0.4472.77
### Browser log

No other log.

**Comment by nickvergessen** [comment]
Mostlikely you use a wrong combination of php-fpm and prefork:
https://nextcloud-talk.readthedocs.io/en/latest/system-requirements.html#webserver

**Comment by yangboyd** [comment]
I use php7_module and mpm_prefork_module.

**Comment by nickvergessen** [comment]
But then you should see something in your browsers log, apache log or nextcloud log.

**Comment by yangboyd** [comment]
Chrome log show the room poll get the latest message, but the chat room does not render the latest message.(the chat room list updates other session's new message.)

The chrome console shows errors:

Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:260
pn.run @ vue.runtime.esm.js:4568
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Kt @ vue.runtime.esm.js:1906
Promise.then (async)
Yt @ vue.runtime.esm.js:1933
ee @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ct.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:81
(anonymous) @ files_pdfviewer-main.js:2

**Comment by yangboyd** [comment]
@nickvergessen It's a timezone issue.
The server use UTC time, but the chrome client use local time. Polled latestMessage's time is not converted to localtime where compare, So they are ignored(UTC less than local(UTC+8)).

**Comment by nickvergessen** [comment]
In our company we range 16h of timezones and never had an issue with our utc server.

**Comment by yangboyd** [comment]
I found the problem occurs here.

          lastChatMessage: function() {
                var e = this.item.lastMessage ? this.item.lastMessage.timestamp : 0;
                if (Object.keys(this.messages).length > 0) {
                    var t = Object.keys(this.messages)
                      , n = t[t.length - 1];
                    if (this.messages[n].timestamp > e)========> e(of polled msg) is UTC time, but this.messages[n].timestamp  is UTC+8 time.
                        return this.messages[n]
                }
                return this.item.lastMessage
            },

This function returns the old message, not the  new message

**Comment by PVince81** [comment]
timestamp is supposed to be a numeric value that is always UTC everywhere, on server and clients

maybe the bug is in the code that sends/submits the message, stored with the wrong timestamp ? you could check the database also, oc_comments table

would be good to know what clients both users were using, web UI or mobile apps and what versions ?
