### ISSUE TITLE
Adding or removing a group from a room does not show a system chat message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5730]
## Steps to reproduce
1. Add a group to a conversation
2. Remove a group from a conversation
3. Check the chat

### Expected behaviour
There should be a system message saying:
> You added group X
> You removed group X

### Actual behaviour
```
```

This only become relevant now that we track the groups

**Comment by PVince81** [comment]
ah! I didn't noticed that https://github.com/nextcloud/spreed/pull/4810 was already in since a while

**Comment by nickvergessen** [comment]
I was waiting to see if #5670 makes it to make sure a potential event is generic enough :D

**Comment by PVince81** [comment]
to clarify: is this ticket here waiting for https://github.com/nextcloud/spreed/pull/5670 or is it independent ?

if yes, I assume we need to add new events like EVENT_BEFORE_GROUPS_ADD and EVENT_AFTER_GROUPS_ADD

in that regards, I found https://github.com/nextcloud/spreed/blob/master/lib/PublicShareAuth/Listener.php#L63 and was wondering how to trigger that case and whether it's triggerable also with groups ?

**Comment by nickvergessen** [comment]
So the thing is our events are old and the current recommended way is to dispatch typed events:
https://docs.nextcloud.com/server/latest/developer_manual/basics/events.html#ocp-event-dispatcher

We would therefor now introduce 4 new event classes:
`BeforeGroupAddedEvent` (before) `GroupAddedEvent` (after)
`BeforeGroupRemovedEvent` (before) `GroupRemovedEvent` (after)

But then we need 4 new ones for circle. So I'd at least try to keep them "neutral" in a way:
`BeforeAttendeeAddedEvent` (before) `AttendeeAddedEvent` (after)
`BeforeAttendeeRemovedEvent` (before) `AttendeeRemovedEvent` (after)

Then the question is if we do 1 event with an array of attendees (similar to the current AddParticipantsEvent) or a dedicated dispatch for each attendee that is added.

**Comment by PVince81** [comment]
I'd vote in favor of an aggregated event with an array. This way the consumer knows upfront what's coming, for example for the use case of showing a single "you have added X, Y, Z and others" message.

If we don't, the consumer will need to use tricks like gathering every user from every event in a local array, and then at some future point process the array. In this scenario it's difficult to determine what would trigger that "future point" as you never know if more events will come in.
