### ISSUE TITLE
SIP Gateway support

### ISSUE THREAD

**Issue by Viksie** [nextcloud/spreed#5734]
The Talk app cannot call cellular/mobile/landline numbers or receive inbound cellular/mobile/landline calls.

In providing a SIP Gateway option, onsite hardware such as the Yeastar TG200 which supports SIP signalling can be utilised to make outgoing or receive incoming calls.

In addition, this will ensure that a business can remain contactable should the data connectivity (WAN link) be disrupted.

This will also assist in the uptake of Talk as users would be reverting to but one softphone client.

**Comment by nickvergessen** [comment]
As per https://nextcloud.com/talk/ sip is possible via the high-performance backend already.
