### ISSUE TITLE
Please add Guest Ban and Waiting Room like Zoom

### ISSUE THREAD

**Issue by ramesh-dada** [nextcloud/spreed#5735]
Hello Super Thank You so much for such a great app, Can you please add an option to ban guest via storing cookie or banning IP to fight abuse as some of the members transfers my link to some other peoples. I will be happy if there will be one of the option Waiting Room Or guest ban as whenever I remove the participant he joins us back again..

**Comment by PVince81** [comment]
- guest ban: see https://github.com/nextcloud/spreed/issues/1423
- waiting room: see https://github.com/nextcloud/spreed/issues/5394
