### ISSUE TITLE
Container doesn't expand vertically any more

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5747]
## Steps to reproduce
1. Open Talk on master
2. Join a conversation

### Expected behaviour
New message form at bottom

### Actual behaviour
New message form is in the middle of the screen
<img width="952" alt="image" src="https://user-images.githubusercontent.com/277525/121695549-6fee6b80-cacb-11eb-98e9-b37e30222ac3.png">

## Talk app

**Talk app version:** master fb314a096f03332f3edf2478d70e74e5225dcc18

Might be related by the 4.0.0 nextcloud/vue upgrade but I don't remember seeing that back then.

@marcoambrosini

**Comment by PVince81** [comment]
it gets worse, once there are more messages, the whole page scrolls down

I suspect that something is wrong with the app content scroll container

**Comment by PVince81** [comment]
okay, waiting for 4.0.1 release then https://github.com/nextcloud/nextcloud-vue/pull/2032

**Comment by nickvergessen** [comment]
Fixed with #5760
