### ISSUE TITLE
Plans to add SIP calling or other integration with a PXB server?

### ISSUE THREAD

**Issue by zguithues** [nextcloud/spreed#575]
The recent work done on this looks great!  I'm excited to try it once i upgrade to Nextcloud 13.

Has there been any consideration towards adding actual phone call support to the platform?  An easy implementation may be to add sip calling, allowing the app to connect to an external PBX server.

I've been using a project called [WAZO](wazo.community) for my office cloud PBX.  It's fully open source, including their webRTC client.  they're also working to api'ify the entire Asterisk platform into a Rest API.  There are many potentials for integration, potentially including a phone call as 2 factor authentication.

**Comment by nickvergessen** [comment]
SIP is already in the manufactoring as far as I know.

**Comment by LorbusChris** [comment]
@nickvergessen uhh this is exciting. can you already give any details?

**Comment by nickvergessen** [comment]
SIP bridge is listed in https://nextcloud.com/talk/ so should be available in the near future.
I also tested it last week and it was working :)

**Comment by tunermason** [comment]
From what I can see Nextcloud Talk is only between users and not able to connect to a sip server. Please correct me as I hope I am wrong

**Comment by nickvergessen** [comment]
Well there is a external signaling server which includes a MCU. In this case the connections are not peer-to-peer anymore, and that is where the SIP bridge jumps in and is possible.

**Comment by tunermason** [comment]
@nickvergessen Thanks for your reply, Can you go into more detail about how this would work or the structure

**Comment by nickvergessen** [comment]
Well, it is a signaling server which also includes an MCU and a SIP bridge. What more should I describe.

**Comment by ehsanmqn** [comment]
> Well, it is a signaling server which also includes an MCU and a SIP bridge. What more should I describe.

Is it possible to change this MCU and use a private SIP brifge and MCU?

**Comment by nickvergessen** [comment]
Well the MCU needs to know all signaling messages and transmit them accordingly, so you need the signaling server anyway. So the all-in-one bundle is the only thing that makes sense.

**Comment by ehsanmqn** [comment]
> Well the MCU needs to know all signaling messages and transmit them accordingly, so you need the signaling server anyway. So the all-in-one bundle is the only thing that makes sense.

So we can use a SIP proxy/registrar such as Asterisk to route desired UIRs to a server running the MCU. Am I true? By the way we can integrate SIP proxy and MCU into one server.

**Comment by Fuseteam** [comment]
@nickvergessen does this sip bridge work with an existing pbx server? the way imagine it is that i have an pbx server with different extensions, users could then connect their extension to make/receive calls

**Comment by nickvergessen** [comment]
I have no experience with other SIP bridges than the one that we offer.

**Comment by Fuseteam** [comment]
i meant using the SIP bridge you offer

**Comment by fancycode** [comment]
The SIP bridge currently supports dialing into or out from rooms. Once a user calls the SIP bridge, an IVR workflow asks for room number and participant pin and then connects the SIP call into the room. For dialing out, a web user can enter a phone number that is then called by the SIP bridge and connected into the room.

What you are asking (having a direct mapping between SIP extension and Nextcloud user, so the user could be "called" from externally through SIP) is on the roadmap, but as far as I know has not been prioritized yet. @nickvergessen please correct me if I'm wrong.
