### ISSUE TITLE
Guest chat input not layouted correctly

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5765]
## Steps to reproduce
1. Create a chat
2. Make it public
3. As a guest open the chat

### Expected behaviour
✨ 

### Actual behaviour
![Bildschirmfoto von 2021-06-14 13-23-36](https://user-images.githubusercontent.com/213943/121884899-c51cbe00-cd13-11eb-83b9-a0accb70c504.png)

I guess it's because of the missing attachment icon

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5850
