### ISSUE TITLE
Can't connect to Signaling server if MySQL SSL is Forced

### ISSUE THREAD

**Issue by acsfer** [nextcloud/spreed#5774]
## Steps to reproduce
1. Enable MySQL SSL in `config.php`
```
'dbdriveroptions' => array(
  \PDO::MYSQL_ATTR_SSL_KEY => '/etc/ssl/mysql/client-key.pem',
  \PDO::MYSQL_ATTR_SSL_CERT => '/etc/ssl/mysql/client-cert.pem',
  \PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/mysql/ca.pem',
  \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
),
```
2. Force SSL on MySQL server with `ALTER USER 'nextcloud'@'%' REQUIRE SSL;`
3. Error while connecting.
>Failed to establish signaling connection. Something might be wrong in the signaling server configuration.
4. Error is "fixed" with  `ALTER USER 'nextcloud'@'%' REQUIRE NONE;` so it seems that SSL still be used but, as it is not mandatory, some MySQL connections are not blocked somewhere.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.2.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
Yes

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

### Browser log
![image](https://user-images.githubusercontent.com/12234510/121916196-38cec300-cd34-11eb-9fd7-b43b676aa4a0.png)

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu 20.00

**Web server:** Apache/Nginx
Apache 2.4

**Database:** MySQL/Maria/SQLite/PostgreSQL
MySQL 8

**PHP version:** 7.2/7.3/7.4
7.4

**Nextcloud Version:** (see admin page)
21.0.2

**Comment by nickvergessen** [comment]
I guess this should be reported at https://github.com/strukturag/nextcloud-spreed-signaling/ instead?

**Comment by acsfer** [comment]
Not their opinion 😆 
https://github.com/strukturag/nextcloud-spreed-signaling/issues/123

**Comment by nickvergessen** [comment]
Alright, then I misunderstood.

**Comment by nickvergessen** [comment]
So we don't do anything special in Talk at this.
We neither manually interact with the database nor does the signaling server.

So only thing I could see is that your signaling server is wrongly configured and uses HTTP without SSL to connect to Nextcloud.
But I then wonder how that translates into a non-SSL connection for the database.

Is there anything in your nextcloud.log or apache log?

**Comment by acsfer** [comment]
Signaling server is forcing SSL (last line here):

```
upstream signaling_server {
    server 127.0.0.1:8080 max_fails=0 fail_timeout=0s;
    keepalive 32;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name signaling.example.com;

    access_log  /var/log/nginx/signaling_access.log  main;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;

    location /standalone-signaling/ {
        proxy_pass http://signaling_server/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection $connection_upgrade;
    }

    location /standalone-signaling/spreed {
        proxy_pass http://signaling_server/spreed;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    try_files $uri $uri/ =444;
}

server {
    listen 80;
    listen [::]:80;
    server_name signaling.example.com;

    return 301 https://$server_name$request_uri;
}
```

Nothing in the Nextcloud log (empty) and on the Nextcloud server, Apache sends a 500 for
`"GET /ocs/v2.php/apps/spreed/api/v2/signaling/welcome/0 HTTP/2.0" 500`

and when not forcing SSL:
`"GET /ocs/v2.php/apps/spreed/api/v2/signaling/welcome/0 HTTP/2.0" 200`

**Comment by nickvergessen** [comment]
> Apache sends a 500 for
> "GET /ocs/v2.php/apps/spreed/api/v2/signaling/welcome/0 HTTP/2.0" 500

But if you have a 500 in your access.log, there must be something in the error.log

If your nextcloud.log is empty, you are either looking at the wrong path (check whether it's overwritten in the config.php, otherwise its nextcloud.log in your data directory) or the file is not writable by the webserver.

**Comment by acsfer** [comment]
When i say "empty" i mean nothing valuable here. Essentially there are Warnings about failed logins, but no ERROR or FATAL level messages. The only errors are on browser console, and i can reproduce it but just issuing a :

`ALTER USER 'nextcloud'@'%' REQUIRE SSL;`

![image](https://user-images.githubusercontent.com/12234510/122005712-4167dd80-cdb6-11eb-894b-de8ebc11057f.png)

then I switch back to fix this error.

`ALTER USER 'nextcloud'@'%' REQUIRE NONE;`

On the n`extcloud.log`, nothing has been logged since last line logged (few hours ago).

**Comment by nickvergessen** [comment]
Then please post your other database parts from the config.php

**Comment by acsfer** [comment]
Full config.php:

```
<?php
$CONFIG = array (
  'hashingThreads' => 4,
  'hashingMemoryCost' => 77824,
  'hashingTimeCost' => 3,
  'passwordsalt' => 'xxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.example',
  ),
  'datadirectory' => '/files/users/nextcloud/data',
  'tempdirectory' => '/srv/users/nextcloud/tmp/nextcloud',
  'dbtype' => 'mysql',
  'version' => '21.0.2.1',
  'overwrite.cli.url' => 'https://nextcloud.example',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbname' => 'nextcloud',
  'dbhost' => 'pnd-03-std-32',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxx',
  'installed' => true,
  'skeletondirectory' => '',
  'default_language' => 'fr',
  'default_locale' => 'fr_FR',
  'activity_expire_days' => 7,
  'auth.bruteforce.protection.enabled' => false,
  'htaccess.RewriteBase' => '/',
  'knowledgebaseenabled' => false,
  'logtimezone' => 'Europe/Paris',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcached_options' =>
  array (
    -1003 => 2,
  ),
  'redis' =>
  array (
    'host' => 'pnd-03-std-32',
    'port' => 6379,
    'dbindex' => 7,
    'timeout' => 0,
    'password' => 'xxxxxxxxxxxxx',
  ),
  'dbdriveroptions' => array(
    \PDO::MYSQL_ATTR_SSL_KEY => '/etc/ssl/mysql/client-key.pem',
    \PDO::MYSQL_ATTR_SSL_CERT => '/etc/ssl/mysql/client-cert.pem',
    \PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/mysql/ca.pem',
    \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
  ),
  'logfile' => '/srv/users/nextcloud/nextcloud.log',
  'updatechecker' => false,
  'appstoreenabled' => true,
  'upgrade.disable-web' => true,
  'overwriteprotocol' => 'https',
  'preview_max_scale_factor' => 1,
  'quota_include_external_storage' => false,
  'trashbin_retention_obligation' => 'auto, 7',
  'updater.release.channel' => 'stable',
  'instanceid' => 'xxxxxx',
  'overwritehost' => 'nextcloud.example',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
  ),
  'simpleSignUpLink.shown' => false,
  'loglevel' => 2,
  'default_phone_region' => 'FR',
);
```

**Comment by nickvergessen** [comment]
You didn't specify any port, so it uses the mysql default port and not an SSL one and that's it.

**Comment by acsfer** [comment]
Wait, what is "SSL one"? The port should be the same. Nextcloud, every app inside it and any other external software works out of the box trough 3306 (default) port.
https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html#mysql-client-server-ports

If this is undocumented, i'll document it myself but i need to understand first...

**Comment by acsfer** [comment]
Also, this is what is logged by the Signaling server once SSL is required.

```
Jun 15 11:08:50 pnd-03-std-32 signaling[66152]: client.go:275: Client from 176.174.255.131 has RTT of 39 ms (39.361297ms)
Jun 15 11:08:50 pnd-03-std-32 signaling[66152]: backend_client.go:512: Received unsupported content-type from https://nextcloud.example/ocs/v2.php/apps/spreed/api/v1/signaling/backend: text/html; charset=UTF-8 (200 OK)
```

Once SSL is **not** required (MySQL side):

```
Jun 15 11:08:51 pnd-03-std-32 signaling[66152]: client.go:275: Client from 176.174.255.131 has RTT of 57 ms (57.466995ms)
Jun 15 11:08:52 pnd-03-std-32 signaling[66152]: hub.go:703: Register user cloud@nextcloud from 176.174.255.131 in unknown-country (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36) jj_Fvqm6S2U6KES7XpyEVGDJSYLFkCd81HEUQuQls8t8PT13UjVOem1FYkNDbk9jSVRJc0IyaTJmdEZUbURwZjhLNm5zdFVQaG83S2hXb3pHRG5oS1FyVVNvNVF1WFdzaWFCLV9KZ0Fjdk40LWtiUFF0SFhIY0VvOEV4RW5FS1ppWWFIRExCYjJfelVuRE5BSU1ucE9KQUh4bTRvbVBRSlA3NTVrVjBBRmU0Q3dDLW8yanhoZU5TemhFdjRyMWJrdW84RmV5V3VSfDIzMTg0NzMyNjE= (private=MTYyMzc0ODEzMnxhOWNUYzdJTXVTZm1uNWZQUG1QV3A5LUJENXRqN0FnYmU1VE03bk5nU2tTOWhJdE1HSFVPYnFKcGUyZGVvVjR1aG5JTXpwWHUtQk84TVBzcnJOazRVRG5kWjNwcGVjNHA0LTlndHJkQ01PT0dZMFl3VFY4TGphUmdvanR4YXdZU3hMcFRPUWdhNGJyakZ2OS1JaTZPMWtza3NybVhPbng3cjZ2NDRBPT18HjRQydM-G0w2-0NeJUuGAlZ_GRuJylvMYsA0RPEskzk=)
Jun 15 11:08:52 pnd-03-std-32 signaling[66152]: clientsession.go:413: Session jj_Fvqm6S2U6KES7XpyEVGDJSYLFkCd81HEUQuQls8t8PT13UjVOem1FYkNDbk9jSVRJc0IyaTJmdEZUbURwZjhLNm5zdFVQaG83S2hXb3pHRG5oS1FyVVNvNVF1WFdzaWFCLV9KZ0Fjdk40LWtiUFF0SFhIY0VvOEV4RW5FS1ppWWFIRExCYjJfelVuRE5BSU1ucE9KQUh4bTRvbVBRSlA3NTVrVjBBRmU0Q3dDLW8yanhoZU5TemhFdjRyMWJrdW84RmV5V3VSfDIzMTg0NzMyNjE= joined room ogg3fx4s with room session id ftr67+J7cKK6PrL9eHz3WJqJGGyIuui97YogV1yAhelxsIIiB+EKV6eL76ZrtSAh8x4itjQXTPQ3tXAb4l3dRFznRdWBbWvvqWrhxH1WVePRsn5rwvC9Lv+nwEMX6ltwHmWkeHzfGgQo7g91RicQXwr3e+gRc8Q/zrEPHGXO5K+c+WXfiUHRNNcnzdxUf7s4+8F7zq4sym0fCiLGulzsDvJk4LTCN8+XcE/TO5Gfqx763x4z0ygVmI3Q/Rg6BqA
Jun 15 11:08:52 pnd-03-std-32 signaling[66152]: clientsession.go:229: Permissions of session jj_Fvqm6S2U6KES7XpyEVGDJSYLFkCd81HEUQuQls8t8PT13UjVOem1FYkNDbk9jSVRJc0IyaTJmdEZUbURwZjhLNm5zdFVQaG83S2hXb3pHRG5oS1FyVVNvNVF1WFdzaWFCLV9KZ0Fjdk40LWtiUFF0SFhIY0VvOEV4RW5FS1ppWWFIRExCYjJfelVuRE5BSU1ucE9KQUh4bTRvbVBRSlA3NTVrVjBBRmU0Q3dDLW8yanhoZU5TemhFdjRyMWJrdW84RmV5V3VSfDIzMTg0NzMyNjE= changed: [publish-media publish-screen]
```
I still can't see where the port thing is valuable here, sorry. 😞
