### ISSUE TITLE
Pasting an image/text enables/disables video

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#5776]
## Steps to reproduce
1. paste a text/image via crtl+v
2. see that sometimes video enable/disables

### Expected behaviour
ctrl+v should not change video mode

### Actual behaviour
sometimes video mode is toggled

## Talk app
on c.nc.c

**Comment by PVince81** [comment]
not reproducible neither on Firefox 89 or Chromium 91

tried pasting in the right sidebar chat and also directly in the chat window

even shift+V doesn't trigger the shortcut

**Comment by tobiasKaminsky** [comment]
I can still reproduce it on c.nc.c
Shall we do a call?

**Comment by nickvergessen** [comment]
Can't reproduce either anymore.

Only thing I noticed is that is you:
* Down Ctrl
* Down V
* Up Ctrl
* Up V (camera now toggles)

But if you do
* Down Ctrl
* Down V
* Up V
* Up Ctrl

The camera does not toggle.

But this only happens when the chat input is not focused. If the chat input is focused, it does the copy+paste

**Comment by tobiasKaminsky** [comment]
It still happens to me, but as it does not happen always, it is really hard to reproduce, might indeed be some kind of timing issue.
(I also use a non default keyboard layout (neo keyboard layout), so that v is not physicial v (on qwertz), but w.
Not sure if this might cause more troubles…

**Comment by nickvergessen** [comment]
Can we also get the browser info?

**Comment by tobiasKaminsky** [comment]
Firefox 91.0 (64-bit) on arch.
(it happened on last coffee call, when I shared the monster mug with you…)

**Comment by nickvergessen** [comment]
So the problem is with image content and the order:

* Down Ctrl
* Down V
* Up Ctrl
* Up V (camera now toggles)

While releasing V the chat input is not focused anymore as the send-button got focused and then releasing v toggles the video.
