### ISSUE TITLE
Ignore unknown event

### ISSUE THREAD

**Issue by kesselb** [nextcloud/spreed#5777]
## Steps to reproduce
1. Join a talk call
2. See ignore unknown event (~ every 3 seconds)

```
signaling.js:673 Ignore unknown event {type: "error", error: {…}}
(anonymous) @ signaling.js:673
```

```
{
    "type": "error",
    "error": {
        "code": "processing_failed",
        "message": "Processing of the message failed, please check server logs."
    }
}
```

## Talk app

**Talk app version:** c.nc.com

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 20.10

**Browser name:** Chrome

**Browser version:** 90

**Comment by solracsf** [comment]
@nickvergessen i can still observe this nowadays (latest NC and Talk to date).

![image](https://user-images.githubusercontent.com/12234510/215869134-2cad0254-a3f0-4602-8102-32640debb0e3.png)
