### ISSUE TITLE
Clicking on the avatar in the conversation list tries to leave the call

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5790]
## Steps to reproduce
1. Have a one-to-one conversation
2. Be in anothern conversation or even call
3. Click on the avatar of a one-to-one conversation in the conversation list to check

### Expected behaviour
You see the profile menu

### Actual behaviour
* If in call: Attempted to leave the call
* If not in call: Conversation is switched
![Bildschirmfoto von 2021-06-17 11-21-41](https://user-images.githubusercontent.com/213943/122369750-c2fa6f80-cf5e-11eb-91cc-04f87ced4d2b.png)

**Comment by PVince81** [comment]
I've seen a related but different issue: if you click on the avatar menu in the top bar, it will click on the parent "a" and display the settings dialog.

I think both can be prevented by having the Avatar component stop the events with `.prevent`.

**Comment by PVince81** [comment]
Seems to be another trouble with v-tooltip as that's where the click handler is happening.
The click handler from Avatar is never called apparently.

I've checked the latest version of v-tooltip and it also doesn't call `evt.preventDefault()` or something.
So probably this is not fixable on nextcloud-vue side...

which means that consumers of Avatar need to make sure that if they wrap them into an `a` element or something, they need to detect whether the click landed on the avatar or outside before proceeding...

**Comment by PVince81** [comment]
another idea: disable the menu in those places

**Comment by PVince81** [comment]
I have a fix for the top bar case here: https://github.com/nextcloud/spreed/pull/5836

the fix might not be suitable for the left sidebar because we do want the ConversationIcon to be clickable when switching conversations, but only when it's not one to one, otherwise we'd want the avatar menu.

**Comment by PVince81** [comment]
PR here for disabling the menu for now: https://github.com/nextcloud/spreed/pull/5837
