### ISSUE TITLE
v12 Talk white screen

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/spreed#5802]
## Steps to reproduce
1. Go to Talk in browser

### Expected behaviour
Something should be there.

### Actual behaviour
White screen.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
12 alpha

**Custom Signaling server configured:** yes/no and version (see additional admin settings: 
No

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
No
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
No

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Windows
**Browser name:** Firefox/Chrome/...
Edge
**Browser version:** 50.1/55/...
Edge 91.0.864.41 (Official build) (64-bit)
### Browser log

<details>
index.js:46 No OC found
Hr @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
re @ globals.js:62
2globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
re @ globals.js:62
ProxyBus.ts:17 Proxying an event bus of version 1.3.0 with 2.0.0
t.ProxyBus @ ProxyBus.ts:17
3globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
re @ globals.js:62
ProxyBus.ts:17 Proxying an event bus of version 1.3.0 with 2.0.0
e @ ProxyBus.ts:17
types.js:243 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
55955 @ types.js:243
ProxyBus.ts:17 Proxying an event bus of version 1.3.0 with 2.0.0
e.ProxyBus @ ProxyBus.ts:17
capabilities.js:35 OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities
getCapabilities @ capabilities.js:35
OBJLoader2.js:47 Using OBJLoader2 version: 3.2.0
89globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
re @ globals.js:62
cloud.mydomaingoeshere.com/:1 Refused to execute script from 'https://cloud.mydomaingoeshere.com/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
2globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
re @ globals.js:62
cloud.mydomaingoeshere.com/:1 Refused to execute script from 'https://cloud.mydomaingoeshere.com/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Viewer.vue:263 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:263
Viewer.vue:566 The following mime is already registered text/csv Object
(anonymous) @ Viewer.vue:566
Viewer.vue:263 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:263
session-heartbeat.js:101 session heartbeat polling started
Viewer.vue:263 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:263
init-collections.js:44 OCA.Sharing.ShareSearch not ready
(anonymous) @ init-collections.js:44
init-collections.js:44 OCA.Sharing.ShareSearch not ready
(anonymous) @ init-collections.js:44
5util.js:135 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:135
(anonymous) @ init.js:101
each @ jquery.js:354
each @ jquery.js:189
(anonymous) @ init.js:100

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Linux 5.10.28-Unraid x86_64
**Web server:** Apache/Nginx
Nginx
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB
**PHP version:** 7.2/7.3/7.4

**Nextcloud Version:** (see admin page)
22.0.0 beta 5
**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
https://gist.github.com/HammyHavoc/2d2d1e2ec88e45d6337551d5829d7695
```
</details>
![image](https://user-images.githubusercontent.com/503951/122573853-eef12000-d046-11eb-924e-3144083bf684.png)

**Comment by nickvergessen** [comment]
Please check the browser console and the nextcloud.log

**Comment by HammyHavoc** [comment]
Sorry about the incomplete report; battery was on 1%. I've gone ahead and added more details for you.

**Comment by nickvergessen** [comment]
> index.js:46 No OC found

That sounds like a generic error of your nextcloud which will block any javascript based app to work.

**Comment by HammyHavoc** [comment]
At the risk of sounding thoroughly clueless, what's the next step from here?

What are some other, common JavaScript NC apps I could try to test if it's a JS related issue?

**Comment by nickvergessen** [comment]
It seems that your beta 5 of the server was either not fully deployed or is corrupted. Try redownloading it

**Comment by HammyHavoc** [comment]
Unfortunately, no luck with that.

What's a JS based NC app that I can try? Latest version of Talk is the only app that isn't working as expected. No issues with Mail, Deck, Files, Tasks, News, Notes or Calendar.

**Comment by nickvergessen** [comment]
So, we deployed this on our company server and it works quite fine. 22.0.0-beta.5 together with Talk 12.0.0-alpha.2

Maybe you can post a link to your test instance or try to redeploy it. Otherwise we can't really help you here.

**Comment by HammyHavoc** [comment]
The new pre-release works and resolves this issue.
