### ISSUE TITLE
Chat input blocked and not focused sometimes

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5811]
## Steps to reproduce
1. Use Talk on c.nc.c
2. Open a conversation
3. Start typing

### Expected behaviour
You see some letters in the input

### Actual behaviour
Input is not focused and empty

## Talk app

**Talk app version:** 12.0.0-alpha.2

**Custom Signaling server configured:**yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:**Ubuntu

**Browser name:** Firefox

**Browser version:** 89.0.1

**Comment by PVince81** [comment]
it is possible that now the "focus" call for the message we scroll to is conflicting with the focus logic of the field.

the code already existed before for when focussing on a message as a result of an anchor in the URL.
now with the unread marker we call the same code, but should not focus, then.

I'll have a look

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5823

**Comment by nickvergessen** [comment]
Pr forgot to autoclose this
