### ISSUE TITLE
Bug Report: Lobby Option in Talk Not Working 

### ISSUE THREAD

**Issue by stownsend101** [nextcloud/spreed#5813]
## Steps to reproduce
1. Create conversation 
2. Select 'enable lobby'
3. Start call 

### Expected behaviour
All attendees join lobby, and moderator accepts into conversation to join call. 

### Actual behaviour
Lobby not appearing, guest join with no approval step. 

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 
Version 21. 

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser
Safari 

**Microphone available:** yes/no
Yes 

**Camera available:** yes/no
Yes

**Operating system:** Windows/Ubuntu/...
Apple

**Browser name:** Firefox/Chrome/...
Safari 

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.2/7.3/7.4

**Nextcloud Version:** (see admin page)
21 

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Works fine here.

Either you need to be more specific on your steps or provide more details in another way so we can reproduce it.
