### ISSUE TITLE
Voice message icon vanishes when chat message is entered, but doesn't return on clean

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5816]
## Steps to reproduce
1. Open a chat
2. See the voice message icon next to the chat input
3. Type a letter into the input
4. See the voice message icon disappear
5. Empty the input again

### Expected behaviour

Voice message icon returns.

### Actual behaviour

The voice message icon is permanently replaced by the arrow icon for sending the message.

![Bildschirmfoto von 2021-06-21 14-27-44](https://user-images.githubusercontent.com/1374172/122761755-de39e780-d29c-11eb-98e8-8704de495b8a.png)

At this point I'm not able to record a voice message anymore until I send another chat message

## Talk app

**Talk app version:** the one on c.nc.com

**Comment by nickvergessen** [comment]
It's due to CTRL+X, if you backspace it works.


Ref https://github.com/nextcloud/spreed/pull/5610#discussion_r649981619

**Comment by ChristophWurst** [comment]
> It's due to CTRL+X, if you backspace it works.

Not quite. On FF/Arch it only works with <kbd>Del</kbd>, not with <kbd><-</kbd>
