### ISSUE TITLE
Disable video doesn't work anymore

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5817]
## Steps to reproduce
1. Have a video call
2. Attempt to disable other users' video

### Expected behaviour

The video hides.

### Actual behaviour

From a user perspective nothing happens. In the console I see an error

![Bildschirmfoto von 2021-06-21 14-30-22](https://user-images.githubusercontent.com/1374172/122762350-864fb080-d29d-11eb-90e5-4aef99f38c26.png)

## Talk app

**Talk app version:** the one on c.nc.com

**Comment by nickvergessen** [comment]
Regression from #5773

**Comment by PVince81** [comment]
I'll have a look
