### ISSUE TITLE
Toastify overlapping each other

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5819]
## Steps to reproduce
1. Create a conversation
2. Open the settings
3. Change guests, lobby and other checkboxes

### Expected behaviour
Have multiple toasts

### Actual behaviour
Regression from #5794 

![Bildschirmfoto von 2021-06-21 14-55-13](https://user-images.githubusercontent.com/213943/122765596-f57ad400-d2a0-11eb-86fc-845a5b4cb920.png)

**Comment by PVince81** [comment]
Damn, indeed we might be overriding too hard.
Will see if this can be achieved with a margin-top instead.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5821
