### ISSUE TITLE
Not possible to add TURN server which uses login + password

### ISSUE THREAD

**Issue by oparoz** [nextcloud/spreed#582]
## Steps to reproduce

1. Add a TURN server

### Expected behaviour

I can add my TURN server which uses a login and a password

### Actual behaviour

I only see a "Shared secret" field

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows/Android

**Browser name:** Firefox/Vivaldi/Iridium/Android app

**Browser version:** Firefox 57.0.4

### Browser log

<details>
```
ICE failed, add a TURN server and see about:webrtc for more details
```
IP adresses shown in the traces are local IP

</details>

## Spreed app

**Spreed app version:** 3.0

**Custom TURN server configured:** not yet

**Custom STUN server configured:** yes

**Comment by Ivansss** [comment]
TURN server configuration is an **Administrator setting**.
An administrator can setup a TURN server with the url + shared secret and the Talk app will generate user names and passwords for every user when needed.
Talk app doesn't provide this TURN server configuration in personal settings for every user.

**Comment by oparoz** [comment]
I'm talking about the admin settings which only accepts a shared secret. TURN servers can be configured with a login and a password instead.

**Comment by fancycode** [comment]
The TURN settings are sent to any participant that is using the service. If you could configure a (global) username/password, this could be abused by participants as you basically give them your non-expiring TURN credentials. That's why the global setting uses a shared secret and generates temporary usernames/passwords that expire after some time.

However it could make sense to have TURN with username/password as per-user configuration?

**Comment by oparoz** [comment]
Interesting.
If I got this right, 
* shared secret -> users get temp credentials
* username/password -> users get the global credentials

It's a shame that it's not possible to also generate temp credentials when using a global account, because even for internal use, it's not a good idea to share those credentials.

I think per-user configuration would be too much of a corner-case. It wouldn't improve the overall reliability of the service.
