### ISSUE TITLE
Notifications for one-to-one chats don't vanish anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5829]
## Steps to reproduce
1. ????
2. Chat with vincent

### Expected behaviour
All work done

### Actual behaviour
Still notifications from vincent open

**Comment by PVince81** [comment]
solution: don't chat with Vincent who's known to trigger all kinds of bugs :wink:

**Comment by nickvergessen** [comment]
Can't reproduce locally 🤔 

Potential things that can be involved:
* Multiple open windows/tabs/devices
* notify_push

**Comment by nickvergessen** [comment]
Doesn't happen anymore
