### ISSUE TITLE
More meaningful error message for not supported browsers

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/spreed#583]
When you use a web browser not supported by the talk app (I guess when the browser does not offer WebRTC support), the app just displays text that says "error accessing mic and camera". The rest of the screen is empty and there are no further menus or information displayed. I'd recommend to display a more meaningful error message because some users won't understand what is going on and just think the app is broken, etc...

![bildschirmfoto 2018-01-12 um 10 18 32](https://user-images.githubusercontent.com/8535968/34867853-fbd868ce-f781-11e7-951d-926cf6ef6ff7.png)

**Comment by nickvergessen** [comment]
Actually we do this, we have 4 different error messages depending on the response of the browser:

* Access to microphone & camera is only possible with HTTPS
* Access to microphone & camera was denied
* WebRTC is not supported in your browser
  Please use a different browser like Firefox or Chrome
* Error while accessing microphone & camera
  'Error while accessing microphone & camera: ' + error.message

Which browser are you using that shows this message?

**Comment by ho1ger** [comment]
I just re-checked the bug. Apparently this was only a temporary issue for the 3.0.0 version. Meanwhile I upgraded talk to 3.0.1 and now the browser (which is Safari in my case) also asked "do you want to allow ... to access camera & microphone". I.e., the bug seems to be fixed with 3.0.1. I can now also use Safari for chats/voice/video.
