### ISSUE TITLE
Raise sidebar/viewer techdebt issue

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5830]
Ref https://github.com/nextcloud/spreed/pull/5824#pullrequestreview-688457727

I understand too little to see what the problem is, so I leave this up to you @danxuliu

**Comment by danxuliu** [comment]
Done:
https://github.com/nextcloud/nextcloud-vue/issues/2052
https://github.com/nextcloud/nextcloud-vue/issues/2053
