### ISSUE TITLE
Avatar menu icons missing

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5834]
## Steps to reproduce
1. Create conversation
2. Add some participants
3. Open avatar menu for participant

### Expected behaviour
Entry for one to one chat with a magnifying glass icon.

### Actual behaviour
Entry is there but the icon is not visible:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/277525/122877971-7e444f00-d337-11eb-9326-684deb1c8211.png">

## Talk app

**Talk app version:** 12.0.0 git master 4a49dc593c39fae2b5911d9b0dd5c61924957ac8

Likely related to the recent nextcloud-vue updates

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2021-06-22 09-11-07](https://user-images.githubusercontent.com/213943/122880053-d9774100-d339-11eb-8871-f680b9bee4f7.png)

Also going ham on the dashboard (where you can't even open it as it automatically opens the conversation already)

**Comment by PVince81** [comment]
okay I'll just disable the menu in the dashbaord as well as part of a PR I'm working on

**Comment by PVince81** [comment]
this PR will remove the menu in dashboard: https://github.com/nextcloud/spreed/pull/5837

**Comment by nickvergessen** [comment]
Actually the problem is the padding from:
https://github.com/nextcloud/nextcloud-vue/blame/90b8c1224d1268d66c23d28aa230a6980fb136db/src/components/PopoverMenu/PopoverMenuItem.vue#L306-L311

**Comment by nickvergessen** [comment]
If `padding: $icon-margin;` is replaced with `margin: $icon-margin;` it works as expected.

**Comment by Pytal** [comment]
Fix in https://github.com/nextcloud/nextcloud-vue/pull/2289
