### ISSUE TITLE
"More actions" is overlapping the settings option

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5835]
## Steps to reproduce
1. Start/join a call
2. Want to check your settings because the camera is not working
3. Hover the button for a short time before clicking

### Expected behaviour
You see the settings ActionButton

### Actual behaviour
It's overlapped by "More actions" tooltip of the `…` button
![Bildschirmfoto von 2021-06-22 08-54-51](https://user-images.githubusercontent.com/213943/122878238-cf544300-d337-11eb-8be2-0403f1ee1f1b.png)

**Comment by PVince81** [comment]
I don't think it's a regression, what you see is the tooltip.

It looks slightly less shitty in bright mode.

Strange, it seems the tooltip's z-index is changing dynamically. I managed to reproduce the issue only once. The second time the tooltip would appear behind the popover.

Possible solution: disable the tooltip text whenever the action menu is open, this should probably be done in the Action component in nextcloud-vue.

**Comment by nickvergessen** [comment]
> Possible solution: disable the tooltip text whenever the action menu is open, this should probably be done in the Action component in nextcloud-vue.

I think that is the best solution

> I don't think it's a regression, what you see is the tooltip.

I know it's the tooltip. But yeah just went back to 21 and also happens there since we have the ... menu basically:
https://github.com/nextcloud/spreed/commit/710957e4062a76fb27fccc678b5a24de4b3266f7#diff-19eee90d2a04c15ea133eff24b9b5974b6ac3189fdb1e382e9ae689dd2c6a720R90-R91

**Comment by nickvergessen** [comment]
Not happening anymore with the topbar
