### ISSUE TITLE
Over sized field in talk_sessions leads to avoidable incompatibility

### ISSUE THREAD

**Issue by ClCfe** [nextcloud/spreed#5838]
Hello

In table migration for talk_sessions, using varchar(512) instead of varchar(255) for field `session_id`

https://github.com/nextcloud/spreed/blob/79cf762ffa713a8a158806b993934922ba2fa0e1/lib/Migration/Version10000Date20201015134000.php#L156

may throw

[settings] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes at <<closure>>

But, as we can see, session_id field needs "only" 255 char:

https://github.com/nextcloud/spreed/blob/79cf762ffa713a8a158806b993934922ba2fa0e1/lib/Service/SessionService.php#L109

this allows to avoid an error on MySQL / MariaDB (old) installations not using `innodb_large_prefix=1` and `innodb_file_format=BARRACUDA`

PS: fix only for utf8, not utf8mb4

**Comment by nickvergessen** [comment]
The High-performance backend creates 512 char session ids.

See https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html for how to update to utf8mb4

Talk is not supported to work without it.
