### ISSUE TITLE
Participant list scroll doesn't reset when switching rooms

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5841]
## Steps to reproduce
1. Open a chat that has a lot of participants and scroll to the bottom
2. Open a chat that has less participants but is still scrollable

### Expected behaviour
Participant list is scrolled to the top

### Actual behaviour
Participant list is scrolled to the bottom

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5844
