### ISSUE TITLE
Wrong message when navigating away while sending a chat message

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5842]
## Steps to reproduce
1. Add a `sleep(7);` before https://github.com/nextcloud/spreed/blob/2c3f80bb08793fec62a95478187ffafffb35bbff/lib/Controller/ChatController.php#L217
2. Write a message and immediately navigate away

### Expected behaviour
Message send or a warning that it is still trying to

### Actual behaviour
Message about leaving the call Oo
![Bildschirmfoto von 2021-06-22 13-44-50](https://user-images.githubusercontent.com/213943/122919654-c461d880-d360-11eb-8bf3-2944895f958f.png)

**Comment by PVince81** [comment]
further issue: even if you leave the message ends up being posted anyway.

we should abort sending when going away to avoid surprising the user

**Comment by PVince81** [comment]
as discussed, let's keep the background send.

see PR to limit the warning to leaving the page completely: https://github.com/nextcloud/spreed/pull/5843
