### ISSUE TITLE
Could not send info never goes away, even if message was resend

### ISSUE THREAD

**Issue by blizzz** [nextcloud/spreed#5845]
## Steps to reproduce
1. send a message while network problems
2. hover over the exclamation mark, click the recent icon
3. submit the message again

### Expected behaviour

The info about the unsent message goes away. (But also a way to cancel it at all.)

### Actual behaviour

It goes away only after a reload

## Talk app

**Talk app version:** 12 Alpha 3

![Screenshot_20210622_144520](https://user-images.githubusercontent.com/2184312/122928038-c2e8de00-d369-11eb-9ab1-232bcbc3861e.png)

(the red annotation is asking how to remove this)

**Comment by PVince81** [comment]
I've noticed this before. I think we should delete this temporary message as soon as the user clicks retry.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/1c2aae6c8745d7b5d19122c5da630914f9cb8d20/src/components/NewMessageForm/NewMessageForm.vue#L363

Deletion code is in place, seems to be broken?

**Comment by PVince81** [comment]
indeed, I'll investigate

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5856
