### ISSUE TITLE
Can't re-enable join sounds

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#5846]
Latest talk v12.0.0-alpha.3 

After disabling the join/leave sounds, you can't re-enable them
The request is always
![image](https://user-images.githubusercontent.com/14975046/122931907-9636c580-d36d-11eb-9dcb-1f447c9c70f0.png)

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5852
