### ISSUE TITLE
Do not fetch the full room list again when only a single room has changed

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#5847]
`roomlist` events sent by the external signaling server provide the id of the changed room in `update.roomid`. Currently when those events are received [the full room list is fetched again](https://github.com/nextcloud/spreed/blob/2bba6b48760ead80bdc0ec1abba4a28f49703f6f/src/utils/signaling.js#L1189), but in theory it should be enough to query just that specific room and update its data.

**Comment by PVince81** [comment]
back then there was no "fetchConversation" action in the store. there is one now.

would be even cooler if signaling could already include the payload so we don't need to refetch, but might be a bit heavy I guess

**Comment by PVince81** [comment]
happy to take care, seems like a quick win

there were concerns from @nickvergessen about refetching because it means every participant would refetch the same room at the same time, so we could add some jitter / random delay + debounce before doing so to avoid everyone hammering the server at the same time.

I'm assuming that we only receive events about the currently joined room being changed ? or also other ones ?

**Comment by fancycode** [comment]
It it helps, the room update event should already include all properties as returned from [Room::getPropertiesForSignaling](https://github.com/nextcloud/spreed/blob/40ec034568336675c9d3230ee2df6afb26a0ea87/lib/Room.php#L381).

**Comment by danxuliu** [comment]
> would be even cooler if signaling could already include the payload so we don't need to refetch, but might be a bit heavy I guess

Yes, that should be already possible for some properties (see @fancycode's comment). But I would start by just fetching the room that changed instead of the full list and do something more elaborate later.

> happy to take care, seems like a quick win

I just noted it down so it was not forgotten, but I did not intend to work on it right now, so feel free to do it ;-)

> there were concerns from @nickvergessen about refetching because it means every participant would refetch the same room at the same time, so we could add some jitter / random delay + debounce before doing so to avoid everyone hammering the server at the same time.

:+1: 

> I'm assuming that we only receive events about the currently joined room being changed ? or also other ones ?

If I am not mistaken you receive update events about any room that you are a participant of.

**Comment by nickvergessen** [comment]
As long as we still refresh (un)regularly to update the message count and others it's fine.

**Comment by PVince81** [comment]
does internal signaling also fire these events or is it limited to standalone signaling ? (to see if we need fallback code)

**Comment by danxuliu** [comment]
It is limited to standalone signaling. Internal signaling only fires `usersInRoom` events when the long polling ends or [`refresh-participants-list` is triggered](https://github.com/nextcloud/spreed/blob/4009de75a20434a484e2bdb1c85153e6fc364b45/lib/Signaling/Listener.php#L55-L99) (but it does not happen in the same cases as the `roomList` event from the standalone signaling), or `message` events when a message is sent by other participant (for example, to send a candidate or a control message).

**Comment by nickvergessen** [comment]
But then the 30sec interval just has to be enough

**Comment by nickvergessen** [comment]
We are doing this since some time now by only fetching modified rooms
