### ISSUE TITLE
Conversation icon+call icon shown in the topbar while in a call

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5853]
## Steps to reproduce
1. Join a call
2. Check the topbar
3. 
![Bildschirmfoto von 2021-06-23 08-55-03](https://user-images.githubusercontent.com/213943/123050215-bebbcf80-d400-11eb-9086-681f39657963.png)

**Comment by PVince81** [comment]
PR: https://github.com/nextcloud/spreed/pull/5854

**Comment by nickvergessen** [comment]
Fixed
