### ISSUE TITLE
Screenshare icon does not indicate/change at all when screensharing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#5859]
## Steps to reproduce
1. Start a call
2. Start a screenshare
3. Forgot you were screensharing cause it’s not obvious

### Expected behaviour
The screenshare icon communicates the state, just like audio and video on/off do. (This is also something which was the case before, although the strikethrough display might not have been the best default icon. :)

### Actual behaviour
The icon stays the exact same, not even the opacity changes.

As an example, here’s how it looks like in Discord, very present and obvious:
![image](https://user-images.githubusercontent.com/925062/123110207-27746d80-d43c-11eb-9560-01c5dfce9872.png)

**Comment by nickvergessen** [comment]
As mentioned in the chat, should be a regression from moving to the actions component
