### ISSUE TITLE
Nextcloud Talk APP NOT Working

### ISSUE THREAD

**Issue by andyxh** [nextcloud/spreed#586]
Hello so the nextcloud talk app on my server doesn't work correct. I tried doing a call and I can see my self but everything else is black and I cant hear anyone or see them. I'm using nextcloud 13 beta RC1. I tired different browsers and I tried ios and android app and still no luck. I don't see any error in the event log

**Comment by Ivansss** [comment]
@andyxh are you trying to call the same user or different users?
Calling the same user will not work because we don't support multiple sessions of the same user at the moment.

Also, you should try to be more precise when you open an issue.
Opening an issue with "Nextcloud Talk APP NOT Working" as a title is just not helpful.

**Comment by andyxh** [comment]
Hey I'm working on getting more info for you. No I'm trying different users.  Okay, so i tested a few more things out. I've done ios to ios and shows black screen and waiting for user to join group and both users have joined no audio or video. ios to android same thing. Google Chrome Windows Desktop to ios works, Google Chrome Windows Desktop to android works.

**Comment by jookk** [comment]
Yes, mine working as yours. 
Calling from desktop (android) chrome browser to another user on talk android app working fine. Audio and video working. 
from android talk app to chrome browser - all fine as previous.
Whats not working is call from Talk to Talk app on android. And I have STUN / TURN server enabled, so network to network (nat) :) Great job!

**Comment by jookk** [comment]
I want to specify, that I had previously installed spreed.me webrtc server backend and nextcloud app. With spreed.me, Talk didnt worked. So, I removed backend, purged configs, and removed nextcloud spreed.me and talk. Server reboot and new talk download.

**Comment by andyxh** [comment]
Sorry but are you still having an issue?

**Comment by jookk** [comment]
Yes, I have still issuue with making call from Talk app to Talk app. 
But, I updated Talk for android from G play, but i will try morning and write out.

**Comment by nickvergessen** [comment]
@andyxh are you behind a firewall? Do you have a Turn server configured?
When the app shows a black screen it could also miss permissions for video and/or audio.
Did you check that?

Just confirmed with Ivan, that a call from android to iOS is working smooth!

**Comment by andyxh** [comment]
Yes i have a firewall, do i need to open a port? 
![capture](https://user-images.githubusercontent.com/24574019/34998785-a7520b94-faa5-11e7-9dc4-7838815ab699.PNG)

**Comment by nickvergessen** [comment]
No, in case of a firewall you need to setup and configure a turn server (or you look for someone that hosts it for you).

**Comment by Zjemm** [comment]
Well that's quite an issue then. Because most people with home internet access are behind consumer firewalls. Most cable and vdsl modems are firewalls that provide Nat to allow multiple clients to get internet access.

So for most consumers this is not going to fly.

Also when at work you will be behind an corporate firewall. Same problem.

Unless you have a direct public IP. Calling with this technique isn't going to work

Or am I missing something?

I have the exact same issue with matrix/riot which also use the same technique

**Comment by andyxh** [comment]
Yes I completely agree with @Zjemm.

Sent from my iPhone 7 Plus

On Jan 27, 2018, at 8:08 AM, Zjemm <notifications@github.com<mailto:notifications@github.com>> wrote:


Well that's quite an issue then. Because most people with home internet access are behind consumer firewalls. Most cable and vdsl modems are firewalls that provide Nat to allow multiple clients to get internet access.

So for most consumers this is not going to fly.

Also when at work you will be behind an corporate firewall. Same problem.

Unless you have a direct public IP. Calling with this technique isn't going to work

Or am I missing something?

I have the exact same issue with matrix/riot which also use the same technique

**Comment by Upperholme** [comment]
This seems to be something of a showstopper for the majority of users. At the very least I'd say it would be essential to communicate the requirement for a TURN server to be configured to the user at the point of enabling the app?

**Comment by nickvergessen** [comment]
> This seems to be something of a showstopper for the majority of users. At the very least I'd say it would be essential to communicate the requirement for a TURN server to be configured to the user at the point of enabling the app?

@Upperholme no, as said above you only need it when you have a restrictive firewall (not a default one from your ISP). But yeah sure, we could show some hints to the admin on first enable and lead them to the settings. Can you create a new issue for that?

**Comment by nickvergessen** [comment]
@andyxh we just tested again with the latest releases and calling from android to ios, android to chrome and chrome to ios all works.
If you are still having issues with that, please open an issue in either app repository:
* https://github.com/nextcloud/talk-ios
* https://github.com/nextcloud/talk-android

Also note, that when android to chrome is working and/or both phones are in the same network, the issue can not be related to a missing TURN server.
