### ISSUE TITLE
When screen sharing, `leave call` button should be smaller and another `end screensharing` button should be next to it

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#5864]
**Is your feature request related to a problem? Please describe.**
When wanting to end the screen share, brain often goes in auto-mode and press the `leave call` button instead
I've seen other users do the same mistake quite a lot

**Describe the solution you'd like**
Reduce the size of the `leave call` button on the top right, and add a `end screen share` with big red design next to it.

**Comment by PVince81** [comment]
at some point we'll also want [end meeting for all](#5395) so we need to take this into account in the buttons concept

**Comment by nickvergessen** [comment]
Could also make the end call button "normal" colors and highlight the screenshare icon with red?

**Comment by skjnldsv** [comment]
Even if red, at the bottom it's not as discoverable I think

**Comment by nickvergessen** [comment]
By now the button is closer to the leave call button so it's more obvious to find:
![grafik](https://github.com/nextcloud/spreed/assets/213943/1f4edaec-18c7-4dfd-9b35-05633171d177)

If more things should be done #7792 should cover it
