### ISSUE TITLE
Reply quote glitches + shifted emoji button when replying

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5870]
## Steps to reproduce
1. Send a message
2. Reply to the message

### Expected behaviour
Nice looking UI

### Actual behaviour
Emoji button shifts up.
Reply quote box is outside the input field now ?? Was this a new design choice or a bug ?
<img width="545" alt="image" src="https://user-images.githubusercontent.com/277525/123381724-623bea00-d591-11eb-8593-b978387e7583.png">

## Talk app

**Talk app version:** 12.0.0 git master af58b3100dcde68c9c4affab371a99aec5a78a9d

**Comment by PVince81** [comment]
PR for the emoji button: https://github.com/nextcloud/spreed/pull/5871

for the quote box position, will need input from @marcoambrosini whether this design change was intended. The quote box used to be inside the input frame.

**Comment by nickvergessen** [comment]
> The quote box used to be inside the input frame.

No, or well maybe technically but not visually: (screenshot from 21)
![Bildschirmfoto von 2021-06-25 10-55-35](https://user-images.githubusercontent.com/213943/123398518-edbe7680-d5a3-11eb-879e-87ed06d1ce9e.png)
