### ISSUE TITLE
Replace local acli component with ListItem

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#5874]
https://github.com/nextcloud/spreed/blob/799ae76d11a13439ffe49801985f1c6d35aeb133/src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue#L23-L64

https://nextcloud-vue-components.netlify.app/#/Components/List%20items?id=listitem

cc @marcoambrosini

**Comment by nickvergessen** [comment]
See #5437
