### ISSUE TITLE
Details tab text overlap

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5878]
## Steps to reproduce
1. Open the details tab in a conversation in the right sidebar

### Expected behaviour
Nice looking tab contents

### Actual behaviour
<img width="251" alt="image" src="https://user-images.githubusercontent.com/277525/123420942-7fd27900-d5bc-11eb-830c-776478d45da4.png">

## Talk app

**Talk app version:** 12.0.0 from c.nc.com

**Comment by nickvergessen** [comment]
Seems fixed in recent versions with french language
