### ISSUE TITLE
Show Chat even if no cam, mic is connected

### ISSUE THREAD

**Issue by frogueat** [nextcloud/spreed#588]
## Steps to reproduce
1. Have no mic/cam connected to the pc
2. go to the app
3. see the message "no access to mic/cam"

### Expected behaviour
Would be great if than at least the chat-functionality would work

### Actual behaviour
Nothing can be done but connect a mic/cam and reload the app

## Browser

**Microphone available:** no

**Camera available:** no

**Operating system:** mac

**Browser name:** Firefox

**Browser version:** 58

### Browser log

<details>
</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
many many
</details>

**Comment by kertase** [comment]
Would be great in deed, should be able to chat without having to share mic or webcam

**Comment by nickvergessen** [comment]
Dupliacte of #538
