### ISSUE TITLE
Security Issue, find Chat Rooms using Embeds

### ISSUE THREAD

**Issue by timondev** [nextcloud/spreed#5883]
## Steps to reproduce
1. Use any Software that embeds Rich Information for URLs
2. Try urls with yournextcloud.com/call/XXXXXXXX (replace X with random characters)
3. Check if you get rich information about your cloud or (if it's a correct url) no information

### Expected behaviour
No Information about your nextcloud on call urls

### Actual behaviour
Incorrect urls give rich information about the cloud, correct ones do not

## Talk app

**Talk app version:** 11.2.2

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by nickvergessen** [comment]
The randomness is big enough that this is not a security issue. And even if you guessed a token you can't do anything? 🤷‍♂️

**Comment by timondev** [comment]
As long as you password protect your chats, I guess not. Are there other security measures that would intervene if you would bruteforce with that technique?

**Comment by nickvergessen** [comment]
> As long as you password protect your chats, I guess not.

First you have to make them public as well.

And then the token security is 33^8 which is ~ 1.4*10^12 which is its a chance of 1 to 1.4 trillion to guess it.
