### ISSUE TITLE
Mark conversation as unread

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#5886]
**Is your feature request related to a problem? Please describe.**
I read a conversation and want to mark it as unread again, so that I can address it later again.

**Describe the solution you'd like**
Mark as unread for a conversation, similar like other messengers are doing it.

**Comment by PVince81** [comment]
@tobiasKaminsky this is already available. Please click the three dots near the last message you've read and you set the marker there by selecting "mark as unread" in the menu.
