### ISSUE TITLE
Can't listen to audio messages in Safari

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#5888]
## Steps to reproduce
1. Try to listen to an audio message in Safari 14.1

### Expected behaviour
It works.

### Actual behaviour
It does not work and shows "Error".

<img width="452" alt="Screenshot 2021-06-28 at 13 22 51" src="https://user-images.githubusercontent.com/878997/123628962-f74e1580-d813-11eb-8555-82a34c01955c.png">

## Talk app

c.nc.c

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS

**Browser name:** Safari

**Browser version:** 14.1

### Browser log

No errors visible.

**Comment by nickvergessen** [comment]
No CSP error or anything?
Can you ask the college where/how he recorded it? there is a difference whether the message was done on android/ios/web

**Comment by LukasReschke** [comment]
> No CSP error or anything?

No errors at all are visible.

> Can you ask the college where/how he recorded it? there is a difference whether the message was done on android/ios/web

@jospoortvliet  / @blizzz do you recall this? :)

**Comment by blizzz** [comment]
I did on Firefox. Arch, btw.

**Comment by nickvergessen** [comment]
Also happens on iPad Safari yet

**Comment by nickvergessen** [comment]
Fixed with #5903
