### ISSUE TITLE
High CPU & Memoery while on talk

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#5890]
Currently running Nextcloud 21.0.2 Talk Version 11.2.2.  Nextcloud Talk  tab is the only thing that i have open in chrome

![image](https://user-images.githubusercontent.com/59488153/123692632-aabb0800-d81c-11eb-847e-74bf1a95ba05.png)

**Comment by nickvergessen** [comment]
Ok.

**Comment by andyxheli** [comment]
OK. I recall it being an issue in the past via https://github.com/nextcloud/spreed/issues/4793 so my question is this related or not ?
