### ISSUE TITLE
Participant list is scrolled to the top when conversations are fetched

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#5904]
Regression(s) introduced in https://github.com/nextcloud/spreed/pull/5844

No matter if the current user is a user or a guest, the conversation watcher is triggered whenever the conversations are fetched (I have not checked why, maybe it is related to the conversation list being purged every time it is fetched), so in user pages the participants tab is scrolled to the top every time that happens, even when staying in the same conversation.

Besides that, in guest pages an error is shown whenever the conversation watcher is triggered, as in guest pages there is no participants tab.

## Steps to reproduce (scenario 1)
- Open a conversation with a long participant list
- Scroll down the participant list
- Wait 30 seconds or more

### Expected behaviour
The participant list is not automatically scrolled.

### Actual behaviour
The participant list is automatically scrolled to the top.

## Steps to reproduce (scenario 2)
- Open a conversation as a guest
- Open the browser console

### Expected behaviour
No errors are shown.

### Actual behaviour
Errors about the participants tab are shown when the conversations are fetched.

**Comment by PVince81** [comment]
hmm ok, so maybe I should have kept the watcher for the token instead of the conversation

but then the existing conversation watcher might have fired still, so maybe need to move both to a token watcher instead

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5905
