### ISSUE TITLE
emoji button not visible in Safari

### ISSUE THREAD

**Issue by Rello** [nextcloud/spreed#5917]
in the current version of cloud.nextcloud.com, the emoji button is hidden.
in HTML it is behind the input so it is overlayed

by moving the emoji stuff second, it works again
![Bildschirmfoto 2021-07-02 um 09 08 39](https://user-images.githubusercontent.com/13385119/124235104-28c92880-db15-11eb-8431-0d6e53af3228.png)

**Comment by nickvergessen** [comment]
cc @marcoambrosini @PVince81

**Comment by gary-kim** [comment]
![image](https://user-images.githubusercontent.com/47195730/124326456-fe30ab80-dbb8-11eb-8813-ba7f644d1930.png)
Seems fine on Firefox? What browser is this on?

**Comment by nickvergessen** [comment]
Title says Safari 🙈

**Comment by gary-kim** [comment]
:see_no_evil:

**Comment by gary-kim** [comment]
:see_no_evil:

**Comment by nickvergessen** [comment]
It feels like safari is overlaying the item.
In the read-only/locked state or the changelog conversation the icon is showing properly.
