### ISSUE TITLE
Error while accessing microphone & camera

### ISSUE THREAD

**Issue by DanLeonelli** [nextcloud/spreed#595]
## Steps to reproduce
1. Try to use the "video calls" app
2.
3.

### Expected behaviour
Use the video calls

### Actual behaviour
Error while accessing microphone and camera

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** macOS High Sierra

**Browser name:** Chrome and Safari

**Browser version:** 63.0.3239.132 (Chrome) / 11.0.2 (Safari)

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`) 2.0.2

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`) No

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`) No

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page) 12.0.4

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>
<img width="1440" alt="screen shot 2018-01-17 at 12 24 15 am" src="https://user-images.githubusercontent.com/35517527/35027116-d2d07f36-fb1c-11e7-9d17-febc46dcedc1.png">
<img width="1440" alt="screen shot 2018-01-17 at 12 24 36 am" src="https://user-images.githubusercontent.com/35517527/35027117-d2e958da-fb1c-11e7-8d3c-716d263c9106.png">

**Comment by nickvergessen** [comment]
Multiple related errors have been fixed for 3.0 which is available with Nextcloud 13 which is to be released soon.
Please check back after you updated to those versions
