### ISSUE TITLE
Call duration format improvements in system message

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5951]
## Steps to reproduce
1. Start a call for about 20 minutes with other people
2. Stop the call
3. Look at the system message with the call duration

### Expected behaviour
Easy to read format that leaves no doubt, easy to read for humans.

### Actual behaviour
For some reason, today I saw "Duration: 21:13" and my brain computed this as 21 hours and 13 minutes, thinking that there was an issue of sorts.

## Talk app

**Talk app version:** 12.0.0 on c.nc.com

## Solution

The part with the seconds doesn't provide any real value.
Either we change the format to "hh:mm" or use something like "h hours and m minutes" (the `moment` library has a module that can render such durations)
The "hh:mm" format might still cause confusion but its advantage is that it's shorter to render, so might be suitable for mobile.

**Comment by PVince81** [comment]
@marcoambrosini thoughts ?

**Comment by nickvergessen** [comment]
The [hh:]mm:ss is very common for call durations in all messengers

**Comment by PVince81** [comment]
> The [hh:]mm:ss is very common for call durations in all messengers

Alright. Maybe designers around the world have done user testing and confirmed that it's ok to do so.
Or it's about conciseness. I guess no reason to do it differently then, closing.
