### ISSUE TITLE
Missing spacing around + button

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5962]
## Steps to reproduce
1. Open talk
2. Look at the "+" button on the top left

### Expected behaviour
Some spacing around it, like before.

### Actual behaviour
Spacing missing on the right:
<img width="134" alt="image" src="https://user-images.githubusercontent.com/277525/124715247-10854f00-df03-11eb-88a8-604ac861e3e1.png">

## Talk app

**Talk app version:** 13.0.0 git master 2144b606228aa40b2fc21f298a3e17ad9a754152

This is must be a very recent regression as I don't see it on c.nc.com @marcoambrosini

**Comment by nickvergessen** [comment]
Works here, which browser?

**Comment by PVince81** [comment]
it's in chromium 91.0.4472.114 with no zoom factor

**Comment by nickvergessen** [comment]
Right, see it there too. works in FF

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/spreed/pull/6201
