### ISSUE TITLE
Lobby - can't set start time

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5980]
Tested with Nextcloud 22 and Talk 12.0.0 on c.nc.com

I enabled the lobby and tried to set a start date:

![image](https://user-images.githubusercontent.com/1589737/124981501-ef714b00-e035-11eb-97e2-455b66663819.png)

But no date/time picker opens if I click on the "start time" input box.

**Comment by PVince81** [comment]
confirmed regression on master

**Comment by PVince81** [comment]
it's behind the dialog
<img width="235" alt="image" src="https://user-images.githubusercontent.com/277525/124983935-e59d1700-e038-11eb-8ce3-9566389d106c.png">

**Comment by PVince81** [comment]
seems I have to increase the picker's z-index from 2000 to 10000 for this to work...
the modal has values around 10000 hard-coded :-/

**Comment by PVince81** [comment]
raised as https://github.com/nextcloud/nextcloud-vue/issues/2097 in nextcloud-vue

**Comment by PVince81** [comment]
PR with quick workaround: https://github.com/nextcloud/spreed/pull/5982

**Comment by PVince81** [comment]
stable21 works fine, so probably the nextcloud-vue update caused the regression
it's broken on stable22 and stable22.1

**Comment by schiessle** [comment]
Awesome, thanks for the super quick fix @PVince81 ! :-)

**Comment by PVince81** [comment]
> Awesome, thanks for the super quick fix @PVince81 ! :-)

I usually consider regressions to be super high priority if they have no workaround
