### ISSUE TITLE
Message list scroll position jumps when switching tab focus

### ISSUE THREAD

**Issue by Pytal** [nextcloud/spreed#5987]
## Steps to reproduce
1. Open a chat with unread messages
2. Scroll down a bit
3. Switch to another tab then switch back

### Expected behaviour
Scroll position shouldn't change.

### Actual behaviour
Message list jumps to first unread message as determined by scroll to mark as read logic.

## Talk app

**Talk app version:** 12.0.0

## Browser

**Browser name:** Chrome

**Browser version:** 91.0.4472.124

**Comment by nickvergessen** [comment]
Already fixed with:
* https://github.com/nextcloud/spreed/pull/5979
* https://github.com/nextcloud/spreed/pull/5978
* https://github.com/nextcloud/spreed/pull/5973
