### ISSUE TITLE
Screensharing prevents menu showing up at right side to open right pane with chat/user list

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/spreed#599]
## Steps to reproduce
1. Start screensharing on Firefox 57.0.4
2. Minimize right pane to only show shared screen

### Expected behaviour
Buttons should show up on the top right corner to reopen right pane

### Actual behaviour
Buttons are not shown/overlayed by shared screen

Screenshot:

![screenshot4](https://user-images.githubusercontent.com/10073629/35050333-783acbd4-fb9a-11e7-9218-3665fb39d163.png)

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Debian 9

**Browser name:** Firefox

**Browser version:** 57.0.4

## Spreed app

**Spreed app version:** 3.0.1

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** (see admin page) 13 RC1

**Comment by Ivansss** [comment]
I just checked it and the problem seems to be that the buttons (full-screen and right-side-bar toggle) are changed to dark style when a screen is being shared.
So the buttons are there but they are not visible.

**Comment by e-alfred** [comment]
Exactly, the buttons are there, but you can't see them.
