### ISSUE TITLE
/ocs/v2.php/apps/spreed/api/v4/room?includeStatus=true takes 45 seconds on c.nc.c

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#5990]
## Steps to reproduce
1. Open the chat web UI
2. It keeps loading until the request finished
3. The requests finishes after 45 seconds.

### Expected behaviour
This should be faster than 45 seconds.

### Actual behaviour
It takes 45 seconds.

## Talk app

c.nc.c

## Browser

Safari Version 14.1.1 on macOS

**Comment by LukasReschke** [comment]
![Screenshot 2021-07-12 at 14 05 02](https://user-images.githubusercontent.com/878997/125284757-28513e80-e31a-11eb-866f-d4f6b2a2c0fa.png)

**Comment by nickvergessen** [comment]
Nothing related in the server log. So no clue. If you have more information that would be helpful.
