### ISSUE TITLE
"Call with 0 guests (Duration x:y)" when starting a 1-1 call between two users

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5991]
## Steps to reproduce
1. Open the convo with another Nextcloud user
2. Start a call
3. ???

### Expected behavior
Tell us what should happen

### Actual behavior

![Bildschirmfoto von 2021-07-12 13-05-34](https://user-images.githubusercontent.com/1374172/125284885-4c148480-e31a-11eb-87ab-b67b0465b520.png)

## Talk app

**Talk app version:** the one on c.nc.com

**Comment by PVince81** [comment]
On master I don't see "0 guests" but "Call with Alice and Bob" even though the current user is Alice.
Possibly a similar bug.

**Comment by PVince81** [comment]
I had 1-1 calls on c.nc.com recently but didn't see the "0 guests" issue, but the one I mentionned above.

**Comment by PVince81** [comment]
> On master I don't see "0 guests" but "Call with Alice and Bob" even though the current user is Alice.
> Possibly a similar bug.

also happening on stable21, so maybe it was expected behavior.

**Comment by PVince81** [comment]
@ChristophWurst have you been able to reproduce the "0 guests" issue again ?

I was not able to reproduce this issue about 0 guests on stable22, so either it was a one-off issue, or there's more steps involved, or it's already solved.

**Comment by nickvergessen** [comment]
> "Call with Alice and Bob" even though the current user is Alice.

there was never handling for "you" in call summary https://github.com/nextcloud/spreed/blob/9e855fc015fce36108d68dc13f595cedd42d80dc/lib/Chat/Parser/SystemMessage.php#L657-L722

**Comment by ChristophWurst** [comment]
> @ChristophWurst have you been able to reproduce the "0 guests" issue again ?

No, it was a one time issue so far but haven't had many 1-1 calls the last few days

**Comment by nickvergessen** [comment]
Database record is:
```json
{"message":"call_ended","parameters":{"users":[],"guests":0,"duration":7}}
```

But that should have exited here already:
https://github.com/nextcloud/spreed/blob/stable22/lib/Activity/Listener.php#L125-L129

So not sure, can not reproduce atm
