### ISSUE TITLE
Nextcloud Talk Notifications Delay (15-20-25s)

### ISSUE THREAD

**Issue by DwinAnderson** [nextcloud/spreed#5992]
## Steps to reproduce
1. iPhone XR (phone-A) and iPhone XR (phone-B), both have identical version of Nextcloud Talk and logged in
2. Close all the applications in phone-A and phone-B (it is also enough to hide application when it was launched)
3. phone-A write message to phone-B. After 20 seconds of doing nothing, notification will be received on phone-B. If phone-A write message1, then immediatelly message2 and then for example message3, so on phone-B they will appear not at the same time, but with delay of 15-20-25 seconds between each other.

### Expected behaviour
1-2 seconds notification of getting message received.

### Actual behaviour
15-20-25 seconds between each notification of getting different messages.

## Talk app

**Talk app version:** 12.0.0

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no (it is written stun.nextcloud.com:443)

## Server configuration

**Operating system**: CentOS 8.4.2105

**Web server:** Nginx 1.14.1

**Database:** Maria 10.3.28

**PHP version:** 8.0.8

**Nextcloud Version:** 22.0.0

**List of activated apps:**

<details>

```
Accessibility	1.7.0
Activity	2.15.0
Brute-force settings	2.2.0
Calendar	2.3.0
Circles	22.0.0
Collabora Online	4.2.0
Collaborative tags	1.11.0
Comments	1.11.0
Contacts	4.0.0
Contacts Interaction	1.2.0
Dashboard	7.1.0
Deck	1.5.0
Deleted files	1.11.0
End-to-End Encryption	1.7.1
Federation	1.11.0
File sharing	1.13.2
First run wizard	2.11.0
Group folders	9.0.2
Log Reader	2.7.0
Mail	1.10.1
Monitoring	1.12.0
News	16.0.0
Nextcloud announcements	1.11.0
Notes	4.1.0
Notifications	2.10.1
Password policy	1.12.0
PDF viewer	2.3.0
Photos	1.4.0
Preview Generator	3.1.1		
Privacy	1.6.0
Recommendations	1.1.0
Right click	1.1.0
Share by mail	1.11.0
Support	1.5.0
Talk	12.0.0
Text	3.3.0
Theming	1.12.0
Two-Factor TOTP Provider	6.1.0
Update notification	1.11.0
Usage survey	1.10.0
User status	1.1.1
Versions	1.14.0
Video player	1.11.0
Weather status	1.1.0
Whiteboard	0.0.3
Auditing / Logging	1.11.0
Default encryption module	2.9.0
External storage support	1.12.1
LDAP user and group backend 1.11.0
```
</details>

**Comment by nickvergessen** [comment]
Seems to be some throttling from Apple, not sure we can do anything about this.

cc @Ivansss

**Comment by DwinAnderson** [comment]
> Seems to be some throttling from Apple, not sure we can do anything about this.
> 
> cc @Ivansss

Really? :( Oh, that's very sad. And nothing possible to do with it? Other apps on phone-A and on phone-B receive notifications from another apps fast, immediatelly (1-2 sec). May be any suggestions where I should look into? Because I am not the only one user on Apple devices, may be others are good with receiving notifications... I haven't found any simular case. I thought that problem was in that i didn't have http-v2 but that wasn't so (for example).
Thank you very much.

**Comment by Ivansss** [comment]
We will track this issue in the Talk iOS app repository. https://github.com/nextcloud/talk-ios/issues/580
