### ISSUE TITLE
Prevent muting others in 1-1 calls

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5993]
## Steps to reproduce
1. Have a 1-1 call
2. Try to mute self but mistakenly click the mute button of the other person
3. Be confused and tell the other person that you're sorry and that should unmute again
4. Laugh at it together

### Expected behaviour
No ability to mute others as there is no real moderation needed.
I'm not sure if this is a good idea.

### Actual behaviour
Ability to mute the other participant.

## Talk app

**Talk app version:** 12.0.0 from c.nc.com

**Comment by nickvergessen** [comment]
I'd like to keep it. Had it already that the other person drops their headset to answer the door or something and creating a feedback loop for me. Being able to mute the other participant is handy in that case, otherwise you need to leave or mute the browser.

**Comment by PVince81** [comment]
good use case, indeed
