### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by myCodingTrip** [nextcloud/spreed#5994]
[root@hadoop000 spreed-master]# ls
appinfo          composer.json  css   jest.config.js  Makefile      package-lock.json  sample-commands      templates
babel.config.js  composer.lock  docs  l10n            mkdocs.yml    psalm.xml          src                  tests
CHANGELOG.md     COPYING        img   lib             package.json  README.md          stylelint.config.js  webpack.js
[root@hadoop000 spreed-master]# make dev-setup
rm -rf js/*
rm -rf /root/spreed-master/build/artifacts
rm -rf node_modules
npm ci

> ejs@2.7.4 postinstall /root/spreed-master/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> core-js@3.14.0 postinstall /root/spreed-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.1 postinstall /root/spreed-master/node_modules/@nextcloud/browser-storage/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@2.6.12 postinstall /root/spreed-master/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.4 postinstall /root/spreed-master/node_modules/@nextcloud/moment/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@2.6.12 postinstall /root/spreed-master/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> deasync@0.1.21 install /root/spreed-master/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting
added 2002 packages in 25.342s

[root@hadoop000 spreed-master]# make build-js
npm run dev

> talk@13.0.0 dev /root/spreed-master
> NODE_ENV=development webpack --config webpack.js

[webpack-cli] Failed to load '/root/spreed-master/webpack.js' config
[webpack-cli] Error: Cannot find module 'webpack'
Require stack:
- /root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js
- /root/spreed-master/node_modules/@nextcloud/webpack-vue-config/index.js
- /root/spreed-master/webpack.js
- /usr/local/nodejs/lib/node_modules/webpack-cli/lib/webpack-cli.js
- /usr/local/nodejs/lib/node_modules/webpack-cli/lib/bootstrap.js
- /usr/local/nodejs/lib/node_modules/webpack-cli/bin/cli.js
- /usr/local/nodejs/lib/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/usr/local/nodejs/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js:24:17)
    at Module._compile (/usr/local/nodejs/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js',
    '/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/index.js',
    '/root/spreed-master/webpack.js',
    '/usr/local/nodejs/lib/node_modules/webpack-cli/lib/webpack-cli.js',
    '/usr/local/nodejs/lib/node_modules/webpack-cli/lib/bootstrap.js',
    '/usr/local/nodejs/lib/node_modules/webpack-cli/bin/cli.js',
    '/usr/local/nodejs/lib/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! talk@13.0.0 dev: `NODE_ENV=development webpack --config webpack.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the talk@13.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-13T20_07_19_931Z-debug.log
make: *** [build-js] Error 2

[root@hadoop000 spreed-master]# node -v
v14.17.3
[root@hadoop000 spreed-master]# npm -v
6.14.13
[root@hadoop000 spreed-master]# webpack -v
webpack 5.44.0
webpack-cli 4.7.2
[root@hadoop000 spreed-master]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

**Comment by PVince81** [comment]
not sure what's going on

mind trying again with Node v14.17.0 ?

**Comment by myCodingTrip** [comment]
> not sure what's going on
> 
> mind trying again with Node v14.17.0 ?

I changed the node version and installed webpack myself, now I am getting the error:

[root@hadoop000 spreed-master]# make dev-setup
rm -rf js/*
rm -rf /root/spreed-master/build/artifacts
rm -rf node_modules
npm ci

> ejs@2.7.4 postinstall /root/spreed-master/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.14.0 postinstall /root/spreed-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.1 postinstall /root/spreed-master/node_modules/@nextcloud/browser-storage/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.12 postinstall /root/spreed-master/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.4 postinstall /root/spreed-master/node_modules/@nextcloud/moment/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> fsevents@1.2.13 install /root/spreed-master/node_modules/chokidar/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported

> core-js@2.6.12 postinstall /root/spreed-master/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> deasync@0.1.21 install /root/spreed-master/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting

> fsevents@1.2.13 install /root/spreed-master/node_modules/jest-haste-map/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported
added 2058 packages in 30.221s
[root@hadoop000 spreed-master]# make build-js
npm run dev

> talk@13.0.0 dev /root/spreed-master
> NODE_ENV=development webpack --config webpack.js

[webpack-cli] Failed to load '/root/spreed-master/webpack.js' config
[webpack-cli] Error: Cannot find module 'eslint-webpack-plugin'
Require stack:
- /root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js
- /root/spreed-master/node_modules/@nextcloud/webpack-vue-config/index.js
- /root/spreed-master/webpack.js
- /root/spreed-master/node_modules/webpack-cli/lib/webpack-cli.js
- /root/spreed-master/node_modules/webpack-cli/lib/bootstrap.js
- /root/spreed-master/node_modules/webpack-cli/bin/cli.js
- /usr/local/nodejs/lib/node_modules/webpack-cli/node_modules/import-local/index.js
- /usr/local/nodejs/lib/node_modules/webpack-cli/bin/cli.js
- /usr/local/nodejs/lib/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (/root/spreed-master/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js:27:22)
    at Module._compile (/root/spreed-master/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (/root/spreed-master/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/index.js:23:18)
    at Module._compile (/root/spreed-master/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/webpack.js',
    '/root/spreed-master/node_modules/@nextcloud/webpack-vue-config/index.js',
    '/root/spreed-master/webpack.js',
    '/root/spreed-master/node_modules/webpack-cli/lib/webpack-cli.js',
    '/root/spreed-master/node_modules/webpack-cli/lib/bootstrap.js',
    '/root/spreed-master/node_modules/webpack-cli/bin/cli.js',
    '/usr/local/nodejs/lib/node_modules/webpack-cli/node_modules/import-local/index.js',
    '/usr/local/nodejs/lib/node_modules/webpack-cli/bin/cli.js',
    '/usr/local/nodejs/lib/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! talk@13.0.0 dev: `NODE_ENV=development webpack --config webpack.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the talk@13.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T01_17_58_138Z-debug.log
make: *** [build-js] Error 2
[root@hadoop000 spreed-master]# node -v
v14.17.0

**Comment by nickvergessen** [comment]
Are you still running npm 6? Node 14 can have both.

Try:
```sh
npm i -g npm@^7
make dev-setup build-js
```

**Comment by myCodingTrip** [comment]
> Are you still running npm 6? Node 14 can have both.
> 
> Try:
> 
> ```shell
> npm i -g npm@^7
> make dev-setup build-js
> ```

Thank you for your answer, the problem is solved
