### ISSUE TITLE
User bubble vertical alignment issue

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5996]
## Steps to reproduce
1. Start a call or trigger any system messages that contain a user bubble

### Expected behaviour
Vertical alignment is optimal.

### Actual behaviour
<img width="259" alt="image" src="https://user-images.githubusercontent.com/277525/125451765-5e848c3b-8abd-474a-9d98-1a23446c5bff.png">

## Talk app

**Talk app version:** 13.0.0 git master (e8936bec0f8a0364c14e058ac71888d60ee6908e)

@marcoambrosini FYI

I tried a quickfix but regardless where I put "vertical-align" or changed "line-height" it didn't yield the wanted results.
Seems that the system message line has line-height: 24px but the bubble only has 20px.

**Comment by ShGKme** [comment]
Not relevant anymore
