### ISSUE TITLE
Setup issue on CI related to InnoDB

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#5998]
## Steps to reproduce

1. Send a PR with only text changes
2. Wait for CI

### Expect
No bada boom

### Actual
Bada boom: `4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE`

See https://github.com/nextcloud/spreed/pull/5932/checks?check_run_id=3066772161 for example

**Comment by nickvergessen** [comment]
Comes from a new DB version. I read about it last week in the engineering chat I think.

**Comment by nickvergessen** [comment]
Server ticket at https://github.com/nextcloud/server/pull/25474
