### ISSUE TITLE
Dynamically choose video quality lower

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#6]
The video quality should be chosen dynamically to ensure the best experience for every user.

**Comment by fancycode** [comment]
WebRTC should adapt to the currently available bandwidth / latency. There should however be a way to set the video quality to grab from the camera which then will be the maximum quality (that is unless we support changing the quality through renegotiation, which doesn't work in all browsers yet).

**Comment by LukasReschke** [comment]
Set to 1280x720 now. (https://github.com/nextcloud/spreed/blob/5573e689843ceaa7f5c3e7e8ccebc23408fd7c9d/js/webrtc.js#L106-L109)
