### ISSUE TITLE
TURN/STUN not working if they have a protocol

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#600]
Say I put: https://stun.mario.com:443 - This would NOT work!

If I put: stun.mario.com:443 - this works.

Is this expected behaviour? Because it's strange UX :-/

cc @nickvergessen

**Comment by nickvergessen** [comment]
Hmm, not sure if it's strange UX, the default of stun is without protocol aswell, that is, because webrtc itself uses stun:stun.mario.com:442 later to connect.
Also we don't control the endpoint of saving this configs, but yeah we could strip it with JS before sending it to the server.

**Comment by fancycode** [comment]
STUN doesn't use `https` as protocol, so it shouldn't be part of the setting. Maybe we can simply strip any protocols from the entered string?

**Comment by mario** [comment]
@fancycode yup, that's what we should do - on the server side :p
