### ISSUE TITLE
Implement Push-To-Talk and Push-To-Mute

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#603]
Ref: https://github.com/nextcloud/talk-android/issues/65

Basically, on Android if you have mic disabled, holding it pulsates the icon and allows sound thus performing push to talk. Lifting your thumb again disables the sound obviously.

### Push to talk

GIVEN my mic is muted
WHEN I press spacebar
AND keep spacebar pressed
THEN my mic is active

GIVEN my mic is active
AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to muted

### Push to mute

GIVEN my mic is active
WHEN I press spacebar
AND keep spacebar pressed
THEN my mic is muted

GIVEN my mic is muted
AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to active

**Comment by grand-lotus-iroh** [comment]
I think this is a beautiful idea.... it would seem to me, the functionality already exist. Just have to find a way to "flip it around". Instead of giving an option to press "m" to toggle mute mic, you would HOLD "M" to enable voice.

so by default, user is always muted. but. when holding "m" they can talk. 

Really looking forward to dumping discord / skype. It would be brilliant if there was a "checkbox" in the specific chat channel admin option to "flip the voice control" settings and make this possible.

**Comment by nickvergessen** [comment]
Things to do:
* Make https://github.com/nextcloud/spreed/blob/8241642ba1ac4f3e15f915d110e24b7403545832/src/components/CallView/LocalMediaControls.vue#L30 use a wrapper so it only works if push-to-talk is not enabled
* Call `toggleAudio` on key down and key up of the m key instead
* Add an option in https://github.com/nextcloud/spreed/blob/b8a860443daff3dc266f419b10caec743a060f5d/src/components/LeftSidebar/LeftSidebar.vue#L76-L84 to select this

This will then work for logged in users. Guests don't have the sidebar yet, so not sure where to add this option.

**Comment by Nyco** [comment]
A more complete ticket: Push to talk, push to mute #3509

**Comment by Nyco** [comment]
**Is your feature request related to a problem? Please describe.**
Two opposite stuations:
- When I am muted, I want to briefly say something to all other participants, and immediately go back to mute
- When my mic is active, I want to briefly mute to sneeze or cough, and immediately go on

It is painfly to look for the very small mic button, aim at it, click on it, do the stuff, and then click again on it.

**Describe the solution you'd like**
Having “Push to talk” and “Push to mute” options, whould allow to win some precious time, and add some dynamics to call already impacted by lag.

The spacebar key is the de facto standard keyboard shorcut, 

**Describe alternatives you've considered**
Push to talk is implemented in most videoconferencing tools.
=> It would be nice to have it in Talk, as it is kind of a lacking feature, which is quite simple and expected from the user point of view.

Some such tools add the "raise hand" to be able to speak when muted, but this is linked to some sort of adminstrative powers, which is more complex.
 
A push to talk/mute is quite an individual feature, and in full control of the user without rights/privilegdes or actions by others, giving immediate results.

**Additional context**
Push to mute, I have seen it anywhere so far, so this might be a funny and useful differentiator for Talk, to be promoted.

**Comment by BloodyIron** [comment]
Push to talk was added to the Android app for Talk, can we please get this implemented for the main talk addon, for the web interface?

**Comment by BloodyIron** [comment]
Yay! So @ma12-co is that for the web version then?

**Comment by ma12-co** [comment]
Yes @BloodyIron :)
