### ISSUE TITLE
Security Question: Relationship with XMPP and End-to-End encryption implementation.

### ISSUE THREAD

**Issue by stevenleeS0ht** [nextcloud/spreed#6034]
1. Is this App based on XMPP protocol?
2. Does this app support end-to-end encryption? (OMEMO or Any other protocol use Double-Ratchet algorithm)
3. Is the compatible with other XMPP server like ejabbered? 

Those information could be included in `README.md`.

**Comment by nickvergessen** [comment]
It's not based on XMPP
It's not compatible with XMPP

We are however coupable with Matterbridge, so if Matterbridge supports XMPP you can bridge Talk with your XMPP this way.

Regarding encryption, calls (video and audio) are end to end encrypted, chat is currently not.
