### ISSUE TITLE
"Leave conversation" is not really "Danger zone" for conversations visible to the instance

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#6037]
**Is your feature request related to a problem? Please describe.**
In conversations which are set to visible to registered users, leaving the conversation is not really a destructive action. So this is a bit scary and not really correct:
![image](https://user-images.githubusercontent.com/925062/126314993-9f2b57cf-c295-427e-9715-988e892503c1.png)

**Describe the solution you'd like**
Hence in the case of you being a member (and not moderator) of the conversation, maybe the title should rather be "Leave conversation" and the text could say "This conversation can be rejoined at any time through the search."

What do you think @marcoambrosini?

**Comment by marcoambrosini** [comment]
Makes sense, though I think it would be too much to create an entire settings section for just this item.. Could we maybe keep them grouped in the same section and rename it?

**Comment by nickvergessen** [comment]
It's dangerous thou if you are a moderator/owner (especially the last one) and then I think it adds quite a lot of complexity for a wording change?

**Comment by marcoambrosini** [comment]
For now I squeezed in a bit more info with the delete chat history pr. Nothing definitive but an improvement over what we have now. Suggestions are welcome

<img width="428" alt="Screenshot 2021-07-22 at 15 53 48" src="https://user-images.githubusercontent.com/26852655/126650848-8ede9769-e068-405e-a665-586c9ae59ccf.png">

**Comment by jancborchardt** [comment]
> It's dangerous thou if you are a moderator/owner (especially the last one) and then I think it adds quite a lot of complexity for a wording change?

Yeah, good point too. Maybe better to keep it consistent whichever state, instead of doing specials. Your call @nickvergessen

**Comment by jancborchardt** [comment]
Oh and @marcoambrosini, the "Delete chat messages" would definitely be before "Delete conversation". Also naming would be better "Delete all messages" since we do not use the word "chat" anywhere.

**Comment by nickvergessen** [comment]
When you are in a call the Tab is called Chat and notifications also mention chat I think. But yeah we could change that.


The order I wondered as well after I saw it today

**Comment by marcoambrosini** [comment]
Yep, agree with both! Will change soon

**Comment by marcoambrosini** [comment]
> When you are in a call the Tab is called Chat and notifications also mention chat I think. But yeah we could change that.

Hmm In that context probably chat is the most helpful word. I think that "conversation" could confuse users

**Comment by nickvergessen** [comment]
Closing as per above, reordering the settings will be done with #5253
