### ISSUE TITLE
Invisible icon for detail Call Info

### ISSUE THREAD

**Issue by xf-** [nextcloud/spreed#604]
## Steps to reproduce
1. Start a Call
2. Close the sidebar
3. Camera left and right are black
4. Find the icon to open the detail again - no text-shadow

### Expected behaviour
Icon should be visible

### Actual behaviour
Icon is in case of black sidebar invisible.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Arch

**Browser name:** Chromium

**Browser version:** up2date

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`) 3.0.1

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Arch

**Web server:** Nginx

**Database:** Maria

**PHP version:** 7.2

**Nextcloud Version:** (see admin page) 13 RC2

**Comment by nickvergessen** [comment]
Can you check if https://github.com/nextcloud/spreed/pull/601/files fixes the issue for you?

**Comment by xf-** [comment]
yeah, it fixes also this issue. I had no Black on Black (i tried the search, but didn't know if the other issue was related)
