### ISSUE TITLE
Cannot open conversation after coming back from suspend

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#6042]
## Steps to reproduce
1. Open Talk
2. Switch a few times between different active conversations
3. Suspend to RAM
4. Restore
5. Try switching conversations

### Expected behaviour
Switch works and joining works (the participant/active state)

### Actual behaviour
The chat view switches but the new message form is stuck on "Joining conversation..."
I remember having a quick glance at the network console and I saw a of of 412 precondition failed from the "lookIntoFuture" calls, probably because the joining process failed for some reason.
Might be related to the "offline mode" handling.

## Talk app

**Talk app version:** the one from c.nc.com

- [ ] TODO: retry to gather more details from network console.
- [ ] TODO: check if a regression, as we touched the message fetching code recently

**Comment by nickvergessen** [comment]
Sounds familiar ( https://github.com/nextcloud/notifications/issues/1030 )
