### ISSUE TITLE
Missing changelog in Talk 12 Talk Updates room

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#6043]
## Steps to reproduce
1. Have a setup with NC 22.0.0
2. Run `occ app:enable spreed`  which will download the released version.
3. Enter the "Talk updates" room

### Expected behaviour
Update list for Talk 12

### Actual behaviour
The last updates list is from Talk 11

## Talk app

**Talk app version:** 12.0.1

The code is in https://github.com/nextcloud/spreed/blob/master/lib/Chat/Changelog/Manager.php#L114

Suggestions welcome @marcoambrosini

**Comment by PVince81** [comment]
Ideas for entries after reading https://github.com/nextcloud/spreed/blob/master/CHANGELOG.md#1200--2021-07-06

- Join the same conversation and calls from multiple devices
- Send voice messages, share your location or contact details
- Add groups to a conversation where new members get added automatically

not sure if the read marker is worth mentioning and not sure how to word it then.

**Comment by nickvergessen** [comment]
those 3 souodn good

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/6045
