### ISSUE TITLE
Allow whiteboard access to Guests

### ISSUE THREAD

**Issue by EarlyLinks** [nextcloud/spreed#6048]
- Nextcloud-Version: [20.0.6]
- TALK-Version: [10.0.9]
- Whiteboard [0.0.3]

**Is your feature request related to a problem? Please describe
Using TALK to communicate with teams and clients, however, within the TALK platform there is no access to edit whiteboards with guests from within the TALK platform. Therefore, creating a visual or sharing creative information with guests on the same screen is not possible. Additionally, editing of the whiteboard is not possible without a login external to the TALK app as well, which creates a problem when trying to collaborate with guests/clients on projects where providing log in access is not appropriate.

**Describe the solution you'd like**
An editable version of the whiteboard within the TALK app  - to allow joint creative drawing/text with guests or team members

**Describe alternatives you've considered**
Guest cannot access the whiteboard app so creative drawing/text cannot currently be done outside TALK either
Using other platforms like COVIU.com which has a whiteboard feature inbuilt to their telehealth platform

**Comment by nickvergessen** [comment]
Please check the settings of the guests app.
It comes with a default list which does not include the whiteboard
