### ISSUE TITLE
Dropdown in participants list

### ISSUE THREAD

**Issue by xf-** [nextcloud/spreed#605]
## Steps to reproduce
1. Create a call
2. Open menu of last participant

### Expected behaviour
Dropdown opens and i can read all items e.g. remove

### Actual behaviour
Dropdown opens and a scroll bar appears from #app-sidebar .participantWithList overflow auto

## Browser

**Microphone available:** ye

**Camera available:** yes

**Operating system:** Arch

**Browser name:** Chromium

**Browser version:** up2date

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`) 3.0.1

## Nextcloud

** Version: 13 RC2

**Comment by nickvergessen** [comment]
Duplicate #571
