### ISSUE TITLE
Video not visible in call after some time

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#6067]
## Steps to reproduce
1. Be in a call
2. Eventually video stops working. It worked earlier in the call.

### Expected behaviour
Video works.

### Actual behaviour
Video stops displaying. 
<img width="983" alt="Screenshot 2021-07-27 at 11 29 30" src="https://user-images.githubusercontent.com/878997/127131201-4aea103d-be68-498d-aa8d-d0325f73cf60.png">

## Talk app
c.nc.c

## Browser

**Microphone available:** no

**Camera available:** no

**Operating system:** macOS

**Browser name:** Chrome

**Browser version:** 92.0.4515.107

### Browser log

<details>

```
20x [Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
```

</details>

**Comment by fancycode** [comment]
This was broken in Chrome M92:
https://bugs.chromium.org/p/chromium/issues/detail?id=1232649

**Comment by nickvergessen** [comment]
I think the main issue is that we recreate the video elements when toggling between grid view and promoted and when the promoted speaker switches

**Comment by nickvergessen** [comment]
Seems to be solved now
