### ISSUE TITLE
Upgrade 20.0.10 to 21.0.3 wipes all talk conversations

### ISSUE THREAD

**Issue by Janl1** [nextcloud/spreed#6068]
I am managing a few Nextcloud installations and during a scheduled upgrade most of them showed the following behavior.
If I rollback the upgrade process and try it again, I get the exact same results...

### Steps to reproduce
Write talk conversations to different users.
Run Nextcloud Updater and wait until it finishes.
Navigate to Talk and the conversations are gone.

### Expected behaviour
All conversations should survive an upgrade.

### Actual behaviour
All conversations are gone.

If I check the talk comments table in the database the messages written before the update are gone. In some cases I find messages which are not visible in Nextcloud Talk

## Server configuration detail

**Operating system:** Linux 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.4.20

**PHP version:** 

7.4.21
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, json, imagick, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, redis, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 21.0.3 - 21.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes - 20.0.10

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - announcementcenter: 5.0.0
 - apporder: 0.13.0
 - calendar: 2.3.1
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.0
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.3
 - external: 3.8.2
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_fulltextsearch: 21.0.2
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.1.0
 - files_retention: 1.10.1
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - fulltextsearch: 21.0.2
 - fulltextsearch_elasticsearch: 21.0.2
 - groupfolders: 9.0.2
 - impersonate: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.1
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - password_policy: 1.11.0
 - passwords: 2021.7.23
 - photos: 1.3.0
 - polls: 3.0.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quicknotes: 0.7.1
 - quota_warning: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.3.1
 - support: 1.4.0
 - systemtags: 1.11.0
 - tasks: 0.14.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.1.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - files_external
 - nextcloud_announcements
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.3.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "htaccess.RewriteBase": "\/",
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "integrity.check.disabled": "true",
    "default_language": "de_DE",
    "loglevel": "4",
    "log_type": "file",
    "logfile": "\/var\/ncdata\/nextcloud.log",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Europe\/Berlin",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "simpleSignUpLink.shown": false,
    "default_phone_region": "DE",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36

**Operating system:** Windows 10 Pro

## Logs

<details><summary>Web server error log</summary>

```
--
```
</details>

<details><summary>Nextcloud log</summary>

```
No errors visible
```
</details>

<details><summary>Browser log</summary>

--
</details>

**Comment by nickvergessen** [comment]
See #5518
