### ISSUE TITLE
Safari sends html tags

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6070]
## Steps to reproduce
1. Press shift+enter repeatedly in the new message form
2. Hit send message

### Expected behaviour
Nothing happens 

### Actual behaviour
A bunch of div opening and closing html tags are sent

https://user-images.githubusercontent.com/26852655/127481833-b8b5331e-e77e-481c-a8ec-64a0a3416f71.mov

**Comment by PVince81** [comment]
duplicate of https://github.com/nextcloud/spreed/issues/4891 ?

**Comment by marcoambrosini** [comment]
yep, dupe
