### ISSUE TITLE
Nextcloud Talk notifications not working

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/spreed#6075]
## Steps to reproduce
1. user 1 sends Talk chat message to user2
2. user2 should get a notifications of new message

### Expected behaviour
Notification on recipient's device (PC, Android or iPhone)

### Actual behaviour
No notification appears on either Android devices, Apple devices or any browser.

## Talk app
version: 12.0.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Browser
Chrome 

**Microphone available:** yes/no
n/a
**Camera available:** yes/no
n/a
**Operating system:** Windows/Ubuntu/...
Android, IOs, Windows

**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 50.1/55/...
Chrome Version 92.0.4515.107 and Firefox, Explorer (it doesnt work on any browser)

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Linux Debian with Kernel 3.10.105

**Web server:** Apache/Nginx
Apache 2.4

**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB 10

**PHP version:** 7.2/7.3/7.4
7.4

**Nextcloud Version:** (see admin page)
22.0.0

**List of activated apps:**
Talk 12.0.1
<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here

</details>

**Comment by e-caste** [comment]
I have opened [the same issue](https://github.com/nextcloud/talk-ios/issues/595) thinking it was specific to the Talk iOS app, but it may be a Talk server bug.  
It seems other people are experiencing it as well, it would be so much better if they were as reliable as in v10.

**Comment by nickvergessen** [comment]
Let's discuss it in #6096
