### ISSUE TITLE
Videos are not selectable anymore if in grid-view if a screen-share is active

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6077]
## Steps to reproduce
1. Join a call where someone is sharing their screen
2. Switch to grid view
3. Try to select the video of another participant

### Expected behaviour
The video of the participant is selected and the view is switched to speaker

### Actual behaviour
Nothing happens

**Comment by nickvergessen** [comment]
Debugging tipp:
Works after toggling to speaker view and back to grid

**Comment by nickvergessen** [comment]
You duplicated your own issue 👯 
#5069
