### ISSUE TITLE
Increase Call Experience Limit

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/spreed#6078]
Hi in https://nextcloud-talk.readthedocs.io/en/latest/call-experience/ we found
<html><body>
<h4 id="number-of-video-streams">Number of video streams<a class="headerlink" href="https://nextcloud-talk.readthedocs.io/en/latest/call-experience/#number-of-video-streams" title="Permanent link"></a></h4>
<div class="wy-table-responsive">

Streams | Quality
-- | --
< 4 | High
4-7 | Medium
8-10 | Low
11-14 | Very low
 14 | Thumbnail

</div>
</body>
</html>

<html><body>
<h4 id="number-of-audio-streams">Number of audio streams<a class="headerlink" href="https://nextcloud-talk.readthedocs.io/en/latest/call-experience/#number-of-audio-streams" title="Permanent link"></a></h4>
<div class="wy-table-responsive">

Streams | Quality
-- | --
< 10 | High
10-19 | Medium
20-29 | Low
30-39 | Very low
40 | Thumbnail

</div>
</body>
</html>

**Request**
Is there the possibility of modifying the limits?
In code or in a config

Best regards

**Comment by nickvergessen** [comment]
We know the values are rather "german" internet orientated, but we don't plan to allow modifying them.
