### ISSUE TITLE
Feature Request: QR Code Login for Talk App (Android and iOS)

### ISSUE THREAD

**Issue by florom** [nextcloud/spreed#6083]
Hi Devs,

Great Work!

Problem:
Setting Up Nextcloud Talk App android/Iphone  is not fast enough. 

Solution:
Integrate QR Code Scanner in Login Screen so that the Settings Security Create new app password → QR Code can read it
and logs in automatically.

Alternative:
Well, I could not think of something as fast as QR Code Scan Setup (Like in the Nextcloud Files? App android/Iphone)

![image](https://user-images.githubusercontent.com/32240626/128354183-b18704f8-6b16-4562-9dc0-c72e56578830.png)

Why:
https://help.nextcloud.com/t/feature-request-qr-code-login-for-talk-app-android-and-ios/121386

Thanks you for considering

**Comment by stefan-niedermann** [comment]
For the Tallk Android there's already an issue here: https://github.com/nextcloud/talk-android/issues/545

**Comment by florom** [comment]
@stefan-niedermann 

I was linked to this project from help.nextcloud.com.

I thought this is the right one for both (Android and iPhone).

**Comment by stefan-niedermann** [comment]
Link for issue in the iOS app: https://github.com/nextcloud/talk-ios/issues/305

@florom yeah, i read the thread :) I will post the two links there, too. Closing this issue as both apps already have issues in their repositories and this can't be implemented in this repository 🙂
