### ISSUE TITLE
"An error occurred while performing the search" when trying to add user to conversation after Nextcloud 22.1.0 update

### ISSUE THREAD

**Issue by meichthys** [nextcloud/spreed#6085]
## Steps to reproduce
1. Update nextcloud to latest version: 22.1.0
2. Try adding a user to a conversation
3. See error. No users will be populated when searching for user to add:
![image](https://user-images.githubusercontent.com/10717998/128519556-36cbe641-44c0-4e16-bc68-aacfab78f8ed.png)

The issue appears to be Talk related since I am able to share calendars/task lists with other users.

### Expected behaviour
Users should be displayed that match my search:
![image](https://user-images.githubusercontent.com/10717998/128519710-0476ed2d-540e-487d-aa8d-20d65634a33d.png)

### Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/10717998/128519739-abb91154-f389-49d0-b398-d3faa22c4f97.png)

## Talk app

**Talk app version:** 12.0.1

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** no 

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox Latest (also tried on other browsers)

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud Version:** 22.1.0

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

![image](https://user-images.githubusercontent.com/10717998/128520161-e4ce3aca-ed6b-44c4-be66-92385f3625b5.png)

</details>

**Comment by meichthys** [comment]
I'm not sure if this is an issue with Talk or Circles, but disabling the Circles app resolves the issue.
https://help.nextcloud.com/t/nextcloud-talk-es-ist-ein-fehler-wahrend-der-suche-aufgetreten/121423

**Comment by nickvergessen** [comment]
As there are lot of duplicates here is a summary:
* There is a bug in Circles which breaks an API provided by the Nextcloud Server: https://github.com/nextcloud/circles/issues/777
* The bug in Circles was fixed
* Until a release of Circles was published, the workaround is to disable Circles
