### ISSUE TITLE
Search for conversation doesnt work inside talk.

### ISSUE THREAD

**Issue by IsaiChristian** [nextcloud/spreed#6092]
### Steps to reproduce
1. Go to talk, 
2. Click on search  inside chat pannels
3. type something

### Expected behaviour
To have a result for my query

### Actual behaviour
frontend: I recieve "An error occurred while performing the search" notification 

## Server configuration detail

**Operating system:** Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.5.11

**PHP version:** 

7.4.22
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 22.1.0 - 22.1.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - breezedark: 22.0.1
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.1
 - circles: 22.1.0
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - encryption: 2.9.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - nextcloud_announcements: 1.11.0
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - recommendations: 1.1.0
 - richdocuments: 4.2.1
 - richdocumentscode: 6.4.1004
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 12.0.1
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - tasks: 0.14.1
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.1
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "colaboracion.pozolcode.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.1.0.1",
    "overwrite.cli.url": "http:\/\/colaboracion.pozolcode.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_sendmailmode": "smtp",
    "mail_smtpauth": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
GET /ocs/v2.php/core/autocomplete/get?search=sa&itemType=call&itemId=new&shareTypes[]=0&shareTypes[]=1&shareTypes[]=7
from 187.171.30.169 by admin at 2021-08-07T02:52:57+00:00
```
</details>

<details><summary>Nextcloud log</summary>

```
GET /ocs/v2.php/core/autocomplete/get?search=sa&itemType=call&itemId=new&shareTypes[]=0&shareTypes[]=1&shareTypes[]=7
from 187.171.30.169 by admin at 2021-08-07T02:52:57+00:00
```
</details>

<details><summary>Browser log</summary>

talk-main.js?v=1ded32c2-0:1 GET https://**********/ocs/v2.php/core/autocomplete/get?search=sa&itemType=call&itemId=new&shareTypes[]=0&shareTypes[]=1&shareTypes[]=7 404
</details>

**Comment by nickvergessen** [comment]
See #6085

**Comment by IsaiChristian** [comment]
@nickvergessen Thanks that fixed the issue.
