### ISSUE TITLE
iOS/macOS - Audio/video channel is deactivated on the server side after muting

### ISSUE THREAD

**Issue by SDuesterhaupt** [nextcloud/spreed#6094]
## Steps to reproduce
1. Participants join a call with activated audio and video
2. Muting the microphone and/or webcam
3. Unmuting the microphone and/or webcam > disconnected by Janus

The Signaling/Janus configuration is a setup according to the default exceptionally domains, API keys and secrets.

### Expected behaviour
If one participant speaks in the conference then the others usually mute their microphones/webcams. If another partner wants to speak then the microphone/webcam is unmuted. All participants can listen this conversation.

### Actual behaviour
Participants with Apple devices mute their microphones and/or webcams. If Apple participants reactivate their microphone or camera then the other members cannot hear or see them. The audio has gone, the webcam has gone (screen is dark black), too.

The Janus server log informs that this audio/video channel has been freed.

The participant has to logout and join the conversation again to renew the Janus data handles.

Clients using Linux/Android with Firefox/Chromium don't seem to have this issue.

## Talk app

**Talk app version:** 12.0.1

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** iOS 14.06 and macOS Big Sur 11.4

**Browser name:** Safari/Chrome

**Browser version:** aligned to the OS system

### Browser log

<details>

```
na
```

</details>

## Server configuration

**Operating system**: Ubuntu 18.04.x LTS

**Web server:** Apache/2.4.29 (Ubuntu)

**Database:** MySQL 5.7.35

**PHP version:** 7.4

**Nextcloud Version:** 22.0.0

**List of activated apps:**

<details>

```
  - accessibility: 1.7.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - calendar: 2.3.1
  - circles: 22.0.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.0
  - external: 3.9.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.0-beta1
  - integration_suitecrm: 1.0.1
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.2
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.1
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 12.0.1
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - talk_matterbridge: 1.22.4
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
```
</details>

**Nextcloud configuration:**

<details>

```
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.octoteq.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.octoteq.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "default_phone_region": "EN",
        "app_install_overwrite": [
            "bruteforcesettings",
            "whiteboard"
        ],
        "updater.release.channel": "stable"
    }
```
</details>

### Server log (janus log)
<details>

```
$ sudo journalctl -u janus --since "2021-07-30 14:30"

Jul 30 14:31:51 cloud.iitgr.com janus[1890]: [WARN] [4017759978343726] Didn't receive audio for more than 1 seconds...
Jul 30 14:32:08 cloud.iitgr.com janus[1890]: [WARN] [4017759978343726] Didn't receive audio for more than 1 seconds...
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: Detaching handle from JANUS VideoRoom plugin; 0x7f07bc007760 0x7f07bc004b90 0x7f07bc007760 0x7f07bc0078b0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [janus.plugin.videoroom-0x7f07bc004b90] No WebRTC media anymore; 0x7f07bc007760 0x7f07bc0078b0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [1450851420946566] WebRTC resources freed; 0x7f07bc007760 0x7f07bc0060d0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [1450851420946566] Handle and related resources freed; 0x7f07bc007760 0x7f07bc0060d0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: Detaching handle from JANUS VideoRoom plugin; 0x7f07bc005d60 0x7f0768003890 0x7f07bc005d60 0x7f07bc003e50
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [janus.plugin.videoroom-0x7f0768003890] No WebRTC media anymore; 0x7f07bc005d60 0x7f07bc003e50
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [4017759978343726] WebRTC resources freed; 0x7f07bc005d60 0x7f07bc0060d0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [janus.plugin.videoroom-0x7f0768002fa0] No WebRTC media anymore; 0x7f07bc005080 0x7f07bc001b00
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [2020059592541375] WebRTC resources freed; 0x7f07bc005080 0x7f07bc0060d0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: Detaching handle from JANUS VideoRoom plugin; 0x7f07bc005080 0x7f0768002fa0 0x7f07bc005080 0x7f07bc001b00
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [4017759978343726] Handle and related resources freed; 0x7f07bc005d60 0x7f07bc0060d0
Jul 30 14:43:19 cloud.iitgr.com janus[1890]: [2020059592541375] Handle and related resources freed; 0x7f07bc005080 0x7f07bc0060d0

```
</details>

**Comment by nickvergessen** [comment]
@fancycode ever heard of something like that?

**Comment by SystemKeeper** [comment]
I'm seeing the same thing without HPB, so might be a more general issue with safari.
I was also able to reproduce the problem with the camera (Tested Safari -> Talk iOS).

Workaround for microphone is to open talk device settings, deselect the microphone and then select it again, works afterwards. On HPB I noticed that the "You have poor internet connectivity" popup is shown when audio is not working after unmuting and the console reports lost packages.

**Comment by SystemKeeper** [comment]
I have done some tests regarding this. This was done on Talk 16.0.3 and Safari 16.3 on MacOS 13.2, tested was audio (mute/unmute) in connection with HPB. 

When we hit this issue, the following can be observed:
```javascript
var simplewebrtc = OCA.Talk.SimpleWebRTC
simplewebrtc.webrtc._audioTrackEnabler._outputTracks["default"]
```
gives us the correct track with `muted = false`:

![image](https://user-images.githubusercontent.com/1580193/235257190-05b39a8d-2ae9-4f6c-b634-6e29ca4f456a.png)

On the other hand when looking at the sender:
```javascript
simplewebrtc.getPeers()[0].pc.getSenders()[0]
```
`track` is null and `trackDisabled`/`kind` are missing:
![image](https://user-images.githubusercontent.com/1580193/235257372-95bd0c35-108f-4739-9340-35fb0069454a.png)

Manually replacing the track in the sender with:
```javascript
simplewebrtc.getPeers()[0].pc.getSenders()[0].replaceTrack(simplewebrtc.webrtc._audioTrackEnabler._outputTracks["default"])
```
works and audio is correctly transmitted again.
After this is done, muting/unmuting works every time and also the track is now set as `trackDisabled` when muted:
![image](https://user-images.githubusercontent.com/1580193/235258074-837dd276-a204-4546-9eab-c4b269b0af7c.png)


Besides this I noticed that we try to detect the kind of stream from the transceivers if everything else fails, but the mid's for the sender do not match (same mid's in Chrome btw):
https://github.com/nextcloud/spreed/blob/e6e194d523874a31431197431e7e1dcce17fbcc4/src/utils/webrtc/simplewebrtc/peer.js#L432-L435
![image](https://user-images.githubusercontent.com/1580193/235269866-4b71b3de-71e1-4a70-a6d3-f33d54047eae.png)
(I don't think it's relevant here, but might still be worth checking)

Only for the receive transceiver mid is set to `audio`/`video`:
![image](https://user-images.githubusercontent.com/1580193/235270101-13125bce-4b05-4893-a04a-c07d91156948.png)

I tried to add some debug logging to the `Peer.prototype._replaceTrack` method, but depending on where I put the logging I could not reproduce the issue anymore (which still might be a coincidence...), which leads to the question if this is some kind of race condition.

**Comment by prismopensource** [comment]
Since this bug is now over 2 years old we were wondering whether there is already a fix on the horizon. Calls with lots of Safari participants are unworkable to the point these users don't want to use Talk anymore. Anything we can do to test or help with possible bugfixes?

**Comment by nickvergessen** [comment]
Had to revert the PR as it caused other issues
