### ISSUE TITLE
recognice people invited by mail when they join the conversation

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#6098]
I really like the feature that I can add a random email address in the participants list and the person will get a invitation by mail:

![image](https://user-images.githubusercontent.com/1589737/128771321-f865c114-1b16-45e6-9bb5-1d8bea45949e.png)

But what is really disturbing is that when the person joins they show up as a guest and they are not recognized as the person invited by mail:

![image](https://user-images.githubusercontent.com/1589737/128771547-6cc1ea12-b702-440f-a9ee-087cc796c8c6.png)

Idea, why not add the email address as a parameter to the link? If we don't want to have the email address visible, we could hash or encrypt it. This way we could match the user and show them with their email address as user name instead of an additional guest.

**Comment by nickvergessen** [comment]
Already scheduled via https://github.com/nextcloud/spreed/issues/1423
