### ISSUE TITLE
App installation: Cannot install Talk

### ISSUE THREAD

**Issue by Dormouse759** [nextcloud/spreed#6099]
I have set up a new install on my VPS. (Centos 7, mariaDB)

When I try to install the Talk app, i receive this error:
```
The column 'sip_enabled' on table 'oc_talk_rooms' already exists.
```

When I drop the table oc_talk_rooms, the error changes to this:
```
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. 
```

I have not figured out a solution for this problem. I have found a similar one, but this workaround didn't help:
```
# mysql -u root -p
MariaDB [(none)]> use nextcloud;
MariaDB [nextcloud]> set global innodb_large_prefix=on;
MariaDB [nextcloud]> set global innodb_file_format=Barracuda;
$ php occ maintenance:repair
```

**Comment by nickvergessen** [comment]
For index length see https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html

Manually deleting a table/column will always cause problems.

Please consult the forum for recovery help

**Comment by Dormouse759** [comment]
@nickvergessen, can you please reopen the issue?
It has not been resolved.

**Comment by SoongVilda** [comment]
Hello, i received same error, deleting something is wonky solutions.

Please, can you fix that?

**Comment by Dormouse759** [comment]
For anyone with the same issue, take a look at an older version of the documentation, there are extra 2 lines of config, you need on older versions of the software. Setting the equivalent variables on the mysql command line does not help.

[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1

I.e. version 16 docs.
https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by nickvergessen** [comment]
> Converting the database gives me a very similar error:

Then you didn't do everything from the manual or run an unsupported database


> can you please reopen the issue?
It has not been resolved.

No as this is not a bug in talk. You screwed up something because of manual database manipulations or something, so when it was a test setup please delete it and redo it, and otherwise get help in the forum

**Comment by Dormouse759** [comment]
I mean in no way to be rude.

Let me just explain my situation:

I don't know PHP, there is old software on CentOS 7. I need to use CentOS 7, beacuse Red Hat dumped CentOS and CentOS 8 is going to die sooner than CentOS 7.

So I'm left here with old software, totally confused trying to make this run. Then this (totally preventible) issue takes me half a day just because someone decided not to set those globs automatically after the server start.

I'm sorry if I sound pissed off, but this shouldn't have been so difficult to make it work.
