### ISSUE TITLE
Chat on black background after disconnect from a call

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#610]
* join a call
* the promoted speaker has disabled video
* chat a bit with the members
* leave the call
* chat is moved to the middle
* expected: background color gets white again (like before joining)
* actual: background color keeps black (like what the promoted speaker had) making the text unreadable

<img width="1312" alt="bildschirmfoto 2018-01-23 um 15 56 29" src="https://user-images.githubusercontent.com/245432/35284109-376f7f7c-005a-11e8-8063-2c2b6c4e126d.png">

cc @jancborchardt @skjnldsv  @nextcloud/talk

**Comment by skjnldsv** [comment]
I can't reproduce :/

**Comment by MorrisJobke** [comment]
I also had it when I lost one time the connection :/

**Comment by skjnldsv** [comment]
Nope, tried with force disconnecting, closing browser, three people... Can't reproduce! Anyone else? :)
@nextcloud/talk

**Comment by MorrisJobke** [comment]
Let’s close and I will report once it happens again

**Comment by nickvergessen** [comment]
I think this could be due to dangling sessions, in which case https://github.com/nextcloud/spreed/pull/698 should help

**Comment by MorrisJobke** [comment]
Happened again just now - @nickvergessen It's not yet released, right?

**Comment by nickvergessen** [comment]
no, we just merged it today :D
