### ISSUE TITLE
Own video controls invisible when attending presentation or screenshare with white background

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#6104]
**Is your feature request related to a problem? Please describe.**
When you are in a call where someone is presenting or screensharing, and the screenshare/presentation has a white background (and the participants video bar is collapsed), the personal video controls (audio/video/screenshare etc) are invisible.

Actually, there are 3 different behaviors:
- audio/video are invisible even on hover
- screenshare and 3-dot-menu are visible only on hover of the action
- expand/collapse is properly visible as long as there’s activity/mouse move

![talk controls completely invisible on white background screenshare](https://user-images.githubusercontent.com/925062/129050007-defdb19e-14a9-4e9b-9759-9990132e07ea.png)

**Describe the solution you'd like**
The actions are all properly visible, for example by using the same design & logic with circular background as the expand/collapse action.

This is sort of related to https://github.com/nextcloud/spreed/issues/5877 @marcoambrosini

**Comment by jospoortvliet** [comment]
The grey color of the expand/collapse can also become invisible, right? like, on black? Or on grey? Maybe a shadow is needed? Just thinking...
And, for fun, another screenshot of the issue 🗡️ 
![Screenshot_20210812_173232](https://user-images.githubusercontent.com/551757/129225196-801de128-33b7-4c5b-b512-584b019c963e.png)

**Comment by nickvergessen** [comment]
Fixed by #6460
