### ISSUE TITLE
Use only remote.php/dav instead of remote.php/webdav

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/spreed#6108]
- [ ] Android Talk @mahibi / @timkrueger https://github.com/nextcloud/talk-android/issues/1478
- [x] ios Talk @Ivansss 

As title says: With NC23 only use remote.php/dav.

@nextcloud/server-triage can we log this for NC22 so that we see which clients are using this?
This is good for all other 3rd party clients.

see sister issue for files https://github.com/nextcloud/server/issues/25867

**Comment by nickvergessen** [comment]
iOS solved, Android handled in https://github.com/nextcloud/talk-android/issues/1478

Closing meta ticket
