### ISSUE TITLE
Spreed/Talk can't activate on NC 20.0.12, 21 nor 22, working on 20.0.7

### ISSUE THREAD

**Issue by Baccanno** [nextcloud/spreed#6124]
### Steps to reproduce
1. Upgrade to NC 21.0.4 or 22.0.1
2. Download Latest Spreed Release ( https://github.com/nextcloud-releases/spreed/releases/download/v11.3.1/spreed-11.3.1.tar.gz / https://github.com/nextcloud-releases/spreed/releases/download/v12.0.1/spreed-12.0.1.tar.gz ) and add it to the `apps` folder
3. Activate through ui or cmd `./occ app:enable spreed`

### Expected behaviour
App should activate

### Actual behaviour
'An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes'

**InnoDb settings can't be changed in this environment (Baracuda/Large)**

I tried manually enabling the app in the DB. It did activate but then it was broken (could not find conversations or other users). 

### Server configuration

**Operating system:**
Linux

**Web server:**
OVH Mutualised (Nginx/Apache I guess)

**Database:**
Mysql 5.6 (InnoDB from oc_properties)

**PHP version:** 
7.3

**Nextcloud version:** (see Nextcloud admin page)

**Comment by Baccanno** [comment]
Also did deactivate 4bytes handling: https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740/12

Definitely same error as  :  https://github.com/nextcloud/server/issues/17025

**Comment by nickvergessen** [comment]
Closing as this is not a Talk issue (but you linked a duplicate in server so that's fine)

@szaimen it basically would happen on any app install as long as db configuration and nextclouds mysql 4byte configuration diverge.

**Comment by Baccanno** [comment]
Thanks for your concern,
Yeah that is why I thought of adding it to the server issues not spreed. 
What is the mean of "diverge"? All solutions seems to ask for tempering with innoDB configuration, that's and environment modification. How comes it did not occur before ? Should we do a fresh install ?

**Comment by nickvergessen** [comment]
Mysql 5.6 is not supported anymore in 21 and 22 (due to underlying libraries), so that's why it didn't work there anymore.

And the other problem is that you mostly followed a mysql 4byte manual for the wrong version as well. For 5.6 there are more changes needed.

See e.g. https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html
