### ISSUE TITLE
Delete messages up to 6 hours, should be X hours

### ISSUE THREAD

**Issue by Terrox** [nextcloud/spreed#6132]
**Is your feature request related to a problem? Please describe.**
11.1
    delete-messages - Allows to delete chat messages up to 6 hours for your own messages or when being a moderator. On deleting the message text will be replaced and a follow up system message will make sure clients and users update it in their cache and storage.

**Describe the solution you'd like**
Delete Messages without time limit, or let me set an unlimited time limit in Chat Settings.

**Describe alternatives you've considered**
A time limit makes the capability useless for me.

**Additional context**
I want to delete messages to clean up the chat records for various reasons. It is not relevant if people have seen or saved the message, forums have no problem with this concept of data being seen and they have Delete buttons.

If you're wondering what I am talking about in regards to people having seen the message, there are people in opposition to the idea of deleting chat messages for reasons usually related to "viewers can save their own chat logs so there's no point deleting a message". Which Is completely irrelevant to the reasons why I'd want to delete a chat message.

**Comment by nickvergessen** [comment]
We don't plan to add a config option for the delete duration (similar to all other chat systems out there)
