### ISSUE TITLE
Talk on nextcloud 22.1

### ISSUE THREAD

**Issue by steve12l** [nextcloud/spreed#6138]
Hi, we are 2 (admins) on nextcloud 22.1, and there is a problem with Talk. 
Cannot create another discussion because it cannot find the second person, even with a search when with version 21 everything worked perfectly. 
Do others have the same concerns?
If you need more information, don't hesitate.
And we're the only two people chatting on our nextcloud

Steve12L

**Comment by nickvergessen** [comment]
Please include more details e.g. nextcloud.log file. Best fill out the full issue template.

If you have the circles app installed, try disabling it. There is a bug preventing user name completion in several dialogs.
If that is not it, we can't help you until you provide the information requested by the issue template

**Comment by steve12l** [comment]
It's OK by disabling circles, thanks a lot! 👍

**Comment by shu0406** [comment]
Will there come an update to fix this problem soon? We need both, talk and circles...

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/6085#issuecomment-904655765
