### ISSUE TITLE
[GSoC idea] Chat system messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#614]
It should be possible for the app to show system messages in the chat.

Samples:
* Person A started a call
* Person B joined the call
* Person B left the call
* Person C was added to the room
* Person A made this room public

Those messages should be stored the same way the chat messages are stored but should display slightly different (less noisy).

**Comment by GLLM** [comment]
Hi all,
here are a few suggestion I made in a now closed issue !
It goes along with this issue, and adds suggestion for duration of calls, as well as time of received/made/missed calls.

1.
A contact calls me, but I could not take the call, or even missed it.
It would be great to see, in the Chat texts,
_Missed call from contact_name at hh:mm on dd/mm/yyy_

2. 
I call a contact, we talk and hang.
I would be great to see, in the Chat texts,
_You called contact_name for duration, at hh:mm on dd/mm/yyy_

3.
A contact calls me, we talk and hang.
I would be great to see, in the Chat texts,
_Contact-name called you for duration, at hh:mm on dd/mm/yyy_

**Comment by jancborchardt** [comment]
@GLLM yes, good enhancements too! :) We don’t need the "at hh:mm on dd/mm/yyyy" part, because time is already in an element separate from the text, and the date is in a separate divider too. :)
