### ISSUE TITLE
Hide Stale Conversations

### ISSUE THREAD

**Issue by kimcdow** [nextcloud/spreed#6140]
I carry on a number of text conversations in Talk,  much like most of what I do in Microsoft Teams,
I would like to have the option of hiding conversations instead of deleting them.
This would allow me to search hidden conversations but would not display them in the left sidebar.
It would be nice if this hide conversation feature also included autohide after X number of days
Please reach out if you have any questions regarding this request

**Comment by jakobroehrl** [comment]
I would like to archive some of my conversations, too. (like I can do it on Signal or Whatsapp)
But I suggest to do it manually not automatically.
