### ISSUE TITLE
Can't search User

### ISSUE THREAD

**Issue by Tealk** [nextcloud/spreed#6144]
### Steps to reproduce
Open a new conversation
try to add user

### Expected behaviour
This message is displayed: An error occurred while performing the search

### Actual behaviour
See a list of useres

## Server configuration detail

**Operating system:** Linux 5.11.22-1-pve #1 SMP PVE 5.11.22-2 (Fri, 02 Jul 2021 16:22:45 +0200) x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.5.11

**PHP version:** 

8.0.9
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 22.1.0 - 22.1.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** zip pack

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - admin_audit: 1.11.0
 - apporder: 0.13.0
 - bookmarks: 4.4.1
 - breezedark: 22.0.1
 - calendar: 2.3.2
 - circles: 22.1.0
 - cloud_federation_api: 1.4.0
 - collectives: 0.12.22
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.0
 - event_update_notification: 1.3.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_downloadactivity: 1.11.1
 - files_linkeditor: 1.1.6
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_texteditor: 2.14.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - forms: 2.3.0
 - groupfolders: 9.0.2
 - guests: 2.0.1
 - integration_mastodon: 1.0.1
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.3
 - maps: 0.1.9
 - metadata: 0.14.0
 - nextcloud_announcements: 1.11.0
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - onlyoffice: 7.1.2
 - password_policy: 1.12.0
 - passwords: 2021.7.23
 - photos: 1.4.0
 - polls: 3.0.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.11.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - sociallogin: 4.8.3
 - spreed: 12.0.1
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - tasks: 0.14.1
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_admin: 3.1.0
 - twofactor_backupcodes: 1.10.1
 - twofactor_nextcloud_notification: 3.2.1
 - twofactor_totp: 6.1.0
 - twofactor_u2f: 6.2.0
 - updatenotification: 1.11.0
 - user_retention: 1.5.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - files_external
 - recommendations
 - support
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "anzah.cloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/anzah.cloud",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "22.1.0.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "default_locale": "de",
    "default_phone_region": "DE",
    "allow_user_to_change_display_name": true,
    "knowledgebaseenabled": true,
    "theme": "",
    "defaultapp": "apporder",
    "skeletondirectory": "\/var\/customers\/webs\/Anzah\/anzah.cloud\/core\/skeleton",
    "trashbin_retention_obligation": "120, auto",
    "versions_retention_obligation": "120, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.release.channel": "stable",
    "check_for_working_webdav": true,
    "loglevel": 3,
    "logdateformat": "d.m.Y H:i:s",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 10485760,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "data-fingerprint": "01b9630d063ba580c331de332a0ab360",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 10,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "twofactor_enforced": false,
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "apporder",
        "circles",
        "groupfolders",
        "whiteboard",
        "issuetemplate",
        "tasks",
        "bookmarks",
        "appointments",
        "quota_warning",
        "jitsi"
    ],
    "migrate_guest_user_data": true,
    "remove_guest_account_on_conversion": true,
    "keep_users_without_login": "no"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Operating system:** debian bullseye

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"csXGN6PtBebLkyTgHcl7","level":3,"time":"2021-08-24T13:40:15+02:00","remoteAddr":"212.211.191.216","user":"Tealk","app":"no app in context","method":"GET","url":"/ocs/v2.php/core/autocomplete/get?search=sd&itemType=call&itemId=h8i328fs&shareTypes[]=0&shareTypes[]=1&shareTypes[]=7&shareTypes[]=4","message":"in_array(): Argument #2 ($haystack) must be of type array, null given","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"in_array(): Argument #2 ($haystack) must be of type array, null given","Code":0,"Trace":[{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/customers/webs/Anzah/anzah.cloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/ocs/v2.php","line":23,"args":["/var/customers/webs/Anzah/anzah.cloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"in_array(): Argument #2 ($haystack) must be of type array, null given","Code":0,"Trace":[{"file":"/var/customers/webs/Anzah/anzah.cloud/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","line":101,"function":"in_array"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/Collaboration/Collaborators/Search.php","line":72,"function":"search","class":"OCA\\Circles\\Collaboration\\v2\\CollaboratorSearchPlugin","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/core/Controller/AutoCompleteController.php","line":77,"function":"search","class":"OC\\Collaboration\\Collaborators\\Search","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"get","class":"OC\\Core\\Controller\\AutoCompleteController","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/customers/webs/Anzah/anzah.cloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/customers/webs/Anzah/anzah.cloud/ocs/v2.php","line":23,"args":["/var/customers/webs/Anzah/anzah.cloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/customers/webs/Anzah/anzah.cloud/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","Line":101},"CustomMessage":"--"},"id":"6124da9fe7ad8"}
```
</details>

<details><summary>Browser log</summary>

jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
XHRGEThttps://anzah.cloud/ocs/v2.php/core/autocomplete/get?search=dfsdfg&itemType=call&itemId=h8i328fs&shareTypes[]=0&shareTypes[]=1&shareTypes[]=7&shareTypes[]=4
[HTTP/2 404 Not Found 116ms]

Error: Request failed with status code 404
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    onreadystatechange https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    promise callback*30321/l.prototype.request https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    t https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    exports https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    searchPossibleConversations https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    request https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    fetchSearchResults https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    debounceFetchSearchResults https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    l https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    setTimeout handler*l https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    setTimeout handler*u https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    handleInput https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    n https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    $emit https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    localValue https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    run https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    pn https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    ie https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Jt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    promise callback*Vt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    ie https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    update https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    update https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    notify https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    set https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    set https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    input https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    n https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    _wrapper https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
talk-main.js:1:2838705
    fetchSearchResults https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    debounceFetchSearchResults https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    l https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    (Async: setTimeout handler)
    l https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    (Async: setTimeout handler)
    u https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    handleInput https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    n https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    $emit https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    localValue https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    run https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    pn https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    ie https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Jt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    (Async: promise callback)
    Vt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    ie https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    update https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    update https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    notify https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    set https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    set https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    input https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    Gt https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    n https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
    _wrapper https://anzah.cloud/apps/spreed/js/talk-main.js?v=ef8ac11a-29:1
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 136 globals.js:62:15

</details>

**Comment by medbf321** [comment]
Disable 'Circles' from Applications.

**Comment by Tealk** [comment]
Ok with deactivated Circles app it works, but I use the Circles very often

**Comment by Tealk** [comment]
why was this closed, there seems to be a bug in connection with Circles?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/6085#issuecomment-904655765
