### ISSUE TITLE
A large user base prevents the app from loading properly 

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/spreed#617]
The page hangs while the user list is being built. After a while Firefox reports that the browser is being slowed down and offers to stop loading. If you wait long enough the page eventually loads. Starting a new user search causes the same problem.

We have around 2000 users in the database

## Steps to reproduce
1. Start the app

### Expected behaviour
List of Users should load in left-hand column 
### Actual behaviour
Page hangs 

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 58

## Spreed app

**Spreed app version:** 2.0.2

**Custom TURN server configured:** yes Coturn

**Custom STUN server configured:** yes Coturn

## Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** MySQL
**PHP version:** 7.0

**Nextcloud Version:** 12.0.5

**Comment by brtptrs** [comment]
![z_screenshot_20180126_003](https://user-images.githubusercontent.com/8102905/35472372-43d5dca4-036e-11e8-8df0-46728a1f5dbd.png)

**Comment by MorrisJobke** [comment]
@nextcloud/talk Could you have a look into this. Maybe someone from @nextcloud/ldap Could also help here.

To get a large user list try the LDAP setup that I described here: https://github.com/nextcloud/server/wiki/How-to-test-LDAP%3F

**Comment by danxuliu** [comment]
@MorrisJobke I guess that the problem comes from adding 200 HTML elements ([the limit set for `select2` results](https://github.com/nextcloud/spreed/blob/3aed53a88866207bf6cffd68bda6cb296519f51a/js/app.js#L52)) all at once. `select2` uses an asynchronous call, so the time spent by the server getting the list of users should not cause any slowdown on the client.

Could you check if changing the limit set for `select2` results from 200 to, for example, 10 solves the issue (and of course beware of caches ;-) )?

**Comment by brtptrs** [comment]
@danxuliu Thanks for the quick response. I tried setting limit to 10 as you suggested. It does not affect the number of items that gets loaded. I guess it has to do with your hint about caches. Which caches are we talking about?

**Comment by brtptrs** [comment]
![z_screenshot_20180131_002](https://user-images.githubusercontent.com/8102905/35611222-aff7fa40-0664-11e8-9473-86e84534a6f4.png)

**Comment by brtptrs** [comment]
![z_screenshot_20180131_003](https://user-images.githubusercontent.com/8102905/35611982-5a945582-0667-11e8-991d-2d0e7f3ea1ee.png)

**Comment by nickvergessen** [comment]
I will have a look, thanks for the hint

**Comment by blizzz** [comment]
Ain't it here the same as with sharing, comments autocomplete, user management etc: just don't load all users? Do a search on demand with a limited number of results.

**Comment by blizzz** [comment]
@nickvergessen  Apparently it uses file_sharing's sharee endpoint. And the search is triggered anyway when typing something in it. We have now official `/autocomplete/get` endpoint in core (which also allows custom server side sorting). Should be easy to exchange the endpoint and add a limit, as minimum impact solution.

**Comment by danxuliu** [comment]
@blizzz The limit is already there, it is the `perPage` parameter (the one I linked above when I said _[the limit set for select2 results](https://github.com/nextcloud/spreed/blob/3aed53a88866207bf6cffd68bda6cb296519f51a/js/app.js#L52)_). I have checked it and the limit works fine with local users (only as many users as specified in `perPage` are included in the response from the server). Could it be a bug with the Sharees endpoint and LDAP?

**Comment by nickvergessen** [comment]
I tested it too and works fine.
I'd say lets change the limit to 10 for now.

But yeah maybe there is another underlying problem with LDAP.

I will try to set up the thing Morris posted to check it out.

**Comment by nickvergessen** [comment]
> We have now official /autocomplete/get endpoint in core (which also allows custom server side sorting).

Nice, but it's not OCS, so we can't use it or get different results in the apps compared to the web.

**Comment by nickvergessen** [comment]
I think the problem could be related to "can only share in groups" and a user being in many (all) groups.
https://github.com/nextcloud/server/blob/870fe20acc90cbfb89bf710f441d62f8bcf92f9d/lib/private/Collaboration/Collaborators/UserPlugin.php#L68-L77

Codewise it looks like that might result in up to 200*(number of groups) results.

**Comment by blizzz** [comment]
> Nice, but it's not OCS, so we can't use it or get different results in the apps compared to the web.

the sharess endpoint isn't either?

**Comment by brtptrs** [comment]
@dan0xii We only have local users, no LDAP

**Comment by nickvergessen** [comment]
> the sharess endpoint isn't either?

That one is, see: https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/apps/files_sharing/appinfo/routes.php#L82-L89

**Comment by nickvergessen** [comment]
@brtptrs okay, so are you using a lot of groups and have limited sharing to own groups only?

**Comment by brtptrs** [comment]
We have only 15 groups.
Ever user is in at lease one group, maybe that plays a role.

**Comment by brtptrs** [comment]
"Sharing limited to own groups" = NO

**Comment by brtptrs** [comment]
Just to verify: pr #620 does NOT solve this problem. After changing the value and checking app.js in the browser we still have the problem.
![z_screenshot_20180131_004](https://user-images.githubusercontent.com/8102905/35632681-97084466-06a7-11e8-93c0-01bdb9cde37f.png)

**Comment by nickvergessen** [comment]
Can you check the Network tab and see how the response for the `sharees` endpoint is?
Does that return set of 20s or is there one request with all?

**Comment by brtptrs** [comment]
I see only one request. 
I'll have a closer look tomorrow.
Thanks for the effort

**Comment by brtptrs** [comment]
I had a closer look and it's only one call to:
sharees?
format=json
search=
perPage=20
itemType=call
_=1517470687796

**Comment by nickvergessen** [comment]
And the result of that contains all 2000 users?

**Comment by brtptrs** [comment]
Yes I copied the result to a  text file and it contains all users.

**Comment by nickvergessen** [comment]
@brtptrs would you be okay with sending me a test account to: `<my github name>`@nextcloud.com

**Comment by brtptrs** [comment]
@nickvergessen Did you get an invitation?

**Comment by nickvergessen** [comment]
Yes, thanks

**Comment by brtptrs** [comment]
@nickvergessen At the moment we also have a problem with a turnserver that blocks video calls. But that is a different issue.

**Comment by nickvergessen** [comment]
Hmm okay, so I just realised you are using Nextcloud 12 and the old Spreed.
So I tested with that, but also that worked fine here without any issues, using the local user backend and set the limit to 2 results, I only get 2 users and 2 groups which is the expected result.

So not sure what exactly is wrong on your side, but I can reproduce the issue there. The interesting thing about the request is, that it is delayed for something like 40 seconds, but the request itself waits for 38ms and takes ~2sec. So not sure why it is delayed so badly and why the result is not matching the input.

**Comment by brtptrs** [comment]
We would like use the new version until we can upgrade to NC13. Is that completely impossible?

**Comment by brtptrs** [comment]
I've testet this locally and can confirm that the "perPage" setting works as expected in a vanilla NC12 insallation. Also setting "'sharing.maxAutocompleteResults' => 20" in the config file works locally.
However, on our production installation neither of the settings has an influence on the nuber of results. 
This is turning into a nightmare, does anyone have an idea where this options get overridden?

**Comment by brtptrs** [comment]
Enabled apps:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_antivirus: 1.0.0.0
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - polls: 0.8.1
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - richdocuments: 1.12.40
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - announcementcenter
  - encryption
  - files_pdfviewer
  - files_videoplayer
  - spreedme
  - systemtags
  - user_external
  - user_ldap

**Comment by nickvergessen** [comment]
The only idea I have it the hard way, can you add the following log calls:

`apps/files_sharing/lib/Controller/ShareesAPIController.php`
find (about line 166):
```php
$usersTmp = $this->userManager->searchDisplayName($search, $this->limit, $this->offset)
```
before add:
```php
\OC::$server->getLogger()->error('Trying to find the wrong limit1: ' . $this->limit, ['app' => 'debugging']);
```

`lib/private/User/Manager.php`
find:
```php
$backendUsers = $backend->getDisplayNames($pattern, $limit, $offset);
```
before add:
```php
\OC::$server->getLogger()->error('Trying to find the wrong limit2: ' . $limit . ' backend ' . get_class($backend), ['app' => 'debugging']);
```

`lib/private/User/Database.php`
find:
```php
. $searchLike .' ORDER BY LOWER(`displayname`), LOWER(`uid`) ASC', $limit, $offset);
```
before add:
```php
\OC::$server->getLogger()->error('Trying to find the wrong limit3: ' . $limit . '/' . $offset, ['app' => 'debugging']);
```

Then open the spreed app and see what gets logged for it.

**Comment by brtptrs** [comment]
One step forward!
The configuration option does work, but then all remaining users get loaded as "email option"

**Comment by nickvergessen** [comment]
hmm okay, let me have a look again.

**Comment by brtptrs** [comment]
Example: If I set the value for "perpage" to 10. Ten users get loaded as normal option with no mail shown in the dropdown list. The rest are shown with mail adress.

**Comment by nickvergessen** [comment]
Can you test the following change:
`apps/files_sharing/lib/Controller/ShareesAPIController.php`
find:
```php
if (isset($contact['EMAIL'])) {
```
before add:
```php
			if ($search === '' && isset($contact['isLocalSystemBook'])) {
				// All local users are already listed via the getUsers()
				// So no need to include them again, when the search term is empty
				continue;
			}
```

**Comment by brtptrs** [comment]
YES!!!! That solved it. 
Thanks!!!

**Comment by nickvergessen** [comment]
I added a bit more code in the PR: https://github.com/nextcloud/server/pull/8205
The problem is currently also searching for `@` or eg. `.de` or `.com` would break it.
The second part of https://github.com/nextcloud/server/pull/8205/files fixes that.
