### ISSUE TITLE
Voice Messages - js error on conversations with "/" in name

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/spreed#6174]
## Steps to reproduce
1. create a conversation with "/" in the conversations name
2. try to add a  voice messge:

> Failed to load resource: the server responded with a status of 404 ()
talk-main.js?v=51daffa7-92:1 Refused to set unsafe header "Content-Length"
(anonymous) @ talk-main.js?v=51daffa7-92:1
/remote.php/dav/files/.../Talk/Talk%20recording%20from%202021-07-01%2022-22-44%20(A/B).wav:1 Failed to load resource: the server responded with a status of 404 ()
talk-main.js?v=51daffa7-92:1 Error while uploading file "Talk recording from 2021-07-01 22-22-44 (A/B).wav":Error: Invalid response: 404  Talk recording from 2021-07-01 22-22-44 (A/B).wav 404
uploadFiles @ talk-main.js?v=51daffa7-92:1

3. adding voice message from android phone also not seems to work in that case.

many of our chats have a "/" in the name because in the past the app automatically used this a delimiter between the user-names.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/6178

**Comment by nickvergessen** [comment]
Sub tasks for iOS and Android have been raised

**Comment by nickvergessen** [comment]
Reopening for adjusting the length
