### ISSUE TITLE
Duplicate sessions no longer being detected 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#6184]
## Steps to reproduce
1. Create a call via ios app or web 
2. Open the session via web or ios app 
3.

### Expected behaviour
Tell us what should happen
 
On talk 11 I always got an popup saying duplicate session and it transfer the session from IOS app to web and from web to ios and thats no longer an option 

### Actual behaviour
Tell us what happens instead

On ios 12.0.1 no longer getting 

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
IOS 12.2.0

Nextcloud Version

22.1.1

**Comment by nickvergessen** [comment]
Feel free to read the changelog
https://github.com/nextcloud/spreed/releases/tag/v12.0.0

**Comment by andyxheli** [comment]
Thank you!! I guess it makes a lot of sense not having it anymore.
