### ISSUE TITLE
Design improvements in the call view

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6191]
* Add some pixels breathing room between the videos
* Make sure the background between the videos is not black but dark grey
* Place icons/buttons of own video always at the same position (independent of grid vs. promoted vs. screenshare view, or when the grid gets another column/row)
* Sort people with videos to the front
* Fixed size of the grid (Teams has 9 max?) to avoid performance issues

**Comment by AndyScherzinger** [comment]
Looping in @karlitschek and @jancborchardt for the "this is it" question

**Comment by karlitschek** [comment]
@AndyScherzinger Looks great!

**Comment by jancborchardt** [comment]
Sounds good! :) @marcoambrosini @nimisha-vijay?

**Comment by marcoambrosini** [comment]
I agree with everything but this

> Sort people with videos to the front

As it would cause continuous reflowing of the video elements and make videos jump around as people toggles video on and off

**Comment by nickvergessen** [comment]
"continuous reflowing of the video elements"

It's more like an initial/one-time thing. should reflow back and forth, but we can discuss it

**Comment by nimisha-vijay** [comment]
Looks good! Also one thing that I noticed on a one-on-one call in speaker view when the navigation and sidebar are both kept open (so the actual content is narrow) -- the other person's mic/video icon can be close to your own and might even overlap and this looks a bit weird, don't you think?

![image](https://user-images.githubusercontent.com/52440189/131829911-3ee5f45c-a239-47bb-a42d-99cc230c60a8.png)
