### ISSUE TITLE
Quote window

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#6209]
## Steps to reproduce

1. Receive a message.
2. Click on the quote message.

### Expected behaviour
Scroll up a message to make it readable:

![obraz](https://user-images.githubusercontent.com/47037905/132309219-f936c606-ae9d-4903-9b80-346bc45bd977.png)

### Actual behaviour
The last message is obscured by a quote window:

![obraz](https://user-images.githubusercontent.com/47037905/132310557-5e5fd991-4711-4aa9-9f73-459b8a5d6a30.png)

## Talk app

**Talk app version:** 12.1.1

## Browser

**Browser name:** Firefox

**Browser version:** 91.0.2

## Server configuration

**Nextcloud Version:** 22.1.1

**Comment by nickvergessen** [comment]
This is handled like suggested since a longer time now
