### ISSUE TITLE
I have no Voice Message (Question?)

### ISSUE THREAD

**Issue by FoxXxHater** [nextcloud/spreed#6216]
Hello,

in my Chats i have no funktion to send voice messages. (see picture)

![Screenshot_1](https://user-images.githubusercontent.com/54017453/132809953-3e7e7059-e2a5-4fb5-b1ab-b113a347bd93.png)

In the End this is more a question.

But how i can activate this funktion?

Have a nice day!

## Talk Version
10.0.9

## Nextcloud Version
20.0.12

**Comment by Ivansss** [comment]
Hello @FoxXxHater :)
Voice messages were introduced in [Talk 12](https://github.com/nextcloud/spreed/releases/tag/v12.0.0)
You would need to upgrade your Nextcloud version to 22 and then install Talk 12.

**Comment by FoxXxHater** [comment]
Okay, thanks

I have to look to update...

Because in my last try all my nextcloud is crashed because the apps are incompatible

**Comment by FoxXxHater** [comment]
> Hello @FoxXxHater :)
> Voice messages were introduced in [Talk 12](https://github.com/nextcloud/spreed/releases/tag/v12.0.0)
> You would need to upgrade your Nextcloud version to 22 and then install Talk 12.

Is Nextcloud 22 a Beta? Because i have updated my to the "latest" version = 21.0.4

![Screenshot_1](https://user-images.githubusercontent.com/54017453/132833791-3c61ed76-1a7e-4ab6-9479-a43fe3b1855f.png)
