### ISSUE TITLE
Record voice messages in the web UI as .mp3

### ISSUE THREAD

**Issue by jacotec** [nextcloud/spreed#6217]
**Is your feature request related to a problem? Please describe.**
The mobile apps are recording voice messages as MP3 (as I'd expect it nowadays), but a voice message done in the Web UI is recorded and distributed as a WAV file.

This is a complete waste of storage and transmission bandwith (especially to the mobile apps).

**Describe the solution you'd like**
Web UI should record a voice message in a compressed format like MP3. As all mobile apps are handling MP3 fine (because they are using it) the MP3 format should be preferred.

**Comment by nickvergessen** [comment]
Unluckily this broke in cross browser compatibility.
It's also impossible for us to ship a MP3 codec or something with a matching license, or to advice users to install one in some other way, so for now this is a will not fix.

Ref:
* https://github.com/nextcloud/spreed/pull/5610
* https://github.com/nextcloud/spreed/pull/5902
* https://github.com/nextcloud/spreed/pull/5898
* https://github.com/nextcloud/spreed/pull/5903

**Comment by jacotec** [comment]
@nickvergessen Hmmmm ... it works perfectly at Element-Web and Rocket Chat, so I don't fully understand the issue.

**Comment by nickvergessen** [comment]
Safari/iOS is unable to play mp3s created with ff or chrome. 🤷‍♂️
As you can see in the linked PRs we tried to fix it in several ways and over a long period so we can go with mp3 but no way worked for all browsers at the same time, so we had to fallback to a format that works for all clients/browsers/apps
