### ISSUE TITLE
Only grab camera / microphone when joining call

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#623]
Currently the camera/microphone is grabbed when the app is started. This should change and the hardware only be grabbed when a user joins a call (and released when the call is left).

Probably makes sense to implement this together with #538.

**Comment by borekon** [comment]
Also it would be great to allow only share the screeng when mic/cam are not available or present (i.e. desktop computers)

**Comment by maxauvy** [comment]
+1 for this.

This app allows for text-only chat, but it's actually impossible in some cases due to the app requesting access to camera/mic at start. Users of desktop computers (p.e.) should also be able to participate :wink:

**Comment by nickvergessen** [comment]
@borekon your request will be dealt with in #512

**Comment by borekon** [comment]
OK, thanks

jueves, 22 marzo 2018, 04:07p. m. +01:00 de Joas Schilling notifications@github.com<mailto:notifications@github.com>:


@borekon<https://github.com/borekon> your request will be dealt with in #512<https://github.com/nextcloud/spreed/issues/512>
