### ISSUE TITLE
Update UI when audio/video call is in progress but user has not joined yet

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#625]
There is no way for users to see that an audio/video call is currently in progress in the room if they are in the room but didn't join the call yet. I think it would be nice to show this somewhere in the UI (maybe the right side where the room name is shown?).

**Comment by Ivansss** [comment]
I also think that's a really important thing we need to add to the UI asap.
@jancborchardt Do you have any ideas here?

**Comment by nickvergessen** [comment]
I think it is duplicate of #534

**Comment by fancycode** [comment]
It's similar, #534 seems to be mostly about the "Join call" button.

**Comment by nickvergessen** [comment]
yeah which is "making it more prominent that a call is happening" 😉

**Comment by jancborchardt** [comment]
Another concrete proposal is at
→#976 If the room does not have an active call yet, button should say "Start call" 

(Then the button would be "Start call" normally, and "Join call" when a call is active.)
