### ISSUE TITLE
🔕 "Silent send" for chat messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6257]
Similar to the idea in https://github.com/nextcloud/spreed/issues/3950 brought up by @jenniferpiperek 
It should be possible to let the author send a message which does not trigger a notification for the recipient independent of their settings/DND. The idea is that I as an author might know that it does not matter when the recipient will read the text.

In the meantime Telegram also got this feature.

- [x] API https://github.com/nextcloud/spreed/pull/7331
- [x] Web #7366
- [x] iOS https://github.com/nextcloud/talk-ios/issues/787
- [x] Android https://github.com/nextcloud/talk-android/issues/1992

**Comment by marcoambrosini** [comment]
Pass in `silent = true` on post request
https://github.com/nextcloud/spreed/pull/7331/files#diff-3f8970573742fb41e3bee92a0f7b7fae33e60043734bcd1171095991c031a6aeR241

UI ideas for now:
- Long press -> dialog for mobile clients
- Split button on web ui

- [ ] Should message object contain info about whether it was sent silently or not? @nickvergessen

**Comment by nickvergessen** [comment]
So, had some thoughts. We could go with a new comment verb, but that would break various places on the API where only 1 verb can be passed in e.g. in the search:
https://github.com/nextcloud/spreed/blob/c07251f0c67d3c02debe1f6dbe0e12ee3fe9f99a/lib/Search/MessageSearch.php#L137

Also if the API would allow multiple verbs, it would also create query complexity by performing an OR (or IN) operation. So for now I think it would be good if we don't store the information (as we noticed this is also how telegram is handling it).

**Comment by marcoambrosini** [comment]
WEB UI

We found 2 types of split buttons. 
1) Looks like a split button but really the arrow opens an action menu and a click on an action immediately triggers it
2) Behaves like a proper split button: persistently modifies the button and then requires a second click to trigger the action

... so more research about split buttons is needed
For now let's have a 3 dot menu to the left of the send button

**Comment by nickvergessen** [comment]
Closing as all implementations are done
