### ISSUE TITLE
Leaving/deleting the current room still shows chat

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#626]
## Steps to reproduce
1. Create public room
2. Leave public room
3. Write something in the chat that is still visible

### Expected behaviour
Either the chat should no longer be visible, or there should be no way to write anything.

### Actual behaviour
A notification is shown that the message could not be sent.

**Comment by nickvergessen** [comment]
@danxuliu

**Comment by nickvergessen** [comment]
Also for guests there is no message shown that the room does not exist anymore or something like that.
