### ISSUE TITLE
Move the local media controls to the topbar

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6268]
As discussed in the design team, I think we should move the local media controls to the top-bar, this would bring the following benefits:

- All the important call actions will be grouped in one single place making the UI simpler (our major competitors do the same, either in a top-bar or in a bottom bar);
- The buttons will be on a dark grey background and not on a video anymore, making the UI more easily readable;
- The buttons will not overlap with speaker icons in speaker mode;

Here's a screenshot of how teams does this:

![2 1](https://user-images.githubusercontent.com/26852655/133985375-1caf1a3a-b00a-4b94-8340-f5761051dd6e.png)

**Comment by nickvergessen** [comment]
This would also solve the jumping of your own controls in the grid view when someone joins/leaves (creating/deleting a row or column) while you try to click. Happens to me almost on a weekly basis...

**Comment by nickvergessen** [comment]
Done with #6460
