### ISSUE TITLE
Audio notification on invite

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#627]
When a user gets invited to a room, she should receive an audio notification besides the notification in Nextcloud. If the browser tab is not visible, you don't see that somebody invited you to a call.

**Comment by kebekus** [comment]
I fully support the enhancement request. The way notifications work at present, Nextcloud Talk is of limited use to me. -- Thanks for coming up with such a useful product, though.

**Comment by nickvergessen** [comment]
Hmm we trigger HTML notifications via the [notifications apps](https://github.com/nextcloud/notifications).

Of course we could add sound there, but I'm not completely sure. I guess we should only do it for this special case.
