### ISSUE TITLE
Background is white rather than dark since the top bar was added to calls

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#6284]
Regression introduced in #6269 

When there are no other participants in the call the "empty" background is now white instead of dark grey.

Besides that, when the call is being left, the background of your own user has a white tint. This might point to a different issue, though, as the background colour should match the avatar, but even before this change it was dark grey.

**Before:**
![Talk-Leave-Call-Background-Before](https://user-images.githubusercontent.com/26858233/134726816-2a37968e-42e5-484e-8e2d-a36b9620df58.png)

**After:**
![Talk-Leave-Call-Background-After](https://user-images.githubusercontent.com/26858233/134726825-0fc6681c-a6c6-4e90-9133-1190a7f9b15a.png)

**Comment by nickvergessen** [comment]
Jup noticed it too
