### ISSUE TITLE
Size of my windows with 2 person conversation.

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/spreed#629]
I have problem with Nextcloud Talk my window size when talking to other person. Basically it is usually too big and in wrong position and I can’t see fully person which I'm talking too. There is no issue when 3-4 person join conversation as all windows get smaller.

Is is possible to change to get my picture smaller every time when talking to somebody? Something like maximum window size?

**Comment by Ivansss** [comment]
At the moment, we are working on an issue when chatting with more than 2 participants #618.
Currently there is no way to adjust your own video size.
However, there have been no issues reported when chatting only with another person.
What's your screen resolution or window size?

**Comment by PiotrIr** [comment]
Hi Ivan,
Sorry I haven't replied but I was trying to find some print screens with this issue. I can't see it on my laptop but two people which were talking to me complained about this. Perhaps their resolution was quite low. I will try to get some print screens in next couple of coming days.
