### ISSUE TITLE
Error when upgrading spreed from NC 12.0.5 to 13.0.0. - shared hosting

### ISSUE THREAD

**Issue by DaCryptor** [nextcloud/spreed#630]
Cannot upgrade to NC13.

NC-upgrade itself worked, but spreed won't update.

Error:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO HhHvb_talk_rooms (name, token, type, password) VALUES(?, ?, ?, ?)' with params ["", "6634", 3, ""]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6634' for key 'tr_room_token'

What can I do to have this fixed? Already had spreed installed in NC 12.0.5

Please help.

**Comment by nickvergessen** [comment]
Easiest way to "fix" this would be to delete all rooms and participants before the update.
The error basically says you either tried to update twice, or you have two rooms in your old database which have the same token

**Comment by DaCryptor** [comment]
Deleted the two rooms in different tables. That solved the first problem, but now I've got the error

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `activity_id`, `object_id`, `subjectparams` FROM `HhHvb_activity` WHERE (`app` = ?) AND (`type` = ?) AND (`object_type` = ?)' with params ["spreed", "spreed", "room"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_id' in 'field list'

Any ideas? I disabled the Activity-App right from the beginning. Is this the cause?

**Comment by nickvergessen** [comment]
Sounds like your activity app is not up to date?!

**Comment by nioc** [comment]
I had same issue when I installed talk ; following @DaCryptor comment, I updated table:
````sql
ALTER TABLE `owncloud`.`oc_activity` 
ADD COLUMN `object_type` VARCHAR(45) NULL DEFAULT NULL AFTER `link`,
ADD COLUMN `object_id` BIGINT(20) NOT NULL DEFAULT 0 AFTER `object_type`;
````
