### ISSUE TITLE
"you attended a call" notification shows up again

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#6302]
## Steps to reproduce
1. have a call 
2. see notification
3. dismiss it, it pops up again

![image](https://user-images.githubusercontent.com/5836855/135394450-915a16d0-ef7d-4c99-86f4-0975201519e2.png)

### Expected behaviour
Do not show it all as I attended it? Or at least do not show it again after dismissing it.

### Actual behaviour
It is shown and even after dismissing it, it pops up again.

## Talk app
on c.nc.c

**Comment by nickvergessen** [comment]
> Do not show it all as I attended it?

Please go to settings/user/activity and uncheck this field:

![Bildschirmfoto von 2021-09-30 09-57-53](https://user-images.githubusercontent.com/213943/135411775-4a61784e-7634-43af-b5f4-ce2fb1db759d.png)

> Or at least do not show it again after dismissing it.

I guess this is an issue with the notify_push. Can you confirm that it eventually fades away after wards?

**Comment by tobiasKaminsky** [comment]
> uncheck this field

I unchecked. Let's see. 

Thank you!
