### ISSUE TITLE
Notifications not sent when tab/chat is opened on a device, even when "notify all" is selected

### ISSUE THREAD

**Issue by msartiano** [nextcloud/spreed#6305]
## Steps to reproduce
1. Install Talk App on Android/iOS and login, open talk and then close it, ready to receive notifications.
2. Open Talk on a web page, and open a discussion with a friend. This now is your active discussion.
3. Ask that friend to send a message. The notification will not be sent to your mobile device.

### Expected behaviour
If I choose to notify all, then all devices are notified. As some people may want to silence phones, I suggest having another option "send notification for every message to your devices"

### Actual behaviour
A mobile notification is sent, as the tab could have been left opened in the browser, and the receiver could have missed important messages

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Operating system:** Linux hosting, Windows for web, Android and iOS for mobile

**Browser name:** Firefox

**Browser version:** Latest

## Details
I believe this could be also intented as a device, although it completes changes the experience of a chat system, as when it is opened on Web, the recipient misses any mobile notificaiton. Let's say I open the web page, then go out to walk the dog, and I get a critical message, I would miss it.

Is this expected?
Is there a possible fix or any workaround?

One workaround that I thought is to have 2 accounts, a me-web and me-app account, and do it for my other talk participants, instruct them to use web on web and app on app. Then Share the App Talk folder in the web/main profile so that files that are shared, are seen in it.
As you can probably tell, it would be very cumbersome to do so, and also to instruct to remember to click to a non relevant active discussion so that you can receive messages from all the other participants

Thanks for all the help in advance, the software is amazing, and I hope I may be wrong and that I just did not see the option to do so ;)

**Comment by nickvergessen** [comment]
Still being worked towards with https://github.com/nextcloud/spreed/issues/1575 and partial solution which is still not optimal in #1970
