### ISSUE TITLE
Video Verification not working when "Limit starting a call" is set to "Users and Moderators"

### ISSUE THREAD

**Issue by jacotec** [nextcloud/spreed#6306]
## Steps to reproduce
When "Limit starting a call" is set to "Users and Moderators" in the general talk settings, Video Verification can't be used. The link recipient just gets "Failed to load the page".

I have the "Limit starting a call" set to "Users and Moderators" intentionally, because we use some chats with external guests via public link. Allowing everyone to start a call will "bomb" us with calls instead chat messages where we decide if we start a call or not.

### Expected behaviour
Video Verification should be excluded from this limitation internally as otherwise this complete feature does not work currently with this setting.

### Actual behaviour
Video Verification does not work at all

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
yes

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
yes

**Comment by nickvergessen** [comment]
Nice clash of functionality. Absolutely right, this needs fixing somehow.

#6190 will introduce more granular permissions and should help with that looking forward
