### ISSUE TITLE
Talk doesn't work on Google Chrome

### ISSUE THREAD

**Issue by abarranco79** [nextcloud/spreed#631]
## Steps to reproduce
1.I perform the installation without problems
2.I can see the icon in the installed toolbar
3.And I receive the error... Error accessing the microphone and camera.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Error accessing the microphone and camera.

## Browser
Google Chrome
**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
both
**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by DanLeonelli** [comment]
I have the same problem

**Comment by Ivansss** [comment]
@abarranco79 are you connecting to your server via https?
Chrome requires a https connection to give camera and microphone permissions.

**Comment by nickvergessen** [comment]
Closing due to the lack of feedback
