### ISSUE TITLE
Can not complete a mention with the mouse

### ISSUE THREAD

**Issue by seepatrol** [nextcloud/spreed#6318]
<img width="769" alt="1538-446-max" src="https://user-images.githubusercontent.com/91799116/135726961-54649f1f-3713-4719-89a6-e071eb5da097.png">

i can't click on the name that i want in nextcloud talk. on chrome.

**Comment by nikola-gladovic** [comment]
I think this ticket was already fixed on current version.

**Comment by nickvergessen** [comment]
At least with Firefox it is not working.

**Comment by manu-p** [comment]
Not working with Brave Version 1.34.80 Chromium: 97.0.4692.71 (Build officiel) (64 bits)
