### ISSUE TITLE
Talk needs a way to hide certian users/groups from contacts!

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#632]
There are certain accounts/groups that are designed for services or admin purposes that I don't want users to know exist much less be able to call.  Please create some way to hide them from the call roster/contact list so that users cannot see or call them.

**Comment by nickvergessen** [comment]
Well those are the same options as you get when you are trying to share a file.
How do you hide them there?

**Comment by Luticus** [comment]
Hummm, that's a good point.  I guess I didn't think about that because with file sharing you have to start typing in then name before the list populates with suggestions where as with Talk it shows the list fully populated and is narrowed by typing.  Whatever the case, you're right.  I would like these accounts and groups hidden from the share lists as well.  Perhaps this issue is better served in the main Nextcloud github.

**Comment by nickvergessen** [comment]
Yes, that's exactly my point, can you open an issue there?
https://github.com/nextcloud/server/issues/new

**Comment by nickvergessen** [comment]
PS: You should mention the key word "collaboration" there. Thats the API which is used for sharing and calling

**Comment by Luticus** [comment]
Thanks, I will do that.
