### ISSUE TITLE
iOS nextcloud talk logs out after login

### ISSUE THREAD

**Issue by cottyard** [nextcloud/spreed#6328]
This might not be a bug because I'm not very good with server stuff. I just set up a nextcloud server on Ubuntu and everything worked fine with browsers and the Android app, but it went wrong with the iOS app. Just posting to check if anyone knows what happened. Server access log attached.

## Steps to reproduce
1. Install the latest NextCloud 
2. Install the latest talk app on the admin page
3. Login from iOS NextCloud app by any user

### Expected behaviour
Android nextCloud app from google play works just fine (v12.2.1)

### Actual behaviour
In iOS app, user will log out after a successful login.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
No

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
No

**Operating system**: Ubuntu/RedHat/...
Ubuntu 20.04

**Web server:** Apache/Nginx
Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL
SQLite

**PHP version:** 7.2/7.3/7.4
8.0.11

**Nextcloud Version:** (see admin page)
22.2.0

### Server log (data/nextcloud.log)
<details>

```
unix: - - [04/Oct/2021:16:51:07 +0000] "POST /login HTTP/2.0" 303 0 "-" "\xE7\x9A\x84iPhone (Nextcloud Talk)"
unix: - - [04/Oct/2021:16:51:07 +0000] "GET /login/flow/grant?stateToken=Ikb43yJo9yJqP8WZ4JXHm4rCeEsG76xkiixKGh6bgt55IRtKIbwpA1gMW0KpwOgv&clientIdentifier= HTTP/2.0" 200 4957 "-" "\xE7\x9A\x84iPhone (Nextcloud Talk)"
unix: - - [04/Oct/2021:16:51:08 +0000] "GET /core/js/oc.js?v=03a58b4d HTTP/2.0" 200 4100 "-" "\xE7\x9A\x84iPhone (Nextcloud Talk)"
unix: - - [04/Oct/2021:16:51:08 +0000] "GET /cron.php HTTP/2.0" 200 40 "-" "\xE7\x9A\x84iPhone (Nextcloud Talk)"
unix: - - [04/Oct/2021:16:51:09 +0000] "POST /login/flow HTTP/2.0" 303 0 "-" "\xE7\x9A\x84iPhone (Nextcloud Talk)"
unix: - - [04/Oct/2021:16:51:10 +0000] "GET /ocs/v2.php/cloud/user?format=json HTTP/2.0" 401 106 "-" "Mozilla/5.0 (iOS) Nextcloud-Talk v12.3.0"
unix: - - [04/Oct/2021:16:51:10 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/2.0" 200 817 "-" "Mozilla/5.0 (iOS) Nextcloud-Talk v12.3.0"
unix: - - [04/Oct/2021:16:51:10 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0" 405 0 "-" "Mozilla/5.0 (iOS) Nextcloud-Talk v12.3.0"
```
</details>

**Comment by SystemKeeper** [comment]
`unix: - - [04/Oct/2021:16:51:10 +0000] "GET /ocs/v2.php/cloud/user?format=json HTTP/2.0" 401 106 "-" "Mozilla/5.0 (iOS) Nextcloud-Talk v12.3.0"`

The iOS Talk App checks for 401 status code (when an app token is revoked), see [here](https://github.com/nextcloud/talk-ios/blob/40ac5868fb9cb376e58d9e32db144ec06b47993d/NextcloudTalk/NCAPIController.m#L1925-L1934) and [here](https://github.com/nextcloud/talk-ios/blob/40ac5868fb9cb376e58d9e32db144ec06b47993d/NextcloudTalk/NCAPIController.m#L1523-L1543)

So the result of `GET /ocs/v2.php/cloud/user?format=json` will log you out immediately again. Not sure why this call fails. Have a look if there's anything in the nextcloud log.
