### ISSUE TITLE
Access to microphone & camera was denied

### ISSUE THREAD

**Issue by DanLeonelli** [nextcloud/spreed#633]
## Steps to reproduce
1. Update to NC 13
2. Try to use Talk
3. Access to microphone & camera was denied

### Expected behaviour
The app should work

### Actual behaviour
The app still won't work

## Browser
Safari (latest version) and Chrome (latest version)

**Microphone available:**Yes

**Camera available:** Yes

**Operating system:** macOS

**Browser name:** Safari / Chrome

**Browser version:** 11.0.3 / 64.0.3282.140

## Spreed app

**Spreed app version:** 3.0.1

**Custom TURN server configured:** No

**Custom STUN server configured:** No

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** 13.0.0

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by Ivansss** [comment]
You should give your browser access to your camera and microphone in order to use the app at the moment.
Also, Safari is currently not supported.

**Comment by GLLM** [comment]
One question though,
I'm on NC 13 stable (updated via Beta canal).
I have a laptop with micro+cam at work.
My contact has a desktop without cam or micro.
I expected to be able to TEXT chat --> I cannot.

Is this expected ?
Couldn't Nextcloud infor the user that the app will run in text-restricted mode due to that ?

It's a pity I must continue using whatsapp due to this.

Thanks,
GLLM

**Comment by Ivansss** [comment]
Hi @GLLM,
This is already in the roadmap #619 and might be included in the next release.

**Comment by DanLeonelli** [comment]
Hello @Ivansss thank you for replying. I see that Safari is currently not supported, but what about Chrome? I'm experiencing the same issue with it.

**Comment by Ivansss** [comment]
@DanLeonelli are you connecting via HTTPS?

**Comment by DanLeonelli** [comment]
@Ivansss Does it work only via HTTPS? (Sorry if it sounds like a dumb question, I'm new)

**Comment by Ivansss** [comment]
Not a dumb question 😄 
But as said here https://github.com/nextcloud/spreed/issues/631#issuecomment-363729700, Chrome requires a https connection to give camera and microphone permissions.

**Comment by DanLeonelli** [comment]
@Ivansss Thanks a lot for the help. I'll see how to enable a HTTPS connection right away. 😸

**Comment by GLLM** [comment]
Thanks @Ivansss :-D Sorry for bothering.

**Comment by Ivansss** [comment]
@GLLM no problem 😊 
@DanLeonelli You can try in the meanwhile with Firefox, since it doesn't have that requirement.

**Comment by owhen** [comment]
Having the exact same Problem, but I still connect via HTTPS.

**Comment by Ivansss** [comment]
@owhen Can you explain a bit more your problem? :)
There were 2 different problems discussed in this issue.
Do you have camera/mic in your device?
What browser are you using?

**Comment by owhen** [comment]
@Ivansss sure. When I open the Talk App, I get the same error message: https://user-images.githubusercontent.com/35517527/35920631-5e039078-0be6-11e8-8ae1-dbb8699641fb.png
I tried this with the latest Chrome and Firefox on Ubuntu. I am using a ThinkPad T430, but with Nextcloud 12 and other browser applications using Camera/mic I don't have this problem.
On my cell phone, Nextcloud Talk works.

**Comment by Ivansss** [comment]
@owhen is your camera/mic being grabbed by another browser/app when you launch the Talk app?
Could you tell us what error message do you see in your browser's console?
Should be after "Access to microphone & camera failed"
