### ISSUE TITLE
mention a group in a talk group

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/spreed#6359]
**Is your feature request related to a problem? Please describe.**
Whenever I want to mention a group in a talk group it doesn't work and I have to mention the people in the group individually.

**Describe the solution you'd like**
Please add the function that groups can be mentioned with @ (for example @nextcloudgroup1).

**Describe alternatives you've considered**
Mention people individually (but this is not a good solution)

**Comment by nickvergessen** [comment]
See #6339
