### ISSUE TITLE
Joining a call via public link without a pass should add me as a participant

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#636]
Why doesn't it happen?

**Comment by Ivansss** [comment]
That should happen.
Do you mean joining the call being a logged-in participant or a guest?

**Comment by mario** [comment]
As a guest. Shouldn't it turn me into a participant automatically?

**Comment by mario** [comment]
Or maybe I'm just being stupid and I need to be logged in :)

**Comment by Ivansss** [comment]
You could join both ways.
If you are a logged-in user you will be added permanently as a participant of that room.
If you are a guest, you will be added as a guest. So when you leave the room, you are no longer a participant.
