### ISSUE TITLE
All conversations gone after manual upgrade from Nextcloud 20.0.8 to 21.0.5

### ISSUE THREAD

**Issue by th-dorsch** [nextcloud/spreed#6361]
## Steps to reproduce
1. setup standard NC installation using archive nextcloud-20.0.8.tar.bz2 and web setup chosing DB MySQL.
2. open Talk app, create two chats and a few messages (screenshots and data dumps of tables oc_comments and oc_talk_* enclosed)
3. manually upgrade the installation to NC21.0.5
4. verify that no previous chats are shown in the Talk app.

### Expected behaviour
On opening the Talk app V10.0.10 in NC V21.0.5 I should see my recently created two chats with the before entered messages.

### Actual behaviour
Talk V10.0.10 opens in NC V21.0.5 with no previous chats shown.
All data referenced in this issue originates from a dedicated test installation created solely for documentation purposes. Prior to this artificial installation we manually migrated a big (>350GB data) client installation and the aforementioned issues came up during health check. For this client the chat history is of utmost importance so we manually rolled back the upgrade. No further upgrade to NC21 is currently possible until this issue is somehow clarified. Migrations of 11 further V20.0.8 instances of the same client are also now on hold waiting for clarification of this issue.

## Talk app

**Talk app version: V10.0.10 before upgrade, V11.3.2 after upgrade. 

**Custom Signaling server configured: no

**Custom TURN server configured: no

**Custom STUN server configured no

## Server configuration

**Operating system**: Ubuntu 20.04.3

**Web server:** Apache 2.4.41/Nginx 1.20.1

**Database:** Ver 15.1 Distrib 10.3.31-MariaDB

**PHP version:** 7.4.3

**Nextcloud Version:** pre: 20.0.8 / past: 21.0.5

**List of activated apps:** 

<details>

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 4.0.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.10.5
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.8.6
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.10
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**

<details>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "thorstentest.--------------.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/thorstentest.--------------.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}

</details>

List of attached files:
Chat1.jpg - screenshot of test chat in Talk app
Chat2.jpg - screenshot of test chat in Talk app
tables_pre_update.sql.txt - tables oc_comments and oc_talk_* before update
tables_post_update.sql.txt - tables oc_comments and oc_talk_* after update
updatelog.txt - STDOUT and STDERR of the occ upgrade command
nextcloud.log
![Chat1](https://user-images.githubusercontent.com/92690468/137644274-a487cf59-6014-45f5-b5e0-883eeb3df41e.jpg)
![Chat2](https://user-images.githubusercontent.com/92690468/137644275-6677d2a1-233b-4742-8537-b604b4a4ee0c.jpg)
[Issue.txt](https://github.com/nextcloud/spreed/files/7360814/Issue.txt)
[nextcloud.log](https://github.com/nextcloud/spreed/files/7360815/nextcloud.log)
[tables_post_update.sql.txt](https://github.com/nextcloud/spreed/files/7360818/tables_post_update.sql.txt)
[tables_pre_update.sql.txt](https://github.com/nextcloud/spreed/files/7360819/tables_pre_update.sql.txt)
[updatelog.txt](https://github.com/nextcloud/spreed/files/7360820/updatelog.txt)

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues/5518#issuecomment-845646929
