### ISSUE TITLE
iOS: Safari doesn't work. 

### ISSUE THREAD

**Issue by hoellen** [nextcloud/spreed#637]
Hello,

I can't establish a connection from any browser to Safari Browser on iOS (iPad). 
But it works with the iOS Talk App. 

Other connections from and to Android, Linux, Windows with Browser Chrome and Firefox works fine. 

I use the latest spreed app from App Store and a coturn server for TURN/STUN. 
## Steps to reproduce
1. Open Room
2. Join room on one client (me: Linux, Firefox 58)
3. Join room on iPad (iOS 11.2.5)

### Expected behaviour
Connection works.

### Actual behaviour
On Safari (iOS) there is still the 'Waiting for others to join the call …' message. On the other Client (e.g. Linux, Firefox 58) the screen goes black and want to open a connection.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** iOS 11.2.5

**Browser name:** Safari

**Browser version:** 11

### Browser log
The logs provided are from my Firefox (the other Client) which I'm trying to connect. 
<details>

Insert your browser log here, this could for example include:
Javascript console log:
```
JQMIGRATE: Migrate is installed, version 1.4.0															core.js:7:542
CONNECTED																																		simplewebrtc.js:18008:4
Starting spreed …																														app.js:540:4
Joined 																																			signaling.js:235:5
	Object {
			"ocs": {
				"meta": {
				  "status": "ok",
				  "statuscode": 200,
				  "message": "OK"
				},
				"data": {
				  "sessionId": "3/vwnF23VosHZsu/d+zDGk2bGlTuhn/+fNCM/dBfQa//d2/LyvFhrfQ9mWCmEre4SHILygvZ9+fHO5M5kFJwg1k+bIurYpBTeexErOcmwiwN65vqlbhvnTfm30Qj713FsTZ+ExvOpYcTmUDAsVhRWYv/Lf2grk+m/UAbwyAvwtASXgMx65kvBCtctLB8luVkl1Td/NyKlnKWAX+6aWceZo7wcY4u0zkrB8LovZK05dFdfc4l9/gk6i8nr4EuCPz"
				}
			}
		}
join CB  Object { clients: {} }																							simplewebrtc.js:18270:4

Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://cloud_url/core/vendor/core.js?v=75bcefe7-114
Source-Map-Adresse: purify.min.js.map
```

</details>

## Spreed app

**Spreed app version:** 3.0.1

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: CentOS 7.4

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2.2

**Nextcloud Version:** 13.0.0

### Server log
`nothing in log`

**Comment by Ivansss** [comment]
Sorry @hoellen but Safari is not a supported browser at the moment.
That was one of the reasons for start implementing a native app for iOS 😄

**Comment by TravelTrader** [comment]
But the native App doesn't work, too!
After enter the server it says that I hadn't installed the Talk App but I use it in macOS/Firefox.
Any suggestions?

**Comment by Ivansss** [comment]
What Nextcloud server version are you running?

**Comment by TravelTrader** [comment]
Thanks for your reply.
The newest: `13.0.1`

**Comment by Ivansss** [comment]
Interesting... 🤔 
Could you send me an email to `ivan AT nextcloud DOT com` with your NC server url?

**Comment by TravelTrader** [comment]
Follows ... thanx!
