### ISSUE TITLE
List of device names is too narrow and might trim away important parts

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6389]
## Steps to reproduce
1. Use firefox so devices have weird names
2. Start a call and open the device checker
3. Try to select a device

### Expected behaviour
Device names are fully visible

### Actual behaviour
Parts are cut off

![Bildschirmfoto von 2021-10-22 16-14-12](https://user-images.githubusercontent.com/213943/138469557-3423b614-a1c3-49d3-bcaa-b1a95a011120.png)

**Comment by Antreesy** [comment]
@nickvergessen, FYI:
Multiselect element contains span with attribute `title`, which contains full name of device:

![image](https://user-images.githubusercontent.com/93392545/214798174-e1089482-e2cb-406e-ad8f-3651b2e911b8.png)

`title` is supported by all browsers and work as a tooltip on hover:
https://www.w3schools.com/tags/att_global_title.asp
![image](https://user-images.githubusercontent.com/93392545/214798688-c0e3ee99-607f-4636-a2bf-67bede3ba782.png)
