### ISSUE TITLE
Can not start conversation with email address of user

### ISSUE THREAD

**Issue by danir-de** [nextcloud/spreed#6397]
## Steps to reproduce
1. Configure Nextcloud with LDAP (Active Directory) user backend
2. Let users log in
3. Go to the Talk app
4. Search for a user that you didn't chat before using his forename.

### Expected behaviour
I would expect the search fields to be able to find users based on their forenames or email addresses, just like with the contact search in the menu bar or with the user search in the file sharing menu.

### Actual behaviour
I would expect being able to find users via any part of their visible name (like their forename) or via their e-mail address.
But I can only find them using the exact string "surname, forename".

I've attached two screenshots, demonstrating the issue:
![image](https://user-images.githubusercontent.com/4672840/138685902-95c94a67-76c8-42e8-ba59-1e39ff8df291.png)
![image](https://user-images.githubusercontent.com/4672840/138685920-6277f2d0-b1e7-4617-a00f-4986ac0236b1.png)

## Talk app

**Talk app version:** 12.1.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Operating system:** Windows

**Browser name:** Firefox & Chrome

**Browser version:** latest (93 & 95)

### Browser log
No relevant occurrences' in browser log.

**Operating system**: Debian
**Web server:** Nginx

**Database:** Maria 10.6

**PHP version:** 8.0

**Nextcloud Version:** 22.2.0 - 22.2.0.2

**Comment by danir-de** [comment]
I can confirm that it's not that way in the main share dialog, there I can search for any part of the name or the email and it finds it.

**Comment by danir-de** [comment]
I just found out that this bug only applies to the left "global" chat search and not on the search of the info panel on the right side of the screen, if that makes sense.

**Comment by nickvergessen** [comment]
Okay, currently that's expected then, as you can not start a chat with an email address atm but only add them later.

**Comment by danir-de** [comment]
The problem is not limited to searching by the e-mail address, but you can also can't find people by their the first name.

I also found out that this applies to the calendar app (when searching for people to invite to an event), so maybe the problem is not limited to just spreed? If so, should I also open a bug report on the nextcloud server is this something to fix in the individual apps?

**Comment by nickvergessen** [comment]
That sounds a bit like an issue with your ldap configuration then 🤔

**Comment by danir-de** [comment]
Thank's I'm gonna check that, but the issue with the e-mail still remains then.

**Comment by nickvergessen** [comment]
Duplicae of #4937
