### ISSUE TITLE
Can't install on Nextcloud 13

### ISSUE THREAD

**Issue by stonie08** [nextcloud/spreed#640]
I just upgraded from nextcloud 12 to 13 and wanted to try the talk app. Unfortunately I was unable to activate the app.

## Steps to reproduce
1. Go to the app overview on NC 13
2. press "activate"

### Expected behaviour
The app should be downloaded and installed

### Actual behaviour
It's sitting there for a short periiod of time and then just displays a red error:
```An exception occurred while executing 'SELECT `activity_id`, `object_id`, `subjectparams` FROM `oc_activity` WHERE (`app` = ?) AND (`type` = ?) AND (`object_type` = ?)' with params ["spreed", "spreed", "room"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_id' in 'field list'```

## Spreed app

**Spreed app version:** 3.0.1

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration
**Operating system:** Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - gpxpod: 2.2.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - qownnotesapi: 17.5.0
 - serverinfo: 1.3.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_trashbin
 - files_versions
 - ownpad
 - sharebymail
 - spreed
 - survey_client
 - user_external
 - user_ldap

```
</details>

### Server log (data/nextcloud.log)
<details>

</details>

**Comment by nickvergessen** [comment]
Do you have the activity app on your server? It sounds like it is not up to date?!

**Comment by stonie08** [comment]
I didn't have the activity app activated at all until I read your reply, as it wasn't listed as a requirement for the Talk app to work.
However I activated it and I still get the same error with the talk app.
The version of the activity app is shown to me as 2.6.1

**Comment by nickvergessen** [comment]
It's not a requirement, we check if the activity app is installed/available and if so we fix something in there. But it seems that in your case an older version of the app is there. This also happened in #630 where it was fixed by manually making sure teh activity table is okay.
So I will have a look if we can take another precaution there.

**Comment by stonie08** [comment]
I'm pretty sure I deactivated the activity app some versions ago. NC even stated, when activating the activity app, something like "the app is going to be activated, but needs to be updated, we'll forward you in 5 seconds"

**Comment by DaCryptor** [comment]
Same here (see #630).

Deactivated the activity app a long time ago. As I said, manually fixing the table worked well (to my very big surprise, as this was the first time for me changing things in my database manually). :-)
