### ISSUE TITLE
List of open conversations

### ISSUE THREAD

**Issue by jeekajoo** [nextcloud/spreed#6431]
**Is your feature request related to a problem? Please describe.**
Unless we begin to search the name of an existing conversation, it is not listed and so we cannot find/join it.
It means we have to know it exists. And we have to know the name of the conversation.

**Describe the solution you'd like**
List all existing conversations that we can join

**Describe alternatives you've considered**
Add button to show all existing conversations that we can join

Thanks !

---

- [x] Frontend https://github.com/nextcloud/spreed/issues/9675
- [x] iOS https://github.com/nextcloud/talk-ios/issues/1262
- [x] Android https://github.com/nextcloud/talk-android/issues/3070

**Comment by nickvergessen** [comment]
# 🖍️ Design

The rough design idea for web is to make the + menu a action menu with 2 entries:
![grafik](https://github.com/nextcloud/spreed/assets/213943/94af4e90-5bc1-4d1d-bbd0-19a61b00949a)

Afterwards we show the "RoomSelector" modal that is also used when you "Forward message" from the … menu of a chat message
![grafik](https://github.com/nextcloud/spreed/assets/213943/13a14057-6521-4985-8d56-efc884a16b80)

The list of conversations can be accessed by simply searching for an empty string `''` on the existing endpoint:
https://nextcloud-talk.readthedocs.io/en/latest/conversation/#get-open-conversations

**Comment by mahibi** [comment]
how should this be done for mobiles?
On android, we have the plus button at the bottom:
![grafik](https://github.com/nextcloud/spreed/assets/2932790/2908c784-77a3-493c-afdf-660e47c5f587)

a) should this show 2 options, eg. "create new conversation" and "list open conversations" with an expanded menu list this one:
https://stackoverflow.com/questions/30699302/android-design-support-library-expandable-floating-action-buttonfab-menu

b) or should the "list open conversations" be placed just as an option inside the screen that is opened when clicking the plus button?

![grafik](https://github.com/nextcloud/spreed/assets/2932790/7f23bd8e-2e04-42a5-846f-68d656d99a8a)

cc @jancborchardt @nimishavijay @AndyScherzinger

**Comment by SystemKeeper** [comment]
Please see also https://github.com/nextcloud/talk-ios/issues/1262

**Comment by jancborchardt** [comment]
Expanded FAB doesn't seem to be a thing anymore according to the spec, or am I missing something?
https://m3.material.io/components/floating-action-button/guidelines

So yes, let's go with having "List open conversations" in the + menu, but one entry further up, below "New public conversation".

**Comment by nimishavijay** [comment]
Agreed! One wording suggestion: the tooltip/alttext for the `+` button can be changed to "Create or join conversation" and there would be 2 items under that: "Create new conversation" and "Join an open conversation", what do you think?

**Comment by DorraJaouad** [comment]
I am already working on filters for the conversations list and I changed the `+` button to a 3-dot button as shown in PR #9688 and there are 3 options already. We can add a 4th option "List open conversations"

**Comment by jancborchardt** [comment]
@DorraJaouad yep sounds good! Order and wording of the actions would then be:
- Create new conversation
- List open conversations
- (divider line here?)
- Filter unread mentions
- Filter unread messages

**Comment by mahibi** [comment]
Do we already have an icon in mind for the "List open conversations" button?

**Comment by nimishavijay** [comment]
What do you think about the [forum icon](https://fonts.google.com/icons?selected=Material%20Icons%3Aforum%3A)? 
Otherwise we could just do the [public icon](https://fonts.google.com/icons?selected=Material%20Icons%3Apublic%3A) or [chat](https://fonts.google.com/icons?selected=Material%20Icons%3Achat%3A). Telegram uses a loudspeaker, similar to the [campaign icon](https://fonts.google.com/icons?selected=Material%20Icons%3Acampaign%3A), my vote still goes to forum. What do you think? :)

**Comment by mahibi** [comment]
I would prefer the [public icon](https://fonts.google.com/icons?selected=Material%20Icons%3Apublic%3A)
What are your opinions? @jancborchardt @DorraJaouad @SystemKeeper ?

**Comment by DorraJaouad** [comment]
I go for [forum icon](https://fonts.google.com/icons?selected=Material%20Icons%3Aforum%3A) or [list icon](https://fonts.google.com/icons?selected=Material+Icons:format_list_bulleted:&icon.query=list)

**Comment by mahibi** [comment]
so i went with the list icon for now. 
For wording things etc., please feel free to have a look/suggest improvements: https://github.com/nextcloud/talk-android/pull/3102
