### ISSUE TITLE
document preview will not be updated

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6482]
## Steps to reproduce
1. create a md document and share it via talk 
2. a preview will shown up in the chat
3. change the shared document
4. there is no preview update not even if you share the document with another chat

## Talk app 12+13 // NC 22/23

**Comment by nickvergessen** [comment]
We can not monitor the files that are "visible" in the chat to see if their preview would change. For now this is a will not fix as it would kill the performance of the server
