### ISSUE TITLE
"Join call" messages incomplete when multiple people clicking on "start call" at the same time

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#6490]
Tried in c.cn.com 22.2.1.2 with Talk 12.2.1

Andy clicked on "start call", I clicked the same button a few second later. I saw already in the chat that Andy started the call but the button hasn't change from "start call" to "join call" for me yet.

![image](https://user-images.githubusercontent.com/1589737/141499110-a51ac5f2-42b5-4a83-924d-b326237cc5e8.png)

As a result their is no message in the chat that I joined the call.

**Comment by blizzz** [comment]
Who is this You in the screenshot?

**Comment by nickvergessen** [comment]
It says "You joined the call" right there in the middle of the screenshot ❓

**Comment by schiessle** [comment]
🙈 forget it, seems that I was to much side tracked today. 🙈
