### ISSUE TITLE
No longer receiving Talk Notifications 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#6491]
## Steps to reproduce
1. Send message to user. 
2. Received message from user￼
3.

### Actual behaviour
No longer receiving talk notification via web, desktop client, IOS, Android. 

## Talk app
12.3.1
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
12.1.2
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

## Browser

**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
**Operating system:** Windows/Ubuntu/...
Windows 10, IOS, Android
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 50.1/55/...
95.0.4638.69
### Browser log

**Operating system**: Ubuntu/RedHat/...
Ubuntu 20.04
**Web server:** Apache/Nginx
apache2
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB 10.5.13
**PHP version:** 7.2/7.3/7.4
8.0.12
**Nextcloud Version:** (see admin page)
22.2.2

If i send a test via sudo -u www-data php /var/www/nextcloud/occ  notification:test-push --talk username it works 

but if someone send me a massage or I send someone a message or call nothing happens

**Comment by andyxheli** [comment]
Just got this error today 

{"reqId":"4wJdIXzMkLTwoIzM4osP","level":3,"time":"2021-11-15T15:08:54+00:00","remoteAddr":"77.97.178.63","user":"admin","app":"notifications","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v1/chat/63jvairb","message":"cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0 RC1","version":"22.2.2.0","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":113,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":64,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":294,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/Push.php","line":303,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/Push.php","line":124,"function":"sendNotificationsToProxies","class":"OCA\\Notifications\\Push","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/App.php","line":99,"function":"flushPayloads","class":"OCA\\Notifications\\Push","type":"->"},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":272,"function":"flush","class":"OCA\\Notifications\\App","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/ChatManager.php","line":259,"function":"flush","class":"OC\\Notification\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/ChatController.php","line":242,"function":"sendMessage","class":"OCA\\Talk\\Chat\\ChatManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"sendMessage","class":"OCA\\Talk\\Controller\\ChatController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"CustomMessage":"cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications"},"id":"6192b1fb0c5c8"}

**Comment by nickvergessen** [comment]
Please update the certificate chain of your server. It seems to not accept recent Let's encrypt certificates

**Comment by andyxheli** [comment]
Hello i ran a ssl check and i dont seem to be having an certification chain issue
![image](https://user-images.githubusercontent.com/59488153/142438039-4f4eb294-9d8c-43e4-8270-7979e369647e.png)
