### ISSUE TITLE
Nextcloud Talk Screen Share Loop

### ISSUE THREAD

**Issue by HasanZahir1992** [nextcloud/spreed#6495]
![screen loop](https://user-images.githubusercontent.com/93823067/141610378-40f287b1-1551-43e9-9b4e-950c429e39e2.png)
**Is your feature request related to a problem? Please describe.**
when i share screen it creates a loop in my screen

**Describe the solution you'd like**
Let the screen share does not effect the person whose sharing screen OR when a user shares screen let it not refelect on the person who shares creen
**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
We will not change this for now, as it's important for people to see which screen they shared in a Multiscreen setup or if they need to check again what other people can (not) see
