### ISSUE TITLE
IntegrityCheck failed

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6497]
NC: 22.2.2
Talk: 12.2.1

![image](https://user-images.githubusercontent.com/24530680/141644174-db6dca8f-2298-4523-9e80-d32b1b7830fb.png)

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- spreed-12-1-2
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid for required scope. (Requested: spreed-12-1-2, current: CN=spreed)

Raw output
==========
Array
(
    [spreed-12-1-2] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid for required scope. (Requested: spreed-12-1-2, current: CN=spreed)
                )

        )

)

**Comment by nickvergessen** [comment]
Works fine here with NC 22.2.2 and Talk 12.1.2

**Comment by jakobroehrl** [comment]
With NC23 + 13.0.0-rc.3 is no problem anymore
