### ISSUE TITLE
Web version does not show if message was read

### ISSUE THREAD

**Issue by m3dbedb** [nextcloud/spreed#6553]
### Steps to reproduce
1. Connect to next cloud via web browser (tested in firefox for linux)
2. Type a message in private message and public talk root
3. When correspondent using linux and firefox would read your message you will still see one recieved mark (as if the message send to server, not read by reciepent)

### Expected behaviour
When reciepent wold read my message I expect to see two read merks as it works when my message is read in chrome for windows.

### Actual behaviour
When I use nextcloud with linux and firefox I don't see when my messages are read by correspondents

### Server configuration

**Operating system:** linux (centos, debian)

**Web server:** linux

**Nextcloud version:** 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installation

**List of activated apps:** none

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
mozilla for centos 91.3.0esr (64-битный)
**Operating system:**
centos 7

**Comment by acsfer** [comment]
Transferred to @nextcloud/talk

**Comment by nickvergessen** [comment]
The double checkmarks appear when the message was read by everyone that has "Read privacy" set to public.

**Comment by m3dbedb** [comment]
> The double checkmarks appear when the message was read by everyone that has "Read privacy" set to public.

Neither regular user, nor admin may edit privacy of regular user. To see "Who has access to your data?" option you should be admin, and you may edit only your privacy. I suppose it is an issue.

**Comment by nickvergessen** [comment]
can you please add some screenshots? I'm failing to understand what you are talking about

**Comment by m3dbedb** [comment]
I mean delivery and read status. https://mashtips.com/get-whatsapp-message-delivery-read-status/ I ask for next cloud improvement to be able to see who have read your message in group chat like other solutions do. (You may see names of people who have read last message in group chat)
![cloudСнимок](https://user-images.githubusercontent.com/25632818/145046590-09e1ea00-29d0-4f51-8855-7f4ce7814680.JPG)

**Comment by m3dbedb** [comment]
> can you please add some screenshots? I'm failing to understand what you are talking about

I have replied in message above
