### ISSUE TITLE
Hover issues in top bar in call view

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#6561]
## Steps to reproduce
1. Start a call
2. Hover on the screen share icon
3. Hover on the audio and video icons

### Expected behaviour
Consistent behavior, either always a hover, or no hover, and aligned icons.

### Actual behaviour
Misaligned hover.
<img width="139" alt="image" src="https://user-images.githubusercontent.com/277525/142604557-c21044bd-35bb-4d69-ae32-6d095f155a06.png">

No hover on audio and video.

## Talk app

**Talk app version:** the one with NC 23 on c.nc.com

**Comment by nickvergessen** [comment]
Screenshare already fixed with #6552
Rest is in #5877
