### ISSUE TITLE
user count of a conversation on the wrong side?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6562]
Maybe the count should placed after "Teilnehmer":

see: https://github.com/nextcloud/spreed/pull/6409

![image](https://user-images.githubusercontent.com/24530680/142607539-2cc2cafe-dddc-4eae-a86e-3ef5b4bffb3f.png)

**Comment by nickvergessen** [comment]
Was a problem in the german translation:
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/spreed/338455902
Fixed it
