### ISSUE TITLE
Cannot scroll in conversation settings dialog

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#6572]
## Steps to reproduce
1. Create a new conversation
2. Open the settings dialog
3. Try scrolling down

### Expected behaviour
Can scroll

### Actual behaviour
Cannot scroll, the container seems broken.

## Talk app

**Talk app version:** the one from NC 23 on c.nc.com

**Comment by PVince81** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/277525/142632142-7d50877c-0f29-461a-8f1b-c6211129c770.png">

**Comment by PVince81** [comment]
this was in Firefox 94.0.1

**Comment by nickvergessen** [comment]
Works fine here with Firefox 94.0
Can you make sure to hard reload?

**Comment by PVince81** [comment]
right, after a hard reload it appears

there's one bug though: while the dialog is fading in, it still looks broken and without scrollbar, and once the fade in effect is finished, it is scrolled properly

so this makes this issue less critical

**Comment by nickvergessen** [comment]
> while the dialog is fading in, it still looks broken and without scrollbar, and once the fade in effect is finished, it is scrolled properly

That is a bug in `AppSettingsDialog` then and needs to be reported in the vue library
