### ISSUE TITLE
Talk not working between browsers but working between browser and mobile app

### ISSUE THREAD

**Issue by Ruchbah** [nextcloud/spreed#659]
All of the below happened on the same network.

## Steps to reproduce
1. User A with Firefox (or Opera), asks user B with Firefox (or Opera) to join call
2. User B with Firefox (or Opera) joins call
3. Users can chat but can't see or hear each other

## Works properly ONLY IF:
1. User A with Firefox (or Opera), asks user B with iOS app to join call
2. User B joins from iOS app
3. Everything ok

##  Browsers used:
1. Firefox
2. Opera

## NextCloud version
13.0.0

Any hint?

**Comment by Sesivany** [comment]
I'm experiencing the same behaviour.

**Comment by Ivansss** [comment]
Are User B with Firefox and User B with iOS app in the same network?

**Comment by Ruchbah** [comment]
They are all on the same network.

**Comment by Ivansss** [comment]
Interesting 🤔 
So I guess User A and User B are different Nextcloud users, right?
When using Firefox both users press "Join call" button?

**Comment by Ruchbah** [comment]
Different users, yes. 
And joint call, yes.

**Comment by Ivansss** [comment]
What FF version and OS are you using?

**Comment by jookk** [comment]
I can test this today evening

**Comment by Ruchbah** [comment]
OS: MacOS 10.13.3
Firefox: 59
Opera: 49
iOS: latest :)

**Comment by Ivansss** [comment]
I can't reproduce your issue 😞 
Could you please create a public call in your instance and post the link here?

**Comment by nickvergessen** [comment]
or send it to `ivan AT nextcloud.com`

**Comment by davidus05** [comment]
Same problem here.

**Comment by nickvergessen** [comment]
Closing due to the lack of feedback
