### ISSUE TITLE
Clicking a link scrolls to the latest message

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#6607]
## Steps to reproduce
1. Scroll back in chat history
2. Click a link

### Expected behaviour
The scroll position remains at the current position

### Actual behaviour
The scroll position jumps back to the most recent message

### Additional note

This does not happen when using the middle-mouse button to open in a new tab.

## Talk app

**Talk app version:** v13.0.0-rc.3 

## Browser

**Operating system:** Arch Linux

**Browser name:** Firefox

**Browser version:** 93

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/6769
