### ISSUE TITLE
Talk13: New permissions

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6610]
If I create a new chat group with these default permission for the participants:
![image](https://user-images.githubusercontent.com/24530680/143414710-62fabd90-1356-40f6-ba5e-f215ec66c04e.png)
Why could a user of this group can start a call?

**Comment by nickvergessen** [comment]
Moderators are excluded from the "default" permissions and can always start a call.

That being said, the initial population of the dialog seems to not work.

**Comment by jakobroehrl** [comment]
Tried it with a normal user, not with an admin.

> That being said, the initial population of the dialog seems to not work.

OK, this could clarifiy it.

**Comment by nickvergessen** [comment]
So the default permissions currently are XOXXX, so start call is actually granted, you just don't see it

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/spreed/pull/6612
