### ISSUE TITLE
Voice cannot be heard

### ISSUE THREAD

**Issue by HasanZahir1992** [nextcloud/spreed#6611]
**Is your feature request related to a problem? Please describe.**
While having a conversation, one of the users voice is not heard to other users in the middle of a meeting. This issue has happened multiple time on differrent users

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment]
Please provide more information, like the versions you used, the browsers, whether TURN, STUN and HPB server are defined, etc.
