### ISSUE TITLE
Call dose not refresh when leaving call

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#6619]
## Steps to reproduce
1. Both users join the call via talk app "ios, Android"
2.
3.

### Actual behaviour
I noticed regularly that when both users join a call via talk app ios or android i can be all the call for 3 to 4 hours when both users leave the call the talk via web still shows that that call is still on then i click on the call refresh the browser and then is says call ended and gives me how long the call is. 

This dose not happen if users are using the talk via web. Seems like the talk app is not sending a refresh that the call ended. I have not tested in on short calls only long calls. It also dose not happen if one user is using the web and one is using the mobile app. just seems to happen more when both users are using the mobile app. 

Sorry about the title didnt know how to properly name it 

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
	12.1.2
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

## Browser

**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
**Operating system**: Ubuntu/RedHat/...
Ubuntu 20.04 Server
**Web server:** Apache/Nginx
Apache2
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB 10.15
**PHP version:** 7.2/7.3/7.4
8.0
**Nextcloud Version:** (see admin page)
22.2.3

**Comment by andyxheli** [comment]
i tested it on a short call and it didn't happen. Only happens on very long calls.

**Comment by nickvergessen** [comment]
If it's not a bug in the server why report it there?

**Comment by andyxheli** [comment]
Well im not sure where the issue is. So if its not a bug what is it ?  Like the below image is says i left at 9:38AM but i actually left at 5:23AM like the first user i just launched the web portal and when to the talk conversation and then is showed that i left. 

![image](https://user-images.githubusercontent.com/59488153/143604359-78666524-b0f8-4995-a9fa-9697f1487627.png)
