### ISSUE TITLE
Notifications for group mentions should be explicit

### ISSUE THREAD

**Issue by Pytal** [nextcloud/spreed#6626]
## Steps to reproduce
1. Someone mentions @all/@here in one of your channels

### Expected behaviour
Receive a notification like "Bob mentioned everyone in conversation Group Chat"

### Actual behaviour
Receive the notification "Bob mentioned you in conversation Group Chat"

## Talk app

**Talk app version:** v12.1.2

**Comment by nickvergessen** [comment]
Since group mentions are only coming up soon ( #6340 ) lets not use that in the string for "all".

Maybe:
> Bob mentioned everyone in conversation Group Chat

?

**Comment by Pytal** [comment]
> Bob mentioned everyone in conversation Group Chat

💯

**Comment by Pytal** [comment]
> Bob mentioned everyone in conversation Group Chat

Yep, that works

**Comment by nickvergessen** [comment]
Wording has been further refined with the group mentions
