### ISSUE TITLE
Ability to change Microphone and Camera after initial selection

### ISSUE THREAD

**Issue by oberling** [nextcloud/spreed#6628]
**Is your feature request related to a problem? Please describe.**
I recently foud that after some updates now the Talk app tries to always find the last used video/microphone device. If it finds it it will use it without asking whether this device still should be used. Even after resetting permissions in browser, deleting cookies, all data, even reinstalling the browsers (Chrome and Firefox) it still insists on wanting permission for only and exactly those devices that once were chosen.

**Describe the solution you'd like**
Preferred solution: I'd like to be able to set my microphone/camera before the permission gets asked for by the browser.
Different solution I'd like: I'd like to be able to either set up in preferences of Talk/NextCloud account or which device to use.
Different solution I'd like: Restore the dropdown option available until Nextcloud 19-ish when having no permission yet.

**Describe alternatives you've considered**
I tried uninstalling/reinstalling two Browsers, clearing all data (cookies, browser history, cached data and the like). I also tried on two different machines with different OSes.
Different webpages utilizing the webcam give me drop-down-options to select the device from a list of devices when having no permission yet. This has been verified in two different tabs of the same browser-session. The problem should therefor definitely be located within NextCloud Talk App.

**Additional context**

**Code hints**
It seems to me that the problem is somewhere in some BrowserStorage not getting reset on login or whereever it should get reset [https://github.com/nextcloud/spreed/blob/master/src/utils/webrtc/MediaDevicesManager.js](https://github.com/nextcloud/spreed/blob/master/src/utils/webrtc/MediaDevicesManager.js).
I also tried in the console to `navigator.mediaDevices.enumerateDevices()` and sure enough this lists all my audio and video devices. Still the grant-permission dialog only shows one option for each device and no drop-down.

**Comment by nickvergessen** [comment]
With Nextcloud 23 a device selector will be shown after pressing the Join call button.
For older versions the device selection is available via the options menu in the call, or via the bottom left Talk settings menu at all times.
