### ISSUE TITLE
Media device fallback grabs camera on on first load even when not in call

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#6629]
## Steps to reproduce

1. Do a system update
2. Not sure what I did, I just switched through chats as I usually do
3. Be unlucky :four_leaf_clover: 
4. Check the camera LED
5. Act surprised :scream: 

See notes below for more background information as it contains possible clues.

### Expected behaviour
Camera doesn't turn itself on

### Actual behaviour
Camera is on.
Camera icon is visible on the left of the URL in the browser, which means that tab has opened it.

It doesn't happen any more after reloading the page.

## Talk app

**Talk app version:** the one from c.nc.com

## Browser

**Microphone available:** internal microphone and USB camera's microphone

**Camera available:** two cameras, one internal one and one USB

**Operating system:** openSUSE Tumbleweed 20211124

**Browser name:** Firefox

**Browser version:** 94.0.1

### Browser log

Selected snippets
```
Not connected to signaling server yet, defer joining room XXXXXX0346 signaling.js:1017:2
Connected 
open { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 31991, … }
signaling.js:636:2
Ignore unknown event 
Object { type: "bye", bye: {…} }
signaling.js:740:4
Close 
close { target: WebSocket, isTrusted: true, wasClean: false, code: 1005, reason: "", srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
signaling.js:666:2
Reconnecting socket as the connection was closed unexpected signaling.js:680:3
Reconnect in 983.613737597221 signaling.js:600:1
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
Connecting to wss://XXXXX.nextcloud.com/standalone-signaling/spreed for XXXXXX0346 signaling.js:626:1
Connected 
open { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 33551, … }
signaling.js:636:2
Hello response received 
Object { id: "1", type: "hello", hello: {…} }
signaling.js:907:1
Joined signaling.js:217:2
...
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 3 util.js:135:11
setVisualLastReadMessageId token=XXXXXX3462 id=XXXX96 3 MessagesList.vue:616
temporarymessage:  
Object { id: Getter & Setter, actorId: Getter & Setter, actorType: Getter & Setter, actorDisplayName: Getter & Setter, timestamp: Getter & Setter, systemMessage: Getter & Setter, messageType: Getter & Setter, message: Getter & Setter, messageParameters: Getter & Setter, token: Getter & Setter, … }
 uploadId XXXXXXXXX3030 fileUploadStore.js:231:3
Attempt to set a forbidden header was denied: Content-Length xhr.js:125:10
setVisualLastReadMessageId token=XXXXXX3462 id=XXXX96 2 MessagesList.vue:616
clearLastReadMessage because of isSticky token=XXXXXX3462 MessagesList.vue:702
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 6 util.js:135:11
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
Could not find previous video device, falling back to default/first device in the list XXXXXXXXXXXXXX3vPf/XXXXXXXXXXXXXXXXXXXXXzdE= 
Array(5) [ {…}, {…}, {…}, {…}, {…} ]
0: Object { deviceId: Getter & Setter, groupId: Getter & Setter, kind: Getter & Setter, … }
	__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
	deviceId: "kMLLle2dBzNqFa/OFeaP1uCLuOq40fG8SFK2Q4B6Ktk="
	fallbackLabel: "Camera 1"
	groupId: "cMlojBw+d3gcmGDxuJOFncO7f++adaVEdzTdYU6RMFQ="
	kind: "videoinput"
	label: "Video Capture 5"
	<get deviceId()>: function get()
	<set deviceId()>: function set(e)
	<get fallbackLabel()>: function get()
	<set fallbackLabel()>: function set(e)
	<get groupId()>: function get()
	<set groupId()>: function set(e)
	<get kind()>: function get()
	<set kind()>: function set(e)
	<get label()>: function get()
	<set label()>: function set(e)
	<prototype>: Object { … }
1: Object { deviceId: Getter & Setter, groupId: Getter & Setter, kind: Getter & Setter, … }
	__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
	deviceId: "sp4DVepaPSwCdXOS70sivqxD4TdqZ9jG4Md4ifel294="
	fallbackLabel: "Camera 2"
	groupId: "cMlojBw+d3gcmGDxuJOFncO7f++adaVEdzTdYU6RMFQ="
	kind: "videoinput"
	label: "Video Capture 5"
	<get deviceId()>: function get()
	<set deviceId()>: function set(e)
	<get fallbackLabel()>: function get()
	<set fallbackLabel()>: function set(e)
	<get groupId()>: function get()
	<set groupId()>: function set(e)
	<get kind()>: function get()
	<set kind()>: function set(e)
	<get label()>: function get()
	<set label()>: function set(e)
	<prototype>: Object { … }
2: Object { deviceId: Getter & Setter, groupId: Getter & Setter, kind: Getter & Setter, … }
	__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
	deviceId: "frR3TPOUE/rdTq4vU/I0G98kjkpboNIbOvfhUbderKo="
	fallbackLabel: "Microphone 1"
	groupId: "HL6yD5aAEpH8qeRcOHAvY5sgrPE28dqA7wJNCWLLEPI="
	kind: "audioinput"
	label: "Built-in Audio Analog Stereo"
	<get deviceId()>: function get()
	<set deviceId()>: function set(e)
	<get fallbackLabel()>: function get()
	<set fallbackLabel()>: function set(e)
	<get groupId()>: function get()
	<set groupId()>: function set(e)
	<get kind()>: function get()
	<set kind()>: function set(e)
	<get label()>: function get()
	<set label()>: function set(e)
	<prototype>: Object { … }
3: Object { deviceId: Getter & Setter, groupId: Getter & Setter, kind: Getter & Setter, … }
	__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
	deviceId: "+703jGJQOTR3m6ghOYPfKlXvaGg2TABGy1NNYYVKk3o="
	fallbackLabel: "Microphone 2"
	groupId: "2DYJyvQBaIxOQUl6XI1dFqJxxR8Zu41DirybEzp3EDQ="
	kind: "audioinput"
	label: "Webcam C270 Mono"
	<get deviceId()>: function get()
	<set deviceId()>: function set(e)
	<get fallbackLabel()>: function get()
	<set fallbackLabel()>: function set(e)
	<get groupId()>: function get()
	<set groupId()>: function set(e)
	<get kind()>: function get()
	<set kind()>: function set(e)
	<get label()>: function get()
	<set label()>: function set(e)
	<prototype>: Object { … }
4: Object { deviceId: Getter & Setter, groupId: Getter & Setter, kind: Getter & Setter, … }
	__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
	deviceId: "slFWV5Wch94y2xPiUL/9rbnMY91pCApVjK/9LliJbh8="
	fallbackLabel: "Microphone 3"
	groupId: "HL6yD5aAEpH8qeRcOHAvY5sgrPE28dqA7wJNCWLLEPI="
	kind: "audioinput"
	label: "Monitor of Built-in Audio Analog Stereo"
	<get deviceId()>: function get()
	<set deviceId()>: function set(e)
	<get fallbackLabel()>: function get()
	<set fallbackLabel()>: function set(e)
	<get groupId()>: function get()
	<set groupId()>: function set(e)
	<get kind()>: function get()
	<set kind()>: function set(e)
	<get label()>: function get()
	<set label()>: function set(e)
	<prototype>: Object { … }
	__ob__: Object { value: (5) […], dep: {…}, vmCount: 0 }
	length: 5
<prototype>: Object { … }
pop: function 20144()
push: function 20144()
reverse: function 20144()
shift: function 20144()
sort: function 20144()
splice: function 20144()
unshift: function 20144()
<prototype>: Array []
MediaDevicesManager.js:208:5
Leave room XXXXXX3462 signaling.js:1118:1
The request has been canceled 
```

If needed, I've got a saved copy of the full log locally (it's a bit much to anonymize everything).

## Server configuration

Server is c.nc.com

## Notes

The second camera is selected as the default one in the Talk settings.
Also: for some reason **both cameras appear as "Video capture 5"**, but can be switched properly (I might raise a separate issue for that), you can see this in the expanded array at the end of the log snippet above.

Going into the settings and switching the camera switched it off.

I wasn't able to reproduce this more than once, so perhaps it might be related to the order in which the blur background logic is getting initialized. 

### Background and theory

I was already on Talk and last Friday I did a system update. And today I only loaded Talk once at first.
Considering the message "Could not find previous video device, falling back to default/first device in the list" and also the weird "Video capture 5" labels, I suspect that Talk had a different video device id/name stored from the settings, but after the system update did not find it any more, so it tries to fall back to an existing one. And maybe the fallback logic itself caused the decide to get open ?

But why would it even bother touching the video device when I haven't joined any call ?
I suspect that the [background blur is initialized too early](https://github.com/nextcloud/spreed/issues/6443) and maybe is already trying to grab the device, and maybe the fallback code came in the way "let me open that for you".

It might be able to reproduce this by simulating a device name change to trigger the fallback logic.

Thoughts ? @danxuliu

**Comment by danxuliu** [comment]
> Also: for some reason both cameras appear as "Video capture 5", but can be switched properly (I might raise a separate issue for that), you can see this in the expanded array at the end of the log snippet above.

Please note that `Video capture` is not a string from Talk; this label comes from the browser/system. However, what could be a bug in Talk is that the label from one device is stored in a different one. To verify that, if you see the duplicated label in the settings, please run the following and check if the label is duplicated in the results too (the devices needs to be enumerated while a stream is active as that is the only time that it is guaranteed that the browser will return the label):
```
navigator.mediaDevices.getUserMedia({ video: true }).then(stream => {
    navigator.mediaDevices.enumerateDevices().then(devices => {
        console.log(devices)
        stream.getTracks().forEach(track => { track.stop() })
    })
})
```

> But why would it even bother touching the video device when I haven't joined any call ?

Good question :-P Did you open Talk settings by any chance? Or even "open", that is, double click on the settings, which would open the dialog and quickly close it again, maybe even before it was shown. I have been able to reproduce the issue that way; opening the dialog triggers getting the stream, but if it is closed too fast the streams are stopped... before being started, so once they are finally started the close routine was already applied and thus they are not closed.

**Comment by PVince81** [comment]
this is the result from the snippet while starting a call alone:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/277525/143871126-e12320ed-6424-44f8-82c6-ce9c09b1217d.png">

indeed it seems the label might be a glitch in my system, so perhaps we can ignore that until you think it will mess with the device states

this morning I didn't touch the settings at all

and just now when testing a call alone I had a state where the webcam was still being grabbed.
I did see a similar thing last week in the company call.

**Comment by PVince81** [comment]
regarding camera staying on after leaving the call, I've raised here: https://github.com/nextcloud/spreed/issues/6630

**Comment by nickvergessen** [comment]
So I can reproduce this with:

* Open settings
* See permissions requests of Browser popping up
* Close settings
* Grant permissions

**Comment by PVince81** [comment]
@nickvergessen yours is likely yet another issue

regarding the original issue, it happened to me again today after a reboot.
usually I have Firefox booting up on its own after logging in and the Talk page is open by default

I did not go to settings nor do anything camera related.

also this time the log doesn't contain anything related to fallback devices, only some lines related to loading the blur models

Log below:
<details>
ConsoleLogger.js:29:16
Connecting to wss://XXX.nextcloud.com/standalone-signaling/spreed for XXXXi2ju signaling.js:626:1
Not connected to signaling server yet, defer joining room XXXXi2ju signaling.js:1017:2
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Connected 
open { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 18625, … }
signaling.js:636:2
Ignore unknown event 
Object { type: "bye", bye: {…} }
signaling.js:740:4
Close 
close { target: WebSocket, isTrusted: true, wasClean: false, code: 1005, reason: "", srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
signaling.js:666:2
Reconnecting socket as the connection was closed unexpected signaling.js:680:3
Reconnect in 1152.7777213176792 signaling.js:600:1
Message to focus not found in DOM 938501 MessagesList.vue:800
Connecting to wss://s4.nextcloud.com/standalone-signaling/spreed for XXXXi2ju signaling.js:626:1
Connected 
open { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 20324, … }
signaling.js:636:2
Hello response received 
Object { id: "1", type: "hello", hello: {…} }
signaling.js:907:1
Joined signaling.js:217:2
Join room XXXXi2ju signaling.js:1048:1
Joined 
Object { id: "2", type: "room", room: {…} }
 XXXXi2ju signaling.js:1091:1
Users joined 
Array [ {…} ]
signaling.js:1161:3
Users joined 
Array [ {…} ]
signaling.js:1161:3
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
Users left 
Array [ "W9Bm9613kYvZKQeOLOMFo3hpVchc-mDHrnfsG_IYZRt8PT13TXBud1pYMEZqWFNUbkJwNkJuN2xHd2kzX3IwWG84T2RzU3B3X3ZKdmVmd1BfNVcwN1Vab3pYcGdvU3czT2djdThXSDU2TVRlUTdjX09GWGo5aFRyUmNzX1BGb1lxSk0zNVUwazNyTnhqWGI2Rmh1TjNHZFFhamtLMUw4TXhSTDBzRlpEQnNORXFtU0N5VGFxLWl6ZThDcG1DQ0h4NjNxUVNHZWZDdWV1SjRXRmJ8MTA1NzUyODM2MQ==" ]
signaling.js:1192:3
Room list event 
Object { type: "event", event: {…} }
signaling.js:1234:2
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
setVisualLastReadMessageId token=XXXXi2ju id=938501 MessagesList.vue:616
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
setVisualLastReadMessageId token=XXXXi2ju id=938501 MessagesList.vue:616
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:1:33588
Is MediaStreamTrack.dispatchEvent() supported?:  false MediaStreamTrack.js:71:3
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 11 util.js:135:11
setVisualLastReadMessageId token=XXXXi2ju id=938539 MessagesList.vue:616
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
Leave room XXXXi2ju signaling.js:1118:1
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:537
Left 
Object { id: "3", type: "room", room: {…} }
signaling.js:1125:2
Room list event 
Object { type: "event", event: {…} }
signaling.js:1234:2
Joined signaling.js:217:2
Join room YYYYYY5606 signaling.js:1048:1
Joined 
Object { id: "4", type: "room", room: {…} }
 YYYYYY5606 signaling.js:1091:1
Users joined 
Array [ {…} ]
signaling.js:1161:3
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Got notification data App.vue:289
Polling interval updated to 900000 App.vue:326
clearLastReadMessage because of isSticky token=YYYYYY5606 MessagesList.vue:702
setVisualLastReadMessageId token=YYYYYY5606 id=938565 4 MessagesList.vue:616
Users joined 
Array [ {…} ]
signaling.js:1161:3
Room list event 
Object { type: "event", event: {…} }
signaling.js:1234:2
Users left 
Array [ "FjkfYGxBgEe-QHFI8yVK9e0I1TmdR1iQJYBqNkGSbkh8PT1BLWlCbjRIVjRkWGtFR1JvUWxJMUE1c0lHM0d6SV9FT3Mtd3p4Rm9QQzV0cWtWNkl6aWtiZ2JMdFNQcUJzMnY3S05PV29CTk1tcWJKOFhUYklnazhRZ0Y5RENnN3kzQ2dmdUJ5X1dkYmlRSkY0NDdOOG5MT0ZVWDRXUG0xWDJybHBhalRSX3Z3TVdJSUd2NlQ2eVppdG9SanFhdUlwMjFwNzZla00zTFA2aXFmZmx8MjgwODUyODM2MQ==" ]
signaling.js:1192:3
setVisualLastReadMessageId token=YYYYYY5606 id=938565 9 MessagesList.vue:616
setVisualLastReadMessageId token=YYYYYY5606 id=938568 2 MessagesList.vue:616
OC.requestToken changed XXXXXXXXonvqZMarJ6x8Ely8qBzRXzpmhWizKXuCQ=:/xKxxzrzuDdf98AYBtcAgq1WiK/LvFeR/zI8yGD4iHI= index.js:321:9
setVisualLastReadMessageId token=YYYYYY5606 id=938568 2 MessagesList.vue:616
Room list event 
Object { type: "event", event: {…} }
signaling.js:1234:2
setVisualLastReadMessageId token=YYYYYY5606 id=938568 2 MessagesList.vue:616
No new notification data received App.vue:294
Polling interval updated to 900000 App.vue:326
</details>

**Comment by danxuliu** [comment]
> indeed it seems the label might be a glitch in my system, so perhaps we can ignore that until you think it will mess with the device states

It should not; the labels are stored just to show them to the user, but they are not used for anything else.

> @nickvergessen yours is likely yet another issue

Yes, it is the same as #6630, fix is in #6634

> regarding the original issue, it happened to me again today after a reboot.
> usually I have Firefox booting up on its own after logging in and the Talk page is open by default
>
> I did not go to settings nor do anything camera related.

It is so strange... The media streams are requested when the Talk settings or the device checker are shown, when a call is started and when an audio message is recorded. I wonder if Firefox booting up tries to recover the last page state and that somehow messes with the detection of the modal being open and ends requesting the stream. Currently I am quite lost, I am afraid :-)

> also this time the log doesn't contain anything related to fallback devices, only some lines related to loading the blur models

Note that the messages about fallback devices are shown when the device list is updated, not during the request of the streams (although the device list is updated after the streams are got). Therefore whether fallback devices are being used or not should not cause the issue. Similarly the background blur is initialized with the Talk settings and device checker dialogs, but the background blur itself does not trigger a media request, it just uses the video stream being given to it.

**Comment by PVince81** [comment]
the bug did not happen this morning when I booted and Firefox resumed this tab

but also my laptop was super slow for other reasons, so it might have prevented the suspected race condition

I'll keep an eye in the coming days and gather more information as I seem to be the only one with this issue so far

**Comment by PVince81** [comment]
this hasn't happened since after a few reboots and system updates

I'll close this for now as I seem to be the only one who had this issue, maybe it was an env specific problem that disappeared after updating the browsers
