### ISSUE TITLE
Nextcloud 23 Failed to send message to signaling server

### ISSUE THREAD

**Issue by apg1980** [nextcloud/spreed#6636]
NC 23
Mariadb 0.5.13
PHP 8.0.13
Ubuntu 20.04 LTS
Signaling 0.4.0

Talk is working fine, but got this messages after some times.

`{"reqId":"wU0yIsouLTXPPnPyofdO","level":3,"time":"2021-11-30T16:55:50+01:00","remoteAddr":"","user":"--","app":"spreed","method":"","url":"--","message":"Failed to send message to signaling server","userAgent":"--","version":"23.0.0.10","exception":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `POST https://mysignalingurlreplaced/standalone-signaling/api/v1/room/niot4uje` resulted in a `403 Forbidden` response:\nAuthentication check failed\n\n","Code":403,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":294,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":87,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":141,"function":"doRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php","line":269,"function":"backendRequest","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Signaling/Listener.php","line":171,"function":"roomDeleted","class":"OCA\\Talk\\Signaling\\BackendNotifier","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Talk\\Signaling\\{closure}","class":"OCA\\Talk\\Signaling\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Room.php","line":652,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php","line":121,"function":"deleteRoom","class":"OCA\\Talk\\Room","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php","line":116,"function":"doDeleteRoom","class":"OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php","line":90,"function":"deleteIfFileIsRemoved","class":"OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Manager.php","line":137,"function":"callback","class":"OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/BackgroundJob/RemoveEmptyRooms.php","line":72,"function":"forAllRooms","class":"OCA\\Talk\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Talk\\BackgroundJob\\RemoveEmptyRooms","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":63,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"CustomMessage":"Failed to send message to signaling server"},"id":"61a64a1237aef"}`

**Comment by nickvergessen** [comment]
Please check your signaling secret and configs
They seem to not match
