### ISSUE TITLE
Performance is bad while calling

### ISSUE THREAD

**Issue by davidus05** [nextcloud/spreed#665]
## Steps to reproduce
1. Invite users to call
2. Call and share your screen
3. Now do something in nextcloud

### Expected behaviour
The performance should be as good as before

### Actual behaviour
Nextcloud gets very slow, site load takes very long

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Firefox/Chrome

## Spreed app

**Spreed app version:** 3.1.0

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.21

**PHP version:** 7.0.25-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**List of activated apps:**

<details>
```
Enabled:
 - activity: 2.6.1
 - announcementcenter: 3.2.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - comments: 1.3.0
 - contacts: 2.1.0
 - dav: 1.4.6
 - deck: 0.3.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
```
</details>

**Comment by gurussia** [comment]
when i use spreed me it was very good, but then i see other program that you can choose your mobile internet connection and if your internet connection is slow, compression is little or much, this is the same as if nextcloud talk application put choose what compression to be, if you choose poor compression or poor bandwitch then to you something that can get speed and if is possible quality. davidus05 if your nextlcoud server is slow and if you have jabber client nextcloud, disable and try again. I tell you bcouse when i activate jabber nextcloud client nextcloud is working really slow, include it can wait 1 minute without do nothing, when i disable nextcloud jabber client nad write nextlcoud inemdiatelly work, php71 and php7.2 are really fast, but in php7.2 mcrypt is obsolete so it don't know how nextcloud will know that and will work

**Comment by nickvergessen** [comment]
Well it could also reach the limits of your server. Calling pings the server for each user continuously (for new chat messages and changes in the participant list).

**Comment by nickvergessen** [comment]
Closing as per above, because there is not a lot we can do against this.

**Comment by JohnWalkerx** [comment]
Few days ago I changed my server to fpm-fcgi (mpm_event) for http2.
After that I noticed the same problems. Also when one participant was in a spreed session (no other participants). Or just two participants in local network. Also connection failures. Web UI loads very slow. 
CPU load was not really high. Didn't see any heavy load. But I haven't done any major research.

After I switched back to mod_php (mpm_prefork) every works fine.
If someone facing the same issues, maybe this can help you.

Is this really a performance problem of my server? 🤔 

### Server Configuration
**Machine:** Intel NUC with Intel Celeron CPU J3455 4x @ 1.50GHz, RAM 8 GB, SSD 250 GB
**Operating system:** Linux 4.4.0-141-generic # 167-Ubuntu SMP
**Database:** mysql 5.7.24
**PHP version:** PHP 7.2.13-1
**Nextcloud version:** 15.0.0.10
**Spreed/Talk app version:** 5.0.0
