### ISSUE TITLE
User Volume | Screenshare with audio | adjust screenshare volume independently

### ISSUE THREAD

**Issue by DillFrescott** [nextcloud/spreed#6651]
**Is your feature request related to a problem? Please describe.**
Yes! I am unable to share audio with my screen, Unable to adjust volume of participants, and unable to independently adjust said screensharing volume.

**Describe the solution you'd like**
I would love these three things added to Talk!

**Describe alternatives you've considered**
Using other software.

**Additional context**
n/a

**Comment by nickvergessen** [comment]
Audio of screenshare is not available and you can find more details in the search for it.

The other topic is handled in #3155

**Comment by DillFrescott** [comment]
@nickvergessen I know it's not available, this is a feature request for it...

**Comment by nickvergessen** [comment]
See #3546
