### ISSUE TITLE
Adjust volume of each Participant.

### ISSUE THREAD

**Issue by DillFrescott** [nextcloud/spreed#6658]
**Is your feature request related to a problem? Please describe.**
Yes. Often times one friend is too loud or quiet compared to another friend.

**Describe the solution you'd like**
A simple volume slider for each person.

**Describe alternatives you've considered**
Using Discord

**Additional context**
n/a

**Comment by DillFrescott** [comment]
Sorry is a duplicate!

**Comment by pmarini-nc** [comment]
Hello @dillfrescott , what is the issue that this issue is duplicate of? Maybe this one: https://github.com/nextcloud/spreed/issues/3155?
