### ISSUE TITLE
Cannot install Talk on Nextcloud 13 after upgrade from NC 12.04

### ISSUE THREAD

**Issue by saigelosli** [nextcloud/spreed#666]
## Steps to reproduce
1. Click "Enable" button for Talk on Nextcloud app store

### Expected behaviour
I expect that the app should be enabled and activated.

### Actual behaviour
Get error message in red box which says: "An exception occurred while executing 'INSERT INTO `nc_talk_rooms` (`name`, `token`, `type`, `password`) VALUES(?, ?, ?, ?)' with params ["", "onrn", 3, ""]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'onrn' for key 'tr_room_token'"
App does not become active.

## Browser
Firefox 58.0.2 (64 bit)

**Microphone available:** Yes

**Camera available:** Yes

**Operating system:** Ubuntu 16.04.1

**Browser name:** Firefox

**Browser version:** 58.0.2 (64 bit)

### Browser log

<details>
</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache/Nginx
Apache 2.4.18

**Database:** MariaDB  Ver 15.1 Distrib 10.0.33-MariaDB

**PHP version:** 7.0.25-0ubuntu0.16.04.1

**Nextcloud Version:** 13.0

**List of activated apps:**

<details>
Enabled:
  - admin_notifications: 1.0.1
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - dicomviewer: 0.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ojsxc: 3.3.2
  - onlyoffice: 1.2.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - keeweb
  - spreed
  - spreedme
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.saigelosli.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "loglevel": 2,
        "singleuser": false,
        "updatechecker": false,
        "overwrite.cli.url": "http:\/\/cloud.saigelosli.com\/",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
</details>

### Server log (data/nextcloud.log)
<details>
{"reqId":"6per12vzFEeMZWf4MOTL","level":4,"time":"2018-02-16T02:24:31+00:00","remoteAddr":"192.168.201.27","user":"saige.losli","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/saige.losli\/2693843013\/00000002","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 10000000 got 5439488\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #9)\\n#1 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/apps\\\/dav\\\/lib\\\/Upload\\\/UploadFolder.php(39): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('00000002', Resource id #9)\\n#2 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Upload\\\\UploadFolder->createFile('00000002', Resource id #9)\\n#3 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('uploads\\\/saige.l...', Resource id #9, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/remote.php(164): require_once('\\\/var\\\/www\\\/hosts\\\/...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/hosts\\\/cloud.saigelosli.com\\\/docs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":178}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.0.14"}
{"reqId":"IooMIhyWYFncscMaewtO","level":3,"time":"2018-02-16T02:26:35+00:00","remoteAddr":"192.168.201.27","user":"saige.losli","app":"core","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"An exception occurred while executing 'INSERT INTO `nc_talk_rooms` (`name`, `token`, `type`, `password`) VALUES(?, ?, ?, ?)' with params [\"\", \"onrn\", 3, \"\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'onrn' for key 'tr_room_token'","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
</details>

**Comment by nickvergessen** [comment]
Sounds like you enabled it before.

Did you happen to restore a backup after a failed attempt?

**Comment by saigelosli** [comment]
Spreed was enabled before I upgraded from 12.04 -> 13.0. And I have been working on scripts to automate backup/restore, so the answer to your question is probably "yes". Only thing I am not sure about is the "failed attempt" part of the question.

1. What can I do to correct the problem now?
2. What do I need to do to ensure this doesn't happen in the future?

**Comment by nickvergessen** [comment]
Well the table which has the duplicate entry reported is new in Talk 3.0.
The data is copied over from the old table on update.

Basically this was done twice. The fix is to delete all oc_talk_* tables before doing a second attempt of the update.

So no, it won't appear in the future.

**Comment by saigelosli** [comment]
Taking your advice, I used the command-line tool "mysql" to remove the 3 tables in my structure that match your suggestion:

MariaDB [nextcloud]> DROP TABLE nc_talk_participants;
MariaDB [nextcloud]> DROP TABLE nc_talk_rooms;
MariaDB [nextcloud]> DROP TABLE nc_talk_signaling;

Now when I go back to the browser and try to install Talk again, it reports this error:

An exception occurred while executing 'SELECT `activity_id`, `object_id`, `subjectparams` FROM `nc_activity` WHERE (`app` = ?) AND (`type` = ?) AND (`object_type` = ?)' with params ["spreed", "spreed", "room"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_id' in 'field list'

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/672

**Comment by saigelosli** [comment]
After updating to 13.0.2, this is still a problem.
