### ISSUE TITLE
callback buttons

### ISSUE THREAD

**Issue by sheytan90** [nextcloud/spreed#6676]
Hello,

I wanted to create a bot to automatically send messages to a channel through the talk server.
This works fine, but I would need users to react to this messages.

Example:
Message: Do you want to attend?
Button_A: Yes
Button_B: No

So the bot can get a callback from the button click from the users. 

Hope you could add this.

Best regards,

Christian

**Comment by nickvergessen** [comment]
See #1879 #1027 and more
Currently not possible, but with webhooks and messages formatting we will also put something like call back buttons on the todo
