### ISSUE TITLE
Talk App showing an almost blank screen.

### ISSUE THREAD

**Issue by silver-gw** [nextcloud/spreed#668]
## Steps to reproduce
1. Upgraded NextCloud from v12.05 to v13.0 
2. Enabled Talk app

### Expected behaviour
Tell us what should happen
I am new to Talk app so I am not sure what the default behaviour should be and if the app needs any kind of configuration but I am guessing it should show some option to chat with contacts. I just installed the app out of the box and havent done any configuration on it.
### Actual behaviour
Tell us what happens instead
When I click on the Talk app icon, it shows the following screen https://ibb.co/hYvzT7 which is almost blank except for the mic and camera icons at the bottom.
## Browser

**Microphone available:** yes/no
I can see the icon
**Camera available:** yes/no
I can see the icon
**Operating system:** Windows/Ubuntu/...
FreeBSD
**Browser name:** Firefox/Chrome/...
FireFox and Chrome
**Browser version:** 50.1/55/...
Chrome 64.0 FF 58.0.2
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by cyBea** [comment]
I can confirm this.
My server is running 
- mariadb 10.1
- php 5.6.30
- apache 2.4.25

First I had the almost white page using firefox 58.0.2 and chromium 64.0.3282.140 using nextcloud 12.0.5 and talk 2.0.2

Then I updated to nextcloud 13.0.0 and talk 3.1 - The issue is now fixed for firefox but persists for chromium.

How can I get more information? Web server logs and nextcloud log didn't show anything related to this.

**Comment by Ivansss** [comment]
I think this is a duplicate of #633 
Do you use HTTPS connection?
This would make sense in @cyBea case, because FF doesn't require a HTTPS connection.

**Comment by cyBea** [comment]
I use https

Also now I checked error console in chromium:
```
JQMIGRATE: Migrate is installed, version 1.4.0
simplewebrtc.js:18007 Uncaught TypeError: Cannot read property 'on' of undefined
    at new SimpleWebRTC (simplewebrtc.js:18007)
    at Object.initWebRTC (webrtc.js:147)
    at n.onStart (app.js:489)
    at n.r [as triggerMethod] (trigger-method.js:32)
    at n.start (application.js:60)
    at HTMLDocument.<anonymous> (init.js:25)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Function.ready (jquery.js:3417)
    at HTMLDocument.I (jquery.js:3433)
<myserver.tld>/:1 EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.

DevTools failed to parse SourceMap: https://<myserver.tld>/apps/spreed/js/vendor/backbone.radio/build/backbone.radio.min.js.map
DevTools failed to parse SourceMap: https://<myserver.tld>/core/vendor/DOMPurify/dist/purify.min.js.map
DevTools failed to parse SourceMap: https://<myserver.tld>/core/vendor/blueimp-md5/js/md5.min.js.map
```

**Comment by Ivansss** [comment]
@cyBea Can you do a hard refresh on Chrome to be sure that it's not a cache issue?
Since we don't use EventSource any more...

**Comment by cyBea** [comment]
Thanks @Ivansss. Hard refresh (Ctrl+F5) fixed the Problem for me. (Restart chromium did not.)

**Comment by silver-gw** [comment]
@Ivansss Hi, I use https and a specific port on my NC and my desktop that does not actually have a mic or camera. But that shouldn't cause the blank screen I am getting. I did all kinds of hard refreshes on both Chrome and FF, tried the private window option. I even tried opening the app on a browser (SeaMonkey) I had never access NC from, in the past. No dice in all cases :(

**Comment by silver-gw** [comment]
This appears to be a limitation that the system must have mic and camera to be able to use this app. This seems to be many people's issue and therefore a duplicate. [#588](https://github.com/nextcloud/spreed/issues/588) [#538](https://github.com/nextcloud/spreed/issues/538)
