### ISSUE TITLE
Broadcast Audio while sharing Browser Tabs

### ISSUE THREAD

**Issue by LinuxTux23** [nextcloud/spreed#6680]
It would be very nice, if you could implement a function that allows users to broadcast the audio output of a Tab, like it is possible in Google Meets. (Screenshot)
On the NX-Help Website, I have found some old ticket, asking the same question. But reading this ticke there was not clear, if this feature is planned anyway in the near future.

I think this feature would be very nice to have, because then there is really no need to stick to Google Meets etc. when it comes to Video/Audio conferences.

[Nextcloud Help Ticket](https://help.nextcloud.com/t/talk-screensharing-with-audio-possible/96964)

[Stackoverflow Article](https://stackoverflow.com/questions/19382444/is-it-possible-broadcast-audio-with-screensharing-with-webrtc/61904043#61904043)

Screenshot from Google Meets:

![screenshot](https://user-images.githubusercontent.com/44779537/145305183-01bb40bc-deee-4658-9861-1c838708b088.png)

Happy to hear from you:

LinxuTux23

**Comment by nickvergessen** [comment]
This works since quite some time actually.
