### ISSUE TITLE
Sort participants in the callview based on more attributes

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6697]
### Current
FIFO

### Expected
* Permissions
* Joined with media

### Additional
To prevent constant resorting, we should add people at the front if the conversation is restricted and the new user has permissions and otherwise give it some delay after a resorting happened.

**Comment by nikola-gladovic** [comment]
I think we have 3 media: mobile, video, audio. how to sort those ? which media is top priority ?

**Comment by nickvergessen** [comment]
The most important bit would be to have people with any media/permission at the beginning

**Comment by nickvergessen** [comment]
Rightsidebar fixed in https://github.com/nextcloud/spreed/pull/6872
Actual call view is a bit more complicated

**Comment by nikola-gladovic** [comment]
@marcoambrosini 
Could you please explain about this ticket? 
What should we update more? :)

**Comment by marcoambrosini** [comment]
@nickvergessen could you explain exactly how you'd want it done?

**Comment by nickvergessen** [comment]
E.g. in the company call it's a bit weird when you have 3 pages of participants and people with permissions that could enable the mic/video are spread over all pages. It would make more sense if they are "at the beginning" so you have to paginate as little as possible. But then again it might also be okay to recommend the speaker view more
