### ISSUE TITLE
Show groups in dropdown, and omit yourself

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#67]
In the »Choose person« dropdown we should also show the groups you are part of, and omit yourself.

**Comment by nickvergessen** [comment]
@schiessle @rullzer I wonder if https://github.com/nextcloud/server/blob/6e52091c8e344cf0ea83ab44f79c550f139bb6ac/apps/files_sharing/lib/Controller/ShareesAPIController.php#L434-L436 should be registered also based on the itemType, so e.g. this spreed app can return users independent from the share manager.

I like the idea of having one endpoint for all these requests, but on the other hand it already starts getting messy a bit. Any though?

**Comment by rullzer** [comment]
mmmm I get your point @nickvergessen. Having yet another endpoint would hugely duplicate the code.

Possibility would be to filter based on the itemType indeed.

However, keep in mind that we search based share type. So the sharees have to properly fall into that category.

**Comment by nickvergessen** [comment]
Server was merged, groups are displayed and the current user is skipped => closing
