### ISSUE TITLE
Signaling event roomlist.update triggered too often?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6706]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

It's been some time that we removed the participant information from the room list end point, so this might be caused by legacy, but:

## Steps to reproduce
1. As user 1 create a room with many users
1. As user 2 create a one-to-one with user 1
1. As user 1 start a call in the room with many users
1. As user 1 open the console / network tab
1. As user 2:
    i. Join the one-to-one
    i. Wait 3 seconds
    i. Join the shared call
    i. Wait 3 seconds
    i. Join the one-to-one
    i. Wait 3 seconds
    i. Join the shared call

### Expected behaviour
As user 1 there was no actual reason to reload your room list

### Actual behaviour
As user 1 your room list is refreshed for each of the joins,
But none of the values in there actually changed
```json
{
  "type": "event",
  "event": {
    "target": "roomlist",
    "type": "update",
    "update": {
      "roomid": "m6turkvr",
      "properties": {
        "name": "Private conversation",
        "type": 2,
        "lobby-state": 0,
        "lobby-timer": null,
        "read-only": 0,
        "listable": 0,
        "active-since": {
          "date": "2021-12-14 15:07:05.000000",
          "timezone_type": 3,
          "timezone": "UTC"
        },
        "sip-enabled": 0
      }
    }
  }
}
{
  "type": "event",
  "event": {
    "target": "roomlist",
    "type": "update",
    "update": {
      "roomid": "5878504764",
      "properties": {
        "name": "Private conversation",
        "type": 1,
        "lobby-state": 0,
        "lobby-timer": null,
        "read-only": 0,
        "listable": 0,
        "active-since": null,
        "sip-enabled": 0
      }
    }
  }
}
```

## Talk app

**Talk app version:** master and 13.0.1

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Comment by nickvergessen** [comment]
@fancycode any clue when/how/where this is triggered?
I logged the requests we send to the signaling server and there is NO 
https://github.com/nextcloud/spreed/blob/4d2ecfcd96a6df7ed34bddd91dce2484a9750213/lib/Signaling/BackendNotifier.php#L240-L254
fired, so the update seems to be generated in the signaling server on it's own?

**Comment by nickvergessen** [comment]
Is it this part:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/7628a15e616d4dd1a1010278707e328bd614209e/backend_server.go#L575

**Comment by nickvergessen** [comment]
Indeed seems to be it, if I empty the alluserids arrays in invite and disinvite it vanishes:
https://github.com/nextcloud/spreed/blob/4d2ecfcd96a6df7ed34bddd91dce2484a9750213/lib/Signaling/BackendNotifier.php#L159-L196

In the case of an invite the user should reload the participant list, but not the room list anymore.

**Comment by nickvergessen** [comment]
Actually it comes from when a user disconnects from a room:
https://github.com/nextcloud/spreed/blob/5ac20349c6ff3c16a26bbdd1ecb3d6e9c773b9db/lib/Signaling/Listener.php#L209-L222

`$notifier->roomSessionsRemoved` is actually a `disinvite` event on the HPB:
https://github.com/nextcloud/spreed/blob/4d2ecfcd96a6df7ed34bddd91dce2484a9750213/lib/Signaling/BackendNotifier.php#L215-L224

And the HPB makes everyone reload their list:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/7628a15e616d4dd1a1010278707e328bd614209e/backend_server.go#L576-L578

**Comment by fancycode** [comment]
Actually that event is to update a single room in the list. The `target` is the `roomlist`, but it's for a single room:
https://github.com/strukturag/nextcloud-spreed-signaling/blob/7628a15e616d4dd1a1010278707e328bd614209e/backend_server.go#L349

In the past it was necessary to notify clients to update the room when a client was invited or removed (afaik to update the participant list). Is this no longer the case?

**Comment by nickvergessen** [comment]
> In the past it was necessary to notify clients to update the room when a client was invited or removed (afaik to update the participant list). Is this no longer the case?

Okay, then we should check for that roomId prop and differentiate the behaviour there on our side. As the participant list is not in the room list anymore that bit changed, so the meaning is "refresh your participant list of conversation X", but we by accident currently refresh the full room list which doesn't even contain the participants.

I just discovered a bug on the triggering side. A user disconnecting from a room triggers a disinvite event by accident. It should only happen when the participant was a guest or self-joined user. In a normal users case they will be offline afterwards but nothing changed.

**Comment by nickvergessen** [comment]
Yeah, so all fine with the HPB. We will adjust :)
