### ISSUE TITLE
Remove / sum call notifications up in Chats

### ISSUE THREAD

**Issue by dhuschde** [nextcloud/spreed#6712]
**Is your feature request related to a problem? Please describe.**
When you call someone, but it doesn't work immediately, it happens very quickly that the Chat is flooded with Call Notifications.

**Describe the solution you'd like**
Remove those Notifications after 1 hour for example

**Describe alternatives you've considered**
You could also sum them up, so there will only be one Call message

**Additional context**
![grafik](https://user-images.githubusercontent.com/85834680/146076560-cc76eb9c-a3fe-47e2-af35-d655d3bbe24a.png)

**Comment by nickvergessen** [comment]
Duplicate to this issue and the current target is in the comment:
https://github.com/nextcloud/spreed/issues/1148#issuecomment-992477832
