### ISSUE TITLE
Disabling blur disables video transmittion

### ISSUE THREAD

**Issue by DeepDiver1975** [nextcloud/spreed#6728]
## Steps to reproduce
1. Enable blur mode
2. Disable Blur mode

### Expected behaviour
Video should continue in un-blurred

### Actual behaviour
Video is completly disabled

## Talk app

**Talk app version:** 13.0.0

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no

**Custom STUN server configured:** no 

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Debian

**Browser name:** Firefox

**Browser version:** 95.0

### Browser log

<details>
![Screenshot from 2021-12-20 22-11-14](https://user-images.githubusercontent.com/1005065/146833325-60172641-8cc0-4996-a232-c02744be015c.png)

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** 23.0.0.10

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Huhu @DeepDiver1975 👋 =)

Can you try to update talk to 13.0.1
This should be fixed there with #6688 (see steps in #6687 And the linked issue)

**Comment by DeepDiver1975** [comment]
@PVince81 FYI

@nickvergessen thx. 👍

**Comment by PVince81** [comment]
seems to work fine in 13.0.1 now, thanks
