### ISSUE TITLE
Send message as a guest to public conversation

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/spreed#6736]
Hi! I am looking at how to send a message on behalf of a guest user to a conversation where guests are allowed to post. Cannot understand how to do it.

What is working for me is sending on behalf of a registered user:

`curl --data '{"token":"<roomid>","message":"hi there"}' -H "Content-Type: application/json" -H "Accept: application/json" -H "OCS-APIRequest: true" -H "Authorization: \"Basic ********=\"" -v -X POST https://mydomain.tld/ocs/v2.php/apps/spreed/api/v1/chat/<roomid>
`
If I am not providing credentials in curl, I am getting constantly getting 404 error.

I will be thankful for any help!

**Comment by nickvergessen** [comment]
You first need to join the room so you receive a session and then continue with that cookies

**Comment by ostasevych** [comment]
> You first need to join the room so you receive a session and then continue with that cookies

The thing is that when I poll the participants in the room, I see my guest user. So it's already joined.

So,

`curl -H "Content-Type: application/json" -H "Accept: application/json" -H "OCS-APIRequest: true" -v -X POST https://mydomain.tld/ocs/v2.php/apps/spreed/api/v4/room/7y9djgt4/<roomid>/active
`
followed by

`curl --data '{"token":"<roomid>","message":"hi there"}' -H "Content-Type: application/json" -H "Accept: application/json" -H "OCS-APIRequest: true" -v -X POST https://mydomain.tld/ocs/v2.php/apps/spreed/api/v1/chat/<roomid>
`
gives me 404 error.

Please, help me to create correct sequence to let a guest send messages.

**Comment by nickvergessen** [comment]
The first curl returns cookies which yoj need to send on the second curl

**Comment by ostasevych** [comment]
> The first curl returns cookies which yoj need to send on the second curl

I do not see cookies in the output. Here is, what I am getting:

```
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"id":625,"token":"<roomid>","type":3,"name":"<roomname>","displayName":"<roomname>","objectType":"","objectId":"","participantType":4,"participantFlags":null,"readOnly":0,"hasPassword":false,"hasCall":false,"canStartCall":true,"lastActivity":1640518259,"lastReadMessage":0,"unreadMessages":0,"unreadMention":false,"isFavorite":null,"canLeaveConversation":false,"canDeleteConversation":false,"notificationLevel":null,"lobbyState":0,"lobbyTimer":0,"lastPing":1640518481,"sessionId":"UMritgIbnlu0i5PkUrcDq6f36CwI9B4YPVCTE7xtI\/Aw5aNaFWrTgSEzjwAZ64US6lhAq6x5N+weosNITJEQGfzv6T0bfMsUuwPLVxUaEX7MfhDe\/MIZxcp+3smHvjCb9Bfc6YAZdpxDl6bMEyVR\/toipDkjuOJsDoXrKMTSiLcwuG6qeZKYX2lXxcE5Kiu53piN0cG5iTSs8pZW5P6WOH+SNkyjySjZe4IyZteHYXCy96uuMAY1qdaSdGbMlvv","lastMessage":{"id":33830,"token":"<roomid>","actorType":"users","actorId":"<username>","actorDisplayName":"<display_username>","timestamp":1640518259,"message":"hi {mention-call1}","messageParameters":{"men* Connection #0 to host nextcloud.forumzfd.de left intact
tion-call1":{"type":"call","id":"<roomid>","name":"<roomname>","call-type":"public"}},"systemMessage":"","messageType":"comment","isReplyable":true,"referenceId":""},"sipEnabled":0,"actorType":"guests","actorId":"30a1053a9ddf23be19cb897c849b1df62274d24d","attendeeId":622,"publishingPermissions":null,"canEnableSIP":false,"attendeePin":"","description":"Getting notifications from system devices in the Odesa forumZFD office","lastCommonReadMessage":0,"listable":0,"callFlag":0}}}
```

**Comment by nickvergessen** [comment]
http://stackoverflow.com/questions/30760213/ddg#37127263

This is really something you can just google.
Otherwise try to find help in the forums:
https://help.nextcloud.com

**Comment by ostasevych** [comment]
> http://stackoverflow.com/questions/30760213/ddg#37127263
> 
> This is really something you can just google. Otherwise try to find help in the forums: https://help.nextcloud.com

Thanks a lot for guiding. The thing is that it doesn't look like so elegant.... My goal is to send messages from different devices to a separate conversation to notify about various triggers. The devices usually do not have embedded tools to parse and analyse the responses, eg Mikrotok uses its cut fetch tool.

The conversation will be only one-way: from a device to the conversation channel. I was also thinking whether it is possible to use bot type to send these notifications? What do you think, does it make sense?
