### ISSUE TITLE
Button in create room dialogue hidden

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/spreed#6737]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a small screen and use Nextcloud/Talk.
2. Create a new Room in Talk.
3. Search the Button to create it.

### Expected behaviour
I can see/scroll for a button.

### Actual behaviour
I can't. Mouse scrolling is not working. I just can tab to the button.

![whereisthebutton](https://user-images.githubusercontent.com/34820982/147415823-2c3174dc-e1b4-44d6-855b-3bf61cf3e2b1.png)

Pretty similar to https://github.com/nextcloud/server/issues/29361 (other App and Nextcloud version thou).

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 13.0.1

## My side

Firefox 95.0.2
Windows

**Comment by nickvergessen** [comment]
@marcoambrosini you already knew it was hacky back then 😝 
Care to fix it?
https://github.com/nextcloud/spreed/blame/8fd61822eb5e1ce08ded115bffc82edecb74fc84/src/components/LeftSidebar/NewGroupConversation/NewGroupConversation.vue#L399-L404

**Comment by nickvergessen** [comment]
While on it, please also check all other Modals for problems with small height:
![Bildschirmfoto von 2022-01-04 11-56-44](https://user-images.githubusercontent.com/213943/148049062-b60cb64c-9eb3-43f8-8769-ff64ba1d957e.png)
