### ISSUE TITLE
Asterisk / star shown in window title if notifications are disabled

### ISSUE THREAD

**Issue by cm-schl** [nextcloud/spreed#6741]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set chat notification of some talk chat to "Off" (or "@-mentions only")
2. Open an other chat with someone in talk
3. When a message is received in the chat with notification set to "off" the browser window shows an asterisk / star in the window title (introduced with https://github.com/nextcloud/spreed/pull/2438)

### Expected behaviour
I think if a message is received in a chat where notifications are disabled, the indicator should not be visible.

### Actual behaviour
Indicator gets shown

As a Ferdi User (getferdi.com) the fact that the asterisk is shown in the window title is an important thing because in this way Ferdi can show an indicator that you've got a message in the actually open chat when the window is closed. So it would be a regression if the star wouldn't be shown if you got messages in the actually open chat.

But actually if the user disables the notifications of one chat the indicator of Ferdi (and so also the astersik in the window title) is shown because Talk ignores this settings. The fact that the asterisk generally exists is perfect and important for users using Nextcloud Talk. But it should follow the logic of the Nexcloud Notifications (little bell symbol).

## Talk app

**Talk app version:** 11.3.4

## Browser

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 91.4.1

**Comment by nickvergessen** [comment]
From my POV this is the desired behavior for a chat app.
It can be looked into together with #2195 but would make the feature pretty useless to me. I use the asterisk to see if there is something to read **because** I opted out of all notifications. I can not stay subscribed to all chats and have hundreds of phone vibrations just to be notified that someone wrote somewhere.
