### ISSUE TITLE
Support 1080p streams

### ISSUE THREAD

**Issue by LoveIsGrief** [nextcloud/spreed#6748]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

I have a physical 1080p camera that is only streaming in 1080p. I tried using the virtual camera from OBS and streaming my 1080p desktop through it, but it was also constrained to 720p. Only sharing the desktop directly sent a 1080p stream - I assume that the browser takes over in that regard and spreed/Talk doesn't have an influence when sharing the desktop.

**Describe the solution you'd like**

It would be great if 1080p (or higher) were **first** allowed / possible, **then** the user given an option to choose the quality they would like to stream in.

Step 1 is probably changing https://github.com/nextcloud/spreed/blob/4699421b92f9b943f1f423040db50647b24d4ed2/src/utils/webrtc/VideoConstrainer.js#L185

Step 2 is beyond me.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by nickvergessen** [comment]
We only set a ideal-height/width, not a maximum. We also already had problems with people that sent 1080p and 60 fps, so that is definetly working.

**Comment by LoveIsGrief** [comment]
I finally found out that nextcloud talk needs too much configuration and just switched to https://p2p.chat/ / https://github.com/tom-james-watson/p2p.chat . It was exactly what I was looking for and didn't slow down my nextcloud instance.
