### ISSUE TITLE
Cursor sometimes placed outside of chat input field and typing not possible

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#675]
I don’t know exactly how to reproduce, but it often happens that the cursor is floating outside of the chat input field (latest Firefox) and typing is not possible.

Looks like an issue with contenteditable or so, is that used there?

**Comment by nickvergessen** [comment]
Yeah happened to me too, not sure when and how it happened.

**Comment by danxuliu** [comment]
It looks like a Firefox bug to me.

Check this minimum test case I made: https://jsfiddle.net/0mrosteh/
- First click on the placeholder
- Then click on the white space to the right of the placeholder

In Firefox the cursor is moved to the right of the white space and typing is not possible; in Chromium the cursor stays in the placeholder and typing is possible.

**Comment by nickvergessen** [comment]
meh, anyway we can work around this?

**Comment by danxuliu** [comment]
None that I am aware of (I mean, maybe there is a way, but I have not found it when I tried to tweak the styles).

**Comment by nickvergessen** [comment]
Found https://stackoverflow.com/a/42170494 and it seems to be working
