### ISSUE TITLE
Contacts menu tooltip is not click-through

### ISSUE THREAD

**Issue by DerpgonCz** [nextcloud/spreed#6757]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open any Talk page
2. Click the People (or Contacts, dunno how to call it) icon top-right corner
3. Hover over any of the two action buttons next to any person
4. Observe blinking tooltip and no action on click
5. OPTIONAL: Hover over the bottom of the button, so the cursor is over the button but not over the tooltip. Then the button works.

### Expected behaviour
Clicking either button should perform the associated action (for Talk, start a conversation. For e-mail, not sure, it should open an e-mail client as the link is a `mailto:...`, but nothing happens).

### Actual behaviour
People menu closes, and either nothing happens, or nothing happens and tooltip stays open until page reloads or navigation happens.

## Talk app

**Talk app version:** 11.3.4

**Custom Signaling server configured:** no (also, the link here in the bug report template has double `/index.php/index.php`)

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows 10

**Browser name:** Chrome

**Browser version:** 97

### Browser log

<details>
```
No errors, warnings, or anything relevant.
```
</details>

## Server configuration detail

**Operating system:** Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 8.0.23

**PHP version:** 

7.4.19
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 21.0.1 - 21.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install

**Where did you install Nextcloud from:** Docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - apporder: 0.14.0
 - bruteforcesettings: 2.3.0
 - calendar: 3.0.4
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - drawio: 1.0.2
 - external: 3.8.2
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - integration_gitlab: 1.0.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.11.5
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.2.1
 - password_policy: 1.11.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 2.1.0
 - spreed: 11.3.4
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.14.2
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.10.0
 - timetracker: 0.0.72
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_ldap: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - photos

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.1.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpport": "587",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "overwriteprotocol": "https",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
cleanUpJobOffset: 0enabled: yesinstalled_version: 1.11.0s01_lastChange: 1641654864s01has_memberof_filter_support: 0s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: OXg4V0VKTDlWSFJ1RGVnUg==s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: ou=users,dc=***REMOVED SENSITIVE VALUE***,dc=czs01ldap_base_groups: ou=users,dc=***REMOVED SENSITIVE VALUE***,dc=czs01ldap_base_users: ou=users,dc=***REMOVED SENSITIVE VALUE***,dc=czs01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: cns01ldap_dn: cn=admin,dc=***REMOVED SENSITIVE VALUE***,dc=czs01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 1s01ldap_expert_username_attr: uids01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: employeeTypes01ldap_group_filter: (&(|(objectclass=inetOrgPerson)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: s01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: inetOrgPersons01ldap_host: ***REMOVED SENSITIVE VALUE***s01ldap_login_filter: (&(|(objectclass=inetOrgPerson))(|(mailPrimaryAddress=%uid)(mail=%uid)))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 0s01ldap_matching_rule_in_chain_state: unknowns01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: inetOrgPersons01ldap_userlist_filter: (|(objectclass=inetOrgPerson))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
No errors
```
</details>

<details><summary>Nextcloud log</summary>

```
Not applicable
```
</details>

<details><summary>Browser log</summary>
```
Not applicable
```
</details>

**Comment by DerpgonCz** [comment]
Current temporary fix:
```css
.tooltip {
    pointer-events: none;
}

**Comment by nickvergessen** [comment]
Please update Nextcloud to latest 21.0.x 
21.0.1 is heavily outdated
