### ISSUE TITLE
Talk call notification not shown in Firefox

### ISSUE THREAD

**Issue by pylorak** [nextcloud/spreed#6760]
When I am being called on Nextcloud Talk and I am logged in to my Nextcloud account in my browser (in my tests the Files page was open), I should get a notification about the call through the browser that I can see even if the browser window is minimized or in the background.

This currently works with Chrome but not with Firefox. I have verified that the website is not blocked from showing notifications in Firefox's settings.

Tested with:
Nextcloud 22.2.3
Talk 12.2.2
Firefox 95.0.2
Chromium 89.0.4389.90

**Comment by nickvergessen** [comment]
Works pretty fine here. Just make sure that the tab is not paused by Firefox (like when it comes back up after hibernate). But if you had it open and then switch to another tab it works just fine.
If not try clicking on the notification bell once (top right) and check if it asks for permissions to send notifications.

**Comment by pylorak** [comment]
> If not try clicking on the notification bell once (top right) and check if it asks for permissions to send notifications.

That was it, thanks! Why do I have to click on this bell in NextCloud first though? Is this the desired behavior in NC? I would expect the browser to ask me for permission right away when the first notifications would comes in, without having to click on anything in NextCloud. I don't think this is a browser limitation because other websites ask me for notification permission without having to click anywhere on the page first.

**Comment by nickvergessen** [comment]
> I would expect the browser to ask me for permission right away when the first notifications comes in, without having to click on anything in NextCloud

Browsers do not allow this anymore because too many websites abused this.

https://developer.mozilla.org/en-US/docs/Web/API/Notification#examples

> Note: In the above example we spawn notifications in response to a user gesture (clicking a button). This is not only best practice — you should not be spamming users with notifications they didn't agree to — but going forward browsers will explicitly disallow notifications not triggered in response to a user gesture. Firefox is already doing this from version 72, for example.

**Comment by pylorak** [comment]
I see. Double-thanks, also for the additional info.
