### ISSUE TITLE
Placeholders are overlapping for many users/small screens

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#677]
* have a call with some users
* actual: placeholders (users with no video) are overlapping each other and don't adjust their size
* expected: placeholders are responsive

![bildschirmfoto 2018-02-27 um 16 11 55](https://user-images.githubusercontent.com/245432/36744394-02d955d6-1bed-11e8-8add-49c176a54e11.png)
![bildschirmfoto 2018-02-27 um 16 12 00](https://user-images.githubusercontent.com/245432/36744395-0304d36e-1bed-11e8-91e2-131261d2b042.png)

cc @nextcloud/designers

**Comment by nickvergessen** [comment]
Actually this will be resolved by #1056

**Comment by MorrisJobke** [comment]
@nickvergessen Nice! Thanks 👍
