### ISSUE TITLE
Add button to 'test TURN settings'

### ISSUE THREAD

**Issue by brylie** [nextcloud/spreed#679]
When configuring a TURN server in Nextcloud Talk settings, there is little indication as to whether things are configured properly and working.

# Feature request
Add a 'test settings' button next to the TURN server configuration.

**Comment by morph027** [comment]
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

From https://blog.netways.de/2017/08/16/setting-up-a-turn-server-for-nextcloud-video-calls/:

> The field for “STUN or TURN URI” should look something like this:
> 
> ```
> turn:xxxxx.netways.de:443?transport=tcp
> ```
> 
> but you can also use the IP:
> 
> ```
> turn:185.XX.XXX.XXX:443?transport=tcp
> ```
> 
> adding the part “?transport=tcp” is important as I was not able to get my TURN server to respond without TCP only.
> Next click on “Gather candidates”.
> 
> What you would want as a result should look similar to this:
> 
> ```
> Time Component  Type Foundation Protocol    Address	 Port	         Priority
> 0.006	1	host	0	 UDP	10.0.10.144	60925	126 | 32512 | 255
> 0.009	1	host	1	 TCP	10.0.10.144	63376	125 | 32640 | 255
> 0.010	1	host	1	 TCP	10.0.10.144	9	125 | 32704 | 255
> 0.015	2	host	0	 UDP	10.0.10.144	47302	126 | 32512 | 254
> 0.016	2	host	1	 TCP	10.0.10.144	64892	125 | 32640 | 254
> 0.016	2	host	1	 TCP	10.0.10.144	9	125 | 32704 | 254
> 0.031	1	srflx	2	 TCP	XXX.XX.XX.XX	3362	 99 | 32607 | 255
> 0.051	2	srflx	2	 TCP	XXX.XX.XX.XX	3364	 99 | 32607 | 254
> 0.069	                                                                     Done
> ```
> 
> If you get a timeout with “Not reachable?” then probably a firewall is blocking the connection. Check again if the ports for the TURN server are open and if you can reach it externally via Telnet or something similar.

**Comment by brylie** [comment]
That page gives no results due to an authentication error, since it only has username/password fields:

![screenshot_20180303_103354](https://user-images.githubusercontent.com/17307/36932195-6e6aed12-1ece-11e8-81bb-428940fe2835.png)

Nextcloud Talk uses a shared secret, rather than username/password:

![screenshot_20180303_103653](https://user-images.githubusercontent.com/17307/36932219-df65ad2c-1ece-11e8-8fab-b5ac46031676.png)

How can I test the server using the *TURN server shared secret*?

**Comment by morph027** [comment]
Secrets are for session later, to gather candidates, it is enough.
First, select the google server, click "Remove Server", then enter your URL and click "Add Server", then "Gather canditates"...works for me.

**Comment by brylie** [comment]
OK, thanks. For some reason, the table wasn't being populated with info for me, and my server log had an authentication error.

In any case, the 'test TURN settings' button might be useful. It is a common practice when configuring remote services to have a 'test settings' button.
