### ISSUE TITLE
Fix video size in DeviceChecker

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6809]
![Bildschirmfoto von 2022-01-21 09-43-46](https://user-images.githubusercontent.com/213943/150495426-779e6904-f343-460d-a145-6bfbb37a3147.png)

Please create a follow up issue so we fix the video element size before the final, if we can't get a more medium sized modal

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/6772#issuecomment-1018299821_

**Comment by szaimen** [comment]
The small modal size was changed and 5.1.0 puvlished so should probably be possible to use that now...

**Comment by nickvergessen** [comment]
Fixed with that
