### ISSUE TITLE
Cannot leave screen share

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/spreed#6852]
### Steps to reproduce
1. Create a conversation with some users
2. Share your screen
3. Leave the screen sharing

### Expected behaviour
Screen share should disappear on every participants application

### Actual behaviour
Only the screen sharer can see his screen share disappear, other participants continue to have a fixed screenshot of the precedent screenshare. No way to close this screenshot. 

This seems to be a bug since Talk 13.0.2. Never noticed this behaviour before.
We use a signaling server and TURN and STUN on a different machine.

## Server configuration detail

**Operating system:** Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64

**Webserver:** Apache/2.4.48 (Debian) (apache2handler)

**Database:** mysql 10.5.12

**PHP version:** 

8.0.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 23.0.0 - 23.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - announcementcenter: 6.1.1
 - calendar: 3.0.5
 - circles: 23.0.0
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - deck: 1.6.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_automatedtagging: 1.13.0
 - files_linkeditor: 1.1.8
 - files_mindmap: 0.0.26
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - forms: 2.4.0
 - groupfolders: 11.1.2
 - impersonate: 1.10.0
 - issuetemplate: 0.7.0
 - keeweb: 0.6.8
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - notify_push: 0.3.0
 - oauth2: 1.11.0
 - onlyoffice: 7.3.0
 - password_policy: 1.13.0
 - passwords: 2022.1.20
 - photos: 1.5.0
 - polls: 3.4.2
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - spreed: 13.0.2
 - systemtags: 1.13.0
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.13.0
 - user_ldap: 1.13.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflow_script: 1.8.0
 - workflowengine: 2.5.0
Disabled:
 - appointments
 - bruteforcesettings
 - carnet
 - customproperties
 - emlviewer
 - encryption
 - files_external
 - firstrunwizard
 - mail
 - pdfdraw
 - privacy
 - rainloop
 - support
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.agglo-montbeliard.fr",
        "192.168.50.106",
        "192.168.50.106"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.agglo-montbeliard.fr\/",
    "dbtype": "mysql",
    "version": "23.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "theme": "",
    "loglevel": 0,
    "maintenance": false,
    "trashbin_retention_obligation": "auto, 15",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "appstore.experimental.enabled": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "25",
    "mysql.utf8mb4": true,
    "default_phone_region": "FR",
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "spreed",
        "files_mindmap",
        "pdfdraw",
        "issuetemplate"
    ],
    "allow_local_remote_servers": true,
    "default_language": "fr",
    "force_language": "fr",
    "default_locale": "fr_FR",
    "force_locale": "fr_FR",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis"
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 500background_sync_prefix: s01cleanUpJobOffset: 0enabled: yesinstalled_version: 1.13.0s01_lastChange: 1643289366s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: Q2VudDF4VmluZ3Q9MjAyMCE=s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: DC=pma,DC=locals01ldap_base_groups: ou=Organisation, DC=pma,DC=locals01ldap_base_users: DC=pma,DC=locals01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: adminsi@pma.locals01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 0s01ldap_expert_username_attr: sAMAccountNames01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=group)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: members01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: groups01ldap_host: 10.30.50.2s01ldap_login_filter: (&(&(|(objectclass=user)))(|(mailPrimaryAddress=%uid)(mail=%uid)))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 0s01ldap_matching_rule_in_chain_state: availables01ldap_nested_groups: 1s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: users01ldap_userlist_filter: (&(|(objectclass=user)))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
not relevant ?
```
</details>

<details><summary>Nextcloud log</summary>

```
not relevant ?
```
</details>

<details><summary>Browser log</summary>

JS Console when sharing de-sharing a screen : 

Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »).
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). moz-extension:71:796982
No OC found index.js:46:12
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
OCA.Comments.View initialized comments-app.js:32:8
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
L’utilisation des « Mutation Events » est obsolète. Utiliser « MutationObserver » à la place. listener.js:151:11
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
OCA.Viewer initialized Viewer.js:36:22
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:318
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Loading theming data for notification bell styling App.vue:138
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 3 globals.js:62:15
Registering notifications container as a menu App.vue:148
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Notifications permissions granted App.vue:366
Has notify_push enabled, slowing polling to 15 minutes App.vue:160
Polling interval updated to 900000 App.vue:326
Started background fetcher as session_keepalive is enabled App.vue:204
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 talk-main.js:2:3268173
Setting current user App.vue:330
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Detected browser Firefox 91 (91.0) AuthorAvatar.vue:1:557
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »). index.js:13:9
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »). index.js:13:9
session heartbeat polling started session-heartbeat.js:101:9
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
OCA.Sharing.ShareSearch not ready init-collections.js:42:10
OCA.Sharing.ShareSearch not ready init-collections.js:42:10
shim shim.js:1:9
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Got notification data App.vue:289
Polling interval updated to 900000 App.vue:326
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à eval (« script-src »).
X-Nextcloud-Talk-Hash initialised:  b5f25d9d5c2a848911a665c346970abb209fbe80 talkHashStore.js:78:3
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 116 globals.js:62:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:29:16
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »). moz-extension:22:42
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:2:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:2:33588
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 globals.js:62:15
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 38 globals.js:62:15
Message to focus not found in DOM 9770 MessagesList.vue:808
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 22 globals.js:62:15
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:537
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Connecting to wss://turn.agglo-montbeliard.fr/standalone-signaling/spreed for ixvez3bh signaling.js:626:1
Not connected to signaling server yet, defer joining room ixvez3bh signaling.js:1017:2
Connected 
open { target: WebSocket, isTrusted: true, srcElement: WebSocket, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, timeStamp: 17128, … }
signaling.js:636:2
Hello response received 
Object { id: "1", type: "hello", hello: {…} }
signaling.js:907:1
Joined signaling.js:217:2
Join room ixvez3bh signaling.js:1048:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Joined 
Object { id: "2", type: "room", room: {…} }
 ixvez3bh signaling.js:1091:1
Users joined 
Array [ {…} ]
signaling.js:1161:3
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 10 globals.js:62:15
true CallButton.vue:286
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 10 globals.js:62:15
Is MediaStreamTrack.dispatchEvent() supported?:  false MediaStreamTrack.js:71:3
Is MediaStream.dispatchEvent() supported?:  true MediaStream.js:85:3
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
false CallButton.vue:286
Joining call CallButton.vue:245
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 46 globals.js:62:15
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:537
The request has been canceled 
Object { message: "canceled" }
MessagesList.vue:537
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
[WASM] Loading model of size: 249792 talk-JitsiStreamBackgroundEffect.worker.worker.js:2:33588
INFO: Created TensorFlow Lite XNNPACK delegate for CPU. talk-JitsiStreamBackgroundEffect.worker.worker.js:2:33588
localMediaStarted webrtc.js:1366:2
WebRTC: Using more than two STUN/TURN servers slows down discovery 2 talk-main.js:2
WebRTC: Using five or more STUN/TURN servers causes problems talk-main.js:2
Peer created 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:1060:2
Enabling Simulcasting for Firefox (RID) peer.js:357:2
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Changed quality to 4 VideoConstrainer.js:118:3
Connecting own peer... 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:877:4
Connection established (own peer). 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:882:4
status datachannel is open webrtc.js:1419:2
simplewebrtc datachannel is open webrtc.js:1419:2
Stop waiting sound sounds.js:42:2
Playing join sound because of self joining sounds.js:105:3
Loading waiting sound sounds.js:56:3
Playing waiting sound sounds.js:62:2
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
L’utilisation de la méthode drawWindow de CanvasRenderingContext2D est obsolète. Utilisez l’API tabs.captureTab pour les extensions à la place https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab pagedata-script.js:1:12465
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
Playing waiting sound 2 sounds.js:76:3
Users joined 
Array [ {…} ]
signaling.js:1161:3
Playing waiting sound sounds.js:76:3
Stop waiting sound sounds.js:42:2
Playing waiting sound sounds.js:76:3
Uncaught TypeError: this.backgroundAudio is null
    backgroundInterval sounds.js:76
sounds.js:76:17
Request offer from fdOZCE3Ee-m97Y0P8EhDVx5OFuQ-s86jZyKcceO6sAt8Rl9NdGJjaDFrcnUxSlA2amhlU0I2QWZyM3Y2aGl1RjdNSWM3bmxzX1V3c2VEQXpOX3Z0S05CS3ZXOEU3N3FYdkZTVFp0X3VOcVdPZC1uTVA3eTJCQUFueWZhbTJDdDhZbGE2aUtGdEJTUTg2S01zN1dyaGxCaS00UmszQWNDUlhuMUJOTWVyaU12bHFxUEllRU1saVNpWGN6ekVqNGN6UUlJNXE4dkVndmdrWDNyMGN8ODI0MDQ2MzQ2MQ== signaling.js:1290:1
Stop waiting sound sounds.js:42:2
Playing join sound sounds.js:108:3
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
WebRTC: Using more than two STUN/TURN servers slows down discovery 2 talk-main.js:2
WebRTC: Using five or more STUN/TURN servers causes problems talk-main.js:2
Peer created 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:1060:2
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
Connecting to peer... 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:808:4
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
status datachannel is open webrtc.js:1419:2
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 globals.js:62:15
Connection established. 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:813:4
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
JanusDataChannel datachannel is open webrtc.js:1419:2
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 1 1 peer.js:461:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 16 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 globals.js:62:15
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
WebRTC: Using more than two STUN/TURN servers slows down discovery 2 talk-main.js:2
WebRTC: Using five or more STUN/TURN servers causes problems talk-main.js:2
Peer created 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:1060:2
Send offer to fdOZCE3Ee-m97Y0P8EhDVx5OFuQ-s86jZyKcceO6sAt8Rl9NdGJjaDFrcnUxSlA2amhlU0I2QWZyM3Y2aGl1RjdNSWM3bmxzX1V3c2VEQXpOX3Z0S05CS3ZXOEU3N3FYdkZTVFp0X3VOcVdPZC1uTVA3eTJCQUFueWZhbTJDdDhZbGE2aUtGdEJTUTg2S01zN1dyaGxCaS00UmszQWNDUlhuMUJOTWVyaU12bHFxUEllRU1saVNpWGN6ekVqNGN6UUlJNXE4dkVndmdrWDNyMGN8ODI0MDQ2MzQ2MQ== signaling.js:1319:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Simulcast stream not changed 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 1 1 peer.js:457:2
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 0 0 peer.js:461:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
isStripe:  true Grid.vue:524
stripeOpen:  false Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  808 Grid.vue:525
newGridWidth:  1404 newGridHeight:  808 Grid.vue:529
isStripe:  true Grid.vue:524
stripeOpen:  false Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  808 Grid.vue:525
newGridWidth:  1404 newGridHeight:  808 Grid.vue:529
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
Une chaîne vide a été transmise à « getElementById() ». 2 simplewebrtc.js:347:9
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 2 2 peer.js:461:1
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 1 1 peer.js:461:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
isStripe:  false Grid.vue:524
stripeOpen:  true Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  808 Grid.vue:525
newGridWidth:  1404 newGridHeight:  808 Grid.vue:529
isStripe:  false Grid.vue:524
stripeOpen:  true Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  808 Grid.vue:525
newGridWidth:  1404 newGridHeight:  808 Grid.vue:529
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 34 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 18 globals.js:62:15
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
WebRTC: Using more than two STUN/TURN servers slows down discovery talk-main.js:2
WebRTC: Using more than two STUN/TURN servers slows down discovery talk-main.js:2
WebRTC: Using five or more STUN/TURN servers causes problems talk-main.js:2
Peer created 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
webrtc.js:1060:2
Send offer to fdOZCE3Ee-m97Y0P8EhDVx5OFuQ-s86jZyKcceO6sAt8Rl9NdGJjaDFrcnUxSlA2amhlU0I2QWZyM3Y2aGl1RjdNSWM3bmxzX1V3c2VEQXpOX3Z0S05CS3ZXOEU3N3FYdkZTVFp0X3VOcVdPZC1uTVA3eTJCQUFueWZhbTJDdDhZbGE2aUtGdEJTUTg2S01zN1dyaGxCaS00UmszQWNDUlhuMUJOTWVyaU12bHFxUEllRU1saVNpWGN6ekVqNGN6UUlJNXE4dkVndmdrWDNyMGN8ODI0MDQ2MzQ2MQ== signaling.js:1319:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 8 globals.js:62:15
Simulcast stream not changed 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 1 1 peer.js:457:2
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 0 0 peer.js:461:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
isStripe:  true Grid.vue:524
stripeOpen:  false Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  413 Grid.vue:525
newGridWidth:  1404 newGridHeight:  413 Grid.vue:529
isStripe:  true Grid.vue:524
stripeOpen:  false Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  413 Grid.vue:525
newGridWidth:  1404 newGridHeight:  413 Grid.vue:529
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
Une chaîne vide a été transmise à « getElementById() ». simplewebrtc.js:347:9
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 2 2 peer.js:461:1
Changing simulcast stream 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
 1 1 peer.js:461:1
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
isStripe:  false Grid.vue:524
stripeOpen:  true Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  413 Grid.vue:525
newGridWidth:  1404 newGridHeight:  413 Grid.vue:529
isStripe:  false Grid.vue:524
stripeOpen:  true Grid.vue:524
previousGridWidth:  1404 previousGridHeight:  413 Grid.vue:525
newGridWidth:  1404 newGridHeight:  413 Grid.vue:529
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 14 globals.js:62:15
setVisualLastReadMessageId token=ixvez3bh id=10355 MessagesList.vue:624

</details>

**Comment by nickvergessen** [comment]
Fixed by #6856
