### ISSUE TITLE
overwrite / force notification settings of users as a moderator

### ISSUE THREAD

**Issue by mokkin** [nextcloud/spreed#6863]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Notification settings of new rooms are by default on "only @ mentions".
![grafik](https://user-images.githubusercontent.com/2938748/152504586-ad890241-0891-4bf4-b633-770f29eaf91c.png)

As a moderator of a channel sometimes it is very hard to "pull" users into conversations, as they never check their talk app. If they could notify their users about new messages it would help a lot.

**Describe the solution you'd like**
The default setting should remain on "@mentions only", but the moderator should be able to overwritte users settings for this channel.

**Describe alternatives you've considered**
Instead of permanently overwritting notification settings over user preferences, it could be an option to do that once the room was created or the user added. If then later the user decides to change notification level it could be on his own.

**Comment by SystemKeeper** [comment]
> If they could notify their users about new messages it would help a lot.

wouldn’t it be enough to just mention the room?

**Comment by mokkin** [comment]
That's a very good point!

I just didn't think about this possibility I have even used before. At the end that's all I wanted to achieve! Thank you for the hint.
