### ISSUE TITLE
Future planing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#687]
**Note:** this is not an exclusive list, but more a roadmap/planning/orientation for us employees of Nextcloud

## Priority
- [x] Chat in the mobile apps
  - [x] iOS @Ivansss  
  - [x] Android @mario 
- [x] Multi-Session support ~ @nickvergessen
- [x] Media-query stuff only on "Join call" ~ @nickvergessen
- [ ] Backend integration: MCU, SIP-Bridge, ext. Signaling

## Follow up
- [x] System chat messages (call started/participant joined) ~ @nickvergessen
- [ ] Safari support
- [ ] Edge support
- [ ] Search for chat messages
- [x] Unread chat message counter in room list

## Backlog
- [ ] Federation support
- [ ] Webinary features: Lobby, more calendar integration, presentation mode, user pins, recording
- [ ] Mini chat/call overlay windows
- [ ] Integration with other clients/systems: xmpp, rocketchat, signal, ...

**Comment by GoetheG** [comment]
@nickvergessen: Those are really great ideas you have. If you ware thinking about a chat function within the app, maybe tou should consider Rocket.Chat and its implemention into Nextcloud? You could save a lot of time I think. Take a look here:
github.com/nextcloud/server/issues/9023

**Comment by BornToBeRoot** [comment]
The possibility to chat with people (web/app) without having a microphone/webcam enabled.

![image](https://user-images.githubusercontent.com/16019165/38461742-8937f7fe-3ad8-11e8-8f9e-5044eb30ee6d.png)

Showing a hint is ok, but blocking the whole app, so you can't see chat messages/other people. This would also be great to make webcasts.

**Comment by GoetheG** [comment]
Ol. This sounds really good and also gets me thinking. If you work with open source code and plan on adding a chat function to the app. Rocket.Chat is also open source and famous. Maybe you both should get in touch? Then you shouldn’t invent it all over again and connect with a huge community.

**Comment by peterthomashorn** [comment]
Rocket.Chat+ is a completely different technology stack with Meteor. For sure it does not make sense wasting resources on reinventing the wheel but wouldn't the integration turn out only on the user interface level? Requiring a separate Rocket.Chat+ instance would complicate the setup and add other requirements to the target environment(s). AFAIK Node.js (base of Meteor) support is still lacking for plain web hosting services on which Nextcloud itself runs fine.

**Comment by nickvergessen** [comment]
Please keep this issue free from details, it's a meta/overview issues. Specific discussions should take place in the subtickets.

**Comment by jdinkel** [comment]
How about being able to send pictures and videos through chat?

**Comment by Bellusterra** [comment]
Carrying over the @“users” or @ “groups” from the Nextcloud user and circles app.

**Comment by msrovani** [comment]
A very professional feature would be to provide the room moderator with the ability to record the call in progress, storing it in its cloud, being able to make it available to the users who participated, or by file sharing after the end of the call.

**Comment by nickvergessen** [comment]
Well the thing is we don't know for sure yet.

It was started as a video conferencing tool and that is what the most development power went into so far. One part of that is also to have the possibility to chat.
#875 clearly shows that some people don't want to use it as a conferencing tool (where mention notifications are enough), but want to use it to replace whatsapp or whatever.

**Comment by BornToBeRoot** [comment]
1) A Windows app would also be great... 
To send short messages to colleagues as replacement to e-mail. 

2) Code highlighting to send for e.g. PowerShell commands.

**Comment by nickvergessen** [comment]
Follow up is being handled in https://github.com/nextcloud/spreed/projects/1

**Comment by eutampieri** [comment]
How is the SIP integration going?

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+MCU+%26+SIP%22

**Comment by eutampieri** [comment]
I see… thanks

Eugenio Tampieri
