### ISSUE TITLE
Echoing call, clearly hearing myself from the other side.

### ISSUE THREAD

**Issue by Byter3** [nextcloud/spreed#6887]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Make a call

### Expected behaviour
A call without echo

### Actual behaviour
For some reason some time the call is okay. But other times on the same device in the same enviroment the call is echoing, almost clearly hearing myself from the other side mic's. Mazbe some timing error? It happens on all the devices from android to ios, to different browsers. I would understand it if a not correctlz position mic picks up, the out coming audio, from a laptop or a pc. But most of the modern times this shouldnt happen even in the worst enviroment, specially not on a cell phone, where everything is built in....

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser firefox/edge

**Microphone available:** yes

**Camera available:** yes

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.4

**Nextcloud Version: 21.0.7

**List of activated apps:**

**Nextcloud configuration:**
Talk 11.3.3

**Comment by nickvergessen** [comment]
Browsers currently do echo cancellation, etc and people are always asking for us to allow turning it off.
So not sure what the issue is here

**Comment by Byter3** [comment]
Hey!
I managed to setup the high performance backend finally and the echoing problem went away, so I still think this was some timing issue between the clients. Anyways as I said, the Signaling server solved it.

**Comment by michel-thomas** [comment]
Hello @Byter3 
How did you manage this issue? What has been done to solve your problem, only using a Signaling server? Or some other operation?
Thanks
