### ISSUE TITLE
When in a call, reduce action menus from 2 to 1

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#6889]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When in a call, there are 2 menus, the "More actions" 3-dot icon and the settings gearwheel. While the logic is that "More actions" only shows the actions relevant for inside the call, it creates confusion as to where to find what:
![Current in call menu](https://user-images.githubusercontent.com/925062/153197959-ed743909-ed2b-4c79-9359-5acb09dcb8b2.gif)

**Describe the solution you'd like**
It would be no issue to combine both menus:
![Combined menu](https://user-images.githubusercontent.com/925062/153197963-e8f98333-fc9e-403d-9e0e-4f66510f21eb.png)
(Note that "Rename conversation" should be done via conversation settings and doesn’t need to be in that action menu.)

**Comment by nickvergessen** [comment]
I think device settings should be further at the top.

My suggestion would be:
- Raise
- Blur
- Device
---
(divider here looks good I think)
- Grid
- Full
---
- Copy
- Convo settings

**Comment by jancborchardt** [comment]
@nickvergessen That order sounds good to me as well, no particular preferences. :)

**Comment by jancborchardt** [comment]
Related to that, when you join a conversation link as guest, the "Device settings" are in the sidebar only, and only as "Settings" → we should move those into the main settings menu (next to "Start call") as well to reduce confusion:
![Device settings on call link](https://user-images.githubusercontent.com/925062/156337461-757a8659-1877-4feb-ba80-80461867e4a6.png)
