### ISSUE TITLE
no video from other displayed on android talk app but both visible on web

### ISSUE THREAD

**Issue by rwb99** [nextcloud/spreed#6891]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. use the android talk app
2. call another account
3. no video displayed on android talk app but working via the web interface

### Expected behaviour
Tell us what should happen
be able to see the other persons video from the android talk app
### Actual behaviour
Tell us what happens instead
only seeing my own video from android app but can see both video from web interface from other client
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
13.0.3 (web) 13.0.0 (android newest)
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
yes e4214eb95dee09d564c71227eb554f3084a726d4
**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
yes

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
windows
**Browser name:** Firefox/Chrome/...
chrome
**Browser version:** 85/96/...
97.0.4692.99
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu 20.04
**Web server:** Apache/Nginx
Nginx 1.18.0
**Database:** MySQL/Maria/SQLite/PostgreSQL
PostgreSQL 23.0.0.10
**PHP version:** 7.4/8.0/8.1
8.0
**Nextcloud Version:** (see admin page)
23.0.0
**List of activated apps:**
 - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.14.0
  - breezedark: 23.2.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_automatedtagging: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - talk_matterbridge: 1.23.2
  - talk_simple_poll: 1.3.1
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - circles
  - dashboard
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - password_policy
  - user_ldap
  - weather_status
<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "rb99.club"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/rb99.club",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "defaultapp": "spreed"
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
n/a
```
</details>

**Comment by rwb99** [comment]
https://github.com/nextcloud/talk-android/issues/936#issuecomment-1034110607

**Comment by rfc2822** [comment]
I have the same problem. It helps to completely close Firefox and then call again.

**Comment by nickvergessen** [comment]
Sounds like you are either missing a stun/turn server or the configuration does not work correctly.

At least there is not a generic bug between those components at the moment.
