### ISSUE TITLE
Pasword protection confirm button misplaced

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#691]
![screen shot 2018-03-08 at 14 13 23](https://user-images.githubusercontent.com/4638605/37152896-24ae9884-22db-11e8-9c50-9a96114b6822.png)

**Comment by nickvergessen** [comment]
are you sure it's 13 and not master?

**Comment by Ivansss** [comment]
I can reproduce it in stable13

**Comment by nickvergessen** [comment]
@skjnldsv can you fix this as trade for the reviews yesterday? It's in master and stable13

**Comment by skjnldsv** [comment]
The authenticate css is not loaded event if it's being injected by the proper function... Investigation in progress...
:construction:  :policeman: :oncoming_police_car: :construction:
