### ISSUE TITLE
Send an e-mail if a conversation is unread after a set amount of time

### ISSUE THREAD

**Issue by synlic** [nextcloud/spreed#6916]
---

**Is your feature request related to a problem? Please describe.**
Many users that I work together with on Nextcloud only opens the webapp a few times each month, and don't have the Talk app installed on their phones. This means that messages sent from Talk is often missed for several days/weeks. 

It would be nice if Talk could send an e-mail if a messages is left unread for a set amout of time.

**Describe the solution you'd like**
In the Activities Settings in Nextcloud, add a option that you should receive a e-mail if a messages in Talk is unread for X amout of hours/days. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nickvergessen** [comment]
So if you mention them the should get a notification. Since Nextcloud 23 notifications will be sent via email after a given timeout:
https://github.com/nextcloud/notifications/pull/1074

I think that has to be enough.

**Comment by synlic** [comment]
Ah, great! 

I'll have to upgrade to 23 and check it out. Thanks!
