### ISSUE TITLE
Disappearing Messages

### ISSUE THREAD

**Issue by shashank-brdj** [nextcloud/spreed#6920]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
I would want certain chats/discussion forums to clear chats after a stipulated time. It's frustrating to do "delete chat" manually.
It would also provide privacy for certain chat forums which can be controlled by admin of the group.
It would even help even one to one communications to remain secure. 

**Describe the solution you'd like**
Kindly provide, disappearing messages as a feature. Make it a toggle which can be used by the group moderators.

**Describe alternatives you've considered**
I have tried using "delete chat messages" and its not much of a fix. Doing it all the time is quite tedious
and impractical.

**Additional context**
Since Next Cloud Talk has been developed in a sophisticated manner, it would be ideal if it had an essential feature like other chat platforms. Kindly bring Disappearing messages.

**Comment by nickvergessen** [comment]
Expiring messages have been implemented
https://github.com/nextcloud/spreed/issues/7359
