### ISSUE TITLE
Safari 13 Blank page

### ISSUE THREAD

**Issue by TommySchwartz** [nextcloud/spreed#6942]
Hi!
I'm not a developer or programmer so go easy on me, tried my best to fill out the form.
I know similar subject has been up about a year ago and was resolved back then.
Spreed/talk states at github page to support Safari 12 and above, is this support dropped on purpose with spreed/talk 13 or is it a bug?

Edit:
Same install works with Safari 14.

First noticed this with my docker setup on Intel NUC, but is reproducible with fresh Nextcloud VM from official site.

Regards
Tommy

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Working with Nextcloud 22.5.2 and Talk 12.2.3
2. Update to Nextcloud 23.0.2 and Talk 13.0.3
3. 

### Expected behaviour
Talk app GUI
### Actual behaviour
Blank/white page. Only blue Nextcloud menu bar visible.
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
13.0.3

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
No

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
No

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
No

## Browser

**Microphone available:** yes/no
No popup asking (cleared settings and cache)

**Camera available:** yes/no
No popup asking (cleared settings and cache)

**Operating system:** Windows/Ubuntu/...
MacOS - High Sierra

**Browser name:** Firefox/Chrome/...
Safari

**Browser version:** 85/96/...
13.1.2 (same behavior on 2 computers)

### Browser log

<details>

Console log:
[Error] SyntaxError: Invalid character '\ud835'
	(anonym funktion) (viewer-main.js:2)
[Error] SyntaxError: Invalid character '\ud835'
	(anonym funktion) (talk-main.js:2)
[Error] Viewer app is not installed
	(anonym funktion) (text-viewer.js:2:35158)
[Error] TypeError: undefined is not an object (evaluating 'OCA.Viewer.registerHandler')
	(anonym funktion) (files_pdfviewer-main.js:2:23593)

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Official Nextcloud VM (2022-02-26)
-Ubuntu 12.9-0ubuntu0.20.04.1 (after apt update && upgrade)
-Linux 5.4.0-100-generic x86_64 (after apt update && upgrade)

**Web server:** Apache/Nginx
Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL
PostgreSQL 12.9

**PHP version:** 7.4/8.0/8.1
7.4.3

**Nextcloud Version:** (see admin page)
23.0.2

**List of activated apps:**
Only Talk (fresh install of Nextcloud)

<details>

Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.2
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.105",
            "nextcloud",
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/nextcloud\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "logtimezone": "Etc\/UTC",
        "maintenance": false,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "app_install_overwrite": [
            "spreed"
        ]
    }
}
</details>

### Server log (data/nextcloud.log)
<details>

Cleared log file and tried to login and navigate to Talk, but nothing in logfile is generated.

</details>

**Comment by nickvergessen** [comment]
Works fine here on the iPad.
Did you install the update via the appstore?

**Comment by TommySchwartz** [comment]
Is your iPad running Safari 13?

sudo apt update && upgrade through console.
Then update Nextcloud through Nextcloud admin pages.
Lastly update the talk app through the Nextcloud appstore.

Working fine with:
Firefox 97 (Win & macOS & Ubuntu & Android/LineageOS)
Talk app 13 (Android/LineageOS & iOS) 
Edge 98 (Win)
Safari 14 (macOS Catalina)
Safari ? (iOS 15)

Does not work with Safari 13 (macOS High Sierra).

I think a very(!) high number of Mac's is stuck with Safari 13 / High Sierra because apple dropped support for many older gpus missing Metal api in the drivers.

**Comment by nickvergessen** [comment]
We include all browsers with a marketshare `>0.25%`
https://github.com/nextcloud/browserslist-config/blob/master/browserlist.config.js#L2-L6

Especially with WebRTC technology it is not really easy to support much older browsers. The requirements and specs are still changing.
