### ISSUE TITLE
There was an error loading your contacts

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/spreed#695]
## Steps to reproduce
1. Install Talk to NC13 with LDAP auth
2. click on contact icon near profile picture

### Expected behaviour
Your own contacts list appears

### Actual behaviour
No contacts list appears, message "There was an error loading your contacts" appears 

## Browser
Chrome and Firefox

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 16.04

**Browser name:** Firefox/Chrome

**Browser version:** FF 58.0.2, Chrome 64.0.3282.186

### Browser log

There was an error loading your contacts 
Object { readyState: 4, getResponseHeader: getResponseHeader(), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(), overrideMimeType: overrideMimeType(), statusCode: statusCode(), abort: abort(), state: state(), always: always(), then: then(), … }

## Spreed app

**Spreed app version:** 3.1.0

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** MySQL 14.14

**PHP version:** 7.0

**Nextcloud Version:** 13.0.0

**List of activated apps:**

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - audioplayer: 2.2.5
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - caniupdate: 0.1.2
  - cms_pico: 0.9.7
  - comments: 1.3.0
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - drop_account: 0.0.7
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_linkeditor: 1.0.4
  - files_markdown: 2.0.4
  - files_opds: 0.8.8
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.2
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.2.0
  - ownbackup: 17.5.0
  - password_policy: 1.3.0
  - piwik: 0.3.2
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - registration: 0.4.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.1.0
  - spreedme: 0.3.11
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - richdocuments
  - user_external

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/box.intre.it",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "logdateformat": "r",
        "logtimezone": "Europe\/Rome",
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "box.intre.it"
        ],
        "forcessl": true,
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "appstore.experimental.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Epub",
            "OC\\Preview\\FB2",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "trashbin_retention_obligation": "auto, 180",
        "updatechecker": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": true,
        "onlyoffice": {
            "jwt_header": "AuthorizationJwt"
        }
    }
}

### Server log (data/nextcloud.log)

{"reqId":"8Xa68o97yCNqcA3bWpQ6","level":3,"time":"Thu, 08 Mar 2018 20:35:12 +0100","remoteAddr":"192.168.5.157","user":"prc","app":"index","method":"POST","url":"\/index.php\/contactsmenu\/contacts","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getUID() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Contacts\\\/ContactsMenu\\\/Manager.php(106): OCA\\\\Spreed\\\\ContactsMenu\\\\Providers\\\\CallProvider->process(Object(OC\\\\Contacts\\\\ContactsMenu\\\\Entry))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Contacts\\\/ContactsMenu\\\/Manager.php(63): OC\\\\Contacts\\\\ContactsMenu\\\\Manager->processEntries(Array, Object(OC\\\\User\\\\User))\\n#2 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/ContactsMenuController.php(61): OC\\\\Contacts\\\\ContactsMenu\\\\Manager->getEntries(Object(OC\\\\User\\\\User), NULL)\\n#3 [internal function]: OC\\\\Core\\\\Controller\\\\ContactsMenuController->index(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\ContactsMenuController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\ContactsMenuController), 'index')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/contactsmenu\\\/c...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/spreed\\\/lib\\\/ContactsMenu\\\/Providers\\\/CallProvider.php\",\"Line\":86}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}

**Comment by Ivansss** [comment]
This problem was fixed in #685. Next Talk release will include this bugfix.
Thanks for the report :)
