### ISSUE TITLE
layout in browser on mobile/portrait

### ISSUE THREAD

**Issue by q-ki** [nextcloud/spreed#6957]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Hi there. 

If you make an invitation for a non-nc-registered person for a conversation, this person will use the browser to join this conversation. If this happens with a smartphone in portrait orientation it will end up in a messed up screen. It looks good if you close the details tab or turn the phone into landscape-orientation. But the portrait-orientation-css could use a bit more love or the details-tab should be closed at the start by default.

Thanks a lot ...
Cheers ...
qki

**Comment by nickvergessen** [comment]
Closing in favor of https://github.com/nextcloud/spreed/issues/6969
