### ISSUE TITLE
Flip horizontally 

### ISSUE THREAD

**Issue by q-ki** [nextcloud/spreed#6960]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Hi there.

Using any SmartphoneAsWebcam-Software(1) or OBS-Virtual-Cam(2) as video-source in talk leads to a horizontally flipped image.
Flipping only the camera-source in (1) or (2) to counteract this is easy. But when using OBS I have to flip my whole scene-layout and then have no correct preview of my actions in the software anymore.  

**Describe the solution you'd like**
A simple mirror/flip horizontally function in the talk-camera-settings would be awesome! 

Thanks a lot ...
Cheers ...
qki

**Comment by nickvergessen** [comment]
The video is only flipped for you so you see it as a mirror 🪞

Cc @jancborchardt

**Comment by q-ki** [comment]
Thanks man ! 

I like easy solutions ;-) 

Case closed.
