### ISSUE TITLE
Unable to delete shared files or Deck cards in conversations

### ISSUE THREAD

**Issue by mokazemi** [nextcloud/spreed#6990]
## Steps to reproduce
1. Send a **file** (share it) or a **deck card** in a conversation
2. Try to delete it.
3. There's no option to delete!

### Expected behaviour
User should be able to delete any messages.

### Actual behaviour
There's no option to delete these kind of messages. 
![image](https://user-images.githubusercontent.com/18334056/157913884-20b28fb7-3ebd-4146-8697-a3dcedc48981.png)

**Talk app version:** 13.0.3

**Nextcloud Version:** 23.0.2

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/pull/7047
