### ISSUE TITLE
Video is about 5 secs delayed

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6998]
I had 2 1:1 calls in the last days.
In every call the audio and video qualitiy was quite good, but the video was about 5 secs delayed.

Latest NC versions with Talk HPB

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/issues/6804 ?
Anyway very unlikely something in Talk or something we could fix in Talk

**Comment by jakobroehrl** [comment]
Thanks a lot, I try if the HPB upgrade helps
