### ISSUE TITLE
confirm before muting another user in a call 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6999]
I muted another user accidently, maybe a confirm dialog would helpful.
And I can't remute the user.

**Comment by nickvergessen** [comment]
Hmm not a big fan of having to confirm those actions. cc @jancborchardt @marcoambrosini 

Being unable to unmute someone is a privacy/security feature. We don't plan to implement that. But there is #4566 as potential middle-step

**Comment by marcoambrosini** [comment]
I don't have a strong opinion on this @jancborchardt?
