### ISSUE TITLE
Add copy link to room button

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#7]

**Comment by ChristophWurst** [comment]
Do you mean in the list on the left?

We have to make sure to *not* ignore the hash on page load then, of course. Otherwise sharing a link is useless 😉 https://github.com/nextcloud/spreed/blob/8f9cb3db4b85e80ae8f9bc4288f1f894f2b919dc/js/index.js#L29-L32

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/spreed/issues/34 though
