### ISSUE TITLE
Shared files disappear from conversation thread after leaving conversation

### ISSUE THREAD

**Issue by old-mouse** [nextcloud/spreed#7009]
### Steps to reproduce
1. Start conversation with somebody.
2. Upload new file using "Upload new files" or "Share from files".
3. Select "Leave conversation".
4. Rejoin conversation.

### Expected behaviour
Shared files should remain in conversation thread. Or (if this is a feature) at least some warning message about "possible data loss" should appear.

### Actual behaviour
Shared files are replaced with message "You shared a file which is no longer available".
Actually uploaded files are still present at sender's NextCloud storage.

## Server configuration detail

**Operating system:** Linux 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64

**Webserver:** Apache/2.4.52 (Debian) (apache2handler)

**Database:** mysql 10.5.12

**PHP version:** 

7.4.28
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 23.0.2 - 23.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - cloud_federation_api: 1.6.0
 - contacts: 4.0.8
 - contactsinteraction: 1.4.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - files: 1.18.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - mail: 1.11.7
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - spreed: 13.0.3
 - support: 1.6.0
 - survey_client: 1.11.0
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.13.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - workflowengine: 2.5.0
Disabled:
 - circles
 - comments
 - dashboard
 - encryption
 - federation
 - files_external
 - files_trashbin
 - firstrunwizard
 - ojsxc
 - systemtags
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "X.X.X.X"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "23.0.2.1",
    "overwrite.cli.url": "http:\/\/X.X.X.X",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "proxy": "X.X.X.X:3128",
    "log_type": "file",
    "logfile": "nextcloud.log",
    "loglevel": 2,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
Seems to be intentional:
https://github.com/nextcloud/spreed/blob/1284b9d1b9396380b73fcfcb6ca355c9d2f7d3b5/lib/Share/RoomShareProvider.php#L129-L136

It's there since the beginning of sharing basically:
https://github.com/nextcloud/spreed/commit/19186045f5f0177b19a65956b43c2d516dbc37ac


@danxuliu and memory about this decision?
Group shares also are not deleted when you are removed from a group etc. 🤔

**Comment by danxuliu** [comment]
> @danxuliu and memory about this decision?

I thought it made sense :shrug: From the [pull request](#1050) description: _In the same way that a user must be a participant of a room to send a message to it a user must be a participant of a room to share a file with it [...]. Similarly, when a user leaves a room she has no longer access to the shares in the room; for consistency, her own shares are also removed._

> Group shares also are not deleted when you are removed from a group etc. :thinking:

I would expect my shares to be removed when I leave a room (or group!), but I could also understand it if they were kept, so if it makes more sense to keep them for consistency with group shares then fine by me too.

**Comment by nickvergessen** [comment]
@jancborchardt @nimishavijay @marcoambrosini any preference from UX perspective? What would be the user assumption?

**Comment by old-mouse** [comment]
Ohh, I've forgotten to mention, that text messages are retained when I leave conversation. Only files are removed.

**Comment by marcoambrosini** [comment]
I'd assume that the files stay in the conversation. That's what happens in most messengers, but of course the files are sort of "owned" by the conversation and not by users at that point. In our case I'd also delete the shares by default.
We should probably ask the user if they wants to keep their shares upon leaving?

**Comment by nimishavijay** [comment]
> any preference from UX perspective?

Files should probably stay by default, I don't think it is necessary to ask the user. If the user is deleted from the instance then it makes more sense to delete the file.

**Comment by nickvergessen** [comment]
Okay, so the code in https://github.com/nextcloud/spreed/blob/1284b9d1b9396380b73fcfcb6ca355c9d2f7d3b5/lib/Share/RoomShareProvider.php#L129-L136 should be removed and the integration tests adjusted accordingly.
