### ISSUE TITLE
Group sync still working?

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/spreed#7039]
## Steps to reproduce
1. Talk room is connected to a group
2. Add another user to that group

### Expected behaviour
User should automatically be also in the talk room

### Actual behaviour
He's not.

## Talk app

**Talk app version:** 	13.0.4

**Custom Signaling server configured:** yes/

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** Maria

**PHP version:** 8.0

**Nextcloud Version:** 23.0.3

---

I get my users/groups by User and Group SQL Backends 4.7.1 into the cloud, but this still works. Also I recently moved to another server, but everything seems to work. So, maybe this is a bug with the current versions?

**Comment by nickvergessen** [comment]
Yes this is still working and we have an integration test ensuring it:
https://github.com/nextcloud/spreed/blob/master/tests/integration/features/conversation/group-participants.feature#L35-L51

Maybe your Group SQL Backend is not triggering the correct hooks. Please open an issue there
