### ISSUE TITLE
Android app password fails to login

### ISSUE THREAD

**Issue by hukoeth** [nextcloud/spreed#704]
## Steps to reproduce
1. Enable 2FA in Nextcloud install with Talk installed and enabled
2. Create an App Password
3. Login to the Android Talk app using App password

### Expected behaviour
The Android App should log on to Nextcloud

### Actual behaviour
App hangs showing the "waiting animation" indefinately (waited 10 minutes)
"Normal" login method works

**Operating system:** Ubuntu 17.10 / Android 7.1.1

<details>
```
Insert your browser log here, this could for example include:
No warnings or errors in server log
```

</details>

## Spreed app

**Spreed app version:** 3.1.0

**Custom TURN server configured:** no 

**Custom STUN server configured:** no

</details>

**Comment by nickvergessen** [comment]
Hi, can you post your issue in the repository of the android app please? 
https://github.com/nextcloud/talk-android

Thanks, and also thanks for testing :)

**Comment by hukoeth** [comment]
Sorry, my bad. In case someone finds this I just opened https://github.com/nextcloud/android/issues/2356 for this issue
