### ISSUE TITLE
Video Lag while on call

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed#7046]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Call end user via talk web
2. User pickups via iphone talk app
3.

### Expected behaviour
The video  lags when users moves. Not sure if this is an issue just for me or might be related to 
https://help.nextcloud.com/t/talk-12-video-lag-and-motion-blur-with-1080p-webcam/121636
https://github.com/nextcloud/spreed/issues/6093
https://github.com/nextcloud/spreed/issues/6093

I tired it Web to web and did Notice the issue seems to be more related Phone to Web

## Talk app
13.1.1
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
13.0.4
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

## Browser

**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
**Operating system:** Windows/Ubuntu/...
Windows 11
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 85/96/...
Version 99.0.4844.74 (Official Build) (64-bit)
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Ubuntu
**Web server:** Apache/Nginx
Apache2
**Database:** MySQL/Maria/SQLite/PostgreSQL
MaraiaDb
**PHP version:** 7.4/8.0/8.1
8.0
**Nextcloud Version:** (see admin page)
23.0.3
**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.241.202.254",
            "cloud.next.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/cloud.next.com",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,1",
        "skeletondirectory": "",
        "default_phone_region": "US",
        "allow_local_remote_servers": true,
        "preview_max_memory": 1280,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Which user is moving and which device is lagging?

Can you please extend the steps? I can not reproduce a problem

**Comment by andyxheli** [comment]
Hello, thanks for your reply. The users that are on the IPhone are lagging on the users web screen. I tired it with two different iphone and iPad and same result. I made a call via talk web users joins it via iPhone, IPad, when I see them under the talk web the users that are using iPhone, iPad are laggging.

**Comment by andyxheli** [comment]
Maybe this is an iPhone Talk app issue ?

**Comment by andyxheli** [comment]
> Which user is moving and which device is lagging?
> 
> Can you please extend the steps? I can not reproduce a problem


Dose this error help
![image](https://user-images.githubusercontent.com/59488153/161589670-ac6449e8-7149-4508-a14e-f7b5d2aba001.png)

**Comment by andyxheli** [comment]
@nickvergessen just wanted to let you know that i updated to Talk 13.0.5 and still the same issue

**Comment by andyxheli** [comment]
So this seems to be related to one user so far as i can see.
