### ISSUE TITLE
No echo cancellation on some occasions (IOS/Android/Web?)

### ISSUE THREAD

**Issue by Marcel2508** [nextcloud/spreed#7058]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Make a call
2. Leave the call
3. Enter the call again (From IOS to Android)

### Expected behaviour
Echo cancellation - I shouldn’t hear myself.

### Actual behaviour
I can hear my own echo.

## Talk app

**Talk app version:** latest

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

in some occasions the noise cancellation doesn’t work and I can hear my own echo. When joining a call from IOS (initiated with Android) it first works as expected. After leaving the call and rejoining (from IOS side) I can constantly hear my echo. 
when the Android user disconnects and rejoins the Echo is gone again. So either the issue might be in Android app when someone joins a call or in IOS App when joining an existing call (after previously disconnected).

Someone already reported a similar issue here: https://github.com/nextcloud/spreed/issues/6887 

It might be a timing or configuration problem on either IOS or Android when someone joins a call?

**EDIT:** Another issue could be that IOS or Android or Web is echoing it‘s own input in the own video display. Rocket. Chat had similar problems? 

https://github.com/RocketChat/Rocket.Chat/issues/15018

**Comment by nickvergessen** [comment]
Are you talking about the mobile apps? Or joining in the browser?
