### ISSUE TITLE
Conversation disappears if joining but not responding to thread

### ISSUE THREAD

**Issue by paulate** [nextcloud/spreed#7086]
## Steps to reproduce
1. User 1 (signed in to Nextcloud) creates a conversation and opens it up to guests and shares the link.
2. User 2 (signed in to Nextcloud) clicks on the link, sees the conversation, but does not write a message in the conversation. The conversation appears on the left hand side, and clicking on the "..." icon in the side bar allows me to "leave conversation." But user 2 does not click this button.
3. User 2 then clicks another conversation in the side bar. Then user 2 refreshes the talk/spreed home page. The conversation vanishes from the side bar. 

### Expected behaviour
I am "user 2" in this scenario. I expect that once I click on a link to the conversation thread I have "joined" it by seeing the conversation and it appearing on the left hand sidebar. I want to be able to return to this thread without having to add to the conversation in the chat. However, it is only when I write a message in the conversation that it actually registers as me "joining" the conversation. If this is not the intended behavior, then I would prefer that it does not appear in the sidebar with the option to "leave conversation" because that UI is not consistent with the mental model of the intended behavior.  Also, perhaps a "join conversation" button that allows me to join without writing a message would be helpful. 

### Actual behaviour
Clicking on the link shows the conversation in the side bar and in the chat interface. Refreshing the page, the conversation disappears from the side bar and I have no way of accessing the chat again except through the link shared by User 1. 

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Mac os 12.1

**Browser name:** Chrome 

**Browser version:**  99.0.4844.84

## Talk app

**Talk app version:** not an admin so I can't see it... looks like Talk 10

**Comment by paulate** [comment]
I also now cannot seem to keep this conversation persistent in my sidebar, even if I've typed in a response into the conversation.  I clicked "leave conversation" at one point, and then clicked on the link again to see the conversation, typed in a response to the chat, and then clicked on a different conversation, and upon refreshing the conversation disappears from the sidebar.

**Comment by nickvergessen** [comment]
You will be removed (no matter your action) from public conversations unless a moderator added you or when the conversation is an "Open conversation"
![Bildschirmfoto von 2022-04-04 12-51-22](https://user-images.githubusercontent.com/213943/161529205-7f8b89d4-5443-4e5a-96ae-b890e3fe41f4.png)

The reason is that for a public link the password could change or being added and we would need to reask the logged in user for the new password etc.
