### ISSUE TITLE
Hover state overlapping border on emoji picker

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7098]
I guess that is one of the places we should use the version without background? cc @marcoambrosini
![Bildschirmfoto von 2022-04-06 11-27-16](https://user-images.githubusercontent.com/213943/161943815-261b349c-655c-4918-92ec-de25529a322f.png)
 
Regression from #7082

**Comment by nickvergessen** [comment]
`type="tertiary-no-background"`

**Comment by marcoambrosini** [comment]
yep that's right!
