### ISSUE TITLE
Let users delete their messages anytime (remove 6 hour limit)

### ISSUE THREAD

**Issue by nousernameavailableanymore** [nextcloud/spreed#7134]
The old request was closed without any meaningful explanation.
Are there any technical reasons for having such a seemingly arbitrary timeframe?
Let people finaly delete their messages as is common practice in all other chat applications.

I cant believe we have been discussing / requesting such a basic feature for years now.
If you are worried about implications then make it an admin setting, problem solved.

**Comment by nickvergessen** [comment]
We had a close look back then:
https://github.com/nextcloud/spreed/pull/4861#issuecomment-753967049
From the known instant messengers, only telegram allows this. Everyone else has limits.

We made this a design decision to retain a certain degree of history. We can rediscuss this once there is enough interest, but I think it still makes sense.

**Comment by nousernameavailableanymore** [comment]
> From the known instant messengers, only telegram allows this.

What is "this"? Deleting messages?
Then I would be very interested what you consider "known instant messengers".

Almost ALL of them allow deleting messages. 
Whatsapp, Facebook Messenger and Discord do without limitations (I was able to delete messages in all three that were months old). 
These three alone cover 90% of the market according to the stats I could find.
Thats the reason why Talk sticks out like a sore thumb.

**Comment by SystemKeeper** [comment]
> Almost ALL of them allow deleting messages.
> Whatsapp, Facebook Messenger and Discord do without limitations

WhatsApp does not allow to delete messages without limitation. You can always delete messages for yourself, but not others, see https://faq.whatsapp.com/iphone/chats/how-to-delete-messages for example.

**Comment by nousernameavailableanymore** [comment]
> WhatsApp does not allow to delete messages without limitation

That seems to be true. Since I dont use Whatsapp, I needed to check on someone elses phone. But yes, you are correct, there also seems to be a time limitation.

However, what I dont understand: all of the other messengers (well, maybe apart from Matrix) are company-based solutions.
A central software vendor makes all the decisions.
Whereas Talk (being a part of Nextcloud) should put the choice in the users hands not having to follow arbitrary restrictions from some faceless corporation.

So why not simply make this an admin setting?
I could understand if there were technical limitations or the feature was hard to implement. But this does not seem to be the case here, as deleting messages is already available.
But just looking at other (worse) software and saying "well, all the others also have limitations", when there is _clearly_ a demand for unristricted message deletion is (imho) the completely wrong approach.

If it is technically possible, then (always!) give the users (in this case the admins of the NC instance) the choice.
This choice to customize the software to your own needs is the reason why many people are here in the first place.

**Comment by jcharaoui** [comment]
I asked several users on my instance to share photo ID for a legal proceeding, thinking we would be able to delete it afterwards. Then I found out that there is a hardcoded time limit.

It should be possible at least for instance administrators to delete messages regardless of age.

**Comment by MparkG** [comment]
yes its annoying to have limitations.

**Comment by Antreesy** [comment]
Completed with https://github.com/nextcloud/spreed/pull/11451 starting from version 29

**Comment by SystemKeeper** [comment]
> that sounds to be contrary to the topic: "remove 6 hour limit" :/

These are 2 different things: Edit is allowed for 6 hours, deletion is now unlimited.

**Comment by MparkG** [comment]
Danke you for clarifying! 

Am 13. Mai 2024 22:34:57 MESZ schrieb "Marcel Müller" ***@***.***>:
