### ISSUE TITLE
Not possible to see all reactions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7139]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a message with more than 20 different reactions
2. As author try to see the reactions

### Expected behaviour
It is possible

### Actual behaviour
It is not possible to see a list with who reacted with what and what are the less favorite options.
Also if a reaction was used by 50 different people the popover starts becoming useless.

**Comment by nikola-gladovic** [comment]
When hovering, will show all people who react the same icon. The issue is that the number of people greater than 20. so the tooltip will not have enough place to show more.
so what is your suggestion ?

**Comment by DorraJaouad** [comment]
The idea would be:
Reaction button has title "All" and when clicking on it, it shows a modal including a list where each item is the name of the user with the avatar and the reaction. 
Maybe other tabs breaking down the list by reaction (like other messengers) ? 
cc @nextcloud/designers

**Comment by marcoambrosini** [comment]
Sounds reasonable @DorraJaouad
