### ISSUE TITLE
Migration to MySql fails with installed spreed

### ISSUE THREAD

**Issue by meberli** [nextcloud/spreed#714]
## Steps to reproduce
+ Install  Talk
+ convert sqlite to mysql:
    
     php occ db:convert-type --all-apps mysql [user] [host] [database]

### Expected behaviour
Migration should run

### Actual behaviour
Exception afte some time, Migration aborts:
```
[Doctrine\DBAL\Exception\TableNotFoundException]
  An exception occurred while executing 'SELECT * FROM "oc_spreedme_rooms"':
  SQLSTATE[HY000]: General error: 1 no such table: oc_spreedme_rooms
```
## Spreed app

**Spreed app version:** current app from 03-2018

## Server configuration detail

**Operating system:** Linux 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64

**Webserver:** LiteSpeed (litespeed)

**Database:** mysql 5.6.39

**PHP version:** 7.2.3
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, apcu, bcmath, dom, fileinfo, gd, imagick, imap, intl, json, exif, mysqlnd, mysqli, PDO, pdo_mysql, OAuth, pdo_sqlite, Phar, posix, pspell, soap, sockets, tidy, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - deck: 0.3.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - gpxpod: 2.2.2
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - onlyoffice: 1.2.0
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "vespadeluxe.ch"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/vespadeluxe.ch\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by nickvergessen** [comment]
This table does not exist anymore in 3.1, did you finish the upgrade before trying to migrate to another database?

**Comment by meberli** [comment]
this was on a new installation of nextcloud. I have installed it last Saturday. ,
today I tried to migrate from sqlite to mySQL then this error occurred

**Comment by donb9000** [comment]
I have run into this issue as well while trying to convert from sqlite to mariadb. The error about missing table oc_spreedme_rooms occurs whether or not I use the "--all-apps" option.

I've also found that if I disable or remove the talk app, the conversion gets an "Exception: App not found" error instead.

nextcloud: 13.0.2
Talk app: 3.2.1
sqlite: 3.23.1
mariadb: 10.1.33

**Comment by tinloaf** [comment]
I just encountered the same problem. This is the migration info of the `spreed` app in my installation:

```
root@picard:/var/www/html/nextcloud# sudo -u www-data php occ migrations:status spreed
    >> App:                                                spreed
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\Spreed\Migration
    >> Migrations Directory:                               /var/www/html/nextcloud/apps/spreed/lib/Migration
    >> Previous Version:                                   2001Date20180103150836
    >> Current Version:                                    3002Date20180319104030
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     3002Date20180319104030
    >> Executed Migrations:                                14
    >> Executed Unavailable Migrations:                    14
    >> Available Migrations:                               14
    >> New Migrations:                                     14
```

Looks very much like it's updated to the last version, right?

**Comment by donb9000** [comment]
I was not aware of the migrations:status command....

For completeness, here is the migration info from my installation:

    [root@monster nextcloud]# runuser -u http -- ./occ migrations:status spreed
        >> App:                                                spreed
        >> Version Table Name:                                 oc_migrations
        >> Migrations Namespace:                               OCA\Spreed\Migration
        >> Migrations Directory:                               /usr/share/webapps/nextcloud/apps/spreed/lib/Migration
        >> Previous Version:                                   2001Date20180103150836
        >> Current Version:                                    3002Date20180319104030
        >> Next Version:                                       Already at latest migration step
        >> Latest Version:                                     3002Date20180319104030
        >> Executed Migrations:                                14
        >> Executed Unavailable Migrations:                    14
        >> Available Migrations:                               14
        >> New Migrations:                                     14

**Comment by donb9000** [comment]
I don't claim to know how the migration processes for nextcloud work, but to satisfy my own curiosity, I went looking for references to `oc_spreedme_rooms` in my installation. This is what I found:

There are 14 files in spreed/lib/Migration...

```
[root@monster Migration]# pwd
/usr/share/webapps/nextcloud/apps/spreed/lib/Migration
[root@monster Migration]# ls -l
total 72
-rw-r--r-- 1 http http  3461 Jun  9 08:24 Version2000Date20170707093535.php
-rw-r--r-- 1 http http  2696 Jun  9 08:24 Version2000Date20171026140256.php
-rw-r--r-- 1 http http  3375 Jun  9 08:24 Version2000Date20171026140257.php
-rw-r--r-- 1 http http  5343 Jun  9 08:24 Version2001Date20170707115443.php
-rw-r--r-- 1 http http  2117 Jun  9 08:24 Version2001Date20170913104501.php
-rw-r--r-- 1 http http  1625 Jun  9 08:24 Version2001Date20170921145301.php
-rw-r--r-- 1 http http  2332 Jun  9 08:24 Version2001Date20170929092606.php
-rw-r--r-- 1 http http  1731 Jun  9 08:24 Version2001Date20171009132424.php
-rw-r--r-- 1 http http 12089 Jun  9 08:24 Version2001Date20171026134605.php
-rw-r--r-- 1 http http  1737 Jun  9 08:24 Version2001Date20171026141336.php
-rw-r--r-- 1 http http  1584 Jun  9 08:24 Version2001Date20171031102049.php
-rw-r--r-- 1 http http  4579 Jun  9 08:24 Version2001Date20180103144447.php
-rw-r--r-- 1 http http  1901 Jun  9 08:24 Version2001Date20180103150836.php
-rw-r--r-- 1 http http  1851 Jun  9 08:24 Version3002Date20180319104030.php
```

8 of those files directly reference the `spreedme_rooms` table (minus the `oc_` prefix)...

```
[root@monster Migration]# pwd
/usr/share/webapps/nextcloud/apps/spreed/lib/Migration
[root@monster Migration]# ag -Q spreedme_rooms -u -C3
Version2001Date20171009132424.php
40-             /** @var ISchemaWrapper $schema */
41-             $schema = $schemaClosure();
42-
43:             $table = $schema->getTable('spreedme_rooms');
44-             $table->addColumn('activeSince', Type::DATETIME, [
45-                     'notnull' => false,
46-             ]);

Version2001Date20170707115443.php
89-             $query = $this->db->getQueryBuilder();
90-
91-             $query->selectAlias($query->createFunction('COUNT(*)'), 'num_rooms')
92:                     ->from('spreedme_rooms');
93-             $result = $query->execute();
94-             $return = (int) $result->fetch();
95-             $result->closeCursor();
--
100-            }
101-
102-            $query->select('id')
103:                    ->from('spreedme_rooms')
104-                    ->where($query->expr()->eq('type', $query->createNamedParameter(Room::ONE_TO_ONE_CALL)));
105-            $result = $query->execute();
106-

Version2000Date20170707093535.php
71-                     $table->setPrimaryKey(['id']);
72-             }
73-
74:             if (!$schema->hasTable('spreedme_rooms')) {
75:                     $table = $schema->createTable('spreedme_rooms');
76-
77-                     $table->addColumn('id', Type::INTEGER, [
78-                             'autoincrement' => true,

Version2000Date20171026140256.php
65-             }
66-
67-             $update = $this->connection->getQueryBuilder();
68:             $update->update('spreedme_rooms')
69-                     ->set('name', $update->createNamedParameter(''))
70-                     ->where($update->expr()->eq('id', $update->createParameter('room_id')));
71-
72-             $query = $this->connection->getQueryBuilder();
73-             $query->select('*')
74:                     ->from('spreedme_rooms');
75-             $result = $query->execute();
76-
77-             $output->startProgress();

Version2001Date20171026134605.php
190-
191-            $query = $this->connection->getQueryBuilder();
192-            $query->select('*')
193:                    ->from('spreedme_rooms');
194-
195-            $result = $query->execute();
196-            while ($row = $result->fetch()) {

Version2001Date20171026141336.php
43-                     $schema->dropTable('videocalls_signaling');
44-             }
45-
46:             if ($schema->hasTable('spreedme_rooms')) {
47:                     $schema->dropTable('spreedme_rooms');
48-             }
49-
50-             if ($schema->hasTable('spreedme_room_participants')) {

Version2000Date20171026140257.php
72-             $entropy = (int) $this->config->getAppValue('spreed', 'token_entropy', 8);
73-
74-             $update = $this->connection->getQueryBuilder();
75:             $update->update('spreedme_rooms')
76-                     ->set('token', $update->createParameter('token'))
77-                     ->where($update->expr()->eq('id', $update->createParameter('room_id')));
78-
79-             $query = $this->connection->getQueryBuilder();
80-             $query->select('*')
81:                     ->from('spreedme_rooms')
82-                     ->where($query->expr()->emptyString('token'))
83-                     ->orWhere($query->expr()->isNull('token'));
84-             $result = $query->execute();

Version2001Date20170921145301.php
40-             /** @var ISchemaWrapper $schema */
41-             $schema = $schemaClosure();
42-
43:             $table = $schema->getTable('spreedme_rooms');
44-             $table->addColumn('password', Type::STRING, [
45-                     'notnull' => false,
46-                     'length' => 255,
```

Again, I have no idea how the migration processes work, but some of those references directly query the `spreedme_rooms` table, so I can only guess that the migration process is running some of these older migration functions and failing because the table no longer exists.

I hope that this helps...

**Comment by Grunthos** [comment]
I'm also getting this problem. Any progress or suggestions? Is there any other way to change DB type?

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/10298
