### ISSUE TITLE
Deck cards, locations and other shared objects not shown in shared items tab

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7144]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Follow up needed after https://github.com/nextcloud/spreed/pull/7076
https://github.com/nextcloud/spreed/pull/7076/commits/a7762280b815c2b51ffdded9dab101fa39939e7f

## Steps to reproduce
1. Share a deck card to a conversation
2. Open the shared items tab

### Expected behaviour
Deck cards, locations and other items show fine

### Actual behaviour
Error or no deck cards/locations shown

**Comment by nickvergessen** [comment]
@marcoambrosini you implemented deck cards and locations, right?
Now only the "other" with a simple text + link (if available) fallback is missing?

**Comment by marcoambrosini** [comment]
done
