### ISSUE TITLE
Implement modal for further shared items results

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7145]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Follow up needed after https://github.com/nextcloud/spreed/pull/7076
https://github.com/nextcloud/spreed/pull/7076/commits/a7762280b815c2b51ffdded9dab101fa39939e7f

## Steps to reproduce
1. Share a deck card to a conversation
2. Open the shared items tab

### Expected behaviour
See a modal or something with more items

### Actual behaviour

Notification in top right:
> Screenshot feature only. Implementation of the real feature will come soon! 😎

![Bildschirmfoto von 2022-04-13 16-52-10](https://user-images.githubusercontent.com/213943/163208497-2266c909-90da-4898-a3e9-1f94ae1cfe60.png)

**Comment by marcoambrosini** [comment]
done!
