### ISSUE TITLE
Add a specific notification type for reactions

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#7187]
Reactions notifications should be a different notification type in order to display them correctly.
It could also be a subject parameter in order to differentiate them from normal chat message notifications.

**Comment by nickvergessen** [comment]
Sample: Daphne reacted to Franks message:

> ![Bildschirmfoto von 2022-04-20 16-14-54](https://user-images.githubusercontent.com/213943/164250816-396ba8a9-de24-4326-aa45-4128148d9139.png)

Screenshot from Frank shows him being notified "about his message", instead about the reaction from daphne

**Comment by nickvergessen** [comment]
After a quick call:
* Notifications can be distinguished by `subjectParameters.reaction` being there
* If that one is found, we display the `subject` (which is already parsed plain text)
* If that one is not found, proceed as before

Please confirm the behaviour on Android @mahibi

**Comment by mahibi** [comment]
> Please confirm the behaviour on Android @mahibi

same issue for android. https://github.com/nextcloud/talk-android/issues/1935

btw if it's possible to deploy the server side fix (https://github.com/nextcloud/spreed/pull/7184 right?) on sermo this would help. So i don't have to waste time find out why i can't get my local docker instance to run..
