### ISSUE TITLE
Database migration error when upgrading to 14.0.0-rc3

### ISSUE THREAD

**Issue by OliveiraHermogenes** [nextcloud/spreed#7210]
## Steps to reproduce
1. Upgrade to version 14.0.0-rc3 from 14.0.0-rc2

### Expected behaviour
Successful upgrade.

### Actual behaviour
Database migration error:
```
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Fix the namespace in database tables
Exception: Database error when running migration 14000Date20220330141647 for app spreed An exception occurred while executing a query: SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying = bigint LINE 1: ...LEFT JOIN "oc_filecache" "f" ON "s"."item_source" = "f"."fil... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts.
```

## Talk app

**Talk app version:** 14.0.0-rc2

**Custom Signaling server configured:** No 

**Custom TURN server configured:** Yes

**Custom STUN server configured:** Yes

**Operating system**: Debian sid

**Web server:** Apache

**Database:** PostgreSQL 14

**PHP version:** 8.1

**Nextcloud Version:** 24.0.0 RC1

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/pull/7206

you can adjust the line and just run the occ upgrade again
