### ISSUE TITLE
Explicit integration (and unit?) tests for the summary

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7216]
It would be nice to add (either here or in another pull request) integration tests for [`getReactions()`](https://github.com/nextcloud/spreed/blob/c07251f0c67d3c02debe1f6dbe0e12ee3fe9f99a/lib/Controller/ReactionController.php#L115) (the integration tests currently check the basic information included in the message, but not the extended one with the participants provided by `getReactions()`) as well as unit tests for the summary.

_Originally posted by @danxuliu in https://github.com/nextcloud/spreed/issues/7205#issuecomment-1108927126_

**Comment by vitormattos** [comment]
Related PR: https://github.com/nextcloud/server/pull/32220

**Comment by nickvergessen** [comment]
Seems you misunderstood.
Basically the idea is that:
https://github.com/nextcloud/spreed/blob/master/tests/integration/features/reaction/react.feature
Should have a check like:
```
    Then user "participant1" sees the following reactions on message "Message 1" in room "room" with 200
      | room | actorType | actorId      | actorDisplayName         | reaction |
      | room | guests    | guest        |                          | 👤 |
      | room | users     | participant1 | participant1-displayname | 👍 |
      | room | users     | participant1 | participant1-displayname | 🚀 |
      | room | users     | participant2 | participant2-displayname | 👍 |
```
