### ISSUE TITLE
Reactions bubble should overlay the unread messages horrizontal line

### ISSUE THREAD

**Issue by mejo-** [nextcloud/spreed#7219]
## Steps to reproduce
1. Open a conversation with unread messages
2. Hover over the message just above the unread messages indicator line
3. Watch the reactions bubble. It's *under* the unread messages indicator line

### Screenshot

![talk-unread-reactions](https://user-images.githubusercontent.com/3582805/165246046-0c3a5499-a368-43a0-a1ab-435ae2cf3675.png)

### Expected behaviour
I guess it would look cleaner if the reactions bubble would overlay the unread messages indicator line.

## Talk app

cloud.nc.c instance

## Browser

**Operating system:** Linux

**Browser name:** Firefox

**Browser version:** 99

**Comment by nickvergessen** [comment]
Assigning the issue instead of the overview to marco
