### ISSUE TITLE
Allow text chat for clients without camera or microphone

### ISSUE THREAD

**Issue by ndom91** [nextcloud/spreed#723]
Currently users without a microphone or camera get enumerateDevices() fail and then the UI simply says "Error while accessing microphone & camera" and does not load the user list, room list, anything.

They shoudl still be allowed to text chat, right?

If there is a workaround currently available, please point me in the right direction. I've been playing around with ../spreed/js/webrtc.js to disable the requirement of camera and mic to load, but have not been fruitful.

**Comment by nickvergessen** [comment]
Fixed  with #619 for the next release

**Comment by ndom91** [comment]
Woohoo!
