### ISSUE TITLE
When adding a user with a very long name to a conversation group, all information is not displayed

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7254]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When trying to add a user to a new conversation group, if the user's name is too long, it is not displayed completely

**Describe the solution you'd like**
Insert a tooltip in the component to display the full information

**Additional context**
![image](https://user-images.githubusercontent.com/102530814/165987742-e6d26702-fa3e-4f1a-9d48-a92ddc259ce4.png)

**Comment by Antreesy** [comment]
@nickvergessen @mstolf 
Isn't this issue related to this PR: https://github.com/nextcloud/spreed/pull/4548 ?

Tried to reproduced this bug by editing `innerHTML` with username through the Devtools,
Conditions for tooltip appearance are recalculating on `@mouseover` event properly:
![image](https://user-images.githubusercontent.com/93392545/214808636-40b8d2d4-f668-4558-aa16-eef8134784b6.png)

On the other hand, tooltip is not displayed when adding a user through the left sidebar search:
![image](https://user-images.githubusercontent.com/93392545/214809320-ea75b80a-48d9-4023-9b51-854d3c2463af.png)

Shouldn't we close this issue and open new one, with bug mentioned above?

**Comment by nickvergessen** [comment]
> Shouldn't we close this issue and open new one, with bug mentioned above?

Or you fix the remaining bit with this ticket. As you wish.
