### ISSUE TITLE
mentions not replaced when creating a task

### ISSUE THREAD

**Issue by blizzz** [nextcloud/spreed#7280]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a post with a mention
2. Click three-dot-menu
3. Click "Create a task"

### Expected behaviour
Mention is replaced with display name

### Actual behaviour
technical placeholder is visible

![Screenshot_20220502_142347](https://user-images.githubusercontent.com/2184312/166233456-f9ce4600-a150-462d-8e40-bef0aea67f4a.png)

## Talk app

**Talk app version:** 14 on cloud.nc.c

## Browser

**Operating system:** Arch btw

**Browser name:** Firefox

**Browser version:** 99

### Browser log

n/a

</details>

## Server configuration

cloud.nc.c

**Comment by nickvergessen** [comment]
Fixed already: https://github.com/nextcloud/deck/pull/3683
Seems to miss a release or deployment
