### ISSUE TITLE
Add email address or username below name when adding participants to a conversation group

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7284]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Here in Brazil we have many names that are common, and it is very easy for two people with the same name to appear, making it difficult to add the user to a chat group

![image](https://user-images.githubusercontent.com/102530814/166289130-d34d9e30-a44c-4710-b404-872991fb3d99.png)

**Describe the solution you'd like**
As a solution for this type of case, I thought of inserting the email address or the username under the name, in this way it would be easier to identify the correct user to be added.

![image](https://user-images.githubusercontent.com/102530814/166290221-c0b14377-6ddb-4e51-9e8d-364fe505d1f8.png)

**Describe alternatives you've considered**
Currently, both users are inserted, their profiles are viewed and the incorrect one is removed.

**Comment by nickvergessen** [comment]
Backend fix in https://github.com/nextcloud/server/pull/32249
Afterwards we can use the info from the API

**Comment by nickvergessen** [comment]
Server branch merged, so this can now be picked up

**Comment by nickvergessen** [comment]
Basically the API has an additional optional attribute in the response: `shareWithDisplayNameUnique`
When it is given and set it should be displayed in a subline

**Comment by nickvergessen** [comment]
We will show what the server API returns, and I think it is the email.

**Comment by marcoambrosini** [comment]
Hmm not sure we should show an email there. @nimishavijay what do you think?

**Comment by nimishavijay** [comment]
This is an interesting problem! 
Do you think it might be a privacy concern for some users who wouldn't want their email address exposed? And showing the username might be a bit confusing to normal users who are not admins.

Usually a combination of name and avatar is used as an identifier. So maybe the background colour for the default avatar could be different for each user. Then there would be one Pedro Silva with a blue background and a Pedro Silva with a purple background, which can help distinguish the 2 users. What do you think?

**Comment by nickvergessen** [comment]
> Hmm not sure we should show an email there.

This is nothing to discuss really. We do the same thing already when you share a file. The search result needs to show the unique factor provided by the API when it is provided and it only is provided if 2 entries have the same display name.

> Do you think it might be a privacy concern for some users who wouldn't want their email address exposed?

This is already done in the sharing app: https://github.com/nextcloud/server/pull/23017

> So maybe the background colour for the default avatar could be different for each user.

Also nothing to discuss here and well it would have to change in all clients how to recalculate the color based from input data.
