### ISSUE TITLE
Include document viewer in talk

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7287]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
It would be interesting for Talk to have a document viewer for the formats doc,docx,xls,xls,eml similar to the pdf viewer

**Describe the solution you'd like**
Include a document viewer with read-only permission for doc,docx,xls,xls,eml format files

**Comment by nickvergessen** [comment]
When you install any of the office apps:
* https://apps.nextcloud.com/apps/richdocuments
* https://apps.nextcloud.com/apps/onlyoffice
* https://apps.nextcloud.com/apps/hancomoffice
* https://apps.nextcloud.com/apps/officeonline

that works already.
