### ISSUE TITLE
When making a private call, the message "Waiting for others to join the call" is appearing, treat for when it is a private call, the name of the user who has not yet connected the call appears

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7292]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Today, when we make a private call, the generic message "Waiting for others to join the call" appears, implying that there is more than one participant joining the conversation.

**Describe the solution you'd like**
I thought in the case of a private call, the name of the user who has not yet joined the call appears

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/102530814/166448299-ccd14ed4-35a6-4146-b7c7-8079da9096a3.png)

**Comment by nickvergessen** [comment]
Already the case now:
https://github.com/nextcloud/spreed/blob/5a4dbda23af2d25aac4c3705af3fae48ad3d7c3d/src/components/CallView/shared/EmptyCallView.vue#L131-L137
