### ISSUE TITLE
When leaving a call, the join call button is displayed until the other participant leaves the call

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7295]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When leaving a call, the join call button is displayed until the other participant leaves the call

**Describe the solution you'd like**
Check if it is possible when it is a private call, when one participant leaves the call, end the call of the other participant

**Comment by nickvergessen** [comment]
This is currently intended

**Comment by nickvergessen** [comment]
Closing in favor of https://github.com/nextcloud/spreed/issues/12195
