### ISSUE TITLE
Add option to rename a conversation without having to enter it

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7297]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently, to be able to rename a conversation group it is necessary to click on it, click on the settings button and then select the option to Rename the conversation, which is very impractical and requires many clicks to perform the action.

**Describe the solution you'd like**
In the left sidebar, in the "..." button, include an option to rename the conversation, in this way, with just two clicks, the user would perform the desired action

**Additional context**
Example:
![image](https://user-images.githubusercontent.com/102530814/166476747-ce4d752e-4f3d-4d36-87dc-92a372ca24cd.png)

**Comment by nickvergessen** [comment]
Can't find the ticket at the moment, but the plan is to move the renaming into the conversation settings.
This would then be automatically solved as the settings are already reachable from there
