### ISSUE TITLE
Skip old rooms from default room list and live updating?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7299]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Numbers
After getting some numbers I asked an individual on our instance with a lot of rooms (450+) if they are okay with checking their room last activity date. Since they agreed, here is the query + result:

#### By year+month only
```sql
SELECT YEAR(last_activity) AS year, MONTH(last_activity) AS month, COUNT(*)
FROM oc_talk_rooms
WHERE id IN (
	SELECT room_id
	FROM oc_talk_attendees
	WHERE actor_type = 'users'
	AND actor_id = '…')
GROUP BY year, month
ORDER BY year DESC, month DESC;
+------+-------+----------+
| year | month | COUNT(*) |
+------+-------+----------+
| 2022 |     5 |       38 |
| 2022 |     4 |       55 |
| 2022 |     3 |       28 |
| 2022 |     2 |       20 |
| 2022 |     1 |       12 |
| 2021 |    12 |       10 |
| 2021 |    11 |       14 |
| 2021 |    10 |       29 |
| 2021 |     9 |       14 |
| 2021 |     8 |        6 |
| 2021 |     7 |       16 |
| 2021 |     6 |       13 |
| 2021 |     5 |       16 |
| 2021 |     4 |       13 |
| 2021 |     3 |       13 |
| 2021 |     2 |        7 |
| 2021 |     1 |       11 |
| 2020 |    12 |        8 |
| 2020 |    11 |       10 |
| 2020 |    10 |        1 |
| 2020 |     9 |        9 |
| 2020 |     8 |        3 |
| 2020 |     7 |        4 |
| 2020 |     6 |        6 |
| 2020 |     5 |        8 |
| 2020 |     4 |        7 |
| 2020 |     3 |        8 |
| 2020 |     2 |        6 |
| 2020 |     1 |        3 |
| 2019 |    12 |        1 |
| 2019 |    11 |        9 |
| 2019 |    10 |        5 |
| 2019 |     9 |        3 |
| 2019 |     8 |        2 |
| 2019 |     7 |        5 |
| 2019 |     6 |        8 |
| 2019 |     5 |        3 |
| 2019 |     4 |        4 |
| 2019 |     3 |        1 |
| 2019 |     2 |        1 |
| 2019 |     1 |        2 |
| 2018 |    11 |        2 |
| 2018 |    10 |        6 |
| 2018 |     8 |        2 |
| 2018 |     7 |        1 |
| 2018 |     6 |        2 |
| 2018 |     5 |        1 |
| 2018 |     3 |        2 |
| 2018 |     2 |        1 |
| 2018 |     1 |        1 |
| 2017 |    12 |        1 |
| NULL |  NULL |        6 |
+------+-------+----------+
```

#### By year only
```sql
SELECT YEAR(last_activity) AS year, COUNT(*)
FROM oc_talk_rooms
WHERE id IN (
	SELECT room_id
	FROM oc_talk_attendees
	WHERE actor_type = 'users'
	AND actor_id = '…')
GROUP BY year
ORDER BY year DESC;
+------+----------+
| year | COUNT(*) |
+------+----------+
| 2022 |      153 |
| 2021 |      162 |
| 2020 |       73 |
| 2019 |       44 |
| 2018 |       18 |
| 2017 |        1 |
| NULL |        6 |
+------+----------+
```

### Problem / Impact
Currently we are doing multiple things every time we get the room list:
* Get user status for 1-1
* Get last comment and parse it
* Calculate unread messages

As per the above example it seems we could skip ~300 rooms for the user if we would only pull their rooms that had something happening in the last 4 months (as it is also very unlikely that they are needed ad hoc, and if they are and someone else posts in them, the next polling will bring them in). Another person on our instance with 550+ chats would also be reduced to ~160 chats:
```
+------+----------+
| year | COUNT(*) |
+------+----------+
| 2022 |      163 |
| 2021 |      199 |
| 2020 |       79 |
| 2019 |       51 |
| 2018 |       22 |
| 2017 |        1 |
| NULL |       36 |
+------+----------+
```

### New desired behaviour?
Since we have the search available, I wonder if we should just do similar to this:
* Only load conversations active in the last X months
* As a last entry add a dummy in the conversation list telling to use the search
* When the search is used we query the server already for open conversations and could just also return joined conversations matching the search term

### Potential issues
* Clients which keep a local copy of the conversation list need to adapt to the behaviour (unless we exclude them via user agent or something)
* When the active list is too short/empty, we might need a check on the size and could then make a second query (and we can cache the if) for those users to return more.

**Comment by vitormattos** [comment]
Is a good test to do and check if we will got a performance increasing.
I think that is good validate first in a specific branch and check if we got a good performance on instances with a lot of rooms.

**Comment by marcoambrosini** [comment]
What about lazy loading conversations just as we do with messages? We could load say 30 convs initially and then request for more as the user scrolls down and hits a certain scroll threshold.

**Comment by vitormattos** [comment]
Is a good idea without possible issues.

**Comment by nickvergessen** [comment]
We can't offset on a dynamic api

@danxuliu had another idea. Basically we only load all conversations initially and after that only load conversations that have the last active newer than the last load.

Unresolved question: how to delete conversations up on removal... We don't know which conversations the user has been removed from or which one's were deleted and need removal.

**Comment by danxuliu** [comment]
Maybe we could use a signaling message for that. If a user is removed from a conversation (either only that user or because the whole conversation was removed) a signaling message is sent to the user, and when received the client just removes the room from its list.

I guess it would even work when the conversation clustering is enabled as long as the user is already in a room and thus connected to one of the different signaling servers (so it will not work if the user is in the initial Talk page, before joining a conversation, although I guess not a lot of people stay in that page :-) ).

For federated conversations that would be a different story, but it could be an optimization specific to non-federated setups anyway.

**Comment by nickvergessen** [comment]
The HPB should already sent different events which we could use to trigger a "full update" of the conversation list in case of disinvite/delete
And if we did not receive an event like this we just do a simple "update refresh of recently changed"

That could work 🤔
