### ISSUE TITLE
 Transform text into a hyperlink when the word starts with "www."

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7303]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently, if the word starts with http:// or https:// it is automatically transformed into a link, but if a website is inserted, for example www.nextcloud.com, the text is not considered a link

**Describe the solution you'd like**
 Transform text into a hyperlink when the word starts with "www."

**Describe alternatives you've considered**
Include https:// before the url

**Comment by nickvergessen** [comment]
We use a library for link parsing:
https://github.com/juliushaertl/vue-richtext/blob/master/package.json#L45-L46

So not sure it is that easy and also not sure it is even wanted.
e.g. when posting code or other strings without spaces it could trigger a url even though not wanted:
```
Hello experimenta.science is making progress!
```
would create a link to https://experimenta.science/ although it was never intended and the user wanted:
```
Hello experimenta. science is making progress!
```
Or something a like.

**Comment by nickvergessen** [comment]
By now this would need to go into https://github.com/nextcloud/vue-richtext

But we restricted it there recently:
https://github.com/nextcloud/vue-richtext/issues/790
