### ISSUE TITLE
UI switching between large conversations is slow

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#7319]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have two conversations with multiple >20 users and lots of messages
2. Switch between the conversations

### Expected behaviour
The message list should load fast

### Actual behaviour
The message list takes multiple seconds to load, even though the actual network requests to the API are fast.

This happens on our instance but I couldn't reproduce it locally with the dev javascript build, probably because I haven't enough message history, reactions or manually added users.

But the profile from our instance should give an idea on where to investigate further. From there I see two major points:
<img width="1440" alt="Screenshot 2022-05-05 at 15 04 41" src="https://user-images.githubusercontent.com/3404133/166930945-b1b5d310-eccc-470f-a0d9-c7ad63f7aef5.png">

- Destruction of the old components (it seems that for the v-tooltip each destroy is issuing a timeout function to hide it)
<img width="873" alt="Screenshot 2022-05-05 at 15 05 15" src="https://user-images.githubusercontent.com/3404133/166931010-3f379cbe-54a3-4a31-9636-1d660ab6ffc8.png">

- When rendering the new components a lot of style recalculations are happening during emoji-mart related code

<img width="1440" alt="Screenshot 2022-05-05 at 15 16 55" src="https://user-images.githubusercontent.com/3404133/166931166-bec5fc0d-0c3b-4801-9a0f-c95a4072da87.png">

## Additional context:

- I feel this has started with the upgrade to 24
- The tooltip thing links like skipDelay is not passed over here: https://github.com/Akryum/floating-vue/blob/v2.0.3/src/components/Popover.vue#L285
  - Seems like this commit https://github.com/Akryum/floating-vue/commit/70043d3850dfe0f3bf0b32b9f5878fe70f40549a is not part of the most recent v-tooltip release
  - Might need https://github.com/nextcloud/nextcloud-vue/pull/2600

**Comment by nickvergessen** [comment]
Do we by accident always load/render and just visually hide the emoji picker?

**Comment by nickvergessen** [comment]
Patch at https://github.com/nextcloud/spreed/pull/7326
