### ISSUE TITLE
Voice messages cannot be deleted

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/spreed#7324]
Voice messages cannot be deleted from Talk, as is the case with simple text messages.

To delete voice messages you have to go to the Talk folder under Files and delete the voice message there.

Deleting voice messages is also not possible in the Talk app.

**Comment by nickvergessen** [comment]
This work on Nextcloud 24 + Talk 14
Are you on the latest versions?

**Comment by R7JANV1** [comment]
Oh great (AIO users still on version 23.X.X)

**Comment by R7JANV1** [comment]
> This work on Nextcloud 24 + Talk 14 Are you on the latest versions?

Is this feature also available for the apps?

**Comment by R7JANV1** [comment]
This function is not available either in the apps or in the browser.  Neither pictures, voice messages or videos can be deleted from the chat.

Please reopen the ticket.

**Comment by nickvergessen** [comment]
It's possible with the usual 6h restriction:
![grafik](https://github.com/nextcloud/spreed/assets/213943/01b6b29a-da4c-4147-ae9a-d58793fbc71a)

**Comment by R7JANV1** [comment]
Correct, my mistake, this does not work in the Android app.

**Comment by nickvergessen** [comment]
cc @mahibi can you check and raise an issue?

**Comment by mahibi** [comment]
> cc @mahibi can you check and raise an issue?

can reproduce. https://github.com/nextcloud/talk-android/issues/3111

**Comment by R7JANV1** [comment]
The same behavior with video, image, contact and location.
