### ISSUE TITLE
Use JWT instead of requiring the HPB to check authentication of the user

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7336]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Background numbers of a company call:
```
$ cat nextcloud.log | grep "nextcloud-spreed-signaling" | grep "Validated" | wc -l
395
```

We could save 395 requests hitting the server by using JWT as auth mechanism. Could use a private/public key model and expose the public key via capabilities which are checked by the HPB anyway already. This way the HPB could validate the signaling ticket directly without contacting the server again.

**Comment by fancycode** [comment]
Implementation of the signaling server started in https://github.com/strukturag/nextcloud-spreed-signaling/pull/251

I'll try to find some time to also look into the Talk side.

**Comment by fancycode** [comment]
Draft PR for the Talk side in https://github.com/nextcloud/spreed/pull/7472

**Comment by fancycode** [comment]
We could even include the token of the room the user is currently joining in the JWT to get rid of the initial room join validation request.

**Comment by nickvergessen** [comment]
Implemented
