### ISSUE TITLE
🔍 Search for messages in mobile apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7357]
- [x] API: Unified search https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/search.html#fetching-individual-search-results
- [x] Web: Already available
- [x] iOS https://github.com/nextcloud/talk-ios/issues/511
- [x] Android https://github.com/nextcloud/talk-android/issues/1047

**Comment by nickvergessen** [comment]
* Search provider to search for messages in any chat: `talk-message`
* Search provider to search for messages in a single chat: `talk-message-current`

**Comment by marcoambrosini** [comment]
UI-wise: 

Mobile clients
**Conversation search**
Displays search results only for current conversation

**Conversations list search**
Other conversation's messages
Conversations
Users
Groups

**Comment by nickvergessen** [comment]
All parts done
