### ISSUE TITLE
Docx File not correct via TALK

### ISSUE THREAD

**Issue by Elvis2000NC** [nextcloud/spreed#7358]
When I send a DOCX file via TALK, the file also opens correctly. Everything seems correct. However, the recipient cannot print the file correctly because the icon created over the print icon is an almost blank sheet. Does anyone know this problem and has a solution? I opened the PDF with Adobe Reader, Foxit Reader and in Firefox. Always the PDF looks the same and the information is missing.
![grafik](https://user-images.githubusercontent.com/76623282/167799606-a455a2d5-9b59-478d-97d5-4d489376213b.png)

**Comment by nickvergessen** [comment]
Since this is not a bug with Talk (we only invoke the viewer) can you please report it to OnlyOffice?
https://github.com/ONLYOFFICE/onlyoffice-nextcloud
