### ISSUE TITLE
Compile SCSS manually

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7373]
The SCSS cacher has been removed with https://github.com/nextcloud/server/pull/32261

So we need to manually compile our SCSS files.
Would of course be nice to get rid of them if possible and move the stuff to the actual components, but e.g. with the At.scss and unified search as well as the icons it might not be suitable.
There we should fix them to the new variables manually and then compile them like in the server

- [x] app https://github.com/nextcloud/spreed/pull/7576
- [x] At https://github.com/nextcloud/spreed/pull/7576
- [x] icons https://github.com/nextcloud/spreed/pull/7576
- [x] publicshare https://github.com/nextcloud/spreed/pull/7576
- [x] publicshareauth https://github.com/nextcloud/spreed/pull/7576
- [x] unified-search https://github.com/nextcloud/spreed/pull/7576
- [x] icon-folder-multiple-image is undefined used in RightSidebar.vue for "shared items" https://github.com/nextcloud/spreed/pull/7576
- [ ] settings-admin https://github.com/nextcloud/spreed/pull/7577
- [ ] #7578

https://github.com/nextcloud/spreed/blob/9e9197cc56fd8374c4916ba1fd029721cd1a5486/src/mainPublicShareSidebar.js#L98-L115

**Comment by skjnldsv** [comment]
> Would of course be nice to get rid of them if possible and move the stuff to the actual components, but e.g. with the At.scss and unified search as well as the icons it might not be suitable.

just importing them in your main.js should work out of the box.
For the icons mixin thing though, we can chat about it tomorrow to find out what is missing :)
