### ISSUE TITLE
Nextcloud Talk Permission Issue for Sending messages

### ISSUE THREAD

**Issue by Gowtham-eng** [nextcloud/spreed#7433]
There is no feature of a Conversation Group only the admin can able to send a message and this is the biggest issue of the broadcasting messages of users and permissions.

**Describe the solution you'd like**

I want to allow permission only admin can send a message in everyone's group. 

**Describe alternatives you've considered**

It's Similar to broadcast messages if we sorted this out there is no need for an announcement center or make an announcement center better to add more features like adding attachments while posting a nextcloud announcement.

**Additional context**
There is no permission access for an admin to control the group of every messages to post it by users or admin

**Comment by nickvergessen** [comment]
This has been implemented for the next version already: #3886
