### ISSUE TITLE
Can't Install Talk in nextcloud 13 (exception occurred while executing 'ALTER TABLE oc_talk_participants ...)

### ISSUE THREAD

**Issue by bjarkan** [nextcloud/spreed#747]
## Steps to reproduce
With admin account in app store click activate in Talk App
with https://www.techandme.se/nextcloud-vm/

### Expected behaviour
Actually install talk service

### Actual behaviour
An exception occurred while executing 'ALTER TABLE oc_talk_participants ADD inCall TINYINT(1) DEFAULT '0' NOT NULL': SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud_db.oc_talk_participants' doesn't exist in engine

**Comment by nickvergessen** [comment]
Please report to "techandme"

**Comment by eldelacajita** [comment]
@nickvergessen You mean this bug should be related to their VM? Someone already reported it [there](https://github.com/nextcloud/vm/issues/471), and was told to report it here.

I'm getting the exact same error. Where should we report this?

**Comment by nickvergessen** [comment]
Well our integration tests which install on mysql, sqlite and postgres are working fine, so there must be something wrong with the VM, yes.
