### ISSUE TITLE
📊 Simple polls API - part 2

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7480]
Follow ups to https://github.com/nextcloud/spreed/pull/7306

- [x] Add new media tab
- [x] Add capability for mobile clients
- [x] Question that came up:
Should we have an option that prevents changing the vote after you voted once? The goal is to prevent Band-Wagon on the second level via the editing option, but e.g. Telegram still allows this and we think it could be useful e.g. when you use it to agree on an appointment and duties change or similar stuff.

**Comment by mahibi** [comment]
For the system message that someone voted on a poll, please don't use "talk-poll" as attribute text. Let's use "talk-poll-voted" instead.
Could you do that @vitormattos ?

This would make it much easier for the android app to differentiate between the messages.

**Comment by vitormattos** [comment]
It sounds like a good idea.

**Comment by mahibi** [comment]
i vote for 
`{"option0":1,"option1":1}`
as it's the structure the android app expects atm

**Comment by nickvergessen** [comment]
Fix in https://github.com/nextcloud/spreed/pull/7500

**Comment by mahibi** [comment]
@nickvergessen closed unintentionally? or is there already capability / mediatab?

**Comment by nickvergessen** [comment]
Follow ups in https://github.com/nextcloud/spreed/pull/7512

Now only the editing/revoting question is open.
To be clarified with @marcoambrosini next week.

**Comment by nickvergessen** [comment]
- [ ] Editing shall be allowed in both modes
- [ ] We should show the number of voters to the author and moderators on hidden polls so they know when to close
