### ISSUE TITLE
Mention autocomplete options not visible on master

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7481]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Type `@t` into the chat and wait

### Expected behaviour
Mention popup shows

### Actual behaviour
No popup, but you see requests for status, etc. So seems like the thing is there, just not shown?

## Talk app

**Talk app version:** master

**Comment by nickvergessen** [comment]
Also works with arrow down + enter, so maybe a z-index or position error with the new theming?

**Comment by SystemKeeper** [comment]
For me it's appearing in the bottom left corner under the side bar:

![image](https://user-images.githubusercontent.com/1580193/173826266-c1f024e0-b0d8-43ee-9be2-f5999e8f4a05.png)

**Comment by marcoambrosini** [comment]
Seems like a container element issue

**Comment by nickvergessen** [comment]
Ah, I guess this is because of the removed SCSS cacher 🙈

**Comment by nickvergessen** [comment]
Works in the meantime
