### ISSUE TITLE
PHP dev dependencies should not be loaded by Talk

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7492]
Since #7372 the Composer autoloader is explicitly registered [when bootstraping Talk](https://github.com/nextcloud/spreed/commit/f0edd9cf52dc12fbdd9278650a70383b19968d98#diff-4eb824426a8cffb8b33b62b57744c69f32ea30ea755249a7a6170d9402885debR114). However, the autoloader includes not only runtime dependencies, but also development dependencies, which are now unnecessarily loaded for every request.

Moreover, this could also break the Nextcloud server if some API was changed and one of the composer dependencies has not been updated yet. For example, since https://github.com/nextcloud/server/commit/813b50ed428a8bc36817d19c84444e96dbe3b668 `IQueryFunction` is returned instead of `string` (it might be reverted soon, but that is a different story). This change [is already applied in the repository of `christophwurst/nextcloud/OCP`](https://github.com/ChristophWurst/nextcloud_composer/commit/b6789dd4128302a1d6c38c0239c762d0fab620eb) and it should be included in the [published package](https://packagist.org/packages/christophwurst/nextcloud#dev-master), but composer downloads `dev-master 5e97194` rather than `dev-master b6789dd`. This causes any request to the Nextcloud server to fail (and there will be no errors in nextcloud.log, but in the web server logs) due to the mismatch between the server API and the [christophwurst/nextcloud/OCP](https://github.com/nextcloud/spreed/blob/f0edd9cf52dc12fbdd9278650a70383b19968d98/composer.json#L4) API (which should be loaded only for development tasks, like running Psalm).

**Comment by vitormattos** [comment]
About the IQueryFunction I solved here:
https://github.com/nextcloud/spreed/pull/7486

**Comment by vitormattos** [comment]
About the package to solve the psalm problems, I think that, maybe, will be good to implement a cron to check the updates of Christoph package like the follow cron script and create a PR with the changes:
https://github.com/ChristophWurst/nextcloud_composer/blob/master/.github/workflows/cron.yml

**Comment by nickvergessen** [comment]
Just for the record, as long as you don't run phpunit/psalm locally you don't need the dev dependencies, so installing with `composer install --no-dev` is fine and should not yield any issues.
Other than that I'm not sure how to improve the situation.

Could only go with a second composer file in another directory, but that would mean the packaging action and all other actions we use from the `.github` template directory would need adjusting to execute `composer install` in multiple locations
