### ISSUE TITLE
Questions About Nextcloud Talk 

### ISSUE THREAD

**Issue by Daniel3356** [nextcloud/spreed#7495]
I'm looking for a free self-hosted solution that allows employees inside a company to chat and perhaps even perform video calls. I was wondering whether Nextcloud Take allows me to use it for free if I have my own my SIP trunk line (Twilio) or if I can utilise webRTC for free.
(For Startup)

Thanks

**Comment by nickvergessen** [comment]
SIP is not available with a subscription, but WebRTC is
