### ISSUE TITLE
Issue with Database

### ISSUE THREAD

**Issue by tgois** [nextcloud/spreed#7502]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Activate Talk
2.
3.

### Expected behaviour
Talk is active

### Actual behaviour
Following error appears "Database error when running migration 13000Date20210625232111 for app spreed An exception occurred while executing a query: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1021 Disk full (/tmp/#sql_9491c_0.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")"
Talk is not active

## Talk app

**Talk app version:** 14.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.4.18

**Nextcloud Version:** 24.0.1

**List of activated apps:**

<details>
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - audioplayer: 3.3.0
  - calendar: 3.3.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.12
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.0
  - richdocumentscode: 21.11.402
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption: 2.7.0
  - files_external
  - spreed: 12.1.2
  - user_ldap
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "server address"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "http:\/\/server ip",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false,
        "app_install_overwrite": [
            "cookbook"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by tgois** [comment]
It is an issue of talk interfacing with the Database, and since no other process that uses the same database has any issues, it is not an issue with the Database. That is why i post it here.

I have used several search engines to look for that, and spent hours trying solutions and nothing worked.

And since you keep closing this whitout giving a solution, it is going to be hard to get one...

**Comment by nickvergessen** [comment]
We have hundred thousands of Talk installations working fine. So it's not a problem with our source code but with your database configuration. I guess the "No space left on device" error from the beginning brought your server into a faulty state.
Best help I can offer is trying to reboot it and then try check and repair commands and queries like e.g. https://phoenixnap.com/kb/mysql-repair-database#ftoc-heading-4
