### ISSUE TITLE
⏳ Expiring messages - API part 2

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7508]
- [x] Adjust background job logic
    - [x] Adjust method name after merge of:
      https://github.com/nextcloud/server/pull/33086
    - [x] Transform the background job to run it for all rooms in one go: 
      https://github.com/nextcloud/spreed/pull/7571
- [x] Unshare attachments
  https://github.com/nextcloud/spreed/pull/7629
- [x] Allow to set expiration via console/occ
  https://github.com/nextcloud/spreed/pull/7596
- [x] Move send system message after change the expiring time to a Listener
  https://github.com/nextcloud/spreed/pull/7595
- [ ] Unit tests (if necessary)

**Comment by vitormattos** [comment]
I think that all is done here.
