### ISSUE TITLE
GPS location is not visible

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/spreed#7519]
## Steps to reproduce
1. Send from Android Talk app gps location
2. open web talk app -> gps location is not visible -> BUG

When I am trying to reply, location (address , not gps location) is visible
Maybe you should display gps location and address, not only adress. E.g "	51° 06′ 42″ N, 17° 02′ 56″ E ( street name, building number etc)" or add option in settings to choice format.

Nextcloud: 24.02
Talk: 14:02
Web browser: Firefox 102 Ubuntu snap
OS (client): Ubuntu 22.04
OS (server): Ubuntu 20.04

Chromium -> the same problem Version 103.0.5060.53 (Official Build) snap (64-bit)

![obraz](https://user-images.githubusercontent.com/3769853/177439318-0c6cad8d-a9d4-4de5-bfbf-4f2b520e76d6.png)

**Comment by nickvergessen** [comment]
Can you inspect the website, switch to the network tab and find the request to URL that contain `/chat/` and see if you fins the one that brings the locations? The response from that request would be helpful

**Comment by pawlosck** [comment]
You meant this request?
https://XXX/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/CCC/share?limit=20&objectType=location&lastKnownMessageId=3190

If yes, response is empty
![obraz](https://user-images.githubusercontent.com/3769853/177619808-c0d4fc24-b729-445a-9fe6-1b6542d670f2.png)

**Comment by nickvergessen** [comment]
Test code

```
curl -k -u admin:admin \
    -H "OCS-APIRequest: true" \
    https://localhost/ocs/v2.php/apps/spreed/api/v1/chat/3cyxfvxm/share  -X POST \
    -d 'objectType=geo-location' \
    -d 'objectId=geo:52.5450511,13.3741463' \
    -d 'metaData={"type":"geo-location","id":"geo:52.5450511,13.3741463","latitude":"52.5450511","longitude":"13.3741463","name":"Nextcloud Berlin Office"}'

```

**Comment by nickvergessen** [comment]
Regression from f00ffac4eff3c9c45ac93e3f27024f235853d1f2
