### ISSUE TITLE
When creating a conversation it's not possible to select participants with the keyboard

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/spreed#7530]

**Comment by nickvergessen** [comment]
It is actually possible, but there is no visual indication that you are currently "hovering" a certain participant.

**Comment by Antreesy** [comment]
Possible to navigate through the list and select/deselect with `Tab`, `Shift+Tab`, `Enter`.
Is that enough for the case, or do we need an arrow navigation in addition?

https://github.com/nextcloud/spreed/assets/93392545/4aa23f0f-511e-4370-a5ff-a54d5c3ee75a
