### ISSUE TITLE
Allow to opt-out of keyboard shortcuts 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7563]
There are keyboard shortcuts for activating different functions in the Talk app. Shortcuts such as these can interfere with shortcuts used by some assistive technologies.

To follow the WCAG-requirements, and make sure that this can work with these assistive technologies the best option would be to give an option to turn off these shortcuts.

You could also make it so the shortcuts are only active when the user has focused on the area they affect.

We also recommend that you test to make sure the shortcuts don’t interfere with screen reader commands in particular (NVDA, Jaws, Orca).

### Suggested solution

* Give an option to turn off keyboard shortcuts
* Set them to only be active when the user is in the area they affect
* Test so the shortcuts don’t interfere with screen reader commands

**Comment by marcoambrosini** [comment]
Shouldn't this be an override that affects all apps in the accessibility settings?

**Comment by nickvergessen** [comment]
Could also see it like that. @ChristophWurst did you implement something in the mail app already?

**Comment by nickvergessen** [comment]
https://www.w3.org/TR/WCAG21/#character-key-shortcuts

Problem is especially shortcuts without ctrl/alt or another modifier.

So especially our mute (M), video on/off (V), push-to-talk (space), ...

**Comment by JuliaKirschenheuter** [comment]
Please make sure, that new shortcuts have no conflicts with a shortcuts of most popular screen readers (NVDA, Jaws, Orca)

**Comment by nickvergessen** [comment]
Server PR for a global setting to opt out of keyboard shortcuts to satisfy accessibility is in:
https://github.com/nextcloud/server/pull/34081

Initial state to check is: `loadState('theming', 'shortcutsDisabled', false)`

If that is `true` the app(s) must not register ANY shortcuts.
