### ISSUE TITLE
Sound notification for chat message

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/spreed#760]
Can we get a sound to play when someone types a message in the text chat portion of Talk please? It's so easy to miss that someone has typed a message right now!

**Comment by GoetheG** [comment]
This isna good idea. I really hope that you Nextcloud guys consider just adding Rocket.Chat into Nextcloud or donsomething together or whatever.

**Comment by BloodyIron** [comment]
Please don't hijack this ticket/issue...

**Comment by nickvergessen** [comment]
Sorry sound playing is not possible without user interaction, see https://github.com/nextcloud/notifications/pull/117

**Comment by BloodyIron** [comment]
Hi @nickvergessen ,

I've found a bunch of resources that talk about Sound in Push Notifications as part of the standard:
* https://web-push-book.gauntface.com/demos/notification-examples/

(many more elsewhere)

However, I do agree it seems like current browsers don't support the sound notification. And I can't find why, or when this will change.

Is there any way we could keep this issue open waiting for browsers to gain support for this? Because I really want this to eventually be added, as having non-audible notifications for spreed messages and such is really easily ignored/accidentally missed.

**Comment by nickvergessen** [comment]
Sadly it's the other way around,
Notification.sound was part of the standard and has been deprecated, that's why it's listed in "Obsolete handlers" :crying_cat_face: 
https://developer.mozilla.org/en-US/docs/Web/API/Notification#Obsolete_handlers

**Comment by BloodyIron** [comment]
So what is the long-term way we (as a society, not even just the scope of this discussion) can address this functional need?
What about using WebRTC for "notification"-esque outcomes? Ala Discord/Riot

**Comment by jookk** [comment]
sound notifications are missing on new messages. Now messaging and no new msg notification 👎  
possible someway?

**Comment by nickvergessen** [comment]
There are text notifications and browser/os notifications.

Sound is not possbile because Firefox and Chrome (both supported browsers atm) prevent playing audio without direct user interaction.

**Comment by alauzon** [comment]
FaceBook does it with Messenger. Why can't we do it also?

**Comment by honzapatCZ** [comment]
Bump, How can facebook do it while we cant?

**Comment by thecyberd3m0n** [comment]
there is no sound even if tab is opened, and loaded. I can leave opened nextcloud and allow permission, but please - just play some sound when something happens. Not from background - just normally.

**Comment by nickvergessen** [comment]
From background means without the user pressing a play button.
You can be pretty damn sure that we do it as soon as browsers allow this. Currently it's not the case 🤷‍♂️

Why can Facebook do it? Well because browsers have hardcoded lists with websites that allow this. Similar limitation was there for Screensharing on Chrome in the past, but in this case we could work around it with a Browser extension. With call sounds that doesn't work so far.

**Comment by thecyberd3m0n** [comment]
why my codepen can do it?

https://codepen.io/Noizinfected/pen/wvoMaKY

**Comment by thecyberd3m0n** [comment]
https://stackblitz.com/edit/angular-chat-bot-ehpte5?file=src%2Fapp%2Fangular-bot%2Fchat.service.ts

another example

**Comment by BloodyIron** [comment]
My own E-Mail server (Zimbra), the web interface, can trigger notification sounds. And I guarantee you the domain I own for it has not been applied to any browser-internal whitelists. So I think it's bunk that this is unachievable.

Furthermore, there are plenty of websites where they have ebedded chat support, asking "can we help you?" kind of things at random times, whether you're on the tab or not, and they often make a noise. There's no way this is on a whitelist either.

I call bunk that this cannot be done with the current state of browsers, there's plenty of evidence to the contrary.

**Comment by fancycode** [comment]
> why my codepen can do it?

Because you click on the button, i.e. there is a user action.

> I call bunk that this cannot be done with the current state of browsers, there's plenty of evidence to the contrary.

We happily accept pull requests that implement this.

**Comment by thecyberd3m0n** [comment]
I've created a live presentation using the project (with messenger feature) I'm working on. I'm using same way as on other examples, but here I'm using 2 different devices (PC and smartphone) along with websocket server which transmits messages between them.
https://webmshare.com/ea7da

**Comment by thecyberd3m0n** [comment]
> We happily accept pull requests that implement this.

seems like a challenge. Pls give me some time to put up your dev environment ;)

**Comment by honzapatCZ** [comment]
There already was an implementation doing exactly that. The PR was closed, because of this, so it isnt easily accepted.

**Comment by nickvergessen** [comment]
Im locking this issue here now to avoid further comments that just distract developers.
As per above we will do it when it's possible.

**Comment by nickvergessen** [comment]
Comment from @honzapatCZ  in https://github.com/nextcloud/spreed/issues/5096

> So the latest issue was closed, because "Evil browsers have some list of allowed sites or whatever", while I really tried, I searched thru the source of chromium and didnt find any, closest was this: https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/html/media/autoplay_policy.cc
> But thats normal policy that can be changed by the user the same as notifications at: chrome://settings/content/sound
And even that occurs only if the user didnt interact with the website at all, while if you have opened the messenger in some tab, you probably clicked thru some conversations as this is mainly to avoid spam websites that play crazy sounds and scams on load.
