### ISSUE TITLE
subfeatures on a per-user basis

### ISSUE THREAD

**Issue by amun1** [nextcloud/spreed#761]
Does/will Talk have options to enable subfeatures on a per-user basis?

Let's say I have my own nextcloud server and have enabled Talk for all (10) users, however
- for users 1 to 5 I only want to enable chat
- for users 6 to 8 I only want to enable chat and audio calls
- for users 9 and 10 I want to enable all subfeatures (chat, audio calls, video calls and screen sharing)

**Comment by GoetheG** [comment]
Well, adding to that there should be a discussion on what is being planned within Nextcloud. Is Nextcloud building an alternative to Slack and Skype? If yes, then there ahould be serious consideration on workking together with the Mattermostc, Riot.im and/or Rocket.Chat guys.

I don’t see a particular reason to add your proposed features right now until this Slack topic is still open. If the Nextcloud developers are planning a real alternative to Slacken, then we should have a different discussion.

Why do I think that Nextcloud plans a Slack alternative?
–  Nextcloue Talk was launched.
–  Integration with moodle.
–  Inteoduction of Circles and other apps

Really looking forward to seeing where you are headed.

**Comment by nickvergessen** [comment]
We are not going to do this.

We are also not going to support enabling the app for only some groups.
The problem is that we would need to give away the information to other people whether you are allowed to use the app, or they try to call you and they don't even know that you can't answer the call.

**Comment by amun1** [comment]
I don't see why giving away that information to other people would be an issue (unless it would somehow be technically difficult to implement it) but thanks for the feedback anyway.
It's a shame because people that are running a nextcloud server on low-end hardware like the raspberry pi and/or don't have high internet access speeds (or run nextcloud as a tor hidden service) won't be able to provide Talk without running into issues when multiple clients start video calling for example.

**Comment by nickvergessen** [comment]
> It's a shame because people that are running a nextcloud server on low-end hardware like the raspberry pi and/or don't have high internet access speeds (or run nextcloud as a tor hidden service) won't be able to provide Talk without running into issues when multiple clients start video calling for example.

Just for the record: traffic of video calls is not going through the nextcloud server. It's peer-to-peer (from user to user) directly.

**Comment by amun1** [comment]
Of course I remembered that **after** posting my comment.
As soon as I realised my mistake I removed my comment but apparently you beat me to it.
I must have gotten confused by the warning about Talk at https://github.com/nextcloud/nextcloudpi/wiki/Why-is-my-Pi-so-slow%3F#nextcloud-apps
