### ISSUE TITLE
Contacts already removed still appear in the list for a new call

### ISSUE THREAD

**Issue by bjarkan** [nextcloud/spreed#763]
Just give a try... create a new user... impersonate it or access with it...

Remove him/her... 

Click talk and try to choose who to invite the conference/call... voilà there he/she is... even been removed from the nextcloud

Is there a way to limit the users?... the accounts?... where it load that info from?

**Comment by nickvergessen** [comment]
The endpoint we use is from the server, so it should be the same for sharing.
Can you check and confirm?

**Comment by bjarkan** [comment]
It happen too when you try to share a file... where is the endpoint spreed/talk use to retreive users?... just to clear the user there... or to notify the component.

**Comment by nickvergessen** [comment]
Can you please create an issue in the server repository?
https://github.com/nextcloud/server/issues
