### ISSUE TITLE
Custom background image for own video in calls

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/spreed#7637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
In Talk it is currently possible to blur the background of the video being sent. However it is not possible at the moment to replace the background with a custom image instead.

**Describe the solution you'd like**
Note that [replacing the background with a custom image is already supported by the code that blurs the background](https://github.com/nextcloud/spreed/blob/9e9197cc56fd8374c4916ba1fd029721cd1a5486/src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js#L57-L61); what is missing is a UI to select the custom image (and of course adjusting the code to use the selected image).

The feature are two ways two support that and both should be present in the end, while there is no strict order
1. select an image from you Nextcloud account or upload one to you Nextcloud account to then be used (the later being an additional step to the first one
2. select an image from a predefined, talk-shipped set of background images, best to ask @jancborchardt and @nimishavijay for potential background images, usually it is nature/landscape, office and "funny" background images like space or colored balls.

**Describe alternatives you've considered**
none that I am aware of except using the blur option

**Additional context**
-

**Comment by nickvergessen** [comment]
Shipped backgrounds have the advantage we can put them into the img/ folder of the app and use them directly.

Uploaded items mean we need a public accessible endpoint which allows to access the image without any permission checks, etc. This has a lot of potential for security risks.

**Comment by AndyScherzinger** [comment]
Wouldn't you need to know the exact image name _and_ be a participant in the call/room at least?

**Comment by AndyScherzinger** [comment]
Again as stated there is no particular order, so starting with a fixed and shipped set as step one is just fine.

**Comment by danxuliu** [comment]
Note that the composition of the background image and the video is locally done in the browser of the sender participant. Other participants just receive the final video, they do not need access to the background image. Therefore the endpoint would need to be accessed only by the same participant that uploaded the image.

**Comment by jancborchardt** [comment]
For simplicity, the default images could be the ones we already ship with Dashboard (some make more sense, some less though).

Or what kinds of images would be expected there? Stock office and home working backgrounds – maybe we need to do a photoshoot? ;)

**Comment by nickvergessen** [comment]
> For simplicity, the default images could be the ones we already ship with Dashboard (some make more sense, some less though).

Since dashboard can be disabled we would duplicate them to talk.

> Or what kinds of images would be expected there?

I would suggest:
* Office
* Home-Office
* Nature
* Cinema/Theater
* something (board) gaming related

**Comment by marcoambrosini** [comment]
1st design pass done, feedback welcome. @jancborchardt @nimishavijay @nickvergessen 
Please note that the first 3 buttons in the background editor need to be designed, but they will likely be an icon + label. Will need something more complex for the custom one. 

<img width="1185" alt="Screenshot 2023-04-05 at 16 41 43" src="https://user-images.githubusercontent.com/26852655/230132819-7035d028-90f5-4177-b1f3-8217105c009b.png">

**Comment by marcoambrosini** [comment]
Ok I think I came up with a much better design for this that's way more tidy and much easier to read/scan

<img width="947" alt="Screenshot 2023-04-10 at 14 47 46" src="https://user-images.githubusercontent.com/26852655/230914038-3eb3b4ba-47dc-4d0a-a283-cf4f3ea08261.png">

**Comment by marcoambrosini** [comment]
moving design comments to #9251 as requested by @nickvergessen
