### ISSUE TITLE
My own @mention should only show first name

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#7663]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Whenever I am @mentioned with my full name, this feels too official.

**Describe the solution you'd like**
Only see "@Tobias" instead of "@Tobias Kaminsky"

**Describe alternatives you've considered**
- Ignore it 🙈
- have "@\me" instead: 
  - User xy: @\Tobias Kaminsky can you do xy" 
  - User xy: @\me can you do xy" 
  - as it would be still blue/primary color it is still easy to spot

**Additional context**
I know this might be hard(er), as we do only have "full name"

**Comment by nickvergessen** [comment]
We have a huge issue in the left sidebar already as first names are not unique. Even worse in other regions/languages. Also depending on the company climate it can be totally indiscreet and unappropriated to e.g. call the boss by their first name only, even if the software does this change.

I also think that `@me` can cause even more confusion, as we never use first person. System messages say "You added X" not "I added X". `@You can you do XY` gives a weird language feeling, so to not worsen the situation I would say we don't touch this.

@jancborchardt opinion?

**Comment by tobiasKaminsky** [comment]
🙈🙈🙈 I was not clear enough, sorry!
This was only about mentions to me.

And true, it might be for other company not ok to have the boss address you with "Hello @Tobias" instead of "Hello @Tobias Kaminsky".

**Comment by tobiasKaminsky** [comment]
Not sure how this was "limited" to left side/navigation subline (and thus also nut sure if this changes anything), but
I was only talking about chat…

**Comment by jancborchardt** [comment]
Yes, understood you were talking about the chat. :) What we were saying is:
- We should nornally use full name for several reasons like professionality, same names being a thing, it being difficult in some languages to parse first name from full display name, etc
- Only exception being the left navigation, where we use "first name" in the subline as a short version because we have space constraints
