### ISSUE TITLE
do not ask for browser permission until they are actually needed

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/spreed#769]
## Idea
The idea in my use case is to provide a simple public short-lived chat-only platform. Some users get scared when they're asked for mic/vid permissions on a chat and it doesn't give a good impression to tell them to accept even though there is not going to be an actual RTC call.

## Steps to reproduce
1. open a public call link as a guest or join a room as a registered user
2. click "join call"

### Expected behaviour
at 1. guest should see Talk window with sidebars and chat in the middle.
at 2. browser should ask for mic/vid/screenshare/etc. permission

### Actual behaviour
Browser asks for permissions even before the site at 1. is loaded. If user denies permission, site breaks (probably related to #512).

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Arch Linux

**Browser name:** Firefox, Chromium

**Browser version:** latest as of the time of writing

## Spreed app
**Spreed app version:** 3.1.0
**Custom TURN server configured:** no
**Custom STUN server configured:** no

**Comment by nickvergessen** [comment]
Duplicate https://github.com/nextcloud/spreed/pull/619
