### ISSUE TITLE
While in a call the chat doesn't keep scrolling to the end

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7690]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a call
2. Have the chat open
3. Move the window to a second screen to take notes in the other part
4. Colleagues post messages

### Expected behaviour
Chat should stay scrolled to the bottom and always show the last messages

### Actual behaviour
First message is like 80% visible and you can scroll to the bottom.
If you don't new messages are not shown

## Talk app

**Talk app version:** 14+

**Comment by nickvergessen** [comment]
So we don't scroll when the window is not focused, which is okay when the window is not visible, but if you do a recording it is rather annoying.

**Comment by SystemKeeper** [comment]
Maybe it would also make sense to use the page visibility api here... I regularly have a chat open on the second screen and it won't scroll because the window is not focused anymore 😕 
Also in a call it totally makes sense 👍

**Comment by nickvergessen** [comment]
I fear that is exactly what we are using:
https://github.com/nextcloud/spreed/blob/e454db16b0b0e96be8ac67207f01b21c731f6541/src/App.vue#L249

**Comment by SystemKeeper** [comment]
The problem is this I guess:
https://github.com/nextcloud/spreed/blob/2d3c1b294127473cad08dcc42f2c1144cb897c4d/src/components/MessagesList/MessagesList.vue#L817

We still check for focus, not the visibility: https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
