### ISSUE TITLE
[enhancement] Allow chat-only sessions (disable RTC call feature on-demand)

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/spreed#770]
As an extension to #769, it would be nice for the room admin to be able to enable/disable features selectively.

My use case is providing a simple public short-lived chat-only sessions .Disabling the "call" feature completely for a specific room (or rooms) would be nice to have as it tempts users to click the "join call" button either out of curiosity or due to misunderstanding of how the service works.

**Comment by nickvergessen** [comment]
That is nothing we want to aim for atm.
