### ISSUE TITLE
[enhancement] a guest should be asked for a name before joining a public room

### ISSUE THREAD

**Issue by cptMikky** [nextcloud/spreed#771]
Currently a guest joins a room directly when clicking the public link (and optionally enters the password). He can then change his name in the "call" tab but this doesn't update his name in chat (probably related to #722 ) and in chat the messages are still presented as coming from a "Guest". 

This gets even more confusing when more guests join the room.

I think the password dialog is the best place to put this prompt. For rooms with passwords there would be two fields, for passwordless rooms the password input can be disabled or hidden.

Adding some bells and whistles, a pseudo-random avatar could then be generated from the guest's name in a similar fashion to what Github does.

**Comment by nickvergessen** [comment]
New messages have the new guest name in the upcoming release. Existing messages are being dealt with in #722
