### ISSUE TITLE
_this.$refs.submitButton.focus is not a function

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7725]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

`ButtonVue` does not have a `focus()` method, so it can no longer [be used in the UploadEditor](https://github.com/nextcloud/spreed/blob/8edad9d5659d4a15b45550c345e36d6ac72ac3c0/src/components/UploadEditor.vue#L161). Should it be called on `submitButton.$el` instead?
```
[Vue warn]: Error in nextTick: "TypeError: _this.$refs.submitButton.focus is not a function"

found in

---> <UploadEditor> at src/components/UploadEditor.vue
       <Content>
         <App> at src/App.vue
           <Root>
```

**Comment by nickvergessen** [comment]
Fixed by #7920

Duplicated by #7860
