### ISSUE TITLE
Public call not deleted after initiator leaves

### ISSUE THREAD

**Issue by kevinkk525** [nextcloud/spreed#773]
## Steps to reproduce
1. Create a new public call from Nextcloud Talk app
2. share link and let someone join
3. leave the call within the Nextcloud Talk app (delete the call entry, so you can't enter the call anymore)

### Expected behaviour
Call should be ended for everyone and link deleted

### Actual behaviour
Every participant stays in the room and the link still works after everyone left.
That means, I have an open call on my server all the time, ready to be joined by anyone that still has the link and I do not even know how to close the call because:
- the initiator does not have it in his list anymore as he left the call
- the participants are only public people that can't close the call

This is also a security risk as you now have an unmoderated open call anyone can join.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows (public participant), Android (initiator)

**Browser name:** Firefox

**Browser version:** 59

## Spreed app

**Spreed app version:** 3.1.0

**Custom TURN server configured:** no 

**Custom STUN server configured:** no 

## Server configuration detail

**Operating system:** Linux 4.8.8-040808-generic #201611150231 SMP Tue Nov 15 07:33:21 UTC 2016 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.21

**PHP version:** 7.1.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** update from NC, OC

**Where did you install Nextcloud from:** nextcloud homepage

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - announcementcenter: 3.2.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_fulltextsearch: 0.6.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - fulltextsearch: 0.6.1
 - fulltextsearch_elasticsearch: 0.6.1
 - gallery: 18.0.0
 - impersonate: 1.0.3
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - news: 12.0.1
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - richdocuments: 2.0.5
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_external: 0.4
 - workflowengine: 1.3.0
Disabled:
 - documents
 - encryption
 - keeweb
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "filelocking.enabled": "true",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "log_rotation_size": 10485760,
    "ldapIgnoreNamingRules": false,
    "default_language": "de",
    "defaultapp": "files",
    "remember_login_cookie_lifetime": 1296000,
    "trashbin_retention_obligation": "auto",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by nickvergessen** [comment]
Duplicate of #697
