### ISSUE TITLE
Popovers can not be opened if the parent element of an open popover is removed

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7736]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

This might be caused by the focus trap and fixed with https://github.com/nextcloud/nextcloud-vue/pull/3021, but I have not checked.

## How to reproduce

- Create a conversation
- Write a message
- Hover on the message to show the message menu
- Click on the three dots menu to show the extended options (copy link, mark as unread...)
- Click somewhere outside the message and the menu

### Expected result

The menu is closed and it is possible to open it again (or any other popover)

### Actual result

The menu is closed, but it is not possible to open it again (nor any other popover)

**Comment by nickvergessen** [comment]
Can not reproduce anymore. I guess this is also the focustrap thing and is fixed with Vue beta3 at least?

**Comment by danxuliu** [comment]
[Fixed by the update to @nextcloud/vue 6.0.0-beta.3](https://github.com/nextcloud/spreed/pull/7777)
