### ISSUE TITLE
Allow to delete chat messages

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/spreed#774]
Enhancement / feature request: 

Moderator as well as user who wrote a message should be able to remove a chat message again.
Use case: somebody copy/pasted a password into the chat by accident. Legally problematic text, bad language, etc.

Should be handled in similar way as with any other messenger.

As discussed with Joas: might make sense to instead of completing deleting the line, replace it with a placeholder (i.e. some gray bar or similar) so people know that a message/line has been removed, so that other messages around that still make sense in the context.

UI-wise: a trashcan icon on the right side that appears when the user hovers over a chat line.

**Comment by diplodata** [comment]
Would it be possible to have an update on this issue?  Lack of ability to delete a message is a real problem for my users, and goes against (most) social media conventions.

**Comment by nickvergessen** [comment]
Not really planned atm, since well its a chat. What you sent can be read already

**Comment by diplodata** [comment]
OK. Well it's your app. But I'd say that "might be already read" is badly flawed logic.  @mathiasconradt makes the good point about what if you accidentally paste/post something you'd never wish to share (like a password) or even detail that you really should not share for other reasons (perhaps ethical or legal).

IMO this app is an important tool for enabling Nextcloud to seriously challenge Slack.  Enabling this functionality would be a small but important way of strengthening that challenge.

**Comment by DudleyDursley** [comment]
Deleting messages in chats isn't really unheard of. Afaik you can edit/delete messages in Slack if the admin allows it and several messaging apps even offer ephemeral messages that auto-delete themselves after a set time.
A delete function might also be used as a base for other features like a message archive management, to store only the last xyz messages or x months/years of messages.

**Comment by radoeka** [comment]
Just tried to delete a message in a chat at talk version 5.0.2, but that is not possible.
Owncloud is to give users control over their data, however in this case I can't delete messages from chat.  That really surprises me.  

Is possible to indicate when it will be possible to remove messages from the chat?

**Comment by jospoortvliet** [comment]
@radoeka this is planned for the next release, actually, we can't finish everything at once :rocket: 

But note that the guarantee of data control Nextcloud offers is by self-hosting. Reality is that another user can always take a picture of the message or copy it - this is the internet, once something is sent out  you can't take it back. You can try, but it is like MS Outlook's ability to recall emails - yeah, fun, but it won't work with my mail client and you can't erase somebody's memory or screenshots or copies they made...

**Comment by Elfanar** [comment]
I would really love to see this working.

**Comment by thecyberd3m0n** [comment]
I would like to see command to just drop whole conversation from database. I want to make it privacy feature accessible as command :)

**Comment by goekce** [comment]
Feature would also be useful for chats with a very long history. In my particular case opening a chat with a frequent chat partner takes about five seconds until Nextcloud Talk skipped to the most recent message.

**Comment by nickvergessen** [comment]
yeah, but that will be fixed with #1164 
It shouldn't require you to delete all the history everytime.

**Comment by goekce** [comment]
you are right, #1164 would definitely be *the* solution. Deletion feature would be just a workaround.

**Comment by born2webdesign** [comment]
@jospoortvliet Glad to hear about that ‘next release’ :) But—when will that come? ;) I get it that priorities may shift, but to me this is a real show-stopper. Is this still scheduled? Looking forward to it!
@nickvergessen, @goekce Right, _the_ solution—just not for the problem originally asked about here ;)

**Comment by nickvergessen** [comment]
It's currently not planned for one of the next releases due to priorities, but it was moved to backlog. Let me quote the readme:
> You can always pick a task of any of the milestones and we will help you to get it into the assigned milestone or also an earlier one if time permits. It's just a matter of having an overview and better visibility what we think should be worked on, but it's not exclusive.

**Comment by Eisteed** [comment]
Is there any eta on delete / edit message ? Kind of a must have feature for a chat application :/ ..

**Comment by nickvergessen** [comment]
See the message above yours

**Comment by Eisteed** [comment]
Thank you I can read answer from 15 Jul 2019, I just wanted to know if there was anything new on this today, I guess the answer is still no then.

**Comment by FlyGitJet** [comment]
Hi. First of all, awesome App! But i would agree, deleting or editing messages would be Note than great. I am using nextcloud Talk for a primary school right now, and we have several critical usecases for this Feature:
* Teacher is monitoring the discussion and needs to deleted wrong or inappropriate Message as moderator. He actually HAS to bei able to so this!
* Parents want to remove a Message their Child has written
* Kids tent to send wrong Messages and want to correct them. Worst Case they will be laugh at due to a Bad / wrong Message and they can't delete it

I agree, deleting does not solve the issue of someone doing local copies. But this is far less a danger then the usescases above. So currently we would love to give the Kids our own, secured Messenger, but this Feature might become a Road Blocker for us, for teachers even aus a legal aspect, despite that Talk is such a great App that really would Help our school right now.

**Comment by Nyco** [comment]
Note : Edit chat messages #1836

**Comment by HammyHavoc** [comment]
Just showing my support for implementing this. Not allowing deletion of messages in 2020 really holds Talk back from being a serious contender for us.

**Comment by kesselb** [comment]
@HammyHavoc use https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/ to show your support. Writing a comment sends a notification to everyone subscribed to this issue.

**Comment by Terrox** [comment]
> But note that the guarantee of data control Nextcloud offers is by self-hosting. Reality is that another user can always take a picture of the message or copy it - this is the internet, once something is sent out you can't take it back.

That isn't the point and I don't see why it is a reason to avoid consideration of message deletion (I've seen this on the same topic in Roll20). Just because someone might have a copy of some data doesn't mean there's no point removing it. Chat would be MUCH more useful if the admin could remove messy and wrong messages for things like Project discussions, Play-By-Post games, seminar chats and so on. The messages can be deleted in the database manually anyaway, so there is no way that anyone thinks it is a perfectly trustworthy permanent record.

**Comment by HammyHavoc** [comment]
> > But note that the guarantee of data control Nextcloud offers is by self-hosting. Reality is that another user can always take a picture of the message or copy it - this is the internet, once something is sent out you can't take it back.
> 
> That isn't the point and I don't see why it is a reason to avoid consideration of message deletion (I've seen this on the same topic in Roll20). Just because someone might have a copy of some data doesn't mean there's no point removing it. Chat would be MUCH more useful if the admin could remove messy and wrong messages for things like Project discussions, Play-By-Post games, seminar chats and so on. The messages can be deleted in the database manually anyaway, so there is no way that anyone thinks it is a perfectly trustworthy permanent record.

Consider this: Windows now includes a clipboard with history, I accidentally sent the wrong screenshot to a colleague and was unable to remove it. Imagine if I'd sent a screenshot or a piece of text with sensitive information in it. A user-facing method to delete messages is a complete no-brainer to include.

And regarding it "being the internet", not necessarily, it's quite commonly just the corporate intranet. Obviously the thing to do is to minimize the number of people that the data reaches. Imagine making an error of these proportions in a group chat of several _dozen_ people.

**Comment by Terrox** [comment]
As another point - I would prefer both edit & delete, but anything is better than nothing as is. The Chat messages are stored in the Comments table, same table as File Comments - File Comments has edit and delete already. So there is at least some reference code to work from.

**Comment by Terrox** [comment]
> is to minimize the number of people that the data reaches. Imagine making an error of these proportions in a group chat of several _dozen_ people.

Well that would actually require live editing connected participants chat windows, some of us are not concerned with that part yet - we just want the record edited regardless of what anyone's screen currently shows. Syncing the chat log would be fine I imagine though, after edit/delete sends resync command to all users - text changes.

**Comment by HammyHavoc** [comment]
> > is to minimize the number of people that the data reaches. Imagine making an error of these proportions in a group chat of several _dozen_ people.
> 
> Well that would actually require live editing connected participants chat windows, some of us are not concerned with that part yet - we just want the record edited regardless of what anyone's screen currently shows. Syncing the chat log would be fine I imagine though, after edit/delete the server sends resync command to all users - text changes.

As long as there's a user-facing option in the web and app UI for removing a message, I think it's a very important step forward for making Nextcloud Talk a serious option.

**Comment by nickvergessen** [comment]
It's not easy like with file comments, as chat messages can be federated with the matterbridge and the mobile clients fetch them once and store them locally, so that needs a separate way to update them there.

I'm locking this for now as no comments are necessary at this point.
We know the reasons to the feature (that's why it's still open).
We will fix it at some point when it reached the top of the todo list.
Until then anyone can pick it up and send a pull request to fix it.
