### ISSUE TITLE
reactions in Talk API sometimes delivered as array, sometimes map

### ISSUE THREAD

**Issue by popstr** [nextcloud/spreed#7751]
If there are no reactions to a message, that message will be delivered with `reactions: []`, which is an array of some kind. In the case where there is a reaction, the value is delivered as `reactions: {"\u2764\ufe0f":1}` which is an object/map, not an array.

PHP might parse this just fine, but in Go it's trickier (and i imagine same thing for all statically typed languages). Go expects to always get the same data type. I suppose it's possible to work around it (haven't tried and I don't use reactions right now anyway), but I think it is an example of bad API design to use different types depending on the value (empty or non-empty).

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Send 2 messages in Talk
2. React to one of the messages with an emoji
3. Get the message using Talk API
4. Notice the different types of the `reactions` field for the 2 messages

### Expected behaviour
The `reactions` field should have the same type always.

### Actual behaviour
When `reactions` is empty, it's delivered as an array. When it's non-empty, it's delivered as a json object/map.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
14 (Nextcloud 24)

**Comment by nickvergessen** [comment]
> PHP might parse this just fine

The thing is: in php they are the same thing: an array.
The only difference is whether the keys are numeric or strings. The problem is for an empty array it can not know if it would be string based if it would have entries:
https://3v4l.org/BDnWk

**Comment by popstr** [comment]
Sorry, I don't have the time to set up a custom installation of nextcloud. Anybody used to testing out pull requests for nextcloud could do it. We just need to make sure the reactions value it is always a json object (starts with "{"), no matter if the message has any reactions or not.
