### ISSUE TITLE
Custom Emoji

### ISSUE THREAD

**Issue by fuzunspm** [nextcloud/spreed#7753]
Admins or users should control, add or set custom emojis or even remove them like lgbt emoji.

**Comment by jancborchardt** [comment]
🌈 We 👭🏽 don’t ⚢ plan 🏳️‍⚧️ on ⚣ making 👬🏿 emojis ⚧️ customizable. 🏳️‍🌈

**Comment by fuzunspm** [comment]
very smart reply

**Comment by jancborchardt** [comment]
you’re welcome
