### ISSUE TITLE
Viewer FileInfo missing attributes

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#7764]
```js
vue.runtime.esm.js:4560 [Vue warn]: Missing required prop: "etag"
found in
---> <Images> at src/components/Images.vue
       <Modal>
         <Viewer> at src/views/Viewer.vue
           <Root>
```

On a secondary note, if you want to be able to use the editor in Viewer, [please also provide the permission attribute](https://github.com/nextcloud/viewer/blob/cffe295c9e9bae1903cfc3081b18a1d1d8232f14/src/views/Viewer.vue#L270-L274) https://github.com/nextcloud/spreed/blob/05d663e4ac908d6643f5dc15d20c7f4bd06d8e1d/src/components/MessagesList/MessagesGroup/Message/MessagePart/FilePreview.vue#L451-L463

**Comment by nickvergessen** [comment]
> this.currentFile?.permissions?.includes('W')

We currently only have the number permissions so I guess we need to translate them...

**Comment by nickvergessen** [comment]
> vue.runtime.esm.js:4560 [Vue warn]: Missing required prop: "etag"

I can also not reproduce this. Is it new from upcoming work?
