### ISSUE TITLE
Unclear paging when getting chat messages

### ISSUE THREAD

**Issue by popstr** [nextcloud/spreed#7765]
Not sure if this is a bug or I am misunderstanding the API docs, but let's find out.

Let's say I have a chat conversation with >200 messages and I want to get them all. In the docs i read that I can use the `lastKnownMessageId` parameter for this and after making a request I can get the message id for the next page by reading the `X-Chat-Last-Given` header of the response.

(Docs say this:
"lastKnownMessageId: Serves as an offset for the query. The lastKnownMessageId for the next page is available in the X-Chat-Last-Given header."
https://nextcloud-talk.readthedocs.io/en/latest/chat/#receive-chat-messages-of-a-conversation
)

When i do this, i set `lastKnownMessageId` to `0` for the first request. I get 200 messages as expected and a number in the `X-Chat-Last-Given` header.
In this case i get messages from id `1243` to `1044` with the _newest message first_. `X-Chat-Last-Given` header in the response is `1044`.
Then I want to get the rest of the messages (older than `1044`), but if I send `lastKnownMessageId=1044` to the API I will only get the messages newer that this id, which is the very same messages that I already got.

How is this paging supposed to work? If it was sorted the other way around it could work. But now I have no idea what to set `lastKnownMessageId` to. `0` only gets me the newest ones, `1044` gets me the same ones over again, and I can't just make a wild gess.

Did i misunderstand how to use the API or is this a bug in the API design?

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a chat room and fill it with >200 messages
2. Try to get all messages using the API...

### Expected behaviour
I should be able to get all messages of a conversation using some sort of pagination.

### Actual behaviour
I am only able to get the latest 200 messages.

## Talk app

**Talk app version:**
14

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.1

**Nextcloud Version:** 24.0.1

**Comment by popstr** [comment]
Ok, i can see now that this has to do with the `lookIntoFuture` parameter. If I set this to 0, then the paging works as expected. If i set it to 1, it works like i have described.
This could be pointed out in the docs, but to me it seems that the difference in behavior between `lookIntoFuture=1` and ´0´ is enough to split this endpoint into 2 separate. Right now the behaviors for different combinations is complex and confusing imho.

**Comment by nickvergessen** [comment]
> but to me it seems that the difference in behavior between lookIntoFuture=1 and ´0´ is enough to split this endpoint into 2 separate. 

While that might be true, it does not help as we then just need to maintain multiple endpoints that do the same thing due to our policy about backwards compatibility.
Sorry that you had such a hard time with it, but I'm glad you now figured it out.

> This could be pointed out in the docs

Any suggestion for what exactly to add/reword?
