### ISSUE TITLE
Component maintainability needs to be recovered

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7830]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

We have several issues at the moment which makes it very hard to find the correct spot to do some things.

- [ ] NewMessageForm is ~1k lines and not maintainable anymore, but also it contains a lot of features that could just be split into new subcomponent
    - [x] Extract modal with file template picker
    - [x] AdvancedInput should die in favor of RichContentEditable #4333
- [x] MessagePart/Poll.vue contains the Modal, but should only be the card/Button - https://github.com/nextcloud/spreed/pull/11448
    - [x] Voting/result modal should be a new component containing the logic and not be part of a MessagePart component.
- [ ] Settings dialog has so many different sections we should group them by usecase (why is guests and meetings so far apart?)
    - [x] Also renaming should be moved inside

**Comment by Antreesy** [comment]
Mostly done, rest is tracked in https://github.com/nextcloud/spreed/issues/11200
