### ISSUE TITLE
C&P modal -> enter does not send image message

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#7860]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. copy an image, e.g. via screenshot tool
2. select text input field
3. press ctrl + v
4. see dialog 
5. press enter

### Expected behaviour
"message" should be sent -> image pasted into chat

### Actual behaviour
enter does nothing, one has to click on "submit"

## Talk app

**Talk app version:** found on c.nc.c

**Comment by nickvergessen** [comment]
> enter does nothing, one has to click on "submit"

It doesn't to "nothing" but now closes the modal as the close button is focused for keyboard input.

Maybe we can/should focus the submit button (especially for pasting image/file content)

**Comment by tobiasKaminsky** [comment]
Closing the modal is even more worse than doing nothing, imho :)
Enter should be the primary action (sending/submitting) and Esc closing/exiting modal.

**Comment by nickvergessen** [comment]
Related: #7725

**Comment by nickvergessen** [comment]
Fixed by #7920
