### ISSUE TITLE
Call connections sometimes fail to be established when using the internal signaling server and PostgreSQL

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7863]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

When the internal signaling server is used the signaling messages are stored in the database when sent, and then read from the database when fetched by the target participant. In order to establish a call connection some signaling messages must be received in the same order that they were sent (the remote description must be processed before processing the remote candidates); otherwise the connection can not be established. However, when using PostgreSQL the input and output order can be different, and when that happens the signaling messages are received in the wrong order, thus causing the connection to not be established.

**Comment by nickvergessen** [comment]
Should be rather easy. We can sort by the autoincrement in
https://github.com/nextcloud/spreed/blob/c07251f0c67d3c02debe1f6dbe0e12ee3fe9f99a/lib/Signaling/Messages.php#L128-L132

or sort the array by the id before returning.
