### ISSUE TITLE
Adapt talk mentions widget for mobile clients

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#7867]
### Is your feature request related to a problem? Please describe.

With https://github.com/nextcloud/server/pull/33658 mobile clients can access app widget data.

### Describe the solution you'd like

Adapt the *upcoming cards* widget to https://github.com/nextcloud/server/pull/33658 once it's done.

### Blocked by

* https://github.com/nextcloud/server/pull/33658

**Comment by tobiasKaminsky** [comment]
If someone can give me a hint how to retrieve, I can also give it a try.

I think this is where the current dashboard widget fetches the data, right?
https://github.com/nextcloud/spreed/blob/45cb031bb619fc0b935694bd7a4bf16889f1eafd/src/views/Dashboard.vue#L184

**Comment by nickvergessen** [comment]
> I think this is where the current dashboard widget fetches the data, right?

yes. But it will not be trivial to duplicate the API in a useful manner. I will have a look later this week.
