### ISSUE TITLE
followed participant is not "framed" like the current speaker in the speaker mode.

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#7879]
The followed participant is not "framed" like the current speaker in the speaker mode. Is that known/expected or should I open a new issue for that?
![Talk-Call-Speaker-Mode-Default-Framed](https://user-images.githubusercontent.com/26858233/189314918-731e5a09-9788-444e-8863-e5bdde1317cd.png)
![Talk-Call-Speaker-Mode-Following-Not-Framed](https://user-images.githubusercontent.com/26858233/189314974-6e837d45-a452-45db-b045-e0d2ac40c4f4.png)

_Originally posted by @danxuliu in https://github.com/nextcloud/spreed/pull/7868#pullrequestreview-1101964260_

**Comment by nickvergessen** [comment]
Works fine here.
![Peek 2022-09-14 11-03](https://user-images.githubusercontent.com/213943/190111060-c7437ff2-264e-4dbd-ba8b-a4902c0bda1d.gif)

Can you still reproduce @danxuliu ?

**Comment by danxuliu** [comment]
Yes, this can still be reproduced, but it only happens when there are two participants in the call.
