### ISSUE TITLE
Some modals can not be closed by clicking on the X

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7891]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce (scenario 1)
- Create and close a poll
- Show the poll results
- Click on the `X` icon in the modal

### Expected behaviour
The modal is closed

### Actual behaviour
The modal is not closed

## Steps to reproduce (scenario 2)
- Upload a file to the conversation or record a voice message
- In the modal shown to confirm/customize the upload, click on the `X` icon

### Expected behaviour
The modal is closed

### Actual behaviour
The modal is not closed

**Comment by nickvergessen** [comment]
I guess there is a zindex added somewhere on our end, seeing the broken popover in the other ticket seem to confirm something alike

**Comment by marcoambrosini** [comment]
Fix here https://github.com/nextcloud/nextcloud-vue/pull/3230

**Comment by nickvergessen** [comment]
So closing
