### ISSUE TITLE
Poll voters details are shown behing the poll results modal

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7892]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

![Talk-Poll-Results-Popup-Behind-Modal](https://user-images.githubusercontent.com/26858233/189577514-7e218c09-b5d3-4cab-b12d-483a2025c470.png)

**Comment by nickvergessen** [comment]
Seems to be fixed now for me
![Bildschirmfoto vom 2022-09-13 10-05-26](https://user-images.githubusercontent.com/213943/189846224-a1fb42a2-a36e-436e-aca1-7ef7c99be8fe.png)

Maybe it was the missing containers in #7897 ?

**Comment by danxuliu** [comment]
Yes, this was fixed by #7897
