### ISSUE TITLE
File previews are cropped in modal to confirm/customize the upload

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7894]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
![Talk-Upload-Modal-Files-Overflow](https://user-images.githubusercontent.com/26858233/189578615-281f234b-bf39-45ae-8d51-9b3e438ea3eb.png)

**Comment by nickvergessen** [comment]
Fixed with #7965
