### ISSUE TITLE
Admin confirmation breaks the settings

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7902]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Go to admin settings
2. Toggle the warning checkbox

### Expected behaviour
✨ 

### Actual behaviour
![Peek 2022-09-13 12-15](https://user-images.githubusercontent.com/213943/189876269-067912f1-a1aa-46f5-bf75-94c728aa35f9.gif)

Might or not be fixed by https://github.com/nextcloud/server/pull/34044

**Comment by PVince81** [comment]
@Pytal FYI

**Comment by nickvergessen** [comment]
Still happening

**Comment by Pytal** [comment]
Cannot reproduce on server `master` and spreed `master`

The code paths for `OCP.AppConfig.setValue()` use the legacy `OC.PasswordConfirmation.requirePasswordConfirmation()`

**Comment by nickvergessen** [comment]
Interesting:
Also the text inputs use `OCP.AppConfig.setValue()` and there the bug does not occur. 🤔

**Comment by nickvergessen** [comment]
That being said, let me try to move the checkbox to NcCheckboxRadioSwitch to see if that removes the bug.

**Comment by nickvergessen** [comment]
Seems to work https://github.com/nextcloud/spreed/pull/7958
