### ISSUE TITLE
NC 25 Copy Link not working on Group Conversations

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#7909]
## Steps to reproduce
1. Create a Group Conversation
2. Allow guests to join via link
3. Copy Link 
4. conversation Link copied to clipboard
5. Try to paste 
6. No link

### Expected behaviour
should copy the link 

### Actual behaviour
No working even tho it says it was copied

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
15.0.0-beta.3
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Windows
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Might be solved by #7910

**Comment by nickvergessen** [comment]
PS: All vue-clipboard2 interactions seem broken in Chromium and Firefox

**Comment by marcoambrosini** [comment]
I did some digging and I don't quite understand what's going on here. The vue2-clipboard promise is fulfilled but no text is added to the clipboard. 
I tried doing it manually by creating an offscreen `textarea` and using `document.execCommand('copy')` and I get the same result: promise fulfilled and no text copied. 
@danxuliu could we have a look together at this?

**Comment by nickvergessen** [comment]
Vue lib issue raised in https://github.com/nextcloud/nextcloud-vue/issues/3275

**Comment by raimund-schluessler** [comment]
The problem is likely the focus-trap of the popover which interferes with these hacky `document.execCommand('copy')` solutions. I would say the proper way is to switch to `navigator.clipboard.writeText()`, see e.g. https://github.com/nextcloud/tasks/pull/2115 which fixes the issue for Tasks.
