### ISSUE TITLE
If all messages expire, the chat shows the loading animation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7919]
When all messages are "Expired" the chat shows the loading animation instead of an empty content message. But that also needs cross verification with the mobile apps, so it's good to manage it additionally.
![Bildschirmfoto vom 2022-09-14 14-24-50](https://user-images.githubusercontent.com/213943/190152647-4923e598-f204-44e4-a3bd-4ebd64fa886b.png)

Patch for testing:
```diff
diff --git a/lib/Model/Message.php b/lib/Model/Message.php
index d888d0133..5e8202961 100644
--- a/lib/Model/Message.php
+++ b/lib/Model/Message.php
@@ -192,7 +192,7 @@ class Message {
                        'isReplyable' => $this->isReplyable(),
                        'referenceId' => (string) $this->getComment()->getReferenceId(),
                        'reactions' => $reactions,
-                       'expirationTimestamp' => $expireDate ? $expireDate->getTimestamp() : 0,
+                       'expirationTimestamp' => time() + 5, //$expireDate ? $expireDate->getTimestamp() : 0,
                ];
 
                if ($this->getMessageType() === ChatManager::VERB_MESSAGE_DELETED) {
diff --git a/src/components/MessagesList/MessagesList.vue b/src/components/MessagesList/MessagesList.vue
index 0bd7b689d..293fa616c 100644
--- a/src/components/MessagesList/MessagesList.vue
+++ b/src/components/MessagesList/MessagesList.vue
@@ -272,7 +272,7 @@ export default {
                 */
                this.expirationInterval = window.setInterval(() => {
                        this.removeExpiredMessagesFromStore()
-               }, 30000)
+               }, 3000) // FIXME }, 30000)
        },
 
        beforeDestroy() {
```

- [ ] Web
- [x] Android @timkrueger 
- [ ] iOS App @Ivansss

**Comment by timkrueger** [comment]
On Android it looks like that:

<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td><img width="300" src="https://user-images.githubusercontent.com/606665/190337879-55977bce-c1c8-485c-8a31-176b14af94a2.png" /></td>
    <td><img width="300" src="https://user-images.githubusercontent.com/606665/190337884-0ec77388-c38c-4885-b27b-fbb95bca47be.png" /></td>
  </tr>
</table>

Beside the fact that the system messages are duplicated, it is OK I think. Maybe this is related with this issues:
- https://github.com/nextcloud/talk-android/issues/2171
- https://github.com/nextcloud/talk-android/issues/2060

**Comment by nickvergessen** [comment]
Can you check the following steps:

* Create conversation
* Set up message expiration
* Clear chat history
* Wait amount of the expiration
* Open the chat (and there should be 0 chat messages and system messages in it)

Does that render properly?

**Comment by timkrueger** [comment]
> Can you check the following steps:
>
> ... 
> 
> Does that render properly?

That's the result:

<img width="300" src="https://user-images.githubusercontent.com/606665/190423660-4aad43e7-d29c-4446-a6c7-fa7c5c2bf1ab.png" />

**Comment by nickvergessen** [comment]
@marcoambrosini I guess it's not okay to be completely empty? Do we need an empty content thing?

**Comment by Ivansss** [comment]
On iOS the "old" chat placeholder is shown if there are no messages in the chat.

![IMG_0135](https://user-images.githubusercontent.com/4638605/191305921-be17e767-6cb8-4aa2-83a0-5d32ff4f49a7.PNG)

**Comment by nickvergessen** [comment]
Maybe we can align the empty content messages.

This is my proposal for now:
![Bildschirmfoto vom 2022-09-21 07-07-35](https://user-images.githubusercontent.com/213943/191418889-410d2b37-4ed6-4c64-b87e-129887fa275e.png)
