### ISSUE TITLE
preview sizes are inconsistent and grey background looks not nice

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/spreed#7921]
The previews of odt, ods and md files are not the same. In different situations I saw different preview sizes. 
In general they are way too big IMHO Half the size would be fine from my perspective. 

Also the mouse over grey background doesn't look good and is a lot bigger than the actual document preview.  

<img width="1238" alt="Screenshot 2022-09-14 at 18 25 03" src="https://user-images.githubusercontent.com/867445/190210599-c3d96ac3-cbdf-445b-a847-f4e748d50285.png">

This is on tech-preview from today

**Comment by karlitschek** [comment]
@jancborchardt

**Comment by nickvergessen** [comment]
They used to be much smaller. Definitely not intended

**Comment by nickvergessen** [comment]
Size fix in https://github.com/nextcloud/spreed/pull/7960

The grey hover is actually from the message container and I'm not sure we can fix that easily at the moment.
