### ISSUE TITLE
no option to create poll in 1:1 chat

### ISSUE THREAD

**Issue by mahibi** [nextcloud/spreed#7934]
### Expected behaviour
option to create poll is visible.

fix
https://github.com/nextcloud/spreed/blob/737741cd68d00b94c1164cdf9acbbda3a5d80b8f/src/components/NewMessageForm/NewMessageForm.vue#L359-L362
and check that the user has posting permissions

### Actual behaviour
no option to create poll

**Comment by nickvergessen** [comment]
Also the posting permission check is missing for attachments

**Comment by marcoambrosini** [comment]
I don't think polls should be a thing in 1:1
