### ISSUE TITLE
error posting chat message via api - TypeError: XMLWriter::writeElement(): Argument #2 ($content) must be of type ?string, stdClass given at /var/www/html/lib/private/AppFramework/OCS/BaseResponse.php#148

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/spreed#7952]
I post messages from a Python script to a chat on my Nextcloud server using [the api](https://nextcloud-talk.readthedocs.io/en/turn_doc/chat/#sending-a-new-chat-message).

I'm seeing a new error every time I post a message. The error shows up in my main Nextcloud server log, and it seems to have started when I upgraded the Talk app to version 14.0.5 on Thu Sep 15.

The error is: `TypeError: XMLWriter::writeElement(): Argument #2 ($content) must be of type ?string, stdClass given at /var/www/html/lib/private/AppFramework/OCS/BaseResponse.php#148`.

Here's the full error message from my `nextcloud.log` file (redacted and formatted for readability):

```json
{
    "reqId": "redacted",
    "level": 3,
    "time": "2022-09-15T20:20:04+00:00",
    "remoteAddr": "redacted",
    "user": "redacted",
    "app": "PHP",
    "method": "POST",
    "url": "/ocs/v2.php/apps/spreed/api/v1/chat/redacted",
    "message": "TypeError: XMLWriter::writeElement(): Argument #2 ($content) must be of type ?string, stdClass given at /var/www/html/lib/private/AppFramework/OCS/BaseResponse.php#148",
    "userAgent": "python-requests/2.20.0",
    "version": "24.0.5.1",
    "data": {
        "app": "PHP"
    }
}
```

The message still shows up in the chat room despite the logged error.

My Nextcloud server is running in a Docker container from a `24.0.5-apache` image.

On the client side, I get an HTTP 200 response with nothing in the body. I'm using code [almost exactly like this](https://github.com/nextcloud/spreed/issues/1879#issuecomment-584407332) to send messages and my code hasn't changed since Dec 2021.

Hopefully this is enough info to point to the culprit. I'm happy to provide more debugging information or a stand-alone repro if necessary.

Note the response status code is 200 but [the docs say it should be 201](https://nextcloud-talk.readthedocs.io/en/turn_doc/chat/#sending-a-new-chat-message).

**Comment by nickvergessen** [comment]
I guess it's because of https://github.com/nextcloud/spreed/commit/df021e8019bf79072592b7756e3928cea9e55376 ?

**Comment by nickvergessen** [comment]
can you try to revert that to see if it fixes it?

**Comment by nickvergessen** [comment]
Patch at https://github.com/nextcloud/spreed/pull/7954

**Comment by meonkeys** [comment]
> can you try to revert that to see if it fixes it?

Yep, that seems to fix it. After reverting that commit I no longer see the error message logged.
