### ISSUE TITLE
Focus-trap is not working (and throws error on console) for permissions editor and new conversations dialog

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7970]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the new conversations dialog
2. Check browser console ❌ 
3. Add a participant
4. Open the participant menu
5. Open the permissions editor
6. Check browser console ❌ 

Also ref #7701

**Comment by Antreesy** [comment]
Checked all NcModals and NcPopovers
Last one will be fixed with mentioned PR

**Comment by Antreesy** [comment]
Solved upstream, no more errors
