### ISSUE TITLE
Hover state of reactions missing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7989]
So it's not possible anymore to see who reacted

**Comment by tobiasKaminsky** [comment]
It works when I first add  a reaction, e.g. then there are 3 :+1: and it says "xy, zz any you".
As soon as I remove my own reaction, I cannot see it.

**Comment by nickvergessen** [comment]
Findings:
* The data is always loaded from the API
* Problem seems to be that `trigger="hover"` is not understood anymore by the popover:
https://github.com/nextcloud/spreed/blob/c0ea9d22b775ea5c29a81d16f79c0dc28ee37506/src/components/MessagesList/MessagesGroup/Message/Message.vue#L138

**Comment by nickvergessen** [comment]
So it's a regression from https://github.com/nextcloud/nextcloud-vue/pull/2600
But I wonder why we didn't notice it during the dev time :(
