### ISSUE TITLE
Settings disappear after activating the lobby

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/spreed#7997]
## Steps to reproduce
1. Open conversations settings 
2. Enable lobby

### Expected behaviour
The settings in  the settings view will stay.

### Actual behaviour
The settings in the settings view disappear. See the screencast:

[Screencast from 23.09.2022 11:37:40.webm](https://user-images.githubusercontent.com/606665/191937597-f31d65b1-416f-4929-abc3-fad9107b0e3a.webm)

## Talk app

Sermo as of today

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Fedora 36

**Browser name:** Firefox

**Browser version:** 104.0.2 

## Server configuration

Sermo as of today

**Comment by nickvergessen** [comment]
Doesn't happen locally. So updating sermo to include #7975

**Comment by nickvergessen** [comment]
Seems to still happen...

**Comment by nickvergessen** [comment]
Can now reproduce... seems the chat or sidebar need some content
