### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#801]
![image](https://user-images.githubusercontent.com/16019165/39092195-8541511e-4608-11e8-8930-10a825240000.png)

The context menu is cut off in the middle.

The Guest is the last entry in the list (maybe this is the issue?!).

**Comment by Ivansss** [comment]
Thanks for the report @BornToBeRoot :)
This issue has been already fix in #745  and will be added in the next release.
