### ISSUE TITLE
occ talk:active-calls: wrong return code when there is one or more active calls

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#8014]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Run `occ talk:active-calls` when at least a call is going on
2. Check the return code (from a shell command line: `echo $?`)

### Expected behaviour
The return code of the command should be 0, if the command is successful.

### Actual behaviour
The return code is 0 only if there are no active calls. Note that a wrong return code may break external programs that run the program in batch mode, for example, for monitoring purposes. In my case it was Python's subprocess.check_output.

## Talk app

**Talk app version:** 14.0.5

## Server configuration

**PHP version:** 8.1

**Nextcloud Version:** 24.0.5

**List of activated apps:**

**Comment by nickvergessen** [comment]
> Note that a wrong return code may break external programs that run the program in batch mode, for example, for monitoring purposes.

This is exactly what we use it for on our instance. We cancel our upgrade attempt when there is an active call.

We could change this now for 25 where we allow to get machine readable data from the command:
* https://github.com/nextcloud/spreed/pull/7986

Or replace it with an option like `--exist-non-zero-when-active` and then properly document it in the changelog.
