### ISSUE TITLE
Poll view can't be closed with a click on `X`

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/spreed#8024]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

![image](https://user-images.githubusercontent.com/606665/192502985-3e26dfed-583f-4995-bfbe-d2ded0da7242.png)

## Steps to reproduce
1. Open a poll
2. Click on the `X` in upper right corner.

### Expected behaviour
The `X`  is highlighted when moving the mouse pointer over it. And a click closes the view.

### Actual behaviour
The `X` is not highlighted when moving the mouse pointer over it. And a click don't closes the view.

**Comment by nickvergessen** [comment]
This is fixed, but sermo is still breaking on pulling master. For now click on the background or use `ESC` key
