### ISSUE TITLE
Left sidebar and main content jump

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#8029]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. ??? I think I switched convos ???

### Expected behaviour

The usual UI

### Actual behaviour

![Bildschirmfoto vom 2022-09-27 16-10-32](https://user-images.githubusercontent.com/1374172/192550242-851cd5d7-ac1a-490c-b3cc-5029f27707fc.png)
![Bildschirmfoto vom 2022-09-27 16-10-18](https://user-images.githubusercontent.com/1374172/192550248-429a7df4-d552-4184-8f76-2423d607cc8c.png)

## Talk app

**Talk app version:** latest on 25

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by ChristophWurst** [comment]
As I try to inspect the DOM the elements jumped back. Browser bug?!

**Comment by nickvergessen** [comment]
Did you resize the window? That is known to break all kind of things:
https://github.com/nextcloud/nextcloud-vue/issues/3289

**Comment by ChristophWurst** [comment]
No, I didn't

**Comment by nickvergessen** [comment]
Let's see if it continues to happen after the position sticky change in the vue lib

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-10-06 11-40-38](https://user-images.githubusercontent.com/1374172/194280622-0b1c5fae-55d9-4bdb-9888-41b7b992246d.png)

Just happened on our internal instance. This is the highest jump I've ever seen :1st_place_medal:

**Comment by nickvergessen** [comment]
Also on conversation switching?

Seeing the right sidebar continuing through out the screenshot, I still assume that it can be related and fixed by https://github.com/nextcloud/nextcloud-vue/pull/3309

**Comment by CarlSchwan** [comment]
Happens to me all the time when i switch back to talk after 1 or 2 hours having talk in the background 😔

Firefox 105

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3309 was still not merged, so still having high hopes on that one.

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-11-03 18-00-19](https://user-images.githubusercontent.com/1374172/199786425-e18c97b1-e893-48b5-bb38-6af8bb2244af.png)



> [nextcloud/nextcloud-vue#3309](https://github.com/nextcloud/nextcloud-vue/pull/3309) was still not merged, so still having high hopes on that one.

Is that shipped already?

**Comment by nickvergessen** [comment]
We just downgraded to vue 7.0.0 for todays release: https://github.com/nextcloud/spreed/pull/8274
As the 10+ seconds waiting time until the NcModal appears to join a call was not acceptable

**Comment by ChristophWurst** [comment]
> This is the highest jump I've ever seen 1st_place_medal

![Bildschirmfoto vom 2022-11-17 13-42-22](https://user-images.githubusercontent.com/1374172/202449442-3033d6ad-924d-4c68-8618-14592cf8eee3.png)

New record set today

**Comment by ChristophWurst** [comment]
![Bildschirmfoto vom 2022-11-30 12-52-54](https://user-images.githubusercontent.com/1374172/204789535-08de547a-96ef-4573-974d-67c785252b2d.png)

does our shared instance have the update already?

**Comment by nickvergessen** [comment]
No

**Comment by nickvergessen** [comment]
Now finally merged with #8405 and released with some follow up hacks for regressions in the vue lib as 15.0.2

**Comment by ChristophWurst** [comment]
I haven't had the issue for a few weeks but it returned a few days ago. Does that correlate with any app/package updates?

**Comment by nickvergessen** [comment]
15.0.3 which ships `@nextcloud/vue` 7.4 was released (and I guess deployed) ~2 weeks ago.
Maybe the vue lib had another regression?
