### ISSUE TITLE
Displaying browser menu makes the right side bar jump

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/spreed#8034]
In Firefox, pressing Alt key to display the top menu bar makes the right side bar in Talk jump.

![image](https://user-images.githubusercontent.com/87175513/192775863-5802aa31-a016-4e2e-82bf-a7ab71cbdf2c.png)

c.nc.com

**Comment by nickvergessen** [comment]
Any resizing of the content causes this. It's a bug in the Vue lib

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/3289

PR with a potential fix is in the vue repo
