### ISSUE TITLE
Message search results only show who sent a message, but now in which chat

### ISSUE THREAD

**Issue by jld3103** [nextcloud/spreed#8056]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Message search results only show who sent a message, but now in which chat.

**Describe the solution you'd like**
The icon and title should be the one of the room and the message text should be prefix with something like `You:` or `{name}:`

**Describe alternatives you've considered**
Only changing the title and the icon would make it worse because then it shows in which chat the message was but not who sent it.

**Additional context**
This is for the web interface and also the Android client, haven't checked if iOS is also affected, but probably yes because the search results don't contain enough information right now to properly display the described solution. See https://github.com/nextcloud/talk-android/issues/2412

**Comment by nickvergessen** [comment]
Please note that there are 2 search blocks while you are in a conversation.

The first block is the current conversation and only shows the author.
The second block is "other" conversations and shows "AUTHOR in CHAT"

![grafik](https://user-images.githubusercontent.com/213943/193281948-eec50278-c5f7-40d6-8978-554dfa1c7d75.png)
