### ISSUE TITLE
Public password conversations layout miss aligned 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed#8060]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create Public Share with password
2. Go to public share to enter password
3.

### Actual behaviour
![image](https://user-images.githubusercontent.com/59488153/193346736-2c6c0de4-6794-4d11-8670-7b3e2b1015e0.png)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
14.0.5
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

## Browser

**Microphone available:** yes/no
Yes
**Camera available:** yes/no
Yes
**Operating system:** Windows/Ubuntu/...
Windows 11
**Browser name:** Firefox/Chrome/...
Chrome, Edge, Firefox
**Browser version:** 85/96/...

**Operating system**: Ubuntu/RedHat/...
Ubuntu 22.0.4
**Web server:** Apache/Nginx
Apache2
**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB 10.6.7
**PHP version:** 7.4/8.0/8.1
8.1
**Nextcloud Version:** (see admin page)
24.0.5

```
Insert your server log here
```
</details>

**Comment by andyxheli** [comment]
Added the following and it fixed the issue. Do you now where in the code i can ad these so i can create a pull request ?  

input[type='text']+.icon-confirm:disabled, input[type='password']+.icon-confirm:disabled, input[type='email']+.icon-confirm:disabled {
    position: absolute;
    top: 0px;
    right: -5px;
    width: 45px !important;
    height: 45px;
    background-color: transparent !important;

**Comment by Antreesy** [comment]
It requires backport of a style rule at nextcloud/server to stable24: https://github.com/nextcloud/server/blob/253118298dbac78d13c5333279def8bbd3ad555c/core/css/guest.css#L245-L249

```css
.icon-confirm.input-button-inline {
	position: absolute;
	right: 3px;
	top: 5px;
}
```

But file wasn't updated for a year, didn't we reach the EOL till the moment?

**Comment by nickvergessen** [comment]
3 days ago, yes
