### ISSUE TITLE
Mobile app usage wrongly triggers rate limit

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8083]
Currently both places, the hotel as well as the venue, are being brute force protected and are throttled heavily.
We register more than thousand failed attempts per day, but I don't think someone is trying to hack something. So my current assumption is that some kind of session expiration or something kicks in, which then means the apps try to access a room without permissions.

**Comment by dell-mic** [comment]
Hi,

not sure if this is technically related, but I am experiencing quite frequently the error:
```
There were too many requests from your network. Retry later or contact your administrator if this is an error.
```

This shows for Talk only and not for other apps of the same instance.

This is a personal Nextcloud instance only used by a few people.

It could be coincidence, but the first time I noticed this error I was trying running Talk from within Rambox (https://rambox.app/) in addition to a normal browser window for other apps.

Let me know if I can help with further information.

Thanks a lot & best regards,
Michael

**Comment by nickvergessen** [comment]
Current assumption is that this is influenced also by:
* https://github.com/nextcloud/spreed/issues/8328 and
* #8712

So closing for now until it happens again and we have more hints
