### ISSUE TITLE
Converstation Management API returns empty string instead of xml

### ISSUE THREAD

**Issue by matzexcom** [nextcloud/spreed#8108]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

After updating from 14.0.4 to 14.0.5 the endpoints from talk don't return XML OCS Results.

## Steps to reproduce
1. Install Nextcloud with Talk APP
2. Call "Creating new Conversation" Endpoint (https://nextcloud-talk.readthedocs.io/en/latest/conversation/#creating-a-new-conversation)
3. Return value is an empty string

### Expected behaviour
Conversation Management API returns XML OCS Result

### Actual behaviour
An empty string is returned after API request

## Talk app

**Talk app version:** 14.0.5

**Custom Signaling server configured:** no 

**Custom TURN server configured:** no 
**Custom STUN server configured:** no

## Browser
 not needed

## Server configuration

**Operating system**:  Linux 5.4.0-123-generic x86_64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.0.23

**Nextcloud Version:** 24.0.5

**List of activated apps:**

<details>

```


Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - admin_audit: 1.14.0
 - circles: 24.0.1
 - cloud_federation_api: 1.7.0
 - comments: 1.14.0
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_pdfviewer: 2.5.0
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - firstrunwizard: 2.13.0
 - groupfolders: 12.0.1
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - nextcloud_announcements: 1.13.0
 - notifications: 2.12.1
 - oauth2: 1.12.0
 - password_policy: 1.14.0
 - photos: 1.6.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - recommendations: 1.3.0
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - spreed: 14.0.5
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - twofactor_backupcodes: 1.13.0
 - updatenotification: 1.14.0
 - user_status: 1.4.0
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - workflowengine: 2.6.0
Disabled:
 - encryption
 - files_external
 - user_ldap


```

</details>

**Nextcloud configuration:**

<details>

```

{
  "system": {
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
      "*"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.5.1",
    "overwrite.cli.url": "http:\/\/nextcloud.p601723.webspaceconfig.de\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "default_language": "de",
    "default_locale": "de_DE",
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "pipe",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "check_for_working_wellknown_setup": false,
    "maintenance": false,
    "loglevel": 2
  }
}

```
</details>

### Server log (data/nextcloud.log)
<details>

```
[PHP] Fehler: TypeError: XMLWriter::writeElement(): Argument # 2 ($content) must be of type ?string, stdClass given at /html/nextcloud/lib/private/AppFramework/OCS/BaseResponse.php#148

POST /ocs/v2.php/apps/spreed/api/v4/room
from 95.91.234.152 by p601723 at 2022-10-06T14:10:31+00:00
```
</details>

**Comment by nickvergessen** [comment]
There should be something in the nextcloud.log file giving us a hint.
Then again, the top of the conversation api documentation page has a warning about incompatibility with XML.

In general the XML source is more like deprecated. if you use `ocs/v2.php/` the default layout is JSON and that is also what we test and use in our clients.

Out of curiosity: What of tool/client are you developing?
Would it be possible to use the JSON format?

**Comment by nickvergessen** [comment]
Urgh, we had fixed this already. Just forgot to backport:
https://github.com/nextcloud/spreed/pull/7954

**Comment by nickvergessen** [comment]
Fixed as per above
