### ISSUE TITLE
Make mentions to current user more prominent

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#811]
Currently all mentions are shown the same: bold text with _@_ followed by the display name of the user.

![chat-mention-original](https://user-images.githubusercontent.com/26858233/39241391-04eb4d86-4887-11e8-9aae-18dc868a0053.png)

Mentions to the current user should be more prominent so you can easily see where you are mentioned.

This could be done by highlighting the mention itself to the current user:

![chat-mention-highlight-current](https://user-images.githubusercontent.com/26858233/39241400-0b6622e4-4887-11e8-9332-ecfd83465e65.png)

The special appearance besides the bold text could be given to all mentions too, but using the primary colour for mentions to the current user to make it more prominent (similar to [what Riot does](https://github.com/nextcloud/server/pull/7514#issuecomment-356304123)):

![chat-mention-highlight-all](https://user-images.githubusercontent.com/26858233/39241410-113e7568-4887-11e8-914f-b585a05980d7.png)

Another option could be to highlight the whole message in which the mention appears (this is done for example by Quassel IRC):

![chat-mention-highlight-line-strong](https://user-images.githubusercontent.com/26858233/39241419-17df2a84-4887-11e8-8528-c23e09eafc0b.png)

Personally I think that using the primary colour there would be too much, although I like this approach with a softer colour (primary colour with 0.2 opacity), as it should make easy to spot a mention when scrolling while not "competing" with other elements that use the primary colour, like buttons or the header:

![chat-mention-highlight-line-soft](https://user-images.githubusercontent.com/26858233/39241431-20dfb504-4887-11e8-8c74-4d9ef118b0b5.png)

@nextcloud/designers Opinions?

**Comment by jancborchardt** [comment]
Yep, Riot approach looks best for sure. Rounded container around every mention, primary color fill if you are mentioned yourself.

**Comment by danxuliu** [comment]
>  Riot approach looks best for sure

I agree that it looks best, although I prefer highlighting the whole line because I think it is easier to spot. Anyway I have implemented the Riot approach in #813.
