### ISSUE TITLE
Bot Translator for Talk in chatbox

### ISSUE THREAD

**Issue by wisiagency** [nextcloud/spreed#8111]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
we need Automatic Translator for Talk, like Jakebot in Discord, or is there a way to put jakebot or any other automatic translator in our Talk using API?
**Describe the solution you'd like**

**Describe alternatives you've considered**
talk bots that will automatic translate language to other language in chat box
**Additional context**

**Comment by nickvergessen** [comment]
Translation feature is available since Nextcloud 27
