### ISSUE TITLE
Dashboard: other content than on web

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#8121]
I tested it with c.nc.c and can share more info / screenshot, if needed.
On web I see:
- Matthieu -> you were mentioned
- Alex -> you were mentioned
- Joas: chat message

On API:
- 14 entries
- all of them are "xyz left", "call ended"
--> seems to show only system infos

**Comment by nickvergessen** [comment]
@vitormattos can you have a look?

**Comment by nickvergessen** [comment]
Also can you maybe add screenshots? They might help seeing the states better, eg whether the dashboard showed the half empty view etc.

**Comment by tobiasKaminsky** [comment]
I think it is enough to compare web and API (via curl):
```
curl --request GET \
  --url 'https://cloud.nextcloud.com/ocs/v2.php/apps/dashboard/api/v1/widget-items?format=json&limit=14&widgets%5B%5D=spreed' \
  --header 'Authorization: Basic 123123' \
  --header 'OCS-APIRequest: true' \
  --header 'format: json'
```

Content is entirely different.

**Comment by tobiasKaminsky** [comment]
Hm. Now I opened such a conversation. 
And it seems that this was kind of "unread status message".

Those are all group chats, where someone left the conversation.
