### ISSUE TITLE
NC Talk desktop app/ features in NC desktop client

### ISSUE THREAD

**Issue by aov-arnold** [nextcloud/spreed#8143]
Currently only talk push notifications and limited message answering are available through the NC desktop client.
When you see a talk push windows notification you have to click the NC systray icon and then the message to open the the whole conversation in the browser/ web-app. This takes quite some clicks and time. It is not convenient if you are communicate via NC talk frequently.

There should be a NC Talk desktop app or the features of the mobile NC talk desktop app (iOS/ Android) should be included into the NC desktop client.

At least a click on the windows push notification should directly open the conversation in the browser/ web-app to make it easier. 

@nickvergessen Are there already any plans regarding this?

**Comment by nickvergessen** [comment]
There is an issue somewhere at least
