### ISSUE TITLE
Pending call message in 1on1 calls is very generic

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#8155]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When starting a call in a 1on1 conversation, the message is very generic:
![image](https://user-images.githubusercontent.com/925062/195313955-83ec8715-1043-4fd4-891a-18cadf81db95.png)

**Describe the solution you'd like**
A simple "Waiting for [display name] to join the call …" would be great. :)

**Comment by jancborchardt** [comment]
@marcoambrosini @nickvergessen if you describe where and how this would need to be changed, it could make a good first issue. :)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/b1be9e3b3412016fa443d2f2db7a8e3e7387ed99/src/components/CallView/shared/EmptyCallView.vue#L117

The information whether it's a 1-1 is `this.conversation.type` and `this.conversation.displayName` is the display name of the other person

**Comment by KANE-99** [comment]
Added PR: https://github.com/nextcloud/spreed/pull/8224

**Comment by nickvergessen** [comment]
Fixed with above
