### ISSUE TITLE
Video of other person in 1on1 call is not rounded

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#8156]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call
2. Look at the video of the other person

### Expected behaviour
Nice border-radius, just like for your own video.

### Actual behaviour
Sharp edges, ow!
![image](https://user-images.githubusercontent.com/925062/195319056-4a49038e-fab9-4dc2-b0dd-dfe647b616aa.png)

## Talk app

**Talk app version:** Latest on cloud.nc.com

**Comment by nickvergessen** [comment]
The corners appear once the video is being cropped iirc.

**Comment by RotonEvan** [comment]
Can I work on this?

**Comment by nickvergessen** [comment]
Sure 👍
