### ISSUE TITLE
Message expiration does not work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#8178]
RC5, 15.0.0-rc.5
This does not remove any messages after waiting this time:
![image](https://user-images.githubusercontent.com/24530680/195984886-7595d4e4-db55-49d1-9a00-f425aa3a5cf7.png)
Here it's gone:
![image](https://user-images.githubusercontent.com/24530680/195984943-49c2635d-ccb1-408e-8cf4-09c670bca18f.png)
But in the room all messages are still there

**Comment by nickvergessen** [comment]
Note that the setting only affects new messages. But I now see that this is not stated in the description. So we should fix the description.

**Comment by nickvergessen** [comment]
This should be solved by now as the API endpoint also filters out messages.
For your case it mostlikely means the background jobs never ran.
