### ISSUE TITLE
Non-group members can see group membership in Talk app

### ISSUE THREAD

**Issue by geotheory** [nextcloud/spreed#818]
## Steps to reproduce
1. User A to create Group X and add any users
2. User B (who is not in Group X) to start new call with `X (group)` in Talk dropdown list
3. User B can see a list of members of Group X

Admins might need to ensure group membership is not visible to non-members.  I cannot see any other parts of Nextcloud where this information is accessible, but may be wrong.  There does not appear to be any mechanism to achieve this in Talk.

**Comment by nickvergessen** [comment]
You could use the setting from https://github.com/nextcloud/spreed/issues/825

Then users are only able to call groups which they are a member of.
Apart from that there is no way to prevent this.
