### ISSUE TITLE
Stable API/protocol?

### ISSUE THREAD

**Issue by mittorn** [nextcloud/spreed#8215]
**Is your feature request related to a problem? Please describe.**
There are no stable API. Client API was completely broken many times, all CLI clients i found even cannot login, chatbot projects are dead and old client versions just says that Talk is not installed on server

**Describe the solution you'd like**
Make stable API allowing writing 3rd party clients or separate bot application. With stable API i will be sure that i do not need by new phone because old client deprecated (2-4 years is not so much time to drop it completely)

**Describe alternatives you've considered**
Integrate some chat transport support to be able mirror chat to some stable protocol (XMPP/IRC/Matrix)

**Additional context**
NextCloud Talk's A/V part is good, so why not have good text-only chat part, availiable for low-end devices, as it done for Matrix, XMPP?

**Comment by nickvergessen** [comment]
Our API is as stable as possible. You can find the documentation at https://nextcloud-talk.readthedocs.io/en/latest/

The latest breaking was needed so users can be in multiple rooms at the same time, but that API level is there now since March 2021.

**Comment by nickvergessen** [comment]
Before that we only added new APIs additionally. So the last version before march shipped v3, v2 and v1.
But that was not possible with the multiple sessions support as there is no 1-1 mapping between a user and a session.

Hope that helps as information.

**Comment by mittorn** [comment]
OK, I think, it may be closed
