### ISSUE TITLE
Talk not enabled after upgrade to NC 25 and spreed 15  enabling fails with error

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/spreed#8219]
## Steps to reproduce
1. Upgrade an older instance to Nextcloud 25
2. Upgrade to Talk 15
3. Message "An error occurred during your request. Unable to proceed."

If tried by commandline occ app:install spreed the whole nextcloud-instance failed with error 500

### Expected behaviour
App should be installed correctly

### Actual behaviour
App not installed

### Browser log
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at rebuild-navigation.js:17:20
    at Array.forEach (<anonymous>)
    at rebuild-navigation.js:16:15

**Web server:** Apache

**Database:** MySQL/Maria/

**PHP version:** 8.0.24

**Nextcloud Version:**  25.0.0

**Comment by nickvergessen** [comment]
There is a known issue with the upgrade in Nextcloud 25.0.0 that has been fixed for 25.0.1 already.
If you receive a 500, there should be useful messages in the nextcloud.log file of your data directory. Without that info we can not confirm it's the same issue or something else

**Comment by Bolli84** [comment]
The erroe i can find in the log: 

> Declaration of OCA\Talk\Share\RoomShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares): array must be compatible with OCP\Share\IShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares, $shallow = true) at .............apps/spreed/lib/Share/RoomShareProvider.php#520

**Comment by nickvergessen** [comment]
Okay, yeah that is the one we fixed in the server https://github.com/nextcloud/server/pull/34688
