### ISSUE TITLE
talk13.0.9 

### ISSUE THREAD

**Issue by Mrzzhi** [nextcloud/spreed#8229]
Install talk13.0.9
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by nickvergessen** [comment]
You need to enable UTF8 support in Nextcloud first:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
