### ISSUE TITLE
Infinite loading spinner in chat interface

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8230]
Works perfectly for the mobile app. Looks like the web app has an infinite loading spinner when this is set, so some slight improvement needed there, but definitely gets the main job done on this. Thanks for that quick suggestion!

Console log from the spinner problem (in case this helps):
```
TypeError: e is null
    wc index.js:1221
    Xe VueJS
    wc index.js:1219
    VueJS 14
    fetch index.js:1187
    promise callback*fetch index.js:1185
    mounted index.js:1181
    VueJS 19
    addConversation conversationsStore.js:101
    v vuex.esm.js:831
    commit vuex.esm.js:437
    commit vuex.esm.js:37
    _withCommit vuex.esm.js:601
    commit vuex.esm.js:36
    commit vuex.esm.js:394
    n conversationsStore.js:411
    c conversationsStore.js:2
    _invoke conversationsStore.js:2
    v conversationsStore.js:2
    T conversationsStore.js:2
    o conversationsStore.js:2
    S conversationsStore.js:2
    S conversationsStore.js:2
    updateLastCommonReadMessage conversationsStore.js:405
    v vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    n messagesStore.js:763
    c messagesStore.js:2
    _invoke messagesStore.js:2
vue.runtime.esm.js:2989:37
```

_Originally posted by @gitd8b in https://github.com/nextcloud/spreed/issues/8227#issuecomment-1291293251_

**Comment by nickvergessen** [comment]
cc @marcoambrosini

**Comment by meonkeys** [comment]
I don't think this is a Talk bug. I see an infinite spinner when I paste a bare link in a Markdown text file.

**Comment by abartl** [comment]
FYI as a temporary quick solution, it is possible to block the spinner / with an adblocker.
