### ISSUE TITLE
No contacts displayed

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/spreed#825]
## Steps to reproduce
1. Install nextcloud
2. Install spreed app

### Expected behaviour
Contacts should be displayed

### Actual behaviour
No contacts are shown. Only, if I write username, the contact shows. After that, I am able to use spreed normally (only in browser). Anyway, I prefer using it mobile, but there are also no contacts shown. Is this spreed problem, or android app? Should I open a issue on talk-android?
Also, on my previous instance (nextcloud 13 and 13.0.1, spreed 3.1.0) there was no problem with showing contacts in browser and in phone, and everything was working like a charm.

No errors in server log

![pc1upl](https://user-images.githubusercontent.com/30871217/39316719-2742811c-497a-11e8-9a56-f5a114b4fd8d.png)

![pc2upl](https://user-images.githubusercontent.com/30871217/39316720-27693730-497a-11e8-8b98-556172cf9927.png)

![pc3upl](https://user-images.githubusercontent.com/30871217/39316722-278eb1cc-497a-11e8-823c-1f29b6fa0de6.png)

![pc4upl](https://user-images.githubusercontent.com/30871217/39317036-eb6800da-497a-11e8-92db-e01bb5276004.png)

![screenshot_20180426-170536](https://user-images.githubusercontent.com/30871217/39316724-27d2909a-497a-11e8-84fc-2e1fc4202970.png)

Also I searched for a solution here, find this https://github.com/nextcloud/spreed/pull/685 , but don't know if it was for my issue, tried it but nothing happend.

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Firefox & Chrome

## Spreed app

**Spreed app version:** 	3.1.0

**Custom TURN server configured:** no
**Custom STUN server configured:** no

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7

**Nextcloud Version:** 13.0.1 & 13.0.2

**Comment by nickvergessen** [comment]
Yeah sorry, but I'm glad you found the solution.
