### ISSUE TITLE
Support meeting duration + show countdown with an alert with live countdown when the meeting is ending soon

### ISSUE THREAD

**Issue by devnoname120** [nextcloud/spreed#8264]
This would come in handy in order not to run overtime and also nudge participants into wrapping up.

**Comment by nickvergessen** [comment]
* Ref https://github.com/nextcloud/spreed/issues/6766 Should already help a bit as the duration is shown.
* Setting a timer/countdown is another more difficult thing and tracked in https://github.com/nextcloud/spreed/issues/1218
So will close this as duplicate

**Comment by devnoname120** [comment]
@nickvergessen Thanks! And sorry for the duplicate I couldn't find these issues using the search feature.

**Comment by nickvergessen** [comment]
No issue at all. I knew they existed and still had to search long time with different keywords until I found them again :)
