### ISSUE TITLE
"Someone voted" shows in conversation list

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8266]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. User A starts a poll (public, multiple votes)
2. User B votes

### Expected behaviour
Either no message about the vote of user B is shown, or it should be shown in the conversation list and the chat

### Actual behaviour
The messages that user B voted is shown in the conversation list, but not in chat. Also a push notification is received by user A, that user B voted.

<img width="381" src="https://user-images.githubusercontent.com/1580193/199560383-9be0c92b-c7c5-4a51-b49c-18eab087e279.png">

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1580193/199560568-19f1074a-e930-418a-8c85-b9b38e21aab8.png">

## Talk app

**Talk app version:** Sermo

**Comment by nickvergessen** [comment]
My current take is: we don't show it in the chat as it can be quite spamy. But we need to make it appear in the left sidebar as an update so that the chat is moved up again.

**Comment by SystemKeeper** [comment]
> My current take is: we don't show it in the chat as it can be quite spamy.

I agree, but in this case it shouldn't send push notifications either, right? In my test every room participant got a push when someone voted and when the poll was closed (the last might make sense, because in this case it's a visible system message, but not sure).

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/blob/master/lib/Controller/PollController.php#L186

Okay, seems like it is enabled here. Should set the last parameter to false and then we have no more push :)
