### ISSUE TITLE
Number of votes not visible before voting myself

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8267]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. User A starts a poll (public, multiple answers)
2. User B votes

### Expected behaviour
User A (or a moderator) should be able to see how many votes are there already.

### Actual behaviour

Talk-Web:
<img width="351" src="https://user-images.githubusercontent.com/1580193/199561376-82b44ee7-0072-405e-b230-04230e72a1ff.png">

Talk-iOS:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/1580193/199561535-028b7c96-6cb5-49f9-89c8-2e9bde7ff596.png">

Talk-Web after voting myself (User A):
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1580193/199561840-b80228e7-7b1f-4997-9289-4f7fa80b61c4.png">

## Talk app

**Talk app version:** Sermo

**Comment by nickvergessen** [comment]
At least the result between API and UI should be consistent.
I think we argued for not having the number shown to not support a bias towards it.

**Comment by Ivansss** [comment]
> I think we argued for not having the number shown to not support a bias towards it.

I thought we decided to show it 🤔
So the poll owner could know how many users voted already in order to close the vote or not (without the need of voting itself)

**Comment by nickvergessen** [comment]
Yeah we do allow it for the poll creator and moderators:
https://github.com/nextcloud/spreed/blob/master/lib/Controller/PollController.php#L259-L264

So it's a bug in the UI and:
https://github.com/nextcloud/spreed/blob/master/src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue#L114-L121

Needs to be copied into:
https://github.com/nextcloud/spreed/blob/master/src/components/MessagesList/MessagesGroup/Message/MessagePart/Poll.vue#L56-L57
