### ISSUE TITLE
Administration settings > Talk : Internal Server Error through PHP 8

### ISSUE THREAD

**Issue by ffs69** [nextcloud/spreed#8269]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Hello everybody.
Hoping you can help me 🙇‍♂️ Thanks in advance and have a good day 😘

## Steps to reproduce
1. Hosted on shared hosting with PHP 8.1 activated
2. For security reasons `PHP exec()` is disabled
3. Trying to go to the settings page of the Talk apps

### Expected behaviour
I should see the Talk app setup page.

### Actual behaviour
I'm facing an error message :
```
Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.
```
## Talk app

**Talk app version: 15.0.0** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured: no** (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured: no** (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured: no** (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Not concerned**

## Server configuration

**Operating system: Debian**

**Web server: Apache**

**Database: MariaDB**

**PHP version: 8.1**

**Nextcloud Version: 25.0.0** (see admin page)

## The reasons mentioned by my host

`Obviously the line @exec('apachectl -M | grep mpm', $output, $returnCode); in apps/spreed/lib/Settings/Admin/AdminSettings.php is problematic on our shared platform: the PHP exec() function is not available, and the use of @ no longer gives the possibility of ignoring its unavailability since PHP 8.`

Is there a way to setup a command or a line in this file to circumvent this difficulty? It should be very helpfull.

Thank you very much for reading my problem, and in advance thank you for the help to overcome it.

Long life to GitHub, Talk and Nextcloud; and above all thank you to the community 🙇‍♂️

**Comment by nickvergessen** [comment]
Do you have access to the error log of the webserver?

We would need to know whether the function is not available in terms of undefined, or if it is available but not accessible.

Can you put this code into a test.php on your webserver, open it in the browser and post us the result?
```php
<?php

		var_dump('function_exists', function_exists('exec'));
		var_dump('get_defined_functions(true)', in_array('exec', get_defined_functions(true)));
		var_dump('get_defined_functions(false)', in_array('exec', get_defined_functions(false)));
		var_dump('ini_get(disable_functions)', strpos(ini_get('disable_functions'), 'exec'));
```

If you still are in contact with the provider could you ask them how they made the function unavailable?

**Comment by ffs69** [comment]
Thank you very much for the reply.

Running test.php gives this:

`string(15) "function_exists" bool(false) string(27) "get_defined_functions(true)" bool(false) string(28) "get_defined_functions(false)" bool(false) string(26) "ini_get(disable_functions)" int(51) `

I just questioned my host to get the answer, as soon as I have it I'll send it to you.
