### ISSUE TITLE
hide details, keep messages

### ISSUE THREAD

**Issue by punkyard** [nextcloud/spreed#8293]
could you add an option to remove/hide manually details one by one
or hide them all with a one-click button?

cause details are really polluting the chatt
thanks

![talk activities in chat](https://user-images.githubusercontent.com/59349105/200039321-a073fba9-2ee5-4de9-bb2b-63d105ba578d.png)

**Comment by nickvergessen** [comment]
As mentioned on the PR, a ticket already exists
