### ISSUE TITLE
Multiline avatars in bottom stripe

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#8314]
<img width="500" alt="multiline_bottom_stripe" src="https://user-images.githubusercontent.com/4638605/200619330-409ad136-3117-447f-88f7-e19779f68c9e.png">

Console output:

![console_output](https://user-images.githubusercontent.com/4638605/200619451-79bb7ecc-541e-4c64-a494-342e3fee941f.png)

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/spreed/pull/8245

Definetly should only have 1 row when it's the bottom stripe.
