### ISSUE TITLE
Unknown error on Signaling Server connectivity check when admin is not in "Limit to Groups" list

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#8315]
### Steps to reproduce

1. Make sure admin is not in the "Limit to Groups" list and the list is not empty
2. Check the connectivity with the Signaling Server

### Expected behaviour

There are two options:

- option 1: no error
- option 2: explicit error

I'd advocate for option 1.

### Actual behaviour

Uknown error 

### Device brand and model

Fairphone 2

### Android version

10

### Nextcloud Talk app version

15.0.1

### Nextcloud server version

25.0.1

### Talk version

15.0.1

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

No

**Comment by nickvergessen** [comment]
> Check the connectivity with the Signaling Server

Where exactly are you testing this?
If the user is not allowed to use Talk, the mobile app must not be able to connect, that's just how it is meant to be?

**Comment by pmarini-nc** [comment]
Sorry, I should have specified that.

I'm testing in the Web UI, settings/admin/talk.
