### ISSUE TITLE
Silent call option is not reset until page reload

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8323]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a silent call in Room A for coworking
2. End the call
3. Move to Room B for a meeting

### Expected behaviour
Call starts with notifications

### Actual behaviour
Call is silent again. This is totally unexpected and since it's ringing locally the user might not realise that the other party didn't get a notification.

## Talk app

**Talk app version:** master + stable25

**Comment by nickvergessen** [comment]
Related https://github.com/nextcloud/spreed/issues/8336

**Comment by Antreesy** [comment]
Fixed with #11719 for v29 only? Or backport?

**Comment by nickvergessen** [comment]
Let's keep 29 for now so we test it a bit to see if it feels natural now.
We can decide on the backport once the next release is due
