### ISSUE TITLE
Silent sent and silent call modes are not behaving the same

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8336]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Yesterday I was very surprised that the "Silent send" option directly sends out the message. I would have assumed that similarly to the "Silent call" option it toggles the button and not send my half baked message already. I assume the problem was we didn't have a button icon for it. So I suggest to use simply the outlined version: https://materialdesignicons.com/icon/send-outline

**Comment by ASCE-D** [comment]
Hey Devs, I would like to work on this issue please assign me

**Comment by nickvergessen** [comment]
You can pick it up 👍🏼
