### ISSUE TITLE
🖖 Breakout rooms 🖌️ Frontend

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8339]
Meta ticket at https://github.com/nextcloud/spreed/issues/8337

## ETA 13/01
- [x] BR configuration modal
  - [x] Room number count
  - [x] Auto assignment
  - [x] Manual assignment
  - [x] Allow users to move freely between rooms
- [x] BR Management
  - [x] Start breakout rooms 
  - [x] Stop breakout rooms 
  - [x] reconfigure breakout rooms 

## ETA 20/01
- [x] Moderation
  - [x] Send message to a breakout room
  - [x] Request assistance
  - [x] Show assistance requests to moderators in other rooms 
- [x] Sidebar
  - [x] Allow mods to move users
- [x] Handle breakout room start signaling message #8477 
- [x] Fetch participants of all breakout rooms (requires endpoint @nickvergessen )

## ETA 27/01
- [x]  Cleanup settings
  - [x] Disable lobby in BRs should be removed
  - [x] No guests option in BRs

**Comment by nickvergessen** [comment]
Follow ups from https://github.com/nextcloud/spreed/pull/8403

- [ ] Should use constants for the different modes instead of magic numbers
- [ ] Should change the conversation detail in the conversationStore when an action was successful, to avoid having to wait for a page reload
- [ ] Don't get breakout rooms when the conversation breakout room mode says they are off.
- [ ] Checkbox is not accessible, but seems NcCheckboxRadioButton component can not be used as is.
- [ ] In manual assignment with 1 room, the button to assign people has no label or clear icon what it does.

**Comment by SystemKeeper** [comment]
- [ ] Breakout-Room Tab shouldn't be visible for changelog room
![image](https://user-images.githubusercontent.com/1580193/215619631-903f3b85-fd79-412a-8f7e-e8f7ac522e8b.png)

**Comment by nickvergessen** [comment]
Yeah it should not be down when not configured, but currently it seems not to be reactive at all
