### ISSUE TITLE
do not show results of deleted polls

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/spreed#8342]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a poll in talk
2. End the poll ==> Results-button is shown in chat
3. delete the message that had the poll in it

### Expected behaviour
Poll and results get deleted.

### Actual behaviour
poll is deleted
results-button is still shown.

**Comment by nickvergessen** [comment]
Not sure that is easily doable in hind-sight as there is no link that allows us to find out which message should be "killed"

**Comment by xbluemonkx** [comment]
Ok, I see. An alternative would be to be able to delete the results manually too. But from my point of view it is a no-go that I am not able to delete the results of a vote.

**Comment by nickvergessen** [comment]
It might also only be a caching issue in the frontend. If you reload the page after deleting the poll I think the result is gone?

**Comment by xbluemonkx** [comment]
reload and shift-reload did not solve it

**Comment by nickvergessen** [comment]
Pull request started at https://github.com/nextcloud/spreed/pull/8351

Still missing some bits, but should be fixed in the upcoming release
