### ISSUE TITLE
Add additional information about supported API versions to routes

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/spreed#8353]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
To use the APIs clients always need to specify the API version they want to use.

**Describe the solution you'd like**
The routes should have information about the possible values for a parameter.
This way the clients can treat each of the endpoint versions completely differently, so we won't have any conflicts.
In theory we could just parse the requirements regex, but that is pretty fragile and we don't know if that would also work for other apps.
My proposal is to add a new parameter for each route that points to an array that defines possible values similar to this:
```php
$possibleValues = [
  'apiVersion' => ['v4', 'v5'],
];
```

**Describe alternatives you've considered**
Right now all endpoints only support one `apiVersion`, so we could just define a default version. In the case that a second version will be supported in the future, this would be bad because the implement behind the different versions of the endpoint will differ. That would result in different expected/supported request parameters and response bodies.

**Additional context**
We should check if other apps have a similar situation and if the solution would work for those too.

**Comment by vitormattos** [comment]
This could be solved by:

```php
$possibleValues = [
  'apiVersion' => 'v(4|5)',
];
```
But, we have an user case of an endpoint that have more than a version to do this at this moment?

**Comment by provokateurin** [comment]
This is outdated, we went with parsing the regex. cc  @nickvergessen
