### ISSUE TITLE
Fix CallTime popover

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#8388]
While the options in the NcActions are grey/max contrast/something
This one is pretty dark/black or white/bright:
Before | After
---|---
![Bildschirmfoto vom 2022-11-21 11-49-19](https://user-images.githubusercontent.com/213943/203032088-447b1b7d-a9a4-4fb6-b2bd-d0e7111f3c60.png) | ![Bildschirmfoto vom 2022-11-21 11-49-25](https://user-images.githubusercontent.com/213943/203032089-c2ccfe08-3f7f-4e7f-a1d9-cc512384fcbe.png)
![Bildschirmfoto vom 2022-11-21 11-51-13](https://user-images.githubusercontent.com/213943/203032273-ea6ee968-e7ab-464d-8446-6023dd18d0a8.png) | ![Bildschirmfoto vom 2022-11-21 11-51-18](https://user-images.githubusercontent.com/213943/203032278-1e878ca0-d8f8-4c00-9958-0a165ca6cfa8.png)

Also the rounding is different from the actions menu, but we can move this to a follow up, as the PR has too many things touching already.

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/pull/8341#discussion_r1027861232_

**Comment by nickvergessen** [comment]
Still a thing?

**Comment by nickvergessen** [comment]
Solved
