### ISSUE TITLE
Document icon-url on call rich objects

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8389]
https://github.com/nextcloud/spreed/pull/8333 introduced an optional `icon-url` for the call objects in rich messages.
This attribute is however not documented in https://github.com/nextcloud/server/blob/d18a293ee50f1a17942391b2031f39fed6ff2eae/lib/public/RichObjectStrings/Definitions.php#L166-L196

**Comment by nickvergessen** [comment]
Also not all rich objects are currently fed this value:

apps/spreed/lib/Notification/Notifier.php  (5 usages found)
- [ ] 364 'type' => 'call',
- [ ] 601 'type' => 'call',
- [ ] 626 'type' => 'call',
- [ ] 677 'type' => 'call',
- [ ] 701 'type' => 'call',

**Comment by vitormattos** [comment]
We got commits at this file after the enumerating of rows, now we have different rows and 2 more rows was added to this list.

> Also not all rich objects are currently fed this value:
> 
> apps/spreed/lib/Notification/Notifier.php (5 usages found)
> 
>     * [x]  line 364 'type' => 'call',
>     * [x]  line 601 'type' => 'call',
>     * [x]  line 626 'type' => 'call',
>     * [x]  line 677 'type' => 'call',
>     * [x]  line 701 'type' => 'call',
