### ISSUE TITLE
Make sending signaling messages easier

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/spreed#8392]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Sending a signaling message requires using nested json.
Sending a broken signaling message never returns an error to the client.

**Describe the solution you'd like**
Remove the nested json and just keep it a nested object. Backwards compatibility is still kept.
Return with a bad status code instead of just breaking if the supplied message is invalid.

**Describe alternatives you've considered**
Remove the nesting altogether, but that would either break backwards compatibility or require some more checks to see which format is used.

**Comment by nickvergessen** [comment]
> Remove the nested json and just keep it a nested object. Backwards compatibility is still kept.

It's "nested" as you can send X messages in one request (mostlikely 1 signaling message is needed for each connected remote)

> Return with a bad status code instead of just breaking if the supplied message is invalid.

you have sample input that should break differently? But yeah it looks like we always return 200 unless an exception occurs

**Comment by provokateurin** [comment]
I'm not entirely sure, but I think it should be possible to just make the parameter of type `array` and then the json decoding will be take care of by the framework. Together with https://github.com/nextcloud/openapi-extractor/pull/22 it would allow documenting the exact signaling messages that are accepted.

I will have to test if it will actually work, but I hope it will :thinking:

**Comment by nickvergessen** [comment]
> I'm not entirely sure, but I think it should be possible to just make the parameter of type array and then the json decoding will be take care of by the framework.

```
OCA\Talk\Controller\SignalingController::signaling(): Argument #2 ($messages) must be of type array, string given, called in /home/nickv/Nextcloud/28/server/lib/private/AppFramework/Http/Dispatcher.php on line 230
```

Test says nop. It would need modification in frontend and mobile clients therefore it would be breaking compatibility with older versions => won't do that for the sake of documenting it.

**Comment by provokateurin** [comment]
Hm ok, I saw some code that suggested this would work. I'll investigate if that code might be broken

**Comment by provokateurin** [comment]
But if this parameter is sent in the request body then it should be possible to just pass the full json object without encoding it first. The request body could look something like this:
```json
{
	"token": "abc"
	"messages": [
		{
			"ev": "message"
			"sessionId": "123"
			"fn": "{...}"
		}
	]
}
```
Then it would also be possible to only optionally json decode the `fn` field. If it is sent in the request body it is a lot easier to just send it as json instead of encoding it first.

It should be possible to implement this while keeping it compatible with the existing behavior, but adding a new endpoint might also make sense.
@nickvergessen does this make sense or am I completely off track?

**Comment by provokateurin** [comment]
The signaling messages themselves might be random garbage, but you still need to hook them up to the api which is way more complex than it needs to be. Of course this works just fine, but it is not great especially because it is not documented at all (in markdown or openapi) what exactly needs to be sent.
It might not be a big problem in the bigger picture, but it is an api that is pretty hard to use and I would like it to be simpler.

**Comment by provokateurin** [comment]
Closing this because it isn't worth the effort and introducing a change that is not necessary.
