### ISSUE TITLE
Participants count in call is not visible when sidebar is open

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8407]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call and try to keep an overview about the participant count
2. It's visible in the topbar
![Bildschirmfoto vom 2022-11-29 15-56-59](https://user-images.githubusercontent.com/213943/204563273-a33bf686-35b9-40cf-8fe1-4f44378f45fc.png)

3. but as soon as you open the right sidebar for chatting or handling permissions etc, you can not see the count anymore. Keeping an eye on the participant cound and reading the chat in parallel is the most common usecase and task for webinar moderators.
![Bildschirmfoto vom 2022-11-29 15-57-08](https://user-images.githubusercontent.com/213943/204563449-016a83cb-2100-4fbf-918c-b5609dd6c00e.png)

### Expected behaviour
The count should be visible.

### Actual behaviour
Only total participant count is visible.

### Solutions
1. Either we should something like (1/8) on the participants tab (but the string is dangerously long already and might trim in several langauges or screen resolutions, or 
2. We don't hide the participant icon when the sidebar is open
3. We move the information to another place where it is visible all the time (*cough* initial suggested and discussed subline *cough*)

**Comment by marcoambrosini** [comment]
Temporary fix could be not hiding icon, but my proposal here would be to group into collapsible list item with captions, much like we're doing for breakout rooms


https://user-images.githubusercontent.com/26852655/204759828-4dd67018-6945-4792-9324-f6cce0e21321.mov

Count should be to the right of the caption

**Comment by nickvergessen** [comment]
> but my proposal here would be to group into collapsible list item with captions

But that area is not visible when you are on the chat during the call, so we need to show it somehow
