### ISSUE TITLE
Get single conversation endpoint doesn't return user status

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#8411]
Get single conversation [endpoint](https://nextcloud-talk.readthedocs.io/en/latest/conversation/#get-single-conversation-also-for-guests) doesn't return user status info.

### Expected behaviour
User status information should be returned at least for NC users.

**Comment by nickvergessen** [comment]
Should apply similar constraints as https://github.com/nextcloud/spreed/blob/3d49db3b713b7fd6379b288a379f30401400cd88/lib/Controller/RoomController.php#L208-L210 but yeah, otherwise there is no reason not to have this.

**Comment by Ivansss** [comment]
Could we add a capability when this endpoint returns the user status?
Then the clients would know when they can trust the user status returned by this endpoint.
