### ISSUE TITLE
User attachements (pics,pdf..) in TALK cannot be opened anymore on any browser (Edge/Chrome/Firefox) 

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/spreed#8417]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. User 1 send an attachement to user2 in TALK (source is independant)
2. User 2 can view & open attachement from SmartPhone (iPhone)
3. User 2 can view ,but cannot open (infinite sandglass) in web-browser
4. User 2 tries to open the TALK Photo (pic) into the PHOTO App - same (sandglass) (web-browser)
    User 2 can view ,but cannot open (infinite sandglass) in PHOTO App (web-browser)

### Expected behaviour
User shoud be able to view and open attachements, when they are presented from anywhere and from other users

### Actual behaviour
see "steps to reproduce"

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

spreed: 14.0.6

**Operating system:** RHEL 8.6

**Browser name:** Firefox/Chrome/Edge: all

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

Operating System:  Red Hat Enterprise Linux release 8.6 (Ootpa)

Webserver:  Apache/2.4.37 (Red

Database:  mysql 10.3.35-MariaDB,

PHP version:  PHP Version => 7.4.26

**Nextcloud Version:** 24.0.7

**List of activated apps:**

Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - analytics: 4.5.0
  - announcementcenter: 6.3.1
  - apporder: 0.15.0
  - audioplayer: 3.3.1
  - bookmarks: 11.0.4
  - breezedark: 24.0.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - cms_pico: 1.0.20
  - collectives: 1.5.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.18
  - cospend: 1.4.10
  - dashboard: 7.4.0
  - data_request: 1.11.0
  - dav: 1.22.0
  - deck: 1.7.2
  - dicomviewer: 1.2.4
  - documentserver_community: 0.1.13
  - drawio: 1.0.5
  - electronicsignatures: 2.0.1
  - end_to_end_encryption: 1.10.0
  - event_update_notification: 2.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_antivirus: 3.3.1
  - files_automatedtagging: 1.14.0
  - files_downloadactivity: 1.15.0
  - files_external: 1.16.1
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.5.0
  - files_photospheres: 1.24.3
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - gpxpod: 4.3.0
  - groupfolders: 12.0.2
  - health: 1.5.1
  - imageconverter: 1.3.4
 - impersonate: 1.11.0
  - integration_discourse: 1.0.4
  - integration_dropbox: 1.0.5
  - integration_github: 1.0.4
  - integration_gitlab: 1.0.6
  - integration_google: 1.0.8
  - integration_jira: 1.0.4
  - integration_mastodon: 1.0.3
  - integration_moodle: 1.0.2
  - integration_openproject: 2.1.0
  - integration_reddit: 1.0.5
  - integration_suitecrm: 1.0.3
  - integration_twitter: 1.0.3
  - integration_zammad: 1.1.1
  - issuetemplate: 0.7.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - news: 19.0.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - onlyoffice: 7.5.8
  - passman: 2.4.2
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.8.3
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quicknotes: 0.8.1
  - quota_warning: 1.15.0
  - rainloop: 7.2.6
  - ransomware_protection: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - socialsharing_diaspora: 2.5.0
  - socialsharing_email: 2.5.0
  - socialsharing_facebook: 2.5.0
  - socialsharing_twitter: 2.5.0
  - spreed: 14.0.6
  - support: 1.7.0
  - systemtags: 1.14.0
  - talk_matterbridge: 1.25.2
  - talked: 0.4.0
  - tasks: 0.14.5
  - terms_of_service: 1.10.2
  - text: 3.5.1
  - theming: 1.15.0
  - timemanager: 0.3.4
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.1
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - video_converter: 1.0.5
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - welcome: 1.0.2
  - workflow_media_converter: 1.7.0
  - workflow_ocr: 1.24.6
  - workflow_pdf_converter: 1.9.0
  - workflow_script: 1.9.0
  - workflowengine: 2.6.0

*{
    "system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***,
            "dbindex": ***REMOVED SENSITIVE VALUE***,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "24.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/***REMOVED SENSITIVE VALUE***\/***REMOVED SENSITIVE VALUE***\/nextcloud.log",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "logtimezone": "***REMOVED SENSITIVE VALUE***\/***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CH",
        "knowledgebaseenabled": false,
        "log_rotate_size": ***REMOVED SENSITIVE VALUE***,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "passman",
            "dicomviewer",
            "radio",
            "cookbook",
            "health",
            "issuetemplate",
            "documentserver_community",
            "imageconverter",
            "epubreader",
            "workflow_pdf_converter"
        ]
    }
}

**Comment by nickvergessen** [comment]
Is there anything red printed in the browser console (F12) when yiu click on the image?

**Comment by Githopp192** [comment]
Gescannte%20Dokumente.pdf:1 : this is one of the docs, which cannot be opened

double-check firewall, no blocks (using suricata)
---------------------------------------------------------------------------------------------

$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
/remote.php/dav/files/xxx/Talk/Gescannte%20Dokumente.pdf:1 
             
Failed to load resource: the server responded with a status of 404 ()
Viewer.vue:450 
        
       Error: Invalid response: 404 
    at a (response.js:10:15)
    at t.handleResponseCode (response.js:21:19)
    at stat.js:65:36
    at stat.js:33:23
    at Object.next (stat.js:14:53)
    at i (stat.js:5:58)
(anonym) @ Viewer.vue:450
2globals.js:62 
        
       $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
sr5s:1 
        
       Refused to apply style from 'https://xxxx/apps/dashboard/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

![image](https://user-images.githubusercontent.com/32612067/205103472-d8ec8608-842d-4498-baff-5bf61ed3e472.png)

**Comment by Githopp192** [comment]
![image](https://user-images.githubusercontent.com/32612067/205103873-eacccf03-8cd5-49bf-a493-10781a25f859.png)

**Comment by Githopp192** [comment]
opening own objects (pic,pdf ..) in TALK is functional

**Comment by nickvergessen** [comment]
I have to assume that one of the viewer apps then causes the issue. It works fine here and in general.
But also the 404 seems weird. Could also mean your URLs are misconfigured but you removed them from the output 🤷‍♂️
So can't really help you there. I would recommend to ask in the forum for help as it's clearly a configuration issue and not a bug with Talk:
https://help.nextcloud.com/

**Comment by Githopp192** [comment]
hm .. 404 means not found.

https://mydomain/remote.php/dav/files/Michael/Talk/IMG-20221030-WA0003.jpg

as example: IMG-20221030-WA0003.jpg is not found under user "Michael"

Talk is working with "shares/Freigaben", but the issue is, that file: files/Michael/Talk/IMG-20221030-WA0003.jpg does not exist, but exists in the user directory, from the user who sent the talk message and attached this pic (IMG-20221030-WA0003.jpg).

Sabre\DAV\Exception\NotFound File with name /Talk/IMG-20221030-WA0003.jpg could not be located
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>File with name /Talk/IMG-20221030-WA0003.jpg could not be located</s:message>
...
</d:error>

I could be a config error - but i didn't change anything, but did nc upgrade from 24.0.6 to 24.0.7 - i think since this issue popped up.

I can open own stuff in Talk without any issue. So the problem must come from either:

* Talk does not propagate user attachements properly (shares)
* User, the Sender did manually remove the share
* there might be a some kind of cleanup-job, which cleaned up attachement shares or/and attachement

from this aspect 404 is clear - file is not there (at the place to be expected) anymore

**Comment by nickvergessen** [comment]
> Talk does not propagate user attachements properly (shares)

At least in Talk we didn't change anything like that. Especially not if you ran another 24 version before already.

> User, the Sender did manually remove the share

That would be the easiest answer, but in that case it should also not appear in the chat anymore. Maybe you can share a screenshot or confirm how the message in the chat looks, but you said it would work in the mobile app, just not in the browser?

> there might be a some kind of cleanup-job, which cleaned up attachement shares or/and attachement

Also nothing we do in Talk at all.

**Comment by Githopp192** [comment]
ok, we come closer to the RCA

login as admin via Browser to https://mydomain

1. as admin make attach a pic to my user (Michael) - status: ok
file: 20221204_001324.png

![image](https://user-images.githubusercontent.com/32612067/205180361-c216fcbc-bcae-4bea-90c2-5b2feea5dcd8.png)

2. File is in Talk Dir from user "admin"- status: OK

![image](https://user-images.githubusercontent.com/32612067/205180587-96970e20-c1b0-44b4-b31a-15007be93a9b.png)

3. Talk share is done (user "admin") - status: OK
![image](https://user-images.githubusercontent.com/32612067/205180821-e8781fa3-8321-4a53-b306-050ac0a2fa9c.png)

4. logoff Browser (Edge)

5. iPhone Talk App can open the just created share from Talk  (20221204_001324.png) - status: ok

iphone can open: 

![image](https://user-images.githubusercontent.com/32612067/205182158-778ea3f5-93b9-4ea3-9638-b9c4dfa4e073.png)

7. login via Broswer to https://mydomain with user: Michael
   go to "Files/Talk" -->
   file: 20221204_001324.png is not in Talk dir from user Michael - status: NOT OK
   There is also no share from admin with this name (20221204_001324.png)

![image](https://user-images.githubusercontent.com/32612067/205181191-628fb2e6-af3e-44a4-a624-5e0a648fcd41.png)

8.  Browser debug confirms (F12)
![image](https://user-images.githubusercontent.com/32612067/205181923-2789df8c-f397-43cc-a3c1-5562f6b31503.png)

**Comment by SystemKeeper** [comment]
Probably related to https://github.com/nextcloud/server/pull/35258
Please test with 24.0.8 again.

**Comment by Githopp192** [comment]
did test this hehave on a test (snap) setup on debian with same version:24.0.7
could not trigger the issue there - 

but that doesn't mean anything, this installation is much bigger and the app setup is much more extensive

yes, i'm going to plan a maint.-window this SUN .. and we will see ...

**Comment by SystemKeeper** [comment]
If it’s related to the bug above, then it will not occur on new instances. You can try to apply the patch if you want to check if it’s this problem.

**Comment by Githopp192** [comment]
i will do Marcel, thx - i' will give feedback on SUN after patching

**Comment by Githopp192** [comment]
btw .. just saw, that 24.0.8 is not released yet.
So, i've got two options: 

- wait ...
- install nextcloud-24.0.8rc1.zip (is the correct one ?)

**Comment by SystemKeeper** [comment]
… or apply the PR as a patch: https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html

the RC should be installable if you change the channel to Beta

**Comment by Githopp192** [comment]
thx

**Comment by Githopp192** [comment]
i can confirm. NC 24.0.8RC fixed it ! - well done
