### ISSUE TITLE
Ability to set an emoji as a conversation avatar

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed#8444]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Whatsapp allows to set an emoji as a group chat icon. I think this could be a very nice UX addition for 2 reasons:
1. facilitate quick group chat creation (without having to choose a picture which takes longer)
2. make easily recognisable group chats (without having to sacrifice the precious characters in the title to make it start with an emoji)

**Describe the solution you'd like**
While creating a group chat, the user can spawn an emoji picker and choose from those.  
At that point either:
1. the selected emoji gets rasterized and saved as image on the server or
2. the corresponding image for the selected emoji is chosen from a high resolution emoji pack such as https://twemoji.twitter.com/ which also contains SVG versions  

the image is then used as the conversation avatar.

Whatsapp UI:
1. tap the icon button
![IMG_8441](https://user-images.githubusercontent.com/48513706/206276065-9048f29b-118d-43b4-9e0d-15d28f4c6534.jpg)
2. choose "Emoji and Sticker"
![IMG_8442](https://user-images.githubusercontent.com/48513706/206276061-0915af9a-1c61-4983-bb1c-8792031b94c3.jpg)
3. choose emoji and background color
![IMG_8443](https://user-images.githubusercontent.com/48513706/206276070-6c7fcd9b-238e-49bc-83f2-78ea14a53ea3.PNG)

**Describe alternatives you've considered**
Emoji in the chat title, manually picked picture as a conversation avatar.

**Additional context**
Issue opened as requested by @nickvergessen in #927.

**Comment by nickvergessen** [comment]
So as a quick plan the following idea came up:
* If the room name contains an emoji as first character, we will use that emoji and return it as an SVG on the conversation avatar endpoint
* The background of the emoji is automatically generated based on the full displayname of the room, so multiple rooms with the same emoji could still have a different icon for easier distinction.
