### ISSUE TITLE
Unread message count does not update

### ISSUE THREAD

**Issue by diplodata** [nextcloud/spreed#848]
Firstly THANK YOU for the 3.2 enhancements, which are great :)

I'm not sure what the intended behaviour is for notifications/unread message counts.  I'm guessing a setting to enable notifications of new messages is a different issue (I'm not seeing any option for this yet in notification settings).  But it seems that the unread messages count _should_ at least be responsive to new messages.  I'm finding it works on login, but after that does not update when new messages are received.

## Steps to reproduce
1. User A initiate chat with User B. User B responds
2. User B navigates to another app
3. User A sends another message to User A
4. User B navigates back to Talk

### Expected behaviour
User B should see unread message count of 1 against the chat 'room' for User A

### Actual behaviour
I'm not seeing any unread count number, even after a few minutes.

## Browser Chrome / FF

**Microphone available:** no
**Camera available:** no
**Operating system:** Ubuntu 16.04
**Browser name:** Firefox/Chrome
**Browser version:** both latest

## Spreed app
**Spreed app version:** 13.2

**Operating system**: Ubuntu 16.04
**Web server:** . Apache 2.4.33
**Database:** .  MariaDB
**PHP version:** . 7.2
**Nextcloud version:** 13.0.2 RC 1
**Where did you install Nextcloud from: a daily build

**Comment by nickvergessen** [comment]
It does update, but takes about 10 seconds, because we don't watch all the channels live but instead ask for the numbers when refreshing the room list (which is about all 10 seconds)

**Comment by nickvergessen** [comment]
Closing as per above
