### ISSUE TITLE
Talk: Unable to Install - Wrong File Size

### ISSUE THREAD

**Issue by gbkelley** [nextcloud/spreed#8481]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Download and Install

### Expected behaviour
Completes Successfully

### Actual behaviour
Fails with: Could not extract app spreed: Extracted file /tmp/oc_tmp_ieB8si-folder/spreed/js/talk-public-share-auth-sidebar.js does not have the correct file size '4907008' (5881100 expected). Archive may be corrupted.

File size in raw .gz file is 5.9Mb

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
15.0.2

**Comment by nickvergessen** [comment]
Is your system low on memory, disk space or has a slow network speed?
Do you have access to the console so you could try to install the app from there?

**Comment by gbkelley** [comment]
128Gb RAM, 1Tb Disk Space, plenty of bandwidth.

I'll pass on the error and have the sysadmin for that linux box try a console install. Odd the installer is reporting a file size different from the actual file size in the .gz archive. First app install that has failed, all others have been OK.

**Comment by nickvergessen** [comment]
> First app install that has failed, all others have been OK.

Yeah, on the other hand Talk might also be one of the biggest apps you tried to install (120+MB unpacked).
On that note, since there was only your report about this it is unlikely an issue in the packaging of the app, as there would be many more when installing would not work at all.

In case you need further help, please try creating a post in the forums:
https://help.nextcloud.com/c/support/7
