### ISSUE TITLE
Talk chat can't edit our own message

### ISSUE THREAD

**Issue by yjjoe-head** [nextcloud/spreed#8483]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Cannot edit our own posted message in Talk. As a user I would like to be able to edit my message after posted

**Describe the solution you'd like**
Get a edit button

**Describe alternatives you've considered**
any ways to edit our own post

**Additional context**

**Comment by nickvergessen** [comment]
Duplicate of #1836

**Comment by mophilly** [comment]
As is said in issue #1836, this is a much needed improvement.
