### ISSUE TITLE
Attachments folder for the other person in a chat is not used, when uploading images / files via "upload from device" on Android app

### ISSUE THREAD

**Issue by nousernameavailableanymore** [nextcloud/spreed#8484]
This one is a bit complicated to explain.

When you have a two person chat (Alice and Bob) and Alice uploads an image via "upload from device" via the Android Talk app, this image is uploaded to Alices attachments folder.
HOWEVER, this image is then linked to Bobs Nextcloud root folder instead of the folder Bob has set for his Talk attachments.

This does NOT occur when opening the image in an image viewer (for example the camera apps galery) and then sharing the image with the Talk app.
In this case, the image is put into Alices Talk attachments folder and linked to Bobs attachment folder (as it should be).

Also, those images in Bobs root folder, cannot be removed or moved to another folder, cluttering the root folder which is very annoying.

---

## Steps to reproduce
1. Have a two person chat (Alice and Bob)
2. Open Talk app for Android
3. in the two person chat, click on the attachments icon next to the message bar
4. select "upload from device" (this should open the Android image picker, see image below)
5. select an image

### Expected behaviour
Image gets uploaded to Alices Talk attachments folder and linked to Bobs attachment folder.

### Actual behaviour
Image gets uploaded to Alices Talk attachment folder and linked to Bobs nextcloud root folder, ignoring the setting for the Talk attachments folder.

## Talk app
**Talk app version:** 14.0.7
**Android app version:** 15.0.3

## Server configuration
**Operating system**: Ubuntu Linux 5.4.0-135-generic x86_64
**Web server:** Apache
**Database:** 	mysql 10.3.37 
**PHP version:** 8.1.12
**Nextcloud Version:** 24.0.8

Image picker:
![image](https://user-images.githubusercontent.com/45376324/208977886-5c28df39-7c83-4d4a-90a7-ac02e5e014d9.png)

**Comment by nickvergessen** [comment]
It's unlikely that this is related to the way Alice shared the file.
It is more related if a race-condition happens for Bob when his files are requested the first time after.

> Also, those images in Bobs root folder, cannot be removed or moved to another folder, cluttering the root folder which is very annoying.

Bob should be able to move the files around just like any other files.

**Comment by nousernameavailableanymore** [comment]
@nickvergessen I have NC Talk 14.0.8 and Android app 15.1.1 installed, however the issue still occurs (in addition to images now having no preview anymore in the Android app, only a placeholder).
