### ISSUE TITLE
Deleting vs removing conversations?

### ISSUE THREAD

**Issue by diplodata** [nextcloud/spreed#849]
I see issue #774 (feat request to delete conversations) has been actioned in 3.2 - excellent!

I'm now unclear what the difference is between _delete conversation_ and _removing conversation from list_.  When I start a new conversation with someone with whom I've just removed one, you'd expect it to reopen previous messages, but it doesn't.  How do you reopen a removed thread?

**Comment by nickvergessen** [comment]
You can't, the only difference is removing will remove it only for you, deleting deletes for everyone.
When you once left, you need to be readded by a moderator/owner.

**Comment by diplodata** [comment]
Thanks Nick.  I note the current behaviour is that:

- Users A and B have an existing chat thread
- User A selects "remove conversation from list"
- User B can still see the conversation, and replies
- User B gets pop-up error "Error occurred while sending message"

Is this intended behaviour?

Aside from that error message, the behaviour raises I think two issues from UI perspective: firstly that _User A_ might _remove from list_ the thread on the assumption it can be revived (when it cannot); and secondly that there is (for me at least) an inference in "_remove from list_" that it would not kill the thread for others, but when the thread is only 2 people it does kill it, because User B cannot revive it.

**Comment by nickvergessen** [comment]
A conversion can only be deleted by a moderator or by the owner (user which created the conversation (or both users in a one2one conversation

I know see, that the check is somewhat wrong and both items (delete and remove from list) are shown for one to one conversations. We will fix that for the next version (only delete will be displayed).

**Comment by nickvergessen** [comment]
Also it seems that https://github.com/nextcloud/spreed/pull/743 incorrectly doesn't remove the chat anymore for participants that are in the conversation while it is being deleted...

**Comment by nickvergessen** [comment]
> Also it seems that #743 incorrectly doesn't remove the chat anymore for participants that are in the conversation while it is being deleted...

We will deal with that in:
https://github.com/nextcloud/spreed/issues/857
