### ISSUE TITLE
install talk 15.0.2 erro

### ISSUE THREAD

**Issue by TwoDogs2** [nextcloud/spreed#8496]
install talk 15.0.2 erro
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
reference resources：https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
The result is still not good

**Comment by nickvergessen** [comment]
Then you are missing one of the steps from the documentation. Please retry carefully.

**Comment by TwoDogs2** [comment]
> Then you are missing one of the steps from the documentation. Please retry carefully.
Which step did I lose? I actually follow the manual

**Comment by nickvergessen** [comment]
I'd guess step 1, 3 or 4

**Comment by TwoDogs2** [comment]
> https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

is not, I have strictly followed these steps

**Comment by TwoDogs2** [comment]
> I'd guess step 1, 3 or 4

I tried again but failed

**Comment by nickvergessen** [comment]
Can you perform the steps and make a screenshot of each output after the modification?

**Comment by TwoDogs2** [comment]
> Can you perform the steps and make a screenshot of each output after the modification?

Yes, of course，However, I reinstalled it and found that many plug-ins were missing from Apps，See the screenshot for details
![image](https://user-images.githubusercontent.com/121689365/210140384-acdb85db-7f5f-4a8f-bd69-2900bfef31a8.png)

**Comment by TwoDogs2** [comment]
> Can you perform the steps and make a screenshot of each output after the modification?
1.
![image](https://user-images.githubusercontent.com/121689365/210151378-8295eb7c-8108-484f-b1d8-4d8bd4bac459.png)
2.
![image](https://user-images.githubusercontent.com/121689365/210151382-f8972d7b-fb71-4395-96de-a109314d7850.png)
3.
![image](https://user-images.githubusercontent.com/121689365/210151393-20901320-b330-4c47-8a0e-e2f1dc5376be.png)
4.
![image](https://user-images.githubusercontent.com/121689365/210151399-062070a4-c429-4fd6-8a19-ddcab04e3941.png)
5.
![image](https://user-images.githubusercontent.com/121689365/210151405-bc4f090c-146c-4b6a-ab72-b71e42b4978c.png)
6.
![image](https://user-images.githubusercontent.com/121689365/210151410-b448f140-a81a-4409-8597-fd6567958861.png)
7.
![image](https://user-images.githubusercontent.com/121689365/210151414-94107fcc-a3b0-46d9-a72e-f5a02161a78a.png)
8.
![image](https://user-images.githubusercontent.com/121689365/210151438-fda548b7-031e-458d-98b6-f595332841da.png)

**Comment by TwoDogs2** [comment]
> Can you perform the steps and make a screenshot of each output after the modification?

I turned off the maintenance mode and re executed steps 5 and 6, but it still didn't work
![image](https://user-images.githubusercontent.com/121689365/210152034-fc148f04-832a-4b34-9845-241d1378d120.png)
![image](https://user-images.githubusercontent.com/121689365/210152039-f182be74-9355-465b-94bf-bdbf42858b13.png)

**Comment by nickvergessen** [comment]
Between screenshot 2 and 3 you are missing:

> Restart the MySQL server in case you changed the configuration in step 1.

That is what activates your changes from the previous steps and only then it works

**Comment by TwoDogs2** [comment]
> Between screenshot 2 and 3 you are missing:
> 
> > Restart the MySQL server in case you changed the configuration in step 1.
> 
> That is what activates your changes from the previous steps and only then it works

Hey, my server has been restarted But it still doesn't work

**Comment by TwoDogs2** [comment]
> Between screenshot 2 and 3 you are missing:
> 
> > Restart the MySQL server in case you changed the configuration in step 1.
> 
> That is what activates your changes from the previous steps and only then it works

I restart the service now, but it still doesn't work
![image](https://user-images.githubusercontent.com/121689365/210160623-6781b533-5255-4e03-a2d7-0d3632a60d12.png)

**Comment by nickvergessen** [comment]
Which Maria DB version are you using?

**Comment by nickvergessen** [comment]
Maybe you are using 10.2?
Then check the old manual
https://docs.nextcloud.com/server/20/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier


Not sure why that block was dropped in newer docs as 10.2 is still supported 🤔

**Comment by TwoDogs2** [comment]
> Maybe you are using 10.2? Then check the old manual https://docs.nextcloud.com/server/20/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier
> 
> Not sure why that block was dropped in newer docs as 10.2 is still supported 🤔

Yes, it's a database problem. I upgraded to the 10.9 version and solved it perfectly. Thank you very much

**Comment by TwoDogs2** [comment]
> > Maybe you are using 10.2? Then check the old manual https://docs.nextcloud.com/server/20/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier
> > Not sure why that block was dropped in newer docs as 10.2 is still supported 🤔
> 
> Yes, it's a database problem. I upgraded to the 10.9 version and solved it perfectly. Thank you very much

![image](https://user-images.githubusercontent.com/121689365/210169515-53fd914f-bf03-46b3-9c48-9ffac35ecbed.png)
