### ISSUE TITLE
Transcription of live video calls

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#8503]
**Describe the solution you'd like**
Optional live closed caption transcription of a live video call.  Allows for deaf and hard-of-hearing participation as they can read your words as you talk.

Video and Audio call transcriptions for the deaf and hard-of-hearing.  Only platform I am using with live transcription support is [Zoom](https://duckduckgo.com/?t=ffab&q=zoom+transcription&ia=web).

Transcription support in this case is applied to the live conversation (as opposed to a recording).
- #8504 

**Describe alternatives you've considered**
- #5833
 
**Additional context**
I realize this might well be outside of the realm of what can be built into Talk, but I at least would love to collaborate on ideas and potential fixes.  Thanks for considering either way!  [See this re-post to the forum](https://help.nextcloud.com/t/transcription-of-video-and-audio-calls-for-the-deaf-and-hard-of-hearing/152812)

**Comment by nickvergessen** [comment]
The toughest issue will be to find a service that does transcription for free and has an acceptable outcome.
Privacy respect being the follow up necessity.

**Comment by nickvergessen** [comment]
> Not sure how feasible but whisper.cpp seems to be able to be compiled to WebAssembly: https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm

_Originally posted by @juliushaertl in https://github.com/nextcloud/spreed/issues/3969#issuecomment-1368689728_

**Comment by Kofangun** [comment]
is there news about that subject ? anyone ?
sounds not too difficult with whisper

**Comment by sunjam** [comment]
Guess this is a duplicate of #6915
