### ISSUE TITLE
Transcription of Recordings

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#8504]
**Is your feature request related to a problem? Please describe.**
Creating this issue to keep it differentiated from
- #8503 

**Describe the solution you'd like**
Transcriptions of Talk video or audio call recordings to text.  Allows the deaf and hard-of-hearing to see text transcriptions of a video / audio call.

**Describe alternatives you've considered**
- #5833

Thanks either way for considering.  Understandable if this feature lies outside of scope, but hoping for ideas and suggestions where possible.  :)  [See this re-post to the forum](https://help.nextcloud.com/t/transcription-of-video-and-audio-calls-for-the-deaf-and-hard-of-hearing/152812)

**Comment by nickvergessen** [comment]
The toughest issue will be to find a service that does transcription for free and has an acceptable outcome.
Privacy respect being the follow up necessity.

**Comment by nickvergessen** [comment]
> Not sure how feasible but whisper.cpp seems to be able to be compiled to WebAssembly: https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm

_Originally posted by @juliushaertl in https://github.com/nextcloud/spreed/issues/3969#issuecomment-1368689728_
