### ISSUE TITLE
Talk Admin Panel Fails to Load

### ISSUE THREAD

**Issue by benyanke** [nextcloud/spreed#8516]
## Steps to reproduce
1. Open ${yourNextcloudInstall}/settings/admin/talk
2. White page is returned with no content, errors logged in log file:

`{"reqId":"[redacted]","level":3,"time":"2023-01-03 01:58:33","remoteAddr":"[redacted]","user":"[me]","app":"PHP","method":"GET","url":"/settings/admin/talk","message":"[snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'function_exists', because its argument '$function' content (exec) matched a rule at /nextcloud/apps2/spreed/lib/Settings/Admin/AdminSettings.php#506","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.2.3","data":{"app":"PHP"}}`

### Expected behaviour
Page should load without error.

### Actual behaviour
see above.

## Talk app

**Talk app version:** 15.0.2

**Custom Signaling server configured:**  I don't think so, but I can't see my admin.

**Custom TURN server configured:** I don't think so, but I can't see my admin.

**Custom STUN server configured:**  I don't think so, but I can't see my admin.

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Any

**Browser name:** Any

**Browser version:** Any

### Browser log
nothing notable here

## Server configuration

**Operating system**: Ubuntu (container host)

**Web server:** container: `ghcr.io/wonderfall/nextcloud:25`

**Database:** container: `mariadb:10.7`

**PHP version:** see container

**Nextcloud Version:** 25.0.2

**List of activated apps:**

  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.0
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - health: 1.6.1
  - lookup_server_connector: 1.13.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - settings: 1.7.0
  - spreed: 15.0.2
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.5.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0

**Nextcloud configuration:**
```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "logdateformat": "Y-m-d H:i:s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_X_REAL_IP"
        ],
        "trusted_domains": [
            "[redacted]:443",
            "[redacted]:443"
        ],
        "overwritehost": "[redacted]",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "[redacted]",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "auth.bruteforce.protection.enabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "tasks",
            "files_clipboard",
            "admin_notifications",
            "ownpad",
            "spreedme",
            "twofactor_rcdevsopenotp"
        ],
        "mysql.utf8mb4": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "[redacted]"
        ],
        "default_phone_region": "USA",
        "mail_sendmailmode": "smtp"
    }
}
```

### Server log (data/nextcloud.log)

see above in first section

**Comment by benyanke** [comment]
For what it's worth, as a workaround, I was able to comment out the call in question, as shown below, and it now works.

![image](https://user-images.githubusercontent.com/4274911/210299812-26ad7c46-9a15-41f1-a658-805728da0e8b.png)

**Comment by nickvergessen** [comment]
Please report to `ghcr.io/wonderfall/nextcloud:25` .
We have to be able to check whether we can use a function. Having extra stuff in place that throws when trying to find out if a function can be used is nothing we can work around

**Comment by benyanke** [comment]
Ok, thank you!
