### ISSUE TITLE
Integrate with a hardware conference room solution

### ISSUE THREAD

**Issue by nuokh** [nextcloud/spreed#8532]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can not use our existing conference room hardware natively with Nextcloud Talk. The meeting organisator has to sacrifice his personal laptop and hook it up via HDMI when he chooses Nextcloud Talk for a hybrid meeting. 

Because auf this, Nextcloud Talk is getting neglected by meeting organisators. They prefer Teams, Zoom or Google Meetup. Here, the conference room hardware can take care of everything and the meeting organisator can just walk into the room and press "join meeting" on the conference hardware touchscreen.

**Describe the solution you'd like**
The ability to integrate with a hardware conference room solution of any vendor, e.g. [Logitech](https://www.logitech.com/en-gb/products/video-conferencing/room-solutions.html) or [Polycom](https://www.poly.com/de/de/solutions/platform).

To be specific, with Teams, Zoom or Pexip integration for Polycom I can create a meeting and select a time and a room. When I enter the room ~15 minutes before the meeting starts, the Polycom touchscreen already shows a big button to join the scheduled meeting.

**Describe alternatives you've considered**
Enterprise solutions like [Teams ](https://www.ip-insider.de/polycom-unterstuetzt-microsoft-teams-a-738038/)or [Zoom](https://www.poly.com/de/de/solutions/platform/zoom/video).

**Additional context**
The end result looks like this:
![image](https://user-images.githubusercontent.com/9081831/210827748-579a45f3-2707-4273-988b-bed3db48112a.png)

**Comment by jospoortvliet** [comment]
Hi there,

Generally, anything that just relies on a browser works - so it's doable with some setups. For others, specific hardware that connects to specific software, we don't have it.

We haven't really been approached by any hardware vendor indeed, to build in support. I think they are the party to initiate this, generally. We would be interested in working with them, I imagine. But I don't see how we could initiate this, sorry!

Perhaps you can ask your hardware vendor for Talk support, they can reach out and we'd work on it.

**Comment by thukza** [comment]
Oh this is a very bad response , then they say open source is not supported enough

**Comment by nickvergessen** [comment]
Well first of all without testing hardware it will be tough to develop something alike and keep it working.
On the other side e.g. Citrix can be used already and even better with the upcoming desktop client: https://github.com/nextcloud/talk-desktop
