### ISSUE TITLE
👤 Ask Guest to enter a name when connecting

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#855]
If a guest joins a conversation with a public link, ask him to enter a name.

I know you can change it here: 
![image](https://user-images.githubusercontent.com/16019165/39623291-746d15d0-4f95-11e8-8a4e-7714eab3bc2c.png)

But i think the most won't do this... so why don't ask him when he connects.

**Comment by nickvergessen** [comment]
@jenniferpiperek what do you think design-wise?
New screen like for the password, combine it with password, or just a modal afterwards?

**Comment by BornToBeRoot** [comment]
I would combine it with the passwort. So the user is "forced" to enter something... 

It's similar to Adobe Connect.

**Comment by BornToBeRoot** [comment]
Having only "Guests" in the conversation can be really annoying. 

If a non authenticated user joins a conversation via public link (password protected or not). There should be a dialog in the center of the screen, where the user is forced to enter a name.

- It should not be pre-filled with the name "guest", so the user has to enter something
- Continue button should be enabled when the user has entered at least 3 characters
- No option to cancel/close this dialog

Something simple like this:
![image](https://user-images.githubusercontent.com/16019165/76715473-db148b00-672c-11ea-992d-c6fd698587c8.png)

**Comment by szaimen** [comment]
https://github.com/nextcloud/spreed/issues/855#issuecomment-599297629
I like this solution 👍

But actually I would only force the user to enter a username if he wants to write something, because sometimes I don't want to write something in a public chat but only see what others have written there...

**Comment by jancborchardt** [comment]
A blocking, even soft-blockong modal in this case is a no-go. It introduces an unnecessary step, one we actually had at some point and removed again.

How about this:
If you join as a guest with no name set, the message input placeholder says:

> Writing as "Guest". Set your name

"Set your name" being linkified (primary color) and when clicked, opens sidebar with the name change input.
The rest of the message field is of course normally clickable.

Solves the issue nicely, gives feedback, and doesn't block anything. We only need to make sure it works well on mobile too.

What do you think @ma12-co @nickvergessen?

**Comment by nickvergessen** [comment]
Let's not mess with the `div[content-editable]`. It's bugous enough already with the mention chips and autocomplete.

At least the lobby waiting screen (which is already blocking) can have a direct setting option. Maybe an adjusted placeholder is enough as a first step, maybe even an opened tooltip to draw more attention to the setting?

**Comment by nickvergessen** [comment]
Added to the lobby screen with https://github.com/nextcloud/spreed/pull/3133

So I'm closing this as per above

**Comment by jancborchardt** [comment]
If we do hide the right sidebar by default, and the lobby is not activated (which normally it is not), then this will still be an issue. So I’d still say we keep it open?

What I proposed above will not mess with the contenteditable, but can insert a separate element floating a z-index above the input (or whichever way works). In any case – we should keep tracking this issue as it’s not solved for most cases.

**Comment by ma12-co** [comment]
Since we will have actions in the AppContent, one of these actions could be 'change name'. And that indeed could bring up the mini modal! It's also very mobile friendly!

**Comment by jancborchardt** [comment]
> Since we will have actions in the AppContent, one of these actions could be 'change name'. And that indeed could bring up the mini modal! It's also very mobile friendly!

You mean the 3-dot-menu? This is too hidden for changing your name, since as a guest you might not look in the menu before you start writing.

What’s wrong with the subtle but clear message in the message input field as proposed above at https://github.com/nextcloud/spreed/issues/855#issuecomment-599993308

**Comment by ma12-co** [comment]
> What’s wrong with the subtle but clear message in the message input field as proposed above at #855 (comment)

Nothing really, just a pain of a component to touch xD
cc @nickvergessen

**Comment by Pilzinsel64** [comment]
Some possible optins from my side:
- What's about asking the user for a name either when clicking to the message box where you write your message or right before sending the message?
- If it would be fine for you (for me it would be) force the user by accessing the page, like in the polls app.
- Get an uniquie name from the server, like `Guest 45` or `Guest45`. So you can at least see a difference seeing the number.

And maybe use a similar dialog as the Poll app does for public polls?

What I know is that ~95% of all users don't set a name themself. And that's really horrible.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/spreed/pull/5499#issuecomment-930080553 for the design feedback

**Comment by jancborchardt** [comment]
It would indeed be nice to show a proper modal here. Not only for putting in the guest name, but also for showing the conversation image and name as a quick "Welcome".

Who is interested in making a mockup here @nextcloud/designers? :)

**Comment by szaimen** [comment]
I can do that :)

**Comment by nickvergessen** [comment]
If possible also account for the lobby in case it's active, e.g. before a webinar.

PS that one already has the option it seems but we need to "enforce it":


![Image](https://github.com/nextcloud/spreed/assets/213943/667013c7-7861-4105-a4ea-68fc693d61b3)

**Comment by szaimen** [comment]
Hi, here is my mockup:

| Public call | Lobby |
|---|---|
| ![Board-4](https://github.com/nextcloud/spreed/assets/42591237/bdc224ce-f568-4e07-be69-c87634731e98) | ![Board](https://github.com/nextcloud/spreed/assets/42591237/b3515e34-f9b1-4662-b9a6-cb7ad1f58245) |
| ![Board-3](https://github.com/nextcloud/spreed/assets/42591237/5a3d197d-6d8e-4183-8b78-11a4f27990e2) | ![Board-2](https://github.com/nextcloud/spreed/assets/42591237/90f636f2-adc6-4332-836a-d8771d70ce8b) |

WDYT? :)

**Comment by Antreesy** [comment]
Are we agreed, that a guest shall not continue using (reading, chating) in the joined conversation, until he'll submit a name?
I thought that was blocking before

**Comment by Antreesy** [comment]
> Yes, that was the idea.

No, that's clear from mockup, but not from the UX point of view, in my minds at least.

We're forcing users to input something, but basically prevent them from being anonymous. Maybe, consider an opportunity to "Continue as `Guest`"?

**Comment by szaimen** [comment]
That is why there is a placeholder guest. They could simply type in guest?

**Comment by Antreesy** [comment]
`placeholder !== input`, it should be clear when you have an empty input or a pre-filled one. That lead us to the question, what's better from design perspective, pre-filled input with "Guest", or an additional button?

Also if guests will type that themselves, That would be untranslatable, and supported on the language they've typed it and you're currently using. We have a wide support across the Talk for the default (empty) Guest, typing by themselves will break it:
![image](https://github.com/nextcloud/spreed/assets/93392545/3c71f0c0-ef62-4752-82fe-db6ba281f4c9)

**Comment by szaimen** [comment]
I would actually like to not introduce an extra button for users that want to not change their name. Why should we make it easy for them to keep using guest when we instead want them to enter their name?

**Comment by Antreesy** [comment]
I think, that returns us to 3-years-old discussion: https://github.com/nextcloud/spreed/issues/855#issuecomment-599325630

It's just my opinion, but still, it's better to see `t('Guest')`, than non-translatable `Guest`, or even something less readable like whitespace (` `) which leaves a name row empty, or emoji (`👍`), which breaks avatars.
If person doesn't want to share his name, he could find a lot of other ways to avoid doing that, way worse for other users, than placeholder name. Maybe an additional button is not the best choise here, I agree
