### ISSUE TITLE
API for joining a call does only work with cookies

### ISSUE THREAD

**Issue by BMerz** [nextcloud/spreed#8559]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up a converstion in Nextcloud Talk
2. Use API with following steps (e. g. with curl)
3. Get signalling: curl -X GET -H "Content-Type: application/json" -H "OCS-APIRequest: true" -u "user:pwd" https://server/ocs/v2.php/apps/spreed/api/v3/signaling/settings
4. Set user active: curl -X POST -H "Content-Type: application/json" -H "OCS-APIRequest: true" -u "user:pwd" https://server/ocs/v2.php/apps/spreed/api/v4/room/[conversation]/participants/active
5. Join call: curl -X POST -H "Content-Type: application/json" -H "OCS-APIRequest: true" -u "user:pwd" https://server/ocs/v2.php/apps/spreed/api/v4/call/[conversation]

### Expected behaviour
According to documentation all preconditions should be met.
See:
https://nextcloud-talk.readthedocs.io/en/latest/call/#join-a-call

### Actual behaviour
404 error is reported.
Joining the call only works if cookies are activated. E. g. for curl options -c [file] -b [file] need to be set.
Either behavior of API should be changed or in documentation it should be added which cookies need to be present.

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
15.0.2

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no 

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Browser

curl Version 7.74.0

### Browser log

<details>
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>

```

</details>

## Server configuration

**Operating system**: RaspbianOS

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.1.14

**Nextcloud Version:** 25.0.2

**List of activated apps:**

Talk + others

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
Enabled:
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - guests: 2.3.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2023.1.21
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.2
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.8.2
  - contactsinteraction: 1.4.0
  - encryption: 1.6.0
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - weather_status: 1.3.0

```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
XXX - XXX [15/Jan/2023:18:46:15 +0100] "POST /ocs/v2.php/apps/spreed/api/v4/room/XXX/participants/active HTTP/2.0" 200 2439 "-" "curl/7.74.0"
XXX - XXX [15/Jan/2023:18:46:34 +0100] "POST /ocs/v2.php/apps/spreed/api/v4/call/XXX HTTP/2.0" 404 132 "-" "curl/7.74.0"

```
</details>

**Comment by nickvergessen** [comment]
Yeah cookies are mandatory for all usages of Talk.
On that note, everytime you do not send cookies the request is more expensive for the Nextcloud server to authenticate, so any client should when possible use Cookies, not only for Talk but for everything

**Comment by nickvergessen** [comment]
What kind of client are you working on? 😎

**Comment by BMerz** [comment]
Thanks for the information with the cookies.
Is there a documentation for the cookie handling?
I want to include Nextcloud Talk into my home-automation with a ESP32 controller. As an example: when the door bell rings signal it by a nextcloud call. Chat works already ;-)

**Comment by vitormattos** [comment]
Hi @BMerz,
If you are using PHP, you can use this package:
https://symfony.com/doc/current/components/browser_kit.html
With this package you don't be worried about cookies because this package will store the cookie during a sequence of requests.

**Comment by BMerz** [comment]
Hi @vitormattos ,
thanks for the hint. But for the ESP32 controller I don't use PHP but C and the idf-environment from Espressif.

**Comment by nickvergessen** [comment]
@vitormattos the current scope of the ticket is to add a simple line at the beginning of the documentation that cookies/sessions are at the moment required. Not fiddling around and make calls work without them.

**Comment by vitormattos** [comment]
But, my point is that I reproduced the scenario and at this case I think that cookie isn't required because I don't received an error message as was described.

**Comment by nickvergessen** [comment]
Without cookies you can not join a call, as you first need to join a room.
