### ISSUE TITLE
UI breaks when trying to join a call in a conversation that has no chat message

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/spreed#858]
## Steps to reproduce
1. User joins room A and tap on "Join call".
2. User joins room B (without tapping on "Leave call' on room A).
3. User join call on room B.

### Expected behaviour
User is able to leave call on room B.

### Actual behaviour
User is unable to leave call and the button still says "Join call".
User can navigate to other rooms but looks like is waiting for participant to join a call.

**Comment by nickvergessen** [comment]
> User can navigate to other rooms but looks like is waiting for participant to join a call.

is the very same as #857 

The state of the UI is mixed between "in chat" and "in call"

**Comment by nickvergessen** [comment]
The button does not update because of the chat:
```
TypeError: $element.position(...) is undefined[Weitere Informationen]
chatview.js:406:11
```

So this might be completly solved by #857 

cc @danxuliu

**Comment by nickvergessen** [comment]
Only happens when there are no chat messages at all.

**Comment by nickvergessen** [comment]
Doh, of course we can not calculate the top-margin of nothing to the top
