### ISSUE TITLE
Leave empty calls automatically 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed#8594]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
I was going over some Google meet getting's and seen this option and it was enabled by default so i thought it would be useful  to have maybe under Nextcloud. 

**Additional context**
![image](https://user-images.githubusercontent.com/59488153/214331049-0f620498-e666-41d1-9247-6a7733c361f4.png)

**Comment by nickvergessen** [comment]
I think the better solution is to have and utilize #7518

**Comment by andyxheli** [comment]
I would agree sounds like a good idea.
