### ISSUE TITLE
Class 'OCA\Talk\Vendor\Firebase\JWT\JWT' not found in file '/var/www/nextcloud/apps/spreed/lib/Config.php' line 490

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/spreed#8597]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
Spreed 15.0.3 installed from github source in nc 25.0.3 in Debian 11 throws error log
```
Class 'OCA\Talk\Vendor\Firebase\JWT\JWT' not found in file '/var/www/nextcloud/apps/spreed/lib/Config.php' line 490
```
and UI shows connecting...

No such problem in talk 14.0.5 in nc 24 with same signaling hpb.

Probably caused by change
https://github.com/nextcloud/spreed/commit/79c1920a23147d86aa06aa10789e2d2c40dd54d9
https://github.com/nextcloud/spreed/commit/1cdd96a113eb4912631463c8d273d47f58f0c7a6

### Expected behaviour
No problem with connection setup.

### Actual behaviour
Talk connection is not starting.

## Talk app

**Talk app version:** 15.0.3

**Custom Signaling server configured:** yes - HPB

**Custom TURN server configured:** no

**Custom STUN server configured:** no

**Comment by nickvergessen** [comment]
You need to run `composer install` or `composer install --no-dev` when you use git.

**Comment by pboguslawski** [comment]
Problem was resolved by replacing deps problem workaround that worked for earlier version...
```
make clean-dev
npm install --force
```
...with standard
```
make dev-setup
```
Thank you for pointing in right direction!
