### ISSUE TITLE
Unread mention marker not always shown?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8599]
- 7 starred conversations
- 6 unread conversations (some group, some 1:1) 3 are visible, 3 not

--> no "unread chat" bubble

Some I manually set to "unread" again. But this should not affect it, right?
Hard refresh sometimes show it, but not always.
Sometimes it vanishes when scrolling, but as I understand it, it should be shown again, when I scroll to op of list?

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/spreed/issues/3299#issuecomment-1403329301_

**Comment by nickvergessen** [comment]
I can not reproduce, but maybe someone else can?
cc @Antreesy

**Comment by tobiasKaminsky** [comment]
During testing, @Antreesy pointed out, that this bubble is only shown for @ mentions.
So if there is a 1:1 chat with "just" unread messages it will not show an info.
Same for group chats, which "only" have unread messages.

I think this now leads to false assumption, as it is says "unread messages" and not "unread mentions" (or similiar).

**Comment by tobiasKaminsky** [comment]
@nickvergessen is my last comment true? Is it to designed to not show for unread group chats?

**Comment by nickvergessen** [comment]
The feature is called "unread mentions" so I guess it works as designed and expected at the moment, since mentions in group chats bring up the marker.

**Comment by tobiasKaminsky** [comment]
Not sure what you mean with marker (from a technical pov).
Imagine an important chat, where I set it to notify me on all messages, will I then see this bubble, even without mention? 
Same question for 1:1 chat: If you write me something, I see a small blue unread counter in list, but no big blue bubble.
So in both cases I would loos info that there are unread important messages, as I am trusting the "unread mentions" bubble?

If so, then I'll create a new issue to have this info for all types.

**Comment by nickvergessen** [comment]
> Imagine an important chat, where I set it to notify me on all messages, will I then see this bubble, even without mention?

I guess no from reading the code, as it's not a mention, so no unread mention counter, just a normal read counter => will not match the filter

> Same question for 1:1 chat: If you write me something, I see a small blue unread counter in list, but no big blue bubble.

You will see the "Unread mentions" bubble (marker I talked about)

**Comment by Antreesy** [comment]
> You will see the "Unread mentions" bubble (marker I talked about)

Well, current realisation works with parameter `item.hasUnreadMentions`, which is triggered only with actual @-mentions.
So if we want to add there 1-1 chats, it needs to be develop in addition.

**Comment by nickvergessen** [comment]
That flag is set for 1-1 chats automatically
