### ISSUE TITLE
Feature Request: Circles Integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#860]
Mentioned as an aside on issue #786 for Chat Notifications.  Would be great to add support for Circles sharing to the Talk app -- [here is a link to API information.](https://github.com/nextcloud/circles/wiki)

[Circles - Create Groups of Users and Share with Them](https://github.com/nextcloud/circles)

**Comment by GoetheG** [comment]
This is definitely something that should be part of the roadman the Nextcloud guys have. Circles is a very powerful solution but unfortunately dot every app does offer integration with that.

**Comment by wargreen** [comment]
Is it some news ?
We seem to be at the Following Major :)

**Comment by nickvergessen** [comment]
Sorry, it was moved to the backlog at the moment, because there are other things higher on the priority list. But if someone still implements this, we will put it in the next release.

**Comment by Rick26L** [comment]
I am looking for the possibility to have a better User and Options Management for the Talk App.

For Example:

Deny to Chat with Groups.
Enable the possibility to Chat with circles
Restrict the use of Talk to Users/Groups
Restrict the possibility for Users to initiate Chats/Calls.

**Comment by nickvergessen** [comment]
This was fixed for Talk 8

**Comment by osm-frasch** [comment]
I’m trying to group **external users** together in the CIRCLES App and later invite them to a group chat in TALK (A school class for example). I can't select the Circle in Talk. **Please implement Circle in Talk completely**.  It will be easier to invite **external users in group chats** if it works with Circles.

**Comment by nickvergessen** [comment]
Federation is still on the todo list for Talk completely, see #21
