### ISSUE TITLE
Support sharing of recordings in mobile clients

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8606]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently the mobile clients support starting and stopping a recording. A notification is generated when the recording is stored, but the mobile clients do not offer an option to share the recording, as the web does.

**Describe the solution you'd like**
Mobile clients should allow to execute the action attached to the notification and therefore share the recording in the chat.

**Describe alternatives you've considered**
Have a half-functioning feature.

**Comment by nickvergessen** [comment]
This is done via the notification now, right?

So closing this in favor of #8759
