### ISSUE TITLE
Nextcloud Talk replication/integration with another Nextcloud talk server

### ISSUE THREAD

**Issue by dolphinscorp** [nextcloud/spreed#8619]
Hi Experts

Is it possible to integrate two Nextcloud talks? We have live nextcloud talk which we are going to restrict completely over VPN only. For android apps and public users we want to create another Nextcloud Talk installation (that will be used only for talk purpose and will be used by android apps only). 

Is there way to sync all private and group Talk chats? so that once android user who also have access to VPN only live Nextcloud talk, can find his conversion that he made on public Nextcloud talk?

OS: Debian 11
Nextcloud: 25.0.3

**Comment by nickvergessen** [comment]
So we are working on federation: #21 

The other thing that comes in mind is using the "matterbridge" integration we have already.
