### ISSUE TITLE
<< use of closed network connection >> external signaling errors logs 

### ISSUE THREAD

**Issue by TBI-NS** [nextcloud/spreed#8664]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. 
user connects to talk from any device
2.
He receives messages well and can send them
3.
He uses talk normally

### Expected behaviour
Tell us what should happen
normal use of talk

### Actual behaviour
Tell us what happens instead

févr. 01 08:35:45 **************.fr signaling[3255226]: client.go:303: Error reading from 91.172.218.**7: read tcp 127.0.0.1:8081->127.0.0.1:53820: use of closed network connection

févr. 01 08:36:08  **************.fr signaling[3255226]: client.go:301: Error reading from client 2oPW8JCf-1gjS3w9CFJ1JaRSfKaiuHmKI3Qe1892-QR8PT1ncy01NGQ2ODlXbk5DZ0RkTTJXUXNmSDFUZjBka0RvRkhWanlIVHptU2NSbHZPRDlDQkNON2x0QmY2U2J1RUYzSHFobTRhSDdxamNoY1pJUDdlNnliQ0Y1SWE2R1d4eDBTR2xFZzBYYlVVcGU3U2NfQ1lUQmxvREhfWUJFWGNJZFNocnZTenB0eXd4c2JlU3hoMzhZZzBNTWt4aW9uclZXbVRZS0lxQ2REQm1LbU58MjQ5NjMyNTc2MQ==: websocket: close 1006 (abnormal closure): unexpected EOF

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
Last on all device

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
yes

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
yes

## Browser

**Microphone available:** yes/no
yes
**Camera available:** yes/no
yes
**Operating system:** Windows/Ubuntu/...
Windows / IOS / Android
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

OVH 1Gbit/s 8c/16t

**Operating system**: Ubuntu/RedHat/...

Ubuntu 
**Web server:** Apache/Nginx
Apache
**Database:** MySQL/Maria/SQLite/PostgreSQL
PostgreSQL

**PHP version:** 7.4/8.0/8.1
8.1

**Nextcloud Version:** (see admin page)
Last

**List of activated apps:**
<details>
 - activity: 2.17.0
  - admin_audit: 1.15.0
  - backup: 1.2.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - calendar_resource_management: 0.3.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - data_request: 1.12.0
  - dav: 1.24.0
  - deck: 1.8.3
  - documentserver_community: 0.1.13
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_bpm: 1.0.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - forms: 3.0.3
  - hibp: 0.1.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - ncdownloader: 1.0.2
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.2
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - registration: 2.0.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - uppush: 1.1.3
  - user_migration: 2.0.1
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_media_converter: 1.7.0
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - firstrunwizard: 2.14.0
  - geoblocker: 0.5.7
  - support: 1.8.0
  - twofactor_totp
  - user_ldap

</details>

We are 85 people on the talk, the external signaling server works well but I often see in the signaling server logs << signaling[3255226]: client.go:303: Error reading from 176.166.81.**0: read tcp 127.0. 0.1:8081->127.0.0.1:52430: use of closed network connection>>

Out of the 85 people I would say that there are 20% who have the problem..

**Comment by nickvergessen** [comment]
Hi there, great that you got it working with the external signaling. However the error is either there, or in the network. There is nothing the Nextcloud Server code can do about it.

**Comment by TBI-NS** [comment]
Hello, thank you for your quick response, do you have any idea? because to tell the truth I have made 4 installations of external reporting servers from 4 different sources and I always have this type of error..

I even went so far as to rent 3 servers in 3 different datacenters to check that the network was not the problem..

The dedicated server network has no problem, it's the best French datacenter that is used lol

**Comment by nickvergessen** [comment]
> do you have any idea?

Not really, I'm mainly the PHP backend developer of the Talk server and barely know go, not speaking of the external signaling code at all
