### ISSUE TITLE
Device preview prevents call from starting while editing document

### ISSUE THREAD

**Issue by himpierre** [nextcloud/spreed#8709]
Hello devs.

Here is my problem. When opening a never before opened document and enter the chat for that very document via sidebar I cannot start a call because obviousely talk tries to open the device preview window. It works if I go back to talk and disable the "always show preview screen before joining a call in this conversation". Then starting a call works while having the document open.

I was thinking, maybe pop-up windows are disabled in the browser but it shouldn't work then in the talk app, right?

Question: Is it possible to disable the device preview globally?

## Steps to reproduce
1. open a document
2. start a call
3. nothing happens

### Expected behaviour
video call should start

### Actual behaviour
video call does not start

## Talk app

**Talk app version:** 15.0.3

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 22.0.4

**Browser name:** Firefox 109.1 / Chromium

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1

**Nextcloud Version:** 25.0.3

**Comment by nickvergessen** [comment]
The problem is the Modal is behind the viewer.

**Comment by himpierre** [comment]
> The problem is the Modal is behind the viewer.

Ok, so you are aware if the problem then?

**Comment by nickvergessen** [comment]
#8551 recently noticed similar related things

**Comment by himpierre** [comment]
It would be super cool to have a patch release. I mean, the current behaviour is a little bit to confusing for the user I think.

cheers, t.

Am 6. Februar 2023 22:00:39 MEZ schrieb Joas Schilling ***@***.***>:
>#8551 recently noticed similar related things
>

**Comment by nickvergessen** [comment]
Before we can do a release we need a patch 🤷

**Comment by himpierre** [comment]
Right. :)

Am 2023-02-06 22:33, schrieb Joas Schilling:
> Before we can do a release we need a patch 🤷

**Comment by rriemann** [comment]
I recorded a video of the issue

https://user-images.githubusercontent.com/111932/231517426-bdb88451-519a-4090-9ceb-be0498ea6c1f.mp4

**Comment by himpierre** [comment]
It would not hurt to see that issue fixed. :)

Am 13. April 2023 15:27:41 MESZ schrieb Robert Riemann ***@***.***>:
>I recorded a video of the issue
>
>https://user-images.githubusercontent.com/111932/231517426-bdb88451-519a-4090-9ceb-be0498ea6c1f.mp4
> 
>

**Comment by nickvergessen** [comment]
cc @marcoambrosini since you touch the media preview at the moment, can you increase the z-index of the modal?

**Comment by himpierre** [comment]
Hello Y'all.

Just tried with NC 27.0.1 and Talk 17.0.2. Now it's even worse. I cannot close the Collabora Window anymore to take care of the talk device preview. I had to hard reload the browser window.

cheers, t.
