### ISSUE TITLE
Use the link picker

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/spreed#8714]
In case you want to use the link picker, here is how:

`RenderReferenceEvent` must be dispatched when loading the page. No problem here, it is already done [there](https://github.com/nextcloud/spreed/blob/b6f3890821fd12718c0bc2892b6249e6eaa82a42/lib/Controller/PageController.php#L276) (to tell the apps to load their reference scripts). The reference provider list is now provided via initial state for the picker when `RenderReferenceEvent` is dispatched.

Then, the link picker itself. 3 ways to use it:
- It [will be](https://github.com/nextcloud/nextcloud-vue/pull/3708) included in RichContentEditable one day
- [The helper function](https://github.com/nextcloud/text/blob/main/src/components/Suggestion/LinkPicker/suggestions.js#L30-L40)
This creates a Vue instance which mounts a ReferencePickerModal somewhere. The function returns a Promise which resolves with the link text and rejects if it is closed.
- Directly with the [ReferencePickerModal](https://github.com/nextcloud/vue-richtext/blob/master/src/referencePicker/ReferencePickerModal.vue) component (exposed by vue-richtext as well). It emits "submit" (with the link as data) and "cancel" events. You can optionally pass the initial selected provider ID in a prop.

I don't know if it makes more sense to
1. Immediately post the generated link in the conversation
2. or insert it in the message composition input

The second one, probably.

https://user-images.githubusercontent.com/11291457/217245224-fb25c012-be2e-4785-b14c-feb2c80deff5.mp4

**Comment by nickvergessen** [comment]
Ref #4333 we are going to go with the RichContentEditable

**Comment by nickvergessen** [comment]
#4333 is now merged, so closing this one as when it's not already done it needs fixing in the vue lib anyway.
