### ISSUE TITLE
User status in topbar and conversation list is not synchronized

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8744]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a conversation and leave the conversation open

### Expected behaviour
When the conversation list is updated and we're in a 1:1 conversation, the status should be reflected in the top bar as well. Interestingly enough the message is updated, but the icon is not in this case?

### Actual behaviour
<img width="350" src="https://user-images.githubusercontent.com/1580193/218535858-680e7c5a-0275-4aed-99ba-5204babe7fa7.png" />

## Talk app

**Talk app version:** 15.0.3 on c.nc.c

**Comment by nickvergessen** [comment]
Seem this every now and then. I'm always not sure which combination is the correct data at that moments.

**Comment by nickvergessen** [comment]
From my assumption it's a problem with rerendering of the "conversation icon" component. which might be re-used incorrectly.
