### ISSUE TITLE
Send push notification on every message

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#875]
We should send push notification on every message (not just mention) in rooms/conversations you're part of. Then clients can decide what to show and what not to.

Already more than a few people complained about this, so I suggest we do this fast and release a small release.

cc @Ivansss

**Comment by nickvergessen** [comment]
This will really escalate in the web UI...

Maybe we start with 1on1 rooms? Or really everything?

**Comment by mario** [comment]
The point is, I'll do the following:

- the first message in a conversation: show the text
IF you don't open the chat in the meantime, and I receive n-th notification, I will show "More messages unread" or something similar.

You can either do something similar or ignore the messages, but the request does make sense considering everyone else does it in a very similar way.

**Comment by e-alfred** [comment]
It would be good to have notifications for every message (maybe configurable by the user if they want to "snooze" them temporarily for example) because if a user doesn't always watch their rooms they could miss something.

**Comment by mario** [comment]
This is IHMO quite important so poking this issue one more time :P

**Comment by jookk** [comment]
Missing feature - very important. Without it, talk is more webinar then (vbr, whats..) app replacement...  (My little ⬆️ up)

**Comment by florianwgnr** [comment]
Really important feature in order to get more people to use nextcloud talk. Doesn't work that well if you have to mention someone in their private (2 people) chat in order to send a notification (on their mobile device).

**Comment by john-2000** [comment]
Agree having a number of missed messages would be great.

Also then not needing to reference each person with `@personxyz` would be super

**Comment by eszeus** [comment]
A really important feature, anything new to it?

**Comment by eszeus** [comment]
@mario Any update on this topic? :D Working Notifications for an instant messaging app is a core function.
Just want to push this issue :P

**Comment by nickvergessen** [comment]
> Working Notifications for an instant messaging app is a core function.

Yes, but it was not build to be one. It was build to be a video/audio calling app, which now has chat support. So yes, we might lack a lot of stuff which you think a IM should have, because we aren't one (yet)

And please don't push issues, it just distracts the developers because there are more useless emails.

**Comment by eszeus** [comment]
Hey @nickvergessen , sorry I didnt mean to offend ;)
But it would be awesome to have it as a "must-have", would mean a lot of companies could throw others like whatsapp and co. into the trash and instead using nextcloud much more.

Grüße aus Frankfurt btw^^

**Comment by kokotko1337** [comment]
ou dint saw this feature request ... sorry for dupe

**Comment by eszeus** [comment]
@kokotko1337 its a secret and hidden society here... 

Jk, I didnt find it either first :D

**Comment by GoetheG** [comment]
Before we ask this question @mario we should see a manifesto with clear milestones. Nextcloud is a really good thing and I am thankful for the guys from Nextcloud and all the supporters here. I really am. What I am missing with Nextcloud Talk is a clear statement of what you want to achieve here.

The Nextcloud marketing people say that Nextcloud is a better Dropbox, a better Google Drive, a better Box and so on. It really is cause it's self hosted and it gives me all the tools I need.

What do you want to achieve with Nextcloud Talk? Is it a batter Skype? A better Slack? A better WhatsApp? I just don't know. Or is this just a stand alone thing you have here which has no 'enemy' in mind.

In any way I think that the administrator should have the right to choose how many notifications he'ss allow for the users. And maybe the user should decide that.

**Comment by nickvergessen** [comment]
> In any way I think that the administrator should have the right to choose how many notifications he'ss allow for the users. And maybe the user should decide that.

No, this should not be decided by the admin, but by the user

**Comment by eszeus** [comment]
Anything New? Is there a milestone yet, or a planned implementation? Or is it just 

> Yes, but it was not build to be one. It was build to be a video/audio calling app, which now has chat support. So yes, we might lack a lot of stuff which you think a IM should have, because we aren't one (yet)

And please don't push issues, it just distracts the developers because there are more useless emails.

**Comment by nickvergessen** [comment]
We made this for one2one chats in the last release, see https://github.com/nextcloud/spreed/pull/1029#issuecomment-408484167 for more details.
Further stuff will be done in #1099 once we were able to resolve the iOS problem
