### ISSUE TITLE
Recording service helpers may not be stopped in some cases

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#8750]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
Extracted from #8708 

If a recording is started in the recording server and then stopped again before the recording actually started the service helpers may not be properly stopped in some cases. For example, if the recording is stopped before [the virtual display was launched](https://github.com/nextcloud/spreed/blob/44b741330cba3a8d92ac0383fff69a4fa4411cae/recording/src/nextcloud/talk/recording/Service.py#L209) (which would be highly unlikely, as it would need to be almost immediate), as the starting thread would not be aware that the recording is stopped and, therefore, that the virtual display and the rest of the helpers should not be started.

However, if the virtual display was already launched [it would be stopped when the recording is stopped](https://github.com/nextcloud/spreed/blob/44b741330cba3a8d92ac0383fff69a4fa4411cae/recording/src/nextcloud/talk/recording/Service.py#L305-L312), which would implicitly prevent the browser (and probably the recording) from starting (as the display would not be available, and therefore the browser and recorder processes would fail to start). Nevertheless, it would be better not to rely on that behaviour or, at least, not to rely only on that.

Note that the helpers are properly stopped if the recording is stopped once it has actually started, the problem only happens when stopping the recording while it is being started.

**Comment by nickvergessen** [comment]
Could imagine either to:
* Poll from the recording server
* Add a background job to repeatingly send the stop

**Comment by danxuliu** [comment]
No, no, it is a problem specific to the `Service` Python class due to the threads :-) Sorry if it was not clear.

It should be just a matter of using a proper lock and/or adding a `stopped` attribute to the `Service` class and check it before trying to start a helper.
