### ISSUE TITLE
Talk - High Usage CPU on local PC & Bad Performance when using visio

### ISSUE THREAD

**Issue by Jason-Linux** [nextcloud/spreed#8751]
## Steps to reproduce
1. Start Conf Calll with 20 Persons

### Expected behaviour
We expected that the call is smooth and functional

### Actual behaviour
High CPU Usage on client Computer
Freeze on Visio

## Talk app

**Talk app version:** 15.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows

**Browser name:** Firefox/Chrome/Brave

**Browser version:** 

Firefox : 15.0.3
Chrome : Version 109.0.5414.122

### Browser log

No error in LOG

</details>

## Server configuration

**Operating system**: Rocky Linux

**Web server:** Apache

**Database:** Mysql

**PHP version:** PHP 8.1.9

**Nextcloud Version:** 25.0.1

**List of activated apps:**

Talk
Appointment
2FA
Deck

**Nextcloud configuration:**

Standard Config From Documentation

### Server log (data/nextcloud.log)

No LOG

**Comment by Jason-Linux** [comment]
Can you help me to correct this issue and fix talk to be usable

**Comment by nickvergessen** [comment]
> Custom Signaling server configured: no

As per https://github.com/nextcloud/spreed#scalability and https://nextcloud-talk.readthedocs.io/en/latest/call-experience/ it is simply close to impossible to have a call with 20 people without using the external signaling server (which also is called high-performance backend)

**Comment by Jason-Linux** [comment]
I understand but how i create an external signaling server

**Comment by Jason-Linux** [comment]
I wouldl like Self -hosted my infra

**Comment by fancycode** [comment]
The standalone signaling server is available at
https://github.com/strukturag/nextcloud-spreed-signaling
