### ISSUE TITLE
Use specific object type for recording notifications

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8759]
Ref: https://github.com/nextcloud/spreed/pull/8550

Currently notifications for a stored recording has the type `chat` set. This is difficult on iOS when we want to show actions, because we need to know upfront if these actions should be applied to the received notification. The only way to distinguish "normal" chat notifications and recording notifications is to check the available actions, but this is neither a good solution, nor a future-proof one. Suggestion is to use a specific `object_type` here.

To check with @mahibi 
- [x] Is changing the `object_type` from `chat` a lot of trouble on Android?
   - no problem 
- [x] Does using the links from the `actions` array work for you? The needed parameters (`fileId` and `timestamp`) are not available separately right now. (For iOS this should work)
   - not nice, but should be okay

**Comment by SystemKeeper** [comment]
> * Does using the links from the `actions` array work for you? The needed parameters (`fileId` and `timestamp`) are not available separately right now. (For iOS this should work)

I just realized that I would basically have to do a similar assumption here, like "POST" will be sharing and "DELETE" will be dismissing. Looks like we can't add an identifier to the action element itself: https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md#action-element
So would it be possible to have `fileId` and `timestamp` as parameters somewhere as well or a way to identify an action?

**Comment by nickvergessen** [comment]
- [ ] We should also add the file to subject or message so that the user can click on the file name to preview/listen to the recording before sharing
