### ISSUE TITLE
"isRecordingEnabled()" should check that a recording server is configured

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#8762]
[`isRecordingEnabled()`](https://github.com/nextcloud/spreed/blob/9cb74afbc48d587d406e316680c155686fca7ebd/lib/Config.php#L144-L153) should check that a recording server is configured.

Besides that, although the official recording server requires the HPB I would not check the signaling server, as maybe other third-party recording servers could work without requiring the HPB (if I recall correctly _talked_ does not need an HPB). But that would be secondary, in any case at least it should be checked that a recording server is configured.

**Comment by nickvergessen** [comment]
> if I recall correctly talked does not need an HPB

Yeah, but it also works completely different as far as I know and therefor does not depend on our API endpoints and UI options

**Comment by danxuliu** [comment]
> > if I recall correctly talked does not need an HPB
> 
> Yeah, but it also works completely different as far as I know and therefor does not depend on our API endpoints and UI options

Not right now, but maybe in the future they would like to integrate it with them. Or someone else develops another recording server that does not use the HPB (in fact ours will strictly require the external signaling server only starting with https://github.com/nextcloud/spreed/pull/8756).

Anyway, I have rephrased the issue, as the important part is to check the recording server; not to check the signaling server was just my view on this.

**Comment by danxuliu** [comment]
Fixed in #8874
