### ISSUE TITLE
Guest name disappear when he leaves the conversation

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/spreed#8787]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a new Talk conversation and permit guests to join with URL
2. As a guest, set your nickname and post a message to the conversation
3. See the guest name properly displayed in the conversation
4. The guest leaves the conversation
5. His name is replaced by "Guest" in the conversation

### Expected behaviour
Guest names should be persistent

### Actual behaviour
Guest name are replaced by "Guest" when the guest leave the conversation

**When Guest n°2 is online :** 
![image](https://user-images.githubusercontent.com/6248852/219943877-f4d9ddab-f3a7-4841-a53f-e981eed94b6e.png)

**Guest n°2 leaves the conversation :**
![image](https://user-images.githubusercontent.com/6248852/219943938-6e242f03-556c-45c4-9f0f-7aa3c142a706.png)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
15.0.3

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Browser

**Microphone available:** yes/no
not relevant

**Camera available:** yes/no
not relevant

**Operating system:** Windows/Ubuntu/...
Windows & Ubuntu

**Browser name:** Firefox/Chrome/...
Firefox & Chromium

**Browser version:** 85/96/...
FF 110.0

### Browser log

<details>
```
Insert your browser log here, this could for example include:
not relevant

</details>

## Server configuration
<!--
You can use the Issue Template application to prefill most of the required information: https://apps.nextcloud.com/apps/issuetemplate
-->

**Operating system**: Ubuntu/RedHat/...
Debian

**Web server:** Apache/Nginx
Apache

**Database:** MySQL/Maria/SQLite/PostgreSQL
MariaDB

**PHP version:** 7.4/8.0/8.1


**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - auto_groups: 1.5.1
  - calendar: 4.2.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - emlviewer: 1.0.7
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.4
  - integration_mastodon: 1.0.6
  - integration_twitter: 1.0.3
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.3
  - maps: 0.2.4
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.2
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - passwords: 2023.2.22
  - photos: 2.0.1
  - polls: 4.1.2
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - snappymail: 2.26.2
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - duplicatefinder: 0.0.15
  - encryption
  - extract: 1.3.2
  - files_markdown: 2.3.6
  - tables: 0.2.2
  - twofactor_totp
  - user_ldap

```
</details>

**Nextcloud configuration:**

<details>

```
sudo -u www-data php occ config:list system
```
</details>

### Server log (data/nextcloud.log)
<details>

```
not relevant
```
</details>

**Comment by vitormattos** [comment]
When a guest is added to a room, he have an entry at table attendees and is possible to update this entry to set a custom name.

When the guest is removed from a room, is deleted from table attendees and isn't possible to get the name.

A possible solution  is put a flag on this table to identify who is deleted but this will have a big side effect because we will need to change all to consider this flag.

Other possible way is to have a backup table to store all deleted rows from attendees table.

Thinking here to identify the best way to solve this problem.

**Comment by nickvergessen** [comment]
> Other possible way is to have a backup table to store all deleted rows from attendees table.

That's not a good solution.

We had a guests name table in the past. I guess when we added the attendees table and migrated the guest names we lost that.

Hmm so I guess it's not a simple bug fix but more a missing feature

**Comment by Mer0me** [comment]
I've set a **dirty** workaround waiting for a better solution : I have a cronjob that transform actor_type='guests' in actor_type='users' (oc_comments), and retrieve the display name of the oc_talk_attendee to put it on the actor_id field in the oc_comments table. With that, i think Talk believe it's a deleted user and the cleanup of the attendee table doesn't affect the displayed name in the chat room...

**Comment by nickvergessen** [comment]
Yeah I was thinking about this as well, or at least something a like.
We should either have a new attendee type for "deleted guests" or keep the original entry and make sure they are hidden from the sidebar.

But unluckily that requires coordination across our clients and is therefore not a quick thing to fix.

**Comment by nickvergessen** [comment]
So I just checked the code a bit. We don't delete the attendee anymore when a guest user leaves a room.
However when a guest has an old session fetching the participant list purges them:
https://github.com/nextcloud/spreed/blob/c1970caef4409c05f7e12b4e5a965b13d2a1665f/lib/Service/ParticipantService.php#L985-L1005

This however still deletes the attendees and I think that is exactly where the problem comes from.
Now deleting that code is simple, but it comes with a huge side effect: The table will only grow from here on.
The other thing that I suspect needs changing is the participant endpoint should filter out guests that don't have a session.
