### ISSUE TITLE
Screensharing has a priority over selected / following participant

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#8799]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call between 2+ users
2. As User 1, start screensharing
3. As User 2, try to click on other participants or local video, to manually set it as main

### Expected behaviour
Main place should be occupied by followed participant's / local video, shared screen moved to Stripe

### Actual behaviour
![image](https://user-images.githubusercontent.com/93392545/220111905-16c41a39-310d-4fd5-a5e2-2cfe13d84319.png)
Screensharing occupies both places

## Talk app

**Talk app version:** 16 (probably older versions too)

**Comment by DorraJaouad** [comment]
Is it still reproducible ? 

As I tested, when you are not following the tile, the video is in the stripe and presenter overlay and the screensharing in presentation. When you follow, the tile in stripe is just standard placeholder and the rest remains the same.

**Comment by DorraJaouad** [comment]
Not reproducible anymore
