### ISSUE TITLE
 spreed time is eight hours faster

### ISSUE THREAD

**Issue by zhaoketong** [nextcloud/spreed#8816]
nextcloud time is China time zone;
But the log and spreed time show up in 8 hours

**Comment by nickvergessen** [comment]
The displayed times depend on the user's timezone. It's saved during the login.
Please check the values in `oc_preferences`:
```sql
SELECT * FROM oc_preferences WHERE appid = 'core' AND configkey = 'timezone';
```

**Comment by zhaoketong** [comment]
The&nbsp;oc_preferences.configvalue is Asia/Shanghai,I think it's true&nbsp;


zkt
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joas ***@***.***&gt;; 
发送时间: 2023年2月22日(星期三) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nextcloud/spreed]  spreed time is eight hours faster (Issue #8816)





 
The displayed times depend on the user's timezone. It's saved during the login.
 Please check the values in oc_preferences:
 SELECT * FROM oc_preferences WHERE appid = 'core' AND configkey = 'timezone';

**Comment by FunctionalHacker** [comment]
I have the same issue. The database query returns the correct timezone if `Europe/Helsinki` but still the web interface and Android app shows chat timestamps in UTC.
