### ISSUE TITLE
Ad-hoc Groups

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/spreed#8854]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Describe the solution you'd like**
I would like to have the ability to select users by name lookup and add them into a group without setting up a group name.  This would be similar to Slack or even an SMS app where you can add people to the group before you start the conversation.  Even if the grouping is closed once you start, this would be easier for our organization to use it.  There are some Statically set groups that we use so that is still helpful but have the ability to not create a formal group would greatly increase our use of the app.

**Comment by SystemKeeper** [comment]
Isn't this the same as #8553 ?
