### ISSUE TITLE
Unable to scroll to the bottom of the message list

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8856]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Notice that the "scroll to bottom" arrow is visible
3. Try to scroll to the bottom with the mouse

### Expected behaviour
The arrow and the border above the input should be hidden (in fact, I am already at the bottom of the list)

### Actual behaviour
The only way to "move" to the bottom is to click on the arrow (it doesn't change the scroll location, as I am already at the bottom, but the arrow and the border disappears)

![Bildschirm­foto 2023-02-25 um 22 23 19](https://user-images.githubusercontent.com/1580193/221380399-8c944410-86ba-4dd6-9e45-16450496cd7e.png)

When reloading the page it sometimes works even with scrolling, after switching from conversation 1 to conversation 2 it's not working.

## Talk app

**Talk app version:** 16 Beta 1 on c.nc.c

## Browser

**Browser name:** Chrome & Safari

**Browser version:** 110 & 16.3

**Comment by nickvergessen** [comment]
Similarly to #8868 and #8857 I assume there is an issue with the main container element or the mounting of the app

**Comment by Antreesy** [comment]
Issue goes from ChatView.vue component:
```
isChatScrolledToBottom: getCapabilities()?.spreed?.config?.chat?.legacy || false
```
which converts to `undefined || false`.
Make sense for me to move this logic to MessagesList.vue

**Comment by nickvergessen** [comment]
Let's fix it for now without moving the code place, in case we have to revert the PR. If the problem is a missing casting, we can add it in ChatView.vue?
