### ISSUE TITLE
File upload modal is placed outside of the app

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8857]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Try to upload a file (Attachment icon -> Upload from device)

### Expected behaviour
The preview should be displayed in a modal above the message list

### Actual behaviour
![Bildschirm­foto 2023-02-25 um 22 36 23](https://user-images.githubusercontent.com/1580193/221380759-ac949857-27a1-44ba-b1b4-54f79d17cd4d.png)

## Talk app

**Talk app version:** Latest master and 16 Beta 1 on c.nc.c

## Browser

**Browser name:** Chrome and Safari

**Browser version:** 110 and 16.3

**Comment by nickvergessen** [comment]
I tried downgrading `@nextcloud/dialogs` to 3.2, but that did not fix it.
