### ISSUE TITLE
Shared files are returned as system messages

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8858]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation with shared files

### Expected behaviour
Preview of the file / image should be shown. The message is reactable and can be replied to.

### Actual behaviour
The message is received as a system message which neither is reactable, nor can be replied to.

### Additional infos

The problem comes from #8798, in particular this part:
https://github.com/nextcloud/spreed/blob/9184830ed995a258417f1d4e7d43752c3a9dcc1c/lib/Chat/Parser/SystemMessage.php#L414-L424

For files shared `$metaData['messageType']` is set, but looks like it's an empty string?! Before the change the check for `voice-message` would fail and therefore fallback to setting the message type to `ChatMananger::VERB_MESSAGE`, this is not the case anymore.

Comparison NC 25.0.4 and NC 26 Beta 5:
![image](https://user-images.githubusercontent.com/1580193/221381985-af48a077-2d6a-4586-9c9a-f1876310369d.png)

**Comment by nickvergessen** [comment]
Ah, so i was not wrong. I noticed after the upgrade that a message was missing the avatar and reaction options, but it worked for other images that were posted before 🙈
