### ISSUE TITLE
Breakout room option is shown for public conversations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8865]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

1. Should either show a dedicated error that public rooms are currently not supported, or
2. Hide the option

**Comment by ChristophWurst** [comment]
It also shows for 1-1s. Bug?
