### ISSUE TITLE
Regression: Auto focus of "Message" field when replying to a message does not work anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#8866]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Click "Reply" on a message
2. Start typing
3. Notice the message field was not focused

### Expected behaviour
After clicking the "Reply" action, the message field should be focused, as was the case before.

### Actual behaviour
The message field is not focused.

## Talk app

**Talk app version:** Current on cloud.nc

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 22.04

**Browser name:** Firefox

**Browser version:** 109.0.1

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/issues/8848
