### ISSUE TITLE
Text input is HTML encoded while posting

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8869]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Write a chat message like `Load is > 20`

### Expected behaviour
Chat reads `Load is > 20`

### Actual behaviour
Chat reads `Load is &gt; 20`

## Talk app

**Talk app version:** 16 beta 1

**Comment by nickvergessen** [comment]
Mostlikely regression from #4333

**Comment by nickvergessen** [comment]
`&gt;` is send on the POST request so yeah, that's the origin of the problem

**Comment by SystemKeeper** [comment]
Also if you try to paste something that contains `<` or `>` it will be remove. So pasting `Test <TestInfo>` will result in `Test` being inserted.
