### ISSUE TITLE
Message buttons bar position is unexpected

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8885]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

The message buttons bar positioning is a bit distrubing. It's flipping way too much around up and down and it's hard to focus in a list of single line messages like in the company call.

![Bildschirmfoto vom 2023-02-28 15-28-31](https://user-images.githubusercontent.com/213943/221888134-2df60693-542b-42dd-8477-2adc1f0fd49b.png)

Especially while in a crowded call it's way to hard to focus a dedicated message

**Previous changes regarding the position:** https://github.com/nextcloud/spreed/pull/8716

**Comment by Antreesy** [comment]
Proposed options:
 - increase hover zone for one-line messages
 - display time + check stamp on the left of MessageList
 - display buttons on the right of Message and vertically
 - display buttons on the top-right corner fo Message, shrink buttons size to 32px

**Comment by nickvergessen** [comment]
> What do you mean by hard to focus? Are you talkin about the fact that it disappears when your cursor goes out of the boundary of the buttons bar?

Yeah mostly this and since you are on top of another message it will open the buttons for the new message, while it used to be the correct message in the past

**Comment by nickvergessen** [comment]
E.g.
![image](https://user-images.githubusercontent.com/213943/222089107-7b8958a9-6bd6-44a5-8000-bc1cd132e58b.png)


The problem is that the actions are more over another message than they belong to. that means the slightest mismove making you leave the popover menu will hover the other message instead.
