### ISSUE TITLE
Cursor appears behind placeholder after deleting characters

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/spreed#8893]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Enter some text in the input field
2. Delete all the characters
3. Cursor appears behind the placeholder text

### Expected behaviour
The cursor should be located before the placeholder text

### Actual behaviour
The cursor appears behind the placeholder text

## Talk app

**Talk app version:** c.nc.c

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Arch

**Browser name:** Firefox

**Browser version:** 110

**Comment by nickvergessen** [comment]
Was fixed in the vue lib already, but not yet released:
https://github.com/nextcloud/nextcloud-vue/pull/3835
