### ISSUE TITLE
Drag-n-drop modal on ChatView flickers on `mouseover`, `mouseleave` events

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#8917]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a chat
2. Drag a file to the chat - Modal pops up
3. Try to move a file above borders and text

### Expected behaviour
Modal should be stable

### Actual behaviour
See video:
[drag-drop-flicker.webm](https://user-images.githubusercontent.com/93392545/222408221-8b6b4093-2570-402d-aad3-b278ac8e8773.webm)

## Talk app

**Talk app version:** (16 and below)

**Comment by SystemKeeper** [comment]
Tested on sermo (so latest master), sadly this is not fixed on Safari. In Chrome it's working fine.

**Comment by SystemKeeper** [comment]
@marcoambrosini Probably more suited for you with a Mac 😄

**Comment by nickvergessen** [comment]
@Antreesy @marcoambrosini please have a look together.

It seems to flicker so badly, that letting go opens the file and makes you leave the chat, etc.
