### ISSUE TITLE
Messages with media files and caption

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#8932]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Most of the time i want to support my media file (screenshot, GIF, e.t.c.) with some comments. But now i must do it prior sending the file, or right after it, so another participant don't get it without context

---

**Describe the solution you'd like**
See screenshots and mockups below:

![image](https://user-images.githubusercontent.com/93392545/222542900-9149dfb1-f845-4435-bf14-74f517beb1b8.png)
_Message appearance in chat_

![image](https://user-images.githubusercontent.com/93392545/222548194-046eb355-9287-4ce9-922c-b16d9d77b940.png)
_Upload files modal appearance_

---

**Additional context**
Screenshot was captured after some manipulations in messageStore. It just works out of the box, so probably, there is no problems with passing media and text together:

![image](https://user-images.githubusercontent.com/93392545/222543643-ef14286d-9e97-48d3-bed7-e85a46dc5bf3.png)

**Comment by SystemKeeper** [comment]
See
https://github.com/nextcloud/spreed/issues/5354
https://github.com/nextcloud/talk-ios/issues/779

**Comment by Antreesy** [comment]
Close this as a duplicate of issue 5354 (mockups were moved there)
