### ISSUE TITLE
Misplaced pencil icon for conversation settings modal description

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#8933]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create conversation
2. Open its settings

### Expected behavior

Nice UI

### Actual behavior

![Bildschirmfoto vom 2023-03-03 10-36-19](https://user-images.githubusercontent.com/1374172/222685645-274217a5-7301-4971-9ec8-75ef6af4cbe6.png)

## Talk app

**Talk app version:** gmbh instance

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by ChristophWurst** [comment]
It gets worse

![Bildschirmfoto vom 2023-03-03 10-38-45](https://user-images.githubusercontent.com/1374172/222685972-2efe38d5-28cb-4f79-a62a-8e871d5292bd.png)

**Comment by nickvergessen** [comment]
cc @marcoambrosini @Antreesy

**Comment by Antreesy** [comment]
It's fixable, but i'm confused with both input border and bottom line:

![Screenshot from 2023-03-03 14-15-17](https://user-images.githubusercontent.com/93392545/222729587-7331a345-4cb6-4475-9609-b306cb5c9afe.png)
![Screenshot from 2023-03-03 14-15-12](https://user-images.githubusercontent.com/93392545/222729599-087724ad-b765-47a3-897a-7b762cc8a812.png)

@jancborchardt @nimishavijay maybe we could remove it?
![image](https://user-images.githubusercontent.com/93392545/222730064-5e9feec0-9a4b-4291-8c2a-e6d68a65ab98.png)

**Comment by nimishavijay** [comment]
You're right! we did discuss removing the bottom line in another issue or a design review call. We can get rid of that. Additionally, since the description allows for a lot of text we could increase the height to display 2 lines instead of one. Then the input field could be full width and the buttons could go below the input field. cc @marcoambrosini on this as well
