### ISSUE TITLE
Should not make unknown user ids a `@-mention`

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#895]
If I write just @, it should not change to "Unknown user". In general, if you can't find a proper user, just don't replace it please.

**Comment by nickvergessen** [comment]
I agree, however that needs fixing in the comments manager in the server repo, feel free to ping `@blizzz` on the issue then

**Comment by blizzz** [comment]
:ping_pong: 

Mh, the regex should already ask for at least on other non-whitespace character after the @: https://github.com/nextcloud/server/blob/master/lib/private/Comments/Comment.php#L228 and this tool supports me: https://regex101.com/r/QF23Sv/1

Also, I don't see this happening in file comments. So, I guess it is indeed happening just in Talk, but by code review I don't spot the cause at once. Unless it is unreleased, I cannot reproduce the behaviour @mario describes. 

> user, just don't replace it please.

So, you like having `@58dbcd56-86aa-4dd0-9144-514f91baa42f` in your comment text?

**Comment by mario** [comment]
@blizzz if the user doesn't exist sure? Maybe I really wanted to type "@58dbcd56-86aa-4dd0-9144-514f91baa42f"?

**Comment by mario** [comment]
I don't know. But still. Do you think we should close this issue then @blizzz ?

**Comment by blizzz** [comment]
Yup, also because we don't want to present internal/technical details to end users.
