### ISSUE TITLE
Unsupported browser message for Brave users

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#8966]
Talk runs significantly better on Brave than on Safari, can we please remove the warning or remember when it's been dismissed and never show it again?

<img width="912" alt="Screenshot 2023-03-06 at 15 05 55" src="https://user-images.githubusercontent.com/26852655/223132487-fcdca27b-3589-4cf4-8174-dfb86c8f956b.png">

**Comment by nickvergessen** [comment]
cc @danxuliu anything negative known regarding Brave?

**Comment by solracsf** [comment]
As Brave is Chromium based, i can't see why this would be a problem.

**Comment by nickvergessen** [comment]
@marcoambrosini then send a PR to allow it, (but don't add it to the toast)
