### ISSUE TITLE
Wrong notifications

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#897]
When a user joins a room to enter chat, the other person (or people) get a notification that somebody invited them to a call.

This is just wrong. There should be no notification in this case. The call notification should only happen once the user actually enters THE CALL.

**Comment by nickvergessen** [comment]
We could rename it to `invited you to a (group|private) conversation`.

But I also think that the actual "call notifications" `A group call has started in {call}` are enough. We don't need to notify when nothing happened?

**Comment by mario** [comment]
Like I said in the report, I agree.

**Comment by mario** [comment]
PR is ready, whenever you are :D

**Comment by nickvergessen** [comment]
Wording has been adjusted to reflect the split of conversation/room and call properly
