### ISSUE TITLE
Combine breakout rooms and participants tab

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#9005]

**Comment by marcoambrosini** [comment]
I propose to move the search and adding of new participants to the conversation to a dialog based flow similar to the conversation creation. What we have now is not very clear anyway.

Once that's done, it should be quite trivial to merge the two tabs.
cc @nickvergessen @jancborchardt @nimishavijay

**Comment by nickvergessen** [comment]
> I propose to move the search and adding of new participants to the conversation to a dialog based flow similar to the conversation creation. What we have now is not very clear anyway.

This will be a pain when I e.g. manage speaking rights during our company calls. I need to be able to quickly find people and hand them over some rights, not go via multiple layers first. It's already painful enough to have to switch between chat and participants tab (in a call both are in the sidebar).

**Comment by jancborchardt** [comment]
Agree with @nickvergessen – why put it in a dialog when it is right there. Let's focus on the issue at hand we discussed and not introduce a new layer. :)

**Comment by jancborchardt** [comment]
@nickvergessen isn’t the title of the issue "Combine breakout rooms and participants tab" still what we should do?

**Comment by jancborchardt** [comment]
@nickvergessen right, sounds good! :)
