### ISSUE TITLE
Message jumps when MessageButtonBar is shown at the bottom

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9016]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Hover over the last message

### Expected behaviour
MessageButtonsBar should be shown, without moving the message

### Actual behaviour
The message is moved up a bit and the MessageButtonsBar is not fully visible

https://user-images.githubusercontent.com/1580193/224322708-2fc78678-551a-45d6-ba91-19551c1a3f8b.mov

Probably related to #9003 ?

## Talk app

**Talk app version:** On c.nc.c

## Browser

**Operating system:** MacOS Ventura 13.2

**Browser name:** Chrome

**Browser version:** 110

**Comment by SystemKeeper** [comment]
> at least we won't revert the other PR.

Please no. 😅

Yes, not sure if the current one can be tweaked a bit, otherwise this is way better than the last one.

**Comment by ShGKme** [comment]
With two one-line messages sometimes it makes an infinity loop:

https://user-images.githubusercontent.com/25978914/224427177-0b9c1055-9ccf-43c4-a3bc-21179be8b746.mp4

P.S. the video has lower FPS that the message actually jumps

**Comment by nickvergessen** [comment]
Btw this is Chrome only.
Firefox "underflows" the Input:
![grafik](https://user-images.githubusercontent.com/213943/224428729-c7d499cd-48e3-4d6b-b1e6-e0bde9d7623a.png)
