### ISSUE TITLE
Special symbols replaced when use EmojiPicker

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#9040]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Type on of the `<`, `>`
2. Pick an emoji using the EmojiPicker
3. See result

### Expected behaviour
Tell us what should happen

### Actual behaviour

https://user-images.githubusercontent.com/93392545/224549080-c8a99812-cd07-41e6-831f-64d3162810cd.mp4

Should be the issue with NcRichContenteditable, which parses all the symbols when paste something. Doesn't affect the resulted message, though

## Talk app

**Talk app version:** (16 + 17)

**Comment by nickvergessen** [comment]
This is an issue with upstream, right?
Upstreaming the fix we build in talk should help already?

**Comment by Antreesy** [comment]
It should
