### ISSUE TITLE
Ping useless?

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#907]
What do we use the ping for? I mean, you can always know if user is active if he's pulling messages or pulling signaling stuff.

**Comment by nickvergessen** [comment]
Right, we should update the ping when you pull for signaling messages

**Comment by nickvergessen** [comment]
@fancycode can you confirm this would work for the external signaling too?

**Comment by mario** [comment]
This will need a new capability so I know I don't need to ping :P

**Comment by fancycode** [comment]
The external signaling server has its own ping through the websocket connection. For now it is sending backend ping requests for sessions connected to the external signaling server so they don't expire in Nextcloud:
https://github.com/nextcloud/spreed/blob/53955c8fcd2ba5b05f3b1fdeb13353404dde9ee3/lib/Controller/SignalingController.php#L422

This calls `Room#ping` internally which I'm assuming will stay and will be called internally when clients are pulling messages/signaling? If so, +1 for removing the OCS `Call#pingCall` route.
