### ISSUE TITLE
'Ignore unknown event' error in browser console

### ISSUE THREAD

**Issue by solracsf** [nextcloud/spreed#9080]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
Join a Talk room and observe browser console.
Similar to https://github.com/nextcloud/spreed/issues/5777

![image](https://user-images.githubusercontent.com/12234510/226047502-f27e53c7-3bae-4de3-8b2b-142d556b1790.png)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 14.0.9

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`) yes

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`) yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10

**Browser name:** Brave

**Browser version:** 1.49.120

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1

**Nextcloud Version:** (see admin page) 24.0.10

**Comment by fancycode** [comment]
This is handled since https://github.com/nextcloud/spreed/pull/7472 (Talk 15):

https://github.com/nextcloud/spreed/blob/77ee14308d7a1a38f043b2d953c8b8d47546295b/src/utils/signaling.js#L736-L738

**Comment by nickvergessen** [comment]
> Nextcloud Version: 24.0.10
> Talk app version: 14.0.9

Okay, closing then
