### ISSUE TITLE
Chat msg expiration — doesn’t delete old messages

### ISSUE THREAD

**Issue by Moonbase59** [nextcloud/spreed#9081]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set "message expiration" in a converstion to "1 day" (using cog wheel icon).
2. Let guests participate (using link)
3. Wait for 2 or 3 days: No old messages have been deleted!

### Expected behaviour
Old messages deleted as per description. Users rely on that, for data protection reasons.

### Actual behaviour
Old messages can still be read.

## Talk app

**Talk app version:** 15.0.4

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`) **No info to be found here, using AIO)**

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`) **Same, shows mydownain:3478, checks okay**

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`) **Same, shows `stun.nextcloud.com:443`)**

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** All

**Browser name:** Miscellaneous

**Browser version:** Miscellaneous

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu 22.04 LTS

**Web server:** Whatever AIO installs

**Database:** Whatever AIO installs

**PHP version:** Whatever AIO installs, I _think_ 8.0.something

**Nextcloud Version:** AIO v4.6.2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

(command didn’t work, shows `sudo: php: command not found`)
</details>

**Nextcloud configuration:** (command didn’t work, shows `sudo: php: command not found`)

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```

(command didn’t work, shows `sudo: php: command not found`)
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```

 (Where to get? How?)
</details>

**Comment by nickvergessen** [comment]
This is intentional. The setting is not retroactive similarly to other messengers with such a setting.
