### ISSUE TITLE
Conversation history should load from bottom up and in batches

### ISSUE THREAD

**Issue by josch** [nextcloud/spreed#909]
I ended up text chatting a lot with somebody using the spreed app. Now whenever I open that conversation again, it takes a while until all the old conversation history is downloaded. Thus, this feature request:

Could you make it that, when opening a conversation, it only shows part of the old conversation? Lets say the last n days or the last x messages. And to see the older messages, one would have to scroll to the top and click "show older messages" or something. I think this is how other web-based chat systems do it as well.

Thanks!

**Comment by nickvergessen** [comment]
Hmm we are loading from newest to oldest and should only load more messages when necessary?

Isn't it done like that?

**Comment by josch** [comment]
Right now, messages are loaded from oldest to newest and as messages are loaded, the chat log gets longer and longer. For every long conversations it also eats a lot of CPU and I repeatedly delete long conversations as it takes 20 Minutes to load them once they become long.

**Comment by nickvergessen** [comment]
Is this with the phone/mobile apps or in the browser?

**Comment by josch** [comment]
In the browser.

**Comment by jancborchardt** [comment]
Can confirm on our current cloud.nc version, old messages are loaded first. (Penalizes people for actually using Talk a lot.)

**Comment by nickvergessen** [comment]
Closing in favor of #1164
