### ISSUE TITLE
Use bit flags instead of boolean for "inCall" flag.

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#911]
Currently the flag `inCall` is a boolean field that is `true` when a participant is in the call and `false` when in the room (but not the call yet).

I suggest to change this to an integer so different flags can be encoded into it:
- in call
- with audio
- with video
- with screensharing
- etc.

This will allow showing different icons in the participant list or hiding the video panel if no video is published and will also help with the MCU/phone integration.

@Ivansss @nickvergessen What do you think? I could start working on a PR.

**Comment by Ivansss** [comment]
Good idea 👍  I think that would be a nice feature!
Then we could even move functions like "Select screensharing" there.
So you could see easier who is sharing a screen and select which one you want to see.
