### ISSUE TITLE
Remove unused property

### ISSUE THREAD

**Issue by vitormattos** [nextcloud/spreed#9112]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/1079143/226405708-6301ad94-2d1a-4584-9fe3-efaa86dc9b3e.png)

https://github.com/nextcloud/spreed/blob/7d56efb562eaeb3df80ec0674907fa670e73db14/lib/Service/AvatarService.php#L47

**Describe the solution you'd like**
* [ ] Remove the unused property

**Comment by nickvergessen** [comment]
Fixed by #9113
