### ISSUE TITLE
Discussion: Signal protocol integration

### ISSUE THREAD

**Issue by AndreAle94** [nextcloud/spreed#912]
What do you think of integrating the Signal protocol since it is open source and well documented and the source code is available for the Android, iOs and JavaScript clients. 
This would involve the introduction of end-to-end cryptography for chat messages and audio-video calls using a secure and tested protocol.

**Comment by mario** [comment]
Signal uses WebRTC for audio&video as far as I know, just like we do.

**Comment by AndreAle94** [comment]
yes, I meant for chat messages. Now everything works with simple messages in plain text or am I wrong? Introducing end-to-end encryption would be a step forward in terms of privacy.

**Comment by tatramaco** [comment]
I was about to raise the exact same request as I believe this would be easier than trying to leverage the EE2E provided for files.

**Comment by nickvergessen** [comment]
Duplicate: https://github.com/nextcloud/spreed/issues/683

**Comment by Quotz** [comment]
bump
