### ISSUE TITLE
Chat description: hard/impossible to select/copy text

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#9136]
1. add some info, e.g. shared user/password/url to chat description
2. hover mouse over it, try to select/copy it -> not possible as hover info hides
3. click on chat, to see description: still cannot copy it as text is read-only(?)
4. finally click on edit to select text you want (this is only possible as moderator)

**Comment by Antreesy** [comment]
Currently conversation title and description are wrapped in the anchor, and open conversation settings on click (click works mostly everythere inside TopBar) - same functionality as in the NcAction popover menu:
https://github.com/nextcloud/spreed/blob/64606c9cb25c4d86fc7118c5c8fba55405008e5e/src/components/TopBar/TopBar.vue#L32-L34
![image](https://github.com/nextcloud/spreed/assets/93392545/c2af3489-1ad7-4b78-a8a0-a398dd4febb9)


We may discuss it on design level, what's more important for us (cc @jancborchardt @nimishavijay @marcoambrosini ):
* quickly open conversation settings menu;
* be able to copy name/description text;

**Comment by Antreesy** [comment]
> I think what @tobiasKaminsky is referring to is actially the "Conversation settings" modal.

That's step 3 what you're describing. Text on step 2 is selectable, but on any interaction we open a modal.
So for me, should be fixed in both places:
* Disable click-to-open described above
* Allow to select inside the modal

**Comment by marcoambrosini** [comment]
I think that clicking on the whole element to open the settings is way more important than being able to select text from there. But yes once the settings are open the text should be selectable.
