### ISSUE TITLE
Linkpicker breaks /commands if one has any implemented

### ISSUE THREAD

**Issue by small1** [nextcloud/spreed#9142]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open up a channel in talk 
2. Start typing on your slash command /help
3. Watch the link picker open
4. Type command to end and press enter

### Expected behaviour
If command is matched it should pick that over the link picker. 

### Actual behaviour
Executes one of the options in link picker unless you leave a whitespace after the command 

## Talk app

**Talk app version:** 16

**Custom Signaling server configured:** yes (irrelevant) 

**Custom TURN server configured:** yes (irrelevant(

**Custom STUN server configured:** yes (irrelevant)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Chrome 

**Browser version:** 110.0.5481.177

**Operating system**: Debian 10

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1

**Nextcloud Version:** 26.0.0

**Comment by nickvergessen** [comment]
The actual idea is that the talk commands are smart picker results and therefore can be autocompleted.

**Comment by nickvergessen** [comment]
Btw pressing `ESC` once should stop the link picker

**Comment by nickvergessen** [comment]
Commands are deprecated in favor of webhook bots:

---

Webhook based bots are available in the upcoming Nextcloud 27.1 with Talk 17.1
Preview versions of both are already available, detailed documentation can be found at https://nextcloud-talk.readthedocs.io/en/latest/bots/

Please let us know if you need any help with the API or have any questions on the usage
