### ISSUE TITLE
How to use own Intranet penetration solution without the default configured stun server

### ISSUE THREAD

**Issue by robertbob987** [nextcloud/spreed#9144]
I deployed nextcloud in LAN, I want to use talk for collaboration, I also deployed VPN and frpc to do Intranet penetration, I plan not to use the default stun server of nextcloud talk, but I found that the default configuration is no way to delete, it seems that this is written in the code, how should I solve this problem

**Comment by nickvergessen** [comment]
Set up coturn or any other stun server yourself and configure it

**Comment by isdnfan** [comment]
see the answer in https://help.nextcloud.com/t/how-to-use-own-intranet-penetration-solution-without-the-default-configured-stun-server/158363/3?u=wwe
