### ISSUE TITLE
notification in Android App for chat messages

### ISSUE THREAD

**Issue by laarisyko** [nextcloud/spreed#916]
I'm testing the beta of nextcloud talk. I really like it 👍 

Is there a way to get notifications?

I don't know whether I got a text messages or not. A real chat in the style of Whats App, Threema, ... will not work, if you don't know whether you got a messages. I think this feature is critical to motivate people to switch to nextcloud talk.
Nextcloud talk is really great for small business and I think you get a lot of users if you promote it now as a save alternative, also because of the DSVGO law: https://dsgvo-gesetz.de/

**Comment by jookk** [comment]
https://github.com/nextcloud/spreed/issues/875 related

**Comment by mario** [comment]
Indeed. You currently get notifications on mentions.
