### ISSUE TITLE
Status indicator in app and browser based interface

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/spreed#917]
For my NextCloud server, I'm on a Ubuntu 16.04 based server behind a Verizon FiOS residential account. My server does more than just NextCloud but isn't overworked. I have most of the time got near real-time communication with the video chat app's and great response with the web interface. but...

Sometimes I have a start of a connection that doesn't finish; hangs without tossing the connecting username to the corresponding app on the other device, also successful toss of the usernames, but never starts video or sound. I suspect this is due to using shitty free WiFi at some MacDonald's (works at some but not others). Another time I was so rural America that I had no data and like 2G connectivity.

It would be supremely awesome if I knew before starting a call that I didn't have the bandwidth to succeed. Or that the other person didn't.

Also, maybe this is a separate topic, but I get way better video service app to app than voice-only service. 

Also, maybe this is a separate topic, but I can't seem to connect between an app interface and a web interface. Web to web = yes, app to app = yes.

**Comment by nickvergessen** [comment]
This should be done since a long time already and just recently received another improvement in Talk 13
