### ISSUE TITLE
The browser you're using is not fully supported by Nextcloud Talk. - in Yandex Browser

### ISSUE THREAD

**Issue by byiigor** [nextcloud/spreed#9170]
I use Yandex Browser, based on chromium and get this message.
"The browser you're using is not fully supported by Nextcloud Talk. Please use the latest version of Mozilla Firefox, Microsoft Edge, Google Chrome, Opera or Apple Safari."
All functional fully working.

## Steps to reproduce
1. Open chat in yandex browser https://browser.yandex.com/

### Expected behaviour
No message 
"The browser you're using is not fully supported by Nextcloud Talk. Please use the latest version of Mozilla Firefox, Microsoft Edge, Google Chrome, Opera or Apple Safari." : "Приложение Talk для Nextcloud не полностью поддерживает браузер, который вы используете. Рекомендованные браузеры: Mozilla Firefox, Microsoft Edge, Google Chrome, Opera и Apple Safari.",

### Actual behaviour
Have message:
"The browser you're using is not fully supported by Nextcloud Talk. Please use the latest version of Mozilla Firefox, Microsoft Edge, Google Chrome, Opera or Apple Safari." : "Приложение Talk для Nextcloud не полностью поддерживает браузер, который вы используете. Рекомендованные браузеры: Mozilla Firefox, Microsoft Edge, Google Chrome, Opera и Apple Safari.",

## Talk app
15.0.5

## Browser
Yandex Browser

**Browser version:** 
23.3.0.2246 (64-bit)

**Comment by nickvergessen** [comment]
For Nextcloud 26 with Talk 16 the message was removed for Yandex

**Comment by crocobc** [comment]
Hi there,

Exactly the same problem with Brave browser (Also fully working).

Since the last update (25.0.5). Never add this message before....

Not a problem, just annoying.

Regards

**Comment by nickvergessen** [comment]
Brave was added to the allow list already for the next version
