### ISSUE TITLE
FR: List only people in own group

### ISSUE THREAD

**Issue by gerroon** [nextcloud/spreed#918]
Hi

I am using Nextcloud  13.02 and Talk app 3.2.1

It looks like the talk app is letting everyone to see everyone else in the NC instance when adding people. I find this to be very awkward and not a smart strategy. 

Let me give you an example. I added my son (and added his user to our family group) so he could talk to us and his grandparents. When he opened the talk page to add people, his first comment was that " Why am I seeing some random people here". So it goes for everyone else who are not used to this way of communicating.

So if the user is in "@family" and wants to talk someone using the talk app,  the app should only list people in the "@family" group noone else.

It would be very nice if we could make so that the talk app only lists people in their own group, not  just for visual reasons but  for security, privacy and usability as well.

thanks

**Comment by gerroon** [comment]
Yeah that would be nice indeed, I can read german but that does not help me.

**Comment by gerroon** [comment]
@joergmschulz 

Thanks I will give it a try.

**Comment by mario** [comment]
@gerroon works? So we can close the ticket.

**Comment by gerroon** [comment]
@mario 
Yes it seems to work, I will test it more.
