### ISSUE TITLE
Unexpected INF value for uploadLimit results in bad JSON

### ISSUE THREAD

**Issue by mishamosher** [nextcloud/spreed#9181]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Configure PHP with `upload_max_filesize` and `post_max_size` set to `0`.
2. Configure a Recording backend in the Talk settings.
3. Reload the Talk settings page.

### Expected behaviour
The settings should load and present the saved recording settings.

### Actual behaviour
The saved recording settings are not presented to the user due to an invalid JSON situation.

## Talk app

**Talk app version:** 16.0.1

**Custom Signaling server configured:** e93291b10007779997577d6f8e368a2bb91822b7

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Any

**Browser name:** Any

**Browser version:** Any

### Browser log

<details>
```
    Error: Could not parse initial state recording_servers of spreed
    at R (index.esm.js:19:15)
    at i.beforeMount (RecordingServers.vue:120:1)
    at Pt (vue.runtime.esm.js:3017:61)
    at cn (vue.runtime.esm.js:4031:13)
    at e (vue.runtime.esm.js:3854:5)
    at nr.$mount (vue.runtime.esm.js:8772:12)
    at init (vue.runtime.esm.js:4407:19)
    at vue.runtime.esm.js:6567:17
    at p (vue.runtime.esm.js:6521:13)
    at h (vue.runtime.esm.js:6640:17)
```
</details>

## Server configuration

**Operating system**: Any

**Web server:** Any

**Database:** Any

**PHP version:** Any

**Nextcloud Version:** 26

## Additional information

The core of the issue is a combination of a non-JSON encodable INF value:
https://github.com/nextcloud/server/blob/9e73412e3f596d3bed478ecce4d014950d8993e9/lib/private/legacy/OC_Helper.php#L425

An attempt to encode such INF:
https://github.com/nextcloud/spreed/blob/2c98b323e68ef65d3176f13bf9bcd09fa14287b4/lib/Settings/Admin/AdminSettings.php#L480

And the PHP array containing the INF value that can't be enconded into a JSON:
https://github.com/nextcloud/server/blob/3f231d68d7066d605f261f652f5263613d56ada4/lib/private/InitialStateService.php#L67

Maybe a check with `is_infinite()` and returning `0` instead would be a solution?

**Comment by nickvergessen** [comment]
Patch at https://github.com/nextcloud/spreed/pull/9244/files if you want to test it

**Comment by mishamosher** [comment]
Tested and working!
