### ISSUE TITLE
Can't send a message to a single breakout room from main room

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#9183]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a call
2. Start breakout rooms session
3. Try to send a message from main room to breakout room

### Expected behaviour
Message should be sended to server

### Actual behaviour
Temporary message saved in the store and shown as loading, but there is some error when sending request

https://user-images.githubusercontent.com/93392545/228173180-7eb63c61-8c7e-4525-832a-3f7b01800ea7.mp4

## Talk app

**Talk app version:** 16, 17

## Browser
**Operating system:** Ubuntu
**Browser name:** Chrome

### Browser log
```
{
   "message":"Request failed with status code 400",
   "name":"AxiosError",
   "config":{
      "transitional":{
         "silentJSONParsing":true,
         "forcedJSONParsing":true,
         "clarifyTimeoutError":false
      },
      "transformRequest":[
         null
      ],
      "transformResponse":[
         null
      ],
      "timeout":0,
      "xsrfCookieName":"XSRF-TOKEN",
      "xsrfHeaderName":"X-XSRF-TOKEN",
      "maxContentLength":-1,
      "maxBodyLength":-1,
      "env":{
         "FormData":null
      },
      "headers":{
         "Accept":"application/json, text/plain, */*",
         "Content-Type":"application/json",
         "requesttoken":"4g3KH/qtVEZLYaJZ8s7EmrdMRHYdH4E1+mxBYztyx00=:zXTyL5TbbSR+UM4Pm4ilyPhnDwxnRs5kw185SFcRqw8="
      },
      "method":"post",
      "url":"https://sermo.nextcloud.com/ocs/v2.php/apps/spreed/api/v1/breakout-rooms/8024839283/broadcast",
      "data":"{\"message\":\"test\",\"token\":\"8024839283\"}"
   },
   "code":"ERR_BAD_REQUEST",
   "status":400
}

```

**Comment by nickvergessen** [comment]
`breakout-rooms/8024839283/broadcast` is always distributing to all breakout-rooms

To write to a dedicated room the normal messaging endpoint should be used
