### ISSUE TITLE
Message expiration: Last message is not previewed in the left pane

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#9185]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a conversation 
2. Write a message in the conversation
3. Set expiration to 1 hour (handy for testing, another value should give the same behaviour)
4. Write another message
5. Let the message expire

### Expected behaviour

The conversation in the conversation pane should preview the latest message as in other conversations. In the example above should be the message written in step 2.

Maybe related is another issue that I noticed. In a 1-to-1 conversation when there are no messages in a conversation for a longer time period than the expiration period and when there were some messages before the expiration was set, a persistent and inconsistent unread notification was shown. I had to delete the conversations to get rid of these notifications.

### Actual behaviour
The conversation in the conversation pane doesn't show any message below the title. In the Android app a "No messages yet" is shown.

## Talk app

c.nc.com

## Server configuration

c.nc.com 

**Nextcloud configuration:**

c.nc.com

**Comment by nickvergessen** [comment]
Well see how we can solve it on the web and depending on that create a follow up for Android

**Comment by pmarini-nc** [comment]
> Maybe related is another issue that I noticed. In a 1-to-1 conversation when there are no messages in a conversation for a longer time period than the expiration period and when there were some messages before the expiration was set, a persistent and inconsistent unread notification was shown. I had to delete the conversations to get rid of these notifications.

Currently experiencing this on c.nc.com in conversation: 4516360567

**Comment by nickvergessen** [comment]
So currently this is the result:

Desktop | iOS | Android
---|---|---
![Bildschirmfoto vom 2023-03-29 14-14-08](https://user-images.githubusercontent.com/213943/228532063-c229483a-2747-4d70-8529-469cf468c5bd.png) | ![IMG_0089](https://user-images.githubusercontent.com/213943/228532122-ca9df7d1-c28b-4a2c-adf8-fc396bd522b9.jpg) | ![grafik](https://user-images.githubusercontent.com/213943/228533116-1094307b-f954-4edb-aa23-b80b407c1540.png)

The problem is the state that the message was dropped due to expiration is unknown to the clients. So I would assume it's better to have an empty subline.

cc @nimishavijay @marcoambrosini

**Comment by nickvergessen** [comment]
🏓  @nimishavijay @marcoambrosini can we have some feedback?

**Comment by nickvergessen** [comment]
> Is it not possible to show the latest non-expired message? That would be the ideal case, as mentioned.

Unluckily not at the moment.

So raised an issue in android to align:
https://github.com/nextcloud/talk-android/issues/3019
