### ISSUE TITLE
Use the conversationIcon component in mentions

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#9188]
Do we want to use the avatar also in mentions?

![image](https://user-images.githubusercontent.com/25978914/225577272-00c4c866-e04b-4cec-8f64-c934101b2e1c.png)

![image](https://user-images.githubusercontent.com/25978914/225578579-e35d570e-77b9-4ecb-bf83-a1a3e983a513.png)

_Originally posted by @ShGKme in https://github.com/nextcloud/spreed/pull/9059#pullrequestreview-1343192187_

**Comment by ShGKme** [comment]
Don't we want to use the avatar also in the chat message? (the second example in the issue)
