### ISSUE TITLE
Own video is only partly visible in speaker mode

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9203]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Join a group call in speaker mode

### Expected behaviour
With the stripe visible, my own video should be fully visible

### Actual behaviour

Video is partly hidden behind sidebar
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1580193/228531437-ce241c00-5821-4e8d-b57e-766f6dfec50b.png">

GridDebug
```
{
    "minWidth": 200,
    "minHeight": 150,
    "videosCap": 19,
    "videosCapEnforced": false,
    "targetAspectRatio": 1,
    "videosCount": 6,
    "videoWidth": 208,
    "videoHeight": 250,
    "devicePixelRatio": 2,
    "dpiFactor": 1,
    "dpiAwareMinWidth": 200,
    "dpiAwareMinHeight": 150,
    "gridAspectRatio": "3.3",
    "columnsMax": 4,
    "rowsMax": 1,
    "numberOfPages": 2,
    "videoContainerAspectRatio": 0.832,
    "bodyWidth": 1512,
    "bodyHeight": 830,
    "gridWidth": 832,
    "gridHeight": 250
}
```

### Workaround
* Switch to grid mode
* Switch back to speaker mode

Grid Debug after workaround
```
{
    "minWidth": 200,
    "minHeight": 150,
    "videosCap": 19,
    "videosCapEnforced": false,
    "targetAspectRatio": 1,
    "videosCount": 6,
    "videoWidth": 249.66666666666666,
    "videoHeight": 250,
    "devicePixelRatio": 2,
    "dpiFactor": 1,
    "dpiAwareMinWidth": 200,
    "dpiAwareMinHeight": 150,
    "gridAspectRatio": "3.0",
    "columnsMax": 3,
    "rowsMax": 1,
    "numberOfPages": 2,
    "videoContainerAspectRatio": 0.9986666666666666,
    "bodyWidth": 1512,
    "bodyHeight": 830,
    "gridWidth": 749,
    "gridHeight": 250
}
```

## Talk app

**Talk app version:** 16.0.2 on c.nc.c

## Browser

**Operating system:** MacOS

**Browser name:** Chrome

**Browser version:** 111

**Comment by nickvergessen** [comment]
Happens only with a certain screen size btw
