### ISSUE TITLE
delay between sound and picture in call screen sharing recording

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/spreed#9211]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
I noticed the video (the slides I was sharing) was 4 to 5 seconds in advance on the sound (my voice).
At that moment, I was sharing a window of my computer.

I tried to reproduce a second time, I had a similar issue.

I tried to reproduce this time sharing my whole screen. The video and the sound were correctly synchronized.

I tried to reproduce again, sharing a window. The was a bit of a delay, but much less than the first time.

I tried to reproduce again. This time, when I went back on Talk page to stop the recording, I noticed it was still trying to start the recording 🙃 (I was testing for 30-60seconds maybe... and now after 5 minutes, it is still trying to start the recording 🙃)
![image](https://user-images.githubusercontent.com/87175513/228890095-c2a66b06-c4bc-4ea2-a49b-53f0fca96b49.png)

I am not sure where this delay is rooted. I am not sure how to reproduce.

## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Talk app
c.nc.c
**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows 11

**Browser name:** Firefox

**Browser version:** 111.0.1 (64-bit)

### Browser log
can you update the template to tell people where to fetch browser logs ?

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

c.nc.c

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
@maximelehericy do you have a parallel external recording so we know if the delay is from you sending or on the video generation side?

**Comment by nickvergessen** [comment]
Can recommend https://obsproject.com/ for that. But also could be done by anyone else participating in your calls, or just by carefully observing.

**Comment by nickvergessen** [comment]
Can not reproduce locally and on our instance
