### ISSUE TITLE
status":"failure","statuscode":429,"message":"Reached maximum delay

### ISSUE THREAD

**Issue by TBI-NS** [nextcloud/spreed#9228]
Hello, 

Since this morning my signaling server returns me this error for one of my NC.

I have other NC talk servers running on this signaling server with no issues.

I tried reinstalling talk but no change after reinstalling.

Signaling server log : 

`i1FeVg3X1dMbUE9PXwPrfx81U_uvB5DkPLzvxu7i6xX9CDaxjp8dlRDp1C7NQ==)
avril 01 14:06:02 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 92.184.102.44 has RTT of 82 ms (82.668448ms)
avril 01 14:06:02 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:02 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:03 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 88.169.184.190: read tcp 127.0.0.1:8081->127.0.0.1:45356: use of closed network connection
avril 01 14:06:04 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 92.184.102.44: read tcp 127.0.0.1:8081->127.0.0.1:45388: use of closed network connection
avril 01 14:06:04 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 88.169.184.190 has RTT of 24 ms (24.389272ms)
avril 01 14:06:04 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:05 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 92.184.102.44 has RTT of 39 ms (39.683779ms)
avril 01 14:06:06 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:07 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 88.169.184.190: read tcp 127.0.0.1:8081->127.0.0.1:38190: use of closed network connection
avril 01 14:06:08 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 92.184.102.44: read tcp 127.0.0.1:8081->127.0.0.1:38204: use of closed network connection
avril 01 14:06:09 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 88.169.184.190 has RTT of 16 ms (16.392445ms)
avril 01 14:06:09 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:09 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 92.184.102.44 has RTT of 46 ms (46.949411ms)
avril 01 14:06:09 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:11 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 88.169.184.190: read tcp 127.0.0.1:8081->127.0.0.1:38220: use of closed network connection
avril 01 14:06:11 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 88.169.184.190 has RTT of 19 ms (19.208906ms)
avril 01 14:06:11 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
avril 01 14:06:12 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 88.169.184.190: websocket: close 1006 (abnormal closure): unexpected EOF
avril 01 14:06:12 tchat.liliumnetwork.fr signaling[19785]: client.go:303: Error reading from 92.184.102.44: read tcp 127.0.0.1:8081->127.0.0.1:38224: use of closed network connection
avril 01 14:06:13 tchat.liliumnetwork.fr signaling[19785]: client.go:284: Client from 92.184.102.44 has RTT of 39 ms (39.721809ms)
avril 01 14:06:13 tchat.liliumnetwork.fr signaling[19785]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://nas.nightshift-lyon.fr/ocs/v2.php/apps/spreed/api/v3/signaling/backend
`

**Comment by TBI-NS** [comment]
NC talk A : Talk and HPB signaling => OK
NC talk B : Talk and the same HPB signaling not ok. 

The signaling server configuration has been the same for 8 months and was working perfectly for all NC talk yesterday morning

**Comment by nickvergessen** [comment]
> Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"}

Seems like one server is communicating with a wrong secret
