### ISSUE TITLE
message links doesnt scroll to linked message in chathistory (if they are old)

### ISSUE THREAD

**Issue by nordxONE** [nextcloud/spreed#9232]
When i am searching messages in the talk-webapp and clicking on searchresults which are older messages, it doesnt scroll to the part of the chat, like it does when i click on newer found messages.

its a general problem with links to messages. For example when i try to jump to a message with its link (and its an old message):
https://domain/index.php/call/CALLID#message_123
it wont jump to the text in the chat history.

**Comment by nickvergessen** [comment]
It works when opening the link directly or in a new tab.
The remaining bit is handled in #6046
