### ISSUE TITLE
Typing indicators

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9248]
- [ ] Original issue: https://github.com/nextcloud/spreed/issues/2094
- [x] Server/API https://github.com/nextcloud/spreed/issues/9272
- [x] Frontend https://github.com/nextcloud/spreed/issues/9271
- [ ] Android https://github.com/nextcloud/talk-android/issues/2930
- [x] iOS https://github.com/nextcloud/talk-ios/issues/1181

**Comment by nickvergessen** [comment]
* Account-wide setting:
  * Similar to the read-status setting a account wide setting is added that enables the sending **and** receiving of those messages. So a user can only see the typing indicator, when they are also sharing their own typing status.
  * Setting is stored in oc_preferences like the read-status but not copied to conversation level as it's not needed for the technical side
  * The user's setting is populated as capability setting
* UI:
  * There should be a single line on top of the input field `X is typing …`
  * Maybe with avatars (depends on the looks of it)
  * Showing up to 3? user names
  * If more users are typing we show `X users are typing`
* Technology:
  * To not overload the PHP server with requests we will communicate this information as signaling messages
  * Internal signaling server support is optional
  * The clients/frontend send a signaling message every X seconds when their chat input is non-empty
  * Receiving clients expire the information after X seconds or when receiving a signaling message that the other side stopped

**Comment by nickvergessen** [comment]
Regarding the questions:

* Jan: If it's not a big performance concern I would say yes to both. Cause then guests have a similarly nice experience as people with accounts
* Me: It's more like they don't have a settings page (yet), so either the option is very visible or it's quite some extra efforts (but might be worth it anyway so they can see the keyboard shortcuts, etc)

**Comment by jancborchardt** [comment]
First mockups:
- The line is shown inbetween the last message and the input field, not shifting any messages above (in case people stop typing)
- Includes avatar(s) and a line in `--color-text-maxcontrast`, with the name in bold
- Single person indicator centers the small avatar horizontally with the bigger avatars in the chat (maybe right-align is also fine). Text is "**Name** is typing"
- Multiple people are simply shown comma-separated and with the overlapped avatars (needs a component at some point), up until 3 people like: "**Marco** and **Nimisha** are typing"
- For more than 3 people, only 3 keep showing as avatars and full name (could be either the ones who have most recently typed or have started typing first, whatever is more performant), and ends with "and X others are typing" like "**Nimisha, Marco, Joas** and 3 others are typing"

One person is typing | More than 3 people are typing
-|-
![Typing indicator 1 person](https://user-images.githubusercontent.com/925062/230289101-367262b6-a4f2-4ca1-a058-040814fcd02d.png)|![Typing indicator multiple people](https://user-images.githubusercontent.com/925062/230289110-f47df8c5-6557-49df-a08c-a0a264c50810.png)

**Comment by nickvergessen** [comment]
Just for the record, Nextcloud still does not have the pattern of a "First name" and extracting it from the available user display name does not work for certain languages. Would it be okay to show the full names, or do we want to ignore the concerns from users of those languages (we have the same issue in the left sidebar already)

**Comment by jancborchardt** [comment]
@nickvergessen of course – sorry I forgot about that. Showing full names is fine, and indeed what we should do to be internationally compatible.

**Comment by nickvergessen** [comment]
Closing the meta issue as the most tasks are completed.
