### ISSUE TITLE
Background image (similar to background blur) in calls

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9251]
- [x] Original issue https://github.com/nextcloud/spreed/issues/7637
- [x] Server/API https://github.com/nextcloud/spreed/issues/9268
- [x] Frontend
    - [x] https://github.com/nextcloud/spreed/issues/9269
    - [x] https://github.com/nextcloud/spreed/issues/9270
- [x] ~~Android~~
- [x] ~~iOS~~

**Comment by nickvergessen** [comment]
## Draft

- The device picker aka. interstitial view should also be shown/used when opening device settings while being in a call
- Next to the "Blur background" an option is added to replace the background with an image and picks the option that was used last time
- On selecting an image a second view of the IV is opened which then allows to pick the actual image
- A predefined list (check #7637) will be provided
- Ultimately the user could also upload their own background

## Open questions

- [ ] How can a user uploaded image be provided inside the WebRTC code
- [ ] Should there be restrictions (dimensions and types)

**Comment by marcoambrosini** [comment]
moving design comments here from #7637 

#### 1

1st design pass done, feedback welcome. @jancborchardt @nimishavijay @nickvergessen 
Please note that the first 3 buttons in the background editor need to be designed, but they will likely be an icon + label. Will need something more complex for the custom one. 

<img width="1185" alt="Screenshot 2023-04-05 at 16 41 43" src="https://user-images.githubusercontent.com/26852655/230132819-7035d028-90f5-4177-b1f3-8217105c009b.png">

**Comment by marcoambrosini** [comment]
#### 2

Ok I think I came up with a much better design for this that's way more tidy and much easier to read/scan

<img width="947" alt="Screenshot 2023-04-10 at 14 47 46" src="https://user-images.githubusercontent.com/26852655/230914038-3eb3b4ba-47dc-4d0a-a283-cf4f3ea08261.png">

cc again @nimishavijay and @jancborchardt for feedback

**Comment by R7JANV1** [comment]
The first of the predefined images to select should be the default background image which can be customized under Design by the admin. If there is no custom image set, then the default Nextcloud image with the clouds should appear.

**Comment by jancborchardt** [comment]
@marcoambrosini looks really great! Only tiny feedback:
- [ ] "No effect", "Blur" and "Custom" should be capital first letter
- [ ] From @nimishavijay: Button labels are a bit generic, Choose → Join call
- [ ] The "Back" button is not really needed as we have an X in the top right?
- [ ] Silent call silently went away (the 3 dot menu has that)

**Comment by marcoambrosini** [comment]
@jancborchardt  this has all been addressed and merged already :)

**Comment by fenris** [comment]
can we upload our personal/own/organization background?
