### ISSUE TITLE
Call recording file name could be improved

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#9252]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
The current call recording file names are a bit technical, and if you record a lot of calls then they are not very much distinguished.

E.g. currently a filename looks like: `recording-20230404-130002.webm`

**Describe the solution you'd like**
It would be nice to include the name of the conversation in the beginning like so:
`Design-team-public-recording-20230404-130002.webm`
Probably have to remove emojis and replace spaces with dashes (I assume spaces are not allowed).

**Comment by jancborchardt** [comment]
If including the conversation name is not desired for whatever reason, it would still be nice to capitalize the "R" of "Recording". :)

**Comment by nickvergessen** [comment]
Also we could improve the date handling with `2023-04-04 13-00-02` ? (can't use colon as it breaks syncing to windows, but that's what most OS do with screenshots)
