### ISSUE TITLE
Frontend - Part 2+3 "Background image (similar to background blur) in calls"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9270]
* Overview issue at https://github.com/nextcloud/spreed/issues/9251
* Part 1: https://github.com/nextcloud/spreed/issues/9269

---

## Part 2
- [x] Live preview while picking background
- [x] Allow to upload custom image
- [x] Allow to pick from files
- [x] Proper active feedback to blur, clear and custom buttons
- [ ] Investigate issue with aspect ratio of the video which is changed from 4:3 to 16:9
- [ ] Handle case of old servers (needed for desktop client) and only show the blur feature in that case

**Comment by jancborchardt** [comment]
Here’s my background picks. As I understand we want to ship 8 by default?

These are the ones I would definitely add (intentionally 2 office ones cause I think office will be one of the most common backgrounds):
- Home https://stocksnap.io/photo/house-interior-ZZ1IHRDEML
- Cozy warm office https://stocksnap.io/photo/interior-design-BY59S6FSEP
- White office: https://stocksnap.io/photo/white-room-Y5OWUE5TW7
- Abstract: https://stocksnap.io/photo/abstract-background-RKQU798YK0
- Nature/beach: https://stocksnap.io/photo/nature-path-H5TIZKOQ4Z
- Park https://commons.wikimedia.org/wiki/File:Wooden_footbridge_in_Shinjuku_Gyoen_National_Garden,_Tokyo,_Japan,_a_sunny_day_with_blue_sky.jpg
- Space station: https://images.nasa.gov/details/iss036e005944

Sort of funny ones, we could include a few depending on how many we want:
- Library https://commons.wikimedia.org/wiki/File:Long_Room_Interior,_Trinity_College_Dublin,_Ireland_-_Diliff.jpg
- Stage https://commons.wikimedia.org/wiki/File:La_Fenice_Opera_House_from_the_stage.jpg
- Old workshop: https://commons.wikimedia.org/wiki/File:Werkstatt_eines_Schiffszimmerers_im_Altonaer_Museum_IMG_5128_edit.jpg
- Stadium seats https://stocksnap.io/photo/sport-venue-Y4M9C05O2Q
