### ISSUE TITLE
Since upgrade calls won't connect

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#9277]
Since I upgraded to the latest version of talk my calls will not connect, even if to and from the same network.

I have apache 2.4 on Debian 11
php 8.1/php-fpm
Nextcloud 26
mariadb
coturn for stun/turn
no high performance backend (yet)
no recording backend

I have confirmed that coturn is on and reachable. chat works and calls do ring through but they don't connect

firefox error log shows this:
Connection failed. AHJmZN+e6MGqD+3vtC/7u6lObn+u/ZEdCNGu0FhLKAr1tWPtWZkvtBNMICMpz0S25JhD6ZjTeeLeW7214oufmLPom+iKU2EQ0tuXrhGoM0MQLBooqDQ84Qu5J0PsqOQ7aQ0SoNhYlrSrL3i5/d06K6c+G+/qzAtXtpiSinugfGhtj2ftdDFYU842w7eDPlosKsjQ+rV0EXJB2m4FNKS0XWVzeo7yWFLh63ys/DUxhAPruqqTXJdsCtYmfAUj4vj 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, receiverOnly: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, … }
webrtc.js:864:4

Calls have historically worked fine.

**Comment by Luticus** [comment]
Narrowed it down, for whatever reason calls do not seem to work in firefox or firefox based web browsers so far. In chromium they seem to work fine.

**Comment by nickvergessen** [comment]
That could indicate a misconfigured coturn. IIRC there was a difference in usage between Firefox and Chrome

**Comment by Luticus** [comment]
I've tested with multiple configurations from talk as well.
![image](https://user-images.githubusercontent.com/7807109/231852754-2187676a-c17b-49bc-850a-2826c0207ff3.png)

As you can see, talk thinks turn is reachable. So far all Chrome based clients seem to work, so does Nextcloud talk on Android. 

Any firefox based client, such as librewolf or even firefox itself, shows this:
![image](https://user-images.githubusercontent.com/7807109/231852275-289f8606-989f-45b3-8577-708fec1d6124.png)

**Comment by nickvergessen** [comment]
If this is still an issue for you, please reach out to the forums as this is more a configuration issue on your side and not a bug in talk in general:
https://help.nextcloud.com/c/support/talk/52
