### ISSUE TITLE
Paste Pictures from Clipboard (on MacOS)

### ISSUE THREAD

**Issue by EricSand** [nextcloud/spreed#9292]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I make a screenshot on MacOS and try to paste it into a chat from the OS clipboard.

**Describe the solution you'd like**

Use CMD + V to paste a picture from the OS clipboard into the chat entry field (e.g. Wire MacOS client is able to do that).

**Describe alternatives you've considered**

Saving the screenshot to a file first and then sending it as attachment is very time consuming.

**Comment by nickvergessen** [comment]
CMD+V should definitely work when the chat input is focused

**Comment by EricSand** [comment]
I did some more tests:

On MacOS:
- If you have a screenshot directly in the clipboard, you cannot paste it via context menu or CMD+V
- If you CMD+C a jpg in finder and CMD+V in chat input, it pasts the file path without sending the picture / file
<img width="110" alt="grafik" src="https://user-images.githubusercontent.com/51123902/231080264-666ec1fc-ff01-46e2-9144-12f3b6093128.png">


On iOS:
- If you make a screenshot and select Copy to have it in the clipboard, you cannot paste in the Talk App
- If you go into photos app and copy a picture, you cannot paste in the Talk App

**Comment by SystemKeeper** [comment]
> <img alt="grafik" width="110" src="https://user-images.githubusercontent.com/51123902/231080264-666ec1fc-ff01-46e2-9144-12f3b6093128.png">

This looks like the iOS app, not the web app?! In this case, this is not supported right now, see https://github.com/nextcloud/talk-ios/issues/887

**Comment by EricSand** [comment]
Its the native MacOS client from the MacOS App Store: https://apps.apple.com/de/app/nextcloud-talk/id1296825574
<img width="757" alt="grafik" src="https://user-images.githubusercontent.com/51123902/231092062-dbbdee51-2ae5-4052-8704-82ebaa222edd.png">

**Comment by SystemKeeper** [comment]
Nope, that's the iOS app which is also able to run on Macs with M1/M2 chips (look closely above "Öffnen").
Alternatively there is now a desktop version in beta: https://github.com/nextcloud/talk-desktop
