### ISSUE TITLE
Editor/viewer while in a call

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/spreed#9295]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When there is a meeting taking place and someone shares a text file, photo, etc in the chat and you open it, you cannot see the meeting anymore as that area is covered by the file. So in case you are taking meeting notes, it becomes quite difficult to mute/unmute, or tell who is speaking, etc

**Describe the solution you'd like**
Show the meeting in a smaller container on the screen while the editor/viewer is open.
![image](https://user-images.githubusercontent.com/52440189/231227322-9c3975ff-6a26-4dd5-8882-87b299448dd6.png)

Must haves:
- [ ] The video of the speaker (or avatar placeholder in case the video is off)
- [ ] Controls for your own audio and video

Nice-to-haves:
- [ ] A smaller video of yourself in the corner to check your own video (indicated by the grey square in the bottom right of the speaker video)
- [ ] A button to collapse this container down and continue the call in the background (indicated by the chevron-down icon in the top right corner of the speaker video). Much like it is possible to collapse the videos of others in the speaker view.
- [ ] A button to return to the call view (the maximise button in the top left corner of the speaker video)

**Describe alternatives you've considered**
n/a

**Additional context**

Current state in Files, which would require some cleaning up.
![image](https://user-images.githubusercontent.com/52440189/231227525-568e19af-a3fa-458b-9622-d4e62ab00a36.png)

cc @jancborchardt @AndyScherzinger @nickvergessen 
_(edited to rearrange must-haves and nice-to-haves)_

**Comment by jancborchardt** [comment]
One edit @nimishavijay – I would actually move the "Maximize" button out of "Must have" because the way to return to the call would be to simply close the viewer.

Having a maximize button there would lead to a possibly confusing state where you have a call, with a viewer over it, with a maximized call over it again (?).

So to keep both the technical implementation and the mental model simple, I would cut the "maximize" button as the "x" button of the viewer already has that functionality.

What do you think @nimishavijay?

**Comment by SystemKeeper** [comment]
There’s also this work, which is kind of related https://github.com/nextcloud/spreed/pull/9069

**Comment by nickvergessen** [comment]
> There’s also this work, which is kind of related https://github.com/nextcloud/spreed/pull/9069

Yeah, but after some thoughts and discussions, we think this is the wrong way around and it should not be the editor that is being moved (especially since a small collabora-online etc does not scale)

**Comment by ShGKme** [comment]
> Current state in Files, which would require some cleaning up.

In this proposal, should call in files also looks the same as in the proposal for call view?

**Comment by jancborchardt** [comment]
> For now focus on the "In Talk" experience. We can afterwards see how big the effort is to bring this view over to the files app and public sharing page.

Just for reference @ShGKme: Yes, the idea could be that a bottom right sticky speaker view could work for all sorts of different apps. But yes as @nickvergessen said, for the future. :)
