### ISSUE TITLE
Camera check covered behind Nextcloud office blocks joining calls from document chat sidebar

### ISSUE THREAD

**Issue by rriemann** [nextcloud/spreed#9300]
## Steps to reproduce
1. open a Nextcloud office document and its sidebar
2. join a call
3. notice that the "Camera and Mic Check" modal is covered behind the document

https://user-images.githubusercontent.com/111932/231517426-bdb88451-519a-4090-9ceb-be0498ea6c1f.mp4

### Expected behaviour
The modal appears above the modal.

### Actual behaviour
The modal is very hard to find.

## Talk app**Talk app version:** (see apps admin page: `/index.php/settings/apps`)

16.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** opensuse

**Browser name:** Firefox

**Browser version:** 110.0.1

**Nextcloud Version:** 26.0.0

**Comment by nickvergessen** [comment]
Kind of related to https://github.com/nextcloud/spreed/issues/9295

**Comment by rriemann** [comment]
Duplicate of https://github.com/nextcloud/spreed/issues/8709

I hope both can be solved in next patch release. 💪
