### ISSUE TITLE
AvatarVersion should be populated for all conversation types

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9320]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a group conversation and open it -> group icon (`icon-conversation-group-*`) is retrieved for that conversation and cached
2. Allow guests to join that conversation

### Expected behaviour
The field `avatarVersion` on the room object should change, since a new avatar needs to be loaded (`icon-conversation-public-*`).

### Actual behaviour
Currently the field `avatarVersion` is only populated for custom conversation avatars. But "changes" to the "default" avatars are not reflected there, leaving the wrong conversation icon until the cache expires.

![image](https://user-images.githubusercontent.com/1580193/232319686-1168e62f-471d-4212-89da-f28a6804464f.png)

I would say it's a bug, but you could argue that this is by design and should be considered an enhancement. Not sure.

## Talk app

**Talk app version:** master on sermo

**Comment by SystemKeeper** [comment]
Also in 1-1 conversation `avatarVersion` is also not populated. Not sure if this is possible, but would be nice to invalidate the cache in case an avatar changed.

**Comment by nickvergessen** [comment]
The 1-1 one I'm not sure we can solve in a good performant way

**Comment by SystemKeeper** [comment]
We need to add a header to allow to distinguish between custom and default avatars.
We are now able to get avatars for a conversation from a single API endpoint, wether it's a custom conversation avatar or the default ones. Currently it is possible to distinguish these two by looking at the avatarVersion field which is only set for custom conversation avatars.
When this issue here is solved, this would not be possible anymore. For profile avatars we have a custom http header `X-NC-IsCustomAvatar` which is set in case a custom profile avatar is set. We should do the same for custom conversation avatars.

Background
When editing a conversation we need to decide wether to show a delete option for an avatar or not, because this option is only valid in case there's a custom conversation avatar set.
