### ISSUE TITLE
Mention the smart picker

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/spreed#9322]
Not a big issue. Just wondering if the smart picker could be mentioned in the README or the appstore description so it is more obvious to admins and users that it can be used in Talk.

**Comment by nickvergessen** [comment]
The readme is not shipped, nor do I assume any end-user ever reads it (on updates) nor will they see/read the appinfo/info.xml

But it was added to the "New in Talk" list which we forgot and that will ship with Talk 16.0.3 on Thursday:
https://github.com/nextcloud/spreed/commit/9822155ca542bde151cee68da65ca819c9f02832#diff-efd7969eb986e673c516f027cbca3287f4eaf3f831c59bf6d6ee0da16d7d1231R129
