### ISSUE TITLE
Can't join in video room in nc 26

### ISSUE THREAD

**Issue by Uptobillion** [nextcloud/spreed#9339]
---

## Steps to reproduce
1. make a video to test account(cant connect)
2. use test account to open video room
3. can‘t see and hear each other 

## Talk app

**Talk app version:**16.02

**Custom Signaling server configured:** yes  31aa0e2a1146e287d17be13644ed885efa39ec33

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Chrome

**Browser version:** 85/96/...

</details>

**Database:** Maria

**PHP version:** 8.2

**Nextcloud Version:** 26.0

### Server log (data/nextcloud.log)
<details>
nothing happened!
</details>

**Comment by nickvergessen** [comment]
The provided information is not sufficient enough to be able to help you. Please provide browser logs and screenshots
