### ISSUE TITLE
Error when creating a new conversation

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#9361]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Try to create any conversation (single, group, public)
2. Add participants (or don't)
3. See result

### Expected behaviour
Loading indicator, then correct creating of conversation

### Actual behaviour
Conversation is still created, but visible only with the next fetch request
![image](https://user-images.githubusercontent.com/93392545/233775871-91bce2e7-e816-41b6-b122-5cdb96ed0e4d.png)

## Talk app

**Talk app version:** master

### Browser log

Error creating new private conversation: 
a {message: 'Request failed with status code 500', 
name: 'AxiosError', 
code: 'ERR_BAD_RESPONSE', 
config: {…}, 
request: XMLHttpRequest, 
…}

code: "ERR_BAD_RESPONSE"
config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}
message: "Request failed with status code 500"name: "AxiosError"
request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response: "<?xml version=\"1.0\"?>\n<ocs>\n <meta>\n  <status>failure</status>\n  <statuscode>500</statuscode>\n  <message>Internal Server Error\nCould not resolve OCP\\SpeechToText\\ISpeechToTextManager! Class &quot;OCP\\SpeechToText\\ISpeechToTextManager&quot; does not exist</message>\n </meta>\n <data/>\n</ocs>\n"responseText: "<?xml version=\"1.0\"?>\n<ocs>\n <meta>\n  <status>failure</status>\n  <statuscode>500</statuscode>\n  <message>Internal Server Error\nCould not resolve OCP\\SpeechToText\\ISpeechToTextManager! Class &quot;OCP\\SpeechToText\\ISpeechToTextManager&quot; does not exist</message>\n </meta>\n <data/>\n</ocs>\n"

**Comment by Antreesy** [comment]
cc @nickvergessen should be related with SpeechToText work

**Comment by nickvergessen** [comment]
You need to pull latest master of the server

**Comment by Antreesy** [comment]
It helps, but I'd like to leave it open until it'll be fixed on sermo

**Comment by nickvergessen** [comment]
> until it'll be fixed on sermo

That should happen every night.
