### ISSUE TITLE
Mentions not working anymore for users with spaces

### ISSUE THREAD

**Issue by deviloper** [nextcloud/spreed#9389]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Description

After the last upgrade of NextCloud (26.0.1) and Talk (16.0.3) when I'm using the desktop client (mobile version is working correctly) it does not create tags and doesn't notify the receiver even if notifications are enabled for that chat.

The tags are working correctly in case the tagged user doesn't have an avatar.

## Steps to reproduce
1. Open Nextcloud in a browser on talk interface
2. Start a new chat with a contact who has set an avatar (working correctly without it)
3. Send a new message tagging him with "@"

### Expected behaviour
A tag should be sent as a chip in the chat and the destination client should receive a push notification

### Actual behaviour
- The message contains @""contactname"" instead of the chip
- No push notification sent to the receiver

## Talk app

**Talk app version:** 16.0.3

**Custom Signaling server configured:** yes

**Custom TURN server configured:** no

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Edge

**Browser version:** 112.0.1722.58 (64 bit)

### Browser log

<details>

![image](https://user-images.githubusercontent.com/5602328/235124541-382f8284-422b-4d2c-afcf-8efa0f76223e.png)

</details>

## Server configuration

<details>
An external provider provider manages the server.
</details>

**Comment by nickvergessen** [comment]
Only happens with users that contain a space in the user if

**Comment by nickvergessen** [comment]
Problem origins from https://github.com/nextcloud/nextcloud-vue/blob/6c7b0348f28329e7787805a763194ad282a0e248/src/mixins/richEditor/index.js#L116-L122

It also is reproducable with spaces in group ids.

**Comment by deviloper** [comment]
Thank you!
