### ISSUE TITLE
Allow editing of ffmpegCommon recording parameters for use of GPU acceleration

### ISSUE THREAD

**Issue by rutgerputter** [nextcloud/spreed#9418]
Can we add a config parameter to add additional ffmpegCommon option? I would like to add things like "-hwaccel vaapi" for instance, so we can offload the recording to the GPU.

This is in reference to the following line:
https://github.com/nextcloud/spreed/blob/76eaaee883331b57d37c9cd4a09696c94054a8e0/recording/src/nextcloud/talk/recording/RecorderArgumentsBuilder.py#L53

**Comment by rutgerputter** [comment]
We could add a line in server.conf, in the `[ffmpeg]` section like:

`commonoptions = -init_hw_device vaapi=foo:/dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device foo`

and set:
`outputvideo = -filter_hw_device foo -vf 'format=nv12|vaapi,hwupload' -c:v vp9_vaapi -crf 10 -b:v 1M`

I guess this would be perfect for a Intel iGPU and would lower the cpu load considerably

**Comment by rutgerputter** [comment]
Info source for HW acceleration:
https://trac.ffmpeg.org/wiki/Hardware/VAAPI

**Comment by nickvergessen** [comment]
cc @danxuliu

**Comment by rutgerputter** [comment]
I'm not a Python guru, but I'm testing some of my own work here:
https://github.com/nextcloud/spreed/compare/master...rutgerputter:spreed-gpu:master

Will reply here if it works as expected.
