### ISSUE TITLE
Empty messages should not be possible to send

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9507]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open a conversation
2. Press spacebar 
3. Press return

### Expected behaviour
Nothing should happen, because the message is empty (after trim).

### Actual behaviour
The message is actually send as an empty message. This happens since switching to `NCRichContentEditable` (I think). Corresponding issue of the vue-lib https://github.com/nextcloud/nextcloud-vue/issues/4068.
Not sure if we should prevent this on frontend or backend.

## Talk app

Master, stable26

**Comment by nickvergessen** [comment]
The backend and frontend should prevent this
