### ISSUE TITLE
Adjust layout of the template picker with server update

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9511]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

* Follow https://github.com/nextcloud/server/pull/38174

**Comment by Antreesy** [comment]
I would like to do it after this PR will be merged:
* #9430 

TemplatePreview was refactored, renamed and moved there, so there will be several conflicts (again)

**Comment by nickvergessen** [comment]
That's fine
