### ISSUE TITLE
New message form is not shown in the Talk sidebar of public shares and video verification

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#9529]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

@Antreesy  This is probably a regression from https://github.com/nextcloud/spreed/commit/fd1084bef101f732e6df7c793fd83e716b4de202#diff-3836025d8a95ea6ee32db4350094d4371beeee2384ff8752007852ef0572cc47L45-R45, although I have not checked it (but it can be reproduced on our cloud too, which is running Talk v16.0.3, and the backport of that pull request [is included in that version](https://github.com/nextcloud/spreed/pull/9302)).

## How to test (scenario 1)

- Open the Files app
- Open the right sidebar for a file
- Open the _Sharing_ tab in the sidebar
- Add a new _Share link_
- In a private window, open the share link that was copied to clipboard
- Join the conversation

### Expected behaviour

The _New message_ form is shown at the bottom of the chat view

### Actual behaviour

The _New message_ form is not shown

## How to test (scenario 2)

- Open the Files app
- Open the right sidebar for a file
- Open the _Sharing_ tab in the sidebar
- Add a new _Share link_
- Open the menu for the share link that was just created
- Enable _Password protect_
- Enable _Video verification_
- In a private window, open the share link that was copied to clipboard
- Request password

### Expected behaviour

The _New message_ form is shown at the bottom of the chat view

### Actual behaviour

The _New message_ form is not shown

**Comment by Antreesy** [comment]
main selector for sidebars is undefined, when we're trying to get it:
https://github.com/nextcloud/spreed/blob/fd1084bef101f732e6df7c793fd83e716b4de202/src/components/ChatView.vue#L109

For main app it was defined before mount:
https://github.com/nextcloud/spreed/blob/fd1084bef101f732e6df7c793fd83e716b4de202/src/main.js#L80

So should be done for sidebars as well
