### ISSUE TITLE
StartedTyping signaling message is send for each keystroke

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9548]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Type something in the chat input and observer the signaling messages being send

### Expected behaviour
As far as I understood, we should send one `startedTyping` signaling message to each participant (and to each newly joined participant in case we are still typing) and after a timeout (or sending the chat message) send a `stoppedTyping` to all participants. This means as long as we are continuously typing, we only ever get one `startedTyping` signaling message.

### Actual behaviour
A signaling message is send each time the chat input changes, e.g. for each keystroke.

So either this is a bug on web or we should make this behavior more clear as this will 1.) interfere with the current talk-ios implementation and 2.) not work like this on talk-ios.

## Talk app

Master on sermo

**Comment by nickvergessen** [comment]
@Antreesy is on vacation.

@ShGKme can you have a look maybe?

**Comment by SystemKeeper** [comment]
In general the question is if we can assume that for each `startedTyping` we receive at most one `stoppedTyping`. 
See also questions at https://github.com/nextcloud/spreed/issues/9272#issuecomment-1528757620. 
Should typing indicators be tracked by userid? Or by session? If we receive 2 times `startedTyping` from `user1` and then 1x `stoppedTyping` from `user1` should the typing indicator be hidden for that user or do we wait for the second `stoppedTyping` message to arrive?

**Comment by nickvergessen** [comment]
I think it's somehow sensible to resend the typing, so that if connection is lost, you can ignore old typings after some seconds.
But shouldn't happen on each keystroke I guess. maybe some delay like once per second?
