### ISSUE TITLE
Talk user added to chat with wrong display name when added over group

### ISSUE THREAD

**Issue by support-tt** [nextcloud/spreed#9551]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create chat
2.  Add nextcloud group
3. Log in with newly created user that is created over OpenID Provider

### Expected behaviour
The user should be added to the chat with the given_name parameter

### Actual behaviour
The user is added to the group chat, but in the participants view, the userid is shown instead of the name of the user. When you manually add a user to the chat, the user is shown correctly.

## Talk app

**Talk app version: 15.0.5** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured: yes, 1.1.2** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured: yes** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured: yes** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu 20.04, docker all-in-one image 25.0.4.

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.0

**Nextcloud Version:** (see admin page) 25.0.4

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
This app is not aware of different user backends and also should not be.
It uses the user manager to get the user object and then uses the `IUser::getDisplayName()` function on it.

So if there is any issue, I guess it's a problem with the user backend, because it either is not populating the object correctly, or it is not triggering the `OCP\User\Events\UserChangedEvent` event via the user manager when it modifies the display name.
