### ISSUE TITLE
Support Username and Password authentication for the TURN Server

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed#9552]
Insted of a static auth, can Nextcloud talk support username and password authentication for the TURN Server. Seems liike everyone is going this route.

**Comment by Luncheon3462** [comment]
Please, this is greatly needed.  I do not code, but if a bounty would get this done, I would happily contribute.

**Comment by fancycode** [comment]
See also https://github.com/nextcloud/spreed/issues/3301#issuecomment-617047376
