### ISSUE TITLE
16.0.3: Can't add Guest User Group to Chat Group

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#9566]
I can use all of my user groups here:
![grafik](https://github.com/nextcloud/spreed/assets/24530680/86fff07d-4330-488a-82e7-7c905dc4e26e)

But If I want to add the automatic created (the Guests App does it) Guest User Group, it does not show up here:
![grafik](https://github.com/nextcloud/spreed/assets/24530680/e69e55dd-1e3c-4985-9c16-3974c3427e30)

But it exists in the user management and I already used it for sharing a calender with my guests:
![grafik](https://github.com/nextcloud/spreed/assets/24530680/fc8c0475-b19c-464c-a0b9-25e4f4ff2470)

**Comment by nickvergessen** [comment]
I guess it's not a real group on the groupmanager or the group is automatically excluded from sharing.
But at least it's nothing Talk does, so please report at the guests app 👍
