### ISSUE TITLE
Is it possible not to have two participants with the same nick?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/spreed#957]
Being me the nextcloud manager with nick "tiger" I noticed that in the public chat also another participant can assume my nick by changing the name, is it possible to avoid that more parties are using the same nick? not to worry about mess in the chat?

**Comment by nickvergessen** [comment]
Not really, but when you have an avatar set, guest messages can be identified very easily

**Comment by tigernero79** [comment]
yes, but if I went with nextcloud talk with my nick example: Tiger, and then I use any pc and by shared link, from there I can change my nick as a guest in tiger, so I would find myself with two users with the same name and it's not good it creates confusion
