### ISSUE TITLE
The first letter is not kept in chat 

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/spreed#958]
With Nextcloud Talk, when I start a conversation in public chat via link sharing, when I start writing on smartphone in the chat, the first letter is not kept, if I write "test" exits written "est" I have to click t twice. this error does it only from smartphone browsers on pc works well,

https://github.com/nextcloud/talk-android/issues/190

I'm talking about a mobile browser, if I click on the generated link of the public chat, I'll log in, but when I start writing a word, the first character is not retained if I click it twice. example "test" becomes "est" without "t" if I click the initial twice then the test t remains

**Comment by Ivansss** [comment]
What mobile browser are you using?
That only happens with public conversations or with any type?

**Comment by Ivansss** [comment]
Ok. But what mobile browser are you using? (Chrome, Firefox,...)

**Comment by tigernero79** [comment]
Samsung internet browser and chrome mobile

**Comment by nickvergessen** [comment]
Closing due to the lag of feedback
