### ISSUE TITLE
Don't offer calls to deactivated user accounts

### ISSUE THREAD

**Issue by stweil** [nextcloud/spreed#959]
## Steps to reproduce
1. Deactivate (disable) at least one Nextcloud user.
2. Select the talk app in Nextcloud.
3. Start entering the name of the desired call partner.

### Expected behaviour
Users see a list of potential call partners. This list should not offer the names of deactivated Nextcloud users because those users won't be able to accept the call (their Nextcloud account is disabled).

### Actual behaviour
My Nextcloud 13 installation has several deactivated users. All of these are offered as call partners,

## Browser / OS
Tested with Firefox on Debian GNU Linux, but I expect that the issue is neither browser nor OS specific.

## Spreed app

**Spreed app version:**  Talk 3.2.2 (latest)

**Comment by nickvergessen** [comment]
Will be handled in https://github.com/nextcloud/server/issues/9948
