### ISSUE TITLE
'modifiedSince' not working in room endpoint

### ISSUE THREAD

**Issue by CrazyShipOne** [nextcloud/spreed#9598]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Using PostMan to make a request to https://www.example.com/ocs/v2.php/apps/spreed/api/v4/room?includeStatus=false&modifiedSince=1994892264

### Expected behaviour
According to the [document](https://nextcloud-talk.readthedocs.io/en/latest/conversation/#get-user-s-conversations), if `includeStatus` is not set to **true**, conversation that only has lastActivity after  `modifiedSince` will be returned.

### Actual behaviour
All conversations are returned, even `includeStatus` is set to **false** and `lastActivity` is 10 years later...

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
15.0.5

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)
no

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

not capable

## Server configuration

**Operating system**: Ubuntu/RedHat/...
Official Docker: nextcloud:25

**Web server:** Apache/Nginx
Official Docker: nextcloud:25

**Database:** MySQL/Maria/SQLite/PostgreSQL
MySQL

**PHP version:** 8.0/8.1/8.2
Official Docker: nextcloud:25

**Nextcloud Version:** (see admin page)
Official Docker: nextcloud:25

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
Enabled:  
 - apporder: 0.15.0  
 - bookmarks: 12.1.0  
 - calendar: 4.3.4  
 - camerarawpreviews: 0.8.1  
 - checksum: 1.2.1  
 - cloud_federation_api: 1.8.0  
 - comments: 1.15.0  
 - contacts: 5.2.0  
 - contactsinteraction: 1.6.0  
 - dashboard: 7.5.0  
 - dav: 1.24.0  
 - drawio: 2.1.1  
 - extract: 1.3.5  
 - federatedfilesharing: 1.15.0  
 - federation: 1.15.0  
 - files: 1.20.1  
 - files_external: 1.17.0  
 - files_markdown: 2.4.0  
 - files_mindmap: 0.0.27  
 - files_pdfviewer: 2.6.0  
 - files_rightclick: 1.4.0  
 - files_sharing: 1.17.0  
 - files_trashbin: 1.15.0  
 - firstrunwizard: 2.14.0  
 - logreader: 2.10.0  
 - lookup_server_connector: 1.13.0  
 - maps: 1.0.2  
 - metadata: 0.18.0  
 - nextcloud_announcements: 1.14.0  
 - notifications: 2.13.1  
 - oauth2: 1.13.0  
 - occweb: 0.1.0  
 - password_policy: 1.15.0  
 - photos: 2.0.0  
 - privacy: 1.9.0  
 - provisioning_api: 1.15.0  
 - rainloop: 7.2.6  
 - ransomware_protection: 1.14.0  
 - recommendations: 1.4.0  
 - related_resources: 1.0.3  
 - richdocuments: 7.1.4  
 - serverinfo: 1.15.0  
 - settings: 1.7.0  
 - sharebymail: 1.15.0  
 - spreed: 15.0.5  
 - support: 1.8.0  
 - survey_client: 1.13.0  
 - systemtags: 1.15.0  
 - talk_matterbridge: 1.26.0  
 - text: 3.6.0  
 - theming: 2.0.0  
 - twofactor_backupcodes: 1.14.0  
 - updatenotification: 1.15.0  
 - user_ldap: 1.15.0  
 - user_status: 1.5.0   
 - viewer: 1.9.0  
 - weather_status: 1.5.0  
 - workflowengine: 2.7.0
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
```json
{
	"system": {
		"htaccess.RewriteBase": "/",
		"enable_previews": false,
		"memcache.local": "\\OC\\Memcache\\APCu",
		"apps_paths": [
			{
				"path": "/var/www/html/apps",
				"url": "/apps",
				"writable": false
			},
			{
				"path": "/var/www/html/custom_apps",
				"url": "/custom_apps",
				"writable": true
			}
		],
		"memcache.distributed": "\\OC\\Memcache\\Redis",
		"memcache.locking": "\\OC\\Memcache\\Redis",
		"redis": {
			"host": "***REMOVED SENSITIVE VALUE***",
			"password": "***REMOVED SENSITIVE VALUE***",
			"port": 6379
		},
		"passwordsalt": "***REMOVED SENSITIVE VALUE***",
		"secret": "***REMOVED SENSITIVE VALUE***",
		"trusted_domains": [
			"localhost",
			"example.com"
		],
		"trusted_proxies": "***REMOVED SENSITIVE VALUE***",
		"trashbin_retention_obligation": "30, 60",
		"overwriteprotocol": "https",
		"datadirectory": "***REMOVED SENSITIVE VALUE***",
		"dbtype": "mysql",
		"version": "25.0.0.18",
		"overwrite.cli.url": "http://localhost",
		"dbname": "***REMOVED SENSITIVE VALUE***",
		"dbhost": "***REMOVED SENSITIVE VALUE***",
		"dbport": "",
		"dbtableprefix": "oc_",
		"dbuser": "***REMOVED SENSITIVE VALUE***",
		"dbpassword": "***REMOVED SENSITIVE VALUE***",
		"installed": true,
		"instanceid": "***REMOVED SENSITIVE VALUE***",
		"ldapIgnoreNamingRules": false,
		"ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
		"mysql.utf8mb4": true,
		"maintenance": false,
		"mail_smtpmode": "smtp",
		"mail_sendmailmode": "smtp",
		"mail_from_address": "***REMOVED SENSITIVE VALUE***",
		"mail_domain": "***REMOVED SENSITIVE VALUE***",
		"mail_smtpauthtype": "LOGIN",
		"mail_smtpauth": 1,
		"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
		"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
		"mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
		"loglevel": 2,
		"app_install_overwrite": [
			"dropit",
			"occweb",
			"files_external_gdrive",
			"files_external_onedrive",
			"drawio",
			"apporder",
			"files_mindmap",
			"extract",
			"ransomware_protection"
		],
		"mail_smtpsecure": "tls",
		"mail_smtpport": "587",
		"theme": ""
	}
}
```
</details>

### Server log (data/nextcloud.log)
<details>
no log outputed when made the call

</details>

**Comment by SystemKeeper** [comment]
Hey, I think `modifiedSince` is not available on Talk 15 and was only introduced in Talk 16: https://github.com/nextcloud/spreed/pull/8726
