### ISSUE TITLE
Signaling messages wrong when conversation is switched

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9615]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps
1. Join `Room1`
2. Start typing
3. Switch to `Room2` before the typing indicator timed out

### Expected behaviour
* There should be a `stoppedTyping` message send to `Room1` before the room is left. 
* No message is send to `Room2`.

### Actual behaviour
* No message is send to `Room1`
* There is a `startedTyping`(!) message send to `Room2`

Could be related to #9604 

## Talk app

**Talk app version:** Sermo -> I don't think #9603 fixes these cases

**Comment by nickvergessen** [comment]
#9604 is about received typing messages from others. So this here might be different (although still partly related)
