### ISSUE TITLE
Discussion: ActivityPub, OStatus Integration & Fediverse Support

### ISSUE THREAD

**Issue by sunjam** [nextcloud/spreed#965]
Allow Nextcloud Talk users to federate via [ActivityPub](https://activitypub.rocks/) and [OStatus](https://en.wikipedia.org/wiki/OStatus) with [federated chat services](https://github.com/thefederationinfo/the-federation.info/issues/138)

- Diaspora
- Mastodon & GNU Social
- Hubzilla
- Friendica
- Pleroma
- Socialhome

**Comment by nickvergessen** [comment]
Integration with several services is handled in multiple issues:
https://github.com/nextcloud/spreed/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+integration%22

Im closing this one, because collection issues tend to grow infinite without ever being able to solve them.
