### ISSUE TITLE
Error "Getting the account information failed: account not found" when HPB trial expired

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/spreed#9656]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The logfile is generating these entries from Nextcloud-App **Spreed**:

`{"reqId":"xrWYwfDNdMZX0GBjIupY","level":3,"time":"2023-05-28T15:30:06+00:00","remoteAddr":"","user":"--","app":"spreed","method":"","url":"--","message":"**Getting the account information failed: account not found - HTTP status: 404** Response body: ","userAgent":"--","version":"26.0.2.1","data":{"app":"spreed"},"id":"6473762837795"}`

### Steps to reproduce

1. No speacial activity
2. Check NC Logfiles
3. Showing errors by App Spreed

### Expected behavior

No log errors

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.3.3. Please update your

This seems strange as my PHP is 8 and Nextcloud shows the correct configuration.
```

### List of activated Apps

```shell
This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.3.3. Please update your

This seems strange as my PHP is 8 and Nextcloud shows the correct configuration.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"xrWYwfDNdMZX0GBjIupY","level":3,"time":"2023-05-28T15:30:06+00:00","remoteAddr":"","user":"--","app":"spreed","method":"","url":"--","message":"Getting the account information failed: account not found - HTTP status: 404 Response body: ","userAgent":"--","version":"26.0.2.1","data":{"app":"spreed"}}
```

**Comment by nickvergessen** [comment]
> > This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.3.3. Please update your
>
> This seems strange as my PHP is 8 and Nextcloud shows the correct configuration.

My guess would be that you didn't switch which PHP is used for CLI.

Regarding the error. It just means that your trial for the HPB are not found:
https://github.com/nextcloud/spreed/blob/master/lib/Service/HostedSignalingServerService.php#L324

Maybe they expired? Try to remove them in the admin settings.

**Comment by MarcS1975** [comment]
> My guess would be that you didn't switch which PHP is used for CLI.

How can I switch PHP on CLI? I know PHP8 is installed and it is correctly used by Apache/NC, just not on CLI.

**Comment by MarcS1975** [comment]
> Regarding the error. It just means that your trial for the HPB are not found: https://github.com/nextcloud/spreed/blob/master/lib/Service/HostedSignalingServerService.php#L324
> 
> Maybe they expired? Try to remove them in the admin settings.

Yes, thank you. You are right, I had a HPB trial and it has expired, but when I hit "Delete the Singnaling Server Account", I get an error in NC. "There is no such account registered."
Is there a config file that I can amend?

**Comment by nickvergessen** [comment]
> How can I switch PHP on CLI?

https://askubuntu.com/questions/1373755/how-to-change-php-version-in-ubuntu-20-04-console

> Is there a config file that I can amend?

After you fixed your command line to use the correct PHP version, you should be able to run:

```sh
occ config:app:delete spreed hosted-signaling-server-account
occ config:app:delete spreed hosted-signaling-server-account-id
occ config:app:delete spreed signaling_mode
occ config:app:delete spreed signaling_servers
```

See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html for help if needed.
