### ISSUE TITLE
Error with VideoCall App in Nextcloud 13

### ISSUE THREAD

**Issue by ovguiti** [nextcloud/spreed#966]
Hello,

I have Nextcloud 13 installed. after update I can not activate the VideoCall - Plugin, here is the error message:

An exception occurred while executing 'INSERT INTO "oc_talk_rooms" ("name", "token", "type", "password") VALUES(?, ?, ?, ?)' with params ["", "a7d5", 2, ""]: SQLSTATE[23000]: Integrity constraint violation: 19 column token is not unique

what is the problem?

bye and thanks

**Comment by enoch85** [comment]
@ovguiti Do you run PostgreSQL?

**Comment by ovguiti** [comment]
No, SQLite3

**Comment by enoch85** [comment]
@ovguiti Please fill in the complete issue template, then it would be easier to debug.

**Comment by ovguiti** [comment]
Hello,

the error occurs when activating the "Talk" Apps. A small pink box appears that contains:

An exception occurred while executing 'INSERT INTO "oc_talk_rooms" ("name", "token", "type", "password") VALUES(?, ?, ?, ?)' with params ["", "a7d5", 2, ""]: SQLSTATE[23000]: Integrity constraint violation: 19 column token is not unique

Otherwise there is nothing.

**Comment by nickvergessen** [comment]
It is not recommended to run Talk on SQLite.
SQLite should only be used for testing and 1-2 User instances in general.

Talk itself requires too much DB interaction.
