### ISSUE TITLE
No "end call" when seeing preview

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#9661]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. open an image
2. try to end cal 
3. no button

### Expected behaviour
Button should be there

### Actual behaviour
No button

![image](https://github.com/nextcloud/spreed/assets/5836855/0c27dab5-32dc-4e10-80bd-0a4daf80c3bf)

## Talk app

**Talk app version:** NC27.

**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.0/8.1/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment]
Not sure what to do apart from overcrowding the small overlay with all the buttons.
To end the call you need to exit the viewer for now.

cc @jancborchardt @marcoambrosini  for design ideas

**Comment by tobiasKaminsky** [comment]
Also not sure, and yes, every user should be able to close viewer and then end call…
I would also be fine with not "fixing" it, but just wanted to raise attraction.

**Comment by jancborchardt** [comment]
Yeah, to be honest I think it is fine if the call is not end-able from the viewer. You can mute, you can hide your video, and if the call ends on the other side it ends.
