### ISSUE TITLE
Filter conversation list for unread / mentioned conversations only

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9668]
Especially after vacations and sick leave there are quite often a lot of unread and mentioned conversations.

* The idea is to have filter options available for the conversation list, e.g.
    - `is:unread` - Shows only conversations with unread chat messages
    - `is:mentioned` - Shows only conversations with unread mentions

A possible design draft could look like this:
![grafik](https://github.com/nextcloud/spreed/assets/213943/3fe289cb-ea61-4acd-9200-6c3cd2fd8f9f)

But there should also be a visual button that can be clicked to filter the list or it is a direct suggestion when clicking into the search field

---

- [x] Frontend https://github.com/nextcloud/spreed/issues/9677
- [x] iOS https://github.com/nextcloud/talk-ios/issues/1264
- [x] Android https://github.com/nextcloud/talk-android/issues/3072

**Comment by nickvergessen** [comment]
@jancborchardt I guess this should also be available on the mobile apps?

**Comment by AndyScherzinger** [comment]
For mobile apps I suggest to have a filter menue item on the search bar, just like the Deck Android app for example which also sports an indicator if filtering is active.

I can also post a screenshot when I am back at a keyboard.

**Comment by mahibi** [comment]
![grafik](https://github.com/nextcloud/spreed/assets/2932790/4f4d36ec-14f4-47f0-bdfe-60fe43ab09d0)

![grafik](https://github.com/nextcloud/spreed/assets/2932790/c15c60fd-1f66-4555-9756-ce358b1bab47)

**Comment by nickvergessen** [comment]
All done
