### ISSUE TITLE
Frontend - Make list of open conversations discoverable and usable

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9675]
* Overview issue: https://github.com/nextcloud/spreed/issues/6431
* Design idea at https://github.com/nextcloud/spreed/issues/6431#issuecomment-1573232581
    * If that does not work for your client, please reach out to the design team soon, so they can schedule it
* API endpoint at https://nextcloud-talk.readthedocs.io/en/latest/conversation/#get-open-conversations

**Comment by DorraJaouad** [comment]
**Brief overview of the prospective PR**  

* The modal used is RoomSelector with adding a prop to alter its API endpoint. It will have a default which is "/room" ( the current one).
* The access flow: + NcActions button in the left sidebar > [[ list-icon ](https://fonts.google.com/icons?selected=Material+Icons:format_list_bulleted:&icon.query=list)] List open Conversation button.

There are two ways to render the list:
* The modal will render a clickable list of conversations, each leading to an open conversation view when clicked. [ as in [Android ](https://github.com/nextcloud/talk-android/pull/3102)]

**OR** 
* The modal will render a checkable list where the user can check more than one conversation using checkboxes and join them all at once with the `join` button at the bottom.


@marcoambrosini can you please give your feedback on the above?
