### ISSUE TITLE
"connectivityError received" in Chrome

### ISSUE THREAD

**Issue by ochorocho** [nextcloud/spreed#968]
## Steps to reproduce
1. Install Spreed/Talk App
2. Install TURN Server as described here (but use default ports, coz 80 and 443 are already taken): https://blog.netways.de/2017/08/16/setting-up-a-turn-server-for-nextcloud-video-calls/
3. Configure Talk Apps STUN and TURN with yours (in my case its same Domain)

### Expected behaviour
Chrome should also be able to establish a connection like Firefox does.

### Actual behaviour
Black/No Video and no voice

## Browser
Version 67.0.3396.87 (Offizieller Build) (64-Bit) 

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS 10.12.6

**Browser name:** Chrome

**Browser version:** 67.0.3396.87

### Browser log

![nextcloud](https://user-images.githubusercontent.com/4623070/41521007-bca97132-72d0-11e8-88fc-729a48e1c61b.png)

## Spreed app

**Spreed app version:** 3.2.2

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.27

**Nextcloud Version:** 13.0.2

**List of activated apps:**

<details>

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/my.domain.com\/",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}
</details>

**Turnserver Log**
```
.... tons of "401: Unauthorized" Messages cut off ... 
Jun 18 07:11:20 z7-web13 turnserver: 428264: session 001000000000000069: realm <> user <>: 
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 000000000000000057: realm <> user <>: incoming packet message processed, error 401: Unauthorized
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 000000000000000057: TCP socket closed remotely 5.158.158.170:11750
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 001000000000000069: TCP socket closed remotely 5.158.158.170:55036
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 003000000000000057: TCP socket closed remotely 5.158.158.170:42419
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 003000000000000057: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:42419, reason: TCP connection closed by client (callback)
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 001000000000000069: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:55036, reason: TCP connection closed by client (callback)
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 000000000000000057: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:11750, reason: TCP connection closed by client (callback)
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 001000000000000070: TCP socket closed remotely 5.158.158.170:4835
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 001000000000000070: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:4835, reason: TCP connection closed by client (callback)
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 006000000000000068: TCP socket closed remotely 5.158.158.170:35909
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 008000000000000066: TCP socket closed remotely 5.158.158.170:3075
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 006000000000000068: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:35909, reason: TCP connection closed by client (callback)
Jun 18 07:11:48 z7-web13 turnserver: 428293: session 008000000000000066: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 5.158.158.170:3075, reason: TCP connection closed by client (callback)
Jun 18 07:12:06 z7-web13 turnserver: 428311: session 005000000000000054: closed (2nd stage), user <> realm <> origin <>, local 172.16.211.33:3478, remote 82.113.121.107:27099, reason: allocation watchdog determined stale session state
```

**Comment by nickvergessen** [comment]
No idea, @Ivansss any clue?

**Comment by ochorocho** [comment]
@nickvergessen just Talked to the the Admin again. Server uses a proxy and incoming/outgoing firewall. Dunno if that helps but this is the only difference to my private server which we tested all features prior to installing Nextcloud at work.

Thanks :-)

**Comment by ochorocho** [comment]
yep, coturn ist installed on the same server. Anything i can test or try? ...
My bet is on the proxy cutting things off which firefox doesn't care but Chrome does care.

**Comment by nickvergessen** [comment]
In this case you should fix your proxy? :)
