### ISSUE TITLE
does not work in Firefox anymore

### ISSUE THREAD

**Issue by albialbi** [nextcloud/spreed#969]
## Steps to reproduce
1. start with firefox on linux
2. asking for mic and video will not happen

### Expected behaviour
Does not work on firefox on linux anymore. Last version which worked was 3.1.0. All newer versions do not ask for access to mic and cam.

**Comment by brtptrs** [comment]
We have Talk 3.2.2 running an NC 13.04 and using Firefox on Ubuntu seems to work fine.

**Comment by nickvergessen** [comment]
The "Ask for access to mic and cam" was moved to the moment you join the actual call. So you can chat without accessing the camera.

Can you check that again? And otherwise please check your browsers JS console for any potential errors.
