### ISSUE TITLE
No notification on Talk for conversation room

### ISSUE THREAD

**Issue by df911** [nextcloud/spreed#9708]
## Steps to reproduce
1. I created a new conversation room
2. When I send a new message, I don't have notification on Chrome browser or Android Talk (installed from Play Store)
3. If a contact sends me a message, I get a notification.

### Expected behaviour
When I send a new message, i would like to receive a notification

### Actual behaviour
When I send a new message, I don't have notification on Chrome browser or Android Talk (installed from Play Store)

## Talk app

Talk version 16.0.4
Nextcloud Docker 26.0.2
Chrome browser version  114.0.5735.91 x64
Android talk 16.0.1

**Comment by SystemKeeper** [comment]
I am sorry, I don’t understand your problem. Expected and actual behaviour are identical?!
To debug notifications on android take a look at https://github.com/nextcloud/talk-android/blob/master/docs/notifications.md

**Comment by df911** [comment]
Hello,
I change the expected behaviour.
I already follow the instructions of this link but no success :(

**Comment by df911** [comment]
Yes. thanks for the confirmation !
