### ISSUE TITLE
Typing indicator is too close to the message input

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#9719]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

The typing indicator is too close to the message input.

![image](https://github.com/nextcloud/spreed/assets/25978914/97d2e760-dea9-4cce-81e5-99a6e0df1138)

![image](https://github.com/nextcloud/spreed/assets/25978914/ed5f2d20-b44c-4e55-832e-1760b2a38c52)

What about positioning it in the middle of the `.wrapper`'s padding?

![image](https://github.com/nextcloud/spreed/assets/25978914/7ce8127d-a075-4c88-a5be-d1f29cd3c49a)

**Comment by AniketSaraswat112** [comment]
HI @ShGKme I would like to work on this issue please assign this to me.

**Comment by Antreesy** [comment]
Case "More than 3 persons are typing in the call" should be considered when working on that issue, because in the sidebar chat indicator wraps into two lines of text
Original issue: https://github.com/nextcloud/spreed/issues/9589
Fix to that issue: 18324284787803a431b9a65432b96289143f20ea
