### ISSUE TITLE
Unterhaltung lässt sich bei einem User nicht starten bzw. löschen

### ISSUE THREAD

**Issue by nice1984** [nextcloud/spreed#972]
Hallo,
hier mein Problem:
Wenn ich versuche mit den einem betsimmten User eine Unterhaltung zu starten funktioniert das nicht, ich kann die Unterhaltung weder entfernen noch löschen.

Was mir aufgefallen ist, dass in der Adresszeile keine ID angezeigt wird
Anzeige: "adresse"/nextcloud/apps/spreed

Bei allen anderen steht: "adresse"/nextcloud/call/gbqo3f8j <- ID ändert sich je nach User

Ich hoffe, dass mir jemdand weiter helfen kann, wenn gewünscht, kann ich es auch in Englisch übersetzen

Danke und Gruß

Daniel

**Comment by nice1984** [comment]
Hello now i try in english,
my problem here:
When I try to start a conversation with a particular user, that does not work, I can not remove or delete the conversation.

What struck me is that in the address line no ID is displayed
Display: "address"/nextcloud/apps/spreed

For all others is: "address"/nextcloud/call/gbqo3f8j <- ID changes depending on the user

I use Nexcloud13.0.4 and Talk 3.2.2

It´s the same if I user Firefox, Edge or Chrome also the Nextcloud Talk App.

If I press F12 the following Error Message appears:

"Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://adress/nextcloud/core/vendor/core.js?v=05ce0c40-118
Source-Map-Adresse: purify.min.js.map[Weitere Informationen]"

I hope that somebody can help me.

Thanks and regards

**Comment by nice1984** [comment]
Hello now i try in english,
my problem here:
When I try to start a conversation with a particular user, that does not work, I can not remove or delete the conversation.

What struck me is that in the address line no ID is displayed
Display: "address"/nextcloud/apps/spreed

For all others is: "address"/nextcloud/call/gbqo3f8j <- ID changes depending on the user

I use Nexcloud13.0.4 and Talk 3.2.2

It´s the same if I user Firefox, Edge or Chrome also the Nextcloud Talk App.

If I press F12 the following Error Message appears:

"Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://adress/nextcloud/core/vendor/core.js?v=05ce0c40-118
Source-Map-Adresse: purify.min.js.map[Weitere Informationen]"

I hope that somebody can help me.

Thanks and regards

**Comment by nickvergessen** [comment]
That is the actual problem.

You might need to share your server + a test user, or need to debug it yourself. core.js however refers to a problem in Nextcloud itself and not in the Talk app.

**Comment by nice1984** [comment]
Hello,
here is the adress: https://cloud.niceservice.de
there you can registred you.
Thank you
Daniel

**Comment by nice1984** [comment]
Hello,
here is the adress: https://cloud.niceservice.de
there you can registred you.
Thank you
Daniel

**Comment by nickvergessen** [comment]
I just tested it on your instance and worked quite fine for me.
It jhust took about 30 secs to establish the connection, but afterwards no problem.

**Comment by nice1984** [comment]
Hello, it works for all users but for one not, if you try to talk with marhens it does not work. Meanwhile ich setup a new Linux Server with Ubuntu Server 1804 and import all data. So it works as before. 
Thank you
Daniel
