### ISSUE TITLE
The loading animation should not be as dark. Please use a brighter color for it.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#9720]
As discussed with @jancborchardt and @nimishavijay, the loading animation should not be as dark. Please use a brighter color for it.

See the following screenshot:
![image](https://github.com/nextcloud/spreed/assets/42591237/254b6efb-c493-4760-add3-da0121addaa1)

**Comment by ShGKme** [comment]
I'm taking the issue as I already started to work on this problem in the Talk Desktop client
