### ISSUE TITLE
Error with displaying the screen demonstration button

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/spreed#9725]
You need to start and stop the screen demonstration many times and it will disappear
![image](https://github.com/nextcloud/spreed/assets/65107731/92e53333-c1f3-4475-b2ff-fdca4617f341)

NC: 26.0.2
Talk: 16.0.4

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/spreed/assets/1580193/356e8887-88cb-48c4-9893-2318ab307da9

I was able to reproduce this. Steps:
* Share a another tab in chrome
* Go back to Talk
* Open the popover menu of the screen sharing button
* Disable screen sharing in the chrome bar

**Comment by Kitanit** [comment]
@SystemKeeper Hi, am I correct in assuming that the patch for this bug will not come out until NC 28?

![image](https://github.com/nextcloud/spreed/assets/65107731/ee0c5986-6fa1-4540-b4e3-ad43b9ed4b75)

**Comment by SystemKeeper** [comment]
We are close to the release of 27 and I would not consider it a showstopper bug, so I tagged it for 28. This is constantly reevaluated, so it could be fixed in 28 and backported to earlier versions or it could get postponed to a later version than 28.

**Comment by Antreesy** [comment]
Was noticed on 28, needs another testing round
