### ISSUE TITLE
Webp image file support

### ISSUE THREAD

**Issue by Folaht** [nextcloud/spreed#9757]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

Yes, because there's no webp support, I can't upload webp images in chat,  
a common image filetype on the web.  

They show up as 'empty image file' images.

**Describe the solution you'd like**

When I upload a webp image into chat, that image shows up.  

**Describe alternatives you've considered**

Turning webp images into png files, which is cumbersome.

**Comment by Folaht** [comment]
Never mind. This seemed to be an issue on my part, at least partially.  
Downloading `webp-pixbuf-loader` did it for me.  

I am running Manjaro OS and used a nativefier.  
But the person at the other end complained about not seeing the picture as well  
and she is running an iOS. I just sent a webp picture to her.
If she can see it, then I'll close off this issue.

**Comment by ShGKme** [comment]
@Folaht Do you still this issue or we should close the issue? :)

**Comment by Folaht** [comment]
I have this issue again.

**Comment by ShGKme** [comment]
> I still have this issue or I have it again. It only worked for a short while. `webp-pixbuf-loader` is installed. It neither works for nativefier or firefox browser.

Please provide more details about your issue:
- Nextcloud and Nextcloud Talk versions or system report
- How the issue does look like, how it looks in the chat
- Browser log
- Does webm work in files?

**Comment by Folaht** [comment]
Nextcloud version: 27.1.4~ynh1
Talk version:  17.1.3

This is what it looks like in the chat.
![image](https://github.com/nextcloud/spreed/assets/9342090/4629ed70-bc67-4ced-b91a-d3b1a2bce673)

> Does webp work in files?
Yes

I'm now noticing that files dragged into talk end up 0k in size.

**Comment by Folaht** [comment]
Alright, I've figured out this seems to be a specific nativefier issue.  
It happens when I copy an image file from my browser to my nativefier app.

**Comment by ShGKme** [comment]
> Alright, I've figured out this seems to be a specific nativefier issue, not a spreed issue. And nativefier is no longer maintained. I'll jump to gluon instead.

You can try Talk Desktop

**Comment by Folaht** [comment]
Issue moved to https://github.com/nextcloud/talk-desktop/issues/449
