### ISSUE TITLE
Image support for images without filename extensions

### ISSUE THREAD

**Issue by Folaht** [nextcloud/spreed#9758]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**

When I upload an image without a filename extension, it is not recognized as such.  
Some images on the internet don't have them for whatever reason  
and when I try to show it to someone by pasting it into chat, it doesn't show up.  

**Describe the solution you'd like**

Show up when uploading such images.  
Have them recognized by mime/type.  

**Describe alternatives you've considered**
None.

**Comment by nickvergessen** [comment]
> Have them recognized by mime/type.

We will not do that unless the server says so:
https://www.coalfire.com/the-coalfire-blog/mime-sniffing-in-browsers-and-the-security
