### ISSUE TITLE
If the room does not have an active call yet, button should say "Start call"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#976]
Currently the button says "Join call" in any case, which makes it seem like there’s always a call going on.

It would be better to label it "Start call", and only label it "Join call" when others already are in an active call.

**Comment by nickvergessen** [comment]
The necessary information should already be available in the UI with `hasCall`.

**Comment by jancborchardt** [comment]
Cool, sounds good. Will look into it once https://github.com/nextcloud/spreed/pull/974 is merged cause otherwise there will just be conflicts again :D
