### ISSUE TITLE
[RFC] Grid navigation buttons are not aligned in-line relative to grid/video/page border

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#9767]
Currently grid navigation buttons are not aligned in-line relative to grid/video/page border. Introduced in https://github.com/nextcloud/spreed/pull/6649

![image](https://github.com/nextcloud/spreed/assets/25978914/9037129a-d9da-4ec9-a0e4-42ae4665fccc)

We are discussing 8px (same as other paddings on this page) and 0px (in-line with video) with @Antreesy.

What do you think?
cc @marcoambrosini 
cc @SystemKeeper
cc @mahibi 

8px | 0px 
---|---
![image](https://github.com/nextcloud/spreed/assets/25978914/6a7eac58-931a-4033-957f-c84ea18aa774) | ![image](https://github.com/nextcloud/spreed/assets/25978914/d1860678-946e-4cab-940a-159ff6bcb55e)
![image](https://github.com/nextcloud/spreed/assets/25978914/8f6ae587-1ff3-4d47-97e1-9a494384db79) | ![image](https://github.com/nextcloud/spreed/assets/25978914/7f22c45c-5ca8-4f03-864a-1746c6e91ec2)

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/spreed/pull/9727#issuecomment-1587187630

"I would go with the 8px personally."

**Comment by ShGKme** [comment]
Current position with `-4px` was introduced here: https://github.com/nextcloud/spreed/pull/6649

**Comment by marcoambrosini** [comment]
8px looks good yes!
