### ISSUE TITLE
Sync LDAP group members with conversation participants

### ISSUE THREAD

**Issue by forlornidealist** [nextcloud/spreed#9791]
**Is your feature request related to a problem? Please describe.**
This is related to #4810, which added the capability to synchronize a group conversation's participant as the group's membership changes. This works great for local Nextcloud groups, but we're using an LDAP backend. I see no mention of LDAP or other external identity backends in that issue, so I'm guessing this is not a bug and was never meant to be implemented for LDAP.

**Describe the solution you'd like**
The ability for a conversation started with a group to dynamically change the participants when that group's membership changes, as in the mentioned issue, but for LDAP groups.

**Describe alternatives you've considered**
In the meantime, we will likely just use the API to create and synchronize local groups with relevant LDAP groups, but it would be nice to have it built-in if possible.

**Comment by nickvergessen** [comment]
Talk is using the official events to listen to membership changes:
https://github.com/nextcloud/spreed/blob/63bd1f467359492d99261df75bfed08774cc764b/lib/Listener/GroupMembershipListener.php#L41-L46

If they are not triggered correctly by the LDAP app, that is nothing we can help with or work around.

But it looks like the code actually is there:
https://github.com/nextcloud/server/blob/0186194ae969dfebe260733a587e83984a11230f/apps/user_ldap/lib/Jobs/UpdateGroups.php#L188-L190

Maybe there is a related error in your nextcloud.log?

**Comment by elephantastyczny** [comment]
I can confirm, that it's already working as described.
