### ISSUE TITLE
Documentation: Provide a second TURN server example (eturnal)

### ISSUE THREAD

**Issue by sando38** [nextcloud/spreed#9816]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently coturn is the only TURN server example. In matrix/synapse we added [eturnal](https://matrix-org.github.io/synapse/latest/setup/turn/eturnal.html) as an alternative which received good feedback as well. It provides multiple packages, including Docker images and is easy to configure.

**Describe the solution you'd like**
Would you be interested in a PR providing instructions to setup eturnal as a second TURN server implementation example for Nextcloud Talk?

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by nickvergessen** [comment]
I guess you can extend https://github.com/nextcloud/spreed/blob/master/docs/TURN.md then with a second block
