### ISSUE TITLE
Chat access for guests via API

### ISSUE THREAD

**Issue by absurd-turtle** [nextcloud/spreed#9857]
Is there a possibility to interact with the Chat API without authentication?
I noticed that requests without authentication get declined by the API but there is a possibility to chat without logging in for public chats.
When a request is sent there it includes a requesttoken header. Where does this token come from, what is it for and how can I generate one to communicate with the API?

**Comment by nickvergessen** [comment]
You just need to join the room and reuse the cookies.
That is exactly how guests interact with the API when they use their browser
