### ISSUE TITLE
Password field gets autofilled

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#986]
## Steps to reproduce
1. Start a call
2. Open the sidebar
3. Share the link and click to set password

### Expected behaviour
The popover is shown, and because there’s no password yet the input field is empty.

### Actual behaviour
The password input is prefilled with the password of my user account of this instance.

**Comment by nickvergessen** [comment]
Yeah, nothing we can do about it. We have all tricks and tipps in place, but Firefox and Chrome are actively working against this.
