### ISSUE TITLE
Threads 2.0

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9869]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Threads 1.0 is coming with https://github.com/nextcloud/spreed/issues/1469 but it's only a "filter to a list of chained replies"

To more utilize the feature here are some thoughts for Threads 2.0 but they are a lot more work for the API and clients:

- Threads should be nameable
- Threads should be searchable (in the unified search)
- Threads should be listable:
    - Options:
        - A threads list should be available in the right sidebar?
        - Users can pick between "ChatView" is a list of "threads" or list of "messages"

**Comment by marcoambrosini** [comment]
Should we close this and go for 2.0 right away?
