### ISSUE TITLE
Scrollbar in text input visible outside of boundary

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/spreed#9894]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. open any talk conversation
2. enter a large amount of text
    - scrollbar will show on right hand side

### Expected behaviour
Scrollbar should be displayed within boundaries of text input.

### Actual behaviour
Parts of the scrollbar are displayed outside the boundaries of the text input box.

![talk-scrollbar](https://github.com/nextcloud/spreed/assets/70907959/33479605-f8e1-47f6-b5e9-a220e929b47f)

## Browser

**Operating system:** Arch Linux

**Browser name:** Firefox (Flatpak from Flathub)

**Browser version:** 114.0.2

**Comment by nickvergessen** [comment]
Talk issue or vue lib?

**Comment by DorraJaouad** [comment]
> Talk issue or vue lib?

vue lib but styles have already changed.
![image](https://github.com/nextcloud/spreed/assets/84044328/d0012db5-3562-4758-b885-06b7b4c41e51)
