### ISSUE TITLE
403 Forbidden` response: Authentication check failed using signaling server

### ISSUE THREAD

**Issue by cidk2000** [nextcloud/spreed#9899]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open Talk 
2. select conversation 
3. chat box is also disabled 

### Expected behaviour
use as normal 

### Actual behaviour
cannot use talk when signalling server settins in ui are 

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`) 17.01

**Custom Signaling server configured:** yes Running version: 5cba69686b8804b67f591b9d7d813e077e5edf35

**Custom TURN server configured:** yes coturn on same server as signalling 
**Custom STUN server configured:** no - using stun.nextcloud.com

## Browser Firefox

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Nexcloud on Hyper-v Ubuntu 22.04

**Browser name:** Firefox

**Browser version:** 114

### Browser log

<details>
```
Insert your browser log here, this could for example include:
[wdh log](https://github.com/nextcloud/spreed/files/11952304/wdh.log)

a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/

**Web server:** Nginx > nginx reverse proxy on another server 

**Database:** /Maria/

**PHP version:**/8.2

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
Enabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - cloud_federation_api: 1.10.0
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - music: 1.8.4
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.0
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - registration: 2.2.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - smb_test: 0.3.7
  - spreed: 17.0.1
  - support: 1.10.0
  - survey_client: 1.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - activity: 2.19.0 (installed 2.15.0)
  - approval: 1.0.12 (installed 1.0.12)
  - circles: 27.0.0 (installed 23.0.0)
  - comments: 1.17.0 (installed 1.13.0)
  - contacts: 5.3.2 (installed 5.3.2)
  - dashboard: 7.7.0 (installed 7.3.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.13.0)
  - mail: 3.2.3 (installed 3.2.3)
  - sharebymail: 1.17.0 (installed 1.16.0)
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0 (installed 1.13.0)
  - twofactor_totp: 9.0.0
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.103",
            "cloud.wh-computers.co.uk",
            "localhost",
            "192.168.1.101",
            "mail.wh-computers.co.uk",
            "wh-computers.co.uk",
            "92.27.138.96"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "X-Forwarded-For",
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.0.8",
        "overwrite.cli.url": "https:\/\/cloud.wh-computers.co.uk",
        "overwritehost": "cloud.wh-computers.co.uk",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "GB",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/London",
        "log_rotate_size": "10485760",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "preview_max_memory": "512",
        "app.mail.transport": "php-mail",
        "allow_local_remote_servers": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ],
        "preview_imaginary_url": "http:\/\/192.168.1.102:9000",
        "theme": "",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtptimeout": 30,
        "mail_smtpsecure": "ssl",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        }
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
log file too large too many garbage entries (poor log rotate) ive posted an entry from web log this is repeated throught the log!
[spreed] Error: GuzzleHttp\Exception\ClientException: Client error: `POST https://rtc.wh-computers.co.uk/standalone-signaling/api/v1/room/77j45iw7` resulted in a `403 Forbidden` response:
Authentication check failed

 at <<closure>>

 0. /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 69
    GuzzleHttp\Exception\RequestException::create("*** sensitive parameters replaced ***")
 1. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 204
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 153
    GuzzleHttp\Promise\Promise::callHandler()
 3. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 48
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 248
    GuzzleHttp\Promise\TaskQueue->run()
 5. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 224
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 269
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 226
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Promise\Promise->wait()
10. /var/www/html/nextcloud/lib/private/Http/Client/Client.php line 297
    GuzzleHttp\Client->request()
11. /var/www/html/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php line 85
    OC\Http\Client\Client->post()
12. /var/www/html/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php line 146
    OCA\Talk\Signaling\BackendNotifier->doRequest()
13. /var/www/html/nextcloud/apps/spreed/lib/Signaling/BackendNotifier.php line 473
    OCA\Talk\Signaling\BackendNotifier->backendRequest()
14. /var/www/html/nextcloud/apps/spreed/lib/Signaling/Listener.php line 450
    OCA\Talk\Signaling\BackendNotifier->sendRoomMessage()
15. /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OCA\Talk\Signaling\Listener::notifyUsersViaExternalSignalingToRefreshTheChat()
16. /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
17. /var/www/html/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 87
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
18. /var/www/html/nextcloud/apps/spreed/lib/Chat/ChatManager.php line 323
    OC\EventDispatcher\EventDispatcher->dispatch()
19. /var/www/html/nextcloud/apps/spreed/lib/Controller/ChatController.php line 244
    OCA\Talk\Chat\ChatManager->sendMessage()
20. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Talk\Controller\ChatController->sendMessage()
21. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController()
22. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch()
23. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main()
24. /var/www/html/nextcloud/ocs/v1.php line 64
    OC\Route\Router->match()
25. /var/www/html/nextcloud/ocs/v2.php line 23
    require_once("/var/www/html/nextcloud/ocs/v1.php")

POST /ocs/v2.php/apps/spreed/api/v1/chat/77j45iw7
```
Insert your server log here
```
</details>

**Comment by fancycode** [comment]
Is this the same as https://github.com/strukturag/nextcloud-spreed-signaling/issues/508?

**Comment by cidk2000** [comment]
i still have issues with the app but not this one, ill post on the nextcloud community as calls are not bieng made after the signalling server is up ill close this as duplicate as - https://github.com/strukturag/nextcloud-spreed-signaling/issues/508
