### ISSUE TITLE
Show "Talking time" in participants list during a call

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9903]
TBD

**Comment by jancborchardt** [comment]
Quick mockup how it could look like in the sidebar, as @karlitschek said the "In a call" text can of course be replaced in the room of the current call.
"Talking time" would count up just like the call timer:
![image](https://github.com/nextcloud/spreed/assets/925062/c74f1452-566a-405a-993a-28c2b3097bfa)

**Comment by nickvergessen** [comment]
For the record, in case the user reset their status from in a call to a custom one, we would show that emoji/icon and this fake text

**Comment by nickvergessen** [comment]
- Data channel messages are used for the white speaking border
- Information is not available/accessible on the HPB nor the Nextcloud server
- Therefore time calculation takes place on the clients
- If possible the data should be stored in a way that it survives page reloads (e.g. in the browser storage), in case a user refreshes or has to leave and join a call due to permission changes, etc.
