### ISSUE TITLE
Nick for avatar is distributed through datachannel

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#991]
The nickname that is shown below the avatar is currently distributed through the datachannel by sending a `nickChanged` event to the `status` channel.

This is done once at call establishment and whenever the (guest) user changes the name.

We should change this to use the name from the participant list. This avoids having different places where the name of a user is stored / updated and allows removing the workaround for the MCU that periodically updates the name through the DataChannel (see #398).

@Ivansss adding this as issue so what we discussed doesn't get lost

**Comment by Ivansss** [comment]
Also display names for logged-in users should be retrieved from there.
So we no longer need `peer.nick` for users' display name.

**Comment by nickvergessen** [comment]
This should be a subset of #397 as we need to get rid of datachannels anyway
