### ISSUE TITLE
Basic emoji parsing

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#994]
Now that the Android app can nicely render emojis (and send them) it would be cool to have the web app do the same.

E.g. I'm not asking for a fancy picker or anything, just render them instead of a strange set of unicode char(s) :)

cc @danxuliu

**Comment by nickvergessen** [comment]
> ![bildschirmfoto von 2018-06-26 09-21-00](https://user-images.githubusercontent.com/213943/41895441-5a721b56-7922-11e8-92d9-4796cedc67a6.png)

Works fine here. The problem is you are missing an emoji font on your system.

**Comment by Ivansss** [comment]
I guess it depends on the browser as well.

**Comment by nickvergessen** [comment]
But yeah, I guess we can try something like github does and replace the emojis with images when there is no font available?

**Comment by danxuliu** [comment]
Yes, my idea was to add emoji support for Nextcloud 14, but I will not be able to finish it before the feature freeze of the server, so hopefully Nextcloud 15.

I will try to add something just for Talk in the meantime, though.

**Comment by mario** [comment]
Good discussion folks, thanks for this. And thanks for the system font hint @nickvergessen.

**Comment by mario** [comment]
After investigating, I can see emojis @Ivansss sends from iOS but I can't see ones sent from Android.

E.g. regular smiley is:

\uD83D\uDE00

Which renders properly on Android but not on the web.

**Comment by mario** [comment]
Fixed by sending charsequence instead of a string.
