### ISSUE TITLE
Markdown support - Frontend

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9949]
* Overview ticket: https://github.com/nextcloud/spreed/issues/1027
* API discussion: https://github.com/nextcloud/spreed/issues/9950

We plan to role out the following support for markdown:

# non-optional
- [ ] bold
- [ ] italic

# optional
Optional means it is just shown with the markdown syntax

- [ ] strike-through
- [ ] list
- [ ] todo list with checkboxes
- [ ] code block using 3 `
- [ ] inline code using `
- [ ] quote
- [ ] headlines
- [ ] dividers `---`

**Comment by SystemKeeper** [comment]
What would be the expected behaviour when copying a message? Would the clipboard now contain the „raw“ message, e.g. with markdown syntax or the „plain“ message, e.g. just the text ?

**Comment by nickvergessen** [comment]
I would expect copying the raw content, so that posting it results in the same message

**Comment by nickvergessen** [comment]
There is a `markdown` property on messages now. If that is false, all Markdown rendering should be disabled:
https://github.com/nextcloud/spreed/pull/10067
