### ISSUE TITLE
Active users should always be sorted first, even if not moderators

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#995]
Currently the sorting is:

- Moderators (online)
- Moderators (off)
- Regular users (online)
- Regular users (off)

Instead it should be:

- Moderators (online)
- Regular users (online)
- Moderators (off)
- Regular users (off)

(Just talked about with @Ivansss @schiessle )

**Comment by nickvergessen** [comment]
I disagree, the room you just created is not normal.
In normal cases and e.g. webinaries you have less then 10% moderators and in such cases the 4-5 moderators should be immediately visible (since you need to ask them to add people etc.).

**Comment by jancborchardt** [comment]
Good point actually – agreed.
