### ISSUE TITLE
Auto Correct option

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/spreed#9953]
It would be nice the there was an auto correct option under the nextcloud chat.

**Comment by SystemKeeper** [comment]
Maybe you could provide _slightly_ more information about what you‘d like to see? 😉

**Comment by AndyXheli** [comment]
Hey @SystemKeeper 😃  So for example if someone spells a word incorrectly while chatting maybe have an option under highlight the word or words meaning its smelled wrong and give an option of the correct smelling 

Here's how MS Teams dose it. 
![Screenshot 2023-07-11 152222](https://github.com/nextcloud/spreed/assets/59488153/2d501b46-a4b0-4a7b-8fc1-fd206dfa9e9c)

**Comment by AndyXheli** [comment]
After you comment i did test on Firefox and it dose show the corrections but chrome dose not ? any thoughts

**Comment by SystemKeeper** [comment]
Does it work at all in chrome? (Maybe disabled?)
Can you check https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable if it works there?
I would suspect it’s an „issue“ in the vue lib more then in Talk, if at all.

**Comment by AndyXheli** [comment]
So I did some research an this  has to be enabled in chrome sometimes it would be enabled by default 

![image](https://github.com/nextcloud/spreed/assets/59488153/5bf85fc6-2b4e-4e82-b892-82de09f43521)
