### ISSUE TITLE
Log and show who promoted whom to moderator

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#996]
For information/security purposes, we could show a message like "Ivan promoted Joas to moderator" or "Camila demoted Daniel from moderator" in the chat whenever that happens. 

What do you think @nextcloud/talk

**Comment by mario** [comment]
This is part of system messages. I'm sure there's an issue for this.

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/spreed/issues/614
