### ISSUE TITLE
Ability to favorite rooms (thus have them pinned to the top)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#998]
Just like in Files, when you favorite a folder or file, it’s sorted up top and easily accessible.

Similarly we should do it with Talk, where you can favorite conversations, and they will be sorted up top in the list. That way you can easily "pin" permanent groups like Company group or colleagues you work with often.

cc @nextcloud/talk Same for iOS and Android apps @mario @Ivansss :)

**Comment by mario** [comment]
This will be supported in the apps once the backend/server supports this.

**Comment by nickvergessen** [comment]
Didn't autoclose....

This is now implemented in the web UI

**Comment by jancborchardt** [comment]
An issue for some necessary follow-up fixes here: https://github.com/nextcloud/spreed/issues/1064 :)
